### ISSUE TITLE
As a rundeck user, i'd like to have the possibility to sort rundeck job executions option on user interface.

### ISSUE THREAD

**Issue by katanafleet** [rundeck/rundeck#1002]
In our rundeck jobs, we have some options that depend on over options. (options  which are generated with an option provider which take as url parameter a previous option)
It would be very useful to sort our job execution options on rundeck GUI, in order to choose option in an intuitive order for the job's user.   
![job_option_order](https://cloud.githubusercontent.com/assets/6132120/4896407/8872d71c-63f9-11e4-95ba-7002c101d37e.PNG)

As it's an enhancement, I've also post a request : https://groups.google.com/forum/#!topic/rundeck-discuss/G1_Fr_UKBKU

Thx

**Comment by wjimenez5271** [comment]
+ 1 for support for this in the GUI

**Comment by natefaerber** [comment]
+ 1 for support for this in the GUI

**Comment by wilprig** [comment]
+1 for support for this in the GUI

**Comment by urgerestraint** [comment]
+1 for support for this in the GUI

**Comment by hmalinov** [comment]
+1 for GUI

**Comment by tobiasmh** [comment]
+1 for GUI

**Comment by jsparknz** [comment]
+1 for GUI!

**Comment by dfsis** [comment]
+1 for GUI!

**Comment by ThomLambert** [comment]
+1 for GUI

**Comment by tgeric** [comment]
+1 for GUI

**Comment by AndrewFarley** [comment]
Almost 7 months later +1 for GUI.  Did manual export/import of the XML after reordering items worked, but would be much nicer if I could drag them around similar to how you can re-order workflow items.

**Comment by gschueler** [comment]
I added this feature on trello https://trello.com/c/wU2Aq3H1 please vote for it there

**Comment by ZackWhiteIT** [comment]
This

**Comment by katanafleet** [comment]
Thx a lot !
