### ISSUE TITLE
Temporary file of inline script gets deleted before running with invocation String

### ISSUE THREAD

**Issue by vroumvroum** [rundeck/rundeck#1005]
If running inline script with Invocation String like "sudo -u username", the temporary file gets deleted before it could be run.

sudo: unable to execute /tmp/1415208774656-node1-dispatch-script.tmp.sh: No such file or directory

**Comment by ahonor** [comment]
@vroumvroum Can you try this in 2.4.0?

**Comment by gschueler** [comment]
thanks, will close this
