### ISSUE TITLE
Option to store inline script on target node to a specific directory

### ISSUE THREAD

**Issue by vroumvroum** [rundeck/rundeck#1014]
It would be very useful to have an option to keep inline script on target node on a specific directory with a chosen name.

**Comment by meatsac** [comment]
> Here is a workaround
> 
> * Write your inline script inside Rundeck's editor without any Rundeck's Script Content (@option.option@)
> * Add Invocation String (cp) to copy your script to a custom directory
> * Run your script as "command" or "Script file or URL" as workflow step with your options and/or arguments
> 
> This way you can edit and run your script with rundeck editor an still be able to run it directly from server as a standalone script.

I can't believe I never thought of this. Genius!!!

**Comment by fdevans** [comment]
Thanks for the workaround!
