### ISSUE TITLE
use nodes from filtered tags

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#102]
A process that requires a mixture of both - steps to be dispatched to nodes and steps to be executed on the rundeck node.

I'd like to be able to have a step that executes another job and passes the node to the job id that is currently been executed.

This way there can be a mix of executing on the node, but also executing on the rundeck node using the former node as a value.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/419)

Original Creator: Matt

**Comment by ahonor** [comment]
Can be handled by Node step jobref
