### ISSUE TITLE
Jobs not adhering to simple repeating schedule

### ISSUE THREAD

**Issue by joesapo** [rundeck/rundeck#1023]
Rundeck 2.2.3

I have numerous jobs which are set to run on certain days of the week, for example: Tue - Sat.  I have these set up in the "Schedule to run repeatedly / Simple" tab of the job editor.  Despite checking the days of the week I would like the job to run, it is scheduled to run every day.  It does run at the correct time specified.

**Comment by ahonor** [comment]
@joesapo Can you try this on 2.4.0?
