### ISSUE TITLE
HTML formats in description

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#103]
Hi

I understand the removal of html format from tag `<description>` and the removal of `<additional>` from rundeck for improve speed. But since rundeck is to be used for different kind of users and not only sysadmins and IT people I think it's important to have some small help in the job it self that explain how it works.

The html formats in the description if big enough would allow that, and will work as a kind of small pretty documentation of the job.

An example of that will be something like that (language is portuguese):

@@@
 <additional><![CDATA[Este comando realiza duas tarefas em
sequ√™ncia. Em primeiro lugar obt√©m a actualiza√ß√£o do servidor da GEDI
e em segundo lugar executa a actualiza√ß√£o do SIAG<font
color="#0000ff"><br/><br/>√â obrigat√≥rio indicar o n¬∫ da actualiza√ß√£o
no formato apropriado (e.g. "2.0.0-20101231.01").</font>.<br/><br/

> <b><u>Aten√ß√£o: Este comando n√£o realiza os backups das bases de
> dados.</b></u>]]></additional>
> @@@
> Thanks,

Miguel Lamy

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/422)

Original Creator: Miguel Lamy

**Comment by ahonor** [comment]
Use the Run book feature that supports mark deep.
