### ISSUE TITLE
Enhancement Request: Ability to use job's options in webhooks

### ISSUE THREAD

**Issue by kayvonr** [rundeck/rundeck#1042]
Currently, including a job's execution options in webhook calls is not supported. For example:

Job defined with the following options:
![screen shot 2014-12-04 at 7 11 49 pm](https://cloud.githubusercontent.com/assets/2281150/5308819/927bc446-7be9-11e4-9920-15e5187f9747.png)

So with the following webhook set up:
![screen shot 2014-12-04 at 7 12 30 pm](https://cloud.githubusercontent.com/assets/2281150/5308818/927a9062-7be9-11e4-8fec-a982d3393e71.png)

The ${option.XXX} params do not get expaned, and the final url is "/job?rundeck_job_id=my_job_UUID&rundeck_execution_id=50706&time=${option.year}-${option.month}-${option.day}%20${option.hour}:00:00"

Would be helpful to be able to include all job options in the webhook calls

**Comment by fdevans** [comment]
Due to the age of this request and recent feature releases we are going to close this request.  If there are still gaps in the feature set please feel free to open an enhancement request against the current version of Rundeck with your ideas.
Thank you, 
Rundeck Team
