### ISSUE TITLE
Killing Jobs does not Work

### ISSUE THREAD

**Issue by qoomon** [rundeck/rundeck#1045]
I write a test job that simply calls  "ping 127.0.0.1 -t" (-t loop forever option)
unfortunately RunDeck is not able to kill or stop this command the job is running forever or at leas the ping process.

Tested under Windows and CentOs

**Comment by ahonor** [comment]
Does the job stop and the process continue on the remote node? Is the node execution done over SSH for both cases?

**Comment by osigida** [comment]
Kinda nasty bug, just find out 5 heavy processes running simultaneously, which are supposed to be killed.

**Comment by angusfz** [comment]
The same result in rundeck version 2.4.2
Using below command then kill job via rundeck, but process still running on execute node.
```bash
while true; do date; sleep 1; done
```

**Comment by jankei83** [comment]
Rundeck 2.5.1 and the "kill job" feature doesn´t work yet. I tried to use OpenSSH to login => same problem.

service.NodeExecutor.default.provider=script-exec
plugin.script-exec.default.command=ssh -i <SSH-CERT> -oStrictHostKeyChecking\=no -tt ${node.username}@${node.hostname} ${exec.command}

**Comment by gMickey** [comment]
Reproducing on 2.6.2 on local windows host and remote windows note.
I think custom kill handler is the best choice since it's hard to make one universal solution.

**Comment by purduemike** [comment]
You guys can try a timeout in front of your command.

`timeout 15s command`

**Comment by davalente** [comment]
Same issue here. 
If I run this command (/usr/bin/ssh -q -tt user@host sleep 120) with "Execute locally" the process is killed, works perfectly. If I use a run the command "sleep 120" with "Dispach to node" and script exec: (plugin.script-exec.default.command=ssh -q -tt ${node.username}@${node.hostname} ${exec.command}) it doesn't work, the local ssh processes is not killed.

**Comment by shlomoa** [comment]
2.9.3 same thing
Note that the script created and executed remotely is removed,
The process will continue as long as the current child is running.
What should happen is that rundeck will kill the process tree, several examples here:
[https://stackoverflow.com/questions/392022/best-way-to-kill-all-child-processes](url)

**Comment by ahonor** [comment]
@shlomoa are you using openssh to (e.g., similar to @davalante) as the node executor?

**Comment by shlomoa** [comment]
Yes
