### ISSUE TITLE
Login fails the first time, but succeeds the second

### ISSUE THREAD

**Issue by AndyBerman** [rundeck/rundeck#1049]
I've tested this with IE and Chrome using the admin user.
After the first login attempt, it just goes right back to the login page - no error.
When I try to login again, it works.
We've installed on Linux and Windows, and get the same behavior.
Running version 2.3.2

**Comment by machinefixer** [comment]
Similar thing happened on me, after installation when I login as admin with password "admin", rundeck take me to the 404 which url is "localhost:4440", so I checked rundeck-config.properties file, the grails.serverURL has the defualt value "http://localhost:4440", and when you modify this value, you can't put a redundant slash behind your port like "http://xxxx.xxxx.com:4440/", rundeck will not find the correct page.

**Comment by SkyKing4AR2** [comment]
I have this older but same issue on a new install and wonder if there is any further information available to resolve the issue. I am using the exact fully qualified URL in the properties file, i.e. xxxx.domain:port in Internet Explorer.
