### ISSUE TITLE
'Fail the step without running on any remaining node' not behaving as expected

### ISSUE THREAD

**Issue by schicky** [rundeck/rundeck#1068]
In version 2.4 when running multiple threads, if 1 node fails it halts all other running threads and fails instead of letting them finish their steps and not starting new nodes. Running nodes should be allowed to finish. 

![image](https://cloud.githubusercontent.com/assets/7059792/5684885/159ab4ce-9803-11e4-8993-092e262876af.png)

**Comment by jefffiser** [comment]
Having the same issue but using a reference job.  The parent job (and reference job) are set to use single (1) thread(s) only but the issue still occurs.
