### ISSUE TITLE
high availability of rundeck web app

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#107]
Make rundeck able to be run in a 'hot/hot' or 'hot/standby' configuration where there are at least two instances of rundeck. Both aware of the 'universal state' of the rundeck state.

Goal being at least able to have quick failover (in case of host crash, etc.) from primary to secondary instance.

This has a lot of ramifications, it is likely acceptable that a running job (job that is running when the host dies) would fail. But, for example, any queued jobs, or other scheduled jobs, would be executed on the 'new primary machine'.

This is pretty much a classic 'leader/slave setup example'.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/436)

Original Creator: Esa

**Comment by ahonor** [comment]
This is a Pro feature
