### ISSUE TITLE
Make job xml export deterministic (notification element order)

### ISSUE THREAD

**Issue by kcd83** [rundeck/rundeck#1077]
The order of elements in the job xml export varies at random. If you run a diff on multiple exports you can examples like:

```
     </context>  
     <notification> 
+      <onfailure> 
+        <plugin type='HipChatNotification'> 
+          <configuration> 
+            <entry key='room' value='ChatOps'/> 
+          </configuration> 
+        </plugin> 
+      </onfailure>  
       <onstart> 
         <plugin type='HipChatNotification'> 
           <configuration> 
             <entry key='room' value='ChatOps'/> 
           </configuration> 
         </plugin> 
-      </onstart>  
-      <onfailure> 
-        <plugin type='HipChatNotification'> 
-          <configuration> 
-            <entry key='room' value='ChatOps'/> 
-          </configuration> 
-        </plugin> 
-      </onfailure> 
+      </onstart> 
     </notification>  
```

This is hardly an "issue" but it could be an enhancement for those of us storing the xml in source control. Particularly if we detect changes and push them nightly :)

...seems like this was once resolved in version 1
http://rundeck.lighthouseapp.com/projects/59277/tickets/110-job-xml-format-from-rd-jobs-list-f-out-is-not-consistent-between-runs
https://github.com/rundeck/rundeck/commit/46e9e0606c39c87efd2438ffd57b608271ad5964?diff=unified

**Comment by gschueler** [comment]
I believe this is fixed, work was done corresponding to SCM feature (2.6.0)
