### ISSUE TITLE
Feature Request: Expose log output as a variable for notification plugins

### ISSUE THREAD

**Issue by rodriguezsergio** [rundeck/rundeck#1080]
From the docs

http://rundeck.org/docs/manual/jobs.html

> Each Job execution is stored and contains information about the nodes where steps executed, success and duration of each step. The job execution output can be downloaded, forwarded to an external log store or sent as part of a notification via email, IRC, ticketing system, or other destinations.

After seeing that, I spent a good bit of time trying to figure out how to forward the job output to a notification plugin, but was unable to come up with anything. Hopefully, I'm not the first one to want something similar to this. It's already advertised in the docs! :smile:

**Comment by gschueler** [comment]
@srodrig0209 sorry bad phrasing, i think the docs are meant to say it's possible to send the logs via *email* notification, and not imply it is also possible via plugin.

it's a good feature request.  How would you imagine the plugin receives the data, just as a local temp file it can then send somewhere if needed?

**Comment by srodrig0209** [comment]
In my case, the log output I'm concerned with is quite short (a few lines at most), so I was hoping to pass that in directly to my shell script as an argument.

**Comment by ahonor** [comment]
I know of cases where some user's output is in the 100s of megabytes. Also some people sometimes just want the last N lines. For those cases, knowing the size or length is important. A temp file would give the plugin writer a way to check this but perhaps there are alternatives.
