### ISSUE TITLE
SSH plugin appends ^M to scripts, failing jobs to fail

### ISSUE THREAD

**Issue by mezbiderli** [rundeck/rundeck#1082]
We have a script that echoes a couple of lines to a tmp file, and then executes them, using Rundeck-ssh plugin.

   - type: rundeck-kingpin-ssh
      nodeStep: true
      configuration:
        commands: |-
          echo -e "#!/usr/bin/expect
          # No echoes to the user
          log_user 0
          log_user 0
          log_user 0
          
          # Debug
          exp_internal 0

However, rendered file contains ^M appended to each EOL, failing jobs.

#!/usr/bin/expect^M
^M
# No echoes to the user^M
log_user 0^M
log_user 0^M
log_user 0^M
^M
# Debug^M
exp_internal 0^M
^M
# Checks the last spawn and exits with the same exit value if not zero^M

/bin/sh: /tmp/b54af185-c4bb-4f0b-a629-ea7a1a992544-321-setbootdevice: /usr/bin/expect^M: bad interpreter: No such file or directory

This wasn't an issue with the same plugin before 2.4.1.

Is this known?

Thanks

**Comment by gschueler** [comment]
can you explain more how your plugin works and how the script is executed?

**Comment by mezbiderli** [comment]
Actually this is an issue while saving the workflow definition. Plugin simply executes command remotely using a custom pipe mechanism to forward passwords (not really relevant to this context).

Say I want to save these lines in step definition (as directly entered in textbox)

do_stuff_0
echo -e "do_stuff_1

do_stuff_2"
do_stuff_3

exported job definition looks like this;

    - type: rundeck-kingpin-ssh
      nodeStep: true
      configuration:
        commands: |-
          do_stuff_0
          echo -e '#do_stuff_1^M
          ^M
           do_stuff_2"
           do_stuff_3

Note there's no ^M after commands other than echo (not sure quotes have an implication for it)

Plugin does what is exactly ordered, flushes content as is, with ^Ms. Hence fails when flushed content is executed.

I know this is not the best practice to follow, but most of our workflows run this way atm.

Any insights to where fix might be would also be quite helpful. I browsed grails content but it's not clear where step content is serialized (with ^Ms).

Thanks!

**Comment by gschueler** [comment]
ok, i think this is caused by recent switch to use jQuery javascript lib in the GUI for submitting ajax requests (vs. old use of prototype js lib).  The line endings in the form are being sent differently than they used to.  We stumbled on this with Script steps, because the script content was getting stored with DOS line endings if you use a Windows client to rundeck, i.e. you are browsing the web GUI from windows.

We also had to tweak what kind of line endings in scripts were then subsequently used based on the target node's OS type.

I'm guessing that the textbox content you enter for your custom step plugin is being stored with DOS line endings now and passed that way to your plugin.  A test would be to try to perform the same job create/edit on a web browser using a mac/unix machine, and see if the bogus ^M chars get inserted in the step definition.

Maybe we need to have a way for multi-line input properties for plugins to declare the kind of line endings they want to receive.

**Comment by mezbiderli** [comment]
Interesting... actually these line endings are generated when viewing/storing using Chrome on MacOs.. Same results with Mozilla Firefox 35.. Again, using either browsers I can see ^M on saved workflow definition (before it is even executed).

Has this been fixed recently? Latest CL we have in our fork is dcefb0536d179143b35606071652e1752528c330 (12/18).

Thanks!

**Comment by gschueler** [comment]
no, wouldn't have changed since then. the jquery change i mentioned happened in 2.3.x. Maybe the ^M are sent in all cases then, regardless of client.

do you mean that the ^M is shown in the gui, or only in the xml/yaml definition?

**Comment by mezbiderli** [comment]
^M is only shown in stored workflow definition. Even the yaml doesn't show ^Ms on browser, they are visible only when workflow is downloaded and opened with say vi. If ^Ms are cleaned up and re-loaded, workflow works fine..

Let me know if I could be looking at a certain code, or trying debugging..

**Comment by mezbiderli** [comment]
This seems to be the suspect (jquery.js::serializeArray())

			return val == null ?
				null :
				jQuery.isArray( val ) ?
					jQuery.map( val, function( val ){
						return { name: elem.name, value: val.replace( rCRLF, "\r\n" ) };
					}) :
					{ name: elem.name, value: val.replace( rCRLF, "\r\n" ) };
		}).get();

I am trying reverting effects of this change in _wfisave

**Comment by mezbiderli** [comment]
It seems to be introduced as a fix to http://bugs.jquery.com/ticket/6876

**Comment by mezbiderli** [comment]
Replacing \r\n with \n (if browser agent is mozilla) seems to have solved the problem

var data= jQuery("#"+formelem+" :input").serialize().replace(/%0D%0A/g, "%0A");

**Comment by gschueler** [comment]
ok, sounds like fixing the line endings should happen on the server side, and not rely on the client input.

thanks for getting to the heart of the problem.

**Comment by azplanlos** [comment]
I can see this behaviour again with version 3.04 when using an inline script step in a job
