### ISSUE TITLE
Enter <cr> does not work under the activity view for a project 

### ISSUE THREAD

**Issue by jedblack** [rundeck/rundeck#1084]
When viewing activity history for a particular project and trying to filter the view, if you hit 'enter' on the keyboard it just refresh the page view.  You actually have to click the filter button for the filtering to work.  Was not a big deal at first, but has been confusing more and more users.  Would this be an easy fix, appear to be a pure UI/UX bug.

![activity filter](http://i.imgur.com/1t4NPSk.png)

**Comment by gschueler** [comment]
sounds like a ui bug

**Comment by jedblack** [comment]
Thank you Greg!
