### ISSUE TITLE
rundeck fails with Solaris 10 hosts due to pam conversation error

### ISSUE THREAD

**Issue by sagetrey** [rundeck/rundeck#1085]
Background: ssh to this solaris hosts works fine with ssh username and password. 
The solaris boxes are using quest plugin called vintella for authenticating against AD. 

Scenarios:
Some of the solaris box rundeck fails with ssh password method. Turning on debug on the solaris side shows the following error. The same username and password works on the other linux boxes and during manual login. So I am absolutely certain that I not entering wrong ssh password on the rundeck portal:

[ID 516830 auth.info] pam_vas: Authentication <failed> for <Active Directory> user: testuser

[ID 800047 auth.info] Failed password for test user

[ID 800047 auth.info] Received disconnect from 10.102.3.4: 3: com.jcraft.jsch.JSchException: Auth fail

**Comment by ahonor** [comment]
Reopen if this is still an issue.
