### ISSUE TITLE
'Algorithm negotiation fail'  JSCH

### ISSUE THREAD

**Issue by ffk23** [rundeck/rundeck#1087]
For hardened OpenSSH >6.6 server need support DH-SHA2.(for example it used in openssh for  Cygwin 1.7.32) It was coded but undeclared in the capabilities.
Jsch team has prepared the patch http://sourceforge.net/p/jsch/patches/7/ 
Maybe you can include patched jsch in new Rundeck release

**Comment by gschueler** [comment]
It looks like we could set the config value manually without patching the Jsch code:

```{.java}
Jsch.setConfig("kex","diffie-hellman-group1-sha1,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha1,diffie-hellman-group-exchange-sha256")
```

**Comment by gschueler** [comment]
note: it might be possible to set this via the ssh config settings http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html#specifying-ssh-config-options

e.g.:  node attribute `ssh-config-kex="..."`

(haven't tested this)

**Comment by gschueler** [comment]
- [ ] upgrade to jsch 0.5.2

**Comment by RMachnik** [comment]
I still see this failing even when I have updated to jsch 0.1.55
