### ISSUE TITLE
 Export archive does not work

### ISSUE THREAD

**Issue by reigner-yrastorza** [rundeck/rundeck#1094]
------- Forwarded Message --------
Subject: 	Re: [rundeck] Export archive does not work
Date: 	Thu, 29 Jan 2015 17:59:15 -0800
From: 	Alex Honor <alex@simplifyops.com>
Reply-To: 	rundeck-discuss@googlegroups.com
To: 	rundeck-discuss@googlegroups.com <rundeck-discuss@googlegroups.com>

Hi Reigner,
I think the web page is timing out on the export. Can you log this as an issue?
Thanks

On Thu, Jan 29, 2015 at 11:36 AM, Reigner S. Yrastorza <reigner@yrastorza.us> wrote:

    Hi,

    Rundeck version: rundeck-2.4.0-1.1.GA.noarch
    OS: CentOS 6.5
    Jobs: 304 jobs
    DB: H2

    When I am trying to do an export archive of a project using the web interface, it just loads and doesn't do anything.

    Note:
    1. There is nothing in the logs indicating a failure
    2. rd-jobs from the CLI works
    3. Already tried different browsers
    4. From the previous versions I am aware it takes awhile to complete

    Any ideas?

    Thanks,
    Reigner S. Yrastorza

**Comment by gschueler** [comment]
to handle potentially long export processes, it should be done asynchronously and allow the user to download the file after it is done
