### ISSUE TITLE
Can not use CLI tools with auth error

### ISSUE THREAD

**Issue by mats116** [rundeck/rundeck#1096]
I try to use cli tool on rundeck.
But an error similar to the following are displayed

```
$ run -i <job id>

Error: Error making server request to http://localhost:4440: Error occurred while trying to authenticate to server: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```

※config

```
$ cat /etc/rundeck/framework.properties
# framework.properties -
#

# ----------------------------------------------------------------
# Rundeck server connection information
# ----------------------------------------------------------------

framework.server.name = localhost
framework.server.hostname = localhost
framework.server.port = 4440
framework.server.url = http://localhost:4440
# Username/password used by CLI tools.
framework.server.username = admin
framework.server.password = admin

rundeck.tokens.file = /etc/rundeck/tokens.properties

# ----------------------------------------------------------------
# Installation locations
# ----------------------------------------------------------------

rdeck.base = /var/lib/rundeck

framework.projects.dir = /var/rundeck/projects
framework.etc.dir = /etc/rundeck
framework.var.dir = /var/lib/rundeck/var
framework.tmp.dir = /var/lib/rundeck/var/tmp
framework.logs.dir = /var/lib/rundeck/logs
framework.libext.dir = /var/lib/rundeck/libext

# ----------------------------------------------------------------
# SSH defaults for node executor and file copier
# ----------------------------------------------------------------

framework.ssh.keypath = /var/lib/rundeck/.ssh/id_rsa
framework.ssh.user = rundeck

# ssh connection timeout after a specified number of milliseconds.
# "0" value means wait forever.
framework.ssh.timeout = 0

# ----------------------------------------------------------------
# S3
# ----------------------------------------------------------------

framework.plugin.ExecutionFileStorage.org.rundeck.amazon-s3.bucket = hoge
framework.plugin.ExecutionFileStorage.org.rundeck.amazon-s3.path = project/${job.project}/${job.execid}
framework.plugin.ExecutionFileStorage.org.rundeck.amazon-s3.region = ap-northeast-1
```

```
$ cat /etc/rundeck/tokens.properties
admin: admin
```

**Comment by gschueler** [comment]
the message "the trustAnchors parameter must be non-empty", is a java error meaning that the truststore  used for SSL connections is missing.  For Rundeck, it is usually not configured to use the truststore set unless you have enabled SSL for the rundeck server.  

how did you install Rundeck and start the server?

**Comment by mathieuchateau** [comment]
Hello,

I have same issue. I am using latest version on Rundeck (2.5.2-1), and try now to use cli command. 

I am doing SSL offloading, so url for rundeck is https, but no https on rundeck itself

```Java
Error: Error making server request to http://localhost:4440: Error occurred while trying to authenticate to server: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```
But RDECK_SSL_OPTS is correct based on previous comment here:

    export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=/etc/rundeck/ssl/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"

I am doing SSL offloading, may it be related ? 
This file is missing: /etc/rundeck/ssl/truststore

```Shell
[root@myserver ~]# ll /etc/rundeck/ssl/
total 4
-rw-r--r--. 1 rundeck rundeck 158 Jul  7 20:04 ssl.properties
```

**Comment by gschueler** [comment]
If you are not using HTTPS locally to connect to rundeck, you should not use the RDECK_SSL_OPTS when executing the CLI.  Otherwise, make sure the /etc/rundeck/ssl/truststore exists/is a valid truststore

**Comment by mathieuchateau** [comment]
Hello,
thanks @gschueler , it works after commenting. At the same time I am confident I did not uncomment it . Could it be uncommented by default ?

**Comment by mathieuchateau** [comment]
Checking in profile file source code, RDECK_SSL_OPTS is enabled by default, will make a pull request to get a condition

if [ -f /etc/rundeck/ssl/truststore ];then
	export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=/etc/rundeck/ssl/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"
fi

**Comment by danielladd** [comment]
I am receiving the trustAnchors response when attempting to run rd-project. I have rundeck behind a load balancer that applies an SSL layer, the rundeck server itself is not configured with ssl. Any thoughts on how to support this configuration?

**Comment by kazgurs** [comment]
Running behind a load balancer shouldn't really be an issue, since the CLI tools make requests to localhost:4440, just try commenting `export RDECK_SSL_OPTS=` in `/etc/rundeck/profile`.

**Comment by gschueler** [comment]
fyi: we are working on a new cli tool which will eventually replace the old set.  The functionality should be on par with the old tools.  The authentication is set via environment variables and does not use the `/etc/rundeck/profile`, it can be used standalone

https://github.com/rundeck/rundeck-cli/

**Comment by gschueler** [comment]
closing, the cli tools were removed in 2.7.0 in favor of new tool [rd](https://rundeck.github.io/rundeck-cli/)
