### ISSUE TITLE
Bulk delete

### ISSUE THREAD

**Issue by richiereynolds** [rundeck/rundeck#1097]
I have a job with thousands of executions. How can delete them all? I can no longer export the project as I get GC out of memory error. Is there a manual command i can run in the mysql database?

**Comment by gschueler** [comment]
you could try using the API, there is an endpoint to delete all executions for a job, see http://rundeck.org/docs/api/index.html#delete-all-executions-for-a-job

You can also use the API to query for a set of executions, and use that set to call the bulk delete API

**Comment by venkat-vs-id** [comment]
If are using a FILE-DB like me, here is a quicker way to delete all the executions

http://venkat-echo.blogspot.com.au/2015/12/py-rundeck-delete-executions.html
