### ISSUE TITLE
rpm conflicts with firelsystem package when installing on Amazon Linux

### ISSUE THREAD

**Issue by bluskool** [rundeck/rundeck#1098]
Attempting to install from the latest rpm on Amazon Linux reports the following error:

```
Transaction check error:
  file /usr/share/man from install of rundeck-1.4.2-1.1.noarch conflicts with file from package filesystem-2.4.30-3.8.amzn1.x86_64
  file /usr/share/man/man1 from install of rundeck-1.4.2-1.1.noarch conflicts with file from package filesystem-2.4.30-3.8.amzn1.x86_64
  file /usr/share/man/man5 from install of rundeck-1.4.2-1.1.noarch conflicts with file from package filesystem-2.4.30-3.8.amzn1.x86_64
```

**Comment by gschueler** [comment]
thanks, i think we can remove the reference to /usr/share/man, since we don't include the documentation in the distribution anymore

**Comment by bluskool** [comment]
I didn't even notice before, but the version being installed was 1.4. It seems there was a problem with the  latest RPM being downloaded yesterday. I checked a latest.rpm I had downloaded yesterday and it was installing older yum repos. The latest.rpm that I downloaded today installs the the latest repo.

**Comment by gschueler** [comment]
oh, i see now it says rundeck-1.4.2. 

did you have any issue with the newer rpm? if not, we can close this

**Comment by bluskool** [comment]
No issues with the new RPM. Thanks
