### ISSUE TITLE
RUNDECK : Authentication failure connecting to nodes

### ISSUE THREAD

**Issue by rahulkalva** [rundeck/rundeck#1099]
Issue Type: Bug
Rundeck version: 1.6.2-1
JDK Version: jdk1.6.0_18
Server OS: amd64 Linux 2.6.9-42.ELsmp

Issue:

RUNDECK : Authentication failure connecting to nodes

(For Rundeck GUI issues, please include the following:)

Client OS: (your OS name, version)
Client web browser: (your browser name, version)
Log details -

When we configure a job to run the command "touch /tmp/test" in our agents from the server , we are getting the following error -

Authentication failure connecting to node: "test123Agent". Make sure your resource definitions and credentials are up to date.
09:00:02 Failed: AuthenticationFailure: Authentication failure connecting to node: "test123Agent". Make sure your resource definitions and credentials are up to date.

But, when i try to do the same command in the agnet directly, the touch command is working correctly.

Also, verified the ssh from parent to child agent which was working correctly -

ssh $(awk '/project.ssh-keypath = / {print $3}'
/road/local-web/rundeck/projects/ROAD_RELENG/etc/project.properties) releng@test123Agent

Please let me know the details on how to fix this.

**Comment by ahonor** [comment]
Hi @rahulkalva,
Are you using ssh-agent?

**Comment by rahulkalva** [comment]
Hello Ahonor,

Yes, we are using ssh-agent.

**Comment by charmeep** [comment]
Hi,

I have a similar error. I have setup password less ssh. 

This is working fine 
ssh -i $(awk '/framework.ssh.keypath = / {print $3}' $RDECK_BASE/etc/framework.properties) testlogin@testnode

^2015-02-08T19:31:11Z|nodebegin||{node=testnode|step=1|stepctx=1|user=testlogin}|^
^2015-02-08T19:31:11Z||VERBOSE|{node=testnode|step=1|stepctx=1|user=testlogin}|Using ssh keyfile: /Users/charmee/.ssh/id_rsa^
^2015-02-08T19:31:11Z||VERBOSE|{node=testnode|step=1|stepctx=1|user=testlogin}|Starting SSH Connection: testlogin@testnode (testnode)^
^2015-02-08T19:31:11Z||VERBOSE|{node=testnode|step=1|stepctx=1|user=testlogin}|Set timeout to 0^
^2015-02-08T19:31:11Z||VERBOSE|{node=testnode|step=1|stepctx=1|user=testlogin}|Connecting to testnode:22^
^2015-02-08T19:31:11Z||ERROR|{node=testnode|step=1|stepctx=1|user=testlogin}|Authentication failure connecting to node: "testnode". Make sure your resource definitions and credentials are up to date.^
^2015-02-08T19:31:11Z||ERROR|{node=testnode|step=1|stepctx=1|user=testlogin}|Failed: AuthenticationFailure: Authentication failure connecting to node: "testnode". Make sure your resource definitions and credentials are up to date.^

I am not using ssh-agent. How can I fix this?

**Comment by gadelkareem** [comment]
same here using ec2 plugin

**Comment by haimari** [comment]
Same issue here:
SSH works from CLI but not from rundeck
and as mentioned above i also see ec2-user@ when using ec2 plugin without any way to modify it

**Comment by mat-green** [comment]
add username.default=ubuntu ot the Mapping Params of the EC2 plugin configuration.
