### ISSUE TITLE
Bug: options url ampersand symbol replaced with "amp;"

### ISSUE THREAD

**Issue by mumblez** [rundeck/rundeck#1101]
rundeck version: 2.4.0

Love the new feature to use markdown and html in the description fields but noticed a small bug when editing existing steps and re-saving the job; it breaks the options provided by url as it replaces the ampersands '&' with 'amp;', e.g.

http://url?option1=value1**&**option2=value2
becomes
http://url?option1=value1**amp;**option2=value2

Each time you edit and re-save the job extra **amp;** appears!

**Comment by gschueler** [comment]
does it happen even if you don't modify the options for the job?

**Comment by mumblez** [comment]
if I don't modify any options and save it's ok, but if I modify an option, save the option and save the job then it happens.

Was scratching my head for a while, I had thought it was the new markdown text I was putting in, stripping it out had no effect then I spotted the numerous "amp;" in the options url, I really should of spotted it sooner!!!

**Comment by siminm** [comment]
Happens to me also. No way to undo this now :-\

**Comment by mumblez** [comment]
@siminm it's OK if you didn't edit the option even though you see the amp; if you do edit you'll have to replace with & before saving, workaround for now

**Comment by gschueler** [comment]
option value is double encoded in form field
