### ISSUE TITLE
Unable to start Grails: java.lang.reflect.InvocationTargetException

### ISSUE THREAD

**Issue by lonefreak** [rundeck/rundeck#1102]
Is anyone having trouble to build/package Rundeck using Ant 1.8.3? When I try to package it as stated in the Readme file, I get this error:

[ERROR] Failed to execute goal org.grails:grails-maven-plugin:1.3.7:maven-clean (default) on project rundeck: Unable to start Grails: java.lang.reflect.InvocationTargetException: The following error occurred while executing this line:
[ERROR] jar:file:/home/user/.ivy2/cache/org.apache.ant/ant/jars/ant-1.8.3.jar!/org/apache/tools/ant/antlib.xml:37: Problem: failed to create task or type componentdef
[ERROR] Cause: The name is undefined.
[ERROR] Action: Check the spelling.
[ERROR] Action: Check that any custom tasks/types have been declared.
[ERROR] Action: Check that any <presetdef>/<macrodef> declarations have taken place.

I found a Grails issue (https://jira.grails.org/browse/GRAILS-6897) that says Grails is not compatible with versions of Ant above 1.7. But I just can't agree with that since you guys ship it with Ant 1.8.3 as a dependency. What can I possibly being doing wrong?

**Comment by lonefreak** [comment]
I'm using
Grails Version: 3.0.0.BUILD-SNAPSHOT
Groovy Version: 2.4.0
JVM Version: 1.8.0_25

All in a Macbook running OSX 10.10.1

**Comment by gschueler** [comment]
current dev branch uses grails 2.4.4, and the build is done using gradle, and will require JDK 7 or 8.  See https://github.com/rundeck/rundeck/blob/development/README.md

Older versions (e.g. 2.3) use grails 1.3.7, and will require JDK 6 or 7

**Comment by varra4u** [comment]
Hi Team,

I'm getting the below error while building the code with grails 1.3.7!!!! Please find the error message shared.

[INFO]
[INFO] --- grails-maven-plugin:1.3.7:maven-clean (default) @ rundeck ---
[INFO] Using Grails 1.3.7
Maven Central: http://repo1.maven.org/maven2/
Grails Central: http://grails.org/plugins
WARNING: Configurational method [inherits] in grails-app/conf/BuildConfig.groovy doesn't exist. Ignoring..
Application Version: 2.5.0
WARNING: Configurational method [legacyResolve] in grails-app/conf/BuildConfig.groovy doesn't exist. Ignoring..
WARNING: Configurational method [legacyResolve] in grails-app/conf/BuildConfig.groovy doesn't exist. Ignoring..
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] RunDeck App ....................................... FAILURE [3.083s]
[INFO] Rundeck Launcher .................................. SKIPPED
[INFO] RunDeck Launcher Parent ........................... SKIPPED
[INFO] RunDeck parent project ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.890s
[INFO] Finished at: Sun May 10 07:46:34 IST 2015
[INFO] Final Memory: 31M/620M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.grails:grails-maven-plugin:1.3.7:maven-clean (default) on project rundeck: Unable to start Grails: java.lang.reflect.InvocationTargetException: loader constraint violation: when resolving overridden method "org.apache.tools.ant.helper.ProjectHelper2$RootHandler.setDocumentLocator(Lorg/xml/sax/Locator;)V" the class loader (instance of org/codehaus/groovy/grails/cli/support/GrailsRootLoader) of the current class, org/apache/tools/ant/helper/ProjectHelper2$RootHandler, and its superclass loader (instance of <bootloader>), have different Class objects for the type andler.setDocumentLocator(Lorg/xml/sax/Locator;)V used in the signature -> [Help 1]


Thanks,
Krishna

**Comment by gschueler** [comment]
don't use grails 1.3.7, currently we use 2.4.4.

try following the build instructions here https://github.com/rundeck/rundeck/wiki/Building-and-Testing
