### ISSUE TITLE
Make secure option default value secure

### ISSUE THREAD

**Issue by mprasil** [rundeck/rundeck#1106]
Currently, if we set the *Secure* or *Secure Remote Authentication* option with a *Default Value* and provide the job to user that doesn't have the right to edit the job, visually it looks like the pre-filled value is hidden to him, however the value can be easily retrieved:
- as a value of the password field 
 - suggestion: show as empty, if running the job with empty field use default value, GUI can indicate this by placeholder attribute saying something like "Use default."
- in the Download Job definition XML/YAML file. 
 - suggestion: add support for *export* action for a job in the project context in the aclpolicy file

As it is right now, calling the option *Secure* is misleading and from security standpoint it's just *Plain text* option with little security benefits. (like not storing the value after run)

**Comment by gschueler** [comment]
secure option defaults can be stored in Key Storage facility now (rundeck 2.6.2+)
