### ISSUE TITLE
documentation needed: using the sudo password and ssh private key passphrase via storage facility for ssh

### ISSUE THREAD

**Issue by tomkregenbild** [rundeck/rundeck#1110]
Is there a way to provide the sshKeyPassphrase value to a scheduled job and enable the job to run repeatedly?

From what I see I am only able to run the job manually and provide the passphrase by hand with each run.

**Comment by gschueler** [comment]
You can use a stored password for the ssh password, however, this needs to support the key passphrase as well.

**Comment by tomkregenbild** [comment]
@gschueler Is there any update on this? is there a plan to add it in the near future?

**Comment by gschueler** [comment]
you can now use a node attribute `ssh-key-passphrase-storage-path` that points to a password in the Storage facility to do this, from issue #1122. Documentation was not updated, changing the title of this issue

**Comment by pecigonzalo** [comment]
Can you use that to pass a storage passphrase as a parameter to a script? can you provide an example?

Thanks

**Comment by gschueler** [comment]
stored passwords/keys can't be used directly in scripts.  If you create a script-based plugin, then stored passwords can be passed to the plugin

**Comment by pecigonzalo** [comment]
Fine, how?

**Comment by gschueler** [comment]
Sorry, I looked at the documentation, this is only available for NodeExecutor and FileCopier plugins right now.  To use it you would create a script-plugin NodeExecutor, see [Script Plugin Development](http://rundeck.org/docs/developer/plugin-development.html#script-plugin-development)  then define a configuration property using the various storage options shown under [Property Rendering Options](http://rundeck.org/docs/developer/plugin-development.html#property-rendering-options).  Here is an example:

~~~ {.yaml}

name: my-plugin
rundeckPluginVersion: 1.0
author: me
date: 10/15/2015
version: 1.1
providers:
    - name: my-node-exec
      service: NodeExecutor
      title: Test Executor
      description: "Test"
      plugin-type: script
      script-file: "myscript.sh"
      script-args: "--node ${node.hostname} --user ${node.username}"
      config:
        - name: passwordStoragePath
          title: Password Storage Path
          type: String
          required: false
          description: "Optional storage path for authentication password. Can contain property references to node attributes. A node attribute named password-storage-path will override this value."
          scope: Instance
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"
            storage-file-meta-filter: "Rundeck-data-type=password"
            instance-scope-node-attribute: "password-storage-path"
        - name: password
          title: Password Secure Option Name
          type: String
          required: false
          description: "Secure Option name for Password"
          scope: InstanceOnly
          default: "option.password"
          renderingOptions:
            valueConversion: "PRIVATE_DATA_CONTEXT"
            valueConversionFailure: "remove"
            instance-scope-node-attribute: "password-option"
~~~

**Comment by gschueler** [comment]
For Sudo and secondary Sudo password authentication using Key Storage facility.

Add a node attribute:

* `sudo-password-storage-path`: path in the Storage Facility to a password for sudo
* `sudo2-password-storage-path`: path in the Storage Facility to a password for secondary sudo
