### ISSUE TITLE
2.4.1 Using the Script Execution under the Default Node File Copier caused a 'chmod: cannot access' error upon script copy

### ISSUE THREAD

**Issue by smithtimamy** [rundeck/rundeck#1112]
I have been chasing my tail trying to figure this one out. Because of a problem we have been running into with jsch-scp, I decided to use the Script Execution in the Default Node File Copier but am stuck on a `chmod: cannot access` error when executing the job because the chmod is using the incorrect filename.

The job definition contains a very simple inline script that is just echoing out the hostname of the remote machine

The settings I have for the Script Execution are (from the project.properties file):

```
service.FileCopier.default.provider=script-copy
plugin.script-copy.default.command=/usr/bin/scp -o "StrictHostKeyChecking no" -o "LogLevel ERROR" ${file-copy.file} ${node.username}@${node.hostname}\:/var/tmp/${file-copy.filename}
plugin.script-copy.default.remote-filepath=/var/tmp/${file-copy.filename}
plugin.script-copy.default.shell=bash -c
```

This is the job execution output I am getting for the script copy to the remote node:

```
[workflow] beginExecuteNodeStep(MYSERVERNAME): NodeDispatch: com.dtolabs.rundeck.execution.ExecutionItemFactory$1@7f18d44
[script-copy] executing: bash -c /usr/bin/scp -o "StrictHostKeyChecking no" -o "LogLevel ERROR" /opt/local/share/rundeck/var/tmp/dispatch1414138524299533048.tmp rundeck@MYSERVERNAME.domain.com:/var/tmp/dispatch1414138524299533048.tmp
[script-exec] executing: /usr/bin/bash -c /usr/bin/ssh -q -o "StrictHostKeyChecking no" -o "LogLevel Error" rundeck@MYSERVERNAME.domain.com chmod +x /tmp/1424109782748-MYSERVERNAME-dispatch-script.tmp.sh
chmod: cannot access `/tmp/1424109782748-cmh-pnkappspa-001-dispatch-script.tmp.sh': No such file or directory
[script-exec]: result code: 1, success: false
[script-exec]: result code: 1, success: false
Failed: NonZeroResultCode: Result code was 1
```

I am sure I am missing something as far as the chmod goes but I cannot find what/where to change that filename.

Please let me know what additional information that is needed.

We are running Rundeck 2.4.1-1 americano limegreen bullhorn

**Comment by gtmx** [comment]
Hi,
Were you able to solve this issue?

**Comment by gschueler** [comment]
some changes in the way rundeck invokes file copiers probably caused this.  Rundeck now predetermines the destination path for the file, so the `plugin.script-copy.default.remote-filepath` will not be used I believe.
try changing the `plugin.script-copy.default.command ` to use `:${file-copy.destination}` instead of `:/var/tmp/${file-copy.filename}`
To change the tmp dir used for copying scripts, update the node to have an attribute `file-copy-destination-dir`.  In 2.5, you can also set this in the project/framework properties

**Comment by gtmx** [comment]
Thnx greg. Issue was so dumb. Node executor was set to stub :D

**Comment by smithtimamy** [comment]
Cleaning up this old open issue.

@gschueler the suggestion to use ```:${file-copy.destination}``` worked wonderfully when we ran into a similar issue when updateing to version 2.7.1.
