### ISSUE TITLE
Any Ideas to Disable Auto Expand Feature After Entered An Project?

### ISSUE THREAD

**Issue by Naolador** [rundeck/rundeck#1113]
Hi all,

I have dozens of jobs and groups in a project, each time I entered this project rundeck will automatically expand all groups, so I have to scroll down a lot to locate my group and found my job which wanna use it.
Anyone have any ideas about how to disable automatically expand all groups after I entered a project? I think I should add an option in "rundeck-config.properties" to adjust the gui prefferences, but don't know how.

**Comment by ahonor** [comment]
This can be controlled via the "Job Group Expansion Level" in the project configuration
