### ISSUE TITLE
Duration is not being calculated correctly on report page

### ISSUE THREAD

**Issue by schicky** [rundeck/rundeck#1117]
I'm using version 2.4.0-1. The duration's reported for each step are incorrect. The duration of the overall job seems accurate.

Report Tab:
![image](https://cloud.githubusercontent.com/assets/7059792/6322121/29ce29d4-badc-11e4-90a1-43bac1060d93.png)

From the Log Output tab:
![image](https://cloud.githubusercontent.com/assets/7059792/6322122/3732ef60-badc-11e4-8d43-a948fc44ea06.png)

**Comment by jefffiser** [comment]
+1
