### ISSUE TITLE
Check hosts are alive before dispatching jobs

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#112]
I'm unsure if this makes sense but currently we use EC2 a lot and so my project has lots of nodes listed.  Not all of these nodes will be alive and it's annoying to get tons of errors per run.  I would like an option to say "ignore dead nodes" in some fashion and have Rundeck attempt a pre-run ssh to all hosts to check alive status and then only dispatch the jobs to alive nodes (to keep the output clean).

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/452)

Original Creator: Ashley Penney

**Comment by rdmendo** [comment]
+1
need "ignore dead nodes" or "ping before dispatch"

**Comment by gschueler** [comment]
Node Healthcheck is available in Rundeck Enterprise https://rundeck.com
