### ISSUE TITLE
Remote URL provider is getting 'amp;' injected on save

### ISSUE THREAD

**Issue by jedblack** [rundeck/rundeck#1125]
For example, this is a remote URL for jenkins integration:

https://jenkins.lipsum.net/plugin/rundeck/options/build?project=service&amp;amp;build=.*&amp;artifactRegex=service-*\.rpm

On every save of the options section of job (eve if there is no changes) , it appends the amp;

Meaning, you start with this:

https://jenkins.lipsum.net/plugin/rundeck/options/build?project=service&build=.*&artifactRegex=service-*\.rpm

Click save, and them expand the option section, it now looks like this:

https://jenkins.lipsum.net/plugin/rundeck/options/build?project=service&amp;build=.*&amp;artifactRegex=service-*\.rpm

Click save again, and it looks like this:

https://jenkins.lipsum.net/plugin/rundeck/options/build?project=service&amp;amp;build=.*&amp;artifactRegex=service-*\.rpm

Rinse and repeat....

**Comment by gschueler** [comment]
are you using 2.4.2? see #1101

**Comment by ahonor** [comment]
Reopen if this is still a concern
