### ISSUE TITLE
Run job from a specific step

### ISSUE THREAD

**Issue by nitdana** [rundeck/rundeck#1130]
Hi,

It would really nice to have the ability to run specific steps of a job.
Especially in a scenario in which a big job fails in the middle, and you want to resume the process from the point it stopped.
Right now the way to handle it is to duplicate the big job and to delete the unnecessary steps.

We would really appreciate it.
Thanks,
Nitzan.

**Comment by tomkregenbild** [comment]
+1 it would make things easier with large jobs

**Comment by Slind14** [comment]
:+1:

**Comment by JeanPascalR** [comment]
It would be a good feature to provide the index of the first step and the index of the last step to launch a specific range of a workflow.

**Comment by fdevans** [comment]
Based on feature availability in Rundeck Enterprise we are going to close this request.  If you would like to try Rundeck Enterprise to see if that version can address your request please feel free to say Hello at hello@rundeck.com.
Thank you, 
The Rundeck Team
