### ISSUE TITLE
Feature Request: ACL: possibility to hide definition tab

### ISSUE THREAD

**Issue by TomGudman** [rundeck/rundeck#1136]
Hi,

In some scenarios, you do not want the user to see the command we are going to run (e.g: contains a password in the command line). Therefore it would be cool if we could hide the definition tab from non admin users. 

Current version used: 2.4.2
OS: Centos6

Thank you

**Comment by gschueler** [comment]
also #124

**Comment by TomGudman** [comment]
Re,

It is vaguely related to #124 but it is 2 different problems IMO. Indeed 
#124 talks about ACLs for jobs whereas this is more ACLs for UI 
components. Eg: "Do not display 'debug mode'"

Cheers
Thomas

**Comment by gschueler** [comment]
the idea is you could use acls to allow "run" access, but not "read" access, thus hiding the Details tab

**Comment by kmusard** [comment]
+1 for allowing run without reading or exporting of the job definition

**Comment by gschueler** [comment]
I have a question about how this should work, though:

If you can run a job without viewing the details, are you able to see the execution output?  If so Are you able to view the steps that are running, i.e. the type of step and so on?

**Comment by kmusard** [comment]
I would still like the user to be able to see the execution output and the steps that are running, but would like the option to restrict viewing or exporting the job definition.  Although it is possible a use case might exist where you just want someone to be able to run the job without access to its output and steps as well.

**Comment by ahonor** [comment]
might be overloading the "edit" ACL action but another idea is to require "edit" to given access to see a Definition

**Comment by MLukman** [comment]
I vote for this feature request to separate ACL action for viewing jobs definition which will grant/prohibit viewing the "Definition" tab as well as exporting job as XML/YAML.

Definitely necessary if the jobs contain passwords or integration tokens that you don't want the system operators to take a peek at.

Rundeck 2.7.3-1

**Comment by molkmeister** [comment]
@gschueler @MLukman Has there been any update on this?

Rundeck 2.7.3-1

**Comment by oCHRISo** [comment]
+1 on @MLukman comment.

**Comment by TomGudman** [comment]
FWIW, what I ended up doing is using a "launcher script" to hide things you do not want the user to see.

1. The job execute the launcher_script.sh (or .bat for Windows people)
2. Within the launcher_script call your "real" program with the extra secret arguments you need. 
3. The end-user will only see the launcher_script and any argument provided by the end-user
4. Profit.

I can understand that this solution may not work in some odd cases however it should be a viable solution the majority of the time. Unfortunately that creates an extra script to maintain. 

Hopefully, one day, rundeck will hide this tab ;-) It has been now 2 years since I created this issue but it's open source code so if you really need it, code it. Sadly I cannot ;) 

Keep +1 the thread and we may get it one day :)

**Comment by sys-ops** [comment]
+1 on @TomGudman comment.

**Comment by jwaversveld** [comment]
http://rundeck.org/news/2018/04/27/rundeck-2.11.0.html

The feature is there and working:

> Job Definition visibility ACL:
> A new ACL access level view is a subset of the read access level for jobs, and does not allow users to view the “Definition” tab of a Job, or download the XML/YAML definitions.

**Comment by gschueler** [comment]
added in 2.11
