### ISSUE TITLE
Feature Request: Form: returned value for selected input

### ISSUE THREAD

**Issue by TomGudman** [rundeck/rundeck#1138]
Hi,

I would like to know if it is possible to have different values than what is displayed in the select box
For instance:
- Yes (will return '-c')
- No (will return '-p')

I did try the [JSON](http://rundeck.org/2.4.2/manual/jobs.html#json-format) way in the job definition via the web form but it did not work for me. It just displays ugly things ;-) Example:

```
Allowed values (List): [ { name: "Yes", value: "-c"} ,{ name: "No", value:"-p"} ]
```

Version: 2.4.2
OS: Centos6

Thank you

**Comment by gschueler** [comment]
JSON data will work only if you use a Remote URL to return the JSON.

It would be useful to enhance options to allow embedded JSON or more configuration.  There is also a feature request to make plugins for option providers, which could be another solution

**Comment by TomGudman** [comment]
Re,

> JSON data will work only if you use a Remote URL to return the JSON.
Yes, I was fairly sure of that but I was in desperate/lucky mode ;-)

> It would be useful to enhance options to allow embedded JSON or more
> configuration. There is also a feature request to make plugins for
> option providers, which could be another solution
I dunno the code but I reckon embedded JSON sounds the best candidate 
for a quick win. Then later on the plugins could superseed it.

Cheers,
Thomas
