### ISSUE TITLE
project wide properties

### ISSUE THREAD

**Issue by richiereynolds** [rundeck/rundeck#1139]
is there some way to define project wide, or even server wide, properties that I can then access in my jobs?

**Comment by gschueler** [comment]
this has actually been requested a number of times before, surprised that there is not an existing enhancement request filed for it.  Definitely would be useful

**Comment by SentinelDoorbell** [comment]
+1

**Comment by ocrespo** [comment]
same here

**Comment by dave-knight** [comment]
+1

**Comment by puremourning** [comment]
+1!

**Comment by ckyma** [comment]
+1

**Comment by mambu** [comment]
+1

**Comment by charlysotelo** [comment]
+1

**Comment by johnpaularthur** [comment]
+1  Please!

**Comment by ahonor** [comment]
This is possible by defining a project global variable. http://rundeck.org/docs/administration/configuration-file-reference.html#global-execution-variables
