### ISSUE TITLE
Jobs getting 'stuck' when using multiple job references

### ISSUE THREAD

**Issue by schicky** [rundeck/rundeck#1140]
After upgrading to 2.4.0 we've had jobs get 'stuck' where there is nothing running on any of the nodes but the job keep showing running. The screen shot shows that, and if you look at the log output there is nothing new. I check the connections to the servers and don't see anything open. Usually the jobs finish up eventually. For example we have a job run for 30 minutes but it finished the last node in 15 minutes so it does 15 minutes of nothing. We recently we had a job run on 8 nodes and finish in a minute but kept running for almost 3 days until we killed it.

![image](https://cloud.githubusercontent.com/assets/7059792/6646482/8bd77ce8-c99b-11e4-990b-c12cae03560d.png)

**Comment by schicky** [comment]
Afrter

**Comment by gschueler** [comment]
was there anything in the service log?

**Comment by schicky** [comment]
I'm using tomcat so I assume the equivalent is catalina.out and I didnt see anything in there. I turned on debug logging and saw some strange things. You can see the gap in time, this is a smaller gap as usually and it seems to increase when the number of nodes I execute on increases. It also lists node failures but all the nodes on the job are reported as successful. 

![image](https://cloud.githubusercontent.com/assets/7059792/6688738/2e646a3c-cc8c-11e4-8fb9-d404ad7a8378.png)

**Comment by gschueler** [comment]
(sorry did not intend to close this issue before)

**Comment by gschueler** [comment]
that debug output saying `Node failures: {(nodename)=[]}` means there were node failures on that node (the list is empty), so that is misleading

**Comment by gschueler** [comment]
can you paste or email your job definitions?  Are there many jobs executing on the server at the same time?  

If you get another "stuck" job, it would be interesting to see the stats from the System Report page, as well as to perform a Thread Dump from that page.

**Comment by schicky** [comment]
I can reproduce this on a busy instance as well as an instance with nothing else running on it. Emailing over the job def. and thread dumps/metrics now.

**Comment by schicky** [comment]
I tried testing with older versions of Rundeck and still had the same issue, it doesn't appear to be a version problem. It looks like we reconfigured our jobs around the same time as the upgrade and it threw me off. It looks like its an issue when using job references to job references. I have many variations of the parent job with different filters so abstracting it makes updating much quicker and I don't repeat myself.

This one gets stuck for a while, time varies by number of nodes
![image](https://cloud.githubusercontent.com/assets/7059792/6901780/8eab9540-d6dd-11e4-9c97-18ec386634c0.png)

This does not
![image](https://cloud.githubusercontent.com/assets/7059792/6901843/04fe3914-d6de-11e4-8a72-841b98a5043a.png)

**Comment by ajxb** [comment]
I'm seeing a similar problem in 2.6.1-1.  I've only spotted this happening for one specific job as it is related to our production releases and monitored during production deployments.

The job is executed in parallel across 20 nodes at a time, 158 nodes in total.  It looks like the following...

![rundeck job](https://cloud.githubusercontent.com/assets/1756536/13279698/88b191a0-dad1-11e5-8bac-530ad2d8018c.png)

Looking at the logs downloaded from the Log Output tab, I can see that the job started on the first node at 07:00:21, and completed at 07:13:44.  A total time of 13:23, however, according to RunDeck the job continued for another 10mins 43s, verified from both the frontend...

![rundeck job time](https://cloud.githubusercontent.com/assets/1756536/13279946/f66c3a8c-dad2-11e5-9d11-1252393f5b15.png)

And the execution log:

`[2016-02-24 07:00:16,376] jmolineaux start [31221:running] Bet.Net jmolineaux/- "Deploy/Deploy - Release"[d1a1623c-13c3-46ff-93dc-41ba950709b1]`
`[2016-02-24 07:24:18,443] jmolineaux finish [31221:succeeded] Bet.Net jmolineaux/- "Deploy/Deploy - Release"[d1a1623c-13c3-46ff-93dc-41ba950709b1]`

Any pointers on where I should begin to help investigate this further for you, as the output is slightly misleading from the frontend and it's causing sign-off for release deployments to be delayed unnecessarily (I think).

**Comment by gschueler** [comment]
can you send the `.rdlog` file for that execution (it contains more information about the progress of each step/node)?

Also, if you are able to, can you take a thread dump during the "lag" period where it is still running, but not appearing to do anything?  Also, if you can duplicate the `.rdlog` at that point in time it may be useful as well

**Comment by ajxb** [comment]
Sorry for the delay, we only execute this particular job once a fortnight.

I've sent you logs and thread dumps, let me know if there is anything else you need.

**Comment by bluikko** [comment]
This is happening to me since update to 2.7.1-1 and seems to be very easily reproduced. Even running a simple ad-hoc Command causes it. Can I share some logs or something to help troubleshoot it?

**Comment by vinillum** [comment]
Has there been any progress on this?

We are seeing this issue as well on RD 2.10.6-1 and our job definition is of similar depth as @schicky reported.

We were running this on 128 nodes with 50 nodes in parallel, no other jobs were running at the same time, and the job had to wait 15 hours before it finished:

```
^2018-02-07T05:02:52Z|stepend||{node=localhost|step=6|stepctx=1@node\=remote.node/6|user=Juozas.Varonenka}|^
^2018-02-07T20:14:11Z|nodeend||{node=remote.node|step=1|stepctx=1|user=remote}|^
```

The actual work that the job was doing took only an hour, before it stalled for 15 hours.

There's nothing in the service.log to indicate an issue.
