### ISSUE TITLE
[Question] Is there a standard workflow for using a VCS with jobs?

### ISSUE THREAD

**Issue by dandunckelman** [rundeck/rundeck#1141]
I recently setup a way store Rundeck job code in Git and upon making changes, the new code is deployed to the server so it can be referenced by a job.

It's not as automated as I'd like, because I have to still create a Rundeck job that references where I have placed the code on the server...which maybe I could automate with the API.  Anyway...

I'm wondering:  is there a standard way of versioning jobs?

Thanks!

**Comment by gschueler** [comment]
vote for more scm integration on this card: https://trello.com/c/96zJS0UR

for now you would have to rely on something like jenkins as an intermediate build server to automate either producing an artifact (rpm/zip) that could be used to deploy to Rundeck, or to directly upload the jobs to rundeck

**Comment by dandunckelman** [comment]
@gschueler thanks.  My implementation included Jenkins, so I'm glad we're in agreement there.
