### ISSUE TITLE
Documentation: Database docs link to 404 Not Found

### ISSUE THREAD

**Issue by dbeckham** [rundeck/rundeck#1148]
In the latest version of the [Administration Guide](http://rundeck.org/docs/administration/index.html) (currently 2.4.2), the [Setting up an RDB Datasource](http://rundeck.org/docs/administration/setting-up-an-rdb-datasource.html) section links to the [Mysql-setup-guide](https://github.com/rundeck/rundeck/wiki/Mysql-setup-guide) wiki page here on Github, which in turn, links back to the [Relational Database](http://rundeck.org/docs/administration/relational-database.html) section in the Rundeck doc, but that page no longer exists and returns a 404 Not Found error.

Links:
+ http://rundeck.org/docs/administration/index.html --> 
+ http://rundeck.org/docs/administration/setting-up-an-rdb-datasource.html --> 
+ https://github.com/rundeck/rundeck/wiki/Mysql-setup-guide --> 
+ http://rundeck.org/docs/administration/relational-database.html *(404 NOT FOUND)*

Also, wouldn't it be better if all RDB related documentation were in the Rundeck docks instead of both the docs and the Github wiki pages?

**Comment by gschueler** [comment]
+1 the info from the wiki should be moved to the docs, and links fixed
