### ISSUE TITLE
Is there documentation on how to set up rundeck as a cluster?

### ISSUE THREAD

**Issue by edibben** [rundeck/rundeck#1152]
I've read http://rundeck.org/docs/administration/scaling-rundeck.html.  I've also found these suggestions:

In rundeck-config.properties add:
rundeck.clusterMode.enabled=true

And in framework.properties add a UUID via uuidgen unique to each instance. Eg:
rundeck.server.uuid=62BBF3F7-78EF-47AB-9DEA-E77C976B912B

I'm attempting to install rundeck in AWS.  I have two EC2 servers, and ELB, logs going to S3 and a MySQL RDS on the back end.  I've got a couple of problems.

Both servers running rundeck but the ELB won't redirect traffic unless only ONE server is running rundeck.  

I know I need to copy the project and ACL information between servers - is there any doco on specifically what needs to be copied?

I'm willing to write down all my findings for the next person to use (if this all isn't documented already).

Thanks

**Comment by edibben** [comment]
When I enabled stickiness within the ELB things started working.  I'll probably put together a document of what I've done and post in on the google group.

**Comment by bugcy013** [comment]
Hi edibben,

can you Please share the document, I am also interested to run rundeck in cluster mode.

Please guide me.

**Comment by remijouannet** [comment]
Hi,
This is one of the first link that appears when you type "rundeck cluster" in google, 
so if someone is interested, I made a simple docker-compose to run a cluster with just two node https://github.com/remijouannet/docker-rundeck-cluster ;)
