### ISSUE TITLE
Workflow broken after job rename

### ISSUE THREAD

**Issue by mathieuchateau** [rundeck/rundeck#1155]
Hello,

imagine this scenario:
-Create two jobs
-Create a workflow to execute both jobs
-Workflow is working
-Rename one job to another name, directly editing job
-Workflow is broken, not finding the job with previous name

Suggestion: use job Guid to survive job rename

**Comment by vladbabii** [comment]
Please make it an option to use either name or uuid. 
I use this renaming feature to replace jobs by changing names without having to edit all dependencies.

**Comment by zychonatic** [comment]
you also have the same problem if you change the path of the job.
there is still a open bug report from 2012: https://github.com/rundeck/rundeck/issues/156

i would also need this, as i want to change my folder structure in rundeck, but i need to touch hundreds of jobs now

**Comment by warmfusion** [comment]
This is a disappointing bug - Jobs all have UUIDs; why on earth would RunDeck link based on anything else...

Anyone got a sensible workaround to ensure multiple jobs remain related?

**Comment by gschueler** [comment]
fix in https://github.com/rundeck/rundeck/pull/3115
