### ISSUE TITLE
debian package startup failing on jessie/unstable with systemd

### ISSUE THREAD

**Issue by pniederlag** [rundeck/rundeck#1156]
I installed rundeck-2.4.2-1-GA.deb on a debian testing/unstable system that is using systemd (replacing sysv-init). In general it provides a working compatibility layer for running sysv-init style scripts. For rundeck this is however failing like so:

```
/etc/init.d/rundeckd status
● rundeckd.service
Loaded: not-found (Reason: No such file or directory)
Active: inactive (dead)
```

**Comment by acasademont** [comment]
This would come really handy. Right now the start/stop process is not very reliable.
