### ISSUE TITLE
2.5 release

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#1157]
Release 2.5

todos:

- [x] update upgrade guide
    - (java 7 required)
- [x] User profile: generate token broken
- [x] mysql-connector-java jar missing
- [x] default project store should use filesystem, not db

**Comment by ahonor** [comment]
Job import requirement for a scheduled job
```
# Failed to add 1 Jobs:
failed:
- reason: 'Invalid Option definition: catalog: Specify a Default Value for Required
    options when the Job is scheduled.

    Validation errors: Invalid Option definition: catalog: Specify a Default Value
    for Required options when the Job is scheduled.'
  job: db/nightly_catalog_rebuild
```

**Comment by ahonor** [comment]
For upgrade guide:

new error when running rd-project create: 
```
com.dtolabs.client.services.CentralDispatcherServerRequestException: Failed to create the project, result code: 409 Conflict
```

**Comment by ahonor** [comment]
Since it's a new feature and user/admins may need to change their project provisioning code, I think the project storage default should be "filesystem" (i.e., rundeck.projectsStorageType=filesystem
). In a subsequent release we can decide to make it "db".

**Comment by gschueler** [comment]
- [ ] `dispatch -s script -- args` fails

**Comment by gschueler** [comment]
- [ ] orchestrator xml export fails if no plugin config

**Comment by gschueler** [comment]
- [ ] script based remote node workflow step plugin fails to work
