### ISSUE TITLE
Feature Request: Node ordering/parallelization Rank Attribute "exclusivity" option

### ISSUE THREAD

**Issue by mgsococo** [rundeck/rundeck#1160]
I want to execute on nodes in order and in parallel (Thread Count > 1), but with an option to not execute nodes with different Rank Order in parallel with the ones that are currently executing.  That is, all nodes with (ascending) Rank Order value 1 must complete the job/step before any nodes with Rank Order value 2 may begin. 

A more thorough example:

Let's say we have a set of systems operating a service that we must occasionally fully stop for maintenance, and then start it up.  It is a basic three-tier application with presentation, API, and database servers which I'll reference as `www`, `api`, and `db`.   We have 5 `www` servers, 10 `api` servers, and 2 `db` servers.

In the case of this application, we have the following tasks that must happen in a specific order: shutdown, code deployments, and startup. The shutdown sequence must happen as follows:  all `www`, followed by `api`, and finally `db`.  Code deployments and startup happen in the opposite order. I'll give examples for the shutdown task, but the same applies to the other tasks.
 
Rundeck supports basic ordering of the nodes via the Rank Attribute setting in the job definition.  However, because in this case we can't begin to shut down any `api` servers before all of the `www` servers are down, nor can we shut down any `db` servers before all of the `api` are down, we end up having to make a choice between the following:

  - We can keep the job simple by limiting the Thread Count to 1 and using the Rank Attribute.  This guarantees the above condition but at the expense of the job being slow.
  - We can make things faster by setting up 4 jobs consisting of a master job and one job for each server type and setting Thread Count to a higher value.  This also guarantees the above condition, but at the expense of being more complex.  It effectively multiplies the number of jobs required for a given task by 4.

What I propose is a simple way to get the best of both worlds where a single job can do the given task, in the proper order, and with maximum parallelization:  Provide a setting in the Job Definition that changes the execution behavior to run up to Thread Count threads per value of the Rank Attribute, each value of Rank Attribute executed exclusively of the others.

For example, let's say we have a Thread Count of 8 and the following server type+Rank Attribute value pairs:

  - `www`, rank 1
  - `api`, rank 2
  - `db`, rank 3

In the case where we have ascending Rank Order behavior, when this new execution option is selected, the execution should proceed as follows:

 1. All 5 `www` begin and complete the step or job (depending on node order/step order selection) before anything else happens.
 2. The first 8 `api` begin executing and as they complete the remaining 2 execute as threads become available.  Nothing else happens until all 10 `api` finish.
 3. Finally, execute on the 2 `db`.

In the case where we have descending Rank Order, it should proceed in the opposite order:

 1. Complete execution of the step or job on the 2 `db`.
 2. Complete execution on the 10 `api` as per above.
 3. Complete execution on the 5 `www`.

I hope I have described this well enough, let me know if I should clarify.

**Comment by gschueler** [comment]
you might look at this pull request, adding a plugin interface to define "orchestrators" for the nodes https://github.com/rundeck/rundeck/pull/826
if I understand your request, I think it would be able to accomplish your task

**Comment by mgsococo** [comment]
It ultimately might be able to do that, but it would appear that I'd have to do this by writing an orchestration plugin, with the logic I stated above, in Java?

**Comment by gschueler** [comment]
yes it would require a new plugin.

**Comment by gschueler** [comment]
see example "tiered rank" orchestrator plugin
