### ISSUE TITLE
rd-jobs clears the libext/cache directory

### ISSUE THREAD

**Issue by new23d** [rundeck/rundeck#1162]
Running the rd-jobs CLI tools clears out the libext/cache directory. Exploded .zip plugins obviously fail to work after that until Rundeck is restarted.

As discussed at https://groups.google.com/forum/#!topic/rundeck-discuss/L1s3OCh0bIc and https://groups.google.com/forum/#!topic/rundeck-discuss/yi5W_qtB16w previously, I can confirm that the behaviour can be reproduced with Rundeck version 2.4.2 running on RHEL 6.5 x86_64 OpenJDK 7 .

**Comment by gschueler** [comment]
believe this is the same as #808

**Comment by new23d** [comment]
We have an rd-jobs wrapper script now, which adjusts the permissions so that the directory may not be emptied. Interesting output from the command then, hoping to give a clue on where to look:

WARN  JarPluginScanner: Could not delete plugin lib dependency directory

**Comment by gschueler** [comment]
@new23d this issue is arising because the CLI tools unfortunately are attempting to load the plugins, which is totally unnecessary.  I fixed #808 by removing that from the CLI tools, it will be fixed in rundeck 2.5

**Comment by new23d** [comment]
Thanks @gschueler . No chance for a version 2.4.3 :) ? I also raised the topic of an LTS version for Rundeck on the mailing list not so long, to no interest sadly. We lack the confidence to adopt x.y.0 versions.

**Comment by gschueler** [comment]
@new23d sorry, perhaps it may happen at some point. For now rundeckpro via simplifyops.com is your best bet for more support

**Comment by gschueler** [comment]
closed as dupe
