### ISSUE TITLE
Rundeck fails to parse YAML with non-specific tags for scalar values

### ISSUE THREAD

**Issue by dbeckham** [rundeck/rundeck#1165]
Rundeck fails to parse YAML job definitions when non-specific node tags are used to indicate scalar values.   According to the YAML spec, these tags should be interpreted as `tag:yaml.org,2002:str`, or a `seq` or `map`, depending on the data represented.  In this case, the data is a quoted string and should be `tag:yaml.org,2002:str`.

Example non-specific tag:

```

---
minute: ! '*'
```

Example error:

```
could not determine a constructor for the tag tag:yaml.org,2002:yaml in "<reader>", line 9, column 12: month: ! '*' ^ 
```

Non-specific node tags are described in the YAML spec, [section 6.9.1](http://yaml.org/spec/1.2/spec.html#id2784064), specifically the "Non-Specific Tags" section.

> If a node has no tag property, it is assigned a non-specific tag that needs to be resolved to a specific one. This non-specific tag is “!” for non-plain scalars and “?” for all other nodes. This is the only case where the node style has any effect on the content information.
> 
> It is possible for the tag property to be explicitly set to the “!” non-specific tag. By convention, this “disables” tag resolution, forcing the node to be interpreted as “tag:yaml.org,2002:seq”, “tag:yaml.org,2002:map”, or “tag:yaml.org,2002:str”, according to its kind. 

**Why are you adding non-specific tags to YAML output?**
Because the Ruby YAML libraries, both built in and Psych do this when YAML is emitted for certain types of data.

**Comment by gschueler** [comment]
we use [snakeyaml](https://code.google.com/p/snakeyaml/) for yaml support, which supports Yaml 1.1.  Is this a Yaml 1.2 specific thing?

**Comment by dbeckham** [comment]
@gschueler No, but it was expanded further in 1.2. In the 1.1 spec, the related section is [8.2 Node Tags](http://yaml.org/spec/1.1/current.html#id900262) and is only related to scalars which would be resolved to `tag:yaml.org,2002:str`. This actually makes it much more simple to implement this fix since you do not have to worry about whether or not the data could be a sequence or map.

**Comment by gschueler** [comment]
ok, from what I gather, the fix is to alter the constructor mapping we use for snakeyaml in the Job YAML parsing.  currently we use the snakeyaml "SafeConstructor" which has basic mappings to java classes, but sounds like we need to extend it a bit
