### ISSUE TITLE
Job option namespace allows for race conditions

### ISSUE THREAD

**Issue by russellballestrini** [rundeck/rundeck#1166]
It seems when multiple jobs share a common parent and both trigger at the same time (scheduled), the options get interleaved during the job execution causing undesirable results.

This seems to happen because they are sharing the same namespace and ultimately becomes a race condition.

**Comment by gschueler** [comment]
this might be the same as #1129

**Comment by gschueler** [comment]
please try the 2.5.0 release and let me know if the issue is solved with #1129

**Comment by russellballestrini** [comment]
My colleague @jbecker42 has upgraded our Rundeck deployments to 2.5.0 release.

I have a 2 jobs that share a common parent scheduled to run tonight and tomorrow morning, I will update this issue with the results!  Thank you for the uber fast response time and communication.

**Comment by russellballestrini** [comment]
YES! Great work!  Confirmed 2.5.0 release fixed multiple defects including this one!
