### ISSUE TITLE
Old install password is cached

### ISSUE THREAD

**Issue by billalbertson** [rundeck/rundeck#1169]
In changing the admin password for rundeck post-install, I've found the following issue:

1.  Edit the framework.properties file, replace framework.server.password = admin with framework.server.password = reallyeasypassword

2.  Either run a service rundeckd stop/start or restart.

3.  Attempt to log in with new password.  This fails with a password error.  Logging in with "admin" as a password always succeeds.

Checking the system configuration setting from the rundeck gui shows:  
framework.server.password: ***** 

This indicates that it is not reading the password from the framework.properties file for an unspecified reason.  This issue persists across multiple service and system restarts, and has no workaround.

**Comment by gschueler** [comment]
the framework.properties defines the login credentials for the CLI tools.

to change the default admin username, modify the realm.properties file.

**Comment by gschueler** [comment]
here is the reference documentation http://rundeck.org/docs/administration/authenticating-users.html#propertyfileloginmodule
