### ISSUE TITLE
rundeck.gui.login.welcomeHtml option is not rendering HTML

### ISSUE THREAD

**Issue by mikeleigh** [rundeck/rundeck#1177]
Adding the following entry in /etc/rundeck/rundeck-config.properties does not render the text as HTML
`rundeck.gui.login.welcomeHtml=Test <b>App</b>`

Instead the text is rendered verbatim

**Comment by gschueler** [comment]
what version of rundeck?

**Comment by mikeleigh** [comment]
This is with version 2.5.0-1from the rpm repository deployed on CentOS 6.5 x86 64 with Java 1.7 update 79.
