### ISSUE TITLE
JettyCombinedLdapLoginModule -> case sensitve

### ISSUE THREAD

**Issue by Zophar78** [rundeck/rundeck#1182]
Hello,
We are now the using the new JettyCombinedLdapLoginModule for authenticating users. It works well except that it is case sensitive when assigning roles. For example:

    com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule required
        ignoreRoles="true"
        storePass="true"
        ....
        reportStatistics="true";

    org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
        debug="true"
        useFirstPass="true"
        file="/etc/rundeck/peb_realm.properties";

The module used for role assignment (JettyRolePropertyFileLoginModule) is case sensitive. If a user enter "MyUserLogin" and his user is set as "myuserlogin" in peb_realm.properties he won't get any role.

**Comment by gschueler** [comment]
sounds like a case insensitive option should be added

**Comment by Zophar78** [comment]
As LDAP is not case sensitive in any case i think you should go without option... case insensitive in any case.

**Comment by gschueler** [comment]
well the role property file might be used in combination with other login modules i suppose.  perhaps case insensitive by default, but option to change it
