### ISSUE TITLE
"Default" for multivalue option fetched from remote URL

### ISSUE THREAD

**Issue by pkr1234** [rundeck/rundeck#1189]
Hi,

I'm aware that you can specify the default as a delimiter separated list for a multi value option. But I do not know this list when it is fetched from a remote URL (json) - it is dynamically populated. 

How do I configure an option with all values as "selected"? I could not find this as it seems to be a basic GUI requirement.

I'm populating the multivalue option from jenkins. It is populating the values fine but all values are "unselected". When jenkins calls this, I want it to automatically select all values. How do I do that?

**Comment by gschueler** [comment]
we could extend the json format perhaps to indicate default values

**Comment by pkr1234** [comment]
Umm no. A better way would be to offer this during option creation. How about providing this under "Allow multiple input values to be chosen."? Something like "Select all by default" and "Select none by default".

**Comment by f0** [comment]
+1

**Comment by richiereynolds** [comment]
+1

**Comment by snahelou** [comment]
+1

**Comment by mcdowellstl** [comment]
+1, was just trying to figure out a way to do this..

**Comment by h4wkmoon** [comment]
+1

**Comment by h4wkmoon** [comment]
IMO, it may be not too difficult to do something like this : 
* in the json format, allow a boolean field named "selected".
```
[
        {"name":"Apache","value":"apache"},
        {"name":"NGinx","value":"nginx", "selected": true},
        {"name":"Tomcat","value":"tomcat"},
        {"name":"JBoss","value":"jboss"},
]
```
* If the option is multi-value, we can have several values "selected". If not only, the first is considered.

I could try to help, if I can find the right place to modify rundeck source code. (Even if I'm not a java dev)

**Comment by schast** [comment]
Hi,

the same problem exists for not multi-valued options.
i would like to force the default selected value for not multi-valued options like this:
```
[
   {"value" : "01_00_00","name" : "01_00_00"},
   {"value" : "01_01_00","name" : "last installed: 01_01_00", "selected": true},
   {"value" : "01_02_00","name" : "01_02_00"}
]
```

**Comment by schast** [comment]
@ahonor can you please add this to milestone 2.7.x?

**Comment by schast** [comment]
@gschueler can you please add this to milestone 2.7.x?

**Comment by 0xAalaoui** [comment]
+1

**Comment by niall-munnelly** [comment]
I have several use-cases where selecting all for an option would be a boon. +1.

**Comment by schast** [comment]
@gschueler can you please add this to milestone 2.8.0?

**Comment by schast** [comment]
hi @gschueler,
first of all: Thank you for your great work!

this is not working for single valued options.
i have a job with the following options:
```
options:
- delimiter: ','
  enforced: true
  multivalued: true
  name: node
  required: true
  value: node01
  values:
  - node01
  - node02
- enforced: true
  name: product_devops-testapp
  required: true
  valuesUrl: http://localhost/cgi-bin/tmp.pl?node=${option.node.value}
```

the url returns the following json objects:
```
URL: http://localhost/cgi-bin/tmp.pl?node=node01
[
    { "value" : "testapp;00_00_01", "name" : "00_00_01" },
    { "value" : "testapp;00_00_02", "name" : "00_00_02" },
    { "value" : "testapp;00_00_03", "name" : "last installed: 00_00_03", "selected" : true }
]

URL: http://localhost/cgi-bin/tmp.pl?node=node02
[
    { "value" : "testapp;00_00_01", "name" : "00_00_01" },
    { "value" : "testapp;00_00_02", "name" : "last installed: 00_00_02", "selected" : true },
    { "value" : "testapp;00_00_03", "name" : "00_00_03" }
]
```

when the first node is selected it works.
![screenshot_2017-04-11_12-46-33](https://cloud.githubusercontent.com/assets/3838857/24906181/fb46b248-1eb6-11e7-9158-9264ede7fe62.png)

when the second node is selected, the previous selected entry is displayed. the selected=true value is ignored.
![screenshot_2017-04-11_12-46-22](https://cloud.githubusercontent.com/assets/3838857/24906190/02ae4aa0-1eb7-11e7-844f-9f4c71d6c254.png)

**Comment by gschueler** [comment]
@schast ok, can you file a new issue?

**Comment by hugospinto** [comment]
Hello @gschueler,

I am experiencing an issue similar to the one reported by @schast (only difference is that my 1st option in the job is single valued and 2nd option is multivalued). The default selected values for the multivalued remote cascade option are loaded correctly at first, but if I change the 1st option, the default selected values for the 2nd option are not processed (the options are updated, but no option with selected=true is selected).

I am using rundeck 2.8.2-1. Thank you for your help.

Hugo
