### ISSUE TITLE
Cascading URL as option provider does not work if the hostname is an option

### ISSUE THREAD

**Issue by pkr1234** [rundeck/rundeck#1191]
To reproduce:

Let's say my URL is http://hostname/path/something.json

If I now use the following URL as remote option provider model, it fails to create the option.

```
${option.jsonurl.value}/${option.path.value}/something.json
```

It does not let me create the option even when jsonurl is available with a valid URL i.e. http://hostname.

Note that ${option.path.value} works if the hostname is not an option

**Comment by shawnchasse** [comment]
I am also seeing similar behavior to this. here's an example of a URL im trying to build:

http://${option.serverName.value}:${option.serverPort.value}${option.contextRoot.value}/static/path/definition

the root of my problem is that colon and the `$`. if i hardcode the colon and hardcode the port then all is well but as soon as i try to parameterize the port the whole thing blows up on me.
