### ISSUE TITLE
run --follow doesn't display the output of a job

### ISSUE THREAD

**Issue by arthurlogilab** [rundeck/rundeck#1194]
From the anvils demo vagrant image, I'm trying to display the output of a "echo hello world" job to the command line and don't seem to be able to : 

```
[root@rundeck anvils]# run -i 8a9f28cf-6395-4633-8948-2f8564ef8aad -p anvils --follow --progress --verbose -l debug
WARN  SimpleHttpConnectionManager: SimpleHttpConnectionManager being used incorrectly.  Be sure that HttpMethod.releaseConnection() is always called and that only one thread and/or method is using this connection manager at a time.
Job execution started:
[10] echo hello world <http://192.168.50.2:4440/execution/follow/10>
###########
[10] execution status: succeeded
```

Is there a configuration that has to be done on the job or is it a bug ?

**Comment by gschueler** [comment]
using `--progress` displays hash-mark progress indicator instead of text output

**Comment by arthurlogilab** [comment]
@gschueler sure, what about --follow ?

**Comment by arthurlogilab** [comment]
oh, I get it now, --progress suppresses the --follow output and the --verbose too. I think this is still a bug. 

What combination of options can be used to know which node sends what output ?

**Comment by ahonor** [comment]
See the `rd` CLI
