### ISSUE TITLE
run command line to execute random commands not just jobs

### ISSUE THREAD

**Issue by arthurlogilab** [rundeck/rundeck#1195]
This is a feature request. The run command doesn't seem to have a way of executing arbitrary commands like we have in the web interface (/project/anvils/command/run) 

It would be nice to be able to do : 

```
[root@rundeck anvils]# run -F '.*' --command 'echo hello world' -p anvils --follow --progress --verbose -l debug 
```

**Comment by gschueler** [comment]
use the `dispatch` tool. `run` executes jobs

**Comment by arthurlogilab** [comment]
Thanks for the tip, sorry for the noisy issue
