### ISSUE TITLE
Notifications on 'recovery' : when the execution succeeded after a failure

### ISSUE THREAD

**Issue by biguphpc** [rundeck/rundeck#1196]
A good way to save time in monitoring the jobs executed by rundeck would be to receive emails when a job recovered from a failure.
1. Adding a notification option 'on recovery' that would send a notification when a job succeeded after a failure
2. Allowing notification plugins to access job execution history, so plugin developers could make custom notifications based on previous executions. i.e. send a notification every N failures instead of every time.

**Comment by papagr** [comment]
On 27.04.2015 20:30, Laurent Marchal wrote:
>
> A good way to save time in monitoring the jobs executed by rundeck 
> would be to receive emails when a job recovered from a failure.
>
>  1. Adding a notification option 'on recovery' that would send a
>     notification when a job succeeded after a failure
>  2. Allowing notification plugins to access job execution history, so
>     plugin developers could make custom notifications based on
>     previous executions. i.e. send a notification every N failures
>     instead of every time.
>

I also agree. This is a missing feature.
