### ISSUE TITLE
exclude-precedence is missing

### ISSUE THREAD

**Issue by alexmfring** [rundeck/rundeck#1200]
Hey after upgrading Rundeck from 2.4 to 2.5.
Seems like <exclude-precedence></exclude-precedence> is missing from the node filters.

**Comment by gschueler** [comment]
ah, someone noticed :)

it is now deprecated, as our node filter mechanism is changing under the hood.

I'm curious, is it a feature that you use? 

If you really need it for now, you can set this in rundeck-config.properties:

```
rundeck.nodefilters.showPrecedenceOption=true
```

**Comment by ahonor** [comment]
Reopen if this is still a concern
