### ISSUE TITLE
quartz.properties no longer exists

### ISSUE THREAD

**Issue by ctgaff** [rundeck/rundeck#1210]
Referencing doc:  http://rundeck.org/docs/jp/administration/13-scaling-rundeck.html

$RDECK_BASE/server/exp/webapp/WEB-INF/classes/quartz.properties 

This file no longer exists in version 2.5.

**Comment by bugcy013** [comment]
Hi Guys,

Have facing have issue with rundeck-launcher version 2.5.1 also. can you please guide me. All workaround is there.

**Comment by gschueler** [comment]
the workaround is to simply create the file manually

**Comment by gschueler** [comment]
alternative, set quartz properties in the rundeck-config.properties file.  You will have to replace the "org.quartz" part with "quartz.props", e.g:

    quartz.props.threadPool.threadCount=20

instead of `org.quarts.threadPool.threadCount`
