### ISSUE TITLE
Project Edit: Simple Configuration Edit silently fails under certain conditions on save

### ISSUE THREAD

**Issue by ctgaff** [rundeck/rundeck#1211]
When editing choices for SSH and SCP, if the same values are not chosen for storage and authentication, they will not not be saved, but there is also no indicator of this occurring other than going back and visually inspecting.

**Comment by gschueler** [comment]
the file copier and node executor use the same property names for things like the key path, so they necessarily must be the same value.  the project edit page should probably show a warning/error if you try to use different values.

**Comment by ahonor** [comment]
The project configuration pages have been heavily renamed in 2.9. Please reopen if this is still a concern in 2.10+
