### ISSUE TITLE
netstat shows rundeck only running on :::4440

### ISSUE THREAD

**Issue by elextro** [rundeck/rundeck#1214]
I install rundeck via rpm then started it using "service rundeckd start", but it doesn't seem like it's listening on my ipv4 address. All i see when I do a netstat -an | grep 4440 is:
tcp6       0      0 :::4440                 :::*                    LISTEN

The rundeck server does not listen on my ipv4 address.

**Comment by gschueler** [comment]
try adding this to the JVM options in /etc/profile:
`-Djava.net.preferIPv4Stack=true`

**Comment by elextro** [comment]
Hey @gschueler.  This worked! I now see my port listening on 0.0.0.0:4440. However, when I log into rundeck with my credentials, it routes me to localhost:4440\menu\home. I'm accesses rundeck through a public IP address so it fails on me. Did I miss a configuration somewhere?

**Comment by gschueler** [comment]
modify your `rundeck-config.properties`, set the `grails.serverURL` to use the IP/hostname you want for your server, then restart rundeck

**Comment by elextro** [comment]
That did it for me. Thanks!

**Comment by abrahamrhoffman** [comment]
Hi - running deb installed rundeck on Ubuntu 14.04.3.

Edited /etc/rundeck/profile to include: "-Djava.net.preferIPv4Stack=true" and of course add the "\" after the last entry. 

However, when I service rundeckd start, rundeck is starting then quickly stopping. I checked the logs, but nothing is being written. Any ideas?

**Comment by abrahamrhoffman** [comment]
I can hit anything else on the server remotely, but I cannot access tcp4 port 4440.

**Comment by buzzing-bee** [comment]
> try adding this to the JVM options in /etc/profile:
> `-Djava.net.preferIPv4Stack=true`

I don't see any "JVM options" in /etc/profile, so how (or where) do I add "-Djava.net.preferIPv4Stack=true"
I'm using Ubuntu 18.04
