### ISSUE TITLE
change default rundeck config file format to groovy

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#122]
rundeck-config.properties is in Java properties format, but sometimes extended configuration (e.g. mail plugin) requires/benefits from using groovy syntax.

the default rundeck-config file should be converted to groovy format and renamed rundeck-config.groovy

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/512)

Original Creator: Greg Schueler

**Comment by ahonor** [comment]
Obsolete and will be superseded by application.yml when Grails upgraded to 3.x.
