### ISSUE TITLE
documentation: update command for creating encrypted/hashed passwords for jetty

### ISSUE THREAD

**Issue by ctgaff** [rundeck/rundeck#1222]
1) The documentation is out of date with the Jetty release.
2) I still cannot get it to work against the latest version.

Red Hat Enterprise Linux Server release 6.6 (Santiago)
java version "1.7.0_80"
Java(TM) SE Runtime Environment (build 1.7.0_80-b15)
Java HotSpot(TM) 64-Bit Server VM (build 24.80-b11, mixed mode)

cd /opt/rundeck
java -cp server/lib/jetty-all-7.6.0.v20120127.jar:server/lib/jetty-all-7.6.0.v20120127.jar org.mortbay.jetty.security.Password jsmith mypass
Error: Could not find or load main class org.mortbay.jetty.security.Password

**Comment by ctgaff** [comment]
2.5.1-SNAPSHOT

**Comment by gschueler** [comment]
Jetty 7 changed to use org.eclipse as the package name everywhere, here is the correct command:

```{.bash}
$ jar tvf server/lib/jetty-all-7.6.0.v20120127.jar  | grep Password
  1574 Fri Jan 27 08:36:52 PST 2012 org/eclipse/jetty/jndi/factories/MailSessionReference$PasswordAuthenticator.class
  4788 Fri Jan 27 08:23:20 PST 2012 org/eclipse/jetty/util/security/Password.class
$ java -cp server/lib/jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass
mypass
OBF:1xfd1zt11uha1ugg1zsp1xfp
MD5:a029d0df84eb5549c641e04a9ef389e5
CRYPT:jsnDAc2Xk4W4o
```

**Comment by gschueler** [comment]
which documentation page were you looking at?  The Authenticating Users page in the admin guide has the correct info: http://rundeck.org/docs/administration/authenticating-users.html#propertyfileloginmodule

**Comment by ctgaff** [comment]
Hello Greg,

Monday, May 11, 2015, 2:29:29 PM, you wrote:


which documentation page were you looking at? The Authenticating Users page in the admin guide has the correct info: http://rundeck.org/docs/administration/authenticating-users.html#propertyfileloginmodule
—
Reply to this email directly or view it on GitHub.

I had the wrong version of the documentation apparently, my bad.

-- 
Best regards,
 Corey                            mailto:ctgaff@gmail.com

**Comment by gschueler** [comment]
ok thanks, i'll close this

**Comment by gentunian** [comment]
@gschueler  I reach here from this link: http://rundeck.org/docs/administration/configuring-ssl.html#securing-passwords

I did the same as @ctgaff  did and finally reached this issue.

Thanks to both!

**Comment by gschueler** [comment]
i see, i will re-open to fix the documentation

**Comment by PeterGarlic** [comment]
There is still a bad link to old password generation on documetation at "Authentication" page:
http://rundeck.org/docs/jp/administration/09-authentication.html

**Comment by gschueler** [comment]
@PeterGarlic the docs/jp is out of date, and needs to be removed see #1838

**Comment by wtlinnertz** [comment]
I get the error:

"Error: Could not find or load main class org.eclipse.jetty.util.security.Password"

when following the documentation on:

http://rundeck.org/docs/administration/authenticating-users.html#propertyfileloginmodule

to execute the command:

java -cp jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass

I am using java version "1.7.0_111"
