### ISSUE TITLE
fileExtension ignored in DestinationFileCopier interface

### ISSUE THREAD

**Issue by fvillain** [rundeck/rundeck#1225]
Hello,

I am writing a Java plugin implementing the DestinationFileCopier interface.
This looks fine until I try to create a Job with a node step "Script file or URL" . The problem is that the fileExtension parameter I explicitly defined in the Job Step definition seems to be ignored or not taken into account.
So, I get a file with a .bat extension on my file...
Which is fine, unless I want to execute some powershell script , and you have to have a .ps1 extension on the script to do so

Let me know if you need more information

**Comment by fvillain** [comment]
This happens on version 2.4.2 by the way

**Comment by dernotte** [comment]
Probably should be linked to #1199, and be fixed/enhanced together

**Comment by fvillain** [comment]
Any news on this ?

**Comment by fvillain** [comment]
Solved in 1.6.3
