### ISSUE TITLE
Support for Preauthenticated Mode and HTTP reverse proxy combo

### ISSUE THREAD

**Issue by dennisklein** [rundeck/rundeck#1229]
Hi,

as far as I can see, the preauthenticated mode only supports AJP at the moment. The packaged rundeck-launcher does currently not spawn an AJP connector. I would love to see support added for the HTTP reverse proxy/preauthenticated mode combo. We need a way to pass in `REMOTE_USER` and `REMOTE_USER_GROUPS` variables via configurable HTTP headers.
=> This way we could make use of existing authentication methods in other http servers without using the deprecated AJP connector in Jetty (deprecated in Jetty 8 and dropped in Jetty 9, https://wiki.eclipse.org/Jetty/Howto/Configure_AJP13).

I am willing to put some time into this myself, but I am not a Java/Jetty/Spring expert. I would appreciate any comment and/or pointers on how to achieve this very much!

Best regards,
Dennis

**Comment by sidewinder12s** [comment]
+1

Also not an expert at all, but I would be looking for this support so we can use the SSO provider we are using. 

Not sure if this would be the right place, but can a REMOTE_MAIL attribute be passed in also?

**Comment by gschueler** [comment]
For the authorization roles this would be simple to add.  For the REMOTE_USER we would need a little more work.

For the roles part of it,  create a new AuthorizationRoleSource, (see [PreauthenticatedAttributeRoleSource.groovy](https://github.com/rundeck/rundeck/blob/development/rundeckapp/src/groovy/org/rundeck/web/infosec/PreauthenticatedAttributeRoleSource.groovy)), and add it to resources.groovy like [this](https://github.com/rundeck/rundeck/blob/development/rundeckapp/grails-app/conf/spring/resources.groovy#L144).

For remote user, the [AuthorizationFilters](https://github.com/rundeck/rundeck/blob/development/rundeckapp/grails-app/conf/rundeck/filters/AuthorizationFilters.groovy) is where username is retrieved from `request.remoteUser`.  Possibly we can add a new way to determine the username, and allow switching from request.remoteUser, to getting it from HTTP header.  However, there are other places in the Rundeck app code where `request.remoteUser` is used to check/get the logged in username.  

Another solution would be to create a new Servlet Filter which would wrap the incoming HttpRequest object, and when the appropriate configuration is set, get the remote user from the HTTP header, and override the `getRemoteUser()` method.

**Comment by blysik** [comment]
In my setup, I'd like to be able to use the X-Forwarded-User header, instead of REMOTE_USER.  Is this issue related to this?

**Comment by gschueler** [comment]
@blysik yes, there's not currently a way to use that.  You'd have to implement a custom servlet filter and enable it in web.xml

**Comment by hany** [comment]
We too are very interested in having the ability to pass user info via HTTP headers. We're using an OAuth proxy in front of all services, and it has the ability to pass in `X-Forwarded-User` header info. It would be great if this can be supported.

**Comment by rdezavalia** [comment]
I will love to see this feature implemented. I'm not able use pam with jaas, having this feature will solve my problem. Not a java coder myself, so I can't help :(

**Comment by a-leung** [comment]
+1

I have https://github.com/bitly/oauth2_proxy working and it can be configured to pass `HTTP_X_FORWARDED_USER`, `HTTP_X_FORWARDED_EMAIL`, `HTTP_X_FORWARDED_FOR` as part of the request header.

If the user id in rundeck can use the `HTTP_X_FORWARDED_EMAIL` as the logged in user. If the email is in a roles file, give the user the defined role (i.e. admin), otherwise, assign a 'default' role to the user.

**Comment by ssbarnea** [comment]
It seems that the is not much interest on fixing these, if RunDeck wants to build a community among the product, we need to see some efforts from the team. If you cannot do a basic setup, you will probably go for one that works.

**Comment by ak0ska** [comment]
+1

Could this issue have an idea card on the Trello board please?

**Comment by gschueler** [comment]
added trello card: https://trello.com/c/XcHUf8zX

**Comment by jegadeshs** [comment]
+1

**Comment by plambert** [comment]
Is there anything left from this issue that isn't supported in 2.6.0?  If not, should this issue be closed?

**Comment by gschueler** [comment]
@plambert closing
