### ISSUE TITLE
Add auth support to URL Resource Model Source configuration

### ISSUE THREAD

**Issue by andham** [rundeck/rundeck#1230]
I'd like to keep the resource model in svn repo, which requires authentication. Currently there is no support for providing credentials for the URL resource model source to use.
Maybe rundeck's key storage could be used for this?

**Comment by gschueler** [comment]
you can use `http://user:password@hostname/path`, for BASIC auth

**Comment by varra4u** [comment]
Yes, I tired with Basic authentication.. It worked well.

**Comment by andham** [comment]
Ok, great! I'll try that.
