### ISSUE TITLE
Build failed with the development build!! 

### ISSUE THREAD

**Issue by varra4u** [rundeck/rundeck#1233]
Hi,
I'm getting the following error while building the project.

[INFO] Rundeck library rundeck-storage-api ............... SUCCESS [8.459s]
[INFO] Rundeck library rundeck-storage-data .............. SUCCESS [2.119s]
[INFO] Rundeck library rundeck-storage-conf .............. SUCCESS [2.568s]
[INFO] Rundeck library rundeck-storage-filesys ........... SUCCESS [2.071s]
[INFO] RunDeck storage project ........................... SUCCESS [0.023s]
[INFO] Rundeck Core ...................................... SUCCESS [1:39.692s]
[INFO] RunDeck Bundled Plugins ........................... SUCCESS [0.013s]
[INFO] RunDeck Stub Plugin ............................... SUCCESS [2.339s]
[INFO] RunDeck Script Plugin ............................. SUCCESS [2.300s]
[INFO] RunDeck LocalExec Node Step Plugin ................ SUCCESS [1.804s]
[INFO] RunDeck CopyFile Step Plugin ...................... SUCCESS [1.522s]
[INFO] RunDeck Jetty Server .............................. SUCCESS [4.001s]
[INFO] RunDeck App ....................................... FAILURE [37.068s]
[INFO] Rundeck Launcher .................................. SKIPPED
[INFO] RunDeck Launcher Parent ........................... SKIPPED
[INFO] RunDeck parent project ............................ SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2:48.671s
[INFO] Finished at: Mon May 11 19:54:25 UTC 2015
[INFO] Final Memory: 70M/168M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.grails:grails-maven-plugin:1.3.7:maven-clean (default) on project rundeck: Unable to start Grails: java.lang.reflect.InvocationTargetException: loader constraint violation: when resolving overridden method "org.apache.tools.ant.helper.ProjectHelper2$RootHandler.setDocumentLocator(Lorg/xml/sax/Locator;)V" the class loader (instance of org/codehaus/groovy/grails/cli/support/GrailsRootLoader) of the current class, org/apache/tools/ant/helper/ProjectHelper2$RootHandler, and its superclass loader (instance of <bootloader>), have different Class objects for the type andler.setDocumentLocator(Lorg/xml/sax/Locator;)V used in the signature -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

PS: 
I tried with linux 64 bit OS and Java 1.7

Please help us to get rid of this problem.

Thanks,
Krishna

**Comment by varra4u** [comment]
Its getting failed with the same error for 2.5.0 version tooo....!!!!! 

please help us...

**Comment by gschueler** [comment]
sorry, the maven build does not work completely at this time.  please use gradle

**Comment by varra4u** [comment]
Oh.... Ok..  Sure ........ I will try and let you guys know the status ... 

Thank you for support.

**Comment by varra4u** [comment]
It is success finally in Linux with Java-1.7 ... Thanks.

**Comment by gschueler** [comment]
i will update the readme, as it still shows maven instructions.  thanks
