### ISSUE TITLE
Schedule single job execution

### ISSUE THREAD

**Issue by andham** [rundeck/rundeck#1235]
Feature request:
It would be great if a job execution could be scheduled for a single execution at a later time. Currently it is possible to schedule for multiple/repeated executions or trigger one immediate execution. What I would like is to, for an existing job definition, schedule it to be executed at one specific time in the future (at 11.00 tomorrow for example).

**Comment by luisfdez** [comment]
@andham , are you asking for something like the following item? If so, it looks like it's in the pipeline :)

https://trello.com/c/cmqu4fdW/44-at-time-scheduling-of-jobs
https://github.com/rundeck/rundeck/issues/150

**Comment by andham** [comment]
Yes, thanks for the heads up! Closing as already reported/requested (#150).
