### ISSUE TITLE
Successful job notification content shows job as Failed

### ISSUE THREAD

**Issue by johnmartel** [rundeck/rundeck#1237]
After a successful job, the email notification sent displays the job as **Failed** in the `/scheduledExecution/showExecutionHead` rendering.

Here is an example:
![rundeck-issue-notification-failed](https://cloud.githubusercontent.com/assets/3068511/7589658/eda144de-f891-11e4-9bdc-2f62fcd8c8fb.jpg)

**Comment by johnmartel** [comment]
I am using Rundeck launcher 2.5.0

**Comment by gschueler** [comment]
dupe of #1221
