### ISSUE TITLE
Failed to kill job: Bad Request

### ISSUE THREAD

**Issue by vinsonzou** [rundeck/rundeck#1240]
question 1：Failed to kill job: Bad Request
question 2：job can't finished.

upgrade to version 2.5.0 from version 2.0.1.
![rundeck_error](https://cloud.githubusercontent.com/assets/2347587/7646186/892c97e8-faf2-11e4-81c7-c015ed250c95.png)

**Comment by gschueler** [comment]
Is there any information in the service log? Could be related to #1179

**Comment by vinsonzou** [comment]
@gschueler thank you.
version 2.5.1 are fixes.
