### ISSUE TITLE
Are there any docker container made for building rundeck?

### ISSUE THREAD

**Issue by SydOps** [rundeck/rundeck#1241]
I am waiting the new release 2.5.1 for some new feature. To save my time, I ask first. 

Are there any docker container made and can be used to build rundeck directly, so I needn't re-write by myself? 

Any hints? If not, maybe I should start working on it.

**Comment by gschueler** [comment]
There look to be a few of them if you search the registry: https://registry.hub.docker.com/search?q=rundeck&searchfield=

**Comment by SydOps** [comment]
Thanks @gschueler 

I have gone through that registry, and one of them is done by myself. :-) But these are docker containers to run rundeck server, not for build environment, such as gradle. 

I need a container to directly build rundeck, generate the rpm/deb file. For example, when the new release is not ready, I can start to use the new feature. 

Wait, you have published the new release, I can see version 2.5.1 is online now, so great job. Thanks again.

But anyway I still hope to have an easy way to build it.  Here is the error I got when I run `cd core; gradlew build`

```
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
:core:compileTestGroovy

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:compileTestGroovy'.
> You must assign a Groovy library to the 'groovy' configuration.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 5 mins 2.197 secs
```

**Comment by SydOps** [comment]
new problem now:

```
OpenJDK 64-Bit Server VM warning: INFO: os::commit_memory(0x00000000d7b68000, 81453056, 0) failed; error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
# Native memory allocation (malloc) failed to allocate 81453056 bytes for committing reserved memory.
# An error report file with more information is saved as:
# /root/rundeck-development/rundeckapp/hs_err_pid326.log
:rundeckapp:grailsWar FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':rundeckapp:grailsWar'.
> Process 'command '/root/rundeck-development/local/grails-2.4.4/bin/grails'' finished with non-zero exit value 1

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 30 mins 12.86 secs
```

Will increase docker container memory and try again.

**Comment by gschueler** [comment]
@SydOps You should use the top-level gradlew script instead. I see the core "gradlew" script is out of date, using an older version of gradle, but it should really be removed anyway.  e.g. from the top-level directory:

`./gradlew build`

or if you just want to build the core lib:

`./gradlew -p core build`

**Comment by SydOps** [comment]
@gschueler,

I did again with increased memory, but still fail, will continuous work on it. 

Curiously how you prepare the build environment, by Vagrant? If you have it, could you share the `Vagrantfile`?

**Comment by gschueler** [comment]
@SydOps I have basic Vagrant config i can upload.  I will create a github repo and post the link.  just testing it now

**Comment by gschueler** [comment]
here is a vagrant build config https://github.com/gschueler/vagrant-rundeck-build

**Comment by SydOps** [comment]
Thanks @gschueler. I saw the new repositiry.

But what's in jenkins-build.sh ? Seems you have the build environment set in Jenkins directly. 

Let me think if I can build an isolate build server without Jenkins via Docker.

**Comment by gschueler** [comment]
jenkins-build.sh is just a simple wrapper around the build, so that it can be reproduced the same as we do it in jenkins.  it doesn't rely on any jenkins environment stuff

**Comment by gschueler** [comment]
link: https://github.com/rundeck/rundeck/blob/development/jenkins-build.sh

**Comment by SydOps** [comment]
it is done, the Dockerfile is at here: https://github.com/BWITS/rundeck-build-Dockerfile
the docker image is `docker pull bwits/rundeck-build`

**Comment by gschueler** [comment]
:+1:
