### ISSUE TITLE
Job retries even though it succeeds

### ISSUE THREAD

**Issue by aramonc** [rundeck/rundeck#1242]
After upgrading to 2.5 from 2.4 & importing the job definitions from 2.4, we noticed that certain jobs that were only meant to run twice a day had been run 6 times or more. Upon reviewing one of the jobs that ran at an unscheduled time & they were retries of jobs that had been marked as successful.

Any ideas as to what this could be?

**Comment by gschueler** [comment]
It could be related to an 2.5.0 issue that causes some jobs to have problems completing ( #1179  ) . Is there any output in the service log?

**Comment by aramonc** [comment]
@gschueler thank you for the quick response. I'll get back to you on Monday.

**Comment by aramonc** [comment]
@gschueler I don't believe it's related to #1179 . I'm not seeing the same SQL errors in the service log. I'm not actually seeing much detail on the service log that might point as to why. For example, the specific job mentioned above, here's the log that I could find for it:

```
INFO  ExecutionUtilService: Execution successful: 400
INFO  ScheduledExecutionService: scheduling immediate job run: TEMP:admin:15:625
WARN  ExecutionJob: ExecutionJob: Execution not found with ID [625], will retry for up to 60 seconds...
INFO  ExecutionService: updated scheduled Execution
INFO  ExecutionJob: ExecutionJob: Execution found with ID [625] retried (1)
```

And here are screenshots from Rundeck that marked the 400 job as successful & retried with the 625 job.

![job_400](https://cloud.githubusercontent.com/assets/2242224/7681093/c535c01c-fd3a-11e4-8e81-1dc5852345cb.png)

![job_625](https://cloud.githubusercontent.com/assets/2242224/7681094/c8adf674-fd3a-11e4-9a96-231c5c65503d.png)

**Comment by gschueler** [comment]
ok, strange behavior for sure.

**Comment by gschueler** [comment]
after a little investigation, I think you should try 2.5.1 release and see if that fixes the issue, I suspect it will.

**Comment by aramonc** [comment]
@gschueler it did. testing with one of our frequently running jobs & no retries were schedules. Thank you!
