### ISSUE TITLE
Job not Completing when starting background process

### ISSUE THREAD

**Issue by rsrinath80** [rundeck/rundeck#1243]
In RunDeck I have job that SSH to linux box and runs a shell script that starts a Coherence server as background process. Even though the Shell script completes the Run deck Job does not complete because the process it started is still running as background process. 
Please let me know How to fix this. 
I have the job to SSH to 12 servers and run the shell script and since the job never completes on first server it never proceeds to other nodes.

**Comment by iceycake** [comment]
Any solution on this?

**Comment by systems-github** [comment]
Any workaround on this ?

**Comment by ahonor** [comment]
Usually, this is due to starting up a daemon like process. You might have to close stdin and also nohup and put the process.

**Comment by zengyuxing007** [comment]
met the same problem, how to fix it???

**Comment by zengyuxing007** [comment]
add " > /dev/null 2>&1 " success fixed this problem

**Comment by AO-StreetArt** [comment]
I was able to get around this by adding the below lines to the top of the shell script being executed:

    exec 0<&-
    exec 1>&-
    exec 2>&-

**Comment by rjgonza** [comment]
Not happy about this, but had to also ad this redirect work around...

**Comment by sandip-stats** [comment]
Will Rundeck consider providing an elegant solution to the issue?

**Comment by rjgonza** [comment]
How come this was closed?

**Comment by ahonor** [comment]
This should be encapsulated by a step plugin designed for managing nohup'ing and managing file descriptors.

**Comment by ahonor** [comment]
Reopening until a plugin is bundled

**Comment by quantumkv** [comment]
Has there been any update on this issue?

**Comment by derekslenk** [comment]
Still having this problem with shell scripts
