### ISSUE TITLE
Specify user to run command

### ISSUE THREAD

**Issue by richiereynolds** [rundeck/rundeck#1248]
On the command line, I think we should be able to specify the user to run a job as so it has the same level of protection as running a job from the GUI. E.g. when running a job from the GUI, if that spawns some jobs using the command line run, we should be able to pass the ${job.user} to the command line jobs.

**Comment by ahonor** [comment]
Take a look at this recent addition  http://rundeck.org/2.5.1/man1/cli-tool-authentication.html

**Comment by richiereynolds** [comment]
Does this work with the usr/bin/run utility? I'm setting a duff password and it still lets me run jobs.

**Comment by richiereynolds** [comment]
it does work with /usr/bin/run.
