### ISSUE TITLE
Include info on notifications sent in job log output

### ISSUE THREAD

**Issue by andham** [rundeck/rundeck#1251]
Currently there is no info on notifications sent in the log output for a job execution. I think that this would be good, at least when debug log level is selected.

**Comment by gschueler** [comment]
do you mean, the notifications for the job should be printed into the log output?

kind of a chicken/egg scenario, since e.g. the mail notification can include the log output

**Comment by gschueler** [comment]
i agree it would be useful to be able to see whether notifications were triggered, and any error messages they might have produced if they were unsuccessful as well.

**Comment by andham** [comment]
I (now) understand the chicken/egg scenario, but from a debugging perspective the info is useful.

Couldn't rundeck just send the output log in the notification as it is at that time, which means that the notification debug info is only available in the web ui?

**Comment by gschueler** [comment]
Possibly.... I'll have to look into maybe keeping the log file "open" until after notifications happen.  IIRC, closing the log file is something that happens prior to "completing" the execution by updating the DB with its status, which happens before invoking the notifications, so the log file may be in a closed state already by the time the notifications happen.  Other related issues: logging uses a plugin system for writing the log output (default to a file), and for uploading it to a storage location after completion.  So it might not be as simple as just appending more output to it after the execution finishes.

Other ideas: have another log for notifications, which can be appended to the "output" log in the api/gui. Or: log the notification events into the DB and also render that as part of the execution view in the GUI, but not have it be considered part of the log file.
