### ISSUE TITLE
jobs never complete in 2.5.1

### ISSUE THREAD

**Issue by ko-christ** [rundeck/rundeck#1253]
Remote node jobs never complete (again) in 2.5.1-1.7.GA (CentOS 7.1, H2 db)
Bug does not exist in version 2.4.2-1.3.GA
#1190
#1179

**Comment by gschueler** [comment]
what if any error messages are in the service log?

**Comment by ko-christ** [comment]
Debug output of a two-step job.
1st step is a successful local "echo hello world" command
2nd step is an unsuccessful remote "echo hello world" command
https://paste.kde.org/pkf7e9czz

**Comment by gschueler** [comment]
can you paste any error messages in the `/var/log/rundeck/service.log` file?

**Comment by ko-christ** [comment]
This is the error message in the /var/log/rundeck/service.log file.

ERROR ExecutionUtilService: Execution failed: 5974: [Workflow result: , step failures: {2=Dispatch failed on 1 nodes: [srv.local: Unknown: java.lang.NullPointerException]}, Node failures: {srv.local=[Unknown: java.lang.NullPointerException]}, flow control: Continue, status: failed]
