### ISSUE TITLE
options removed while creating a job

### ISSUE THREAD

**Issue by mathieuchateau** [rundeck/rundeck#1254]
Hello,

in 2.5.1-1, when creating a new job, and editing both options and inline script, I quickly have options that disapear when clicking on them with this error in red:
no option with name XXX found

never saw that with previous version

**Comment by mathieuchateau** [comment]
in rundeck.log:
ERROR grails.app.controllers.rundeck.controllers.EditOptsController - no option with name XXX found

**Comment by mathieuchateau** [comment]
Ok found out how to reproduce on demand:

-Create a new job.
-Add at least on option
through same browser open a new tab, and start editing another job option
-Go back to the first tab
Click on one option

then you have the error.

I do that because I often got same options between job or script logic.

**Comment by varra4u** [comment]
Hi @Mathieu,
I tried to reproduce this but couldn't.

Just need a clarification on the approach. What do you mean by "Add at least one option"??

Is it complete save or just option save?

-Krishna

**Comment by mathieuchateau** [comment]
Hello,

Adding a variable. I couldn't save at at all.

**Comment by opub** [comment]
I think I am running into this.  My scenario is that I have a job that just calls several other jobs using job reference workflow steps.  Each of those "child" jobs have different options.  So I am trying to add them all to the "parent" job.

1. edit parent job in one tab
2. open another tab (I'm using Chrome 52) and edit one of the child jobs
3. edit an option in the child job so you can copy the name, description, default, etc.
4. create a new option in the parent job that matches the values in step 3 and save it
5. edit the parent workflow step to pass the new option to the child job
6. repeat steps 3-5 with any other options in the current child job and any other child jobs

The newly created options in the parent job will disappear as you do this.  They will also get removed from the workflow job step arguments field.

**Comment by ahonor** [comment]
Can't reproduce
