### ISSUE TITLE
option with default value but not required not provided when scheduled

### ISSUE THREAD

**Issue by mathieuchateau** [rundeck/rundeck#1256]
Hello,

Rundeck version: 2.5.1-1

I have a simple job with 3 options, each with default value. One of them is a password, and the only one not set as required.

If I execute it manually without touching anything it works (password option is provided for execution).

When scheduled, password option is not present/not provided.

Going to the job execution that failed, under title of job, where Rundeck is displaying options, the password one is not there.

If I set it as required, then scheduled execution succeed.

Why do we have a different behavior between a manual execution and scheduled one ?

Is it normal a non required option but with default value is not provided when scheduled ?

We should have same behavior between manual and scheduled execution. As before scheduling we test job manually and this discrepancy is bad.

Regards,
Mathieu Chateau

**Comment by mathieuchateau** [comment]
Another information:
this same job is also part of a workflow, and was working (without option set as required). So only direct schedule of job is impacted I guess.

**Comment by gschueler** [comment]
bug is not reproducible in latest release
