### ISSUE TITLE
Colorized log output broken in 2.5.x

### ISSUE THREAD

**Issue by danifr** [rundeck/rundeck#1258]
I'm using a logging module (https://docs.python.org/2/library/logging.html) for most of the python scripts I have in Rundeck.

Before the update to 2.5, the output messages from this logging system were red(ish) making easy  differentiate them from the normal output (in standard black).

Seems that after the update to 2.5, every message is shown in black.

![screenshot from 2015-05-26 16 24 01](https://cloud.githubusercontent.com/assets/7135482/7814843/1245fa4e-03c5-11e5-8423-3bc94b788edf.png)

I also tested it with 2.5.1 and same result.

Is there a way to have this feature back?

Thanks!

**Comment by gschueler** [comment]
Is this a command run on a remote node, or the local server node?

fyi: that red color is added when output is written to the STDERR file of the process, normally. 

I will see if I can reproduce the issue

**Comment by danifr** [comment]
Hi Greg,

in both cases, the command was run directly on the local server.

> fyi: that red color is added when output is written to the STDERR file of the process, normally.

But in this case INFO should be using the standard STDOUT, right?

Thanks for your help!

**Comment by gschueler** [comment]
I reproduced the behavior, using a local command.

I think there was a change between Ant 1.7 and 1.8, which was upgraded in Rundeck 2.5.  We still use the Ant Exec task for local command execution. It appears that output to STDERR is not behaving the same way as expected from Ant 1.7, so STDERR output is being logged as normal INFO level, for local commands.

I'm not sure how your python logger is setup, but if the original output was red, it would suggest it was coming on STDERR.

I don't know how fancy your logger is, but if you really want colorized output you can also use ANSI color codes

**Comment by ahonor** [comment]
Also consider the new Log Filter plugin to colorize and/or format log output.
