### ISSUE TITLE
When referencing another job, Rundeck should internally use jobs' uuid instead of names

### ISSUE THREAD

**Issue by danifr** [rundeck/rundeck#1259]
We have several jobs that are meant to be called from others.

* 'Job A' calls 'Job B'.
* 'Job C' calls 'Job B'.
* 'Job D' calls 'Job C'.

If for some reason 'Job B's name changes, all the references get screwed and consequently all the jobs start to fail.

To avoid this, I propose start using job's uuid instead of job's name. 
I believe something similar is already being used in the Jobs page.

Thank you so much,
Daniel.

**Comment by mathieuchateau** [comment]
Hello,

yes I also opened an issue about this, which was already a duplicate of a previous one.
2 years it's known, but not yet fixed
https://github.com/rundeck/rundeck/issues/156

**Comment by danifr** [comment]
Hi Mathieu,

let's continue there then. https://github.com/rundeck/rundeck/issues/1155
I'll close this one.
