### ISSUE TITLE
Workflow restart

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#126]
- Issue Type: Feature
- Rundeck version: 1.4.2

---

Issue:

When running a workflow, if a given step fails it should be possible to restart the workflow at that step.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/549)

Original Creator: Jason Martin

**Comment by jamieps** [comment]
+1

**Comment by Raboo** [comment]
+1

**Comment by waihungshum** [comment]
+1

**Comment by mnpoonia** [comment]
Is this feature available now?

**Comment by ak0ska** [comment]
+1

**Comment by wubrg** [comment]
What is the status of this feature request?

**Comment by gschueler** [comment]
This roadmap item is on our Trello board: https://trello.com/c/LPnsZ019 please vote for it there.

In general, the number of votes on trello influences the priority for these items, and [sponsored development](http://simplifyops.com/development.html) does as well.

**Comment by gschueler** [comment]
available in rundeck enterprise https://docs.rundeck.com/docs/manual/execution-lifecycle/job-resume.html#job-resume-plugin-enterprise

**Comment by adityavemuri4567** [comment]
@gschueler do we have this feature in rundeck open source or do we have any similar plugin?
