### ISSUE TITLE
Job ID doesn't match real job UUID

### ISSUE THREAD

**Issue by danifr** [rundeck/rundeck#1265]
Hi,

I deleted a job by mistake. Luckily, this was not a problem because I had a backup.

I (re)imported the job, but after doing it, the Activities page is still showing the message:

``````
```#79XX (Job ID 88 has been deleted)```
``````

The funniest thing is that AKAIK there has never been a Job with ID=88 ...

I modified the exported XML, changing the current uuid value (6d1539af-bf0b-4f8d-8b26-1b8fa9ec3c15) for 88, and then imported it again. After doing this, the log entries get properly linked again...

Where does this job ID 88 come from?
I'm using an external mysql database since a few versions ago (~v 2.1), might this be related?

Daniel.

**Comment by danifr** [comment]
Ok, time passed and now I have a better understanding of what happened here. Also I was able to fix it editing some of the DB entries.

So apart from the uuid, every job has an internal ID starting at 1 and being incremented by one every time a new job is created.

This ID is used in `base_report` (column name jc_job_id) `scheduled_execution` (column name id) `rdoption` (column name scheduled_execution_id) and `execution` (scheduled_execution_id) tables.

To display the log entries per job properly, this column needs to be **the same** value in all the tables mentioned before.

**Comment by danifr** [comment]
I still think there should be a way to revert an accidental job deletion and recreating a job with the same UUID should do the trick.
Thanks.

**Comment by ahonor** [comment]
Please reopen if this is a concern
