### ISSUE TITLE
Allow grouping of nodes

### ISSUE THREAD

**Issue by jedblack** [rundeck/rundeck#1266]
We have a 18 clusters in our environment, of which there is about 10 nodes per cluster.  It would be super helpful if we could somehow group nodes into user defined groups(i.e. check boxes) so that when a job runs, we could select the grouping rather than try to select the 10+ nodes per cluster.

The only way around this is the have jobs duplicated that just target the nodes in a given cluster.  For example; instead of having code-deploy-cluster1, code-deploy-cluster2...etc, we could just have code-deploy and under the 'nodes' section of the job we could select check boxes names 'cluster-1', 'cluster-2' and those would actually map to those 10 nodes with the given cluster.  Perhaps a way to do this is drive it by node 'tags' and allow tags to be check boxed in a job

**Comment by jedblack** [comment]
Is there some other way to accomplish this need?

**Comment by gschueler** [comment]
if you add tags to the nodes, you can select/deselect all nodes with a certain tag from the Job run  page

**Comment by ahonor** [comment]
Please reopen if this remains a concern
