### ISSUE TITLE
rd-jobs is failed after change admin password

### ISSUE THREAD

**Issue by SydOps** [rundeck/rundeck#1268]
With default `/etc/rundeck/realm.properties` (username is admin/admin), `rd-job` runs fine

But after I update the password in `/etc/rundeck/realm.properties`, I got this error.
```
[rundeck@rundeck ~]$ rd-jobs
ERROR BaseFormAuthenticator: Form-based auth failed
Error: Error making server request to http://rundeck.ap-southeast-2.np.core.in.media.telstra.com.au:4440: Unable to authenticate user: admin
```

**Comment by SydOps** [comment]
Got this in `/etc/rundeck/framework.properties`

    framework.server.password = admin

So I need adjust the password as well if the admin password in `/etc/rundeck/realm.properties` is changed.

**Comment by SydOps** [comment]
I can set MD5 or OBF key for admin password in `/etc/rundeck/realm.properties`, but can't set the same in `/etc/rundeck/framework.properties` and have to put plain password in it. 

Is it possible to add the feature to support MD5/OBF in `framework.properties` as well?

**Comment by gschueler** [comment]
the rd-jobs tool needs a plaintext password to log in to the server, so using MD5/OBF in framework.properties would not work.

In 2.5.1 release, we added new support for specifying password in an alternate way for the cli tools, see http://rundeck.org/docs/man1/cli-tool-authentication.html

**Comment by SydOps** [comment]
Thanks, @gschueler
