### ISSUE TITLE
Context variable syntax clarification

### ISSUE THREAD

**Issue by andham** [rundeck/rundeck#1269]
On http://rundeck.org/docs/manual/jobs.html#context-variables it says that the syntax for using a context variable in an inline script is @blabla@. However, when trying this in Rundeck 2.5.1 I only get ${blabla} to work. Is the docs wrong?

In the following example from Rundeck, only the second echo row outputs the value of the variable.
![2015-05-29 12-40-02](https://cloud.githubusercontent.com/assets/142806/7881142/044bed6c-0600-11e5-8320-e0ba32054f5f.png)

**Comment by ahonor** [comment]
@andham for inline scripts the @token@ format is supported. You can use environment variable references but only if the SSH is configured to accept them. See http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html#passing-environment-variables-through-remote-command

**Comment by andham** [comment]
@ahonor Right, that's what the docs says as well. But I can't get that to work in v2.5.1. However, the ${bla} syntax works. Is it a bug?

**Comment by gschueler** [comment]
@andham there is a difference between the *token substitution* and the Bash variable usage.

token substitution happens to the script by rundeck, and uses syntax `@key.name@`, e.g.:

~~~ {.bash}
echo 1: @job.id@
~~~

Shell environment variable works just like any other variable in the shell, and rundeck sets the environment variables to contain a flattened form of "key.name" as `RD_KEY_NAME`, meaning you would use `$RD_KEY_NAME` or `${RD_KEY_NAME}` (bash syntax) to reference it:

~~~ {.bash}
echo 2: ${RD_JOB_ID}
~~~

**Comment by andham** [comment]
Ah, now I get it! Thanks for the clarification!

**Comment by bougyman** [comment]
I'm having a similar problem now where @execution.href@ is not showing up in my inline script. Does the framework config have to be non-default for this to work?
