### ISSUE TITLE
Allow impersonation of a user for testing purposes

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#127]
It's often critical to be able to see rundeck as a particular user, to validate they can perform certain actions and possibly do a dry run (i.e. not actually run the workflow, but simply check that they can accomplish the goal).

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/73)

Original Creator: Noah Campbell

**Comment by Alveel** [comment]
Hi! Has there been any progress on this or nah?

Thank you 👍

**Comment by gschueler** [comment]
Sorry, we don't have this feature, however Rundeck PRO's ACL manager GUI can let you test and verify access control for users and groups.

**Comment by MeenachiSundaram-Velmurugan** [comment]
I'm part of Equinix Org. and we use Rundeck PRO
Impersonate feature is very useful and please open this issue to have this feature.
