### ISSUE TITLE
Make Project specific context variables like project.dir available to executions

### ISSUE THREAD

**Issue by andham** [rundeck/rundeck#1270]
I think it would be great if custom project wide context variables could be configured. It could for example be a common file path that used in several jobs.

Also, I think that it would be good if the project-specific stuff like project.dir also were available as context variables.

**Comment by gschueler** [comment]
see #806 

also, people have requested job-specific variables that can be set

**Comment by mathieuchateau** [comment]
+1

**Comment by andham** [comment]
@gschueler Thanks for the pointer! So this ticket would then be more about making project-specific things like project.dir available as context variables.

**Comment by ntikare** [comment]
+1

**Comment by gschueler** [comment]
Project-global context variables were added in 2.6.8.

I will rename this issue to reflect desire for `project.dir`
