### ISSUE TITLE
Moving RDECK_BASE

### ISSUE THREAD

**Issue by richiereynolds** [rundeck/rundeck#1278]
Hi, I have an RPM installation of 2.4.1 on Redhat. My RDECK_BASE dir is the default /var/lib/rundeck, I'm using a mysql DB.
is it possible for me to change that base dir? I'd like to move it to /data/rundeck (space issues).
1. Is that possible?
2. Will it affect future installs/upgrades using rpm?
3. What would be the steps? I'm guessing:
shutdown RD
cp -r /var/lib/rundeck /data
change the rundeck user's home dir to /data/rundeck
modify /etc/rundeck/profile - the RDECK_BASE setting
start RD
Anything else?

**Comment by varra4u** [comment]
The above one should work but gets failed at upgrades I guess!!

But you can create a soft link between these two right!??

**Comment by richiereynolds** [comment]
sorted
