### ISSUE TITLE
Fix permissions on etc/admin.aclpolicy with the launcher

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#128]
It looks like the launcher is installing the admin.aclpolicy with some odd permissions.  I could understand rw,r,r, but r,r,r seems like a mistake.

@@@
   noahc-mbp:rundeck noahcampbell$ rm -r /tmp/rdl-rpm /tmp/rdl-tools
   override r--r--r--  noahcampbell/wheel for /tmp/rdl-rpm/etc/admin.aclpolicy? y 
   override r--r--r--  noahcampbell/wheel for /tmp/rdl-tools/etc/admin.aclpolicy? y
@@@

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/78)

Original Creator: Noah Campbell

**Comment by ahonor** [comment]
Obsolete
