### ISSUE TITLE
email address validation on job import should not restrict domain TLDs

### ISSUE THREAD

**Issue by fanie-riekert** [rundeck/rundeck#1281]
I have a development environment with isolated DNS, SMTP and IMAP, it uses the name 'core.devint' as the domain name. I have tried to configure rundeck to send email notifications to the email address rundeck@core.devint which fails with the error below. 

$] rd-jobs load -p core.devint -f test_job.yaml -F yaml
Total Jobs Uploaded: 1 jobs                                                       
Failed to add 1 Jobs:                                                           
failed:                                                                           
\- reason: 'Invalid Email address:  rundeck@core.devint                                                                                                       

Validation errors: Invalid Email address: rundeck@core.devint'                
       job: test_job                                                                                                                             
       Error: Failed to load 1 Jobs                                                

Interestingly it works when I use rundeck@core.com as the email address. Also rundeck@core.devint is accepted as the sender's mail address in the rundeck-config.properties file, not sure whether this is an oversight, or not? I would appreciate a setting to relax the strictness of the validation of email address of development environments are allowed.

Thank you
Fanie

**Comment by gschueler** [comment]
+1 i've hit this issue as well

**Comment by fanie-riekert** [comment]
Thanks for fixing the bug.
