### ISSUE TITLE
Feature Request: Filter activity by node

### ISSUE THREAD

**Issue by jasonhensler** [rundeck/rundeck#1290]
I ran into an issue were I wanted to see who had run what on a node from rundeck. I quickly realized there does not appear to be a simple way to do this. I think it would be a great feature to be able to filter activity logs based on the node that the job was executed on.

**Comment by LoovtO** [comment]
For folks waiting for this enhancement, I had the same need and did this way (MySQL DB) for a job list: 
```
select distinct br.report_id
from base_report br
left join execution e on ( br.id = e.id )
where e.succeeded_node_list='NODENAME' or e.failed_node_list='NODENAME';
```
and then filter results (here last 10 executions) with job name found: 
```
select br.id, e.succeeded_node_list, e.failed_node_list, br.date_started, br.date_completed, br.status, br.report_id, br.title
from base_report br
left join execution e on ( br.id = e.id )
where br.report_id like '%JOBNAME%' and e.succeeded_node_list='NODENAME' or e.failed_node_list='NODENAME' order by br.id desc limit 10;
```

**Comment by Slm0n87** [comment]
+1

**Comment by gschueler** [comment]
see https://github.com/rundeck/rundeck/pull/2056
