### ISSUE TITLE
Feature Request: More GUI customization for Plugins

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#1298]
As of RunDeck 2.5.1, the default node step plugins are much more fancy in terms of ability to customize options. For example, the default script plugin:

![script-plugin](https://cloud.githubusercontent.com/assets/592046/8321595/93e4c3da-1a5b-11e5-9171-470ff09b695f.png)

We can see a few features here:
- TextField can have hint text "Enter the commandline arguments for the script"
- Options can have a help icon, hovering on the help icon shows markdown text
- Collapsable "Advanced" section
- Display-only field (Execution Preview) which are dynamically updated when other fields are entered

It'll be nice if custom plugin can support these features as well.

Note: originated from [this discussion](https://groups.google.com/forum/#!topic/rundeck-discuss/7LKVSbvlid8)

**Comment by danifr** [comment]
+1

**Comment by hekaldama** [comment]
+1

**Comment by gschueler** [comment]
FYI: this one: "Collapsable "Advanced" section" is currently possible with the [Property Rendering Options](http://rundeck.org/docs/developer/plugin-development.html#property-rendering-options), it now supports `groupName` and `grouping`.

**Comment by hekaldama** [comment]
That helps me. Thanks!
