### ISSUE TITLE
Proper way to use Github/Gitlab WebHooks

### ISSUE THREAD

**Issue by natlibfi-arlehiko** [rundeck/rundeck#1299]
[Github](https://developer.github.com/webhooks/) and [Gitlab](https://gitlab.com/help/web_hooks/web_hooks.md) services both send event notifications using a HTTP POST requests, without allowing to add information from the event as URL parameters. Rundeck doesn't (AFAIK) have any functionality to parse the POST body and get the relevant information out. This is a problem when a job is supposed to run a build based on a branch or tag the event originated from.

I don't see these services can be supported by Rundeck plugins, so I'm considering to build a simple proxy which takes the webhook requests and calls Rundeck API with correct parameters. Any better ideas?

**Comment by gschueler** [comment]
right now you would need an intermediate service to receive the webhook from github, then convert to an API call to Rundeck.

We have some ideas about enabling that kind of interaction, e.g. allowing a Job to receive a custom HTTP request content and know how to convert the input data to job options, but right now there is no feature in Rundeck to do it

**Comment by danifr** [comment]
Also interested in this. +1

**Comment by jgmchan** [comment]
:+1: 
This would be an awesome feature to have. I'm in a situation where I will probably need to set up a Jenkins server just to kick off a Rundeck deploy job.

**Comment by mumblez** [comment]
+1

**Comment by AndreaGiardini** [comment]
:+1: @ak0ska

**Comment by ak0ska** [comment]
+1

**Comment by ulrith** [comment]
Are there any progress on that?

**Comment by gschueler** [comment]
No movement yet, but this has a lot of +1's, adding it to the Trello roadmap.  Vote for it here and add your use case/comments: https://trello.com/c/0ZbiPo4Q

**Comment by jstop** [comment]
:+1:

**Comment by amaranto** [comment]
+1

**Comment by nbarrientos** [comment]
Yes, please :)

**Comment by leonsr** [comment]
Any solution to this??? Any pluging created for Rundeck to collabore with Github or Gitlab

**Comment by AndrewFarley** [comment]
+1, would be great in Rundeck.  But for everyone above asking what to do, I'm very successfully using API Gateway and Lambda on AWS to not have to host a middleman server myself, and API gateway is flexible enough to receive POSTs of ANY format, parse headers, and handle GET requests with params also/instead.  A million-ish calls a month would still fall under the free tier.  :P  Use it up boys.

**Comment by jairojunior** [comment]
:+1:

**Comment by sok-pomaranczowy** [comment]
+1

**Comment by IngussNeilands** [comment]
+1

**Comment by vincenzo** [comment]
+1

**Comment by happicamper** [comment]
+1

**Comment by abhinandankothari** [comment]
+1

**Comment by valentin2105** [comment]
+1

**Comment by pant03** [comment]
+1

**Comment by grafjo** [comment]
+1

**Comment by mkersh200** [comment]
+1

**Comment by rycummins** [comment]
+1

**Comment by jenciso** [comment]
+1

**Comment by viniciusraupp** [comment]
+1

**Comment by linlinas** [comment]
+1

**Comment by gschueler** [comment]
Reminder: `+1` on github will let us know when an issue is interesting to you, but we use the actual Votes on the Trello board to prioritize these requests. 

Please vote here if you are interested in a feature: https://trello.com/c/0ZbiPo4Q

**Comment by stokkie90** [comment]
+1

**Comment by tmloberon** [comment]
+1

**Comment by zmirc** [comment]
+1

**Comment by amramtamir** [comment]
+1

**Comment by rangsan** [comment]
I'm waiting for this feature be released . :)

**Comment by linlinas** [comment]
+1

**Comment by bahamut45** [comment]
+1 👍

**Comment by darkounet** [comment]
👍 🙃

**Comment by krepkay** [comment]
Hi folks. Is there any simple and elegant solution for triggering rundeck's job by webhooks by now?

**Comment by AndrewFarley** [comment]
@krepkay Mentioned above, this needs a plugin to be made to have it "elegant" but I've setup two clients with Gitlab + Rundeck integration using an API Gateway + Lambda as a middleman.  It's not very difficult (with serverless.com) to get an API Endpoint up, and just a little Node/Python code to "transform" the webhook from one form (gitlab http) to another (rundeck api).  This endpoint can either act as a security gateway, and have an API Key setup for it and store an API key for rundeck in your lambda (or KMS), or you can have it as a more open endpoint and "passthru" the rundeck API key from the incoming request to the outgoing request.  I'm sorry I can't open source my chunk of code that does this, it's one of those things I hope to white-label one day, but I hope this helps!

**Comment by linlinas** [comment]
Hello, has anyone manage to integrate a git webhooks with a rundeck api or is there a proper way to translate a webhook to rundeck api ?

**Comment by devalih** [comment]
+1

**Comment by terwey** [comment]
Hey, I had this issue too and I solved it using an nginx proxy. The steps I took are described here:
https://leethax.org/2019/05/18/rundeck-github-webhook.html

I hope it might save someone else some time.

**Comment by tholok97** [comment]
+1

**Comment by ProTip** [comment]
Webhooks have been introduced in `3.1.1`:
https://docs.rundeck.com/docs/history/#webhooks-incubating
https://docs.rundeck.com/docs/manual/webhooks/run-job.html#usage

Please check that out as a solution and let us know if there are any issues!
