### ISSUE TITLE
Configure Rundeck to run with SSL turned on by default

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#130]
The default configuration for rundeck should be ssl enabled (with a redirect from non ssl connections to make it non-painful if you forget https).

A temporary certificate should be generated that expires in 20 years and an admin page to change the certificate.  This should be part of building a new package.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/91)

Original Creator: Noah Campbell

**Comment by ahonor** [comment]
Leaving this up to the rundeck admin.
