### ISSUE TITLE
Feature Request: API for updating email address of users

### ISSUE THREAD

**Issue by wjimenez5271** [rundeck/rundeck#1301]
This would be useful for environments that are using LDAP where the email address of the user is not picked up by rundeck (my understanding is the LDAP integration does not do that). If there was an API for managing the email address of the user, one could at least work around it by programmatically syncing this information to rundeck.

**Comment by ahonor** [comment]
The User Profile API can set the email address. See http://rundeck.org/docs/api/#modify-user-profile
