### ISSUE TITLE
Job timeouts before actual timeout value

### ISSUE THREAD

**Issue by robizz** [rundeck/rundeck#1302]
Hi,
it seems that rundeck applyies a timeout to jobs that differs from the value configured in the gui.
(Version "2.5.0-1 cafe au lait saddlebrown grain")
For example for this job settings:

![rundeck](https://cloud.githubusercontent.com/assets/1004352/8349549/2c7b2586-1b1e-11e5-9a8c-2bf8158441a9.png)

the rundeck job is killed after 1h (whilst the timeout value if forced to 3h), i'm experiencing the same behaviour in other jobs with the same timing configuration.

the job launches a python AWS backup script that polls the backup completion on AWS (that could last hours)

this is the final value returned in rundeck log:

```bash
Result: 2147483647
Failed: NonZeroResultCode: Result code was 2147483647
Execution failed: 38317: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [rundeck-su1.stormreply.com: NonZeroResultCode: Result code was 2147483647]}, Node failures: {rundeck-su1.stormreply.com=[NonZeroResultCode: Result code was 2147483647]}, flow control: Continue, status: failed]
```

Let me know if you need further details to narrow the search.

Thank you for the amazing job you do on Rundeck!

Roberto

**Comment by eugenegwon** [comment]
I have same problem. 
in my case, I configured 'timeout' to 15 mins, but every job longer than 5mins were timeouted :(
I solved this issue by change framework.ssh.timeout(in /etc/rundeck/framework.properties) to 86400000.
strange thing is, default value '0' means 'wait forever', but seems like it doesn't working...

**Comment by EC123** [comment]
We are suffering the same issue.  Timeout initially set to 4m, changed to nothing, changed to 30d while all the time running on a 5m schedule with only one copy allowed to run at once.  All job runs were timing out at 4m until rundeck was restarted.  Looks like a bug to me.  We are running cafe bonbon cornflowerblue globe

**Comment by dgrine** [comment]
+1

**Comment by ypodo** [comment]
We are suffering the same issue

![image](https://cloud.githubusercontent.com/assets/1647305/12077962/e9751cfe-b205-11e5-9e8e-079f40d883e6.png)

**Comment by gschueler** [comment]
reproduced
