### ISSUE TITLE
Always it shows incorrect password from linux to linux with rundeck-2.5.1

### ISSUE THREAD

**Issue by varra4u** [rundeck/rundeck#1306]
Hi Team,
I am facing an issue when we start Rundeck in Linux Server.

When I try executing a command/job to a Linux node using Password option getting below exception but works very well when I run rundeck server in Windows.

Authentication failure connecting to node: "naren". Password incorrect.
Failed: AuthenticationFailure: Authentication failure connecting to node: "naren". Password incorrect.
Execution failed: 10: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [naren: AuthenticationFailure: Authentication failure connecting to node: "naren". Password incorrect.]}, Node failures: {naren=[AuthenticationFailure: Authentication failure connecting to node: "naren". Password incorrect.]}, flow control: Continue, status: failed]

Hope you guys faced this earlier !!  Am I missing any configuration here ???

PS:
Please find my project.properties file:
# Project ce configuration, generated
# Sat Jun 27 16:40:29 IST 2015

project.name=ce
resources.source.1.config.requireFileExists=false
project.ssh-authentication=privateKey
service.NodeExecutor.default.provider=jsch-ssh
resources.source.1.config.includeServerNode=true
resources.source.1.config.generateFileAutomatically=true
resources.source.1.config.format=resourcexml
resources.source.1.config.file=C:\Users\krishna\Downloads\rundeck\NEW\projects\${project.name}\etc\resources.xml
project.ssh-keypath=C:\Users\krishna\.ssh\id_rsa
service.FileCopier.default.provider=jsch-scp
resources.source.1.type=file

project.ssh-password-storage-path=keys/projects/rundeck.password

Reesources.xml file 

<?xml version="1.0" encoding="UTF-8"?>

<project>
  <node name="INC-adsad" description="Rundeck server node" tags="" hostname="INC-adsd" osArch="amd64" osFamily="windows" osName="Windows 7" osVersion="6.1" username="rareddy"/>

```
<node name="krishna-local-pswd-inline" description="Rundeck node" tags="" hostname="192.168.56.101" osArch="x86_64" osFamily="Linux" osName="Linux" username="krishna" ssh-password-option="option.sshPassword1" ssh-authentication="password"/>

<node name="krishna-linux-test-machine" description="Rundeck node" tags="" hostname="x.x.x.x" osArch="x86_64" osFamily="Linux" osName="Linux" username="username" ssh-password-option="option.sshPassword1" ssh-authentication="password"/>
```

</project>

Thanks,
Krishna

**Comment by varra4u** [comment]
Hi Team,

I found out the issue. Password is getting appended with a new line character, hence it is getting failed.
So I changed the code as given below in com.dtolabs.rundeck.core.tasks.net.SSHTaskBuilder.configureSSHBase(INodeEntry, Project, SSHConnectionInfo, SSHBaseInterface, double, PluginLogger) method in "case password:" block:
sshbase.setPassword(password.trim());

So it started working. But I'm not sure whether it is a bug or due to some miss configuration.

But it is strange since it is happening with only Linux rundeck servers!! 

Guys,
Please validate and let me know.

Thanks,
Krishna

**Comment by varra4u** [comment]
Hi @gschueler,

Thanks for validating, I've changed the source code, it's working after modification, shall I commit the code by pulling a merge request?

Let's know your thoughts.

Regards,
Krishna

**Comment by adalziso** [comment]
I am having the same issue in a recent version of rundeck on Ubuntu. 
I have also considered configuration issues. but I could not identify any update to solve the problem.
Does this problem still exists ?
Is there any work around besides the  code update ?

**Comment by ahonor** [comment]
@adalziso How are the passwords being set in the key store (e.g., via GUI, API, CLI)?

**Comment by adalziso** [comment]
I followed the process from the rundeck doc:
http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html

I have used the job input properties to retrieve the user and password for node  ssh/scp remote execution

This is what I have for my node definition in the json project resource file:

"host1.mam.serviceengage.com": {
    "nodename": "host1.mam.serviceengage.com",
    "hostname": "10.183.68.138",
    "username": "option.usamUser",
   "ssh-authentication": "password",
    "ssh-password-option": "option.usamPassword",
    "description": null,
    "tags": [
      "dc:wdc04",
      "osName:Ubuntu",
      "osFamily:linux",
      "TESTWS"
    ]
  },

These are the input properties for my project:

    <options preserveOrder='true'>
        <option name='NODE' value='host1.mam.serviceengage.com'>
          <description>Node name</description>
        </option>
        <option name='usamUser' value='usamuser' />
        <option name='usamPassword' secure='true' />
      </options>
    </context>

I also tried, for debug purpose, project keystore, without success

Thanks

**Comment by ahonor** [comment]
@adalziso the job definition is showing it's a secure type but i don't see a key path for the option. Eg

    storagePath: keys/path/to/some.password

**Comment by adalziso** [comment]
@Alex
I was not planning to use secure storage for the password. My idea is to retrieve the password value from the job input property.
Do I still need a storage path ?

**Comment by ahonor** [comment]
@adalziso Ah, ok I misunderstood.

**Comment by adalziso** [comment]
@alex
Do you know how can I start debug for those classes ?
I tried to update /etc/rundeck/log4j.properties
log4j.com.dtolabs.rundeck.core=DEBUG, cmd-logger
stop / start rundeck server without success

**Comment by mjeke** [comment]
When can fix this problem?

**Comment by ltamaster** [comment]
Hi @varra4u,

Do you still have this issue? 
I tested on the lastest Rundeck and it worked for me.

Thanks 
Luis

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team

**Comment by varra4u** [comment]
Thanks for the update Luis, haven't checked it lately, will give a try and comeback if it doesn't work.

________________________________
