### ISSUE TITLE
Enable the configuration of excluded cipher suites for SSL

### ISSUE THREAD

**Issue by jeffearl** [rundeck/rundeck#1321]
Firefox 39.0 fails to connect to Rundeck over SSL and reports error code: ssl_error_weak_server_ephemeral_dh_key. Could a configuration item be added to allow "weak" cipher suites to be excluded? Perhaps something like the rundeck.jetty.connector.ssl.excludedProtocols option?

**Comment by gschueler** [comment]
is there a good default list of excluded cipher suites?

**Comment by jeffearl** [comment]
On Java 7 I think you would need to disable all the accepted Diffie Helman ephemeral suites. sslscan showed that DHE-RSA-AES256-SHA, DHE-RSA-AES128-SHA, and EDH-RSA-DES-CBC3-SHA were all accepted on my Rundeck instance. Thanks for addressing this so quickly.

**Comment by gschueler** [comment]
i made it so you can whitelist the values instead of blacklisting if needed
