### ISSUE TITLE
How to configure server or project-wide parameters for a rundeck jobs?

### ISSUE THREAD

**Issue by fukanchik** [rundeck/rundeck#1325]
Hi,
I have a rundeck project which i prefer to deploy into several rundecks. 
There is variability in jobs which i would prefer to configure at server-wide level.
E.g. site-specific service URLs, timeouts, user names.

Is it possible to configure a parameter  in a server which will be available in rundeck jobs?
And if yes, what is the syntax to use it, e.g. similar to @option.name@, may be @server.name@ exists ?

A few jobs in the project have steps which run something via HTTP GET:
wget -qO- "http://host:port/script.cgi?version=@option.binary_version@&hosts=@option.hosts_list@&instance=@option.instance@"
or via python script using xmlrpc:
```
import xmlrpclib
import sys

s = xmlrpclib.ServerProxy('http://<host>:<port>/service')
```

**Comment by ahonor** [comment]
This is now supported in 2.6.8
