### ISSUE TITLE
Active/passive execution mode

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#1327]
Add a toggleable "passive" flag for a Rundeck instance, which will disallow any manual executions and prevent any scheduled executions from occurring.

Should support using a config flag at boot time, as well as API while active to toggle.

- [x] Add internal "Passive" mode for a Rundeck server to disallow any scheduled/triggered executions
- [x] Add config for starting in passive mode (file config)
- [x] Add API for toggling Passive mode
- [x] Add new Access control action requirement for toggling Passive mode
- [x] GUI Disables “run” button for jobs/commands in passive mode
- [x] Add GUI for toggling passive mode

**Comment by ahonor** [comment]
if you go to the Nodes page in Passive mode you still see "Run a command ..." menu item in the Node Actions menu

**Comment by ahonor** [comment]
API endpoint to enable or disable executions with xml response type causes 404 error.
Service log contains: 

     2015-07-24 19:44:32.335:INFO:/:GroovyPagesServlet:  "/WEB-INF/grails-app/views/execution/apiExecutionModeActive.gsp" not found

**Comment by jquick** [comment]
Will there be a way to execute all the jobs that were scheduled to run during passive mode? If not maybe a log or some info of when passive mode was enabled/disabled so they can be manually started via the api would be helpful.

**Comment by ahonor** [comment]
@jquick good idea. a log of all the "skipped" scheduled executions due to disabled schedule or execution mode.
