### ISSUE TITLE
Multivalue option does not trigger remote URL option

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#1340]
Version: 2.6.0-0-SNAPSHOT

Remote URL for Option "Snapshot":
```
http://lsc626:8888/?scriptFile=List_Snapshots&arg0=${option.Node.value}
```

When option "Node" is a single value, things work correctly.

![image](https://cloud.githubusercontent.com/assets/592046/8718424/ec8e73d2-2bd6-11e5-83fe-ae18195488c1.png)

If I change option "Node" to multivalue, Snapshot does not get populated:

![image](https://cloud.githubusercontent.com/assets/592046/8718412/d18eb39e-2bd6-11e5-858e-09ad21f09f7c.png)

**Comment by jabobs** [comment]
![screen shot 2015-08-25 at 8 44 53 am](https://cloud.githubusercontent.com/assets/4109093/9468224/123f0774-4b06-11e5-9450-845d8038cc4e.png)

I am able to adhoc run a job with a remote script with option parameters to the script.  It will complete successfully, but if I schedule the job, the parameter options are never recognized and passed to the script.  Would this be related to this defect?

**Comment by jabobs** [comment]
Turns out I just had to make all fields 'required'.
Related to [1256](https://github.com/rundeck/rundeck/issues/1256)

**Comment by gschueler** [comment]
cannot reproduce
