### ISSUE TITLE
Feature Request:  Allow for User-Specified Files to be Attached in Email Notifications

### ISSUE THREAD

**Issue by mbidewell** [rundeck/rundeck#1348]
As a user, I would like Rundeck to be able to attach user-specified files to email notifications so that log output and other data can be more easily disseminated.

**Comment by henkbl** [comment]
I like this idea, in addition I would like to see the ability to attach these files to the job execution history and have a link to download the file/s after the job has finished.

**Comment by vaidik** [comment]
+1

**Comment by adamunion** [comment]
+1

**Comment by rundeckuser** [comment]
Is this available now? Waiting for it. It is really a great feature to have.

**Comment by fuzaro** [comment]
+1

**Comment by michnmi** [comment]
+1
