### ISSUE TITLE
Need canonical XML serialization for jobs

### ISSUE THREAD

**Issue by ddzed15** [rundeck/rundeck#1350]
Hello,
When running rd-jobs list to get the Project or Job XML, and if the job has "Send Notification" checked, each cli run shows the Notification Model section in a different order.
This make auto version of project/job XML into SCM  ( like Git ) show these as diff's even though nothing else has changed in the file. 
See attached screenshot below.
![voila_capture 2015-07-17_19-40-08_](https://cloud.githubusercontent.com/assets/13194050/8790287/fbb22a84-2f00-11e5-9a78-46c7581bb828.png)

Cheers, Dharmendra

**Comment by gschueler** [comment]
add in 1fea6c0db77022f77e76964d890a1d1fd43c75aa
