### ISSUE TITLE
non rundeck user cannot write to logs when using cli

### ISSUE THREAD

**Issue by memelet** [rundeck/rundeck#1352]
env: debian install

If a user in the rundeck group, but not the rundeck user, executes a cli command the command fails because the user does not have permissions to write to the logs. 

log dir perms:
  drwxr-s--x 2 rundeck adm  4.0K Jul 22 00:25 rundeck

log file perms:
  -rw-rw-r-- 1 rundeck adm    3469 Jul 21 12:18 rundeck.jobs.log

So the question is: Should the dir/files be changed to rundeck:rundeck, or do any users that need to run cli command need to be adm group? I would prefer the former.

**Comment by gschueler** [comment]
I think the problem is that CLI tools are being configured with log4j.properties that is meant for the server...the CLI tools don't need to write to the rundeck.jobs.log, actually should not need logging output as the output should go to console/stdout

**Comment by ahonor** [comment]
The rd-* tools are obsolete. Now use `rd` CLI.
