### ISSUE TITLE
Improve workflow step up/down graphics for usability

### ISSUE THREAD

**Issue by kgeis** [rundeck/rundeck#1360]
When I click on the up/down arrows to rearrange steps in a workflow, nothing happens.

**Comment by gschueler** [comment]
those are not buttons, but a drag handle. you can drag the steps

**Comment by kgeis** [comment]
I see the hover text now, but some other affordance would improve usability. Maybe an icon that looks like a single button, or on clicking, surrounding the row with a dotted blue border.

**Comment by mathieuchateau** [comment]
Hello,

I have this issue when connecting from iPad, there some things that doesn't
work (at least I can't get them to), this one included.


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-07-24 23:42 GMT+02:00 Ken Geis <notifications@github.com>:

**Comment by gschueler** [comment]
:+1: on using glyphicons, the workflow editor GUI code is fairly old and could do with a few touch ups.

And for mobile UI buttons would probably be a better way to do it

**Comment by gschueler** [comment]
fix in #1907
