### ISSUE TITLE
MailNotificationPlugin.groovy does not work with rundeck 2.5.2

### ISSUE THREAD

**Issue by nilroy** [rundeck/rundeck#1361]
I installed rundeck 2.5.2 (from .deb package)on Ubuntu and configured to use MailNotificationPlugin.groovy as one plugin (by placing it within /var/lib/rundeck/libext folder. I had to modify on line as some class paths changed in new rundeck

Before:
 def mbuilder = new org.grails.mail.MailMessageBuilder(null,sender)

After:
def mbuilder = new grails.plugin.mail.MailMessageBuilder(null,sender)

But whenever a job tries sending one email notification I am getting below error in /var/log/rundeck/service.log

Error sending notification email: Could not find matching constructor for: grails.plugin.mail.MailMessageBuilder(null, org.springframework.mail.javamail.JavaMailSenderImpl)

**Comment by gschueler** [comment]
sounds like it needs some fixes
