### ISSUE TITLE
HTML envcoding breaks regexes and Allowed Values URL for

### ISSUE THREAD

**Issue by richiereynolds** [rundeck/rundeck#1364]
Hi, RD 2.4.1

If I add a Remote URL for an allowed values list of e.g.
http://localhost:1080/tprundeck/getResourceNames.jsp?project=${job.project}&type=region
that works fine.
If I then go back in to edit that job it appears as
http://localhost:1080/tprundeck/getResourceNames.jsp?project=${job.project}&amp;amp;type=region
Note the html encoding. If i change, say just the localhost part to a new hostname this then becomes:
http://server:1080/tprundeck/getResourceNames.jsp?project=${job.project}&amp;amp;amp;type=region
Which no longer works.
When these are displayed they should not have the html encoded characters in there.

Option Restriction Regexes have the same issue, if I enter a complex regex, when I go to re-edit the job it appears html encoded which is then impossible to decipher, I want to see the regex I actually entered.
This is made even harder by another issue where if an optional option is not filled in then a literal ${option.optionName} is passed rather then an empty string so regexes have to cope with that. I think that's been raised previously though.

**Comment by gschueler** [comment]
this is fixed already in later versions, check closed issues

**Comment by richiereynolds** [comment]
Thanks, have upgraded to 2.5.2.
