### ISSUE TITLE
unable to change current directory in rundeck job

### ISSUE THREAD

**Issue by SagarMalla** [rundeck/rundeck#1365]
I am trying to change the current working directory in a job execution step. I am running the following commands 
1. pwd 
2. cd java_apps
3. pwd

the output is as follows:
1. /home/sagarmalla/
2. Failed: IOFailure: java.io.IOException: Cannot run program "cd": error=2, No such file or directory
[workflow] finishExecuteNodeStep(localhost): NodeDispatch: IOFailure: java.io.IOException: Cannot run program "cd": error=2, No such file or directory

I need to change path as my application is not taking absolute path to execute. Can you please help me out here?

Regards
Sagar

**Comment by ahonor** [comment]
Hi @SagarMalla 
Each command step is a separate remote execution. You'll have to combine the steps in a script.
