### ISSUE TITLE
cli command: WARN SimpleHttpConnectionManager being used incorrectly

### ISSUE THREAD

**Issue by mathieuchateau** [rundeck/rundeck#1372]
Hello,

When I start a cli command I get each time:

WARN  SimpleHttpConnectionManager: SimpleHttpConnectionManager being used incorrectly.  Be sure that HttpMethod.releaseConnection() is always called and that only one thread and/or method is using this connection manager at a time.

**Comment by richiereynolds** [comment]
me too

**Comment by SentinelDoorbell** [comment]
+1

**Comment by unluddite** [comment]
same

**Comment by ocrespo** [comment]
same here

**Comment by dave-knight** [comment]
+1

**Comment by ckyma** [comment]
+1

**Comment by mambu** [comment]
+1

**Comment by Popsiclestick** [comment]
+1 anymore word on this?

**Comment by andrewpwade** [comment]
+1. It's not even sent to stderr which makes 'dispatch' quite annoying if you're trying to get a list of nodes.

(Java 1.8.0_60 on Ubuntu 14.04)

**Comment by rophy** [comment]
+1 errors / warnings should go to stderr

**Comment by peco8** [comment]
+1

**Comment by gschueler** [comment]
we are planning to replace the old CLI tools, see #1899  you can try the new (work in progress) tools here https://github.com/rundeck/rundeck-cli
