### ISSUE TITLE
Scheduled job Time zone support

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#138]
Is it possible to schedule jobs specifying the time zone? Our
environment consists in different servers supporting different time
zones, and we would like to have a single Rundeck to handle all the
scheduled tasks.

We could try to do the math and schedule all the jobs in local time,
but this would not support different daylight savings settings.

This would be a great feature for large organizations.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/257)

Original Creator: peppla

**Comment by nilroy** [comment]
@gschueler Is this feature available yet? If not do you know when this could be?

**Comment by gschueler** [comment]
@nilroy it is not available yet

added to our roadmap trello board, please vote for it there: https://trello.com/c/W4M03gnm
