### ISSUE TITLE
JS Error: Object doesn't support property or method 'updateError' under IE11

### ISSUE THREAD

**Issue by snebel29** [rundeck/rundeck#1383]
Hi,
When trying to load the execution status for the node within "monitor"/"report" sheet "Follow execution", the browser stay on "loading..." status, "INspecting the element" you see the Javascript Error: Object doesn't support property or method 'updateError' is shown in the JS Console, this error just happens under Windows 8.1 Enterprise and IE11 (11.0.9600.17842), Under Linux - Chrome is working fine

Find here some printScreens:
https://drive.google.com/open?id=0B-0JFS1f1_jTfjFCU1BqaG92TTU2TnVxNzdpMWZ0U0tjc1ZBUjMtSnFDY2pPTEVjOXhYRmc

Steps to reproduce:
Under IE11 create a job, execute it with the option "Follow Execution" then go to the Monitor/Report section and click on the left arrow of the node => to roll out de step details. The error is raised

I could provide further details if need,
Regards

**Comment by gschueler** [comment]
thanks, this looks like a JS bug when a certain Ajax call results in an error.  Is there any log in your browser console about what URL was being requested, or what kind of error response there was from the server?

**Comment by snebel29** [comment]
Hi @gschueler ,
I attached to the previous link an additional screen shot with the last HTTP request just before the error.

https://drive.google.com/open?id=0B-0JFS1f1_jTfjFCU1BqaG92TTU2TnVxNzdpMWZ0U0tjc1ZBUjMtSnFDY2pPTEVjOXhYRmc

Let me know,
Thanks

**Comment by gschueler** [comment]
hmm, doesn't look like an HTTP error was the cause.  Maybe IE 11 is just very strict about JS?  In either case it is a JS bug.
