### ISSUE TITLE
Jobs loaded and executed from XML rather than loaded from XML and executed from DB

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#139]
A surprising discrepancy was found between the on disk XML defined for a job and the one loaded in to the DB for RunDeck.  Ideally the XML could either be polled and loaded in to the DB on a regular interval or parsed every time the job is loaded/executed.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/264)

Original Creator: John Wyles

**Comment by ahonor** [comment]
Use SCM plugin for this use case.
