### ISSUE TITLE
Existing projects are not loaded from db

### ISSUE THREAD

**Issue by aguy** [rundeck/rundeck#1392]
Even with "rundeck.projectsStorageType = db" in rundeck-config.properties and existing projects in the mysql db, a fresh install/upgrade of rundeck does not load them.

here is the config, using 2.5.2-1
```
loglevel.default = "INFO"
rdeck.base = "/var/lib/rundeck"
rss.enabled = "false"
rundeck.security.useHMacRequestTokens = "true"
rundeck.security.apiCookieAccess.enabled = "true"
dataSource {
  dbCreate = "update"
  url = "jdbc:mysql://<db-host>:3306/rundeck?autoReconnect=true"
  driverClassName = ""
  username = "rundeck"
  password = "*****"
  dialect = ""
}
rundeck.projectsStorageType = db
grails.serverURL = "http://<url>"
rundeck.clusterMode.enabled = "true"
rundeck.execution.logs.fileStoragePlugin="org.rundeck.amazon-s3"
```

Then, if I create a project with the same name as an existing project in db, it's still created on filesystem, and all the jobs from the same name project in db, appear.

**Comment by gschueler** [comment]
it looks like you are using groovy format for the config.  If so, make sure to quote "db":

~~~{.groovy}
rundeck.projectsStorageType = 'db'
~~~

**Comment by aguy** [comment]
Great, that's it!
it's weird that projects were still moved in the db with the wrong syntax tho

Thanks
