### ISSUE TITLE
dispatch failed after upgrade to rundeck 2.5.2, and now 2.5.3

### ISSUE THREAD

**Issue by yuhaze** [rundeck/rundeck#1395]
I had posted this to 
https://groups.google.com/forum/#!topic/rundeck-discuss/c1DBcDhTlU0

a few days ago, but think this is a better place, especially since I still can't get jobs to run.

Please help.

Thanks

**Comment by gschueler** [comment]
Is there any error message in the rundeck service log?

**Comment by gschueler** [comment]
I see "Using ssh key storage path: keys/TG/id_rsa" right before the exception is thrown.  Does that key storage path exist in the new install?

**Comment by yuhaze** [comment]
This is the last bit in the service log:SSHFP 2 2 e06a604a492843acf8027f6b7eb048877a9253396689d3fbae144016c3a65783, boardmanufacturer=Intel Corporation, nr_java_found=false, memoryfree_mb=830.07, clientversion=3.7.1, netmask_lo=255.0.0.0, bios_release_date=07/30/2013, apt_package_updates=[“openssh-server”, “lvm2”, “libfuse2”, “openssh-client”, "libdevmapper-event1.02.1", “libuuid1”, “fuse”, “libcurl3-gnutls”], sshrsakey=AAAAB3NzaC1yc2EAAAADAQABAAABAQC6aIx31+lW6sFzegGMwF+9X2kEtAS94x7xtVHAYG/1SmSPzbyYZf/EJi0DDl+AOvD2t9MI5Y/9xYFF8dowwp7g0Jwq9v0150qhafgB1TAftd9Zv5RwAzSDAIp4Oy7/JgJe1fh4rzpYnWKEItwGB1436YrnezdByL3xX5Cv9TjCalKT68yfOCAE6hbhuyJA4ph6o0aeyp1Fm18Uc19ruqLQ1O0gjr7Xi9oxpRw/76JGNidPaRNOoTrVwjx9DNEyw81cpGWcYmyQ8NezVMkj6GjVAy11Usw62QAXbBy7Uk1DB2jyZKluCGscGfo2R71NvbIvzRFoNyrVDtyVcIKZYcnD, boardproductname=440BX Desktop Reference Platform, staging_http_get=curl, architecture=amd64, blockdevice_sda_vendor=VMware, type=Other, netmask=255.255.255.0, is_pe=false, selinux=false, network_lo=127.0.0.0, jenkins_plugins=, timezone=CDT, nr_ruby_found=true, lvm_vg_0=server, lsbdistdescription=Ubuntu 12.04.2 LTS, boardserialnumber=None, ip2=10, ip1=10, ip4=51, ip3=1, physicalprocessorcount=1, hostname=image1.colony10.topgolf.com, operatingsystem=Ubuntu, fqdn=image1.colony10.topgolf.com, sshdsakey=AAAAB3NzaC1kc3MAAACBALtLdV3LBY9SdTxN+4Z8HpdwsdyN62yr8tjs8q7fm2bWrZEdI9dOCYyFOkcFaqx/CcGgN1bwwGZzpkmzQhqmCZ9OyHgxuuQ6YihCAbODOjRYTmZIVDNvHvoT+891CprIyWctLmuDr0uFj9g75E5TzhYUYJmfE+LiiMiXXd+0sLazAAAAFQDnxvPHVPE4QEAKuuZENBzTM8sTRQAAAIBpsymWidZMaft0vECSSubcFG0ecMBqK94P1q9u8N71kurMWuKF/ioJWsSNjl/L7e1Fzg6ylTV/1qaHTYElncydT9Hr2NNMhFP8I5uZueiksgN+FWcvfPJkzTcR/DgYnSAdB6G18NOOvldov5bO6UYuJWA8hNrD1YQUMNeQz4utTAAAAIAOBPtFu1oQ4oipAfzckZZ6kRL/+7UPs+hle7uz3AYJbdh8TcgdUrHVxxNyrmjuncseRWWGMet2Des8LvhsDgpS5771oXxulr17d6Gn7yv9+siWsGYLuK1At1Ch8XdNLAej7DgYLtoL672Ed7N62sin3HsNpgrIJC0PgWnG0rCyxw==, is_virtual=true, lvm_pvs=2, apt_security_updates=0, manufacturer=VMware, Inc., memoryfree=830.07 MB, sshfp_rsa=SSHFP 1 1 37f6c9196b1d33a7911d07efdcd1fd75b6457e32SSHFP 1 2 8ffa713d2dd991d4e4b0f6c3c2e45e27857e8a0171bb1a27b36a59522aca936b, lsbdistcodename=precise, sshfp_ecdsa=SSHFP 3 1 19afef38b177ce373d73a113cf90270a767776daSSHFP 3 2 52c09c8cc3916a20193c213d407eeec640545ffa9ef73e963495a7436628c7e9, macaddress=00:0c:29:d7:27:b6, operatingsystemrelease=12.04, serialnumber=Serial Number VMware-56 4d 5f a8 30 4a 14 de-82 8f 09 f7 4b d7 27 b6, clientnoop=false, operatingsystemmajrelease=12.04, id=root, facterversion=2.2.0, gemslist={“libshadow”=>"1.0.1"}, apt_update_last_success=1439399483, path=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin, lsbdistid=Ubuntu, bios_version=6.00, productname=VMware Virtual Platform, uptime_hours=1748, uptime=72 days, bios_vendor=Phoenix Technologies LTD, hardwareisa=x86_64, processors={“models”=>["Intel(R) Xeon(R) CPU E5-2620 0 @ 2.00GHz"], “count”=>1, “physicalcount”=>1}, concat_basedir=/var/lib/puppet/concat, blockdevice_sda_size=26843545600, iptables_version=1.4.12, puppetversion=3.7.1, apt_has_updates=true, lvm_support=true, lsbmajdistrelease=12.04, uptime_seconds=6294715, rubyversion=1.9.3, ps=ps -ef})DEBUG ConvertUtils: Convert string 'image1.colony10.topgolf.com' to class 'java.lang.String'DEBUG StringConverter: Converting 'String' value 'image1.colony10.topgolf.com' to type 'String'DEBUG ConvertUtils: Convert string 'image1.colony10.topgolf.com' to class 'java.lang.String'DEBUG StringConverter: Converting 'String' value 'image1.colony10.topgolf.com' to type 'String'DEBUG LoggingResourceModelSourceCache: [ResourceModelSource: 1.url (URL Source), project: Topgolf-Operations] Caching model data for (173 nodes)DEBUG HMacSynchronizerTokensHolder: Generate token for /project/Topgolf-Operations/job/show/bdc09e0f-ddef-41d1-9510-910c735ef752: fce529bf-ed0d-4894-bf78-c5af7c2b72c6:[admin, 172.16.0.77]: e2839...DEBUG HMacSynchronizerTokensHolder: Generate token for /project/Topgolf-Operations/job/show/bdc09e0f-ddef-41d1-9510-910c735ef752: dcc84db7-77c3-4871-b8b3-12f4b4efccc3:[admin, 172.16.0.77]: 9230c...DEBUG HMacSynchronizerTokensHolder: Generate token for /project/Topgolf-Operations/job/show/bdc09e0f-ddef-41d1-9510-910c735ef752: 0b58ae2a-8109-4e71-b2bb-4de3232e4ddb:[admin, 172.16.0.77]: 61ea8...DEBUG QuartzSchedulerThread: batch acquisition of 0 triggersDEBUG QuartzSchedulerThread: batch acquisition of 0 triggersDEBUG QuartzSchedulerThread: batch acquisition of 0 triggersDEBUG QuartzSchedulerThread: batch acquisition of 0 triggersDEBUG QuartzSchedulerThread: batch acquisition of 0 triggersDEBUG QuartzSchedulerThread: batch acquisition of 0 triggersDEBUG QuartzSchedulerThread: batch acquisition of 0 triggersDEBUG QuartzSchedulerThread: batch acquisition of 0 triggersDEBUG QuartzSchedulerThread: batch acquisition of 0 triggersDEBUG QuartzSchedulerThread: batch acquisition of 0 triggersOn August 13, 2015 at 11:49 AM Greg Schueler <notifications@github.com> wrote:Is there any error message in the rundeck service log?—Reply to this email directly or view it on GitHub.

**Comment by yuhaze** [comment]
I just ran with password, and i got the same failure[workflow] beginExecuteNodeStep(node2.dallas5.topgolf.com): NodeDispatch: com.dtolabs.rundeck.execution.ExecutionItemFactory$4@894aabe13:08:07  Using ssh password storage path: keys/TG/rundeck_user13:08:07rundeck1.colo1.topgolf.com1. do a w[workflow] finishExecuteNodeStep(node2.dallas5.topgolf.com): NodeDispatch: Unknown: null13:08:07  Failed dispatching to node node2.dallas5.topgolf.com: java.lang.NullPointerException13:08:07  Failed dispatching to node node2.dallas5.topgolf.com: com.dtolabs.rundeck.core.execution.workflow.steps.node.NodeStepException: java.lang.NullPointerException at com.dtolabs.rundeck.core.execution.ExecutionServiceImpl.executeNodeStep(ExecutionServiceImpl.java:158) at com.dtolabs.rundeck.core.execution.dispatch.SequentialNodeDispatcher.dispatch(SequentialNodeDispatcher.java:116) at com.dtolabs.rundeck.cOn August 13, 2015 at 11:55 AM Greg Schueler <notifications@github.com> wrote:I see "Using ssh key storage path: keys/TG/id_rsa" right before the exception is thrown. Does that key storage path exist in the new install?—Reply to this email directly or view it on GitHub.

**Comment by gschueler** [comment]
does the password or key at that storage path exist?

**Comment by yuhaze** [comment]
Yes, I check at the OS level, there are two paths, one under meta, the other under contentI the browser, I removed and reselected the id_rsa key as well as the rundeck_passwordI also tried to use the password setting instead of the key, and the debug output references that right before the exception.I take it that, if I can unselect and reselect the key and / or password in the browser interface, that the application sees it a knows it is there.TonyOn August 13, 2015 at 1:19 PM Greg Schueler <notifications@github.com> wrote:does the password or key at that storage path exist?—Reply to this email directly or view it on GitHub.

**Comment by ahonor** [comment]
Please reopen if this remains an issue
