### ISSUE TITLE
[rundeck.gui.login.welcomeHtml] Style tags not working

### ISSUE THREAD

**Issue by pfweberp** [rundeck/rundeck#1396]
Hey,

It seems that the rundeck.gui.login.welcomeHtml property doesn't work as I expected.
The HTML content is only showed partially. HTML-tags like center / align / style aren't working - the content stays on the left side.

I've tried following variations:

```
<p style="text-align:center"><img src="http://localhost/logo.png" align="center"><br />
<b><a href="http://localhost/filename.html">View last deployments</a></b><br />
For questions please contact <a href="mailto:xy@z.com">xy@z.com</a><br /></p>
```

```
<img src="http://localhost/logo.png" align="center"><br />
<center><b><a href="http://localhost/filename.html">View last deployments</a></b><br />
For questions please contact <a href="mailto:xy@z.com">xy@z.com</a><br /></center>
```

```
<div align="center"><img src="http://localhost/logo.png" align="center"><br />
<b><a href="http://localhost/filename.html">View last deployments</a></b><br />
For questions please contact <a href="mailto:xy@z.com">xy@z.com</a><br /></div>
```

In all cases the content is shown correctly, but without respecting the style / div / align tags for content-centering.

Rundeck version: 2.5.3-1

Can you please have a look?

**Comment by gschueler** [comment]
the HTML is sanitized allow only a certain set of tags and attributes, and style/align is not allowed.  However, you can use `class` attribute.  We use bootstrap for the basis of the CSS, so try using the CSS classes such as the text alignment classes: http://getbootstrap.com/css/#type-alignment

**Comment by pfweberp** [comment]
Thanks for your quick feedback - I will try on Monday and let you know :)

**Comment by pfweberp** [comment]
Hey,

Thanks again - 
it's working perfectly with the class attribute.
