### ISSUE TITLE
postgresql support is not documented

### ISSUE THREAD

**Issue by ssbarnea** [rundeck/rundeck#1405]
PostreSQL is the defacto DB used by most open source apps and I was surprised to find out that it's support (or lack of) is not documented in http://rundeck.org/docs/administration/setting-up-an-rdb-datasource.html

I was able to get get rundeck to create the database tables using the settings below but it seems that all tables are also empty, which makes me think that the configuration was not fully completed.

```
dataSource.dbCreate = update
dataSource.url = jdbc:postgresql://db.example.com/rundeck
dataSource.username=rundeck
dataSource.password=secret
```

**Comment by ahonor** [comment]
You might have to specify the driver class name.

    dataSource.driverClassName = org.postgresql.Driver

**Comment by ssbarnea** [comment]
I would have thinked about about the same, but to my surprise it it did work without specifying the driverClassName, still this was needed:
```
rundeck.projectsStorageType=db
```
Any I found another documentation page at http://rundeck.org/docs/jp/administration/07-relational-database.html that is saying something about adding
```
rundeck.v14.rdbsupport=true
```
For me this option looks quite weird to me, looks more like an option to test some experimental feature. Didn't try it yet as now is kinda working... but extremely slow. see https://groups.google.com/forum/#!topic/rundeck-discuss/2zc5HbBTIKY

**Comment by CodingMinds** [comment]
The following configuration seems to work well with rundeck 2.5.3-1 and PostgreSQL 9.1:
```
# Use PostgreSQL as data source
dataSource.driverClassName = org.postgresql.Driver
dataSource.dbCreate = update
dataSource.url = jdbc:postgresql://localhost/rundeck
dataSource.username = rundeck
dataSource.password = secret

# Enables DB for Project configuration storage
rundeck.projectsStorageType=db

# Enable DB for Key Storage
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=keys
```
