### ISSUE TITLE
Plugin for Ansible?

### ISSUE THREAD

**Issue by ashish235** [rundeck/rundeck#1408]
This is really a desirable feature to have. If rundeck can support Ansible out-of-the-box, the world'd be a much better place.

**Comment by azimut** [comment]
+1

**Comment by dapangmao** [comment]
+1

**Comment by ghkem** [comment]
+1

**Comment by ktosiek** [comment]
How would you imagine such integration?
Those are the parts I can imagine from the top of my head:
* Resource Model Source - just load data from a path, shouldn't take long at all
* Node Executor - run an Ansible module
* File Copier - just call Ansible's copy module
* Workflow Step - run a playbook, restricted to current nodes (by node names?)
  Can a workflow step fail only some nodes?

This kind of integration would let users keep the connection configurations in Ansible (and use Ansible's connection plugins), with RunDeck being mostly a GUI/Audit trail.

**Comment by ahonor** [comment]
@ktosiek I think that's a great run down of what is needed. For the node executor, will the goal to be to execute command strings via Ansible?

**Comment by ktosiek** [comment]
Yes, basically calling the Ansible's command (or shell?) module. Or even any module, I'm not sure how elastic that plugin type is.

**Comment by ahonor** [comment]
@ktosiek I can help with this as I've already done a little experimentation with an ansible-playbook workflow step plugin. I would recommend our creating a project for this in a separate repo. I can create something here for us to collaborate: https://github.com/rundeck-plugins/ansible

**Comment by ktosiek** [comment]
That would be great. I'm not well versed in Java (actually, I only kind of read it), so it would really help me if someone set up the scaffolding.
I think the Resource Model Source should be written in Python - this way we can directly access Ansible API, and I've already written a simple one at work in 10 lines. For other parts, I think just calling the ansible executable is good enough.

**Comment by ashish235** [comment]
Some of the features which I would love to see is. 
Rundeck being able to use Ansible's inventory file. If Rundeck could also modify this file based on my rundeck workflow it would be better.
Dynamically read various variable file from Ansible and populate them in Rundeck.
If Rundeck could understand the Ansible roles and use them in an intuitive way.   

I 'm not really a developer but kind of a devops guy, so can't help you guys implementing these features but I can suggest other lot of useful features. 

Cheers!

**Comment by ktosiek** [comment]
Hmm, writing to the inventory would be pretty unusual - is this something that RunDeck supports for other resources? And having RD know too much about the inventory would stop us from using Ansible API for it (which already supports inventory directories, dynamic inventories and vars_plugins behind the scenes).

Now, this brings another question - should we use RunDeck resources only to filter Ansible inventory, or should we generate the inventory from them? I can see arguments for both, and for example Vagrant provisioner allows both styles.

**Comment by ahonor** [comment]
@ktosiek and @ashish235 I created a repository here: https://github.com/rundeck-plugins/ansible

**Comment by ashish235** [comment]
@ahonor, great and thanks.

**Comment by ajmali2** [comment]
Ansible supports dynamic inventories .. i did this once for a company i worked with .. created a mysql database with all the nodes inside .. created group nodes eg GROUP_Development, which had custom tags of the nodes that belonged to the group. When running a playbook inside rundeck you could run it against individual hosts .. or again a group .. the dynamic inventory query would be able to pull that info across.

If anyone is interested I could see if i still have the scripts, or whip one up.

Regards
AJ

**Comment by rilindo** [comment]
Hey guys, somebody whipped up a third-party plugin for Ansible:

https://github.com/Batix/rundeck-ansible-plugin

It is newish, but the author has been responsive to changes and suggestions.

**Comment by ozsk** [comment]
+1

**Comment by ahonor** [comment]
Closing this issue. Please follow the rundeck-ansible-plugin mentioned above.
