### ISSUE TITLE
Feature request: Capture the entire Log o/p in a variable. 

### ISSUE THREAD

**Issue by ashish235** [rundeck/rundeck#1413]
For error handling purpose we only have a few options as out disposal like the error code, error message. This satisfies most of the requirement but in some more complex cases I have to read or grep certain pattern from the log o/p, which doesn't seem to be possible right now.

Please let me know if this would be feasible. 
## 

Ashish

**Comment by gschueler** [comment]
we do have plans for capturing step output to be used in later steps, see #116 

If you like you can add your use-case there, and [vote for this issue on trello](https://trello.com/c/oU8OjZoH)

**Comment by ashish235** [comment]
Great thanks, @gschueler . Will put and use case.

Cheers!

**Comment by ahonor** [comment]
Log filter plugins should enable you to capture/parse output.
