### ISSUE TITLE
Feature request: Job parallel execution limit & queuing

### ISSUE THREAD

**Issue by BlairPaine** [rundeck/rundeck#1426]
Allow a parallel execution limit to be defined at the job level (i.e. separate limit configured for each job) even when the job is executed locally.  This would allow certain jobs to be limited less than the Quartz job threadCount.  This would be in addition to the node level thread limit.

Executions for that specific job are queued up when the limit is reached.

Details:
https://groups.google.com/forum/#!topic/rundeck-discuss/RSGha9ZtBYA

Many thanks,
Blair.

**Comment by ahonor** [comment]
@blairpaine perhaps this is an additional setting to the "Multiple Executions" boolean (ie, "Allow this Job to be executed more than one time simultaneously? " in the job edit page).

**Comment by blairpaine** [comment]
@ahonor yes when "Multiple Executions?" is set to true there could be an additional field displayed to add an optional execution limit.  For example, if I added 50 to the execution limit then a maximum of 50 instances of that specific job can run at any one time.   Beyond the limit the instances would be queued up until executing instances complete/fail/timeout etc.

**Comment by shyam** [comment]
+1 to this feature request. 

A variant of this is - disabling "Multiple Executions?" should atleast queue the job, rather than sending error "Server responded with code 409, message: Execution had a conflict"

**Comment by bmccraw86** [comment]
+1 for this.  Either fix referenced here would be a big help.  We have external systems kicking off job executions through the API and without a queue, the API call fails.  Not desirable.

**Comment by minhuber** [comment]
+1

**Comment by jabobs** [comment]
+1

**Comment by metacoma** [comment]
+1

**Comment by ARentz07** [comment]
I'd say what would be most useful to most users would be the queueing, if not the limit on parallelism.

+1

**Comment by cgrigor** [comment]
+1

**Comment by straux** [comment]
+1

**Comment by ngrunwald** [comment]
+1

**Comment by Pinguiculus** [comment]
+1

**Comment by dopesong** [comment]
+1

**Comment by radius314** [comment]
+1

**Comment by MoradT** [comment]
+1

**Comment by maveco69** [comment]
+1

**Comment by kincl** [comment]
+1

**Comment by charlesmims** [comment]
+1

**Comment by stbka** [comment]
+1

**Comment by Axiioss** [comment]
+1

**Comment by davkoch** [comment]
+1

**Comment by bsloan** [comment]
+1

**Comment by padraiglennon** [comment]
+1

**Comment by gufertum** [comment]
+1

**Comment by alv000h** [comment]
+1

**Comment by dandunckelman** [comment]
> There haven't been much activity here. This is stale. Is it still relevant? This is a friendly reminder to please resolve it. :-)

Easier said than done

**Comment by gschueler** [comment]
related trello card, https://trello.com/c/MijkQiFP

**Comment by gschueler** [comment]
#1047

**Comment by vivekrodge** [comment]
Is it implemented ?

**Comment by ARentz07** [comment]
Apparently not, at least [based on this comment](https://github.com/rundeck/rundeck/issues/1047#issuecomment-501790116).
