### ISSUE TITLE
Multivalue delimiter not working?

### ISSUE THREAD

**Issue by snebel29** [rundeck/rundeck#1427]
Hi,
When trying to use a delimiter different than "," with "Enforce from Allowed Values" the string is not splitted into individual values so is not possible to choose different values by selecting their "checkboxes", I'm using 2.5.2-1 version, find here a job definition example.

<pre lang="yaml">
<code>
- id: 391b2658-ea32-47a6-a0c4-8177fe8a230c
  project: 'test'
  loglevel: INFO
  sequence:
    keepgoing: false
    strategy: node-first
    commands:
    - exec: echo $hostname
  description: test multivalue
  name: test_environment
  uuid: 391b2658-ea32-47a6-a0c4-8177fe8a230c
  options:
    multivalue:
      enforced: true
      required: true
      values:
      - 1|2|3
      multivalued: true
      delimiter: '|'
</pre>
</code>

**Comment by plambert** [comment]
Is it valid YAML syntax to have a pipe in a bare string?

Try with:

...
values:
- '1|2|3'
...

And see if that works?

**Comment by snebel29** [comment]
Good point, that yaml definition was downloaded from rundeck gui hence
created using the gui too, I have no access rigth now to any rd instance..
ill test it by uploading the manually quoted yaml definition, specially on
last 2.6.1 version to see and let you know but wouldn't be surprise if that
finally works ;-)

**Comment by snebel29** [comment]
Hi,
I just realized what was the problem, It was my mistake because I was using pipes "|" to delimite within the allowed values when this is explicitly specified "Comma separated list" so there was just one value allowed "1|2|3" hence no need for check boxes, looks like Multi-valued and enforce form allowed values shouldn't be used together.. at least there is no need for. 

I mean if you have a list of predefined values check boxes will be shown and no need for multivalue and the other way around

About quoting or not strings on the YAML definitions,, reading documentation over there looks like special characters should be escaped or enclosed between quotes, however those rundeck yaml seems working fine, I didn't dig more on that..

Regards
