### ISSUE TITLE
RPM Repository No Longer Supporting EL5

### ISSUE THREAD

**Issue by fixed4life** [rundeck/rundeck#1434]
Upgrading today from 2.5.1.1 to 2.5.3-1.10.GA yielded the following error:
error: rundeck-2.5.3-1.10.GA: Header V4 RSA/SHA1 signature: BAD, key ID e2d1065b

It appears that the repository no longer contains V3 signatures required fro EL5.  This seems to be inherent in repositories created with EL6 unless specifically created with the option to use/support v3.  There is no way for EL5 servers to use the repo or packages at all unless this is resolved.

**Comment by gschueler** [comment]
we use bintray.com for hosting the rpm packages, maybe we should open an issue with them

**Comment by dfsis** [comment]
+1

pm -Uvh http://repo.rundeck.org/latest.rpm
Retrieving http://repo.rundeck.org/latest.rpm
error: /var/tmp/rpm-xfer.g1yHmn: Header V4 RSA/SHA1 signature: BAD, key ID e2d1065b
error: /var/tmp/rpm-xfer.g1yHmn cannot be installed

**Comment by gentunian** [comment]
Same here with RHEL5

**Comment by gentunian** [comment]
This may help 

http://unix.stackexchange.com/questions/27063/centos-yum-repository-bad-header-v4-rsa-sha1-signature

**Comment by gschueler** [comment]
thanks, it looks like adding `--force-v3-sigs` to the rpm sign macro will produce a v3 rsa signature. i can do that for subsequent releases.

**Comment by fixed4life** [comment]
Will this be resolved for 2.6.1-1.12.GA which is currently in the repos, or only future releases?

**Comment by gschueler** [comment]
I can resign the current release

**Comment by fixed4life** [comment]
Excellent, please let us know when you have a chance to do so.

**Comment by gschueler** [comment]
i uploaded the files to bintray, please give them a try

**Comment by gentunian** [comment]
Mmm.. I've tried directly without luck:

```
[root@scripts rundeck-latest]# rpm -Uvh http://repo.rundeck.org/latest.rpm
Retrieving http://repo.rundeck.org/latest.rpm
error: /var/tmp/rpm-xfer.1uLwHf: Header V4 RSA/SHA1 signature: BAD, key ID e2d1065b
error: /var/tmp/rpm-xfer.1uLwHf cannot be installed
```

Maybe there's a need to sign the repo `.rpm` too?. I've manually created the repo:

```
[rundeck-release-bintray]
name=Rundeck - Release
baseurl=https://dl.bintray.com/rundeck/rundeck-rpm
gpgkey=http://rundeck.org/keys/BUILD-GPG-KEY-Rundeck.org.key
gpgcheck=1
enabled=1
```
and try to install it: `yum install rundeck` without luck:

```
Downloading Packages:
(1/2): rundeck-config-2.6.1-1.12.GA.noarch.rpm                                                 | 9.0 kB     00:00     
(2/2): rundeck-2.6.1-1.12.GA.noarch.rpm                                                        |  94 MB     07:45     
----------------------------------------------------------------------------------------------------------------------
Total                                                                                 206 kB/s |  94 MB     07:48     
warning: rpmts_HdrFromFdno: Header V3 RSA/SHA1 signature: NOKEY, key ID e2d1065b
rundeck-release-bintray/gpgkey                                                                 | 3.4 kB     00:00     
Importing GPG key 0xE2D1065B "Rundeck Build (automated builds) <build@rundeck.org>" from http://rundeck.org/keys/BUILD-GPG-KEY-Rundeck.org.key
Is this ok [y/N]: y
error: rpmts_HdrFromFdno: Header V3 RSA/SHA1 signature: BAD, key ID e2d1065b


Problem opening package rundeck-2.6.1-1.12.GA.noarch.rpm
```

**Comment by gschueler** [comment]
strange, i've resigned the rpms with v3 sigs.  `rpm --checksig` verifies on centos 6, but not on rhel 5. (try <http://repo.rundeck.org/latest-test.rpm> )

I wonder if it's a gpg issue.

i'm signing the rpms via jenkins rpm-sign plugin, passing these parameters, culled from <http://adminotes.blogspot.fr/2011/12/centos-6-rpm-sign-problem-v4-signatures.html> :

    --define "__gpg_sign_cmd %{__gpg} gpg --force-v3-sigs --digest-algo=sha1 --batch --no-verbose --no-armor --passphrase-fd 3 --no-secmem-warning -u \\\"%{_gpg_name}\\\" -sbo %{__signature_filename} %{__plaintext_filename}"

On centos 6:

~~~
[vagrant@localhost ~]$ rpm -vv --checksig rundeck-2.6.1-1.12.GA.noarch.rpm 
D: loading keyring from pubkeys in /var/lib/rpm/pubkeys/*.key
D: couldn't find any keys in /var/lib/rpm/pubkeys/*.key
D: loading keyring from rpmdb
D: opening  db index       /var/lib/rpm/Packages rdonly mode=0x0
D: locked   db index       /var/lib/rpm/Packages
D: opening  db index       /var/lib/rpm/Name rdonly mode=0x0
D:  read h#     218 Header sanity check: OK
D: added key gpg-pubkey-c105b9de-4e0fd3a3 to keyring
D:  read h#     282 Header sanity check: OK
D: added key gpg-pubkey-e2d1065b-5570a328 to keyring
D: Using legacy gpg-pubkey(s) from rpmdb
D: Expected size:     98699594 = lead(96)+sigs(1284)+pad(4)+data(98698210)
D:   Actual size:     98699594
rundeck-2.6.1-1.12.GA.noarch.rpm:
    Header V3 RSA/SHA1 Signature, key ID e2d1065b: OK
    Header SHA1 digest: OK (3de7e2463ed969c41879c66ff455598d5aadf4bd)
    V3 RSA/SHA1 Signature, key ID e2d1065b: OK
    MD5 digest: OK (f95d6bf6d176408d6acb9a7f9aebf64b)
D: closed   db index       /var/lib/rpm/Name
D: closed   db index       /var/lib/rpm/Packages
~~~

on rhel5:

~~~
[root@ip-... ~]# rpm -vv --checksig rundeck-2.6.1-1.12.GA.noarch.rpm 
D: Expected size:     98699594 = lead(96)+sigs(1284)+pad(4)+data(98698210)
D:   Actual size:     98699594
D: opening  db environment /var/lib/rpm/Packages joinenv
D: opening  db index       /var/lib/rpm/Packages rdonly mode=0x0
D: locked   db index       /var/lib/rpm/Packages
D: opening  db index       /var/lib/rpm/Pubkeys rdonly mode=0x0
D:  read h#     517 Header sanity check: OK
D: ========== RSA pubkey id 90770e1b e2d1065b (h#517)
rundeck-2.6.1-1.12.GA.noarch.rpm:
    Header V3 RSA/SHA1 signature: BAD, key ID e2d1065b
    Header SHA1 digest: OK (3de7e2463ed969c41879c66ff455598d5aadf4bd)
    V3 RSA/SHA1 signature: BAD, key ID e2d1065b
    MD5 digest: OK (f95d6bf6d176408d6acb9a7f9aebf64b)
D: closed   db index       /var/lib/rpm/Pubkeys
D: closed   db index       /var/lib/rpm/Packages
D: closed   db environment /var/lib/rpm/Packages
D: May free Score board((nil))
~~~

**Comment by fixed4life** [comment]
This worked perfectly well on my CentOS 5 server this morning.

**Comment by gentunian** [comment]
No luck for me. I will continue with manual instead (I really need upgrading I can't spend more time, my system has low disk space and in 2.6 is solved the opened file descriptors issue). Thanks for your sharings and efforts!

cheers

**Comment by dpetzel** [comment]
I have also run into this recently. I was directed here from https://groups.google.com/forum/#!topic/rundeck-discuss/v0CPhsJgueU.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
