### ISSUE TITLE
Feature Request - Display MotD on project main pages

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#1437]
Currently message of the day for each project is only displayed in Project List page.

Since we only have a single project, it's very common for users to bookmark the project Jobs page. In this case, users go to Jobs page directly to perform their tasks, and never have the chance to notice Message of the Day.

Is it possible to put MotD on the main pages (Jobs, Nodes, Activities etc), something like this:

![image](https://cloud.githubusercontent.com/assets/592046/9717400/05e514c4-55a5-11e5-8092-9e16e0998bb0.png)

**Comment by danifr** [comment]
:+1: I like the idea.
Sometimes my jobs fail because other services are being intervened.

It'd be great if I could display a global banner to my users saying "Notice XXX is being intervened. Some jobs may fail"

**Comment by mjburling** [comment]
This is getting on two years old, but I would love to see such a feature.
