### ISSUE TITLE
Jobs seem to get killed but continue running

### ISSUE THREAD

**Issue by joshuaspence** [rundeck/rundeck#1444]
This has happened to us around five times today, the executions will get marked as "Killed" but the execution will continue anyway and eventually complete.

We are on v2.5.2 and there is nothing interesting in `/var/log/rundeck/rundeck.log`.

![rundeck-blurred](https://cloud.githubusercontent.com/assets/234676/9843877/b1788eae-5b01-11e5-91e8-6af25ae01ee8.png)

**Comment by joshuaspence** [comment]
Jobs also seem to be executing much slower than usual. One particular job has gone from 17 minutes to 29 minutes.

**Comment by joshuaspence** [comment]
OK. The issue seemed to be that we had two different Rundeck hosts running, both pointing to the same database. One of the hosts wasn't actually in use so I terminated it and the problem seems to have gone away.

**Comment by gschueler** [comment]
@joshuaspence if you want to use multiple rundeck servers with the same database, enable clusterMode, which will prevent scheduled jobs from running on more than one server

**Comment by joshuaspence** [comment]
Thanks. Is there any downside to enabling clust mode?

**Comment by gschueler** [comment]
no. just be aware that scheduled jobs will run on the server on which they were last updated (uploaded, modified, or created). If one server goes offline, the others do not automatically queue the scheduled jobs: you need to call an API endpoint to transfer the scheduling to another server.

**Comment by joshuaspence** [comment]
OK, thanks.
