### ISSUE TITLE
Old or new job versions run after modification

### ISSUE THREAD

**Issue by rocso** [rundeck/rundeck#1447]
Hi,

I'm currently running RunDeck version 2.5.1-1. This is a production system and I have not yet upgraded to the latest version of RunDeck. I have checked the lists of bug fixes in the later releases but did not see any matching the following issue

Scenario: I have a job defined that is running reliably as a scheduled job. I then edit the job in order to change a step. Subsequent [scheduled] runs will now sometimes run the old version and sometimes the new version.

The way I'm using RunDeck is generally but not always as follows (through the GUI):
I define single-purpose jobs that I don't schedule but can run manually to test or recover,
I then define a job that calls these single-purpose jobs as workflow steps, that I then schedule as needed.

The problem occurred after I defined a new single-purpose job and added it as a new step in the scheduled job. For example, I modified the job scheduled for 00:05 each day on Friday and it ran the new version fine on Sat, Sun, Mon but on Tuesday for no explicable reason it ran the old version. Nothing in RunDeck was changed over this period.

If I list the job definition either in the GUI or via rd-jobs I see only the latest version.

This is the second time this has happened with this same job. The first time IIRC I simply added an option and may have rearranged the ordering of a couple of steps via the GUI. The second time I added a new step and removed an old step via the GUI.

I'm currently trying to work around the issue by duplicating the scheduled job and then deleting the original, assuming that this might disambiguate the job versions.

**Comment by ecoron** [comment]
Hi, 
we noticed the same issue, sometimes is an older version of scheduled job executed.
We are on Version 2.5.3

**Comment by ecoron** [comment]
as a workaround we do the trick to disable the scheduler (and save the job)
after doing the changes in job we enable the scheduler again. the result is no more random execution of old or new version of the job definition.

**Comment by wricardo** [comment]
I'm having the same issue here. I'm running version 2.5.0-1

**Comment by oscaro-data** [comment]
This issue is still present on version 2.6.2.
Is there a correction planned ?
Thank you

**Comment by pvanacker** [comment]
This issue is still present on version 2.6.2.
Is there a correction planned ?
Thank you

**Comment by DJHills** [comment]
I have also just observed the issue in version 2.6.2.

**Comment by danifr** [comment]
Hi @gschueler,

I had this issue today (v2.6.2). I don't know if it is still present on newer versions of Rundeck.
In my case, the scheduled job was run using an old option instead of the one that was supposed to use.

Is there a way I can check against the database what are the last options used for a certain job and who modified it and when? I'd like to check if it was actually a bug or a human error.

Thanks a lot!

**Comment by ahonor** [comment]
Curios if the SCM plugins will satisfy managing the versions.

**Comment by fielixlv** [comment]
how to resolve this problem?

**Comment by ltamaster** [comment]
Hi @rocso 

I was trying to reproduce it on the last version of rundeck, it worked OK for me. Have you still having this issue?

Thanks
Luis

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
