### ISSUE TITLE
Cancel/Save options on workflow step become unresponsive after error

### ISSUE THREAD

**Issue by obrienmorgan** [rundeck/rundeck#1448]
Rundeck 2.5.3

Steps to reproduce...
1. Add a new Node step - Script to a job
2. Without entering script to execute, click Save
3. Script must be specified error shown

Expected...
User can enter desired script and click Save, resolving error

Actual...
Both Cancel & Save buttons are now unresponsive. Only action user has available is to cancel edits to job. Potentially losing any unsaved work.

![image](https://cloud.githubusercontent.com/assets/7516744/9923034/787bfe0c-5ca4-11e5-8a39-bf08643634c5.png)

**Comment by obrienmorgan** [comment]
Same issue occurs for Node step - Command

**Comment by gschueler** [comment]
thanks for the report
