### ISSUE TITLE
Job set as "execute locally" should not require privilege to rundeck server node

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#1459]
So I have a job as:

- One single workflow step "Local Command" , per node or per workflow.
- Node selection set to "Execute Locally"

If user does not have [read,run] privilege to rundeck_server, executing the job will fail with:

```
	No matched nodes: MultiNodeSelector{nodenames=[server_node]}
```

However, if I create as job as:

- One single workflow step "Local Command" , per node or per workflow.
- Node selection set to "Dispatch to Nodes"

Then, the job will success by selecting any random node, even though the job performs exactly the same thing:  running a local command on rundeck server node.

(In both cases, user does not have access privilege to rundeck server)

**Comment by rophy** [comment]
Workaround: instead of "Execute locally", define a 'stub' node, and configure the job to run on that node.

**Comment by JPGrieb** [comment]
I'm getting this same error. What release will it be fixed in.

**Comment by gschueler** [comment]
Local Command step plugin should require `run` access to the server node
