### ISSUE TITLE
Support for SSH CA

### ISSUE THREAD

**Issue by hany** [rundeck/rundeck#1467]
OpenSSH supports the use of a [certificate authority](https://www.digitalocean.com/community/tutorials/how-to-create-an-ssh-ca-to-validate-hosts-and-clients-with-ubuntu). When used, an authorized person will "sign" certificate requests (very similar to SSL), and a new public key will be generated side-by-side your existing key pair. For example:

```
-rw------- 1 rundeck rundeck 1671 Sep  8 17:23 /var/lib/rundeck/.ssh/id_rsa
-rw-r--r-- 1 rundeck rundeck 1410 Oct  9 14:02 /var/lib/rundeck/.ssh/id_rsa-cert.pub
-rw-r--r-- 1 rundeck rundeck  382 Sep  8 17:23 /var/lib/rundeck/.ssh/id_rsa.pub
```

The `id_rsa-cert.pub` is the signed SSH key. When `ssh`'ing to a host, OpenSSH will offer up the `id_rsa-cert.pub` key when authenticate with this key (check out the `CERTIFICATES` section of the `ssh-keygen`(1) man page).

It appears that Rundeck does not support this, and does not attempt to offer up this signed key. Any chance this can be added?

**Comment by rikatz** [comment]
:+1:

**Comment by gschueler** [comment]
we use Jsch library for java based ssh, it does not seem that it supports that feature: https://sourceforge.net/p/jsch/mailman/message/34632621/
