### ISSUE TITLE
Disable/Enable Schedule in Job Actions menu (Rundeck 2.6.0-1) 

### ISSUE THREAD

**Issue by paulpet** [rundeck/rundeck#1468]
Job scheduled to run Mon-Fri, then "Disable Schedule" in Job Actions pop-up menu, then "Enable Schedule" in Job Actions menu and the job will be scheduled to run everyday (not Mon-Fri as originally configured).

**Comment by miguelantonio** [comment]
Reproduced, will post pull request with fix
