### ISSUE TITLE
Enable Scheduling and Execution reverting to "No" during job edit (2.6.0-1)

### ISSUE THREAD

**Issue by paulpet** [rundeck/rundeck#1470]
Every time I edit a job the "Enable Scheduling?" and "Enable Execution?" are always set to No, even if I change them to Yes when I return to edit the job they are again both showing as "No". 

Jobs continue to work, but if any edits take place then we need to always remember to alter these two fields back to "Yes" every time.

Running 2.6.0-1, upgraded from 2.5.3.

**Comment by paulpet** [comment]
I cannot seem to replicate this issue after re-authenticating into rundeck so I am going to assume it was some sort of caching aberration. Closing issue.

**Comment by fseiftsmlb** [comment]
I'm getting this as well.  upgrading from 2.4.x to 2.6.x all of our jobs have been set to no.  However, If we set it to yes it during an edit, the parameter change holds.
