### ISSUE TITLE
scm export commits yaml format in .xml extension

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#1471]
version: 2.6.1.0-snapshot - ba0cef2eb975ad6181f951102b276be6c15bc102

Steps to reproduce:

1. Config git scm export to export as yaml
2. Commit changes in jobs page
3. Check local scm dir `/var/rundeck/projects/xxx/scm`
4. Committed file is named ${job.name}-${job.id}.**xml**, while file contents are in yaml format.

**Comment by gschueler** [comment]
the file name is determined by the "File Pattern", which has default extension of .xml.  Perhaps it should also allow use of the format like `${file.format}`
