### ISSUE TITLE
When disabling a crontab style schedule and restarting the rundeck service, the schedule is enabled again after service restart.

### ISSUE THREAD

**Issue by oovoo** [rundeck/rundeck#1475]
Steps to reproduce:
1. create crontab style schedule
2. disable the schedule
3. restart the service
4. schedule is enabled again -> error

**Comment by snebel29** [comment]
Would be useful to know the version you're using

**Comment by oovoo** [comment]
Sorry,
2.6.0-1 with MySQL DB.
