### ISSUE TITLE
Setting up oracle as  RDB Datasource

### ISSUE THREAD

**Issue by kino71** [rundeck/rundeck#1476]
Hello,
I'm trying to connect the latest rundeck (2.6.0, self contained launcher on Solaris) with Oracle.
I followed the instruction in http://rundeck.org/docs/administration/setting-up-an-rdb-datasource.html but I get "Could not load JDBC driver class " in service.log

thanks

**Comment by ahonor** [comment]
You might need to add this property to the rundeck-config.properties

       dataSource.driverClassName=oracle.jdbc.driver.OracleDriver

**Comment by kino71** [comment]
Hello Alex,
you're right I thought it was already there, but I was mistaken.
Unfortunately I still have problems :

2015-10-14 17:50:20,903 [main] ERROR context.GrailsContextLoaderListener  - Error initializing the application: Error creating bean with name 'transactionManagerPostProcessor': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'transactionManager': Cannot resolve reference to bean 'sessionFactory' while setting bean property 'sessionFactory'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'sessionFactory': Invocation of init method failed; nested exception is java.lang.NullPointerException

but "Could not load JDBC driver class " is gone.

thanks

**Comment by ahonor** [comment]
@kino71 can you check if there were two instances of rundeck running?

**Comment by gschueler** [comment]
Other problems which could cause that error:

* unable to connect to DB
* authentication failure

**Comment by kino71** [comment]
@ahonor there is only one instance of rundeck running on this host
@gschueler I'm trying different combination of jdbc drivers and datasource.url
we have Oracle 11g , jdk 1.7
I first tried with ojdbc14.jar, now I'm using ojdbc6.jar that should match jdk/oracle version.

rundeck-config.properties:

#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
#loglevel.default=INFO
loglevel.default=VERBOSE
rdeck.base=/SG/RunDeckTest

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
grails.serverURL=https://rundeck-test:4443
dataSource.dbCreate = update
#dataSource.url = jdbc:h2:file:/SG/RunDeckTest/server/data/grailsdb;MVCC=true;TRACE_LEVEL_FILE=4

dataSource.url = jdbc:oracle:thin:@oradevrdek:1515:XE
dataSource.driverClassName=oracle.jdbc.driver.OracleDriver
dataSource.username = RUNDECK_TEST
dataSource.password = r4ND3sK1
dataSource.dialect = org.hibernate.dialect.Oracle10gDialect

I tried with:
dataSource.url = jdbc:oracle:thin:@oradevrdek:1515:devrdek
(devrdek is our Oracle service name)
with no luck.

**Comment by kino71** [comment]
Hi, 
it worked with :

dataSource.url = jdbc:oracle:thin:@oradevrdek:1515/devrdek
(devrdek is our Oracle service name)

I got some create table error, but I know I have to fix it manually.

thanks!
