### ISSUE TITLE
Upgrade to 2.6.0: Node selection defaults to "user has to explicitly select target nodes"

### ISSUE THREAD

**Issue by mprasil** [rundeck/rundeck#1477]
These options default to values that break backwards compatibility:
* Node selection - defaults to "The user has to explicitly select target nodes" which makes all older jobs behave differently. (all hosts are by default unchecked)
* Enable Scheduling - This appears to be working fine (job can be executed) but when I try to edit the job, the option is set to "No", so when I don't notice that before saving I will end up disabling it.
* Enable Execution - Same as scheduling.

In my opinion all of these should default to 2.5.3 behavior.

**Comment by gschueler** [comment]
thanks for the report

**Comment by gschueler** [comment]
Moved some parts of this to #1502
