### ISSUE TITLE
[Enhancement?] Being able to preselect nodes even when using node filters

### ISSUE THREAD

**Issue by snebel29** [rundeck/rundeck#1480]
When using node filters even when selecting "User has to explicitly select target nodes" it's not possible to select them, 

There is a very clear message explaining that node filters will be applied once the job is run, but is there any chances of changing this behaviour?

Would be wonderful if after click on Run buttom you gather the nodes and you can preselect them.

**Comment by gschueler** [comment]
agree...see #877

**Comment by gschueler** [comment]
duplicates #877
