### ISSUE TITLE
SCM: File Path Template Parameter issue 

### ISSUE THREAD

**Issue by dustinak** [rundeck/rundeck#1489]
When trying to remove ${job.id} from the "File Path Template" Git Export configuration, I get an "Invalid Value" error.

So for instance if I just set my "File Path Template" to be: ${job.group}${job.name}.yaml instead of ${job.group}${job.name}-${job.id}.yaml it gives me this error.

**Comment by gschueler** [comment]
Right now in Rundeck you can define two jobs with the same name & group in the same project. We want to fix that behavior, but currently it could cause an issue if you don't include the job id in the file path.  However, we I guess it could be just a warning and not prevent you from removing it.
