### ISSUE TITLE
rd-jobs list does not include the 'project' property in Rundeck 2.6.0

### ISSUE THREAD

**Issue by dalisch** [rundeck/rundeck#1490]
When running the rd-jobs command line tool, the 'project' property is not included for the 'list' option in the exported job output.  This causes the import to fail when attempting to re-import the jobs definitions created by the previous command's output.  (Only tested so far with yaml format).

**Comment by gschueler** [comment]
this is a change noted in the Compatibility section of the release notes: http://rundeck.org/docs/history/version-2.6.0.html#compatibility

use `rd-jobs -p` to import to a specific project

**Comment by dalisch** [comment]
Thanks Greg -- test is successful with this change.  Closing this issue.
