### ISSUE TITLE
SCM imports reads as XML even though YAML has been chosen

### ISSUE THREAD

**Issue by LordMike** [rundeck/rundeck#1492]
When setting up imports, I copied most settings from the export page (file paths, repo paths, key files) and set the import format to Yaml. But when importing any file, the following error appears:

    Failed importing: Services/Webfile Watcher-4c3680f2-971e-4c8d-bee7-7a4f98026e05.xml: rundeck.controllers.JobXMLException: Unable to parse xml: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

The content of the file in question (in the repo) is very much Yaml. 

Sidenote: I'll redo the entire repo anyways, as the UUID's no longer match (I migrated to a MySQL db recently and created new UUID's).

Might be slightly related: #1471 

Server version: `2.6.0-1`

**Comment by LordMike** [comment]
#1471 *is* related. Renaming all files to `.yaml` resulted in a successful import.

**Comment by gschueler** [comment]
thanks for confirmation about 1471.  looks like it is using the file extension to determine the format, not the configuration setting
