### ISSUE TITLE
SCM rebase gives a non-descriptive message

### ISSUE THREAD

**Issue by LordMike** [rundeck/rundeck#1493]
When importing changes (to resolve commit conflicts), and chosing to rebase, Rundeck replies with: `org.eclipse.jgit.transport.FetchResult@31c0af85 org.eclipse.jgit.api.RebaseResult@61435e47` as a message.

![image](https://cloud.githubusercontent.com/assets/1027111/10592147/7834b79c-76ba-11e5-9f95-0724ae997ecd.png)

Server version: `2.6.0-1`

**Comment by gschueler** [comment]
this might have been fixed by https://github.com/rundeck/rundeck/issues/1486 but i'll check
