### ISSUE TITLE
SCM side-by-side import and export result in extra steps

### ISSUE THREAD

**Issue by LordMike** [rundeck/rundeck#1495]
When I've saved a changed to SCM and pushed it to the remote repo, Rundeck immediately requests that I import the exact same changes, which just seems weird.

Perhaps make it so that when a job is committed, and pushed, it is marked as `current`, so that Rundeck doesn't think it's old?. (Because if I could push it to the remote, then *it is* current, no matter what others say).

**Comment by gschueler** [comment]
should already be fixed: https://github.com/rundeck/rundeck/issues/1488
