### ISSUE TITLE
rundeck not listening after installation

### ISSUE THREAD

**Issue by ginzel** [rundeck/rundeck#1498]
Hello!
Based on [Instructions](http://rundeck.org/downloads.html) "Yum RPM Install" I did on CentOS 6.7:

~~~
rpm -Uvh http://repo.rundeck.org/latest.rpm
yum install rundeck
service rundeckd start
~~~

Everything went well, but rundeck does not listen neither on localhost nor on eth0 – investigated with `nmap`. Rundeck is running – `ps -ax |grep rundeck`

~~~
cd /var/log/rundeck
ls -lt |head
less rundeck service
~~~
gives

~~~
2015-10-20 10:35:49,491 [main] WARN  org.grails.plugin.platform.events.EventsImpl - Event listener rundeck.services.JobEventsService#jobChanged declared for topic jobChanged and namespace app but no such event is declared, you may never receive it
2015-10-20 10:35:54,115 [main] ERROR grails.app.conf.BootStrap - NOT importing existing filesystem projects filesystem

WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable.
WARN  EventsImpl: Event listener rundeck.services.JobEventsService#jobChanged declared for topic jobChanged and namespace app but no such event is declared, you may never receive it
ERROR BootStrap: NOT importing existing filesystem projects filesystem
~~~

What is the [manual](http://rundeck.org/downloads.html) missing, please?

**Comment by LordMike** [comment]
Unsure if the command in CentOS is the same, but on Debian, I can do a `# netstat -anolp | grep LISTEN | grep rundeck` and find the listening sockets.

It may:
* Listen on 4440
* Listen on IPv6 (only)

**Comment by ginzel** [comment]
Thank you,
it's the same,
no results = not listening.

HG

**Comment by LordMike** [comment]
Have you waited 10 minutes? 
Is there a CPU load?
Do the logs contain anything useful?
Do you have 1+ GB memory?

**Comment by ginzel** [comment]
Thank you.

On Wed, Oct 21, 2015 at 09:28:51AM -0700, Michael Bisbjerg wrote:
>   Have you waited 10 minutes?
No. Now yes, but did not help.

>   Is there a CPU load?
No.
uptime
22:44:48 up 1 day,  4:12,  1 user,  load average: 0.44, 0.26, 0.09

>   Do you have 1+ GB memory?
Yes.
free -m
Mem:          9825       2510       7314         68        472        703
-/+ buffers/cache:       1335       8490
Swap:        12015          0      12015

>   Do the logs contain anything useful?
service.log:
2015-10-21 22:43:53.651:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440

**Comment by gschueler** [comment]
if the service.log contains `AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440` then it appears like it is listening on port 4440 on localhost.  Is it not accessible there?

**Comment by ginzel** [comment]
~~~
 wget 127.0.0.0:4440
--2015-10-27 09:14:00--  http://127.0.0.0:4440/
Connecting to 127.0.0.0:4440... failed: Network is unreachable.
netstat -anolp | grep LISTEN | grep rundeck	# returns nothing
~~~

**Comment by LordMike** [comment]
Could you try `http://127.0.0.1:4440` as well as showing us the contents of
`route -n` and `/etc/hosts`

Mvh.
Michael

**Comment by jennyfountain** [comment]
I am seeing the same issue:

This is what I see in my log:
jobChanged declared for topic jobChanged and namespace app but no such event is declared, you may never receive it

never see it starting port 4440.

**Comment by ginzel** [comment]
Thank you. It seems it works.

~~~
yum update
…
(7/8): rundeck-2.6.1-1.12.GA.noarch.rpm
(8/8): rundeck-config-2.6.1-1.12.GA.noarch.rpm

grep release /etc/issue
CentOS release 6.7 (Final)

service rundeckd restart
sleep $((10*60))

netstat -anolp | grep LISTEN | grep rundeck

route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
10.76.19.0      0.0.0.0         255.255.255.0   U     0      0        0 eth0
169.254.0.0     0.0.0.0         255.255.0.0     U     1002   0        0 eth0
0.0.0.0         10.76.19.254    0.0.0.0         UG    0      0        0 eth0

cat /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6

wget 127.0.0.1:4440
--2015-11-03 16:30:33--  http://127.0.0.1:4440/
Connecting to 127.0.0.1:4440... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://127.0.0.1:4440/user/login;jsessionid=lannlh7wb2i1wox6wjz5cbb4 [following]
--2015-11-03 16:30:33--  http://127.0.0.1:4440/user/login;jsessionid=lannlh7wb2i1wox6wjz5cbb4
Reusing existing connection to 127.0.0.1:4440.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: `index.html'

links 127.0.0.1:4440
~~~

But why the `netstat -anolp` does not show rundeck please?

**Comment by LordMike** [comment]
It might. I may have been too quick with the command. The Grep for rundeck
might be what's hiding it (since the process could be called Java). It
would be more correct to grep for "4440".

E.g.: netstat -anolp | grep LISTEN | grep 4440


Mvh.
Michael

**Comment by ginzel** [comment]
Yes, the application is java in my case. I am sorry.

**Comment by ageri** [comment]
add "dataSource.dbCreate = update" on /etc/rundeck/rundeck-config.properties and restart the rundeckd
