### ISSUE TITLE
Add AT time scheduling of jobs.

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#150]
* Issue Type: Request/Enhancement
* Rundeck version: 1.4.3

---

Issue:

Would like the ability to schedule a job to run once at a specific point in time and then never again.
Thanks!

---

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/520)

Original Creator: Michael Gibson

**Comment by vaneldik** [comment]
+1

**Comment by danifr** [comment]
+1

**Comment by marcotuliolp** [comment]
+1

**Comment by dfinninger** [comment]
+1 this is feature is exactly what I am looking for

**Comment by abohne** [comment]
+1

**Comment by davemcdonnell** [comment]
+1

**Comment by angystardust** [comment]
+1

**Comment by paulpet** [comment]
+1

**Comment by webdevwilson** [comment]
+1

**Comment by ulrith** [comment]
+1

**Comment by hemantb** [comment]
+1

**Comment by mdorenkamp** [comment]
+1

**Comment by sebw** [comment]
This feature would be very nice. I have developed several "forms" in Rundeck to deploy bundles from a Nexus repository. I would love to be able to schedule deployments during the night!

**Comment by hemantb** [comment]
A workaround would be to setup the Job, and in the end of job disable the cron

**Comment by luisdavim** [comment]
+1

**Comment by mprasil** [comment]
+1

**Comment by mtward** [comment]
+1

**Comment by MoradT** [comment]
+1. That will indeed be good to get this feature

**Comment by gloppasglop** [comment]
If you enter the following crontab expression it will execute just once:

0 21 30 22 FEB ? 2016

Will execute the job at 21:30:00 on 22-FEB-2016

**Comment by paulpet** [comment]
@gloppasglop I used to do this too. But it's not a real fix. For example you may have the job already regularly scheduled in the crontab but also need to run it on an ad-hoc basis occasionally. Additionally, it would be nice to have permissions that allow a user to schedule a one off jobs, without them having to have permissions to alter the entire job config itself, which is the case for crontab changes I believe.

**Comment by ahonor** [comment]
@gloppasglop that's a good tip and we should document it

**Comment by minhuber** [comment]
@paulpet: Not sure if I understand this "ad-hoc" properly. I have several jobs with schedules (eg. every hour) and in any of these ones, I can click on the button: "Run job now" and it executes immediately. Doesn't affect the scheduled ones. Regarding the permissions, simply add in the project context for the specific user only the run permission and you're (hopefully) all set.

**Comment by paulpet** [comment]
@minhuber the scenario I was running up against, was wanting certain users with low privilege levels to be able schedule 1 off executions at specific times (usually late in the evenings, not run immediately). Those jobs would also have scheduled executions set up in the crontab too, which I didn't want the (regular) users to modify.

If an AT type interface was available for normal users to schedule one-off jobs, that would be ideal.

**Comment by danifr** [comment]
@minhuber for example, we would like to use this feature to schedule reboots/shutdowns via Rundeck

**Comment by Ziaunys** [comment]
+1

**Comment by jamieps** [comment]
I have got something working for this now, which allows for ad-hoc scheduling, I'm hoping to raise a PR within the next couple of weeks.
