### ISSUE TITLE
Enhancement: Avoid concurrent executions across multiple jobs.

### ISSUE THREAD

**Issue by LordMike** [rundeck/rundeck#1500]
I currently have two parts of a MySQL backup job: A full backup routine, and an incremental backup routine. 

It's somewhat simple for me to just let the full backup run every Monday, and the incremental once every day during Tuesday through Sunday. I could then rely on the fact that the job(s) would never run for more than 24 hours given my MySQL databases size.

But if I wanted to run incrementals every 10 minutes or more often even, I'll run into two problems:
- I should not run two incrementals concurrently (solved using Rundecks features today)
- I should not run an incremental on top of a concurrently running full backup (not covered - two separate jobs)

I imagine that the existing `Multiple Executions?` option can be extended as such:
- **Yes**: Allows multiple executions of _this_ job
- **No**: Disallows multiple executions of _this_ job by setting the `concurrent_group` name to the jobs ID (the GUID)
- **No, custom group**: Disallows multiple executions of _this_ job if any other job in the specified `concurrent_group` is already running

The idea here being to introduce a `group`-based instead of a `job`-based concurrency/locking approach, using a new field named `concurrent_group`. To keep things simple, and not having to check two different types of locking (because that leads to concurrency issues on its own), I propose to change the current setup into a kind of automated group name that doesn't conflict with other groups.

So, to implement (architecturally):
- The field `concurrent_group` should be introduced.
  - A migration can ensure that it is set to the job id for existing jobs
  - Code can default to the job id if the field is empty
- The UI should either
  - Set the `concurrent_group` name to being the job id if **No** is checked, in addition to setting the current yes/no setting
  - Set the `concurrent_group` name to the specified value (from the UI) in addition to setting the current yes/no setting
- Code checking for concurrency should be changed to check the `concurrent_group` instead of job-id's

**Comment by gschueler** [comment]
We have an existing "Job State Conditional" step you can use for this.  You can assert the state of another job (such as make sure it is not running), if this fails you can exit the current job

**Comment by LordMike** [comment]
I can imagine the following issue: Say I had three or four jobs, all excluding each other from running concurrently, will the n-1 job state conditionals all be checked atomically?

This could easily happen if I made my setup simple, and set up monthly, weekly and daily backup jobs, all set to run at the same time. Instead of scheduling the jobs so they wouldn't conflict (again assuming the they run in less then 24 hours), I could/would assume that the conditionals would prevent any two jobs from running concurrently.

Another way to solve the pickle would be to have locking files in place (or other kinds of OS locks), but this again is an issue if there are multiple nodes in play.
