### ISSUE TITLE
SCM import should have a "Remove UUIDs" option

### ISSUE THREAD

**Issue by scaissie** [rundeck/rundeck#1503]
I'm getting an import error, conflicting UUIDs, when I try to import a job that exists in another project. Like "Upload Job Definition", SCM Import should have an option that will allow you to remove the UUIDs during the import.

**Comment by DevOpsFu** [comment]
:+1:  for this request. I'm setting up a Rundeck server to manage multiple environments; I have a project per environment and ideally they should be able to share the exact same job configuration. I'd like to handle the separation of nonprod/prod environments by having them point at different branches, and use Pull Requests to get the nonprod job config promoted up to production.

**Comment by Miminoux** [comment]
+1

**Comment by MoradT** [comment]
I am looking forward seeing that feature implemented. Indeed, that's crucial as we manage multiple projects which need the same kind of jobs. So definitely 👍

**Comment by airbornemist6** [comment]
+1 This is a huge deal for us. We just attempted to create automation that automatically stands up a dev sandbox project for users in our dev environment, but it's all basically useless because of global UUIDs :sob:
