### ISSUE TITLE
Scheduler status icon is not changed whith cluster mode

### ISSUE THREAD

**Issue by mats116** [rundeck/rundeck#1505]
(My cluster is constituted by ELB, EC2, RDS and S3 on AWS.
node-1 & node-2 are both active)

I turn off the Scheduled job on node-1.

the icon is ![](https://i.gyazo.com/889cc4036c6c2ce239926816d72da1f4.png) on node-1

But, the icon on npde-2 is ![](https://i.gyazo.com/09a4c0b4a3e6153fa7d9c8c8d485d96a.png).

Is this a bug?

(Schedule setting is right , there is the bug about icon)

**Comment by ahonor** [comment]
Is this still a concern in 2.10.x?
