### ISSUE TITLE
[Feature Request] Run scheduled jobs with different options

### ISSUE THREAD

**Issue by gadelkareem** [rundeck/rundeck#1506]
Currently Rundeck allows to schedule a job to run only if you have a "default" value for the options on the job. Would be great if we can specify the options on the schedular so it would run several times with different options, for ex: ( env:staging, env:prod...)

**Comment by LordMike** [comment]
Maybe a job in general should have multiple triggers? (Much like Windows scheduled tasks)

**Comment by gschueler** [comment]
dupe of https://github.com/rundeck/rundeck/issues/828
