### ISSUE TITLE
Feature Request: plain text node filter results view

### ISSUE THREAD

**Issue by andrewpwade** [rundeck/rundeck#1507]
Thanks to the useful tag/parameter filtering, I often use rundeck to get a list of servers to be used as in input elsewhere, or just for reporting.

It would be useful to have on the node filter results page a link to a plain-text list of results of resource names, with no pagination.

**Comment by ahonor** [comment]
@andrewpwade What format would this be? Perhaps, it's a link to the formats already supported (eg,  ResourceModelFormatter plugins).

**Comment by andrewpwade** [comment]
@ahonor Plain text, no attributes/tags, just node names separated by a new line.
