### ISSUE TITLE
Retry Failed Nodes does not handle nodes with spaces

### ISSUE THREAD

**Issue by ajxb** [rundeck/rundeck#1508]
In RunDeck 2.5.3-1 if a job failed and I selected the *Run Again > Retry Failed Nodes* option I would be returned to the relevant job page, the **Nodes** section of the page would display a list of selected nodes that the job execution had failed on. Clicking on the *Run Job Now* button would execute against only those nodes that the job failed on.

![nodes 2 5 3-1](https://cloud.githubusercontent.com/assets/1756536/10692128/14053ac4-7987-11e5-8df7-2afdde3b5452.png)

In RunDeck 2.6.0-1 if I perform the same actions I see the following displayed in the **Nodes** section of the page : *Warning: The Node filters specified for this Job do not match any nodes, execution may fail.*.  Clicking on the *Run Job Now* button would result in the job being executed against all of the nodes again.

![nodes 2 6 0-1](https://cloud.githubusercontent.com/assets/1756536/10692131/1b069c3c-7987-11e5-9810-0c4fca4db538.png)

This only seems to occur if I make use of a dynamic node filter (i.e. set the node filter to make use of another property that exists within my job).  An example of a job that exhibits this behaviour can be seen below:

```xml
<joblist>
  <job>
    <id>86655996-56b8-4125-aea5-b0e08a30aa9f</id>
    <loglevel>INFO</loglevel>
    <multipleExecutions>true</multipleExecutions>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <fileExtension>.ps1</fileExtension>
        <description>Run test</description>
        <scriptargs />
        <script><![CDATA[if ([system.environment]::MachineName -contains "DEV-VW-WEB03") {
  exit 1
}

if ([system.environment]::MachineName -contains "DEV-VW-WEB05") {
  exit 1
}]]></script>
        <scriptinterpreter>powershell -File </scriptinterpreter>
      </command>
    </sequence>
    <description>Retry Test A - Using a node filter that has been populated from options</description>
    <name>Sandbox - Retry Test A</name>
    <context>
      <project>Bet.Net</project>
      <options>
        <option name='Environment' value='dev2' values='dev2,qa,stg' enforcedvalues='true' required='true'>
          <description>The environment to deploy to</description>
        </option>
      </options>
    </context>
    <dispatch>
      <threadcount>10</threadcount>
      <keepgoing>true</keepgoing>
      <excludePrecedence>true</excludePrecedence>
      <rankOrder>ascending</rankOrder>
    </dispatch>
    <uuid>86655996-56b8-4125-aea5-b0e08a30aa9f</uuid>
    <nodefilters>
      <filter>environment: ${option.Environment}</filter>
    </nodefilters>
    <group>Deploy</group>
    <timeout>120m</timeout>
  </job>
</joblist>
```

I believe that this is a regression to existing functionality.

**Comment by gschueler** [comment]
I was not able to reproduce this using the latest code.  Have you tried 2.6.4?

**Comment by ajxb** [comment]
Hi Greg,

Thanks for looking into this for me.  Following your update I've taken another more detailed look and I think I've figured out what I've broken.  There was unfortunate timing between a system upgrade to 2.6.0 and a change in our node naming conventions.

I've subsequently found that our node naming may be to blame.  We added spaces into our nodenames in the resources.yaml file like so:
```
DVW-WEB-MULTI07 - 10.16.0.190:
  ...
DVW-WEB-MULTI08 - 10.16.0.191:
  ...
```
I've found that if the job fails on nodes named like the above then the _Run Again > Retry Failed Nodes_ exhibits the behaviour described in my original report (even in the latest version 2.6.6).  If I tweak my node names to remove the spacing then all returns to normal.

I'm going to update all of our nodenames to remove spacing.  I'm happy for this issue to be closed (although you could argue that in the long run something might need to be done about nodenames with spaces in them).

Cheers!

**Comment by gschueler** [comment]
@ajxb ok, thanks for tracking down the issue.  I will rename the issue, that is still a bug!

**Comment by gschueler** [comment]
@ajxb i tried to reproduce this using spaces in node names, but was still unable to do so.  If you can isolate an example, please let me know

**Comment by gschueler** [comment]
@ajxb spoke too soon! I did reproduce this.
