### ISSUE TITLE
Too many open files issue (RPM)

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#151]
- Issue Type: Bug
- Rundeck version: 1.4.2

---

Issue:

RunDeck user is hitting default ulimit on CentOS fairly easily (after a couple days uptime).

---

Reproduce:

Use RunDeck until it stops responding to API calls; when one attempts to login, a message appears as follows:
@@@
/etc/rundeck/framework.properties: Too many open files
@@@

---

To resolve:

Patch /etc/security/limits.conf to increase open files limit for the rundeck user. Patch forthcoming for RPM spec file.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/531)

Original Creator: Moses Lei

**Comment by gentunian** [comment]
I'm suffering this in production with 2.5.1 release. I set file descriptors limit to `100000` and problem continues happening. Any tip or clue to avoid this from happening?

**Comment by gschueler** [comment]
@gentunian if you do a `lsof`, do any files stand out (e.g. temp files), that could indicate the file handles are not getting closed out properly?

**Comment by gentunian** [comment]
@gschueler I see a lot of `(deleted)` records, I've restarted the server early today (when I wrote my comment above), this are `deleted` records:

    # lsof -p 1363 | grep deleted | wc -l
    946

Also, I can see that there are repeating jars in `lsof -p <pid> | grep pluginJars` output, in `$RDECK_BASE/var/tmp/`. I guess I will keep this data in mind when this happen again.
