### ISSUE TITLE
/var/lib/rundeck is owned by root:root instead of rundeck:rundeck

### ISSUE THREAD

**Issue by ssbarnea** [rundeck/rundeck#1511]
It seems that if you install rundeck from DEB you end-up with /var/lib/rundeck folder owner by the wrong user. This is a critical bug because this breaks lots of things: imagine that the rundeck user will not be able to creat files and directories there, will not be able to generate ssh key,....

**Comment by devnajan** [comment]
In active_directory, if I want to read searchbase groups with their attributes and write it into MS SQL. How can I do this? I am new in Python. Please help.

**Comment by mathieuchateau** [comment]
@devnajan : your question is out of this topic, and not a direct issue of rundeck. Your question is even true without rundeck at all. Please find another way to ask your question.

**Comment by ambikads** [comment]
I am trying to automate rundeck server setup and face the same issue with /var/lib/rundeck permissions.
