### ISSUE TITLE
Stylesheet gives HTTP 404 after update

### ISSUE THREAD

**Issue by LordMike** [rundeck/rundeck#1512]
Hi,

I just updated to the latest version, `2.6.1`. After that (and I recall from previous upgrades too), the stylesheet was missing. So the rundeck webpage was ... unrecognizable :).

I issued a `service rundeckd restart` and the problem fixed itself - perhaps the upgrade script should do a restart too?

When the CSS was missing, it had the following url:
`http://rundeck.local:4440/assets/rundeck-3119d277beda1b3d1916596ac3648faf.css`

Now it has:
`http://rundeck.local:4440/assets/rundeck-7a7c8b28173cc257e443e77d3fdf73ec.css`

**Comment by ahonor** [comment]
Please reopen if this remains a bug in 2.10.x
