### ISSUE TITLE
/j_security_check responds with HTTP 200

### ISSUE THREAD

**Issue by ofosos** [rundeck/rundeck#1514]
Hi,
I'm having the problem that /j_security_check, when presented with user & password, is returning an HTTP 200 ok and displaying an HTML page with the content "Invalid user and password". According to the API docs this should respond with HTTP 401 unauthorized.

Regards, Mark

**Comment by gschueler** [comment]
are you deploying to tomcat?

**Comment by ofosos** [comment]
I'm using the rpms if that helps.

**Comment by gschueler** [comment]
Here is an example login script: https://github.com/rundeck/rundeck/blob/development/test/api/rundecklogin.sh

there wouldn't be a 401 unauthorized when logging in via username/password, you would just either be redirected to /user/login or /user/error, or see the login form in the 200 response again.

**Comment by ofosos** [comment]
Dang. I was pretty sure the api docs said it would return 401. Reading them now, they only say things about the redirect chain. Ok, I think it's not optimal, but you can close this case.
