### ISSUE TITLE
SCM does not change branches once created

### ISSUE THREAD

**Issue by jyaworski** [rundeck/rundeck#1515]
Hello:

It looks like SCM doesn't do a git checkout of a git branch whenever the branch is changed, or if the directory existed under git before scm was enabled (and was a different branch). I changed my branch from master to dev, and it continued making commits to master.

**Comment by gschueler** [comment]
ok, can you explain the workflow you are trying to do?

**Comment by jyaworski** [comment]
@gschueler I originally set up SCM to pull from master. I decided I wanted to push to the dev branch instead (this was exporting). I disabled SCM, reconfigured it to use the dev branch, and then re-enabled it. I was still on the master branch, even though dev was enabled in the config.
