### ISSUE TITLE
sudo and su only running first command as expected user

### ISSUE THREAD

**Issue by Slind14** [rundeck/rundeck#1517]
command:
```
sudo -u someUser bash -c "whoami;whoami"
```
result:
```
someUser
rundeck
```
Same with `sudo su` and with `EOF` instead of -c

Is there any work around for this, besides a local script? I tried it with the command and script workflow step. After 3 hours of testing all the possibilities I could imagine nothing worked. The only way that worked was with a local script (`sudo -u someUser bash -c "path/to/script.sh"`) which does not work in my use case.

I assume that I'm not the first one running into this issue, how did you deal with it so far, is there a work  around (without a local script or additional `ssh -tt user@127.0.0.1 "sudo -u.."`) ?

**Comment by gschueler** [comment]
to preserve quotes in the command string, you may need to double-quote it:

    -c "'whoami;whoami'"

note use of `"` followed by `'`

**Comment by Slind14** [comment]
wow that works. Why didn't this come to my mind? Thank you :)
