### ISSUE TITLE
Insert new command

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#152]
- Issue Type: Feature
- Rundeck version: 1.4.2

---

Issue:

Currently commands can only be added at the bottom of the list of commands (scripts, job calls, etc) of a Job.

It'd be really handy to have an "insert above" icon, in addition to the existing 3 (delete, edit, move)

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/532)

Original Creator: Hasan

**Comment by ahonor** [comment]
Can use drag and drop to reorder steps.
