### ISSUE TITLE
Rundeck connection to hosts behind a Bastion host

### ISSUE THREAD

**Issue by tomkregenbild** [rundeck/rundeck#1523]
Is there a way to allow rundeck to connect to nodes behind a bastion host?

The connection should look like this:
Rundeck --> (port 22 + ssh key) bastion machine --> (port 22 + forwarded ssh key) rundeck node.

I found this discussion but it seems the solution there did not work and it seems like a work around and not a straight forward solution to the problem.

**Comment by klj613** [comment]
SSH config for the rundeck user:

```
Host bastion1
    HostName x.x.x.x
    ProxyCommand none
    BatchMode yes
    PasswordAuthentication no
    StrictHostKeyChecking no

Host *.bation1.corp.net
    ServerAliveInterval 60
    TCPKeepAlive yes
    ProxyCommand ssh %r@bastion1 nc `echo "%h" | perl -pe 's/bastion-//g' | perl -pe 's/.bation1.corp.net//g'` %p
    ControlMaster auto
    ControlPath ~/.ssh/mux-%r@%h:%p
    ControlPersist 5m
    StrictHostKeyChecking no
```

then use the host to connect to: `bastion-192.168.2.3.bastion1.corp.net

of course i suggest enabling host key checking if you manage your known host keys

some of the settings might not be needed. i just copied from one of my old examples.

**Comment by tomkregenbild** [comment]
Thanks, I'll check it.

**Comment by tomkregenbild** [comment]
In any case I do think that a built in Rundeck solution can be really helpful.

**Comment by klj613** [comment]
I agree :)

**Comment by tomkregenbild** [comment]
@klj613 the suggested solution doesn't seem to work, it works when I run it locally from bash but when I try it using Rundeck it seems to ignore this configuration and just try to connect directly to the server.

I also tried the solution that was suggested here but in this case I can't find a way to forward the SSH key pass phrase automatically and safely.

https://groups.google.com/forum/#!topic/rundeck-discuss/DSk-36p0MP0

Is there a chance to implement it in future versions as an integrated option in rundeck?

**Comment by ARentz07** [comment]
👎 for the proposal above. This solution is a rundeck-user-wide configuration change, which might not be desirable. For instance, if you have multiple Openstack tenants to which you need to connect, you would have to modify the configuration before every job run to connect to each. Connecting to multiple at once would also be impossible. It would be preferable to be able to set this ssh config on the fly, possibly through variable expansion from a job option.

**Comment by ARentz07** [comment]
However, I will say a big 👍 to the idea of a bastion host being a first-class thing in rundeck. :)

**Comment by mikelaws** [comment]
Still in its early stages, but I built a quick Node Executor plugin with "region-aware" bastion host support (i.e. uses a region name as a host tag that can be used to generate a bastion host name (e.g. `${REGION}-bastion.example.com` --> `us-west-1-bastion.example.com`).  It can also use a static bastion host (or no bastion host at all), but I built it specifically to support using Rundeck across AWS regions and multiple bastion hosts.  Might be worth a quick look (and some community input)...

https://github.com/AppliedInfrastructure/regional-bastion-ssh-executor

**Comment by ahonor** [comment]
There is also this one https://github.com/rundeck-plugins/openssh-bastion-node-execution

**Comment by rturam** [comment]
@tomkregenbild Are you able to solve this issue? How?

**Comment by anishcorratech** [comment]
@ahonor 

> There is also this one https://github.com/rundeck-plugins/openssh-bastion-node-execution

Is there a documentation on configuring openssh-bastion-node-execution along with rundeck-ec2-nodes-plugin

**Comment by booshlinux** [comment]
I realize this is closed, but here is a solution I came up with today, that might help others in the future.

When configuring your Default Node Executor, under Project settings->Edit configuration choose `openssh/executor`. Choose `privatekey` for Authentication, and your `id_rsa` key file for SSH key Storage Path. (If your id_rsa file is not in Rundeck's key storage, go configure that first).
For SSH Custom Options populate this field with the following:
```
-oStrictHostKeyChecking=no -F /var/lib/rundeck/.ssh/config
```
Note, the `-F` option will require some modification based on what username you are using for authentication. In my case, one username is being used. This user is called `rundeck`.
Create a config file to source from, (The file given with the `-F` flag):
```
Host <host behind bastion>
  Port 22
  ProxyCommand ssh -v <host in front of bastion> -W %h:%p
  IdentityFile /var/lib/rundeck/.ssh/id_rsa
```

Now the next step is the most important. When `known_hosts` cannot be written to, (which you will not see happen without the `-v` flag), you will see the following errors:
```
debug1: read_passphrase: can't open /dev/tty: No such device or address
Host key verification failed.
```
Not sure what the correlation there, but I'm just reporting what I've found from my own experimenting. 
Create this file, and change the permissions to reflect the user running the SSH executor plugin. (In my case, `rundeck`.)
```
# touch /var/lib/rundeck/.ssh/known_hosts
# chown rundeck. /var/lib/rundeck/.ssh/known_hosts
# su - rundeck
$ ssh <host to use with bastion host>
... adds host into known_hosts ...
<logout>
```

After running the job with the above changes, I am able to use an intermediary host to connect to another, without the use of other plugins as mentioned above.
