### ISSUE TITLE
Sudo authority on localhost

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#153]
- Issue Type: Feature
- Rundeck version: Any

---

Issue:

RunDeck is able to run scripts on localhost, but only as the RunDeck user.  For certain small networks the RunDeck console may double as an additional server for other purposes (eg, TomCat, Bind, etc).  Lack of local sudo capability prohibits using RunDeck to manage it.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/534)

Original Creator: Hasan

**Comment by dandunckelman** [comment]
I'm trying to do just this on v2.8.2.

Is there a solution?

**Comment by gschueler** [comment]
possible using a plugin: https://github.com/rundeck-plugins/sudo-local-execution
