### ISSUE TITLE
Links are broken in plugin developers guide

### ISSUE THREAD

**Issue by mnpoonia** [rundeck/rundeck#1531]
links are broken an example is 
http://rundeck.org/2.5.0/developer/node-executor-plugin.html

On above page there is a link to NodeExecutor javadoc Under [Java PluginType ](http://rundeck.org/2.5.0/developer/node-executor-plugin.html#java-plugin-type)  which points to 
http://rundeck.org/2.5.0/javadoc/com/dtolabs/rundeck/core/execution/service/NodeExecutor.html

Which is an invalid link.

**Comment by gschueler** [comment]
sorry, try latest docs, or 2.5.1+ for now
