### ISSUE TITLE
Aborting queued jobs doesn't remove them from the queue

### ISSUE THREAD

**Issue by chrispynacho** [rundeck/rundeck#1538]
If you set the quartz.props.threadPool.threadCount to something low. Then execute more jobs than the threadCount. QuartzScheduler will create threads until it reaches threadCount. So you end up with two sets of jobs. A set with Threads, that are running, and Rundeck reports them as RUNNING. And another set that do not have threads, that are "queued" up in QuartzScheduler, are not running, and Rundeck reports them as RUNNING.

If you abort a job from the second set, Rundeck will look for the job using QuartzScheduler's getCurrentlyExecutingJobs() method, which only returns jobs from the first set.

https://github.com/rundeck/rundeck/blob/development/rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy#L1124
and 
https://github.com/rundeck/rundeck/blob/development/rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy#L652

So, if I read this correctly, Rundeck decides that since it couldn't find the job in QuartzScheduler, the job must have already finsihed and marks it as cancelled and the job appears to be aborted.

Later as jobs in the first set complete, QuartzScheduler creates new threads for jobs in the second set (until it reaches threadCount of course) and starts them executing.

This will end up executing the "queued" job we thought we aborted!

You can replicate this by setting quartz.props.threadPool.threadCount to something low (like 1), executing a series of jobs (like 10) that run 'sleep 120' or some long-running process, then aborting some of the later jobs. You should see that all of your jobs will end up with execution logs, even the ones you aborted.

Instead of QuartzScheduler's getCurrentlyExecutingJobs() method. Rundeck should use getJobGroupNames() and getJobKeys() to iterate through all jobs, queued or not. Then call interruptJob() to try and kill a running job, failing that call deleteJob() to remove a queued job.

QuartzDocs show how to iterate through all jobs: http://quartz-scheduler.org/documentation/quartz-2.x/cookbook/ListJobs

**Comment by chrispynacho** [comment]
I am trying to put together a test to verify this. But I need a little guidance on how to best set up the test. Mostly because I want to change the Quartz threadCount to 1, which would require restarting Rundeck.
I'm thinking of creating a test similar to https://github.com/rundeck/rundeck/blob/development/test/api/test-execution-abort.sh that sets the threadCount and restarts Rundeck. But the test needs to know more about the Rundeck instance and have privileges to change the config and restart Rundeck. And it needs to wait until rundeck is responsive again as well.

**Comment by chrispynacho** [comment]
(whoops hit the wrong button)
If I went with a lower-level test, mocking out the behavior of quartzScheduler... I run into a problem of the main logic of aborting an execution in various states being in ExecutionService, but the reference to the scheduler being in ScheduledExecutionService.
Any guidance of where to put our tests would be helpful.

**Comment by gschueler** [comment]
@chrispynacho i assume you would change the interruptJob method in ScheduledExecutionService? i think you'd add a failing test of that method that reveals the incorrect behavior
