### ISSUE TITLE
Stepping stone control.

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#154]
- Issue Type: Feature
- Rundeck version: Any

---

Issue:

On occasion it is necessary to use ssh twice, from one remote machine to another. Currently RunDeck's full functionality is only of use on the nearby machine.

It'd be nice to be able to provide RunDeck with a list of authentication credentials for the "stepping stones" to a multiply remote ssh Host, and use RunDeck as normal.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/535)

Original Creator: Hasan

**Comment by ahonor** [comment]
Can use bastion hot node executor for this.
