### ISSUE TITLE
Job never ends when salt-minion agent is down

### ISSUE THREAD

**Issue by albertmfb** [rundeck/rundeck#1548]
Good morning,

i notice that executing a job when the salt-minion agent is down on a node causes that the job never ends (it stays in an indefinite state of execution)

Any ideas to prevent this problem?
Any helpwould be appreciated.

product versions:

rundeck-2.6.1-1.12
salt-master-2015.8.0-2.el6.noarch
salt-minion-2015.8.0-2.el6.noarch
salt-api-2015.8.0-2.el6.noar

**Comment by gschueler** [comment]
are you using the salt plugin? this sounds like an issue with the plugin not timing out

**Comment by albertmfb** [comment]
yes, i am using rundeck-salt-plugin-0.3.jar.

Is it possible to configure timeout specifically for this plugin? It seems that the job timeout is ignored in this case..

Regards.

**Comment by albertmfb** [comment]
updating saltstack master and salt api has solved the problem.

salt-api-2015.8.1-1.el6.noarch
salt-master-2015.8.1-1.el6.noarch

Now, the job finishes by timeout.

Thanks.
