### ISSUE TITLE
Possible missing dependency on libpam0g-dev (Ubuntu 14.04/deb package 2.6.1)

### ISSUE THREAD

**Issue by arielsalvo** [rundeck/rundeck#1549]
Trying to setup pam authentication for rundeck, I came across a missing link (libpam.so -> libpam.so.0)

Adding it manually seemed to do the trick, but later found out the link is actually provided by libpam0g-dev.

Should this package be added as a dependency for rundeck?

**Comment by gschueler** [comment]
hmm, sounds like it might be necessary
