### ISSUE TITLE
Feature Request: web api should have same ACL as the api token user

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#1550]
Rundeck 2.6.1.0-SNAPSHOT

I'm trying to create a hubot-rundeck, and found that when interacting with rundeck through web api, only one group is allowed: 'api_token_group'.

Basically this means I cannot implement a hubot interface with web api, since ACL is limited to a single group.

Is there any reason why web api cannot simply share the same ACL as the token owner?

**Comment by davewongillies** [comment]
I'd love to know about this too :+1:

**Comment by gschueler** [comment]
it would be possible to add this kind of behavior for tokens.  the reasons it currently does not work this way:

* user authorization roles are determined by the authentication method (e.g. LDAP) each time a user logs in, and is not accessible to Rundeck outside of a user login session, so Rundeck can't dynamically "look up" what roles a user/token should be given
* we could store the user role list when generating the token, but it's brittle/potentially a security issue:
    1. roles may change, i.e. a user may have some auth role added/removed, which won't be known to Rundeck
    2. a user may be removed from LDAP, e.g. no longer a valid user or no longer allowed to access rundeck, but since the API token could still be used with the original user roles, the token is still valid while the user can no longer log in.

It could still be useful, but we should make the risks explicit and make it an optional feature.

Some ideas for mitigating these problems;

* add expiration to tokens
* allow admin to determine a super set (whitelist) of allowed token roles.  generating a token would only allow the intersection of that whitelist and the user's roles

In the long term, if Rundeck had its own authentication system (v.s relying on servlet container/jaas as we do now), then we could fix these problems.

**Comment by acasademont** [comment]
This would be really nice. Right now I can only have one set of permissions for API tokens, I would love to give limited API tokens to each project and also have un admin token.

**Comment by hekaldama** [comment]
+1

Feel free to make some notes on this to start us in the right direction for a PR.

**Comment by mbanton** [comment]
+1

**Comment by mnhan3** [comment]
+1

**Comment by lusis** [comment]
At this point, I can see a few simple things that would be a happy medium:

- Support the concept of user vs admin token groups
- Allow non-user associated tokens in some fashion

It might be "nice" if the policy could follow the token in a sense as well if that makes sense.

**Comment by willemdh** [comment]
The suggestion of @lusis  would be a minimum requirement to get some security with authentication tokens. 

+1

**Comment by BobVanB** [comment]
+1

**Comment by doug2525** [comment]
+1

**Comment by datinho** [comment]
+1

**Comment by oberon1900** [comment]
+1

**Comment by warmfusion** [comment]
This is a pretty serious deal breaker for our use of RunDeck.

We are looking to trigger a RunDeck job from a CI build on particular projects, but if we're expected to issue an API key that is able to execute _any_ job across the whole environment as API keys are effectively given the same permissions its basically pointless having API tokens at all.

Tokens are associated with users - as can be seen [here](http://rundeck.org/docs/api/index.html#get-a-token) but this seems pointless, so why not associate api tokens with groups at the time the token is created by the user.

Tokens could be considered as though they were users in their own right, with RunDeck managing the relationship between token and access groups.

**Comment by ahonor** [comment]
@warmfusion understood. You will be happy to know we are working on solving that problem now and will be in the next rundeck release.

**Comment by sumpfgottheit** [comment]
That's great news! ACLs/Group-Memberhip for API-Tokens are very welcome here. Keep up the good work!
