### ISSUE TITLE
unable to select a default node to run jobs against

### ISSUE THREAD

**Issue by ssbarnea** [rundeck/rundeck#1551]
I already asked about this at http://stackoverflow.com/questions/33740402/how-to-configure-a-default-node-to-execute-rundeck-commands-against but my impression is that there is a lack of subscriptions to the "rundeck" tag on stackoverflow, at least for the moment.

The use-case is very simple: as a rundeck project admin I do want to enable people to run custom commands inside the project without having them to always select the node they have to run them against. We use a single node which means that the entire node selection feature becomes an anti-feature. 

If we would be able to define a default-node per project, this would prevent this issue from occurring.

**Comment by ctgaff** [comment]
Unless I am misunderstanding your question, this would be done with:

1) making sure you select "target nodes are selected by default" within the job definition
2) add your node(s) to "matched nodes" via the "node filter"

Now when the job is executed, the node(s) will be automatically selected.

**Comment by ssbarnea** [comment]
I think you misunderstand the question: that's a request to allow us to configure a default node (preselected) when we click the command tab. This must be configured per project.

**Comment by rasebo** [comment]
Ah, yeah, I don't think that's currently supported, unless it's hidden somewhere. 

I think this would be a good feature, as we sometimes have a master or testing node in a project where we want to run some commands that are not yet defined as standalone jobs.

**Comment by ahonor** [comment]
Another idea would be to define a saved node filter which can be used inside the Command tab
