### ISSUE TITLE
Console output is not wrapped making impossible to see long lines

### ISSUE THREAD

**Issue by ssbarnea** [rundeck/rundeck#1558]
It seems that the web console output does not wrap lines and due to this is practically impossible to see the output of the long lines (imagine lines that can have 10k+ characters).

This seems to be cause by this CSS code `white-space: pre;` when instead it should only use: `pre-wrap` as specified in http://www.w3schools.com/cssref/pr_text_white-space.asp

**Comment by rootAmeen** [comment]
Could you please push this update to the yum repo? Thanks.

**Comment by gschueler** [comment]
@rootAmeen this will be included in 2.6.3 release which is forthcoming
