### ISSUE TITLE
OSX RDECK_BASE not set or does not exist

### ISSUE THREAD

**Issue by matthewferguson694** [rundeck/rundeck#1562]
Hi All :)

I am trying to build a rundeck server on OS X 10.10 here, I can't get past this issue.  Its probably something easy for you guys to answer, but I would really appreciate some help :)

'''✔  mferguson 23/Nov/15  ~/rundeck/server/sbin
15:46 $ ./rundeckd
RDECK_BASE not set or does not exist
✘-1  mferguson 23/Nov/15  ~/rundeck/server/sbin
15:47 $ ll
total 24
drwxr-xr-x   4 mferguson  staff   136 Nov 23 15:42 .
drwxr-xr-x  10 mferguson  staff   340 Nov 23 15:39 ..
-rw-r--r--@  1 mferguson  staff  6148 Nov 23 15:42 .DS_Store
-rwxr-xr-x   1 mferguson  staff  3350 Nov 23 15:38 rundeckd
'''

Thanks!

**Comment by penekk** [comment]
You need to set base directory variable, either as an environment or within the script (and if im not wrong, it should have been done by the installer). If you're doing a manual setup, you can try initializing basedir by running the launcher directly from .jar

**Comment by matthewferguson694** [comment]
I defined it as an environmental variable, I then restarted my terminal emulator, still no luck

✘-1  mferguson 24/Nov/15  ~/rundeck/server/sbin
18:40 $ tail ~/.bash_profile

RDECK_BASE="/Users/mferguson/rundeck"

✔  mferguson 24/Nov/15  ~/rundeck/server/sbin
18:40 $  ./rundeckd
RDECK_BASE not set or does not exist

Is Rundeck support on OS X?  Its been tough getting this far haha!

**Comment by ahonor** [comment]
Rundeck is developed and tested on OS X. You will need to export RDECK_BASE in your bash profile.
