### ISSUE TITLE
context variable job.group returns groupPath instead of group

### ISSUE THREAD

**Issue by boudekerk** [rundeck/rundeck#1565]
Hi,

in the job context I'd like to be able to get the current group, but job.group returns the groupPath, not the group. I.e. with a job in a nested group like "A/B/myjob", I'd expect ${job.group} to return B, not A/B.
Is this assumption correct? If not, how to get the actual group?

Kind regards,
Bartosz

**Comment by ahonor** [comment]
Hi @boudekerk, it's correct that it does return the full group path. You'll have to use some script to get the "basename" of the group path.
