### ISSUE TITLE
can't ssh to any node (ssh works fine without password from CLI with users 'root' & 'rundeck' )

### ISSUE THREAD

**Issue by haimari** [rundeck/rundeck#1566]
Using "privateKey", but getting this error

[workflow] beginExecuteNodeStep(va-vpc-i-0ba2c1bb.domain.com): NodeDispatch: com.dtolabs.rundeck.execution.ExecutionItemFactory$4@79d19eac
22:30:54    Using ssh keyfile: /root/.ssh/id_rsa
22:30:54    Starting SSH Connection: ec2-user@ (va-vpc-i-0ba2c1bb.domain.com)
22:30:54    ssh-agent started with ttl 20
22:30:54    ssh-agent used as identity repository.
22:30:54    Using private key file: /root/.ssh/id_rsa
22:30:54    Set timeout to 0
22:30:54    Connecting to :22
22:30:54    Authentication failure connecting to node: "va-vpc-i-0ba2c1bb.domain.com". Password incorrect.
22:30:54    Failed: AuthenticationFailure: Authentication failure connecting to node: "va-rtb-adplatform-vpc-i-0ba2c1bb.domain.com". Password incorrect.

**Comment by gschueler** [comment]
if you are using the ec2 plugin, and you don't want to connect as user `ec2-user` (the default), change the mapping config https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin#configuring-the-mapping

    username.default=rundeck
