### ISSUE TITLE
Combine SSH password and SSH Key passphrase?

### ISSUE THREAD

**Issue by jyaworski** [rundeck/rundeck#1567]
Hello:

I have a use-case where I would like to take advantage of newer SSH features that allow a sort of 2FA with ssh keys and ssh passwords. Per http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html#authentication-types it seems like it's password XOR key, and you can't combine them.

Can this be added?

Links:

http://security.stackexchange.com/questions/17931/possible-to-use-both-private-key-and-password-authentication-for-ssh-login

http://unix.stackexchange.com/questions/231314/how-do-i-configure-sshd-to-1-require-public-key-and-2-require-a-password-for/231375#231375

**Comment by jyaworski** [comment]
To add to this, we will be using 2FA for box access, and 3FA for root access with sudo and http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html#secondary-sudo-password-authentication.

This would significantly improve our security posture.

**Comment by gschueler** [comment]
Rundeck uses Jsch for SSH, so if it is supported by Jsch it could be added. Alternately, a script-based SSH plugin (like [this example](https://github.com/rundeck/rundeck/tree/development/examples/ssh-script-plugin) ) using the system openssh could perhaps be made to work that way

**Comment by menathor** [comment]
Hello

I see this is still open. Did anyone figure out a way of doing this using the built in ssh plugin rather than having to script it to use openssh? I agree with @jyaworski - being able to set "AuthenticationMethods publickey,password" in sshd_config in newer ssh versions (to force both a key AND a password) is much more secure.
