### ISSUE TITLE
Multi-Factor authentication for web login?

### ISSUE THREAD

**Issue by jyaworski** [rundeck/rundeck#1568]
Hello:

Can multi-factor authentication for the web UI be worked on? Something like Duo Mobile / Google Authenticator plus LDAP credentials, etc?

**Comment by boudekerk** [comment]
Yubikey :-)
U2F?

**Comment by jyaworski** [comment]
Whatever works. Some 2FA solution.

**Comment by paradoxbound** [comment]
Really want an option for 2FA ideally Google Authenticator

**Comment by isuftin** [comment]
+1 - This is a blocker for running Rundeck within our data center at a larger scale right now. We have no good way of performing ADFS/SAML auth.

**Comment by gschueler** [comment]
Right now the solution would need to involve using Apache/nginx or some other front end as a proxy.  Configure it to use multifactor authentication, and configure Rundeck in "preauthenticated" mode

**Comment by paradoxbound** [comment]
We would like to see this baked in or a plugin, currently using HAproxy as front end and it is not possible there.

**Comment by hibiitt** [comment]
Yes, please this is a needed feature for larger corporations. Especially for technicians who need to work from home.

**Comment by spirrello** [comment]
Is there any update on this feature request?

**Comment by jgibbarduk** [comment]
+1

**Comment by spirrello** [comment]
+10

**Comment by dimare27** [comment]
+1

**Comment by sksirajbasha** [comment]
is this available in rundeck 3.0 ? I noticed an extended LDAP module with PAM support.

**Comment by sksirajbasha** [comment]
@gschueler can you confirm is this is similar to SSO option provided in rundeck 3.0 ?

**Comment by paulholden** [comment]
@gschueler [wrote](https://github.com/rundeck/rundeck/issues/1568#issuecomment-257603759):
> Right now the solution would need to involve using Apache/nginx or some other front end as a proxy. Configure it to use multifactor authentication, and configure Rundeck in "preauthenticated" mode

This would involve using [these instructions](https://rundeck.org/docs/administration/security/authenticating-users.html#preauthenticated-mode) to move the responsibility for authentication to the reverse proxy, correct?

@paradoxbound [wrote](https://github.com/rundeck/rundeck/issues/1568#issuecomment-257561729):
> Really want an option for 2FA ideally Google Authenticator

There is a request for a Google Authenticator Apache module at https://github.com/google/google-authenticator/issues/25 - I guess this could be used in conjunction with Rundeck's "preauthenticated" mode as mentioned above.

[Instructions here](https://www.techrepublic.com/blog/australian-technology/pairing-apache-and-google-authenticator/) describe how this should work in principal.

**Comment by I12crash** [comment]
MFA is still very much a thing, and I would love to see this addressed.

**Comment by alexbartok** [comment]
+1
Would like to see 2FA integration as well.

**Comment by marktongarcia** [comment]
+1
I'm introducing rundeck to our company after testing it in a lab. but not being able to support yubi-key 2fa is a show stopper.

**Comment by I12crash** [comment]
If anyone is interested, I did get 2FA working on Rundeck with Duo using their proxy LDAP. Here's some more info. This will work with their free tier: https://duo.com/docs/ldap

**Comment by fdevans** [comment]
Thank you for the feedback/request for this feature.  The Rundeck Product Team has added this to their internal request list and will research options and prioritize accordingly.  Thank you @I12crash for the workaround suggestion.  There are also MFA options available through our Okta and Ping Identity plugins available in the Enterprise version of Rundeck.

**Comment by 3e-maciej** [comment]
what is the status of 2fa in rundeck? will it be available in community version?

**Comment by fdevans** [comment]
This is available in our Commercial versions of Rundeck. We don't have plans to add it to Open Source.

**Comment by joe-speedboat** [comment]
Duo or FreeIPA work as expected with 2FA.
I see no point to implement 2FA in every application itself.
We use: AWX, Rundeck, Zabbix, Graylog, Gitea, Guacamole (was a bit tricky) ... everything with 2FA over FreeIPA (which you can connect to AD if you like).
I never looked back and we passed every Audit
