### ISSUE TITLE
Very slow GUI

### ISSUE THREAD

**Issue by usualstuff** [rundeck/rundeck#1570]
Hello,
When I click basically on every link, it takes about 10 seconds for page to load.
My best guess that most amount of time is spent in ACL evaluations.

Here auth.log for URL request that just shows a job:
http://pastebin.com/6HyK8N6j

As you can see, it takes 15 seconds to do this. Is there a solution to this problem?
Thanks!

admin.aclpolicy: http://pastebin.com/27brXKbd
profile: http://pastebin.com/i5nLeYxg
system info: http://pastebin.com/g3YaxCza

**Comment by kino71** [comment]
Hello, 
are your projects on file or db ?
rundeck.projectsStorageType=db/file 

I'm facing something similar while migrating from project storage file to db.
At first I thought it was the ACL (https://github.com/rundeck/rundeck/issues/1539)
Now, I'm investigating into the content of the table scheduled_execution which I cannot explain and seems involved in my issue.

thanks

**Comment by usualstuff** [comment]
Hello.

I haven't changed that, projects are stored in file. 
What kernel version in your environment? I suspect that this could be related.

**Comment by kino71** [comment]
I'm on Solaris, using java 1.7.0_72

**Comment by usualstuff** [comment]
Nope. Tried fresh ubuntu install: same 10-15 secs on every refresh.

**Comment by kino71** [comment]
Eventually I sorted my issue out by changing jdbc driver.
I'll update issue #1545 to share the solution.

**Comment by usualstuff** [comment]
Thank you, Kino. I can confirm that: after I connected rundeck to mysql db, the GUI started to worked as expected.

regards,
Alex
