### ISSUE TITLE
Possibility to occult options to clients in rundeck jobs

### ISSUE THREAD

**Issue by albertmfb** [rundeck/rundeck#1571]
When using salt-step to execute jobs in rundeck via saltstack it is necessary to configure the salt_user and salt_password options in jobs.

Is the any way to occult to a client these two parameters from the jobs configured in rundeck configuration?

Until now, these parameters are visible to them and it is not necessary.
Thanks in advance.

**Comment by albertmfb** [comment]
Good morning,
on this subject, the only way that i found until now is to do 2 jobs, 

one with salt_user and salt_password options, and another one (offered to the final users), that calls the first, so on this way to users dont see the options.

Do you know another option more easily to do this?
Any information would be appreciated.

Thanks.

**Comment by ahonor** [comment]
The salt-step should make the user and password config properties. Please submit a request to https://github.com/rundeck-plugins/salt-step
