### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by sebw** [rundeck/rundeck#1573]
Hi,

After upgrading to 2.6.1 from 2.5.1 (on RHEL6), I get "too many open files" error on a daily basis.

`# grep 'open file' /var/log/rundeck/service.log  | wc -l
9579`

I have been running Rundeck for 2.5 years and have always been running the default nofile limit (1024). After upgrading and after the first errors, I raised to 4096, and now I'm running rundeck with 8192 limit.

```
com.dtolabs.rundeck.core.plugins.PluginException: java.io.FileNotFoundException: /var/lib/rundeck/var/tmp/pluginJars/20151024013440000-rundeck-flow-control-plugin-2.6.1.jar (Too many open files)
Caused by: java.io.FileNotFoundException: /var/lib/rundeck/var/tmp/pluginJars/20151024013440000-rundeck-flow-control-plugin-2.6.1.jar (Too many open files)
ERROR URLResourceModelSource: Error requesting URL Resource Model Source: https://rundeck.example.org/rundeck_itop_resource.php: Unable to get and write file: /var/lib/rundeck/var/urlResourceModelSourceCache/example/ead4cf6b8f3a2d5916dd103afb940ad0a515a58e.temp (Too many
 open files)
com.dtolabs.rundeck.core.common.UpdateUtils$UpdateException: Unable to get and write file: /var/lib/rundeck/var/urlResourceModelSourceCache/example/ead4cf6b8f3a2d5916dd103afb940ad0a515a58e.temp (Too many open files)
Caused by: java.io.FileNotFoundException: /var/lib/rundeck/var/urlResourceModelSourceCache/example/ead4cf6b8f3a2d5916dd103afb940ad0a515a58e.temp (Too many open files)
ERROR URLResourceModelSource: Error requesting URL Resource Model Source: https://rundeck.example.org/rundeck_itop_resource.php: Unable to get and write file: /var/lib/rundeck/var/urlResourceModelSourceCache/example/ead4cf6b8f3a2d5916dd103afb940ad0a515a58e.temp (Too many
 open files)
com.dtolabs.rundeck.core.common.UpdateUtils$UpdateException: Unable to get and write file: /var/lib/rundeck/var/urlResourceModelSourceCache/example/ead4cf6b8f3a2d5916dd103afb940ad0a515a58e.temp (Too many open files)
Caused by: java.io.FileNotFoundException: /var/lib/rundeck/var/urlResourceModelSourceCache/example/ead4cf6b8f3a2d5916dd103afb940ad0a515a58e.temp (Too many open files)
ERROR URLResourceModelSource: Error requesting URL Resource Model Source: https://rundeck.example.org/rundeck_itop_resource.php: Unable to get and write file: /var/lib/rundeck/var/urlResourceModelSourceCache/example/ead4cf6b8f3a2d5916dd103afb940ad0a515a58e.temp (Too many
 open files)
com.dtolabs.rundeck.core.common.UpdateUtils$UpdateException: Unable to get and write file: /var/lib/rundeck/var/urlResourceModelSourceCache/example/ead4cf6b8f3a2d5916dd103afb940ad0a515a58e.temp (Too many open files)
Caused by: java.io.FileNotFoundException: /var/lib/rundeck/var/urlResourceModelSourceCache/example/ead4cf6b8f3a2d5916dd103afb940ad0a515a58e.temp (Too many open files)
Caused by: java.io.FileNotFoundException: /var/lib/rundeck/logs/rundeck/example/job/d8aa8bdd-282d-4a95-9f5d-88eacf2956df/logs/663952.rdlog (Too many open files)
Caused by: java.io.FileNotFoundException: /var/lib/rundeck/logs/rundeck/example/job/d8aa8bdd-282d-4a95-9f5d-88eacf2956df/logs/663952.rdlog (Too many open files)
Caused by: java.io.FileNotFoundException: /var/lib/rundeck/logs/rundeck/example/job/fd066d1b-5aad-408c-a893-26190d9a4f6c/logs/663953.rdlog (Too many open files)
Caused by: java.io.FileNotFoundException: /var/lib/rundeck/logs/rundeck/example/job/fd066d1b-5aad-408c-a893-26190d9a4f6c/logs/663953.rdlog (Too many open files)
```

I will try to downgrade.

**Comment by mathieuchateau** [comment]
Hello,

can you install and do lsof on rundeck process to see what files are
actually opened?
It may help narrow issue.


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-11-30 9:53 GMT+01:00 Sébastien Wains <notifications@github.com>:

**Comment by sebw** [comment]
Unfortunately this is my production instance, so I quickly had to restart it.

I ran lsof last week and noticed that rundeck was keeping a lock on deleted files. I'll run the command again if that happens again.

**Comment by sebw** [comment]
I just run lsof, Rundeck has been running since yesterday

```
# lsof  -n | grep rundeck | grep deleted | wc -l
3170

# lsof  -n | grep rundeck | grep deleted
[...]
java      35073    rundeck 3355r      REG               8,17   2012214    2379954 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/org.eclipse.jgit-3.7.1.201504261725-r.jar (deleted)
java      35073    rundeck 3356r      REG               8,17    125146    2379955 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/JavaEWAH-0.7.9.jar (deleted)
java      35073    rundeck 3357r      REG               8,17    352585    2379956 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/httpclient-4.1.3.jar (deleted)
java      35073    rundeck 3358r      REG               8,17    181410    2379957 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/httpcore-4.1.4.jar (deleted)
java      35073    rundeck 3359r      REG               8,17     58160    2379960 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/commons-codec-1.4.jar (deleted)
java      35073    rundeck 3361r      REG               8,17   2761258    2379961 /mnt/data/rundeck/var/tmp/pluginJars/20151024013440000-rundeck-git-plugin-2.6.1.jar (deleted)
java      35073    rundeck 3362r      REG               8,17      9525    2379958 /mnt/data/rundeck/var/tmp/pluginJars/20151024013440000-rundeck-orchestrator-plugin-2.6.1.jar (deleted)
java      35073    rundeck 3363r      REG               8,17     16138    2379959 /mnt/data/rundeck/var/tmp/pluginJars/20151024013440000-rundeck-script-plugin-2.6.1.jar (deleted)
java      35073    rundeck 3364r      REG               8,17   2012214    2379963 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/org.eclipse.jgit-3.7.1.201504261725-r.jar (deleted)
java      35073    rundeck 3366r      REG               8,17    125146    2379964 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/JavaEWAH-0.7.9.jar (deleted)
java      35073    rundeck 3367r      REG               8,17    352585    2379965 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/httpclient-4.1.3.jar (deleted)
java      35073    rundeck 3368r      REG               8,17    181410    2379966 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/httpcore-4.1.4.jar (deleted)
java      35073    rundeck 3369r      REG               8,17     58160    2379971 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/commons-codec-1.4.jar (deleted)
java      35073    rundeck 3370r      REG               8,17      9525    2379967 /mnt/data/rundeck/var/tmp/pluginJars/20151024013440000-rundeck-orchestrator-plugin-2.6.1.jar (deleted)
java      35073    rundeck 3373r      REG               8,17     16138    2379968 /mnt/data/rundeck/var/tmp/pluginJars/20151024013440000-rundeck-script-plugin-2.6.1.jar (deleted)

# cd /mnt/data/rundeck/var/tmp/pluginJars/
# ls -l
total 5248
-rw-rw-r--. 1 rundeck rundeck    3906 Dec  1 16:05 20151024013440000-rundeck-copyfile-plugin-2.6.1.jar
-rw-rw-r--. 1 rundeck rundeck    2301 Dec  1 16:05 20151024013440000-rundeck-flow-control-plugin-2.6.1.jar
-rw-rw-r--. 1 rundeck rundeck 2761258 Dec  1 16:05 20151024013440000-rundeck-git-plugin-2.6.1.jar
-rw-rw-r--. 1 rundeck rundeck 2546868 Dec  1 16:05 20151024013440000-rundeck-jasypt-encryption-plugin-2.6.1.jar
-rw-rw-r--. 1 rundeck rundeck    6075 Dec  1 16:05 20151024013440000-rundeck-job-state-plugin-2.6.1.jar
-rw-rw-r--. 1 rundeck rundeck    3473 Dec  1 16:05 20151024013440000-rundeck-localexec-plugin-2.6.1.jar
-rw-rw-r--. 1 rundeck rundeck    9525 Dec  1 16:05 20151024013440000-rundeck-orchestrator-plugin-2.6.1.jar
-rw-rw-r--. 1 rundeck rundeck   16138 Dec  1 16:05 20151024013440000-rundeck-script-plugin-2.6.1.jar
-rw-rw-r--. 1 rundeck rundeck    9531 Dec  1 16:05 20151024013440000-rundeck-stub-plugin-2.6.1.jar

# ls -l /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/httpclient-4.1.3.jar
-rw-rw-r--. 1 rundeck rundeck 352585 Dec  1 16:10 /mnt/data/rundeck/libext/cache/rundeck-git-plugin-2.6.1/lib/httpclient-4.1.3.jar
```

**Comment by mathieuchateau** [comment]
Hello,

on my side, restarted yesterday too:

lsof -n | grep rundeck | wc -l
35356

lsof -n | grep rundeck | grep deleted | wc -l
684

But when checking for rundeck process (cat /proc/PID/limits), limit is
still 4096:
Limit                     Soft Limit           Hard Limit           Units
Max open files            4096                 4096                 files

mem entries from lsof can be ignored as it's for shared library.

If I do my usual way:
lsof -p PID | wc -l
I only have 496 entries, which looks much more real against 4096 limit.



Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-12-01 16:12 GMT+01:00 Sébastien Wains <notifications@github.com>:

**Comment by sebw** [comment]
I think it all depends on how many jobs are scheduled.

I have 183 jobs, most of them are scheduled and have about 1700 executions every day.

**Comment by mathieuchateau** [comment]
It may also depends if execution are local and opening themselves files
(reading logs & co).
I have 1294 executions per days.

What number do you get if doing like me lsof -p PID |wc -l ?


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-12-02 9:29 GMT+01:00 Sébastien Wains <notifications@github.com>:

**Comment by sebw** [comment]
# lsof -p 21601 | wc -l
1839

# lsof -p 21601 | grep deleted | wc -l
702

**Comment by marek-knappe** [comment]
We have the same problem:

{code}
....
java      12251 12776  rundeck  273r      REG              253,2    352585                42018 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/httpclient-4.1.3.jar (deleted)
java      12251 12776  rundeck  274r      REG              253,2    181410                42019 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/httpcore-4.1.4.jar (deleted)
java      12251 12776  rundeck  275r      REG              253,2      9526              8409139 /var/lib/rundeck/var/tmp/pluginJars/20151203063144000-rundeck-orchestrator-plugin-2.6.2.jar (deleted)
java      12251 12776  rundeck  276r      REG              253,2     16138              8409141 /var/lib/rundeck/var/tmp/pluginJars/20151203063144000-rundeck-script-plugin-2.6.2.jar (deleted)
java      12251 12776  rundeck  277r      REG              253,2      9533              8409143 /var/lib/rundeck/var/tmp/pluginJars/20151203063144000-rundeck-stub-plugin-2.6.2.jar (deleted)
java      12251 12776  rundeck  278r      REG              253,2   2012214              2250664 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/org.eclipse.jgit-3.7.1.201504261725-r.jar (deleted)
java      12251 12776  rundeck  279r      REG              253,2     58160                42020 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/commons-codec-1.4.jar (deleted)
java      12251 12776  rundeck  280r      REG              253,2    125146              2250665 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/JavaEWAH-0.7.9.jar (deleted)
java      12251 12776  rundeck  281r      REG              253,2    352585              2250666 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/httpclient-4.1.3.jar (deleted)
java      12251 12776  rundeck  282r      REG              253,2    181410              2250667 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/httpcore-4.1.4.jar (deleted)
java      12251 12776  rundeck  283r      REG              253,2     58160              2250668 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/commons-codec-1.4.jar (deleted)
java      12251 12776  rundeck  286r      REG              253,2      9526              8409147 /var/lib/rundeck/var/tmp/pluginJars/20151203063144000-rundeck-orchestrator-plugin-2.6.2.jar (deleted)
java      12251 12776  rundeck  287r      REG              253,2     16138              8409148 /var/lib/rundeck/var/tmp/pluginJars/20151203063144000-rundeck-script-plugin-2.6.2.jar (deleted)
java      12251 12776  rundeck  288r      REG              253,2      9533              8409149 /var/lib/rundeck/var/tmp/pluginJars/20151203063144000-rundeck-stub-plugin-2.6.2.jar (deleted)
java      12251 12776  rundeck  289r      REG              253,2   2012214              4251844 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/org.eclipse.jgit-3.7.1.201504261725-r.jar (deleted)
java      12251 12776  rundeck  290r      REG              253,2    125146              4251869 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/JavaEWAH-0.7.9.jar (deleted)
java      12251 12776  rundeck  291r      REG              253,2    352585              4251873 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/httpclient-4.1.3.jar (deleted)
java      12251 12776  rundeck  292r      REG              253,2    181410              4251900 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/httpcore-4.1.4.jar (deleted)
java      12251 12776  rundeck  293r      REG              253,2      9526              8409153 /var/lib/rundeck/var/tmp/pluginJars/20151203063144000-rundeck-orchestrator-plugin-2.6.2.jar (deleted)
java      12251 12776  rundeck  294r      REG              253,2     16138              8409155 /var/lib/rundeck/var/tmp/pluginJars/20151203063144000-rundeck-script-plugin-2.6.2.jar (deleted)
java      12251 12776  rundeck  295r      REG              253,2      9533              8409156 /var/lib/rundeck/var/tmp/pluginJars/20151203063144000-rundeck-stub-plugin-2.6.2.jar (deleted)
java      12251 12776  rundeck  296r      REG              253,2   2761849              8409172 /var/lib/rundeck/var/tmp/pluginJars/20151203063144000-rundeck-git-plugin-2.6.2.jar (deleted)
java      12251 12776  rundeck  297r      REG              253,2     58160              4252802 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/commons-codec-1.4.jar (deleted)
java      12251 12776  rundeck  298r      REG              253,2   2012214              8409160 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/org.eclipse.jgit-3.7.1.201504261725-r.jar (deleted)
java      12251 12776  rundeck  299r      REG              253,2    125146              8409161 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/JavaEWAH-0.7.9.jar (deleted)
java      12251 12776  rundeck  300r      REG              253,2    352585              8409162 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.2/lib/httpclient-4.1.3.jar (deleted)
....
{code}

# lsof | grep delete | wc -l
6650

**Comment by ahonor** [comment]
the open plugin jar files was addressed in recent release
