### ISSUE TITLE
Child job notifications don't trigger

### ISSUE THREAD

**Issue by johnpaularthur** [rundeck/rundeck#1574]
If you have notifications enabled for child jobs, they do not trigger.  Only the 1st parent job triggers notification.  So we have no idea, until we dig into logs, what child job has failed.

Example, I have notification set for all the jobs below.  However, the parent job (job1) is the only job that will send a notification.   Even if job1a2 has notifications set, it will not send if it is called by a parent job.  To be clear, job1 will capture the failure of job1a2 and send a notification.   But I am looking to capture the success and failure notification of each child job.

job1
->job1a
--->job1a1
--->job1a2
->job1b
->job1c

**Comment by johnpaularthur** [comment]
Also as an FYI.   If I call the same child job as a script step from the parent job (i.e. /rundeckinstall/tools/bin/run -p "Projectname" -j "Test/Bad Job Run")  it will send a notification.   So something about defining the step as a "Job Reference" as opposed to "Script" disables notifications.

**Comment by jmkent** [comment]
This has been an ongoing pain point for us as we have a lot of chained jobs in general and would like to be able to report on incremental progress out of the box (especially when you have lengthy multi-step ETL --> Rebuild model chains).

Would be great to be able to show notifications per child job OR simple add a new workflow item type of a notification item (so we could at least add a notification step for checkpointing in a complex workflow).

**Comment by tuan-phan** [comment]
Please enable notification for child job. Such as I use child job name "Pagerduty trigger", this job use pager-duty notification plugin to trigger event. The parent job will trigger this job if failed. Unhappy It's not working.
