### ISSUE TITLE
Route /api/10/execution/[NN]/state gives a wrong state

### ISSUE THREAD

**Issue by dernotte** [rundeck/rundeck#1575]
Hi,
I have an app that use rundeck as an external execution layer. When I want to run a script I call the run adhoc script API, read the ID of the created job, loop on the /api/10/execution/[NN]/state waiting for the executionState to be different from "running", and then I call the /api/10/execution/[NN]/output/state to get the output. 
Sometimes, the /api/10/execution/[NN]/state route could give a executionState = "SUCCEEDED", and at the same time the /api/10/execution/[NN]/output/state could give the execState = "running" for the same job. 
I'm using Rundeck 2.5.3-1

**Comment by alexisabril** [comment]
This seems to still be an issue, any updates?

**Comment by gschueler** [comment]
the `execution/ID/state` endpoint should be fixed to return the same state as the the output endpoint, or clarified as to what the "executionState" value means.

Basically, the `execution/ID/output` endpoint (and the `execution/ID` endpoint) will have the correct state of the execution as known in the DB, returned in the "execState" value.  
The `execution/ID/state` endpoint "executionState" data value has a slightly different meaning, which indicates the progress of the execution's workflow only.  The workflow might have completed, thus returning "SUCCEEDED", prior to the execution itself finishing (closing output log, updating DB to reflect the "execState").
