### ISSUE TITLE
Issue Trying to Download the Latest RPM

### ISSUE THREAD

**Issue by lmayorga1980** [rundeck/rundeck#1577]
warning: /var/cache/yum/x86_64/7/rundeck-release-bintray/packages/rundeck-2.6.1-1.12.GA.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID e2d1065b: NOKEY
Retrieving key from http://rundeck.org/keys/BUILD-GPG-KEY-Rundeck.org.key

GPG key retrieval failed: [Errno 14] HTTP Error 404 - Not Found
[vagrant@cmserver ~]$ sudo yum install rundeck
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
- base: mirror.solarvps.com
- extras: mirror.us.leaseweb.net
- updates: mirror.pac-12.org
  Resolving Dependencies
  --> Running transaction check
  ---> Package rundeck.noarch 0:2.6.1-1.12.GA will be installed
  --> Processing Dependency: rundeck-config for package: rundeck-2.6.1-1.12.GA.noarch
  --> Running transaction check
  ---> Package rundeck-config.noarch 0:2.6.1-1.12.GA will be installed
  --> Finished Dependency Resolution

Dependencies Resolved
# 
#  Package                                                                      Arch                                                                 Version                                                                        Repository                                                                             Size

```
Installing:
 rundeck                                                                      noarch                                                               2.6.1-1.12.GA                                                                  rundeck-release-bintray                                                                94 M
Installing for dependencies:
 rundeck-config                                                               noarch                                                               2.6.1-1.12.GA                                                                  rundeck-release-bintray                                                               9.0 k

Transaction Summary
==============================================================================================================================================================================================================================================================================================================================
Install  1 Package (+1 Dependent package)

Total size: 94 M
Installed size: 126 M
Is this ok [y/d/N]: y
Downloading packages:
warning: /var/cache/yum/x86_64/7/rundeck-release-bintray/packages/rundeck-2.6.1-1.12.GA.noarch.rpm: Header V3 RSA/SHA1 Signature, key ID e2d1065b: NOKEY
Retrieving key from http://rundeck.org/keys/BUILD-GPG-KEY-Rundeck.org.key


GPG key retrieval failed: [Errno 14] HTTP Error 404 - Not Found
```

**Comment by gschueler** [comment]
sorry, there was a rundeck.org site snafu momentarily, please try again

**Comment by ahonor** [comment]
@lmayorga1980 apologies. The key should now be available http://rundeck.org/keys/BUILD-GPG-KEY-Rundeck.org.key
