### ISSUE TITLE
Document how to grant via ACL for Per-Job schedule and execution toggling

### ISSUE THREAD

**Issue by makered** [rundeck/rundeck#1578]
Not sure if I am missing something but I can't find a way of granting ability to toggle job schedule/execution via an ACL policy to a non-admin user.

The user is granted "create,read,update,delete,run,runAs,kill,killAs" for type "job" but is missing "Disable Schedule" and "Disable Execution" options in the GUI.

Thanks

**Comment by gschueler** [comment]
The documentation is missing.  You can grant `toggle_schedule` to allow schedule enable/disable, and `toggle_execution` to allow execution enable/disable.

**Comment by makered** [comment]
Thanks!
