### ISSUE TITLE
The size (8192) given to the column 'json_data' exceeds the maximum allowed for any data type (8000)

### ISSUE THREAD

**Issue by arminioa** [rundeck/rundeck#1579]
Hi Team,

I'm using Microsoft SQL Server for the database. 
After upgrading from 2.5.2 to 2.6.1/2.6.2 I'm getting this error in service.log:

2015-12-04 07:59:40,610 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create table plugin_meta (id numeric(19,0) identity not null, version numeric(19,0) not null, date_created datetime not null, json_data varchar(8192), data_key varchar(255) not null, last_updated datetime not null, project varchar(255) not null, primary key (id))
2015-12-04 07:59:40,612 [main] ERROR hbm2ddl.SchemaUpdate  - The size (8192) given to the column 'json_data' exceeds the maximum allowed for any data type (8000).

Thanks

**Comment by cihatgenc** [comment]
Same issue here. In SQL Server the max size of a varchar is 8000.
Either the size must be changed to 8000 or the sqltype must be set to varchar(max) to be able to work with SQL Server.

I'm not a java developer so not sure how to change this correctly, but issue is in the PluginMeta.groovy file where a maxsize is being set, and no sqltype option.

    static constraints = {
    jsonData(nullable: true, blank: true, maxSize: 8192)
    }
    static mapping = {
    key column: 'data_key'
    }
    Long id
    String key
    String project
    String jsonData  -> **should be something like: jsonData (type: 'string', sqlType: "varchar(max)")**
    Date dateCreated
    Date lastUpdated

Workaround is to create the table manually:

    create table plugin_meta 
    (id numeric(19,0) identity not null
    , version numeric(19,0) not null
    , date_created datetime not null
    , json_data varchar(max)
    , data_key varchar(255) not null
    , last_updated datetime not null
    , project varchar(255) not null
    , primary key (id))

**Comment by gschueler** [comment]
we have some other domain classes using similar fields, but i notice they have a slightly different definition, perhaps we can update the PluginMeta table to match. E.g. for PluginStep:

https://github.com/rundeck/rundeck/blob/development/rundeckapp/grails-app/domain/rundeck/PluginStep.groovy#L11

and

https://github.com/rundeck/rundeck/blob/development/rundeckapp/grails-app/domain/rundeck/PluginStep.groovy#L38
