### ISSUE TITLE
Profile firstName does not accepts accents

### ISSUE THREAD

**Issue by gentunian** [rundeck/rundeck#1581]
Not critical, just information.

First name in the profile section does not allow anything but: `[^[a-zA-Z0-9\s\.,\(\)-]+$]`

Error message:

`Property [firstName] of class [class rundeck.User] with value [Sebastián] does not match the required pattern [^[a-zA-Z0-9\s\.,\(\)-]+$]`

cheers!

**Comment by tudorminator** [comment]
The same pattern is used for last name validation too. Any reason for not accepting unicode?

**Comment by gschueler** [comment]
it should be more accepting
