### ISSUE TITLE
Scheduled jobs reflect new default options' values after several runs

### ISSUE THREAD

**Issue by saimak** [rundeck/rundeck#1583]
I have a job which is scheduled to run every hour. If it's default options' values are modified then the new values are not reflected in the next multiple runs. Rather, they are reflected after several runs. But, if job is manually run in between, new values are picked. Is there any kind of caching in the scheduled jobs for the default parameters?

**Comment by ahonor** [comment]
Can't reproduce. Please reopen if you continue to find this problem in 2.10+
