### ISSUE TITLE
how to check the amount of job runing on one node?

### ISSUE THREAD

**Issue by hustneverland** [rundeck/rundeck#1587]
Is there a way of how to check the amount of job runing on one node?

**Comment by daniel00k** [comment]
There isn't a direct way of getting jobs on nodes but it's possible via API calls. 

1) List currently running executions http://rundeck.org/docs/api/index.html#listing-running-executions

2) For each execution, call the execution state. http://rundeck.org/docs/api/index.html#execution-state

**Comment by ahonor** [comment]
Please reopen if this remains a concern
