### ISSUE TITLE
Rundeck-Plugin-Libs in MANIFEST:MF needs wildcard

### ISSUE THREAD

**Issue by rb8** [rundeck/rundeck#1589]
I am evaluating Rundeck and it sounds very good tool!

But I have a problem: 
I am creating a new plugin that needs more than 100 jars.
When I write MANIFEST file the line "Rundeck-Plugin-Libs" seems can't manage wild card as, for example:
"Rundeck-Plugin-Libs: lib/*.jar"
(eclipse approve this syntax and create correctly the jar plugin)

note:
1)
to write my hundred jar filenames in sequence is not possible:
"Rundeck-Plugin-Libs: lib/name1.jar lib/name2.jar lib/name3.jar  ... lib/name100.jar  "
is not possible. in fact, eclipse show this error: "line too long!"

2)
to write my hundred jar filenames in differente rows is not possible:
"Rundeck-Plugin-Libs: lib/name1.jar \ 
lib/name2.jar \
lib/name3.jar  \
... \
lib/name100.jar  "
is not possible. in fact, eclipse show this error: "invalid header field"

**Comment by ahonor** [comment]
Please reopen if this is still a concern
