### ISSUE TITLE
rundeck-launcher command line option are all broken

### ISSUE THREAD

**Issue by kampka** [rundeck/rundeck#1594]
I was trying out rundeck to automate operations because I heard it was a solid solution, here is what I found whilst trying to install it:

--installonly is basically useless (#599)
--configdir is accepted by the server, but the launcher does not respect it when processing the config templates, this leaving all files in $basedir/server/config or $basedir/etc, so rundeck throws an exception on login and shows a blank page
--sbindir does nothing, aparently. sbin is still copied to $basedir/server/sbin
--bindir places the files in the given directory, but one of the seem usable because they all rely on things like "$RDECK_BASE/etc/<configfiles>" to exist, which cannot work when --configdir is used.
--projectdir does nothing, which bugs me the most because it is supposed to hold non-volatile data, except that it places a h2 database file there which is probably broken (org.h2.jdbc.JdbcSQLException: Feature not supported: "isWrapperFor" [50100-176] in grailsh2.trace.db)
--help is broken because it tells you actually have options, which you don't

This is what I found, and I haven't event started looking at anything functional (and I won't, since this software is clearly not production ready).
Just wanted to let you known what I found so you can improve on it in the future, but seeing that the installer is broken for two years leaves me with little hope.

**Comment by matcornic** [comment]
I have the same issues, especially on configdir and projectdir

**Comment by adragoset** [comment]
This is actually pretty ridiculous.  How are you supposed to update config in a docker container when the install only option on the installer is broken for over 4 years. Now i have to figure out how to start rundeck then stop is update all the configuration then restart it in an entrypoint script in my container.

**Comment by theredcat** [comment]
@gschueler @jtobard We are now in 2019
I've done an installation that seems standard to me and I don't have the expected result :

```
~# addgroup --gid 819 rundeck
~# adduser --home /var/lib/rundeck --uid 819 --gid 819 rundeck
~# mkdir /var/lib/rundeck /etc/rundeck  /usr/share/rundeck
~# chown rundeck.rundeck /usr/share/rundeck/ /etc/rundeck /var/lib/rundeck
~# su -s /bin/bash - rundeck
~$ cd /usr/share/rundeck/
~$ wget https://dl.bintray.com/rundeck/rundeck-maven/rundeck-3.0.13-20190123.war
~$ /usr/bin/java -jar /usr/share/rundeck/rundeck-3.0.13-20190123.war --basedir /var/lib/rundeck/ --configdir /etc/rundeck --installonly -d
# Here is the problem...
VERBOSE: {rdeck.base=/var/lib/rundeck/, server.https.port=4443, rundeck.server.configDir=/etc/rundeck, # {truncated}
VERBOSE: Extracting bin scripts to: /var/lib/rundeck//tools/bin ...
VERBOSE: Writing config file: /var/lib/rundeck/server/config/rundeck-config.properties
VERBOSE: Writing config file: /var/lib/rundeck/server/config/log4j.properties
VERBOSE: Writing config file: /var/lib/rundeck/server/config/realm.properties
VERBOSE: Writing config file: /var/lib/rundeck/server/config/ssl.properties
VERBOSE: Writing config file: /var/lib/rundeck/server/config/jaas-loginmodule.conf
VERBOSE: Writing config file: /var/lib/rundeck/server/sbin/rundeckd
VERBOSE: Done. --installonly: Not starting server.
~$ /usr/bin/java -jar /usr/share/rundeck/rundeck-3.0.13-20190123.war --basedir /var/lib/rundeck/ --configdir /etc/rundeck --installonly
2019-02-06 19:02:06.292 ERROR --- [           main] r.i.DefaultRundeckConfigPropertyLoader   : Unable to load rundeck-config.properties.
```
Of course since files are created in the wrong directory.

Even if I do a `cp -aR /var/lib/rundeck/server/config/* /etc/rundeck/` before launching the server it doesn't work and I have errors on startup.

Since I'm a standard loving guy, I just want to install Rundeck while complying to the FHS (https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard).

Do you have a how to or some pointer to the documentation to achieve this ?

**Comment by ProTip** [comment]
Hi @theredcat 

I have dug into the code a bit and I don't believe Rundeck will expand the installation templates out into a custom config directory currently..

As a work around, after moving the config files into another directory, you can set these JVM properties as per the `deb`/`rpm` installation and I believe they will load:

https://github.com/rundeck/rundeck/blob/master/packaging/common/etc/rundeck/profile#L75-L76

**Comment by theredcat** [comment]
If it's useful for anyone, this is my basic installation procedure. You'll still have to create the systemd unit file, do a real configuration for the database, for the auth, create a `/etc/rundeck/profile` to export the right RDECK_JVM if you want to use rd-acl, move the rd-acl script in the right directory, etc.. 

```
~# addgroup --gid 819 rundeck
~# adduser --home /var/lib/rundeck --uid 819 --gid 819 rundeck
~# mkdir /var/lib/rundeck /etc/rundeck  /usr/share/rundeck /var/log/rundeck
~# chown rundeck.rundeck /usr/share/rundeck/ /etc/rundeck /var/lib/rundeck /var/log/rundeck
~# su -s /bin/bash - rundeck
~$ cd /usr/share/rundeck/
~$ wget https://dl.bintray.com/rundeck/rundeck-maven/rundeck-3.0.13-20190123.war
~$ /usr/bin/java -Drundeck.jaaslogin=true -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf -Dloginmodule.name=RDpropertyfilelogin -Drdeck.config=/etc/rundeck -Drundeck.server.configDir=/etc/rundeck -Dserver.datastore.path=/var/lib/rundeck/data/rundeck -Drundeck.server.serverDir=/var/lib/rundeck -Drdeck.projects=/var/lib/rundeck/projects -Drdeck.runlogs=/var/lib/rundeck/logs -Drundeck.config.location=/etc/rundeck/rundeck-config.properties -Djava.io.tmpdir=/tmp/rundeck -Drundeck.server.workDir=/tmp/rundeck -Dserver.http.port=4440 -Drdeck.base=/var/lib/rundeck -jar /usr/share/rundeck/rundeck-3.0.13-20190123.war --installonly -d
~$ mv /var/lib/rundeck/config/* /etc/rundeck/
~$ cd /etc/rundeck
~$ for i in $(ls /etc/rundeck); do sed -i -re 's/http(\\?:\/\/)'$(hostname -a)'\\?:4440$/https\1my-rundeck.public-domain.com/g' $i; done
~$ sed -i 's/'$(hostname -a)'/localhost/g' *
~$ sed -i 's/\/var\/lib\/rundeck\/logs/\/var\/log\/rundeck/g' log4j.properties
~$ /usr/bin/java -Drundeck.jetty.connector.forwarded=true -Drundeck.jaaslogin=true -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf -Dloginmodule.name=RDpropertyfilelogin -Drdeck.config=/etc/rundeck -Drundeck.server.configDir=/etc/rundeck -Dserver.datastore.path=/var/lib/rundeck/data/rundeck -Drundeck.server.serverDir=/var/lib/rundeck -Drdeck.projects=/var/lib/rundeck/projects -Drdeck.runlogs=/var/lib/rundeck/logs -Drundeck.config.location=/etc/rundeck/rundeck-config.properties -Djava.io.tmpdir=/tmp/rundeck -Drundeck.server.workDir=/tmp/rundeck -Dserver.http.port=4440 -Drdeck.base=/var/lib/rundeck -jar /usr/share/rundeck/rundeck-3.0.13-20190123.war --skipinstall -d```

If you wonder why UID 819, it's not random at all it comes from here : https://github.com/freebsd/freebsd-ports/blob/master/UIDs

**Comment by theredcat** [comment]
Still an issue unfortunatly
