### ISSUE TITLE
Querying 5k nodes leads to very long queries on the webui

### ISSUE THREAD

**Issue by kamaradclimber** [rundeck/rundeck#1597]
When searching for nodes in the web UI, rundeck currently returns data as html.

The data volume is really high, for instance on our 5573 nodes, it represent around 302MB whereas the initial data is only 0.5MB.

It has many downsides, one of them being that rundeck dedicate one core to build this html leading to 100% cpu on that core (effectively limiting the data transfer to 10Mb/s).

Overall, the interface feels very slow when searching nodes.

What could be done to mitigate that issue?

**Comment by kamaradclimber** [comment]
More figures depending on the various projects we have:

Node in the project | Time to fetch data
-------------------------|------------------------
382                      | 20 secs
1668                     | 76 secs
2773                     | 150 secs
5573                     | 4 minutes (timeout)

Those project node sources are completely independant and have no filter applied.

**Comment by ahonor** [comment]
@kamaradclimber what kind of model source is this?

**Comment by kamaradclimber** [comment]
@ahonor URL Source, with cache result set and timeout to 120.

It seems that the fetch of the source done very quickly:
- a tcpdump show the whole source is sent to rundeck server in a few seconds
- the beginning of the data (time to first byte is 1 second) sent to my browser contains the number of nodes which can only be known if the whole source has been parsed by the rundeck server.

**Comment by ahonor** [comment]
@kamaradclimber for comparison sake, can you save the result of a URL query containing the 5k nodes to a file and configure a File Model Source? I am curious to see how the UI responds.

**Comment by kamaradclimber** [comment]
Result is the same: timeout after 4 minutes (exactly) and 299 MB of transferred data.

**Comment by ahonor** [comment]
@kamaradclimber where does the timeout occur? For example, if you go to the Nodes page and list all, it will say load next 20 or list remaining. Does it timeout when you say list remaining?

**Comment by kamaradclimber** [comment]
It appears on the Commands page when setting the `.*` filter.
![2015-12-16-164713_926x155_scrot](https://cloud.githubusercontent.com/assets/503537/11845532/afacf64e-a414-11e5-840f-0023dd1263af.png)

**Comment by kamaradclimber** [comment]
Yes on the node page, it does that "Next 20… Load 5553 remaining…"

**Comment by ahonor** [comment]
@kamaradclimber what is the maxheap size setting (i.e., -Xmx)?

**Comment by kamaradclimber** [comment]
XmX is 16384m

**Comment by kamaradclimber** [comment]
@ahonor have you been able to confirm the bug ?

**Comment by kamaradclimber** [comment]
@ahonor I'd be glad to help fixing the issue. Could you give me some pointers ?

**Comment by ahonor** [comment]
@kamaradclimber we are looking into making the URL source work more asynchronously.

**Comment by kamaradclimber** [comment]
Thanks @ahonor  for your answer.

I am not sure to understand how it will reduce the size of exchanged data, could you explain?

**Comment by ahonor** [comment]
@kamaradclimber it won't have an effect on the data size but hopefully improve the UI responsiveness.
