### ISSUE TITLE
Non-fatal error at the end of job execution

### ISSUE THREAD

**Issue by AndyBerman** [rundeck/rundeck#1598]
When I run any type of job on the windows server that is hosting rundeck, I get an error like this on the last line of the output:

    Could Not Find C:\WINDOWS\TEMP\24-13433-self-ops.mitre.org-dispatch-script.tmp.bat

The host server is windows and it happens for every type of job I run on it.

Running 2.6.2-1, but also got this error back on 2.5.

**Comment by DavidMellors** [comment]
I just installed rundeck on Windows and saw the same thing. 
http://rundeck.org/docs/plugins-user-guide/node-execution-plugins.html was helpful to understand why this was happening and once I changed the permissions on C:\Windows\Temp I didn't see it again.

**Comment by AndyBerman** [comment]
That was the problem.  I changed permissions on c:\windows\temp so that the Rundeck service could write into that directory.
Thanks!
