### ISSUE TITLE
Yet another WinRM plugin

### ISSUE THREAD

**Issue by ghost** [rundeck/rundeck#1599]
Hi Devs,

I've open-sourced another script based node-executor plugin for WinRM. It is aimed at PowerShell scripting. It's called "TR WinRM Plugin".

https://github.com/thomsonreuters/tr-rundeck-winrm-plugin

Thanks!

**Comment by gMickey** [comment]
Hello!

Unfortunately, i can't make it work on windows, but thanks to you, i was inspired to write my own in pure powershell:

https://github.com/gMickey/ps-rundeck-winrm-plugin

**Comment by dhruvahuja** [comment]
Great, gMickey! My plugin is deployable from Linux only indeed.
