### ISSUE TITLE
Job returning as succeeded even with failed step

### ISSUE THREAD

**Issue by cleberps** [rundeck/rundeck#1600]
The jobs status returned as succeeded when the correct should be return as failed. To reproduce this follow this steps:
1) Create jobA that run any script, e.g. "ls /; sleep 3m;"
2) Create jobB that always returns as failed, using a script run with "exit 1" at the end. Job B has a retry of 0.
3) Create jobC that contains a task for job state waiting the JobA to be stopped and succeed. That task also has an error handler that execute a script that simply run a "sleep 1m". The second task is a job reference for JobC and contains a error handler to Halt and fail the execution. JobC has a retry of 15.

On normal operation JobC should retry 3 or 4 times before touch Job B execution and halt/fail. The job really halt but even with task JobB been reported as failed the jobC is marked as succeeded. It seems that the correct return for job C should be Failed because the error handler says that it must fail/halt.

**Comment by gschueler** [comment]
i'm not quite sure how your jobs are set up (do you have sample job.xml you can upload?)

if you are not running 2.6.2 yet, it might be fixed by this issue https://github.com/rundeck/rundeck/issues/1528

**Comment by cleberps** [comment]
Hi, I checked the issue #1528 but my scenario is different.
Attached are the 3 jobs. While JobA is running also run JobB and wait. I also attached a screenshot from the results. Even with a failed step the whole job is returned as succeeded.

![screenshot_rundeck_job](https://cloud.githubusercontent.com/assets/652576/12233873/ea51a902-b850-11e5-9f21-6f2e4e6335f6.png)
[Jobs.zip](https://github.com/rundeck/rundeck/files/85737/Jobs.zip)

**Comment by Creativex** [comment]
Hi, I have a same issue. I have one job with 2 job ref and 2 scripts. If one of the scripts fails, my job fails, but if it's one of the jobs ref, my job returns succeeded.

**Comment by aman-thakral** [comment]
I have a similar issue.  I'm running: Rundeck 2.6.9-1 
* Workflow Strategy: Step-Oriented
* The job consists references, script, and command.
* The last step is a command: `rm -rf /tmp/my_temp_folder`
* All steps run on the same node.

**Comment by gschueler** [comment]
please include your job.xml definition

**Comment by aman-thakral** [comment]
Added to my comment above

**Comment by TJarriault** [comment]
Hi,
I have the similar issue, with rundeck 2.7.3. Do you solved this issue ?

Regards,

Tony

**Comment by kaminek** [comment]
Hi, same here with `Rundeck 3.0.12-20190114`.
Any fix?
