### ISSUE TITLE
Allow multiple cron triggers per job

### ISSUE THREAD

**Issue by biguphpc** [rundeck/rundeck#1608]
Right now it's possible to set a single cron trigger/schedule per job. If the job needs to run on two distinct schedules it needs to be dupliacted which is not ideal. That would be very useful and powerful if we could add more than one schedule pet job. That would allow complex schedules like: run the job run every day at 4 pm AND on 31st Dec at midnight..etc

The underlying quartz scheduler supports multiple CronTriggers and allowing multiple schedules on the interface would make rundeck so much more powerful.

Thanks for this great piece of software!

**Comment by trakkyo** [comment]
+1

**Comment by KevinIp** [comment]
+1

**Comment by shoelzle** [comment]
+1

**Comment by kpchen** [comment]
+1

**Comment by 9h87f497h4387b9** [comment]
+1

**Comment by acalisesi** [comment]
+1

**Comment by dhanasekaran-anbalagan** [comment]
+1

**Comment by synapseit** [comment]
+1

**Comment by aleonsan** [comment]
+1

**Comment by HowardHong** [comment]
+1

**Comment by isermaniac** [comment]
+1

**Comment by ZoeLeah** [comment]
+1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frachel** [comment]
+1

**Comment by skywalke34** [comment]
+1

**Comment by spalmrot-tic** [comment]
+1

**Comment by dd5154** [comment]
+1

**Comment by Stephen-Bo** [comment]
+1

**Comment by fdevans** [comment]
This is available in our Enterprise version with Project Schedules.
