### ISSUE TITLE
Referenced job not only executing on targeted node

### ISSUE THREAD

**Issue by jpwilsch** [rundeck/rundeck#1609]
I'm running Rundeck 2.6.2-1

I have a job A, containing a few node steps. A node filter is applied on this job, selecting 3 nodes. The job ask the user to explicitly select target nodes.

I also have a job B, with referenced the job A, to run as a node step. The same node filter is applied to job B, and the user is also asked to explicitly select target nodes.

When I run job B, with just one node selected and targeted, the job A is nevertheless run on the 3 nodes corresponding to the node filter, and not only on the node selected when launching job B.

Is this normal behavior ?
How can I make a referenced job run on the node selected when launching the referecing job ?

**Comment by ambikads** [comment]
I have the same issue.

**Comment by jmiro227** [comment]
We also have the same issue.

**Comment by ahonor** [comment]
In rundeck 2.9+, you can override node filters for child jobs.
