### ISSUE TITLE
Integration tests fail when data source is configured as an external database.

### ISSUE THREAD

**Issue by ramesh-aadhav** [rundeck/rundeck#1616]
dataSource {
    pooled = false; //it is recommended not to use connection pool unless file encryption is enabled
    driverClassName = "org.postgresql.Driver"
    username = abc
    password = xyz
}
hibernate {
    cache.use_second_level_cache=true
    cache.use_query_cache=true
    cache.provider_class='net.sf.ehcache.hibernate.EhCacheProvider'
}
// environment specific settings
environments {
    development {
        dataSource {
            dbCreate = "create-drop" // one of 'create', 'create-drop','update'
            url = POSTGRES_DB_URL
        }
    }
    test {
        dataSource {
            dbCreate = "update"
            url = POSTGRES_DB_URL
        }
    }
    production {
        dataSource {
            dbCreate = "update"
            url = POSTGRES_DB_URL
        }
    }
}

When the data source is linked to an external database rather than the out-of-the-box embedded DB H2, my integration tests fail. The rundeck war package is not building. 
And where and how do I distinguish the environments to be "development" or "test" or "production" ?
Can someone guide me?

**Comment by ahonor** [comment]
Please reopen if this remains a concern
