### ISSUE TITLE
Log file uses system default file encoding, should force UTF-8

### ISSUE THREAD

**Issue by alexey-pankratyev** [rundeck/rundeck#1619]
I have a problem with the encoding.  When you execute a command through a web interface (commands) or via the dispatch server 
Example:    (dispatch -p explotation  -F 'name: tamer' -f -- sudo echo \\'Тестируем\') 
and introduce the characters in Russian, I get a response consisting of a question mark
Example:    (?????????).
With the encoding server (centos 6) there are no problems -    
[root@tamer ~]# locale -a | grep ru 
ru_RU
ru_RU.cp1251
ru_RU.iso88595
ru_RU.koi8r
ru_RU.utf8
russian
ru_UA
ru_UA.koi8u
ru_UA.utf8

OS: centos6 (the source and receiver)
Browser:  chrome , firefox mozilla, chromium version - 

 46.0.2490.71 (64-bit)  

I would be very grateful for the help!

![err](https://cloud.githubusercontent.com/assets/1902027/12180908/34e16476-b590-11e5-914e-84a24e2db21b.png)
![err2](https://cloud.githubusercontent.com/assets/1902027/12180909/34e29e7c-b590-11e5-8b7e-79d89735919a.png)

[4922.zip](https://github.com/rundeck/rundeck/files/81662/4922.zip)
[4923.zip](https://github.com/rundeck/rundeck/files/81656/4923.zip)

**Comment by gschueler** [comment]
the output file is ASCII, so i think your system default charset is set to ASCII.  Make sure the locale/charset is set to use UTF-8, prior to starting Rundeck. You can also try adding `-Dfile.encoding=UTF-8` to your `/etc/rundeck/profile` in the RDECK_JVM variable.

I will mark this as a bug, I think the log file writer may be using the default encoding, but it should force it to use UTF-8

**Comment by alexey-pankratyev** [comment]
Found the solution myself ! The problem was that I decided to make the upstart script, but not out run rundeck user, run as root, root is probably not the system environment ! But still should not be allowed to run as a non rundeck!

**Comment by alexey-pankratyev** [comment]
Close the error ! And I apologize for paid for nothing the time on me !

**Comment by gschueler** [comment]
I am going to re-open this: it should force the correct file encoding for the log files!!

**Comment by alexey-pankratyev** [comment]
That's right ! Good attitude to work !

**Comment by naechin91004** [comment]
Hello.
I have same problem on 2.6.2.
I adding  -Dfile.encoding=UTF-8  to /etc/rundeck/profile  in the RDECK_JVM variable.
But I can't fix it.

My server OS is ubuntu 14.04, and locale is ko_KR.UTF8.
How can fix this problem?
I want temporary solution. Please Help me
