### ISSUE TITLE
SCM: not compatible with clustering/HA

### ISSUE THREAD

**Issue by makered** [rundeck/rundeck#1622]
SCM does not seem to work well in an environment where Rundeck is set up as an HA cluster (load balancer, multiple rundeck nodes) because the checkout directory is created on the node from which SCM setup is being performed in the GUI.

For example, after setting up SCM on node 1 and logging into node 2, there is no indication that SCM was even configured for a given project.

This is understandable considering only recent introduction of SCM support, just wondering if it is safe to utilize some solution to sync checkout directory between nodes out of band (e.g. rsync /var/rundeck/projects/)?

**Comment by gschueler** [comment]
Currently SCM integration works only on a single cluster server, as a single point for import/export of jobs to SCM.  Part of the reason: SCM import will create/update jobs in the central DB, used by all servers, so it should only happen from a single server at a time to avoid confusion and issues synching. Similarly, it doesn't make sense to have multiple servers in the cluster both exporting the same changes to a single git repo.

However, I can understand wanting to see SCM status in the GUI from other servers, and possibly triggering the synch (commit,push,pull, etc) that happens from a single server.  But currently Rundeck doesn't do any cross-server communication outside of the database.

So: true, SCM integration not designed to be fully featured across all cluster servers, but it is designed to be functional for a single server even in cluster mode.  You just have to manage SCM integration on a single server node.  

One enhancement that might improve this: allow transferring the SCM integration control point to another cluster server, similar to cluster schedule transfer.

**Comment by ARentz07** [comment]
@gschueler Is this still accurate, that clustering and SCM are incompatible? I was just playing around with this in a clustered setup and did notice it sometimes would 'lose' my SCM plugin config changes and wondered why.

**Comment by gschueler** [comment]
@ARentz07 yes, only a single cluster node will be configured for scm integration.

**Comment by atheiman** [comment]
The approach we are taking to this is a shared filesystem between our two rundeck app nodes using [GlusterFS](https://www.gluster.org/) (there are similar distributed FS tools). We use it to share job execution logs as well. It seems like a good solution to the clustering of Rundeck app nodes.

**Comment by makered** [comment]
We use S3 for sharing job exec logs but not for SCM local repo sharing, is that a safe approach?

**Comment by atheiman** [comment]
@makered I'm not sure what youre asking exactly, or if youre replying to me, but I dont think you would want to use S3 for SCM (seems unnecessary to put that into S3) or SCM for sharing job exec logs (they would be too big for git client I assume).

<hr/>

Right now we only have a standalone instance running, but we should have our clustered environment running in the next week or so. I can't say 100%, but I don't think there will be any issues with using GlusterFS for SCM, it's just yaml files stored on the FS, so GlusterFS should work fine for this.

<hr/>

Are you able to read S3 job execution logs back down onto the servers in a clustered env? I think we were having difficulty getting this working, all we could do was basically backup the logs to S3.

**Comment by makered** [comment]
@atheiman We currently have a 2-node cluster with S3 as shared storage for logs via the S3 plugin as described [here](http://rundeck.org/docs/administration/scaling-rundeck.html)

This setup worked well for us for some time now and we did not come across issues accessing the logs. We recently started looking into SCM but are somewhat discouraged by having to manage this feature from a single node (we load balance console access). Per @gschueler's explanation I was wondering if sharing local SCM storage among the nodes might address the issue.

**Comment by atheiman** [comment]
gotcha, yes I agree it would be nice if the SCM plugin had support for this directly rather than having to work around with a shared FS using Gluster or similar tools. Might be better off logging an issue to the plugin directly for this https://github.com/rundeck-plugins/rundeck-s3-log-plugin/issues ?

<hr/>

We'll have to go through the instructions for the s3 plugin again and see where we're going wrong getting the logs back out of S3, that would be very helpful to us.

**Comment by dinfiesta** [comment]
Still having this issue on Rundeck 3.0.17-20190311 and ideas on fix?
