### ISSUE TITLE
Import failed because character unicode x01 was found within xml file

### ISSUE THREAD

**Issue by snebel29** [rundeck/rundeck#1628]
Hi,
Copying text from another application to some job description, I pasted the "x01" character by mistake, I then exported the project as usually then when trying to import this project over a different instance it start failing with the following errors

```
2016-01-13 08:30:34,732 [qtp1267032364-26] ERROR grails.app.services.rundeck.services.ProjectService - Failed parsing jobs from XML at archive path: rundeck-LRS/jobs/job-87373777-6f6a-49bd-8354-0c1c84de2203.xml

[Fatal Error] :16:82: An invalid XML character (Unicode: 0x1) was found in the element content of the document.
ERROR ProjectService: Failed parsing jobs from XML at archive path: rundeck-LRS/jobs/job-87373777-6f6a-49bd-8354-0c1c84de2203.xml
INFO  ProjectService: Loaded 9 jobs
INFO  ProjectService: Loaded 0 executions, map: [:]
INFO  ProjectService: Loaded 0 reports
```

I realize that the GUI was noticing me the presence of this character with a tiny red background, however this is not always easy to see when working with a lot of text.. The result is that any action with the xml file generated by RD was not possible until the character was removed.

I'm wondering if wouldn't be a good enhancement to avoid any not valid xml character or escape them in some way before getting into the database...

Regards

**Comment by gschueler** [comment]
would you be able to send the file or archive to me so i can examine it? thanks

**Comment by snebel29** [comment]
Hi,
Find it here
https://drive.google.com/open?id=0B-0JFS1f1_jTZFJDOTFuQTZoUUU
