### ISSUE TITLE
Environment variables feature request

### ISSUE THREAD

**Issue by Mapel88** [rundeck/rundeck#1629]
Hello dear devs!
I hope I'm posting this in the right place, please let me know if not :)

Is it possible to add environment variables that can be accessed from all job steps and nodes?
For example, I want to use rundeck ip while running scripts on remote nodes, but don't want to add another tag for it in resource.xml per node..

I thought of two options:
1. Add more variables like RD_JOB_SERVERURL (or ${job.serverUrl}) that will contain data of the rundeck server (OS, version, ip, hostname etc)
2. Load the data from framwork.properties (or any other configuration file) so it can be used as variables in scripts (this way users can add whatever environment variables they wish to use in the future)

Thanks!

**Comment by cyrilthank** [comment]
Add an environment variable which can be used as placeholder to use/pass common values to all jobs

**Comment by ahonor** [comment]
@Mapel88 Use a global configuration setting. http://rundeck.org/docs/administration/configuration-file-reference.html#global-execution-variables
