### ISSUE TITLE
Feature request: Node filter supporting ranges in Job execution page

### ISSUE THREAD

**Issue by ambikads** [rundeck/rundeck#1633]
It will be nice to have 
1. Node filtering option in job execution page. Right now we have to manually to check/uncheck the node names, this can be a pain when there are many nodes. Can we have an option to perform node filtering in the job execution page similar to how we have in the commands page. This node filter would be a subset of the nodefilter set while defining the job.
2. Node filtering option which supports ranges (like choosing range of pages to print). It would be awesome to be able to do `hostname1-10,35,60-70`  in the job execution page.

**Comment by metacoma** [comment]
+1 very useful thing

**Comment by ambikads** [comment]
Currently using rundeck for our software deployment. This feature would be very helpful. Any chance this can be done for the next release?

**Comment by fdevans** [comment]
Due to the age of this request and more recent feature releases we are going to close this request.  If there are still gaps in the feature set please feel free to open an enhancement request against the current version of Rundeck with your ideas.
Thank you, 
The Rundeck Team
