### ISSUE TITLE
remotely execute httpie command failed

### ISSUE THREAD

**Issue by WalterInSH** [rundeck/rundeck#1638]
I'm trying to execute [httpie](https://github.com/jkbrzt/httpie) command on a remote machine. But it's hanging without any logs.

I'm sure I can execute command on the remote machine,and here is the detail.

![qq20160120-0 2x](https://cloud.githubusercontent.com/assets/4099427/12445387/f8b1a650-bf9e-11e5-8daf-bfde098b0ada.png)

and here is the output

```
Python 2.6.6
0.9.3
```

Rundeck version 2.6.2-1
Both of the rundeck host and target host are centos

**Comment by ahonor** [comment]
Curious if it could be due to python output buffering. Maybe try setting `PYTHONUNBUFFERED`

**Comment by WalterInSH** [comment]
@ahonor Thanks for replying
I used the following command, it didn't work. Is this what you meant?
```
python -u /usr/bin/http get baidu.com
```

**Comment by ahonor** [comment]
@WalterInSH right. Not sure what else would prevent the output.

**Comment by WalterInSH** [comment]
I finally use curl instead of httpie. I would work, but not friendly.I'll let you know if I have any updates.

**Comment by arunanc** [comment]
For those who end up here looking for a solution (just like I did), the answer is to use the "--ignore-stdin" flag.

`http --ignore-stdin`
