### ISSUE TITLE
The displayed current step being executed is not always correct when monitoring a running job 

### ISSUE THREAD

**Issue by tonyhaywardtr** [rundeck/rundeck#1639]
I have many step-oriented jobs that run multiple steps on several servers. When watching the "Monitor" tab of a running job, I've noticed that the step that's currently executing is not always correct, but is shown to be a previous step that already completed successfully. By refreshing the browser and reselecting the "Monitor tab", the correct step then appears.

I'm using Rundeck 2.6.2. I noticed this in 2.5.x as well.

**Comment by gschueler** [comment]
is there any error message in the javascript console?  What client browser/os are you using?

**Comment by tonyhaywardtr** [comment]
I'm using Chrome on Windows 7, but I've seen it with Chrome on Mac OS 10.11.2 and Windows 10 as well. 
There are no errors in the Javascript console.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
