### ISSUE TITLE
Editing CSS files is not reflecting 

### ISSUE THREAD

**Issue by rootameen** [rundeck/rundeck#1641]
Hey Guys,

I'm trying to do some visual modifications on my deployment that suits my needs. When I try to change any specific attribute it doesn't reflect on the running CSS. For example if I wanted to edit .optionmultiarea to be bigger than 11em to display more options, No matter what css file in /var/lib/rundeck/exp/webapp/assets/ I do the changes in, it just doesn't reflect.

I tried restarting the service but still it didn't reflect.

Any tips?

Thanks in advance.

**Comment by gschueler** [comment]
directly editing those files will not work. We have had requests to customize the css more, so are planning to add a feature for doing that.

**Comment by rootAmeen** [comment]
But what's the workaround if I want to do them today?

**Comment by ltamaster** [comment]
Hi
you could try this:
https://groups.google.com/forum/#!topic/rundeck-discuss/dRYniNunr5o

best
