### ISSUE TITLE
SCM: NoSuchFileException

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#1642]
When changing a job I get an NoSuchFileException, but the changes are saved.
After a rundeck restart it works for a day.
```
Rundeck Version: 2.6.2
SCM Export Options:
    Committer Name: ${user.fullName}
    Committer Email: ${user.email}
    Base Directory: /home/rundeck/projects/xxx/scm
    File Path Template: ${job.group}${job.name}-${job.id}.${config.format}
    Git URL: https://xxx/rundeck-scm-xxx.git/
    Branch: master
    SSH:
    Strict Host Key Checking: yes
    Format: yaml
```
[2016-01-26 - Rundeck NoSuchFileException.txt](https://github.com/rundeck/rundeck/files/104447/2016-01-26.-.Rundeck.NoSuchFileException.txt)

**Comment by gschueler** [comment]
Thanks, I think I've seen this pop up, and I thought it was a spurious issue in our automated tests.  

To be clear, you mean that after you edit a job definition, and hit "save", this error occurs?

**Comment by schast** [comment]
Yes, after edit a job definition, and hit "save", this error occurs.
edit the same job after a rundeck restart will work.

**Comment by gschueler** [comment]
i believe this may be fixed, although i have not directly reproduced it. it may be related to #1644
