### ISSUE TITLE
Job import fails when XML single quote style on attributes

### ISSUE THREAD

**Issue by ogafosir** [rundeck/rundeck#1643]
Uploading jobs via: `https://rundeck.vops.io/api/14/project/{{ project_name }}/jobs/import?uuidOption=remove`  fails when the attributes of the xml elements are 'single_quoted'. The same definition with "double_quoted" attributes is working OK.

[jobs_fails.txt](https://github.com/rundeck/rundeck/files/104958/jobs_fails.txt)
[jobs_works.txt](https://github.com/rundeck/rundeck/files/104962/jobs_works.txt)

```
            "HTTP/1.1 400 Bad Request", 
            "Set-Cookie: JSESSIONID=8y7sw23397c0bdowpl0cglvl;Path=/", 
            "Expires: Thu, 01 Jan 1970 00:00:00 GMT", 
            "Content-Type: text/xml;charset=UTF-8", 
            "X-Rundeck-API-Version: 15", 
            "Connection: close", 
            "Server: Jetty(7.6.0.v20120127)", 
            "", 
            "<result error='true' apiversion='15'>", 
            "  <error code='api.error.jobs.import.invalid'>", 
            "    <message>Jobs Document was invalid for format xml: rundeck.controllers.JobXMLException: Unable to parse xml: org.xml.sax.SAXParseException; lineNumber: 4; columnNumber: 30; Open quote is expected for attribute \"preserveOrder\" associated with an  element type  \"options\".</message>", 
            "  </error>", 
            "</result>"
```

I believe BOTH styles of xml files should be supported.

**Comment by gschueler** [comment]
what version of rundeck are you using?

I don't see any error loading that job in 2.6.3-snapshot.

**Comment by ogafosir** [comment]
Running version 2.6.2-1

**Comment by ahonor** [comment]
Please reopen if this remains a concern

**Comment by scty-nchitturi** [comment]
I am see an error when trying to import a job xml to rundeck. I am running rundeck on windows
