### ISSUE TITLE
Unable to add text to footer

### ISSUE THREAD

**Issue by rootameen** [rundeck/rundeck#1645]
Hi. 

I wanted to add more text to the footer, but I couldn't do it. When I try to add anything to the ./exp/webapp/WEB-INF/classes/gsp_rundeck_common_footer_gsp_html.data which seems to be the only file actually reflecting changes, the applications gives me a 500 error 
" Error 500 - Internal Server Error.
Error applying layout : base"

 Even adding a single character to the text gives this issue. If I replace 1 character with another character it works. But this is really not useful for me to do what I need.

This is similar to some extent to an issue I posted before but I haven't got any answers for it: https://github.com/rundeck/rundeck/issues/1641

Thanks in advance.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
