### ISSUE TITLE
problem modifying timeout en rundeck 2.6.1

### ISSUE THREAD

**Issue by albertmfb** [rundeck/rundeck#1648]
It seems that changing the timeout for a job doesn´t work in rundeck 2.6.1
The timeout seems to be changed (it appears in the job configuration), but when job is executed, the timeout value that uses to stop is which was assigned when it was created, not the modified one.

product version:  rundeck-2.6.1-1.12.GA.noarch

Any ideas to solve this?
Thanks.

**Comment by gschueler** [comment]
several other issues reported relate to this, i believe it's a bug

**Comment by ahonor** [comment]
Could not reproduce in 2.10.
