### ISSUE TITLE
commands and jobs running in /var/log/rundeck instead of /var/lib/rundeck

### ISSUE THREAD

**Issue by rasebo** [rundeck/rundeck#1649]
I am using rundeck 2.6.2-1 installed as a .deb package on Jessie.

While troubleshooting one of the jobs, I noticed that all jobs and commands are not running in ~rundeck (/var/lib/rundeck) as I would have expected them to, but rather in /var/log/rundeck. 

Checking the paths in rundeck, running a simple pwd outputs /var/log/rundeck as the current path, while ~ resolves, as it should, to /var/lib/rundeck:

<img width="539" alt="screen shot 2016-01-28 at 16 44 27" src="https://cloud.githubusercontent.com/assets/1422444/12652076/2e2ef33a-c5e1-11e5-8631-ec03b6226740.png">

**Comment by ahonor** [comment]
Please reopen if this remains a concern

**Comment by OmriShiv** [comment]
I'm seeing this on 2.10.1-1 installed using the deb
