### ISSUE TITLE
Records in Workflow, workflow_step and workflow_workflow_step do not get cleaned up when executions are deleted

### ISSUE THREAD

**Issue by yobryon** [rundeck/rundeck#1654]
I've noticed in our rundeck instance that the db continues to grow over time, even though we aggressively prune executions and try to keep history below approx 10k executions. Digging into it, I see that these three tables (Workflow, workflow_step and workflow_workflow_step) still contain records for executions that have been deleted from the other tables (by using the application to delete them).

This installation is using h2 db, started its life on 2.5.3, and was upgraded to 2.6.1 and then 2.6.2.

**Comment by makered** [comment]
Noticing similar behavior following bulk execution deletion via ```executions/delete``` on 2.6.2 and mysql.

Unfortunate consequence of the workflow tables being large is that the "Get Executions for a Job" API call (```/api/1/job/[ID]/executions```) that we use to determine which executions to purge by date is slow.

**Comment by makered** [comment]
Adding the following index from https://github.com/rundeck/rundeck/issues/1547 helped speed up ```/api/1/job/[ID]/executions``` immensely:

```create index WORKFLOW_WORKFLOW_STEP__WORKFLOW_COMMANDS_ID on workflow_workflow_step(workflow_commands_id);```

**Comment by ahonor** [comment]
+1 Index should be added to domain model.

**Comment by bryonwilliams** [comment]
in case it helps anyone else, this is what I've been doing to clean up periodically:
```
create memory table ids (id bigint);
insert into ids select workflow_id from execution;
insert into ids select workflow_id from scheduled_execution;
delete from workflow_workflow_step where workflow_commands_id not in (select id from ids);
delete from workflow_step where id not in (select workflow_step_id from workflow_workflow_step);
delete from workflow where id not in (select WORKFLOW_COMMANDS_ID from workflow_workflow_step);
drop table ids;
```

**Comment by makered** [comment]
Thanks @bryonwilliams,

In my case I had to also add an index on ids:

```create table ids (id bigint) ENGINE=MEMORY;```
```alter table `ids` add index `id_idx` (`id`)```

**Comment by shamil** [comment]
@gschueler will this going to be fixed anytime soon?

**Comment by reubenfirmin** [comment]
Since deletes on these tables can take forever if they are large, here's a workaround that incorporates the above and allows truncates. (It seems questionable that commands are stored in the history tables; it would be so much easier if the schema was a little cleaner.) Note that this deletes all history, and adds the missing index.

```
create table ids (id bigint);
insert into ids select workflow_id from scheduled_execution;
create table workflow_step_bak as (select * from workflow_step where id in (select workflow_step_id from workflow_workflow_step inner join ids on (ids.id = workflow_workflow_step.workflow_commands_id)));
create table workflow_workflow_step_bak as (select * from workflow_workflow_step where workflow_step_id in (select id from workflow_step_bak));
create table workflow_bak as (select * from workflow where id in (select workflow_id from scheduled_execution));
alter table scheduled_execution drop constraint fk_jln7b7a683uwkl4fg6kpacqnp; -- ymmv on the constraint name
truncate execution, log_file_storage_request, workflow_step, workflow_workflow_step, workflow;
create index WORKFLOW_WORKFLOW_STEP__WORKFLOW_COMMANDS_ID on workflow_workflow_step(workflow_commands_id);
insert into workflow select * from workflow_bak;
insert into workflow_step select * from workflow_step_bak;
insert into workflow_workflow_step select * from workflow_workflow_step_bak;
alter table scheduled_execution add constraint fk_jln7b7a683uwkl4fg6kpacqnp foreign key (workflow_id) references workflow(id);
drop table ids, workflow_bak, workflow_step_bak, workflow_workflow_step_bak;
```

**Comment by jimr6007** [comment]
How is this issue still open after so many years?

I ask that way, sorry, don't meant to seem flippant :)

...because I imagine that I must be missing some fundamental information on the relationship between executions and workflows.

is there a reason that all workflows related database data/rows should NOT be deleted when corresponding executions are deleted, bulk deleted via the UI for example?
