### ISSUE TITLE
Pseudo-terminal will not be allocated because stdin is not a terminal.

### ISSUE THREAD

**Issue by rootameen** [rundeck/rundeck#1655]
Edit: updating comment/title because of new findings:

Hi guys. 

I have a command that can only run through ssh -t from rundeck server to node. However, when adding it to a job either as a remote script or executing locally using ssh -t I get the error: 

Pseudo-terminal will not be allocated because stdin is not a terminal.

when I add -t -t which should force it I get: tcgetattr: Invalid argument

How can I force jsch/rundeck to use ssh -t or just use the default ssh connection in the system?

**Comment by rootAmeen** [comment]
After more debugging, I found that the command while running from the service takes around 10 seconds to complete. When I run it through rundeck it finishes within 1 second. Still trying to find root cause.

**Comment by scalp42** [comment]
@rootAmeen try `ssh -tt`

**Comment by gschueler** [comment]
the jsch plugin does not allocate a pseudo terminal, unless you are using the "sudo" authentication feature (so it can input a sudo password.)

You can either: try using the system `ssh` executable directly, by means of either a script plugin, or the "script-exec" node executor

**Comment by scalp42** [comment]
@rootAmeen what @gschueler means is:

```
service.NodeExecutor.default.provider=script-exec
plugin.script-exec.default.command=/usr/bin/ssh -q -oSendEnv\=* -oStrictHostKeyChecking\=no -tt ${node.username}@${node.hostname} ${exec.command}
```

**Comment by gschueler** [comment]
@scalp42 :+1:

**Comment by OrKoN** [comment]
@scalp42 @gschueler how can I provide identity file to the command? it is defined in project.ssh-key-storage-path

**Comment by ahonor** [comment]
The "Allocate Pty" project config setting should cause a TTY for all the connections.

**Comment by abbos1117** [comment]
has any solution for gitlab-ci.yaml file that error ?
