### ISSUE TITLE
Unable to connect remotely to RunDeck UI

### ISSUE THREAD

**Issue by abrahamrhoffman** [rundeck/rundeck#1656]
- wget http://dl.bintray.com/rundeck/rundeck-deb/rundeck-2.6.2-1-GA.deb
- sudo apt-get install openjdk-7-jdk
- sudo dpkg -i rundeck-2.6.2-1-GA.deb
- Replace /etc/rundeck/rundeck-config.properties "grails.serverURL=http://localhost:4440" with "grails.serverURL=http://FQDN:4440"
- Appended "-Djava.net.preferIPv4Stack=true" to /etc/rundeck/profile in the RDECK_JVM path.
- service rundeckd start

RunDeck starts listening on TCP4:4440, which is cool... but I can't connect to it through an external host!

Is there an entry that I need to make to ensure that I can connect from a remote host? I figured since netstat shows 0.0.0.0:4440 I should be able to connect... but no joy. :(

**Comment by madhusudhanane** [comment]
Same issue on Amazon Linux. 

Couldn't connect to port 4440 , this port is open in security group , but still couldn't telnet to it

[root@PDXA-DEV-FAB01 rundeck]# netstat -ane |grep 4440
tcp 0 0 :::4440 :::* LISTEN 568 69267499

2016-02-02 20:17:38.337:INFO:/:Initializing Spring FrameworkServlet 'grails'
2016-02-02 20:17:38.364:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440

**Comment by madhusudhanane** [comment]
Initially i doubted ipv6 (https://github.com/oswaldlabs/chef-rundeck/issues/39) , but the issue was with the firewall that blocked my machine to bind to port 4440 :(

**Comment by abrahamrhoffman** [comment]
@madhusudhhanane , did disabling ipv6 in the kernel fix the issue?

**Comment by madhusudhanane** [comment]
@abrahamrhoffman , no, it was a firewall issue. Please check if there is a firewall that prevents you from accessing the port.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
