### ISSUE TITLE
Different Output when running from CLI vs Rundeck

### ISSUE THREAD

**Issue by rootameen** [rundeck/rundeck#1659]
Hi guys,

I'm having a major issue with my rundeck deployment. I have a script that connects to other devices and grab information. When I run the script locally using rundeck user I get the desired output without any issue.

However, when I put the EXACT SAME command as a local command in rundeck job, it doesn't fetch the output correctly. Redirecting the output to a file shows that it grabs a bunch of control characters (^M, ^H, and so on) which breaks my script. 

Why does rundeck behave this way? and how can I tackle this issue with bash and expect scripts? Unfortunately even using ssh -t in commands is not working and giving a Pseudo-terminal will not be allocated because stdin is not a terminal error. 

Please help.
Thanks.

**Comment by rootAmeen** [comment]
@gschueler any ideas?

**Comment by danifr** [comment]
What version of Rundeck are you using?

A similar issue was fixed on v2.4.1.
https://github.com/rundeck/rundeck/blob/development/CHANGELOG.md#issues-9

**Comment by ahonor** [comment]
Reopen if this remains a concern
