### ISSUE TITLE
Rundeck on oracle 12c

### ISSUE THREAD

**Issue by xwyz** [rundeck/rundeck#1661]
I'm trying to use an Oracle  database backend - unfortunately this does not seem to be working, I am hoping this is down to simple misconfiguration on my part.

So far I've done the following:

-  Installed rundeck and configured it to point to my Oracle instance, I've put the following in the settings file:
```
rundeck.v14.rdbsupport=true
dataSource.Url=[removed]
dataSource...
dataSource.dbCreate=update
dataSource.dialect=org.hibernate.dialect.Oracle10gDialect
rundeck.projectsStorageType=db
```
- Initially this failed to boot up as it could not create the tables in Oracle (multiple fields of type LONG), I remedied this by following advice in #676. I now have the tables setup.
- I try to run rundeck again but get the error:
`
getGeneratedKeys() support is not enabled
`
- I tracked this down to an issue on [StackOverflow](http://stackoverflow.com/questions/24050291/grails-hibernate4-upgrade-errors-on-getgeneratedkeys). I now boot rundeck with the command line parameter:
`
-Dhibernate.jdbc.use_get_generated_keys = true
`
- Rundeck now boots and things are starting to look a lot better. *However* when I now try to create a new project I get the following error under the project name field, in a red validation error box:
`
java.lang.ArrayIndexOutOfBoundsException: 9
`
- In the log I see:
`
ERROR FrameworkService java.lang.ArrayIndexOutOfBoundsException: 9
`
- Somehow the rest of the stack trace seems to have been swallowed.

Any ideas on what is going wrong here? Do you think it is misconfiguration or is this actually in issue with Oracle integration?

**Comment by gschueler** [comment]
What version of Rundeck?

If you partially started rundeck before, it could be some problem in the oracle tables that were created, maybe try clearing it out and starting again.

**Comment by xwyz** [comment]
Hi 

This is occurring with rundeck 2.6.1. Oracle version is 12c.

It's a good idea to check the tables for data - I have just checked them and they are all empty. Should I actually be seeing some content there initially, maybe something went wrong in the install process?

**Comment by ahonor** [comment]
@xwyz just installed 2.6.2 and configured to 12c w/o any errors. Was a clean install.

**Comment by xwyz** [comment]
Ok that's good news. I will try with 2.6.2 and report my findings.

Just to clarify I am running this standalone and not under tomcat, but I don't see how that could cause an issue.

So I can make sure I replicate your setup as best as possible could you post the contents of your rundeck configuration file used in the test?

**Comment by jquick** [comment]
I remember getting those errors from trying a newer ojdbc driver. I think we are still using something old like ojdbc14.

**Comment by ahonor** [comment]
@xwyz the datasource config I used was basically what you showed in your initial comment. I did download the newest driver jar file from the Oracle site.

**Comment by xwyz** [comment]
Thank you all for your guidance on this. Happy to report that this was not an issue with rundeck but a problem with the oracle driver I was using. Upgrading to the latest version of the ojdbc driver from oracle has resolved the issue.
