### ISSUE TITLE
IOException on rd-jobs list with yaml output format

### ISSUE THREAD

**Issue by dspinellis** [rundeck/rundeck#1663]
The  `rd-jobs list` yaml format output seems to be broken in version `RUNDECK version 2.6.2 (0)` on `Amazon Linux AMI release 2015.09`.

```
$ sudo -u rundeck rd-jobs list -f /tmp/rundeck-project.yaml -p cloud-admin -F yaml
Error: Failed request to list the queue: java.io.IOException: No such file or directory
$ sudo -u rundeck rd-jobs list -f /tmp/rundeck-project.yaml -p cloud-admin -F xml
# Found 17 jobs:
[...]
Wrote xml to file: /tmp/rundeck-project.yaml
```

The problems seems to be due to the lack of the `/tmp/rundeck` directory when the following system call is executed.

```
open("/tmp/rundeck/listStoredJobs9047096263674195687.yaml", O_RDWR|O_CREAT|O_EXCL, 0666)
```

which is created in `core/src/main/java/com/dtolabs/client/services/RundeckAPICentralDispatcher.java`

```
                temp= File.createTempFile("listStoredJobs", ".yaml");
```

The directory used is defined as follows:

```
packaging/root/etc/rundeck/profile:RUNDECK_TEMPDIR=/tmp/rundeck
```

However, apparently `/tmp/rundeck` is not created when Rundeck is installed. Another user [has reported](https://groups.google.com/forum/?fromgroups=#!topic/rundeck-discuss/I9DG6gpJtWo) what may be  the same problem.

**Comment by spuder** [comment]
I find that the /tmp/rundeck directory exists on my .deb installation of rundeck 2.6.4 on ubuntu 14.04

**Comment by aaroncline** [comment]
I ran into this issue on Rundeck 2.6.6.  It turns out you can just set an environment variable named "TEMP" with a writable path.  This will give java enough information to work with at least in my case...

```
export TEMP="/tmp/"
rd-jobs list -p PROJECT -f $TEMP/file.yaml -F yaml
```

**Comment by richiereynolds** [comment]
I don't think it matters whether it's created on installation or not. If a process is going to use a working directory, it shoud check if it's there first and if not, create it. This sounds like a clear bug to me.
