### ISSUE TITLE
Problem when running scripts from rundeck

### ISSUE THREAD

**Issue by Grey-Hunter** [rundeck/rundeck#1665]
Hi all,
I'm using rundeck to automate running command in Junos-running routers/switches at my envirenoment. I'm using expect scripts to spwan SSH to the devices to run some commands and preview the results on the web interface of rundeck. 

The problem occur only when I run long commands as this example:

show pfe statistics traffic | match fabric | no-more

The output will be presented as the following:

<img width="218" alt="screen shot 2016-02-08 at 10 34 33 pm" src="https://cloud.githubusercontent.com/assets/17129147/12896608/e583c6d4-ceb3-11e5-9b8b-0ab646b239a8.png">

But when I try to run the same command from within the rundeck server using the command line it work smoothly:

re0> show pfe statistics traffic | match fabric|no-more 
    Fabric drops               :                    0

{master}

What can be the casue for such behavior?

Of course running any shorter commands will work just fine.

Thanks.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
