### ISSUE TITLE
Script-based plugin setting for merging parent environment variables

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#1666]
The script-based plugin (especially on windows) should have a setting indicating the environment variables from the parent process (aka the rundeck server process) can be inherited by the plugin script.

Currently, it provides execution context as env vars:
https://github.com/rundeck/rundeck/blob/7ce2d894213c26e490d9d2c89e5b219c29016d27/core/src/main/java/com/dtolabs/rundeck/core/utils/ScriptExecUtil.java#L164

**Comment by gschueler** [comment]
* adding provider setting `mergeEnvironment`
* adding new `rundeckPluginVersion` value "1.1", defaulting this value to true

~~~{.yaml}
name: example script-based node step plugin
version: 1.0
rundeckPluginVersion: 1.1
providers:
  - name: example-node-step
    service: WorkflowNodeStep
    title: Example Script Node Step
    description: Does nothing
    mergeEnvironment: true

~~~

The default value is `false` if `rundeckPluginVersion: 1.0`, and `true` if `rundeckPluginVersion: 1.1` or later.
