### ISSUE TITLE
Add documentation for changing date formats, and general localization

### ISSUE THREAD

**Issue by rasebo** [rundeck/rundeck#1667]
I modified _rundeck/exp/webapp/WEB-INF/grails-app/i18n/messages.properties_, following the format here: http://momentjs.com/docs/#/displaying/format/ in order to adjust how rundeck is displaying the date and time. The relevant lines now read:
```
# date format used in content of All Events list items
jobslist.date.format=YYYY-MM-DD hh:mm
jobslist.date.format.ko=YYYY-MM-DD hh:mm
jobslist.running.format.ko=hh:mm
```
This produced the required changes to the date's format, but I have just noticed that when February started, the increment for the days was not reset to 1:
<img width="387" alt="screen shot 2016-02-09 at 16 20 51" src="https://cloud.githubusercontent.com/assets/1422444/12922420/50ac4900-cf49-11e5-8308-72cd1fba2ebd.png">
It now looks like we are on day 40 in February:
<img width="474" alt="screen shot 2016-02-09 at 16 17 09" src="https://cloud.githubusercontent.com/assets/1422444/12922430/5f220f92-cf49-11e5-8e78-28294c811cc5.png">
... which makes me think it either does not reset the increment, or it's just using DDD for some odd reason (which stands for Day of Year) instead of DD.

I am not sure that my modifications on the date format had any impact on this, but I thought it would be worth mentioning.

**Comment by gschueler** [comment]
the `jobslist.date.format` uses Java SimpleDateFormat, which is different than the moment.js format used by `jobslist.date.format.ko`.

in this case `D` is "day in year", for the java format.  Try changing to:

~~~{.properties}
    jobslist.date.format=yyyy-MM-dd hh:mm
~~~

**Comment by rasebo** [comment]
Right, this did it, thanks. 
Perhaps it would be a good idea to document this somewhere?

**Comment by gschueler** [comment]
@rasebo yes, it would be useful, i think a general "localization and customization" guide would be nice to have.  I will change the title of this issue to reflect that

**Comment by ssbarnea** [comment]
I think that the problem is bigger, read https://github.com/rundeck/rundeck/issues/1682#issue-133928883 -- RunDeck has bad default setting for date-time formats, it was supposed to be ISO-8601 which is the first thing to do.

**Comment by rasebo** [comment]
Well, to be honest, besides making the product less US-centric and more global, I think it would also make sense having an option in the product that would help users select different localisation settings. 

I think this would be a good improvement and should be on the roadmap.

**Comment by gjvc** [comment]
operations tools which have *time* at the core of their operation and which have an international userbase (follow-the-sun support coverage) should use ISO-8601, no question. 

 I'm deploying under docker using the official rundeck image and i can't apply the change described here.   It's depressing that i can't change this in 2022.

**Comment by ssbarnea** [comment]
LOL, reading this ticket reminded me of old times and made me realise that I did not make the wrong decision to avoid rundeck in 2016 and start using Ansible. Surprise, years later I see myself part of Ansible.

@rasebo Hi! Long time no see! I guess it is the time to close the ticket as they will never look at it.
