### ISSUE TITLE
[CLI] Use token instead of user/pass

### ISSUE THREAD

**Issue by pygillier** [rundeck/rundeck#1671]
Currently we need to pass all env vars (URL, USER and PASS) to run jobs from cli. (the doc needs to be updated to tell **all** vars are required to change user)

As it is available on API, we should be able to launch jobs from cli with a `--token` parameter.

**Comment by gschueler** [comment]
cli tools removed in 2.7.0 use [rd](https://rundeck.github.io/rundeck-cli/), it supports token authentication
