### ISSUE TITLE
Scheduled Jobs do not fill variables from URL

### ISSUE THREAD

**Issue by Mithgaraf** [rundeck/rundeck#1675]
Job details:
- calls a local-to-rundeck-host script
- variable provided is filled from URL
- runs on a schedule once every 4 hours

Problem:
- default (blank) value gets used instead of the value pulled from the URL when on a scheduled run.
- URL value gets used when the job is run manually.

This renders my job relatively unschedulable via RunDeck.  I will have to have cron run a script that calls that script with the value returned by the URL.

(I shouldn't have to do this.)

**Comment by ahonor** [comment]
@Mithgaraf Remote options can now define a default which should be selected. See http://rundeck.org/docs/manual/jobs.html#json-format
