### ISSUE TITLE
Kill does not work for jobs on a schedule

### ISSUE THREAD

**Issue by SergeyCherman** [rundeck/rundeck#1676]
Issue reproduced on: 2.6.2 and 2.4.1

When a job has a schedule, and is being run on demand and a kill is issued the job will still finish. Example job script is:
echo "start"
sleep 10s
echo "finish"

Job is kicked off manually and I issue a kill command, the Job says killed but will finish regardless and in the log will show both a kill and a succeed with the log output as "start \n finish". If the job does not have a schedule then kill will terminate the job as expected.

**Comment by koolay** [comment]
I have the same problem

**Comment by ahonor** [comment]
Could not reproduce in 2.10. Please reopen if this remains a concern
