### ISSUE TITLE
Code example in documentation incorrect

### ISSUE THREAD

**Issue by Alicia-Solinea** [rundeck/rundeck#1678]
In the Plugin Developers Guide, there is a code example on how to push notifications to HipChat via a groovy script: http://rundeck.org/docs/developer/notification-plugin.html#execution-data

in the "MinimalNotificationPlugin.groovy: " exmaple - the code is as follows:

....
_onstart { 
        println("success: data ${execution}")
        true
    }_
......
_ onsuccess {
        println("job start: data ${execution}")
        true
    }_

....
These print lines should be reversed. This issue also appears in the "MyNotificationPlugin.groovy: " code example.

**Comment by gschueler** [comment]
thanks for the issue report
