### ISSUE TITLE
ShellScriptNotificationPlugin.groovy and ${execution.<parameters>}

### ISSUE THREAD

**Issue by albundy83** [rundeck/rundeck#1679]
Hello,

I have added the plugin ShellScriptNotificationPlugin.groovy in folder /var/lib/rundeck/libext/ (I'm under debian 7) and I have then tried to used it...
I have created a script that take all the parameters like this : 
```bash
APP=$1
TAG=$2
PROJECT=$3
JOBNAME=$4
JOBID=$5
EXECID=$6
EXEC_DATESTARTED=$7
EXEC_DATEENDED=$8
EXEC_STATUS=$9
EXEC_HREF=${10}
```
I have then configured Shell Script in Notification with the following parameters : 
Path to script : 
```bash
/root/my_script.sh
```
Arguments : 
```bash
"${option.APP}" "${option.TAG}" "${job.project}" "${job.name}" "${job.id}" "${job.execid}" "${execution.dateStarted}" "${execution.dateEnded}" "${execution.status}" "${execution.href}"
```

But I have a problem with all ${execution.*} parameters.
They are not interpreted.
As comparison, I have tried to send all those parameters using builtin "Send Email" notification, and it works because I receive everything.
I don't know what is causing the issue.

Thanks for your help.

**Comment by gschueler** [comment]
Hi, the `${execution.href}` variable is not available in the arguments to the notification.  it is available within the context of the notification plugin, so you could modify the plugin code to use it.  but when you pass the script arguments via the notification setting in a job, that string is only interpreted using the context data available to the job.  Sorry, there is a difference between the data available within the plugin's code, vs. the data context available in the job.

you could modify the plugin (or create a custom version of it) to do what you want. 

you could replace `${execution.href}` with `${job.url}`, however and that should work.

**Comment by albundy83** [comment]
Yes, that's what I have finally done.
I have added directly in the groovy script the missing variables : 
"${execution.dateStarted}" "${execution.dateEnded}" "${execution.status}" "${execution.href}"
Thanks again for your answer.
