### ISSUE TITLE
Default date and time format should be ISO-8601

### ISSUE THREAD

**Issue by ssbarnea** [rundeck/rundeck#1682]
As any serious application, the default settings should be standardised ones, not specific to a single geography.

Default date and time format should be [ISO-8601](https://en.wikipedia.org/wiki/ISO_8601) so anyone would be able to read them, not only US based users.

**Comment by ahonor** [comment]
+1

**Comment by rasebo** [comment]
+1

**Comment by albundy83** [comment]
I got the same need with execution.dateStarted and execution.dateEnded variables that I want to use in a notification plugin (ShellScriptNotificationPlugin.groovy).
I have just added the following lines to convert it easily : 
```groovy
Date dateS = Date.parse( "yyyy-MM-dd HH:mm:ss.SSS", execution.dateStarted.toString() )
String dateStartedIso8601 = dateS.format( "yyyy-MM-dd'T'HH:mm:ss.SSSZ" )

Date dateE = Date.parse( "yyyy-MM-dd HH:mm:ss.SSS", execution.dateEnded.toString() )
String dateEndedIso8601 = dateE.format( "yyyy-MM-dd'T'HH:mm:ss.SSSZ" )
```
Have a good day.

**Comment by danifr** [comment]
+1

**Comment by gjvc** [comment]
+1000
