### ISSUE TITLE
any plans for a gradle upgarde ?

### ISSUE THREAD

**Issue by atlasloewenherz** [rundeck/rundeck#1683]
The latest release of Gradle is version 2.11, released on 8th February 2016, and the rundeck project is still using the gradle 1.11.

this is a kind of reminder that this does not get lost as a todo.

**Comment by gschueler** [comment]
yes i made a stab at upgrading to gradle 2.8 a bit ago (and removing maven pom's, which are not functioning anyway).

I will push a branch, which i'm not sure if it is complete or not yet, a PR will pass it through travis for build testing however so we can see where we are.

**Comment by ahonor** [comment]
Currently on gradle 3.5
