### ISSUE TITLE
stdout & stderr appearing out of order in script job output

### ISSUE THREAD

**Issue by pwhack** [rundeck/rundeck#1687]
I have a job in v2.6.2 with a single Bash script step. If the specifics of what the script does are pertinent I can include a copy but the issue I'm seeing appears to be related to how Rundeck is merging stdout and stderr output. The script includes some simple echo statements giving a friendly explanation of what's about to happen then a command is run. The echo statements and zero-status exiting command output is appearing in order correctly in the Job Output tab. But if the commands sent anything to stderr, that content is out of context with stdout and will appear somewhere else in the stdout stream. Attached is a sample output of what I mean:

[sample_bad_output.txt](https://github.com/rundeck/rundeck/files/135208/sample_bad_output.txt)

Here's how I would expect the order to be:

[sample_good_output.txt](https://github.com/rundeck/rundeck/files/135213/sample_good_output.txt)

**Comment by jdlc** [comment]
+1

**Comment by varCharlie** [comment]
+1 This would be very helpful.

**Comment by deepkamal** [comment]
facing the same problem, can it be worked uppon?
