### ISSUE TITLE
Does rundeckdb.trace.db really need be backup?

### ISSUE THREAD

**Issue by SydOps** [rundeck/rundeck#1689]
In document `backup and recovery` (http://rundeck.org/docs/administration/backup-and-recovery.html#backup), we are asked to backup the whole data folder `/var/lib/rundeck/data`

But seems the file `rundeckdb.trace.db` is plain text file with a lot of errors in it (Currently in my environment, there are ldap error reported) , it makes the file really big. 
```
[rundeck@rundeck data]$ file rundeckdb.trace.db
rundeckdb.trace.db: ASCII text
[rundeck@rundeck data]$ file rundeckdb.h2.db
rundeckdb.h2.db: data

[rundeck@rundeck data]$ head -5  rundeckdb.trace.db
02-17 12:21:29 jdbc[3]: exception
org.h2.jdbc.JdbcSQLException: Feature not supported: "isWrapperFor" [50100-176]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:344)
	at org.h2.message.DbException.get(DbException.java:178)
	at org.h2.message.DbException.get(DbException.java:154)

```

I take care the ldap error by myself, backup is serious thing I am working on. I upload the `data` folder to s3 bucket daily, so need know your option, if I DO need backup `rundeckdb.trace.db` or not.

If that's only log in it, shouldn't be named as `*.db`, maybe `rundeckdb.trace.log` is better name, and should be moved to `logs` folder

**Comment by ahonor** [comment]
@SydOps I would treat it as kind of debug information. I don't use it.

**Comment by gschueler** [comment]
@SydOps it is not needed.  see this issue too https://github.com/rundeck/rundeck/issues/1175#issuecomment-97610012

**Comment by SydOps** [comment]
thanks, @ahonor & @gschueler
