### ISSUE TITLE
ldap, user role and group

### ISSUE THREAD

**Issue by SydOps** [rundeck/rundeck#1691]
I have successfully set ldap/ldaps in rundeck, now I need set permission on resources that ldap users can access.

There are two ldap groups: "level3_users" and "level4_users" 

I'd like to give full permission to "level4_users" and limit permission to "level3_users"

I target the setting on `admin.aclpolicy`, but only work fine with group `user`. 

So how to create a new group "level3_users" and "level4_users" in rundeck?

how to automatically map ldap groups to rundeck groups?

Can I set more roles in `exp/webapp/WEB-INF/web.xml`?

**Comment by gschueler** [comment]
LDAP roles are assigned to the user, based on the LDAP configuration.  You should be able to see what roles are assigned to a user after login, in the "Profile" link under the account name in the page header.

Given those user roles, you can then define ACLs for the same names, so you would use "level3_users" as the group name to match in the ACL file.

**Comment by SydOps** [comment]
Thanks, @gschueler 

login with a ldap account, and the profile group is `user` only.

Here is my jaas-auth.conf file for your reference.

```
[root@rundeck rundeck]# cat jaas-auth.conf
authentication {

  org.eclipse.jetty.plus.jaas.spi.PropertyFileLoginModule required
  debug="true"
  file="/etc/rundeck/realm.properties";

  com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
  debug="true"
  contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
  providerUrl="ldaps://ldap.example.com"
  authenticationMethod="simple"
  forceBindingLogin="true"
  userBaseDn="cn=users,cn=accounts,dc=np,dc=example,dc=com"
  userRdnAttribute="uid"
  userIdAttribute="uid"
  userObjectClass="posixAccount"
  roleBaseDn="cn=groups,cn=accounts,dc=np,dc=example,dc=com"
  roleNameAttribute="cn"
  roleMemberAttribute="memberUid"
  roleObjectClass="posixGroup"
  supplementalRoles="user"
  cacheDurationMillis="300000"
  reportStatistics="true"
  nestedGroups="true";


};
```

**Comment by SydOps** [comment]
seems I didn't set properly on `supplementalRoles`

**Comment by SydOps** [comment]
after I updated `supplementalRoles` to   

    supplementalRoles="user,level3_users,level4_users"

Seems I can manage the users with proper permission. 

But not sure why I have to add user in `supplementalRoles`, if I remove `user` and keep the rest two groups, I got `!role` issue when login.

**Comment by gschueler** [comment]
@SydOps the supplementalRoles are added *in addition* to any roles discovered via LDAP, typically you only add "user" since that is a requirement of the web-app security constraint for Rundeck.

it sounds like your LDAP role search is not returning the results you expect

**Comment by SUJER** [comment]
I am having a similar issue, I have a LDAP group rundeck_dev and I don't want to use realm.properties file  providing access to an individual user instead I want to add the user in LDAP group so that he should get access to projects and jobs

so is there any workaround to use LDAP groups and how to map groups to those projects ACL groups.

**Comment by avnban1988** [comment]
@SUJER How are you linking individual user with with Project in rundeck. Can you please provide sample configuration
