### ISSUE TITLE
Confusion between "Simple" and "Crontab" scheduling

### ISSUE THREAD

**Issue by NashGlover** [rundeck/rundeck#1692]
I have a job that used to run at the first of every month. I set this using the crontab style scheduling. Later I wanted to set it to run a weekly schedule. To do this, I just used the "Simple" scheduling. The text that says "Next execution in ..." beside the job is still set to the first of the month. When I look at the job definition view, it says "Schedule: at 06 : 30 every Sunday". And underneath it shows the "Next execution in ..." still set to the first of the month.

There seems to be some confusion as to which scheduling type it's accepting. Maybe there needs to be a more definitive choice that shows in the UI between the crontab and the simple scheduling so that there isn't confusion? Like if "Simple" is chosen when the save button is clicked, that will be reflected in the "Next execution in ..." dialogue.

**Comment by gschueler** [comment]
this sounds like a bug, if you select "Simple", it should honor that

**Comment by NashGlover** [comment]
The "Next execution in... " text is now correct and it ran on Sunday as we wanted.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
