### ISSUE TITLE
import certificate to enable ldaps 

### ISSUE THREAD

**Issue by SydOps** [rundeck/rundeck#1694]
Hi 

I followed the steps in [Communicating over secure ldap (ldaps://)](http://rundeck.org/docs/administration/authenticating-users.html#communicating-over-secure-ldap-ldaps) 

I successfully did it to import certificate to `$JAVA_HOME/lib/security/cacerts`, and login with ldap account. But I can't make it work to import certificate to `/etc/rundeck/ssl/truststore`. Are there any steps I missed?

**Comment by elvin159** [comment]
assuming you already used the keytool command to import it into /etc/rundeck/ssl/truststore. 

you need to add the following in your /etc/rundeck/profile after the last export of RDECK_JVM

`RDECK_JVM="$RDECK_JVM $RDECK_SSL_OPTS"
`

**Comment by SydOps** [comment]
@elvin159 

Thanks to provide the solution. 

Has no chance to test it, since my rundeck is running well. I close it first.
