### ISSUE TITLE
any plan to support ssh port in node definition?

### ISSUE THREAD

**Issue by fanyeren** [rundeck/rundeck#1695]
in my company，ssh port is not 22

**Comment by gschueler** [comment]
you can set `hostname="host:123"` in the node definition to supply the SSH port

**Comment by fanyeren** [comment]
@gschueler  thanks

**Comment by mostlyvirtual** [comment]
I hope it's OK that I'm re-opening this, but I can't find a place to modify the node definition in Rundeck 3.0.22-20190512.
I added the node via the Rundeck web panel, and I'm not sure where it stores the config file.
