### ISSUE TITLE
Add ability to list projects with rd-project

### ISSUE THREAD

**Issue by jyaworski** [rundeck/rundeck#1696]
Hello:

In trying to implement a fix to https://github.com/voxpupuli/puppet-rundeck/issues/181 I noticed that <code>rd-project</code> has no option to list projects. Could this be added?

**Comment by gschueler** [comment]
+1 yes it should be added

**Comment by ahonor** [comment]
rd-project is obsolete but the new `rd` CLI tool does list projects
