### ISSUE TITLE
Add ability to overwrite project parameters with rd-project

### ISSUE THREAD

**Issue by jyaworski** [rundeck/rundeck#1697]
Hello:

In trying to implement a fix to https://github.com/voxpupuli/puppet-rundeck/issues/181 I noticed that <code>rd-project</code> has no option to overwrite a project parameter; it only works if the project doesn't exist. Can we have an 'update' functionality, such that if I wanted to use rd-project to change project properties of an existing project, I could?

**Comment by gschueler** [comment]
it is supported in the API, so shouldn't be that hard to add to the CLI tool

**Comment by ahonor** [comment]
The `rd` CLI supports this and rd-project is now obsolete
