### ISSUE TITLE
Rundeck i18n - how to translate plugins?

### ISSUE THREAD

**Issue by miguelantonio** [rundeck/rundeck#1698]
Hi guys, I'd like to know your suggestion/architecture to translate plugins, as they have usually text on the implementation, we are interested in a full spanish rundeck and will contribute to it, so any tips or existing way to do it?

Thanks!

**Comment by gschueler** [comment]
@miguelantonio good question! I think we will need to extend the plugin property attributes and provide a way to supply a messages.properties bundle in a plugin.

**Comment by ahonor** [comment]
Plugins now support i81n http://rundeck.org/docs/developer/plugin-development.html#plugin-localization
