### ISSUE TITLE
acl exception for admin

### ISSUE THREAD

**Issue by guya65** [rundeck/rundeck#1705]
when using 
1: Default admin  acl policy
2: AD authentication
3: Groups with spaces in them

It appears we can run adhoc jobs on a node but not view them

```
2016-02-23 17:05:49,800 - Evaluating Decision for: res<type:adhoc> subject<Username:guy.attrill Group:APP Rundeck Admin EMEA> action<run> env<http://dtolabs.com/rundeck/env/project:ServiceDeskAdmin>: authorized: false:  No context matches subject or environment => REJECTED_NO_SUBJECT_OR_ENV_FOUND (0ms)
```

**Comment by ahonor** [comment]
Can you post your policy file?

**Comment by guya65** [comment]
description: Admin project level access control. Applies to resources within a specific project.
context:
  project: '.*' # all projects
for:
  resource:
    - equals:
        kind: job
      allow: [create] # allow create jobs
    - equals:
        kind: node
      allow: [read,create,update,refresh] # allow refresh node sources
    - equals:
        kind: event
      allow: [read,create] # allow read/create events
  adhoc:
    - allow: [read,run,runAs,kill,killAs] # allow running/killing adhoc jobs
  job:
    - allow: [create,read,update,delete,run,runAs,kill,killAs] # allow create/read/write/delete/run/kill of all jobs
  node:
    - allow: [read,run] # allow read/run for nodes
by:
  group: "APP Rundeck Admin EMEA"

---

description: Admin Application level access control, applies to creating/deleting projects, admin of user profiles, viewing projects and reading system information.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      allow: [create] # allow create of projects
    - equals:
        kind: system
      allow: [read,enable_executions,disable_executions,admin] # allow read of system info, enable/disable all executions
    - equals:
        kind: system_acl
      allow: [read,create,update,delete,admin] # allow modifying system ACL files
    - equals:
        kind: user
      allow: [admin] # allow modify user profiles
  project:
    - match:
        name: '.*'
      allow: [read,import,export,configure,delete,admin] # allow full access of all projects or use 'admin'
  project_acl:
    - match:
        name: '.*'
      allow: [read,create,update,delete,admin] # allow modifying project-specific ACL files
  storage:
    - allow: [read,create,update,delete] # allow access for /ssh-key/* storage content

by:
  group: "APP Rundeck Admin EMEA"

**Comment by dsumike** [comment]
Using Rundeck 2.6.x, I was able to authenticate against an Active Directory group with spaces by formatting the permission as follows:

group: ['APP Rundeck Admin EMEA', 'My Other Group']

**Comment by guya65** [comment]
if you run an adhoc job can you view the results?

**Comment by ahonor** [comment]
Please reopen if this remains a concern
