### ISSUE TITLE
Listing Running Executions API, "Total" error value using wildcard ("*") in the URL

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#1711]
Using "GET /api/15/project/[PROJECT]/executions/running " returns an invalid value for "total" parameter. This is only when it requests information about all projects using wildcard ("*") .

For example

1) GET /api/15/project/*/executions/running
I get this:
{"paging":{"count":5,"total":0,"offset":0,"max":20},"executions":[{"id":149,"href":"http://luisao-ubuntu:4440/api/15/execution/149","permalink -....................................

As you can see It returns total = 0

2) Then,  I try again but setting the project name in the URL:

GET /api/15/project/test/executions/running

{"paging":{"count":5,"total":5,"offset":0,"max":20},"executions":[{"id":159,"href":"http://luisao-ubuntu:4440/api/15/execution/159","permalink" ....................................

In this case the total value works properly.

The rundeck version is 2.6.2

Best
Luis

**Comment by miguelantonio** [comment]
Also happens in 2.6.3
