### ISSUE TITLE
SCP copy fails with domain user (Two @ symbols)

### ISSUE THREAD

**Issue by juanitocalero** [rundeck/rundeck#1715]
I have configured a node with a domain user: `user@mydomain`
The node is in other domain: hostname is `server.myotherdomain`
Both domains are connected networks of Windows machines with Active Directory permissions.

I'm using the new (beta) OpenSSH provided by Microsoft's powershell team

Command line SSH login works OK with:
`ssh -l user@mydomain server.myotherdomain`
or
`ssh user@mydomain@server.myotherdomain`

Command line SCP works OK with

`scp myfile user@mydomain@server.myotherdomain:remotefile`

Now, in Rundeck, SSH login and command execution works correctly too with this configuration. 
Unfortunately, SCP copy fails with this error when called through Nexus workflow step copy:

(real names edited)

```
Nexus request status: 200, Content-type: application/java-archive, Content-length: 68563602
17:07:04            Begin copy 68563602 bytes to SERVER:c:\folder
17:07:04            Using ssh password storage path: keys/user
17:07:04            copying file: 'C:\cygwin64\tmp\nexus-get-artifact8237091009962309853.tmp' to: 'SERVER:c:\pixeltemp'
17:07:04            Set timeout to 0
17:07:04            Connecting to mydomain@server.myotherdomain:22
17:07:04            Connecting to mydomain@server.myotherdomain port 22
17:07:04            mydomain@server.myotherdomain
17:07:04            failed: [jsch-scp] Failed copying the file: mydomain@server.myotherdomain
17:07:04            Remote copy failed for node: SERVER
```

The internal stacktrace shows this error:

```
Caused by: java.net.UnknownHostException: mydomain@server.myotherdomain
```

Looks like jsch-scp is getting confused with the use of two @ symbols.

**Comment by ahonor** [comment]
HI @juanitocalero, Not sure the [jsch](http://www.jcraft.com/jsch/) library will be modified to accept `user@domain` as the "user" identifier. SCP traditionally uses `user@host:directory/targetfile` addressing.

**Comment by Novitoll** [comment]
+1

**Comment by andreykhr** [comment]
Hi, you can use ssh options

`scp -o "User=user@mydomain" myfile server.myotherdomain:remotefile`
