### ISSUE TITLE
Doesn't remember login

### ISSUE THREAD

**Issue by scalp42** [rundeck/rundeck#1724]
We noticed that the time after login that it remembers the auth is very short (we have to relogin every couple hours).

Not sure if it's a bug or we're missing something.

Thanks in advance for the help!

**Comment by scalp42** [comment]
Solution was:

- edit `/var/lib/rundeck/exp/webapp/WEB-INF/web.xml` (change path depending on you Rundeck install)
- find `<session-config>
- bump it:

```
        <session-config>
                <session-timeout>43200</session-timeout>
        </session-config>
```

**Comment by gschueler** [comment]
Thanks, I added your comment to the [FAQ](https://github.com/rundeck/rundeck/wiki/Faq#how-do-i-change-the-default-session-timeout-duration)

**Comment by sebw** [comment]
Is there any plan to port this setting to rundeck-config.properties?

/var/lib/rundeck/exp/webapp/WEB-INF/web.xml is installed by the RPM and I don't want to change it for different reasons:
- we install Rundeck with Saltstack, changing a setting after deploying a WAR is not impossible but still complex
- future package update bringing changes to web.xml would not be applied (would be placed in web.xml.rpmnew)

Thanks

**Comment by gentunian** [comment]
That would be great for monitoring users and have session timeout per user.

My case is a monitor in the wall showing all the activity logged as user `activity` with only that role. I wish *he* never logs out :(

**Comment by lw-schick** [comment]
@gschueler  Would be nice to know in the FAQ what f.e 43200 means in minutes/hours ...

**Comment by Nimble85** [comment]
I added to file "rundeck-config.properties" 

server.session.timeout: timeout in seconds

**Comment by JesusRo** [comment]
> 
> 
> That would be great for monitoring users and have session timeout per user.
> 
> My case is a monitor in the wall showing all the activity logged as user `activity` with only that role. I wish _he_ never logs out :(

Maybe a kiosk mode whould be a nice funtionallity
