### ISSUE TITLE
After 2.6.3 upgrade, nodes are not updated

### ISSUE THREAD

**Issue by joshuaspence** [rundeck/rundeck#1725]
This might be related to #1716. After upgrading to v2.6.3, it seems that Rundeck is not detecting new nodes correctly. We are using the AWS provider and new instances are not being shown in the UI. I'm guessing that it is related to this change:

> Asynchronous nodes cache. Per-project and global toggle and configurable retention delay. By default, projects now use an asynchronous method for retrieving Node data from Resource Model Sources. You should see an improvement in page load when using slow model sources (such as a URL for a slow endpoint).

**Comment by gschueler** [comment]
it may be a UI bug #1716 if so you would see javascript error in the browser console

otherwise, it may be related to the ec2 nodes provider: it has its own asynchronous cache of nodes.  Try disabling the asynchronous cache in that project and see if it resolves the nodes.  the ec2 provider needs to be updated to allow disabling its internal asynchronous cache.

**Comment by schast** [comment]
i don't think this is related to UI bug #1716.
After setting "project.nodeCache.enabled=true" the "resources.source.1.config.url" is never been called.

this is my project config:
```
project.nodeCache.delay=10
project.nodeCache.enabled=true
resources.source.1.config.cache=false
resources.source.1.config.timeout=30
resources.source.1.config.url=http\://myserver/cgi-bin/NodeProvider.pl
resources.source.1.type=url
```

Rundeck Version: 2.6.4

**Comment by fiquett** [comment]
Same issue.. Rundeck Version: 2.6.4.. 
Confirmed on the web server providing node resource via access logs..

URL only gets accessed once when saving "Resource Model Source" configuration but doesn't seem to get refreshed after that.
