### ISSUE TITLE
execute job on rundeck server other than rundeck user

### ISSUE THREAD

**Issue by rangsan** [rundeck/rundeck#1726]
The job always execute as rundeck user on the node rundeck server both node selection method "execution locally and dispatch to nodes", no matter what i set to other user in the node/project/framework configuration.

I would like to run job as different user on rundeck server itself.
rundeck v. 2.6.3-1
linux centos 6.6 2.6.32-504.3.3.el6.centos.plus.x86_64

**Comment by kylepolich** [comment]
This is an important feature I would also like to take advantage of.

**Comment by anmaon** [comment]
This feature is needed for us too. Is there any update on this ?

**Comment by falloutphil** [comment]
I've just downloaded RunDeck to replace manual processes we have running.  The processes are tied to accounts and many run on localhost.  Not being able to default what account scripts are run under, means a quick transition is now tied-up with complications.... This makes it hard to sell the product to management - they won't want to here about sshing back onto the box, etc, etc.  There should be a single place in the config which sets what rundeck child processes run-as by default on localhost.

**Comment by ahonor** [comment]
@falloutphil question: is sudo an acceptable underlying mechanism to change user?

**Comment by falloutphil** [comment]
Thanks @ahonor for reply!

So we sudo from rundeck account to our production account(s)?  That might work.

For now I've got it working by sshing back into the box as the production user - it works fine, but it's a bit messy.

**Comment by ahonor** [comment]
@falloutphil ok, yes I know of that convention to ssh back to the otheruser@rundeckserver which might be ok but you have to define a special node for it. I was thinking about a new step plugin that basically wraps sudo and lets you run a local command

**Comment by falloutphil** [comment]
@ahonor yes that's exactly what I've done.

Can you walk me through the step plugin suggestion?  This is my first day of RunDeck, so assume I know next to nothing :-)

**Comment by ahonor** [comment]
@falloutphil here's an example. Let me know what you think as issues there: https://github.com/ahonor/sudo-command-step

**Comment by falloutphil** [comment]
Thanks for this @ahonor 

Am I correct in thinking this will allow me to run a **single** command line into the local box via sudo?

* Will each command effectively be run in it's own isolated sub-shell which will then terminate on command completion for that step - so there there is no continuity of environment.  Rather than sudo-ing into an account and providing a sequence of steps under that account before terminating the shell? 
* Can you confirm with the ssh solution once the node is setup, does a **single** job create a new login for each command step too?  If this is the case then the sudo solution should be leaner then negotiating an ssh login each time.  I hadn't thought about at this but had (perhaps incorrectly) assumed that a single ssh session would be started per-job-per-node and commands pumped into it, rathe rthan starting a new session for each step? 

I accept all this could be minimized by batching stuff up into scripts to minimize the number of sudo calls, but this hides steps from non-technical users who will only be viewing progress at the job/step level.

**Comment by ahonor** [comment]
@falloutphil each command step is it's own invocation and there is no continuity from a shell process standpoint. Regarding the step plugin, please direct your questions to that repo.

**Comment by tsolodov** [comment]
Hi Rundeck Team.

It's important feature. Are you planning to implement it?

**Comment by ahonor** [comment]
@tsolodov I have seen some sudo based plugins for local step execution. Would that work for your need?

**Comment by tsolodov** [comment]
No, it would not. But thank you for suggestion!

**Comment by auscop** [comment]
I have been althrough Rundeck doco and I am left wondering if I am missing something. If I read this correctly there is still no way to run a command as a different user without using a sudo plugin? I work in an environment were I would like to create jobs that can run on up to 1000+ Linux servers. Having to add an NPE user of rundeck accross our entire environment would be a nightmare with the security folk. I would think it would be a standard Rundeck feature to be able to choose a username and password when you create a job. Even better still have the ability as an option to enter a username/password at job execution. I have also noticed when I add nodes via a "Ansible Resource Model Source" I can select an "ssh user" the job will then run as that user, but if I unselect "Gather Facts" it then defaults back to trying to run the job as user "rundeck". This ticket has been open for over 3 years now and it seems to be getting zero attention. :(

**Comment by niall-munnelly** [comment]
Hi,
You can define the user as anyone you want in the node and project definitions if you have credentials, and these can also be set to context variables derived from job options:

This value can also include a property reference if you want to dynamically change it, for example to the name of the current Rundeck user, or the username submitted as a Job Option value:

${job.username} - uses the username of the user executing the Rundeck execution.
${option.someUsername} - uses the value of a job option named "someUsername".
The same holds true for passwords, key pass phrases, etc:

https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html#ssh-password-with-a-job-option

**Comment by auscop** [comment]
Hi Niall-Munnelly,  Yep I had a look at that document a couple of times. All the examples shown seem to be for if a user is using the filesystem to store their projects and they can manually edit the config files. Currently mine is in mariadb and I am not a DBA. I am attempting to do all my configuring through the web browser. And the only place I ever see an option for a username (ssh user) is under Nodes in my project configuration. As for project definitions my only options I see are for ssh keys and password, I see no where to enter a username.  The option of using ${job.username} would be great but I am at a loss of where I define this.  I am running Rundeck 3.1.2-20190927. I can post configs and screenshots if needed.  Thanks for your input.

**Comment by niall-munnelly** [comment]
You have to define these by editing the project configuration and nodes, assuming you have edit rights. My resource files are on-disk, but I edit them in the UI (and I've been toying with the idea of using git).

I put up a couple gists for you - one [nodes.yaml](https://gist.github.com/niall-munnelly/882e3047b868b5cf8181366dbf8ae5f5) and one [job definition](https://gist.github.com/niall-munnelly/f84f496ef3b63b450ec3bb133fb754b3) - for you to see practical examples of this.

**Comment by auscop** [comment]
Niall-munnelly,  Thanks for that, was very helpful. Looks like my main issue was I was only importing my nodes from an Ansible Inventory, when I do that there is no yaml/xml/json file to edit. I had been looking everywhere for an editable file or a place to put a username. It looks like if you use an Ansible Inventory you don't get this option. I am guessing the quickest solution for me is to write a script to read my Ansible inventory file to create a yaml file that I then use to import all my hosts so I can and the username options.  Very helpful thanks.

**Comment by puremourning** [comment]
look at the docs for resource model provider ‘plugins’.

**Comment by auscop** [comment]
puremourning,  l have looked at that documentation a number of times, I find information on EVERY Resource Model format except Ansible. When I add my 500+ nodes via the "Ansible Resource Model Source" they are succesffully imported, yet when you select the "Edit" tab after the import you get a message of "No modifiable sources found". All my projects are in Mariadb so I am unable to edit via the CL.

**Comment by puremourning** [comment]
does your ansible inventory include things like `andible_user` ? if so, does the sensible resource model not set the username for the node ?

**Comment by auscop** [comment]
After further testing for some reason the SSH user I have in the Ansible Playbook workflow is now being accepted when at other times it was ignored and the play would always run as the rundeck user. I have no idea what I have done different.

**Comment by prajwalahluwalia** [comment]
How can i run simple touch command on my local server.  just want to create a files.txt in my Desktop on which rundeck is running, but it fails everytime showing permission error, though it works for remote node. I am new to rundeck and having trouble running command o local server. Need help.

**Comment by DougDavenport** [comment]
New Rundeck user here. Spent a lot of time trying to ssh as a different user to the local Rundeck server with no success. Finally found this issue and discovered it is a long standing problem. This should have been in the documentation. This is an important capability and setting up the local server via sudo differently than the other remote servers is not very elegant.

On a more positive note, there is a simple workaround. Name the local node different than:

framework.server.hostname
framework.server.name

and it works, for me anyways.

Hope someone finds this useful.
