### ISSUE TITLE
[API] Importing jobs for multiple projects

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#1728]
The actual API dose not have the possibility to import jobs to multiple projects in a single API call.

It could not be used the API - http://rundeck.org/docs/api/#importing-jobs - without specifying the "project" parameter.

eg:  /api/14/jobs/import?project=myproject

Currently, this option is *deprecated* API which is a bit inconvenient.

**Comment by jasonk** [comment]
It's only deprecated because it was replaced by /api/14/project/[PROJECT]/jobs/import, so you pass the project as part of the path, instead of as a parameter, which makes it match the other project-related APIs.

**Comment by gschueler** [comment]
importing jobs into different projects will require multiple api calls
