### ISSUE TITLE
Feature Request: Use Key storage password as argument in Job execution

### ISSUE THREAD

**Issue by ambikads** [rundeck/rundeck#1730]
Key storage is great for storing private keys, pass phrases needed for ssh, why not leverage this for job execution as well. We have scripts that we want to automate that needs admin password. It will be nice to have something like this in job execution page. This script will run every day and it does'nt make sense for the user to login and type the admin password and kick off the job every single day.

script.sh keys/password

Is there any other way I can achieve this?

**Comment by gschueler** [comment]
can you explain more about what you mean?

Added in 2.6.3: https://github.com/rundeck/rundeck/issues/1657

you can store passwords in key storage, and use them as the default value for a secure option.  then you can schedule the job and it will use the stored value

**Comment by ambikads** [comment]
@gschueler I need a admin password to execute a specific command inside a script. I have a rundeck job that executes this script. We do not want to store this password on the server.  I have the encryption plugin setup for keystorage and can store password.  How do I use the password from key storage in the job execution? I would like to pass the password as an argument to the script. I am using 2.6.2 but will upgrade to the latest if this works. Thanks!!

**Comment by ambikads** [comment]
@gschueler can you please let me know if this is possible? thanks!!

**Comment by gschueler** [comment]
yes, use a Key Storage password as the default in the option definition for the job (in 2.6.3 or later)
