### ISSUE TITLE
hide security token in api call

### ISSUE THREAD

**Issue by SydOps** [rundeck/rundeck#1739]
I set API call to run a job easily via `curl` command with `argString` 

```
curl -s -H 'X-Rundeck-Auth-Token: <RUNDECK_TOKEN>'
--data-urlencode "argString=-arg1 STRING "
http://localhost:4440/16/job/ebaed1f0-7b94-4a3b-8cf9-d26c21bbedaa/run
```

 The command will be run by a robot account, I need checkin it to Git/stash.

The rundeck token has admin permission, that I need find a way to hide it.  Can we have some functions same as AWS STS service to generate temporary security token?

Any other suggestion?

**Comment by gschueler** [comment]
@SydOps you are executing curl via another Rundeck Job?  one solution would be to store the token in the Key Storage, and use it as a secure job option with a key storage default.

Otherwise, maybe there should be a way to generate a token tied to the job execution, only valid for the duration of that job execution and injected into the available execution variables.

**Comment by SydOps** [comment]
Thanks @gschueler 

I read the documents about `key storage`, looks it is not suitable for my request.Let me explain more. 

I set Rundeck as a Central Tasks manager, customise a lot of jobs. Some of them need be run by another applications, such as bamboo and Jenkins,  when these tools doing automation build and deployment.

I feed the API link to bamboo to trigger some jobs. With exist solution, I need put the token with admin permission (plain text) to Bamboo. So how to hide these token?

**Comment by gschueler** [comment]
I'm not sure about Bamboo, but Jenkins has a feature for "secrets", where you can store encrypted/obscured secrets.  when you use them in a job they will be masked out from the output

**Comment by ak0ska** [comment]
What we do is to have an Apache proxy for the API usage, and the proxy applies a rewrite rule to inject the token locally before forwarding the query to Rundeck.
