### ISSUE TITLE
Rundeck cluster configuration is lost after restart

### ISSUE THREAD

**Issue by chswtj** [rundeck/rundeck#1742]
We have Rundeck 2.6.2-1 deployed as war file on Tomcat running behind Apache 2.2 on Red Hat Enterprise Linux Server release 6.5 (Santiago).
We use Oracle DB 11gR2 on a second server.

We set in 

```
rundeck-config.propereties : rundeck.clusterMode.enabled=true
framework.properties: rundeck.server.uuid=<value generated by uuidgen>
```

With this setup we are currently executing approx. 3000 jobs per day on our production environment.

After changing admin password and adding a new user with new acl we restarted rundeck server.

Since then, many of the scheduled jobs are executed twice.
It seems that after a restart the configuration that rundeck runs as as cluster is lost.
I had to export all scheduled jobs, delete them in rundeck and reload again.
This is very painful, because we fear, that we have to reload all scheduled jobs after a restart of Rundeck.

**Comment by chswtj** [comment]
Due to maintenance reason we had to stop and start rundeck.
After the start, all scheduled jobs are started twice again.
We solved this by exporting the jobs to xml, deleting  them in rundeck  and importing them from xml again.

Is there another option, instead of exporting/deleting/importing ?

**Comment by gschueler** [comment]
@chswtj cluster mode enabled should prevent that from happening, it is meant to assign each scheduled job to a particular cluster server. at startup a cluster server will try to "claim" any unclaimed jobs.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
