### ISSUE TITLE
Apache commons-collections-3.2.1.jar security hole fix

### ISSUE THREAD

**Issue by yuntaoge** [rundeck/rundeck#1748]
Sir, would you please upgrade the 2 commons-collections-3.2.1.jar in the Rundeck package to 3.2.2 or above? As you know, there is this serialization security hole in version 3.2.1. Thank you very much!

/var/lib/rundeck/exp/webapp/WEB-INF/lib/commons-collections-3.2.1.jar
/var/lib/rundeck/cli/commons-collections-3.2.1.jar

**Comment by gschueler** [comment]
these have been merged, and will be in the next release https://github.com/rundeck/rundeck/pull/1736

AFAICT Rundeck is not affected by this or similar Groovy issue since Grails is not affected grails/grails-core#9113. It does not use Java object serialization
