### ISSUE TITLE
Command outside Rundeck will not run in Rundeck

### ISSUE THREAD

**Issue by oldingn** [rundeck/rundeck#1750]
This simple command runs outside Rundeck on Red Hat Enterprise Linux Server release 6.7 (Santiago):

$ echo $(date -d "1 hour ago" +%s)
1458079658
$
When I execute it as a Command in Rundeck (or as part of a job as an execution step), it fails:

16:08:44    javasjstg   date: extra operand `ago'
16:08:44        Try`date --help' for more information.
16:08:44        

This happens with 2.6.4 and 2.5.3, but works as expected with 1.5.3 of Rundeck.

Is this the expected behaviour?

Thanks in advance!

**Comment by oldingn** [comment]
Here's the work-around:
Use single quotes to surround the parameter, and surround the whole expression with double-quotes.

$ echo "$(date -d '1 hour ago' +%s)"
1458146025

gives this output as a Rundeck command:
10:33:45	hostname 	1458146025

**Comment by ahonor** [comment]
Please reopen if this remains a concern
