### ISSUE TITLE
Include instructions on how to launch rundeck from a public IP or domain name

### ISSUE THREAD

**Issue by slimandslam** [rundeck/rundeck#1756]
Documentation suggestion:

On this page:  http://rundeck.org/downloads.html

Include the steps necessary to launch rundeck from 
an IP address or domain name

**Comment by jessemarple** [comment]
Issue moved to [rundeck/docs #302](https://github.com/rundeck/docs/issues/302) via [**ZenHub**](https://www.zenhub.com/)
