### ISSUE TITLE
Can't expand "Matched Nodes" in chrome

### ISSUE THREAD

**Issue by jasonk** [rundeck/rundeck#1757]
I believe this started with 2.6.4, but I haven't had a chance to try older versions to confirm.

When preparing to run a job that has a pre-defined node filter (in my case the pre-defined filter is 'hostname: .+'), checking the box for 'Change the Target Nodes' correctly expands to show the tag selectors and the text 'Matched Nodes (23) >', but clicking on the matched nodes doesn't have any effect and there doesn't seem to be a way to get the list of nodes to pop-up.

Rundeck version: 2.6.4-1 (installed from RPM)
Chrome version: Version 49.0.2623.87 (64-bit) (on OS X)

I also tried in Safari, where it works.  There is no output in the javascript console when it doesn't work.

It looks like it might be an initialization problem, if I inspect that element and extract the id, then manually run the expand action like this:

```
Expander.toggle($('_exp_adf70ce0'),'adf70ce0');
```

Then list expands.

I suspect this is a result of the onmousedown handler not being activated because it's element is initially hidden, and then for some reason it does not get activated again once that element is shown.  This also seems to be the only place in Rundeck where an element has an 'onmouse*' handler defined in HTML, rather than using Event.observe, so updating it to use Event.observe would probably fix this..

Another interesting tidbit, if you inspect the element in chrome, and then in the inspector edit the onmousedown handler (even something as simple as adding a space before Expander.toggle) then it starts working, which helps to reinforce that the onmousedown handler isn't getting recognized while it's hidden (because editing it forces the browser to redraw that element, causing it to get registered at that time).

**Comment by ahonor** [comment]
Please reopen if this remains a concern
