### ISSUE TITLE
Multiple Node Exectuors Per Job

### ISSUE THREAD

**Issue by srizzling** [rundeck/rundeck#1761]
Rundeck Version: 2.6.4-1

We are experimenting with different node executors to help with deployment, (using docker as way to isloate things, still requiring the ssh executor to execute things on nodes) and was wondering if there was a way to have different node executors per project, so that a job can chose what executor to use.

For example if we want to use ssh executor in job of a project, and use another exector as part of another job.

I wasn't able to find a way to do this, and the project (kindof) implies this is possible when you create the project as it mentions a "default" node executor.

**Comment by ahonor** [comment]
@srizzling you can define nodes to specify their own node-executor.

**Comment by srizzling** [comment]
Oh right. Do you set that via the Resource? I'm not able to find the entry for it via the docs:
http://rundeck.org/docs/man5/resource-yaml.html

**Comment by ahonor** [comment]
@srizzling Docs could be easier to find on this one but see http://rundeck.org/docs/plugins-user-guide/configuring.html#node-specific

**Comment by srizzling** [comment]
Aha! Cheers!
