### ISSUE TITLE
ssh connection failures

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#1766]
Hello, ssh encountered a problem, please help look card
###### 

framework.ssh.keypath = /home/admin/.ssh/id_rsa
framework.ssh.user = admin

[root@localhost rundeck]# /etc/rc.d/init.d/rundeckd restart
Stopping rundeckd:                                         [  OK  ]
Starting rundeckd:                                         [  OK  ]

ERROR ExecutionUtilService: Execution failed: 37: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [172.16.196.1: AuthenticationFailure: Authentication failure connecting to node: "172.16.196.1". Make sure your resource definitions and credentials are up to date.]}, Node failures: {172.16.196.1=[AuthenticationFailure: Authentication failure connecting to node: "172.16.196.1". Make sure your resource definitions and credentials are up to date.]}, status: failed]
###### 

I did not use the ssh account rundeck
Even my admin privileges of key
[root@localhost rundeck]# ll /home/admin/.ssh/id_rsa
-rwxrwxrwx 1 admin admin 1675 Oct 21 09:58 /home/admin/.ssh/id_rsa

**Comment by qicaihuoyan** [comment]
There modified
/etc/rundeck/framework.properties
service rundeckd restart
There does not restart the service following the entry into force of this modified

**Comment by abhishekunotech** [comment]
Can you post the values in the file "/var/rundeck/projects/Automation/etc/resources.xml"?

**Comment by ahonor** [comment]
Please reopen if this remains a concern
