### ISSUE TITLE
Issues deploying to an autoscaling group

### ISSUE THREAD

**Issue by joshuaspence** [rundeck/rundeck#1775]
We are using Rundeck to deploy application changes to EC2 instances that are within an autoscaling group. We regularly see issues where nodes fail with "Connection timed out". Roughly, what I think is happening is as follows:

  # Rundeck evaluates the nodes on which the job should be executed. This happens at the very start of the job.
  # During the execution of the job, some of the nodes which were previously selected are terminated (the autoscaling group scales down).
  # When Rundeck tries to deploy to these nodes, the connection times out.

Is there a way to handle this issue in the current version of Rundeck?

**Comment by chad-upton** [comment]
Really this isn't a job for rundeck to manage, you really should have your deploy script suspending all autoscaling and terminations while you are deploying.  Check out the autoscaling actions in the aws documentation for a list of them all.

**Comment by joshuaspence** [comment]
Perhaps, but Rundeck could help here. Like if nodes were evaluated dynamically rather than statically.

**Comment by jinesh-choksi** [comment]
A workaround was suggested in [rundeck/rundeck#78](https://github.com/rundeck/rundeck/issues/78)

**Comment by ahonor** [comment]
Please reopen if this remains a concern
