### ISSUE TITLE
deb package: make config files configs

### ISSUE THREAD

**Issue by zerkms** [rundeck/rundeck#1786]
So that they were not overwritten every new version update.

At least:
- exp/webapp/WEB-INF/web.xml
- webapp/WEB-INF/grails-app/i18n/messages.properties

**Comment by elvin159** [comment]
+1 on this issue. I had a rude awakening when i went to upgrade my rundeck cluster and had an annoying time not being able to login.

**Comment by gschueler** [comment]
the problem with doing that is that web.xml and messages.properties often change with new release versions.  If they are marked as Config, they would not get updated.  This is unfortunate.

for messages.properties I would like to see if there is a way to customize it without modifying that file (i.e. another file that will override the values within it).

for web.xml changes, (I assume to modify the `security-constraint`?) this is a sore point with our use of servlet container managed security, and something I really hope we can strategically migrate away from in the future. Perhaps there is a way for the container to augment it with a secondary file? (Need to look into that for tomcat/jetty).

Open to suggestions

**Comment by elvin159** [comment]
As per the debian policy manual[1] it seems like if a user changes their version of the web.xml to handle security-constraint (my use case) AND the package maintainer has a new version of the web.xml. It's up to the user to resolve the differences. Which i think seems to be reasonable. I do believe this is the same behavior in RPM land. 

> "If neither the user nor the package maintainer has changed the file, it is left alone. If one or the other has changed their version, then the changed version is preferred - i.e., if the user edits their file, but the package maintainer doesn't ship a different version, the user's changes will stay, silently, but if the maintainer ships a new version and the user hasn't edited it the new version will be installed (with an informative message). If both have changed their version the user is prompted about the problem and must resolve the differences themselves. "


[1]https://www.debian.org/doc/debian-policy/ap-pkg-conffiles.html

**Comment by gschueler** [comment]
makes sense. I'd be willing to try it, would you want to send a pull request? :)

also see https://github.com/rundeck/rundeck/pull/1591

**Comment by elvin159** [comment]
i'll look into it. Just gotta find the precious time.

**Comment by gschueler** [comment]
web.xml and WEB-INF are no longer possible to modify after install, ideally in rundeck 3. if there is still a need to make this kind of change, please open another issue.  additionally rpm/deb packaging has been separated into another repo https://github.com/rundeck/packaging
