### ISSUE TITLE
Project Export Times Out.

### ISSUE THREAD

**Issue by gbarnes27** [rundeck/rundeck#1792]
In the processes of migrating from embedded database to MySQL and was starting to export our projects when three of our projects would time out before it would give me the prompt to download.  Anyway around this or a way to export via CLI?  
Version = 2.4.2

Thanks 
Greg

**Comment by jaredledvina** [comment]
Hey @gbarnes27,

I know this is a super old issue but, was curious if you ever found a solution to the time outs?

**Comment by gbarnes27** [comment]
Wow this is old.  No way around from what I found so I actually just exported each job one by one and then imported them.  Now we are on MySQL and things run much faster.

Thanks for the follow up.

Thanks
Greg Barnes

System Owner |  W  682.605.3121  |  M  918.408.5758
twitter<https://twitter.com/Sabre_Corp> | facebook<https://www.facebook.com/SabreCorporation> | linkedin<https://www.linkedin.com/company/sabre-corporation> | youtube<https://www.youtube.com/user/SabreNewsTV> | blog<http://www.sabre.com/insights/blog/>
[Home]<http://www.getthere.com/>
This message contains information which may be proprietary or confidential, and may include material non-public information. Disclosing information in this message to any person outside of the company, or trading securities when you have material non-public information, is prohibited by our Business Ethics Policy<http://current.sabre.com/orgs/Legal/Pages/SP_BusinessEthicsPolicy.aspx>.

**Comment by jaredledvina** [comment]
Hey @gbarnes27,

Darn, alright, thanks for the reply!
