### ISSUE TITLE
Custom Orchestrator Failing

### ISSUE THREAD

**Issue by srizzling** [rundeck/rundeck#1802]
Hey Guys,

I am trying to debug a orchestrator plugin and I am unable to find out the root cause of the failure.

I have the logic working in a test where a node should be "released" once a execution is completed (this is implement in returnNode). So I have a test like this
```java
for(int i=0; i<2; i++){
  List<INodeEntry> nodes = new ArrayList<INodeEntry>();
  INodeEntry node1 = create("fakevip1");
  INodeEntry node2 = create("fakevip2");
  INodeEntry node3 = create("fakervip1");
  INodeEntry node4 = create("fakervip2");

  nodes.add(node1);
  nodes.add(node2);
  nodes.add(node3);
  nodes.add(node4);
  CustomOrchestrator plugin = new CustomOrchestrator(null, nodes);
  assertEquals(node1, plugin.nextNode());
  assertEquals(node3, plugin.nextNode());
  plugin.returnNode(node1, true, null);
  assertEquals(node2, plugin.nextNode());
  plugin.returnNode(node2, true, null);
  plugin.returnNode(node3, true, null);
  assertEquals(node4, plugin.nextNode());
  plugin.returnNode(node4, true, null);
  assertEquals(null, plugin.nextNode());
}
```

This unit test works, but when I deploy it to a running rundeck instance it doesn't seem to call the returnNode function after finishing the execution on each of the nodes. BUT if I stop the execution manually via the interface, it stops the execution, and returns the node (release the node) on the last one it finished completing the job on.

I am using 2.6.4 core lib in my custom orchestrator (using Rundeck 2.6.4).

I edited/manually deployed Max Percentage Orchestrator plugin and couldn't replicate the issue. Would you have any idea where I could debug to look further into the issue? I am kind of running out of ideas.

**Comment by srizzling** [comment]
Ok, just for my understanding it seems like it won't call return node, result.node = null. Would there be any reason result.node will be null?

``` java if(result.node!=null) {
                            this.orchestrator.returnNode(result.node, result.success, result.result);
                        }
```
https://github.com/rundeck/rundeck/blob/6cde23d6aa01b426465b1413ba80d3d4ed3972e8/core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeProcessor.java#L83

**Comment by gschueler** [comment]
@srizzling the purpose there was that a marker "Entry" object was used to tell remaining threads to stop processing new nodes, which would result in the thread adding a result with no node

does your orchestrator respond `true` to `isComplete()` when all nodes are done?

perhaps try taking a thread dump when in the strange state, or if you can attach a debugger

**Comment by srizzling** [comment]
I'm still really confused as we had a working copy during the 2.4.0 (we had a custom snapshot)

 
customOrchestrator: Next Node is called
customOrchestrator: Next Node is called
test.local: says hi 
customOrchestrator: returnNode should be called at this point
customOrchestrator: Next Node is called
customOrchestrator: Next Node is called
test2.local: says hi 
customOrchestrator: This is a test, returnNode should be called at this point
customOrchestrator: Next Node is called
customOrchestrator: Next Node is called
test3.local: says hi 
This is a test, returnNode should be called at this point
customOrchestrator: Next Node is called
customOrchestrator: Next Node is called
test4.local: says hi 
customOrchestrator: This is a test, returnNode should be called at this point

I was just testing with MaxPercentageOrchestrator with 33% and 1 thread with 4 hosts. And saw nextNode is called twice before the next node executes. Although what I see in my plugin is that nextNode is called 4 times at the start (which isn't what I would expect as I have set thread count to one, so should be called once)

**Comment by srizzling** [comment]
Ok I think I know what is the change from the previous version.

In this commit: https://github.com/rundeck/rundeck/commit/4a6f847f4e0459cf7441d15d0b6332cf441cb8cd 

You made a change where the getCallable function is done outside the execution on a node: https://github.com/rundeck/rundeck/blob/4a6f847f4e0459cf7441d15d0b6332cf441cb8cd/core/src/main/java/com/dtolabs/rundeck/core/execution/dispatch/OrchestratorNodeProcessor.java#L72

This breaks our custom Orchestrator, as we have lock in the nextNode to wait till the exection is complete on the node before calling next node again. Now it all it calls all the next node before it executes.

We would suggest having another function that can be run inside the execution. Does this seem correct to you?

Thanks,
Sriram

**Comment by gschueler** [comment]
@srizzling do you mean your `nextNode` method will block until the original node is returned?  What it should do is return `null` until you are ready for the next node

**Comment by srizzling** [comment]
But doesn't it wait for all nodes to be processed before executing? or am I mistaken?

**Comment by gschueler** [comment]
the original mechanism used a separate thread for each take/run/return.  the newer code uses a single thread to take nodes, then queues them to be 'run' by threads in the threadpool.  if no nodes are available to take (`nextNode` returns null), it will either wait for one to finish if it has already queued some nodes, or it will sleep if `isComplete` returns false.

btw, happy to look at your code if you want to share it (privately if need be)

**Comment by srizzling** [comment]
Thanks! @gschueler I ended up resolving this the way you suggested and it worked.

i.e in pseduo code
in nextNode:
// check  if lockednodes.size == threadCount (return null)
// lock node and add to lockednode array (return item)

is complete should check nodes is empty and lockedNodes is empty

Thanks again for you help, my general noobness :)
