### ISSUE TITLE
Can't use node.XXX variables in email subject

### ISSUE THREAD

**Issue by joelsdc** [rundeck/rundeck#1805]
We are trying to use node.XXX variables in the email subject for notifications but they don't get replaced with the value.

For example:

Subject: Test job run on ${node.hostname} by ${job.username} with parameters ${option.params}

Both job.username and option.params get replaces with their values, but node.hostname won't.

Are we doing anything wrong?

Thanks!

**Comment by ambikads** [comment]
@joelsdc you can mention node names when the job succeeds or fails. See https://github.com/rundeck/rundeck/issues/1968

**Comment by gschueler** [comment]
@joelsdc node data is not available in that context.  Jobs could be executed against multiple nodes
