### ISSUE TITLE
Remote Option Provider only supports basic auth

### ISSUE THREAD

**Issue by buildscientist** [rundeck/rundeck#181]
Currently the remote option provider supports basic http authentication. It would be nice if Rundeck users could somehow modify the header of the http request to the remote option provider to support alternate authentication methods. 

A good example of this would be authenticating against Jenkins RESTful API. Jenkins has a feature whereby any API calls can require a [crumb/hash](http://javadoc.jenkins-ci.org/hudson/security/csrf/CrumbIssuer.html) to be included with the request header.  

I'd say this is a minor feature request because I could use basic auth with the Jenkins API key given to every account OR turn on anonymous read only access on my Jenkins instance but that would give everyone access to my build workspace, artifacts etc. 

Other use cases for this would be having Rundeck interface with other option providers such as Nexus and Artifactory.

**Comment by MattMencel** [comment]
:+1:
