### ISSUE TITLE
Documentation: add job.executionType to context variables documentation

### ISSUE THREAD

**Issue by ctrlrsf** [rundeck/rundeck#1811]
Would be great if we had a job context variable we could check to see if the job was scheduled or not.

For example, `${job.wasScheduled}` which we could check from a plugin via environment variable `$RD_JOB_WASSCHEDULED` (don't care what variable name actually is)

This would help differentiate between jobs that ran on their set schedule, vs jobs that were ran ad-hoc by a Rundeck user.

If we can determine this some other way, would love to hear how.

If there's no opposition to this new context variable and you have some pointers, I can start working on a pull request.

**Comment by ahonor** [comment]
+1

**Comment by plambert** [comment]
+1

**Comment by ctrlrsf** [comment]
Just created a PR to add a context variable called job.executionType. Depending on how the job was ran, we can expect this to be either "adhoc", "user", or "scheduled".

**Comment by fuinyroot** [comment]
+1

**Comment by gschueler** [comment]
you can use `${job.executionType}`

**Comment by fuinyroot** [comment]
Based on http://rundeck.org/docs/manual/jobs.html#context-variables , there is no context variable named **job.executionType** 

Please re-open this ticket

**Comment by gschueler** [comment]
@fuinyroot ok, it should be documented, sorry.  will retitle the issue
