### ISSUE TITLE
ACL based on a job's UUID

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#1812]
Due that it is possible to create more than one job with the same name across projects, it could be a good idea to use the UUID to track/manage them generally.

So, it could be nice to have the way to specify ACLs policies for jobs based on the UUID rather than the name.

**Comment by stbka** [comment]
I have a similar issue. 
There are 2 jobs with the same name in different groups and I want to deny on of those and allow the other to a user. Is there a way to do that? 
I tried with a match rule and both pattern name and group. But it did not work.
