### ISSUE TITLE
RunDeck Redirects to random hostname string when running in a Docker container

### ISSUE THREAD

**Issue by kubilus1** [rundeck/rundeck#1813]
Rundeck keeps replacing the hostname you type with a generated random string when running in a Docker container.

For instance, going to http://localhost:4440/login will allow me to login but I am directed to: http://d8540d76ed8f:4440/menu/home

I have tried setting the Docker hostname to localhost '-h localhost'.  No change
I have tried specifying the server.hostname with -Dserver.hostname=localhost.  No change.

I am running this with the rundeck-launcher jar.  2.6.6

**Comment by david-richer-adsk** [comment]
I am also running rundeck 2.6.4 in a container. I use the properties ```grails.serverURL``` in rundeck-config.properties to set the server url.

**Comment by david-richer-adsk** [comment]
However, I am using the rpm package.

**Comment by ahonor** [comment]
@kubilus1 the launcher uses the `hostname` command as the default for unset serverUrl.

**Comment by hekaldama** [comment]
The docs cover this here:

http://rundeck.org/docs/administration/configuring-ssl.html

if you look at steps 5 and on. I know it is SSL but same for SSL and HTTP. Configure these in your container either at boot time, volume mount, or COPY'ing the files into the image via Dockerfile. I use an entrypoint in my Dockerfile for this with some bash like:

```bash
sed -i.bak '/grails.serverURL/s,=.*,='$FULL_URL',' /etc/rundeck/rundeck-config.properties
sed -i.bak '/framework.server.url/s,=.*,= '$FULL_URL',' /etc/rundeck/framework.properties
sed -i.bak '/framework.server.port/s/= .*/= '$SERVER_PORT'/' /etc/rundeck/framework.properties
```

Does that make sense at all?

**Comment by mbigras** [comment]
Thank you @ahonor! 

A quick way to get up and running is to use the `--hostname` switch to `docker run`

For example:

```
docker run -t --hostname=localhost -p 4440:4440 rundeck java -jar rundeck-launcher*
```
