### ISSUE TITLE
Failed status when node filter does not match any node

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#1814]
When scheduling a job with a node filter, if the node filter does not match any node during run, the job fails. The problem with this is the fact that, for this job, no node does not really means error - it is only an indication that the job has nothing to do.

One approach could be to add  a boolean flag on the job, that control the execution status for this case (not maches nodes), considering that in some cases the failure status is required because will indicate  a misconfiguration or a failure.

**Comment by pgressa** [comment]
@gschueler I will fix this as this will be follow up when https://github.com/rundeck/rundeck/pull/2104 will be out - once there's no intersection then it will fail.

**Comment by bbomgardner** [comment]
+1 makes sense as a filter intersection feature. Could definately use that flexibilty over no-match senarios.
