### ISSUE TITLE
Git Export and Git Import in YAML format issue in 2.6.6

### ISSUE THREAD

**Issue by david-richer-adsk** [rundeck/rundeck#1815]
After upgrading to 2.6.6, I am unable to import jobs using git import plugin in YAML format. The jobs was exported by the Git Export plugin. They seem to disagree what should be the format of the ```threadcount``` field.

When I export a job in 2.6.6 in yaml format, threadcount out has changed:
  * 2.6.4: ```threadcount: 1```
  * 2.6.6: ```threadcount: '1'```

Git import fail because it seem to except an integer.

Thanks,
David

**Comment by gschueler** [comment]
immediate guess is a regression due to fixing this https://github.com/rundeck/rundeck/issues/1773

**Comment by david-richer-adsk** [comment]
Thanks for the quick fix!
