### ISSUE TITLE
Context Variable: allow node options containing slash

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#1823]
i would like to use node options with a slash in the option name.

the replacement of ${node.myTestOption/test01} and ${RD_NODE_MYTESTOPTION_TEST01} works correctly.

But in "Inline Script Content" the **@node.myTestOption/test01@** is ignored and not replaced.

**Comment by schast** [comment]
Hi @gschueler, is there any progress on this bug?

**Comment by gschueler** [comment]
sounds like a bug, if `${node.blah/blah}` works but `@node.blah/blah@` doesn't work.
