### ISSUE TITLE
YAML job export / import issue

### ISSUE THREAD

**Issue by ajxb** [rundeck/rundeck#1824]
In RunDeck 2.6.6 if we export a job in YAML format the threadcount field is delimited with single quotes (see [job-2.6.6-yaml.txt](https://github.com/rundeck/rundeck/files/234530/job-2.6.6-yaml.txt)).

If I subsequently try to import the job definition I get the following error:

```
Error: Failed request to load jobs: Jobs Document was invalid for format yaml: rundeck.controllers.JobXMLException: Unable to create Job: Cannot cast object '10' with class 'java.lang.String' to class 'java.lang.Integer'
```

We were previously using RunDeck 2.6.1 and the threadcount field in exported jobs does not have single quotes around the parameter (see [job-2.6.1-yaml.txt](https://github.com/rundeck/rundeck/files/234529/job-2.6.1-yaml.txt)).

Importing the jobs exported from our original instance works just fine.

I see this behaviour in both the rd-jobs command line tool and from the web frontend.

Please can you investigate, as all of our backup scripts rely on the export of jobs in yaml format.

Cheers!

**Comment by gschueler** [comment]
@ajxb fixed in dev, will be creating a new release later this week https://github.com/rundeck/rundeck/issues/1815
