### ISSUE TITLE
Log output page load delay when using S3 log storage plugin

### ISSUE THREAD

**Issue by wjimenez5271** [rundeck/rundeck#1837]
Noticing there is an increased delay when using the S3 log storage plugin. The delay isn't that bad (2-3 seconds), but the page doesn't show anything in the content area while its loading and I expect users not aware of this will assume there were no logs for that job (false negative) and leave the page before it has a chance to load. If there was some initial message communicating the content was being loaded that would make a big difference.

**Comment by ahonor** [comment]
There is now an progress message displayed for 2.10+
