### ISSUE TITLE
Is openjdk-9-jre supported?

### ISSUE THREAD

**Issue by LordMike** [rundeck/rundeck#1839]
I just installed `rundeck` on a clean `Ubuntu 16.04`, and `openjdk-9-jre-headless` was picked by apt. I received various errors (primarily a `HTTP 503` being unable to access `/`).

The `service.log` contains a humongous amount of exceptions, an excerpt of the first few lines are here. I read other issues reg. downgrading `rundeck` but I then realized that Ubuntu 16.04 and Java 9 are pretty new (in addition to the Rundeck webpage listing `apt-get install openjdk-7-jdk`), so I tried uninstalling jdk9 and fetching jdk8 (`openjdk-8-jre-headless`). 

Then it worked (I now get a login screen).

> WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable.
> 2016-05-04 23:18:35.389:INFO:oejs.Server:jetty-7.6.0.v20120127
> 2016-05-04 23:18:37.238:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
> 2016-05-04 23:18:38.368:INFO:/:Initializing Spring root WebApplicationContext
> WARN  GrailsWebApplicationContext: Exception encountered during context initialization - cancelling refresh attempt
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gspTagLibraryLookup': Invocation of init method failed; nested exception is org.springframework.beansError creating bean with name 'rundeck.PluginTagLib': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with naation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionService': Cannot create inner bean '(inner bean)#6erty 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#654dbb78': Initialization of bean failed; nested excens.factory.BeanCreationException: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationExcepame 'mailService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException
>         at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
>         at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
>         at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
>         at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
>         at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
>         at org.eclipse.jetty.server.Server.doStart(Server.java:261)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
>         at com.dtolabs.rundeck.RunServer.run(RunServer.java:120)
>         at com.dtolabs.rundeck.RunServer.main(RunServer.java:80)
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rundeck.PluginTagLib': Initialization of bean failed; nested exception is org.springframewception: Error creating bean with name 'frameworkService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean wiot create inner bean '(inner bean)#654dbb78' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with namelization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notificationService': Initialization of bean failed; neswork.beans.factory.BeanCreationException: Error creating bean with name 'mailService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException
>         ... 11 more
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'frameworkService': Initialization of bean failed; nested exception is org.springframework.ion: Error creating bean with name 'executionService': Cannot create inner bean '(inner bean)#654dbb78' while setting bean property 'target'; nested exception is org.springframework.beans.fror creating bean with name '(inner bean)#654dbb78': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with namization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mailService': Invocation of init method failed; nested exmentException
>         ... 11 more
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionService': Cannot create inner bean '(inner bean)#654dbb78' while setting bean pro is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#654dbb78': Initialization of bean failed; nested exception is org.springframework.ben: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with f init method failed; nested exception is java.lang.IllegalArgumentException
>         ... 11 more
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#654dbb78': Initialization of bean failed; nested exception is org.springframexception: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating beaation of init method failed; nested exception is java.lang.IllegalArgumentException
>         ... 11 more
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframewoeption: Error creating bean with name 'mailService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException
>         ... 11 more
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mailService': Invocation of init method failed; nested exception is java.lang.IllegalArgum
>         ... 11 more
> Caused by: java.lang.IllegalArgumentException
>         at java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(java.base@9-internal/ThreadPoolExecutor.java:1556)
>         at grails.plugin.mail.MailService.setPoolSize(MailService.groovy:73)
>         at grails.plugin.mail.MailService.afterPropertiesSet(MailService.groovy:92)
>         ... 11 more
> ERROR GrailsContextLoaderListener: Error initializing the application: Error creating bean with name 'gspTagLibraryLookup': Invocation of init method failed; nested exception is org.springfionException: Error creating bean with name 'rundeck.PluginTagLib': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creatince': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionService': Cannot create inner bean 'ting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#654dbb78': Initialization of bean failegframework.beans.factory.BeanCreationException: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.Beang bean with name 'mailService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException
> org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'gspTagLibraryLookup': Invocation of init method failed; nested exception is org.springframework.beansError creating bean with name 'rundeck.PluginTagLib': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with naation of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionService': Cannot create inner bean '(inner bean)#6erty 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#654dbb78': Initialization of bean failed; nested excens.factory.BeanCreationException: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationExcepame 'mailService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException
>         at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:733)
>         at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:233)
>         at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1214)
>         at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:676)
>         at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:455)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
>         at org.eclipse.jetty.server.handler.HandlerWrapper.doStart(HandlerWrapper.java:90)
>         at org.eclipse.jetty.server.Server.doStart(Server.java:261)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:59)
>         at com.dtolabs.rundeck.RunServer.run(RunServer.java:120)
>         at com.dtolabs.rundeck.RunServer.main(RunServer.java:80)
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'rundeck.PluginTagLib': Initialization of bean failed; nested exception is org.springframewception: Error creating bean with name 'frameworkService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean wiot create inner bean '(inner bean)#654dbb78' while setting bean property 'target'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with namelization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notificationService': Initialization of bean failed; neswork.beans.factory.BeanCreationException: Error creating bean with name 'mailService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException
>         ... 11 more
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'frameworkService': Initialization of bean failed; nested exception is org.springframework.ion: Error creating bean with name 'executionService': Cannot create inner bean '(inner bean)#654dbb78' while setting bean property 'target'; nested exception is org.springframework.beans.fror creating bean with name '(inner bean)#654dbb78': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with namization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mailService': Invocation of init method failed; nested exmentException
>         ... 11 more
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'executionService': Cannot create inner bean '(inner bean)#654dbb78' while setting bean pro is org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#654dbb78': Initialization of bean failed; nested exception is org.springframework.ben: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with f init method failed; nested exception is java.lang.IllegalArgumentException
>         ... 11 more
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name '(inner bean)#654dbb78': Initialization of bean failed; nested exception is org.springframexception: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating beaation of init method failed; nested exception is java.lang.IllegalArgumentException
>         ... 11 more
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'notificationService': Initialization of bean failed; nested exception is org.springframewoeption: Error creating bean with name 'mailService': Invocation of init method failed; nested exception is java.lang.IllegalArgumentException
>         ... 11 more
> Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'mailService': Invocation of init method failed; nested exception is java.lang.IllegalArgum
>         ... 11 more
> Caused by: java.lang.IllegalArgumentException
>         at java.util.concurrent.ThreadPoolExecutor.setCorePoolSize(java.base@9-internal/ThreadPoolExecutor.java:1556)
>         at grails.plugin.mail.MailService.setPoolSize(MailService.groovy:73)
>         at grails.plugin.mail.MailService.afterPropertiesSet(MailService.groovy:92)
>         ... 11 more

**Comment by eduherraiz** [comment]
Same case here!

**Comment by sanderao** [comment]
I experienced the same issue. Uninstalling jdk9 and installing jdk8 fixed it. There is a know issue with jdk9 and Bean creation.

**Comment by gschueler** [comment]
jdk 8 is required for now

**Comment by namrataSatpathy** [comment]
facing same issue . is there no support for jdk9 ?
