### ISSUE TITLE
Feature Request: Job search

### ISSUE THREAD

**Issue by schicky** [rundeck/rundeck#1842]
The project search feature in 2.6.7 is helpful.Would be very helpful to have this feature to search for jobs in each project. Might also be helpful to search for a job name across projects but definitely within a project.

**Comment by ahonor** [comment]
@schicky, thanks for the feedback. For the job search, there is a filter now but perhaps it's not what you're looking for.

**Comment by schicky** [comment]
That's been there the whole time and we missed it. Functionally that is exactly what I'm looking for, maybe if it were as obvious as the project search it could help. Or even the ability to share or create common filters for everyone to have available would be nice. Like if I'm doing function x I use the x filter and y when I'm doing y style jobs.
