### ISSUE TITLE
Ansible jobs hanging

### ISSUE THREAD

**Issue by yassineazzouz** [rundeck/rundeck#1846]
Hi Guys,

First thank you for the great work you are doing on rundeck, I started using rundeck recently and very happy with it.

I recently come across a very weird issue when running long ansible workflow jobs, after a certain time the job hangs and stop logging, I took a look at what the process is doing and it seems  that it was stuck trying to write to a PIPE

[root@prssnbd1adm01 ~]# strace -p 11480
Process 11480 attached
write(1, "6.1M\t./hue_server_db_20160512-1"..., 4096

I tried to increase the Log output Limit parameter to 1GB but it does not seems to fix the issue. This is probably related to the maximum PIPE in Linux. I'm using centos 6.7 so it should be 64KB I think.

Plus the other weird thing is that logs are not updated dynamically in the UI while the job is running.

Thanks,

**Comment by yassineazzouz** [comment]
output lsof:

[rundeck@prssnbd1adm01 ~]$ lsof -p 28218
COMMAND     PID    USER   FD   TYPE DEVICE SIZE/OFF     NODE NAME
ansible-p 28218 rundeck  cwd    DIR 253,25     4096 20840449 /var/lib/rundeck
ansible-p 28218 rundeck  rtd    DIR  253,1     4096        2 /
ansible-p 28218 rundeck  txt    REG 253,17     9032    11902 /usr/bin/python
......
ansible-p 28218 rundeck  mem    REG 253,17 99158576     4194 /usr/lib/locale/locale-archive
ansible-p 28218 rundeck    0r  FIFO    0,8      0t0 35560664 pipe
ansible-p 28218 rundeck    1w  FIFO    0,8      0t0 35560665 pipe
ansible-p 28218 rundeck    2w  FIFO    0,8      0t0 35560665 pipe
......
ansible-p 28218 rundeck    4r  FIFO    0,8      0t0 35560664 pipe
.....
ansible-p 28218 rundeck    7r  FIFO    0,8      0t0 35560664 pipe
ansible-p 28218 rundeck    8r  FIFO    0,8      0t0 35560664 pipe
ansible-p 28218 rundeck    9r  FIFO    0,8      0t0 35560664 pipe
ansible-p 28218 rundeck   10w   REG 253,15 17623859       33 /tmp/ansible.log
ansible-p 28218 rundeck   11w   REG 253,15        0       45 /tmp/.ansible-lock.16928
ansible-p 28218 rundeck   12r  FIFO    0,8      0t0 35560664 pipe
ansible-p 28218 rundeck   13r  FIFO    0,8      0t0 35560664 pipe
ansible-p 28218 rundeck   14r  FIFO    0,8      0t0 35560664 pipe
....

Appreciate you help,
Regards,

**Comment by ahonor** [comment]
@yassineazzouz can you invoke ansible so that python does not buffer any output?

**Comment by ahonor** [comment]
@yassineazzouz can you log an issue for the plugin project to find out?

**Comment by yassineazzouz** [comment]
Hi @ahonor ,

Thanks, I will log a different issue on the plugin project although I think it is related to the the way rundeck pipe the job output.

Not sure if that's what you are suggesting but I added export PYTHONUNBUFFERED=1 to bashrc and profile file but does not seems to resolve the issue, the jobs are still hanging.

Thanks,

**Comment by yassineazzouz** [comment]
Hi @ahonor ,

I forced python to disable buffering using "-u" option which should be equivalent to PYTHONUNBUFFERED environment variable but unfortunately it does not seems to help the jobs are still blocking after around 450 lines of log.

Thanks,

**Comment by ahonor** [comment]
@yassineazzouz did you ever get a response from the Batix/rundeck-ansible-plugin? I think it must be resolved there
