### ISSUE TITLE
Rundeck scheduler incorrectly calculates execution time

### ISSUE THREAD

**Issue by konradstarzyk** [rundeck/rundeck#1849]
I set the job to execute at 12:30PM:
<img width="1122" alt="zrzut ekranu 2016-05-14 o 12 20 28" src="https://cloud.githubusercontent.com/assets/1548325/15267879/54843d38-19ce-11e6-886a-68ffc6d76e1f.png">

however, although it is 12:20PM now, rundeck wants to execute this job in 6 hours.

<img width="595" alt="zrzut ekranu 2016-05-14 o 12 20 51" src="https://cloud.githubusercontent.com/assets/1548325/15267882/630e8ef8-19ce-11e6-89f5-78e34e78e686.png">

 I am in CEST timezone, and apparently rundeck knows well what is the UTC time now.
<img width="696" alt="zrzut ekranu 2016-05-14 o 12 21 04" src="https://cloud.githubusercontent.com/assets/1548325/15267884/67d68c92-19ce-11e6-902c-38f4cb7141ff.png">

**Comment by jdxin0** [comment]
My job scheduled at 00:30 am, but it started at 5:34 am.
![screen shot 2016-07-08 at 11 46 08 am](https://cloud.githubusercontent.com/assets/11607613/16676826/9e2bb91c-4501-11e6-9483-d82ba84f53a4.png)
![screen shot 2016-07-08 at 11 46 43 am](https://cloud.githubusercontent.com/assets/11607613/16676834/ae042de2-4501-11e6-8b12-a61dddec3990.png)

I use rundeck to manage a lot of heavy tasks(takes hours to execute).
I wonder if it reach limit.

**Comment by talenhao** [comment]
I have another program. My execution time is right, but display time is error. 
![spectacle j26827](https://cloud.githubusercontent.com/assets/13248206/19545530/ad7a361e-96b9-11e6-9f55-59b89be2f0a8.png)
