### ISSUE TITLE
Log html viewer

### ISSUE THREAD

**Issue by cueBall123** [rundeck/rundeck#1852]
I've been trying create a more intuitive log output using the HTML rendering and the existing bootstrap library. And I notice that every new line is being encapsulated by a `<div class="log_line level_normal"> </div>`. I'm circumventing this by making html markups without line breaks. Is there any way to make rundeck stop adding these divs. This would help a lot if there was a switch which can make it stop doing this.

**Comment by ahonor** [comment]
Hi @cueBall86, I am curious how you are designing the log output. Can you say or show how you intend for it to look?

**Comment by cueBall86** [comment]
@ahonor I don't know if I can post a screen shot here. But the idea is to use jinja template to print out html markups to the log output. The jinja template would have the script tag linking it to the rundeck jquery path(in assets). I had to remove all line breaks while I print it out the markups. I don't know if this is recommended or not. But people are liking the formatted html logs.

**Comment by ahonor** [comment]
You can attach a file for the screenshot.

**Comment by cueBall86** [comment]
I meant, i'll have to obviously hide all the data from it .I'll post something soon.

**Comment by cueBall86** [comment]
![image](https://cloud.githubusercontent.com/assets/5472024/15544312/d0bd71fc-225d-11e6-958f-0a4387601b14.png)

**Comment by ahonor** [comment]
@cueBall123 Rundeck 2.9 introduced log filter plugins. I was curious if you had tried those
