### ISSUE TITLE
Local Node Execution - change framework.file-copy-destination-dir

### ISSUE THREAD

**Issue by gdowmont** [rundeck/rundeck#1857]
After setting `framework.file-copy-destination-dir = ~/` rundeck correctly expands tilde to the home directory of the user it is connecting as when running script workflow step on remote nodes.

However the same setting produces `Failed dispatching to node localhost: error writing to tempfile: ~/0-158-localhost-dispatch-script.tmp.sh (No such file or directory)` when using 'execute locally'.

I have tried specifying '~/' as '$HOME' in framework.properties but it does not interpolate the variable either, but only when running against the localhost.

Is it possible to either pass a separate framework.file-copy-destination-dir when running on localhost or somehow interpolate a variable in framework.properties?

The use case here is that /tmp is mounted with noexec which causes all executions to fail. I am trying to provide another directory that will be always present on all nodes and that will be always writable and executable as the user it is connected as, hence home directory. I know I could possibly create common directory on all nodes but I am trying to avoid that.

Does anyone have any idea?

Thanks

**Comment by gschueler** [comment]
for local node you could override the value as a node attribute `file-copy-destination-dir` in the resources definition
