### ISSUE TITLE
Invalid request token with FireFox

### ISSUE THREAD

**Issue by elmheryne** [rundeck/rundeck#1858]
Hello,

I use Rundeck for a while (V 2.6.7), however I have a problem that seems to occur only through the FireFox browser (V.42 at home, trying V.46) (only in FireFox, IE and Chrome => OK)

I always manage to submit one form, but in the second, I have an error message in the IHM.
   "Invalid request The request token Did not include a valid token, or the token has expired. Please try your request again."
I apply the patch found here => rundeck.security.useHMacRequestTokens = false

In the log, I have no error whatsoever on the audit or the access.

But that did not solve my problem. Is there a solution I would have missed it?

**Comment by ahonor** [comment]
Please reopen if this remains a concern
