### ISSUE TITLE
Rundeck ACL based on AD groups

### ISSUE THREAD

**Issue by jfacow** [rundeck/rundeck#1863]
I am going to use Rundeck in production.

While reading docs, I found that users management is based on local ACL files. And AD authentication is available.

My question is: Is it possible to manage users access to Jobs and Nodes by AD groups?

Fox example: AD groups: rundeck_restrat_svcName1, rundeck_restrat_svcName2, ect..

Thanks for any information.

**Comment by ahonor** [comment]
@jfacow most users use LDAP (eg AD) groups in their ACL policies.

**Comment by jenulis** [comment]
I'm supporting Rundeck in production with a connection to AD.  If you are
familiar with connecting java apps to AD, you get typical functionality.

AD groups work in acl file(s) even if  they are a bit difficult to setup
and error prone.

Mike

**Comment by ahonor** [comment]
Please reopen if this remains a concern
