### ISSUE TITLE
Feature request - Configurable default tab for follow execution

### ISSUE THREAD

**Issue by larhauga** [rundeck/rundeck#1867]
I would like to se an option in the job configuration, where it is possible to define which pane should be shown by default, when following the execution.
The intent would be to go directly to the log output tab, in stead of the Summary tab.

Tags: Enhancement

Kind regards
Lars

**Comment by djschilling** [comment]
I would also really like to see this feature.
In most of the cases i am only interested in the log output, and clicking there every time is annoying.

**Comment by aairey** [comment]
Can be closed, since #3304 was merged.
