### ISSUE TITLE
Script plugins for Workflow/Node steps: allow key storage automatic read

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#1868]
The script plugin [Property Rendering Options](http://rundeck.org/docs/developer/plugin-development.html#property-rendering-options) `STORAGE_PATH_AUTOMATIC_READ` does not work for `WorkflowNodeStep` and `WorkflowStep` script-plugin types.

**Comment by Jesus-Osuna-M** [comment]
.
