### ISSUE TITLE
Documentation Bug: Broken Links In Wiki

### ISSUE THREAD

**Issue by isuftin** [rundeck/rundeck#1871]
https://github.com/rundeck/rundeck/wiki/Resource-model-providers

Chef: https://github.com/opscode/chef-rundeck = 404

Amazon EC2: https://github.com/dtolabs/java-ec2-nodes = Deprecated. Should point to https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin

Jclouds: https://github.com/gschueler/rundeck-jclouds (Work in-progress) = Has not been updated in 5 years :(

**Comment by gschueler** [comment]
thanks, i updated the wiki page to point to our plugins list at http://rundeck.org/plugins/
