### ISSUE TITLE
Odd Step-oriented behavior

### ISSUE THREAD

**Issue by straypacket** [rundeck/rundeck#1874]
In a Workflow, with two node steps, I setup with the Random Subset orchestrator with a count of 1. I have a pool of 6 nodes.

If I select a Node-oriented strategy, it will pick up one node, run step 1 and 2 and then exit, as expected.

If I select a Step-oriented strategy, it will pick up one node and run step 1. However it will run step 2 on all of my 3 nodes, using a sequential execution.

I tested this on version 2.6.6-1 and master from commit 17c6a475e7e8e322c78605da2c76e0ea2ca2f981 (2nd May).

Debug:
[rundeck_steporiented.txt](https://github.com/rundeck/rundeck/files/296785/rundeck_steporiented.txt)

**Comment by gschueler** [comment]
reproduced
