### ISSUE TITLE
Unable to Define SSH Key at Project Level

### ISSUE THREAD

**Issue by sprokopienko** [rundeck/rundeck#1877]
No keys are defined at framework level.  Only default settings in /etc/rundeck/project.properties.
With the below settings, the following error is seen when running a job:
Failed: ConfigurationFailure: SSH Private key path is expected to start with "keys/":

Providing a test resources.xml file to the project, and defining the same settings for key and password at the node level results in a successful job run.

Version: rundeck-2.6.2-1.13

Settings in project-specific project.properties:
project.ssh-authentication=privateKey
project.ssh-key-storage-path=keys/lxopsrdpriv
project.ssh-password-storage-path=keys/lxopsrdpass

**Comment by gschueler** [comment]
can you verify this same thing happens in the latest release?

**Comment by richiereynolds** [comment]
I see the same thing with trying to put this at the framework level. And yes, in the latest release.

**Comment by gschueler** [comment]
Having trouble reproducing this.

@sprokopienko you said you saw it happen if you have not framework level config, and try to do a project level config

@richiereynolds you said you were trying this at the framework level and saw the bug.

I can't seem to trigger the same error unless the `project.ssh-key-storage-path` or `framework.ssh-key-storage-path` is actually invalid.

Note in framework.properties, the entries need to be prefixed with `framework.` and in project.properties they are prefixed with `project.`.  for a node there is no prefix, simply the attribute matches the entry name, e.g. `ssh-key-storage-path`.

**Comment by gschueler** [comment]
Note that the error if you specify an invalid path is:

    SSH Private key path is expected to start with "keys/": blah/key1.private

If your output does not show a path, that implies it is using a blank string, or maybe just a space character.. Somehow that is the value that is read from your config

**Comment by richiereynolds** [comment]
Hi, here's a concrete example; it works fine if I put this on the node:
```
ssh-key-passphrase-storage-path="keys/${job.username}.passphrase"
ssh-key-storage-path="keys/${job.username}.key"
```
If I remove that from the node and put this in the framework.properties:
```
framework.ssh-key-passphrase-storage-path="keys/${job.username}.passphrase"
framework.ssh-key-storage-path="keys/${job.username}.key"
```
I get the keys error:
```
Failed: ConfigurationFailure: SSH Private key path is expected to start with "keys/": "keys/Richard.Reynolds.key"
10:48:21	localhost		Execution failed: 30082: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [LO.LO1.tpdevlive-btxfh1l.tpbtx: ConfigurationFailure: SSH Private key path is expected to start with "keys/": "keys/Richard.Reynolds.key"]}, Node failures: {LO.LO1.tpdevlive-btxfh1l.tpbtx=[ConfigurationFailure: SSH Private key path is expected to start with "keys/": "keys/Richard.Reynolds.key"]}, status: failed]
```

But i think you can see that:

1. it does start with "keys"

2. it's the same path as on the node, which works fine when it's on the node

**Comment by richiereynolds** [comment]
You're not going to believe this ...

I removed the double quotes around the value in the framework properties and it started working.

**Comment by gschueler** [comment]
aha! .properties format strikes again.

ok I will close this, glad you got it sorted
