### ISSUE TITLE
Compatible with PostgreSQL

### ISSUE THREAD

**Issue by peco8** [rundeck/rundeck#1887]
Excuse me,
I wonder if Rundeck is only compatible with Mysql?
Because I couldn't find any information about PostgreSQL in an official docs.

I could succeeded to connect to postgres with JDBC (Java Database Connectivity), and it works well.
`DATABASE_URL=${DATABASE_URL:-"jdbc:postgresql://db/rundeck"}`

If Mysql is prefered, is using PostgreSQL not really recommended?

**Comment by miguelantonio** [comment]
Hi @peco8, Rundeck is compatible with virtually any JDBC database, of course any mayor as postgres, it uses a ORM internally

**Comment by peco8** [comment]
Hi @miguelantonio,
Thanks for the answer. I didn't even know Rundeck uses ORM internally.
So it uses Hibernate or some O/R framework inside?

I'd prefer to use raw SQL because of perform query though.

**Comment by atlasloewenherz** [comment]
hi @peco8,

yes its using hibernate-> jdbc(+dbcp) -> any DBMS thats supports JDBC.

In my experience with RD + MySQL, RD is performing well and AFIK the performance of RD Queries is nor relevant to the jobs you execute neither does it affect their performance.

**Comment by peco8** [comment]
Hi @atlasloewenherz ,

Thanks for the great answer. 
I thought I could aggregate functionality with schedular efficiently, so it could be great if I can adjust query to RDBMS specifically. (shell script + here docs)
So in this case it might not work that way as you pointed out.

Should I manipulate DB with hibernate?  or any other ways?

**Comment by atlasloewenherz** [comment]
hi @peco8,

i really cannot answer your question, since i don't know what you intend to do? what are you working on?
- rundeck job?
- rundeck plugin?
- rundeck core?

**Comment by peco8** [comment]
hi @atlasloewenherz,

Yes, rundeck job.  I mean the case is something like aggregating the total amount on a table, and put it out in CSV format.

**Comment by peco8** [comment]
@atlasloewenherz, @miguelantonio 

well I actually still can't figure out that ORM works internally in Rundeck.

You mean we have some options to use hibernate to access data?
Working ORM internally doesn't really make sense to me.
( When I use raw query, it will directly parsed in RDBMS. )

I'm currently working on developing rundeck jobs.

**Comment by ahonor** [comment]
@peco8 Did you get this configuration working?
