### ISSUE TITLE
Typo in webpage RSS feed

### ISSUE THREAD

**Issue by ottlinger** [rundeck/rundeck#1889]
I'm not sure if that's the right place, but the RSS feed at
http://rundeck.org/news/feed.xml
shows a wrong title.

It should be 
_Rundeck News_
instead of 
_Rudeck News_
in
```
<channel>
<title>Rudeck News</title>
```

**Comment by gschueler** [comment]
ha, thanks for the catch....that is in the gh-pages repo https://github.com/rundeck/rundeck-ghpages

**Comment by gschueler** [comment]
fixed
