### ISSUE TITLE
Job which script has command input fails

### ISSUE THREAD

**Issue by shigemk2** [rundeck/rundeck#1892]
Rundeck version: 2.6.8

I registered a job with command input like this.

```sh
#!/bin/bash
select option in "foo" "bar"
do
    echo "you pressed $option"
    break;
done
```

I expect this result. I want to type number during job execution.

```sh
1) foo
2) bar
#? 1
you pressed foo
```

But actual result got error.

```sh
13:40:07			1) foo
13:40:07			2) bar
13:40:08			#? 
13:40:08			Result: 1
13:40:08			Failed: NonZeroResultCode: Result code was 1
13:40:08			Execution failed: 2: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [xxxxxx: NonZeroResultCode: Result code was 1]}, Node failures: {xxxxxx=[NonZeroResultCode: Result code was 1]}, status: failed]
```
I want to type keys during job execution(e.g. passwd, select etc..). How can I avoid this problem?

**Comment by gschueler** [comment]
rundeck does not support accepting direct input in that way.  You should adapt your script to use Job Options, and use `${option.blah}` or `$RD_OPTION_BLAH`

**Comment by shigemk2** [comment]
Sorry, I have a very basic question. What is the option.blah? I search this word in doc, but I couldn't find it.

**Comment by gschueler** [comment]
I just mean your job option, see http://rundeck.org/docs/manual/jobs.html#job-options

define a job option named "foobar", with values "foo" and "bar".  It will show up in the GUI as a select box to choose from before the user runs the job.  Then within your job's scripts or commands, you can use `${option.foobar}` to read the value

**Comment by shigemk2** [comment]
I see. Thank you for your information.
