### ISSUE TITLE
Running a job as a different user (asUser parameter)

### ISSUE THREAD

**Issue by papagr** [rundeck/rundeck#1893]
POSTing to /api/12/job/[ID]/executions and using the optional parameter "asUser" used to work fine in Rundeck 2.6.1.

After upgrading to Rundeck 2.6.7, "asUser" parameter is ignored. The job is executed successfully but the user is not the one specified by "asUser".

The API user has "runAs" permission set.

**Comment by gschueler** [comment]
confirmed, this is a regression
