### ISSUE TITLE
Error building plugin: Class XXPlugin was not a valid plugin class for service: WorkflowNodeStep

### ISSUE THREAD

**Issue by miguelantonio** [rundeck/rundeck#1894]
Hi! just want to document something that happened to me, but just solved it

This error showed up as I was not declaring the default constructor public XXPlugin(){}

That's all, this issue is just for documentation, thanks!

**Comment by gschueler** [comment]
should enhance the error message to be more informative: "expected class YY, with a public constructor with no parameters"

**Comment by miguelantonio** [comment]
@gschueler hey about this, how about we just add the exception in isValidProviderClass? or do you have any other guideline for us to follow so we can contrib?

**Comment by gschueler** [comment]
to enhance the message, would just be to modify this https://github.com/rundeck/rundeck/blob/master/core/src/main/java/com/dtolabs/rundeck/core/plugins/JarPluginProviderLoader.java#L209

**Comment by miguelantonio** [comment]
Ok, so just add a text advice then, full: "Class XXPlugin was not a valid plugin class for service: WorkflowNodeStep. Expected class XX, with a public constructor with no parameter"

@variacode95

**Comment by gschueler** [comment]
@miguelantonio 👍

**Comment by variacode95** [comment]
Understood and Acknowledged !! :+1:

**Comment by gschueler** [comment]
via #1894
