### ISSUE TITLE
GUI option dynamic refresh broken in 2.6.6 and 2.6.8

### ISSUE THREAD

**Issue by richiereynolds** [rundeck/rundeck#1895]
We have just upgraded from 2.6.4 and found that dynamic population of options has stopped working properly.

Our URL is for populating a "Nodes" multi-valued option is:
http://localhost:1080/tprundeck/getResourceNames.jsp?project=${job.project}&type=node&regionname=${option.Region.value}&tpname=${option.TP.value}&componentname=${option.Component.value}

We find that the Nodes option updates correctly when we select a "Component" but is not updated when we select a "TP" or a "Region".
This makes a previously working GUI unusable.

Note that TP and Region are optional values, Component is required and has "enforce from list" set.
We checked and found that even having "required" was not enough to trigger the cascade, it needs both required and enforce from list.

#1832 appears to suggest this might be fixed in 2.6.8 but we've just tried that version and it's still not working.

**Comment by richiereynolds** [comment]
#1832 appears to suggest this might be fixed in 2.6.8 but we've just tried that version and it's still not working.

**Comment by gschueler** [comment]
I bit the bullet, and replaced the messy javascript/remote html for cascading options with knockout #1900

**Comment by richiereynolds** [comment]
Any date for 2.6.9 yet?

Thanks,
