### ISSUE TITLE
"run" and "dispatch" launchers are named too generically

### ISSUE THREAD

**Issue by williamh** [rundeck/rundeck#1896]
Hello.

I noticed in the .rpms that you install /usr/bin/run and /usr/bin/dispatch. These names seem extremely generic and they could easily be used by other products as well.
Would you please consider renaming them to /usr/bin/rd-run and /usr/bin/rd-dispatch so they will be consistent with the names of the other launchers you install?

Thanks much for your time,

William

**Comment by gschueler** [comment]
we are working on replacing those commandline tools, see https://github.com/rundeck/rundeck-cli

**Comment by williamh** [comment]
I am packaging your software for Gentoo Linux. Should I package rundeck-cli as well as rundeck, or is rundeck-cli still too early in development?

**Comment by ahonor** [comment]
@williamh it would be great to try out the rundeck-cli. It is early in its development but it would be great for you to start looking into incorporating it.
