### ISSUE TITLE
Rundeck start is very slow

### ISSUE THREAD

**Issue by amitdaniel86** [rundeck/rundeck#1897]
Hello , 

I'm running rundeck on docker container and when i restart the container it took something like 6-7 mins until rundeck start .

this is the logs .
What am i'm doing wrong ?

container restarted - 3:47:58
Rundeck start - 3:54:01
Total time : 6:43 mins ...

The mysql is AWS RDS .

What i'm doing wrong ?

**6/15/2016 3:47:58 PM**Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
6/15/2016 3:47:59 PMWARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable.
6/15/2016 3:47:59 PM2016-06-15 12:47:59.101:INFO:oejs.Server:jetty-7.6.0.v20120127
6/15/2016 3:48:22 PM2016-06-15 12:48:22.914:INFO:oejw.StandardDescriptorProcessor:NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
6/15/2016 3:48:37 PM2016-06-15 12:48:37.345:INFO:/:Initializing Spring root WebApplicationContext
6/15/2016 3:53:51 PMINFO  BootStrap: Starting Rundeck 2.6.7-1...
6/15/2016 3:53:51 PMINFO  BootStrap: using rdeck.base config property: /var/lib/rundeck
6/15/2016 3:53:51 PMINFO  BootStrap: loaded configuration: /etc/rundeck/framework.properties
6/15/2016 3:53:54 PMINFO  BootStrap: RSS feeds disabled
6/15/2016 3:53:55 PMINFO  BootStrap: Rundeck is ACTIVE: executions can be run.
6/15/2016 3:53:58 PMINFO  BootStrap: Rundeck startup finished in 14186ms
6/15/2016 3:53:58 PM2016-06-15 12:53:58.425:INFO:oejsh.ContextHandler:started o.e.j.w.WebAppContext{/,file:/var/rundeck/lib/exp/webapp/},/var/lib/rundeck/exp/webapp
6/15/2016 3:54:00 PM2016-06-15 12:54:00.815:INFO:/:Initializing Spring FrameworkServlet 'grails'
**6/15/2016 3:54:01 PM**2016-06-15 12:54:01.328:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440

**Comment by gschueler** [comment]
how much memory is allocated?

**Comment by amitdaniel86** [comment]
It's a docker container and the machine has : 8 GB memory

             total       used       free     shared    buffers     cached
Mem:          7984       7815        168          4        382       4023
-/+ buffers/cache:       3409       4574
Swap:            0          0          0


rundeck start with : -Djava.io.tmpdir=/tmp/rundeck -Xmx1024m -Xms256m -XX:MaxPermSize=256m

**Comment by amitdaniel86** [comment]
@gschueler Do you have any input for that ?

**Comment by gschueler** [comment]
the slowest part seems between these two lines:

    6/15/2016 3:48:37 PM2016-06-15 12:48:37.345:INFO:/:Initializing Spring root WebApplicationContext
    6/15/2016 3:53:51 PMINFO BootStrap: Starting Rundeck 2.6.7-1...

You might try enabling DEBUG level logging to see what is happening in the interim.

1024m memory is probably bare minimum, but should be sufficient.

do you have a `grails.serverURL` defined in the rundeck-config.properties file?

**Comment by amitdaniel86** [comment]
@gschueler 
I will enable debug mode and update .

Yes of course i have grails.serverURL -

grails.serverURL=https://rundeck.MYDOMAIN.com

**Comment by amitdaniel86** [comment]
@gschueler Any update ?

**Comment by ahonor** [comment]
I can't reproduce this
