### ISSUE TITLE
Replace old rundeck cli tools with modern version

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#1899]
new client code: https://github.com/rundeck/rundeck-cli

**Comment by wilrodriguez** [comment]
The new cli tools look pretty awesome! I'd love to see a cli tool for evaluating the acl rights of a given user.

**Comment by gschueler** [comment]
@wilrodriguez you can (sort of) do that using the current `rd-acl` tool, use the `rd-acl list -g group1,group2` command, which will evaluate a number of ACL tests for the specified groups.  If you specify e.g. `-p project` or `-j jobname` it will also evaluate those type of resources.  To find out acl values for specific jobs/nodes you have to do them individually however, it doesn't look at what is actually in your system

**Comment by wilrodriguez** [comment]
Oh nice! I was wondering if that was possible. I was about to try and implement my own logic to test that sort of thing. This saves some time! Thanks Greg!
