### ISSUE TITLE
Compatiblity Mode in Internet Explorer

### ISSUE THREAD

**Issue by niphlod** [rundeck/rundeck#1901]
Hi, apparently this merge (https://github.com/rundeck/rundeck/pull/1423) was reverted... is there a reason behind it ?
Without setting that tag, or setting an header on each response, compatibility is not changed, and "enteprise usage" on Win is compromised...

The first 3 meta on each page should be

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

**Comment by gschueler** [comment]
That looks like it was accidentally reverted, it should be restored.  thanks for bringing that to attention
