### ISSUE TITLE
Node name matching is case sensitive

### ISSUE THREAD

**Issue by michael-dickinson** [rundeck/rundeck#1908]
Node names appear to be case sensitive, this should not be the case. If you specify a node to execute a job on using an option, then the user has to enter the node name in the correct case. Filtering on nodes also requires the correct case to be used. Given that DNS is case insensitive, this distinction seems limiting and pointless. This was checked on 2.6.2.1 and 2.6.6.1

**Comment by richiereynolds** [comment]
I don't think this should be done. Node names aren't necessarily host names so I don't see the DNS connection. I would say that most users would expect case sensitivity. (Everything else is)

**Comment by ahonor** [comment]
As @richiereynolds states, there are many uses of "nodes" so case sensitivity could be important.
