### ISSUE TITLE
Upon login the browser does not ask if the user want to save the password

### ISSUE THREAD

**Issue by segadora** [rundeck/rundeck#1909]
Version: 2.6.8
Browser: Chrome
OS: Linux

**Comment by ahonor** [comment]
This is a browser feature and not something rundeck can force

**Comment by segadora** [comment]
So in what browser are (browser remember login) supported? @ahonor 
It dosn't work in Chrome or Firefox.

**Comment by gschueler** [comment]
it works in Chrome and Firefox for me. perhaps you have disabled it or chosen "don't remember this password" in the past, the browser might no longer prompt you until you reset it.

**Comment by taisph** [comment]
Chrome disables login/password remember/autofill on sites with self-signed, invalid and otherwise untrusted certificates. Firefox probably does the same.
