### ISSUE TITLE
Enable referencing jobs across projects

### ISSUE THREAD

**Issue by ARentz07** [rundeck/rundeck#1916]
If I have a project A containing job 1 and project B containing job 2, I would like the ability to add referencing job 2 as a step in job 1. I've run into a real use case in Rundeck where this would prove quite useful. Rather than copy-pasting (read: export and re-import) jobs across multiple projects, why not simply re-use existing jobs across the projects?

## Considerations
ACL policy implementation could be interesting. Let's say Jim has access to run any job in project A, but not project B. Should Jim be able to run job 1, knowing it references job 2? Sadly, I'm not sure. Ideally, I'd say no. If we allowed cross-project references but didn't support cross-project ACL policy checks, users could simply create a job to call another job in a project to which they wouldn't normally have access. Thus, in the hypothetical scenario, Jim shouldn't be able to run job 1.

Feedback on this is appreciated!

_(Note: I tried skimming through the issues to find something related, but no luck. This is not to say I did a completely thorough search.)_

**Comment by jenulis** [comment]
@ARentz07 You could you created a job that executes a CLI command that runs the job on the other project. You could also try an HTTP job that hits the API.

**Comment by ARentz07** [comment]
@jenulis True, I hadn't evaluated the HTTP step plugin yet. Would it give the same ability as a regular job reference step - that is, access to logs, and monitoring during the job run? My assumption there was of course, that it did not.

**Comment by gschueler** [comment]
Do you really want the job 2 to be part of another project? there has been discussion about "job libraries" https://github.com/rundeck/rundeck/issues/807

also see: https://github.com/rundeck/rundeck/issues/118

**Comment by ahonor** [comment]
I have discussed this issue several times and in the end the possibility of a change in one project having any potential impact on another outweighs sharing jobs between projects. An alternative is to create a plugin for that shared functionality. 

-1

**Comment by ARentz07** [comment]
@gschueler, thanks for referencing the "job libraries" proposal. That should be equally well-suited to cut down on duplication and drift between jobs.

**Comment by ARentz07** [comment]
Closing this out, since we have a good alternative. Thanks a lot! @ahonor @gschueler 💯
