### ISSUE TITLE
Question about Log Output

### ISSUE THREAD

**Issue by max-peroch** [rundeck/rundeck#1918]
Is there a way to have a quiet log output when a job is ran ?
Basically I would love to hide this kind of result :

```
    Result: 1
    Failed: NonZeroResultCode: Result code was 1
```

The script that is launched is already very explicit, and ran a lot, so the extra info that Rundeck wrap on it is a noise in this scenario.
Thanks for your answer !

Maxime

**Comment by ahonor** [comment]
@max-peroch Try the new Log Filter plugin to quiet the output
