### ISSUE TITLE
API query "Executions" not accepting all GET parameters

### ISSUE THREAD

**Issue by fernandopcg** [rundeck/rundeck#1923]
I'm trying to get all executions for a given project using: 
`GET /api/14/project/MY_PROJECT/executions`
And trying to filter them based on the statusFilter and userFilter

However, when issuing a GET request passing these parameters (Within the URL), the response is not even filtered properly and I receive executions with different users or statuses.

However, when issuing an OPTIONS request and passing parameters (Not in the URL but in the request body) it does work even though the API says to use GET (And we can only use GET for this request as per some limitations we have)

**Comment by gschueler** [comment]
what is your exact request URL?

**Comment by fernandopcg** [comment]
It's this (IP address and Project name redacted for privacy reasons) 
GET from `http://XX.XX.XX.XX:4440/api/14/project/My_Project_Name/executions?statusFilter=failed`
Headers:

- `Content-Type: application/json`
- `X-Rundeck-Auth-Token: <token>`
- `Accept: application/json`

The response comes in XML format even though I'm asking for a JSON, but that is not a big deal, the filter not working, however, is

**Comment by fernandopcg** [comment]
I've traced the issue down to the `Content-Type` header that messes up the whole request (It's not needed for a GET anyway, was there from a previous POST). The output is still a XML, I'll open a different issue for that
