### ISSUE TITLE
Failed: EXIT_CODE: Execution failed on minion with exit code 1

### ISSUE THREAD

**Issue by openstackAnalyst** [rundeck/rundeck#1925]
When running the job using rundeck salt-step plugin, i receive an error as shown below:

Execution failed: 58: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [vmSaltMinion: EXIT_CODE: Execution failed on minion with exit code 1]}, Node failures: {vmSaltMinion=[EXIT_CODE: Execution failed on minion with exit code 1]}, status: failed
Setup

I have configured rest_cherrypy and eauth as shown below:

external_auth:
    pam:
        openstack:
            - .*
            - '@runner'

rest_cherrypy:
port: 8000
host: 0.0.0.0
disable_ssl: true
debug: true

In the /var/log/salt/master logs, i can only see :

2016-06-30 19:23:23,395 [py.warnings ][WARNING ][12695] /usr/lib/python2.7/dist-packages/salt/client/mixins.py:312: DeprecationWarning: kwargs must be passed inside the low under "kwargs"
2016-06-30 19:23:24,202 [py.warnings ][WARNING ][12738] /usr/lib/python2.7/dist-packages/salt/client/mixins.py:312: DeprecationWarning: kwargs must be passed inside the low under "kwargs"

Versions Report

openstack@vmSaltMaster:~$ salt --versions-report
Salt: 2015.5.3
Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
Jinja2: 2.7.2
M2Crypto: 0.21.1
msgpack-python: 0.3.0
msgpack-pure: Not Installed
pycrypto: 2.6.1
libnacl: Not Installed
PyYAML: 3.10
ioflo: Not Installed
PyZMQ: 14.0.1
RAET: Not Installed
ZMQ: 4.0.4
Mako: Not Installed
Tornado: Not Installed
Debian source package: 2015.5.3+ds-1trusty1
openstack@vmSaltMaster:~$

**Comment by gschueler** [comment]
please file in the https://github.com/rundeck-plugins/salt-step repo
