### ISSUE TITLE
Help me  with “ Unknown: [jsch-scp] Failed copying the file: No response from server”

### ISSUE THREAD

**Issue by hanyan007** [rundeck/rundeck#1929]
hi~

  when  i  excute a job  with script in rundeck server , print  

Unknown: [jsch-scp] Failed copying the file: No response from server, proxy_GD_DX_19

rundeck 2.6.7-1
node  centos 6.5 64bit

thanks~

**Comment by PeterGarlic** [comment]
https://groups.google.com/forum/?hl=en#!forum/rundeck-discuss

**Comment by ahonor** [comment]
Please reopen if this remains a concern
