### ISSUE TITLE
refresh of resource.xml not working instantly

### ISSUE THREAD

**Issue by zychonatic** [rundeck/rundeck#1934]
hi,

after editing the resource.xml directly, new nodes are not showing up immediatly in the frontend.
it takes ~30sec to see the new node.

it was working previously in version 2.6.2, what have changed since then?

is there a solution for this?

**Comment by zychonatic** [comment]
i saw that in 2.6.3 there was the asyncronous resource cache introduced. can we somehow disable it? this issue is breaking our automated setup of hosts

**Comment by ahonor** [comment]
@zychonatic yes you can disable it for the project.

**Comment by looprock** [comment]
Hi Alex, I'm having issues finding out how to disable this. Could you please point me at a reference?  Thanks!

**Comment by looprock** [comment]
Is this the right setting? project.nodeCache.enabled=false

**Comment by ahonor** [comment]
@looprock correct
Eg
```
project.nodeCache.delay=30
project.nodeCache.enabled=false
```
