### ISSUE TITLE
After initial installation and login, the URL changes from <IP>:4440 to localhost:4440

### ISSUE THREAD

**Issue by IronRainNL** [rundeck/rundeck#1935]
I deployed RunDeck in a test environment, on a headless server.
After installation, I logged in from my laptop, and after I hit the login button, the URL changed from: 

`<IP>:4440`
to
`http://localhost:4440/menu/home` 

which wouldn't open of course.

Manually changing the URL back to the IP solves the problem.

EDIT:
This happens with everything I try to do, for example creating a new project.
After I hit the create button, it tries to connect on `localhost:4440` instead of `<IP>:4440`.

Derk

**Comment by IronRainNL** [comment]
I have found the config file where these properties can be edited.
Would it be an idea to get the IP address of the machine that runs RunDeck instead of localmachine, and use this in the configs?

**Comment by gschueler** [comment]
change the `rundeck-config.properties` file to set the `grails.serverURL` to point to the URL you want the server to be accessible from.

**Comment by rajeshgit221** [comment]
Hi All,
Installed rundeck and changed from local host to ipaddress in below two places but still i get the "this site can't be reached" error, not sure whats going on, can someone help me with this issue ?

1. rundeck-config.properties
2. framework.properties

Error when i tried to login:
This site can’t be reached
"ipaddress took too long to respond."
ERR_CONNECTION_TIMED_OUT 

Thanks in Advance...

**Comment by gschueler** [comment]
check your firewall settings
