### ISSUE TITLE
"Responsive" design hide long option names 2.6.1

### ISSUE THREAD

**Issue by snebel29** [rundeck/rundeck#1940]
When using long option names, and depending on the size of the "window" the option name is hidden under the text box, see attached screenshot for further details.

The expected behavior would be to do not hide it, by continuing in the text in the next paragraph or something similar.

![medium_width](https://cloud.githubusercontent.com/assets/9039085/16681554/55ec07c4-44ed-11e6-916f-33e06efc250d.png)

![short_width](https://cloud.githubusercontent.com/assets/9039085/16681551/541bfc88-44ed-11e6-82cc-9cf8ce058962.png)

![broad_width](https://cloud.githubusercontent.com/assets/9039085/16681559/5a1c5d1c-44ed-11e6-9f2f-cf484cb5adfa.png)

Regards

**Comment by bergerx** [comment]
This could be an ugly hack but, appending a `<wbr>` tag after the underscore(`_`) and dot(`.`) characters while preparing the HTML in rundeck could help as described here:
http://stackoverflow.com/questions/6316863/css-word-wrap-line-break-on-underscores-in-addition-to-whitespace-and-hyphens

or maybe this one, but this seems more ugly: 
http://stackoverflow.com/a/5108401/140651

**Comment by gschueler** [comment]
@bergerx thanks for suggestions
