### ISSUE TITLE
Weird behaviour during enable/disable jobs scheduling.

### ISSUE THREAD

**Issue by philippevidal80** [rundeck/rundeck#1941]
Hello,

I installed Rundeck Cluster in 2.6.8-1 on 2 AWS EC2 instances (with S3 Logs, RDS).

Now, when I create or import a job with schedule that run for times and wish to make it **not** "schedule to run repeatedly" anymore, I select NO and SAVE the job definition.

Oddly, job continue to be schedule and run... ? Even if I choose NO EXECUTION and NO SCHEDULING after that.

The only solution found was to re-schedule the job with new cron and select YES for "schedule to run repeatedly", YES for "Enable Scheduling", YES for "Enable Execution" and SAVE job definition to reactivate the job "normaly".

Finally, let "schedule to run repeatedly" on YES and NO for "Enable Scheduling", NO for "Enable Execution". SAVE job definition and I could make this job definitively stop.

Did I missed something on "schedule/no schedule" process ? Is it a bug ?

I don't think this issue is related to cluster installation because all tasks have been done on the same rundeck server node.

Thank you.

Regards,
Philippe

**Comment by makered** [comment]
Experiencing the exact same issue, also with a 2 node Rundeck cluster 2.6.8-1.

**Comment by gschueler** [comment]
I can't reproduce this.

You uploaded a scheduled job to a cluster node.  On the same node you edited and selected "schedule to run repeatedly?" to NO, and saved it.

Is that all that you did?

**Comment by makered** [comment]
In my case, we have two nodes that are round-robin load-balanced so it is quite possible that we disabled the schedule on a job from a different node then the one where the job was initially scheduled (does it matter?).

Our workflow:

1. Created a job and scheduled to run repeatedly.
2. After some time and executions, edited the job in the UI, set "Scheduled to run repeatedly?" to "No" and saved.
3. Noticed that job continued executing.

**Comment by gschueler** [comment]
@makered thanks, i think the issue lies in the clustering

**Comment by makered** [comment]
Thanks @gschueler!

**Comment by philippevidal80** [comment]
Big big thanks @gschueler.

**Comment by jennyfountain** [comment]
We are having the same issue - do you know when 2.6.9 will go up?

**Comment by gschueler** [comment]
i set the due date to Aug 5, we expect to release it sometime this week however
