### ISSUE TITLE
scheduled job delay

### ISSUE THREAD

**Issue by jdxin0** [rundeck/rundeck#1943]
<img width="339" alt="screen shot 2016-07-09 at 9 40 28 am" src="https://cloud.githubusercontent.com/assets/11607613/16705341/382fb3a8-45b9-11e6-9307-55e8925be833.png">

scheduled job should be executed 35 min ago.

**Comment by ahonor** [comment]
Please reopen if this remains a concern

**Comment by splio-ngirardi** [comment]
Dear all,

Same issue here. I started using rundeck in production since the beginning of the week and during the ramp up we encountered delay in the jobs executions. Any ideas ? (4vCPU/4GB RAM)

**Comment by ahonor** [comment]
@splio-ngirardi how many concurrent jobs are running when this occurs?

**Comment by splio-ngirardi** [comment]
Dear Alex,

Thank you for your answer.
Not able to know ... after reading documentation, I have to change : org.quartz.threadPool.threadCount = 20 ? (Am I wrong ?)

I have 500 jobs with differents scheduling. Is there a way to know which value I have to set ?
Here is system health :

stats: scheduler
--
ratio | 10%10% Complete
running | 1
threadPoolSize | 10
active | 45
