### ISSUE TITLE
only the one role is useable

### ISSUE THREAD

**Issue by wu0407** [rundeck/rundeck#1946]
rundeck install from rpm and configure the "security-role" in the web.xml.But only the frist role can use. The  "develop" user can login in my configure,but the admin and  useronlu can not login,to complain “HTTP ERROR 403 !role” .
I read the [security-role](http://rundeck.org/docs/administration/authenticating-users.html#security-role) and [i-get-an-error-logging-in-http-error-403--reason-role](https://github.com/dtolabs/rundeck/wiki/Faq#i-get-an-error-logging-in-http-error-403--reason-role)
. not any document with rpm to add --skipinstall.

I want  create different aclpolicy by role.  like this  http://www.techpaste.com/2015/06/rundeck-user-permissions-and-access-control-setup/  .how to accomplish it ? 

rundeck version: 2.6.8-1
web.xml:
```
        <security-role>
                <role-name>dev</role-name>
                <role-name>user1</role-name>
        </security-role>
```
realm.properties:
```
admin:admin,user,admin,architect,deploy,build
develop: MD5:e10adc3949ba59abbe56e057f20f883e,dev
useronlu:123456,user1
```

**Comment by gschueler** [comment]
"security-role" defines required roles to simply log in to the application, it can be used to filter users who are allowed to use Rundeck.  If you want *all* users who can log in to use rundeck, then it's easiest to use the default `<role-name>user</role-name>`, and use a common "user" role for everybody inside realm.properties.

**Comment by wu0407** [comment]
ok,thank you reply. that is work.
