### ISSUE TITLE
rundeck salt step plugin job fails if "id:" is not used in /etc/salt/minion file

### ISSUE THREAD

**Issue by openstackAnalyst** [rundeck/rundeck#1951]
Hi

In my setup, salt master and minions are configured in a multi master configuration and whenever a minion is installed on a new server, the salt master takes the minion hostname automatically without setting it specifically in the /etc/salt/minion file at #id: parameter.

salt master and minion communicate with each other properly but when i run a job from rundeck using the salt step plugin, the jobs fail with an error as, "dispatch failed to node <node name>".

if i change my salt master to another salt master server and use it as SALT API END POINT which has minions with the #id: set to the hostname of the minion, the jobs are running fine.

How will salt step plugin in rundeck dispatch the commands to the remote minions which do not have the #id: option with hostname added in the /etc/salt/minion file.

please help me if anyone has an idea about it and how can i fix the problem.

**Comment by gschueler** [comment]
should be filed in the salt step plugin repo, thanks

**Comment by openstackAnalyst** [comment]
Thanks.

I posted my query in salt step plugin 

Link : https://github.com/rundeck-plugins/salt-step/issues/16
