### ISSUE TITLE
High CPU by mysql when deleting executions

### ISSUE THREAD

**Issue by tomkregenbild** [rundeck/rundeck#1952]
I am trying to delete old execution history using the following script:
https://github.com/danifr/rundeck-scripts/blob/60c396573c67290cf4c3c64d82f727f4f50d0d65/py_scripts/deleteoldlogs.py

The script can run for days without ever ending and over time mysql opens more and more processes that take 100% CPU until all CPU's are 100% used and the server is barely operating.

From what I see the script is only using the Rundeck API so there is nothing that should really be done to change the script.

In addition I have to add that we ran this script on two other servers and after 20 minutes they ended with no problems but on the server where we have a long history of executions this scenario is happening.

We are using rundeck with version 2.6.8 and also tried with 2.6.7.

**Comment by niphlod** [comment]
uhm. it seems that it takes every execution without any pagination and without date limits, then calculates the dates inside the script AFTER fetching everything... 

I have a prototype written in powershell (Win shop here) that doesn't burn cpu (or at least it seems so) using more "nice" calls, but it uses "modern" api i.e. /projects/proj_name/executions with "olderFilter"

**Comment by gschueler** [comment]
fyi: we have been working on a newer CLI tool (`rd` https://github.com/rundeck/rundeck-cli/), I just added support for bulk execution deletion via the API.  Several download/install options available: https://github.com/rundeck/rundeck-cli/releases

It is not a complete replacement for the script above, but it should use the API efficiently, if you want to check it out.

**Comment by dprime** [comment]
@gschueler What version of Rundeck do I need to running for that bulkdelete command to work? I get timeout errors when running it against 2.6.7-1. Other calls work like listing jobs and so on, so it's all configured correctly.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
