### ISSUE TITLE
Improve error message: "Option <name> is required, but storage value could not be read."

### ISSUE THREAD

**Issue by ARentz07** [rundeck/rundeck#1954]
Lately my team's been experiencing an issue wherein specific members of the team consistently get an error message like this one, for example:
```
Option ZabbixPassword is required, but storage value could not be read.
```

In /var/log/rundeck/rundeck.log, corresponding entries can be found such as this one: 
```
2016-06-27 08:07:14,466 [qtp1111974043-53] ERROR grails.app.controllers.rundeck.controllers.ScheduledExecutionController - Option ZabbixPassword is required, but storage value could not be read.
```

This has been difficult to troubleshoot for us because it doesn't occur for all users and doesn't seem to follow a pattern of OS or ACL privileges. 

I think this code is where the exception is coming from: https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy#L1938

More relevant info:
Rundeck 2.6.7-1 ("cafe bonbon goldenrod plane")
Node setup is a single app node with the embedded H2 database
Running on RHEL6.7

**Comment by gschueler** [comment]
When does this occur? Saving or running a job?

**Comment by ARentz07** [comment]
When running a job. For example, right after clicking the "Run Job Now" button. Here is a screenshot of one instance.

<img width="1433" alt="edited_rundeck_screenshot_1" src="https://cloud.githubusercontent.com/assets/2237314/16964351/92c30860-4dc0-11e6-9977-630ce4bb4107.png">

**Comment by gschueler** [comment]
it may happen if the user does not have access to the storage path..

**Comment by ARentz07** [comment]
I think I got it working by updating the acl policies so that users experiencing the problem could "read" storage at the path I was using. 
Sorry for logging an issue for this - not sure why but we've been using rundeck for a couple of months on my team and hadn't run into this before.

**Comment by gschueler** [comment]
@ARentz07 no problem, we should improve the error message to suggest checking ACLs
