### ISSUE TITLE
Error(rundeck.controllers.JobXMLException:Document root tag was not 'joblist': 'Error') coming when trying to import a rundeck job through curl  

### ISSUE THREAD

**Issue by arpitGarg01** [rundeck/rundeck#1955]
Using : 

curl -H "X-Rundeck-Auth-Token:tDVnJUaSvgMK71ftwk8NzUz6K7cDuZJh" -F xmlBatch=@/home/ec2-user/test.xml --insecure https://hostname:4443/api/14/project/DistributedArchitecture/jobs/import

Error : 
<result error='true' apiversion='17'>
  <error code='api.error.jobs.import.invalid'>
    <message>Jobs Document was invalid for format xml: rundeck.controllers.JobXMLException: Document root tag was not 'joblist': 'Error'</message>
  </error>

**Comment by gschueler** [comment]
what does the test.xml file contain?

here is an example using curl: https://github.com/rundeck/rundeck/blob/master/test/api/test-jobs-import.sh

**Comment by ahonor** [comment]
Please reopen if this remains a concern
