### ISSUE TITLE
API call returns XML instead of JSON

### ISSUE THREAD

**Issue by fernandopcg** [rundeck/rundeck#1957]
I'm sending this GET request with headers

> http://x.x.x.x:4440/api/16/project/deploy_application/jobs
> X-Rundeck-Auth-Token: 3fuh6klvylwbk4gu3y
> Accept: application/json

I'm trying this with Chrome extensions _Postman_ and _Simple Rest Client_ for testing, as well as from a Java application (Which is where we want to request the data). However the response comes in XML form as opposed as the expected result.

But here comes the fun part: When using _Advanced REST Client_ Chrome app it **does** work using the same request parameters.

We would need to have this data in JSON format, so this is a problem. Any clue?

**Comment by gschueler** [comment]
what version of rundeck are you using?

**Comment by fernandopcg** [comment]
It's Rundeck 2.6.8

**Comment by gschueler** [comment]
can you try with `curl`?

e.g. this returns json correctly for me:

    curl -H x-rundeck-auth-token:xxx http://madmartigan.local:4440/api/16/project/test/jobs -H accept:application/json

**Comment by Greg-Szabo** [comment]
Hi,

I'm having the same issue. Here are some details for troubleshooting purposes:
Rundeck-2.6.8, unpacked WAR with Tomcat 8.0.32 and JDK 1.8.0_91
Command:
GET /api/17/system/info
Headers:
Content-Type: application/json
Accept: application/json
X-Rundeck-Auth-Token: (authtoken)

Results:
1. (ok) Using curl and adding the headers with -H: expected results are received (json result)
2. (ok) Fiddler4: expected results are received
3. (wrong) AngularJS $resource: XML result received (showed into a json object byte-by-byte)
4. (wrong) Chrome Postman: XML result received

I tried adding User-Agent to my AngularJS $resource headers (Chrome and Firefox footprints) but it didn't make any difference. In Postman I tried the User-Agent "Fiddler", without any difference. When I changed the content-type and the accept headers to xml, I received XML results as expected in all four tests.

Postman sets the Content-type to application/xml;charset=UTF-8 in the response. Fiddler sets the the content-type to application/json;charset=UTF-8 in the response.

Right before I sent this message, it hit me, that maybe it's something to do with cookies. Fiddler shows a JSESSIONID cookie in the response and Postman doesn't capture cookies by default. So, I installed Interceptor for Postman and I turned it on. IF I also set the "User-Agent" (to anything) in Postman, now it returns json results. If I disable the User-Agent header or disable the interceptor (so it doesn't worry about cookies), it falls back to XML results. (All other settings are the same as detailed above.)

I'm happy to debug this further, if any other information is necessary.
Regards,
Greg

**Comment by gschueler** [comment]
Why do you specify `Content-Type: application/json` for the GET request? GET request does not have content, so should not have a content-type.

It's curious that there is a difference when you set User-Agent.

Is the XML content the valid data set for `system/info`? or is it an error message?

**Comment by gschueler** [comment]
i tested with Postman, and the response was XML.  I copied postman's generated Curl command, and the response was JSON.  Looking at my logs, the first request had a long user-agent string, and the curl request had a short user-agent string just with `curl/7.43.0`.  long story short, it looks like if the user-agent contains 'WebKit', the response sends XML instead of json. 😡 

I will look into why this is happening.  

You can try forcing a user-agent, or append `?format=json` to the request if you need JSON

**Comment by gschueler** [comment]
It looks like grails' default handling of content-negotiation will ignore the `accept` header for certain user-agents, as it believes those to be web browsers.  This is a reasonable default behavior.  (Although I understand now some issues I had making Ajax requests within the HTML/GUI code).

If you really want to disable this you can set this value in rundeck-config.properties:

~~~{.properties}
grails.mime.disable.accept.header.userAgents=
~~~

(i.e. set it to blank)

For normal usage via REST client code, either specify an appropriate `User-Agent` header, or do not send one.

closing this issue

**Comment by gschueler** [comment]
ref to grails content-negotiation docs: http://docs.grails.org/2.4.4/guide/single.html#contentNegotiation

**Comment by Greg-Szabo** [comment]
Hi Greg,

Thanks for all the useful information. Both `?format=json` and the additional rundeck config property worked fine.

In the case of AngularJS, the front-end is an actual client web browser and the XMLHTTPRequest standard doesn't allow changing the User-Agent. (Relevant details [here](https://www.w3.org/TR/XMLHttpRequest/#the-setrequestheader%28%29-method).)
So for any json-based JavaScript front-end these settings are mandatory.

I suggest mentioning the grails config setting on the Rundeck API page, maybe under the "XML and JSON section". I just noticed that "format" is already mentioned there, maybe for beginners it's worth mentioning the exact syntax, like you did in this ticket.

Thanks for all the hard work on Rundeck.

Regards,
Greg

**Comment by jp** [comment]
Hello,

I have a similar issue with the version 2.7.3, but I don't manage to get a workaround.

### Using header Content-Type: application/json
As per the documentation http://rundeck.org/docs/api/#execution-info

`$ curl "http://localhost:4440/api/2/execution/2" -H "X-Rundeck-Auth-Token:lwPqJIZpN53HLuK1vVidSppr1ek7TW4u" -H "Content-type:application/json"
<result success='true' apiversion='18'>
  <executions count='1'>
    <execution id='2' href='http://localhost:4440/project/test/execution/show/2' permalink='' status='aborted' project='test'>
      <user>admin</user>
      <date-started unixtime='1490128677482'>2017-03-21T20:37:57Z</date-started>
      <date-ended unixtime='1490128871210'>2017-03-21T20:41:11Z</date-ended>
      <abortedby>admin</abortedby>
      <description>for i in `seq 1 72000` true; do  sleep 0.5 ; echo $(date) $i ; echo $(date) $i ; echo --; done</description>
      <argstring />
    </execution>
  </executions>
</result>`

### Using header accept:application/json

`curl "http://localhost:4440/api/10/execution/2" -H "X-Rundeck-Auth-Token:lwPqJIZpN53HLuK1vVidSppr1ek7TW4u" -H accept:application/json                                            
{"error":true,"apiversion":18,"errorCode":"api.error.item.unsupported-format","message":"The format is not valid: json"}`

### Using another route

`curl "http://localhost:4440/api/10/execution/2/state" -H "X-Rundeck-Auth-Token:lwPqJIZpN53HLuK1vVidSppr1ek7TW4u" -H accept:application/json                                           
{"startTime":"2017-03-21T20:37:57Z","stepCount":1,"allNodes":["localhost"],"targetNodes":["localhost"],"updateTime":"2017-03-21T20:40:42Z","nodes":{"localhost":[{"stepctx":"1","executionState":"FAILED"}]},"executionId":2,"steps":[{"startTime":"2017-03-21T20:37:57Z","id":"1","nodeStep":true,"duration":165101,"stepctx":"1","updateTime":"2017-03-21T20:37:57Z","parameterStates":{},"nodeStates":{"localhost":{"errorMessage":"Result code was 143","startTime":"2017-03-21T20:37:57Z","duration":165099,"updateTime":"2017-03-21T20:40:42Z","endTime":"2017-03-21T20:40:42Z","executionState":"FAILED","meta":{"resultCode":143,"failureReason":"NonZeroResultCode"}}},"endTime":"2017-03-21T20:40:42Z","executionState":"FAILED"}],"serverNode":"localhost","endTime":"2017-03-21T20:40:42Z","executionState":"FAILED","completed":true}`

Is there something here to get the output as JSON?

**Comment by fernandopcg** [comment]
@jp have you tried putting `?format=json` (see the comment above yours) behind your URL? I've noticed you haven't posted that result in your comment

**Comment by jp** [comment]
Yes I tried it, same result as the "accept" header:

`$ curl "http://localhost:4440/api/10/execution/2?format=json" -H "X-Rundeck-Auth-Token:lwPqJIZpN53HLuK1vVidSppr1ek7TW4u"
{"error":true,"apiversion":18,"errorCode":"api.error.item.unsupported-format","message":"The format is not valid: json"}`

**Comment by gschueler** [comment]
If you are using api v 10, json format is not supported

change to use api v18

**Comment by jp** [comment]
Ok, it works :smile: 
API reference states `GET /api/1/execution/[ID]`
which provide the same result as version 10.

Result with version 18:

`curl "http://localhost:4440/api/18/execution/2/state" -H "X-Rundeck-Auth-Token:lwPqJIZpN53HLuK1vVidSppr1ek7TW4u" -H accept:application/json                                           
{"startTime":"2017-03-21T20:37:57Z","stepCount":1,"allNodes":["localhost"],"targetNodes":["localhost"],"updateTime":"2017-03-21T20:40:42Z","nodes":{"localhost":[{"stepctx":"1","executionState":"FAILED"}]},"executionId":2,"steps":[{"startTime":"2017-03-21T20:37:57Z","id":"1","nodeStep":true,"duration":165101,"stepctx":"1","updateTime":"2017-03-21T20:37:57Z","parameterStates":{},"nodeStates":{"localhost":{"errorMessage":"Result code was 143","startTime":"2017-03-21T20:37:57Z","duration":165099,"updateTime":"2017-03-21T20:40:42Z","endTime":"2017-03-21T20:40:42Z","executionState":"FAILED","meta":{"resultCode":143,"failureReason":"NonZeroResultCode"}}},"endTime":"2017-03-21T20:40:42Z","executionState":"FAILED"}],"serverNode":"localhost","endTime":"2017-03-21T20:40:42Z","executionState":"FAILED","completed":true}`

THanks @gschueler

**Comment by jp** [comment]
@gschueler , I can try this, but do you know if this is working with v2.5.3?

**Comment by thanhbinh0995** [comment]
i added the header when fetch data and it's work
headers: {
	"Authorization": "Basic YnRwaGFtOlF3ZSFAIzEyMw==",
	"Accept": "application/json",
	"Content-Type": "application/json"
}

**Comment by dkhode** [comment]
Just in case, if you're using `curl`:

`curl -k -X GET -H "Accept:application/json" "http://localhost:4440/api/14/execution/2?authtoken=YOURTOKEN"`

Hope, It will helps someone!

**Comment by agarg136** [comment]
Hi, I am trying to trigger a rundeck job and parse the response back.
I am able to get the job triggered with the code below but the response I am getting seems to point out an error with the json

This is how I am sending the request:-

	url = env.Config().RunDeck().Address() + "/" + env.Config().RunDeck().JobId() + "/run?format=json"

	if req, err = http.NewRequest("POST", url, bytes.NewBuffer(body)); err != nil {
		response.New(http.StatusBadRequest).Error("Bad Request").Write(w, r)
		return
	}
	req.Header.Add("X-RunDeck-Auth-Token", env.Config().RunDeck().AuthToken())
	req.Header.Add("Accept", "application/json")
	req.Header.Add("Content-Type", "application/json")

	client := &http.Client{}
	if resp, err = client.Do(req); err != nil {
		panic(err)
	}
	env.Logger().Debug("Response ", zap.Any("res", resp))

	response.New(http.StatusFound).Result("Request submitted to trigger job on runDeck").Write(w, r)

This sends post request body to rundeck and triggers the job. However, I do not see a json response as I expected. Instead, I get this error message:- 

{"level":"debug","ts":"2021-03-07T11:00:30.080-0500","caller":"decider/service.go:394","message":"Response ","trace_id":"0431690a-7044-4d09-8da9-e5325ca192a7","resError":"json: unsupported type: func() (io.ReadCloser, error)"}

Could anyone suggest what could be wrong here ?
