### ISSUE TITLE
Running steps in parallel

### ISSUE THREAD

**Issue by rkgaddabathini** [rundeck/rundeck#1958]
I have couple of jobs which my team has to trigger with a single click(New Job where all jobs are called as steps) and want all steps to be executed in parallel. 

Do we have any such option?
Is there an alternative to do that ?

**Comment by gschueler** [comment]
you can use the "parallel" strategy.

It is enabled via configuration in rundeck-config.properties:

    feature.incubator.parallelWorkflowStrategy=true

**Comment by rkgaddabathini** [comment]
Awesome. This is exactly what I wanted.

Thanks,
Ravi Kumar G
