### ISSUE TITLE
Interpret ANSI escape sequences

### ISSUE THREAD

**Issue by waldner** [rundeck/rundeck#196]
It'd be nice if the job output window could interpret the ANSI escape sequences to see colors and other effects, otherwise the output is a bunch of stuff like (eg puppet)

[0;36mnotice: Finished catalog run in 11.97 seconds[0m
[0;36mnotice: Finished catalog run in 15.53 seconds[0m

etc.

Of course with most command colored output can be turned off (which is what I'm doing ATM), but it'd be nice to be able to leave it enabled and see pretty output in rundeck.

**Comment by ava-dylang** [comment]
where is the setting to enable color codes in log output?

**Comment by gschueler** [comment]
closing this issue, since ansi color support was added in release 2.1.2 #786 

It is enabled by default in Rundeck log output.  

You may need to set an Environment variable for the command you run to turn on colorized output if it doesn't automatically do so

**Comment by royeectu** [comment]
@gschueler, which environment variables do I need to set in order to get a colorised output? 
The "Ansi color" option is selected but for some reason it doesn't work.

**Comment by gschueler** [comment]
@royeectu it depends on the command. look at the docs or the man page for the particular command you are executing

**Comment by royeectu** [comment]
@gschueler, I'm running Ansible playbooks (ansible-playbook) and I don't have the colors.
Also if I run ls -l --color=auto for example, there are no colors.
Please advise.

**Comment by gschueler** [comment]
it might require another env var to indicate appropriate terminal type

**Comment by mdelagrange** [comment]
Adding `export ANSIBLE_FORCE_COLOR=true` to my shell script fixed Ainsible terminal coloring for me.

**Comment by SergeyBear** [comment]
@mdelagrange many thanks for ansible fix!!!
