### ISSUE TITLE
Accessing key storage in plugin.script-exec.default.command

### ISSUE THREAD

**Issue by OrKoN** [rundeck/rundeck#1967]
Hi,

I want to run ssh binary in `plugin.script-exec.default.command` as follows:

```
plugin.script-exec.default.command=/usr/bin/ssh -q -oSendEnv\=* -oStrictHostKeyChecking\=no -tt ${node.username}@${node.hostname} ${exec.command}
```

But I need to define -i option and provide the path to the file stored in Rundeck Key Storage.

How do I get the path to the key to pass it via -i?

Thanks in advance

**Comment by ahonor** [comment]
@OrKoN you will have to create a node-executor plugin to do that. You can do this using a shell script. Here's an [example](https://github.com/rundeck/guitars-demo/tree/master/plugins/mtl-exec-plugin/mtl-exec-plugin) that shows how to define the plugin property to access key data

      config:
        - name: ssh_key_storage_path
          title: SSH key Storage Path
          type: String
          required: false
          description: "Optional storage path for ssh-key file. Can contain property references to node attributes. A node attribute named ssh-key-storage-path will override this value."
          scope: Instance
          renderingOptions:
            selectionAccessor: "STORAGE_PATH"
            valueConversion: "STORAGE_PATH_AUTOMATIC_READ"
            storage-path-root: "keys"

**Comment by ahonor** [comment]
Please reopen this if it remains a concern
