### ISSUE TITLE
SSHProtocolFailure on v2.6.8

### ISSUE THREAD

**Issue by juanpaulo** [rundeck/rundeck#1976]
Looking through the issues I thought #1796 would fix this but for some reason I'm still getting SSHProtocolFailure errors when connecting to remote machines on v2.6.8 (cafe bonbon hotpink pushpin). Went through the logs and I didn't get much information other than this:

```
Algorithm negotiation fail
Failed: SSHProtocolFailure: Algorithm negotiation fail
```

**Comment by gschueler** [comment]
if you enable debug logging on the job, is there any more info?

**Comment by jamieps** [comment]
What OS are the remote nodes running? We had a problem connecting to systems running Solaris 8/10, the error message for that was similar.

**Comment by jamieps** [comment]
The issue we had was that when connecting to SunSSH (the Solaris fork of OpenSSH), JSch and the SSH server couldn't agree on an algorithm to use. I think it's because our systems were on older versions of Solaris which only supported: `diffie-hellman-group-exchange-sha1` and `diffie-hellman-group1-sha1`.

To get around this we now override the SSH algorithm explicitly for Solaris systems, by adding the `ssh-config-kex` attribute to Solaris nodes, set to `diffie-hellman-group1-sha1`.

**Comment by Gibby** [comment]
I am having the same issue, doesn't matter if I use a 1024 or 2048 bit key. Also tried setting ssh-config-kex but that didn't work either.

rundeck server: RHEL 6.8
node: Solaris 10 sparc
rundeck version: rundeck-launcher-2.6.9.jar
java version: jdk-8u102-linux-x64.tar.gz

Job debug log:
21:19:20 [myusername@myserver _][VERBOSE] [workflow] Begin execution: rundeck-workflow-node-first context: null
21:19:20 [myusername@myserver _][VERBOSE] preparing for sequential execution on 1 nodes
21:19:20 [myusername@myserver _][VERBOSE] Executing command on node: myserver, NodeEntryImpl{tags=[], attributes={nodename=myserver, hostname=myserver, osVers=5.10, osArch=sparc, description=Last updated 2016-09-09 15:44:35, osName=SunOS, username=myusername, tags=}, project='null'}
21:19:20 [myusername@myserver _][VERBOSE] NodeSet: MultiNodeSelector{nodenames=[myserver]}
21:19:20 [myusername@myserver _][VERBOSE] Workflow: com.dtolabs.rundeck.core.execution.workflow.StepFirstWorkflowStrategy$stepFirstWrapper@7a696c31
21:19:20 [myusername@myserver _][VERBOSE] data context:  {node={os-version=, hostname=myserver, osVers=5.10, os-arch=sparc, name=myserver, os-family=, description=Last updated 2016-09-09 15:44:35, os-name=SunOS, username=myusername, tags=}, job={wasRetry=false, user.name=myusername, project=myproject, url=http://myserver:8880/project/myproject/execution/follow/21, execid=21, serverUUID=null, serverUrl=http://myserver:8880/, loglevel=DEBUG, name=uptime, id=0671dd31-917b-4210-bcde-e85f1648e0b5, retryAttempt=0, group=null, username=myusername}, globals={}, option={}}
21:19:20 [myusername@myserver 1][VERBOSE] [workflow] Begin step: 1,NodeDispatch
21:19:20 [myusername@myserver 1][VERBOSE] 1: Workflow step executing: com.dtolabs.rundeck.execution.ExecutionItemFactory$4@49c1e76
21:19:20 [myusername@myserver 1][VERBOSE] preparing for sequential execution on 1 nodes
21:19:20 [myusername@myserver 1][VERBOSE] Executing command on node: myserver, NodeEntryImpl{tags=[], attributes={nodename=myserver, hostname=myserver, osVers=5.10, osArch=sparc, description=Last updated 2016-09-09 15:44:35, osName=SunOS, username=myusername, tags=}, project='null'}
21:19:20 [myusername@myserver 1][VERBOSE] [workflow] beginExecuteNodeStep(myserver): NodeDispatch: com.dtolabs.rundeck.execution.ExecutionItemFactory$4@49c1e76
21:19:20 [myusername@myserver 1][VERBOSE] Using ssh keyfile: /nfs/home/myusername/.ssh/id_rsa
21:19:20 [myusername@myserver 1][VERBOSE] Starting SSH Connection: myusername@myserver (myserver)
21:19:20 [myusername@myserver 1][VERBOSE] Using private key file: /nfs/home/myusername/.ssh/id_rsa
21:19:20 [myusername@myserver 1][VERBOSE] Set timeout to 0
21:19:20 [myusername@myserver 1][VERBOSE] Connecting to myserver:22
21:19:20 [myusername@myserver 1][VERBOSE] Connecting to myserver port 22
21:19:20 [myusername@myserver 1][VERBOSE] Connection established
21:19:20 [myusername@myserver 1][VERBOSE] Remote version string: SSH-2.0-Sun_SSH_1.1.8
21:19:20 [myusername@myserver 1][VERBOSE] Local version string: SSH-2.0-JSCH-0.1.53
21:19:20 [myusername@myserver 1][VERBOSE] CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
21:19:20 [myusername@myserver 1][VERBOSE] aes256-ctr is not available.
21:19:20 [myusername@myserver 1][VERBOSE] aes192-ctr is not available.
21:19:20 [myusername@myserver 1][VERBOSE] aes256-cbc is not available.
21:19:20 [myusername@myserver 1][VERBOSE] aes192-cbc is not available.
21:19:20 [myusername@myserver 1][VERBOSE] CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
21:19:20 [myusername@myserver 1][VERBOSE] CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
21:19:20 [myusername@myserver 1][VERBOSE] SSH_MSG_KEXINIT sent
21:19:20 [myusername@myserver 1][VERBOSE] SSH_MSG_KEXINIT received
21:19:20 [myusername@myserver 1][VERBOSE] kex: server: gss-group1-sha1-toWM5Slw5Ew8Mqkay+al2g==,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,diffie-hellman-group1-sha1
21:19:20 [myusername@myserver 1][VERBOSE] kex: server: ssh-rsa,ssh-dss
21:19:20 [myusername@myserver 1][VERBOSE] kex: server: aes256-ctr
21:19:20 [myusername@myserver 1][VERBOSE] kex: server: aes256-ctr
21:19:20 [myusername@myserver 1][VERBOSE] kex: server: hmac-sha1
21:19:20 [myusername@myserver 1][VERBOSE] kex: server: hmac-sha1
21:19:20 [myusername@myserver 1][VERBOSE] kex: server: none
21:19:20 [myusername@myserver 1][VERBOSE] kex: server: none
21:19:20 [myusername@myserver 1][VERBOSE] kex: server: en-CA,en-US,es,es-MX,fr,fr-CA,i-default
21:19:20 [myusername@myserver 1][VERBOSE] kex: server: en-CA,en-US,es,es-MX,fr,fr-CA,i-default
21:19:20 [myusername@myserver 1][VERBOSE] kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
21:19:20 [myusername@myserver 1][VERBOSE] kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
21:19:20 [myusername@myserver 1][VERBOSE] kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc
21:19:20 [myusername@myserver 1][VERBOSE] kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc
21:19:20 [myusername@myserver 1][VERBOSE] kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
21:19:20 [myusername@myserver 1][VERBOSE] kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
21:19:20 [myusername@myserver 1][VERBOSE] kex: client: none
21:19:20 [myusername@myserver 1][VERBOSE] kex: client: none
21:19:20 [myusername@myserver 1][VERBOSE] kex: client: 
21:19:20 [myusername@myserver 1][VERBOSE] kex: client: 
21:19:20 [myusername@myserver 1][VERBOSE] Disconnecting from myserver port 22
21:19:20 [myusername@myserver 1][ERROR] Algorithm negotiation fail
21:19:20 [myusername@myserver 1][ERROR] Failed: SSHProtocolFailure: Algorithm negotiation fail
21:19:20 [myusername@myserver 1][VERBOSE] [workflow] finishExecuteNodeStep(myserver): NodeDispatch: SSHProtocolFailure: Algorithm negotiation fail
21:19:20 [myusername@myserver 1][VERBOSE] 1: Workflow step finished, result: Dispatch failed on 1 nodes: [myserver: SSHProtocolFailure: Algorithm negotiation fail]
21:19:20 [myusername@myserver _][VERBOSE] [workflow] Finish step: 1,NodeDispatch
21:19:20 [myusername@myserver _][VERBOSE] [workflow] Finish execution:  rundeck-workflow-node-first: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [myserver: SSHProtocolFailure: Algorithm negotiation fail]}, Node failures: {myserver=[SSHProtocolFailure: Algorithm negotiation fail]}, status: failed]
21:19:20 [myusername@myserver _][VERBOSE] [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [myserver: SSHProtocolFailure: Algorithm negotiation fail]}, Node failures: {myserver=[SSHProtocolFailure: Algorithm negotiation fail]}, status: failed]
21:19:20 [myusername@myserver _][ERROR] Execution failed: 21: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [myserver: SSHProtocolFailure: Algorithm negotiation fail]}, Node failures: {myserver=[SSHProtocolFailure: Algorithm negotiation fail]}, status: failed]

**Comment by gschueler** [comment]
@Gibby it looks like the server only declares these support for cipher `aes256-ctr` but the client is showing `aes256-ctr is not available`.

Did you try installing the JCE unlimited strength policy files:

http://www.oracle.com/technetwork/java/javase/downloads/jce-7-download-432124.html

**Comment by Gibby** [comment]
@gschueler that worked. Thanks!
