### ISSUE TITLE
Tilde symbol ~not expanded on the local RunDeck node

### ISSUE THREAD

**Issue by willemdh** [rundeck/rundeck#1980]
As discussed in tis thread: https://groups.google.com/forum/#!topic/rundeck-discuss/KeHabaiRtiw, it seems the tile symbol ~ is not getting expanded properly on the local RunDeck node. 
This means we can't copy files to the homefolder of the rundeck user (except if we would use the full path, which would then no longer work on other nodes, as the home folder is /var/lib/rundeck

It would be nice if one day this would work. (Very low priority.. )

**Comment by macropin** [comment]
I seem to have reproduced this with a local script. ~ in the script is executed as a literal tilde. Which breaks things.
