### ISSUE TITLE
Feature request to add html code in description text boxes

### ISSUE THREAD

**Issue by lokly** [rundeck/rundeck#1984]
Each job is documented in our wiki and I want to reference each job to the wiki the a href tag in the description area. Currently the user must copy the url. 
Please add a feature to enter html code to the description text-areas for project and jobs. 
Thanks

**Comment by gschueler** [comment]
You can add Markdown/html in the extended description of Jobs.  For projects you can add a "readme.md" for the project with markdown/html content.
