### ISSUE TITLE
Local Command not handling empty option

### ISSUE THREAD

**Issue by ScottG489** [rundeck/rundeck#1989]
I encountered this issue on version **2.6.0-1**

Steps to reproduce:
1. Create new job
2. Add a option, leaving all properties of it at their defaults (not required, no default value, etc)
3. Add a Local Command step which echo's the option. In my case I called my option '**field**':
`echo ${option.field}`
4. Finish creating the job and navigate to it to run it
5. Run the job without entering anything into the text box

The output will be `${option.field}` literally. I would expect an empty line as output.

**Comment by gstachowiak** [comment]
Hi.

Any chance of fixing it. It's very annoying.

**Comment by ahonor** [comment]
In 2.10 the ${option.field} expands to blank.
