### ISSUE TITLE
How to pass password for sudo 

### ISSUE THREAD

**Issue by Hemantt91** [rundeck/rundeck#1990]
I have few nodes. which i am connecting via rundeck.  now i want to run everything with sudo.

I am getting below error.
Failed: Unknown: java.lang.InterruptedException
16:10:28        [sudo] password for rundeck: 

can someone tell me how to pass password for this in rundeck.

**Comment by PeterGarlic** [comment]
https://groups.google.com/forum/#!forum/rundeck-discuss
