### ISSUE TITLE
Sporadic http 404 errors, gone after page reload

### ISSUE THREAD

**Issue by vdmkenny** [rundeck/rundeck#1999]
I'm on the latest rundeck version 2.6.9, but I had this issue with the previous version as well.
Often when browsing rundeck's web interface, for example editing a job or just a random page, I get hit with a "the resource could not be found" error. the url gets redirect to http://$rundeckhost/error/HTTP_BAD_GATEWAY.html.var. When I try again, it often works. These issues are sporadic, but often enough that all my jenkins builds which trigger rundeck jobs fail as well.

Jenkins log output:
Failed to get job with the identifier : ENV:GROUP/deploy : Invalid HTTP response 'HTTP/1.1 404 Not Found' for http://$rundeckhost/error/HTTP_BAD_GATEWAY.html.var

**Comment by gschueler** [comment]
is rundeck running behind a proxy?

**Comment by vdmkenny** [comment]
Well, It's running behind a reverse proxy in apache so it can be accessed from a subdomain at port 80.

**Comment by gschueler** [comment]
`HTTP_BAD_GATEWAY.html.var` is being returned by the proxy.  not sure why but perhaps check apache logs?

**Comment by vdmkenny** [comment]
You're right, I noticed it on another application on that server as well, definitely a network issue here. Thanks.
