### ISSUE TITLE
Oauth login module

### ISSUE THREAD

**Issue by vuliad** [rundeck/rundeck#2000]
Is it possible to login in rundeck via oauth?

**Comment by gschueler** [comment]
currently you would need to use something like oauth2_proxy as a proxy in front of rundeck to manage the oauth authentication. see also #1883

**Comment by donaldguy** [comment]
I posted a gist here: https://gist.github.com/donaldguy/eaa99fb0d1f17c0576255c3cf3ffc7ea

for using https://github.com/grammarly/rocker to build a container containing the kindlyops fork of oauth2_proxy and running it with rundeck per the runtime configuration of https://github.com/jjethwa/rundeck
