### ISSUE TITLE
Unable to kill a job that is not logging anything or seem stuck.

### ISSUE THREAD

**Issue by vfiset** [rundeck/rundeck#2001]
I have 3 jobs running in my rundeck install v2.6.7-1

They are all in a wierd state. The UI says it's running but there is nothing in the "Log Output" tab.

When I hit the "kill job" button, the following message appears: "Failed to Kill Job."

Nothing useful shows up in the application logs.

I had to restart rundeck to solve the problem.

**Comment by talenhao** [comment]
+1

**Comment by talenhao** [comment]
I have the same problem.

**Comment by openlucho** [comment]
I'm seeing the same issue in 2.7.1-1 after a recent upgrade.  I'm not able to stop the job without restarting the rundeck service and the job doesn't seem to respect the timeout settings for the job (keeps running after timeout is exceeded).  The job finishes all steps successfully, but fails to terminate. 

I noticed this in the service.log
`WARN  ExecutionJob: Execution 17990 save result status: failed (attempts=9/10), retrying in 199536ms
ERROR SqlExceptionHelper: Data truncation: Data too long for column 'succeeded_node_list' at row 1
ERROR ExecutionJob: Execution 17990 save result status: caught exception: Hibernate operation: could not execute statement; SQL [n/a]; Data truncation: Data too long for column 'succeeded_node_list' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; Data truncation: Data too long for column 'succeeded_node_list' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
        at rundeck.services.ReportService.reportExecutionResult(ReportService.groovy:65)
        at rundeck.services.ExecutionService.logExecution(ExecutionService.groovy:843)
        at rundeck.services.ExecutionService$_saveExecutionState_closure61.doCall(ExecutionService.groovy:2227)
        at rundeck.services.ExecutionService.saveExecutionState(ExecutionService.groovy:2148)
        at rundeck.quartzjobs.ExecutionJob$_saveState_closure4.doCall(ExecutionJob.groovy:509)
        at rundeck.quartzjobs.ExecutionJob.withRetry(ExecutionJob.groovy:447)
        at rundeck.quartzjobs.ExecutionJob.saveState(ExecutionJob.groovy:519)
        at rundeck.quartzjobs.ExecutionJob.execute_internal(ExecutionJob.groovy:162)
        at rundeck.quartzjobs.ExecutionJob$_execute_closure1.doCall(ExecutionJob.groovy:90)
        at com.codahale.metrics.Timer.time(Timer.java:99)
        at rundeck.quartzjobs.ExecutionJob.execute(ExecutionJob.groovy:89)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:202)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:573)
Caused by: com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3833)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771)
        at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2435)
        at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2582)
        at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2535)
        at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1911)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2145)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2081)
        at com.mysql.jdbc.PreparedStatement.executeUpdate(PreparedStatement.java:2066)
        ... 13 more
ERROR ExecutionJob: Execution 17990 save result status: failed (attempts=10/10) with exception: Hibernate operation: could not execute statement; SQL [n/a]; Data truncation: Data too long for column 'succeeded_node_list' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
ERROR ExecutionJob: ExecutionJob: Failed to save execution state for 17990, after retrying 10 times: org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; Data truncation: Data too long for column 'succeeded_node_list' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
`

**Comment by gschueler** [comment]
@openlucho this specific error is due to schema changes introduced recently.  see https://github.com/rundeck/rundeck/issues/2228#issuecomment-269426400

**Comment by openlucho** [comment]
Thanks, that solved my issue.

**Comment by vfiset** [comment]
@ahonor why are you closing?

**Comment by ahonor** [comment]
@vfiset are you still getting this problem?

**Comment by ctrlrsf** [comment]
@ahonor I did get this in 2.10.1. I ran the three alter statements and it's fixed now. Going forward, do these have to be added to a schema migration script or release notes?

Error:
```
ERROR ExecutionJob: ExecutionJob: Failed to save execution state for 9744, after retrying 10 times: org.springframework.dao.DataIntegrityViolationException: Hibernate operation: could not execute statement; SQL [n/a]; Data truncation: Data too long for column 'succeeded_node_list' at row 1; nested exception is com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'succeeded_node_list' at row 1
```

Before:
```
mysql> describe base_report;
+---------------------+---------------+------+-----+---------+----------------+
| Field               | Type          | Null | Key | Default | Extra          |
+---------------------+---------------+------+-----+---------+----------------+
| id                  | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| version             | bigint(20)    | NO   |     | NULL    |                |
| action_type         | varchar(256)  | NO   |     | NULL    |                |
| author              | varchar(255)  | NO   |     | NULL    |                |
| ctx_name            | varchar(255)  | YES  |     | NULL    |                |
| ctx_project         | varchar(255)  | NO   | MUL | NULL    |                |
| ctx_type            | varchar(255)  | YES  |     | NULL    |                |
| date_completed      | datetime      | NO   |     | NULL    |                |
| date_started        | datetime      | NO   |     | NULL    |                |
| mapref_uri          | varchar(255)  | YES  |     | NULL    |                |
| message             | longtext      | NO   |     | NULL    |                |
| node                | varchar(255)  | YES  |     | NULL    |                |
| report_id           | varchar(3072) | YES  |     | NULL    |                |
| status              | varchar(256)  | NO   |     | NULL    |                |
| tags                | varchar(255)  | YES  |     | NULL    |                |
| title               | longtext      | NO   |     | NULL    |                |
| class               | varchar(255)  | NO   |     | NULL    |                |
| aborted_by_user     | varchar(255)  | YES  |     | NULL    |                |
| adhoc_execution     | bit(1)        | YES  |     | NULL    |                |
| adhoc_script        | longtext      | YES  |     | NULL    |                |
| ctx_command         | varchar(255)  | YES  |     | NULL    |                |
| ctx_controller      | varchar(255)  | YES  |     | NULL    |                |
| failed_node_list    | varchar(255)  | YES  |     | NULL    |                |
| filter_applied      | varchar(255)  | YES  |     | NULL    |                |
| jc_exec_id          | varchar(255)  | YES  |     | NULL    |                |
| jc_job_id           | varchar(255)  | YES  |     | NULL    |                |
| succeeded_node_list | varchar(255)  | YES  |     | NULL    |                |
+---------------------+---------------+------+-----+---------+----------------+
```

After:
```
mysql> describe base_report;
+---------------------+---------------+------+-----+---------+----------------+
| Field               | Type          | Null | Key | Default | Extra          |
+---------------------+---------------+------+-----+---------+----------------+
| id                  | bigint(20)    | NO   | PRI | NULL    | auto_increment |
| version             | bigint(20)    | NO   |     | NULL    |                |
| action_type         | varchar(256)  | NO   |     | NULL    |                |
| author              | varchar(255)  | NO   |     | NULL    |                |
| ctx_name            | varchar(255)  | YES  |     | NULL    |                |
| ctx_project         | varchar(255)  | NO   | MUL | NULL    |                |
| ctx_type            | varchar(255)  | YES  |     | NULL    |                |
| date_completed      | datetime      | NO   |     | NULL    |                |
| date_started        | datetime      | NO   |     | NULL    |                |
| mapref_uri          | varchar(255)  | YES  |     | NULL    |                |
| message             | longtext      | NO   |     | NULL    |                |
| node                | varchar(255)  | YES  |     | NULL    |                |
| report_id           | varchar(3072) | YES  |     | NULL    |                |
| status              | varchar(256)  | NO   |     | NULL    |                |
| tags                | varchar(255)  | YES  |     | NULL    |                |
| title               | longtext      | NO   |     | NULL    |                |
| class               | varchar(255)  | NO   |     | NULL    |                |
| aborted_by_user     | varchar(255)  | YES  |     | NULL    |                |
| adhoc_execution     | bit(1)        | YES  |     | NULL    |                |
| adhoc_script        | longtext      | YES  |     | NULL    |                |
| ctx_command         | varchar(255)  | YES  |     | NULL    |                |
| ctx_controller      | varchar(255)  | YES  |     | NULL    |                |
| failed_node_list    | longtext      | YES  |     | NULL    |                |
| filter_applied      | longtext      | YES  |     | NULL    |                |
| jc_exec_id          | varchar(255)  | YES  |     | NULL    |                |
| jc_job_id           | varchar(255)  | YES  |     | NULL    |                |
| succeeded_node_list | longtext      | YES  |     | NULL    |                |
+---------------------+---------------+------+-----+---------+----------------+
27 rows in set (0.05 sec)
```

MySQL alter statements:
```
alter table base_report change column filter_applied filter_applied longtext;
alter table base_report change column succeeded_node_list succeeded_node_list  longtext;
alter table base_report change column failed_node_list failed_node_list  longtext;
```

**Comment by ahonor** [comment]
@ctrlrsf, the underlying app framework, grails, attempts to do the database migration but as you can see it is not bulletproof. Our long term goal is to implement better migration with a different tool.
