### ISSUE TITLE
StrictHostKeyChecking in framework.properties

### ISSUE THREAD

**Issue by azalio** [rundeck/rundeck#2005]
Hello!

I'm trying set option 
`framework.ssh-config-StrictHostKeyChecking=no`
but this option don't work.

After restart rundeckd I see in logs:
`Host key verification failed.`

 Where is my error?

**Comment by azalio** [comment]
Anybody?

**Comment by gschueler** [comment]
do you have any project/node ssh-config-StrictHostKeyChecking values? the most specific value would override earlier values

**Comment by azalio** [comment]
No, I don't have this value in other project/node.
