### ISSUE TITLE
Rundeck`s variables?

### ISSUE THREAD

**Issue by Michael754267513** [rundeck/rundeck#2008]
dear all:
          first,Rundeck is very good project,i  use to deploy my project, but i have some questions about rundeck`s variables.
         1, i use to rundeck workflow step,i have some job,the first job define some options and  the other jobs to use this options, but it is fail, i don`t find rundeck about global variables.  
         2, Do you have some default variables in rundeck? for example: i use to run a job in some nodes,and i want to get variable,let me know this job running in the node`s  IP address.because i want to log it.

**Comment by wilrodriguez** [comment]
Not sure if this is what you're looking for, but the notes for the [2.6.8](http://rundeck.org/2.6.9/history/version-2.6.8.html) release sum up globals. If you're more thinking about job/node level, just check the [job page](http://rundeck.org/2.6.9/manual/jobs.html#context-variables).

If you're looking to get a variable based on the results of a step, however, that isn't really something rundeck is capable of at the moment.

**Comment by Michael754267513** [comment]
Thinks , i use to  Remote URL in Allowed Values,and on ,my other job use to  get this option in my worksetp, this option is null , i run  job  without workstep ,the option is success. 
links:
http://rundeck.org/2.6.9/manual/jobs.html?utm_source=rundeckapp&utm_medium=2.6.9%20Linux%20java%201.7.0_79&utm_campaign=helplink&utm_content=editOpts/edit#option-model-provider
Example:
 var1.json:
              { "Name": "value1" }
job A and job B, \
A is config  http://1.1.1.1/test/options/var1.json and Restrictions is enforced
B is config workstep use to A.
run job A,this option is value1
run job B this option is null

**Comment by ahonor** [comment]
Please reopen if this remains a concern
