### ISSUE TITLE
Environment variable support

### ISSUE THREAD

**Issue by kulmam92** [rundeck/rundeck#2011]
Would add Environment variable support for Rudeck?

Jenkins expose set some environment variables and those can be referenced from scripts. Default environment variable can be found from [this link](https://wiki.jenkins-ci.org/display/JENKINS/Building+a+software+project#Buildingasoftwareproject-JenkinsSetEnvironmentVariables). There's also plugin called [EnvInject](https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin) that let you declare them dynamically.

This will make it easy to pass parameters between jobs and let us create very flexible jobs.

Best,
Yong

**Comment by jamielennox1** [comment]
I'm sure this is already supported. check [context-variables](http://rundeck.org/2.6.6/manual/jobs.html#context-variables)

You can also pass variables at the project level using [project.globals](http://rundeck.org/docs/administration/configuration-file-reference.html#project-global-execution-variables)

You can reference all of these variables using RD_* as the environment variable. You'll need to allow the instance to accept environment variables using this [link](http://rundeck.org/2.6.6/plugins-user-guide/ssh-plugins.html#passing-environment-variables-through-remote-command)

**Comment by ahonor** [comment]
Correct, project globals are the recommended solution.

**Comment by SolarisYan** [comment]
Hi there, who can tell me how to use Global variables like project.globals.X in job option?
i use it in job option like ${globals.kafka_broker}, but the job will error with `kafka_broker=${globals.kafka_broker}: bad substitution`.
@ahonor can you help me? thanks a lot
