### ISSUE TITLE
High cpu usage with no/few jobs running

### ISSUE THREAD

**Issue by bengerman13** [rundeck/rundeck#2016]
System: EL7
rundeck version: 2.6.8-1

Rundeck is regularly at 200-300% cpu usage.  When this happens, the UI becomes very slow. We have 9 projects (but most aren't actually used yet) and about 10-15 scheduled jobs, nearly all of which are Ansible tasks. Initially, we thought this was due to the slowness of the built-in database, but  switching to mysql did not seem to help

Top output:

```
    top - 11:40:36 up 63 days, 14:39,  9 users,  load average: 3.04, 4.28, 4.62
    Tasks: 158 total,   2 running, 156 sleeping,   0 stopped,   0 zombie
    %Cpu(s):  6.1 us,  0.5 sy,  0.0 ni, 93.3 id,  0.1 wa,  0.0 hi,  0.1 si,  0.0 st
    KiB Mem :  7910992 total,  3126036 free,  2061968 used,  2722988 buff/cache
    KiB Swap:  4194300 total,  4173808 free,    20492 used.  5351200 avail Mem 

      PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                     
      24302 rundeck   20   0 4810400 1.528g  23432 S 300.0 20.2 284:31.80 java      
```

thread dump: https://gist.github.com/bengerman13/9893fe4b086363aec31936ed4fd309df

**Comment by gschueler** [comment]
it looks like you have 20 threads calling "tailExecutionOutput", which indicates a user watching the output of an execution log.  But other than that I don't see any odd thread behavior.

what is your memory configuration for Rundeck? how many quartz threads have you configured? how is it deployed?  Can you screenshot your system info page?

**Comment by bengerman13** [comment]
Thanks for the quick reply.

The tailExecutionOutput may be interesting (or a red herring) - there was a job I was trying to monitor, but the "Log Output" page would not load, and the report for the failed step hangs for minutes, then shows an error message (trying to pull it up now, but it takes a long time for the error to show)

Java memory settings: -Xmx1024m -Xms256m -XX:MaxPermSize=256m
I haven't altered the quartz threadcount, so it's the default (10)
![rundeck-conf](https://cloud.githubusercontent.com/assets/15840717/17789403/ef7171bc-6546-11e6-8d30-a3428f45ba94.png)

**Comment by gschueler** [comment]
i meant the System Report page.  
1024m is the minimum recommended for max memory, so you may want to increase that.

**Comment by bengerman13** [comment]
I increased the min and max memory to 4096 and 1024, which of course required a bounce. The slowness didn't occur for more than a week last time, so I'll just monitor in the mean time, I suppose.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
