### ISSUE TITLE
Rundeck 2.6.8 - Remote Node SSH failures

### ISSUE THREAD

**Issue by Kronnork** [rundeck/rundeck#2017]
Hi Team,

I installed rundeck 2.6.8 and after bootstrapping node to rundeck node when I run a command on the remote node I get the following error:

**ERROR ExecutionUtilService - Execution failed: 5: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [SSHProtocolFailure: Session.connect: java.io.IOException: End of IO Stream Read]}, Node failures:**

https://github.com/rundeck/rundeck/issues/1796 suggestion of  upgrading JSCH to v0.1.53 is also not relevant as the jar version is prepackaged with the launcher.

Kindly let me know if I have missed any configurations.

Thanks
Kron

**Comment by lancepowell** [comment]
make sure the bootstrapped node is up to date on the latest packages. apt-get update or yum update. I've seen older versions of ldap cause an ssh issue that may or may not be your problem.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
