### ISSUE TITLE
Inline scripts token expansion broken in 2.6.9. How to escape the @ character?

### ISSUE THREAD

**Issue by kureus** [rundeck/rundeck#2021]
Upgraded to latest release and some of my scripts broke where I have an @ character in use.
So for example uploading a file using curl needs an @ to indicate its a file, e.g.

curl -F file=@/path/To/File http://somedomain/?filename=@option.filename@

In 2.6.6 this worked and the option.filename token was expanded properly. In 2.6.9 RD seems to pick up the first @ and expand from there.
Was there a major change to how token expansion works?
Do I now need too escape the first @ to get this working again or is this a bug?
---

Orginally posted this in the google group and was asked to create an issue here
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/rundeck-discuss/JNC8aP-c1kU/UXHNR_dxAgAJ

**Comment by gschueler** [comment]
I'm unable to reproduce this. Can you post your job definition (xml) with the error?

**Comment by kureus** [comment]
Simple test case to reproduce the issue I was talking about.

<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='domain' value='mydomain.com' />
      </options>
    </context>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>198f2bdf-fd17-4435-9eb3-919a6e52a66d</id>
    <loglevel>INFO</loglevel>
    <name>Token expansion test</name>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <script><![CDATA[echo 'hello@@option.domain@']]></script>
        <scriptargs />
      </command>
    </sequence>
    <uuid>198f2bdf-fd17-4435-9eb3-919a6e52a66d</uuid>
  </job>
</joblist>

I would expect this to write out hello@mydomain.com but instead writes out hellooption.domain@
Ran on Rundeck 2.6.9-1 cafe bonbon indigo tower 2016-08-03

**Comment by gschueler** [comment]
thanks for the test case

**Comment by kureus** [comment]
@gschueler Any further news on this?

**Comment by kureus** [comment]
Fantastic @gschueler. Many thanks

**Comment by schast** [comment]
Hi,

have big problems with this change.
i have inline script perl code with functions like this:
```
sub perlFunction {
    ...
    return \@files;
}
```

the script would now be generated without the backslash:
```
sub perlFunction {
    ...
    return @files;
}
```

i have tried to escape with:
```
rundeck inline script: \\@files
generated file: \\@files;

rundeck inline script: \\\@files
generated file: \\@files;
```

Please reopen this Ticket.

**Comment by gschueler** [comment]
@schast i will open a new ticket.  would you prefer a way to disable it completely?

**Comment by gschueler** [comment]
@schast https://github.com/rundeck/rundeck/issues/2185
