### ISSUE TITLE
command output is in debug mode

### ISSUE THREAD

**Issue by EmilVarona** [rundeck/rundeck#2032]
Hi, We're running RD v2.6.8. When we issue command from https://rundeck/project/1/command/run UI, all output is in debug mode. This is tedious especially when you are trying to get a simple output from a large number of hosts. As there doesn't seem to be an obvious way to disable debug output, can terse output be set as the default somehow?

**Comment by grzechog** [comment]
In your _rundeck-config.properties_ file change the log level to INFO.

loglevel.default=INFO

**Comment by opawina** [comment]
Hi!
Should I restart service after changing rundeck-config.properties.
Thanks!

**Comment by yeswanth5009** [comment]
Yes
