### ISSUE TITLE
Broken link on the description of the cron settings.

### ISSUE THREAD

**Issue by azalio** [rundeck/rundeck#2033]
Hello!

![2016-08-28_18-54-48](https://cloud.githubusercontent.com/assets/1963324/18034879/a1117196-6d59-11e6-8baa-a116101509af.png)

http://www.quartz-scheduler.org/docs/tutorials/crontrigger.html - is broken.

**Comment by mathieuchateau** [comment]
+1

**Comment by gschueler** [comment]
this issue is out of date, the link was fixed in 2.6.9
 75c2b0e2b6dcffa65be0acf2351058ac43031402
