### ISSUE TITLE
Edit user profile form API

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#2035]
It could be interesting to have the option to update the user profile  (First Name, Last Name, and Email ) using the API.

For example, for this user case:
- rundeck use Active Directory to authenticate.
- the Git Export is enable, and the Committer Name/Email is set to ${user.fullName}/ ${user.email}

Then, it is needed to update manually the fullname and email of the user profile in order to avoid an error with Git Export plugin.

So, having the option to upgrade the profile with an API option, it is possible to build a custom plugin/script to get the user information from the AD and update the user profile automatically.

Thanks

**Comment by airbornemist6** [comment]
Definitely need this. We've been trying to find a solution for this too.

**Comment by ahonor** [comment]
This was added in 2.9
