### ISSUE TITLE
using Job References, ${DATE} only gets expanded as option value in the top job.

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#2039]
Using the default value ${DATE} doesn't work when the job is part of a Job References. 
It just works on the "father" Job, but it is not expanded on the job references.

The short term workaround is passing the top level option to job reference.

Example:

![screenshot from 2016-08-31 18-19-48](https://cloud.githubusercontent.com/assets/6034968/18146869/5c4dcb8a-6fa8-11e6-8c13-e9d611f606bb.png)

![screenshot from 2016-08-31 18-21-24](https://cloud.githubusercontent.com/assets/6034968/18146878/6daf1384-6fa8-11e6-94f9-8ad51d2b20a0.png)

![screenshot from 2016-08-31 18-25-26](https://cloud.githubusercontent.com/assets/6034968/18146870/60ba658e-6fa8-11e6-973c-84ce451d2b57.png)

**Comment by gschueler** [comment]
Question: the `${DATE}` is expanded with the execution's "dateStarted" timestamp.  However the Job reference may not execute until later... Should the job reference's `${DATE}` be the same as the "dateStarted" for the execution, or the exact time that the Job reference executes?
