### ISSUE TITLE
Plugin Cache Directory Space Leak

### ISSUE THREAD

**Issue by jwestc01** [rundeck/rundeck#2041]
I'm having an issue where my RunDeck RHEL server is running out of space in var. A 'df -k’ on the volume is showing 100% full but a 'du -sh' is not finding any files which may be contributing to the issue. To find the files that are taking space we had to use the  ‘lsof -nP' command which is showing a lot of deleted files that are still in use (in the RunDeck plugin cache directory).

> ```
>    /var/log/rundeck$ sudo lsof -nP | grep '(deleted)'
>    java  2255  rundeck  206r  REG  253,3  2012214  132860 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/org.eclipse.jgit-3.7.1.201504261725-r.jar (deleted)
>    java  2255  rundeck  219r  REG  253,3  2012214  133899 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/org.eclipse.jgit-3.7.1.201504261725-r.jar (deleted)
>    java  2255  rundeck  229r  REG  253,3  2012214  134223 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/org.eclipse.jgit-3.7.1.201504261725-r.jar (deleted)
>    java  2255  rundeck  207r  REG  253,3   125146  132866 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/JavaEWAH-0.7.9.jar (deleted)
>    java  2255  rundeck  220r  REG  253,3   125146  134004 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/JavaEWAH-0.7.9.jar (deleted)
>    java  2255  rundeck  237r  REG  253,3   125146  134226 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/JavaEWAH-0.7.9.jar (deleted)
>    java  2255  rundeck  208r  REG  253,3   352585  132867 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/httpclient-4.1.3.jar (deleted)
>    java  2255  rundeck  222r  REG  253,3   352585  134066 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/httpclient-4.1.3.jar (deleted)
>    java  2255  rundeck  242r  REG  253,3   352585  134227 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/httpclient-4.1.3.jar (deleted)
>    java  2255  rundeck  209r  REG  253,3   181410  132874 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/httpcore-4.1.4.jar (deleted)
>    java  2255  rundeck  244r  REG  253,3   181410  134228 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/httpcore-4.1.4.jar (deleted)
>    java  2255  rundeck  223r  REG  253,3   181410  134067 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/httpcore-4.1.4.jar (deleted)
>    java  2255  rundeck  210r  REG  253,3    58160  132875 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/commons-codec-1.4.jar (deleted)
>    java  2255  rundeck  246r  REG  253,3    58160  134230 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/commons-codec-1.4.jar (deleted)
>    java  2255  rundeck  224r  REG  253,3    58160  134145 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/commons-codec-1.4.jar (deleted)
>    java  2255  rundeck  251r  REG  253,3    86884  134504 /var/lib/rundeck/var/tmp/pluginJars/20160419112037000-Utils-plugin-node-registration.jar (deleted)
>    java  2255  rundeck  234r  REG  253,3    86884  134212 /var/lib/rundeck/var/tmp/pluginJars/20160419112037000-Utils-plugin-node-registration.jar (deleted)
>    java  2255  rundeck  217r  REG  253,3    86884  134211 /var/lib/rundeck/var/tmp/pluginJars/20160419112037000-Utils-plugin-node-registration.jar (deleted)
>    java  2255  rundeck  252r  REG  253,3     9527  135528 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-orchestrator-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  235r  REG  253,3     9527  134215 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-orchestrator-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  218r  REG  253,3     9527  134214 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-orchestrator-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  225r  REG  253,3    11030  133605 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-stub-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  211r  REG  253,3    11030  132777 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-stub-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  213r  REG  253,3    11030  132881 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-stub-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  202r  REG  253,3    11030  132776 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-stub-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  227r  REG  253,3    16139  133608 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-script-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  203r  REG  253,3    16139  132778 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-script-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  214r  REG  253,3    16139  132779 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-script-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  228r  REG  253,3  2763171  134146 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-git-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  216r  REG  253,3  2763171  132880 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-git-plugin-2.6.7.jar (deleted)
>    java  2255  rundeck  205r  REG  253,3  2763171  132856 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-git-plugin-2.6.7.jar (deleted)
> ```

I see in the code of com.dtolabs.rundeck.core.plugins.JarPluginScanner, when its instantiated, it deletes the cache directories if they exist:

> ```
>    if (pluginJarCacheDirectory.exists() && !FileUtils.deleteDir(pluginJarCacheDirectory)) {
>        log.warn("Could not delete plugin jar cache");
>    }
>    log.info(String.format("Deleting plugin lib dependency directory at %s", this.cachedir));
>    if (this.cachedir.exists() && !FileUtils.deleteDir(this.cachedir)) {
>        log.warn("Could not delete plugin lib dependency directory");
>    }
> 
>    // Create the directories
>    this.cachedir.mkdirs();
>    this.pluginJarCacheDirectory.mkdirs();
> ```

With the logs set to trace I do see multiple messages indicating that RD is deleting the cache directories:

> ```
>    sudo grep "JarPluginScanner: Deleting plugin" service.log*
>    service.log:INFO  JarPluginScanner: Deleting plugin jar cache at /var/lib/rundeck/var/tmp/pluginJars
>    service.log:INFO  JarPluginScanner: Deleting plugin lib dependency directory at /var/lib/rundeck/libext/cache
>    service.log:INFO  JarPluginScanner: Deleting plugin jar cache at /var/lib/rundeck/var/tmp/pluginJars
>    service.log:INFO  JarPluginScanner: Deleting plugin lib dependency directory at /var/lib/rundeck/libext/cache
>    service.log:INFO  JarPluginScanner: Deleting plugin jar cache at /var/lib/rundeck/var/tmp/pluginJars
>    service.log:INFO  JarPluginScanner: Deleting plugin lib dependency directory at /var/lib/rundeck/libext/cache
>    service.log:INFO  JarPluginScanner: Deleting plugin jar cache at /var/lib/rundeck/var/tmp/pluginJars
>    service.log:INFO  JarPluginScanner: Deleting plugin lib dependency directory at /var/lib/rundeck/libext/cache
>    service.log:INFO  JarPluginScanner: Deleting plugin jar cache at /var/lib/rundeck/var/tmp/pluginJars
>    service.log:INFO  JarPluginScanner: Deleting plugin lib dependency directory at /var/lib/rundeck/libext/cache
>    service.log:INFO  JarPluginScanner: Deleting plugin jar cache at /var/lib/rundeck/var/tmp/pluginJars
>    service.log:INFO  JarPluginScanner: Deleting plugin lib dependency directory at /var/lib/rundeck/libext/cache
>    service.log:INFO  JarPluginScanner: Deleting plugin jar cache at /var/lib/rundeck/var/tmp/pluginJars
>    service.log:INFO  JarPluginScanner: Deleting plugin lib dependency directory at /var/lib/rundeck/libext/cache
>    service.log:INFO  JarPluginScanner: Deleting plugin jar cache at /var/lib/rundeck/var/tmp/pluginJars
>    service.log:INFO  JarPluginScanner: Deleting plugin lib dependency directory at /var/lib/rundeck/libext/cache
> ```

What I think is happening is that the PluginScanner is being instantiated multiple times. When a new one is built it deletes the directories but the old scanners are still holding the files opened in the deleted directories. So a df on the filesystem does not show the space being used but the files are on disk taking up space until the java process is terminated and the file system finally frees them. The longer RD is running and the more people are clicking around in the UI the more of these deleted files we get. From my testing so far I have not been able to generate a reliable way to replicate the issue. However, most of our activity at this point is around jobs;  editing and executing. 

In addition, I have not been able to pin point what in the code might be instantiating multiple scanners. A quick code search appears to indicate that there are two possible places of instantiation (I say possible because I'm not familiar with how groovy works so I can't say its instantiated there for certain):

> ```
>    rundeck/rundeckapp/grails-app/conf/spring/resources.groovy
>    rundeck/core/src/main/java/com/dtolabs/rundeck/core/plugins/PluginManagerService.java
> ```

Here is the info on my RD, OS and JVM versions:

> ```
>    /opt/rundeck/jvm/bin/java -version && more /etc/redhat-release && uname -a
>    java version "1.8.0_77"
>    Java(TM) SE Runtime Environment (build 1.8.0_77-b03)
>    Java HotSpot(TM) 64-Bit Server VM (build 25.77-b03, mixed mode)
>    Red Hat Enterprise Linux Server release 6.6 (Santiago)
>    Linux <hostname> 2.6.32-504.30.3.el6.x86_64 #1 SMP Thu Jul 9 15:20:47 EDT 2015 x86_64 x86_64 x86_64 GNU/Linux
>    Rundeck © Copyright 2016 #SimplifyOps. All rights reserved. Licenses 2.6.7-1 cafe bonbon goldenrod plane
> ```

Please let me know if there is any other information you need from me. Later this week I will be trying 2.6.9 GA to see if the issue persists there. In addition, if I am able to produce a consistent way to replicate the issue I will update this report.

**Comment by gschueler** [comment]
some fixes went into 2.6.9 that change the way plugins are loaded, please try that version at let me know if the issue persists

**Comment by jwestc01** [comment]
Initial tests in 2.6.9 seem to work. Next week I will promote it to my production and let you know the results.

**Comment by jwestc01** [comment]
After running the server for longer, we are still seeing duplicated local files:

> sudo lsof -nP | grep '(deleted)' | grep rundeck
> java      20746   rundeck  178u      REG              253,2         0     131078 /tmp/rundeck/org.hibernate.cache.spi.UpdateTimestampsCache.data (deleted)
> java      20746   rundeck  182u      REG              253,2         0     131082 /tmp/rundeck/org.hibernate.cache.internal.StandardQueryCache.data (deleted)
> java      20746   rundeck  201r      REG              253,6     16139    2359316 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-script-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  211r      REG              253,6 101450523    2359322 /var/lib/rundeck/var/tmp/pluginJars/20160526081626000-MMUtils-plugin-was.jar (deleted)
> java      20746   rundeck  212r      REG              253,6  53609960    1703949 /var/lib/rundeck/libext/cache/MMUtils-plugin-was/lib/com.ibm.ws.admin.client_8.5.0.jar (deleted)
> java      20746   rundeck  213r      REG              253,6  45291200    1703950 /var/lib/rundeck/libext/cache/MMUtils-plugin-was/lib/com.ibm.jaxws.thinclient_8.5.0.jar (deleted)
> java      20746   rundeck  215r      REG              253,6   2423205    1703951 /var/lib/rundeck/libext/cache/MMUtils-plugin-was/lib/com.ibm.ws.orb_8.5.0.jar (deleted)
> java      20746   rundeck  231r      REG              253,6     16139    2359376 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-script-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  237r      REG              253,6     16139    2359382 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-script-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  238r      REG              253,6   2763171    2359326 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-git-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  239r      REG              253,6   2012214    1703973 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/org.eclipse.jgit-3.7.1.201504261725-r.jar (deleted)
> java      20746   rundeck  240r      REG              253,6    125146    1703974 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/JavaEWAH-0.7.9.jar (deleted)
> java      20746   rundeck  241r      REG              253,6    352585    1703975 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/httpclient-4.1.3.jar (deleted)
> java      20746   rundeck  242r      REG              253,6    181410    1703976 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/httpcore-4.1.4.jar (deleted)
> java      20746   rundeck  243r      REG              253,6     58160    1703977 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/commons-codec-1.4.jar (deleted)
> java      20746   rundeck  244r      REG              253,6     11030    2359328 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-stub-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  245r      REG              253,6      9527    2359330 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-orchestrator-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  247r      REG              253,6     86884    2359332 /var/lib/rundeck/var/tmp/pluginJars/20160526081626000-MMUtils-plugin-node-registration.jar (deleted)
> java      20746   rundeck  273r      REG              253,6     16139    2359394 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-script-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  291r      REG              253,6     16139    2359400 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-script-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  302r      REG              253,6     16139    2359406 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-script-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  372r      REG              253,6     11030    2359379 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-stub-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  386r      REG              253,6     11030    2359385 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-stub-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  388r      REG              253,6     86884    2359387 /var/lib/rundeck/var/tmp/pluginJars/20160526081626000-MMUtils-plugin-node-registration.jar (deleted)
> java      20746   rundeck  389r      REG              253,6 101450523    2359407 /var/lib/rundeck/var/tmp/pluginJars/20160526081626000-MMUtils-plugin-was.jar (deleted)
> java      20746   rundeck  390r      REG              253,6  53609960    1704124 /var/lib/rundeck/libext/cache/MMUtils-plugin-was/lib/com.ibm.ws.admin.client_8.5.0.jar (deleted)
> java      20746   rundeck  391r      REG              253,6  45291200    1704125 /var/lib/rundeck/libext/cache/MMUtils-plugin-was/lib/com.ibm.jaxws.thinclient_8.5.0.jar (deleted)
> java      20746   rundeck  392r      REG              253,6   2423205    1704133 /var/lib/rundeck/libext/cache/MMUtils-plugin-was/lib/com.ibm.ws.orb_8.5.0.jar (deleted)
> java      20746   rundeck  414r      REG              253,6     11030    2359397 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-stub-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  428r      REG              253,6     11030    2359403 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-stub-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  435r      REG              253,6   2763171    2359408 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-git-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  436r      REG              253,6   2012214    1704176 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/org.eclipse.jgit-3.7.1.201504261725-r.jar (deleted)
> java      20746   rundeck  437r      REG              253,6    125146    1704177 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/JavaEWAH-0.7.9.jar (deleted)
> java      20746   rundeck  438r      REG              253,6    352585    1704178 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/httpclient-4.1.3.jar (deleted)
> java      20746   rundeck  439r      REG              253,6    181410    1704179 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/httpcore-4.1.4.jar (deleted)
> java      20746   rundeck  440r      REG              253,6     58160    1704180 /var/lib/rundeck/libext/cache/rundeck-git-plugin-2.6.7/lib/commons-codec-1.4.jar (deleted)
> java      20746   rundeck  441r      REG              253,6     11030    2359409 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-stub-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  442r      REG              253,6      9527    2359410 /var/lib/rundeck/var/tmp/pluginJars/20160429184235000-rundeck-orchestrator-plugin-2.6.7.jar (deleted)
> java      20746   rundeck  444r      REG              253,6     86884    2359411 /var/lib/rundeck/var/tmp/pluginJars/20160526081626000-MMUtils-plugin-node-registration.jar (deleted)
> 
>

**Comment by gschueler** [comment]
please reopen if still valid
