### ISSUE TITLE
freemarker template error

### ISSUE THREAD

**Issue by avinchakov** [rundeck/rundeck#2046]
Rundeck 2.6.9
Yesterday suddenly started errors:

> Sep  1 19:15:01 FreeMarker template error:
> Sep  1 19:15:01 The following has evaluated to null or missing:
> Sep  1 19:15:01 ==> executionData.failedNodeListString  [in template "slack-incoming-message.ftl" at line 39, column 27]
> Sep  1 19:15:01 Tip: If the failing expression is known to be legally null/missing, either specify a default value with myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthessis: (myOptionVar.foo)!myDefault, (myOptionVar.foo)??
> Sep  1 19:15:01 The failing instruction (FTL stack trace):
> Sep  1 19:15:01 ==> ${executionData.failedNodeListString}  [in template "slack-incoming-message.ftl" at line 39, column 25]
> Sep  1 19:15:01 Java stack trace (for programmers):
> Sep  1 19:15:01 freemarker.core.InvalidReferenceException: [... Exception message was already printed; see it above ...]

After that:

> Sep  1 19:20:01 [quartzScheduler_Worker-13] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - The table 'workflow_step' is full
> Sep  1 19:20:01 [quartzScheduler_Worker-13] ERROR org.quartz.core.JobRunShell - Job PS:RuruCronProcess:ps.xsolla.com.220:RuruCronProcess threw an unhandled Exception: 
> Sep  1 19:20:01 org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not execute statement; uncategorized SQLException for SQL [n/a]; SQL state [HY000]; error code [1114]; The table 'workflow_step' is full; nested exception is java.sql.SQLException: The table 'workflow_step' is full

As a result of three hours jobs didn't work((((
Help to find the reason please

**Comment by ahonor** [comment]
Please reopen if this remains a concern
