### ISSUE TITLE
Commands tab - no output

### ISSUE THREAD

**Issue by JesusRoNGAHR** [rundeck/rundeck#2047]
Now, running commands across several nodes, don't give any output except errors.
I.E.: I run 'date' across 10 nodes, the only output is one of the node which is down.
I've checked that the OUTPUTFILEPATH has the same info, it seems the output from the commands exectued where not stored.
I did the same but via a job and it's working fine, so the issue is only with "Commands".
I don't know when this started to failed on my installation... and I didn't see other errors.
How can I check this deeper?

**Comment by JesusRoNGAHR** [comment]
Some screenshots about the issue

![no_output2](https://cloud.githubusercontent.com/assets/19263238/18243633/39ab4e56-735c-11e6-89d9-4d0f8cb75de9.png)
![no_output1](https://cloud.githubusercontent.com/assets/19263238/18243634/39fa1856-735c-11e6-84d2-ad92b6adbba3.png)

**Comment by atlhon** [comment]
+1, same problem here
how do you upgrade rundeck?

**Comment by JesusRoNGAHR** [comment]
Hi

I usually stop rundeck, change the soft link from rundeck-launcherXXXXX.jar to the new one and start again, is this a wrong way?

Anyhow, I managed to get my output. I set this on rundeck-config.properties
loglevel.default=INFO

I was at ERROR before.

Is this correct? Do I need INFO level to get adhoc commands output?

**Comment by ahonor** [comment]
Can't reproduce in 2.10

**Comment by kdebisschop** [comment]
In 3.3.10, I also needed to change loglevel.default in server/config/rundeck-config.properties from WARN to INFO.

When I did a clean reinstall, the value was INFO - maybe it changed at some point?
