### ISSUE TITLE
How to execute a job from another job's inline script ?

### ISSUE THREAD

**Issue by flopma** [rundeck/rundeck#2048]
Hello,

I need to call a job B from job A in inline script ?

Is this feasable in Rundeck 2.6.2 ?

Thx,
--
Issa

**Comment by airbornemist6** [comment]
If you just need to call a job in the same project, use the job step plugin. If you need to call a job in another project, you'll want to use the API to do it via curl. http://rundeck.org/2.6.9/api/index.html#running-a-job

**Comment by flopma** [comment]
I guess it will be the curl way because I have some dynamic parameters (that job A reads from a file) I need to send to job B and the job step plugin does not allow that to my knowledge.
