### ISSUE TITLE
Not all groups pulled in by LDAP

### ISSUE THREAD

**Issue by alexray92** [rundeck/rundeck#2049]
I'm running on 2.6.9-1, and have confirmed with another user on IRC that it isn't just me - in my case, I have LDAP authentication working against Active Directory and am able to sign in.  However, on the profile page (and in the logs), only 9 of 22 (the other user said 5 of 7) are shown.  In my case, it is always the same set of groups, but in a different order.  The remaining 13 groups never shown up.  This is also persistent across restarting rundeckd.

This could be a problem with things like ACLs that depend on AD groups.

**Comment by gschueler** [comment]
are the groups in sub-groups?  what does your jaas ldap config look like?

**Comment by alexray92** [comment]
Nope, no sub groups at all.  My jaas-ad.conf file looks like this:

`ldap {
        com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
        debug="true"
        contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
        providerUrl="ldaps://dc01.xxxxxxx:636"
        bindDn="CN=rundeck auth,OU=xxxxx,..."
        bindPassword="secret"
        authenticationMethod="simple"
        forceBindingLogin="true"
        userBaseDn="..."
        userRdnAttribute="sAMAccountName"
        userIdAttribute="sAMAccountName"
        userPasswordAttribute="unicodePwd"
        userObjectClass="user"
        roleBaseDn="..."
        roleNameAttribute="cn"
        roleMemberAttribute="member"
        roleObjectClass="group"
        cacheDurationMillis="300000"
        reportStatistics="true"
        supplementalRoles="users"
        storePass="true";
        org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
        debug="true"
        useFirstPass="true"
        file="/etc/rundeck/realm.properties";
};
`

And my profile is like this:

`export RDECK_JVM="-Djava.security.auth.login.config=/etc/rundeck/jaas-ad.conf \
        -Dloginmodule.name=ldap \`

**Comment by gschueler** [comment]
can you try adding this to RDECK_JVM: `-Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG`

**Comment by gschueler** [comment]
then restart the server, and it should show additional debug output for ldap

**Comment by alexray92** [comment]
Done.  From the rundeck audit log:

`2016-09-02 12:17:41,199 - Evaluating Decision for: res<name:DatabaseOperations, type:project> subject<Username:alex... Group:1 Group:2 Group:3...Group:9> action<configure> env<http://dtolabs.com/rundeck/env/application:rundeck>: authorized: true: GRANTED, reason: GRANTED, evaluations:    ACLRule</etc/rundeck/admin.aclpolicy[2][type:project][rule: 1]>{'Admin, all access.' context={application='rundeck'} type='project' for: { group='1'} allow=[*]} GRANTED for action configure => GRANTED (1ms)`

From the service log:

`2016-09-02 12:17:35.763:INFO:cdrjj.JettyCachingLdapLoginModule:Login attempts: 1, Hits: 0, Ratio: 0%.
2016-09-02 12:17:35.765:DBUG:cdrjj.JettyCachingLdapLoginModule:Cache Miss for alex....
2016-09-02 12:17:35.766:DBUG:cdrjj.JettyCachingLdapLoginModule:Searching for users with filter: '(&(objectClass={0})({1}={2}))' from base dn: OU=...
2016-09-02 12:17:35.801:DBUG:cdrjj.JettyCachingLdapLoginModule:Found user?: true
2016-09-02 12:17:35.802:INFO:cdrjj.JettyCachingLdapLoginModule:Attempting authentication: CN=...,OU=...
2016-09-02 12:17:36.092:DBUG:cdrjj.JettyCachingLdapLoginModule:JettyCachingLdapLoginModule: User 'alex...' has roles: [Group 1, Group 2...Group 9]
2016-09-02 12:17:36.093:DBUG:cdrjj.JettyCachingLdapLoginModule:Adding alex... set to expire: 1472843856093300000
`

**Comment by gschueler** [comment]
did you try adding `nestedGroups="true"` to your jaas config? If that doesn't help, it sounds like there must be something different about those groups that are missing. Since you are doing a binding login, it might be possible that the binding user is not authorized to search/query for those groups.  In that case you can try `forceBindingLoginUseRootContextForRoles="true"` in your config, which forces the roles query to be done with the root bind context

**Comment by alexray92** [comment]
I tried both before I realized I was overlooking something - roleBaseDn was set one OU too deep, that was the problem.  PEBKAC
