### ISSUE TITLE
Rundeck 2.6.9-1 is not fully translated to Spanish

### ISSUE THREAD

**Issue by lfacchinelli** [rundeck/rundeck#2058]
Hi all

Today i updated my Rundeck instance to 2.6.9-1 and i realize through my profile that i can set language from English to Spanish .

After that i realized some text are translated to spanish and some aren't translated

So, as a native speaker of Spanish, I can help doing that translate-related work .

I didn't want to start working without open this issue to see what the community thinks about and also set an issue to let everyone who want to translate to spanish be able to comment.

Regards

Luciano

**Comment by JesusRoNGAHR** [comment]
Hi Luciano,

Take a look here to see how to help on translations
https://github.com/rundeck/rundeck/wiki/Internationalization

And here for the current es labels
https://github.com/rundeck/rundeck/blob/development/rundeckapp/grails-app/i18n/messages_es_419.properties

Kr.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
