### ISSUE TITLE
There is no way to run jobs on autoscaled instances without unique names. 

### ISSUE THREAD

**Issue by juliangamble** [rundeck/rundeck#2059]
Hopefully I'm wrong, but it seems that there is no way to run jobs on autoscaled AWS instances without unique names. 

JG

**Comment by gschueler** [comment]
@juliangamble this is a limitation of the ec2 plugin, see https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/issues/10

**Comment by ahonor** [comment]
Closing here as this is an issue with the ec2-nodes plugin
