### ISSUE TITLE
Error "Entry not found by path:" when committing to git scm with hyphen in folder name

### ISSUE THREAD

**Issue by atheiman** [rundeck/rundeck#2060]
If I have a job in a directory with a `-` in the name (i.e. `my-folder/myjob`) the git commit will fail with a `Entry not found by path:` error.

This is on `Rundeck 2.6.9-1 cafe bonbon indigo tower 2016-08-03`

**Comment by gschueler** [comment]
I can't reproduce this error.  are you only using the export plugin? or both export and import?

can you reproduce it in a new project?  can you send the job that is causing the error?

**Comment by adamsd1019** [comment]
I'm having this issue as well, except I used the pipe (|) symbol in my job name and got the same error as reported.
