### ISSUE TITLE
Secret options with default values are unset in retries

### ISSUE THREAD

**Issue by andresvia** [rundeck/rundeck#2066]
Running 2.6.2-1 cafe bonbon crimson headphones here.

When a job fails and a retry is triggered, the secret options in the form of $RD_OPTION_\* are unset on the retry execution.

**Comment by gschueler** [comment]
have you tried with a newer release?

**Comment by andresvia** [comment]
I'm not able to reproduce on rundeck-launcher-2.6.9.jar. I'll consider upgrade. Thanks a lot.
