### ISSUE TITLE
Rundeck Job running multiple times

### ISSUE THREAD

**Issue by bhanda01** [rundeck/rundeck#2067]
I have configured one job named (RPRDE1-DA-MP1.0-Action through( log moving and housekeeping)) which is scheduled to start at 5:00 AM CST and should perform server restart and cleanup in 18 servers.
![rundeck1](https://cloud.githubusercontent.com/assets/22148268/18434796/e2630c04-790c-11e6-9e2c-583b507852fc.png)

Initially it was running fine, once per day. After I changed the working days from whole week(Monday-sunday) to only weekdays(Monday-friday) the job started to run twice at 5:00AM, I changed the days back to whole week(Monday-sunday) plus some minor changes, now it's creating three instances at 5:00AM.
![image](https://cloud.githubusercontent.com/assets/22148268/18434909/b47f982e-790d-11e6-94d4-7a50ff8cc420.png)
#3333, #3329 and #3331 are the three instances, all triggered at 5:00 AM(The timings in pic are in IST)

Anyone have any idea what is causing this issue?, as currently rundeck is creating three process on each node for the same script.

**Comment by gschueler** [comment]
what version of Rundeck?

Have you tried turning off the schedule completely and re-enabling it?

**Comment by bhanda01** [comment]
Version 2.6.7 . I tried turning off the schedule completely, also I changed the nodes count from 18 to 1(as it was effecting the servers) and re-enabled it, today the job ran twice.

**Comment by gschueler** [comment]
do you have multiple rundeck instances?

**Comment by bhanda01** [comment]
Yes, we have three different instances.

**Comment by gschueler** [comment]
I you have multiple rundeck instances pointing to the same RDB, you should have clustermode enabled. if not, then scheduling is likely to get messed up. clustermode assigns job schedules to only a particular node of the cluster

**Comment by bhanda01** [comment]
I went to the rundeck-config.properties file of the three instance and added "rundeck.clusterMode.enabled=true" to the property file(Note: rundeck.clusterMode.enabled was missing earlier).
Still the job created 2 instances(even though currently the job scheduling is disabled).
Since yesterday I am facing another issue:
The triggered jobs are now not executing it's functionality, they are in hung state with msg "Waiting for execution to start...", even when I try to kill the jobs, I am getting below error:
![image](https://cloud.githubusercontent.com/assets/22148268/18546308/f00579fa-7b5a-11e6-8db0-32488efc7c41.png)

**Comment by gschueler** [comment]
you will also need to assign a unique UUID to each cluster instance in `framework.properties`:

    rundeck.server.uuid=306A9F91-4E3D-465D-9392-6133E9D85269

generate a new uuid (e.g. use `uuidgen` command) and set for each instance.  When starting up the server should log `Cluster mode enabled, this server's UUID: ...`, and in the GUI it will indicate the unique id in the page footer

**Comment by bhanda01** [comment]
I performed the mentioned changes in framework.properties(added UUID) and  enabled clustermode in rundeck-config.properties but the issue reoccurred,

First below is how we have configured rundeck in three Linux flavored servers:
We are using three servers with apache-tomcat-7.0.69.
for all three we have rundeck-config.properties file in which we enabled clustermode:
rundeck.clusterMode.enabled=true

For framework.properties file we have a shared directory "etc" i.e. all the three servers are using the same "framework.properties" file. I added the UUIDs of three servers in framework.properties file followed by a restart for all three servers.
#Server UUID
rundeck.server.uuid=9a6b9a70-a18e-4c80-8b6a-95c35f2f0794
rundeck.server.uuid=0485db0e-2191-43c4-8938-fbe3e4644a81
rundeck.server.uuid=299a4bf5-b887-4b9b-ad16-fc098c5f6121

Observation post property file changes:
We didn't saw any job duplication or any pre mentioned issues post this, however we did saw that all the jobs were pointing to only one UUID(299a4bf5-b887-4b9b-ad16-fc098c5f6121).

All the jobs worked fine until on 22nd Sep our first rundeck server went down with below error:
Error: Exception thrown by the agent : java.rmi.server.ExportException: Port already in use: 2222; nested exception is:
        java.net.BindException: Address already in use

After this all the scheduling was lost, we kept the first rundeck server down and went to individual jobs, they were retaining the job and scheduling details and once we again saved the config of jobs the scheduling was back.

Few days later when we made the first server live again we saw the jobs were duplicating.
Currently we have kept the first server down and scheduling is working on second server.

###################################################################
**Any idea on what is causing this job duplication and how it can be avoided?**
I think the issue can be related to the fact that framework.properties file is shared between all three servers.

**Comment by ahonor** [comment]
@bhanda01 each instance must have its own framework.properties

**Comment by ahonor** [comment]
Please reopen if this remains a concern
