### ISSUE TITLE
local-node-executor=script-exec double rm temp file, prevents killing process

### ISSUE THREAD

**Issue by hjdr4** [rundeck/rundeck#2070]
At the moment : Rundeck 2.6.9-1 

I have changed the default local executor because inline scripts are invoked "sh -c" style and cannot be killed(...).

So I have setup :
`local-node-executor="script-exec" script-exec-shell="bash -c" script-exec="exec ${exec.command}"`

Now my inline scripts are directly running under Rundeck, so no more "sh -c" stuff, I'm happy until...
When I kill a script, I get 
`Failed to remove remote file: /tmp/15-291669-rundeck-dispatch-script.tmp.sh`
error and the script does not get killed, probably because of the exception.
The file is considered 'remote' from the log, and I think this is the cause of double rm issue.

My system audit logs indicate a single rm command issued, so maybe I'm wrong about double rm.
`type=EXECVE msg=audit(1473769358.955:15683246): argc=3 a0="chmod" a1="+x" a2="/tmp/15-291669-rundeck-dispatch-script.tmp.sh"
type=EXECVE msg=audit(1473769358.963:15683250): argc=3 a0="/usr/bin/python" a1="-u" a2="/tmp/15-291669-rundeck-dispatch-script.tmp.sh"
type=PATH msg=audit(1473769358.963:15683250): item=0 name="/tmp/15-291669-rundeck-dispatch-script.tmp.sh" inode=536752 dev=fe:00 mode=0100775 ouid=110 ogid=118 rdev=00:00 nametype=NORMAL
type=EXECVE msg=audit(1473769367.951:15683466): argc=3 a0="rm" a1="-f" a2="/tmp/15-291669-rundeck-dispatch-script.tmp.sh"
`

**Comment by hjdr4** [comment]
Upgraded to last version, I don't have the problem.
Probably thanks to https://github.com/rundeck/rundeck/issues/1947

**Comment by ahonor** [comment]
Please reopen if this remains a concern
