### ISSUE TITLE
How can I change timezone of rundeck

### ISSUE THREAD

**Issue by koolay** [rundeck/rundeck#2072]

**Comment by airbornemist6** [comment]
Rundeck should be using the timezone of the server it's running on.

**Comment by koolay** [comment]
@wilrodriguez 
Actually, it 's  not.

**Comment by wilrodriguez** [comment]
@koolay Whoops, you're right. Found it, try greg's instructions here: https://groups.google.com/forum/#!topic/rundeck-discuss/_NUBNfuS9tM

**Comment by koolay** [comment]
@gschueler

**Comment by koolay** [comment]
@wilrodriguez 

It works.
export JAVA_OPTIONS="-Duser.timezone=<timezone>"
