### ISSUE TITLE
Run on failed nodes doesn't work on more complex workflow 

### ISSUE THREAD

**Issue by pgressa** [rundeck/rundeck#2074]
# Bug report

**My Rundeck detail**
- Rundeck version: 2.6.9-1
- install type: war
- OS Name/version: CentOs 7.2

**Expected Behavior**

Let's have a job called: master-job with these specifics:
- node filter that matches 100 nodes. 
- and jobref steps (setup as workflow) that contains node filters: job_a (60 nodes); job_b (20 nodes); job_c (20 nodes)

When I run master-job, I expect that job_a will be executed on nodes that are intersection of these two sets (master-job nodes and job_a nodes). 

This is a big pain point when you have more complex workflow then a few simple commands, but composed from jobrefs, which works with actually large set of nodes but in separated way (like it's described above). Once you run such workflow against ~500 nodes, and 20 of them fails (10 in one job, 5 in another, ... ).. then feature Run failed node could save a lot of time (instead of investigating what jobs that are referenced in jobref to restart with what nodes).

**Actual Behavior**

No matter on how many jobs the master-job failed, the Run on failed nodes will run whole procedure.

**How to reproduce Behavior**
Described above in expected behaviour.

**Comment by pgressa** [comment]
Hi @gschueler,

I would like to fix this issue, because I don't really know when this will came up to road map. What I need is to kind of verification with you about the right place where to fix this and how. 

First of all I think both cases are valid:
- I have a jobref where targed nodes are intersect of a jobref node filter (or referenced job node list) and main job node filter (that's where the 'Run on failed nodes' or 'Change nodes' doesn't work)
- I have a jobref which is always executed with on nodes selected by node filter (we have such workflows where we use this approach)

So we speak more about feature then bug right now. But I need to show direction a little bit to ease the realisation. So this must be done right?
- Add new option to jobref step, whether target nodes should be intersection or it's static
- Add evaluation of target nodes somewhere here https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy#L2761 where context for jobref is being prepared

Is my understanding of this problem right? Thanks!

**Comment by gschueler** [comment]
@pgressa yes i think you have the right idea.  You would have to filter the nodes twice to get the subset, e.g using `NodeFilter.filterNodes(selector, prefiltered)`
