### ISSUE TITLE
Serious bug with the job scheduler

### ISSUE THREAD

**Issue by ricsipontaz** [rundeck/rundeck#2076]
# Bug report

**My Rundeck detail**
- Rundeck version: Rundeck 2.6.9-1
- install type:rpm
- OS Name/version: CentOS 7 64bit

**Expected Behavior**

Duplicate a previous job with crontab schedule. Edit the job, change from a Crontab schedule to a Simple one, and it works with the new values.

**Actual Behavior**

Previous Crontab definition overrides the Day of the Week field with the Simple scheduler

**How to reproduce Behavior**

Duplicate (don't create a new one) a job with similar schedule: 
0 35 \* ? \* \* *

Change the schedule to the following, use the SIMPLE scheduler:
10:40 on Monday and Tuesday

Under Definition there's the following schedule:
at 10 : 45 every day

it looks like the previous "*" wild-card definition overrides the selected days.
...

**Comment by gschueler** [comment]
cannot reproduce in 2.6.9 or later
