### ISSUE TITLE
rundeck

### ISSUE THREAD

**Issue by sachinvgaikwad** [rundeck/rundeck#2078]
# Bug report

(Note: Please fill in the blank `___` about your rundeck installation below. You can remove this line.)

**My Rundeck detail**
- Rundeck version: 2.6.9-1___
- install type: _deb__ (rpm,deb,war,launcher)
- OS Name/version: _Ubuntu__

Can we define a job that once it completes, it starts again plz steps to do that

(_For enhancements_: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by ahonor** [comment]
@sachinvgaikwad you can just have a second step which is a jobref call to itself.
