### ISSUE TITLE
Delay between retries

### ISSUE THREAD

**Issue by daveres** [rundeck/rundeck#2083]
# Enhancement request

We want to implement retries in a failed job but in some circumstances, we prefer to wait a period between to retries because it's very likely that the job fails another time if we retry after a fail.

We could create a step to make this functionality but it's better to implement job definition.

The last request is to make the wait time exponential, for example, first time 5 minutes, second 10 minutes, third 15 minutes, etc. until job timeout.

**Comment by truppert** [comment]
This would be awesome.  I also see times where an immediate retry fails, where a retry 10 minutes later would succeed because the thing being run needs a bit of time to reset.

**Comment by apassy** [comment]
This would be great - The failure i get are OFTEN because the data on the systems I'm pulling from isn't ready - but I want to get it as soon as it is.  so an instant retry is useless.

**Comment by ahonor** [comment]
+1
