### ISSUE TITLE
Links to localhost in the Activity tab for the running job

### ISSUE THREAD

**Issue by jinesh-choksi** [rundeck/rundeck#2086]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.9-1
* install type: rpm
* OS Name/version: CentOS 7.x

**Expected Behavior**
- For a running job:
- **EITHER** the "> running" tab is not meant to become active **OR** if it is then the links in the information it generates need to be converted into the proper URL for rundeck.

**Actual Behavior**
- For a running job, in the "Activity" tab, if you click the link for the Job at the top of the page, the "> running" tab becomes active and you can click on it to expand it and see the activity details of the job.
- Clicking on the job id link at this points returns in an error since the URL is: http://localhost:4440/execution/show/JOB_ID

![issue](https://cloud.githubusercontent.com/assets/7047770/18875477/e91b7d6c-84bd-11e6-9d76-7ba9dfc2a00f.png)

**How to reproduce Behavior**
- Use Rundeck to run a job.
- Switch to the "Activity" tab and click on the link for that active job.
- On the page that appears, the "> running" tab in the "Activity for this Job" section is greyed out and you cannot click on it to see activity for this job.
- If you were to now click the link for the job at the top of the page, the "> running" tab becomes active and you can click on it to expand it and see the activity details of the running job.

**Comment by gschueler** [comment]
I'm not quite sure what the error is.  Do you mean that "http://localhost" is not the correct base URL? If so, you may need to change your `grails.serverURL` configuration value in the `rundeck-config.properties` file.  This determines the base for URLs generated for the application.

**Comment by jinesh-choksi** [comment]
Sorry for the confusion. Yes the issue is that "http://localhost" is not the correct base URL. We have already configured grails.serverURL correctly and all the other URLs in Rundeck are correct except for the ones you see in the screenshot. I believe that the URLs in the screenshot are incorrect maybe because its a code path which shouldn't be active. i.e. clicking the link for the job should not make the "> running" tab become active when you are in the Activity tab of that active job.

**Comment by gschueler** [comment]
the "running" tab is only deactivated when you are viewing a running execution of a job.  Clicking on the Job itself (job view page) will allow the Running activities tab to be used.  that is the intended behavior.

I will check whether the URL used is being generated correctly

**Comment by gschueler** [comment]
I double checked, the URL used in the now running activity tab looks correct to me.  it is generated absolutely using the grails.serverURL value

**Comment by jinesh-choksi** [comment]
Thanks for checking. One last query before closing the issue: should the URL be using the "framework.server.url" value or should it definitely be the grails.serverURL value?

I ask because we have Rundeck behind an httpd SSL proxy and I may have wrongly configured the grails.serverURL (or the framework.server.url values.)

I just checked and in the:
- rundeck-config.properties file: grails.serverURL=http://localhost:4440
(i apologise for earlier stating we had it correctly configured)

whilst in the:

- framework.properties file, framework.server.url = https://rundeck.fqdn.com

**Comment by gschueler** [comment]
`framework.server.url` is only used by the CLI tools to connect to the server. the `grails.serverURL` is used to generate URLs used by the API and the GUI
