### ISSUE TITLE
Using variable in Storage path job options

### ISSUE THREAD

**Issue by Nomekrax** [rundeck/rundeck#2092]
# Bug report

When specifying a variable instead of a hardcoded value in key storage path, option is not interpreted

**My Rundeck detail**
- Rundeck version: 2.6.9-1
- install type: deb
- OS Name/version: Ubuntu 14.04.5

**Expected Behavior**

What I want to do is using a variable when declaring a secure option in the key storage path like this : keys/${job.username}/mykey
The purpose is to use this option as an argument in a command line.

**Actual Behavior**

When executing the job, the path is just not interpreted because (I think) the variable doesn't exists in the process. This results by raising an error : "The ' characters around the executable and arguments are not part of the command".

**How to reproduce Behavior**

Complete workflow is : 
Assume that you already created a key called mykey which type is Password in your key storage. For example, Bob should have a key located in keys/Bob/mykey
- Create an option called userpass, select Secure as input type and then specify keys/${job.username}/mykey as Storage Path.
- Create a command line node step and write this : echo ${option.userpass}
- Run the job with Debug mode activated

...

**Comment by Bengrunt** [comment]
Would definitely love that to be fixed. :+1:

**Comment by tiendungitd** [comment]
Does this issue has been fixed ? I still got the same in latest version
