### ISSUE TITLE
 ${job.nodefilter} variable for passing Node filter to Job Reference 

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#2095]
It could be very useful to have a job's context variable  like  ${job.nodefilter}   in order to pass the node filter of a "overall" job to Jobs References Steps.

An user case example:

Job A => the overall Job
Job B is a step of Job A
Job C is a step of Job B
I would like to pass the node filter from Job A to Job B and Job C

For example passing the node filter to the Job References like:

![screenshot from 2016-10-03 16-29-50](https://cloud.githubusercontent.com/assets/6034968/19050811/a20b54ba-8986-11e6-9423-791d0d252e3a.png)

**Comment by puremourning** [comment]
Isn't it simpler to just to `${node.name}`. Or am I missing something?

**Comment by pgressa** [comment]
Imho this is very similar to https://github.com/rundeck/rundeck/issues/2074

**Comment by gschueler** [comment]
@pgressa yes it is similar. I think adding `${job.nodefilter}` will be a simple way to solve part of the problem. Your request to have a way to create subset of the filter is also useful

**Comment by steveblackmon** [comment]
+1. Propagating a node filter across all of the job references called is an obviously useful behavior that seems to still be lacking. The only workaround I can find is to pass the filter as an option throughout the entire chain, which a) makes it impossible to use the awesome node selector GUI on launch b) sucks.

**Comment by Slm0n87** [comment]
+1 - specially for more complex worflows that feature would make the node-definition easier by inheriting the nodefilter.

**Comment by ltamaster** [comment]
This was added on 2.10.2
https://github.com/rundeck/rundeck/pull/2974
