### ISSUE TITLE
RFE: Add a dashboard

### ISSUE THREAD

**Issue by asyd** [rundeck/rundeck#210]
I wish a dashboard like jenkins CI to have a list of all jobs, which last success data, last error date, last execution time. Could be a nice place to add some job context actions like purge history, edit, etc.

We use rundeck to launch some monitoring scripts, so we need a single page to see all jobs status w/o clicking a lot :) 

Thanks!

**Comment by gargrag** [comment]
+1

**Comment by infa-kparida** [comment]
+1
