### ISSUE TITLE
Jobs Document was invalid for format yaml: java.lang.NullPointerException: Cannot get property 'class' on null object"

### ISSUE THREAD

**Issue by rayjohnson** [rundeck/rundeck#2101]
# Bug report

Calling rest service to import a job.  Yaml format.  I had some old code that called the end point just fine via Curl.  I'm writing a ruby program that manipulates the rundeck config a little before uploading.  However, at this point the differences I see are caused only by the ruby to_yaml implementation.  (All the fields are the same - differences are thing that are quoted or not and style of quote.  Still looks like valid rundeck config and yml.

**My Rundeck detail**
- Rundeck version: 2.6.8-1

**Expected Behavior**

This is the returned value I get:
{"result"=>{"error"=>["true", {"code"=>"api.error.jobs.import.invalid", "message"=>"Jobs Document was invalid for format yaml: java.lang.NullPointerException: Cannot get property 'class' on null object"}], "apiversion"=>"17"}}

It would be nice if the error message at least told me what it was choking on...

I saved the file to disk and loaded it manually into rounded - that worked fine.

**Actual Behavior**

It should work and load the job.

**How to reproduce Behavior**

Here is the yaml file I tried to import:

``` .yaml
- description: Zuora Export - moves data from Zuora (via AQuA) to Kafka
  executionEnabled: true
  loglevel: INFO
  group: zuora_export
  name: zuora_export-dev
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      threadcount: 1
    filter: 'name: docker-swarm-dev-wc1'
  nodesSelectedByDefault: true
  notification:
    onfailure:
      email:
        attachLog: true
        recipients: rjohnson@yp.com
        subject: Zuora Export (dev) - Failed
  retry: '2'
  schedule:
    month: "*"
    time:
      hour: "*"
      minute: 0/15
      seconds: '10'
    weekday:
      day: "*"
    year: "*"
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        docker_command: "./zuora_export"
        docker_cpus: '0.5'
        docker_env_vars: |-
          YP_ENV=dev
          KAFKA_BROKERS=prod512.wc1.yellowpages.com:9092,prod513.wc1.yellowpages.com:9092,prod514.wc1.yellowpages.com:9092
          KAFKA_ZOOKEEPERS=prod512.wc1.yellowpages.com:2181,prod513.wc1.yellowpages.com:2181,prod514.wc1.yellowpages.com:2181
          AVRO_REGISTRY=http://prod512.wc1.yellowpages.com:8081/
        docker_image: docker.yp.com/billing/zuora_export:217d3a8
        docker_memory: '512'
        docker_pull_image: 'false'
      nodeStep: true
      type: docker
    keepgoing: false
    strategy: node-first
  timeout: 1h

```

**Comment by pmatias** [comment]
Same here, and used the same structure. Using the `arundeckrun` python lib, and the `requests` lib when I saw that I was going nowhere with the first lib. Same results.

Switched to xml format and it works, both library and just using `requests`.

**Comment by gschueler** [comment]
the yaml loads correctly on current API using `rd` tool.

If the problem persists please open again.

**Comment by pmatias** [comment]
I don't think that's the right approach @gschueler, I'm writing Python code, using the cli makes no sense in this scenario.

**Comment by gschueler** [comment]
@pmatias sorry I wasn't clear.  I mean that I verified it is not a problem with the yaml or API itself, so it must be a problem with the python libraries you are using. If there is any error in the service.log that may also provide a clue as to what the library is doing wrong
