### ISSUE TITLE
grails-plugin-databinding-2.4.4.jar/META-INF/grails-plugin.xml missing on WAR deployment on WildFly

### ISSUE THREAD

**Issue by AlbertoPeon** [rundeck/rundeck#2108]
# Bug report

**My Rundeck detail**
- Rundeck version: 2.6.9
- install type: war (rpm,deb,war,launcher)
- Webserver Name/version: WildFly 10

I'm trying to deploy the Rundeck 2.6.9 WAR file into WildFly10 with no luck so far.

The error I am getting during the deployment is:

```
2016-10-10 15:12:03,864 [ServerService Thread Pool -- 77] ERROR context.GrailsContextLoaderListener - Error initializing the application: /content/rundeck.war/WEB-INF/lib/grails-plugin-databinding-2.4.4.jar/META-INF/grails-plugin.xml (No such file or directory)  

java.io.FileNotFoundException: /content/rundeck.war/WEB-INF/lib/grails-plugin-databinding-2.4.4.jar/META-INF/grails-plugin.xml (No such file or directory). 
```

which I've been also seeing on the Rundeck mailing list (ref. https://groups.google.com/forum/#!topic/rundeck-discuss/UZ2GUxCUsRw). 

From what I can see, the file seems to be inside the `/content/rundeck.war/WEB-INF/lib/grails-plugin-databinding-2.4.4.jar` JAR file.

Please note that I also had to inject the `log4j.properties` file in `WEB-INF/classes` prior to this (as mentioned in https://groups.google.com/forum/#!topic/rundeck-discuss/0EOTf_kj-Fc).

Could you advise on how to solve this issue? Thanks!

**Comment by ahonor** [comment]
Please reopen if this remains a concern
