### ISSUE TITLE
Why is parallelWorkflowStrategy in incubator for more than 2 years?

### ISSUE THREAD

**Issue by pgressa** [rundeck/rundeck#2115]
# Bug report

**My Rundeck detail**
- Rundeck version: 2.6.9-1
- install type: war
- OS Name/version: el7

**Expected Behavior**

I expect that after 2 years the parallelWorkflowStrategy would be available as supported workflow strategy by default. 

**Actual Behavior**

If I want to use parallelWorkflowStrategy I have to set `feature.incubator.parallelWorkflowStrategy=true` in config manually, but still don't know whether there are some bugs or other faulty behaviour related to this feature as it's still in incubator.

**Comment by gschueler** [comment]
parallel strategy will not be in incubator in 2.7.  We have a new core implementation of the workflow execution engine, and parallel is one of the default options.

**Comment by pgressa** [comment]
Great!

**Comment by gschueler** [comment]
@pgressa November

**Comment by pgressa** [comment]
Good thanks!
