### ISSUE TITLE
Rundeck doesn't rotate logs Jobs(json)

### ISSUE THREAD

**Issue by smbarrionuevo** [rundeck/rundeck#2129]
# Bug report

Hello, I'm new on rundeck, I need to do a purge the log before 2 month(/var/lib/rundeck/logs/rundeck/Produccion/job). 
I found a framework 'framework.logs.dir' that use the path '/var/lib/rundeck/logs'. I have not found on the Api(web) the option for cleaner the logs. Could you say me, where is the configuration of the purge?. Thank you 
**My Rundeck detail**
- Rundeck version: 2.6.9-1
- install type: rpm (rpm,deb,war,launcher)
- OS Name/version: Centos 7

**Expected Behavior**

---

**Actual Behavior**

---

**How to reproduce Behavior**

---
# Enhancement request

(_For enhancements_: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by niphlod** [comment]
hi @smbarrionuevo , there is no config for letting rundeck automatically purge executions (which, in turn, will remove logs from the storage) but there is the API to delete executions. 
I coded one myself that has the ability to loop all projects in order to prune accordingly (e.g. for some projects, keep 30 days, for other keep 90, etc) but it's for powershell (I see you are on linux)...the gist of it is quite simple

```
#getting a list of all projects
$projects = GET /api/18/projects 
foreach ($proj in $projects):
      while $true:
          #getting a batch of executions, in your case older than 2 months
          $executions = GET /api/18/proj.name/executions?olderFilter=2m
          if $executions.length = 0:
              #nothing to do
              break
          POST /api/18/executions/delete?ids=1,2,17    #all $executions.id comma separated
           #or, instead of bulk deleting, the following deletes one by one
          foreach($exec in $executions):
               DELETE /api/18/execution/$exec.id
```

**Comment by ahonor** [comment]
@smbarrionuevo this is a roadmap item. Vote here https://trello.com/c/OQqroc0A/63-execution-history-retention-policy-or-automatic-deletion
