### ISSUE TITLE
Error while doing "/api/17/job/${SCM_JOB_ID}/scm/import/action/import-all"

### ISSUE THREAD

**Issue by albertovar** [rundeck/rundeck#2132]
# Bug report

I'm trying to do an "SCM job import", executing:

RUNDECK_URL="http://rundeck.hostname.com:4440"
RUNDECK_API_TOKEN="xxxxxxxxxxxx"
HEADER_01="X-Rundeck-Auth-Token: ${RUNDECK_API_TOKEN}"
HEADER_02="Content-Type: application/json"
HEADER_03="Accept: application/json"
JSON='{"input":{"message":"$commitMessage"}}'
API="${RUNDECK_URL}/api/17/job/${SCM_JOB_ID}/scm/import/action/import-all"

curl -s -H "$HEADER_01" -H "$HEADER_02" -H "$HEADER_03" -d "$JSON" "$API"

But I get the following error:

`<!DOCTYPE html> <!--[if lt IE 7 ]> <html class="ie6"> <![endif]--> <!--[if IE 7 ]> <html class="ie7"> <![endif]--> <!--[if IE 8 ]> <html class="ie8"> <![endif]--> <!--[if IE 9 ]> <html class="ie9"> <![endif]--> <!--[if (gt IE 9)|!(IE)]><!--> <html lang="en"><!--<![endif]--> <head> <title> RUNDECK - Error </title> <meta charset="utf-8"> <meta http-equiv="X-UA-Compatible" content="IE=edge"> <meta name="viewport" content="width=device-width, initial-scale=1.0"> <link rel="SHORTCUT" href="/rundeck/images/favicon-152.png"/> <link rel="favicon" href="/rundeck/images/favicon-152.png"/> <link rel="shortcut icon" href="/rundeck/images/favicon.ico"/> <link rel="apple-touch-icon-precomposed" href="/rundeck/images/favicon-152.png"/> <link rel="stylesheet" href="/rundeck/assets/rundeck-f4f472db038bea91409d64814dbbeb8e.css"/> <link rel="stylesheet" href="/rundeck/assets/ansicolor-aaa2b709715051396a7ba4a51c4d1d33.css"/> <link rel="stylesheet" href="/rundeck/assets/non_responsive-cfe762b1ee2cca75dad1f018bfadd49e.css <![endif]--> <script src="/rundeck/assets/jquery-5393bf5931b3c4e7052edeec0d67327b.js" type="text/javascript" ></script> <script src="/rundeck/assets/bootstrap-6b8c56148416f3d639db7f96cb65ef8e.js" type="text/javascript" ></script> <script src="/rundeck/assets/prototype.min-b2d54abe0f33ae393770f2e3508b8779.js" type="text/javascript" ></script> <script src="/rundeck/assets/application-29266526f460f429d47c2ed84a19bbc5.js" type="text/javascript" ></script> <script type="text/javascript"> var appLinks = { disclosureIcon: '/rundeck/images/icon-tiny-disclosure.png', disclosureIconOpen: '/rundeck/images/icon-tiny-disclosure-open.png', iconTinyWarn: '/rundeck/images/icon-tiny-warn.png', iconTinyOk: '/rundeck/images/icon-tiny-ok.png', iconSmallRemoveX: '/rundeck/images/icon-small-removex.png', iconTinyRemoveX: '/rundeck/images/icon-tiny-removex.png', iconSpinner: '/rundeck/images/icon-tiny-disclosure-waiting.gif', executionCancelExecution: '/rundeck/execution/cancelExecution?format=json', tailExecutionOutput: '/rundeck/execution/tailExecutionOutput?format=json', reportsEventsFragment:"/rundeck/reports/eventsFragment", frameworkViewResourceModelConfig: "/rundeck/resources/viewResourceModelConfig", frameworkCheckResourceModelConfig: "/rundeck/resources/checkResourceModelConfig", frameworkEditResourceModelConfig: "/rundeck/resources/editResourceModelConfig", frameworkCreateResourceModelConfig: "/rundeck/resources/createResourceModelConfig", frameworkNodes: "/rundeck/resources/nodes", frameworkNodesFragment: "/rundeck/resources/nodesFragment", frameworkNodesQueryAjax: "/rundeck/resources/nodesQueryAjax", frameworkAdhoc: "/rundeck/resources/adhoc", frameworkReloadNodes: "/rundeck/resources/reloadNodes", frameworkNodeSummaryAjax: "/rundeck/resources/nodeSummaryAjax", frameworkDeleteNodeFilterAjax: "/rundeck/resources/deleteNodeFilterAjax", reportsEventsAjax: "/rundeck/reports/eventsAjax", menuNowrunningAjax: "/rundeck/menu/nowrunningAjax", menuHomeAjax: "/rundeck/menu/homeAjax", menuHomeSummaryAjax: "/rundeck/menu/homeSummaryAjax", menuProjectNamesAjax: "/rundeck/menu/projectNamesAjax", scheduledExecutionRunAdhocInline: "/rundeck/scheduledExecution/runAdhocInline", scheduledExecutionCreate: "/rundeck/scheduledExecution/create", scheduledExecutionExecuteFragment: '/rundeck/scheduledExecution/executeFragment', scheduledExecutionActionMenuFragment: '/rundeck/scheduledExecution/actionMenuFragment', scheduledExecutionRunJobInline: '/rundeck/scheduledExecution/runJobInline', scheduledExecutionDetailFragment: '/rundeck/scheduledExecution/detailFragment', scheduledExecutionDetailFragmentAjax: '/rundeck/scheduledExecution/detailFragmentAjax', scheduledExecutionSanitizeHtml: '/rundeck/scheduledExecution/sanitizeHtml', scheduledExecutionWorkflowJson: '/rundeck/scheduledExecution/workflowJson', executionFollowFragment: "/rundeck/execution/followFragment", adhocHistoryAjax: "/rundeck/execution/adhocHistoryAjax", menuJobs: "/rundeck/menu/jobs", userAddFilterPref: "/rundeck/user/addFilterPref", userClearApiToken: "/rundeck/user/clearApiToken?format=json", userGenerateApiToken: "/rundeck/user/generateApiToken?format=json", workflowEdit: '/rundeck/workflow/edit', workflowRender: '/rundeck/workflow/render', workflowSave: '/rundeck/workflow/save', workflowReorder: '/rundeck/workflow/reorder', workflowRemove: '/rundeck/workflow/remove', workflowUndo: '/rundeck/workflow/undo', workflowRedo: '/rundeck/workflow/redo', workflowRevert: '/rundeck/workflow/revert', workflowRenderUndo: '/rundeck/workflow/renderUndo', editOptsRenderUndo: '/rundeck/editOpts/renderUndo', editOptsEdit: '/rundeck/editOpts/edit', editOptsRender: '/rundeck/editOpts/render', editOptsSave: '/rundeck/editOpts/save', editOptsRenderAll: '/rundeck/editOpts/renderAll', editOptsRenderSummary: '/rundeck/editOpts/renderSummary', editOptsRemove: '/rundeck/editOpts/remove', editOptsReorder: '/rundeck/editOpts/reorder', editOptsUndo: '/rundeck/editOpts/undo', editOptsRedo: '/rundeck/editOpts/redo', editOptsRevert: '/rundeck/editOpts/revert', menuJobsPicker: '/rundeck/menu/jobsPicker', scheduledExecutionGroupTreeFragment: '/rundeck/scheduledExecution/groupTreeFragment', storageKeysBrowse: '/rundeck/menu/storage', storageKeysApi: '/rundeck/storage/access/keys', storageKeysDownload: '/rundeck/storage/download/keys', storageKeysDelete: '/rundeck/storage/delete/keys', apiExecutionsBulkDelete: '/rundeck/execution/deleteBulkApi' } ; </script> <style type="text/css"> .rdicon.app-logo, .nodedetail.server .nodedesc, .node_entry.server .nodedesc{ width: 32px; height: 32px; vertical-align: baseline; } .rdicon.app-logo, .nodedetail.server .nodedesc, .node_entry.server .nodedesc { background-image: url("/rundeck/images/Logo_Produban_32x32_black.png"); background-repeat: no-repeat; } @media only screen and (-webkit-min-device-pixel-ratio: 2), only screen and ( min--moz-device-pixel-ratio: 2), only screen and ( -o-min-device-pixel-ratio: 2/1), only screen and ( min-device-pixel-ratio: 2), only screen and ( min-resolution: 192dpi), only screen and ( min-resolution: 2dppx) { .rdicon.app-logo, .nodedetail.server .nodedesc, .node_entry.server .nodedesc { background-image: url("/rundeck/images/rundeck2-icon-32.png"); background-size: 32px 32px; } } </style> <script language="javascript"> function oopsEmbeddedLogin() { document.location = '/rundeck/'; } </script> <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/> <meta name="layout" content="base"/> </head> <body> <nav class="navbar navbar-default navbar-static-top" role="navigation"> <div class="navbar-header"> <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button> <a href="/rundeck/" title="Home" class="navbar-brand"> <i class="rdicon app-logo"></i> RUNDECK </a> </div> <div class="container"> <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1"> <ul class="nav navbar-nav"> <script </ul> <ul class="nav navbar-nav navbar-right"> <li class="headright"> <li class=""> <a href="/rundeck/menu/systemConfig" title="Configure"> <i class="glyphicon glyphicon-cog"></i> </a> </li> <!-- --> <li class="dropdown"> <a href="/rundeck/user/profile/userLabel" class="dropdown-toggle" data-toggle="dropdown" data-target="#" role="button"> admin <span class="caret"></span> </a> <ul class="dropdown-menu" role="menu" aria-labelledby="userLabel"> <li><a href="/rundeck/user/profile"> <i class="glyphicon glyphicon-user"></i> Profile </a> </li> <li class="divider"></li> <li><a href="/rundeck/user/logout" title="Logout user: admin"> <i class="glyphicon glyphicon-remove"></i> Logout </a> </li> </ul> </li> <li> <a href="http://rundeck.org/2.6.9?utm_source=rundeckapp&amp;utm_medium=2.6.9 Linux java 1.7.0_80&amp;utm_campaign=helplink&amp;utm_content=scm/apiJobActionPerform" class="help "> help <b class="glyphicon glyphicon-question-sign"></b> </a> </li> </ul> </div> </div> </nav> <div class="container"> <div class="container"> <div class="row"> <div class="col-sm-12"> <div class="panel panel-default"> <div class="panel-heading"> <h2 class="panel-title ">An Error Occurred</h2> </div> <div class="panel-body text-danger"> <b>Cannot invoke method leftShift() on null object</b> </div> </div> <div class="panel-group" id="accordion"> <div class="panel panel-default"> <div class="panel-heading"> <h4 class="panel-title"> <a data-toggle="collapse" data-parent="#accordion" href="#internalerror"> Error Details <i class="glyphicon glyphicon-chevron-right"></i> </a> </h4> </div> <div class="panel-collapse collapse collapse-expandable" id="internalerror"> <div class="panel panel-default"> <div class="panel-body"> <div class="container"> <div class="row"> <div class="col-sm-12"> <div><b>Request:</b> /rundeck/api/17/job/c550c49f-af53-4a2d-92d2-f4e0b8e87c7b/scm/import/action/import-all </div> <strong>Message:</strong> Cannot invoke method leftShift() on null object <br/> <strong>Caused by:</strong> Cannot invoke method leftShift() on null object <br/> <strong>Class:</strong> ScmController <br/> <strong>At Line:</strong> [1541] <br/> <strong>Code Snippet:</strong><br/> <div class="snippe </pre> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> </div> <div class="container footer"> <div class="row row-space"> <div class="col-sm-12 "> <a href="/rundeck/menu/welcome" class="version link-bare"> RUNDECK 2.6.9-1 </a> <span class="rundeck-version-identity" data-version-string="2.6.9-1" data-version-date="2016-08-03" data-app-id="RUNDECK"></span> </div> </div> <div class="row row-space"> <div class="col-sm-12"> &copy; Copyright 2016 <a href="http://simplifyops.com"> <span style="color:red;">#Simplify</span>Ops</a>. All rights reserved. <a href="/rundeck/menu/licenses">Licenses</a> </div> </div> </div> <!-- --> </body> </html>`

**My Rundeck detail**
- Rundeck version: 2.6.9-1
- install type: rpm
- OS Name/version: Linux RedHat 7

**Expected Behavior**

---

**Actual Behavior**

---

**How to reproduce Behavior**

---
# Enhancement request

(_For enhancements_: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by gschueler** [comment]
can you paste the stacktrace from the service log, i can't determine what the error is from what you pasted

**Comment by albertovar** [comment]
Hello Greg:

Here you go:

[...]
Kerberos username [rundeck]: Kerberos username [rundeck]: Kerberos username
[rundeck]: ERROR GrailsExceptionResolver: NullPointerException occurred
when processing request: [POST]
/rundeck/api/17/job/c550c49f-af53-4a2d-92d2-f4e0b8e87c7b/scm/import/action/import-all
Cannot invoke method leftShift() on null object. Stacktrace follows:
java.lang.NullPointerException: Cannot invoke method leftShift() on null
object
    at
rundeck.controllers.ScmController$_performScmAction_closure35.doCall(ScmController.groovy:961)
    at
rundeck.controllers.ScmController.performScmAction(ScmController.groovy:960)
    at
rundeck.controllers.ScmController.apiJobActionPerform(ScmController.groovy:1541)
    at
org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1360)
    at
grails.plugin.cache.web.filter.PageFragmentCachingFilter.doFilter(PageFragmentCachingFilter.java:198)
    at
grails.plugin.cache.web.filter.AbstractFilter.doFilter(AbstractFilter.java:63)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
    at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:539)
    at
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
    at
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
    at
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
    at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:288)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:115)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at
com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:97)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at
com.dtolabs.rundeck.server.filters.AuthFilter.doFilter(AuthFilter.java:58)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at
org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1331)
    at
org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:477)
    at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:119)
    at
org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:499)
    at
org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
    at
org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
    at
org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
    at
org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
    at
org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
    at
org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
    at
org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
    at org.eclipse.jetty.server.Server.handle(Server.java:349)
    at
org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
    at
org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at
org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
    at
org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
    at
org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
    at
org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
    at
org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
    at java.lang.Thread.run(Thread.java:745)
Kerberos username [rundeck]: ERROR GrailsExceptionResolver:
NullPointerException occurred when processing request: [POST]
/rundeck/api/17/job/c550c49f-af53-4a2d-92d2-f4e0b8e87c7b/scm/import/action/import-all
[...]

Thank you!


*Alberto Tovar Barrena.*

2016-10-28 0:10 GMT+02:00 Greg Schueler <notifications@github.com>:

**Comment by gschueler** [comment]
i think there is a bug when you don't include all of the expected fields in the input json.  If you look at this doc http://rundeck.org/docs/api/index.html#perform-project-scm-action it shows the json content, try including every field:

~~~{.json}
{
    "input":{
        "message":"$commitMessage"
    },
    "jobs":[
        "$jobId"
    ],
    "items":[
        "$itemId"
    ],
    "deleted":null
}
~~~

set it to `"deleted":[]`

**Comment by ahonor** [comment]
please reopen if this remains a concern
