### ISSUE TITLE
java.lang.NullPointerException: Cannot get property 'workflow' on null object

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#2134]
# Bug report

**My Rundeck detail**
- Rundeck version: 2.6.9-1
- install type: war (rpm,deb,war,launcher)
- OS Name/version: Centos 7

**Expected Behavior**

Runing a "overall" job that has a sequence of job references (each "child" jobs has a Job reference to another Job).
Something like:

![screenshot from 2016-10-28 16-16-06](https://cloud.githubusercontent.com/assets/6034968/19819184/e4fe589c-9d29-11e6-88df-b36e84e4866e.png)

**Actual Behavior**

The execution runs OK, but the "Report" page hang (the status remains on "running") with the error:

java.lang.NullPointerException: Cannot get property &#39;workflow&#39; on null object

![screenshot from 2016-10-28 16-11-09](https://cloud.githubusercontent.com/assets/6034968/19819448/10ac78ba-9d2b-11e6-8834-2df243ab344e.png)

**How to reproduce Behavior**

Create a "overall" job that runs a job reference step. Then, the "child" jobs has also a job reference to another Job. If you have more than 5 "levels" of "child" jobs, the error appears.

**Comment by gschueler** [comment]
believe fixed in 67ee025ee1b4d4a199816244a0018f54a7fde155
