### ISSUE TITLE
Add ACL to allow users "kill" only their own executions

### ISSUE THREAD

**Issue by shadowhunter2009** [rundeck/rundeck#2135]
# Bug report
**My Rundeck detail**

* Rundeck version: 2.6.9
* install type: launcher(rpm,deb,war,launcher)
* OS Name/version: freebsd 

**Expected Behavior**
Executions launched by you could not be killed by others. Even they know the execution id and format that url. 

**Actual Behavior**
Rundeck executions could be killed by someone else

...

**Comment by richiereynolds** [comment]
I think they need to be able to be killed by other users. In a team environment, the user who started a job may not be available.
If the person ahs the permission to run a job, I think they should be able to kill it even if someone else started it.

**Comment by gschueler** [comment]
You can disable `kill` access in the acl policy http://rundeck.org/docs/administration/access-control-policy.html#project-scope-resources-and-actions

**Comment by shadowhunter2009** [comment]
If we disable kill access, it means that those group of users will not be able to kill any executions at all. Am i right?

**Comment by gschueler** [comment]
@shadowhunter2009 you can do disable it only for certain jobs if you want.  

If you want a rule that allows a user to kill any jobs they start, but not others', that would require a feature enhancement, but it would be a useful idea.

**Comment by shadowhunter2009** [comment]
@gschueler Yes that is exactly what I want.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
