### ISSUE TITLE
Feature Request: Add CAS SSO support for authentication

### ISSUE THREAD

**Issue by corecache** [rundeck/rundeck#2140]
Hi,

Adding SSO/CAS authentication beside LDAP auth would be greatly appreciated:

https://www.apereo.org/projects/cas

Thanks!

**Comment by kassanmoor** [comment]
I am also interested in this support, since we already have Jenkins, testlink, bonitabpm ans other services with cas sso

**Comment by SolarisYan** [comment]
that's cool

**Comment by BigbigY** [comment]
+1

**Comment by overag3** [comment]
Some good news, compatibility with JAAS Auth : https://apereo.github.io/cas/4.2.x/installation/JAAS-Authentication.html
Very interested for CAS support !

**Comment by ls-initiatives** [comment]
@overag3 I don't think that helps, does it?
That just lets the CAS server authenticate uses against the same backend as Rundeck, but that doesn't bring Rundeck under SSO.
Or did I miss a bit ?

**Comment by overag3** [comment]
@ls-initiatives my fault, link provided is about CAS server.

This documentation is about CAS Java client
https://github.com/apereo/java-cas-client/blob/master/README.md#jaas
