### ISSUE TITLE
How to pass the data from current job to reference job as input options

### ISSUE THREAD

**Issue by binduparam** [rundeck/rundeck#2146]
Hi,

I need to pass certain values from my current job to reference job as option parameters. I tried in different ways but couldn't figure it out.

Any help would be appreciated

thanks,
Eshwar

**Comment by isuftin** [comment]
@binduparam Could you describe what sort of values you want to pass and in what way you're calling the secondary job? 

The job reference option passing is pretty straightforward

-option1 value -option2 value2 -optiona valuea -optionb valueb

**Comment by binduparam** [comment]
Hi Ivan,

the values which I am trying to pass to the options of the reference are
run time variable data in python script.

So this is how my job looks..

Rundeck job ----> Calling a python script(Passing the path of the script)
                  -----> In next step Calling a job having opions which
need to be filled by the runtime data which is generated in python script.

I couldnt figure out any way to do this, but I requested my team mate to
give me an endpoint which points to the rundeck reference job and accepts
the options as arguments.



Thanks,

**Comment by ahonor** [comment]
@binduparam See the new Log Filter plugins to capture data
