### ISSUE TITLE
API showing job executions: Only finished ones are showing

### ISSUE THREAD

**Issue by fernandopcg** [rundeck/rundeck#2153]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.9-1
* install type: rpm
* OS Name/version: Red Hat 7

**Expected Behavior**

When calling the API to show executions (As per * http://rundeck.org/2.6.9/api/index.html#execution-query *) for the given project (Containing several jobs), **all** of them (Both finished and running) should be shown as response

**Actual Behavior**

Only those executions with a status value of "Failed", "Succeeded" or "Aborted" (i.e. finished executions) are shown. Response JSON does not show job executions currently running, which I can see with a different request (/api/14/project/my_project/executions/running). However I understand that the request should report all executions no matter what their status is (As I am not filtering them)

Filtering by "Succeeded" also shows them though, it's only when the filter is not applied that it does not work.

On the other hand, the API call to show executions for a single job given its Job ID works fine, showing all executions regardless of their status.

___

**How to reproduce Behavior**

Launch this HTTP GET request:

X.X.X.X:4440/api/17/project/my_project/executions?max=500&format=json
(Adding token in headers. Tested with API version 14, 16 and 17, same results)

...

**Comment by fernandopcg** [comment]
Seems like the running jobs are being returned correctly, just at the end of the list. As I have over 600 executions I did not see them, but consider keeping the order regardless of the execution status (Maybe it's because the default order is by finish time?)

**Comment by gschueler** [comment]
@fernandopcg that might be the problem.  perhaps adding the ability to change the sort field to start time would help

**Comment by fernandopcg** [comment]
Yes, an "sortBy" parameter would come in handy. I'm using javascript to sort the list to my needs so I'm fine, but others would surely appreciate such a feature. Thanks!
