### ISSUE TITLE
Time shown in different time zones

### ISSUE THREAD

**Issue by dabest1** [rundeck/rundeck#2160]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.9-1
* install type: rpm
* OS Name/version: AWS Linux AMI

**Expected Behavior**

Time should be shown in the same time zone across the user interface.

**Actual Behavior**

Some locations show UTC time, while other locations in the interface show local time.

**How to reproduce Behavior**

Click on Activity. (https://[rundeck_server]/project/mongodb/activity)
Time is shown in UTC for activity history.
Click on one of the executions. (https://[rundeck_server]/project/[project]/execution/show/[id])
Time is shown in local time zone.

**Comment by jennales** [comment]
Following...We are also having this issue since the time change.

**Comment by mhindery** [comment]
I also would like to have the option to view UTC everythwere in the interface.
