### ISSUE TITLE
Having trouble deleting projects

### ISSUE THREAD

**Issue by shadowhunter2009** [rundeck/rundeck#2163]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.2
* install type: launcher 
* OS Name/version: freebsd

Hi I am facing trouble when I try to delete projects. 

It takes few minutes to delete a projects with few executions. However once the number of executions goes high, it becomes nightmare for me to delete projects. 

Here is my requests: 
1. Could u tell me the steps of deleting projects internally? So I could see whether we could improve performance. From log file, the first step will be deleting executions right? 

2. It takes me more than one day to delete a project with about 30000 executions. Is it normal or sth wrong happening?  

...

**Comment by ahonor** [comment]
@shadowhunter2009 Did you resolve this?
