### ISSUE TITLE
Rundeck 2.6.10 upgrade breaks rundeck on CentOS

### ISSUE THREAD

**Issue by xyntrix** [rundeck/rundeck#2164]
# Bug report

(Note: Please fill in the blank `___` about your rundeck installation below. You can remove this line.)

**My Rundeck detail**
Did an rpm update this morning and our Rundeck installation was left in a broken state.

Aug 04 05:47:32 Updated: rundeck-2.6.9-1.21.GA.noarch
Aug 04 05:47:32 Updated: rundeck-config-2.6.9-1.21.GA.noarch

Nov 11 04:23:01 Updated: rundeck-config-2.6.10-1.22.GA.noarch
Nov 11 04:23:05 Updated: rundeck-2.6.10-1.22.GA.noarch

* Rundeck version: 2.6.10
* install type:  rpm
* OS Name/version: CentOS 6.8

**Expected Behavior**

Rundeck to seamlessly update
___

**Actual Behavior**
Rundeck no longer starts after rpm update

It looks like the rpm adds significant changes to the /etc/rundeck/profile file, and the previous file is not replaced (the rpm update copies the file to /etc/rundeck/profile.rpmnew).   We had to manually copy this into place to get rundeck to start.

Now that it's started. ldap no longer works..  so we're troubleshooting that now too.
___

**How to reproduce Behavior**

Install rundeck 2.6.9 and update to 2.6.10 rpm.
___

# Enhancement request

(*For enhancements*: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by willemdh** [comment]
As my fw blocked my yum update I had to do localinstall. No /etc/rundeck/profile.rpmnew was created. After replacing the old config with your new config you posted, I was able to get the rundeckd service started.
Now I'm stuck at making ssl work properly. I see this in the log:

`WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable`

But in my profile 

`RDECK_JVM="$RDECK_JVM -Drundeck.ssl.config=$RDECK_SERVER_CONFIG/ssl/ssl.properties -Dserver.https.port=${RDECK_HTTPS_PORT}"`

is uncommented. My ssl.properties is /etc/rundeck/ssl/ssl.properties

I'll try moving it.

**Comment by willemdh** [comment]
My AD integration seem also broken. The security roles were deleted from the 
/var/lib/rundeck/exp/webapp/WEB-INF/web.xml
again, just as the last update. I re-added them and configured
JAAS_CONF="/etc/rundeck/jaas-MultiAuth.conf"

But I get this when I try to log in:

```
2016-11-11 21:02:16.694:WARN:oejpj.JAASLoginService:
javax.security.auth.login.LoginException: No LoginModules configured for RDpropertyfilelogin
        at javax.security.auth.login.LoginContext.init(LoginContext.java:272)
        at javax.security.auth.login.LoginContext.<init>(LoginContext.java:389)
        at javax.security.auth.login.LoginContext.<init>(LoginContext.java:466)
        at org.eclipse.jetty.plus.jaas.JAASLoginService.login(JAASLoginService.java:215)
        at org.eclipse.jetty.security.authentication.FormAuthenticator.validateRequest(FormAuthenticator.java:183)
        at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:456)
        at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:227)
        at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1031)
        at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:406)
        at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:186)
        at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:965)
        at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:117)
        at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:111)
        at org.eclipse.jetty.server.Server.handle(Server.java:349)
        at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:449)
        at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:925)
        at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:857)
        at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
        at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:76)
        at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:191)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:609)
        at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:45)
        at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:599)
        at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:534)
        at java.lang.Thread.run(Thread.java:745)
2016-11-11 21:02:34.549:WARN:oejpj.JAASLoginService:
```


And here I'm a bit stuck. Anyone any idea?

**Comment by gschueler** [comment]
make sure your login module name matches the one you defined in your jaas config.  it is looking for the default "RDpropertyfilelogin".

This is the relevant line from /etc/rundeck/profile:

~~~
LOGIN_MODULE="${LOGIN_MODULE:-RDpropertyfilelogin}"
~~~

**Comment by willemdh** [comment]
Hey Greg, 

I just restored my snapshot. But I set JAAS_CONF="/etc/rundeck/jaas-MultiAuth.conf" and LOGIN_MODULE="MultiAuth"

Grtz

**Comment by willemdh** [comment]
Good news! Just retried the upgrade and kept the original file. I found which missing info is the reason the rundeckd cannot be started:

`rundeckd="$JAVA_CMD $RDECK_JVM $RDECK_JVM_OPTS -cp $BOOTSTRAP_CP com.dtolabs.rundeck.RunServer $RDECK_BASE"`

I was also able to get ad authentication working. I think I restored the web.xml from a backup. A diff between the old and hte new shows more changes then only the omitted user roles...

```
<       <display-name>/rundeck-production-2.6.9</display-name>
---
>       <display-name>/rundeck-production-2.6.10</display-name>
9c9
<               <param-value>rundeck-production-2.6.9</param-value>
---
>               <param-value>rundeck-production-2.6.10</param-value>
26,37d25
         <security-role>
                 <role-name>ad-group</role-name>
         </security-role>
         <security-role>
                 <role-name>ad-group</role-name>
         </security-role>
         <security-role>
                 <role-name>ad-group</role-name>
         </security-role>
         <security-role>
                 <role-name>ad-group</role-name>
         </security-role>
147c135
<               <filter-class>asset.pipeline.AssetPipelineFilter</filter-class>
---
>               <filter-class>asset.pipeline.grails.AssetPipelineFilter</filter-class>
```
@xyntrix Try making use of the original profile, edit web.xml with your security roles, restart rundeckd and let us know if you also manage to make it work :)

For convenience, this is my full working profile atm:

```
RDECK_INSTALL="${RDECK_INSTALL:-/var/lib/rundeck}"
RDECK_BASE=="${RDECK_INSTALL:-/var/lib/rundeck}"
RDECK_BASE="${RDECK_BASE:-/var/lib/rundeck}"
RDECK_CONFIG="${RDECK_CONFIG:-/etc/rundeck}"
RDECK_SERVER_BASE="${RDECK_SERVER_BASE:-$RDECK_BASE}"
RDECK_SERVER_CONFIG="${RDECK_SERVER_CONFIG:-$RDECK_CONFIG}"
RDECK_SERVER_DATA="${RDECK_SERVER_DATA:-$RDECK_BASE/data}"
RDECK_PROJECTS="${RDECK_PROJECTS:-$RDECK_BASE/projects}"
RUNDECK_TEMPDIR="${RUNDECK_TEMPDIR:-/tmp/rundeck}"
RUNDECK_WORKDIR="${RUNDECK_TEMPDIR:-$RDECK_BASE/work}"
RUNDECK_LOGDIR="${RUNDECK_LOGDIR:-$RDECK_BASE/logs}"
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx1024m -Xms256m -XX:MaxPermSize=256m -server}"
RDECK_TRUSTSTORE_FILE="${RDECK_TRUSTSTORE_FILE:-$RDECK_CONFIG/ssl/truststore}"
RDECK_TRUSTSTORE_TYPE="${RDECK_TRUSTSTORE_TYPE:-jks}"
JAAS_CONF="${JAAS_CONF:-$RDECK_CONFIG/jaas-MultiAuth.conf}"
LOGIN_MODULE="${LOGIN_MODULE:-RDpropertyfilelogin}"
RDECK_HTTP_PORT=${RDECK_HTTP_PORT:-4440}
RDECK_HTTPS_PORT=4443

if [ -z "$JAVA_CMD" ] && [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ] ; then
  JAVA_CMD=$JAVA_HOME/bin/java
  PATH=$PATH:$JAVA_HOME/bin
  export JAVA_HOME
elif [ -z "$JAVA_CMD" ] ; then
  JAVA_CMD=java
fi

for jar in $(find $RDECK_INSTALL/cli -name '*.jar') ; do
  CLI_CP=${CLI_CP:+$CLI_CP:}$jar
done
for jar in $(find $RDECK_INSTALL/bootstrap -name '*.jar') ; do
  BOOTSTRAP_CP=${BOOTSTRAP_CP:+$BOOTSTRAP_CP:}$jar
done

RDECK_JVM="-Djava.security.auth.login.config=/etc/rundeck/jaas-MultiAuth.conf \
        -Dloginmodule.name=MultiAuth \
        -Drdeck.config=/etc/rundeck \
        -Drdeck.base=/var/lib/rundeck \
        -Drundeck.server.configDir=/etc/rundeck \
        -Dserver.datastore.path=/var/lib/rundeck/data \
        -Drundeck.server.serverDir=/var/lib/rundeck \
        -Drdeck.projects=/var/rundeck/projects \
        -Drdeck.runlogs=/var/lib/rundeck/logs \
        -Drundeck.config.location=/etc/rundeck/rundeck-config.properties \
        -Djava.io.tmpdir=$RUNDECK_TEMPDIR"

RDECK_JVM="$RDECK_JVM $RDECK_JVM_SETTINGS"
RDECK_JVM="$RDECK_JVM -Drundeck.ssl.config=/etc/rundeck/ssl/ssl.properties -Dserver.https.port=${RDECK_HTTPS_PORT}"
RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=/etc/rundeck/ssl/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"

if test -t 0 -a -z "$RUNDECK_CLI_TERSE" ; then
  RUNDECK_CLI_TERSE=true
  export RUNDECK_CLI_TERSE
fi

unset JRE_HOME

umask 002

rundeckd="$JAVA_CMD $RDECK_JVM $RDECK_JVM_OPTS -cp $BOOTSTRAP_CP com.dtolabs.rundeck.RunServer $RDECK_BASE"
```

Grtz
Willem

**Comment by grafjo** [comment]
Hi guys,

just a small note how i got my rundeck up and running again.

my setup:
```
[root@localhost rundeck]# rpm -qa| grep rundeck
rundeck-config-2.6.10-1.22.GA.noarch
rundeck-2.6.10-1.22.GA.noarch
[root@localhost rundeck]# cat /etc/*release
CentOS Linux release 7.2.1511 (Core) 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

CentOS Linux release 7.2.1511 (Core) 
CentOS Linux release 7.2.1511 (Core) 
[root@localhost rundeck]# 
```

* I replaced the `/etc/rundeck/profile` with `/etc/rundeck/profile.rpmnew`
* in the new `profile` file, i changed `-Drundeck.config.location=$RDECK_CONFIG/rundeck-config.properties` -> `-Drundeck.config.location=$RDECK_CONFIG/rundeck-config.groovy`
* deleted `/etc/rundeck/rundeck-config.properties`
* start rundeckd again

**Comment by willemdh** [comment]
@grafjo Tx for posting your config. Can I ask why you are using rundeck-config.groovy instead of rundeck-config.properties? I don't even have the rundeck-config.groovy in my install.

**Comment by grafjo** [comment]
@willemdh the puppet module [voxpupuli/puppet-rundeck](https://github.com/voxpupuli/puppet-rundeck/) is using the groovy based config file

**Comment by fbacchella** [comment]
For the RDECK_HTTPS_PORT, the fix is in pull request #2169.

**Comment by gschueler** [comment]
sorry for this install issue.  I think for 2.6 we should revert the profile changes to make sure 2.6.x upgrades are clean.  For 2.7 we can move forward with the new changes allowing use of `/etc/sysconfig/rundeckd` overrides

**Comment by talenhao** [comment]
I can't start rundeck service before I copy profile.rpmnew to replace profile.
Now it seems OK.

**Comment by gschueler** [comment]
profile changes for 2.6 reverted in d7f17a95d08a783079df4a5d78c72e623ff24799
