### ISSUE TITLE
Project list links to project homepage and does not respect `rundeck.gui.startpage` setting

### ISSUE THREAD

**Issue by theduusK** [rundeck/rundeck#2168]
Hey,

With 2.6.10 there is the new feature called "Project home page".
Even I can't figure out the sense of it, I would need some information about it's configuration.

Our colleagues are confused because they get a nearly empty page without jobs when entering a project from the main page. I wasn't able to find any documentation stuff.

So is there a way to configure the Project home page and, if yes, what possibilities do I have there?

Thanks in advance!

BR
Patrick

**Comment by willemdh** [comment]
I was expecting that the motd.md would be visible on the project page, but I just did a test and the content of motd.md is not visible. Maybe a bug?

**Comment by ahonor** [comment]
+1, show motd also

**Comment by theduusK** [comment]
I would like to set the "Jobs" page as "home page" if possible somehow.
Otherwise the property **rundeck.gui.startpage** is useless and no longer needed imho.

**Comment by gschueler** [comment]
motd is shown on project home page

**Comment by gschueler** [comment]
bug: the `rundeck.gui.startpage` is not reflected when selecting a project from the project list

**Comment by willemdh** [comment]
@gschueler I'm not seeing the content of motd.md which I edited in the project configuration page for my project. Or am I missing something here? What exactly do you mean with 'project home page'?

**Comment by gschueler** [comment]
@willemdh in 2.6.10, the project list will link to a new project home page, which should show the motd/readme.  Also clicking the project name in the navbar will go to that page.

there is not much content in the project home page yet, but the `rundeck.gui.startpage` should be used to link to the preferred nav link when clicking the project name in the project list
