### ISSUE TITLE
Align deb and rpm profile files

### ISSUE THREAD

**Issue by grafjo** [rundeck/rundeck#2170]
Hi guys,

https://github.com/rundeck/rundeck/pull/2030/commits/7ebbf41dbbbebdc940ac373870fbf45b75fbdd6d introduced a big change in the [rpm based profile file](https://github.com/rundeck/rundeck/blob/master/packaging/root/etc/rundeck/profile) this causes some trouble using rpm based linux distributions.

Is there a plan to align the [deb based profile file](https://github.com/rundeck/rundeck/blob/master/packaging/debroot/etc/rundeck/profile) after https://github.com/rundeck/rundeck/issues/2164 is resolved?

**Comment by gschueler** [comment]
they should be kept in sync. recent change to rpm profile need to be synced to deb profile.

i am reverting the rpm profile changes for 2.6, but will keep it for 2.7
