### ISSUE TITLE
after created a job it url links to 'localhost'

### ISSUE THREAD

**Issue by hallwin** [rundeck/rundeck#2183]
* Rundeck version: __rundeck-launcher-2.6.9.jar_
* install type: __jar_ (rpm,deb,war,launcher)
* OS Name/version: ___centos7.2

after javar -jar rundeck-launcher-2.6.9.jar
I login rundeck by the URL http://myip:4440

then after I created a jobs it's url turns to "http://localhost:4440"

how to solve this problem ?

3q !

**Comment by niphlod** [comment]
probably rundeck is unable to find the correct hostname to use.
see [properties](http://rundeck.org/docs/administration/installation.html#system-properties), specifically server.hostname

**Comment by ahonor** [comment]
Set the grails.serverURL in rundeck-config.properties
