### ISSUE TITLE
local ssh-agent enabling doesn't work with yubikey based passwordless ssh

### ISSUE THREAD

**Issue by sujitrect** [rundeck/rundeck#2186]
# Bug report

My company uses yubikey. So, when I do ssh to servers, my yubikey is plugged into my Mac. 
In this env, a simple rundeck job configured with just 1 command (e.g. ls/id etc.) is unable to complete the ssh connection to the configured node(s).
Though I am able to do plain command line ssh into the same host(s) on Terminal.
Below are set in my project.properties and I have not overridden them in resources.xml:
- project.local-ssh-agent=true
- project.local-ttl-ssh-agent=3600

Below are my observations:
- I am not very sure how the ssh agent works with yubikey, but I can't see any agent running.
Though, as per my company advocated steps, I had installed memento and I have run `memento ssh-add`. 
- In my default terminal I could see that $SSH_AUTH_SOCK is set but not $SSH_AGENT_PID.
- Output of `ssh-add -L` when run on Terminal:  
  `ssh-rsa <<public key part>> /usr/local/memento/lib/pkcs11.so`
- I guess above is because my /etc/ssh/ssh_config contains below:
` Host *`  
`  PKCS11Provider /usr/local/memento/lib/pkcs11.so `  

**My Rundeck detail**

* Rundeck version: 2.6.9
* install type: launcher (rpm,deb,war,launcher)
* OS Name/version: Darwin/15.6.0

**Expected Behavior**
Rundeck should be able to ssh into the remote hosts since command line ssh works.
**Actual Behavior**
Rundeck job configured as mentioned in report fails.
___

**How to reproduce Behavior**
I guess you could reproduce if you work with yubikey. I searched in various forums but couldn't find a mention of issue with rundeck and yubikey together. Though, I could get around the issue, which I am mentioning in the *Enhancement request* section below, so that you can provide a graceful solution and hopefully a release with the same.
___

# Enhancement request
This issue led me to play around with [jsch's example JSchWithAgentProxy.java](https://github.com/ymnk/jsch-agent-proxy/blob/master/examples/src/main/java/com/jcraft/jsch/agentproxy/examples/JSchWithAgentProxy.java) and to my surprize, it worked for me and was able to provide me a shell. I zeroed in on [Rundeck's SSHTaskBuilder](https://github.com/rundeck/rundeck/blob/e7ff524c32981e0d3dd03f1c139a7fa2dd9e6e3b/core/src/main/java/com/dtolabs/rundeck/core/tasks/net/SSHTaskBuilder.java#L116) and commented line 116,117  following the cue as mentioned below:  
`//cf.setUSocketPath(base.getSSHAgentProcess().getSocketPath());`  
`//cf.setPreferredUSocketFactories("jna,nc");`  
And, after deploying the compiled class from the changed source, my rundeck job was able to successfully complete the ssh connection and run the specified command.
Let me know if any more inputs are needed from my side.

...

**Comment by ahonor** [comment]
@sujitrect Can you send a PR?

**Comment by sujitrect** [comment]
@ahonor Sorry, I missed sending the PR at that time. And now, I don't have the resources.
