### ISSUE TITLE
Rundeck Rudder Nodes Plugin Not Available/Functional

### ISSUE THREAD

**Issue by mtnZZ4trail71** [rundeck/rundeck#2187]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.11 (problem is on Rundeck web site)
* install type: rpm (rpm,deb,war,launcher)
* OS Name/version: Centos 7

**Expected Behavior**

Follow the link to the Rundeck Rudder Nodes Plugin.
Get the plugin and install it.

**Actual Behavior**

Follow this link:
http://rundeck.org/plugins/2015/12/02/rudder-nodes.html

then follow subsequent link:
https://github.com/Normation/rundeck-plugin-rudder

The .jar file version for the plugin is not present. There is a .zip file however.

Under the 'Releases' heading, the link 'releases page' is dead.

Simply plopping the .zip file into the libext dir does not work. Error messages in attached file.
[rundeck-rudder_error.txt](https://github.com/rundeck/rundeck/files/601707/rundeck-rudder_error.txt)

The following is the listing of the files present in the .zip file:
[rundeck-rudder_unzip.txt](https://github.com/rundeck/rundeck/files/601714/rundeck-rudder_unzip.txt)

**How to reproduce Behavior**

Following the above.

# Enhancement request

(*For enhancements*: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by gschueler** [comment]
download the jar from the Releases section https://github.com/Normation/rundeck-plugin-rudder/releases
