### ISSUE TITLE
Feature Request: let job node filter be selected by options JSON property

### ISSUE THREAD

**Issue by gentunian** [rundeck/rundeck#2188]
# Enhancement request

Nothing found at trello about this one.

As posted in IRC:

> <gentunian> seems not possible to tag dynamically like this tags: ${option.SERVICE.name}+${option.ENVIRONMENT.name} but its possible to use ${option.SERVICE.value} inside a remote URL.
> <gentunian> however, taggin like this ${option.SERVICE} works.
> <gentunian> kind of weird.
> <gentunian> and sadly useless :(
> <gentunian> IDs may determine exactly one such thing. Names (tags) may determine multiple things.
> <gentunian> so by names we can determine multiple nodes.

Rundeck provides the ability to choose options based on remote URLs. The object returned must be a JSON as doc states. For instance:
```
[
{ "name": "option 1", "value": "1"},
{ "name": "option 2", "value": "2"},
...
]
```

This option variable can be used in another remote options just using it like: `${option.MYOPTION.value}`.

I've written a simple REST service that wraps a model returning something like:
```
[
{ "name": "option 1", "value": "1", "anotherProperty": "something", "foo": "bar" }
]
```

This works ok. Name and value keys are provided. It may be useful to be able to access those properties.

So, you can filter nodes by `${option.MYOPTION.[some-property]}`

For example: `${option.MYOPTION.tags}`

Cheers,

**Comment by gschueler** [comment]
use a node filter like `tags: ${option.SERVER}+${option.ENVIRONMENT}`

**Comment by gentunian** [comment]
Hey @gschueler, hi! thanks for replying  ;) 

It works that way. Maybe I didn't mentioned or explained myself correctly when I quoted the IRC:

> seems not possible to tag dynamically like this tags:
> ${option.SERVICE.name}+${option.ENVIRONMENT.name} but its possible to use
> ${option.SERVICE.value} inside a remote URL.
> however, taggin like this ${option.SERVICE} works.

I thought on extending the scope of how to use options values. For example, there some scenarios where you have info you may identified by IDs and use extra meta data for another purposes.

Image a model relation like this one:

```
+---------+         +---------+          +---------+
| MODEL 1 |-------->| MODEL 2 |--------->| MODEL 3 |
+---------+         +---------+          +---------+
```

With the current state of rundeck processing options values I did something like this for remote options providers:

```
// here you are querying the RESTful service with tags
MODEL_ONE: http://localhost:1337/api/model_one
MODEL_TWO: http://localhost:1337/api/model_two?m1=${option.MODEL_ONE.value}
MODEL_THREE: http://localhost:1337/api/model_three?m1=${option.MODEL_ONE.value}&m2=${option.MODEL_TWO.value}
```

This needs to be preprocessed in the backend. `value` property must be a value that you may use to tag nodes and also to filter information. If you allow arbitrary keys in the JSON response, `value` could be an ID that refers to some primary key of the option name, and another property could be the tag filter for that particular response.

You may improve a lot your options to something like this:

```
// here you are querying the RESTful service with ids
MODEL_ONE: http://localhost:1337/api/model_one
MODEL_TWO: http://localhost:1337/api/model_two?m1=${option.MODEL_ONE.value}
MODEL_THREE: http://localhost:1337/api/model_three?m2=${option.MODEL_TWO.value}
```

This case scenario is better explained with a sample data:

```
[
{ "name": "production", "value": "1"},
{ "name": "development", "value": "2}
]
```

seems trivial from the JSON output above that tagging nodes using IDs won't be useful because (mainly) ids will identify uniquely a record a tags are mainly for grouping purposes. The above JSON could be changed so you use the `value` property with things you may tag, but it may be a worst case for querying a RESTful service.

This is because if you want to use the options values to filter nodes then you will need to query the option providers with tags (or partial tags) as it's equivalent.

I hope I make a point there.

cheers!
