### ISSUE TITLE
Failed to apply plugin [id 'nexus-workflow']

### ISSUE THREAD

**Issue by SolarisYan** [rundeck/rundeck#2197]
Hi there, i use ./gradlew build to build rundeck on my compute,but i have some error as follow:

* What went wrong:
A problem occurred evaluating root project 'rundeck'.
> Failed to apply plugin [id 'nexus-workflow']
   > Could not find method add() for arguments [nexusStagingList, class com.adaptc.gradle.nexusworkflow.NexusStagingListTask] on task set.

how can i build rundeck on my own compute?

**Comment by gschueler** [comment]
Hi, I think you are using a newer version of gradle, although I don't know how if you are using the gradle wrapper script.  Did you upgrade your wrapper version?

**Comment by SolarisYan** [comment]
@gschueler   thanks for your reminding，i have install other version of gradle on my computer

**Comment by SolarisYan** [comment]
@gschueler  hi, i use grails build -x test to build rundeckapp, but some errors as follow:

| Loading Grails 2.4.4
Maven Central: http://repo1.maven.org/maven2/
Grails Central: http://grails.org/plugins
Application Version: 2.6.11-SNAPSHOT
| Configuring classpath
| Error Resolve error obtaining dependencies: The following artifacts could not be resolved: org.rundeck:rundeck-core:jar:2.6.11-SNAPSHOT, org.rundeck:rundeck-storage-filesys:jar:2.6.11-SNAPSHOT: Could not find artifact org.rundeck:rundeck-core:jar:2.6.11-SNAPSHOT in repo1_maven_org_maven2_ (http://repo1.maven.org/maven2/) (Use --stacktrace to see the full trace)
| Error Resolve error obtaining dependencies: The following artifacts could not be resolved: org.rundeck:rundeck-core:jar:2.6.11-SNAPSHOT, org.rundeck:rundeck-storage-filesys:jar:2.6.11-SNAPSHOT: Could not find artifact org.rundeck:rundeck-core:jar:2.6.11-SNAPSHOT in repo1_maven_org_maven2_ (http://repo1.maven.org/maven2/) (Use --stacktrace to see the full trace)
| Error Resolve error obtaining dependencies: The following artifacts could not be resolved: org.rundeck:rundeck-core:jar:2.6.11-SNAPSHOT, org.rundeck:rundeck-storage-filesys:jar:2.6.11-SNAPSHOT: Could not find artifact org.rundeck:rundeck-core:jar:2.6.11-SNAPSHOT in repo1_maven_org_maven2_ (http://repo1.maven.org/maven2/) (Use --stacktrace to see the full trace)
| Error The following artifacts could not be resolved: org.rundeck:rundeck-core:jar:2.6.11-SNAPSHOT, org.rundeck:rundeck-storage-filesys:jar:2.6.11-SNAPSHOT: Could not find artifact org.rundeck:rundeck-core:jar:2.6.11-SNAPSHOT in repo1_maven_org_maven2_ (http://repo1.maven.org/maven2/)

can you  help me? thanks a lot

**Comment by gschueler** [comment]
it is depending on the snapshot version of the rundeck-core jar, which is presumably not yet built.

you just need to run `./gradlew -p core install`, which will install it to your local maven repo (`~/.m2/repository`) and allow the grails app to depend on it

**Comment by SolarisYan** [comment]
got it
