### ISSUE TITLE
Option value restrictions not works for job references with remote url allowed values..

### ISSUE THREAD

**Issue by liszi** [rundeck/rundeck#2201]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.9-1
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux Server release 6.8

**Expected Behavior**
There are **two jobs**. **First** has a **required and restricted valued option**, which enforced from **allowed values** from a **remote url json file**, with an array. The **second** job **calls the first** one **as a job reference** step. In the job reference step the required option is given like "**-option not_allowed_value**". This option is a restricted valued option, so running of the **second job should fail** with an error, but it **not fails** 

**Actual Behavior**
Rundeck **doesn't enforce allowed values**. 

**How to reproduce Behavior**
Unzip [example_jobs.zip](https://github.com/rundeck/rundeck/files/613080/example_jobs.zip).
Import "continent_print" file to rundeck as a yaml job, it will create two jobs.
Copy "location_allowed_values.json" file to rundeck server to /var/lib/rundeck/options/ folder with rundeck user permission. (Create options folder with rundeck user permission.)
Run par_print (parent print) job. It will not fail with the given wrong option value.

**Comment by xirixiz** [comment]
Same issue occurs via rundeck cli (1.0.22)

**Comment by Romainj1** [comment]
I have the same Issue with Rundeck 3.0.21 (3.0.21-20190424 ).

**Comment by jtobard** [comment]
No longer an issue on latest version 3.2.x
![image](https://user-images.githubusercontent.com/2894508/79385364-766c6c00-7f36-11ea-8c57-3e2646582c8c.png)
