### ISSUE TITLE
`select all` only selects screen entries -> `bulk delete` becomes useless

### ISSUE THREAD

**Issue by alexfouche** [rundeck/rundeck#2203]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.11
* install type: RPM
* OS Name/version: CentOS 7

In job history `recent`, at the bottom right, there is a `bulk delete` and a `select all`.
Unfortunately, this is useless, since `select all` only selects the 20 entries on the screen, and not really all history of jobs runs !

**Expected Behavior**

`select all` really selects all history according to filter, and not what is shown on screen. `bulk delete` then should delete ALL jobs runs matching filter, not only the ones shown on screen

**Actual Behavior**

`select all` only selects runs that are shown on screen. `bulk delete` then only deletes these 20 jobs runs, which is useless when you have thousands or even only hundreds of previous runs.

**How to reproduce Behavior**

In job history `recent`, at the bottom right, there is a `bulk delete` and a `select all`.

**Comment by alexfouche** [comment]
Discussion going on at https://github.com/rundeck/rundeck/issues/976

**Comment by ahonor** [comment]
Closing in deference to #976
