### ISSUE TITLE
unable to run the jobs on target chef nodes

### ISSUE THREAD

**Issue by cpkatragadda** [rundeck/rundeck#2204]
![rundeck](https://cloud.githubusercontent.com/assets/19722118/20684308/5798cd86-b57d-11e6-9d6f-d3d663050e30.PNG)
# Bug report

(Note: Please fill in the blank `___` about your rundeck installation below. You can remove this line.)

**My Rundeck detail**
Hello,
I was trying to integrate chef with rundeck. I have installed the rundeck and integrated with the chef using the chef-rundeck ruby gem. I was able to reflect the bootstrapped nodes from the chef server into the rundeck. But, while I was trying to run the rundeck job I was getting an issue that connection was refused with http://localhost:9980 on which my sinatra was running. Can any one please help me this issue.
* Rundeck version: ___2.6.11
* install type: __rpm_ (rpm,deb,war,launcher)
* OS Name/version: __RHEL_

**Expected Behavior**

___

**Actual Behavior**

___

**How to reproduce Behavior**

___

# Enhancement request

(*For enhancements*: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by mrala** [comment]
This looks like a chef-rundeck issue. Have you looked at [better-chef-rundeck](https://github.com/atheiman/better-chef-rundeck)?

**Comment by ahonor** [comment]
Please reopen if this remains a concern
