### ISSUE TITLE
User and result columns in Activity page are mixed into each other

### ISSUE THREAD

**Issue by willemdh** [rundeck/rundeck#2207]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.10
* install type: rpm
* OS Name/version: CentOS 7

**Expected Behavior**

Proper column formatting in Activity page, even with longer usernames

**Actual Behavior**

Columns with user and result (last 2 columns) are wrangled into each other when usernames longer then x characters are used:

![image](https://cloud.githubusercontent.com/assets/6462991/20709802/a1a9b542-b637-11e6-83e6-96d2bc3ece82.png)

**How to reproduce Behavior**

Create a user with a long user name, eg an email address. I notticed this issue when I started using userPrincipalName instead of sAMAccountName in my jass config.

**Comment by bbomgardner** [comment]
Could we get this patch added to main? Long nodenames also clutter up the table.
