### ISSUE TITLE
Scheduled job running multiple time

### ISSUE THREAD

**Issue by shoshanav** [rundeck/rundeck#2211]
Hi,

I'm using rundeck 2.6.9.1, and I have a strange issue: I have a scheduled job (which has to run every 30 minutes) and it is running but instead of one time it runs about 50 times (!!) at the same minute.
(As you can see in the screenshot attached)
![rundeck](https://cloud.githubusercontent.com/assets/5328384/20751125/cd561304-b702-11e6-90db-263578cb9a2a.png)

I tried to stop the scheduling and define it again, didn't help. I tried to delete the job and define it again from scratch, didn't help. 

I tried to add another simple job, just to check ,and it was also executed many times.

What can be the problem????

Thanks

**Comment by niphlod** [comment]
hum. what cron line you have in place that defines the schedule ?

**Comment by shoshanav** [comment]
* /30 * * * *

**Comment by willemdh** [comment]
You need `0 0/30 * 1/1 * ? *` to make a cron job that runs every 30 minutes. It's Java cron, which starts with seconds.
This website can help you test your crons:
http://www.cronmaker.com/

**Comment by shoshanav** [comment]
Thanks, I'll change and see if it helps.

(just to clarify, currently it is running every 30 minutes, but many times instead of once)

**Comment by shoshanav** [comment]
Tried to change, but getting: "Format invalid"

**Comment by minhuber** [comment]
@shoshanav
Try this one: 0 0/30 * * * ?
This should get it going for every 30 minutes.

**Comment by shoshanav** [comment]
This worked!!! Thanks

**Comment by willemdh** [comment]
@shoshanav Please close this issue if this is solved for you. :)
