### ISSUE TITLE
After upgrade to 2.7, service don't start  

### ISSUE THREAD

**Issue by vidalsysadmin** [rundeck/rundeck#2215]
* Rundeck version: rundeck-2.7.0-1.24.GA.noarch
* install type: RPM
* OS Name/version: Centos 7.2.1511

**Expected Behavior**
After upgrading the rundeck with yum update, when I start the service with systemd , he start :)  

**Actual Behavior**

When I start the service with systemctl start rundeckd  , the service don't start:

# systemctl status rundeckd 
● rundeckd.service - SYSV: rundeckd, providing rundeckd
   Loaded: loaded (/etc/rc.d/init.d/rundeckd)
   Active: inactive (dead) since jeu. 2016-12-01 09:03:05 CET; 24s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2763 ExecStop=/etc/rc.d/init.d/rundeckd stop (code=exited, status=0/SUCCESS)
  Process: 2731 ExecStart=/etc/rc.d/init.d/rundeckd start (code=exited, status=0/SUCCESS)
 Main PID: 2737 (code=exited, status=0/SUCCESS)

déc. 01 09:03:05 srv-vid-tux60 systemd[1]: Starting SYSV: rundeckd, providing rundeckd...
déc. 01 09:03:05 srv-vid-tux60 rundeckd[2731]: Starting rundeckd: [  OK  ]
déc. 01 09:03:05 srv-vid-tux60 systemd[1]: Started SYSV: rundeckd, providing rundeckd.
déc. 01 09:03:05 srv-vid-tux60 rundeckd[2763]: Stopping rundeckd: [FAILED]

**How to reproduce Behavior**

Try to start service with systemd

...

**Comment by vidalsysadmin** [comment]
After making yum remove rundeckd and yum install rundeckd all is fine. The service start now.

**Comment by stepps** [comment]
The upgrading instructions [here](http://rundeck.org/docs/upgrading/index.html), warn about changes in `/etc/rundeck/profile`.
Purging and reinstalling is good only for vanilla installs. I have moved some variables out of  `/etc/rundec/profile` and I have overwritten the old file with the one that came with the rpm at install (`/etc/rundeck/profile.rpmnew`)

**Comment by jcreedon** [comment]
So I ran into a similar problem, here is how I fixed it:

I upgraded using `yum upgrade rundeck`, however, I did not see the `profile.rpmnew` as mentioned by stepps. It ended up being that I also need to run `yum upgrade rundeck-config`. I then ported over configuration as described in the upgrade instructions and replaced `profile` with `profile.rpmnew`.
