### ISSUE TITLE
Job XML in 2.6.11 doesn't contain a <project> element

### ISSUE THREAD

**Issue by dserodio** [rundeck/rundeck#2224]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.11
* install type: RPM
* OS Name/version: CentOS 6.8

**Expected Behavior**

The job XML returned by the `GET /api/1/job/[ID]` API should include the `<project>` element inside a `<context>` element, like the same API in Rundeck 2.4.2 does.

**Actual Behavior**

The job XML returned by the `GET /api/1/job/[ID]` API **does not** include the `<project>` element inside a `<context>` element. Because of this, the Jenkins Rundeck plugin shows `null` where the project name should be.

**How to reproduce Behavior**

Call the `GET /api/1/job/[ID]` API for an existing job and search for `<project>`.

**Comment by victorssouza** [comment]
Guys, we are also affected by this problem and seems like a regression to me. Are there any plans of looking into this issue?

**My Rundeck detail**

- Rundeck version: 2.8.2
- install type: RPM
- OS Name/version: CentOS 6.8

Best regards.

**Comment by ahonor** [comment]
True, we won't be adding the project back to the serialized job definitions.

**Comment by dserodio** [comment]
@ahonor, how can one get the project for a given job using Rundeck API then?
