### ISSUE TITLE
http to https redirect for Rundeck running as a docker container in Kubernetes

### ISSUE THREAD

**Issue by gitgrasshopper** [rundeck/rundeck#2233]
# Bug report
**My Rundeck detail**
I have Rundeck set up to run as a docker container in Kubernetes.  SSL is handled at the edge, for ingress, so Rundeck would use an http backend within the cluster.

* Rundeck version: Rundeck 2.6.9-1
* install type:  deb
* OS Name/version: debian/jessie

**Expected Behavior**
When I type in https://rundeck.xxx.yyy.zzz, it should get redirected to https://rundeck.xxx.yyy.zzz/user/login.  I would then provide my login and password, and then get into the main Rundeck menu page.

**Actual Behavior**
When I type in https://rundeck.xxx.yyy.zzz, it gets redirected to http://rundeck.xxx.yyy.zzz/user/login and returns "site can't be reached".  I would then append https again and I get to the login page.  I would pass my user and password and redirected to http://rundeck.xxx.yyy.zzz with a "site can't be reached" error.  I've to append https again and will get redirected to the Rundeck main menu.  I can now do what I want, like explore projects, create jobs, run commands, etc.  Only when I logout when I encounter the same https to http redirect and "site can't be reached" error.

Has anyone encountered such Rundeck behavior before?  I searched the issues list but didn't see anything like this.  

**How to reproduce Behavior**
___
# Enhancement request

(*For enhancements*: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by gschueler** [comment]
redirects will use the `grails.serverURL` defined in rundeck-config.properties, make sure that has the correct protocl scheme

**Comment by gitgrasshopper** [comment]
Thanks for responding @gschueler.

This is my entry in the rundeck-config properties:
grails.serverURL=https://rundeck.xxx.yyy.zzz

framework.properties has:
framework.server.name = rundeck.xxx.yyy.zzz
framework.server.hostname = rundeck.xxx.yyy.zzz
framework.server.port = 443
framework.server.url = https://rundeck.xxx.yyy.zzz

**Comment by jjethwa** [comment]
```
-Drundeck.jetty.connector.forwarded=true
```

Might help?

**Comment by gitgrasshopper** [comment]
@jjethwa thanks.  I have that set already in the profile.  I'm still investigating...might have something to do with SSL terminating at the k8s load balancer. The load balancer would then send an http request, so my https url gets redirected to http upon login.

**Comment by gitgrasshopper** [comment]
Here's what's happening:
outside --> F5: uses HTTPS 
F5 --> nginx: uses HTTP with X-Forwarded-Proto: HTTPS
nginx --> app service: uses HTTP with X-Forwarded-Proto: HTTP  (this is where the redirect from https to http is happening)

This is seems to be an issue in our K8s environment, so closing this now.  Thanks for those who responded :)

**Comment by panikdkernel** [comment]
```
  annotations: 
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Host $host:443;
      proxy_set_header X-Forwarded-Server $host;
      proxy_set_header X-Forwarded-Proto https;
      proxy_set_header User-Agent $http_user_agent;
```
      
adding the above annotation fixed this for me
