### ISSUE TITLE
Question: security code review

### ISSUE THREAD

**Issue by chiel1980** [rundeck/rundeck#2234]
Hi,

Did you guys ever did a security review on your code by an external party?
And if yes, are you willing to share these results or can we find it back in some specifc commits?
We are scheduling a code review by an external security company and if you want, we would like to share these results with you/the community as feedback to improve the product (if anything has been found) :)

Michiel

**Comment by ahonor** [comment]
@chiel1980 we have had a few test results provided to us by private parties so nothing we could share. We try to address high priority issues right away. Let us know what you find.

**Comment by ahonor** [comment]
Please reopen if you have any feedback to share
