### ISSUE TITLE
rundeckd won't start : Missing $rundeckd java command variable

### ISSUE THREAD

**Issue by RockTheJib** [rundeck/rundeck#2237]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1
* install type: rpm
* OS Name/version: Centos 7.2

**Expected Behavior**

systemctl start rundeckd or service rundeckd start should start rundeck

**Actual Behavior**

No rundeck process and /var/log/rundeck/service.log file is empty

**How to reproduce Behavior**

systemctl start rundeckd

# Enhancement request
the rundeckd variable was previously in /etc/init.d/rundeckd script as follow :
$prog=rundeckd
rundeckd="${JAVA_HOME:-/usr}/bin/java ${RDECK_JVM} -cp ${BOOTSTRAP_CP} com.dtolabs.rundeck.RunServer /var/lib/rundeck ${RDECK_HTTP_PORT}"
it seems the /etc/init.d/rundeckd is searching for the following files
[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
But since update there is no such files as /etc/sysconfig/rundeckd
Attached file is a working /etc/init.d/rundeckd

Thanks

[rundeckd.txt](https://github.com/rundeck/rundeck/files/648587/rundeckd.txt)

...

**Comment by bvamos** [comment]
A workaround is: putting back this line to init.d/rundeckd after the profile include:

`rundeckd="${JAVA_HOME:-/usr}/bin/java ${RDECK_JVM} -cp ${BOOTSTRAP_CP} com.dtolabs.rundeck.RunServer /var/lib/rundeck ${RDECK_HTTP_PORT}"`

**Comment by ltamaster** [comment]
HI @RockTheJib 
Could you please send me the /etc/rundeck/profile  you have?
Thanks

**Comment by rangsan** [comment]
@bvamos  Thank you it works like a charm.

**Comment by gschueler** [comment]
The /etc/rundeck/profile changed in 2.7, and now defines `rundeckd` there https://github.com/rundeck/rundeck/blob/master/packaging/root/etc/rundeck/profile#L65

If you upgraded, your profile file might be out of date as rpm would not overwrite your changes.  You should move customizations to `/etc/sysconfig/rundeckd` for redhat now.

Please try using the profile from rpm, and setting variables in the sysconfig file.

Sorry about the upgrade issues
