### ISSUE TITLE
Unable to connect to running web service

### ISSUE THREAD

**Issue by jpoling-dswrx** [rundeck/rundeck#2240]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1-1-GA
* install type: .deb
* OS Name/version: Ubuntu 16.04

**Expected Behavior**

Able to modify configuration file(s) to change the listening address/port.

**Actual Behavior**

Modifying /etc/rundeck/framework.properties and /etc/rundeck/rundeck-config.properties (according to http://rundeck.org/docs/manual/configure.html) does not work to change listening address/port settings.

**How to reproduce Behavior**

_Stop Service_
`service rundeckd stop`

_Change Listening Port to 80_
Change port settings in both of the above files to port 80.

_(Re)Start Service_
`service rundeckd start`

_Ensure Service is Listening on New Port (80)_
`netstat -ano`
...
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       Timer
tcp        0      0 127.0.1.1:53            0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      off (0.00/0/0)
tcp6       0      0 :::22                   :::*                    LISTEN      off (0.00/0/0)
tcp6       0      0 :::4440                 :::*                    LISTEN      off (0.00/0/0)
...

Note that it is still listening on the standard 4440 port, not the newly changed port (80).

**Comment by mrala** [comment]
Are you setting `RDECK_HTTP_PORT` in [/etc/rundeck/profile](https://github.com/rundeck/rundeck/blob/master/packaging/debroot/etc/rundeck/profile#L16)?

**Comment by jpoling-dswrx** [comment]
No, am I supposed to? Documentation mentions nothing about that.

**Comment by mrala** [comment]
You could try setting it and verifying if it works or not. I'm not sure if it's in the documentation.

**Comment by jpoling-dswrx** [comment]
Still doesn't work.

`[root@rundeck-vm (:) labadmin]# grep :80 /etc/rundeck/rundeck-config.properties`
grails.serverURL=http://0.0.0.0:80
`[root@rundeck-vm (:) labadmin]# grep :80 /etc/rundeck/framework.properties`
framework.server.port = 80
framework.server.url = http://0.0.0.0:80
`[root@rundeck-vm (:) labadmin]# grep :80 /etc/rundeck/profile`
RDECK_HTTP_PORT=${RDECK_HTTP_PORT:-80}
`[root@rundeck-vm (:) labadmin]# netstat -ano | grep :80`
No results.

**Comment by mrala** [comment]
Have you tried setting it to a port > 1024?

**Comment by jpoling-dswrx** [comment]
Yes, still can't connect. 

`netstat -ano | grep :8080`
tcp6       0      0 :::8080                 :::*                    LISTEN      off (0.00/0/0)

It never listens on tcp (ipv4), only tcp6, which may be the problem.

**Comment by mrala** [comment]
It looks like it's trying to using port 8080, though.

**Comment by jpoling-dswrx** [comment]
Yes... that is one of the  many ports I've tried, to include the default 4440, 80 (it never even starts listening), 8080, 1025, etc.

**Comment by jpoling-dswrx** [comment]
The problem here is that it never starts listening on all interfaces (0.0.0.0) so that I can connect to it. Instead, it only listens on tcp6 :::. When it starts, it should bind to all interfaces (0.0.0.0:<port>) for it to work and be able to connect from another machine, as referenced in the guide here:

https://www.sans.org/reading-room/whitepapers/privilege/introduction-rundeck-secure-script-executions-37162

Yet, it does not. Why, I'm not sure, which is why I'm here hoping to get help to figure that out.

**Comment by gschueler** [comment]
Sorry, we should have an explicit section in the Administrator Guide about setting the http/https ports.

(We are also in the midst of correcting the rpm/deb init scripts of some problems, so bear with me)

For 2.7.1, Debian, you would modify `/etc/rundeck/profile` and set the RDECK_HTTP_PORT variable, or export RDECK_HTTP_PORT in a `/etc/sysconfig/rundeckd` file. (*caveat*, this is changing to `/etc/default/rundeckd` for debian soon)

If you are using  RPM install, you would export the RDECK_HTTP_PORT value inside  `/etc/default/rundeckd`.  

If you are using the launcher, you would specify `-Dserver.http.port=8080` and/or `-Dserver.https.port=8443` on the java commandline to set the port.

Note: in Rundeck 2.6 and earlier, for both rpm and debian, you should modify `/etc/rundeck/profile` to add the same java commandline options to JAVA_OPTS as for the launcher.

If you want to only bind on ipv4 interface, set a java option of `-Djava.net.preferIPv4Stack=true`

**Comment by jpoling-dswrx** [comment]
Does /etc/rundeck/rundeck-config.properties or /etc/rundeck/framework.properties control or have any effect on anything?

**Comment by gschueler** [comment]
@jpoling-dswrx Those files are for app configuration, but have no effect on the web server

**Comment by ahonor** [comment]
Please reopen if this remains a concern

**Comment by lightarrow** [comment]
Even with a new install the /etc/default/rundeckd file is not created doing an install the ubuntu/debian way with apt. Rundeck is not reading the override from /etc/default/rundeckd.
