### ISSUE TITLE
error running rd-acl in rundeck 2.6.3

### ISSUE THREAD

**Issue by herdingkittens** [rundeck/rundeck#2241]
running v2.6.3 on RHEL6.5, 

I am trying to use the rd-acl tool to help troubleshoot my *.aclpolicy files. but I get the following error:

[user@rundeck-prd01 rundeck]$ rd-acl
Error: Could not find or load main class com.dtolabs.rundeck.core.cli.acl.AclTool

not sure where to go from here, a google search was not very productive.

**Comment by abohne** [comment]
I'm experiencing the same issue using 2.7.2.

**Comment by ajmora7** [comment]
Having the same issue, seems to be no fix wherever I look

**Comment by ahonor** [comment]
This might be due to the rd-acl file not reading the /etc/rundeck/profile.
