### ISSUE TITLE
Unable to start rundeck under Ubuntu

### ISSUE THREAD

**Issue by clauded** [rundeck/rundeck#2242]
# Bug report

**My Rundeck detail**

"service rundeckd start" or "/etc/init.d/rundeckd start" don't start rundeck on Ubuntu 14.04. 

Deleting the file /etc/init/rundeckd.conf is a workaround to start rundeck normaly.

* Rundeck version: 2.7.1
* install type: deb (rpm,deb,war,launcher)
* OS Name/version: ubuntu 14.04

**Expected Behavior**

rundeck should start with the service command and at startup

**Actual Behavior**

Errors are logged in /var/log/rundeck/service.log and rundeckd service is not started:

/proc/self/fd/9: 8: exec: /usr/lib/jvm/java-8-openjdk-amd64/bin/java -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf            -Dloginmodule.name=RDpropertyfilelogin            -Drdeck.config=/etc/rundeck            -Drundeck.server.configDir=/etc/rundeck            -Dserver.datastore.path=/var/lib/rundeck/data            -Drundeck.server.serverDir=/var/lib/rundeck            -Drdeck.projects=/var/lib/rundeck/projects            -Drdeck.runlogs=/var/lib/rundeck/logs            -Drundeck.config.location=/etc/rundeck/rundeck-config.groovy            -Djava.io.tmpdir=/tmp/rundeck            -Drundeck.server.workDir=/tmp/rundeck            -Dserver.http.port=4440  -Xmx1024m -Xms256m -XX:MaxPermSize=256m -server  -cp /var/lib/rundeck/bootstrap/javax.servlet-3.0.0.v201112011016.jar:/var/lib/rundeck/bootstrap/log4j-1.2.16.jar:/var/lib/rundeck/bootstrap/jetty-jaas-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-all-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-http-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jna-3.2.2.jar:/var/lib/rundeck/bootstrap/jetty-util-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/not-yet-commons-ssl-0.3.11.jar:/var/lib/rundeck/bootstrap/rundeck-jetty-server-2.7.1.jar:/var/lib/rundeck/bootstrap/jetty-security-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-server-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/libpam4j-1.5.jar:/var/lib/rundeck/bootstrap/jetty-io-9.0.7.v20131107.jar com.dtolabs.rundeck.RunServer /var/lib/rundeck: not found

**How to reproduce Behavior**

Install rundeck 2.6.x on ubuntu 14.04. Upgrade to 2.7.1.

**Comment by burdandrei** [comment]
this is related to https://github.com/rundeck/rundeck/commit/4875c065555e94993a637f184f31f06fa694f5db

here is the fix https://github.com/rundeck/rundeck/pull/2246

**Comment by clauded** [comment]
Thanks! Works fine now.
