### ISSUE TITLE
Log the enable/disable execution or scheduled of a Job

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#2245]
# Enhancement request

It could be very useful to add on the rundeck.job.log when a job schedule/execution is enable/disable through the toggle menu. 

![screenshot from 2016-12-20 09-58-00](https://cloud.githubusercontent.com/assets/6034968/21351341/d38d1306-c69a-11e6-82f7-22648a3745ee.png)

**Comment by ahonor** [comment]
+1

**Comment by taneevans** [comment]
+1

**Comment by jim-thavisay** [comment]
+1
