### ISSUE TITLE
Cannot export jobs from version 2.7.1 - There was an error exporting the Project Archive

### ISSUE THREAD

**Issue by daugustus** [rundeck/rundeck#2249]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1
* install type: rpm
* OS Name/version: Centos 6.4

**Expected Behavior**
Should be prompted to download jar file containing export- this worked fine on 2.6.9

**Actual Behavior**

Error message in browser: There was an error exporting the Project Archive - Not Found

**How to reproduce Behavior**
Upgraded from version rundeck-2.6.9-1.21.GA.noarch
Converted to Mysql db, ran export

Note: there is a file created in /tmp/rundeck that appears to be the file that I want even though the name is not the normal pattern: export-drcloud4625764869195072479.jar
Examing the contents of the file reveals that it seems to contain the normal items in an export. 

WORKAROUND - run the export via the browser, wait for the failure, download- via ssh- the latest jar file located in /tmp/rundeck and rename appropriately. 

WORKAROUND - (IMPROVED) after viewing the error message, refresh the browser. I discovered this workaround after this post.

...

**Comment by gschueler** [comment]
is there any error message in the service.log file?

**Comment by daugustus** [comment]
Nothing at all. However, a simple refresh of the browser displays the usable download link of the archive file.

**Comment by gschueler** [comment]
ok, sounds like a bug. thanks for posting the workaround (refresh the page)
