### ISSUE TITLE
Rundeck Segmentation Fault - 2.7.1

### ISSUE THREAD

**Issue by rileym515** [rundeck/rundeck#2250]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1
* install type: rpm 
* OS Name/version: Oracle Linux 7.3 (3.10.0-514.el7.x86_64)

*Details of config:
Using MariaDB backend for Rundeck and nodes DB with in house written plugin which has worked fine throughout.
Projects are stored on an NFS share (ready for use with a Rundeck cluster)
Java version - openjdk version "1.8.0_111"

**Expected Behavior**

Normal behaviour of Rundeck dispatching jobs to multiple nodes at a time.

**Actual Behavior**

When running a job with a thread count of more than 1 the job instantly fails, the Rundeck process goes into a failed state.
I cannot see anything in the logs for Rundeck expect in the service.log with a single line at the end "Segmentation fault".

**Troubleshooting**

We had been working on improvements coming to the new version of Rundeck and had everything working ok but had delayed patching to latest until we were happy. We put on latest patches and this issue appeared. 
So in attempt to clear any odd behaviour I have built from scratch with a fresh VM and the latest Java and Rundeck yet still cannot run a job with the threads set to more than 1.

**How to reproduce**

Run any job with more than 1 thread.

**I think I have learned a fair bit about Rundeck in the last couple of days trying to troubleshoot this but I have to be honest when it comes to Java i know virtually nothing. 

Happy to provide any more info if it will help troubleshoot.

...

**Comment by ahonor** [comment]
@rileym515 does the rundeckd process crash or is that segfault another executable being logged in the service.log?

**Comment by rileym515** [comment]
Hi - thanks for getting back to me.

Pretty sure this is the rundeckd process bombing

Below is the service.log from the time i restart the process, login, kick off a job with 3 threads and then the segfault. 

OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable.
2016-12-23 17:13:03.338:INFO:oejs.Server:main: jetty-9.0.7.v20131107
2016-12-23 17:13:04.828:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
2016-12-23 17:13:05.365:INFO:/:main: Initializing Spring root WebApplicationContext
INFO  GrailsConfigUtils: [GrailsContextLoader] Grails application loaded.
INFO  BootStrap: Starting Rundeck 2.7.1-1 (2016-12-03) ...
INFO  BootStrap: using rdeck.base config property: /var/lib/rundeck
INFO  BootStrap: loaded configuration: /etc/rundeck/framework.properties
INFO  BootStrap: RSS feeds disabled
INFO  BootStrap: Preauthentication is disabled
INFO  BootStrap: Rundeck is ACTIVE: executions can be run.
INFO  BootStrap: Rundeck startup finished in 250ms
2016-12-23 17:13:14.979:INFO:/:main: Initializing Spring FrameworkServlet 'grails'
2016-12-23 17:13:14.997:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@2f0ed952{/,file:/var/lib/rundeck/exp/webapp/,AVAILABLE}{/var/lib/rundeck/exp/webapp}
INFO  ScheduledExecutionService: creating trigger with crontab expression: 0 55 06 ? * * *
2016-12-23 17:13:15.017:INFO:oejs.ServerConnector:main: Started ServerConnector@2cc82c83{HTTP/1.1}{0.0.0.0:4440}
INFO  ScheduledExecutionService: scheduling new job in project MPR1 d257bc78-8f5d-4ad0-8d83-0c5b790fb3ad: 4:14 Day Server Healthcheck
INFO  ScheduledExecutionService: scheduled job d257bc78-8f5d-4ad0-8d83-0c5b790fb3ad. next run: Sat Dec 24 06:55:00 GMT 2016
INFO  ScheduledExecutionService: rescheduled job in project MPR1: d257bc78-8f5d-4ad0-8d83-0c5b790fb3ad
ERROR ExecutionService: Stale Execution cleaned up: [12]
2016-12-23 17:13:37.459:INFO:cdrjj.JettyCachingLdapLoginModule:qtp1989780873-14: Login attempts: 1, Hits: 0, Ratio: 0%.
2016-12-23 17:13:37.464:INFO:cdrjj.JettyCachingLdapLoginModule:qtp1989780873-14: Attempting authentication: uid=mriley,ou=People,dc=nix,dc=williamhill,dc=com
INFO  ScheduledExecutionService: scheduling immediate job run: TEMP:mriley:4:13
Segmentation fault

Below is also the output from systemctl status rundeckd - if of any use

● rundeckd.service - SYSV: rundeckd, providing rundeckd
   Loaded: loaded (/etc/rc.d/init.d/rundeckd; bad; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2016-12-23 17:14:26 GMT; 3min 12s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 5857 ExecStop=/etc/rc.d/init.d/rundeckd stop (code=exited, status=0/SUCCESS)
  Process: 5250 ExecStart=/etc/rc.d/init.d/rundeckd start (code=exited, status=0/SUCCESS)
 Main PID: 5256 (code=exited, status=139)

Dec 23 17:13:03 sc1uxpreap237.prod.williamhill.plc systemd[1]: Starting SYSV: rundeckd, providing rundeckd...
Dec 23 17:13:03 sc1uxpreap237.prod.williamhill.plc rundeckd[5250]: Starting rundeckd: [  OK  ]
Dec 23 17:13:03 sc1uxpreap237.prod.williamhill.plc systemd[1]: Started SYSV: rundeckd, providing rundeckd.
Dec 23 17:14:26 sc1uxpreap237.prod.williamhill.plc systemd[1]: rundeckd.service: main process exited, code=exited, status=139/n/a
Dec 23 17:14:26 sc1uxpreap237.prod.williamhill.plc rundeckd[5857]: Stopping rundeckd: [FAILED]
Dec 23 17:14:26 sc1uxpreap237.prod.williamhill.plc systemd[1]: Unit rundeckd.service entered failed state.
Dec 23 17:14:26 sc1uxpreap237.prod.williamhill.plc systemd[1]: rundeckd.service failed.

Is there any extra logging I could do which would help debug?

**Comment by ahonor** [comment]
@rileym515 what kind of host is this (eg VM)? What are your JVM flags (see /etc/rundeck/profile)?

**Comment by rileym515** [comment]
@ahonor this is a VMware VM with 4CPU and 8GB memory (ESX 6)

Current JVM settings are default

RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx1024m -Xms256m -XX:MaxPermSize=256m -server}"

Only config I have changed is below

RDECK_PROJECTS="/var/rundeck/projects2"
JAAS_CONF="/etc/rundeck/jaas-ldap.conf"
LOGIN_MODULE="ldap"

This build is the hardened one for the company I work for but as the Rundeck I am working on is current build with latest Rundeck and Java I am a bit confused. The strange part is this was working ok on Rundeck v 2.6.7 with a set of patches from around June time it is when we moved to latest EL7 patches on a fresh build that this has come up.
I do plan on spinning up a non corporate build when I get home to look see if I can reproduce this.

**Comment by ahonor** [comment]
You should increase the max heap size as 1024m is really not enough for normal workloads. Try this setting:

```
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx4096m}"
```

**Comment by rileym515** [comment]
Increase in the JVM settings made no difference.

I have found that if I select allow multiple executions then I can run with 2 threads but no more.

**Comment by rileym515** [comment]
@ahonor thanks so much for your help.

I finally tracked down a log for the Java crash dump and on one of the lines found a reference to an agent called Snoopy which had been recently installed on the server and is part of our new build. For some reason this was causing the issue and after removing the agent Rundeck works as expected again.

For reference to anyone in future the log is in /home/rundeck/hs_err_${PID}.log and the line that pointed me to Snoopy begins R14 as below

Register to memory mapping:

RAX=0x0000000000000000 is an unknown value
RBX=0x000000000000000e is an unknown value
RCX=0x0000000000000002 is an unknown value
RDX=0x0000000000000007 is an unknown value
RSP=0x00007f55050cea58 is pointing into the stack for thread: 0x00007f54c801d800
RBP=0x00007f55041c0780 is pointing into the stack for thread: 0x00007f54c8017000
RSI=0x00007f55050cef30 is pointing into the stack for thread: 0x00007f54c801d800
RDI=0x0000000000000002 is an unknown value
R8 =0x00007f55050ceac0 is pointing into the stack for thread: 0x00007f54c801d800
R9 =0x0000000000000009 is an unknown value
R10=0x0000000000000009 is an unknown value
R11=0x00007f5551c2e594: <offset 0x178594> in /lib64/libc.so.6 at 0x00007f5551ab6000
R12=0x0000000000000158 is an unknown value
R13=0x00007f55041c1220 is pointing into the stack for thread: 0x00007f54c8017000
R14=0x00007f55528c87e0: snoopy_inputdatastorage_data+0 in /usr/local/snoopy-2.4.6/lib/libsnoopy.so at 0x00007f55526bd000
R15=0x000000000000000b is an unknown value

**Comment by ahonor** [comment]
@rileym515 thanks for following up.
