### ISSUE TITLE
windows node file-copy-destination-dir

### ISSUE THREAD

**Issue by SolarisYan** [rundeck/rundeck#2253]
Hi there, i install openssh-server on my windows server, and set the node info as follow:

```
<node name="win_server_08_ssh" tags="windows_ssh" hostname="xxx" username="rundeck" ssh-key-storage-path="keys/ssh-key/win-ssh" osFamily="windows" file-copy-destination_dir="C:\\Users\\rundeck"/>
```

and i define a job use inline script, and set it  executed as: powershell -File " ${scriptfile} ", when i run this job, it shows the info as 
The argument 'C:\Users\rundeck\317-2391-win_server_08_ssh-dispatch-script.tmp.ps1' to the -File parameter does not exist. Provide the path to an existing '.ps1' file as an argument to the -File parameter.

and i find the script in path C:\Users\rundeck  with name "CUsersrundeck317-2391-win_server_08_ssh-dispatch-script.tmp.ps1".  how strange it is.

my rundeck version is 2.6.9-1.

does it a bug? anyone colud help me. thanks a lot

**Comment by SolarisYan** [comment]
get it,the  file-copy-destination_dir="C:\\Users\\rundeck"  shuold be set C:/Users/rundeck/
that't ok

**Comment by SolarisYan** [comment]
another issue, on my windows server 2008, the job not exit when the script execute over, but on my own win10 system, it work fine. does it relate with the powershell version?

**Comment by ahonor** [comment]
Please reopen if this remains a concern
