### ISSUE TITLE
Rundeck should provide "expect"-style functionality

### ISSUE THREAD

**Issue by ashortland** [rundeck/rundeck#226]
Rundeck should be able to automate execution of programs that require terminal interaction (i.e. negotiate a "dialog" on the the connection's I/O channels).

This [expect](http://www.tcl.tk/man/expect5.31/expect.1.html)-style functionality would satisfy a number of common use cases such as responding to a password prompt (sudo, mysql, etc).

**Comment by ahonor** [comment]
Sudo prompt is supported. Anything else should be handled by the step plugin.
