### ISSUE TITLE
2.7.1: Job to multiple hosts never complete

### ISSUE THREAD

**Issue by admun** [rundeck/rundeck#2261]
# Bug report

Not sure this already reported/fixed, but it's a serious bug....
see report from https://groups.google.com/forum/?pli=1#!topic/rundeck-discuss/RylpjkgmBIg

* Rundeck version: 2.7.1 (upgraded from < 2.7.0)
* install type: launcher
* OS Name/version: OEL/RHEL 6

This looks like the H2/MySQL DB schema mismatch with some insert actions, or in-place schema upgrade failed to update schema for the changed fields.

**Expected Behavior**

Job should completed after executed at all nodes

**Actual Behavior**

Job hang and report over 100% done, and H2 SQL error are observed from log

For error log observed, see google group thread above

**How to reproduce Behavior**

1. Create a job execute on multiple nodes
2. Run it

**Comment by admun** [comment]
Note, I get around this issue by dropping the DB file and confirm the newly create DB does not have this issue.

So, it's feel like the in-place schema upgrade didn't work.

**Comment by jamieps** [comment]
This looks like a duplicate of #2228 - it is fixed in 2.7.2 via #2232 (not yet released) for new installations, if you don't mind losing all your data(!). Currently you have to alter the table schema manually for existing installations.

**Comment by aristosv** [comment]
@jamieps 
do you know what commands must run on debian to alter the table schema?
thanks

**Comment by jamieps** [comment]
@aristosv that depends on which database you're using, MySQL, postgresql or H2.

:warning: I'd recommend backing up the data first, although there's little chance of data loss IMO it's better to err on the side of caution.

For MySQL:

```
$ mysql -u <username> -p <database name>
> ALTER TABLE base_report MODIFY COLUMN filter_applied LONGTEXT;
> ALTER TABLE base_report MODIFY COLUMN succeeded_node_list LONGTEXT;
> ALTER TABLE base_report MODIFY COLUMN failed_node_list LONGTEXT;
```

Then `desc base_report;` should show:

```
| failed_node_list    | longtext      | YES  |     | NULL    |                |
| filter_applied      | longtext      | YES  |     | NULL    |                |
| succeeded_node_list | longtext      | YES  |     | NULL    |                |
```

For postgresql, this should work:

```
$ psql -U <username> -d -W <database name>
rundeck=> ALTER TABLE base_report ALTER COLUMN filter_applied TYPE TEXT;
ALTER TABLE
rundeck=> ALTER TABLE base_report ALTER COLUMN succeeded_node_list TYPE TEXT;
ALTER TABLE
rundeck=> ALTER TABLE base_report ALTER COLUMN failed_node_list TYPE TEXT;
ALTER TABLE
```

Then `\d base_report` should show:

```
 failed_node_list    | text                        |
 filter_applied      | text                        |
 succeeded_node_list | text                        |
```

For H2 you'll need to use the H2 client (this is untested):

```
ALTER TABLE base_report ALTER COLUMN filter_applied CLOB;
ALTER TABLE base_report ALTER COLUMN succeeded_node_list CLOB;
ALTER TABLE base_report ALTER COLUMN failed_node_list CLOB;
```

**Comment by aristosv** [comment]
I don't have access to the machine to test it right now, but I simply installed the deb file located here http://rundeck.org/downloads.html So I'm using whatever the default installation is using.

**Comment by jamieps** [comment]
H2 is the default and I'm not that au fait with it. The last set of commands will work but you'll need to use the H2 client to run them.

There's some information on the command line client here: http://www.h2database.com/html/tutorial.html

**Comment by admun** [comment]
Hi @jamieps 

Indeed, this is a dup of #2228 Me bad.

I'm still in a pre-production mode, so I can afford to lose the DB. In fact, my setup right now not migrating the DB to each deployment.

I will wait for 2.7.2.
