### ISSUE TITLE
bash script on a single Linux computer runs for ever

### ISSUE THREAD

**Issue by aristosv** [rundeck/rundeck#2267]
# Bug report

**My Rundeck detail**
* Rundeck version: rundeck-2.7.1-1-GA
* install type: deb
* OS Name/version: debian 8.6

**Expected Behavior**
run bash script (on a single computer) and complete successfully.
```
#!/bin/bash
# import variables
source "${BASH_SOURCE%/*}/variables"
# loop & shuffle
while true
do
 for audio in $(ls $localaudiomedia/* | shuf)
 do
 echo "playing $audio"
 omxplayer --no-osd $audio > /dev/null
 done
done
```
**Actual Behavior**
the script runs, but never completes. It shows "running" status for ever.

**How to reproduce Behavior**
run the bash script on a Linux computer, using rundeck.

**Comment by LoovtO** [comment]
> while true
This is always true, your script will never complete.

**Comment by aristosv** [comment]
same thnig happens with this script
```
#!/bin/bash
# import variables
source "${BASH_SOURCE%/*}/../variables/general"
echo "starting stream"
omxplayer --no-osd --loop $(youtube-dl -g $(cat $localstreammedia/youtube.txt)) > /dev/null
```

**Comment by aristosv** [comment]
Also, the script is run with & at the end, so it drops in the background.

**Comment by aristosv** [comment]
running it like this solved the issue
`> /dev/null 2>&1 &`
