### ISSUE TITLE
API: support "asUser" for listing nodes

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#2270]
Currently API only supports "asUser" for `running jobs` and `running ad-hoc commands`.

If "asUser" for `listing nodes` is supported, then #2255 will be possible through remote option.

**Comment by gschueler** [comment]
`asUser` does not change authorization, only records a different username for adhoc/job executions. IMO `asUser` for listing nodes would not achieve what you want. for #2255 I think we should add that internally so it wouldn't have to use remote url option anyway.  

Additionally, the `asUser` for jobs/adhoc is probably going to be deprecated. We now have user and service API tokens, which allows another username to be used with a token.  I think we should improve recording of the "user" who performs the action (adhoc/job run or kill) to include the user "name" as well as any auth token origin name (i.e. who created the token, or the token ID), this will accurately record the authorization info, as well as the user for whom the action was performed "on behalf of"

I am going to close this, but if you have another reason for this feature, please reopen. thanks.
