### ISSUE TITLE
Scheduled job executions broken after restart

### ISSUE THREAD

**Issue by shoelzle** [rundeck/rundeck#2271]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.0-1
* install type: launcer
* OS Name/version: Debian Wheezy

**Expected Behavior**

One-time scheduled job executions continue after rundeck server restart.

**Actual Behavior**

One-time scheduled job executions are still present after a rundeck server restart, however they don't continue and thus are not executed

**How to reproduce Behavior**

1. Schedule job for a one-time run (button: run job later)
2. Restart rundeck server

...

**Comment by jamieps** [comment]
@shoelzle  Can you check if there are any errors in your `service.log`?

**Comment by willemdh** [comment]
Fyi, I have the same problem.

**Comment by jamieps** [comment]
Is this scheduled jobs, as in using a fixed crontab schedule, or a one-off ad hoc scheduled job (using 'Run Job Later')?

**Comment by shoelzle** [comment]
@jamieps , this only happens with one-off ad-hoc scheduled jobs. I'll clarify this in the issue description.

**Comment by shoelzle** [comment]
@jamieps , I'll check the logs in a few days.

**Comment by jamieps** [comment]
Does your job have secure input options? Those cannot be rescheduled automatically at startup (currently), if so it should log a warning to that effect.

**Comment by shoelzle** [comment]
@jamieps ,the logs say:
```
2017-01-10 10:55:13,999 ERROR ScheduledExecutionService - Ad hoc job not rescheduled: DeploymentBatch: getAuthContextForUserAndRoles: Cannot get AuthContext without user, roles: null, []
2017-01-10 10:55:14,023 ERROR ScheduledExecutionService - Ad hoc job not rescheduled: DeploymentBatch: getAuthContextForUserAndRoles: Cannot get AuthContext without user, roles: null, []
2017-01-10 10:55:14,024 ERROR ScheduledExecutionService - 2 ad hoc scheduled executions could not be rescheduled and will be killed
```
Secure input options are not in use here.

**Comment by gschueler** [comment]
this error: `Cannot get AuthContext without user, roles: null, []`  was mentioned in #2167 I think there is a bug with the ad hoc scheduled jobs

**Comment by Kurisutian** [comment]
I also have this very same bug.

**Comment by gschueler** [comment]
see #2167
