### ISSUE TITLE
any plans for a mobile application?

### ISSUE THREAD

**Issue by aristosv** [rundeck/rundeck#2272]
Are there any plans for a mobile application that can be used to manage a rundeck server? Something that will run on a phone, connect on a rundeck server and allow the execution of jobs/commands?

**Comment by osgav** [comment]
Hey @aristosv - try asking this question in the rundeck-discuss group or the Rundeck Development Trello board, both of these are linked to on the Roadmap: https://github.com/rundeck/rundeck/wiki/Roadmap

**Comment by miguelantonio** [comment]
Hey @aristosv I built one, would you be interested in beta testing it? :) shoot me an email -> miguel@variacode.com

**Comment by miguelantonio** [comment]
We released public beta for Android devices a few days ago: https://play.google.com/store/apps/details?id=com.variacode

iOS to follow in a few days more

**Comment by pb1981** [comment]
@miguelantonio Not getting the Rundeck app in play-store..

**Comment by miguelantonio** [comment]
@pb1981 the app was discontinued until further notice sadly
