### ISSUE TITLE
prompt user for information before running job

### ISSUE THREAD

**Issue by aristosv** [rundeck/rundeck#2274]
I want to set up a rundeck job, to modify a URL in a file. I need a way for the user to be able to input the url before executing the job. This is how I'm doing it now, through the terminal. But I need a way through rundeck for the user to be able to define the www.new-url.com

`sed -i "s/www.old-url.com/www.new-url.com/g" /home/user/url.sh`

**Comment by jamieps** [comment]
@aristosv see: http://rundeck.org/docs/manual/jobs.html#job-options

**Comment by aristosv** [comment]
ok I'm having some trouble with this, because I want to force the user to enter a URL, and I can only force the user by defining Allowed Values or by Matching Regular Expression. This limits the user from entering any URL they want. Any workarounds for this?

**Comment by gschueler** [comment]
@aristosv make the option required if you do not want to restrict the value, but want to require it to be entered.  

closing, this is not an issue.  please post on the rundeck-discuss list for usage questions
