### ISSUE TITLE
¿Timeout by node?

### ISSUE THREAD

**Issue by albertovar** [rundeck/rundeck#2276]
# Bug report
Hello.

Is there a way to set a timeout per node?

Thank you very much

**My Rundeck detail**

* Rundeck version: 2.6.11-1.23
* install type: rpm
* OS Name/version: RHEL 7.2

**Expected Behavior**

___

**Actual Behavior**

___

**How to reproduce Behavior**

___

# Enhancement request

(*For enhancements*: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by jamieps** [comment]
If you're using jsch (SSH) to connect, then you could try specifying this as a per-node attribute to SSH (see http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html#specifying-ssh-config-options), either in `resources.xml` or in your node resource model source. Example:
```xml
<node name="localhost" ssh-config-ConnectTimeout="30" ... />
```
I have used this before to override SSH attributes per-node but I haven't set the timeout specifically.

**Comment by ahonor** [comment]
Please reopen if this remains a concern
