### ISSUE TITLE
Navbar invisible on mobile devices

### ISSUE THREAD

**Issue by mrala** [rundeck/rundeck#2278]
# Bug report

**My Rundeck detail**

* Rundeck version:  2.7.1
* install type: rpm
* OS Name/version: CentOS 6/7

**Expected Behavior**
The navbar should be visible when using a mobile device.
___

**Actual Behavior**
The navbar is invisible when using a mobile device.
___

**How to reproduce Behavior**
Open the page on a mobile device and non-mobile device. Please see screenshots.

<img width="868" alt="non-mobile_rundeck" src="https://cloud.githubusercontent.com/assets/4516025/21936412/0b973488-d97f-11e6-97a8-fa63d09bdca6.png">
<img width="386" alt="mobile_rundeck" src="https://cloud.githubusercontent.com/assets/4516025/21936421/134516b4-d97f-11e6-8045-96cc2b17d71a.png">
___

**Comment by mrala** [comment]
Is there any additional info I can provide that would help?

**Comment by charlesmims** [comment]
Rundeck 2.6.11-1 is similarly afflicted.  Reproduced on iphone 6s-plus, latest versions of chrome and safari.
