### ISSUE TITLE
Unable to use git over ssh

### ISSUE THREAD

**Issue by rileym515** [rundeck/rundeck#2284]
# Bug report

(Note: Please fill in the blank `___` about your rundeck installation below. You can remove this line.)

**My Rundeck detail**

 Rundeck version:  install type: rpm
 OS Name/version: Oracle Linux Server release 7.3

**Expected Behavior**
Use the SCM plugin to export to GiT

**Actual Behavior**
When specifiying the ssh://git@git.local URL in SCM export config I get "Exception caught during execution of fetch command "

If I instead just use the git@git.local without the prepend then the config seems to work ok.

**How to reproduce Behavior**
Try to use the ssh version of the plugin

I know the keys i am using work as these are the ones I use to clone repos to my local box for other projects and I was able to pull the repo I made ready for this over ssh on command line with no issues.

I am trying to figure out the difference between the ssh://git@git and the git@git as I assume the fetch is just a git clone in background?

Config below

![image](https://cloud.githubusercontent.com/assets/24736069/22020858/4e68ae0a-dcb2-11e6-8c24-9e5ff81ba206.png)

...

**Comment by gschueler** [comment]
Can you include the error you get?

**Comment by rileym515** [comment]
Sorry for the delay - it seems the original error was a problem with my GiT repo.

But when I have tried to push the job up remotely i am getting a java error which i am afraid is over my head. Going to look into it but below is a screen grab. The job has gone into the scm dir as expected but remote push has failed.

Has anyone seen this before??

I can also post the entire stack trace if required.

![image](https://cloud.githubusercontent.com/assets/24736069/22146412/7974a562-defc-11e6-8609-490ed554fcff.png)

**Comment by ahonor** [comment]
@rileym515 Did you resolve this?

**Comment by rileym515** [comment]
Sorry I completely forgot to close this issue. 

It turned out to be the internal firewall setup of the company I was working for. There were policies locking this down which could not be changed.

Thanks for the help all.
