### ISSUE TITLE
Broken error message of invalid option value, probably due to apostrophe in message

### ISSUE THREAD

**Issue by rophy** [rundeck/rundeck#2290]
# Bug report

* Rundeck version: 2.7.1
* install type: rpm
* OS Name/version: centos 7

**Expected Error Message**

```
Option ProjectName value: IoT Foundation/asdf doesn't match regular expression: ^[\w\s-_]+$]
```

___

**Actual Error Message**

```
Option [ProjectName, IoT Foundation/asdf, ^[\w\s-_]+$] value: {1} doesnt match regular expression: {2} Option 'PMUsernames' is required.
```
___

**How to reproduce Behavior**

1. Create a job option with regular expression: `^[\w\s-_]+$]`
2. Run the job with option value: `IoT Foundation/asdf`

Note that the apostrophe in `doesn't` is lost, I suspect that might be the cause for broken message?

**Comment by gschueler** [comment]
also message generation fixes via https://github.com/rundeck/rundeck/pull/2227
