### ISSUE TITLE
[ Unable to access Rundeck API ]

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#2291]
Hello,

I just made a fresh RPM install of Rundeck 2.7.1 on a Centos 7.2 host

The install worked fine, I can login, run jbs, scripts, etc ...

But I can't figure out how to access the API.
I try this kind of URL http://myhost:4440/api/2/system/info and I get a 404 not found error.
(when I log into Rundeck, I get this URL http://myhost:4440/menu/home)

I have an older install of Rundeck 2.1 on another machine and this request just works fine.

What am I doing wring ?

Thank you for your help

Best regards
Jérôme

**Comment by gschueler** [comment]
do you mean you are entering the API url in your browser? by default, rundeck disables API access if you log in through a web browser, try from commandine/curl

**Comment by jerome83136** [comment]
Yes, I was trying to access the API from my browser.

It works fine with curl thanks.

Closing
Regards

**Comment by Youans** [comment]
@gschueler What do you mean by disabled by default my case that I need to use cookie authentication to call API method from my website, Is that doable?

**Comment by sjrd218** [comment]
@Youans Add the setting: `rundeck.security.apiCookieAccess.enabled=true` to your rundeck-config.properties and see if that works.

**Comment by ajgeek** [comment]
HI 
I am firsttime user for rundeck,  i have installed using launcher in unix shell , i am unable to launch the api url but after the login its not able to navigate to the default dashbaord view . can anyone guide me with this. PFB SS
![rundeck_error](https://user-images.githubusercontent.com/42539624/44383361-26a58980-a536-11e8-9613-b46fd2d498e0.PNG)
