### ISSUE TITLE
Job execution details do not include all nodes

### ISSUE THREAD

**Issue by ajxb** [rundeck/rundeck#2293]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1-1  ("cafecito steelblue leaf" 2016-12-03)
* install type: rpm
* OS Name/version: CentOS release 6.7 (Final)

**Expected Behavior**
The RunDeck job execution details should accurately reflect all of the nodes that have been deployed to as part of a job execution and should allow navigation of all of the steps that have been executed on said nodes.  This information should tie in with that seen for the job execution on the activity tab.

**Actual Behavior**
The RunDeck job execution seen below reports that the job completed with success on 146 of 146 nodes, when in fact it has been executed on 147 nodes:

![image](https://cloud.githubusercontent.com/assets/1756536/22294125/fcdd4c0e-e309-11e6-817b-1583dc14ae35.png)

Looking at the Report tab I can see that node PVW-WEB-SB01-10.214.1.221 is not included in the data shown on this page:

![image](https://cloud.githubusercontent.com/assets/1756536/22294523/7f865a28-e30b-11e6-8e3e-354c7538f340.png)

I have compared to the information that is shown on the Activity tab for the job execution, and you can see that it reports that the job completed on 147 nodes:

![image](https://cloud.githubusercontent.com/assets/1756536/22294168/260c854a-e30a-11e6-9e26-4b07990eebc2.png)

Furthermore, an email notification sent by the tool includes the node missing from the job execution details page, see attached file : [RUNDECK  Bet.Net - Deploy - Release - BetNet-v1-SBS-Release.2.90.1 - prod - succeeded.zip](https://github.com/rundeck/rundeck/files/729977/RUNDECK.Bet.Net.-.Deploy.-.Release.-.BetNet-v1-SBS-Release.2.90.1.-.prod.-.succeeded.zip)

I've taken a look brief look over the job logs [87380.zip](https://github.com/rundeck/rundeck/files/729988/87380.zip), and have spotted the following which may be of interest:
* In 87380.state.json - References to PVW-WEB-SB01 appear 143 times whereas for a sample subset of other nodes there is always 202 references
* In 87380.state.json - The data for PVW-WEB-SB01 seems to be muddled with PROD-VW-WEB27 whereas for a sample subset of other nodes there is always a one to one reference to only the node in questions, see for example `ROOT.nodes.PVW-WEB-SB01-10.214.1.221[29]` includes details about executionState of PROD-VW-WEB27.  Similarly there seems to be a combination of data at `ROOT.steps[0].parameterStates.node=PROD-VW-WEB27-10.214.0.93.workflow.steps[0].workflow.steps[0].nodeStates` and at other places too.
* In 87380.rdlog - References to PVW-WEB-SB01 appear 625 times whereas for a sample subset of other nodes there is always 1193 references

[rundeck.log.zip](https://github.com/rundeck/rundeck/files/730052/rundeck.log.zip) indicates a ConcurrentModificationException associated with this job execution.

The job workflow we are using has multiple sub-workflows with the top level job responsible for setting up the nodes that are to be executed.  If it's of any use I've attached the associated jobs [jobs.zip](https://github.com/rundeck/rundeck/files/730064/jobs.zip).

**How to reproduce Behavior**

Unsure, this is the first time I've seen this behaviour.

**Comment by gschueler** [comment]
thanks for the detail, the exception might be the cause, but i am unable to expand the zip file you attached (some problem with the compression?).  perhaps use a gist

**Comment by ajxb** [comment]
Hi,  I've recreated all the zips under the following, 
[2293.zip](https://github.com/rundeck/rundeck/files/735738/2293.zip)

If this doesn't work for you I'll try to create a gist capturing the relevant information.

**Comment by ahonor** [comment]
Please reopen if this remains an issue
