### ISSUE TITLE
Jobs do not display by default anymore when entering into a Project

### ISSUE THREAD

**Issue by AndyBerman** [rundeck/rundeck#2296]
**My Rundeck detail**

* Rundeck version: 2.7.1-1
* install type: war
* OS Name/version: Windows 2012

**Expected Behavior**
When we were running on Rundeck 2.4,2.5 and 2.6, when I clicked on a project it showed all the jobs in that project by default.
___

**Actual Behavior**
When I do that under 2.7, it shows a blank page instead.  Here's an example URL for project ABC:
https://rundeck.mycompany.org:4443/project/ABC/home

I know I can click on "Jobs" on the top of them screen to go to:
https://rundeck.mycompany.org:4443/project/ABC/jobs,

But the end users starting at the home page click on the links there which take them to the blank home page.
___

# Enhancement request

Is there a way to get the main page links to go to the "jobs" page instead of the home page?

**Comment by gschueler** [comment]
yes configure the `rundeck.gui.startpage` http://rundeck.org/docs/administration/gui-customization.html

**Comment by AndyBerman** [comment]
I added "rundeck.gui.startpage = jobs" and that set it as desired.
Thanks!
