### ISSUE TITLE
Killing (GUI) or aborting (API) a scheduled job makes the job in "never fire" schedule state

### ISSUE THREAD

**Issue by hjdr4** [rundeck/rundeck#2300]
Hello,

From Rundeck >= 2.6.11,  I have a serious issue with scheduled jobs.
 - I prepare a scheduled job that runs every minute, limited to 1 execution at a time.
- The job is an infinite loop. Scheduler starts the job.
- If I kill the job via GUI or abort the job using API, the schedule state becomes 'Never'
- Editing the task, touching nothing but pressing 'save' button makes the task schedules again.

It breaks every deployment pipelines we use.

Was working as expected using 2.6.9.

**Comment by nilroy** [comment]
@gschueler when can we expect rundeck 2.7.2. This bug is scary and it would hinder me upgrading rundeck at this moment

**Comment by hjdr4** [comment]
Same question about release date.
I'm stuck to 2.6.9 because of this bug.
But 2.6.9 GET  /api/14/project/[PROJECT]/jobs API is broken :/

**Comment by gschueler** [comment]
@nilroy we are planning to release this week
