### ISSUE TITLE
Empty option with default value

### ISSUE THREAD

**Issue by liszi** [rundeck/rundeck#2301]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.9-1
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux Server release 6.8

**Expected Behavior**
A job has an "inline script" step with only one line: echo "value:@option.opt@". This job has an option with a default value. If on Prepare and Run tab the default value is deleted (before running the job), the option should appear as an empty string during the job run.

**Actual Behavior**
Before running the job I delete the default value on the Prepare and Run tab, but the option will use the default value, instead of an empty string.

**How to reproduce Behavior**
1. _Import_ the next yml file as a job:  
[default_test.txt](https://github.com/rundeck/rundeck/files/739200/default_test.txt) (you should modify the extension back to yml, txt is just because of the uploading.)
2. Click the job, leave the default value of the _opt_ option.
3. Run the job. It will print _value:defval_
4. Click on _Run again_
5. Remove the _defval_ string from _opt_ option.
6. Run the job again. It will pring _value:defval_ again, instead of the _value:_ .

**Comment by martinbydefault** [comment]
I've experienced the same behavior with 2.8.1-1 rundeck version.  
In my situation I'm using options to pass them as extra vars to an ansible playbook (using this plugin https://github.com/Batix/rundeck-ansible-plugin).  
I've defined default options just to facilitate the user, but if none of the default options are selected, the extra variable should be passed as empty.  
What is happening now is that if I dont check any value, all defaults values are passed to the extra var.

**Comment by padraiglennon** [comment]
I'm running into the same issue as @martinbydefault on 3.0.24

**Comment by maturbet** [comment]
Still present on 3.2.2

`<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option delimiter='-' enforcedvalues='true' multivalued='true' name='OPT' value='a' values='a,b' valuesListDelimiter=',' />
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>60b895e4-ec3a-472e-b310-358bfa73891d</id>
    <loglevel>INFO</loglevel>
    <name>JOB1</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo ${option.OPT}</exec>
      </command>
    </sequence>
    <uuid>60b895e4-ec3a-472e-b310-358bfa73891d</uuid>
  </job>
</joblist>`
