### ISSUE TITLE
rundeck-cli: JSON format includes description for project list

### ISSUE THREAD

**Issue by gentunian** [rundeck/rundeck#2303]
# Bug report

This may not be a bug but a functionality issue.

When invoking the command `projects` from the `rd` utility with `RD_FORMAT=json` the project name and project description are concatenated. Trying using `-v` option won't work. One should expect to receive a `JSON` object with not mixed values.

**My Rundeck detail**

* Rundeck version: 2.7.1 and rundeck-cli-1.0.5-1
* install type: rpm
* OS Name/version: RHEL 7

**Expected Behavior**

It's expected to receive as output project names, like the following:

```
$ RD_FORMAT=json rd projects
[ "ProjectA", "ProjectB", "ProjectC" ] 
```

or in the best case:
```
$ RD_FORMAT=json rd projects -v
[
   { "name": "ProjectA", "description": "ProjectA description" },
   { "name": "ProjectB", "description": "ProjectB description" },
   { "name": "ProjectC", "description": "ProjectC description" },
]
```

**Actual Behavior**

Each element of the array is being concatenated with project description, just like:

```
$ RD_FORMAT=json rd projects
[ "ProjectA: ProjectA description", "ProjectB: ProjectB description", "ProjectC: ProjectC description" ]
```

**How to reproduce Behavior**

Run `rd projects`

**Comment by gschueler** [comment]
thanks for the report, I will fix it.  It should allow the `-%/--outformat` flag for text output, and default to more sensible json output

**Comment by gschueler** [comment]
closing and re-filed in rundeck-cli project:
https://github.com/rundeck/rundeck-cli/issues/68
