### ISSUE TITLE
Tomcat: Project Archive export does not complete

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2309]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1-oss & 2.0.0-pro
* install type: war/tomcat
* OS Name/version: mac os x

**Expected Behavior**

Project archive action works

**Actual Behavior**

Project archive action goes to Waiting page, but never progresses

**How to reproduce Behavior**

Click "Export project.rdproject.jar" from Archive Export tab in Configure page

**Comment by ltamaster** [comment]
I checked it , it worked OK !!
