### ISSUE TITLE
.topbar background defined in file configuration rather than CSS

### ISSUE THREAD

**Issue by asyd** [rundeck/rundeck#231]
Hi,

we are using a lot of RunDeck, in different environment (dev, testing, production). We used to distinguish them by using differents colors in tools webinterface. 

While it's easy to override RunDeck CSS, having the possibility to define the topbar background color in rundeck configuration will be more easy for us, and probably for other people too. Indeed, we used to deploy the same OS package in all environment, so at the moment we need to apply an ugly patch :)

**Comment by ahonor** [comment]
Reopen if anything more is required.
