### ISSUE TITLE
[feature] Rundeck login session more longest

### ISSUE THREAD

**Issue by zodman** [rundeck/rundeck#2311]
with ldap+ rundeck
the login session expire in small amount of time. need maintaing session forever options on login 

...

**Comment by gentunian** [comment]
Hi @zodman 

You can change the session timeout from:

`RUNDECK_HOME/exp/webapp/WEB-INF/web.xml`

if you use a .rpm installation:

` /var/lib/rundeck/exp/webapp/WEB-INF/web.xml`

Locate the tag: 

```
<session-config>
	<session-timeout>60</session-timeout>
    </session-config>
```

Hope this helps :)

**Comment by zodman** [comment]
<3
