### ISSUE TITLE
Unable to use global variable in Remote Option URL port number

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2312]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.6.11 and 2.7.1
* install type: any
* OS Name/version: any

**Expected Behavior**

Using global variable in the port number of an option values URL should work.

**Actual Behavior**

GUI fails to save the change. javascript error:

    POST http://ecto1.local:4440/editOpts/save?project=ctest&jobWasScheduled=false 500 (Server Error)
    send @ jquery.js?compile=false:8706
    ajax @ jquery.js?compile=false:8136
    _optsave @ jobedit.js?compile=false:525
    onclick @ 280a8afb-5fa9-451d-a2bc-df5852b06cfe:1

Yaml upload fails to validate:

    $ rd jobs load -p ctest -f 280a8afb-5fa9-451d-a2bc-df5852b06cfe.yaml --format yaml
    Error: Jobs Document was invalid for format yaml: rundeck.controllers.JobXMLException: Unable to create Job: For input string: "${globals.service_port}"
    [code: api.error.jobs.import.invalid; APIv18]

**How to reproduce Behavior**

Set the remote option value URL for an option to something like: `http://localhost:${globals.test_port}/path`

**Comment by puremourning** [comment]
Took a brief look at [the code](https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/domain/rundeck/Option.groovy#L167-L169).

I guess the issue is that the java.net.URL strictly validates (and requires RFC2396 addresses), and thus validates on construction (attempting to convert the context variable syntax to an int; fails). Other context variables (outside of the port itself) are technically valid RFC2396.

I guess the solution is to use String rather than URL here in Options.groovy and convert to URL when needed (in TBA locations!). This sounds like a chunk of work. Do you think that's the right solution? If so I might pursue it, as this is quite important for my project.

**Comment by gschueler** [comment]
@puremourning yes i think we need to change to use a string instead of URL to store the value.  For grails db update purposes (until we have db-migration set up), it might work to simply change the field to String.  If that doesn't work, could add a new String field, and have some logic in the Options class to use that field instead of the URL field.

URL was only used I think for the validation purposes in the first place, so the validation would have to be revamped.  The place where the URL is used is only in the code which loads the remote json.

**Comment by puremourning** [comment]
FYI I have changed this locally (from URL type to String) and it seems to work.

**Comment by mumblez** [comment]
just to confirm, can I not do something like setting a globals to `project.globals.options_server=localhost:5555/options` ?
would I have to set the port and path separately?

**Comment by puremourning** [comment]
you can do this:

```
project.globals.options_server=localhost:5555
```

then you can set the option provider to:

```
valuesUrl: http://${globals.options_server}/options/....
```

Which is what we ended up doing.

What you _can't_ do is just configure the _port_ in a global.

**Comment by mumblez** [comment]
@puremourning thanks for the quick response, that works 👍

**Comment by puremourning** [comment]
you're welcome.

**Comment by mcassaniti** [comment]
I tried this in a global variable instead and I do have a port configured (i.e.: `server:port`). I'm finding that the colon gets URL encoded for version 3.2.8 (i.e.: `server%3Aport`).

**Comment by puremourning** [comment]
Using global still works for me on rundeck 3.2.8.

**Comment by mcassaniti** [comment]
Ahhh, that might explain something. Let me do a bit more testing and I will confirm. If it does I've suddenly saved a whole bunch of time trying to separate out our TEST and PROD environments.

**Comment by mcassaniti** [comment]
So I've successfully tested on 3.2.8 and got the expected results. I did hit the failure issue @puremourning mentioned, but I am successfully hitting the URL.
