### ISSUE TITLE
PAM auth working just for user rundeck (admin: user unknown)

### ISSUE THREAD

**Issue by kappacher** [rundeck/rundeck#2315]
# Bug report

**My Rundeck detail**

* Rundeck version: 2711
* install type: rpm (rpm,deb,war,launcher)
* OS Name/version: CentOS/7.2

**Expected Behavior**
PAM authentication (during rundeck web/webapi login) should work for all users that can login with ssh and also belong to extra group "user".
Question: Is PAM auth possible with owning user rundeck for service rundeckd? Or do i need user root?
___

**Actual Behavior**
PAM auth only works for user rundeck (owner of rundeckd), because pam_unix.so calls unix_chkpwd. unix_chkpwd is hardened in such way that only the calling user may authenticate himself. (uid/euid must match against provided username in passwd db). Thus, changing group or permissions of /etc/shadow does not help, group shadow is not honored (no special group).
___

**How to reproduce Behavior**
Fresh RPM install (CentOS 7.2) with as many defaults as possible.
Login with default user admin / admin working out-of-the-box.
Create linux user admin.
CentOS: change password for users admin & rundeck (setting username=password) and supply extra group "user" to them (just to be sure because of secure-login role in web.xml).
Change just 1 file /etc/rundeck/jaas-loginmodule.conf:
RDpropertyfilelogin {
org.rundeck.jaas.jetty.JettyPamLoginModule required
debug="true"
service="sshd"
useUnixGroups="true";
};

Login with user rundeck is working (as expected), but login with user admin fails:
/var/log/secure:
localhost unix_chkpwd[4110]: check pass; user unknown
localhost unix_chkpwd[4110]: password check failed for user (admin)
localhost java: pam_unix(sshd:auth): authentication failure; log
name= uid=1001 euid=1001 tty= ruser= rhost=  user=admin
id Cmd shows: uid=1001(rundeck)

# Enhancement request

(*For enhancements*: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.)

...

**Comment by SergeyBear** [comment]
+1

**Comment by zfredrickson** [comment]
+1
Just ran into the same

`Apr 14 18:48:38 localhost unix_chkpwd[28248]: check pass; user unknown
Apr 14 18:48:38 localhost unix_chkpwd[28249]: check pass; user unknown
Apr 14 18:48:38 localhost unix_chkpwd[28249]: password check failed for user (zfredrickson)
Apr 14 18:48:38 localhost java: pam_unix(sshd:auth): authentication failure; logname= uid=541 euid=541 tty= ruser= rhost=  user=zfredrickson`

541 is "rundeck" user

**Comment by tessercat** [comment]
So doesn't this mean that PAM auth just doesn't work on CentOS 7 for any user except the rundeck user? If so, can you mention something in the documentation so people don't waste massive amounts of time trying to implement something that just doesn't work?

**Comment by sys-ops** [comment]
@tessercat I used the following configuration file:

\# cat /etc/rundeck/jaas-pam.conf 
pamlogin {
  org.rundeck.jaas.jetty.JettyPamLoginModule requisite
        debug="true"
        service="sshd"
        supplementalRoles="readonly"
        storePass="true";

  org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
        debug="true"
        useFirstPass="true"
        file="/etc/rundeck/role.properties";
};

https://rundeck.org/2.10.6/administration/authenticating-users.html#pam

You will find examples of JettyRolePropertyFileLoginModule file down that page.

It works for me and I hope it helps in your case.

**Comment by tessercat** [comment]
@sys-ops I've put what the docs recommend in /etc/rundeck/jaas-loginmodule.conf and I tried exactly what you suggest in /etc/rundeck/jaas-pam.conf (after renaming variables in /etc/rundeck/profile) using Rundeck 3.0.7-20181008 on both CentOS 7.5 and Debian 9.5 to no effect. Logs show the same error encountered by @zfredrickson. Not sure what you're doing that we aren't. Using a different OS? You didn't say which OS you're using. Maybe your unix_chkpwd is different or you've done something to it to loosen security.

**Comment by jospradlin** [comment]
As many have indicated above, on CentOS 7 -- once the PAM config is implemented, the 'rundeck' OS user account can -authenticate- with RunDeck.   However, no other user can whatsoever.    Not exactly useful in it's current state.
