### ISSUE TITLE
Missing dependency on uuid-runtime in debian package since 2.7.2

### ISSUE THREAD

**Issue by schans** [rundeck/rundeck#2316]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.2
* install type: deb
* OS Name/version: Debian

**Expected Behavior**
apt-get upgrade succeeds without error

**Actual Behavior**
Setting up rundeck (2.7.2) ...
usermod: no changes
/var/lib/dpkg/info/rundeck.postinst: 88: /var/lib/dpkg/info/rundeck.postinst: uuidgen: not found
dpkg: error processing rundeck (--configure):
 subprocess installed post-installation script returned error exit status 127
Errors were encountered while processing:
 rundeck

After installing the package uuid-runtime with "apt-get install uuid-runtime" which contains the command uuidgen the rundeck upgrade succeeds.

**How to reproduce Behavior**
Upgrade to 2.7.2 on a debian machine.

...

**Comment by schans** [comment]
This is the commit that introduces the dependency on uuidgen:

https://github.com/rundeck/rundeck/commit/8cabb79e120d5c74c8fb2f7a7ee9753c7919b877

**Comment by schans** [comment]
Pull request https://github.com/rundeck/rundeck/pull/2317

**Comment by gschueler** [comment]
thanks for the pr
