### ISSUE TITLE
add configurable timeout for remote option URLs

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#232]
Timeout is currently hardcoded, should be made into a configuration property.

Additionally, individual options should be able to override the timeout value if necessary (Nice to have).

**Comment by sinc59** [comment]
Hello,
have you progress on this old issue ? It's very disturbing for my use of rundeck.
Do you have a workaround ? How i can modify the hardcoded parameter ?

**Comment by hjdr4** [comment]
Hello,
My remote options are sometime populated by calling Amazon APIs, and they are slow, very slow.
Please quick update the timeout to something reasonable like 60 seconds. Then make a better fix by making the value tunable in any way.
