### ISSUE TITLE
Job options with periods in them do not trigger dependent URL based options to refresh

### ISSUE THREAD

**Issue by ajxb** [rundeck/rundeck#2321]
# Bug report

**My Rundeck detail**

* Rundeck version: 2.7.2-1 ("cafecito teal music" 2017-02-03)
* install type: rpm
* OS Name/version: CentOS release 6.7 (Final)

**Expected Behavior**

I have the created a contrived basic job definition that exhibits the behaviour I'm seeing in this [gist](https://gist.github.com/ajxb/e1ef7b96fa0934023925a1c65acdb77c)

I have options in a job that contain periods in their name:

1. `package.version` - list containing 1,2,3,4
2. `config.version` - Remote URL option that references `package.version`

When the value of `package.version` changes I expect `config.version` to automatically refresh to reflect the new value.

**Actual Behavior**

When using options that have periods in them the dependent option does not refresh its value, the user has to manually click on the check mark to refresh (I.E. if the user changes `package.version` they have to manually refresh `config.version` to see the correctly derived value).

In the attached job I have also created a second set of options that do not contain periods:

1. `package_version` - list containing 1,2,3,4
2. `config_version` - Remote URL option that references `package_version`

When the value of `package_version` changes, `config_version` does automatically refresh to reflect the new value.

**How to reproduce Behavior**

See [gist](https://gist.github.com/ajxb/e1ef7b96fa0934023925a1c65acdb77c)

**Comment by JaviSP** [comment]
+1
Tested with Rundeck version: 3.0.13
