### ISSUE TITLE
Feature Request - Support JOB Markdown output

### ISSUE THREAD

**Issue by damageboy** [rundeck/rundeck#2325]
I would love for job's to be able to output markdown output text and have rundeck render it as pretty html.

It would be great if jobs could either be marked as outputting markdown or some sort of dynamic detection of Markdown output (perhaps by outputting a special line that "notifies" rundeck that the markdown "mode" is turned on.

**Comment by damageboy** [comment]
That's very nice.
How would this handle multiple attachments? Would those be displayed as "tabs" on the job output?
How would a default one be selected?

Is there an issue for this?

**Comment by gschueler** [comment]
@damageboy I don't think there is any issue for this yet, it is still in ideas phase.  Any input is helpful, e.g. if you would like a script to output markdown and have it rendered in-line, that is a good use-case.

**Comment by damageboy** [comment]
I would definitely be interested in "live" markdown support.

In my mind this play a long with a larger feature, that would mimic [TeamCity Service Messages](https://confluence.jetbrains.com/display/TCD9/Build+Script+Interaction+with+TeamCity)

The basic idea would be that "stuff" running under rundeck could detect rundeck's presence by testing something like a `RUNDECK_VERSION` env, variable...

Once it's detected, the scripts running can output various messages that customize the UI / Behaviour of rundeck a-la the service message bus mechanism of TeamCity.

For example a script could output something like:
```
##rundeck[progressMessage 'Deploying Version X.Y.Z']
```

Could alter run-decks step title dynamically from within a script

Or something like:
```
##rundeck[outputMode 'markdown']
```

Could toggle markdown interpenetration/rendering of the rest of the output...

**Comment by gschueler** [comment]
nb: rundeck 2.9 will support this with "Content converter" and "Log Filter" plugins.  the 2.9 beta has this feature.

You can use the built in "Render Formatted Data" log filter plugin, to mark output from a step as markdown data.  Then Rundeck will use a "content converter" which knows how to render Markdown to display it in the gui.

You can mark all output from a step with a certain data type, or you can use this syntax:

        #BEGIN:RUNDECK:DATATYPE:<datatype>

Replacing `<datatype>` with one of the supported data types, e.g. `markdown`.

You can mark the section as ending by echoing:

    #END:RUNDECK:DATATYPE
