### ISSUE TITLE
API: Scm (export/import) action inputs should include item status

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2330]
Issue type: Enhancement Request

The scm export/import action inputs endpoint lists the items that can be selected for the action (such as git import) but it does not included the scm status of those items, e.g. "clean","needs-import" etc.

The API should include that information, so that, e.g. the `rd` tool can print it or automatically select those items when performing a SCM action:

ref: https://github.com/rundeck/rundeck-cli/issues/62

**Comment by Wambosa** [comment]
+1

**Comment by gschueler** [comment]
additionally, there should be an API endpoint to query a job's scm status, and in the project status it should list tracked jobs which have "source file was deleted" scm status

**Comment by gschueler** [comment]
added via #3192
