### ISSUE TITLE
Getting Resource Info problem(new problem)

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#2332]
GET /api/14/project/[PROJECT]/resource/[NAME]

[NAME]-What exactly does it mean?

**Comment by gschueler** [comment]
it is the node name

**Comment by qicaihuoyan** [comment]
But I filled out the node name and did not work
resources.xml Inside the node name is IP

<node name="10.66.170.10" description="formal_10.66.170.10" tags="ceshi" hostname="10.66.170.10:65555" osFamily="CentOS" osVersion="2.6.32-504.el6.x86_64" username="admin"/>

GET /api/14/project/[PROJECT]/resource/10.66.170.10
Does not work

**Comment by qicaihuoyan** [comment]
<node name="10.88.100.10" description="syq_dm_pj-db_hks-mysql_formal_10.88.100.10" tags="dm,pj-db" hostname="10.88.100.10:62222" osFamily="CentOS" osVersion="2.6.32-504.el6.x86_64" username="admin"/>

**Comment by qicaihuoyan** [comment]
[<node name="10.88.100.10" description="syq_dm_pj-db_hks-mysql_formal_10.88.100.10" tags="dm,pj-db" hostname="10.88.100.10:62222" osFamily="CentOS" osVersion="2.6.32-504.el6.x86_64" username="admin"/>]

**Comment by qicaihuoyan** [comment]
![rundeck](https://cloud.githubusercontent.com/assets/13148034/23003292/b3e5be0a-f42a-11e6-9057-05507ab7656f.png)

**Comment by gschueler** [comment]
you will have to explain more about what you are trying to do and how it does not work for you. please post the http requests and response

**Comment by qicaihuoyan** [comment]
I would like to get a node of the resource information
I'm doing it:
curl -H x-rundeck-auth-token:WhtQf0Whc80T16aw7zL49jIxNMPj http://10.88.2.200:4440/api/14/project/sa/resources/10.88.100.10
Unable to get information
But I executed:
curl -H x-rundeck-auth-token:WhtQf0Whc80T16aw7zL49jIxNMPj http://10.88.2.200:4440/api/14/project/sa/resources/

It can get all the information, but I now want to get a node

**Comment by qicaihuoyan** [comment]
curl --data-urlencode "filter=name:172.16.96.9" -H x-rundeck-auth-token:WhtQf0Whc80T16aw7zL49jIxNMPjWZWC http://10.88.2.200:4440/api/14/project/sa/resources/
This is also impossible

**Comment by qicaihuoyan** [comment]
![default](https://cloud.githubusercontent.com/assets/13148034/23193453/0a77edfc-f8e4-11e6-9032-693f3fc1c172.png)

**Comment by gschueler** [comment]
You are using the wrong URL.  It should be `.../project/sa/resource/NODE` not `.../project/sa/resources/NODE` ("resource" not "resources")

In the second problem, you are using a form request (mime type "application/x-www-form-urlencoded") but should use a GET request with a query parameter in the URL.

**Comment by qicaihuoyan** [comment]
Thank you very much because of my negligence
