### ISSUE TITLE
SCM Import not working - UUID Stripped

### ISSUE THREAD

**Issue by hypePG** [rundeck/rundeck#2333]
Issue type: Bug report
**My Rundeck detail**

 Rundeck version: 2.7.1.1
 install type: docker
* OS Name/version: RHEL7 newester Docker Version 

**Expected Behavior**
When using the SCM Export/Import function and remove the UUIDs in th export and change the name pattern accordingly I expect to be able to import jobs in another project in the same rundeck instance.

**Actual Behavior**
I can choose the Jobs I want to import and can define a matching regex. After I confirm my choice I get the "Setup successful" information, but the Jobs won't show in the new project.

I thought this issue would be resolved through the following enhancement:
https://github.com/rundeck/rundeck/pull/2154

Kind Regards

**Comment by gschueler** [comment]
After setup, you will have to do the import...  From the Jobs page, in the Action menu, select `Import Jobs`

does that work?

**Comment by hypePG** [comment]
hey, thanks for the answer. I am expecting the "import jobs" option to show..but I can still only choose "Select Files To Import" again. After this I can choose the files I want to import again and finish the setup, than I get the message "Setup successful" but I am still left with an empty project...

**Comment by hypePG** [comment]
@gonzales-ott-bot not that i know. @gschueler if you need anymore infos please let me know. have you been able to reproduce this behaviour? regards

**Comment by hypePG** [comment]
any news or workaround on this?
