### ISSUE TITLE
API Listing History : Parameter max don't work

### ISSUE THREAD

**Issue by Ataraxo** [rundeck/rundeck#2334]
Issue type: Bug report

Hello,
I'm trying to use Listing History with the API and with the parameter max.
No matter the value of the parameter max I have always a count of 20 events in the return of the API.

My request looks like: GET .../api/14/project/Panorama/history?max=100

My response in XML looks like:
`<events count='20' total='23' max='20' offset='0'>
   <event></event>
   ...
   <event></event>
</events>`

* Rundeck version: 2.7.1
* install type: launcher
* OS Name/version:  Windows 7 64bits

**Comment by gschueler** [comment]
how are you making the query?

Using curl I see the correct results with a 2.7.1 launcher:

    curl -s -H x-rundeck-auth-token:$RD_TOKEN http://ecto1.local:4440/api/14/project/ctest/history | head -n 1
    <events count='20' total='1765' max='20' offset='0'>

using max param:

    curl -s -H x-rundeck-auth-token:$RD_TOKEN http://ecto1.local:4440/api/14/project/ctest/history?max=100 | head -n 1
    <events count='100' total='1765' max='100' offset='0'>

**Comment by gschueler** [comment]
hey are you by chance sending a `Content-Type` header? see this issue: https://github.com/rundeck/rundeck/issues/2322#issuecomment-280155216

**Comment by Ataraxo** [comment]
Hi,
@gschueler thank you. You have right the `Content-Type` was the problem, the issue is resolved.
