### ISSUE TITLE
Possible memory leak?

### ISSUE THREAD

**Issue by acasademont** [rundeck/rundeck#2338]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.7.2-1
* install type: deb
* OS Name/version: Debian Jessie

We've been experiencing memory issues with Rundeck, at first the thought was to increase the memory settings to 4GB but it ends up consuming also the full 4Gb, GC goes mad and we basically need to restart rundeck (happens once a week or so) . I don't think throwing more memory to it is the solution. I've been monitoring the JVM to see what happens and it seems to me that there's some kind of memory leak, as the GC is only able to reclaim less and less memory every time it runs until it just can't do anything and Rundeck goes nuts. How can we help you debug the issue?

<img width="630" alt="screen shot 2017-02-20 at 00 32 42" src="https://cloud.githubusercontent.com/assets/825021/23107804/21d5a3f4-f704-11e6-91cc-634428b604c8.png">

<img width="688" alt="screen shot 2017-02-20 at 00 34 14" src="https://cloud.githubusercontent.com/assets/825021/23107815/575d93b0-f704-11e6-8c1c-975118819e03.png">

**Comment by acasademont** [comment]
HI @gschueler any clues on what might be happening or how can we dig deeper on this one?

**Comment by gschueler** [comment]
@acasademont can you attach a debugger and get a snapshot of the heap? (e.g. before and after one of the gc events?)

**Comment by acasademont** [comment]
I'm not a Java expert I'm afraid, would you do it using the HeapDumpAfterFullGC and HeapDumpBeforeFullGC config options?

**Comment by gschueler** [comment]
you can try:

    jmap -dump:file=dump1.hprof <pid>

if you can, get the heap dump at a nominal memory usage and then when it is filling up.

Was that cliff in your graph at the time of restart?

**Comment by acasademont** [comment]
yes exactly, the graph only goes back to normal after a restart. will try, thanks!

**Comment by acasademont** [comment]
Since we upgraded to Debian Stretch we haven't seen this issue again, which is weird. Closing it for now :)
