### ISSUE TITLE
Whether the node filter supports precise matching?

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#2342]
![1](https://cloud.githubusercontent.com/assets/13148034/23243284/cd9b0f4c-f9b8-11e6-9025-d39022306898.png)
Now I filter hks, the results will show hks and pj-hks
Rundeck support accurate matching Well? For example, I filter hks, only show hks related information, do not show pj-hks information?

**Comment by gschueler** [comment]
how are you making the query?

**Comment by qicaihuoyan** [comment]
curl -H x-rundeck-auth-token:WhtQf0Whc80T16aw7zL49jIxNMPj http://*.*.*.*:4440/api/14/project/sa/resources/ -G --data-urlencode "filter=tags: yss"

**Comment by qicaihuoyan** [comment]
Whether this question is supported

**Comment by qicaihuoyan** [comment]
<node name="*.*.*.*" description="syq_hks_pj-hks_api_formal_*.*.*.*" tags="hks, pj-hks" hostname="*.*.*.*:8888" osArch="" osFamily="CentOS" osName="" osVersion="2.6.32-504.el6.x86_64" username="admin"/>
  <node name="*.*.*.*" description="syq_hks_pj-hks_api_formal_*.*.*.*" tags="hks, pj-hks" hostname="*.*.*.*:8888" osArch="" osFamily="CentOS" osName="" osVersion="2.6.32-504.el6.x86_64" username="admin"/>

I run:
curl -H x-rundeck-auth-token:WhtQf0Whc80T16a http://*.*.*.*:4440/api/14/project/sa/resources/ -G --data-urlencode "filter=tags: pj-hks"
I just want to filter : pj-hks,

**Comment by qicaihuoyan** [comment]
<node name="*.*.*.*" description="syq_hks_pj-hks_api_formal_*.*.*.*" tags="hks, pj-hks" hostname="*.*.*.*:8888" osArch="" osFamily="CentOS" osName="" osVersion="2.6.32-504.el6.x86_64" username="admin"/>
  <node name="*.*.*.*" description="syq_hks_pj-hks_api_formal_*.*.*.*" tags="hks, pj-hks" hostname="*.*.*.*:8888" osArch="" osFamily="CentOS" osName="" osVersion="2.6.32-504.el6.x86_64" username="admin"/>

**Comment by qicaihuoyan** [comment]
![qq 20170308142805](https://cloud.githubusercontent.com/assets/13148034/23692745/78bb7446-040b-11e7-80ac-8277bdf345f8.png)

**Comment by gschueler** [comment]
if you want to exclude tags `hks`, you would have to set the filter `tags: pj-hks !tags: hks`

**Comment by qicaihuoyan** [comment]
Thank you very much for your patience
