### ISSUE TITLE
Passing rundeck node variables into a Job Reference gets an error

### ISSUE THREAD

**Issue by hagay3** [rundeck/rundeck#2345]
Issue type: Bug report
I'm trying to pass job reference node.filter variable and seems like rundeck not initialized the variable yet and the job reference executed with an empty variable.
I tried also to override the node filter with the node.filter with no luck.

![rd1](https://cloud.githubusercontent.com/assets/13578121/23354767/59e3f78c-fcdb-11e6-9624-11f31d3f2252.png)

**My Rundeck detail**

* Rundeck version: 2.6.8
* install type: (rpm,deb,war,launcher?) deb
* OS Name/version: docker

**Expected Behavior**

Job reference takes node.name as an argument

**Actual Behavior**
Error which node.name is not match any node (as it not injected the actual node name)

**No nodes matched for the filters: NodeSet{includes={name=${node.name}, dominant=false, }}**

**How to reproduce Behavior**

Create a job and inside the job a job reference that takes the node.name as an argument

**Comment by gschueler** [comment]
if it is not marked as a "Node Step" then the job reference does not run in a node context.

**Comment by hagay3** [comment]
Ok, so you are saying I need to change it to a node step and than leave the node filter for the job reference blank? Rundeck will pass by itself the node that the job reference should execute on?

**Comment by gschueler** [comment]
If you want to pass `${node.name}` as an option to the job reference, you will need the job reference step to be a Node step, so that it executes once-per-node in your top-level job's filter.  If you want to override the filter, and use the node name, you would do the same thing but use ${node.name} in the filter instead of arguments.

**Comment by hagay3** [comment]
Managed to figured that out, I think you have to add proper documentation for this one.
Thanks!
