### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by mathieuchateau** [rundeck/rundeck#2350]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.7.2-1
* install type: rpm
* OS Name/version: centos 7

Database is H2

**Expected Behavior**
get the job activity list as before.

**Actual Behavior**
Request: /project/Mobistep-PreProd-App/activity
Message: 
Caused by: 
Class: Unknown 
At Line: [-1] 
Code Snippet:
Stack Trace
java.lang.ArrayIndexOutOfBoundsException

Logs:

==> service.log <==
ERROR SqlExceptionHelper: General error: "java.lang.ArrayIndexOutOfBoundsException"; SQL statement:
select this_.id as id1_1_0_, this_.version as version2_1_0_, this_.action_type as action_t3_1_0_, this_.author as author4_1_0_, this_.ctx_name as ctx_name5_1_0_, this_.ctx_project as ctx_proj6_1_0_, this_.ctx_type as ctx_type7_1_0_, this_.date_completed as date_com8_1_0_, this_.date_started as date_sta9_1_0_, this_.mapref_uri as mapref_10_1_0_, this_.message as message11_1_0_, this_.node as node12_1_0_, this_.report_id as report_13_1_0_, this_.status as status14_1_0_, this_.tags as tags15_1_0_, this_.title as title16_1_0_, this_.aborted_by_user as aborted18_1_0_, this_.adhoc_execution as adhoc_e19_1_0_, this_.adhoc_script as adhoc_s20_1_0_, this_.ctx_command as ctx_com21_1_0_, this_.ctx_controller as ctx_con22_1_0_, this_.failed_node_list as failed_23_1_0_, this_.filter_applied as filter_24_1_0_, this_.jc_exec_id as jc_exec25_1_0_, this_.jc_job_id as jc_job_26_1_0_, this_.succeeded_node_list as succeed27_1_0_ from base_report this_ where this_.class='rundeck.ExecReport' and this_.ctx_project=? and (this_.jc_job_id is not null or this_.jc_exec_id is not null) order by this_.date_completed desc, this_.date_started desc, this_.id desc limit ? [50000-193]

==> rundeck.log <==
2017-03-01 22:03:46,040 [qtp1480010240-13843] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - General error: "java.lang.ArrayIndexOutOfBoundsException"; SQL statement:
select this_.id as id1_1_0_, this_.version as version2_1_0_, this_.action_type as action_t3_1_0_, this_.author as author4_1_0_, this_.ctx_name as ctx_name5_1_0_, this_.ctx_project as ctx_proj6_1_0_, this_.ctx_type as ctx_type7_1_0_, this_.date_completed as date_com8_1_0_, this_.date_started as date_sta9_1_0_, this_.mapref_uri as mapref_10_1_0_, this_.message as message11_1_0_, this_.node as node12_1_0_, this_.report_id as report_13_1_0_, this_.status as status14_1_0_, this_.tags as tags15_1_0_, this_.title as title16_1_0_, this_.aborted_by_user as aborted18_1_0_, this_.adhoc_execution as adhoc_e19_1_0_, this_.adhoc_script as adhoc_s20_1_0_, this_.ctx_command as ctx_com21_1_0_, this_.ctx_controller as ctx_con22_1_0_, this_.failed_node_list as failed_23_1_0_, this_.filter_applied as filter_24_1_0_, this_.jc_exec_id as jc_exec25_1_0_, this_.jc_job_id as jc_job_26_1_0_, this_.succeeded_node_list as succeed27_1_0_ from base_report this_ where this_.class='rundeck.ExecReport' and this_.ctx_project=? and (this_.jc_job_id is not null or this_.jc_exec_id is not null) order by this_.date_completed desc, this_.date_started desc, this_.id desc limit ? [50000-193]

==> service.log <==
ERROR GrailsExceptionResolver: ArrayIndexOutOfBoundsException occurred when processing request: [GET] /project/MyProject/activity
Stacktrace follows:
java.lang.ArrayIndexOutOfBoundsException

==> rundeck.log <==
2017-03-01 22:03:46,102 [qtp1480010240-13843] ERROR org.codehaus.groovy.grails.web.errors.GrailsExceptionResolver - ArrayIndexOutOfBoundsException occurred when processing request: [GET] /project/MyProject/activity
Stacktrace follows:
java.lang.ArrayIndexOutOfBoundsException

**How to reproduce Behavior**
Go to the activity page

**Comment by gschueler** [comment]
is there any other stack trace information?

**Comment by mathieuchateau** [comment]
@gschueler  I don't think so, didn't find more

**Comment by mathieuchateau** [comment]
Hello,

I have it again now, after updating to latest rundeck.

Web site is not responding.
h2 file is 12GB

Verbose mode provide more logs:

> 2017-10-30 09:11:53.792:INFO:oejs.Server:main: jetty-9.0.7.v20131107
> 2017-10-30 09:11:55.758:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
> 2017-10-30 09:11:56.461:INFO:/:main: Initializing Spring root WebApplicationContext
> 2017-10-30 09:50:02,893 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index EXEC_REPORT_IDX_0 on base_report (ctx_project, date_completed, jc_exec_id, jc_job
> _id)
> 2017-10-30 09:50:02,894 [main] ERROR hbm2ddl.SchemaUpdate  - General error: "java.lang.ArrayIndexOutOfBoundsException: 0"; SQL statement:
> create index EXEC_REPORT_IDX_0 on base_report (ctx_project, date_completed, jc_exec_id, jc_job_id) [50000-193]
> 2017-10-30 09:50:02,915 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index EXEC_REPORT_IDX_1 on base_report (ctx_project, jc_job_id)
> 2017-10-30 09:50:02,915 [main] ERROR hbm2ddl.SchemaUpdate  - General error: "java.lang.ArrayIndexOutOfBoundsException"; SQL statement:
> create index EXEC_REPORT_IDX_1 on base_report (ctx_project, jc_job_id) [50000-193]
> 2017-10-30 09:50:02,928 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create index BASE_REPORT_IDX_2 on base_report (ctx_project, date_completed, date_started)
> 2017-10-30 09:50:02,928 [main] ERROR hbm2ddl.SchemaUpdate  - General error: "java.lang.ArrayIndexOutOfBoundsException"; SQL statement:
> create index BASE_REPORT_IDX_2 on base_report (ctx_project, date_completed, date_started) [50000-193]
> INFO  BootStrap: Starting Rundeck 2.10.0-1 (2017-10-16) ...
> INFO  BootStrap: using rdeck.base config property: /var/lib/rundeck
> INFO  BootStrap: loaded configuration: /etc/rundeck/framework.properties
> INFO  BootStrap: RSS feeds disabled
> INFO  BootStrap: Preauthentication is disabled
> INFO  BootStrap: Rundeck is ACTIVE: executions can be run.
> ERROR SqlExceptionHelper: General error: "java.lang.ArrayIndexOutOfBoundsException" [50000-193]
> ERROR GrailsContextLoaderListener: Error initializing the application: could not prepare statement
> org.hibernate.exception.GenericJDBCException: could not prepare statement
>         at org.grails.datastore.gorm.GormStaticApi$_withCriteria_closure11.doCall(GormStaticApi.groovy:305)
>         at org.grails.datastore.mapping.core.DatastoreUtils.execute(DatastoreUtils.java:302)
>         at org.grails.datastore.gorm.AbstractDatastoreApi.execute(AbstractDatastoreApi.groovy:37)
>         at org.grails.datastore.gorm.GormStaticApi.withCriteria(GormStaticApi.groovy:304)
>         at rundeck.services.ExecutionService.cleanupRunningJobsAsync(ExecutionService.groovy:686)
>         at BootStrap$_closure1.doCall(BootStrap.groovy:393)
>         at grails.util.Environment.evaluateEnvironmentSpecificBlock(Environment.java:327)
>         at grails.util.Environment.executeForEnvironment(Environment.java:320)
>         at grails.util.Environment.executeForCurrentEnvironment(Environment.java:296)
>         at org.eclipse.jetty.server.handler.ContextHandler.callContextInitialized(ContextHandler.java:788)
>         at org.eclipse.jetty.servlet.ServletContextHandler.callContextInitialized(ServletContextHandler.java:434)
>         at org.eclipse.jetty.server.handler.ContextHandler.startContext(ContextHandler.java:780)
>         at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:284)
>         at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1322)
>         at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:732)
>         at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:490)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:118)
>         at org.eclipse.jetty.server.Server.start(Server.java:342)
>         at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:100)
>         at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:60)
>         at org.eclipse.jetty.server.Server.doStart(Server.java:290)
>         at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:69)
>         at com.dtolabs.rundeck.RunServer.run(RunServer.java:119)
>         at com.dtolabs.rundeck.RunServer.main(RunServer.java:79)
> Caused by: org.h2.jdbc.JdbcSQLException: General error: "java.lang.ArrayIndexOutOfBoundsException" [50000-193]
>         at org.h2.message.DbException.getJdbcSQLException(DbException.java:345)

**Comment by ahonor** [comment]
Please reopen if this is still a concern
