### ISSUE TITLE
API error : Failed to delete file while deleting execution

### ISSUE THREAD

**Issue by Ataraxo** [rundeck/rundeck#2356]
Issue type: Bug report

I try to delete an execution with the API and I get an error:
"2017-03-07 10:22:41,336 WARN  ExecutionService - Failed to delete file while deleting execution 388: C:\Users\tbenapht\Documents\Rundeck\var\logs\rundeck\Panorama\run\logs\388.rdlog"

When i go on the web page the execution does not exist but the log file is always present in the disk.

* Rundeck version: 2.7.2
* install type: launcher
* OS Name/version: Windows 7 64bits

**Comment by ahonor** [comment]
Can't reproduce in 2.10
