### ISSUE TITLE
Execution State The problem

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#2357]
Official api:GET /api/10/execution/[ID]/state
I run:
curl -H 'x-rundeck-auth-token:WhtQf0Whc80T16aw7zL49jIxNMPjWZWC' --header "Accept:application/json" http://*.*.*.*:4440/api/10/execution/866ac379-a6f0-4eaf-a0f9-170562436956/state

Get a bunch of error messages
[error.txt](https://github.com/rundeck/rundeck/files/826973/error.txt)

Use this api need special settings?

**Comment by gschueler** [comment]
execution `[ID]` is not a UUID, it is a long, e.g. "123".  `/api/10/execution/123/state`  It is not the Job ID

**Comment by qicaihuoyan** [comment]
The data came out, but I would like to ask how to use curl to simulate the effect of Tailing Output?

I am currently running:
curl -H 'x-rundeck-auth-token:WhtQf0Whc80T16aw7zZWC' http://10.88.2.200:4440/api/5/execution/92/output?offset=0

**Comment by gschueler** [comment]
If you need to use curl, here is an example: https://github.com/rundeck/rundeck/blob/master/test/api/test-execution-output.sh#L57

otherwise it would be easier to use the rd tool https://rundeck.github.io/rundeck-cli/

**Comment by qicaihuoyan** [comment]
thank you very much
