### ISSUE TITLE
Runtime job option list genetation

### ISSUE THREAD

**Issue by anilalapy** [rundeck/rundeck#2367]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.6.2-1
* install type: deb
* OS Name/version: Ubuntu 14.04

**Expected Behavior**
 
Is there any way of selecting the Job options dynamically? For example, I have two Job options in the a job and I wanted to select the second job option dynamically based on first option selected(That means the second option list must be generated runtime while selecting the first option).   

**Actual Behavior**

Job option values are static, even if I use remote URL. I cant change the values in the list based on previous option. 

**How to reproduce Behavior**

NA

**Comment by puremourning** [comment]
Is this what you want?http://rundeck.org/docs/manual/jobs.html#cascading-remote-options

you use the option value in the remote URL for another option. Use something like ${option.OTHEROPTION.value} in the remote URL. Then changing OTHEROPTION loads the values of this option.

**Comment by anilalapy** [comment]
Thanks, it looks similar. let me try out

**Comment by ahonor** [comment]
Please reopen if this remains a concern
