### ISSUE TITLE
Local execution command issue

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#2369]
rundeck-version:2.7.2-1
The issue is:
I set up a task that requires local ssh to the destination,The project's ssh-key is the admin directory,But when I perform the task when rundeck is called /root/.ssh the following content, is this why

![1](https://cloud.githubusercontent.com/assets/13148034/23936127/28e6017c-098b-11e7-90c6-e7d91e1e97bc.png)
![2](https://cloud.githubusercontent.com/assets/13148034/23936153/4bac740c-098b-11e7-86be-4d7ac8c37122.png)

And the implementation of the task when the need to rundeck root under the ssh-key, copy to the destination machine can only??

**Comment by gschueler** [comment]
The way you should do this with rundeck is, define a node in `resources.xml`:

~~~~{.xml}
<project>
<node name="mynode" username="admin" ssh-keypath="/home/admin/.ssh/id_rsa" hostname="mynode-hostname.company.com"/>
</project>
~~~~

in your job define the node filter:

* Dispatch to Nodes: `true`
* Node Filter: `name: mynode`

or if you want to use a Job Option
* Option Name `node1`
* Dispatch to Nodes: `true`
* Node Filter: `name: ${option.node1}`

Then you just put this in your script:

~~~~ {.sh}
#!/bin/bash
pwd
~~~~

**Comment by gschueler** [comment]
You can specify port in the node:

    hostname="mynode-hostname.company.com:62222"

**Comment by qicaihuoyan** [comment]
Thank you very much for your reply, but my problem is to deploy a cluster application, want to complete the entire deployment in a script, ip pass in a script embodied, rather than three separate running tasks

The problem itself can be solved by the method you recommend, but I would like to use the local implementation method
