### ISSUE TITLE
How can I change the default  execute node when creating job through api？

### ISSUE THREAD

**Issue by deeper-yang** [rundeck/rundeck#2371]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.5.3
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version:  Centos6.5

**Expected Behavior**

I have  defined two remote node , then  I want to create a job through api ，just to run a php command.
But the job always choose the default node（execute locally）. How can I change the defaut to my defined?

**Actual Behavior**
the php command 
`/usr/bin/php /data/admin02/XXXX/dashboard/protected/bin/yiic  CouponApplication start --id=264 --times=1`

The error:
<img src=http://chuantu.biz/t5/50/1489664427x2728278601.png />

**Comment by ahonor** [comment]
@deeper-yang can you show how you are invoking this via api?
