### ISSUE TITLE
Getting LDAP groups from ApacheDS

### ISSUE THREAD

**Issue by dsiluri** [rundeck/rundeck#2372]
Hello guys,
I'm trying to get Rundeck working with ApacheDS, 
I manage to perform authentication against LDAP but I don't get LDAP groups the user belongs to (in this case "infra" group).

* Rundeck version: 2.7.2
* install type: launcher
* OS Name/version: RHES 7.2
* ApacheDS version: 2.0.0

Rundeck log output:

> 2017-03-16 23:32:22.369:DBUG:cdrjj.JettyCachingLdapLoginModule:qtp736714033-12: Searching for users with filter: '(&(objectClass={0})({1}={2}))' from base dn: ou=users,dc=company,dc=com
> 2017-03-16 23:32:22.384:DBUG:cdrjj.JettyCachingLdapLoginModule:qtp736714033-12: Found user?: true
> 2017-03-16 23:32:22.386:INFO:cdrjj.JettyCachingLdapLoginModule:qtp736714033-12: Attempting authentication: uid=jwayne,ou=users,dc=company,dc=com
> 2017-03-16 23:32:22.405:DBUG:cdrjj.JettyCachingLdapLoginModule:qtp736714033-12: JettyCachingLdapLoginModule: **User 'jwayne' has roles: [user]**
> 2017-03-16 23:32:22.407:DBUG:cdrjj.JettyCachingLdapLoginModule:qtp736714033-12: Adding jwayne set to expire: 1489687342406300000

Here below ldap login module conf:
> com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
>       debug="true"
>       contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
>       providerUrl="ldap://localhost:10389"
>       bindDn="uid=admin,ou=users,dc=company,dc=com"
>       bindPassword="xxx"
>       authenticationMethod="simple"
>       forceBindingLogin="true"
>       userBaseDn="ou=users,dc=company,dc=com"
>       userRdnAttribute="uid"
>       userIdAttribute="uid"
>       userPasswordAttribute="userPassword"
>       userObjectClass="inetOrgPerson"
>       roleBaseDn="ou=groups,dc=company,dc=com"
>       roleNameAttribute="cn"
>       roleUsernameMemberAttribute="uniqueMember"
>       roleMemberAttribute="uniqueMember"
>       roleObjectClass="groupOfUniqueNames"
>       roleSearchSubtree=true
>       cacheDurationMillis="300000"
>       supplementalRoles="user"
>       reportStatistics="true"
>       timeoutRead="10000"
>       timeoutConnect="20000"
>       nestedGroups="false";

And ApacheDS current structure:

> dn: ou=users,dc=company,dc=com
> objectClass: organizationalUnit
> objectClass: top
> ou: users
> 
> dn: uid=jwayne,ou=users,dc=company,dc=com
> objectClass: organizationalPerson
> objectClass: person
> objectClass: inetOrgPerson
> objectClass: top
> cn: John Wayne
> sn: Wayne
> uid: jwayne
> userPassword:: e1NTSEF9bU9qVG5QK0U0Y1RBVEZWdzllY0ltOERwMHBvekxqV2hHaDFCY1E9P
>  Q==
> 
> dn: ou=groups,dc=company,dc=com
> objectClass: organizationalUnit
> objectClass: top
> ou: groups
> 
> dn: uid=admin,ou=users,dc=company,dc=com
> objectClass: account
> objectClass: simpleSecurityObject
> objectClass: top
> uid: admin
> userPassword:: e1NTSEF9ZnU1bDZDUkNHSlIwRHNIMVFlZkQxalcyd0xocGZuZWxQNU81L0E9P
>  Q==
> 
> dn: cn=infra,ou=groups,dc=company,dc=com
> objectClass: groupOfUniqueNames
> objectClass: top
> cn: infra
> uniqueMember: uid=jwayne,ou=users,dc=company,dc=com
> 
> dn: dc=company,dc=com
> objectclass: top
> objectclass: domain
> dc: company
>

Any help would be really appreciated.

Thanks
David

**Comment by philworks** [comment]
The struggle is real.  I recently went through this myself.

Try adding: forceBindingLoginUseRootContextForRoles
"true/false" - if true and forceBindingLogin is true, then role membership searches will be performed in the root context, rather than in the bound user context.   Set this to True and give it a try.

I don't think roleSearchSubtree=true is even a thing.

I feel like you're close.

**Comment by ahonor** [comment]
@dsiluri Please reopen if this remains a concern
