### ISSUE TITLE
Preauthenticated mode throws Error Auhtentication is Required

### ISSUE THREAD

**Issue by oazabir** [rundeck/rundeck#2376]
Issue type: Bug report
Version: Rundeck 2.7.3

Preauthenticated configuration results in Error page:

![image](https://cloud.githubusercontent.com/assets/1611494/24104546/5ab1e232-0d7a-11e7-8755-a0e287486b50.png)

Properly configured /etc/rundeck/rundeck-config.properties:
```
rundeck.security.authorization.preauthenticated.enabled=true
rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
rundeck.security.authorization.preauthenticated.delimiter=:
```
Commented out security constraint on /var/lib/rundeck/exp/webapp/WEB-INF/web.xml:
```
<security-constraint>
                <web-resource-collection>
                        <web-resource-name>all</web-resource-name>
                        <url-pattern>/*</url-pattern>
                </web-resource-collection>
                <!--<auth-constraint>
                        <role-name>*</role-name>
                </auth-constraint>-->
        </security-constraint>
```

Apache does produce two request headers:

REMOTE_USER	604422604
REMOTE_USER_GROUPS	admin:user

Confirmed by putting a php page to dump all request header. 

/etc/rundeck/realm.properties has:
```
admin:admin,user,admin,architect,deploy,build
604422604:admin,user,admin,architect,deploy,build
```

Still no luck. Any help would be much appreciated.

**Comment by gschueler** [comment]
If you are using HTTP headers, I believe your config needs to be something like:

    rundeck.security.authorization.preauthenticated.userNameHeader=REMOTE_USER
    rundeck.security.authorization.preauthenticated.userRolesHeader=REMOTE_USER_GROUPS
    rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS

The `attributeName` value does not really need to match, it is used internally when using HTTP headers in the pre-authenticated request, but it does need to be set

**Comment by oazabir** [comment]
Many thanks, this worked. These additional fields seem to be not documented in the Authentication manual.

**Comment by pixdrift** [comment]
I just came across this same issue as the documentation appears out of step with the required configuration, thanks for posting the details.

> The attributeName value does not really need to match, it is used internally when using HTTP headers in the pre-authenticated request, but it does need to be set

This specifically tripped us up, and it appears related to this line:
https://github.com/rundeck/rundeck/blob/88a0620d95cd03d2907c31958521c1639c96496f/rundeckapp/src/java/com/dtolabs/rundeck/server/filters/AuthFilter.java#L105

Is there a reason both need to be set? Is the attributeName (rolesAttribute) still relevant or was it superseded by userRolesHeader (rolesHeader)?

Thanks in advance.

**Comment by gschueler** [comment]
There are two components. The first uses request attributes to read in the roles.  This can be set via an AJP connecter, e.g. with apache http proxy plugin.  The second component is the AuthFilter which can read roles from HTTP headers.  This was added later.  It needs the attributeName so it can set the correct attribute later read by the first component.  HTH.

Agree: the documentation should be clearer
