### ISSUE TITLE
field execution.id suddenly grows

### ISSUE THREAD

**Issue by kino71** [rundeck/rundeck#2379]
Issue type: Bug report
Rundeck version: 2.7.1
install type: launcher
OS Name/version: Sparc SOLARIS 11 (11.2)

**Expected Behavior**
We're running rundeck using Sybase ASE as relational DB.
field "id" table "execution" should increase by 1 at each job run

**Actual Behavior**
It happened twice that increased by some (10^13) instead of just 1.
For instance it went from 28844 to 10000000024425
and from 10000000026069 to 20000000025589

**How to reproduce Behavior**
I haven't been able, It happened twice in a couple of months

Sybase datatype for execution.id is bigint (Signed: -2^63 to 2^63-1, Unsigned: 0 to 2^64-1)

How does rundeck decide the next execution id ?
Maybe I should just change sybase datatype to something smaller to fix this issue.

Is there a way to "fix" the table ?
I could update table execution but is there some constraint I should be aware of ?

Thanks!

**Comment by gschueler** [comment]
You might try searching for a similar issue in relation to Hibernate, that is the ORM library used by grails.  I think the row IDs are autogenerated by the DB, but maybe hibernate is doing something weird.

**Comment by kino71** [comment]
Thanks Greg, I will look into it.
It turned out that both time we had a problem with our db (it was unreachable). 
I'm looking into hibernate docs to check if we can do something to prevent that from happening.
