### ISSUE TITLE
allow file copier default temp dir to be set at project/framework level

### ISSUE THREAD

**Issue by sebw** [rundeck/rundeck#238]
Is there a way to get around a noexec flag set on /tmp ?

Can I specify another temp directory ?

**Comment by ajayrockrock** [comment]
Can probably close this 4 year old ticket as you can now set it at the framework level:  http://rundeck.org/docs/plugins-user-guide/node-execution-plugins.html

I just set this in /etc/rundeck/framework.properties

framework.file-copy-destination-dir = /home/rundeck

And it's no longer copying files to /tmp to execute.

**Comment by sebw** [comment]
Good catch! Closing.
