### ISSUE TITLE
FileCopier-ps1 extension

### ISSUE THREAD

**Issue by gangadhar01a** [rundeck/rundeck#2396]
Issue type: Bug report/Enhancement Request

I would like to execute simple powershell script using file copier "stub" and provided the file extension as .ps1 under advance settings. Still the script has been copying as ".bat" format which is not executed on windows node as expected. 

I have tried "invocation string" as "copy ${scriptfile} ${scriptfile}.ps1 & powershell -file ${scriptfile}.ps1 $ del ${scriptfile}.ps1" which also not worked for me.

Is there any work around to fix this issue?
**My Rundeck detail**

* Rundeck version: 2.7.3-1
* install type: (rpm,deb,war,launcher?) 
* OS Name/version: CentOS

**Expected Behavior**
Script file should be copied as .ps1 format 

**Actual Behavior**
copied as .bat format

**How to reproduce Behavior**

**Comment by gschueler** [comment]
the "stub" file copier is a no-op, for testing. It will not copy any files

**Comment by gangadhar01a** [comment]
Thanks for the swift responds. How I can make script working in the above scenario? Do I need to change the file copier?

**Comment by gschueler** [comment]
WinRM does not include a file copier.  You will have to provide another way to copy files to hosts for script execution.  See the [File Copier Plugin - Script Plugin Type](http://rundeck.org/docs/developer/file-copier-plugin.html#script-plugin-type).  E.g. you might be able to use a NFS share and copy files that way.

(Note: [Rundeck Pro](http://rundeck.com) includes a powershell plugin which provides this feature.)

**Comment by gangadhar01a** [comment]
NFS perfectly works. Thanks

**Comment by ahonor** [comment]
Reopen if this remains a concern
