### ISSUE TITLE
rundeck-script Chinese support questions

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#2411]
Insert one script
##########################
#!/bin/bash

sudo su - <<EOF
echo -e """
####################################################
你好
####################################################
""" >/etc/motd
EOF
#########################
After the implementation, /etc/motd Inside the content is garbled
But in the system to run echo-e,normal

I would like to ask rundeck on the contents of the implementation of this piece of any attention

**Comment by gschueler** [comment]
Are you using Mysql? You may need to set the server to use `utf8mb4` character set: https://dev.mysql.com/doc/refman/5.7/en/server-system-variables.html#sysvar_character_set_server

**Comment by ahonor** [comment]
Please remain if this remains a concern
