### ISSUE TITLE
Notification Plugins should be able to use Key Storage

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2415]
Issue type: Enhancement Request

Add ability for Notification plugins to load key storage values for authentication to other services

**Comment by matthewsrogers** [comment]
I might add that it would be great to also allow Resource Model plugins to use the keystore.  In general, all plugin types could potentially need credentials to function.  It would be nice to be able to use the keystore for all plugin types.

**Comment by gschueler** [comment]
@matthewsrogers yes. I think the only issue is determining how to appropriately authorize the access.  All access to key store happens through the ACL policy authorization, which grants access to user/group.  The Resource Model is loaded for projects, so it is not bound to a particular user or auth group.  I think we would need a new way to authorize projects to the key store.

for notifications, they could use the same authorization level as the executing user

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
