### ISSUE TITLE
making changes to /etc/rundeck/rundeck-config.properties changes nothing on the web gui

### ISSUE THREAD

**Issue by aristosv** [rundeck/rundeck#2416]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 
* install type: deb
* OS Name/version: Linux rundeck 3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u1 (2017-02-22) x86_64 GNU/Linux

**Expected Behavior**
changes to /etc/rundeck/rundeck-config.properties should be reflected to the web gui. for example:
rundeck.gui.title = test-title
rundeck.gui.brand.html = test-title
rundeck.gui.helpLink = http://example.org/

**Actual Behavior**
Nothing changes on the gui. Even after browser cache cleared and rundeck service restarted.

**How to reproduce Behavior**
make changes to /etc/rundeck/rundeck-config.properties. Nothing will change on the gui.

**Comment by yavuzaydin** [comment]
I think I had the same problem because the systemd script to stop rundeck doesn't actually stop rundeck. Try systemctl stop rundeckd.service and then ps aux rundeck, kill that process, start rundeck again and your changes will work.

Still haven't had time to properly report the stop issue though.

**Comment by JeffHemmen** [comment]
I have struggled with this just now.
a) I second yavuzaydin's comment: do a `ps aux rundeck` after your systemctl command to double-check
b) Make sure you are using rundeck-config.properties, not rundeck-config.groovy.
They seem to be mutually exclusive, and meant to contain the same information, just in a marginally different format. Check (in /etc/rundeck/profile or in the `ps` output) which config file you're pointing to.

Hope this helps!

**Comment by ahonor** [comment]
Please reopen if this remains a concern
