### ISSUE TITLE
Visual job/flow modeler

### ISSUE THREAD

**Issue by hbjcr** [rundeck/rundeck#2419]
Issue type: Enhancement Request

It would be very helpful to have a visual modeler for the jobs; it would be something similar to what some ETL tools use for modeling their workflow. This will greatly improve UX and will help make the whole orchestration process easier to the user.

**Comment by ahonor** [comment]
@hbjcr Can you share an example ?

**Comment by hbjcr** [comment]
Something like [CloverETL's designer](https://www.cloveretl.com/products/designer) for instance. I'll say something like your workflow strategy tab but with the ability to visually model the workflow; unless you can do it already with the commercial version, I don't know since I've never used your commercial version myself.
