### ISSUE TITLE
Options allowed values required from databases

### ISSUE THREAD

**Issue by shadowhunter2009** [rundeck/rundeck#2421]
I was trying to require allowed values for rundeck options from postgres.

One way is to dump database into json files and use "A URL to a Remote JSON service" to do it.

Do you have more neat way to do that?

**Comment by gschueler** [comment]
@shadowhunter2009 right now a json file is the way to do it.  Your remote json url can be a `file:/..` url.  We have on our roadmap a plugin interface for providing data instead of using a URL
