### ISSUE TITLE
Job File Input Upload API broken

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2428]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.0

**Expected Behavior**

Using job file upload API should work

**Actual Behavior**

Error result

**How to reproduce Behavior**

use Job File upload API
* use `rd run ` with the `-opt@ filepath`

**Comment by BenJaziaSadok** [comment]
@gschueler does it solved ?  I'm facing also a job file upload API, with this message: 

> "One or more job options do not support file upload file.yml"
