### ISSUE TITLE
Rundeck not starting after update to 2.8.0 from 2.7.3

### ISSUE THREAD

**Issue by Sh4d0wF1gh7** [rundeck/rundeck#2432]
After Rundeck update from 2.7.3 to 2.8.0 on a Debian (Wheezy) machine, rundeck is not starting.

service rundeckd status
Fail is not running

service rundeckd start
Ok running rundeckd

service rundeckd stop
failed to kill 1234 no such process

Going back to 2.7.3 all is ok.

**Comment by colebrumley** [comment]
FYI Looks like this is due to the last line of `/etc/rundeck/profile` being removed in the latest release. I manually added this line back and it took off.

```
rundeckd="$JAVA_CMD $RDECK_JVM $RDECK_JVM_OPTS -cp $BOOTSTRAP_CP com.dtolabs.rundeck.RunServer $RDECK_BASE"
```

**Comment by gschueler** [comment]
the `/etc/rundeck/profile` and init scripts changed from 2.7 to 2.8.  You should use the stock profile, and define overrides in the `/etc/default/rundeckd` (deb) or `/etc/sysconfig/rundeckd` (rpm) files

**Comment by Sh4d0wF1gh7** [comment]
Hello, today i tested again updating to 2.8.2 but same error.

First Post from colebrumley is not matching because this line is here.

Second Post from Gschueler i don´t know how the override should look like in my debian system???

**Comment by gschueler** [comment]
@Sh4d0wF1gh7 what kind of error message do you get?

**Comment by Sh4d0wF1gh7** [comment]
In the service log i get:
`Unrecognized VM option 'MaxMetaspaceSize=256m'
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.`

**Comment by Sh4d0wF1gh7** [comment]
Oh no...
java -version
says only Java 7...
Rundeck is running now with Java 8, followed by this:
https://debian-blog.org/java-8-installieren/

**Comment by gschueler** [comment]
yes Java 8 is required, as mentioned in the Upgrading section http://rundeck.org/docs/upgrading/index.html#upgrading-to-rundeck-2.8-from-earlier-versions
