### ISSUE TITLE
Change Hardcoded Runuser in Init Script

### ISSUE THREAD

**Issue by niall-munnelly** [rundeck/rundeck#2434]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.6.11
* install type: rpm
* OS Name/version: RHEL 6.9
* DB Type/version: mysql? postgres? h2?.. N/A

**Expected Behavior**
The init script sources profile before it executes Rundeck commands. Expectation is that runuser should be executed with argument "-l ${RUNDECK_USER}".

**Actual Behavior**

Runuser command in init script is currently "-l rundeck". This init script will fail if you're running Rundeck as a different user. I suggest that the runuser line in the init script follow expected convention above.

**How to reproduce Behavior**

**Comment by gschueler** [comment]
The rpm spec defines a `rundeck` user and uses the user home dir `/var/lib/rundeck` as the rundeck base dir.  I suppose the init `rundeckd` script could use a variable instead of hardcoding it. Can describe how your setup works with a different user?

**Comment by niall-munnelly** [comment]
Heya, Greg,

Our company uses formatted service accounts for dev/integration, staging and production. Consequently, there are a couple IDs in play, and none of them are "rundeck ;)"

After each rpm installation, I chown the directories back to the appropriate owner, restore my config files and change runuser line from -l rundeck to -l "${RUNDECK_USER}" or whatever the variable is in the profile.

Yours,
Niall

**Comment by niall-munnelly** [comment]
Following up on this.
With the RPM distribution, line 34 of the rundeckd service still says

`nohup runuser -s /bin/bash -l rundeck -c "$rundeckd" >>$servicelog 2>&1 &`

Line 18 explicitly sources the Rundeck profile, which (I think) defines the RUNDECK_USER variable:

`. /etc/rundeck/profile`

Why make users change the value in two files when changing it only in profile will do the trick?
