### ISSUE TITLE
cancel + save button throw an error on one job

### ISSUE THREAD

**Issue by patrickmellinger** [rundeck/rundeck#2439]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.6.7-1
* install type: (rpm,deb,war,launcher?) deb
* OS Name/version: ubuntu 14.04
* DB Type/version: mysql? postgres? h2?.. h2

When I cancel/save editing a specific job, every time i get a connection reset error in the browser (tested with firefox and chrome). i haven't seen anything written up about this issue yet, so sorry if it's a dupe.

It even happens when i clone the job to another project. 

it happens when i ignore the httpd proxy and go straight to the rundeck service.

**Expected Behavior**
Cancel button on the job edit screen should take me back to the job summary page.

**Actual Behavior**
Connection reset error in the browser:
![screen shot 2017-04-17 at 14 35 45](https://cloud.githubusercontent.com/assets/17731759/25105826/3b917f68-237b-11e7-9954-292c43784132.png)

The only error in any log file that i've been able to find is in the httpd error log, and only when i'm using the proxy.

> [proxy_http:error] [pid 8748:tid 140324886238976] (104)Connection reset by peer: [client my_ip:my_port] AH01095: prefetch request body failed to 127.0.0.1:4440 (localhost) from my_ip (), referer: http://my_rundeck_url/project/ownTasks/job/edit/my_UUID

**How to reproduce Behavior**
I attached the yaml job definition. 
1. import the definition. 
2. edit the new job. 
3. click cancel.

[broken_job_yaml.txt](https://github.com/rundeck/rundeck/files/926734/broken_job_yaml.txt)

**Comment by patrickmellinger** [comment]
i upgraded this instance to rundeck 2.8.2 and the problem was NOT solved. :(

**Comment by patrickmellinger** [comment]
this is in the JS console in firefox when i click the cancel button, and i missed it before. 

"Empty string passed to getElementById()."   jquery-5393bf5931b3c4e7052edeec0d67327b.js:19:34

Thanks to Alex-SF on IRC for helping find that.

**Comment by gschueler** [comment]
have not been able to reproduced this

**Comment by patrickmellinger** [comment]
well, thank you for trying to repro it. i'm going to lose access to this host (new job) in a few days, so if there's any info you need from me to help repro this, please let me know.

**Comment by ahonor** [comment]
Please reopen if this remains a problem
