### ISSUE TITLE
Allow option value for thread count

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#2440]
Currently, only an integer is allowed for thread count:

![image](https://cloud.githubusercontent.com/assets/275924/25151271/d7591730-2439-11e7-8ece-f1b3ca77b5d4.png)

It is desirable to also let users define an option to set that parameter.

**Comment by rooty0** [comment]
+1

**Comment by rooty0** [comment]
Hey guys, @ahonor @gschueler , just wondering how complex this task is? Is it possible to implement this in next nearest version? Imo, very useful improvement.

**Comment by ahonor** [comment]
@rooty0 It's pretty simple just need to get it done!

**Comment by gfreestone** [comment]
We would also like to see this.
