### ISSUE TITLE
v2.8.1 Cannot create table job_file_record due to reserved word (oracle)

### ISSUE THREAD

**Issue by jquick** [rundeck/rundeck#2441]
Issue type: Bug report/Enhancement Request

On upgrading to 2.8.1 from 2.7.9 The following error happens on startup:
```
 13 2017-04-18 19:04:15,429 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create table job_file_record (id number(19,0) not null, version number(19,0) not null, date_created timestamp not null, execution_id number(19,0),     expiration_date timestamp, file_name varchar2(1024 char), file_state varchar2(255 char) not null, job_id varchar2(255 char) not null, last_updated timestamp not null, project varchar2(255 char) not null, record_name varchar2(255 char), record_type varchar2(255 char) not null, server_nodeuuid clob, sha varchar2(64 char) not null, size number(19,0) not null, storage_meta clob, storage_reference clob not null, storage_type varchar2(255 char) not null, rduser varchar2(255 char) not null, uuid varchar2(255 char) not null, primary key (id))
 14 2017-04-18 19:04:15,431 [main] ERROR hbm2ddl.SchemaUpdate  - ORA-00904: : invalid identifier
 15 
 16 2017-04-18 19:04:15,468 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: alter table job_file_record add constraint FK_dgig9thteq37sidkc38msxep foreign key (execution_id) references execution
 17 2017-04-18 19:04:15,468 [main] ERROR hbm2ddl.SchemaUpdate  - ORA-00942: table or view does not exist
```

**My Rundeck detail**

* Rundeck version: 2.8.1
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: oracle

**Expected Behavior**
Tabes successfully create

**Actual Behavior**
Dies on table creation. This is due to having a column named "size" as it is a restricted column name. Creation works fine when commenting out size ex:
```
create table job_file_record (
  id number(19,0) not null,
  version number(19,0) not null,
  date_created timestamp not null,
  execution_id number(19,0),
  expiration_date timestamp,
  file_name varchar2(1024 char),
  file_state varchar2(255 char) not null,
  job_id varchar2(255 char) not null,
  last_updated timestamp not null,
  project varchar2(255 char) not null,
  record_name varchar2(255 char),
  record_type varchar2(255 char) not null,
  server_nodeuuid clob,
  sha varchar2(64 char) not null,
  --size number(19,0) not null,
  storage_meta clob,
  storage_reference clob not null,
  storage_type varchar2(255 char) not null,
  rduser varchar2(255 char) not null,
  uuid varchar2(255 char) not null,
  primary key (id)
);
```
Note I have overrode the oracle dialect to handle clob/blob but this does not solve this as its a reserved word issue. Potentially you can create a table using a reserved word by using quotes like "size". But then you also have to select it using quotes whenever you try to use it.

**How to reproduce Behavior**
Apply patch 2.8.x patch using an oracle backend

**Comment by jquick** [comment]
I tried creating it with quotes but I get:
```
[2017-04-18 20:00:26,576] ERROR SqlExceptionHelper: ORA-01747: invalid user.table.column, table.column, or column specification
```
On startup and if you try to upload a file you also get that same error.

**Comment by gschueler** [comment]
can you try using backtick? `` ` ``

also alternately, try this in rundeck-config.properties:

    hibernate.globally_quoted_identifiers=true

**Comment by jquick** [comment]
Trying to create it with a backtick results in:
```
SQL Error: ORA-00911: invalid character
00911. 00000 -  "invalid character"
*Cause:    identifiers may not start with any ASCII character other than
           letters and numbers.  $#_ are also allowed after the first
           character.  Identifiers enclosed by doublequotes may contain
           any character other than a doublequote.  Alternative quotes
           (q'#...#') cannot use spaces, tabs, or carriage returns as
           delimiters.  For all other contexts, consult the SQL Language
           Reference Manual.
*Action:
```
Trying the:
`hibernate.globally_quoted_identifiers=true`
Also didn't work. It did create duplicate of all tables with lowercase table names instead of uppercase names. But either way I always got:
```
ORA-01747: invalid user.table.column, table.column, or column specification
```
On upload

**Comment by gschueler** [comment]
@jquick i think oracle uses double quotes for quoting, not backticks, sorry.  However, the hibernate mapping that rundeck uses I think has to be forced to quote the column.

**Comment by jquick** [comment]
Tried doing a clean install with the:
```
hibernate.globally_quoted_identifiers=true
```
looks like it does the name but not the columns from what I can see:
```
1283 2017-04-18 20:47:30,543 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create table "job_file_record" (id number(19,0) not null, version number(19,0) not null, date_created timestamp not null, execution_id number(19,     0), expiration_date timestamp, file_name varchar2(1024 char), file_state varchar2(255 char) not null, job_id varchar2(255 char) not null, last_updated timestamp not null, project varchar2(255 char) not null, record_name varchar2(25     5 char), record_type varchar2(255 char) not null, server_nodeuuid clob, sha varchar2(64 char) not null, size number(19,0) not null, storage_meta clob, storage_reference clob not null, storage_type varchar2(255 char) not null, rduse     r varchar2(255 char) not null, uuid varchar2(255 char) not null, primary key (id))
1284 2017-04-18 20:47:30,545 [main] ERROR hbm2ddl.SchemaUpdate  - ORA-00904: : invalid identifier
1285 
1286 2017-04-18 20:47:31,030 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: alter table "job_file_record" add constraint FK_dgig9thteq37sidkc38msxep foreign key (execution_id) references "execution"
1287 2017-04-18 20:47:31,030 [main] ERROR hbm2ddl.SchemaUpdate  - ORA-00942: table or view does not exist
```
And the same issues if you manually make the table with quotes after. Would it be a possibility to rename/map the column to something like file_size?

**Comment by jquick** [comment]
Also it looks like that property causes other issues:
(trying to create a new project)
```
Hibernate operation: could not prepare statement; bad SQL grammar [insert into "project" (id, version, date_created, description, last_updated, name) values ("hibernate_sequence".nextval, ?, ?, ?, ?, ?)]; nested exception is java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist
```

**Comment by jquick** [comment]
I also read some places that if you declare the name like:
https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/test/java/org/hibernate/test/quote/User.java#L31
name = "`User`"
It should auto work via hibernate, not sure if this will actually work or not though.

**Comment by gschueler** [comment]
@jquick i am going to test using the "`size`" declaration

**Comment by gschueler** [comment]
looks like like mapping the column as ``"`SIZE`"`` may work, hopefully get a fix out soon

**Comment by jquick** [comment]
@gschueler if needed you can link me to a deb and I can deploy and test it

**Comment by gschueler** [comment]
@jquick the 2.8.2 snapshot build should have it: https://bintray.com/rundeck/ci-snapshot-deb/rundeck

**Comment by jquick** [comment]
@gschueler Tested this out. Working as expected!

Was able to:

- build all tables on a fresh DB (oracle 12c)
- create projects/jobs
- upload files as options on jobs

I confirmed rows were added into the job_file_record table and they included the size column as expected. Thanks!
