### ISSUE TITLE
node step,online edit script where to save

### ISSUE THREAD

**Issue by SolarisYan** [rundeck/rundeck#2459]
Hello, i use rundeck to do devops. can any one tell me
where the  "Script - Execute an inline script" content to save?
![image](https://cloud.githubusercontent.com/assets/8148762/25381097/14854ee8-29e5-11e7-8794-564711d56f26.png)

**Comment by gschueler** [comment]
it is stored in the database

**Comment by SolarisYan** [comment]
@gschueler thanks, i have get it in my enviroment.
