### ISSUE TITLE
why can't i find installation docs

### ISSUE THREAD

**Issue by qinzl1** [rundeck/rundeck#2460]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 
* install type: (rpm,deb,war,launcher?)
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**

**Actual Behavior**

**How to reproduce Behavior**

**Comment by willemdh** [comment]
... Did you try Googling it?
https://www.google.be/search?q=how+to+install+rundeck&oq=how+to+install+rundeck
http://rundeck.org/docs/administration/installation.html
