### ISSUE TITLE
Change the storage to mysql

### ISSUE THREAD

**Issue by jamf4444** [rundeck/rundeck#2463]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: launcher
* OS Name/version: Linux 2.6.32-573.el6.x86_64
* DB Type/version: mysql

**Expected Behavior**

Change the storage to mysql

**Actual Behavior**

 I modified ~/rundeck/server/config/rundeck-config.properties like this

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
rundeck.v14.rdbsupport=true
grails.serverURL=http://172.16.208.221:4440
dataSource.dbCreate = update
#dataSource.url = jdbc:h2:file:/home/gpadmin/rundeck/server/data/grailsdb;MVCC=true
dataSource.url=jdbc:mysql://172.16.209.35:3306/rundeckdb?autoReconnect=true&useUnicode=yes&characterEncoding=UTF8
dataSource.username = root
dataSource.password = 123456
dataSource.driverClassName=com.mysql.jdbc.Driver
rundeck.projectsStorageType=db

Now my rundeck cannot start!Pls help me!

Thank you very much!!

**Comment by gschueler** [comment]
what kind of error message do you get?

**Comment by zionio** [comment]
according to http://rundeck.org/docs/administration/setting-up-an-rdb-datasource.html

`dataSource.url = jdbc:mysql://myserver/rundeckdb?autoReconnect=true`

so try: `dataSource.url=jdbc:mysql://172.16.209.35/rundeckdb?autoReconnect=true`

3306 is the default port, so can be omitted without problem

**Comment by ahonor** [comment]
Please reopen if this remains a concern
