### ISSUE TITLE
Feature: Interpolation in Resource-JSON

### ISSUE THREAD

**Issue by bdwyertech** [rundeck/rundeck#2465]
It'd be really nice to be able to have some more flexibility with regard to interpolation in the Resource-JSON model.

Maybe I have my syntax wrong, but this does not seem to work.

```json
"username": "${option.ssh.user!\"default_user\"}"
```

The idea would be to use the option.ssh.user if set in a job definition, otherwise fall back to the value in the node definition.

It'd also be nice to be able to pass in an array of values for things other than just the tags field 😄 

By the way, I've had this rewrite of the `chef-rundeck` gem up and running for a while, feel free to add it to your list of external services.
https://github.com/bdwyertech/chef-rundeck2

**Comment by ahonor** [comment]
@bdwyertech I finally added the plugin to the list.
