### ISSUE TITLE
Rundeck Start doesn't change the status and active Interface

### ISSUE THREAD

**Issue by CountZerro** [rundeck/rundeck#2467]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.8.1
* install type: (rpm,deb,war,launcher?) deb
* OS Name/version: Ubuntu 14.4
* DB Type/version: mysql? postgres? h2?.. any

**Expected Behavior**

Hi, 

So I have installed Rundeck with deb package :  
apt-get install openjdk-8-jdk
dpkg -i rundeck-2.8.2-1-GA.deb

Already was good.

**Actual Behavior**

But when I start Rundeck : sudo service rundeckd start
The status still at stop/waiting
And I can't launch the web interface (Unable to connect).
I don't know how to fix it.

**How to reproduce Behavior**

apt-get install openjdk-8-jdk
dpkg -i rundeck-2.8.2-1-GA.deb
sudo service rundeckd start

**Comment by sachdevaanshul** [comment]
having similar issue :-( service starts for like 3 seconds and then stops.
