### ISSUE TITLE
how to add node and shat 'stub' mean

### ISSUE THREAD

**Issue by qinzl1** [rundeck/rundeck#2471]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 
* install type: (rpm,deb,war,launcher?)
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**

**Actual Behavior**

**How to reproduce Behavior**

**Comment by zionio** [comment]
This is not the way to open issues.
What you're looking for is 'documentation'.

Take a look here: http://rundeck.org/docs/manual/nodes.html
And here: https://youtu.be/RxNSqprG_BU

**Comment by qinzl1** [comment]
@zionio this not the way add node is only search node

**Comment by zionio** [comment]
@qinzl1 watch the linked video

**Comment by qinzl1** [comment]
@zionio thanks

**Comment by gschueler** [comment]
Please post questions to the user group http://groups.google.com/group/rundeck-discuss or you can use the IRC channel: http://webchat.freenode.net/?nick=rundeckuser.&channels=rundeck&prompt=1
