### ISSUE TITLE
Illegal class name on groovy script with internal function

### ISSUE THREAD

**Issue by maxim0r** [rundeck/rundeck#2473]
Issue type: Bug report

The groovy script with internal functions does not work

**My Rundeck detail**

* Rundeck version:  2.8.2-1
* install type:  launcher
* OS Name/version: Debian8
* DB Type/version: h2

* groovy 2.2

**Expected Behavior**

The script runs successfully

**Actual Behavior**

The script falls with the exception of:
```
Caught: java.lang.ClassFormatError: Illegal class name "33-495-rundeck-dispatch-script/tmp$helloword" in class file 33-495-rundeck-dispatch-script/tmp$helloword
java.lang.ClassFormatError: Illegal class name "33-495-rundeck-dispatch-script/tmp$helloword" in class file 33-495-rundeck-dispatch-script/tmp$helloword
at 33-495-rundeck-dispatch-script.tmp.run(33-495-rundeck-dispatch-script.tmp.sh:3)
```

**How to reproduce Behavior**

1. Install groovy
2. Create job with inline script еxecutable locally
```
#!/usr/bin/groovy

helloword('Andy')

def helloword(user) {
    println "Hello, $user!"
}
```
3. Execute job

**Comment by ahonor** [comment]
Reproduced
