### ISSUE TITLE
Rundeck Clustering

### ISSUE THREAD

**Issue by franctony** [rundeck/rundeck#2476]
Issue type: Bug report/Enhancement Request

  -->

**My Rundeck detail**
Rundeck 2.7.3-1 - Currently using standalone version 

* Rundeck version: Rundeck 2.7.3-1
* install type: (rpm,deb,war,launcher?) : rpm
* OS Name/version: Linux
* DB Type/version: mysql? postgres? h2?.. Oracle

**Expected Behavior**

Hi Team, 

Currently we are using standlone installed..

But,
We are planining to make Rundeck in cluster mode... so we are planning to go with WAR deployment to deploy in tomcat nodes

Tomcat1 & tomcat1 - with WAR deployment
Database - Oracle.. Could you please share the document to achieve this..

will this be active, active mode ? How the load is getting distributed ?
When tomcat1 goes down, how tomcat2 will handle the running job ?

Please adivse on this and provide documentation to achive cluster with two nodes

Thanks,
Antony

**Comment by mrala** [comment]
There is some documentation about clustering here: http://rundeck.org/docs/administration/scaling-rundeck.html#clustering-and-horizontal-scaling

**Comment by franctony** [comment]
Above link doesn't have enough information

**Comment by ahonor** [comment]
@franctony "clustering" with the open source version is fairly limited. Traffic and execution load is distributed by your web load balancer of choice. If you are interested in clustering that can help with auto recovery and load balancing see Pro Cluster. https://www.rundeck.com/product-editions
