### ISSUE TITLE
Rundeck System Datetime 

### ISSUE THREAD

**Issue by ofostier** [rundeck/rundeck#2478]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: build	2.7.3-1
* install type: Docker 
* OS Name/version: Linux Debian
* DB Type/version: mysql

Rundeck don't take the right system datetime.
I've change my /etc/localtime to Paris
`/etc/localtime -> /usr/share/zoneinfo/Europe/Paris`

Now system give me this result with the command "date"
>> Wed May  3 **13:54**:08 CEST 2017

But Rundeck stay with :
>> 2017-05-03T**11:54**:08Z

So i got error when i schedule jobs.

Any idea ?

Thanks

**Comment by BenPhegan** [comment]
You need to also pass this through to the JVM.  If you are using the jordan/rundeck Docker image you can do this with an environment variable:

`
RDECK_JVM_SETTINGS=-Duser.timezone=Europe/Paris
`

Regardless of which image you are using though, as long as you can get that passed in to the JVM args, you should be ok.

**Comment by ofostier** [comment]
It is working
Thx a lot
