### ISSUE TITLE
Can't get SSL proxy to work via HAProxy

### ISSUE THREAD

**Issue by dandunckelman** [rundeck/rundeck#2490]
Issue type: Support

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: deb via Puppet module
* OS Name/version:  Ubuntu 16.04
* DB Type/version: h2

Here's what I'm doing:
- We have a DNS name (i.e. `rd.****.com`), which points to a public IP
- Our firewall maps that public IP to a private IP, which is a virtual IP for our load-balancers (`LBVIP`)
- HAProxy configs:
  - **Frontend**

        frontend vip-https
          bind LBVIP:443 ssl no-sslv3 crt /etc/ssl/certs/ssl.pem
          mode http
          rspadd Strict-Transport-Security:\ max-age=15768000
          acl is_request_for_rundeck hdr(Host) -i rd.****.com
          use_backend rundeck-server if is_request_for_rundeck

  - **Backend**

        backend rundeck-server
          mode http
          balance source
          compression offload
          hash-type consistent
          reqadd X-Forwarded-Proto:\ https
          stats enable
          server rd-vm-hostname rd-vm-ip:4440 check

I followed this:  http://rundeck.org/docs/administration/configuring-ssl.html#using-an-ssl-terminated-proxy
- I added this to `/etc/default/rundeckd`:

      RDECK_JVM_SETTINGS="-Xmx1024m -Xms256m -server -Drundeck.jetty.connector.forwarded=true"
- I updated `grails.serverURL` to be `grails.serverURL = "https://rd.****.com"`

**Expected Behavior**
Requests to `https://rd.****.com` properly load the site

**Actual Behavior**
Requests to `https://rd.****.com` return `curl: (52) Empty reply from server`

I think this is an HAProxy issue, because I don't see anything in the access logs for those requests.  Just looking for help on this, since I'm stuck.

Relates to #732

**Comment by dandunckelman** [comment]
@gschueler you've been able to help me before.  Please let me know if you can help or if you can ping someone more familiar with HAProxy.  Thanks!

**Comment by gschueler** [comment]
@dandunckelman sorry, I don't have any experience with HAProxy

**Comment by dandunckelman** [comment]
Closing as I don't care to go further with this.
