### ISSUE TITLE
js issue when running job from popup

### ISSUE THREAD

**Issue by ronave** [rundeck/rundeck#2494]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.1.0
* install type: launcher
* OS Name/version: Linux Mint 18 Sarah
* DB Type/version: mysql

**Expected Behavior**
When i run a job from the popup screen, the job should run and refresh hte "activity for jobs"

**Actual Behavior**
When i run a job from the popup screen, the job runs but JS fails and the screen is not refreshed with the job execution details

**How to reproduce Behavior**
1.-Get into any job
2.-Press on any job run icon
3.-Start the job

![issue js](https://cloud.githubusercontent.com/assets/24272992/25758185/e072d302-31a3-11e7-96d5-8dd3a3808e48.png)

**Comment by gschueler** [comment]
fixed in https://github.com/rundeck/rundeck/commit/1829742107893d81bc7cd9a78522b5f6fcd0cd1b
