### ISSUE TITLE
Slow Page Loads with Many ACL Policy Entries

### ISSUE THREAD

**Issue by swtch1** [rundeck/rundeck#2495]
Issue type: Enhancement Request/Information Request

The problem I am trying to solve:
Have at least two aclpolicy entries for each LDAP group in my organization.  One for Rundeck access and one that would match against an attribute "accessGroups" on each node.  The attribute corresponds to groups which can execute against that node.  This information comes from config files on the node itself.

Example aclpolicy defining node access:
```
description: Allow Run on Nodes for Group somegroup
by:
  group: somegroup
context:
  project: .*
for:
  node:
  - match:
      accessGroups: "somegroup"
    allow: [read,run]
```

When adding many aclpolicy files (database entries in this case) page load times can slow considerably.  I am trying to support a very large installation and in testing added 5000 aclpolicy entries (yes, I know this is a lot) and saw page loads of around 10-15 seconds.  In troubleshooting I see that for each page load the database is queried for all aclpolicy entries 4 times and likely does the parsing from all policy entries.  

Logged Database Query String:
`select this_.id as id1_15_0_, this_.version as version2_15_0_, this_.data as data3_15_0_, this_.date_created as date_cre4_15_0_, this_.dir as dir5_15_0_, this_.json_data as json_dat6_15_0_, this_.last_updated as last_upd7_15_0_, this_.name as name8_15_0_, this_.namespace as namespac9_15_0_, this_.path_sha as path_sh10_15_0_ from storage this_ where this_.namespace='config' and (this_.dir='acls' or this_.dir like 'acls/%') order by this_.name desc`

I believe I could optimize the query to only process policy files that match the user's groups, and have the query run fewer times.  I would like to do some work and submit a pull request, but I am having trouble seeing where this work is done in the code base.  If you could point me to where these queries are being made generally I can put some time on it.  Or.. if you think there is a better way to define node access rights I would be happy to investigate that route.

EDIT - I did notice [issue 328](https://github.com/rundeck/rundeck/issues/328) so I will investigate there starting Monday, but any direction would be greatly appreciated.

**My Rundeck detail**

* Rundeck version: 2.7.1-1
* install type: RMP
* OS Name/version: CentOS7
* DB Type/version: MariaDB (mysql) 10.2

**Comment by gschueler** [comment]
you might try adding an index into the DB to help with those queries. If that appears to help we can modify the domain classes to generate those indexes. e.g.

    create index STORAGE_INDEX1 on storage(namespace,dir,name)

**Comment by swtch1** [comment]
Greg,

Thanks for the suggestion but I'm not sure that's going to help a lot.  The situation above where I added 5000 acl policies to the database was a test, there was very little else in the storage database and since all aclpolicy entries have namespace=config and dir=acls all of the rows would still be scanned anyways.  The name of the policy is not referenced, except for ordering, in the query above.  

I was planning to try to revise the search a bit so that less acl policies have to be processed in code.  From what I can tell by the queries all acl policies are being queried and parsed regardless of whether they apply or not.  I made a test query against the database grabbing only records that had a particular group in the data field and that took a few ms so I'm reasonably confident the database response time isn't the issue.  

Would you be able to point me to where the query I described is being made so I could dig deeper?  I can write decent Java, but just cannot discern the specific location of this query and surrounding code in the code base.  I really appreciate you looking at this.
