### ISSUE TITLE
Git Plugin significantly slows down jobs view

### ISSUE THREAD

**Issue by shoelzle** [rundeck/rundeck#2496]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: launcher
* OS Name/version: Debian wheezy, Kernel 3.2.0-4-amd64
* DB Type/version: mysql 5.6.31

**Expected Behavior**
Without the GIT plugin enable, the jobs page loads in less than 1 second. With the GIT plugin enabled, I expect the jobs page to load approximately in the same time.

**Actual Behavior**
With the GIT plugin enabled, the jobs page takes ~30 seconds to load.

**How to reproduce Behavior**
In order to reproduce this issue, I suggest you create some jobs (I have 214 jobs) with code in an attached GIT repo.

I'm happy to provide more information if needed.

**Comment by gschueler** [comment]
do you have "Fetch Automatically" set in your git plugin config? 

Is this with the import or export enabled? both?

**Comment by shoelzle** [comment]
Fetch automatically is not set.

**Comment by shoelzle** [comment]
I measured the loading times:
- Import enabled, Export enabled (23 sec initial page load, 11 sec reload)
- Import enabled, Export disabled (16 sec initial page load, 9 sec reload)
- Import disabled, Export enabled (25 sec initial page load, 9 sec reload)
- Import disabled, Export disabled (5 sec initial page load, 3 sec reload)

How I measured:
- Initial page load:
   - Stop rundeck
   - Start rundeck
   - Load jobs view
- Reload:
   - After initial page load, load jobs view again

Runtime Env:
- VM with 2 cores
- 16 GB RAM
- Versions are mentioned in the description
- The VM was not busy with other tasks at the time of the measurements

**Comment by Kurisutian** [comment]
I have the same problem with git and slow loading times. Any news on that?

**Comment by gschueler** [comment]
nb: perhaps job status caching should be improved. perf analysis should be done on the integration b/w rundeck and scm/git plugin

**Comment by RichardGarforth** [comment]
Any update on this issue.  I have same issue with 2.11.5

**Comment by shoelzle** [comment]
I don't have this issue since I upgraded to 3.0.x.
