### ISSUE TITLE
Requesting to stop the service while jobs are running doesn't fully kill the service

### ISSUE THREAD

**Issue by dandunckelman** [rundeck/rundeck#2498]
Issue type: Bug report

**My Rundeck detail**
* Rundeck version: 2.8.2
* install type: deb
* OS Name/version: Ubuntu 16.04
* DB Type/version: h2

**Expected Behavior**
When I run `systemctl stop rundeckd`, I expect all Rundeck processes to stop running.

**Actual Behavior**
When I run `systemctl stop rundeckd`, the `bash` process that starts the java process is killed, but the java process continues to run.
- The `bash` process ID matches what is in `/var/run/rundeckd.pid`
- You'll also see that `systemctl status rundeckd` reports that it has stopped

**How to reproduce Behavior**
- Fresh install
- Start the service:  `systemctl start rundeckd`
- Wait until the service has started
- Confirm it's working via `curl -v localhost:4440`
- Stop the service:  `systemctl stop rundeckd`
- See that the bash process was killed, but the java process remains running
- Because of that, if you were to call `systemctl restart rundeckd`, a new `bash` process is started, but it then fails with this error from `/var/log/rundeck/service.log`:

        2017-05-09 17:52:59.725:WARN:oejuc.AbstractLifeCycle:main: FAILED ServerConnector@36e95b7b{HTTP/1.1}{0.0.0.0:4440}: java.net.BindException: Address already in use
- The only workaround I have is to kill all processes found from `ps aux | grep -i rundeckd` using `kill -9 PID`

**Comment by dandunckelman** [comment]
To be extra sure of this, I explicitly ran all the commands for `stop` from `/etc/init.d/rundeckd` and got the same result.

**Comment by dandunckelman** [comment]
This properly killed both the bash & java processes:  `pkill -P $(cat $PIDFILE)` but maybe there's a way to tweak `killproc` and or the value in `$rundeckd` to get it to work?

**Comment by Dalma-TB** [comment]
same OS and rundeck version -> same is happening, although -9 is not necessary, simple kill is enough. So it is definitely reproducible.

**Comment by dandunckelman** [comment]
To add more context to this:  it seems to happen when it tries to stop the service while one or more jobs are currently running.

This is what I see:

```Bash
# Stop service
systemctl stop rundeckd

# Check for running processes
root@rundeck-01:~# ps aux | grep -i rundeck
rundeck   3671  0.0  0.0  45248  3972 ?        Ss   17:13   0:00 /lib/systemd/systemd --user
rundeck   3675  0.0  0.0  61216  1620 ?        S    17:13   0:00 (sd-pam)
rundeck   3678 12.7 22.0 3621552 891464 ?      Ssl  17:13   1:53 java -Djava.security.auth.login.config=/etc/rundeck/j
aas-auth.conf -Dloginmodule.name=authentication -Drdeck.config=/etc/rundeck -Drundeck.server.configDir=/etc/rundeck -D
server.datastore.path=/var/lib/rundeck/data/rundeck -Drundeck.server.serverDir=/var/lib/rundeck -Drdeck.projects=/var/
lib/rundeck/projects -Drdeck.runlogs=/var/lib/rundeck/logs -Drundeck.config.location=/etc/rundeck/rundeck-config.groov
y -Djava.io.tmpdir=/tmp/rundeck -Drundeck.server.workDir=/tmp/rundeck -Dserver.http.port=4440 -Xmx1024m -Xms256m -serv
er -cp /var/lib/rundeck/bootstrap/log4j-1.2.16.jar:/var/lib/rundeck/bootstrap/jna-3.2.2.jar:/var/lib/rundeck/bootstrap
/jetty-http-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/javax.servlet-3.0.0.v201112011016.jar:/var/lib/rundeck/boot
strap/jetty-jaas-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-all-9.0.7.v20131107.jar:/var/lib/rundeck/bootstr
ap/jetty-server-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/rundeck-jetty-server-2.8.2.jar:/var/lib/rundeck/bootstr
ap/not-yet-commons-ssl-0.3.11.jar:/var/lib/rundeck/bootstrap/libpam4j-1.5.jar:/var/lib/rundeck/bootstrap/jetty-io-9.0.
7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-security-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-util-9.
0.7.v20131107.jar com.dtolabs.rundeck.RunServer /var/lib/rundeck

# Kill processes by PID
root@rundeck-01:~# kill -9 3671 3678

# See that no processes now exist
root@rundeck-01:~# ps aux | grep -i rundeck
root      7150  0.0  0.0  16576  2096 pts/3    S+   17:28   0:00 grep --color=auto -i rundeck
```

**Comment by dandunckelman** [comment]
May be related to https://github.com/rundeck/rundeck/issues/2508 and https://github.com/rundeck/rundeck/pull/2532

**Comment by hugospinto** [comment]
+1

**Comment by acasademont** [comment]
Definitely related to the way Rundeck starts with the current int scripts

**Comment by gschueler** [comment]
possibly related: when stopping the service if a job is running, I've seen rundeck get into a loop as it tries to "finish" the executions by writing them to the DB, because it has logic to retry-with-backoff several times if the DB write fails (which can happen spuriously due to some other process/person modifying the job).  However because the process shutdown has disconnected from the DB, all the DB writes are failing, but the backoff/retry loop is not aware of that, so it takes some time for the retries to wait and repeat until they reach max retry.

Perhaps a fix is if the app shutdown is detected, this specific retry loop can be short circuited

**Comment by acasademont** [comment]
HI @gschueler I believe there are 2 different problems here.

First of all there's an issue with the init scripts in Debian. Right now, when you run "service rundeckd start" 2 processes are spawned. the first one just launches the actual rundeck java process, which is weird, that should be the job of the init script. That's where the problem happens when you run "service rundeckd stop", it just stops the first process (27220), while the actual java app (the second process) keeps running without ever noticing someone has signaled it to stop.

```
root     27220  0.0  0.0  54864  3504 ?        S    00:29   0:00 su -s /bin/bash rundeck -c java -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf            -Dloginmodule.name=RDpropertyfilelogin            -Drdeck.config=/etc/rundeck            -Drundeck.server.configDir=/etc/rundeck            -Dserver.datastore.path=/var/lib/rundeck/data/rundeck            -Drundeck.server.serverDir=/var/lib/rundeck            -Drdeck.projects=/var/lib/rundeck/projects            -Drdeck.runlogs=/var/lib/rundeck/logs            -Drundeck.config.location=/etc/rundeck/rundeck-config.properties            -Djava.io.tmpdir=/tmp/rundeck            -Drundeck.server.workDir=/tmp/rundeck            -Dserver.http.port=4440  -Xmx4096m -Xms1024m -server -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=14440 -Dcom.sun.management.jmxremote.rmi.port=14440 -Djava.rmi.server.hostname=bo02.ulabox.net  -cp /var/lib/rundeck/bootstrap/not-yet-commons-ssl-0.3.11.jar:/var/lib/rundeck/bootstrap/jetty-server-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-security-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/log4j-1.2.16.jar:/var/lib/rundeck/bootstrap/javax.servlet-3.0.0.v201112011016.jar:/var/lib/rundeck/bootstrap/jetty-jaas-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-util-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/rundeck-jetty-server-2.8.1.jar:/var/lib/rundeck/bootstrap/jetty-all-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jna-3.2.2.jar:/var/lib/rundeck/bootstrap/libpam4j-1.5.jar:/var/lib/rundeck/bootstrap/jetty-http-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-io-9.0.7.v20131107.jar com.dtolabs.rundeck.RunServer /var/lib/rundeck                                    
rundeck  27229  2.8  9.7 10393632 3186600 ?    Ssl  00:29  17:14 java -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf -Dloginmodule.name=RDpropertyfilelogin -Drdeck.config=/etc/rundeck -Drundeck.server.configDir=/etc/rundeck -Dserver.datastore.path=/var/lib/rundeck/data/rundeck -Drundeck.server.serverDir=/var/lib/rundeck -Drdeck.projects=/var/lib/rundeck/projects -Drdeck.runlogs=/var/lib/rundeck/logs -Drundeck.config.location=/etc/rundeck/rundeck-config.properties -Djava.io.tmpdir=/tmp/rundeck -Drundeck.server.workDir=/tmp/rundeck -Dserver.http.port=4440 -Xmx4096m -Xms1024m -server -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.port=14440 -Dcom.sun.management.jmxremote.rmi.port=14440 -Djava.rmi.server.hostname=bo02.ulabox.net -cp /var/lib/rundeck/bootstrap/not-yet-commons-ssl-0.3.11.jar:/var/lib/rundeck/bootstrap/jetty-server-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-security-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/log4j-1.2.16.jar:/var/lib/rundeck/bootstrap/javax.servlet-3.0.0.v201112011016.jar:/var/lib/rundeck/bootstrap/jetty-jaas-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-util-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/rundeck-jetty-server-2.8.1.jar:/var/lib/rundeck/bootstrap/jetty-all-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jna-3.2.2.jar:/var/lib/rundeck/bootstrap/libpam4j-1.5.jar:/var/lib/rundeck/bootstrap/jetty-http-9.0.7.v20131107.jar:/var/lib/rundeck/bootstrap/jetty-io-9.0.7.v20131107.jar com.dtolabs.rundeck.RunServer /var/lib/rundeck
```

The second problem arises when you actually try to send a SIGTERM "kill 27229" to the second process, the actual Rundeck java process. But then happens what you said: If a job is running, it will start outputting these "can't save state" messages with the exponential backoff, which takes forever and I just end up doing a "kill -9 27229", which is bad.

**Comment by acasademont** [comment]
So I believe the solution here is 2-fold.

First fix the Debian init scripts using "start-stop-daemon", which is meant for that job. Thats what PR #2532 fixes

Second fix is to tackle the problem you mentioned, gracefully kill rundeck, even though there might be running processes.

**Comment by dandunckelman** [comment]
This continues to hurt on the latest version (2.10.6).

It feels bad.
