### ISSUE TITLE
Is there a way to provide a dropdown menu based on option selection

### ISSUE THREAD

**Issue by gangadhar01a** [rundeck/rundeck#2506]
Issue type: Enhancement Request

We have 2 options "select node" and "enter service" and job we set is to restart a service on selected nodes from first option. 
User will select a node and enter the service name manually for 2nd option. We have more than 30 services for each "node" and I can add all these services to the second option as a drop down menu. Which means the 2nd option will have a dropdown with more than 90 values.

Is there any way that 2nd option (select service) will provide a dropdown menu based on the selection from 1st option (node)?

**My Rundeck detail**

* Rundeck version: 2.7.3-1
* install type: (rpm,deb,war,launcher?):rpm
* OS Name/version: CentOS 7
* DB Type/version: mysql? postgres? h2?..MySql

**Expected Behavior**
Select a node from option 1
and
Based on node selection the dropdown for "enter service" will show up.

**Actual Behavior**

**How to reproduce Behavior**

**Comment by ahonor** [comment]
@gangadhar01a yes that is possible. Take a look here: http://rundeck.org/docs/manual/jobs.html#cascading-remote-options
