### ISSUE TITLE
Add checkboxes to allow disabling steps in a workflow when executing a job

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#251]
Allow the steps to be selectively enabled/disabled for a workflow when you go to run a job.

**Comment by NFDWADM** [comment]
Would also really appreciate this feature!

**Comment by ranjithvaddepally** [comment]
This could be a very useful feature.

**Comment by eskimo-roll** [comment]
+1

**Comment by ZoeLeah** [comment]
+1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
