### ISSUE TITLE
Scripts hangs due to problems with redirection of stdin (windows)

### ISSUE THREAD

**Issue by eblikstad** [rundeck/rundeck#2511]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.6.11
* install type: launcher
* OS Name/version: Windows 2012 R2
* Java: Java 8 Update 112
* DB Type/version: SQL Server 2008 R2

**Expected Behavior**
Rundeck should handle redirection of stdin and make sure that no spawned processes are waiting for a stdin response.

**Actual Behavior**
While executing a single script, the process seems to hang on a second check of stdin. We are experiencing this problem with all script execution.

**How to reproduce Behavior**
In an empty Rundeck job add a "Script file or URL" step. Input the file path of the following cmd script and use "cmd.exe /c" for invocation script"

wmi.cmd (local Rundeck server script file):
winrs.exe -r:server28 -u:domain\user -p:password "wmic OS Get LastBootupTime /Value"
winrs.exe -r:server28 -u:domain\user -p:password "wmic OS Get LastBootupTime /Value"

If you modify the script command line with a dummy input pipe the problem does not occur.
call | winrs.exe -r:server28 -u:domain\user -p:password "wmic OS Get LastBootupTime /Value"

I have tried different methods of launching Rundeck server, but the stdin of the parent process of Rundeck Java does not seem to matter.
Example of launching Rundeck with stdin redirected to nul.
java.exe -Xmx4096m -classpath C:\rundeck-2.6.11\rundeck-launcher-2.6.11.jar -Dserver.http.port=80 -Dserver.https.port=443 -Drundeck.ssl.config=C:/rundeck-2.6.11/server/config/ssl.properties com.dtolabs.rundeck.ExpandRunServer --skipinstall < nul

**Workaround**
We are using "Execute inline script" steps in our jobs. PowerShell script workaround is to use the inputformat none (which redirect stdin to nul). For cmd.exe scripts we modify the invocation to include a dummy input pipe "cmd.exe /c call | "

**Comment by eblikstad** [comment]
I have completed a workaround for this issue on Windows. PowerShell has support for input redirection, while cmd.exe needs a dummy pipe with "call".

PowerShell invocation string:
"powershell.exe -inputformat none -noninteractive -nologo -command"

cmd.exe invocation string:
"cmd.exe /c call |"

**Comment by eblikstad** [comment]
Rundeck uses the deprecated exec method for executing processes and the output stream (child input stream) are closed immediately upon execution. To my understanding also the child input stream needs a separate thread and handling to avoid native platform process deadlocks.

**Comment by eblikstad** [comment]
I have reproduced the problem using a simple Java program. If the process output stream is closed, my cmd.exe script using winrs.exe hangs. The process output pipe should not be closed before after the process has finished (on Windows).

I have enclosed Java source and cmd.exe script example. The Java example hangs upon running on a Windows computer. 

[Exec.zip](https://github.com/rundeck/rundeck/files/1033395/Exec.zip)

**Comment by eblikstad** [comment]
I have created patches for the plugin script-plugin and the rundeck:core project.
[patches.zip](https://github.com/rundeck/rundeck/files/1042260/patches.zip)

**Comment by gschueler** [comment]
Hi @eblikstad thanks, can you submit those as a pull request?

**Comment by eblikstad** [comment]
I'm still doing testing and discovered there was several sources for this problem. I have been reading up on the ANT API and figured out the input output handling. There is a bug in ANT that causes ANT to "inherit" the input stream from the project which is Rundeck. Doing some more testing with the proposed workaround in the ANT issue. https://bz.apache.org/bugzilla/show_bug.cgi?id=36903

**Comment by eblikstad** [comment]
One of the bugs is actually in the Apache ANT libraries. I have submitted a bug report.
https://bz.apache.org/bugzilla/show_bug.cgi?id=61153

The best workaround at moment is to patch the ANT sourcecode and create a temporary jar file.

**Comment by eblikstad** [comment]
Test result for interpreter (process) input for "Script - Execute an inline script" step.

**Inline script step:**
@echo off
winrs.exe -r:yyy.xxx.local -u:administrator -p:password ipconfig.exe
winrs.exe -r:yyy.xxx.local -u:administrator -p:password ipconfig.exe

**Invocation string:** cmd.exe /c
**File extension:** cmd
**Nodes:** Execute locally


Success the job runs from the Rundeck instance running a Windows machine !

**Comment by eblikstad** [comment]
I'm really struggling with the WINRM plugin. I created patches for local script execution and the local command plugin, but the WINRM plugin using the overthere which does not close any I/O streams.

I have 500 nodes for testing, about 50 / 50 Windows 2008 R2 and Windows 2012 R2. My jobs hangs on about 2 / 100 and most often on Windows 2008 R2. The connection type for the nodes are WINRM_NATIVE which executes winrm.exe locally on the Rundeck server and connects to the remote server. The remote process completes, but the local winrs.exe gets stuck.

**Comment by eblikstad** [comment]
I have checked the command line for the local (Rundeck server) winrs.exe processes and all stopping executing the deletion of the remote script file.

winrs -remote:server:5985 -username:admin@DOMAIN -password:password -allowdelegate del C:\WINDOWS\TEMP\1365-20645-server-dispatch-script.tmp.ps1

**Comment by eblikstad** [comment]
I have been testing winrs.exe from a PowerShell script and emulating Rundeck usage. The problem does not occur with my PowerShell script. The script spawns winrs.exe processes, but not more than 32 at a time.

I have run thousands of winrs.exe executions, but none got stuck. The problem is in the Java code.

**Comment by gschueler** [comment]
have you tried with the latest release? can you post a sample job?

**Comment by eblikstad** [comment]
I have planned upgrade of Rundeck to the latest version. I'll start testing of the latest version as soon as possible and post my test job.

**Comment by eblikstad** [comment]
The problem is related to Java thread concurrency issues. My initial Rundeck was running 32 Rundeck threads and on 10 test iterations it hanged every time on 1-5 nodes. When running the same job with only 8 Rundeck threads the job only hanged 3 times on 1 node each time. The Java thread concurrency issue causes a win32 executable hang on the input stream (Rundeck output stream, winrs.exe child process input stream).

**Comment by gschueler** [comment]
when you say "Rundeck threads", do you mean separate jobs, or the threadcount for the nodes?

**Comment by eblikstad** [comment]
I have a single job targetting about 250 nodes. I have been adjusting the threadcount for the nodes. My test job has a single step running a inline script using the WINRM plugin which runs a local (Windows Rundeck server) winrs.exe process to connect to the remote node.

I'm using Apache Procrun for running Rundeck as a service on Windows and I have now tested launching the Rundeck server in an interactive console (cmd.exe) without using Procurun. Same result.

**Comment by eblikstad** [comment]
I have created a simple Java program that runs up to 32 Java threads which executes winrs.exe and waits. My program does 999 iterations of about 250 nodes and so far not a single winrs.exe hang. This is a concurrency issue but I'm uncertain what the root cause is. I'll either create a unit test for WINRM or copy parts of the sourcecode for handling I/O to my test program.

**Comment by gschueler** [comment]
have you tried running winrs.exe directly as a Command step, passing the parameters to dispatch the script (e.g. copy the script somewhere locally and hardcode the path) ?

I'm wondering if there is a problem with the threading in the way the local script is executed.  changing it to a command might reveal that

**Comment by eblikstad** [comment]
Yes, running a winrs.exe command line using a "local command" running in a job dispatched to the nodes works just fine. I have run 10 iterations of winrs.exe command on 250 nodes without a single hang. The problem is within the WINRM plugin.

Note: I'm running a patched version of the local command plugin. https://github.com/rundeck/rundeck/pull/2553

**Comment by gschueler** [comment]
which "WINRM plugin" are you using?

**Comment by eblikstad** [comment]
A slightly patched version of rundeck-winrm-plugin-1.3.2 with support for account delegation or popular called kerberos double hop authentication (winrs.exe -ad).

**Comment by gschueler** [comment]
ok, that plugin is a Node Executor, but does not execute scripts... 

can you post your Job definition so i can more precisely see how you are executing things?

**Comment by eblikstad** [comment]
I have been doing some testing of the overthere library. Both threads for handling output does not complete for some reason. I have added some dummy output to Rundeck just before the threads complete. I will find the problem soon...

**Comment by eblikstad** [comment]
The overthere library blocks on a stream.read() (signle character) in the stream handling threads. The run local command in Rundeck uses a buffer for reading, stream.read(buf).

**Comment by eblikstad** [comment]
Apache ANT also uses a buffer for reading multiple characters at a time. ANT also uses stream.available() to avoid some types of blocking.

**Comment by eblikstad** [comment]
I have found a workaround for the winrm plugin. Use processbuilder instead of runtime exec and redirect input before starting the process to NUL: on Windows.

ProcessBuilder b = new ProcessBuilder("winrs.exe",
b.redirectInput(new File( "NUL:" ));
Process process = b.start();

I need to do more testing to determine the root cause of this problem.

**Comment by eblikstad** [comment]
Code lines from overthere process exeuction (library used by the winrm plugin). Input redirection is the best workaround for problematic Windows tools. Redirect process input to NUL: and KEEP IT OPEN.

//p = Runtime.getRuntime().exec(cmd.toCommandArray(os, false), null, wd);
pb = new ProcessBuilder(cmd.toCommandArray(os, false));
pb.redirectInput(new File( "NUL:" ));
pb.directory(wd);
p = pb.start();
