### ISSUE TITLE
Job continue running forever even if all executions finished

### ISSUE THREAD

**Issue by cxadmin** [rundeck/rundeck#2513]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version:  Rundeck 2.8.2-1
* install type: rpm
* OS Name/version:  CentOS Linux release 7.3.1611 (Core)

**Expected Behavior**
When all execution steps completed I should get failed/success message in web ui.

**Actual Behavior**
Job continue running forever

**How to reproduce Behavior**
It is happen only when I am running on multiple nodes (**more than 10**)
I am using winrm to run powershell commands on many windows machines.

![image](https://cloud.githubusercontent.com/assets/22290258/26090493/0b719f12-3a0e-11e7-82b5-8beca3abfbfb.png)

**Comment by sdepablos** [comment]
Look at this #2228. It's related to a migration not executed.
