### ISSUE TITLE
Node List - Fails to display greater than 100 nodes per page

### ISSUE THREAD

**Issue by JustRiedy** [rundeck/rundeck#2514]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2
* Install type: RPM
* OS Name/version: CentOS 7
* DB Type/version: postgres

**Expected Behavior**
On the node list page my filter returns greater than 20 results, in this case 665. I want to view more nodes per page so I change the per page value to a higher value and see that many results per page.

**Actual Behavior**
On changing the Per Page value to any value greater than 100, the page refreshes successfully but still only displays 100 results.

**How to reproduce Behavior**
Change the Per Page value to any number greater than 100.

**Further Info**
Is there a log I can look in to grab errors around this page generation to assist in troubleshooting?
My node list is generated from a Script, configured in Project Settings, Resource Format = JSON

**Comment by JustRiedy** [comment]
Just rebuilt my Rundeck setup onto a MSSQL database backend and the same issue occurs, unsure if this info will help.

**Comment by gschueler** [comment]
there is an internal truncation value of 100, meant to be used when the node results are displayed e.g. in a widget like in the job editor page.  Sounds like the internal truncation is happening even if the paging size is greater than that.  The fix would be to not truncate results if paging size is greater than the truncation size
