### ISSUE TITLE
Concurrent job executions in clustered environment with v2.7.3

### ISSUE THREAD

**Issue by MoradT** [rundeck/rundeck#2515]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.7.3
* install type: RPM
* OS Name/version: Oracle Linux v7.1.1 x64
* DB Type/version: Mysql (MarriaDB)

I am running on a Clustered environment using below settings:
Node#1
```
# Cluster Mode
rundeck.clusterMode.enabled=true
# Active mode
rundeck.executionMode=active
# UUID of the server
rundeck.server.uuid=e1444362-306d-4123-997a-f6bff6df10fd
```

Node#2
```
# Cluster Mode
rundeck.clusterMode.enabled=true
# Active mode
rundeck.executionMode=active
# UUID of the server
rundeck.server.uuid=e2385641-4f63-44ff-80b9-18375092b6aa
```

**Expected/Actual Behavior**
Every scheduled jobs is executed from one node ONLY unless you go through the following use case.

**How to reproduce Behavior**
Use case description
1 - From node#2 (UI access), you schedule a job.
2 - While this job is running on node#2, run a TAKEOVER api call on node#1 to get all scheduled jobs to node#1.
3 - At this stage, the job runs on the 2 nodes concurrently.

**Comment by ahonor** [comment]
Is this still an issue? I can't reproduce in 2.10.0
