### ISSUE TITLE
Cascading Remote Options (option Provider )

### ISSUE THREAD

**Issue by gangadhar01a** [rundeck/rundeck#2516]
Issue type: Bug report/Enhancement Request

Rundeck mentioned the following statement in order to use Cascading Remote Options:

"Define your option provider to respond correctly based on the selected "repository" value, and define your Remote option URL to include a reference to the "repository" option value"

But the documentation not provided how exactly I need to define the option provider which exactly respond based on the selected "repository value"?

Thanks

**My Rundeck detail**

* Rundeck version: 2.7.3-1
* install type: (rpm,deb,war,launcher?)
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**

**Actual Behavior**

**How to reproduce Behavior**

**Comment by gangadhar01a** [comment]
How I can define a option provider so that the rundeck will load respective services based on the "Hostname" selection?
Hostname: prod-erpapp1 
Services: ERP.logistics.NL, ERP.supply.NL

Hostname: prod-erpfcapp1
Services: ERP.logistcsFC.NL, ERP.supplyFC.NL

Thanks.

**Comment by ahonor** [comment]
@gangadhar01a Did you resolve this?
