### ISSUE TITLE
Job schedule disabled after a fail

### ISSUE THREAD

**Issue by JacCap** [rundeck/rundeck#2521]
Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1-1
* install type: rpm
* OS Name/version: CentOS 7.2.1511
* DB Type/version: (the default for rpm install, which should be h2)

**Expected Behavior**
With a job being scheduled to run each day if it fails on day 1 it will still run on day 2

**Actual Behavior**
After a job failed it becomes disabled, the orange clock icon and the text "Never" are displayed, however when opening the drop-down menu both the "Disable schedule" and "Disable execution" checkboxes are not checked.
To re-enable the schedule you have to check and uncheck the "Disable execution" checkbox
![not_disabled](https://cloud.githubusercontent.com/assets/27197024/26239271/9fe9fb42-3c7c-11e7-90e4-0dc2b3304c50.png)

**How to reproduce Behavior**
Have a scheduled job fail

**Comment by ahonor** [comment]
Unable to reproduce in 2.10.0. Is this still a concern?

**Comment by zhjchen** [comment]
Have similar issue.
we run rundeck 2.10.2-1 in docker container. If the container failed, all scheduled jobs are not scheduled to run any more after the container comes back. 

the following job "sampling vip check" is supposed to run every 5 mins. And the job definition shows its schedule correctly.  However it is never got run again. The database table still shows the job are scheduled to run at a past time. 

![screen shot 2018-02-08 at 12 02 57 pm](https://user-images.githubusercontent.com/529966/35995541-8bcdfd58-0cc8-11e8-8717-342eb3291a69.png)


`MariaDB [rundeck]> select job_name, next_execution from scheduled_execution  where job_name="sampling vip check";
+--------------------+---------------------+
| job_name           | next_execution      |
+--------------------+---------------------+
| sampling vip check | 2018-02-05 05:30:00 |
+--------------------+---------------------+
1 row in set (0.00 sec)
`
