### ISSUE TITLE
Incomplete tokens API response

### ISSUE THREAD

**Issue by ameissnersofi** [rundeck/rundeck#2522]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2-1
* install type: launcher
* OS Name/version: Alpine Linux 3.4 (containerized)
* DB Type/version: PostgreSQL 9.5.2 on x86_64-pc-linux-gnu, compiled by gcc (Debian 4.9.2-10) 4.9.2, 64-bit

**Expected Behavior**
I'm expecting a complete response from rundeck (as exemplified in the documentation http://rundeck.org/docs/api/#list-tokens)

**Actual Behavior**
I get an incomplete response from rundeck.  If I GET from `http://myrundeckIP:4440/api/19/tokens`

For `application/json` the response is simply
```json
[
```

For `application/xml` the response is
```xml
<?xml version="1.0" encoding="UTF-8"?><tokens user="" allusers="true" count="23"><token user="admin" id="<redacted>" creator=""
```

**How to reproduce Behavior**
Run a GET against the v19 endpoint.  versions 18- work as expected.

**Comment by sjrd218** [comment]
This is fixed in recent versions of Rundeck.
