### ISSUE TITLE
Strange code editor behavior: delete option doesn't work

### ISSUE THREAD

**Issue by soar** [rundeck/rundeck#2523]
**Issue type:** Bug report

**My Rundeck detail**

* Rundeck version: `2.8.2-1 cafe cubano olive flag 2017-04-19`
* install type: `deb`
* OS Name/version: `Ubuntu 16.04`
* DB Type/version: plain files?
* Browser: `Firefox Developer Edition 54.0a2 (2017-05-05) (x64)`

**Problem:**

I've recorded video from my screen to explain what happening: https://youtu.be/F6hEvfF3Hi8

In two words: when you have option with type `file` and open code editor - every second letter doubles, when you typing.

**How to reproduce:**

* Create new job or edit existing
* Add option file type `file`
* Save this job and open it again
* Create new script or open existing
* Try to type something

**Comment by blackside** [comment]
I have this same problem in the Inline Script editor window.
Trying to write bash script (or write anything for that matter) results in doubling of letters...
Totally annoying and now I hav to write my scripts, even small oneliners, in a separate text editor...

**Comment by soar** [comment]
Also today I've tried to edit existing Job with file-type parameter. And when I open it, change and try to save - editor becomes clean.

**Comment by shaimona** [comment]
I'm having the same issue.

**Comment by gschueler** [comment]
the original issue is fixed via https://github.com/rundeck/rundeck/issues/2487

renaming to highlight the issue where deleting an option didn't work
