### ISSUE TITLE
Device42 sudo access to NODE

### ISSUE THREAD

**Issue by mmihir82** [rundeck/rundeck#2530]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 
* install type: (rpm,deb,war,launcher?)
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**How to reproduce Behavior**
How to add sudo access to the node was imported from the Device42? 
Can I create a global values in "..etc/resources.xml" so that I can use to run the commands? 
Such as username, sudo, ssh-key

**Comment by ahonor** [comment]
@mmihir82 can you show what the node definition looks like from Device42?

**Comment by mmihir82** [comment]
I saw able to extract the inventory thru Device42 via API

**Comment by ahonor** [comment]
@mmihir82 thanks
