### ISSUE TITLE
How can I execute a script or a command on a particular node ?

### ISSUE THREAD

**Issue by ksachdeva11** [rundeck/rundeck#2535]
Issue type: Information

**My Rundeck detail**

* Rundeck version:  2.8.0
* install type: launcher
* OS Name/version:  Linux
* DB Type/version: mysql? postgres? h2?..

**Background :** I have a script and I have configured a job for it. Presently it runs locally since I have setup the rundeck server on the box itself. 

If I want to run the script on a different node, how can I do it? How can I configure the node details ( IP etc. )? Will rundeck do ssh to the node I want to run my script on? 

Any details will be much appreciated.

Thanks!

**Comment by gschueler** [comment]
Please see the rundeck documentation, in particular here is a [tutorial](http://rundeck.org/docs/tutorials/index.html) and the guide to using the [ssh plugins](http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html)
