### ISSUE TITLE
Rundeck connection with MS sql server db

### ISSUE THREAD

**Issue by chinmaica** [rundeck/rundeck#2537]
Hello,

Can anyone please give me the detail steps to connect rundeck with MS sql server db?

Thanks in advance.

**Comment by niphlod** [comment]
this should be enough

http://rundeck.org/docs/administration/installation.html#mssql-as-a-backend

**Comment by idofabu** [comment]
> this should be enough
> 
> http://rundeck.org/docs/administration/installation.html#mssql-as-a-backend
> 
> if you have any issues ask with the details: I'm running an active-active rundeck cluster in a windows-only e

> this should be enough
> 
> http://rundeck.org/docs/administration/installation.html#mssql-as-a-backend
> 
> if you have any issues ask with the details: I'm running an active-active rundeck cluster in a windows-only environment.

The link is not working.

**Comment by niphlod** [comment]
Prolly moved around...old docs have the right pointer

https://docs.rundeck.com/2.7.2/administration/installation.html#mssql-as-a-backend


Il giorno ven 25 gen 2019, 13:46 idofabu <notifications@github.com> ha
scritto:
