### ISSUE TITLE
Rundeck v.2.8.2 RPM install does not work with CentOS7 (2.7.3 works however)

### ISSUE THREAD

**Issue by steven-tan** [rundeck/rundeck#2540]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: rpm
* OS Name/version: CentOS 7.2.1511
* DB Type/version: default install (local flat file i'm assuming)

**Expected Behavior**
systemctl start rundeckd works

**Actual Behavior**
systemctl start rundeckd throws errors in system log and fails  (see below)

**How to reproduce Behavior**
Follow normal instruction installations as provided by rundeck for rpm install, up to:
yum install rundeck
systemctl enable rundeckd
systemctl start rundeckd

/var/log/messages output is as follows:
May 30 15:11:00 rundeck301 systemd: Starting SYSV: rundeckd, providing rundeckd...
May 30 15:11:00 rundeck301 rundeckd: Starting rundeckd: [  OK  ]
May 30 15:11:00 rundeck301 systemd: Started SYSV: rundeckd, providing rundeckd.
May 30 15:11:00 rundeck301 systemd: Created slice user-1086.slice.
May 30 15:11:00 rundeck301 systemd: Starting user-1086.slice.
May 30 15:11:00 rundeck301 systemd: Started Session c8 of user rundeck.
May 30 15:11:00 rundeck301 systemd: Starting Session c8 of user rundeck.
May 30 15:11:00 rundeck301 systemd: rundeckd.service: main process exited, code=exited, status=1/FAILURE
May 30 15:11:00 rundeck301 systemd: Removed slice user-1086.slice.
May 30 15:11:00 rundeck301 systemd: Stopping user-1086.slice.
May 30 15:11:00 rundeck301 rundeckd: Stopping rundeckd: [FAILED]
May 30 15:11:00 rundeck301 systemd: Unit rundeckd.service entered failed state.
May 30 15:11:00 rundeck301 systemd: rundeckd.service failed.

After giving up on all the earlier troubleshooting attempts, I did a yum remove, and instead manually downloaded version 2.7.3 and installed using:
rpm -ivh rundeck-config-2.7.3-1.27.GA.noarch.rpm rundeck-2.7.3-1.27.GA.noarch.rpm

The service started fine with /var/log/messages output as follows:
May 30 15:32:22 rundeck301 systemd: Starting SYSV: rundeckd, providing rundeckd...
May 30 15:32:22 rundeck301 rundeckd: Starting rundeckd: [  OK  ]
May 30 15:32:22 rundeck301 systemd: Started SYSV: rundeckd, providing rundeckd.
May 30 15:32:22 rundeck301 systemd: Created slice user-1086.slice.
May 30 15:32:22 rundeck301 systemd: Starting user-1086.slice.
May 30 15:32:22 rundeck301 systemd: Started Session c10 of user rundeck.
May 30 15:32:22 rundeck301 systemd: Starting Session c10 of user rundeck.

**Comment by tomdeblende** [comment]
Did you upgrade to java 1.8.0?

**Comment by steven-tan** [comment]
Hmm, no I did not...  I'm guessing that is the issue then?

```
# rpm -qa |grep java
java-1.7.0-openjdk-1.7.0.111-2.6.7.2.el7_2.x86_64
javapackages-tools-3.4.1-11.el7.noarch
tzdata-java-2016h-1.el7.noarch
java-1.7.0-openjdk-headless-1.7.0.111-2.6.7.2.el7_2.x86_64
python-javapackages-3.4.1-11.el7.noarch
```

**Comment by ahonor** [comment]
@steven-tan yes java 1.8 is required
