### ISSUE TITLE
localexec-plugin and script-plugin replaces environment variables for local execution

### ISSUE THREAD

**Issue by eblikstad** [rundeck/rundeck#2541]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.6.11
* install type: launcher
* OS Name/version: Windows 2012 R2
* DB Type/version: SQL Server

**Expected Behavior**
Local execution should inherit system environment variables like PATH.
The system environment variables can be merged with the job option variables.

**Actual Behavior**
Environment variables are replaced by the job options variables.

**How to reproduce Behavior**
Create a job with a execute local command: "c:\windows\system32\cmd.exe /c set"
A full path to the cmd.exe is required because no PATH environment variable exist. The result also shows that other environment variables like windir is missing.

**Comment by puremourning** [comment]
I just found this too after upgrading to rundeck 2.7 from 2.6 (and thus needing `JAVA_HOME` to be set to a JDK8). It breaks things like using `rd` from within scripts executed from `localexec`, which unfortunately we have to do.

The workaround i had to go with is horrid:

```
#!/usr/bin/env bash
source ~/.bashrc
```

Anyone found success with any alternative approach? Any reason _not_ to populate the environment ? I can think maybe if it is a nodestep, you don't want the "local" node's environment affecting the execution of a _specific_ node's step, perhaps.

If this is a sensible thing to do, i think the change would be to just pre-initialise the environment map with `ScriptExecUtil.loadLocalEnvironment()` but that's just a guess.
