### ISSUE TITLE
dispatch to nodes - runs on local rundeck node and fails

### ISSUE THREAD

**Issue by juliangamble** [rundeck/rundeck#2542]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.6.9-1
* install type: (rpm,deb,war,launcher?): jar
* OS Name/version: centos
* DB Type/version: mysql? postgres? h2? h2

**Expected Behavior**
Select 'dispatch to nodes'. Enter a node search pattern - confirm that the node search returns the correct result. Run the job on the node. 

**Actual Behavior**
Both the local node and the remote node are shown in the execution list. The job runs locally and fails, and does not run on the dispatch node. 

**How to reproduce Behavior**
Create a new job with 'dispatch to node'.

**Comment by ahonor** [comment]
@juliangamble Can you post your job definition?

**Comment by ahonor** [comment]
Please reopen if this remains a concern
