### ISSUE TITLE
Enhancement: OPTION Repository

### ISSUE THREAD

**Issue by jaymence** [rundeck/rundeck#2543]
Hi,

Is there an enhancement already suggested to have reusable OPTIONS from existing JOBS to new or other JOBS or something like an OPTION repository. This saves the time of recreating the OPTION which basically almost have the same use to another job.

For example, I have BKPHOME Option which contains the path of the backup directory.  I need to declare this in almost every job that I'm making. If this can be just picked from an OPTION repository then this will be more convenient and will save more time in configuring/creating a job.

**Comment by ahonor** [comment]
@jaymence you might try out project globals for that. See http://rundeck.org/docs/administration/configuration-file-reference.html#project-global-execution-variables
