### ISSUE TITLE
Nodelist does not updated

### ISSUE THREAD

**Issue by shivshankardayal** [rundeck/rundeck#2548]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.8.2-1
* install type: (rpm,deb,war,launcher?) deb
* OS Name/version: Ubuntu 16.04
* DB Type/version: mysql? postgres? h2?.. MySQL

**Expected Behavior**
I fetch resourcexml from a URL. The URL gives 157 nodes but only 32 are shown. No matter what I do it never changes. It should update the list.

**Actual Behavior**
Does not update the list.

**How to reproduce Behavior**
Do not know.

**Comment by shivshankardayal** [comment]
I checked and it fetches data properly. The cache urlResourceModelSourceCache is good. But then when the data goes in resourceModelSourceCache it is only part of the resourcexml given from the url.

**Comment by gschueler** [comment]
rundeck uses the node "name" as the unique id.  Do you have multiple node definitions using the same name? in that case they might only show up in rundeck as a smaller list of nodes.

**Comment by shivshankardayal** [comment]
Thanks. My code changes had caused duplicate names in URL. Closing ticket.
