### ISSUE TITLE
Failed: NonZeroResultCode: Result code was 2147483647

### ISSUE THREAD

**Issue by qinzl1** [rundeck/rundeck#2550]
how i can find the error reason from result code
Result: 2147483647
00:06:11			Failed: NonZeroResultCode: Result code was 2147483647
00:06:11			Execution failed: 1131 in project load_database_to_hdfs: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [BJ-HOST-112: NonZeroResultCode: Result code was 2147483647]}, Node failures: {BJ-HOST-112=[NonZeroResultCode: Result code was 2147483647]}, status: failed]

**Comment by Hackeruncle** [comment]
+1

**Comment by ahonor** [comment]
@qinzl1 that number is generated by the executable. It is not rundeck specific. What executable are you running?
