### ISSUE TITLE
Unable to send webhook to requestbin

### ISSUE THREAD

**Issue by shadycuz** [rundeck/rundeck#2555]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: deb
* OS Name/version: Ubuntu 16.04
* DB Type/version: mysql? postgres? h2?.. Idk =/

**Expected Behavior**
WebHook is sent

**Actual Behavior**
Error in service.log

```
INFO  ExecutionService: updated scheduled Execution
INFO  ExecutionUtilService: Execution successful: 538 in project HealthCheck
WARN  HttpMethodBase: Cookie rejected: "$Version=0; __cfduid=d11525321b479793e03                                                      629162f2470f581496957407; $Path=/; $Domain=.requestb.in". Illegal domain attribu                                                      te ".requestb.in". Domain of origin: "requestb.in"
ERROR NotificationService: Notification failed [onsuccess,succeeded,538]; URL ht                                                      tps://requestb.in/13foeub1: Unable to POST notification after 1 tries: success f                                                      or execution 538 (succeeded): server response: 403 Forbidden
INFO  ExecutionService: updated scheduled Execution
```

**How to reproduce Behavior**

I created a url at https://requestb.in/ to see what the webhook was going to look like. I noticed after running the job no webhook was sent so I went looking into the logs and found the errors.

**Comment by gschueler** [comment]
I tried this.  it looks like the response is a 403 forbidden with this content:

> Error 1010 Ray ID: 36e6aad6cdb7283a • 2017-06-13 17:11:08 UTC
>
> Access denied
> 
> What happened?
> 
> The owner of this website (requestb.in) has banned your access based on your browser's signature (36e6aad6cdb7283a-ua19).
> 
> Cloudflare Ray ID: 36e6aad6cdb7283a

It appears to do the same thing If i use curl:

    curl -H 'user-agent:Jakarta Commons-HttpClient/3.0.1' -X POST https://requestb.in/...

So this seems like spam prevention  by CloudFlare on behalf of requestb.in for that User Agent string.  You might try contacting requestb.in to remove that restriction if it is inadvertent

**Comment by shadycuz** [comment]
The reason I opened is I can't get rundeck to send a webhook to anything.

**Comment by shadycuz** [comment]
nvm I went through my chat history and found one webhook that ran. Closing.
