### ISSUE TITLE
strange behavior on rundeck "NODE FIRST" strategy - nodes step show "NEXT UP"

### ISSUE THREAD

**Issue by rangsan** [rundeck/rundeck#2561]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: rundeck-config-2.8.2-1.31.GA.noarch
* install type: rpm
* OS Name/version: CentOS release 6.9 (Final)
* DB Type/version: h2

**Expected Behavior**
In NODE FIRST strategy, all nodes should run each steps individually. They won't wait for each others for all steps.

**Actual Behavior**
I imported the projects from other rundeck server version 2.6.0-1. When I run the job with multiple nodes at the same time. Sometimes one of the node just wait other node before run next step (Show "NEXT UP" status on UI). The setting of the job is "NODE FIRST" with number of thread count more than number of nodes.

**How to reproduce Behavior**
This behavior happen every time. All jobs are imported by project jar file.

**Comment by richiereynolds** [comment]
We have also seen this behaviour but even on new jobs and happening sporadically.
We have a job that syncronises all nodes periodically with a workflow step, then after that step we expect the number of threads to be kicked off simultaneously but sometimes the nodes run sequentially as if there's only a single thread.

**Comment by bardcir** [comment]
Same Behavior on Rundeck pro 3.0.7-20181008 on either of "Node First" or "Sequential" or "Rule sets", if one node still running current step, all other nodes which have already completed that step will be waiting for that node to complete before proceed to the next step.

**Comment by gschueler** [comment]
can you post example job definitions?

**Comment by bardcir** [comment]
The way I can replicate this is:
1- creating a job with 2 steps
step 1: Ansible playbook that sleep for a random minutes:
`---
- hosts: all
  gather_facts: False

  tasks:
  - set_fact:
     random: "{{ 10 | random }}"
    run_once: yes

  - pause:
      minutes: "{{random}}"
      prompt: "sleeping for {{random}} minutes"
      echo: yes` 

Step 2: command: hostname

Workflow: 
If a step fails: Run remaining steps before failing.
Strategy: Sequential ( or Node first  with more than number of hosts threads count )

execution waits for step 1 ( sleep randomly ) on all nodes, before proceeding to step2 even if the node completed its own sleep time.

TNX!!
