### ISSUE TITLE
Keys storage subfolder not working for acl policy

### ISSUE THREAD

**Issue by dpomnean** [rundeck/rundeck#2563]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.7.1-1
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: RHEL 6
* DB Type/version: mysql

**Expected Behavior**
Editing acl policy to separate keys storage database 'folder' structure. We have multiple projects and would like to have a /keys storage subfolder for each project. For example, /keys/myproject/ would be the subfolder, and all of its keys would be in that subfolder. Essentially not allowing other projects to use another projects' storage key.

**Actual Behavior**
I can get it to work to allow seeing all keys using 'keys/.*', but once I add the subfolder into the acl policy file, it breaks and tells me in the audit log, access rejected. Here is my acl file:

``` {.yml}
description: Users for Linux project
context:
  project: 'Linux' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: [linuxad]

---

description: access to project
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - match:
        name: 'Linux'
      allow: [read,import,export,configure,admin] # allow view/admin of all projects
  storage:
    - match:
        path: 'keys/linux/.*'
      allow: [read,create,update,delete]

by:
  group: [linuxad]

---

description: Other projects
context:
  project: '.*' # read access on all other projects
for:
  resource:
    - allow: 'read' # allow read/create all kinds
  adhoc:
    - allow: 'read' # allow read/running/killing adhoc jobs
  job:
    - allow: 'read' # allow read/write/delete/run/kill of all jobs
by:
  group: [linuxad]

---

description: read only access to other projects
context:
  application: 'rundeck'
for:
  project:
    - match:
        name: '.*'
      allow: 'read' # allow view/admin of all projects
by:
  group: [linuxad]
```

Audit Log:
`authorized: false: REJECTED, reason: REJECTED, evaluations: 	ACLRule</etc/rundeck/linux.aclpolicy[2][type:storage][rule: 1]>{'access to project' context={application='rundeck'} type='storage' match , resource={path=keys/linux/.*} for: { group='linuxad'} allow=[read, create, update, delete]} REJECTED for action read => REJECTED (0ms)`

**Comment by gschueler** [comment]
can you paste the whole audit log line before the `authorized: false` ?

**Comment by gschueler** [comment]
perhaps add another clause to the acl:

~~~ {.yaml}
  storage:
    - match:
        path: 'keys/linux/.*'
      allow: [read,create,update,delete]
    - equals:
        path: 'keys/linux'
      allow: [read,create,update,delete]
~~~

**Comment by dpomnean** [comment]
That seemed to have done the trick. I figured the equals clause was for exact paths to specific files according to the rundeck documentation examples, rather than directories. 
Thanks for the help!

**Comment by roman-io** [comment]
@gschueler these two rules definitely solved the rejected evaluation, but they open this project to access all keys in the storage. I don't understand how this is possible, probably a bug.
My Rundeck setup is `Rundeck 2.11.5-1`

**Comment by mschmeitz** [comment]
Did not work in my case. Using version 3.1.0-20190731 I needed to add another equals:

`
storage:
    - match:
        path: 'keys/linux/.*'
      allow: [read,create,update,delete]
    - equals:
        path: 'keys/linux'
      allow: [read,create,update,delete]
    - equals:
        name: 'keys'
        path: 'keys'
      allow: [read]
`
