### ISSUE TITLE
rundeck 2.8.2 upgrade - ERROR hbm2ddl.SchemaUpdate

### ISSUE THREAD

**Issue by itunesnosignup** [rundeck/rundeck#2566]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2.
* install type: rundeck-launcher-2.8.2.jar
* OS Name/version: RHEL 6.9
* DB Type/version: Oracle Database 12c Standard Edition Release 12.2.0.1.0

**Expected Behavior**
Successful install

**Actual Behavior**

[main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: create table job_file_record (id number(19,0) not null, version number(19,0) not null, date_created timestamp not null, execution_id number(19,0), expiration_date timestamp, file_name varchar2(1024 char), file_state varchar2(255 char) not null, job_id varchar2(255 char) not null, last_updated timestamp not null, project varchar2(255 char) not null, record_name varchar2(255 char), record_type varchar2(255 char) not null, server_nodeuuid long, sha varchar2(64 char) not null, "SIZE" number(19,0) not null, storage_meta long, storage_reference long not null, storage_type varchar2(255 char) not null, rduser varchar2(255 char) not null, uuid varchar2(255 char) not null, primary key (id))
2017-06-15 14:50:51,209 [main] ERROR hbm2ddl.SchemaUpdate  - ORA-01754: a table may contain only one column of type LONG

2017-06-15 14:50:51,214 [main] ERROR hbm2ddl.SchemaUpdate  - HHH000388: Unsuccessful: alter table rdoption add option_type long
2017-06-15 14:50:51,214 [main] ERROR hbm2ddl.SchemaUpdate  - ORA-01754: a table may contain only one column of type LONG

also:

Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "OPTIONS0_"."OPTION_TYPE": invalid identifier

**How to reproduce Behavior**
Upgrade from 2.7.1.1 to 2.8.2

**Comment by gschueler** [comment]
can you try this? https://github.com/jquick/rundeck_oracle_dialect

**Comment by itunesnosignup** [comment]
Thanks that's done the job.
One thing though I get a load of warning in my log:
2017-06-16 10:02:49,499 WARN  ScheduledExecutionService - Attempt to schedule job

My projects list was empty but it seems these are picked up from values in the database -
 SCHEDULED_EXECUTION for example. Is it recommended to clear the schema down upon upgrades? I don't care about retaining the history, and I restore my projects by restoring them to /rundeck/projects and using the RDCLI projects create and jobs load job.

If I deleted all the tables in the schema would it rebuild them all if I have dataSource.dbCreate = update?

**Comment by gschueler** [comment]
@itunesnosignup yes that is probably the cleanest way to do it

**Comment by itunesnosignup** [comment]
So if I have a completely blank schema the 'update' function will build everything, or should it follow the steps from http://support.rundeck.com/customer/en/portal/articles/2415681-oracle-setup ?

**Comment by gschueler** [comment]
@itunesnosignup if you use the rundeck_oracle_dialect i don't think you need to do manual table creation, so it should be sufficient to use the schema 'update' function

**Comment by itunesnosignup** [comment]
Thanks, I'll give it a go.
Marking this as closed as my original issue has been resolved.

**Comment by itunesnosignup** [comment]
FYI clearing the schema and leaving in on UPDATE rebuilt everything (with clobs) correctly.
