### ISSUE TITLE
API acl system level bug

### ISSUE THREAD

**Issue by ronave** [rundeck/rundeck#2569]
Issue type: Bug report

My Rundeck detail

    Rundeck version: 2.1.0
    install type: launcher
    OS Name/version: linux mint 18 sarah
    DB Type/version: mysql

**Expected Behavior**

ACL's created using the API should be shown on the rundeck GUI and should be possible to retrieve them using the API

**Actual Behavior**

When using the API to create system level acl's, these are not shown on the rundeck GUI under the "Access Control" screen and cannot be retrieved by the API either.

**How to reproduce Behavior**

Create a new acl at system level using the API.

**Comment by gschueler** [comment]
fixed in 2.10
