### ISSUE TITLE
Missing system environment variables on local execution

### ISSUE THREAD

**Issue by eblikstad** [rundeck/rundeck#2573]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.6.11
* install type: launcher
* OS Name/version: Windows 2012 R2
* DB Type/version: Microsoft SQL Server

**Expected Behavior**
A script interpreter should inherit the system environment variables.

**Actual Behavior**
All the system environment varibles including PATH is missing.

**How to reproduce Behavior**
Create a job with a inline script. In the script use the single command "set". The command set displays all environment variables from the command script interpreter cmd.exe. Assign the Rundeck server (local node) for executing the job.

**Comment by adragoset** [comment]
This is still an issue. I had to write a script to copy all env variables into framework properties before startup.

**Comment by eblikstad** [comment]
I have a patch for Rundeck 2.6.11 which is working. I'm upgrading this instance to 2.10.6 and can add a pull request for the patch for the latest version.

**Comment by eblikstad** [comment]
The runLocalCommand function in the ScriptExecUtil.java source file uses the legacy exec function in the class java.lang.Runtime. According to the Java 8 documentation, the new ProcessBuilder is preferred for starting processes with a modified environment. https://docs.oracle.com/javase/8/docs/api/java/lang/Runtime.html#exec-java.lang.String:A-java.lang.String:A-java.io.File-
