### ISSUE TITLE
Question - best way to sync 2 rundeck nodes.

### ISSUE THREAD

**Issue by shadycuz** [rundeck/rundeck#2574]
So I want to use Ansible to keep 2 Rundeck nodes in sync. I thought about using the RD cli tool but I ended up trying the API and it was really sweet. The issue I have is when I import a project archive into Rundeck the schedules for all the jobs are enabled. I can't have these jobs running on both the Master Rundeck and the Slave. Maybe I'm going about this the wrong way so I thought I would ask. Maybe I should create a feature request to add the option on Project export via API to enable/diable shedules for the jobs. 

Thanks,
Levi

**Comment by ahonor** [comment]
@shadycuz If you have two rundeck instances sharing the same database they need some extra configuration.

```
rundeck.clusterMode.enabled=true
rundeck.server.uuid=<uuidgen'd value>
```

Without setting that both instances will try to run the schedule
