### ISSUE TITLE
rundeck Scheduled job fail,have no more log

### ISSUE THREAD

**Issue by qinzl1** [rundeck/rundeck#2578]
the failed log:
java.lang.InterruptedException
03:15:35			Failed: Unknown: java.lang.InterruptedException
03:15:35	HOST-112		Execution failed: 1916 in project load_database_to_hdfs: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [HOST-116: Unknown: java.lang.InterruptedException]}, Node failures: {HOST-116=[Unknown: java.lang.InterruptedException]}, status: failed]

**Comment by ahonor** [comment]
@qinzl1 This is not enough info to understand the cause

**Comment by qinzl1** [comment]
@ahonor the question There are no more logs

**Comment by ahonor** [comment]
@qinzl1 Are there any messages in the service.log? Also, can you say more about your configuration?
