### ISSUE TITLE
Question: API Token

### ISSUE THREAD

**Issue by pchevallereau** [rundeck/rundeck#2579]
Issue type: Question

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: .deb
* OS Name/version: ubuntu 16
* DB Type/version: h2 and mysql in the  future

Hi,

My question is, it's possible to disable api token duration? like 2.7.3 rundeck version.
Today we just can change default duration but it's not clean, i use api rundeck for a script who delete executions logs. So i don't want to modify it all 30days.

Thanks, have a good day!

**Comment by gschueler** [comment]
Yes, set the `rundeck.api.tokens.duration.max=0` in the rundeck-config.properties

**Comment by pchevallereau** [comment]
Fine, but we need specify the "d" after 0.

Thank's for help.
Closed!
