### ISSUE TITLE
Editing multiple job reference steps not working

### ISSUE THREAD

**Issue by dpomnean** [rundeck/rundeck#2581]
Issue type: Bug report

**My Rundeck detail**
* Rundeck version: 2.7.1-1
* install type: rpm
* OS Name/version: RHEL 6.9
* DB Type/version: mysql

**Expected Behavior**
Edit multiple job references in a job at the same time.

**Actual Behavior**
I have a job that references many other jobs and when I click on one of the steps to edit the arguments, I cannot edit a different step at the same time. I have to either 'Discard' or 'Save' to close it and open the other step.

**How to reproduce Behavior**
Have a job that has steps to reference other jobs. Click on one of the steps to edit arguments. While that window is still open, click on another job reference step and it will not open. You have to close the first one in order to edit the other ones.

**Comment by dandunckelman** [comment]
Not necessarily a bug in my perspective.

This is more of a feature request.
- As a user editing a job with multiple steps, I'd like to be able to edit multiple steps at the same time.
