### ISSUE TITLE
The problem of activity

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#2584]
Can one-time empty activity inside the record Well?
Do you consider adding this feature?

**Comment by gschueler** [comment]
I don't understand your question

**Comment by qicaihuoyan** [comment]
I want to delete all the activities at once
Now only 20 can be deleted

**Comment by dandunckelman** [comment]
Currently, on `/project/PROJECT_NAME/activity`, one can perform a "bulk delete" and select multiple activities and delete them.

I think what @qicaihuoyan is asking for is a feature request to delete all activities of a project in one request.

@qicaihuoyan Currently, the API permits the following:
- bulk deletion of executions by passing a list of execution IDs:  http://rundeck.org/docs/api/index.html#bulk-delete-executions
- deleting all executions for a job:  http://rundeck.org/docs/api/index.html#delete-all-executions-for-a-job

If I were you, I'd write a script to do the following:
- get the list of job IDs for a project (http://rundeck.org/docs/api/index.html#listing-jobs)
- for each job, delete all executions for that job

**Comment by ahonor** [comment]
@qicaihuoyan If you need to bulk delete like that create a job that calls `rd executions deletebulk`. The GUI is not designed that kind of of bulk delete.
