### ISSUE TITLE
Error connecting to kettle repository using rundeck schedule

### ISSUE THREAD

**Issue by Anderson55555** [rundeck/rundeck#2594]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**
I'm using rundeck to schedule kettle jobs, but the schedule may not work during the early morning and give the error message: Error connecting to repository.

* Rundeck version: 2.6.9.1
* install type: rpm 
* OS Name/version: Redhat release 6.6 
* DB Type/version: oracle

**Expected Behavior**
Kettle job executed as expected

**Actual Behavior**
Execution failed because the job failed 

**How to reproduce Behavior**
The issue repeats each morning

**Comment by ahonor** [comment]
Did you try using an error handler to catch these errors?
