### ISSUE TITLE
Can't pass option type file to a jobref

### ISSUE THREAD

**Issue by reno-oner** [rundeck/rundeck#2598]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.8.2-1
* install type: rpm
* OS Name/version: CentOS7 
* DB Type/version: postgres

**Expected Behavior**
I have one job with a requested option type file. I call this job in an other one (master) via job reference.
I need to pass the file option selected in the master job to the job referenced. 

**Actual Behavior**
I can't pass the file option selected in the master job to the job referenced. tried ${option.fileopt} or ${file.fileopt}

**How to reproduce Behavior**
create a job with option type file. create one job with option type file to pass to job reference of the first job

**Comment by Miminoux** [comment]
👍 
Same here, as I can find, the behavior is worse : 
JobA (A project) has option named "csv" of type file option. It copies it to a node (copy file step) in /tmp then makes some checks on it and then moves it to a better location.
JobB (B project) has to call JobA but is launched by other users. I can't give them access to A project.

I thought I could add a file option named "csv" to JobB which would refer the csv file to JobA with -csv ${file.csv} and that JobA could understand that the file is already on the rundeck server. I also tried "-csv ${option.csv}" but it did not work.

Any workarround ?

**Comment by jplassnibatt** [comment]
This behavior is still in Rundeck 2.11.4-1

**My Rundeck detail**

Rundeck version: 2.11.4-1
install type: jar
OS Name/version: debian
DB Type/version: h2
