### ISSUE TITLE
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes

### ISSUE THREAD

**Issue by rogers140** [rundeck/rundeck#2601]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.6.11-1
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version: centOS 6
* DB Type/version: postgres

**Expected Behavior**
Execute scheduled jobs on certain boxes

**Actual Behavior**
Randomly fails when job is scheduled but alway succeeds with manual run.

**How to reproduce Behavior**
Not sure how, but it starts to happen since Wednesday. Before it works fine. I have turned off node cache by 
```
project.nodeCache.delay=30
project.nodeCache.enabled=false
```

**Comment by rogers140** [comment]
```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=my_boxname, dominant=false, }}
    at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.validateNodeSet(NodeFirstWorkflowStrategy.java:350)
    at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:88)
    at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:182)
    at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=maroon-poa-di-3.ops.palantir.local, dominant=false, }}
No matched nodes: NodeSet{includes={name=maroon-poa-di-3.ops.palantir.local, dominant=false, }}
```

**Comment by wesseljt** [comment]
I'm having the same issue

**Comment by rogers140** [comment]
@wesseljt I `resolved` my issue by rescheduling the jobs  and refreshing the assigned nodes to those jobs in the job editor that failed with this error. And now, it seems everything works fine. Maybe you can try that, too.

**Comment by wesseljt** [comment]
I haven't verified yet, but I think mine has to do with the inventory file for the project nodes. (I'm using the ansible plugin). I had all projects sharing a single inventory file. I since split the projects giving each its own inventory file and it seems like things are working better now. However, worth a shot to just reschedule the jobs if it happens again. Thanks!

**Comment by ahonor** [comment]
Please reopen if this occurs again

**Comment by sixcorners** [comment]
Why does this error occur? Why isn't there a better error message? I'm not changing my number of nodes. I'm not using any plugins. I just want this to run shell scripts..

**Comment by ahonor** [comment]
@sixcorners what do you use to manage node definitions?

**Comment by sixcorners** [comment]
I don't. I just run stuff in the same container that hosts rundeck itself.

**Comment by ahonor** [comment]
@sixcorners Ok, that helps. Do you get this error for every job run attempt?

**Comment by vinillum** [comment]
@ahonor We are also seeing this issue with the following debug output:
`

05:15:00 | localhost |   | [workflow] Begin execution: node-first
-- | -- | -- | --
05:15:00 |   |   | com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[localhost]}
05:15:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421)
05:15:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
05:15:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
05:15:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76)
05:15:00 |   |   | at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132)
05:15:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
05:15:00 |   |   | Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[localhost]}
05:15:00 |   |   | [workflow] Finish execution:  node-first: [Workflow result: , exception: com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[localhost]}, flow control: Continue, status: failed]
05:15:00 |   |   | No matched nodes: MultiNodeSelector{nodenames=[localhost]}
05:15:00 |   |   | com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[localhost]} 	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421) 	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90) 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226) 	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76) 	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132) 	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)

`
The job is scheduled to run every minute, the node itself is a localhost node - the same host as the Rundeck itself - and it succeeds most of the time. Last night, for example, we had it fail 2 times.

Job definition, if helpful:
`

- description: Periodically checks and executes tasks that have been scheduled.
  executionEnabled: true
  group: TASKMANAGER
  id: 466be0cc-36a6-4e28-9993-fa3eeb3925a7
  loglevel: DEBUG
  name: CheckAndExecuteTasks
  nodeFilterEditable: false
  notification:
    onfailure:
      email:
        attachLog: true
        recipients: ${job.user.email}
        subject: Task executor has failed/timed out
  schedule:
    month: '*'
    time:
      hour: '*'
      minute: 0/1
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - description: Executing scheduled tasks
      exec: tclsh $SCRIPTS_DIR_WORKFLOW/CheckAndExecuteTasks.tcl -p ${job.project} -t ${globals.PROJECT_TYPE}
    keepgoing: false
    strategy: node-first
  timeout: 2m
  uuid: 466be0cc-36a6-4e28-9993-fa3eeb3925a7

`

**Comment by antoinevdsk** [comment]
Hi
I have the same issue as rogers140. Sometimes jobs are failing with this error :

`com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=my-server-name, dominant=false, }}
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76)
	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=my-server-name, dominant=false, }}
No matched nodes: NodeSet{includes={name=my-server-name, dominant=false, }}` 

It never fails when I run the job manually.
It can happen on any job, any time, without logic. Of course the targeted server exists and is up and running.

**Comment by zjohcap** [comment]
I have the exact same problem.  Scheduled tasks arbitrarily fail with the below log.  I am running rundeck 2.10.0-1


```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[rundeck]}
  at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421)
  at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
  at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
  at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76)
  at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132)
  at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[rundeck]}
No matched nodes: MultiNodeSelector{nodenames=[rundeck]}
```

**Comment by NicholasKurian** [comment]
I'm also facing this issue, but I am just trying to run some commands locally. Could you please help me?

**Comment by antony360** [comment]
@ahonor any news, I got exactly the same problem, it occurs only on scheduled job, they were created by api. thx

**Comment by ahonor** [comment]
hi @antony360. Are you getting this problem on 3.0.x?

**Comment by antony360** [comment]
@ahonor yep 3.0.8
