### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by majkinetor** [rundeck/rundeck#2602]
FYI, I created a Windows chocolatey package for rundeck. It will be available as soon as you publish new release here as it is [automated](https://gist.github.com/majkinetor/a700c70b8847b29ebb1c918d47ee4eb1/fc72eedc79a55e081eb3adf4bfe8cae2ba6345f0#pushed)

The package page is: https://chocolatey.org/packages/rundeck
Its source code: https://github.com/majkinetor/au-packages/tree/master/rundeck

You can also return to any specific historic version with `--version` argument which is great for testing.

This make it possible to install it with single command, for example: `cinst rundeck --params /Service`
and later update it with `cinst upgrade rundeck`.

It implements windows installation from the docs, with few handy options. It also handle dependencies (nssm, jddk) so people don't have to think about it.

I am probably going to create `rundeck-cli` package in the future.

**Comment by ahonor** [comment]
@majkinetor Very cool!
