### ISSUE TITLE
Job editor autocomplete: incorrectly suggests ${job.user.email}

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2607]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 
* install type: (rpm,deb,war,launcher?)
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**

Autocomplete suggests correct variables.

**Actual Behavior**

Autocomplete suggests non-working variable `${job.user.email}`

See also #947 

**How to reproduce Behavior**

**Comment by orderedchaosdev** [comment]
I am also seeing this behavior and it has caused me problems since I had planned to use this var and can't.

**Comment by toninis** [comment]
Hello,

Any updates on this ? 
Will this feature be available ?

**Comment by jorn-k** [comment]
Hi folks. This issue has been resolved and merged in [4361](https://github.com/rundeck/rundeck/pull/4631). It will be released very soon.

Thank you, again, Rundeck community for continuing to make Rundeck better every day!
