### ISSUE TITLE
Add GUI toggle for not wrapping long lines in the log output

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2608]
Issue type: Enhancement Request

Add a checkbox to the execution log view GUI to allow toggling between wrapping/not-wrapping long output lines.

long lines were not wrapped previous to release 2.6.3, but after #1558 they were wrapped.

**Comment by jcdsilva** [comment]
Have similar request.
Say I have a job which takes 5 minutes to complete. Till it completes, GUI shows "Running" and no log output will be there. Even though my job prints lot of information, I am not sure whether it's running properly as in GUI it just shows "Running". 
Is there any way to get the output before the job gets completed.

**Comment by gschueler** [comment]
@jcdsilva there are a few reasons that might happen.  1. if you are running a python script, it buffers all output by default until it is complete. 2. if you are in cluster mode with a log storage plugin configured, but viewing the execution from a cluster member that is not the one executing the job, you will not see the output until the execution completes.  This is the current design of the way logs work in a cluster.

**Comment by jcdsilva** [comment]
@gschueler 
Thanks for that.
Im using python script but with -u option to provide unbufferred stdout.
Coming to point 2, we have framework.logs.dir defined which is an LVM. But rundeck.clusterMode.enabled is not set.

**Comment by gschueler** [comment]
@jcdsilva then i am not sure why that is happening.  the execution should write log output to a `.rdlog` file as it receives it. The GUI reflects the contents of that file.  you can try looking on the filesystem for that file while a job is running.
