### ISSUE TITLE
Unable to use the API resource refresh endpoint

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#2612]
Hello,

I can't figure out how to use the API refresh resource endpoint.

I have tried these curl requests:

```
curl -XPOST --header "X-Rundeck-Auth-Token:MYTOKEN" "http://MYHOSTNAME:4440/api/2/project/MYPROJECT/resources/refresh
curl -XPOST --header "X-Rundeck-Auth-Token:MYTOKEN" "http://MYHOSTNAME:4440/api/2/project/MYPROJECT/resources/refresh?providerURL:/conf/rundeck/shared_nodes.xml"
```

But it fails with this result:

```
<result error='true' apiversion='18'>
  <error code='api.project.updateResources.failed'>
    <message>Resources were not updated because no resource model provider URL is configured for project MYPROJECT</message>
  </error>
```

My project configuration file contains this:

```
project.resources.allowedURL.1=/conf/rundeck/shared_nodes.xml
resources.source.1.config.file=/conf/rundeck/shared_nodes.xml
resources.source.1.config.format=resourcexml
resources.source.1.config.generateFileAutomatically=false
resources.source.1.config.includeServerNode=true
resources.source.1.config.requireFileExists=true
resources.source.1.type=file
```

What am I doing wrong ?

Thank you for your help

Best regards
Jérôme

**Comment by jerome83136** [comment]
Hi guys,

Any news about this one ?

**Comment by gschueler** [comment]
Hi @jerome83136 the "refresh" endpoint is fairly old and deprecated, I think it should be removed as it does not really have a direct function anymore.  The original behavior was to reload resources from a `project.resources.url` URL endpoint.  However, Rundeck now supports multiple source configurations, including a URL source, and those sources are automatically refreshed by a cache layer.

The cache layer does have a delay, so I understand the need to "force" it to refresh. This is an enhancement that is on our roadmap.

**Comment by jerome83136** [comment]
Hi,
Ok I will wait for this feature to be added on a future release.
Thanks
Regards
Jérôme
