### ISSUE TITLE
Issues with Date Formatting

### ISSUE THREAD

**Issue by ekneidel** [rundeck/rundeck#2618]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: Rundeck 2.8.2-1
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version:  RHEL  2.6.32-358.2.1.el6.x86_64 #1
* DB Type/version: mysql? postgres? h2?.. default

**Expected Behavior**
date format DD should return 01 02 03....29 30 31
date format Do should return 1st 2nd ... 30th 31st
date format D should return 1 2 3 4 ... 29 30 31

**Actual Behavior**
date format DD returns 001 002 003.... 192 193 (julian date) or DDD format
date format D returns DDD format
date format Do returns an error

**How to reproduce Behavior**

use 

YYYY_MM_DD in the Date Format input type field

and
${DATE1:YYYY_MM_DD} in the Allowed Values field

![rd-dateresults](https://user-images.githubusercontent.com/30124683/28130576-3049f716-6705-11e7-8403-bdae7fd9703a.jpg)
![rd-dateinputvalues](https://user-images.githubusercontent.com/30124683/28130577-304d7b66-6705-11e7-8043-fbd87a3cebbd.jpg)

**Comment by ahonor** [comment]
The $DATE variable does not use unix style format but java simple format: https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html

**Comment by ekneidel** [comment]
Alex:

I’m jusing DDD format. It is not returning it .

**Comment by gschueler** [comment]
capital `DD` is the "day of year", if you want day of month use `dd` see  https://docs.oracle.com/javase/6/docs/api/java/text/SimpleDateFormat.html

> D | Day in year | Number | 189
> d | Day in month | Number | 10

**Comment by ekneidel** [comment]
Thank you.

That is in conflict with the momentumjs documentation which is what it is supposed to follow according to the rundeck documentation.

https://momentjs.com/docs/#/displaying/format/

DD is the day of the month
DDD is the day of the year

**Comment by gschueler** [comment]
which part of rundeck documentation says it uses momentjs format?  

the momentjs formatting is only used in displaying dates in the GUI in certain places.

**Comment by ekneidel** [comment]
Internally when you try to add a prompt.

And the on-line documentation      -     http://rundeck.org/docs/manual/jobs.html#input-types

Input Type
Choose between "Plain", "Date", "Secure" and "Secure Remote Authentication". For input types other than "Plain", the multi-valued option will be disabled.
Date Format
If "Date" Input Type is chosen, you can enter a date format to use when selecting the date
in the user interface. Using the momentjs format<https://momentjs.com/docs/#/displaying/format/>.
Default Value
A Default Value will automatically be set for the option if it is not otherwise specified by the user, even if not specified among the arguments when executing a job via the command-line or API. Note that a blank value can be specified via the command-line or API, which will override the use of the Default Value.
