### ISSUE TITLE
why alway throw error 

### ISSUE THREAD

**Issue by qinzl1** [rundeck/rundeck#2622]
Result: 2147483647
Failed: NonZeroResultCode: Result code was 2147483647
Execution failed: 4263 in project load_database_to_hdfs: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [IP: NonZeroResultCode: Result code was 2147483647]}, Node failures: {IP=[NonZeroResultCode: Result code was 2147483647]}, status: failed]

what's wrong.can some body help

**Comment by ahonor** [comment]
@qinzl1 does this job always fail or is it intermittent. It appears the step is failing due to a non-zero exit code from what ever the step runs. What kind of step is it and what is it running?

**Comment by ahonor** [comment]
Closing now but reopen if you have more info
