### ISSUE TITLE
java.awt.HeadlessException job rundeck

### ISSUE THREAD

**Issue by ext94053** [rundeck/rundeck#2623]
**My Rundeck detail**

* Rundeck version: 2.7.3
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version: red hat 2.6.18-371.1.2.el5
* DB Type/version: mysql? postgres? h2?..

I run a script that needs X11 display. Without rundeck, in local machine I run Xming program, and I execute the command in remote machine and it works fine

**Actual Behavior**

I have a job in rundeck where I connect to the remote machine with Nodes Option (Dispatch to Nodes)

I execute with a job rundeck and the job fails with the next error:

java.awt.HeadlessException: 
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
at sun.awt.HeadlessToolkit.getScreenSize(HeadlessToolkit.java:247)
at com.extensibility.rock.l.doGetWorkArea(Platform.java:197)
at com.extensibility.rock.l.a(Platform.java:193)
at com.extensibility.rock.u.<clinit>(Screen.java:52)

Can you help me?

Thanks a lot.

**Comment by ahonor** [comment]
@ext94053 I'm not sure this will be possible. Is the X tool you are running interactive? What is it?

**Comment by ext94053** [comment]
It is a progam in my local computer. Xming https://sourceforge.net/projects/xming/

**Comment by ahonor** [comment]
@ext94053 yes I understood that was the xwindows server you were using. Have you tried exporting the DISPLAY variable to the server on your desktop?

**Comment by ahonor** [comment]
Closing for now but reopen if you have more information
