### ISSUE TITLE
Advanced scheduling

### ISSUE THREAD

**Issue by eblikstad** [rundeck/rundeck#2624]
Hi

The scheduling of Rundeck jobs are limited. It's impossible to schedule a job to run every other week.

A better approach of scheduling would be.
-Start: Time & date
-Daily / weekly /montly
--Daily: Recur every X days
--Weekly: Recur every X days on specified weekdays
--Monthly: Recur on selected months, for specific dates or weekdays in selected week (or all)

An optional end time (time & date) would also be appropriate.

**Comment by ahonor** [comment]
TODO: May need to consider a different trigger: http://www.quartz-scheduler.org/documentation/quartz-2.x/cookbook/BiWeeklyTrigger.html

**Comment by eblikstad** [comment]
I have written a simple PowerShell script (Start-RDJob) which triggers a specific job. As a workaround I use the Windows Task Scheduler to trigger Rundeck jobs. The PowerShell script would also serve other external trigger types. https://stackstorm.com/ among other gave some ideas for different types of triggers.

For every Rundeck job that requires advanced scheduling, I create a Windows scheduled task which starts the the job.

I know about the Rundeck cli, but we are trying to stick to PowerShell for core functions.
