### ISSUE TITLE
Password Visible in ps output (Linux)

### ISSUE THREAD

**Issue by jcdsilva** [rundeck/rundeck#2627]
Issue type: Bug report/Enhancement Request
I have stored passwords as storage key.
But when my customized SSH plugin uses this password top do ssh, it's visible in ps -ef output.

**My Rundeck detail**

* Rundeck version: 2.8.1_1
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: Linux
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**
Passwords stored should be hidden and not visible in shell

**Actual Behavior**
Passwords stored are visible in ps -ef output

**How to reproduce Behavior**
Store passwords in storage key.
Trigger a job using node executor and monitor ps -ef in the rundeck host

**Comment by ahonor** [comment]
@jcdsilva Try the new Log filter plugin that masks passwords.
