### ISSUE TITLE
server UUID not being honored

### ISSUE THREAD

**Issue by ameissnersofi** [rundeck/rundeck#2628]
Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2-1
* install type: launcher
* OS Name/version: Alpine Linux 3.6
* DB Type/version: postgres 9.5.2

**Expected Behavior**
The UUID I supply should be the UUID the server uses

**Actual Behavior**
It's not.

```groovy
rundeck {
    server {
        uuid = "d4ca2ebb-8327-44e3-80b4-af9bc1d7c922"
    }
}
```

```bash
$ cat /opt/rundeck/server/config/rundeck-config.groovy | grep uuid
        uuid = "d4ca2ebb-8327-44e3-80b4-af9bc1d7c922"

$ curl -s -H "X-Rundeck-Auth-Token: $API_KEY" -H "Accept: application/json" http://localhost:4440/api/19/system/info | jq -r .system.rundeck.serverUUID
9ff56517-4a17-4429-862c-89ac22709e1f
```

The UUID I supply in the config file isn't being honored at all.  I've looked through the code and can't figure out why.  Can somebody help?

**Comment by ameissnersofi** [comment]
Furthermore, if i set an UUID in the config, sometimes rundeck doesn't even pick it up at all!

```bash
$ curl -s -H "X-Rundeck-Auth-Token: $API_KEY" -H "Accept: application/json" http://10.0.7.33:4440/api/19/system/info | jq -r .system.rundeck.serverUUID
null
```

**Comment by gschueler** [comment]
set it in the framework.properties file *not* the rundeck-config file

**Comment by ameissnersofi** [comment]
Awesome!  Thanks!
