### ISSUE TITLE
Schedule Takeover crashes rundeck

### ISSUE THREAD

**Issue by ameissnersofi** [rundeck/rundeck#2629]
Bug report

**My Rundeck detail**

* Rundeck version: 2.8.4-1
* install type: launcher
* OS Name/version: Alpine Linux 3.6
* DB Type/version: postgres / 9.5.2

Relevant NODE #1 Config:
```ini
rundeck.clusterMode.enabled=true
rundeck.server.uuid="a uuid"
```

Relevant NODE #2 Config:
```ini
rundeck.clusterMode.enabled=true
rundeck.server.uuid="another uuid"
```

**Initial Setup**
At first, I started to rundeck nodes with clusterMode disabled.  After enabling clusterMode and restarting rundeck, I noticed the UI listed my scheduled jobs as orphans.  I manually went into each job and re-saved it so the node would pick up the job.  I then issued a complete takeover (PUT payload - `{"server":{"all":true}}`) to node #2, and the jobs scheduled "migrated" accordingly.

I proceeded to test catastrophe recovery.  While keeping the underlying postgres DB up, I stoped the two rundecks and then started them again.  This generated new UUID's for each new rundeck node as expected.  I then issued a complete takeover to node #1.

**Expected Behavior**
I expected node #1 to completely takeover the scheduled definitions.

**Actual Behavior**
When calling the endpoint, the rundeck server crashed completely, failing to re-write the entries in the DB.

**How to reproduce Behavior**
Follow the steps above.  Start two standalone instances, create some scheduled jobs.  Enable clusterMode and restart the servers.  They should start complaining about orphaned scheduled jobs.  Manually re-save those definitions through the UI of node #1.  Via the API, issue a complete takeover to node #2.  Pending success, bring both servers down and start them back up (not one at a time - ensure both rundeck's are completely down before starting one back up), ensuring new UUID's were assigned to the brand new nodes.  Issue another complete takeover.  This is where rundeck crashes for me, and I never receive a response from rundeck wether it was successful or not.

**Comment by ameissnersofi** [comment]
Is there an update on this?  Sorry, I know you guys have a lot on your plate.

**Comment by gschueler** [comment]
I'm not sure what you mean by "This generated new UUID's for each new rundeck node as expected".  it is expected that each rundeck server maintains a static UUID, the uuid should not be regenerated...

is there any error message in the logs when it "crashes"?

**Comment by ameissnersofi** [comment]
Sorry - I'm running rundeck inside a Docker container.  As part of the startup script I wrote around standing rundeck up, I've included heredoc'ing the config files.  As part of that, use a uuid generator to make a new uuid, then write that into the conf file.  So when I say "new uuid's as expected" that's what I mean.  I totally understand the confusion, so my bad.

Which file should I tail (launcher install) to find these logs?  I haven't been seeing anything otherwise I would have included it.  :(

**Comment by gschueler** [comment]
if you are running with the launcher, you would tail the stdout of the launcher

**Comment by ameissnersofi** [comment]
After waiting several minutes, these lines finally showed up in the logs:

```bash
Exception in thread "DateCache" java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-08-07 21:24:31.363:WARN:oejut.QueuedThreadPool:qtp1128032093-67: 
java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-08-07 21:24:31.399:WARN:oejut.QueuedThreadPool:qtp1128032093-70: 
java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-08-07 21:24:31.667:WARN:oejs.ServletHandler:qtp1128032093-68: Error for /user/login
java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-08-07 21:24:31.052:WARN:oejs.ServletHandler:qtp1128032093-66: Error for /user/login
java.lang.OutOfMemoryError: GC overhead limit exceeded
2017-08-07 21:24:31.460:WARN:oejut.QueuedThreadPool:qtp1128032093-64: 
java.lang.OutOfMemoryError: GC overhead limit exceeded
```

My REST client (Advanced Rest Client from the chrome store) eventually gave up and timed out.

**Comment by ameissnersofi** [comment]
So, after beefing Xmx up to 2G and MaxMetaspaceSize to 512m, Rundeck never became unresponsive.  The call still timed out, and the heap space skyrocketed up to around 87% usage. (1.5gb / 1.73gb according to the page)

The logs printed these:

```bash
2017-08-07 22:01:55.796:INFO:/:qtp1128032093-42: Initializing Spring FrameworkServlet 'grails-errorhandler'
2017-08-07 22:07:19,401 - [] [] [/] [#] [] - Unauthenticated API request
2017-08-07 22:07:22,272 - [] [] [/] [#] [] - (unauthenticated) UNAUTHORIZED for api/apiSystemInfo
```

**Comment by ameissnersofi** [comment]
Sorry to bug again, @gschueler.  Were those logs helpful?

**Comment by gschueler** [comment]
nothing stands out to me in the logs.  I have not seen that behavior, but I will try to replicate the sequence you have indicated.

**Comment by ameissnersofi** [comment]
So, I have some more information, although I don't know if it will be of any help.  :(

After sending the API call again, I looked at the database to see if my problem might be in there.  Running an activity command, I got this output:

```postgres
datid            | 53209
datname          | rundeck
pid              | 6771
usesysid         | 16630
usename          | <redacted>
application_name | PostgreSQL JDBC Driver
client_addr      | <ip redacted>
client_hostname  | ¤
client_port      | 50184
backend_start    | 2017-09-11 21:19:01.501357+00
xact_start       | 2017-09-11 21:19:01.508321+00
query_start      | 2017-09-11 21:31:56.875076+00
state_change     | 2017-09-11 21:31:56.875101+00
waiting          | f
state            | idle in transaction
backend_xid      | ¤
backend_xmin     | 887254
query            | select logfilesto0_.id as id1_4_0_, logfilesto0_.version as version2_4_0_, logfilesto0_.completed as complete3_4_0_, logfilesto0_.date_created as date_cre4_4_0_, logfilesto0_.execution_id as executio5_4_0_, logfilesto0_.filetype as filetype6_4_0_, logfilesto0_.last_updated as last_upd7_4_0_, logfilesto0_.plugin_name as plugin_n8_4_0_ from log_file_storage_request logfilesto0_ where logfilesto0_.execution_id=$1
```
The state of `idle in transaction` peeks my attention.  I executed the PUT statement via curl ~15 minutes ago, and curl hasn't closed yet.  I keep getting this back when I check the activity on the DB.  Maybe this helps!  (fingerscrossed)

**Comment by ahonor** [comment]
@ameissnersofi did you say if rundeck was in a docker container?

**Comment by ameissnersofi** [comment]
@ahonor sorry - yes.  It's in a docker container, as well as the postgres db to which I'm connecting.

Here's my dockerfile:

```Dockerfile
FROM my-alpine-jdk8:v1_8_144

ENV RDECK_VERSION=2.9.3

ENV RDECK_JAR=rundeck-launcher-${RDECK_VERSION}.jar
ENV RDECK_BASE=/opt/rundeck

RUN apk update && apk --no-cache add ca-certificates bash python python-dev vim git jq gcc curl linux-headers musl-dev ruby postgresql-dev mysql-dev libpq py-pip
RUN pip install hypchat requests envdir psycopg2 MySQL-python boto awscli pytz stompest python-consul python-jwt PyYAML

ADD http://dl.bintray.com/rundeck/rundeck-maven/${RDECK_JAR} ${RDECK_BASE}/rundeck-launcher.jar
ADD http://search.maven.org/remotecontent?filepath=com/hbakkum/rundeck/plugins/rundeck-hipchat-plugin/1.6.0/rundeck-hipchat-plugin-1.6.0.jar ${RDECK_BASE}/rundeck-hipchat-plugin-1.6.0.jar

RUN git clone https://github.com/rundeck-plugins/rundeck-s3-log-plugin.git /tmp/s3logrundeck && cd /tmp/s3logrundeck && ./gradlew clean build --stacktrace && mv /tmp/s3logrundeck/build/libs/s3*.jar /tmp/s3logger.jar && rm -rf /tmp/s3logrundeck && cd /
ADD https://raw.githubusercontent.com/gschueler/rundeck-log4j-streaming-log-plugin/master/log4jStreamingLogWriterPlugin.groovy /tmp/log4jStreamingLogWriterPlugin.groovy

ADD https://storage.googleapis.com/golang/go1.9.linux-amd64.tar.gz /tmp/golang.tar.gz
RUN tar -C /usr/local -xzf /tmp/golang.tar.gz && mkdir -p ${RDECK_BASE}/golang && rm /tmp/golang.tar.gz
ENV GOPATH=${RDECK_BASE}/golang \
    PATH=$PATH:/usr/local/go/bin

ADD content /
ADD aclpolicies /tmp
ENTRYPOINT ["./docker-entrypoint.sh"]
CMD ["/start.sh"]
```

**Comment by ahonor** [comment]
@ameissnersofi can you check if the container is killing the java process? Eg, run:

     docker inspect $containerId -f '{{json .State}}'

Check the value of "OOMKilled".

**Comment by ameissnersofi** [comment]
Here's before calling the endpoint:

```json
{
  "Status": "running",
  "Running": true,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 9118,
  "ExitCode": 0,
  "Error": "",
  "StartedAt": "2017-09-12T22:11:23.801615471Z",
  "FinishedAt": "0001-01-01T00:00:00Z"
}
```
and during:
```json
{
  "Status": "running",
  "Running": true,
  "Paused": false,
  "Restarting": false,
  "OOMKilled": false,
  "Dead": false,
  "Pid": 9118,
  "ExitCode": 0,
  "Error": "",
  "StartedAt": "2017-09-12T22:11:23.801615471Z",
  "FinishedAt": "0001-01-01T00:00:00Z"
}
```

**Comment by andrewmeissner** [comment]
I was able to fix the problem.  It turned out the database was corrupted, somehow.  I exported all my job defs and project configs, dropped the db, recreated it, and reimported my projects and jobs.  I have been able to successfully issue the API call now with no hangs.  I'm still curious as to how the DB got corrupted in the first place.  :(
