### ISSUE TITLE
Using default user/pass combine with job.username

### ISSUE THREAD

**Issue by mmihir82** [rundeck/rundeck#2631]
Issue type: How to? 

**My Rundeck detail**
I have operator users who I like them to use default user/pass to execute jobs. 
I have admin users who I like them to use their own credential user/pass to execute jobs/commands.
How should I go by implementing. The folks who are admin, I have added under project.properties >> `project.ssh.user=${job.username}` and `project.ssh-password-storage-path=keys/${job.username}.password` that works using their own credential. 
Please help!! 

* Rundeck version: 2.8.2-1
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: centos 7
* DB Type/version: mysql? postgres? h2?: h2

**Expected Behavior**

**Actual Behavior**

**How to reproduce Behavior**

**Comment by ahonor** [comment]
@mmihir82 did you work through a solution?

**Comment by mmihir82** [comment]
yes, i was able to resolve. 
Issue I ran into, how to pass different username and under same project? for example:
I use default: root to login and it will use root.password, I have other devices that is using admin as username. How can I pass the different user?
Thank you
