### ISSUE TITLE
Run job failed via api

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#2633]
The current version is:2.8.3-1
I upgraded from 2.8.1, through the api running job error message:

<result error='true' apiversion='20'>
  <error code='api.error.item.unauthorized'>
    <message>Not authorized for action "Run" for Job ID 532e59ed-256c-4ce7-9ea5-9c17bf90ec4c</message>
  </error>

I run the curl command is:
curl -H 'x-rundeck-auth-token:0FZN9Zqf0N0Fe988QYWK1oJDj2NLpSj3' --data-urlencode "argString=-Module ceshi1"  --data-urlencode "argString=-maven_parameter ceshi2" --data-urlencode "argString=-code ceshi3" --data-urlencode "argString=-project_name ceshi4" --data-urlencode "filter=name: 172.16.123.251" http://10.99.2.200:4440/api/1/job/532e59ed-256c-4ce7-9ea5-9c17bf90ec4c/run

This is what happens? Is it that the prompt is not authorized? But my token is the latest generation

**Comment by gschueler** [comment]
you should combine the options `-key value -key2 value2` so that the curl arg is:

    --data-urlencode "argString=-key value -key2 value2 ..."

instead of doing multiple --data-urlencode

**Comment by ahonor** [comment]
Please reopen if you have any other questions about it.
