### ISSUE TITLE
Create a token failure problem

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#2634]
curl -H 'x-rundeck-auth-token:uVCYWwPeLpd4fZ6EIIKdDBCgMG8IVeF4' -H 'Content-Type: application/json' -d '{"roles":"admin"}' http://10.99.2.200:4440/api/11/tokens/admin

-d Behind the parameters do not take effect, is there a problem where the problem?

**Comment by gschueler** [comment]
use api v 19 `/api/19/...`
