### ISSUE TITLE
job reference outside project

### ISSUE THREAD

**Issue by mboogert** [rundeck/rundeck#2637]
Hi,

I think it would be great to create a job reference outside the current project. Some sort of global project where you can define jobs relevant for all projects.

We're using some global jobs which are relevant for multiple projects. At the moment we're defining the same job multiple times in different projects.

Maybe it's by-design for security reasons. Maybe it's possible to have some sort of global project where these kind of jobs could reside.

Regards,
Marcel.

**Comment by ahonor** [comment]
@mboogert this feature is in 2.9.0. You can try it here http://rundeck.org/news/2017/06/20/rundeck-2.9.0-beta1.html

**Comment by mboogert** [comment]
Sounds great. Gonna try the beta. Closing this issue. Thanx for your reply.
