### ISSUE TITLE
Saved filters not available in job editor

### ISSUE THREAD

**Issue by eblikstad** [rundeck/rundeck#2639]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.6.111
* install type: launcher
* OS Name/version: Windows 2012 R2
* DB Type/version: SQL Server

**Expected Behavior**
Saved filter in the Nodes tab should be available in the job editor.

**Actual Behavior**
The dropdown in the node field only displays "Saved filters" and no actual actual saved filters.

**How to reproduce Behavior**
Goto the Nodes tab in a project. Select a tag. Press and Actions and select save filter. Create a new job, scroll down, select dispatch to nodes and press the dropdown on the left side of the node filter.

**Comment by JustRiedy** [comment]
**My Rundeck detail**

- Rundeck version: 2.8.4
- Install type: RPM
- OS Name/version: CentOS 7
- DB Type/version: MSSQL Server

**Behaviour**
Mine loads Saved Filters form inside a New Job/Job Edit no problem.
![000541](https://user-images.githubusercontent.com/14937219/28862481-cd503bea-7797-11e7-8172-3b3ea8a4833d.png)

_First filter name hidden for privacy reasons._

I'd suggest tailing the Rundeck logs, probably Service.log and see if an error occurs when attempting to load that UI.

**Comment by gschueler** [comment]
cannot reproduce in latest release
