### ISSUE TITLE
Takeover of one or all jobs not working properly after upgrade.

### ISSUE THREAD

**Issue by philippevidal80** [rundeck/rundeck#2668]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.7.3-1
* install type: rpm via packages (not repo)
* OS Name/version: Amazon Linux AMI release 2017.03
* DB Type/version: RDS MySQL 5.6.34 (multi-AZ)
* Java version: java-1.7.0-openjdk-1.7.0.141.x86_64 to java-1.8.0-openjdk-1.8.0.141-1.b16.32.amzn1.x86_64

**Expected Behavior**

After upgraded a clutser with two nodes from 2.6.9 to 2.7.3 sequentialy, takeover of one or all jobs works properly.

**Actual Behavior**

Following the upgrade of our cluster, node1 doesn't want to release the jobs it currently schedules to node2. Here is the 3 differents behaviours found not working properly:

- API -> Full takeover

The full takeover hang with locking failure errors.
```...
INFO  ScheduledExecutionService: claimScheduledJob: schedule claimed for 130 on node efXXXX0-6XXe-XXe9-aXXX-29cdXXXXc3bb
INFO  ScheduledExecutionService: claimScheduledJob: schedule claimed for 150 on node efXXXX0-6XXe-XXe9-aXXX-29cdXXXXc3bb
ERROR ScheduledExecutionService: claimScheduledJob: failed for 207 on node efXXXX0-6XXe-XXe9-aXXX-29cdXXXXc3bb: locking failure
ERROR ScheduledExecutionService: claimScheduledJob: failed for 207 on node efXXXX0-6XXe-XXe9-aXXX-29cdXXXXc3bb: locking failure
ERROR ScheduledExecutionService: claimScheduledJob: failed for 207 on node efXXXX0-6XXe-XXe9-aXXX-29cdXXXXc3bb: locking failure
...
```
Takeover api call continue indefinitly to log the locking failure until I stop or restart Rundeck service.

- API -> Job ID takeover

```
root@rundeck_node_hostname:~$ curl -k -X PUT -H "X-RunDeck-Auth-Token: mYaPiToKeN" -H "Content-type: application/xml" -d "<takeoverSchedule><job id='80XXXX6b-6XXX-4XXX-bXX3-9c5bbXXXX9e1'/></takeoverSchedule>" https://localhost:8443/api/14/scheduler/takeover
<takeoverSchedule>
  <self>
    <server uuid='efXXXX0-6XXe-XXe9-aXXX-29cdXXXXc3bb' />
  </self>
  <server uuid='' />
  <job id='80XXXX6b-6XXX-4XXX-bXX3-9c5bbXXXX9e1' />
  <jobs total='0'>
    <successful count='0' />
    <failed count='0' />
  </jobs>
</takeoverSchedule>
```

Job with id 80XXXX6b-6XXX-4XXX-bXX3-9c5bbXXXX9e1 remains on initial node. There is no transfer of schedule.

- GUI -> Save scheduled job on node2 that was previously scheduled on node 1 results in lauching twice the job. 

The job is seen by both nodes to be on node2 but he is launched twice. One by each node.

**How to reproduce Behavior**

Install a cluster of two amazon linux node on AWS EC2 with rundeck with a MySQL AWS RDS database and S3 plugin for rundeck execution logs.

**Precision**

~~I never shutdown (The 2 nodes in same time) and restart the full cluster yet (not possible actually).~~
I finally could restart the all cluster (OS + Rundeck Service). A full takeover was possible but a single SAVE of a job from the non-scheduled node results in double execution of the job.

**Comment by philippevidal80** [comment]
**One more information:**
We found that Rundeck service, when it starts, indicates that cluster mode is enabled mentionning its UUID (service.log) but every commands around cluster stuff respond with an impossible execution of command because cluster mode is not activated. System info provided by API confirmes this fact. No UUID is indicate in the output.
The cluster seems to really enabled when we do a first login through the Web GUI ...

**Comment by andrewmeissner** [comment]
What's the status of this ticket?  I am seeing the same issue where clusterMode isn't enabled until after I login

**Comment by hernando-garcia** [comment]
Hello,
 
We are using the latest version of rundeck and also facing the same issue when a full takeover is triggered in the cluster. 

Any ETA for the resolution of this bug? 

systemctl restart rundeckd.service on the cluster nodes is the only way to fix it right now.

**Comment by zhjchen** [comment]
try to run the takeover api, it always throws unauthorized error, use the token generated by user in admin group. any idea why ?

`<error code='api.error.item.unauthorized'>
    <message>Not authorized for action "Reschedule Jobs (admin)" for Server 57be6d1b-296e-49b9-8314-c3cbea97cc96</message>
  </error>
`
