### ISSUE TITLE
Running an ad-hoc command with ansible plugin results in java.lang.NoSuchMethodError: com.dtolabs.rundeck.core.execution.ExecutionContext.getDataContext()Ljava/util/Map;

### ISSUE THREAD

**Issue by FritsHoogland** [rundeck/rundeck#2675]
Issue type: Bug report

Running a command in a project with ansible setup as handler and inventory synced leads to:

Failed dispatching to node 192.168.66.101: java.lang.NoSuchMethodError: com.dtolabs.rundeck.core.execution.ExecutionContext.getDataContext()Ljava/util/Map;
--
17:15:27 |   | Failed dispatching to node 192.168.66.102: java.lang.NoSuchMethodError: com.dtolabs.rundeck.core.execution.ExecutionContext.getDataContext()Ljava/util/Map;
17:15:28 |   | Execution failed: 69 in project test: [Workflow result: , step failures: {1=Dispatch failed on 2 nodes: [192.168.66.102: Unknown: java.lang.NoSuchMethodError: com.dtolabs.rundeck.core.execution.ExecutionContext.getDataContext()Ljava/util/Map;, 192.168.66.101: Unknown: java.lang.NoSuchMethodError: com.dtolabs.rundeck.core.execution.ExecutionContext.getDataContext()Ljava/util/Map;]}, Node failures: {192.168.66.102=[Unknown: java.lang.NoSuchMethodError: com.dtolabs.rundeck.core.execution.ExecutionContext.getDataContext()Ljava/util/Map;], 192.168.66.101=[Unknown: java.lang.NoSuchMethodError: com.dtolabs.rundeck.core.execution.ExecutionContext.getDataContext()Ljava/util/Map;]}, status: failed]

**My Rundeck detail**

* Rundeck version: rundeck-2.9.1-1.35.GA.noarch
* install type: RPM
* OS Name/version: CentOS Linux release 7.3.1611 (Core)
* DB Type/version: postgres
* installed with nginx as reverse proxy and SSL offloading
* extra plugin: ansible-plugin-2.0.2.jar (downloaded from ansible plugin repository)

**Expected Behavior**
Ad-hoc command to be run.

**Actual Behavior**
Getting the java.lang.NoSuchMethodError error.

**How to reproduce Behavior**
Plain install with postgres and nginx as special, ansible plugin downloaded from Batix repo and put in lib ext directory. Create project with ansible set as ad-hoc command executor, then execute ad-hoc command.

**Comment by FritsHoogland** [comment]
If anyone wants to replay this, I created an ansible playbook that installs this setup after the EPEL repo is added and git and ansible are installed from it: https://gitlab.com/FritsHoogland/install_rundeck.git (run 'ansible-playbook install_rundeck/install_rundeck.yml' after cloning the repo, there is no inventory needed when running locally)

**Comment by gschueler** [comment]
@FritsHoogland thanks, I believe this is a plugin compatibility issue with the new 2.9 release, we should have a fix fairly soon

**Comment by FritsHoogland** [comment]
Do you have an approximation when it'll be fixed (no pressure, just to get an idea)? I am writing a (blog) article about it, and am looking forward to finish it!
