### ISSUE TITLE
RPM works on rhel only

### ISSUE THREAD

**Issue by 375gnu** [rundeck/rundeck#2679]
Issue type: Enhancement Request

* Rundeck version:  any
* install type: rpm
* OS Name/version: opensuse, sles

**Expected Behavior**
The package is installable

**Actual Behavior**
The package is uninstallable

**How to reproduce Behavior**
rpm -i rundeck*.rpm

This is caused by dependencies which exist in rhel-like oses only. For suse-like it should depend on aaa_base.

**Comment by ahonor** [comment]
Rundeck currently does not support Suse
