### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by kurlzor** [rundeck/rundeck#2680]
Hi, I'm not sure where to ask this so I'm trying my luck here.

We use Rundeck at our company and since the most popular Docker image [jjethwa/rundeck](https://github.com/jjethwa/rundeck) is a bit bloated, I ended up creating a [smaller image](https://github.com/kurlzor/docker-rundeck) (several actually, I first made one with alpine and the jar but it had some odd bugs).
Rundeck seems popular enough to have an official Docker image (2000+ stars seems to be a good indicator), so I'm asking here first, as specified in [the checklist](https://github.com/docker-library/official-images/blob/master/NEW-IMAGE-CHECKLIST.md): are you planning on making one or do you mind if I try to make and publish one ?
I wouldn't mind maintaining it. 😄 

Thanks

**Comment by gschueler** [comment]
Thanks for asking @kurlzor we don't have immediate plans for creating our own "official" image.  Jordan's seems popular and there are many ways to configure and use Rundeck.  What makes Jordan's bloated? I don't know what is the best practice for an "official" image, should it be very basic or widely functional?

**Comment by dandunckelman** [comment]
The only point I see for that image being bloated is `FROM debian:stretch` instead of `alpine`.

It would be an interesting exercise to see the size comparisons, assuming one built from alpine was usable.

I currently use the image from https://github.com/jjethwa/rundeck for automating backup verification, so I'm all ears on a smaller image to speed up my job!

**Comment by martinbydefault** [comment]
@kurlzor what problems did you have using alpine and the jar package?
I'm creating one and up to now I haven't had any problems up to now (I based mine in this one: https://github.com/Batix/rundeck-ansible-plugin/blob/master/Dockerfile)
I would like to know your experience to have in mind the problems you had and see if they can be solved or not.  
Because I prefer to use an alpine image since it's smaller in size and because it's also one of the preferred images to use to "dockerize" services.

**Comment by SteveMattar** [comment]
what about the latest tag?

**Comment by ProTip** [comment]
I don't believe we will push to `:latest` at least until the image is done incubating, and then possibly for the latest GA release. The combination of the warning and the  `SNAPSHOT` tag is meant to discourage casual production use while the image is not stable.

Hope to have the configuration conventions solidified(we are trying to make it composable for our and others downstream image builds) very soon.

**Comment by stakemura** [comment]
Could you share how to set server.session.timeout on official docker image?
Would appreciate any feedback.

**Comment by kurlzor** [comment]
> What makes Jordan's bloated?

> The only point I see for that image being bloated is FROM debian:stretch instead of alpine.

https://github.com/jjethwa/rundeck/blob/eb11660c23f374c8c50a93e91342a7ee1473a1e8/Dockerfile#L21

Jordan's image also has MySQL and Postgres inside, plugins you might not need baked in, and supervisord. We were running Rundeck on Kubernetes so Jordan's image really wasn't suited for this.

> what problems did you have using alpine and the jar package?

Alpine gave me a lot of trouble with ssh and permissions when I tried, and doing the exact same thing in debian just worked. It's been a long time though, so I don't really remember the details.

One thing I had to do was to allow to dynamically remove the `<auth-constraint>` section in `/var/lib/rundeck/exp/webapp/WEB-INF/web.xml` because we used Google OAuth to log in. We don't use Rundeck anymore so I don't really have a reason to test the official image but it's good to see that you're creating it. 🙂

**Comment by ProTip** [comment]
@kurlzor Our docker images have been out for a few releases now and we are having a lot of success with them for internal Kubernetes deployments. If you have the time please feel free to try it out and provide feedback 😄 

https://hub.docker.com/r/rundeck/rundeck/

**Comment by Vishvin95** [comment]
I am facing an error:

The Node Source had an error while running rundeck/rundeck:

Parent dir for resource file does not exists, and could not be created: /var/lib/rundeck/projects/Test/etc/resources.xml

Could you please help ?

**Comment by rcastro33** [comment]
Hi @Vishvin95, I've found a workaround editing the resource file of the project in Project Settings > Edit Nodes > Sources. There you have a File source, edit the file path to use some folder under /home/rundeck/ directory (like /home/rundeck/projects/YOUR_PROJECT/resources.json), with the Generate checkbox selected. After that you can edit the properties of nodes

**Comment by viniciusczar** [comment]
If you are use Rundeck with Docker. you need folow steps:
1) Go to  Project Settings -> Edit Nodes
2) Click on "Configure Nodes" (Up, Right) and Click on "Add Source".
3) Then select "+ File"
4) In format (in the right), select "resourcexml", set the path (usually /home/rundeck/projects/test/resource.xml)
5) Set these checkboxes: "Generate", "Include Server Node" and "Writeable".
6) Click on "Save" (of File section)
7) Click on "Save" (of Edit Nodes section)
8) Will appear the config file to edit in "Edit", copy and edit new node select
