### ISSUE TITLE
Global log filters not working

### ISSUE THREAD

**Issue by niphlod** [rundeck/rundeck#2689]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.2
* install type: launcher
* OS Name/version: WS2012R2
* DB Type/version: mssql

**Expected Behavior**
Setting a log filter in each step produces a certain result. 
Assuming they are all equal, removing those and applying the same globally should produce the same result.

**Actual Behavior**
Globally applied log filters seem to not "kick in" (e.g. "Render formatted data").

**How to reproduce Behavior**
Create a job with two inline scripts, with e.g. markdown formatted data and apply to each the log filter "render formatted data". Then remove the log filter in each step and apply only one global.

**Comment by gschueler** [comment]
nb: i think this will be fixed in 2.9.4/2.10

**Comment by niphlod** [comment]
Thanks!

**Comment by gschueler** [comment]
was fixed in 2.9.4/2.10.0
