### ISSUE TITLE
Log filters: not working when referenced job is invoked

### ISSUE THREAD

**Issue by niphlod** [rundeck/rundeck#2691]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.2
* install type: launcher
* OS Name/version: WS2012R2
* DB Type/version: mssql

**Expected Behavior**
If a job is rigged in such a way to output formatted data, or colored data, etc via log filters, it should behave in the same way (or at least, unless specified otherwise in the job reference step).

**Actual Behavior**
A job with output filters doesn't honor them when called as a reference step.

**Comment by calvinboey** [comment]
+1 
Need an option to allow log filter to be honored when being referenced from another job

**Comment by raizdepi** [comment]
#2732
