### ISSUE TITLE
Separate jobs run in parallel

### ISSUE THREAD

**Issue by vinillum** [rundeck/rundeck#2695]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.2
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux 6.7
* DB Type/version: mysql

**Expected Behavior**

We have several jobs on Rundeck that are scheduled to execute in regular intervals. They all run on localhost. We would expect them to start and finish executions separately.

**Actual Behavior**

Rundeck jobs start at the same time, but execution does not start/finish separately.

Job 1 started at 12:00:00am
Started execution at 12:00:00am
Finished execution at 12:07:03am
Job 1 finished with success at 12:07:14am

Job 2 started at 12:00:00am
Started execution at 12:07:03am
Finished execution at 12:07:14am
Job 2 finished with success at 12:07:14am

Jobs 1 and 2 are different jobs that only have the node (localhost) in common. Yet, they seem to be grouped together somehow by Rundeck.

We have set our thread count to 100 and there were only 3 other jobs (with one node each) that have run at that time.

**How to reproduce Behavior**

Schedule several jobs to run at the same time, each with a relatively longer execution time (so you can spot the grouping).
This doesn't happen all the time, though, but it happens at least several times a day when jobs are scheduled to run regularly every 15 minutes.

**Comment by vinillum** [comment]
Not sure if it's relevant, but with debug mode enabled, I can see some log messages that are meant for one job appear on the other job. For example:

Job 1 had these, while Job 2 didn't:
15:50:00 |   |   | Begin: Workflow begin
15:50:00 |   |   | Begin: Workflow begin
15:50:00 |   |   | WillProcessStateChange: saw state changes: {workflow.state=started}
15:50:00 |   |   | WillProcessStateChange: saw state changes: {workflow.state=started}

**Comment by ahonor** [comment]
@vinillum is this still an issue?

**Comment by vinillum** [comment]
@ahonor We have temporarily resolved the issue by stacking every scheduled job 5 seconds apart, however the underlying issue might still be there.
I will upgrade to the latest Rundeck and report back if I still see the issue.

**Comment by ahonor** [comment]
@vinillum ok let us know if 2.10.0 changes the behavior.

**Comment by vinillum** [comment]
@ahonor I was unable to reproduce this issue on 2.10.1. Consider this issue closed - I will re-open if we notice it again.
