### ISSUE TITLE
Rundeck with AWS Cognito?

### ISSUE THREAD

**Issue by zbuckholz** [rundeck/rundeck#2696]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.7.2-1
* install type: (rpm)
* OS Name/version: Amazon AMI
* DB Type/version: mysql

I am considering integrating the Rundeck authentication with the AWS Cognito service, but I am not sure how to integrate jetty jaas with that. Has anyone done this and provided documentation?

Thanks
Zach

**Comment by ahonor** [comment]
No info about that.
