### ISSUE TITLE
Job context variable is not expanded correctly 

### ISSUE THREAD

**Issue by al3k** [rundeck/rundeck#2698]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.2
* install type: deb
* OS Name/version: Ubuntu 14.04.2 LTS
* DB Type/version:  h2.

**Expected Behavior**

Set option type as text and configured default value to be ${job.username} 
We relied on this behaviour in version 2.7.2 as default value for some options.

**Actual Behavior**

Option default value is not set to ${job.username} in job step
It looks like @job.username@ and $RD_JOB_USERNAME are passed correctly, but only ${job.username} is not

**How to reproduce Behavior**
Set option type as text and configured default value to be ${job.username} 
Option default value is not set to ${job.username} in job step

**Comment by Daryes** [comment]
My Rundeck detail
- Rundeck 2.8.3-1
- install type: deb (manual)
- OS Name/version: Ubuntu 16.04.3 LTS
- DB Type/version: internal

Just felt on this today, and after a while I found that not all executor plugins have this behavior.

Create a new job, using an option TEST, string type, using as default value : ${node.name}
having a step configured with : echo test value : ${option.TEST}
Node target set to "Dispatch to Nodes" or "Execute locally", it's the same result

With a node step "Command - Execute a remote command", the log will show "test value : ${node.name}"
With a node step "Local Command - Run a command locally on the server", the log will show "test value : rundeck" (or whatever name the server has)

Others plugins might be affected

**Comment by al3k** [comment]
@gschueler any update on this bug ?
