### ISSUE TITLE
In Running a Job API, option file is not work

### ISSUE THREAD

**Issue by butterflysjh** [rundeck/rundeck#2704]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.2
* install type: launcher
* OS Name/version: macOs 10.12.6
* DB Type/version: mysql

**Expected Behavior**
Running a Job from API，it`s contains file option,file is uploaded and have a ID,but it is not work when excute the API,there is don`t have the option file

**Actual Behavior**

**How to reproduce Behavior**

**Comment by gschueler** [comment]
Can you explain more about how you perform the API call and how it is not working?

Have you tried the `rd` tool which supports file upload? does that work?

**Comment by ahonor** [comment]
Reopen if you have more information
