### ISSUE TITLE
Impossible to use captured key with spaces in name (Key Value Data)

### ISSUE THREAD

**Issue by hoodoomeister** [rundeck/rundeck#2729]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.9.3
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version: mac
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**
Should be possible to use captured any key with spaces in name.

**Actual Behavior**
Key with spaces is captured and printed when 'Log Data' is checked, but there is no possibility to use that key in another step.

**How to reproduce Behavior**
1. Create job with printed in log some space separated strings.
2. Add Log Filters -> Key Value Data with regex to capture key composed of at least two strings space separated.
3. Check 'Log Data' flag in Key Value Data.
4. Add another job and try to print value for key from 2nd step.
5. Run job
Actual:
Key value is displayed for 'Log Data' but it is impossible to reference it as `@data.key@` with ", ',` around key name or without any apostrophe.

**Comment by dimatha** [comment]
+1

**Comment by dimatha** [comment]
Of course, this is also valid for 2.10.1 as well. mb a checkbox to filter out forbidden chars from the captured key names ?

**Comment by vikashkmr3188** [comment]
Please let me know if there is any update on this issue.
