### ISSUE TITLE
Client Certificate Authentication

### ISSUE THREAD

**Issue by f-r-o-g** [rundeck/rundeck#2731]
Has anyone attemted to setup rundeck with Client Certificate Authentication?
A simple -Drundeck.jetty.connector.ssl.setNeedClientAuth=true in the RDECK_JVM of the profile file doesn't seem to work. I am not getting errors in the logs at all.

**Comment by dseapy** [comment]
+1

One potential workaround is use httpd reverse proxy (configured to authenticate client certs), iptables, and preauthenticated-mode.  But installing httpd just for this seems not great.

Alternatively I wonder if I could simply put a custom CertificateLoginModule onto the classpath when running and make a jaas-certificate.conf that references that class?  Would think it would be really easy to make a jar with such a LoginModule.  Maybe i'll give that a try.

**Comment by sjrd218** [comment]
Added in PR #4917.
