### ISSUE TITLE
Rundeck shared data context unavailable for RemoteScriptNodeStep

### ISSUE THREAD

**Issue by niphlod** [rundeck/rundeck#2734]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.2 
* install type: launcher
* OS Name/version: WS2012R2
* DB Type/version: MSSQL

**Expected Behavior**
Using data context throughout all the steps, considering the "data context" as "global" through the job

**Actual Behavior**
It seems that inline scripts can reference it with `@data.foo@`, node steps like "copy file" can use it as `${data.foo}`, but not RemoteScriptNodeStep

**How to reproduce Behavior**
exhibit a) Set data in first step, add "Log Data" stub as second step (dunno if it's useful, but it doesn't log the data just set in the first one), use the data in a  RemoteScriptNodeStep option (plain String, set as `${data.foo}` ) --> no joy, empy value
exhibit b) Set data in first step, use the data in a Copy File step, set dest as `${data.foo}` ) --> works perfectly.

Is this the intended behaviour ?

**Comment by gschueler** [comment]
sounds like a bug
