### ISSUE TITLE
Jobs with multiple steps sometimes eliminate or reorder steps upon saving

### ISSUE THREAD

**Issue by sinksc** [rundeck/rundeck#2737]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.3-1
* install type: rpm
* OS Name/version: Redhat Linux 7

**Expected Behavior**
When using the GUI to create a job with multiple steps, after saving the job the steps should be saved as they were created, in the correct order.

**Actual Behavior**
When using the GUI to create a job with multiple steps, sometimes after saving the job some of the steps disappear or appear in the wrong order. To fix it the job has to be re-edited and the missing steps added back in and/or put back in the correct order. Sometimes this has to happen multiple times until the change "sticks". So far I have not noticed this happening when importing jobs via the `rd` command line utility.

**How to reproduce Behavior**
1. Create a new job
2. Add multiple steps to the job (_I have tested with Command steps and Workflow steps_)
3. Save the job
4. Review the job definition and note that sometimes some of the steps are missing or in the wrong order.

**Comment by dandunckelman** [comment]
I've even seen job options disappear.

**Comment by gschueler** [comment]
job workflows and options that are being editted are stored in the user "session", which is not unique among browser tabs....so this might possibly occur if you had the same job being edited in multiple tabs..?  A fix would be to change that behavior to a use a unique key from the page, or use browser-side local storage instead of server-side, if that is indeed the problem.

any way to reproduce it reliably?

**Comment by sinksc** [comment]
Hi Greg,
[multi-step_job_troubleshooting.zip](https://github.com/rundeck/rundeck/files/1382687/multi-step_job_troubleshooting.zip)

Yes, I can reproduce it consistently. I'll attach a recording I took with the Windows 'psr' tool. If you're running windows you can open the file and see the screen shots and comments. Click on them to zoom in. If it's difficult to read I'd be happy to send you more info or do a quick screen-share session with you.

**Comment by gschueler** [comment]
@sinksc i'm on a mac, the file doesn't seem to be usable... can it be converted into some video format?

**Comment by sinksc** [comment]
@gschueler According to [this doc](https://www.techwalla.com/articles/how-to-open-mht-documents-on-a-mac), on a Mac you can open it with Word, Opera, or Chrome. 

I tried converting it into a PDF and the screen shots were too blurry. Let me know if you don't have success with Word/Chrome/Opera and I can figure out something else. Or if you want to do a quick 5-minute join.me session I can show you the issue.

Here's the blurry PDF file:
[Problem_20171013_0814.pdf](https://github.com/rundeck/rundeck/files/1383599/Problem_20171013_0814.pdf)

**Comment by Miminoux** [comment]
I've had the same behavior on version 2.10.1-1, but I can't find what exactly triggers it, it happens "ramdomly" for me. What I could determine : 
- it happens only on job update, not on creation
- it doesn't happen when modifiying only 1 thing (1 option or 1 step...)

To make sure not to lose any option or step, when I create a job, I add all options before adding the first step. If after creating the first step I realize another option is needed, I create the job (missing many things) without the option I just thought about, edit the job, add the option, save the job, edit the job and then add other steps...

Quite annoying but safe.
