### ISSUE TITLE
PropertyFileLoginModule - Web interface password updates are broken

### ISSUE THREAD

**Issue by erioshi** [rundeck/rundeck#2739]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.3-1
* install type: (rpm,deb,war,launcher?) deb
             From -> https://rundeck.bintray.com/rundeck-deb  rundeck 2.9.3 (on 9/6/2017)
* OS Name/version: Ubuntu 16.04 LTS on a VM
* DB Type/version: mysql? postgres? h2?.. default database config

**Tested on a complete fresh install of OS and all packages just to confirm this bug.**

**Expected Behavior**
Using: PropertyFileLoginModule
Ability to add new web interface users or reset the password for the admin user using the commands shown below from the following document:
http://rundeck.org/2.9.3/administration/authenticating-users.html

Command:
java -cp jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass

Expected Ouput similar to:
OBF:1xfd1zt11uha1ugg1zsp1xfp
MD5:a029d0df84eb5549c641e04a9ef389e5
CRYPT:jsnDAc2Xk4W4o

**Actual Behavior**
Using: PropertyFileLoginModule
Attempting to add a new user or change the default web interface admin password using this commands listed generates an error.

Command:
java -cp jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass

Actual Ouput:
Error: Could not find or load main class org.eclipse.jetty.util.security.Password

**How to reproduce Behavior**
Run Command:
java -cp jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass

**Comment by gschueler** [comment]
Specify the correct path to the jetty-all jar file, as mentioned in the documentation.  For Deb install that would be:

    java -cp /var/lib/rundeck/bootstrap/jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass

**Comment by erioshi** [comment]
Using the full path does not prevent the error:

Using username "smb-adm-local".
Authenticating with public key "imported-openssh-key"
Passphrase for key "imported-openssh-key":
Welcome to Ubuntu 16.04.3 LTS (GNU/Linux 4.4.0-93-generic x86_64)

 * Documentation:  https://help.ubuntu.com
 * Management:     https://landscape.canonical.com
 * Support:        https://ubuntu.com/advantage

0 packages can be updated.
0 updates are security updates.


Last login: Wed Sep  6 21:40:03 2017 from 10.254.254.45
smb-adm-local@script-monkey:~$
smb-adm-local@script-monkey:~$ java -cp jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass
Error: Could not find or load main class org.eclipse.jetty.util.security.Password
smb-adm-local@script-monkey:~$
smb-adm-local@script-monkey:~$ java -cp /var/lib/rundeck/bootstrap/jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass
Error: Could not find or load main class org.eclipse.jetty.util.security.Password
smb-adm-local@script-monkey:~$

**Comment by erioshi** [comment]
I have opened a new issue and included the information from my post above in it.  It can be found at the following link: [https://github.com/rundeck/rundeck/issues/2742](url)
