### ISSUE TITLE
PropertyFileLoginModule - Web interface password updates are broken - missing .jar file

### ISSUE THREAD

**Issue by erioshi** [rundeck/rundeck#2742]
Issue type: Bug report

My Rundeck detail

Rundeck version: 2.9.3-1
install type: (rpm,deb,war,launcher?) deb
From -> https://rundeck.bintray.com/rundeck-deb rundeck 2.9.3 (on 9/6/2017)
OS Name/version: Ubuntu 16.04 LTS on a VM
DB Type/version: mysql? postgres? h2?.. default database config
Tested on a complete fresh install of OS and all packages just to confirm this bug.

Expected Behavior
Using: PropertyFileLoginModule
Ability to add new web interface users or reset the password for the admin user using the commands shown below from the following document:
http://rundeck.org/2.9.3/administration/authenticating-users.html

Command:
java -cp /var/lib/rundeck/bootstrap/jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass

Expected Ouput similar to:
OBF:1xfd1zt11uha1ugg1zsp1xfp
MD5:a029d0df84eb5549c641e04a9ef389e5
CRYPT:jsnDAc2Xk4W4o

Actual Behavior
Using: PropertyFileLoginModule
Attempting to add a new user or change the default web interface admin password using this commands listed generates an error.

Command:
java -cp /var/lib/rundeck/bootstrap/jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass

Actual Ouput:
Error: Could not find or load main class org.eclipse.jetty.util.security.Password

How to reproduce Behavior
Run Command:
java -cp /var/lib/rundeck/bootstrap/jetty-all-7.6.0.v20120127.jar org.eclipse.jetty.util.security.Password jsmith mypass

** Additional Information **

There is no .jar file named jetty-all-7.6.0.v20120127.jar in the directory /var/lib/rundeck/bootstrap/

There is a .jar file named jetty-all-9.0.7.v20131107.jar, but that also fails when run in following command:

java -cp /var/lib/rundeck/bootstrap/jetty-all-9.0.7.v20131107.jar org.eclipse.jetty.util.security.Password jsmith mypass

Error: Could not find or load main class org.eclipse.jetty.util.security.Password

**Comment by gschueler** [comment]
Sorry, the correct jetty-all version is 9.0.7.v20131107 as you discovered.

The correct path to the jar file in the deb install is: `/var/lib/rundeck/bootstrap/jetty-all-9.0.7.v20131107.jar`

    export JARFILEPATH=/var/lib/rundeck/bootstrap/jetty-all-9.0.7.v20131107.jar

The correct command to invoke is:

    java -cp $JARFILEPATH org.eclipse.jetty.util.security.Password jsmith mypass

This should give you the encoded passwords that you expect. 

If you see `Could not find or load main class org.eclipse.jetty.util.security.Password`, then there are a few possibilities:

1. the JARFILEPATH is wrong
2. the jar file is corrupted.  You can verify the contents of the file doing this:

    jar tvf /var/lib/rundeck/bootstrap/jetty-all-9.0.7.v20131107.jar | grep Password.class

You should see something like:

    5091 Thu Nov 07 10:05:34 UTC 2013 org/eclipse/jetty/util/security/Password.class

HTH

**Comment by gschueler** [comment]
fyi: i submitted a change to correct the listed jar version https://github.com/rundeck/rundeck/pull/2749

**Comment by erioshi** [comment]
Thank you!  That resolves the problem for me.
