### ISSUE TITLE
rundeck.log.2017-08-21:2017-08-21 12:12:21,947 [pool-1-thread-1] ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - Database is already closed (to disable automatic closing at VM shutdown, add ";DB_CLOSE_ON_EXIT=FALSE" to the db URL) [90121-193]

### ISSUE THREAD

**Issue by sourcebits-sharath** [rundeck/rundeck#2755]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 
* install type: (rpm,deb,war,launcher?)
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**

**Actual Behavior**

**How to reproduce Behavior**

**Comment by ahonor** [comment]
@sourcebits-sharath how do you reproduce this bug?

**Comment by sourcebits-sharath** [comment]
Run Rundeck for 2 days with following configuration.
 Rundeck detail   
~~~~~~~~~~~~
Rundeck version:2.8.4
install type: rpm
OS Name/version:Linux 
DB Type/version: h2
~~~~~~~~~~~~
-----------------------------------------
run following Jobs:
http://{ipaddress}/job1 
interval 0 0/10 * * * ? *

http://{ipaddress}/job2
interval 0 0/15 * * * ? *

http://{ipaddress}/job3
interval 0 0/30 * * * ? *
