### ISSUE TITLE
Expand Upgrade Guide to Include "Regular" Upgrades

### ISSUE THREAD

**Issue by dirkniblick** [rundeck/rundeck#2764]
Issue type: Enhancement Request

It would be helpful for the [Upgrade Guide](http://rundeck.org/docs/upgrading/index.html) to be expanded with how to apply "regular" upgrades, those not needing any special handling.  For example, the [Installation page](http://rundeck.org/docs/administration/installation.html) has a section on [Updating rundeck using the launcher](http://rundeck.org/docs/administration/installation.html#updating-rundeck-using-the-launcher).  It'd be helpful to see something similar for [Installing from Source](http://rundeck.org/docs/administration/installation.html#installing-from-source) and [Installing with RPM](http://rundeck.org/docs/administration/installation.html#installing-with-rpm).  I mean I wrote up my own set of steps for my RPM setup, but it'd be comforting to know how the developers of the application would handle an upgrade _properly_.

**Comment by martinbydefault** [comment]
I'm having the same problem.  
My version of rundeck is 2.8.1-1, installed with the launcher, and I would like to know what is the procedure to update to 2.8.3 and if I need to take some intermediate steps.
