### ISSUE TITLE
Run only specific steps within a Job

### ISSUE THREAD

**Issue by lucascrezende** [rundeck/rundeck#2773]
Hi all. 

Not sure if this is the right place for this kind of question, but I am trying to find a way to run only specific steps within a job without having to duplicate it and then remove all the steps but the one I want to specifically run.

For example, I have a job with two steps: step 01) load data into a database, step 02) update Zookeeper. Imagine the second step failed by some reason and I need to run it manually to update Zookeeper properly. Currently I will have to duplicate this job, delete step 01, save and then run the duplicated job. 

All right, this was a very simple example, but there are - many - cases with jobs with much more than 2 steps.

Any way to make it happen easier?

Thanks in advance!

**Comment by fdevans** [comment]
Based on feature availability in Rundeck Enterprise (Ruleset Strategy) we are going to close this request.  If you would like to try Rundeck Enterprise to see if that version can address your request please feel free to say Hello at hello@rundeck.com.
Thank you, 
The Rundeck Team
