### ISSUE TITLE
Failed: SSHProtocolFailure: Session.connect: java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by javaenthugm** [rundeck/rundeck#2774]
Issue type: Bug report

Some of Node steps gives 'Connection Reset' error intermittently.  
i.e when the rundeck server tries to copy a scrip (.sh) to another node.

```
Session.connect: java.net.SocketException: Connection reset
Failed dispatching to node hdp-n1: [jsch-scp] Failed copying the file: Session.connect: java.net.SocketException: Connection reset
```
@gschueler 

Can you please comment? 

**My Rundeck detail**

* Rundeck version:  Rundeck 2.7.3-1 
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version:  linux
* DB Type/version: mysql? postgres? h2?..

**Comment by ahonor** [comment]
@javaenthugm Are they always the same nodes? Is there a delay in connecting?

**Comment by yogeshkumark** [comment]
+1
Repeated in rundeck version  mozzarella stick peru piggy-bank 2019-08-01
Rundeck 3.1.0-20190731
Linux - ubuntu

**Comment by MikeVelazcoMtz** [comment]
+1
Repeated in rundeck version jalapeño popper plum pushpin 2019-05-12
Rundeck 3.0.22-20190512

**Comment by MikeVelazcoMtz** [comment]
@yogeshkumark @javaenthugm   Did you find any way to solve this?

@ahonor 
In my case it happens always on the same job, but in different threads. And it reaches always the same server.

**Comment by pandrian** [comment]
This happening in 3.3.2-20200817 as well

**Comment by rbaduel** [comment]
is this fixed already in the newer version?

**Comment by yogeshkumark** [comment]
I have validated the issue from my side to fix it. 
1) Verify the system network bandwidth usage , if it is less increase to double 
2) Network quality and number of bytes been loss 
3) Increase the thread count if it is not sufficient. 

No other solution are working

**Comment by yogeshkumark** [comment]
@javaenthugm 
Please close the issue.

**Comment by fgutierrezz** [comment]
Hello

Could you tell us what was the issue and what problem did you find.

Thanks

**Comment by CookieMonster42** [comment]
> I have validated the issue from my side to fix it.
> 
> 1. Verify the system network bandwidth usage , if it is less increase to double
> 2. Network quality and number of bytes been loss
> 3. Increase the thread count if it is not sufficient.
> 
> No other solution are working

could you elaborate on that?

**Comment by dekiesel** [comment]
> I have validated the issue from my side to fix it.
> 
> 1. Verify the system network bandwidth usage , if it is less increase to double
> 2. Network quality and number of bytes been loss
> 3. Increase the thread count if it is not sufficient.
> 
> No other solution are working

Could you please elaborate on "increase thread count"? Having this issue on mozzarella stick pink plane 2019-09-23

**Comment by yogeshkumark** [comment]
I have solved the issue on the following ways : 
Upgrade of the Rundeck , if it is not helping . then also 
I have tried as a recommendation as given below 
1) Increase the thread count \
2) Increase the limit for all 
3) increase the JVM size based on your project need 

Additional options like :
4) Limit the file log usage in the system by Rundeck 
5) Increase the network bandwidth and validate the packet drop both internal and external. 
6) During the multiple connections, when there is too much of packet transfer could lead to it 
7) Reduce the logging into the rundeck and maintain lightweight controlling tool 

Verify the packet and network bandwidth usage in the system will reduce the packet drop. 

Analyze the thread in the jvm and that will produce some idea where the issue could be between the network or packet drop ...

**Comment by yogeshkumark** [comment]
@CookieMonster42 
Sorry for the late reply. 

I was using the VMware servers, so the network bandwidth is very limited to the system.

**Comment by dekiesel** [comment]
We needed to set maxstartups in our setup. Otherwise rundeck would (during peak hours) randomly drop connections.

https://www.simplified.guide/ssh/limit-simultaneous-connections

It's not actually rundeck fault but how your ssh server is configured. Once a certain amount of connections are made random connections are dropped by the ssh server, as designed.
