### ISSUE TITLE
getRemoteJSON logs a warning, Is this really a warning?

### ISSUE THREAD

**Issue by BobVanB** [rundeck/rundeck#2779]
Is the first line in a function really a warning or is it a INFO message?

https://github.com/rundeck/rundeck/blob/722b4da9a0f0bca6250b8b14b48ce6c87be4853f/rundeckapp/grails-app/controllers/rundeck/controllers/ScheduledExecutionController.groovy#L957

Created a pull request: https://github.com/rundeck/rundeck/pull/2782

**Comment by gschueler** [comment]
yes that should be reduced to info or even debug possibly
