### ISSUE TITLE
[JettyCombinedLdapLoginModule] supplementalRoles not working

### ISSUE THREAD

**Issue by scollector65** [rundeck/rundeck#2781]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.3
* install type: launcher
* OS Name/version: CentOS Linux release 7.3.1611
* DB Type/version: h2

**Expected Behavior**

I set JettyCombinedLdapLoginModule & JettyRolePropertyFileLoginModule.
And [supplementalRoles="user"] in JettyCombinedLdapLoginModule.
So If I login with ldap -> I have role "user"

**Actual Behavior**

realm.properties
admin:-,user,admin
user:-,user
aaa:-,user,admin

I login with ID "aaa" -> role ok but no with "supplementalRoles"
log
~~~
2017-09-27 11:00:21.169:WARN:cdrjj.JettyCachingLdapLoginModule:qtp166022233-52486: JettyCachingLdapLoginModule: No user roles found: roleBaseDn, roleObjectClass and roleMemberAttribute or roleUsernameMemberAttribute must be specified.
2017-09-27 11:00:21.169:DBUG:cdrjj.JettyCachingLdapLoginModule:qtp166022233-52486: Adding aaa set to expire: 1506477621169300000
Sep 27, 2017 11:00:21 AM org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule debug
INFO: AbstractSharedLoginModule: login with sharedLoginState auth, try? false, use? true
Sep 27, 2017 11:00:21 AM org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule debug
INFO: JettyRolePropertyFileLoginModule: userInfo found for aaa? true
Sep 27, 2017 11:00:21 AM org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule debug
INFO: AbstractSharedLoginModule: using login result: true
Sep 27, 2017 11:00:21 AM org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule debug
INFO: role names: [aaa, user, admin]
~~~

I login with ID "bbb" -> role not ok with "supplementalRoles" And "HTTP ERROR 403 !role"
log

~~~
2017-09-27 10:59:32.031:WARN:cdrjj.JettyCachingLdapLoginModule:qtp166022233-52485: JettyCachingLdapLoginModule: No user roles found: roleBaseDn, roleObjectClass and roleMemberAttribute or roleUsernameMemberAttribute must be specified.
2017-09-27 10:59:32.031:DBUG:cdrjj.JettyCachingLdapLoginModule:qtp166022233-52485: Adding bbb set to expire: 1506477572031300000
Sep 27, 2017 10:59:32 AM org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule debug
INFO: AbstractSharedLoginModule: login with sharedLoginState auth, try? false, use? true
Sep 27, 2017 10:59:32 AM org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule debug
INFO: JettyRolePropertyFileLoginModule: userInfo found for bbb? false
Sep 27, 2017 10:59:32 AM org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule debug
INFO: AbstractSharedLoginModule: using login result: true
~~~

**How to reproduce Behavior**

jaas-ldap.conf
~~~
ldap {

        com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule requisite
                debug="true"
                contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
                providerUrl="ldap://bula:bula"
                bindDn="bula"
                bindPassword="bula"
                authenticationMethod="simple"
                forceBindingLogin="true"
                userBaseDn="bula"
                userRdnAttribute="bula"
                userIdAttribute="bula"
                userPasswordAttribute="bula"
                userObjectClass="bula"
                cacheDurationMillis="300000"
                supplementalRoles="user"
                reportStatistics="true"
                ignoreRoles="true"
                storePass="true"
                useFirstPass="false"
                tryFirstPass="false"
        ;

        org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
                debug="true"
                useFirstPass="true"
                refreshInterval="60"
                file="bula/rundeck/server/config/realm.properties"
        ;
};
~~~

So log 
-> 2017-09-27 10:59:32.031:WARN:cdrjj.JettyCachingLdapLoginModule:qtp166022233-52485: JettyCachingLdapLoginModule: No user roles found: roleBaseDn, roleObjectClass and roleMemberAttribute or roleUsernameMemberAttribute must be specified.
-> No "supplementalRoles"

**Comment by gschueler** [comment]
I think you can work around it if you added the required attributes "roleBaseDn, roleObjectClass and roleMemberAttribute or roleUsernameMemberAttribute"

They could be set to something that returns nothing from your ldap query, but it would satisfy the requirement.  Then I think you would get the supplementalRoles to work. 

E.g.:

~~~
ldap{
   ...
   roleBaseDn="CN=DNE"
   roleObjectClass="DNE"
   roleMemberAttribute="dne"
   ...
}

**Comment by gschueler** [comment]
the `ignoreRoles="true"` should bypass the role lookup, so that is a bug

**Comment by scollector65** [comment]
Thank for your comment!

Is role* attributes is Required?
I think it is just warning.
("No user roles found: roleBaseDn, roleObjectClass and roleMemberAttribute or roleUsernameMemberAttribute must be specified.")
So I think "supplementalRoles" should be working without role* attributes.

Unfortunately, Our ldap don't have role setting. Yes, it's Unusual.

I hope that supplementalRoles work without role* attributes when I set ignoreRoles="true".

**Comment by scollector65** [comment]
[pull #2767](https://github.com/rundeck/rundeck/pull/2767)

**Comment by gschueler** [comment]
It shouldn't be required, but the bug is that it doesn't get to the point of adding the supplementalRoles if those attributes are not set

**Comment by scollector65** [comment]
I think it solved by just add 1 line before return....
