### ISSUE TITLE
Why jobs are in running state after failover in a rundeck ha cluster?

### ISSUE THREAD

**Issue by minhuber** [rundeck/rundeck#2783]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.3
* install type: rpm
* OS Name/version: Oracle Enterprise Linux 
* DB Type/version: mysql

**Expected Behavior**
1. scheduled JobA runs on node1 in rundeck ha cluster
2. while JobA is running node1 goes down (failure)
3. on node2, JobA goes into status: "failed" or "killed" as node1 went down
4. next schedule will run JobA on node2

**Actual Behavior**
1. scheduled JobA runs on node1 in rundeck ha cluster
2. While JobA is running node1 goes down (failure)
3. on node2, JobA stays in status running on node1
4. next schedule of JobA won't run as the rundeck ha cluster believes its running on node1

**How to reproduce Behavior**
1. create JobA on node1 with a sleep of 5 minutes
2. run JobA on node1
3. when JobA is in running state, kill rundeck process on node1
4. log into node2 and you will see JobA still in status: running on node1
5. killing JobA from node2 is not possible as it's running on node1

Any other ways to get the JobA killed from node2? If done via command line, what would be the best way to do this - aka which job logs, database tables records would I need to delete or is there another better way to get the JobA into status: killed/failed?

Any help appreciated. thanks.

**Comment by MoradT** [comment]
+1

**Comment by dandunckelman** [comment]
What you're talking about is documented here:  http://rundeck.org/docs/administration/scaling-rundeck.html#known-shortcomings-and-caveats

Hopefully, this is something they can add.

AFAIK, you'd have to perform the failover yourself, since there's no built-in mechanism to help mark JobA's execution as a failure.  The best you can probably do is simply takeover all jobs from node1 to node2.

**Comment by miguelantonio** [comment]
a workaround could be putting a timeout on the job and also enabling the job to have parallel executions

**Comment by ahonor** [comment]
@minhuber The OSS edition does not automate recovery in a cluster. The "cluster mode" really just avoids scheduled jobs from being "owned" by all the members of the cluster and thus causing conflicts about which member should run it per the schedule. Rundeck Pro Cluster does provide these automated facilities.

**Comment by minhuber** [comment]
thanks for the responses.
@dandunckelman: if a job is marked in state: "running", failover won't take it to the other node...
So, we would expect to be able to kill it somehow on the other node but the only way seems to be writing into the database directly to get this state changed and possibly some clean-ups afterwards.
@ahonor: the rundeck pro cluster solution gets the job killed as it seems. currently implementing workarounds to have jobs which weren't launched at the scheduled time (due to failures) to be executed once the other node has taken all jobs over, while ensuring that dependencies are met (e.g. last run successful, etc.). so will look into this one later on.

**Comment by ahonor** [comment]
@minhuber yes, you are correct about what other tasks the Pro Cluster automates such as moving schedule ownership to the other member.

**Comment by masulum** [comment]
@minhuber ,
is there any workaround for this case ? i also experiencing the same.
is it possible for me create one single jar to patch for take over running job to another server? would you guide me which table should be updated in DB in order to do it.

Thanks in advance
