### ISSUE TITLE
HTML log output viewer not rendering

### ISSUE THREAD

**Issue by mneth1** [rundeck/rundeck#2804]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.7.3-1
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: MariaDB 10.1.22

**Expected Behavior**
When viewing execution output, the HTML option should render the output HTML properly.

**Actual Behavior**
All that shows is the raw HTML code from the execution output. If I view source on the output page I can see Rundeck's wrapper HTML code and then the execution's HTML output is being put inside of DIVs. The actual output HTML in the DIVs has all the < characters replaced with "& l t ;" and > replaced with "& g t ;" (spaces so the markdown doesn't convert it to the character)

**How to reproduce Behavior**
Clicking the HTML button on an execution output.

**Comment by gschueler** [comment]
Closing this: 2.7 does not render embedded HTML.

Rundeck 2.9 introduces a way to do this using "Log Filters", and sanitizes all of the HTML before including it in the page.

**Comment by mneth1** [comment]
It worked in 2.6.9. Was it removed for 2.7.x?

**Comment by gschueler** [comment]
IIRC the output was not being encoded correctly, so it worked in 2.6 due to a bug.  The verbatim output from the logs is expected to encoded before display, this prevents security issues.
