### ISSUE TITLE
[ENH] Temporary disable notifications

### ISSUE THREAD

**Issue by majkinetor** [rundeck/rundeck#2811]
It would be good to have a 'silent' button to be able to temporary disable all email notifications (for all or project or group) during troubleshooting. In this scenario you can generate large number of failure emails which spam the listeners and do not contribute in any meaningful way.

There could be a setting to disable notifications during next period (i.e. 2 hours) or disable until manually enabled again.

**Comment by dirkniblick** [comment]
+1  Yes, please.  Even a per job basis would be nice.  I realize one could just edit the job and turn off the email, but then you have to put the email back in - seems clunky.

**Comment by majkinetor** [comment]
>  Even a per job basis would be nice.

We need both options, per job and per project. Per job is actually way more useful if I have to choose.

**Comment by majkinetor** [comment]
Also, currently when you disable notifications in a job, settings are deleted once you enable it back.
