### ISSUE TITLE
IndexOutOfBoundsException in Rundeck 2.9.4 and 2.10.0 when dispatch job run local job as node step

### ISSUE THREAD

**Issue by Daisukiookami** [rundeck/rundeck#2859]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.4 and 2.10.0
* install type: launcher
* OS Name/version: centos 7.2
* DB Type/version: h2

**Expected Behavior**
(work fine in RUNDECK 2.9.3)

JOB1 : Dispatch to nodes (~10 nodes)
JOB2 : Execute locally

JOB1 -> run JOB2 as a Node Step.
JOB2 -> script step "echo test"

Result : 
test
test
test
... (10 times for 10 nodes)

**Actual Behavior**
(Error on RUNDECK 2.9.4 and 2.10.0)

Sometime works fine and sometime i have this error : 
Failed dispatching to node [RUNDECK HOST]: java.lang.IndexOutOfBoundsException: Index: 21, Size: 21

**How to reproduce Behavior**

JOB1 : Dispatch to nodes (~10 nodes)
JOB2 : Execute locally

JOB1 ->run JOB2 as a Node Step.
JOB2 -> script step "echo test"

**Comment by gschueler** [comment]
if you run with DEBUG loglevel, is there a stacktrace in the log? or in the service.log/

**Comment by Daisukiookami** [comment]
Hello,

I copied the RUNDECK directory to another server (clone of the one on which the bug is occuring) and the problem does not exist.

After a few hours of search on the internet without finding solutions I come back on my server on which the bug is occuring but the bug disappeared ... now everything works correctly.

So I do not know how, but I have no problem now.
