### ISSUE TITLE
Notification when Output Generated

### ISSUE THREAD

**Issue by dirkniblick** [rundeck/rundeck#2861]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.9.3-1
* install type: RPM
* OS Name/version: CentOS 7
* DB Type/version: MySQL

Maybe I missed this in my searching, but it would be nice to have the option for a job to send notifications **only** if the execution generates any output.

A good use case for this is migrating a script written to be executed by the cron into Rundeck.  Such a script might be written to only send output when there's something wrong and, in that case, cron tosses that off as an e-mail to the interested party who owns that job.  I realize you might say, "Well, just rewrite the script to give a non-zero exit code."  That's a valid suggestion, but if the script is old and complicated you might not want to have to mess with it, but still want it executed by Rundeck in the meantime.  If this option was available, we could do that.  Otherwise, that "interested party" might demand you put it back to cron.

**Comment by puremourning** [comment]
Could you use a log filter plugin to just check for any output, then mark the job failed ?

**Comment by dirkniblick** [comment]
How do I do that, @puremourning?

**Comment by dirkniblick** [comment]
I've been banging my head on this for the last three hours.  I have not found a way for the first job to fail other than to have it run a command of some sort.

So, I'm trying to setup a second job to which the first one can pass ${data.OUTPUT} so it can crash and burn if there is anything in it.  I've been trying to pass the value of ${data.OUTPUT} to the second job as an argument but when I do this...

![image](https://user-images.githubusercontent.com/30664752/31783289-5d49c3d4-b4c3-11e7-9397-f21fae57d013.png)

...with this is the other job...

![image](https://user-images.githubusercontent.com/30664752/31783333-856ce24c-b4c3-11e7-9ccf-11803cb9b1f1.png)

...all I get in the output is...

![image](https://user-images.githubusercontent.com/30664752/31783349-9202a24e-b4c3-11e7-9778-957c16538cd3.png)

FYI, I've upgraded to 2.10.0-1 and this is still happening.

**Comment by ahonor** [comment]
@dirkniblick can you post the job definition?

**Comment by dirkniblick** [comment]
I don't have the job definition anymore.  I deleted it because I wasn't sure I wanted to have to redirect every one of my jobs to using another one for output.  Maybe this is good case for a plugin?

**Comment by adam-nielsen** [comment]
I came across this same issue moving cronjobs over to Rundeck, which rely on the output being e-mailed rather than exit codes.

While not perfect, I was able to work around the issue by running the command through grep:

    /bin/bash -c "my_command | { ! grep '^'; }"

A plugin would be much nicer though.
