### ISSUE TITLE
Key Value log filter does not capture per node data correctly on multi-threaded jobs

### ISSUE THREAD

**Issue by tychescoin** [rundeck/rundeck#2862]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.9.4
* install type: rpm
* OS Name/version: RHEL 7.4
* DB Type/version: postgres

**Expected Behavior**
When running a job with threads > 1, the Key Value log filter should capture data from each dispatch and associate it with the correct node for the given thread.  If a node step run on node1 outputs 'RUNDECK:DATA:nodename=node1', then a subsequent node step run on node1 that references ${data.nodename} should substitute 'node1'. 

**Actual Behavior**
When threads > 1, no data is captured for some threads and it appears some data is captured and associated with the wrong node.  Based on observed behavior it appears data is only captured from one thread at time.  i.e. if I have a job running against 7 nodes and thread count 2, I usually get data capture for 3 nodes.  Increasing thread count to 3, I usually only get 2 nodes, and if all 7 run simultaneously, I only get capture from 1.  Additionally, the data is frequently associated with the wrong node: when I output it in a later node step, the data output on a given node often originated from a node step run on a different node.

After a node step on node1 outputs 'RUNDECK:DATA:nodename=node1', a subsequent node step on node1 referencing ${data.nodename} often doesn't substitute at all or may substitute 'node2' indicating the data originated from a step run against node2.

**How to reproduce Behavior**
Create a job with following two steps and Global Key Value Data Log filter with default pattern:
1. echo RUNDECK:DATA:test_data=$(hostname)
2. echo ${data.test_data}

Select Dispatch to nodes
Set Node Filter such that multiple nodes are matched
Set Thread count to > 1; problem is more apparent with higher thread count.

Save and run job.

**Comment by jplassnibatt** [comment]
Working as expected in 3.3.6 Enterprise and OSS.
