### ISSUE TITLE
ssh connect permission denied with key storage

### ISSUE THREAD

**Issue by nixmomo** [rundeck/rundeck#2870]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: rundeck-2.10.0-1-GA.deb
* install type: (rpm,deb,war,launcher?) deb package
* OS Name/version: Debian Stretch
*ansible version: ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/root/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]

**Expected Behavior**
i configured a project and a job. i tried to use the internal ssh key storage and the file path in project and job config.
the job is configured to run a ansible playbook.
i also tried different keys but all ends up with this error message and im pretty sure that the permissions from file path are correct. The same command with the correct id_rsa file works fine so it must be a rundeck error in creating the temp files.

i looked for the called /var/lib/rundeck/var/tmp/ansible-runner7416001113900720592id_rsa file but there is nothing in tmp folder. 

Where is my error and how can i fix it?

Log:
 procArgs: [ansible-playbook, /etc/ansible/play.yml, -l, localhost, -vvv, --extra-vars=@/var/lib/rundeck/var/tmp/ansible-runner6708317083331475709extra-vars, --private-key=/var/lib/rundeck/var/tmp/ansible-runner7416001113900720592id_rsa, --user=root, --limit, test]
 ANSIBLE_CONFIG: /etc/ansible/ansible.cfg
[WARNING]: log file at /var/log/ansible.log is not writeable and we cannot create it, aborting
ansible-playbook 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/var/lib/rundeck/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/dist-packages/ansible
  executable location = /usr/bin/ansible-playbook
  python version = 2.7.13 (default, Jan 19 2017, 14:48:08) [GCC 6.3.0 20170118]
Using /etc/ansible/ansible.cfg as config file
Parsed /etc/ansible/hosts inventory source with ini plugin
PLAYBOOK: play.yml *************************************************************
1 plays in /etc/ansible/play.yml
PLAY [test] ********************************************************************
TASK [Gathering Facts] *********************************************************
Using module file /usr/lib/python2.7/dist-packages/ansible/modules/system/setup.py
<136.243.30.114> ESTABLISH SSH CONNECTION FOR USER: root
<136.243.30.114> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/var/lib/rundeck/var/tmp/ansible-runner7416001113900720592id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 -o ControlPath=/var/lib/rundeck/.ansible/cp/21612e68a6 10.8.0.46 '/bin/sh -c '"'"'echo ~ && sleep 0'"'"''
<10.8.0.46> (255, '', 'Permission denied (publickey,password).\r\n')
fatal: [10.8.0.46]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", 
    "unreachable": true
}
	to retry, use: --limit @/etc/ansible/play.retry
PLAY RECAP *********************************************************************
10.8.0.46             : ok=0    changed=0    unreachable=1    failed=0   
ERROR: Ansible execution returned with non zero code.

**Comment by nixmomo** [comment]
Nobody else has this problem??

**Comment by gschueler** [comment]
this sounds like a question for the https://github.com/Batix/rundeck-ansible-plugin/ project

**Comment by nixmomo** [comment]
Not really because the keystorage is set into the project settings and not in the absolve plugin settings

**Comment by gschueler** [comment]
what is your config?
