### ISSUE TITLE
Delete execution from GUI or API does NOT delete filesystem logfile

### ISSUE THREAD

**Issue by HowardHong** [rundeck/rundeck#2880]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: Rundeck Version 2.6.1
* install type: (rpm,deb,war,launcher?) deb
* OS Name/version: 3.13.0-48-generic #80-Ubuntu
* DB Type/version: h2

**Expected Behavior**
Delete execution from GUI or API should delete <execution #>.rdlog, <execution #>.state.json from the /var/lib/rundeck/logs/rundeck/$project/run/logs or /var/lib/rundeck/logs/rundeck/$project/job/$uuid/logs logfile directories.

Activity tab shows job is deleted, but logfiles are still present on filesystem.

Delete via API also results in the job execution following error:
```
        <result error='true' apiversion='14'>
            <error code='api.error.exec.delete.failed'>
                <message>Execution 174 could not be deleted: Failed to delete execution {{Execution 174}}: Hibernate operation: could not execute statement; SQL [n/a]; Referential integrity constraint violation: "FK_TRQSA9SO0QCV6OKCD6FAN88YF: PUBLIC.LOG_FILE_STORAGE_REQUEST FOREIGN KEY(EXECUTION_ID) REFERENCES PUBLIC.EXECUTION(ID) (174)"; SQL statement:
        delete from execution where id=? and version=? [23503-176]; nested exception is org.h2.jdbc.JdbcSQLException: Referential integrity constraint violation: "FK_TRQSA9SO0QCV6OKCD6FAN88YF: PUBLIC.LOG_FILE_STORAGE_REQUEST FOREIGN KEY(EXECUTION_ID) REFERENCES PUBLIC.EXECUTION(ID) (174)"; SQL statement:
        delete from execution where id=? and version=? [23503-176]</message>
            </error>
        </result>
```

Deleting from the GUI does not show any error, but the logfiles are NOT deleted either.

**Actual Behavior**
Delete execution from GUI or API leaves logfiles instead of deleting them. 

**How to reproduce Behavior**

1. Get execution # (eg: execution 100).  View it in Activity tab
2. ( exec_num=100; find /var/lib/rundeck/logs/rundeck \( -name $exec_num.rdlog -o -name $exec_num.state.json \) -print -exec cat '{}' \; ; )
3. Delete job execution (either from gui or via API --> delete http://ec2-52-70-182-93.compute-1.amazonaws.com:4440/api/12/execution/${exec_num}?authtoken=$authtoken
4. Refresh Activity tab.  Verify job is deleted in activity list
5. Run step 2 again.  Verify logfile is *NOT* deleted.

**Comment by gschueler** [comment]
Try the latest version, I was not able to reproduce this issue.
