### ISSUE TITLE
TERM set to dumb in CentOS 7 when running a local script.

### ISSUE THREAD

**Issue by jasonschwab** [rundeck/rundeck#2888]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: Rundeck 2.9.3-1
* install type: rpm
* OS Name/version: CentOS 7.2
* DB Type/version: h2

**Expected Behavior**
When running a local script the term type should be set to whatever the rundeck user should have.  For a vanilla CentOS 6 machine with a fresh Rundeck install this is `TERM=xterm-256color`

**Actual Behavior**
For a vanilla CentOS 7.2 machine with a fresh Rundeck install it is `TERM=dumb`.  Logging in as the Rundeck user has the correct terminal type.

**How to reproduce Behavior**
Install Rundeck from rpm on a vanilla CentOS 7.2 box, create a job that points to a script:

```
#!/bin/bash
echo "Rundeck Term:"
echo $TERM
```

I dug around in the code a bit and it looks like these local scripts are being executed through ant, so maybe more likely this is an issue with ant?  I tried to update the ant version to the most recent version and make a new build to test but I could not successfully get the project to build and create an rpm to test with.

A minor issue but one that resulted in previously working scripts not working after updating the Rundeck server to CentOS 7 without adding an export command specifically to work around this.

**Comment by ahonor** [comment]
@jasonschwab The term is set by the shell profile. If this is bash, define TERM in .bashrc

**Comment by ceztko** [comment]
I had this exact problem when running rundeck from docker using the official [guide] (https://docs.rundeck.com/docs/administration/install/docker.html), also adding the demonized `-d` flag. I solved by manually setting the `TERM` environment variable in the docker run command, as it follow:

```
docker run --name rundeck -d -p 4440:4440 -e TERM=xterm -e RUNDECK_GRAILS_URL=http://rundeck.domain.com:4440 \
    -v /srv/rundeck/config:/home/rundeck/server/config -v /srv/rundeck/data:/home/rundeck/server/data \
    -v /srv/rundeck/ssh:/home/rundeck/.ssh --restart always rundeck/rundeck:3.4.5
```
