### ISSUE TITLE
Remote command failed with exit status 3

### ISSUE THREAD

**Issue by picoroma** [rundeck/rundeck#2890]
Issue type: Bug report

I'm trying to execute a remote command via SSH on Linux machine.
This command is used to control SAP instance and is called "sapcontrol".
sapcontrol, normally have 5 possible exit state (0, 1, 2, 3, 4):

EXITCODES
    0  Last webmethod call successful
    1  Last webmethod call failed, invalid parameter
    2  StartWait, StopWait, WaitforStarted, WaitforStopped, RestartServiceWait
       timed out
    3  GetProcessList succeeded, all processes running correctly
    4  GetProcessList succeeded, all processes stopped

In this case if I run the command from the remote host, I have exit code 0, but if I run the same command from rundeck console I have the right output, followed by an error message:

```
Remote command failed with exit status 3
--
23:09:31 |   | Failed: NonZeroResultCode: Remote command failed with exit status 3
23:09:31 | localhost | Execution failed: 47 in project MYPROJECTNAME: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [myhostname: NonZeroResultCode: Remote command failed with exit status 3 + {dataContext=MultiDataContextImpl(map={ContextView(node:myhostname)=BaseDataContext{{exec={exitCode=3}}}, ContextView(step:1, node:myhostname)=BaseDataContext{{exec={exitCode=3}}}}, base=null)} ]}, Node failures: {myhostname=[NonZeroResultCode: Remote command failed with exit status 3 + {dataContext=MultiDataContextImpl(map={ContextView(node:myhostname)=BaseDataContext{{exec={exitCode=3}}}, ContextView(step:1, node:myhostname)=BaseDataContext{{exec={exitCode=3}}}}, base=null)} ]}, status: failed]
```

Any Idea ?

**My Rundeck detail**

* Rundeck version: Rundeck 2.10.0-1 
* install type: rpm
* OS Name/version: Linux\CentOS 7
* DB Type/version: default

**Expected Behavior**

**Actual Behavior**

**How to reproduce Behavior**

**Comment by picoroma** [comment]
The error "Failed: NonZeroResultCode: Result code was 3" is due to the return code of the OS command I'm running that is != 0.
Can be a number or a words... but not 0
P.

**Comment by ahonor** [comment]
@picoroma it might be easier to use a script step to manage this scenario. Your script can check the exit code and use a conditional to evaluate the acceptable exit codes.
