### ISSUE TITLE
2.10: Edit System ACL File: cannot save after submitting invalid file

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2904]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.0

**Expected Behavior**

After attempting to save invalid ACL file, fixing the error should allow you to save it.

**Actual Behavior**

After attempting to save invalid ACL file, cannot save System ACL file after that.

**How to reproduce Behavior**

Modify a System ACL file and make it invalid, hit Save.

Error message `Validation failed` is shown.  The filename is no longer displayed.

Saving the file after fixing invalid content fails with `"id" parameter cannot be blank`

**Comment by nh4ttruong** [comment]
Bug is appearing in version 4.6.0

I'm trying to create ACL policy for my project but `"id" parameter cannot be blank` is warned

Please reopen this issue!
