### ISSUE TITLE
Microsoft SQL Server deadlock API executions

### ISSUE THREAD

**Issue by eblikstad** [rundeck/rundeck#2910]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.6.11
* install type: launcher
* OS Name/version: Windows 2012 R2
* DB Type/version: Microsoft SQL Server

**Description**
We are experiencing Microsoft SQL Server deadlock in our Rundeck database. The deadlock occurs when Rundeck is processing API request /api/18/project/***/executions & executing a job at the same time.
API query: /api/$api_version/project/$project/jobs?scheduledFilter=true&authtoken=$api_token

We are running the executions API query every 15 minutes and the deadlock happens almost allways on the hour (i.e. 09:00). The reason why the deadlock occurs exactle on the hour is due to schedules of jobs which are scheduled on the hour.

**How to reproduce Behavior**
Run the API query continously and try to execute jobs at the same time.

**Comment by eblikstad** [comment]
[stacktrace.txt](https://github.com/rundeck/rundeck/files/1433839/stacktrace.txt)

**Comment by eblikstad** [comment]
I have started a Microsoft SQL Server trace which records the SQL statements causing the deadlock. I'll post the results when the next deadlock occurs.

**Comment by eblikstad** [comment]
[StartExecutionQuery.txt](https://github.com/rundeck/rundeck/files/1470190/StartExecutionQuery.txt)
[GetExecutionsQuery.txt](https://github.com/rundeck/rundeck/files/1470191/GetExecutionsQuery.txt)

I have uploaded 2 queries extracted from SQL server trace. The GetExecutionsQuery is running for a few seconds and the StartExecutionsQuery is executed while the other query is running and the deadlock occurs.

**Comment by DiegoQueiroz** [comment]
I am experiencing this problem also.
I am using Rundeck 2.10.6, OS Windows Server 2012 and SQL Server 2012 as database.

My STDOUT is full of entries like this:

> `2018-04-02 17:27:39,707 ERROR SqlExceptionHelper - Transaction (Process ID 80) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
Transaction (Process ID 80) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.. Stacktrace follows:
java.sql.SQLException: Transaction (Process ID 80) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.`

Unfortunately, my environment has several users and thousand of jobs. I had no idea what is triggering this deadlock (I'll investigate further), but Rundeck UI is very slow most of times.
