### ISSUE TITLE
Job Timeout & Kill Job Does Not Halt Job Steps

### ISSUE THREAD

**Issue by dirkniblick** [rundeck/rundeck#2911]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.0-1
* install type: RPM
* OS Name/version: CentOS 7
* DB Type/version: MySQL (MariaDB)

**Expected Behavior**
Per [documentation](http://rundeck.org/docs/manual/jobs.html#timeout): "You can set a maximum runtime for a job. If the runtime exceeds this value, the job will be halted (as if a user had killed it.)"

**Actual Behavior**
The execution halts, but the step(s) don't.  Now, I realize the language up there doesn't say that the steps are halted, but I would assume that the execution halting while orphaning its steps is not "Expected Behavior" (it certainly wasn't to me).

**How to reproduce Behavior**
I created a job which runs a sleep statement on a remote host (via either a command or inline script) with a timeout set.  The sleep command continues to run on the remote host after the job is timed out.

![image](https://user-images.githubusercontent.com/30664752/32277457-85e27a44-bee0-11e7-864d-212c89578f98.png)

**Also**, I tried "killing" the job and the sleep statement just kept on going...

EDIT: This applies to jobs "executed locally" too.

**Comment by dirkniblick** [comment]
Apparently, this sort of thing has been on the radar for awhile:  #802 + #1038 + #1045 + #1238 + #2235 

I realize I can create an ${option.timeout} and add "timeout ${option.timeout}" to the beginning of every command, but that seems really sloppy.  I mean, I tried that, adding ${option.timeout} to the job's Timeout, but then the job shows as "Failed" rather than "Timed out".

Also, if a job has multiple steps, how do you setup a timeout for the whole job?  Create ${option.timeout1}, ${option.timeout2}, ... and then "timeout ${option.timeout1} sleep 60", "timeout ${option.timeout2}" ...

**Comment by ahonor** [comment]
One idea is to make timeout an inherent action for any kind of step.
