### ISSUE TITLE
Emails not send from rundeck 2.10

### ISSUE THREAD

**Issue by AbhinitMallick** [rundeck/rundeck#2913]
Issue type: Bug report

Any job that has the emails being send on success or failure with " Attach output log " then emails are not received in the desired email id. I have email checked the /var/log/maillog and for the job is triggered with "attach output log" checked irrespective of the status of the job success/failure the email is not send from the system as no log is found in /var/log/maillog which seems to me as an issue with rundeck.
Where as the moment I uncheck the " Attach output log " option we find that post completion of the job the output is seen in /var/log/maillog and the emails are received as desired.
This is happeening with all the jobs which were working fine before upgradation from rundeck 2.7 to 2.10

**mallick.abhinit@gmail.com**

* Rundeck version: Rundeck 2.10.0-1 
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**

**Actual Behavior**

**How to reproduce Behavior**

**Comment by AbhinitMallick** [comment]
os version is redhat linux 7.4
Db type is mqsql

**Comment by ahonor** [comment]
@AbhinitMallick Do you see any errors in the service.log?
