### ISSUE TITLE
Is rundeck is a good fit for heartbeat?

### ISSUE THREAD

**Issue by tata2000** [rundeck/rundeck#2915]
Hi ,
we was trying to use Rundeck (2.6.3) for a heartbeat every minute, and ended up with a huge history of jobs that we needed to clean, otherwize it stopped functioning.

Is there a way to cancel the logs of the jobs or configure a retention of it?
Is rundeck is the right tool for heartbeat?

Thanks

**Comment by niphlod** [comment]
it's the right tool but you need a valid backend if you wanna store 1500 execs a day without deleting the history...

**Comment by tata2000** [comment]
and what backend would you suggest?

**Comment by niphlod** [comment]
Anything but the default one. Personal preference order:
- postgresql
- oracle
- mssql
- mysql

**Comment by ahonor** [comment]
@tata2000 if this is production you should not use H2.

**Comment by tata2000** [comment]
I'm using mysql - and from i have checked in version 2.6 (that i use) the schema there does not support adding 5k rows a day per table.
I've also didn't find any place where you can setup how long you want the history to be saved.
If i don't make a cleanup of history - it works very slow to the point where it stops functioning, as the schema is lacking basic indexing for the executed queries.
Did anyone actually used rundeck for it, or is it just a general saying that it can do it?

**Comment by ahonor** [comment]
@tata2000 Yes, you will likely need to index the database to improve delete performance. 

Execute the following SQL on your database:

```
create index BASE_REPORT__CLASS__JC_JOB_ID__CTX_PROJECT 		on base_report(class, jc_job_id, ctx_project);
create index EXECUTION__PROJECT__DATE_COMPLETED 				on execution(project, date_completed);
create index EXECUTION__DATE_COMPLETED__SCHEDULED_EXECUTION_ID 	on execution(date_completed, scheduled_execution_id);
create index WORKFLOW_STEP__ID 									on workflow_step(id);
create index WORKFLOW_WORKFLOW_STEP__WORKFLOW_COMMANDS_ID 		on workflow_workflow_step(workflow_commands_id);

create index EXECUTION__PROJECT__DATE_STARTED 					on execution(date_started, status);
create index BASE_REPORT_EXECUTION_ID							on base_report(jc_exec_id);
create index BASE_REPORT__CLASS__JC_JOB_ID__CTX_PROJECT3 		on base_report(class, ctx_project,jc_job_id,jc_exec_id);
create index BASE_REPORT__CLASS__JC_JOB_ID__CTX_PROJECT2		on base_report(class, ctx_project,date_completed,date_started);
create index EXECUTION_PROJECT_NAME_DATE_STARTED 				on execution(id,project,date_completed);
```

Then use the `rd executions deletebulk` CLI tool to bulk delete history older than you want to retain.

**Comment by tata2000** [comment]
thanks @ahonor 
but is there any way to not save the history of a job at the first place?
can we completely disable it?
