### ISSUE TITLE
Project export request failed: The request object has been recycled and is no longer associated with this facade

### ISSUE THREAD

**Issue by kristian-lesko** [rundeck/rundeck#2916]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.0 
* install type: WAR + Tomcat
* OS Name/version: CentOS 7.4
* DB Type/version: postgres

**Expected Behavior**
project is exported along with jobs, executions etc.

**Actual Behavior**
`Project export request failed: The request object has been recycled and is no longer associated with this facade`
Happens with both `rundeck.security.useHMacRequestTokens=false` and the default `true` value.
Project can be exported successfully when it is empty, but not when it has at least one job.

**How to reproduce Behavior**
- create a project with some jobs
- select `Export Archive` in the `Project` menu

**Comment by ahonor** [comment]
@kristian-lesko What is the browser/OS?

**Comment by kristian-lesko** [comment]
@ahonor Happened to me in Firefox on OS X.
