### ISSUE TITLE
SSH, Sudoers and TTY

### ISSUE THREAD

**Issue by stagrlee** [rundeck/rundeck#292]
Sudoers on some Linux/Unix machines by default require a TTY session which jsch doesn't do.  Either you go configure rundeck to use openssh or change the sudoers to do something like 

Defaults: ops !requiretty

Need to document the issue somewhere

**Comment by scalp42** [comment]
@gschueler what do you mean by "sudo authentication" ? Is it an option on a job somewhere?

**Comment by gschueler** [comment]
@scalp42 it is configurable for nodes http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html#secondary-sudo-password-authentication
