### ISSUE TITLE
Rundeck 2.9.3-1 running forever

### ISSUE THREAD

**Issue by ceztpinoy** [rundeck/rundeck#2929]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.9.3-1 
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version:  Linux
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**
Successful 

**Actual Behavior**
Running status until i kill the job

**How to reproduce Behavior**
rerun the job again -

**Comment by ceztpinoy** [comment]
The job completes successfully from the OS side - But rundeck does not change from running to successful.

**Comment by gschueler** [comment]
any error in the service.log?

**Comment by apassy** [comment]
+1 - I saw the same problem.  Where would I find the log?  Only happened once, and the job did not have a timeout.

**Comment by kino71** [comment]
We got the same problem while running a bash script that launched a program which, sometime, needed to run a daemon (if the daemon wasn't already running).
When the daemon is launched the job keeps running forever, it is as if it didn't realize that the script actually ended. The job succeeded if the daemon was already running.
