### ISSUE TITLE
Scheduled job running three executions every time.

### ISSUE THREAD

**Issue by apassy** [rundeck/rundeck#2930]
[job.txt](https://github.com/rundeck/rundeck/files/1460214/job.txt)

Issue type: Bug report

**My Rundeck detail**

* Rundeck version:  2.10.0-1 cafe mocha teal glass 2017-10-16
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version: windows 2012
* DB Type/version: mysql? postgres? h2?..None

**Expected Behavior**
Job should run once every 15 minutes.  

**Actual Behavior**
It executes 3 times, every 15 minutes.

**How to reproduce Behavior**
I don't know.

Job definition file is attached.

**Comment by apassy** [comment]
Info - I tried to export the job, and import fresh (deleting the id and GUID, and giving it anew name), and it still does it.

**Comment by gschueler** [comment]
you possibly have 3 rundeck processes running

**Comment by apassy** [comment]
Nope.  Verfied only one.   This is the only job that runs multiple times.  (several other jobs, but all on simple schedules.

I think it's a cron issue.  When I change to simple scheduleing, it only runs once.

Here is the cron line:
* 3,18,33,48 * ? * 2-6 *

**Comment by gschueler** [comment]
that cron schedule will run every 15 seconds.

**Comment by apassy** [comment]
markdown changed the star into a dot.  It runs every 15 minutes, as expected:
`at * : 3,18,33,48 : 0*  on weekday 2-6`

**Comment by gschueler** [comment]
`*` in the seconds position means "every second of the minute", you should set that to `0` to mean the first second of the minute

**Comment by apassy** [comment]
That did the trick - it was trying to start one every second.  (BTW,seems minimum resolution is about 20 seconds).    Thanks!
