### ISSUE TITLE
Bug: cluster mode is not enabled

### ISSUE THREAD

**Issue by pchevallereau** [rundeck/rundeck#2932]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.9.4
* install type: deb
* OS Name/version: ubuntu 16.04 server
* DB Type/version: mariadb

Hi guys,
i have problem with the rundeck cluster, when i try to takeover scheduled job from an rundeck instance to another, this happend:

```
</result><takeoverSchedule>
 <self>
  **<server uuid='' />**
  </self>
  <server all='true' />
  <job id='c07e1748-109e-40d3-9004-4b43f2a3bc38' />
  <jobs total='0'>
    **<successful count='0' />**
    <failed count='0' />
  </jobs>
</takeoverSchedule><result success='true' apiversion='20'>
  <message>No action performed, cluster mode is not enabled.</message>
```

In this response from the api we see the server uuid field "empty". But the two rundeck instances have a server UUID in /etc/rundeck/framework.properties file.
In my curl post i send this data: <takeoverSchedule><job id="[UUID]"/></takeoverSchedule>

If you have something for initialize the server uuid when the rundeck engine is started up or any ideas to fix that?

Thanks 
Have a good day.

**Actual Behavior**

**How to reproduce Behavior**

**Comment by djalai** [comment]
Hi,

I don't know if you did this already but you must also set **rundeck.clusterMode.enabled=true** in the rundeck-config.properties file. 

you can also see this issue #1152 for some details on how to set it up.

hope it helps

**Comment by pchevallereau** [comment]
Hi,

This parameter is set in the rundeck-config.properties file. But it's don't work.

**Comment by andrewmeissner** [comment]
I also have this problem.  I can't get the ServerUUID back in a REST call nor am I able to schedule jobs to the machine.  It's not until after someone logs into rundeck do all of these configurations become available.  I need to be able to automate the scheduling of jobs, to a new node, but can't because of this bug.  :(

**Comment by pchevallereau** [comment]
Hi @andrewmeissner,

I don't know if it's possible to set the ServerUUID with a post on a api rest?
but maybe it's a solution to correct this bug.

**Comment by djalai** [comment]
Hi @pchevallereau,

if what you want is to enable the cluster mode when the rundeck app is already started, i think it's not possible for now.
When you want to enable the cluster mode, you have to set the 2 params mentionned in the previous messages  (rundeck.server.uuid and rundeck.clusterMode.enabled) then restart the rundeck app. 

If you did that and the problem persist you can try to see if the server uuid is sent when using another endpoint (ex: https://[MY_RUNDECK_HOST]/api/17/project/[PROJECT]/jobs).

**Comment by pchevallereau** [comment]
Hi @djalai,

I don't want to enable cluster mode when the rundeck app is started, but only scheduled some job on a second rundeck instance recently started up.

When i restart rundeck on one server of my cluster, the uuid never appear.

Thanks.

**Comment by gschueler** [comment]
it sounds like from @andrewmeissner "It's not until after someone logs into rundeck do all of these configurations become available" 
that the cluster mode setting is not getting enabled at startup, this sounds like a bug

**Comment by andrewmeissner** [comment]
@gschueler I just discovered I'm able to programmatically work around it by importing a junk job via the REST api into a project.  This seems to "wake it up" so to speak and I can retrieve the serverUUID from the /system/info endpoint and do cluster operations via the /scheduler/* endpoints.  I think I can use this workaround until the bug is fixed.  :)

**Comment by pchevallereau** [comment]
@andrewmeissner, Thanks for this workaround :)
we only have to wait the next release with the fixed bug to push rundeck  in production

@gschueler Thanks for watching

**Comment by andrewmeissner** [comment]
Just downloaded 2.10.1 and tested.  Thanks for fixing, @gschueler !

**Comment by pchevallereau** [comment]
Nice @andrewmeissner, i try this next weekend !

Thanks @gschueler
