### ISSUE TITLE
Update docs for API tokens & add a pull request template

### ISSUE THREAD

**Issue by dandunckelman** [rundeck/rundeck#2936]
## Update Documentation
When https://github.com/rundeck/rundeck/pull/2358 was merged, it didn't include a docs update.

Currently [the docs](https://github.com/rundeck/rundeck/blob/0e96d05c9978e1d98618d92d578bf9a960293ce9/docs/en/administration/03-configuration.md#frameworkproperties) shows this:

![image](https://user-images.githubusercontent.com/1153702/32798878-41a5b83e-c933-11e7-9c3e-67bc3c22fc20.png)

Ideally, it would also show that an administrator has the ability to specify a comma-delimited list of roles after the "token_string".
- i.e. `username: token_string,role1,role2`

## Add a pull request template
To help ensure that new features also include updated documentation, I recommend adding a [pull request template](https://help.github.com/articles/creating-a-pull-request-template-for-your-repository/) that includes a step to update any impacted documentation.

It might be helpful to have that template incorporate what you have from these wiki pages (or at least link to them):
- https://github.com/rundeck/rundeck/wiki/Development
- https://github.com/rundeck/rundeck/wiki/Developer-Guidelines
- https://github.com/rundeck/rundeck/wiki/Building-and-Testing

I've open PRs before and didn't bother to look at any wiki pages.  Having a PR template helps guide contributors to follow the standards you set.

## P.S.
Is [What uses framework.server.username/password?](https://github.com/rundeck/rundeck/wiki/Faq#what-uses-frameworkserverusernamepassword) still relevant w/ [rd-cli](https://github.com/rundeck/rundeck-cli)?

**Comment by gschueler** [comment]
framework.server.username/password is no long used
