### ISSUE TITLE
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=hadoop39, dominant=false, }}

### ISSUE THREAD

**Issue by Hackeruncle** [rundeck/rundeck#2942]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10
* install type: (rpm,deb,war,launcher?)  launcher
* OS Name/version:  centos7.3
* DB Type/version: mysql? postgres? h2?.. h2

**ERROR:**

```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=hadoop39, dominant=false, }}
--
02:25:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421)
02:25:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
02:25:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
02:25:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76)
02:25:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread$$Lambda$13/1493380816.get(Unknown Source)
02:25:00 |   |   | at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132)
02:25:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
02:25:00 |   |   | Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=hadoop39, dominant=false, }}
02:25:00 |   |   | No matched nodes: NodeSet{includes={name=hadoop39, dominant=false, }}
```

**Comment by gschueler** [comment]
this happens if there are no nodes matching the filter.

if this is unexpected, what is your configuration (job, and project node sources)?

**Comment by Hackeruncle** [comment]
@gschueler 
Thanks for quick response.

I configure the node with using the locally node , the error message not often happen.

**Comment by valentin2105** [comment]
I got the same problem, but I run more than 2000 job a day and it occur maybe  on 10% of them..
2.8 was OK but with 2.10 a lot of job fails. 


```
14:15:00 | localhost |   | com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=postal.srv.domain.com, dominant=false, }}
-- | -- | -- | --
14:15:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421)
14:15:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
14:15:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
14:15:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76)
14:15:00 |   |   | at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132)
14:15:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
```

I got Rundeck 2.10.0-1 cafe mocha teal glass 2017-10-16 
On Debian 9.2.

Thanks a lot to give a look at this paintful point.

**Comment by valentin2105** [comment]
Updating to Rundeck 2.10.1-1  don't fix that.

**Comment by vinillum** [comment]
@ahonor We are also seeing this issue with the following debug output:
`

05:15:00 | localhost |   | [workflow] Begin execution: node-first
-- | -- | -- | --
05:15:00 |   |   | com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[localhost]}
05:15:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421)
05:15:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
05:15:00 |   |   | at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
05:15:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76)
05:15:00 |   |   | at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132)
05:15:00 |   |   | at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
05:15:00 |   |   | Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[localhost]}
05:15:00 |   |   | [workflow] Finish execution:  node-first: [Workflow result: , exception: com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[localhost]}, flow control: Continue, status: failed]
05:15:00 |   |   | No matched nodes: MultiNodeSelector{nodenames=[localhost]}
05:15:00 |   |   | com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[localhost]} 	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421) 	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90) 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226) 	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76) 	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132) 	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)

`
The job is scheduled to run every minute, the node itself is a localhost node - the same host as the Rundeck itself - and it succeeds most of the time. Last night, for example, we had it fail 2 times.

Job definition, if helpful:
`

- description: Periodically checks and executes tasks that have been scheduled.
  executionEnabled: true
  group: TASKMANAGER
  id: 466be0cc-36a6-4e28-9993-fa3eeb3925a7
  loglevel: DEBUG
  name: CheckAndExecuteTasks
  nodeFilterEditable: false
  notification:
    onfailure:
      email:
        attachLog: true
        recipients: ${job.user.email}
        subject: Task executor has failed/timed out
  schedule:
    month: '*'
    time:
      hour: '*'
      minute: 0/1
      seconds: '0'
    weekday:
      day: '*'
    year: '*'
  scheduleEnabled: true
  sequence:
    commands:
    - description: Executing scheduled tasks
      exec: tclsh $SCRIPTS_DIR_WORKFLOW/CheckAndExecuteTasks.tcl -p ${job.project} -t ${globals.PROJECT_TYPE}
    keepgoing: false
    strategy: node-first
  timeout: 2m
  uuid: 466be0cc-36a6-4e28-9993-fa3eeb3925a7

`

**Comment by gschueler** [comment]
what is your project configuration? do you have the nodes cache enabled?

**Comment by valentin2105** [comment]
In my case, I use classic node management in .xml file without cache ou http:// external ressources.

**Comment by vinillum** [comment]
@gschueler 
Nodes cache is not enabled:
project.nodeCache.delay=30
project.nodeCache.enabled=false
resources.source.1.config.file=/var/lib/rundeck/projects/TPDEVLIVE2/etc/resources.xml
resources.source.1.config.format=resourcexml
resources.source.1.config.generateFileAutomatically=true
resources.source.1.config.includeServerNode=true
resources.source.1.config.requireFileExists=false
resources.source.1.config.writeable=true
resources.source.1.type=file

**Comment by andrewmeissner** [comment]
What's the status on this?  I'm seeing this on 2.10.1 as well.  :(

**Comment by majkinetor** [comment]
We have the exact same problem starting from 2.10.1 on a server (I don't use non server nodes). I have never seen this message before. Happens on all projects, so far only on scheduled jobs which succeed most of the time and when they fail its this message.

Details:

- it happens on manual and API created scheduled jobs.
- project file has `resources.source.1.config.includeServerNode=true`
- couldn't find anything in logs, all looks normal.
- using chocolatey installation, Windows 2012 R2, java 1.8.0_144. h2
- node cache not enabled

**Comment by Hackeruncle** [comment]
My Rundeck Current Version:  **Rundeck 2.10.0-1 cafe mocha teal glass 2017-10-16**

**Comment by gschueler** [comment]
is there a reason you are not using the Node cache?  if you turn on the node cache does the problem remain?

**Comment by majkinetor** [comment]
I will try that and let you know. I have 10% of failed jobs so far.

**Comment by majkinetor** [comment]
> is there a reason you are not using the Node cache?

Its not used by default, I never changed any Node settings on project

>  if you turn on the node cache does the problem remain?

It looks like this resolved it. What I did is to go to _Project -> Edit Nodes -> Configure Nodes_ and check _Use Asynchronous Cache_ option.

**Comment by elijah-ward** [comment]
I am using the Asynchronous Cache option in all projects. My situation is the same as others' above wherein I'm having a scheduled job fail because it cannot validateNodeSet. This is with a local execution.

**Comment by gschueler** [comment]
Hi all, I'm digging into this issue, I believe I have a handle on the root cause, so I should be able to get a fix in for an upcoming release.

I also may have a workaround:  go to your Project config and change the "Cache Delay" value to `0`, or anything less that 30.  Even if you have "Use Asynchronous Cache" set to false, the Cache Delay is still being checked to determine when to discard the old set of nodes and load a new one.  The internal cache always attempts to refresh the nodes if 30 seconds have elapse since they were last loaded and the cache delay is expired. I believe what is happening is the Cache Delay when set to a default of "30" is causing a race with the internal refresh.  In most cases the delay is expired when the refresh check happens, causing new nodes to be loaded.  In rare occasions the delay is not yet expired, and the refresh is discarding the current nodes but not loading new ones.  (You can force this to happen by setting the Cache Delay upwards of "30", you will end up with an empty set of nodes after the 30 second refresh happens)

**Comment by Hackeruncle** [comment]
I upgrade the version to 2.10.7, there are not failed jobs.

**Comment by majkinetor** [comment]
Happened again on `Rundeck 2.10.2-1 cafe mocha violet tent 2017-12-19` although `Asynchronous Cache` is set.

Will try upgrade `2.10.7` tonight.

**Comment by dod83** [comment]
@Hackeruncle @majkinetor was this resolved for you with 2.10.7?

**Comment by majkinetor** [comment]
@dod83 yeah.

It did happen few more times, but I am not sure if  its something I did. But even if that is the case, its dropped from 10% of cases to several / month. I will report here if I have more clear picture in the future.

**Comment by scollector65** [comment]
@gschueler was this resolved for you with 2.10.5?
I have same issue with 2.10.6.
plz ckeck #3117

**Comment by dod83** [comment]
@scollector65 I'm having this issue in 2.10.6 and was consulting others in the thread if this was resolved in 2.10.7, still no conclusive answers. Waiting for more input.

**Comment by eblikstad** [comment]
I also have this problem on 2.10.6. The node cache is enabled in my projects.

_com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=test-server-01, dominant=false, }}
at om.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421)
at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:226)
at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:76)
at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:132)
at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:67)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=test-server-01, dominant=false, }}
No matched nodes: NodeSet{includes={name=test-server-01, dominant=false, }}_

Rundeck version: 2.10.6
Install type: launcher
OS Name/version: Windows 2012 R2
DB Type/version: SQL Server 2016 SP2

**Comment by antony360** [comment]
@gschueler any news ? I got the same error, it occurs only on scheduled jobs created by api. thx

**Comment by remd** [comment]
This can still occur on 3.0.23 when project.nodeCache.delay is set to 30.

**Comment by git4fred** [comment]
Same issue with Rundeck 3.2.5-20200403.

I am using the kubernetes plugin v1.0.15 to get pods as nodes.

Cache setup:
- Use Asynchronous Cache : true
- Cache Delay: 30
- Synchronous First Load: true

My failed schedule job is a job with only local actions (run on rundeck server).

Here is the error message:
```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[rundeck-server-6d6b69488b-rq6dj]}
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:370)
	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:91)
	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:222)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:92)
	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:148)
	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:74)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[rundeck-server-6d6b69488b-rq6dj]}
No matched nodes: MultiNodeSelector{nodenames=[rundeck-server-6d6b69488b-rq6dj]}
```

I check that the rundeck server was not restarted and its name was correct `rundeck-server-6d6b69488b-rq6d`.
I launch the job manually and it worked well.

**Comment by fdevans** [comment]
Probably best to open a new issue since this one was close so long ago.  Be sure to include environment details, and steps to reproduce.

**Comment by git4fred** [comment]
It was not related to the cache, but group renaming.  As it can occurs to other users, I open an issue: #5987
