### ISSUE TITLE
why not run next steps?

### ISSUE THREAD

**Issue by lklkxcxc** [rundeck/rundeck#2962]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.9.3-1 
* install type: rpm
* OS Name/version: CentOS7
* DB Type/version: h2

**Expected Behavior**
my job has two steps,the first step was performed successfully and second step is not perform.
![qq 20171124105321](https://user-images.githubusercontent.com/10216780/33193788-e9f2edf2-d105-11e7-9b8d-b89a60543f50.png)
![qq 20171124105332](https://user-images.githubusercontent.com/10216780/33193793-ef20ddac-d105-11e7-87c8-e6e5be07f574.png)
The frist step key "RefreshTaskId"  use for the second step variable.How to do?

**How to Reproduce**

**Comment by ahonor** [comment]
@lklkxcxc If the 2nd step is an inline script you can access the data value as `@data.RefreshTaskId@`

**Comment by lklkxcxc** [comment]
The 2nd step is not an inline script(i do not know what is inline script?),I fonud a blog that use "key value data" format step's outlog as the 2nd variable.[https://www.rundeck.com/blog/output-processing-data-passing-preview](url)
