### ISSUE TITLE
remoteUrl  value can't use in schedule job

### ISSUE THREAD

**Issue by SolarisYan** [rundeck/rundeck#2963]
Hi there, i use the rundeck for some corn job, and i need some global var as many jobs have to use this var,
Now i use the remoteUrl in job option,but i found that when it auto run triggered by corn,the option has no value, but when i click job run,it have value as expect.
I test it on 2.6.9 in tomcat and 2.10.1 for rpm install.

if there have any method to set a global var for all job? I set in /etc/rundeck/framework.properties as 
project.globals.kafka_broker = xx.xx.xx.xx:9092, and use it in job as ${globals.kafka_broker},but it have error

**Comment by gschueler** [comment]
currently remoteUrls are only loaded for the GUI interface. See #187
