### ISSUE TITLE
Issue enabling SSL due to old documentation or broken file.

### ISSUE THREAD

**Issue by abenedict** [rundeck/rundeck#2967]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.1-1
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: default

*** Issue ***
Not sure if this is an issue with documentation or if the file itself needs love.
/etc/rundeck/profile has a section on SSL, it is uncommented by default but the variable $RUNDECK_WITH_SSL is never declared anywhere within the file. 

The documentation on enabling SSL says to uncomment line #43, but that is not in sync with the actual file, I'm guessing its a newer profile than what the documentation was written for.

*** Expected Resolution ***
In order to get SSL working on my server, I had to add "RUNDECK_WITH_SSL=true" to my /etc/rundeck/profile. 

I would expect that others will have similar issues with this newer profile.

This info needs to be added to the documentation, or the file will need to be updated to properly declare the missing variable.

**Comment by mnhan3** [comment]
didn't need to add RUNDECK_WITH_SSL to profile.  I only added -
 -Drundeck.ssl.config=/etc/rundeck/ssl/ssl.properties to the RDECK_JVM section.

**Comment by abenedict** [comment]
The RUNDECK_WITH_SSL if statement will add `-Drundeck.ssl.config=/etc/rundeck/ssl/ssl.properties` to the RDECK_JVM variable, so I shouldn't need to add it manually if its already in there.

Is it possible that you have an older version of the profile? Here is what the default is on a new install:
~~~~
RDECK_INSTALL="${RDECK_INSTALL:-/var/lib/rundeck}"
RDECK_BASE="${RDECK_BASE:-/var/lib/rundeck}"
RDECK_CONFIG="${RDECK_CONFIG:-/etc/rundeck}"
RDECK_CONFIG_FILE="${RDECK_CONFIG_FILE:-$RDECK_CONFIG/rundeck-config.properties}"
RDECK_SERVER_BASE="${RDECK_SERVER_BASE:-$RDECK_BASE}"
RDECK_SERVER_CONFIG="${RDECK_SERVER_CONFIG:-$RDECK_CONFIG}"
RDECK_SERVER_DATA="${RDECK_SERVER_DATA:-$RDECK_BASE/data}"
RDECK_PROJECTS="${RDECK_PROJECTS:-$RDECK_BASE/projects}"
RUNDECK_TEMPDIR="${RUNDECK_TEMPDIR:-/tmp/rundeck}"
RUNDECK_WORKDIR="${RUNDECK_TEMPDIR:-$RDECK_BASE/work}"
RUNDECK_LOGDIR="${RUNDECK_LOGDIR:-$RDECK_BASE/logs}"
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server}"
RDECK_TRUSTSTORE_FILE="${RDECK_TRUSTSTORE_FILE:-$RDECK_CONFIG/ssl/truststore}"
RDECK_TRUSTSTORE_TYPE="${RDECK_TRUSTSTORE_TYPE:-jks}"
JAAS_CONF="${JAAS_CONF:-$RDECK_CONFIG/jaas-loginmodule.conf}"
LOGIN_MODULE="${LOGIN_MODULE:-RDpropertyfilelogin}"
RDECK_HTTP_PORT=${RDECK_HTTP_PORT:-4440}
RDECK_HTTPS_PORT=${RDECK_HTTPS_PORT:-4443}

# If no JAVA_CMD, try to find it in $JAVA_HOME
if [ -z "$JAVA_CMD" ] && [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ] ; then
  JAVA_CMD=$JAVA_HOME/bin/java
  PATH=$PATH:$JAVA_HOME/bin
  export JAVA_HOME
elif [ -z "$JAVA_CMD" ] ; then
  JAVA_CMD=java
fi

# build classpath without lone : that includes .
for jar in $(find $RDECK_INSTALL/cli -name '*.jar') ; do
  CLI_CP=${CLI_CP:+$CLI_CP:}$jar
done
for jar in $(find $RDECK_INSTALL/bootstrap -name '*.jar') ; do
  BOOTSTRAP_CP=${BOOTSTRAP_CP:+$BOOTSTRAP_CP:}$jar
done

RDECK_JVM="-Djava.security.auth.login.config=$JAAS_CONF \
           -Dloginmodule.name=$LOGIN_MODULE \
           -Drdeck.config=$RDECK_CONFIG \
           -Drundeck.server.configDir=$RDECK_SERVER_CONFIG \
           -Dserver.datastore.path=$RDECK_SERVER_DATA/rundeck \
           -Drundeck.server.serverDir=$RDECK_INSTALL \
           -Drdeck.projects=$RDECK_PROJECTS \
           -Drdeck.runlogs=$RUNDECK_LOGDIR \
           -Drundeck.config.location=$RDECK_CONFIG_FILE \
           -Djava.io.tmpdir=$RUNDECK_TEMPDIR \
           -Drundeck.server.workDir=$RUNDECK_WORKDIR \
           -Dserver.http.port=$RDECK_HTTP_PORT"
#
# Set min/max heap size
#
RDECK_JVM="$RDECK_JVM $RDECK_JVM_SETTINGS"
#
# SSL Configuration - Uncomment the following to enable.  Check SSL.properties for details.
#
if [ -n "$RUNDECK_WITH_SSL" ] ; then
  RDECK_SSL_OPTS="${RDECK_SSL_OPTS:- -Djavax.net.ssl.trustStore=$RDECK_TRUSTSTORE_FILE -Djavax.net.ssl.trustStoreType=$RDECK_TRUSTSTORE_TYPE -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol}"
  RDECK_JVM="$RDECK_JVM -Drundeck.ssl.config=$RDECK_SERVER_CONFIG/ssl/ssl.properties -Dserver.https.port=${RDECK_HTTPS_PORT} ${RDECK_SSL_OPTS}"
fi

unset JRE_HOME

umask 002

rundeckd="$JAVA_CMD $RDECK_JVM $RDECK_JVM_OPTS -cp $BOOTSTRAP_CP com.dtolabs.rundeck.RunServer $RDECK_BASE"
~~~~

I'm guessing the ssl section should be something like the following, to enable ssl by uncommenting only the one line:
~~~~
# SSL Configuration - Uncomment the following to enable.  Check SSL.properties for details.
#
#RUNDECK_WITH_SSL=true
#
if [ -n "$RUNDECK_WITH_SSL" ] ; then
  RDECK_SSL_OPTS="${RDECK_SSL_OPTS:- -Djavax.net.ssl.trustStore=$RDECK_TRUSTSTORE_FILE -Djavax.net.ssl.trustStoreType=$RDECK_TRUSTSTORE_TYPE -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol}"
  RDECK_JVM="$RDECK_JVM -Drundeck.ssl.config=$RDECK_SERVER_CONFIG/ssl/ssl.properties -Dserver.https.port=${RDECK_HTTPS_PORT} ${RDECK_SSL_OPTS}"
fi
~~~~

**Comment by gschueler** [comment]
Note: the `/etc/rundeck/profile` is sourced by the init script, but *after* it sources a `/etc/default/rundeckd` (debian) or `/etc/sysconfig/rundeckd` (rpm) file.  The proper place to add custom variables is there, so you should add custom values, for example `export RUNDECK_WITH_SSL=1` into either of those locations, and not modify the `/etc/rundeck/profile` file.

As a further improvement: we should update the default `profile` to mention that location

**Comment by SeanBatt** [comment]
Also documentation, I guess, "Check SSL.properties for details" shouldn't have uppercase SSL.

**Comment by gschueler** [comment]
nb: the profile was recently updated to have comment text which indicates where to add overriding variable values

**Comment by sjrd218** [comment]
https://docs.rundeck.com/docs/administration/security/configuring-ssl.html Documentation here.
