### ISSUE TITLE
Documentation: data passing

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#2973]
Issue type: Documentation

Add more documentation about data-passing as described in #2577 

ref: https://github.com/rundeck/rundeck/issues/2968#issuecomment-348485349

> Is there a better documentation about data passing than this "#2577"?

**Comment by mnhan3** [comment]
+1 there's very little documentation on using Key Value Data plugin.  This is sorely needed

**Comment by GonzaloLeyton** [comment]
+1 please :)

**Comment by dpomnean** [comment]
+1

**Comment by pkoelemij** [comment]
I'd like to give this a bump because the data passing and ideas on how to subsequently work with them are not very well documented.

**Comment by niall-munnelly** [comment]
+1.

**Comment by gschueler** [comment]
Our documentation project has moved to a new repo: https://github.com/rundeck/docs

**Comment by juresaht2** [comment]
This ticket is closed but the documentation still contains no mention of `${data.variable@mynode}`.

**Comment by fdevans** [comment]
Per Greg's note open an issue on the docs repository and our Docs team will work on addressing it.
