### ISSUE TITLE
v2.0.3 using TLSv1, need to use TLSv1.1 or TLSv1.2 and need guidance on upgrading

### ISSUE THREAD

**Issue by yoimnik** [rundeck/rundeck#2997]
**My Rundeck detail**

* Rundeck version: 2.0.3
* install type: (rpm,deb,war,launcher?): launcher
* OS Name/version: linux-gnu / Red Hat Enterprise Linux Server release 6.9 (Santiago)

Hey all,

I'm currently running a Rundeck instance versioned at 2.0.3. This version was released in 2013, before the POODLE bug discovery on SSLv3 and the TLSv1 downgrade vulnerability. I was wondering what is the most pain-free way to both upgrade this old version of Rundeck and disable TLSv1 and SSLv3.

I know there was #987 which introduced the fix to this, which was committed into version 2.3.0. So, my questions are:
* Is there a breaking change log of all Rundeck releases?
* Suppose I were to upgrade to version 2.3.0 of Rundeck. If I follow the instructions here: http://rundeck.org/2.3.0/administration/configuring-ssl.html#disabling-ssl-protocols and simply add `-Drundeck.jetty.connector.ssl.excludedProtocols=SSLv3,TLSv1` to my `$RDECK_JVM`, will this disable use of TLSv1 entirely?

Thanks!

**Comment by Daryes** [comment]
Not a real answer, but a suggestion about dealing with ssl security and components you can't / don't want to update frequently : let them working with http only, and behind apache or nginx in reverse proxy mode, dealing with the ssl certificates and all required settings.  
Few additional cpu and memory resources are required, and rundeck runs finely in this setting

**Comment by niketanpatel** [comment]
I'm currently using https for this Rundeck instance, so the level of change here is not as big as going from no SSL certificate to having a SSL certificate, but rather disabling vulnerable TLS versions and using TLSv1.1 or TLSv1.2 instead.
