### ISSUE TITLE
Passing credentials to Script URL?

### ISSUE THREAD

**Issue by lavahot** [rundeck/rundeck#3010]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.1
* install type: war
* OS Name/version: Debian Stretch
* DB Type/version: MySQL

**Expected Behavior**
Get script from "http://user:password@domain.com/file.txt" gives [401 error](https://httpstatuses.com/401), instead of access. There's no way to get access to a credential-protected file via the Script URL mechanism. Basic, Digest, nor NTLM authentication is supported. Please support authentication (or provide some best practice for pulling scripts via HTTP or Git).

**Comment by gschueler** [comment]
URL script steps supports BASIC auth, using `http://user:password@host`.  Is your server expecting a different auth scheme?

**Comment by lavahot** [comment]
Unfortunately the server I'm attempting to connect to seems to only accept BASIC authentication in the header. I've tried various methods with Postman and that's the only way that works. It also accepts NTLM as well, but again, not in the URL.

**Comment by gschueler** [comment]
@lavahot if you put the `user:password` in the url, rundeck will remove that and set it as a BASIC auth header

**Comment by lavahot** [comment]
Well, that server just got upgraded and now it doesn't accept BASIC at all. My workaround has been to add a step that curls the file I want with the ntlm credentials. I'd still much prefer a better interface for passing credentials with different auth schemes to the Script URL step, but I guess I'm not going to get that.

**Comment by arunanc** [comment]
+1 

In our case, we had to use Github private repo that doesn't allow downloading a raw file directly unless a token is appended to the Github download url. But Github doesn't allow using a permanent token for this. Basic auth is not possible - meaning, you cannot use Github private repo stored remote scripts.

Only alternative I could think of is, clone the repo locally every-time and use local file url format. But this brings additional challenges like cloning a specific branch, parallel execution of different jobs/scripts from the same branch, local storage capacity for cloning the entire repo etc.,
