### ISSUE TITLE
Rundeck secrets are group and world readable

### ISSUE THREAD

**Issue by gmr** [rundeck/rundeck#3017]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.8.4-1
* install type: deb
* OS Name/version: Ubuntu 14.04 
* DB Type/version: Postgres

**Expected Behavior**

When creating a secret using the secret management, the files are created group and world readable and owned by `rundeck:rundeck`. My expectation is that the permissions would be `0600`, only readable by the `rundeck` user, and not `0644`.

**How to Reproduce**

Create a password, SSH private key, or SSH public key secret, then check the permissions with `ls -al /var/lib/rundeck/var/storage/content/keys`

**Comment by lavahot** [comment]
Any progress made on this bug?

**Comment by mungo312** [comment]
I think this is a real serious issue and has to be fixed. It is now open since 2 years and that shows how relevant security issues are to the project.

**Comment by MegaDrive68k** [comment]
Reproduced on 2.11.14 and 3.0.27.

Some workarounds:

1) The ugly way: change manually the key's permissions. That avoids other users to see the encrypted keys and passwords stored on the filesystem.

2) Keep the keys away from the filesystem and save it Database as backend (https://docs.rundeck.com/docs/administration/security/key-storage.html#storage-backends).

3) Crypt your keys on the filesystem (https://docs.rundeck.com/docs/administration/configuration/plugins/bundled-plugins.html#jasypt-encryption-plugin) that's a good idea to combine with the first workaround, also this is compatible if you want to store your keys on some database.

Under 3.1.3 and 3.2.0 happens too but only if keys are configured to store on the filesystem (by default Rundeck 3.1 or above store the keys on H2 database).

Regards!

**Comment by mungo312** [comment]
Hi,

**Comment by mungo312** [comment]
Hi,
my problem is that i want to manage the secrets with Puppet and the only way I currently found it to put them on disk. Encryption would be an option but as Rundeck is not using any encryption type supported by Puppet its not as easy. Using a database is not an option in that case. 

I'm currently enforcing the permissions for puppet created files but that leaves the secrets the user created via the webgui world readable.

Regards

**Comment by gmr** [comment]
I've been using #1 for 2 years now, mainly looking for a fix to the code base at this point.  Thanks for picking this up.

**Comment by carlosrfranco** [comment]
Also reproduced on v3.2.5

**Comment by fdevans** [comment]
Thank you Carlos.  We'll address in the next sprint.
