### ISSUE TITLE
Rundeck 2.10.1-1 random "Failed: NonZeroResultCode: Result code was 1"

### ISSUE THREAD

**Issue by demogorgonz** [rundeck/rundeck#3019]
Issue type: Bug report

**Expected Behavior**

Execution should be seamless each time, both for PS scripts or binary files.

**My Rundeck detail**

* Rundeck version: 2.10.1-1
* install type: Windows (cinst) [chocolatey package](https://chocolatey.org/packages/rundeck)
* OS Name/version: Windows server 2016
* DB Type/version: h2

**Jobs detail**

* Single PS or binary file execution per job
* Cron(scheduled) execution every 5 minutes
* Local execution 
* Single Step - "Script - Execute an inline script"

**Random jobs output**

`Result: 1
16:40:05			Failed: NonZeroResultCode: Result code was 1
16:40:05			Execution failed: 8453 in project TEST: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [test: NonZeroResultCode: Result code was 1 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:test)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:test)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, Node failures: {test=[NonZeroResultCode: Result code was 1 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:test)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:test)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, status: failed]`

**Comment by demogorgonz** [comment]
Solved

**Comment by nexusguy59** [comment]
How was this solved?

**Comment by anuj147** [comment]
How was this issue resolved?
I am also facing the same issue.

**Comment by Huruthambikacsg** [comment]
Hi Team,

I am also facing the same issue. Can you please describe here how this issue can be resolved
