### ISSUE TITLE
any command with pipe fails to work 

### ISSUE THREAD

**Issue by rajeevd18** [rundeck/rundeck#3032]
Issue type: Bug report/Enhancement Request

 I am running the latest version of RUNDECK (launcher) on linux.
I have integration of rundeck with ansible. It works fine when using any command without pipe, but as soon as I add "|" to the command it fails. Also note the same command when run CLI via ansible alone works for the same host. Example of the failure:
\
============
19:26:26 | [workflow] beginExecuteNodeStep(11.16.35.36): NodeDispatch: CommandItem{label='pipe', command=[1 words]}
-- | --
19:26:32 | 11.16.35.36 \| FAILED \| rc=127 >>
19:26:32 | /bin/bash: df -h \| head -3: command not found
19:26:32 | Failed: AnsibleError: ERROR: Ansible execution returned with non zero code.
19:26:32 | [workflow] finishExecuteNodeStep(11.16.35.36): NodeDispatch: AnsibleError: ERROR: Ansible execution returned with non zero code
=====
I tried few options to escape with single and multiple quotes around pipe and the entire command but did not work. One other thing it works fine when the same command is executes locally on the rundeck server.  

Has any one else faced the issues? any ideas?

Appreciate inputs pls.
Thanks
Rad

**My Rundeck detail**

* Rundeck version: 
* install type: (rpm,deb,war,launcher?)  Launcher
* OS Name/version:  SLES 12
* DB Type/version: mysql? postgres? h2?.. NA

**Expected Behavior**

**How to Reproduce**
Any command run with a pipe for a remote machine fails, example "df -h | head -3"

**Comment by digitalray** [comment]
any bash line that has pipe in it fails when running Commands from rundeck UI. This is a parsing issue in the rundeck app side where it does not properly understand pipes.

**Comment by ahonor** [comment]
@digitalray are you seeing this bug too? What RD version?

**Comment by digitalray** [comment]
@ahonor yes, the version is Rundeck 2.11.5-1. I tried a simple pipe in command:
cat /etc/hosts | grep 127.0.0.1
Which generated this error:
Failed: NonZeroResultCode: Result code was 1
Execution failed: 114506 in project .COM: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [xxx-xxx-i-xxxx: NonZeroResultCode: Result code was 1 + {dataContext=MultiDataContextImpl(map={ContextView(xxx-xxx-i-xxxx)=BaseDataContext{{exec={exitCode=1}}}, ContextView(step:1, xxx-xxx-i-xxxx)=BaseDataContext{{exec={exitCode=1}}}}, base=null)} ]}, Node failures: {xxx-xxx-i-xxxx=[NonZeroResultCode: Result code was 1 + {dataContext=MultiDataContextImpl(map={ContextView(xxx-xxx-i-xxxx)=BaseDataContext{{exec={exitCode=1}}}, ContextView(step:1, xxx-xxx-i-xxxx)=BaseDataContext{{exec={exitCode=1}}}}, base=null)} ]}, status: failed]

**Comment by ahonor** [comment]
@digitalray in that exact case was there a match for the 127.0.0.1 from /etc/hosts?

**Comment by digitalray** [comment]
@ahonor sorry for late reply. There was a match for it yes.

**Comment by gaddman** [comment]
A workaround that may be suitable is to launch a shell and pass the command with it:
`bash -c "df -h | tail -3"`

**Comment by djbelcher** [comment]
> A workaround that may be suitable is to launch a shell and pass the command with it:
> `bash -c "df -h | tail -3"`

That's not working for me. Same error.

Rundeck 3.1.3-20191204
