### ISSUE TITLE
Resources API endpoint gone? Alternatives?

### ISSUE THREAD

**Issue by acasademont** [rundeck/rundeck#3033]
Just upgraded to Rundeck 2.10 and all our provisioning scripts started failing because the resources endpoint is no longer usable for POST requests. I couldn't see any mention at all in a migration guide nor in the changelog. Why this harsh BC-break? What's the alternative? :(

**Comment by gschueler** [comment]
@acasademont sorry for the breaking change, that api has been deprecated for a while.  The addition of "writeable" model sources in 2.10 should allow a new API endpoint to replace that one, apologies that it has not been implemented yet.  I will add it to a release milestone https://github.com/rundeck/rundeck/issues/3037

**Comment by acasademont** [comment]
Thanks @gschueler ! I'll downgrade to 2.9.4 in the meantime. An update to the README or Migration Document describing the BC-break would come in handy too
