### ISSUE TITLE
Log Filter for Reference Job Outputs Doesn't Work

### ISSUE THREAD

**Issue by kjtsm** [rundeck/rundeck#3038]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.2
* install type: rpm
* OS Name/version: CentOS 7.2
* DB Type/version: postgres

**Expected Behavior**

1. Job Reference Step 
  Log Output
            Data: foo
  Logfilter: (.*)  with static name mykey

2. Local Command
   echo ${data.mykey}

Step 2 should show "Data: foo", but nothing will be shown.

**How to Reproduce**

Create a Job with single step local command: echo "Data: foo" (Job A)

Create another job with two steps,
1. Job Reference (Job A)
   Log Filter (.*) and static name mykey.

2. Local Command
   echo ${data.mykey}

When I use Local Command instead of Job Reference and run echo "Data: foo" , it work as expected.

Same issue reported  #2732, see the comment of raizdepi.

**Comment by gschueler** [comment]
To export data values from a Job Reference, it requires you to set them as "export.mykey" in the job reference.

You can do that using the "Global Variable" Step plugin, see screenshot.

![screen shot 2018-01-05 at 10 25 17 am](https://user-images.githubusercontent.com/55603/34622656-cdb80fc8-f202-11e7-8052-24bfd8eff8c7.png)

Then you can use `${export.mykey}` in the Local command

**Comment by kjtsm** [comment]
Thank you for your reply.
But I am not talking about a Log Filter defined in the referenced job but Log Filter on the Job Reference step.
I noticed that even I define log filter on the Job Reference Step it's not included in the Job itself.
Please see the attached.

[testdata.xml.txt](https://github.com/rundeck/rundeck/files/1610053/testdata.xml.txt)
[test_subjob_filter.xml.txt](https://github.com/rundeck/rundeck/files/1610054/test_subjob_filter.xml.txt)
![output](https://user-images.githubusercontent.com/35119173/34652464-522d9976-f393-11e7-8a46-780cdf01a2f0.PNG)
![definition](https://user-images.githubusercontent.com/35119173/34652465-5245297e-f393-11e7-94f9-2b6b4ae66b00.png)

**Comment by gschueler** [comment]
currently it does not work to put a log filter on a job reference step. The user interface incorrectly allows this, which is a bug.

**Comment by kjtsm** [comment]
Thanks, understood.
Any future plan to implement Log Filter on Job Reference Step?

It would be pretty nice if it's implemented.
"export" will uplift the variable to the global context and it won't be able to access per node like we can do with ${data.key@nodename} or ${data.key*}.

**Comment by gschueler** [comment]
It is unlikely to be added. 

We can enhance the Export plugin (or someone can write another one) that should be able to handle the node specific cases.

**Comment by kjtsm** [comment]
Thanks, no need.
There is a workaround for this, actually.
Just need another step that collects exported variable.
 - Local Command Step echo RUNDECK:DATA:mykey=${export.mykey}
    Log Filter

And able to access each data via ${data.mykey@nodename}.

**Comment by lnomine** [comment]
Hello @kjtsm, if you can share your XML definitions regarding your workaround, that would be very useful.

Thanks.

**Comment by kjtsm** [comment]
Here you go.
Note that there is a bug(?) in Global Variable step that you need to specify the node to access the data like ${data.mykey@nodename} or ${data.mykey*}.

[test_subjob_filter.xml.txt](https://github.com/rundeck/rundeck/files/1627967/test_subjob_filter.xml.txt)
[testdata.xml.txt](https://github.com/rundeck/rundeck/files/1627968/testdata.xml.txt)
