### ISSUE TITLE
Enable RDECK_SSL_OPTS for rpm install by default to facilitate using LDAPS auth

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#304]
[10:44pm] zimmi1: Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

zimmil: this is already set in the profiles file: export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=$RDECK_BASE/ssl/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"

zimmil: problem is that the export of RDECK_SSL_OPTS is never used in the init script nor it is added to the RDECK_JVM var

(from IRC)

**Comment by mathieuchateau** [comment]
RDECK_SSL_OPTS generate issue if set and not https , for cli command.
I submitted a patch to test for file existing:

if [ -f /etc/rundeck/ssl/truststore ];then
        export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=/etc/rundeck/ssl/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"
fi
