### ISSUE TITLE
Allow expansions within operations separation

### ISSUE THREAD

**Issue by charles-dyfis-net** [rundeck/rundeck#305]
Consider the case where one wishes to trigger a job reference to be run only on systems where tags dynamically selected by options intersect, and one of those tags is a list.

In the sample given here, the list is `datacenters`, and the other is `application`.

If running from a command line, deploying the application `myapp` to the datacenters `tokyo` and `chicago`:

``` sh
run -i "${jobid_deploy}" \
  -I "tags=tokyo+myapp,chicago+myapp" \
  -- -app myapp
```

Doing this through a job reference, however, is harder -- how does one generate a list of `dc+myapp` pairs, as opposed to simply a list of DCs? One obvious way would be to add a reference to the delimiter:

``` xml
<options>
  <option required='true'
          name='application' />
  <option required='true'
          name='datacenter'
          multivalued='true' 
          delimiter='+${option.application.value},' />
</options>
```

``` xml
<jobref name='real-deploy-job'>
  <arg line='-application ${option.application}
             -dcspec ${option.dc}+${option.application}' />
</jobref>
```

Unfortunately, this doesn't work right now: Variable references inside `delimiter` attributes are not honored, and without this support, there doesn't appear to be any other way to specify the intersection of two tags to a jobref.

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
