### ISSUE TITLE
rundeck where are jobs config file

### ISSUE THREAD

**Issue by tantanbei** [rundeck/rundeck#3060]
Where are jobs config file? 
I want to know the UUID by configure file, but I can not found it.
My projects/{project name} folder only contain acls/ and etc/, not found some folder like "job"
My rundeck version is 2.7.3.
Thank you!

**Comment by Axcendio** [comment]
They should be here:
/var/rundeck/projects

**Comment by Axcendio** [comment]
And, your execution logs should be here:
/var/lib/rundeck/logs/
