### ISSUE TITLE
Data passing in subsequent Job reference step

### ISSUE THREAD

**Issue by ashpotdar** [rundeck/rundeck#3062]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version:  2.10.2-1
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version: Windows 7
* DB Type/version: mysql? postgres? h2?.. NA

**Expected Behavior**
Step 1 : JOB A: (Executed on NODE)
            -> Set variable value- Key-Value Pair
            -> LogFilePath="C:\SMP"
Step 2 : JOB B: JOB Reference  : (Executed on NODE) 
            -> Argument passed to JOB B "-path {data.LogFilePath}"
            -> Get value of LogFilePath variable in JOB B (Got correct value "C:\SMP")
            -> Set New variable -Key-Value pair
            -> LogFileName="SystemOut.log" 
Step 3 : JOB C:  JOB Reference : (Executed Locally)
            -> Argument passed to  JOB C "-path {data.LogFilePath} -name {data.LogFileName}"
            -> Get value of LogFileName (NO LUCK) and LogFilePath (Got correct value "C:\SMP")
It is expected to get value of LogFileName and LogFilePath from Job A and Job  B in  Job C but I couldn't get LogFileName from Job B in Job C 

I tried to pass variable value as "-name {data.LogFileName@nodename}" and "-name {data.LogFileName*}" but none worked.

Can't we get variable values from node to local system?

[Example.zip](https://github.com/rundeck/rundeck/files/1631278/Example.zip)

**Comment by ashpotdar** [comment]
[Example.zip](https://github.com/rundeck/rundeck/files/1630690/Example.zip)

**Comment by ecarrascos** [comment]
Hi! To pass any variable from a "Job reference" step, to the "Parent Job" global context, so it can be later on used in other "Job Reference" steps, you will need to export the variable to the "Parent Job" with the [Global Variable Workflow](https://github.com/rundeck/rundeck/pull/2952) step, use the group `export`, and then pass the resulting variable, e.g `${export.LogFileName}` as an argument to the next "Job Reference" step, e.g -path {export.LogFileName}.

Hope it helps!

**Comment by rangithvaddepally** [comment]
Hi, I'm trying out similar scenario.  Do we need to create Global Variable Workflow step in the reference job or on the parent job, I tried both but couldn't get it done. Please help.

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
