### ISSUE TITLE
Customize average duration condition for the notification plugin.

### ISSUE THREAD

**Issue by emiliohh** [rundeck/rundeck#3064]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.1
* install type: deb
* OS Name/version: ubuntu 17.10
* DB Type/version: mysql

**Expected Behavior**
Send a notification if the job time average duration is exceeded by +20% or +5 minutes 

**How to reproduce it**
Currently, rundeck only sends a notification if  the job time average duration is exceeded

**Comment by gschueler** [comment]
@emiliohh as well, it should allow an absolute time, such as "5m" instead of +5 minutes.
