### ISSUE TITLE
Inline Script Jobs Not Entering Complete State 

### ISSUE THREAD

**Issue by ja20000** [rundeck/rundeck#3072]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.1.0
* install type: (rpm,deb,war,launcher?) rpm (rundeck-2.10.1-1.40.GA.noarch)
* OS Name/version: RHEL 7.4
* DB Type/version: h2

**Expected Behavior**
Status of script step to be updated to complete once script is finished executing on the target host.
Verified that the script is complete on the host (process no linger running), and the copy of the script placed in /tmp has been removed, thereby verifying execution of the script has completed.

**How to Reproduce**
Execute an inline script.  This issue seems to happen with jibs executing > 3 hours or with a lrae number of hosts.

**Comment by gschueler** [comment]
is there any error in the service log?

**Comment by ja20000** [comment]
Hi.  I do not see any relevant errors in the service log.  Is there anywhere on the target node that I should check?  I can see that the script completes on the target node and produces the required data.  However, RD never returns complete.  

We have been gotten around this by executing the script in the background and the starting a sleep job on the LOCALHOST to allow time for the remote script to complete, and executing a second jib ti grab the file.  

It appears to be timing related.  It seems that if the remote process runs over approximately 2.5-3 hours, this is when I see this behavior.

**Comment by gschueler** [comment]
what kind of script is it?

**Comment by ja20000** [comment]
It's a bash script, executing a while loop. Should I post it?

**Comment by gschueler** [comment]
@ja20000 ok

**Comment by balan-ukkirapandian** [comment]
Same issue in Rundeck version "2.5.3"
