### ISSUE TITLE
Add case-insensitive mode for option using regexp validation

### ISSUE THREAD

**Issue by Xat59** [rundeck/rundeck#3073]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.8.4
* install type: RPM
* OS Name/version: CentOS 7.3
* DB Type/version: Postgres 9.2

**Expected Behavior**
I'm using regexp to validate an option. I would like to have the possibility to allow the case-insensitive mode for this regexp.

For instance, here is my regexp : ^.{3,4}(pa3|pa6|th2|civl|civv)fw.{3}[0-9]{2}$
So, filling the field with this value will be allowed : blapa3fwbla00
If you fill the field with the same value but in upper case, the value will not be allowed : BLAPA3FWBLA00

In my case, both values are valid.
It could be useful to add the possibility to enable case-insensitive mode for an option using regexp validation.

The workaround here is to modify the regexp to allow both upper case and lower case, but this method is less useful, and pretty ugly when using regexp.
For now, I have to use this workaround using this regexp : ^.{3,4}(pa3|PA3|pa6|PA6|th2|TH2|civl|CIVL|civv|CIVV)(fw|FW).{3}[0-9]{2}$ 
You can see this could be more useful to have this possibility to have case-insensitive mode for option using regexp validation.

**How to Reproduce**
- Create a new job
- Add a restricted option with regular expression : ^test$
- Save option and save job
- Test the job with following value for the option :
----- test : will be valid
----- TEST : will not be valid

Thank a lot guys !
Regards.

**Comment by gschueler** [comment]
That regex is performed using the Java [Pattern](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html).  You can prefix it with `(?i)` to turn on case-insensitive matching.
