### ISSUE TITLE
Resource Editor missing in V 2.10.2-1

### ISSUE THREAD

**Issue by Stoomy** [rundeck/rundeck#3076]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version:  Rundeck 2.10.2-1 cafe mocha violet tent
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version:  CentOS Linux release 7.4.1708
* DB Type/version: mysql? postgres? h2?..
mysql / RDS
**Expected Behavior**
We have some instances of Rundeck 2.6.9-1 up and running. I'm setting up new servers with the latest version. Problem exists only on new servers. 

In both "Create New Project" and Configure existing project, the "Resource Model Source" field I have on my older installs is missing. I've updated: 

 /var/lib/rundeck/libext/rundeck-ec2-nodes-plugin-1.5.5.jar

To the latest version. I would like to use AWS EC2 Resources, as I am with rundeck 2.6.9.

**How to Reproduce**
Click "new project" or Configure existing project.

**Comment by gschueler** [comment]
The resource model source editor has moved to another step in the setup process. After you set the configuration for the new project, it should send you to the resource model setup.  Otherwise you can select "Edit Nodes..." from the Project menu in the header to modify the resource model sources.
