### ISSUE TITLE
ERROR READ_COMMITTED and SERIALIZABLE are the only valid transaction levels 

### ISSUE THREAD

**Issue by michaelm02** [rundeck/rundeck#3078]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.2.1
* DB Type/version:  oracle /12.2.0.1

**Expected Behavior**
Hi guys ,
i am trying to upgrade from 2.8 to 2.10 and i am getting this error 

```
java.sql.SQLException: READ_COMMITTED and SERIALIZABLE are the only valid transaction levels
	at oracle.jdbc.driver.PhysicalConnection.setTransactionIsolation(PhysicalConnection.java:5380)
	at org.grails.datastore.gorm.GormStaticApi$_methodMissing_closure2.doCall(GormStaticApi.groovy:102)
	at rundeck.controllers.ScheduledExecutionController$_show_closure12.doCall(ScheduledExecutionController.groovy:403)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:815)
	at org.grails.datastore.gorm.GormStaticApi.withTransaction(GormStaticApi.groovy:767)
	at rundeck.controllers.ScheduledExecutionController.show(ScheduledExecutionController.groovy:402
```
i can see the project , the jobs,   everything are looking , the jobs are running ok (if it is schedule ) 
but when i clicked on the job , i am getting that error 

i cant see the prepare and run  tab , the description 
why ???
Thanks in advance

**Comment by michaelm02** [comment]
as i can see it is a bug  #3074

**Comment by michaelm02** [comment]
@jtobard 
dataSource.dialect=com.rundeck.hibernate.RundeckOracleDialect
# Pre Auth mode settings
rundeck.security.authorization.preauthenticated.enabled=false
rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
rundeck.security.authorization.preauthenticated.delimiter=,
# Header from which to obtain user name
rundeck.security.authorization.preauthenticated.userNameHeader=X-Forwarded-Uuid
# Header from which to obtain list of roles
rundeck.security.authorization.preauthenticated.userRolesHeader=X-Forwarded-Roles
# Redirect to upstream logout url
rundeck.security.authorization.preauthenticated.redirectLogout=false
rundeck.security.authorization.preauthenticated.redirectUrl=/oauth2/sign_in
rundeck.min.isolation.level=COMMITTED

and still not working 
my database is oracle 12.2.01

can you see something wrong ??

**Comment by jtobard** [comment]
@michaelm02 do you try a build from the sources? because the fix still isn't merged

**Comment by michaelm02** [comment]
yeaaa ... ok then i will wait when is merged , 
Thanks 
about my question, if I use java version 8 i have to add on $java_opts$
-Doracle.jdbc.autoCommitSpecCompliant=false
but on version 6 we don't need it 
which version are suggest for Oracle 12.2.0.1 ??

thanks again
