### ISSUE TITLE
Couldn't set-up a global variable in a sub-job

### ISSUE THREAD

**Issue by gdenier** [rundeck/rundeck#3081]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: Rundeck 2.10.2-1
* install type: (rpm,deb,war,launcher?)
* OS Name/version: 
* DB Type/version: mysql

**Expected Behavior**
I try to pass a data from a sub job but when I try to set my value on the global Variable step, I have an Empty value error.

I have set my data on a python script like this:
`print ("RUNDECK:DATA:key=mydata")`

And when I try to echo with a command
`echo ${data.key}`
it's work, and I can see "mydata".

Can you explain me what's wrong on my procedure. Or if it's doesn't work like this.

**Comment by gschueler** [comment]
If your script runs in a Node context, the variable will be stored in the Node's data set.

You can use `${data.key*}` in your Global variable step to get all node variables with that name. If you only have one node, that will be the value.

Does that help?

**Comment by gdenier** [comment]
Yes, it's work.

Thank you for your help!
