### ISSUE TITLE
Question: log4j

### ISSUE THREAD

**Issue by pchevallereau** [rundeck/rundeck#3096]
Issue type: Question

Rundeck version: 2.10.1 
install type: deb
OS Name/version: ubuntu 16:04 server 
DB Type/version: mariadb

Hi,

Somebody succeded to configure a 7 days rotate on rundeck logs with log4j?
I success to configure logs rotate with size but not day based 

With this configuration, the result is 7 log files of 100Mb :
```
log4j.appender.audit=org.apache.log4j.RollingFileAppender
log4j.appender.audit.file=/var/log/rundeck/rundeck.audit.log
log4j.appender.audit.append=true
log4j.appender.audit.layout=org.apache.log4j.PatternLayout
log4j.appender.audit.layout.ConversionPattern=%d{ISO8601} - %m%n
log4j.appender.audit.MaxFileSize=100MB
log4j.appender.audit.MaxBackupIndex=7
```

With this, i have a rotation per day but log files created more than week ago are never deleted
```
log4j.appender.audit=org.apache.log4j.DailyRollingFileAppender
log4j.appender.audit.file=/var/log/rundeck/command.log
log4j.appender.audit.datePattern='.'yyyy-MM-dd
log4j.appender.audit.append=true
log4j.appender.audit.layout=org.apache.log4j.PatternLayout
log4j.appender.audit.layout.ConversionPattern=%d{ISO8601} [%t] %-5p %c - %m%n
```
Thanks a lot

**Comment by gfoligna** [comment]
I have the same issue on prod servers. Even adding apache-log4j-extras to the CLASSPATH.
Running Rundeck 2.10.1.

We need a proper solution to rotate, compress and delete logs with log4j.

**Comment by pchevallereau** [comment]
Follow the link: [](https://github.com/rundeck/rundeck/issues/866#issuecomment-373430890)

**Comment by dreamblack86** [comment]
typo in the attr name:
log4j.appender.audit.MaxBackupIndex=7 
correct one:
log4j.appender.audit.maxBackupIndex=7

**Comment by jupeter** [comment]
You paste 2 same lines. 
[DailyRollingFileAppender](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/DailyRollingFileAppender.html) does not support `maxBackupIndex` parameter
But [RollingFileAppender](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/RollingFileAppender.html) does.
