### ISSUE TITLE
Upgrade to 2.10.5 cant find bundle for SCM

### ISSUE THREAD

**Issue by dpomnean** [rundeck/rundeck#3103]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.5
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: OEL 6.9
* DB Type/version: mysql? postgres? h2?.. mysql

**Expected Behavior**
Enabling SCM Export will return this error.

`Failed fetch from the repository: Loading of translation bundle failed for [org.eclipse.jgit.internal.JGitText, en_US]; Can't find bundle for base name org.eclipse.jgit.internal.JGitText, locale en_US
`

`Plugin was not enabled for SCM export: git-export: An error occurred: Failed fetch from the repository: Loading of translation bundle failed for [org.eclipse.jgit.internal.JGitText, en_US]; Can&#39;t find bundle for base name org.eclipse.jgit.internal.JGitText, locale en_US
`

**How to Reproduce**

SCM export was working fine before I upgraded our dev environment from 2.10.2 to 2.10.5. Our production environment is version 2.10.2 and SCM is working fine.

**Comment by GroovyCarrot** [comment]
I have also just encountered this issue on 2.10.6-1, however restarting rundeck resolved it

**Comment by dpomnean** [comment]
I have installed a lab test version to try a restart after installing 2.10.6 and trying an scm export. Did not work as before, and tried restarting the server. Still gave me the same issue.

**Comment by gschueler** [comment]
are there old versions of the git plugin in your `libext` directory for rundeck?

**Comment by cocoa-maemae** [comment]
The event is a little bit different, but a similar error occurred. Post the below.
https://github.com/rundeck/rundeck/issues/4205
