### ISSUE TITLE
Upgrade bcprov

### ISSUE THREAD

**Issue by chqr** [rundeck/rundeck#3107]
Issue type: Enhancement Request

Hello! We have an internal plugin that depends on a recent version Bouncy Castle. Any objections to upgrading the version of bcprov used by the jasypt-encrypt plugin to 1.59?

**Comment by gschueler** [comment]
no objection, do you want to send a PR?

**Comment by chqr** [comment]
This is in master. https://github.com/rundeck/rundeck/commit/b621c61380c2adc24abdffe1d4f40d2c475c520c#diff-3986fa61eb85029479f294b7efbd51a1

Thanks!
