### ISSUE TITLE
Rundeck monitoring

### ISSUE THREAD

**Issue by pshlykov** [rundeck/rundeck#3108]
Hi All,

What's the best way to monitor Rundeck availability?

Have noticed a few times that it gets stuck i.e. no jobs are scheduled / executed, no errors in either service.log / rundeck.log, login page is available but hangs upon trying to login never returning anything. Also no errors in syslog. The service (i.e. rundeckd status) shows as healthy. This means:

1. no errors to pick from the logs
2. no definite probing by curl (I didn't try to authenticate via j_security_check -- will try when I notice it is in limbo next time)
3. checking running processes is not helpful

The only way to notice it is a time gap between now (time of probing a rundeck health) and the laters change time of a service.log, like below:
```
[rundeck@blackbox rundeck]$ ls -lrt|tail
-rw-rw-r--. 1 rundeck rundeck      139 Jan 31 10:50 rundeck.jobs.log
-rw-rw-r--. 1 rundeck rundeck   953843 Jan 31 23:59 rundeck.executions.log.2018-01-31
-rw-rw-r--. 1 rundeck rundeck  1032562 Jan 31 23:59 rundeck.log.2018-01-31
-rw-rw-r--. 1 rundeck rundeck 29568749 Jan 31 23:59 rundeck.audit.log.2018-01-31
-rw-rw-r--. 1 rundeck rundeck  3613008 Jan 31 23:59 rundeck.access.log.2018-01-31
-rw-rw-r--. 1 rundeck rundeck   529984 Feb  1 13:17 rundeck.executions.log
-rw-rw-r--. 1 rundeck rundeck 13305860 Feb  1 13:17 service.log
-rw-rw-r--. 1 rundeck rundeck   566535 Feb  1 13:17 rundeck.log
-rw-rw-r--. 1 rundeck rundeck 14057615 Feb  1 13:18 rundeck.audit.log
-rw-rw-r--. 1 rundeck rundeck  1682423 Feb  1 17:17 rundeck.access.log
[rundeck@blackbox rundeck]$ less rundeck.access.log

```

Which is a questionable way -- you really need to know how often your jobs run.

Will be grateful for ideas!

Thanks
Pavel

**Comment by willemdh** [comment]
What version are you on? I did not experience the issues you are describing (yet).

About monitoring I'm using an Elastic stack with a Filebeat on my RUndeck server sending all the job, execution and acess logs to Elastic ingest pipeline. You could then configure a watch which triggers if no jobs have finished successfully last x time.

**Comment by pshlykov** [comment]
Hi Willem,

Thanks for the advice. We are on version 2.10.2-1.

What you use is reasonable. I will probably stick to several checks like rundeck.executions.log change time and a 'rundeckd status' output to keep the ball rolling.

Best regards,
Pavel

**Comment by dandunckelman** [comment]
@pshlykov I use Puppet to configure this [monit](https://mmonit.com/monit/documentation/monit.html#Remote-host) check:

```
check host "%{::hostname}" with address "%{::fqdn}"
  if failed
    port 4440
    protocol http
    request "/user/login"
    status = 200
    timeout 1 seconds
  then exec "/usr/bin/post-to-slack"
```

It has been just as useful as when our Rails server gets a `Connection refused` error when talking to the Rundeck API.

**Comment by pshlykov** [comment]
Thanks @dandunckelman ,

In fact, I do almost the same thing but with a few lines of the code in Python.
In our case Rundeck was suffering from the HSQL database file being too big. The login page would still  show but you wouldn't be able to login, and behind the scenes Rundeck wasn't spawning any jobs.

Initially we scheduled the custom script to send a GET request from '/api/21/system/info' endpoint. If Rundeck would hang the request times out and the script would raise an incident in Service-now. Since then we've migrated the Rundeck repo to Postgres and so far haven't seen any new issues.

The only problem with this approach is that you need to re-generate API token. I'll be adding this into the new version of the monitoring script, along with a few additional things to reflect our needs.

**Comment by venkatesh1753** [comment]
@willemdh @dandunckelman Could any one please help me on how to setup an access control policy for rundeck api token?

**Comment by niall-munnelly** [comment]
I’m neither of those people, but I might be able to help. What do you need?

**Comment by venkatesh1753** [comment]
Hi @niall-munnelly , thanks for responding...
I need to create a dynamic token which is more secure than static.
I need to setup an acl for that token, So I can restrict other applications when they are hitting api and trying to access all projects..
The application should have limit access to only that particular project..
Could you please help me how can I do this?
I appreciate your help

**Comment by niall-munnelly** [comment]
I’ll put something representative in gist for you tomorrow.

**Comment by niall-munnelly** [comment]
> Hi @niall-munnelly , thanks for responding...
> I need to create a dynamic token which is more secure than static.
> I need to setup an acl for that token, So I can restrict other applications when they are hitting api and trying to access all projects..
> The application should have limit access to only that particular project..
> Could you please help me how can I do this?
> I appreciate your help

@venkatesh1753, gist here:

https://gist.github.com/niall-munnelly/809eeb0adf69f42c591c0aca39e8ba15

I've annotated this as best I can; please review, read [Rundeck's ACL Policy documentation](https://docs.rundeck.com/docs/administration/security/authorization.html), and ask any questions you might have.
