### ISSUE TITLE
TAGs are in random order - make them to keep ordered like in node source xml. enhancement

### ISSUE THREAD

**Issue by mikador** [rundeck/rundeck#3111]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.5-1
* install type: rpm
* OS Name/version: RHEL 7.4
* DB Type/version: mysql

**Current Behavior**

under https://.../project/projectName/nodes we see
'Node' list (displayed by some tag: tag selection) 
and 
'tags' list (for each node)

those lists of tags (there are multiple tags for each node) are not consistently sorted - no asc or desc  order there.

I think the best would be that those tags list would follow the order of tags which is in source of nodes xml file.

Could that be implemented? 
It is very annoying that Rundeck displays tags in kind of random order for each node in nodes view.

**Expected Behavior**
tags list in node view keep the order of tags same as is in node source xml file.

**Comment by HectorNS** [comment]
Hi,

Any update on this? its annoying to see all the tags disordered when you have a lot of nodes\tags

Regards.

**Comment by carlosrfranco** [comment]
Still happening on v3.2.5
