### ISSUE TITLE
Job State Conditional is not failing my job

### ISSUE THREAD

**Issue by Miminoux** [rundeck/rundeck#3113]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.1-1
* install type: deb
* OS Name/version: debian 8.9
* DB Type/version: mysql

**How to Reproduce**
- Job A runs and fails (for any reason).
- Job B has a Job State Conditional step on job A : Not running and succeeded and Halt and Fail are checked.
- Run job B

**Expected Behavior**
- Job B should stop with Failed status

**Actual Behavior**
- Job B has status Succeedeed

Or maybe I misunderstood the Halt and Fail checkboxes ?

**Comment by gschueler** [comment]
can you paste your job definitions? (at least the workflow part of Job B with the job state conditional step definition?)

**Comment by Miminoux** [comment]
- description: ''
  executionEnabled: true
  group: Aaa test
  id: b5c9e43e-51b9-4874-b214-eb2397dcb7d1
  loglevel: INFO
  name: job B
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - configuration:
        condition: Equals
        executionState: Succeeded
        fail: 'true'
        halt: 'true'
        jobName: Aaa test/job A
        running: 'false'
      errorhandler:
        exec: rm
      nodeStep: false
      type: job-state-conditional
    - exec: hostname
    keepgoing: false
    strategy: node-first
  uuid: b5c9e43e-51b9-4874-b214-eb2397dcb7d1


I get the following output with status Succeeded : 

16:18:34 [thomas@rundeck.intranet.1][NORMAL] {{Job c7cd4a04-376e-422a-b64e-4d003d1c434f}} is NOT RUNNING AND previously FAILED. Expected NOT RUNNING AND 'Succeeded'
16:18:34 [thomas@rundeck.intranet.1][ERROR] {{Job c7cd4a04-376e-422a-b64e-4d003d1c434f}} is NOT RUNNING AND previously FAILED. Expected NOT RUNNING AND 'Succeeded'
16:18:34 [null@rundeck.intranet.1e][NORMAL] rm: opérande manquant
16:18:34 [null@rundeck.intranet.1e][NORMAL] Saisissez « rm --help » pour plus d'informations.
16:18:35 [null@rundeck.intranet.1e][ERROR] Result: 1
16:18:35 [null@rundeck.intranet.1e][ERROR] Failed: NonZeroResultCode: Result code was 1
16:18:35 [thomas@rundeck.intranet._][NORMAL] Execution halted (succeeded):2128316 in project aa: [Workflow result: , flow control: Halt, status: succeeded]

**Comment by Miminoux** [comment]
I've tried specifiying a customstatus (failed) and get execution all green : 

16:23:39 [thomas@rundeck.intranet. 1][NORMAL] {{Job c7cd4a04-376e-422a-b64e-4d003d1c434f}} is NOT RUNNING AND previously FAILED. Expected NOT RUNNING AND 'Succeeded'
16:23:39 [thomas@rundeck.intranet. 1][ERROR] {{Job c7cd4a04-376e-422a-b64e-4d003d1c434f}} is NOT RUNNING AND previously FAILED. Expected NOT RUNNING AND 'Succeeded'
16:23:39 [null@rundeck.intranet. 1e][NORMAL] rm: opérande manquant
16:23:39 [null@rundeck.intranet. 1e][NORMAL] Saisissez « rm --help » pour plus d'informations.
16:23:39 [null@rundeck.intranet. 1e][ERROR] Result: 1
16:23:39 [null@rundeck.intranet. 1e][ERROR] Failed: NonZeroResultCode: Result code was 1
16:23:39 [thomas@rundeck.intranet. _][NORMAL] Execution halted (succeeded):2128326 in project aa: [Workflow result: , flow control: Halt, status: failed]


And as you can see I also used an error handler making another error but nothing changes...
