### ISSUE TITLE
Add parameters to execution page

### ISSUE THREAD

**Issue by PabloLemos** [rundeck/rundeck#3116]
Is there any way to add parameters on the execution page? I am implementing a plugin for saltstack via salt-api and I need to validate different users to be able to use the execution module. I mean if it is possible to specify a dialog box via plugin.yml Workflow style

I have thought about developing some plugin ui but I am not clear how rundeck would pass those vars to the script.

**My Rundeck detail**

* Rundeck version: 2.10.5-1
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: RedHat v6.0
* DB Type/version:  files

**Comment by gschueler** [comment]
Do you mean you want to create a step plugin that asks the users for input when the user runs the job?  Right now the only way to do that is to define the plugin properties in the plugin.yaml, and then when defining the job specify something like `${option.myinput}`, and adding an option named `myinput`.  Then when the user runs the job they will be prompted for `myinput`, which will be passed to the step plugin.

**Comment by PabloLemos** [comment]
@gschueler I mean the execution tab (ad-hoc). When I create jobs, effectively, I create an input to enter the credentials but to develop a NodeExecution plugin I have not found any way to enter that credential from the execution tab.

In addition this credential should be introduced by each user when invoking the execution module.

Thanks a lot
