### ISSUE TITLE
com.dtolabs.rundeck.core.NodesetEmptyException [Again?]

### ISSUE THREAD

**Issue by xeon22** [rundeck/rundeck#3117]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.6-1
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: Centos 7.4
* DB Type/version: mysql? postgres? h2?.. postgres

**Expected Behavior**
This appears to be the same behaviour as #2942 except for the DB Type.

**How to Reproduce**

**Comment by scollector65** [comment]
same
i'm use 2.10.6
