### ISSUE TITLE
scheduler/takeover tooooo long

### ISSUE THREAD

**Issue by niphlod** [rundeck/rundeck#3120]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.5
* install type: launcher
* OS Name/version: WS2012R2
* DB Type/version: MSSQL

**Expected Behavior**
"takeover" is supposed to complete in a matter of seconds, even if the "takeovering" is done to balance the load. When it's used to rebalance scheduled executions following a cluster node shutdown, time taken starts to become a critical path to assure proper HA.
With some jobs scheduled (higher frequency 15min, execution retention 45 days) "takeovering" a project takes too long (75 secs here).
Not being a Java programmer I can't really tell where the code needs fixing, but I can see what happens in the backend.
The select launched is something similar to
```
select ....
from scheduled_execution this_ 
   left outer join 
   execution executions1_ on 
   this_.id=executions1_.scheduled_execution_id 
   where (
   this_.scheduled=1 
   or 
   (executions1_.status='scheduled' and executions1_.date_completed is null and 
           (executions1_.server_nodeuuid is null or executions1_.server_nodeuuid<>'nodeuuid')
    )
   )
   and (this_.server_nodeuuid is null or this_.server_nodeuuid<>'nodeuuid') 
   and this_.project='project_name'
```
If I do a simple count, this returns roughly 50k records in my env. Being it a "select *" the data fetched is a lot, and it's clearly the bottleneck in the method. 
Scheduled jobs in my case are just 25.
Is there a particular reason why the execution table is pulled in, and also without any temporal limits ?  
I'd expect the takeover to just switch over another node the *currently* scheduled jobs, irregardless of the history.

**How to Reproduce**
Create a project with a few jobs in it, schedule executions let's say every 30 seconds, let it run for a while and then try to takeover the project.

**Comment by niphlod** [comment]
Actually, in addition to the previously exposed problem, for every execution.id a single query is issued to check for log_file_storage_request... and it's another big piece of the elapsed time. 
This translates roughly to 50k queries for switching over a single project .... maybe some roundtrips can be avoided ?
As it is basically users must choose between "auditability" vs "availability": keeping some history "just for the sake of auditors" highly impacts the availability... and the limit is hit as soon as it takes more time to takeover than the lowest scheduled frequency of a job.

**Comment by niphlod** [comment]
is noone experiencing this ?

**Comment by tinoji** [comment]
I'm in the same situation ✋
