### ISSUE TITLE
Oracle+MSSQL DB error SqlExceptionHelper

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#3125]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: since 2.10.1 to 2.10.6
* install type: launcher, deb, rpm, war+tomcat
* OS Name/version: Linux (centos 7, debian jessie) and Windows 7
* DB Type/version: Oracle Database 12c Standard Edition Release 12.2.0.1.0 - 64bit Production

**Expected Behavior**
Do not have errors in RD logs

**How to Reproduce**
after enabling cluster mode in rundeck-config.properties:
rundeck.clusterMode.enabled=true

rundeck.log shows:
ERROR org.hibernate.engine.jdbc.spi.SqlExceptionHelper - ORA-00932: inconsistent datatypes: expected - got CLOB

**Comment by jtobard** [comment]
The cause of this error is this query on bootstrap:
```
Hibernate: select this_.id as id1_3_0_, this_.version as version2_3_0_, this_.date_created as date_created3_3_0_, this_.execution_id as execution_id4_3_0_, this_.expiration_date as expiration_date5_3_0_, this_.file_name as file_name6_3_0_, this_.file_state as file_state7_3_0_, this_.job_id as job_id8_3_0_, this_.last_updated as last_updated9_3_0_, this_.project as project10_3_0_, this_.record_name as record_name11_3_0_, this_.record_type as record_type12_3_0_, this_.server_nodeuuid as server_nodeuuid13_3_0_, this_.sha as sha14_3_0_, this_."SIZE" as SIZE15_3_0_, this_.storage_meta as storage_meta16_3_0_, this_.storage_reference as storage_reference17_3_0_, this_.storage_type as storage_type18_3_0_, this_.rduser as rduser19_3_0_, this_.uuid as uuid20_3_0_ 
from job_file_record this_ 
where this_.expiration_date<=? and this_.file_state=? and this_.server_nodeuuid=?
```

the server_nodeuuid is a CLOB field on Oracle database and trying to do a equals operation over the field.

The field can be a varchar as it is in others tables.

**Comment by emiliohh** [comment]
This is also affecting MSSQL

**Comment by jtobard** [comment]
Same error on mssql:
`ERROR SqlExceptionHelper - The data types text and nvarchar are incompatible in the equal to operator.`

**Comment by jplassnibatt** [comment]
Oracle DB 12.2.0.1.0 fix:

    alter table job_file_record add (server_nodeuuid_aux varchar2(36char));
    update job_file_record set server_nodeuuid_aux = dbms_lob.substr(server_nodeuuid,36);
    alter table job_file_record drop column server_nodeuuid;
    alter table job_file_record rename column server_nodeuuid_aux to server_nodeuuid;

this is optional to keep columns original order:

    alter table job_file_record modify (sha invisible, "SIZE" invisible, STORAGE_META invisible, STORAGE_REFERENCE invisible, STORAGE_TYPE invisible, RDUSER invisible, UUID invisible);
    alter table job_file_record modify (sha visible, "SIZE" visible, STORAGE_META visible, STORAGE_REFERENCE visible, STORAGE_TYPE visible, RDUSER visible, UUID visible);

**Comment by emiliohh** [comment]
MSSQL 2017 fix:

ALTER TABLE job_file_record ALTER COLUMN server_nodeuuid VARCHAR(36);
