### ISSUE TITLE
configuration files are overwritten when upgrade .deb package

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#3128]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.6 and olders
* install type: deb
* OS Name/version: debian jessie, ubuntu xenial
* DB Type/version: any

**Expected Behavior**
To keep config files from /etc/rundeck/ folder

**How to Reproduce**
upgrade from 2.10.5-1-GA_all.deb to 2.10.6-1-GA_all.deb will set information from framework.properties, rundeck-config.properties, etc, back as a new install.

**Comment by fgutierrezz** [comment]
Reproduced using :
PRO/Cluster.
Repositories DEB
OS Ubuntu 18

The config files are overwritten (/etc/rundeck/*) this happens using repositories (DEB) doing upgrades/downgrades. 

Tested versions
2.4.5 <> 2.4.8 <> 2.4.9 
2.4.9 > 3.1.1

**Comment by jplassnibatt** [comment]
@fgutierrezz this is not happening anymore.
Test: 3.0.26->3.1.0->3.1.1->3.1.2
and 2.11.14->3.1.2
files are not overwritter anymore.
