### ISSUE TITLE
passing data to error handler?

### ISSUE THREAD

**Issue by rb1980** [rundeck/rundeck#3134]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 
Rundeck 2.10.4-1
* install type: (rpm,deb,war,launcher?)
rpm
* OS Name/version: 
CentOS Linux release 7.3.1611
* DB Type/version: mysql? postgres? h2?..
mariadb-server-5.5.52-1.el7.x86_64

**Expected Behavior**
I want to be able to use the key/values captured in a log filter, to pass to error handler.
I verified via the "logData: true", that it is capturing the key/value successfully, I just don't know how to use it in the error handler, which apparently the "normal" syntax does not work on.
Is there another way?

**How to Reproduce**

```- description: ''
  executionEnabled: true
  id: 212c8fa8-0f30-4577-a6df-309eac913e03
  loglevel: INFO
  name: test
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - errorhandler:
        exec: echo "${data.instance_id}"
      exec: echo "instance_id=12345";exit 1
      plugins:
        LogFilter:
        - config:
            logData: 'true'
            regex: ^(instance_id)\s*=\s*(.+)$
          type: key-value-data
    keepgoing: false
    strategy: node-first
  uuid: 212c8fa8-0f30-4577-a6df-309eac913e03
```

**Comment by sjrd218** [comment]
I think this will be fixed when the fix for #4141 is merged.
