### ISSUE TITLE
Clickjacking Mitigation

### ISSUE THREAD

**Issue by tegansnyder** [rundeck/rundeck#3142]
Issue type: Security

Web Application Potentially Vulnerable to Clickjacking via Nessus scan:

The following pages do not use a clickjacking mitigation response header and contain a clickable event : - http://rundeck-local.com:4440/user/error - http://rundeck-local.com:4440/user/login Port: www (4440/tcp)

**My Rundeck detail**

* Rundeck version: Rundeck 2.6.9-1
* install type: rpm
* OS Name/version: RHEL 6.9
* DB Type/version: mysql

**Expected Behavior**

Clickjacking mitigated.

**How to Reproduce**

Run a Nessus security scan against Rundeck.

**Comment by gschueler** [comment]
Please check the latest release (3.0.13) which includes additional security headers
