### ISSUE TITLE
Problem with command RD_EXEC_COMMAND on WinRM nodes 

### ISSUE THREAD

**Issue by keyser75000** [rundeck/rundeck#3144]
**Issue type: Bug report**

Hi,

I use two plugins to manage via WinRM my Windows servers.
I noticed that my jobs, on both plugins, that use Script or ScriptFile failed with same error :
The term 'chmod' is not recognized as the name of a cmdlet, function, script file, or operable program.

It seems that rundeck Job add "chmod +x" command and a ".sh" at the end of RD_EXEC_COMMAND variable (powershell script in my case).
I use Rundeck 2.10.6, plugins rd-winrm-plugin and rundeck-winrm-plugin.
This behavior didn't happen in earlier versions (2.9.x and until 2.10.2).

I can bypass this error in file winrmexe.rb by modify a test on chmod (to delete it from command) but I did not update these plugins since. I just updated Rundeck several times. Then I realized this issue happen.

Examples of variables in log output :
`RD_EXEC_COMMAND => chmod +x c:\temp\228-5513-xxxx-restart_fusioninventory.ps1.sh`
and :
```
realm => REALM
endpoint => http://xxxx:5985/wsman
user => DOMAIN\user
pass => ********
timeout => 60
command => chmod +x c:\temp\228-5513-xxxx-restart_fusioninventory.ps1.sh
newcommand => chmod +x c:\temp\228-5513-xxxx-restart_fusioninventory.ps1.sh
```

Thanks for help (I post too an issue on rd-winrm-plugin Github but they told me it was probably a Rundeck regression).

**My Rundeck detail**

* Rundeck version: 2.10.6
* install type: deb
* OS Name/version: Linux Debian 8.10
* DB Type/version: mariadb 10.0.0.32

**Expected Behavior**
RD_EXEC_COMMAND variable build with no chmod command at the beginning and .sh at the end when .ps1 extension / powershell "shell" is seleted.

**How to Reproduce**
Rundeck 2.10.6 with one of those plugins : rd-winrm-plugin or rundeck-winrm-plugin.
Create a Script or ScriptFile Job for a Windows Server. No problem with a remote command job.

**Comment by rokhmanov** [comment]
Reproducible on Rundeck 2.10.6-1. Didn't checked the later versions. The "Execute inline script" functionality over WinRM  is pretty much broken. What is the severity of this Issue?

**Comment by keyser75000** [comment]
Maximum severity I'd say : None of my jobs can run.
I had to modify plugin rd-winrm to keep my jobs running.
Other plugin overthere-winrm still can't run as I can't modify it (java code).

**Comment by ltamaster** [comment]
Hi @keyser75000 

Can you share your node definition?
I understand that Rundeck doesn't add the `chmod +x` when the node set the osFamily  attribute with the `windows` value (please take a look [here](https://github.com/rundeck/rundeck/blob/d352a0d6cc242a9a7b5eb6d13cfdb1dc8bf5fe93/core/src/main/java/com/dtolabs/rundeck/core/execution/workflow/steps/node/impl/DefaultScriptFileNodeStepUtils.java#L283)), ex:

```    
<node name="WINDOWS-VIRTUAL" description="Windows Server 2012" tags="" hostname="192.168.0.5" osArch="amd64" 
  osName="Windows Server 2012 R2" osFamily="windows" osVersion="6.3" username="rundeckuser"/>
```

If I removed the `osFamily="windows"` I got the behavior that you described.

**Comment by keyser75000** [comment]
Hi @ltamaster

I used until now "osFamily"="MSWin32".
I changed it with "windows" and it works.
It's OK for me. Thanks a lot !!!
I have obviously missed something since the update to 2.10.x ...

**Comment by mezamoe** [comment]
maybe osFamily should be declared as a "required" entry ? I just ran into the same issue for not having that in my resource file
