### ISSUE TITLE
Report step OK

### ISSUE THREAD

**Issue by TJarriault** [rundeck/rundeck#3147]
[Issue]([url](url
![erreur-schedule](https://user-images.githubusercontent.com/7701382/36550658-146e3da2-17f6-11e8-9b1d-9cc32434feee.PNG)
)) type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 7.6.2
* install type: (rpm,deb,war,launcher?)
* OS Name/version: ubuntu
* DB Type/version: mysql? postgres? h2?..: mysql

**Expected Behavior**
In a principal job report which one execute 2 parallel job, when the principal job is "Failed", the report is"OK" even the JobA is failed. 
To reproduce this follow this steps:
    Create jobA that run any script, e.g. "ls /; sleep 1m; exit 1" (FAILED)
    Create jobB that run any script, e.g. "ls /; sleep 2m; " (OK)

The report for the principal job return OK even is "Failed", why ?

**Comment by dpomnean** [comment]
In your jobA you are adding an exit 1, which will return a "failure".

https://stackoverflow.com/questions/20965762/meaning-of-exit-status-1-returned-by-linux-command
