### ISSUE TITLE
Enhancement request: Retry failed steps

### ISSUE THREAD

**Issue by dpomnean** [rundeck/rundeck#3153]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.2
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: OEL 6.9
* DB Type/version: mysql? postgres? h2?.. MySQL

There are options to retry an entire job if it fails. Would it be possible to add an option into the step override "If a node fails" to retry running the step and having the same options if a job failed? Ex: Number of times to retry, Retry Delay.

We have a case where a step may fail, because of a networking issue, but if ran again it will run successfully.

**Comment by Aladdin4815162342** [comment]
Any update for this feature?

**Comment by Daryes** [comment]
*Disguised shameless bump*

This feature would be very helpful. 
For example, having a single job for importing multiples files in distinct steps. 
The current way Rundeck is handling the retry requires to separate the steps in dedicated jobs. 
Otherwise, any error occurring in a step importing data from a file won't be easy to recover if it doesn't allow to be executed again after the file was consumed.

**Comment by skycolangelom** [comment]
+1

**Comment by e1201141** [comment]
Yes, please this is quite annoying and it will be really helpful when you manage long inventories

**Comment by brucegivens** [comment]
+1

**Comment by Romainj1** [comment]
+1

**Comment by remifrazierucsf** [comment]
See also #4049

**Comment by OdaDaisuke** [comment]
+1

**Comment by amutor** [comment]
Still very much needed enhancement in current version 3.2.1. Especially when runbooks start growing in size and numerous phases are added in, we need to be able to simply resume from failed step, after the issue has been corrected, we do not want to rerun the whole runbook.

**Comment by moreqpi** [comment]
+1

**Comment by gschueler** [comment]
This feature is available in Rundeck Enterprise https://docs.rundeck.com/docs/manual/execution-lifecycle/job-resume.html
