### ISSUE TITLE
Can't abort a job, message is "Unable to modify the execution"

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#3155]
Issue type: Bug report

The message appears if for some reason Rundeck has trouble performing a write to the DB on the specified Execution row, and causes the abort to fail before interrupting the process.

The interruption should happen regardless of the outcome of the DB write.

**My Rundeck detail**

* Rundeck version: 2.10.4

**Expected Behavior**

Aborting an execution should cause the execution to stop even if the DB write does not work.

**How to Reproduce**

The message appears if for some reason Rundeck has trouble performing a write to the DB on the specified Execution row.

**Comment by happicamper** [comment]
@gschueler sorry to comment on here, but I still experience this issue on Rundeck-3.0.9.

**Comment by igal-s** [comment]
@gschueler I also get the same error even with the latest snapshot of 3.0.14

**Comment by happicamper** [comment]
@igal-s any luck of having a workaround?

**Comment by PraveenPusarla** [comment]
@igal-s Did u get any workaround or solution for this? Even i am experiencing the same issue.

**Comment by camaer** [comment]
Same issue here
