### ISSUE TITLE
POST api/21/job/[id]/schedule/enable is returning apiFlipScheduleEnabled.gsp not found

### ISSUE THREAD

**Issue by guice** [rundeck/rundeck#3161]
Issue type: Bug report

POST call to `schedule/enable` (disable), `execution/enable` (disable) is returning Java 404: 
* `HTTP/1.1 404 "/WEB-INF/grails-app/views/scheduledExecution/apiFlipScheduleEnabled.gsp" not found.` (apiFlipExecutionEnabled.gsp for `execution/` calls)

(from HTTP Headers)

URL from your docs: http://rundeck.org/2.10.6/api/index.html#enable-scheduling-for-a-job

Inside the service.log:

* 2018-02-28 15:34:26.912:INFO:/:qtp1452126962-65: GroovyPagesServlet:  "/WEB-INF/grails-app/views/scheduledExecution/apiFlipScheduleEnabled.gsp" not found

I'm running a complete fresh install of Rundesk. Literally just installed it today from the RPM repo.

(I asked this on #irc, but no response. Asked twice)

**My Rundeck detail**

* Rundeck version: 2.10.6-1
* install type: (rpm,deb,war,launcher?)  rpm
* OS Name/version: Oracle Linux 6  
* DB Type/version:   mysql

**Expected Behavior**
API POST /api/21/job/dff23c89-c96d-4a7d-91c7-801e2d9cccae/schedule/enable HTTP/1.1
Content-Type & Accept: application/json

Should return a success or error. I don't know what the real response is supposed to be. I'm using PAW to identify that.

**How to Reproduce**

* A POST to /api/21/job/dff23c89-c96d-4a7d-91c7-801e2d9cccae/schedule/enable HTTP/1.1
* Returning: HTTP/1.1 404 "/WEB-INF/grails-app/views/scheduledExecution/apiFlipScheduleEnabled.gsp" not found.

**Comment by guice** [comment]
A quick Note: turns out the calls _are_ working, but the returns are not... I need the returns for API calls.

I can verify execution/disable, enable and schedule/enable, disable are actually toggling the schedule and execution.

**Comment by gschueler** [comment]
any errors in the rundeck service log?

**Comment by guice** [comment]
Yes, I put it in the ticket:
* 2018-02-28 15:34:26.912:INFO:/:qtp1452126962-65: GroovyPagesServlet: "/WEB-INF/grails-app/views/scheduledExecution/apiFlipScheduleEnabled.gsp" not found

**Comment by gschueler** [comment]
sorry, i meant any other errors

**Comment by guice** [comment]
No other errors. I've appended the full output from a successful toggle. The toggle is indeed working; however, the return is failing, which breaks APIs.

**Comment by gschueler** [comment]
can you try doing it via the `rd` tool? (although note i just discovered this bug: <https://github.com/rundeck/rundeck-cli/issues/147> )

**Comment by gschueler** [comment]
you said " I'm using PAW", what is that?

**Comment by guice** [comment]
PAW is a RestAPI client for MacOS (https://paw.cloud/). I'm building an PHP API Client to communicate to a Rundeck instance. I'm hitting all the APIs, not using any CLI attributes.

Note: the API *is* successfully enabling and disabling the correct attributes of the job. It appears only the return view is broken/missing.

**Comment by gschueler** [comment]
Ok I think I reproduced the error, by introducing a typo in the `Accept:` header:

    Accept: application/jsonzzz

This results in the action being performed correctly, but with the response `404  "/WEB-INF/grails-app/views/scheduledExecution/apiFlipScheduleEnabled.gsp" not found.`

The response is defined for application/xml and application/json, but apparently anything else is not handled correctly. Maybe double-check your input values?

**Comment by guice** [comment]
Oh, you're right. Turns out my Accept: was set to `application/yaml`. Doh. Now I feel sheepish. 

(to my defense, the switching from yaml, xml, json is pretty confusing; there isn't a good consistency between support for xml, yaml, and json.)

**Comment by guice** [comment]
Btw, I get a similar 404 Error when attempting to export Jobs: `project/[name]/jobs/export` while using `Accept: application/json`

This is one of the cases where `json` is not accepted, but `yaml` is. It's the exact opposite of the use case of this ticket (didn't accept `yaml` but accepted `json`).
