### ISSUE TITLE
POST /api/21/project/[project]/resources Does nothing, returns 302 Found

### ISSUE THREAD

**Issue by guice** [rundeck/rundeck#3162]
Issue type: Bug report

Per the docs:
http://rundeck.org/2.10.6/api/index.html#updating-and-listing-resources-for-a-project

> **Updating and Listing Resources for a Project**
>
> Update or retrieve the Resources for a project. A GET request returns the resources for the project, and a POST request will update the resources. (API version 2 required.)

However, `POST /api/21/project/test-project/resources HTTP/1.1` returns `HTTP/1.1 302 Found` and does nothing.

GET successfully retrieves a list, returning 200. POST is what's failing.

Headers: 
```
POST /api/21/project/test-project/resources HTTP/1.1
X-Rundeck-Auth-Token: uXPHkGXw4LOUJQk707KOjcydKGjAQrGg
Content-Type: application/json
Accept: application/json
[...]
```

**My Rundeck detail**

* Rundeck version: 2.10.6-1
* install type: (rpm,deb,war,launcher?)  rpm
* OS Name/version: Oracle Linux 6  
* DB Type/version:   mysql

**Expected Behavior**
`POST /api/21/project/test-project/resources HTTP/1.1`  Should return 201 or 200 for successful creating or updating of a node.

**How to Reproduce**

* POST /api/21/project/test-project/resources 
* (doesn't even matter the body content. It's all returning 302)

**Server Logs**

Here is a `tail -f *.log`:
```
==> rundeck.access.log <==
[2018-02-28 16:29:32,661] "POST /api/21/project/test-project/resources" 192.168.200.1 https admin token 14 ? [] (Paw/3.1.5 (Macintosh; OS X/10.13.3) GCDHTTPRequest)

==> rundeck.api.log <==
[2018-02-28 16:29:32,662] 192.168.200.1 https admin token 16 test-project "POST /api/21/project/test-project/resources" (Paw/3.1.5 (Macintosh; OS X/10.13.3) GCDHTTPRequest)
```

That is literally it. There is nothing within an other log files (including server.log).

**Comment by gschueler** [comment]
That text is out of date, and should be removed.  See the [Changes](http://rundeck.org/2.10.6/api/index.html#changes) section, the POST to that endpoint has been removed.

**Comment by guice** [comment]
Oh boo. Hopefully you'll add the ability to create notes via API at some point. Guess we'll work on a workaround for this.

Thanks,

**Comment by gschueler** [comment]
sorry, the (forthcoming) replacement makes use of the new "Writable" model source feature.  There File resource model source can be set to "writeable", but we don't have a new endpoint to enable that via API yet.

**Comment by gschueler** [comment]
added an enhancement request for that: https://github.com/rundeck/rundeck/issues/3163
