### ISSUE TITLE
Build fails, gradlew process stucked in an infinit loop at Downloading grails-2.5.6

### ISSUE THREAD

**Issue by sum32** [rundeck/rundeck#3170]
Bug

**My Rundeck detail**
17:32:10.051 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting OS memory status event {Total: 4140408832, Free: 1313771520}
17:32:10.052 [DEBUG] [org.gradle.launcher.daemon.server.health.LowMemoryDaemonExpirationStrategy] Received memory status update: {Total: 4140408832, Free: 1313771520}
17:32:10.052 [DEBUG] [org.gradle.process.internal.health.memory.MemoryManager] Emitting JVM memory status event {Maximum: 954728448, Committed: 491257856}
17:32:11.625 [DEBUG] [org.gradle.launcher.daemon.server.Daemon] DaemonExpirationPeriodicCheck running
17:32:11.625 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
17:32:11.626 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
17:32:11.626 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
17:32:11.626 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
17:32:11.626 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
17:32:11.626 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
17:32:12.479 [INFO] [org.gradle.api.internal.project.ant.AntLoggingAdapter] [ant:get] ....................................................

* Rundeck version: b51d98bfa3af16e2cbb9b4a6b41e22eaafd10d11
* install type: Build process
* OS Name/version: centos7

**Expected Behavior**
Sucessfull build

**How to Reproduce**
Dockerfile:
```
FROM centos:7
RUN yum -y update && yum -y install git
RUN git clone https://github.com/rundeck/rundeck.git
RUN yum -y install bash-completion bash-completion-extras
RUN yum -y install java-1.8.0-openjdk-devel
RUN export JAVA_HOME="/usr/lib/jvm/java" && cd /rundeck && ./gradlew --debug build
ENTRYPOINT ["/bin/ls"]
```

> docker build -t test:latest .

I have about 2G free mem when the process is stuck. I tried a lot of other JAVA_HOME places like /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.161-0.b14.el7_4.x86_64/jre.

I managed to build using other environments but I would like to use centos7. Are there any other requirements not listed in the README (Java installed and setting JAVA_HOME, I do not need packageing so make is not needed?)?

**Comment by RameshbabuJaga** [comment]
Me too facing the same issue. Any Solution for this.

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
