### ISSUE TITLE
Job Option - Allowed Values - with comma

### ISSUE THREAD

**Issue by djeeg** [rundeck/rundeck#3172]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.6-1 
* install type: (rpm,deb,war,launcher?) jordan/docker
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?.. mysql

**Expected Behavior**

Trying to have a single option that has commas in the actual value

eg
`destination=/var/backups,source=mysql,type=volume,volume-driver=cloudstor:azure,volume-opt=share=mysql`

Have tried no quotes, double quotes, single quotes

**How to Reproduce**

Use the above option and rundeck will parse as 5 seperate option values, when I would like a single value

Deliminator seems to only apply for joining multi-select options
https://github.com/rundeck/rundeck/issues/1427

**Comment by gschueler** [comment]
what is your job definition?

**Comment by djeeg** [comment]
This was through the Web UI.
I was hoping to get the whole string (with commas) as a single value


```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option enforcedvalues='true' name='BACKUP_MOUNT' required='true' values='"destination=/var/backups,source=backup,type=volume,volume-driver=cloudstor:azure,volume-opt=share=backup"' />
      </options>
    </context>
```

**Comment by djeeg** [comment]
I think this is the place, looks like simple comma (without escaping) is supported.

https://github.com/rundeck/rundeck/blob/063e6bf97b78960cce9b47866e0557b2b556413a/rundeckapp/grails-app/utils/rundeck/codecs/JobsXMLCodec.groovy#L218

**Comment by JesusRo** [comment]
Most likely we would need new option to accomplish such cases, kind of a delimiter chooser.
Something like this:
![image](https://user-images.githubusercontent.com/12175711/38725314-44294f18-3f07-11e8-8220-c5620bfa8a74.png)

So the code could end up like: ```optm.values = optm.values.split(optm.delimiter) as List``` instead the harcoded comma.

In this way, you could always chose another char to delimit your options list and avoid interferences

**Comment by bbomgardner** [comment]
Ran into this today and had to come up with a work around. Would be a nice addition.
