### ISSUE TITLE
Job Library - Unable to find documentation on enabling/usage

### ISSUE THREAD

**Issue by JustinAddams** [rundeck/rundeck#3174]
Issue type: Bug report
**My Rundeck detail**

* Rundeck version: 2.10.1-1
* install type: RPM
* OS Name/version: CentOS 7
* DB Type/version: MSSQL

**Expected Behavior**
As per https://trello.com/c/jtFcbflm Job Libraries were apparently released under version 2.9 but I am unable to find them anywhere in the documentation or GUI.

Is the Trello board incorrect or am I missing something obvious?

**Comment by JustRiedy** [comment]
*bump* I assume Trello is incorrect I just need a confirmation so I can ensure I'm not missing something stupid.

**Comment by ahonor** [comment]
@JustRiedy their was a few enhancements that allow jobs to be called from other projects. We are also adding some additional features for child jobs in 2.11.0. You are correct the docs need to be updated.

**Comment by JustRiedy** [comment]
Ah ok, not quite a job library but definitely useful I could create a non functioning project soley to store jobs.
Thanks for the information.
