### ISSUE TITLE
Rename Projects

### ISSUE THREAD

**Issue by guice** [rundeck/rundeck#3177]
Enhancement Request

Some way to rename projects. Think typos, projects changing scope/names, etc. 

Rundeck Version: 2.10.7

**Comment by ahonor** [comment]
@guice It does not rename the project per se but this new feature may help as a work around. See this PR allowing a separate "label" for a project: https://github.com/rundeck/rundeck/pull/3253

**Comment by pdppdp** [comment]
Please!  A way to rename would be a useful feature for all the reasons mentioed by original requestor.

A label is a fine enhancement, but does not meet the need.  Cloning the project does not either.  Similarly, exporting and importing all the jobs is a N-hour effort for a 5-minute task, and likewise does not meet the need.

**Comment by frachel** [comment]
Voting for this as well. Evaluating this for production use and couldn't believe I couldn't do something as simple as renaming a project.

**Comment by cukal** [comment]
Renaming projects was really easy when starting  the h2 database in server mode: 
`java -cp h2*.jar org.h2.tools.Server -webAllowOthers` and connect to `http://<your ip>:8082` using the connection string: `jdbc:h2:/var/lib/rundeck/data/rundeckdb`
Grab h2*.jar from [http://www.h2database.com/html/download.html](http://www.h2database.com/html/download.html)

**Comment by HowardHong** [comment]
+1

**Comment by tshird** [comment]
+1

**Comment by ZClifton-21** [comment]
+1

**Comment by noahlz** [comment]
Please, my RunDeck son, it's very project name typo

**Comment by dekiesel** [comment]
+1

**Comment by Mapel88** [comment]
+1
