### ISSUE TITLE
Possibility to use variable/option Job Name and Group Path in Job Rereference

### ISSUE THREAD

**Issue by mhaluska** [rundeck/rundeck#3184]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10.7
* install type: deb
* OS Name/version: Debian 8.10 64bit
* DB Type/version: mysql

**Expected Behavior**
1) In main job define option jobname and path
2) In main job define step with Job Reference and as Job Name put ${option.jobname}, as Group Path put ${option.path}
3) call the main job thru GUI/API with options above (for example jobname=Job01 and path=Path01)
4) referenced job is called from main job: Job [${option.path}/${option.jobname}] (in this example Job [Path01/Job01])

I tried all option calling possibilities, @option.something@, $RD_OPTION_SOMETHING, ${option.something}, but it's not propagated to Job Reference:
Job [${option.path}/${option.jobname}] not found,...

**Why?**
I'm currently integrating Rundeck with Zabbix and helpdesk tool. This option possibility allow me to have just one main (wrapper) job definition with all required variable manipulation and definition and calling simple specific job according to trigger name only with required actions on endpoint.

**Comment by mhaluska** [comment]
3 months and no response... maybe not so easy, so also uuid option would be fine.
anyway, also would be fine to choose job from different project using option.

**Comment by sbrech** [comment]
same problem for me, it would be cool to use a variable as 'Job Name'. Currenty I trigger the selected Job with a 'Script Step' which triggers the Rundeck REST API.

**Comment by mhaluska** [comment]
@sbrech: let me know about your integration, I'm now trying use rabbitmq for job distribution, maybe I can help. marek.haluska <at> gmail.com
