### ISSUE TITLE
resources.xml not created

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#3185]
Issue type: Bug report/Enhancement Request

My Rundeck detail
After enabling DB to use Project configuration Storage at rundecl-config.properties file, resources.xml is not beeing created with a new project creation.

****

* Rundeck version: all newer versions
* install type: all
* OS Name/version: any 
* DB Type/version: any

**Expected Behavior**
resources.xml file should be created with localhost node

**How to Reproduce**
-add this line to rundeck-config.properties
rundeck.projectsStorageType=db
-create a new project and save

**Comment by JustRiedy** [comment]
Interesting, I've been using DB since day one and haven't had any issues with node file creation.
Using both XML and now JSON.

I'd recommend looking through the logs: http://rundeck.org/docs/administration/logging.html
Rundeck is super verbose and great at telling you where it failed and it may shed some light on the failure.

**Comment by robinwaffles** [comment]
I faced the same problem.
I noticed that a setup **without** `projectsStorageType=db` doesn't create the project folder and `resources.xml`.

Within the configuration form in the web UI you see:
```
project.description=aproject
project.disable.executions=false
project.disable.schedule=false
project.gui.motd.display=projectList,projectHome
project.gui.readme.display=projectList,projectHome
project.jobs.gui.groupExpandLevel=-1
project.label=aproject
project.name=aproject
project.nodeCache.delay=30
project.nodeCache.enabled=true
service.FileCopier.default.provider=stub
service.NodeExecutor.default.provider=stub
```
What is missing from a setup without `rundeck.projectsStorageType=db` is:
```
resources.source.1.config.file=/var/rundeck/projects/aproject/etc/resources.xml
resources.source.1.config.generateFileAutomatically=true
resources.source.1.config.includeServerNode=true
resources.source.1.type=file
```

**Comment by exavieracemunar** [comment]
It worked. Thanks guys :).

**Comment by sudheer5561** [comment]
@exavieracemunar , can you please how it got fixed. When I create a project, I don't see resources.xml file under /var/rundeck/projects/Project1/etc ( I only see project.properties file ). - thanks

**Comment by exavieracemunar** [comment]
@sudheer5561  just paste the missing configuration on the rundeck. Base on @robinwaffles solution. 

Try to restart the rundeck after pasting these

resources.source.1.config.file=/var/rundeck/projects/aproject/etc/resources.xml
resources.source.1.config.generateFileAutomatically=true
resources.source.1.config.includeServerNode=true
resources.source.1.type=file

Inform me there's a problem or if it works.

**Comment by sudheer5561** [comment]
@exavieracemunar , sorry no luck even after pasting those properties.

I just see project.properties is created for etc folder. 

[root@rundeck-server etc]# pwd
/var/rundeck/projects/card/etc
[root@rundeck-server etc]# ls -lrt
total 4
-rw-rw-r--. 1 rundeck rundeck 647 Sep 24 16:23 project.properties

**Comment by SqlAdmin** [comment]
Im using Rundeck 3.0.6-20180917 on Centos7. Im also facing the same issue even after added these lines.

**Comment by falloutphil** [comment]
> 
> 
> Im using Rundeck 3.0.6-20180917 on Centos7. Im also facing the same issue even after added these lines.
> 
> I fixed it by just setting the file manually.
> 
> ```
> touch resouces.xml
> 
> vi resources.xml
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <project>
> <node name="replica02"  tags="mysql" hostname="10.0.0.1" osArch="amd64" osFamily="unix" osName="Linux" osVersion="4.9.0-2-amd64" username="rundeck"/>
> </project>
> ```
> 
> Then set the permission.
> `chown rundeck:rundeck resources.xml`

I have just seen the same thing, but I think it's a change to the setup, rather than a bug.  I had to go to Project Settings -> Edit Nodes -> Configure Nodes -> Add Source -> File, and then fill in:

Format: resourcexml 
File Path: /var/rundeck/projects/<proj_name>/etc/resources.xml 
Generate: Yes 
Include Server Node: Yes 
Require File Exists: Yes 

Then the resources.xml was created.

It seems there is no longer a requirement to nest it under /var/rundeck/projects/<proj_name>/etc?

**Comment by ahonor** [comment]
@falloutphil yes, that is correct. It's a change to the default project setup to use this new "Local" plugin (not the original File source).
