### ISSUE TITLE
Reload rundeck configs without restarting the whole process

### ISSUE THREAD

**Issue by Slm0n87** [rundeck/rundeck#3193]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.7.1-1
* install type: deb
* OS Name/version: debian jessie
* DB Type/version: mysql

**Expected Behavior**
Add a possibility to reload the rundeck configuration.
After changing the aclpolicy I would like to enable this configuration. Currently I have to restart the whole rundeck process and lose all executing jobs.
Perfect would be a reload option via UNIX signals like SIGUSR1, which can be triggered by an "reload" option within the start script.
But after Java apps usually ignore UNIX singnals you could solve this issue by implementing a config cache which reloads the config regularly.

**How to Reproduce**
Change the aclpolicy -> no possibility to take this config active without restarting the whole process.

**Comment by brandonros** [comment]
This might be out of date. As far as I know, if you edit `rundeck/etc/admin.aclpolicy`for example... the rundeck daemon has some kind of file watcher that automatically reloads the configuration without any intervention.

**Comment by Slm0n87** [comment]
Tested again on: Rundeck 2.10.3-1  
After changing /etc/rundeck/SomeThing.aclpolicy the change was active without restarting the rundeck process whithin the current user session :+1: 
After some more tests, it seems like the config get reloaded after about 30 seconds.  
May you can put some references from the code into this issue, but the issue itself can be closed.

Thanks for the information and the implementation.
