### ISSUE TITLE
Script plugin doesn't receive RD_ variables

### ISSUE THREAD

**Issue by JesusRo** [rundeck/rundeck#3210]
Issue type: Bug

**My Rundeck detail**

* Rundeck version: 2.10.0-1 cafe mocha teal glass 2017-10-16 
* install type: launcher
* OS Name/version: SLES 11
* DB Type/version: mysql

**Expected Behavior**
Based on https://www.rundeck.com/blog/great-user-experience-step-plugins
Make a plugin that using RD_CONFIG_* enviroment variables run an sql command.
RD_CONFIG_DRYRUN should be true/false
RD_CONFIG_SQL_SCRIPT should have content set up on job step
RD_CONFIG_DATABASE_PASSWORD should have password extracted from key storage

**Misbehaviour suffered**
There are no RD_CONFIG_* variables during script runtime so it cannot do the job.
Tryied to echo any one but no luck, also listed all availables and noone starts with RD_

**How to Reproduce**
Using attached plugin
[mysql-execute-step.zip](https://github.com/rundeck/rundeck/files/1837562/mysql-execute-step.zip)

**Comment by ahonor** [comment]
@JesusRo You should be able to see those env vars. Try this at the top of the plugin script to see the available env vars:
```
env | grep RD_ | sort
```

**Comment by JesusRo** [comment]
@ahonor thanks for replying
I tried 
![echo env vars](https://user-images.githubusercontent.com/12175711/37781197-88d1b6f0-2df0-11e8-88f0-1468fea89a8d.png)
but no luck
![result](https://user-images.githubusercontent.com/12175711/37781196-88ab8c78-2df0-11e8-967d-93b906dfe593.png)

I also tried to list all env vars but nothing (like in the zip attached)
No idea what's happening with this. 
I think I will bring up new instance on a lab to test the plugin, just to ensurte that the issue is actually at my installation.

**Comment by plambert** [comment]
Many default installations of the OpenSSH server do not pass environment variables from the client to the server.  Adding `AcceptEnv RD_*` to `/etc/ssh/sshd_config` on the target nodes will allow them to be passed without allowing non-Rundeck variables (which can have unexpected consequences).

If that's not an option, either pass the options you need via command line arguments, or via `@option.name@` substitution.

**Comment by ahonor** [comment]
Agreed, it is probably the remote sshd config that needs to accept RD_ environment variables.
If I run the plugin locally on the rundeck server, I see these env vars which you would also expect:
```
RD_CONFIG_DATABASE_HOST=dbhost
RD_CONFIG_DATABASE_NAME=dbname
RD_CONFIG_DATABASE_PASSWORD=mypass
RD_CONFIG_DATABASE_USERNAME=username
RD_CONFIG_DRYRUN=false
RD_CONFIG_SQL_SCRIPT=CREATE TABLE employees (
RD_JOB_EXECID=5856
RD_JOB_EXECUTIONTYPE=user
RD_JOB_ID=44b996d1-7b60-48bd-af89-32ba85674a46
RD_JOB_LOGLEVEL=INFO
RD_JOB_NAME=test
RD_JOB_PROJECT=fun
RD_JOB_RETRYATTEMPT=0
RD_JOB_SERVERURL=http://rundeck.local:4440/
RD_JOB_SERVERUUID=431a36b4-9866-4667-8eb8-090457dc77a9
RD_JOB_SUCCESSONEMPTYNODEFILTER=false
RD_JOB_THREADCOUNT=1
RD_JOB_URL=http://rundeck.local:4440/project/fun/execution/follow/5856
RD_JOB_USERNAME=admin
RD_JOB_USER_NAME=admin
RD_JOB_WASRETRY=false
RD_NODE_DESCRIPTION=Rundeck server node
RD_NODE_HOSTNAME=rundeck.local
RD_NODE_NAME=rundeck.local
RD_NODE_OS_ARCH=x86_64
RD_NODE_OS_FAMILY=unix
RD_NODE_OS_NAME=Mac OS X
RD_NODE_OS_VERSION=10.12.4
RD_NODE_TAGS=
RD_NODE_USERNAME=alexh
```

**Comment by JesusRo** [comment]
Hi guys,
Sorry for the late response, I had some rest ;)
You hitted the point, I've changed job to execute locally instead to dispatch to nodes and... everything's working fine.
So the issue is in fact at ssh configuration not related with Rundeck.

Thanks a lot for your help.
