### ISSUE TITLE
sh: del: command not found 

### ISSUE THREAD

**Issue by bugcy013** [rundeck/rundeck#3217]
Issue Type: Bug 

Hi Guys,

We are having some issue with script execution in windows node using OpenSSH.

resources.xml
```
<node name="dvteam@10.10.1.181" description="Microsoft Windows Server 2008 R2 Standard" tags="" hostname="10.10.1.181" osArch="x86_64" osFamily="windows" osName="Microsoft Windows Server 2008 R2 Standard" osVersion="Microsoft Windows Server 2008 R2 Standard" username="dvteam" file-copy-destination-dir="C:/\Users/\dvteam/\temp\/"/>
```

We are able to execute the local-script file, after the script execution. we are getting this error.
```
/bin/sh: del: command not found
```
> Note Have verified the file-copy-destination-dir location. I can see the batch file.

```
C:\Program Files\OpenSSH\home\dvteam\temp>ls -ltr
total 1
-rwx------+ 1 dvteam Domain Users 44 Mar 23 16:54 35-91-dvteam_10.10.1.181-script.bat

```

look like similar to #812 I am not sure what is the fix went in. ?

**My Rundeck detail**

* Rundeck version: 2.10.6-1 
* install type: launcher
* OS Name/version: CentOS-7
* DB Type/version: MySQL

**Comment by fgutierrezz** [comment]
If you are using osFamily="windows" it will try to execute windows commands in the remote host, If you want to connect to SSH in windows, try using osFamily="unix"

**Comment by fdevans** [comment]
If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
