### ISSUE TITLE
Accidentaly deleted all my jobs with (badly used bulk delete...)

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#3222]
Hi,

I'm on a 2.10.0-1 RPM Rundeck RPM install.

I don't know how, I wanted to clean some useless jobs on my sandbox and I deleted all my Rundeck jobs...

Do I have a chance to recover them ? (I have no scheduled backup nor project exports :-( )

Many thanks for your help

Best regards
Jérôme

**Comment by swtch1** [comment]
Hey Jerome,

The job definitions are stored in the storage table in the database (at least in our implementation which is using a third party database).  What database are you using?  If you've migrated off of the original HSQLDB you may have a chance to recover from the binary log (see below for a reference to binary log on MySQL) or similar methods for other databases.  If you're on the defaults you may not be so lucky.  I would strongly suggest setting up some backups for the future.

https://stackoverflow.com/questions/6924823/how-to-recover-just-deleted-rows-in-mysql

**Comment by jerome83136** [comment]
Hi,
Yes I'm using the standard MySQL database.
I will try the way you suggest to recover.

Many thanks for your help
Best regards
Jérôme
