### ISSUE TITLE
Running a workflow job with the option "If node set empty" (PR 2456) fails

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#3232]
Hi,

I'm using Rundeck v 2.10.8-1 on Centos 7.

I don't know if this is a bug or if I am the bug :-)

My setup is:

- 2 jobs
-- test_male with node filters pointing to male nodes (running a remote command "hostname")
-- test_female with node filters pointing to female nodes (running a remote command "hostname")

Run #1:
- running the job test_female --> OK (it displays the result of hostname command on each female node)
- running the job test_male --> OK (it displays the result of hostname command on each male node)

Run#2:
- Setting option "If node set empty: continue execution" on both jobs
- Changing the filter on the job "test_female" so that it wont match any node
- running the job test_female --> OK (it displays nothing because it matches 0 node but the state is success)
- running the job test_male --> OK (it displays the result of hostname command on each male node)

Run#3:
- Creating a test_all job wich executes locally
- This job contains 2 workflow steps: the test_female and and test_male jobs
- Running the job test_all fails with a "No matched nodes" error (see attached file for details)

I don't know if what I'm doing is correct.
I would like the "test_all" job to not fail, even if any of the workflow step has no target node, because I have set the "If node set empty: continue execution" option.
Am I  right ?

Many thanks for your help

Best regards
Jérôme

![test_all_result](https://user-images.githubusercontent.com/5392480/38020435-7e64af68-327a-11e8-8ae1-152aeca10d89.png)

**Comment by jtobard** [comment]
Hi @jerome83136 this is why the message has changed to "Continue execution", the workflow continues on an empty node but there's no success code on exit because no job has run on the workflow, so it's a failure.

**Comment by jerome83136** [comment]
Hi,

Thank you for answering so fast.

Following your reply; I did install an error handler with a remote command which does this:
if [[ ${result.reason} != "NoMatchedNodes" ]]; then exit 1; fi
So that only when the concerned job fails because there is no node for it to run on; the error handler allows the workflow to continue

Do you think this is a viable solution ? Maybe is there a better solution based on a Rundeck feature I'm not aware of ?

Many thanks for your help

Best regards
Jérôme

**Comment by bluesliverx** [comment]
Just wanted to note that @jerome83136's answer resolved my issues completely with this as well.

**Comment by fdevans** [comment]
Let us know if this is still an issue on current Rundeck Versions by opening a new issue.  Thanks @jerome83136 for providing a solution.
