### ISSUE TITLE
Token visible by all roles.

### ISSUE THREAD

**Issue by wreyes94** [rundeck/rundeck#3245]
Issue type: Bug report

Rundeck version: 2.10.5-1
install type: rpm
DB type: MariaDb

**Expected Behavior**
Hello, not sure if this a bug or not but on the profile page, you can create api tokens. Currently, every person that logs into our Rundeck box can see everyone's tokens even if they are not members of the same roles. Is this something being worked on? Here is our ACL policy:
description: application access for Rundeck Admin Group
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      allow: [create]
    - equals:
        kind: system
      allow: [read,enable_executions,disable_executions,admin]
    - equals:
        kind: system_acl
      allow: [read]
    - equals:
        kind: user
      allow: [admin]
    - equals:
        kind: apitoken
      allow: [generate_user_token]
  project:
    - match:
        name: 'g01217960.*'
      allow: [read,import,export,configure,delete,promote,admin]
  project_acl:
    - match:
        name: 'g01217960.*'
      allow: [read,create,update,delete,admin]
  storage:
    - allow: [read,create,update,delete]
      match:
        path: '^(keys|keys/g01217960(/.*)?)$'
by:
  group: g01217960

**How to Reproduce**
Create a token on the profile page and specify a role. Have someone else log into the Rundeck box who doesn't belong to the same role and see if they can see the token.

**Comment by ecarrascos** [comment]
Hi wreyes94

From the ACL policy you provided, we can see that you are allowing the following action to your group policy:

```
- equals:
    kind: user
  allow: [admin]
```

So this may not be a bug. Allowing [admin] action for the [user] resource, provides the group of capabilities to modify user profiles across Rundeck , not just for themselves or their group.

Please refer to the documentation http://rundeck.org/docs/administration/access-control-policy.html

Providing the group of:

    - equals:
        kind: apitoken
      allow: [generate_user_token]  
	  
will enable each user that belongs to that group of capabilities to generate and see only their own token under [user->profile].

Can you test modifying your ACL policy according to your requirements and let us know if the behaviour remains?

Hope it helps!

**Comment by wreyes94** [comment]
Thanks for the response, We gave them both admin and the generate_user_token so i'm guessing rundeck ignored the second part and just provided admin access. Removing the admin part fixed it, thanks again.
