### ISSUE TITLE
Force HTTPS

### ISSUE THREAD

**Issue by ivomarino** [rundeck/rundeck#3257]
Hi there, is there a way to force HTTPS? I'm running rundeck as docker container behind HAProxy, when I force HAProxy to redirect everything to HTTPS the https://rundeck.foo.org runs fine, if I don't it always redirects to http://rundeck.foo.org after login attempt? thanks for feedback

**Comment by gschueler** [comment]
rundeck may redirect to the URL defined in your rundeck-config.properties as `grails.serverURL`.  This should be set to the external URL you want to use, such as "https://host.name"

**Comment by h4wkmoon** [comment]
does not work for me, on openshift 3.9 using official image.
rundeck version 3.0.19

**Comment by ProTip** [comment]
Hi @h4wkmoon,

The `grails.serverURL` and the `rundeck.jetty.connector.forwarded=true` settings must be set, and the appropriate `X-Forwarded-Proto` header present. For the official Docker images the environment variable `RUNDECK_SERVER_FORWARDED=true` can be used.
