### ISSUE TITLE
Ability to run tasks in a job individually 

### ISSUE THREAD

**Issue by lucascrezende** [rundeck/rundeck#3261]
I have a job with many tasks in it but sometimes I need to run specific tasks individually but I cannot find a way to do that without duplicating my job and remove the entries I don't want to run. 

Would it be hard to have a "play icon" next to the other icons so it would be possible to run only specific tasks within a job in demand?

**Comment by methom90wh** [comment]
+1 for this.  A way to enable/disable each step would be great.

**Comment by dpomnean** [comment]
Could your tasks be in a separate job for each one? So your main task would be a bunch of job references and if you need to run a specific task, just run the child task job.

**Comment by lucascrezende** [comment]
Probably it could be like that but this is a workaround, not a solution.



‌


Lucas Rezende

Celular / Mobile: +55 21 97529-0881 <+55%2021%2097529-0881>
Skype: lucas.c.rezende

2018-04-17 14:50 GMT-03:00 dpomnean <notifications@github.com>:

**Comment by dpomnean** [comment]
It would make sense to have your steps in their own jobs and have the parent job reference them in case you wanted to use the child jobs in other jobs to reduce the amount of redundancy. Just my two cents.
