### ISSUE TITLE
java.lang.NullPointerException when trying to execute a command

### ISSUE THREAD

**Issue by ryudice** [rundeck/rundeck#3269]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.8
* install type: docker jordan/rundeck:2.10.8 (rpm,deb,war,launcher?)
* OS Name/version: image is based on debian:stretch
* DB Type/version: mariadb

**Expected Behavior**

When I try to execute a command on a node it should run the command or at least give a meaningful error message

**Actual Behavior**

I get a meaningless error message:

```
16:32:24    localhost   Failed dispatching to node RH9-Prod-TIM-223.131: java.lang.NullPointerException: Cannot get property 'meta' on null object
16:32:24        Execution failed: 4 in project SaonDev: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [RH9-Prod-TIM-223.131: Unknown: java.lang.NullPointerException: Cannot get property 'meta' on null object]}, Node failures: {RH9-Prod-TIM-223.131=[Unknown: java.lang.NullPointerException: Cannot get property 'meta' on null object]}, status: failed]
```

**How to Reproduce**

Add the following project configuration:

```
<?xml version="1.0" encoding="UTF-8"?> <project> <node name="localhost" description="Rundeck server node" tags="" hostname="localhost"
osArch="amd64" osFamily="unix" osName="Linux" osVersion="4.4.0-109-generic" username="rundeck"/>

<node name="RH9-Prod-TIM-223.131" description="Tech Integration Production Host 01" tags="" osArch="amd64" hostname="10.144.223.131" osFamily="unix" osName="Linux"
username="ubuntu" ssh-keypath="keys/saondev/ubuntu-user"/>

<node name="RH7-Dev-TIM-223.173" description="Tech Integration Dev Host 01" tags="" osArch="amd64" hostname="10.144.223.173" osFamily="unix" osName="Linux" username="root"
ssh-keypath="keys/saondev/root-rh9.key"/> </project>

```
Then try to run a job.

**Comment by ecarrascos** [comment]
Hi ryudice,

Thank you so much for bringing this to our attention, and we're currently working to verify the scope of this NullPointerException error and how it relates to the Key storage used by Rundeck, as we already managed to reproduce this behaviour.

In the meantime, please refer to our [SSH Plugins documentation](http://rundeck.org/docs/plugins-user-guide/ssh-plugins.html) for guidance and usage of our SSH plugin in order to avoid the NullPointerException. The node attribute "ssh-keypath=" specifies the location of the private key file stored locally on disk. If you use Rundeck's [Key Storage](http://rundeck.org/docs/administration/key-storage.html) for your keys, the node attribute you need to use is "ssh-key-storage-path="

Eduardo Carrasco

**Comment by digitalray** [comment]
Hello @ecarrascos, the ssh documentation link in your comment is not working. I am getting the same error when executing a script on local runback node. Interestingly executing commands is OK. Here is the error from the log:

[2022-06-15T01:56:35,943] ERROR services.ExecutionUtilService [quartzScheduler_Worker-8] - Execution failed: 18 in project DigitalRay: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [web-bm-01: Unknown: java.lang.NullPointerException]}, Node failures: {web-bm-01=[Unknown: java.lang.NullPointerException]}, status: failed]

RUNDECK
APIVERSION : 41
BASE : /opt/rundeck
BUILD : 4.3.0-20220602
BUILDGIT : v4.3.0-0-gcfa3da5
NODE : web-bm-01
SERVERUUID : 86web-bm-01
VERSION : 4.3.0-20220602

EXECUTIONS
ACTIVE : true
EXECUTIONMODE : ACTIVE

OS
ARCH : amd64
NAME : Linux
VERSION : 5.15.0-33-generic

JVM
IMPLEMENTATIONVERSION : 11.0.15+10-Ubuntu-0ubuntu0.22.04.1
NAME : OpenJDK 64-Bit Server VM
VENDOR : Private Build
VERSION : 11.0.15

System Configuration
/opt/rundeck/etc/framework.properties:
framework.server.hostname: localhost
framework.server.name: web-bm-01
/opt/rundeck/server/config/rundeck-config.properties:
grails.serverURL: https://rundeck.digitalray.net
SSH Defaults

/opt/rundeck/etc/framework.properties:
Datasource

/opt/rundeck/server/config/rundeck-config.properties:
dataSource.url: jdbc:mysql://localhost/rundeck?autoReconnect=true&useSSL=false
Plugins

/opt/rundeck/server/config/rundeck-config.properties:
rundeck.execution.logs.fileStorage: {generateExecutionXml=true, cancelOnStorageFailure=true}
rundeck.execution.logs.fileStorage.cancelOnStorageFailure: true
rundeck.execution.logs.fileStorage.generateExecutionXml: true
Login Module

Authentication is performed using JAAS. The configuration file is defined using a System property:
java.security.auth.login.config:
The currently used login module:
rundecklogin
Repositories

Repositories contain plugins which can be searched and installed from inside the application.

/opt/rundeck/server/config/rundeck-config.properties:
rundeck.feature.repository.enabled: true
Limit plugin searches to just installed plugins (true) or include searching the public repository (false | default).

/opt/rundeck/server/config/rundeck-config.properties:
rundeck.feature.repository.localSearchOnly:

![image](https://user-images.githubusercontent.com/6512172/173724940-c055b73c-487d-4d14-919b-971eea7b2cff.png)

**Comment by humerarehman** [comment]
Hi [digitalray](https://github.com/digitalray) - did you find a solution for this? I have same issue.

**Comment by toan-superman** [comment]
Thanks @jhanssenfavaro , I have been stuck in this issue for 3 months, and now you save my life.
