### ISSUE TITLE
Enable Internationalization for Project config level settings

### ISSUE THREAD

**Issue by PeekLeon** [rundeck/rundeck#3300]
Hi,

I would like to internationalize the entire job creation form.

But I don't know how to do with .groovy files like shelduledExecutionService.groovy for example.

How could  integrated a "g.message" for replace the title text or description text.

PS : I not a developer java but i have some skills in development (PHP, javascript, C#)

Sorry for my english, i m french

Thank you

**Comment by gschueler** [comment]
Hi, thanks for the help!

Do you mean you want to internationalize parts of the form that don't have it yet? If so you should look in the various files in `rundeckapp/grails-app/views/scheduledExecution/*.gsp`, they contain the template used to generate the form.  Most of the text is already i18n'ized using g.message, so the messages in messages.properties should apply to it.

**Comment by PeekLeon** [comment]
Hi, thank you for your quick response

Sorry i made a mistake, I wanted to talk about the **Projects forms**  and not ~~Job forms~~ .

The job form are translated by views (*.gsp) there no problem but the project form contains hard text in the file ```rundeck\rundeckapp\grails-app\services\rundeck\services\ScheduledExecutionService.groovy```

Example :

![inter_project](https://user-images.githubusercontent.com/28193768/39241233-75bd77d8-4886-11e8-9c8e-3ffd4c864be3.PNG)

You can find the text here : 

```java
class ScheduledExecutionService implements ApplicationContextAware, InitializingBean, RundeckProjectConfigurable {
    public static final String CONF_GROUP_EXPAND_LEVEL = 'project.jobs.gui.groupExpandLevel'
    public static final String CONF_PROJECT_DISABLE_EXECUTION = 'project.disable.executions'
    public static final String CONF_PROJECT_DISABLE_SCHEDULE = 'project.disable.schedule'

    public static final List<Property> ProjectConfigProperties = [
            PropertyBuilder.builder().with {
                integer 'groupExpandLevel'
                title 'Job Group Expansion Level'
                description 'In the Jobs page, expand Job groups to this depth by default.\n\n' +
                                    '* `0`: collapse all Groups\n' +
                                    '* `-1`: expand all Groups.'
                required(false)
                defaultValue '1'
                renderingOption('projectConfigCategory', 'gui')
            }.build(),
            PropertyBuilder.builder().with {
                booleanType 'disableExecution'
                title 'Disable Execution'
                required(false)
                defaultValue null
                renderingOption('booleanTrueDisplayValueClass', 'text-warning')
            }.build(),
            PropertyBuilder.builder().with {
                booleanType 'disableSchedule'
                title 'Disable Schedule'
                required(false)
                defaultValue null
                renderingOption('booleanTrueDisplayValueClass', 'text-warning')
            }.build(),
    ]

...
```
How could integrated a "g.message" in this code ?

**Comment by gschueler** [comment]
Ah, I see.  Yes, let me look into that...

**Comment by gschueler** [comment]
I will update it in the following way:

for project-config level settings declared in the *Service.groovy files:

titles for categories (these message looks are already present):

`project.configuration.extra.category.[CATEGORY].title`
`project.configuration.extra.category.[CATEGORY].description`

Messages for properties:

`project.configuration.extra.category.[CATEGORY].property.[NAME].[KEY]`

Where `[KEY]` is one of:

* `title` (property title)
* `description` (description)
* `options.[OPTION].label` (label for a predefined Option)
* `defaultValue` (default value text, where the property rendering option "displayType" is "STATIC_TEXT")

For example, the "groupExpandLevel" declared in ScheduledExecutionService.groovy is in category "gui", so would have these message keys:

* `project.configuration.extra.category.gui.groupExpandLevel.title`
* `project.configuration.extra.category.gui.groupExpandLevel.description`

**Comment by PeekLeon** [comment]
I tested like this (in messages.properties and messages_fr_FR.properties):

- ```project.configuration.extra.category.gui.groupExpandLevel.title=TTTTTTTT```
- ```project.configuration.extra.category.gui.groupExpandLevel.description=DDDDDDD```
- ```project.configuration.extra.category.text-warning.disableExecution.title=TTTTTTTT```
- ```project.configuration.extra.category.text-warning.disableSchedule.title=TTTTTTTT```

and like that

- ```project.configuration.extra.category.gui.property.groupExpandLevel.title=TTTTTTTT```
- ```project.configuration.extra.category.gui.property.groupExpandLevel.description=DDDDDDD```
- ```project.configuration.extra.category.text-warning.property.disableExecution.title=TTTTTTTT```
- ```project.configuration.extra.category.text-warning.property.disableSchedule.title=TTTTTTTTT```

but it does not seem to work :'(

**Comment by gschueler** [comment]
thanks, fixed: https://github.com/rundeck/rundeck/pull/3311

with those changes the following codes work in the Project config form:

~~~{.properties}

project.configuration.extra.category.gui.property.groupExpandLevel.title=TTTTT
project.configuration.extra.category.gui.property.groupExpandLevel.description=DESC
project.configuration.extra.category.gui.property.motdDisplay.options.projectList.label=ZZZZZ
project.configuration.extra.category.gui.property.motdDisplay.options.projectHome.label=XXXX
~~~
