### ISSUE TITLE
Missing i18n Texts

### ISSUE THREAD

**Issue by DiegoQueiroz** [rundeck/rundeck#3309]
i18n support is missing on page: `/project/[project_name]/activity`

Text: "`at: [start_time]`"
Text: "`by [user_name]`"
Text: "`in [elapsed_time]`"

These strings aren't present in `messages.properties` file.

![image](https://user-images.githubusercontent.com/976809/39311411-3b9fc17e-4943-11e8-8d1d-d40993db0769.png)

**Comment by gschueler** [comment]
fixed by https://github.com/rundeck/rundeck/pull/3348
