### ISSUE TITLE
Rundeck not reading ACLs created in GUI

### ISSUE THREAD

**Issue by ahmedchater** [rundeck/rundeck#3310]
Issue type: Bug report

We have an issue where ACLs created in the GUI (Project -> Access Control -> Create ACL Policy) are not being read by Rundeck. These ACLs are being created here:

`/var/rundeck/projects/<Project Name>/acls/<Project ACL>.aclpolicy`

However it appears that Rundeck only reads ACLs from /etc/rundeck/. Even the documentation seems to indicate that ACLs are only read from this directory:

http://rundeck.org/docs/man5/aclpolicy.html

ACLPOLICY
Overview
This document describes the YAML format for ACL Policy definition files.

Multiple aclpolicy files can be stored in the same directory, helping the management of each set of rules. This reduces the complexity of each file. The default path is

**RPM install: /etc/rundeck**
Launcher install: $RDECK_BASE/etc

So I'm not sure how ACLs created in the GUI are supposed to get read by Rundeck. Also it appears that it does not look in any subdirectories of /etc/rundeck

**My Rundeck detail**

* Rundeck version: 2.10.8-1
* install type: rpm
* OS Name/version: Amazon Linux v2
* DB Type/version: postgres 9.6.6

**Expected Behavior**
Rundeck would be able to read ACLs created by the GUI in `/var/rundeck/projects/<Project Name>/acls/`

**How to Reproduce**
Create ACL in GUI, Rundeck will not read it. Move it to /etc/rundeck and re-add the context section.

**Comment by gschueler** [comment]
can you post an example of an aclpolicy file that doesn't work?

project-specific ACLs apply only to the project, so they have an implicit project context.

**Comment by ahmedchater** [comment]
Here's the ACL I'm using. Granted the problem may lie in the way I have the ACL configured, I'm still trying to get a better understanding of it.

The ACL works in the /etc/rundeck folder, but does not work when I paste it into the GUI. Also I remove the context section for both sections (because the GUI forces you to).

description: User project level access control. Applies to resources within a specific project. Essentially read/run/kill/refresh.
context:
  project: '<Some Project>'
for:
  resource:
    - equals:
        kind: job
      allow: [read,run,kill]
    - equals:
        kind: node
      allow: [read,update,refresh]
    - equals:
        kind: event
      allow: [read,create]
    - equals:
        kind: adhoc
      allow: [read,run,kill]  
  adhoc:
    - allow: [read,run,kill]
  job:
    - allow: [read,run,kill]
  node:
    - allow: [read,run,refresh]
by:
    username: 'someuser' 
---
 
description: User application level access applies to viewing projects and reading system information.
context:
  application: 'rundeck'
for:
  resource:
    - equals:
        kind: project
      allow: [read]
    - equals:
        kind: system
      allow: [read]
    - equals:
        kind: user
      allow: [read]
  project:
    - match:
        name: '<Some Project>'
      allow: [read]
  system:
    - allow: [read]
  storage:
    - allow: [read]
by:
    username: 'someuser'

**Comment by gschueler** [comment]
the policy with `application: 'rundeck'` will not be applied if you put it in a project ACL.  If you put it in the System ACLs it should work.

Try putting the project specific one in the Project > Access Control, and the system one in the System Config > Access Control
