### ISSUE TITLE
referenced jobs are executed on a default runlist

### ISSUE THREAD

**Issue by 375gnu** [rundeck/rundeck#3320]
Issue type: Bug report
* Rundeck version: 3.10.8
* install type: launcher
* OS Name/version: SLES 12
* DB Type/version: h2

**Expected Behavior**

Referenced jobs inherit a parent's runlist.

**How to Reproduce**

Create 2 jobs running on all nodes, "one" and "two", job "two" should have a step referencing job "one". Then run job "two" but only on one node: job "one" will be executed on all nodes.

If you run job "two" on all nodes job "one" will be executed on all nodes but on every "two" execution on every new node, so it will be executed N*N times instead of just N.

**Comment by 375gnu** [comment]
wonderful

**Comment by vaxvms** [comment]
@375gnu you have to override node filter as described in https://docs.rundeck.com/docs/manual/node-steps/builtin.html#overriding-node-filters
and check "Yes, create node intersection with current job nodes"

poor default choice IMHO
