### ISSUE TITLE
Node intersection not being commutative (shows error)  when "Overriding Nodes" in a Job Reference 

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#3332]
Issue type: Bug report
-->

**My Rundeck detail**

* Rundeck version: 2.10.8
* install type: (rpm,deb,war,launcher?)
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**

Expected behavior: intersection should be commutative.

When adding a Job Reference and selecting `Override node filters` >  `create node intersection with current job nodes` 

Intersection works correctly only when the number of "Overridden nodes" or "Triggered Job's target nodes" are >= (greater or equal) than "current job nodes" ( intersects the matching nodes, without errors). 

Else, an error is shown in the Nodes that are not "intersected" 

**How to Reproduce**

-Create a Job with a Job Reference. 
-Select  `Override Node Filters` > `Yes, create node intersection with current job nodes`

![override node filter](https://user-images.githubusercontent.com/31705339/39485754-2591e4a0-4d50-11e8-90f2-7a70094a31ec.png)

_Case 1_

Triggered JobB target nodes -> `name:Node1,Node2`
Parent Job-> `name:Node1`
Intersection Result: JobB runs on node1 without errors

![2 nodes in jobref 1 node in parent](https://user-images.githubusercontent.com/31705339/39485294-b442da58-4d4e-11e8-89b9-0090b92e3899.png)

_Case 2_

Triggered Job B target nodes -> `name:node1`
Parent Job -> `name:Node1,Node2`
Intersection Result: JobB runs on Node1,  error: "No nodes matched for the filters" on Node2

Expected Result: JobB should only run on Node1, without errors

![1 node in jobref 2 nodes in parent job](https://user-images.githubusercontent.com/31705339/39485332-d3432bc4-4d4e-11e8-9328-0bd66e07aa93.png)

**Comment by gschueler** [comment]
can you include the job definitions?

**Comment by sebastianbello** [comment]
Her you go @gschueler  ( .xml  renamed .txt )
[Parent.txt](https://github.com/rundeck/rundeck/files/1964884/Parent.txt)
[JobB.txt](https://github.com/rundeck/rundeck/files/1964885/JobB.txt)

**Comment by gschueler** [comment]
you have the Job Reference set as a Node step.  That means that for each matched node in the parent job, it is invoked.  In Case 2, Since you set the node filter to `name:node1` in the job reference, and `name: node1,node2` in the parent it is doing this:

* Start job -> filter results: [node1,node2]
* Step 1: jobreference node step ==  Execute for each [node1,node2]:
    1.  execute jobref on set [node1] -> intersect filter "name:node1"-> result: [node1] -> run job
    2.  execute jobref on set [node2] -> intersect filter "name:node1"-> result: [] -> no matched nodes

If you change the job reference to a Workflow step, it will behave like this:

* Start job -> filter results: [node1,node2]
* Step 1: jobreference Workflow step ==  Execute once.
    1.  execute jobref on set [node1, node2] -> intersect filter "name:node1"-> result: [node1] -> run job

**Comment by sebastianbello** [comment]
@gschueler you are absolutely right. Thanks for the clarification!
