### ISSUE TITLE
Key Value Data doesn't print correct values

### ISSUE THREAD

**Issue by thiagobucca** [rundeck/rundeck#3339]
**My Rundeck detail**

* Rundeck version: 2.11
* install type: deb
* OS Name/version: Debian Stretch 
* DB Type/version: mysql

**Expected Behavior**

the value "IL" is printed.

**How to Reproduce**

Hi,

I'm trying to capture key value data from a job and i'm getting some strange behaviour.

Key Value Config: https://postimg.cc/image/m9mz6p5vv/
First job output that matches the regex: https://postimg.cc/image/id9navd8b/

Then i have "command" type step with the following call:
echo ${data.name*}

However, when i run the job echo prints nothing in Log Output, is this something i'm doing wrong or it its a bug?

When i use the same regex with **"Highlight Output"** filter, it works and the string "IL" appears in Log Output console.

Thanks in advance!

**Comment by gschueler** [comment]
I see in your first screenshot the Key Value Data filter is configured for "All Workflow Steps"...try adding it to individual steps instead.

**Comment by jplassnibatt** [comment]
Try this regex filter `\s*"des_state"\s*:\s*"(.+?)"`, the `\s*` will fill all the spaces in the line until it finds the key.

**Comment by jplassnibatt** [comment]
the proper regex fixes the issue
