### ISSUE TITLE
Secure Passwords are Open If we run the Job in Debug Mode

### ISSUE THREAD

**Issue by ggnanasekaran77** [rundeck/rundeck#3344]
Setting environment variable: RD_JOB_EXECID=3
--
06:56:29 |   |   | Setting environment variable: RD_NODE_USERNAME=rundeck
06:56:29 |   |   | Setting environment variable: RD_SECUREOPTION_CONFIGSERVERPASSWORD=test123

**Comment by gschueler** [comment]
use the MaskPasswords log filter plugin
