### ISSUE TITLE
Referenced job options

### ISSUE THREAD

**Issue by methom90wh** [rundeck/rundeck#3377]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.10
* install type: (rpm,deb,war,launcher?) RPM
* OS Name/version:  Oracle Enterprise Linux 7.4
* DB Type/version: mysql? postgres? h2?..  Oracle DB v11.2

When you create a job step that is another job reference it would be nice if you could see somewhere easily a list of the referenced jobs options so you are reminded of them,

**Comment by methom90wh** [comment]
And maybe highlight the required ones.

**Comment by JustinAddams** [comment]
This sounds similar to this issue: https://github.com/rundeck/rundeck/issues/252
