### ISSUE TITLE
ENH:  "Default Value" is not allowed for Job Options with "input Type: Date" despite existing in the code and working as expected.

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#3378]
Issue type:Enhancement Request

**My Rundeck detail**

* Rundeck version: 2.11.1 and prior versions
* install type: (rpm,deb,war,launcher?)
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**
A "default value" for Job Options with "Input Type: Date" is desirable/required. 

However, it seems this value may be already implemented in the code, but not visible when editing the Job Option nor correctly validated before running the job. 
When changing from "Input Type: Date" to "Input type: Plain Text" and back to  "Input Type: Date" the "default value" field becomes visible, editable and usable. 
However, a " Red Border" warning is shown when running the job ( works as expected, though)  

**How to Reproduce**
- Create a Job Option with "Input Type: Date". Save. 

- Edit the newly created "date" option, no "Default Value" field is present.

- Select "Input type: Plain Text" and then go back to "Input Type: Date"

- The required "Default Value" field is now visible and may be populated as desired ( variables, values, etc). Save the option.  Save the Job

- The "default Value" now is selected in the "date " option, however, it is outlined in Red ( warning ) despite being a valid value ( only  "blank" is validated)

- Run the job and it works as expected, despite the "warning"

**Comment by jtobard** [comment]
This is no longer an issue on 3.2.0-SNAPSHOT
