### ISSUE TITLE
Key Storage not working as expected with Windows Setup.

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#3382]
Issue type: Bug report

**My Rundeck detail**
rundeck-launcher-2.11.1.jar 
Windows setup 2008 R2 

-- start_rundeck.bat file 
******************************
set CURDIR=%~dp0
call %CURDIR%etc\profile.bat

java %RDECK_CLI_OPTS% %RDECK_SSL_OPTS%  "-Dserver.http.host=127.0.0.1" "-Dserver.http.port=81" "-Djava.security.krb5.realm=xxx.xxx.com" "-Djava.security.krb5.kdc=DC.xxx.xxx.com" -Dloginmodule.conf.name=jaas-ldap.conf -Dloginmodule.name=ldap  -jar rundeck-launcher-2.11.1.jar --skipinstall -d 

Issue:
******************************
I am using rundeck with Windows setup (IIS 7, Java, etc..) I have followed online docs to do the setup. I got everything working except Python WinRM. I was able to use the Ruby WinRM. Which worked fine, so I know it's not winrm related, but I prefer to use the latest/greatest from rundeck Python WinRM. ALSO I want to let you know that I have successfully test wirnm directly from python CLi.  With that said, looks like the issue is related to not being able to read or pass the KeyStore value, path, or something to the python script. The same setup in CentOs works fine. I think it has to do with the windows setup.

Also it would be helpful if you could update online docs to show the folder mapping from linux setup and windows setup. In case anyone else is interested  here is what I have so far: 
/var/lib/rundeck  -> C:\rundeck\server
/etc/rundeck	->   C:\rundeck\etc
/tmp/rundeck	 ->  C:\rundeck\_Temp       #<- I manually created this myself, was not part of the doc.

Here is the Profile File:
*************************
RDECK_BASE=C:/rundeck
export RDECK_BASE

JAVA_HOME=C:/Program Files (x86)/Java/jre1.8.0_171
export JAVA_HOME

PATH=$JAVA_HOME/bin:$RDECK_BASE/tools/bin:$PATH
export PATH

export JAVA_CMD=$JAVA_HOME/bin/java

if test -n "$JRE_HOME"
then
   unset JRE_HOME
fi

LIBDIR=$RDECK_BASE/tools/lib

CLI_CP=
for i in `ls $LIBDIR/*.jar`
do
 CLI_CP=${CLI_CP}:${i}
done
export CLI_CP

#
# Set min/max heap size
#
export RDECK_JVM="$RDECK_JVM -Xmx1024m -Xms512m -XX:MaxMetaspaceSize=256m -server"
#RDECK_JVM="$RDECK_JVM -Djava.security.auth.login.config=/config/jaas-ldap.conf \
 -Dloginmodule.name=ldap"

export RDECK_JVM="$RDECK_JVM \
		-Djava.security.auth.login.config=/server/config/jaas-ldap.conf \
        -Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG \
		-Djava.security.krb5.realm=xxx.xxx.com \
		-Djava.security.krb5.kdc=dc. xxx.xxx.com \
        -Dloginmodule.name=ldap \
        -Drdeck.config=/etc \
        -Drdeck.base=/server \
        -Drundeck.server.configDir=/etc \
        -Dserver.datastore.path=/server/data \
        -Drundeck.server.serverDir=/server \
        -Drdeck.projects=/projects \
        -Drdeck.runlogs=/server/logs \
        -Drundeck.config.location=/server/config/rundeck-config.properties \
		-Drundeck.server.workDir={$RUNDECK_TEMPDIR:-$RDECK_BASE/server/work} \
        -Djava.io.tmpdir=$RUNDECK_TEMPDIR"

export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=$RDECK_BASE/etc/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"

umask 002

Here is the command error log output:  (see bold below KeyError: 'PATH')
***********************************************************

[workflow] beginExecuteNodeStep(TFS-03Q): NodeDispatch:   CommandItem{command=[1 words]}
--
22:45:48 |   | [WinRMPython] execCommand started, command: dir
22:45:48 |   | [WinRMPython] executing: [[python, -u,   C:\rundeck\libext\cache\py-winrm-plugin-1.0.3\winrm-exec.py,   ${node.hostname}]]
22:45:48 |   | Traceback (most recent call last):
22:45:48 |   | File   "C:\rundeck\libext\cache\py-winrm-plugin-1.0.3\winrm-exec.py", line   1, in <module>
22:45:48 |   | import winrm
22:45:48 |   | File   "C:\tools\python\lib\site-packages\winrm\__init__.py", line 6, in   <module>
22:45:48 |   | from winrm.protocol import Protocol
22:45:48 |   | File   "C:\tools\python\lib\site-packages\winrm\protocol.py", line 11, in   <module>
22:45:48 |   | from winrm.transport import Transport
22:45:48 |   | File   "C:\tools\python\lib\site-packages\winrm\transport.py", line 30, in   <module>
22:45:48 |   | from requests_ntlm import HttpNtlmAuth
22:45:48 |   | File   "C:\tools\python\lib\site-packages\requests_ntlm\__init__.py", line   1, in <module>
22:45:48 |   | from .requests_ntlm import HttpNtlmAuth
22:45:48 |   | File   "C:\tools\python\lib\site-packages\requests_ntlm\requests_ntlm.py",   line 5, in <module>
22:45:48 |   | from cryptography import x509
22:45:48 |   | File   "C:\tools\python\lib\site-packages\cryptography\x509\__init__.py",   line 8, in <module>
22:45:48 |   | from cryptography.x509.base import (
22:45:48 |   | File   "C:\tools\python\lib\site-packages\cryptography\x509\base.py", line   16, in <module>
22:45:48 |   | from cryptography.x509.extensions import Extension,   ExtensionType
22:45:48 |   | File   "C:\tools\python\lib\site-packages\cryptography\x509\extensions.py",   line 13, in <module>
22:45:48 |   | from asn1crypto.keys import PublicKeyInfo
22:45:48 |   | File   "C:\tools\python\lib\site-packages\asn1crypto\keys.py", line 22, in   <module>
22:45:48 |   | from ._elliptic_curve import (
22:45:48 |   | File   "C:\tools\python\lib\site-packages\asn1crypto\_elliptic_curve.py",   line 51, in <module>
22:45:48 |   | from ._int import inverse_mod
22:45:48 |   | File   "C:\tools\python\lib\site-packages\asn1crypto\_int.py", line 56, in   <module>
22:45:48 |   | from ._perf._big_num_ctypes import libcrypto
22:45:48 |   | File   "C:\tools\python\lib\site-packages\asn1crypto\_perf\_big_num_ctypes.py",   line 35, in <module>
22:45:48 |   | libcrypto_path = find_library(b'crypto' if sys.version_info   < (3,) else 'crypto')
22:45:48 |   | File "C:\tools\python\lib\ctypes\util.py", line 53,   in find_library
22:45:48 |   | for directory in os.environ['PATH'].split(os.pathsep):
22:45:48 |   | File "C:\tools\python\lib\os.py", line 425, in   __getitem__
22:45:48 |   | return self.data[key.upper()]
22:45:48 |   | KeyError:   'PATH'
22:45:48 |   | [WinRMPython]: result code: 1, success: false
22:45:48 |   | Failed: NonZeroResultCode: [WinRMPython] Result code: 1
22:45:48 |   | [workflow] finishExecuteNodeStep(TFS-03Q): NodeDispatch:   NonZeroResultCode: [WinRMPython] Result code: 1

*****************
I have tried: 
  - creating numerouse Key Store password values
  - I have made sure the password does not contain special chars
  - I have the username option assigned at the node level (user@domain.com) from resources.
  - Key is assigned to WinRm from the Project Level.
  
Thank you

**Comment by norillsa** [comment]
+1 - I'm seeing the same thing on Rundeck 2.11.4-1 cappuccino saddlebrown pushpin 2018-06-07 - running on Windows Server with Python2.7.12 installed.
