### ISSUE TITLE
duplicate jobs page doesn't show options 

### ISSUE THREAD

**Issue by kino71** [rundeck/rundeck#3384]
Issue type: Bug report/Enhancement Request
Bug report

**My Rundeck detail**

* Rundeck version: 
2.11.2 (tested also on 2.11.1)
* install type: (rpm,deb,war,launcher?)
Launcher
* OS Name/version: 
Solaris 5.11
* DB Type/version: mysql? postgres? h2?..
Sybase ASE

**Expected Behavior**
"Duplicate job" page should shows the options from the job being duplicated.
Options appear if the job is actually created from the "duplicate job" page.

**How to Reproduce**
Duplicate a job.

**Comment by kino71** [comment]
Adding an option to the job makes all the other options reappear.

**Comment by frachel** [comment]
Was about to report this as well, we're using 2.11.3
