### ISSUE TITLE
Node filter negation: Nodes included which don't satisfy the filter

### ISSUE THREAD

**Issue by puremourning** [rundeck/rundeck#3403]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.10.2-1
* install type: rpm
* OS Name/version: RedHat Enterprise Linux 6.7
* DB Type/version: mysql

**Expected Behavior**

When using a node filter that includes a predicate like `!tags: sometag` along with a custom attribute negation, like `!TestAttribute: VALUE`, no nodes should be selected with that tag.

From [the manual](http://rundeck.org/docs/manual/node-filters.html):

> You can negate a match by using !attributename: value

> The result is all nodes which match all of the clauses.

**How to Reproduce**

* Create a new project in the UI
* Doesn't matter about the executor (use stub)
* On the resource model sources, add 2 stub sources, as follows:

![rd-stub-nodes](https://user-images.githubusercontent.com/10584846/40108966-3fe0277c-58f4-11e8-9037-44717a4c1ae1.PNG)

You can see that there are 2 nodes, both of which have the custom attribute `TestAttribute=VALUE`

* has-tag, which has the `noinclude` tag
* no-tag, which does not

To repro:

1. Go to the Nodes page, and enter the following filter: `!TestAttribute=NOT_VALUE !tags: noinclude` 

Expected behaviour:

* "no-tag" should match the filter
* "has-tag" should *not* match the filter

Actual behaviour:

* "no-tag" matches (OK)
* "has-tag" matches (FAIL)

![rd-nodefilter](https://user-images.githubusercontent.com/10584846/40109254-dc4b811a-58f4-11e8-9daa-b07f4c9622a8.PNG)

**Comment by puremourning** [comment]
Any chance of confirming if this is a bug, or am I just holding it wrong ?

**Comment by Ultimation** [comment]
Looks like it may be the same as #4372

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
