### ISSUE TITLE
JDK10 support

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#3413]
Enable Rundeck to work on JDK 10

- [ ] jaxb dependency needs to be included explicitly
- [ ] grails mail plugin issue: https://github.com/grails3-plugins/mail/issues/31 
- [ ] Do not pass null as the credential to UserInfo in the JettyCachingLdapLoginModule class after binding login. A null value causes a stacktrace in JDK 10.

**Comment by SpencerMalone** [comment]
Note, the above PR for the jetty version bump was declined in favor of waiting until grails updates to a version of spring boot with the updated jetty version, and it looks like spring boot is blocked by https://github.com/spring-projects/spring-boot/issues/15239 / https://github.com/eclipse/jetty.project/issues/3137

Just wanted to have that tracked so others could keep an eye on it.

**Comment by SpencerMalone** [comment]
The next grails release should have fixes for the above included.

**Comment by SpencerMalone** [comment]
Well, we're on a later grails release, but it seems there are new problems, which is kind of a bummer. I haven't dug in too much yet, but it's definitely not working on java 11 now (where previously I could get it pretty happy with some minor version bumps)

**Comment by marcjay** [comment]
Given that Java 8 is no longer supported commercially (without Oracle agreements in place, as far as I understand), isn't this quite a serious issue? Should I raise an issue for Java 11 support as that seems more appropriate given it is LTS and 10 is not?

**Comment by marcjay** [comment]
I'd be willing to help with a Java 11 upgrade. It looks like an upgrade to Grails 4 is needed, amongst other things. @gschueler would PRs towards this be accepted? Any guidance, especially on how to break the work down into acceptable chunks would be appreciated, many thanks

**Comment by gschueler** [comment]
@marcjay thanks for the offer to help, but we are starting the work to upgrade to grails 4 in the very near future. We are quite aware of the Java 8 issue! Stay tuned...

**Comment by marcjay** [comment]
Great to hear, thanks for the update 👍

**Comment by sjrd218** [comment]
Added support for JDK 10+ in Rundeck 3.3.0.
