### ISSUE TITLE
WinRM Python output is ONLY shown at the end of the execution. 

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#3416]
This issue is similar to #885 and I believe the issue still exists. I have tried everything possible and I am still not able to get a live WinRM output when using module: "WinRM Node Executor Python".

![winrm-python-screenshot-1](https://user-images.githubusercontent.com/20629911/40316831-6cd07974-5cd4-11e8-949b-0c0637f5af9b.PNG)

From the terminal try running these two scenarios.
Sceanrio #1 using rundeck plugin script
```
export RD_OPTION_USERNAME=WINUSER
export RD_CONFIG_AUTHTYPE=ntlm
export RD_CONFIG_WINRMPORT=5985
export RD_CONFIG_WINRMTRANSPORT=http
export RD_CONFIG_NOSSL=true
export RD_CONFIG_SHELL=powershell
export RD_JOB_LOGLEVEL=DEBUG
export RD_EXEC_COMMAND="write 'before sleep...';dir;write 'sleeping 5-sec';sleep 5;dir;write 'after sleep...'"
export RD_CONFIG_PASSWORD_STORAGE_PATH=WINPASS
python -u /var/lib/rundeck/libext/cache/py-winrm-plugin-1.0.4/winrm-exec.py YOURHOSTSERVER
```

Scenario #2 using python console (output is not that great, but it shows the problem):
```
python -u
import winrm
winrm.Session('YOURHOSTSERVER', auth=('WINUSER','WINPASS'),transport='ntlm').run_ps("whoami;sleep 5;pwd").std_out
```

You'll notice the entire results return once the powershell script is completed. Where before in the old java plugin the results were returned immediately before the sleep command was executed.

Any help is greatly apprecaited.

Thank you

**Comment by gschueler** [comment]
I think you should reopen this issue to https://github.com/rundeck-plugins/py-winrm-plugin repo, this is not a rundeck issue.  Rundeck emits the output as it is received, so if it is happening all at once at the end, then that means the plugin/python is the cause.

**Comment by hs-hub-world** [comment]
Thanks @gschueler  I have opened new issue.
https://github.com/rundeck-plugins/py-winrm-plugin/issues/8
