### ISSUE TITLE
importOptions missplaced in yaml/xml export.

### ISSUE THREAD

**Issue by turlubullu** [rundeck/rundeck#3429]
Hello,
I have a problem with the import options feature, when combined with the xml/yaml job export feature.

When I do a xml/yaml export of a job using the import option feature, the xml/yaml object for the import options is at the wrong place => the importOptions element is in the command element instead of the jobref element.

Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.11.3-1
* install type: rpm
* OS Name/version:  centos 7
* DB Type/version: h2

**Expected Behavior**

A job using the "import options" feature should be exported/imported without the loss of this feature activation.

**How to Reproduce**

Create a Job with options.
Create a Job with previously created Job as a workflow step and activate  the "import options" feature.
Export this job as xml/yaml
Re-import this job.
=> The "import options" feature is not activated anymore.

**Comment by hs-hub-world** [comment]
I am experiancing same isue ;(
