### ISSUE TITLE
Different variable usage for passed job options in thread count

### ISSUE THREAD

**Issue by kirrmann** [rundeck/rundeck#3431]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.11.3-1 
* install type: deb
* OS Name/version: Ubuntu 16.04.4 LTS
* DB Type/version: h2

**Expected Behavior**
Setting **Thread Count** to `${option.threads}` should use the default or passed value for option "threads"

**How to Reproduce**
1. setup job 1 to call job 2 as Job Reference and pass a value for job 2 option "threads"
2. setup job 2 with option "threads" and use this option for **Thread Count**
3. if **Thread Count** is set as `${option.threads}` it references the **default** value for option "threads"
4. if **Thread Count** is set as `@option.threads@` it references the **passed** value of option "threads"

**Comment by kirrmann** [comment]
Can anybody help me with that? Because of this bug it's unpossible to set the Thread Count of Job References

**Comment by eugenegwon** [comment]
any progress on this? I have same problem. 
reference jobs are not using passed value of option.threads; ONLY use default value.

I'm using Rundeck 3.0.2-20180817 version. :(

**Comment by kirrmann** [comment]
still relevant
