### ISSUE TITLE
LOG OUTPUT SLOW - FILE LOCKED MULTIPLE TIMES.

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#3436]
**Describe the bug**
LOG OUTPUT LOADING IS EXTREMLY SLOW. 
The same log file is being read more than once.

**My Rundeck detail**
* Rundeck version: 2.11.3
* install type: rpm
* OS Name/version: Centos 7
* DB Type/version: MSSQL

Looks like rundeck will not close the log file after done reading in the Log Output window. Also, the same process job will re-open the same log file and it will re-read over and over again hence the Log Loading is extremely slow….

Here are the steps to identify the bug.

1- Run job that generates a large log (2 to 3 min).
-	Now find the rundeck PID and run this command to locate the open files: 
-	_command:_ ls -lrn /proc/20515/fd  |grep "513"    
	Note: 20515 is the java proc-ID, 513 is the job id

-	Once you have located the path of the log then you may run the command below to monitor the activity of the file lock

-	_command:_ watch lsof  /var/lib/rundeck/logs/rundeck/TFS-QA/job/2ff64ce9-aa99-4739-9834-ebcb8ae566c3/logs/513.rdlog

-	Now go to the Log Output TAB and you’ll notice the log file is loading multiple times.
-      As the log loads Rundeck UI becomes slower and slower until it becomes unresponsive.

![rundeck-issuse-screenshot-1](https://user-images.githubusercontent.com/20629911/40571347-11bd6f9e-604c-11e8-91d6-06205a96998b.PNG)

 - rundeck-config.properties file
```
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/var/lib/rundeck
quartz.props.threadPool.threadCount = 20

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
# change hostname here
grails.serverURL=http://xxxx:4440

dataSource.dbCreate = update
dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true


#rundeck.projectsStorageType=db
#dataSource.dbCreate = update
#dataSource.driverClassName = com.microsoft.sqlserver.jdbc.SQLServerDriver
#dataSource.url = jdbc:sqlserver://xxxx;DatabaseName=rundeck
#dataSource.username = rundeckuser
#dataSource.password = xxxx
#rundeck.min.isolation.level=UNCOMMITTED

# Enables DB for Project configuration storage
#rundeck.projectsStorageType=db

# Enable DB for Key Storage
#rundeck.storage.provider.1.type=db
#rundeck.storage.provider.1.path=keys


rundeck.gui.execution.tail.lines.default=500
rundeck.gui.execution.tail.lines.max=500
rundeck.gui.login.welcome="Welcome - Login."
rundeck.api.tokens.duration.max=30

#notification email
"/etc/rundeck/rundeck-config.properties" 62L, 2088C
```

**Comment by JustinAddams** [comment]
Just to confirm how big is that log file?
Am I reading it correctly that it's 103MB?

Secondly what "Job" did you run to generate such a log, can I grab a copy to test it on my side see what occurs?

**Comment by hs-hub-world** [comment]
Hi, thanks for the reply.  just to clarify.
Yes - the log size in the screenshot is 103MB.  I have testing with log size as small as 7MB and it is still very slow loading output log. It is only fast when log files are less than 1MB.

Below script is winrm powershell script using plugin:  py-winrm-plugin-1.0.4.zip
```

#You may adjust the log file size by adjusting the (addminutes(x)) value and  (-Seconds x) value
# Higher -Seconds x value (Smaller log file size) / Lower -Seconds x value (Larger log file size)
# Lower addminutes(x) value (Smaller log file size) / Higher addminutes(x) value (Larger log file size)


#powershell script below generates around 7MB file. (slow loading log output)
$StartTime=Get-Date;do{write "Script running"; Get-ChildItem -Recurse  $env:windir\system32;sleep -Seconds 60;}while(($(Get-Date).AddMinutes(-1) - $StartTime) -lt 0);write "Done"

#powershell script below generates around 35MB file. (Very slow loading output)
$StartTime=Get-Date;do{write "Script running"; Get-ChildItem -Recurse  $env:windir\system32;sleep -Seconds 2;}while(($(Get-Date).AddMinutes(-3) - $StartTime) -lt 0);write "Done"

#powershell script below generates around 48MB file. (Extremly, excruciatingly slow loading output)
$StartTime=Get-Date;do{write "Script running"; Get-ChildItem -Recurse  $env:windir\system32;sleep -Seconds 2;}while(($(Get-Date).AddMinutes(-4) - $StartTime) -lt 0);write "Done"
```


thank you for looking into this...

**Comment by JustinAddams** [comment]
7MB Log loads fine, nearly instantly.
35MB Log loads very slow.

I'd say behaviour confirmed.

**Comment by JustinAddams** [comment]
I use the Ruby WinRM plugin available here: https://github.com/NetDocuments/rd-winrm-plugin
It does not output any noise at the end of the log unless there was a failed step

> 07:13:28	localhost	1. Check for Minidump 	Failed dispatching to node SERVER: [WinRMcp]: external script failed with exit code: 1
> 07:13:28			Parallel node dispatch failed: 
> com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$DispatchFailure: Dispatch failed on node: SERVER
> com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$DispatchFailure: Dispatch failed on node: SERVER
> com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$DispatchFailure: Dispatch failed on node: SERVER
> com.dtolabs.rundeck.core.execution.dispatch.ParallelNodeDispatcher$DispatchFailure: Dispatch failed on node: SERVER

Even without this noise my logs were still close to the size you said they would be, so the XML doesnt seem to be affecting you too much.

**Comment by hs-hub-world** [comment]
@JustinAddams Thanks for quick reply. One last question. I noticed you are using the ruby winrm plugin. does  if you run this command `write 'sleeping 5';sleep -seconds 5;write 'after sleep'`
does the first output 'Sleeing 5' show up immediately before sleep or does your output show up once the entire script is completed. In other words, is it a live stream or output only shows up once the execution is completed -?

in my case, output shows up once the entire execution is completed

![rundeck-issuse-screenshot-3](https://user-images.githubusercontent.com/20629911/40816659-f438136e-6502-11e8-94a4-cadf93a9f9c5.PNG)

Thank you

**Comment by JustinAddams** [comment]
@hs-hub-world The output only appears once that steps has finished executing. I am yet to work out how to make it realtime like the built in SSH plugin. I believe I may need to make a Java plugin instead of a script one to get nice realtime updates.

**Comment by hs-hub-world** [comment]
Thanks, @JustinAddams. you mean like this one -> https://github.com/rundeck-plugins/rundeck-winrm-plugin

**Comment by JustinAddams** [comment]
@hs-hub-world Yeah except that one doesn't support PowerShell only CMD
