### ISSUE TITLE
Memory leak with non-heap - maybe api related

### ISSUE THREAD

**Issue by Daryes** [rundeck/rundeck#3437]
**Describe the bug**
Rundeck system memory consumption is increasing heavily and immediately swapped. To the point to call the system OOM killer. Trouble is, the  application heap and non-heap are steady.

**My Rundeck detail**

* Rundeck version: 2.11.3
* install type: deb
* OS Name/version: ubuntu 16.04 server 4.4.0-122-generic
* DB Type/version: file
* RD CLI version: 1.0.27
* RDECK_JVM_SETTINGS="-Xmx512m -Xms384m -XX:MaxMetaspaceSize=256m -server  -javaagent:/server/jolokia/jolokia/jolokia-jvm-agent.jar=port=34440,host=localhost"

**To Reproduce**
It takes around 2 days for the swap increase. To this day, I have no idea where it comes from, as it's not related to the java heap or non-heap, and Rundeck is the only resident process on his server.

I've currently have those elements doing a hefty usage of the rundeck API : 
- each 5 mins, a script calling the API for listing the number of projects, and the number of executed jobs with the following status : running succeeded failed aborted.
- each day at 06 am, a job listing all project, all their executions older than xx days, then removing those executions.
- each day at 06 am, a backup script using the RD CLI listing the existing projects, then a `rd jobs list -f 'file.xml' -p 'project'` on each.
- Some jobs also use a script which call the API to look for a specific job, and wait for a particular execution status (success, usually), with a 1 min delay between checks.

**Resources usage**
The following graphics were taken 2 days after a reboot. 
They are done using influxdata/telegraf for the collector, calling Jolokia as a jmx source. I use this combination on other systems that doesn't show this behavior with Rundeck.
In addition, telegraf also calls each 5 mins the script listing the number of project and job execution status.

System state
![rundeck-1-system_swap](https://user-images.githubusercontent.com/14362813/40584621-60c5ed88-61a4-11e8-9bcc-2aa32cbb22c8.jpg)
Ram: 974M
Swap: 560M

Notice the swap increase, the system reports Rundeck as the sole source using more than 2 Mb

Java heap :
![rundeck-2-jheap](https://user-images.githubusercontent.com/14362813/40584819-236aded6-61a8-11e8-9f4a-b927a4eaf9de.jpg)
The usage keeps slowly growing, as it takes 2 days to stabilize. Even after a month, the committed heap always stays under the initial memory size.
The line is messy because of the monitoring script calling the API. Without, it's the usual slow growth until the GC clears it.

Java threads count :
![rundeck-3-jthreads](https://user-images.githubusercontent.com/14362813/40584871-2bdfcac6-61a9-11e8-95e9-720173666b08.jpg)
The increase are related to the morning executions. The most surprising thing is the total count (right axis) that never stop to increase, even after a full week. Seen it at a time over 100k.
Could make sense as the monitoring makes usage of and additional script calling the API.

Java non-heap :
![rundeck-4-non_heap](https://user-images.githubusercontent.com/14362813/40584946-a21476d2-61aa-11e8-8016-b4ae2b55dc78.jpg)
Sorry for the different date, I forgot to take this screen with the other. 
It's worth noting the non-heap usage is also stabilized at 235 Mb after a while and won't go over.

**Next steps**
Currently, I've deactivated the call to the monitoring script using the API for the jobs execution state. It'll allow for another set of screenshot, but IIRC, the swap consumption is still here, just much more slower.

**Comment by Daryes** [comment]
Took me a while of tests, but through VisualVM, I finally found that as suspected, the memory leak is not in the java heap, and VisualVM and MAP has no real clue about where it could come from. 
Explains also why the different java dumps don't have much difference in size and don't reflect the system resources consumption.

Meanwhile, I got a situation where the monitoring shown the relation between the swap and the Java Tenured Gen increase : after the initialization, each increase is the same amount of swap consumed.  
It's also consistent with the Java loaded class count, increasing each time by a 1-2k count jump, while the unloaded never change from 0, even after many days running.

Running the jvm with `-XX:+PrintGCDetails -XX:+TraceClassUnloading -XX:+TraceClassLoading` shows a lot of those 
```
[Loaded sun.reflect.GeneratedMethodAccessor1311 from __JVM_DefineClass__]
[Loaded sun.reflect.GeneratedConstructorAccessor239 from __JVM_DefineClass__]
[Loaded sun.reflect.GeneratedMethodAccessor1312 from __JVM_DefineClass__]
[Loaded sun.reflect.GeneratedMethodAccessor1313 from __JVM_DefineClass__]
(...) x10 in a row
[Loaded sun.reflect.GeneratedMethodAccessor1325 from __JVM_DefineClass__]
[Loaded sun.reflect.GeneratedMethodAccessor1326 from __JVM_DefineClass__]
```
But not a single unload about those classes, even if `-XX:+CMSClassUnloadingEnabled -XX:-UseConcMarkSweepGC` are set.
Unless I'm mistaken, rundeck don't make usage of the reflect API, but grails does, through groovy.
MAT concurs about this : 
![rundeck-7-mat_suspect](https://user-images.githubusercontent.com/14362813/41594906-4c704652-73c5-11e8-9dfe-937e5171e9c9.JPG)

Also, sounds to me the "leak" is permanent due to the constant class loading, but need time to become visible.  
It's only because of the constant rundeck API polling from the monitoring and also a script handling dependencies used by the jobs that it become more noticeable.

I'm up for any idea or test, as actually it's getting out of my depth.

**Comment by mveroone** [comment]
I think we might be facing this issue too, but our Rundeck server is used way too much to be able to perform the same tests you did.  
In particular, we run a script every night that deletes the executions older than 14/28 days through `rd`, thus through the API.  
We have configured a Heap size of 8 GB but the process uses over 12GB total, so then again, same behaviour.

**Comment by SpencerMalone** [comment]
Seems like maybe this got fixed in https://github.com/rundeck/rundeck/issues/3437

**Comment by Daryes** [comment]
Thanks for the information.   
Waiting for the 3.0.27 (or the next 3.1.0x) then, and I'll check it

**Comment by Daryes** [comment]
I've finally updated directly to v3.2.0.  
After some weeks, it's better as while the java non-heap is still falling into the the swap after a while, it reach a plateau where the increase will be much more slower and manageable.   

There's still a large amount of classes loaded, and at least the unloaded class count is keeping the pace instead of a flat 0.    
But a 10-15% difference where classes are loaded but not unloaded still exists. Most of the time, it can be linked to time periods when the api is requested.  
So while it's not perfect, it's at least better as it seems to be partially contained. Depending of the workload, and with the failing jobs bug after a restart is also fixed, it could be handled with a monthly or weekly process restart maintenance

**Comment by fdevans** [comment]
We apologize if this issue was missed and glad to hear there was some improvement.  If you are still experiencing an issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
