### ISSUE TITLE
Feature request for scp style file transfer facility in rundeck

### ISSUE THREAD

**Issue by andysteady** [rundeck/rundeck#344]
Feature request to have a plugin which can essentially form a simple wrapper to scp.

Arguments can be provided to an scp job which is then turned into a scp command line and executed using any of the authentication mechanism supported by Rundeck (ssh, password, sudo).

Excellent if it could handle scp directly between two remote machines without pulling the files back to the rundeck server.

This is discussed here: https://mail.google.com/mail/u/0/?shva=1#inbox/13db21c4d38d655a which contains the following text from Greg:

"Luckily Rundeck 1.5 allows for new types of steps via plugins: this sounds like a candidate for a new plugin which provides SCP capabilities using the same ssh+sudo mechanism we already use for node execution."

**Comment by pecigonzalo** [comment]
Anyone has a working script/ alternative to transfer this files? Rundeck is pretty useless for windows without the ability to run scripts and just being able to run commands.
