### ISSUE TITLE
sudo: no tty present and no askpass program specified

### ISSUE THREAD

**Issue by ha02148** [rundeck/rundeck#3448]
**Describe the bug**

I have the following node defined.

\<node name="server1" description="test server1" tags="apache" hostname="192.168.1.101"  osFamily="Linux" osName="RHEL" osVersion="7.3" username="test" sudo-command-enabled="true" sudo-password-storage-path="keys/test/sudo.password" \>

Works fine with adhoc command to the node, but failed with the following error on the job.  

sudo: no tty present and no askpass program specified

I can workaround the issue with NOPASSWD: ALL in sudoers, but don't want to do that unless I have to.

**My Rundeck detail**

* Rundeck version: 2.11.3-1 
* install type: rpm
* OS Name/version: Centos 7.4
* DB Type/version: OOTB

**To Reproduce**
1. Create a job with inline script to run sudo
2. Select the target host
3. See the following in the log output.
4. sudo: no tty present and no askpass program specified

**Expected behavior**
sudo command executed without error.

Thanks

**Comment by kumartushar** [comment]
I am also facing same issue when running a command with sudo.

**Comment by cwray** [comment]
Any word on this? I just ran into this problem today.

**Comment by JesusRo** [comment]
Hi @ha02148,
From my own experience, that is shown when sudo ask for interactive input for running the command.
Indeed, that workaround fix the issue because forces sudo to do not ask for anything.

My suggestion (and what I have implemented here) is to make sudoers more granullarity, instead `NOPASSWD: ALL`, specify what commands can be run with sudo without password, kind of this:
```
username = (root) NOPASSWD: /path/to/my/program
```

Then, you could run sudo /path/to/my/program without issues, but any other sudo will still ask,
For reference: [https://www.sudo.ws/man/1.8.15/sudoers.man.html](https://www.sudo.ws/man/1.8.15/sudoers.man.html)

**Comment by gaddman** [comment]
I was able to resolve this by checking the _Force PTY_ option in the Default Node Executor section of the project settings.

**Comment by prajwalahluwalia** [comment]
I am having issue in Ubuntu 18.04.
when i am trying to run touch command in my local system, i am facing this issue
**touch: cannot touch 'files.xml': Permission denied**
If i am using sudo touch files.xml 
**sudo: no tty present and no askpass program specified**

also when i am creating the project it is not eatd in specified path i.e. /var/lib/rundeck/projects/PROJECTNAME/

i am using Rundeck 3.2.4-20200318 on ubuntu 18.04

**Comment by gorky** [comment]
For default SSH Provider:
- add '-tt' to force TTY
- setup Secondary SUDO Authentication as described in [https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html](https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html)
Unfortunately, the Default provider is JSCH which at this time is an abandoned project that only supports low or obsolete protocols.
Unfortunately, this appears to be the only SSH Provider that supports Secondary SUDO Authentication - which for secure installations appears to cripple Rundeck's functionality and renders it useless for setup tasks.
