### ISSUE TITLE
When i add new user, it's obligatory to restart Rundeck

### ISSUE THREAD

**Issue by pchevallereau** [rundeck/rundeck#3452]
When i had a new user to realm.properties file or in realm-w3.properties file for ldap authentification, it's obligatory to restart Rundeck service.

**My Rundeck detail**
* Rundeck version: 2.10.8
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: mariadb

**To Reproduce**
1. Add a new user to the realm.properties file or in realm-w3.properties
2. Save file
3. Try to connect on the web page
4. The user can not login

**Expected behavior**
the possibility to dynamicly add users without restart Rundeck service

**Desktop (please complete the following information):**
 - Windows 7
 - Firefox Browser 52.4.1

**Comment by gschueler** [comment]
what is your jaas configuration?

**Comment by pchevallereau** [comment]
multiauth {
    org.eclipse.jetty.jaas.spi.PropertyFileLoginModule sufficient
      debug="true"
      file="/etc/rundeck/realm.properties";

    com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule required
      debug="true"
      contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
      providerUrl="LDAP-URL"
      bindDn="LDAP-ACCOUNT"
      bindPassword="LDAP-PASSWORD"
      authenticationMethod="simple"
      forceBindingLogin="true"
      userBaseDn="ou=**,dc=**,dc=**,dc=**,dc=**"
      userRdnAttribute="sAMAccountName"
      userIdAttribute="sAMAccountName"
      userPasswordAttribute="unicodePwd"
      userObjectClass="user"
      roleBaseDn="ou=**,dc=**,dc=**,dc=**,dc=**"
      roleNameAttribute="cn"
      roleUsernameMemberAttribute="memberUid"
      roleMemberAttribute="memberUid"
      roleObjectClass="posixGroup"
      cacheDurationMillis="300000"
      supplementalRoles="user"
      reportStatistics="true"
      timeoutRead="10000"
      timeoutConnect="20000"
      nestedGroups="false"
      ignoreRoles="true"
      storePass="true"
      clearPass="true"
      useFirstPass="true"
      tryFirstPass="true";

    org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
      debug="true"
      useFirstPass="true"
      caseInsensitive="true"
      refreshInterval="60"
      file="/rundeck_data/realm-w3.properties";
};

**Comment by pchevallereau** [comment]
Have you found something @gschueler  ?

**Comment by orderedchaosdev** [comment]
@pchevallereau If I'm reading your config correctly then after you update the realm-w3.properties file you will have to wait around 60 seconds for it to reload the realm file and pick up the new changes

**Comment by gtsteffaniak** [comment]
@gschueler Are there any plans to include this again?

**Comment by Fonkyup** [comment]
Could this improvement be added?
