### ISSUE TITLE
Guarantee UNIX characters when uploading scripts

### ISSUE THREAD

**Issue by pellyadolfo** [rundeck/rundeck#348]
The issue has been discussed here (https://groups.google.com/forum/?fromgroups=#!topicsearchin/rundeck-discuss/bug/rundeck-discuss/OW1KGBtznn4).

When Job XML definitions are created on Windows systems, scripts can contain windows characters that will result in an error when executed on a UNIX system.

04:43:08    bash: /tmp/1364956979089-CentOS-r56-dispatch-script.sh: /bin/sh^M: bad interpreter: No such file or directory

It should not be difficult to replace windows end lines by  UNIX endlines somewhere in the process to guarantee that UNIX get not win chars.

Potential places where this verification could be done:
- when Uploading a Job XML definition to create/upddate a job (Java)
- when saving an script in the GUI (Java)
- in the process that sends the script to server side (Java)
- in the process of executing an script invoking dos2unix

**Comment by gschueler** [comment]
This enhancement/bugfix is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
