### ISSUE TITLE
Grails3: war launcher needs a way to load database driver jars

### ISSUE THREAD

**Issue by sjrd218** [rundeck/rundeck#3505]
Mssql, Oracle and other databases need to have a jdbc driver jar on the classpath. Previously this was put in a location after the internal war was exploded. With Spring boot that location went away so we need an alternative.

**Comment by ProTip** [comment]
Looks like we can just add these in as runtime deps to in `build.gradle` and spring boot will incorporate them:

```groovy
runtime group: 'com.microsoft.sqlserver', name: 'sqljdbc4', version: '4.0'
```

```bash
~/projects/rundeck/rundeckapp/build/libs$ jar tvf rundeck-3.0.0-alpha.war | grep sqljdbc
584207 Mon Jun 11 17:20:20 CDT 2018 WEB-INF/lib/sqljdbc4-4.0.jar
```


Do we know which drivers and versions we want to package? I used `sqljdbc4` here due to the compatibility back to Java7(I believe).

**Comment by ahonor** [comment]
@ProTip the databases include:
* mysql
* mariadb
* oracle
* postgresql
* sqlserver

**Comment by sjrd218** [comment]
I think we need to carefully weigh the cost of bundling these drivers against the convenience to our users of distributing them with our product.

By adding the drivers our product packages will increase in size, and we will have to make sure we stay current with these driver versions. Snyk will help us make sure we track vulnerabilities that could be included with these drivers, but that is another thing we should consider.

I have added the ability to pick up jars at runtime if they are put in the RDECK_BASE/server/lib directory, so bundling the drivers is no longer strictly necessary. 

Bundling will increase the convenience to our users, so if we decide to continue in that direction I think that's also ok.

Would like to hear what you guys think.

**Comment by plambert** [comment]
We should find the best way to achieve the benefits of bundling them, and the benefits of not bundling them.

A documentation page with links to the vendors' pages for download, and clear instructions for how to install them, would be helpful.  In addition, maybe link to an importable job (YAML file) to allow the user to upload a driver and then install it for them in the appropriate location?  It should be possible for the job to verify it's a JDBC plugin, as well as prevent overwriting a newer version unless a 'downgrade' option is selected?

It could be perhaps offered in versions using bash for Linux, and PowerShell for Windows?

Just an idea.

**Comment by ProTip** [comment]
I'm hugely in favor of bundling these baring technical constraints.

**Size**:
`111MB` -> `113MB` or ~1.8% of the archive size according to my local testing(incidentally everything spring boot bundles accounts for only about 12MB).

**Bug and Security Fixes:**
We can centralize the effort of ensuring the JDBC drivers for the supported databases are up-to-date; for the project and its users. A cursory search indicates CVEs related to JDBC drivers are very few and far between(gotta love that "Unspecified vulnerability" Oracle issue from 2016 😄 ). With Snyk, the expanding testing infrastructure, and streamlined release process we will be in a pretty good low-effort position to maintain up-to-date drivers in the bundle from a security standpoint.

**Convenience and UX:**
If we aim to support these databases the OOTB experience of needing to download extra drivers and copy them into place is pretty poor.  As we expand our testing suite to validate against an expanded database list we are going to have to ensure we are testing with up-to-date drivers as well. By bundling the drivers we will be reducing the burden for ourselves and our users of automating driver acquisition across the myriad of installation targets and configuration management tools.

**Comment by sjrd218** [comment]
Excellent research @ProTip. You've answered my concerns. I think another compelling advantage to bundling, is that we know the driver will get loaded at the right time by the right classloader. Bundling seems to make a lot of sense in this case.
