### ISSUE TITLE
[ Provide "iteration" option for jobs ]

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#3513]
Hi,

I'm using Rundeck to deploy my applications on several aplication servers

I have a generic task whick allows me to choose some options before launching the deployment.

This task does twoo things:
- It uses nodes filters to select elligible nodes to launch actions on (based of the generic task's input)
- It launches actions on selected nodes; mainly by running loops on them (for i in; do ...)

I wonder if we could have some kind of "looping" job.

Currently, I have a job wich iterates actions by using bash scripting with loops
This job targets 1 node (based on node filters) and launch multiple actions on it, sequentialy
It works, but it is quite slow.

I would like to have a job wich could be launched in paralell, based on input options

The result would be:
Rather than 1 job running 10 actions sequentialy; 1 job which will run all 10 actions at the same time in parallel

I hope I'm clear enough

Any idea to help me achieve this ?

Many thanks in advance

Best regards

Jérôme

**Comment by jerome83136** [comment]
bump :)

**Comment by remifrazierucsf** [comment]
See #606

**Comment by remifrazierucsf** [comment]
+1

**Comment by jerome83136** [comment]
Thank you
