### ISSUE TITLE
Add a back-to-top button?

### ISSUE THREAD

**Issue by ouyangxudu** [rundeck/rundeck#3524]
**Describe the solution you'd like**
add a back-to-top button on the "Log Output"page, when a deploying finish, lots of lows of logs generated, have to scroll a lot the mouse to back to the top to navigator bar to click to another place. 

**Describe alternatives you've considered**
or let the navigator bar pined or locked in the page

**Comment by gschueler** [comment]
Please post the rundeck version, you are using, @ouyangxudu
