### ISSUE TITLE
Logs are not rotating daily untill we restart the rundeck server

### ISSUE THREAD

**Issue by jobsforprabu** [rundeck/rundeck#3525]
Hi Team,

Logs are not rotating on daily basis, untill we will restart the rundeck services. can you please guide me how to resolve this issue. Even changed few configuration in log4j properties but nothing seems to be working

Rundeck 2.10.8-1 

Regards
Prabu ganesh

**Comment by sjrd218** [comment]
Could you send your log4j.properties file?

**Comment by jobsforprabu** [comment]
[log properties.txt](https://github.com/rundeck/rundeck/files/2148853/log.properties.txt)


Please find the attached log4j  file

**Comment by sjrd218** [comment]
It appears that there may be a few errors in your log4j configuration. When I copied your configuration to my server I received a number of log4j error messages related to the configuration. This indicates that log4j will not work as expected.

It appears that the two places where the TimeBasedRollingPolicy are specified may be the problematic areas.

You might try something similar to this:

```
...
log4j.appender.access=org.apache.log4j.rolling.RollingFileAppender
log4j.appender.access.rollingPolicy=org.apache.log4j.rolling.TimeBasedRollingPolicy
log4j.appender.access.rollingPolicy.ActiveFileName=/var/log/rundeck/rundeck.access.log
log4j.appender.access.rollingPolicy.FileNamePattern=/var/log/rundeck/rundeck.access.%d{yyyy-MM-dd}.log
...
```
As you modify the log4j.properties file, be sure to carefully monitor the startup logs to make sure no configuration errors are reported by log4j.

**Comment by jobsforprabu** [comment]
Thanks for your input, let me check it in my instance will let you know the details
