### ISSUE TITLE
Job retry ignored when used as reference job

### ISSUE THREAD

**Issue by mhaluska** [rundeck/rundeck#3527]
**Describe the bug**
When I define job retry I'm expecting also use retry when using this job as reference job. Currently job fails immediately when reference job fails.

**My Rundeck detail**

* Rundeck version: 2.11.4
* install type: rpm
* OS Name/version: CentOS Linux release 7.5.1804 (Core)
* DB Type/version: mysql

**To Reproduce**
Steps to reproduce the behaviour:
1. Create job Test1 with some command
2. Create job Test2 with some command and exit code != 0, set job retry to 2
3. As a 2nd step to job Test1 add reference job Test2
4. Run the job Test1
5. Job Test1 fails immediately without retry Test2 job

**Expected behaviour**
Retry reference job Test2 two times before failing Test1.

**Comment by mhaluska** [comment]
found in docs, not possible for inherited job

**Comment by Jokero** [comment]
To be honest, don't know why it was closed. This looks as a missing important feature

**Comment by amartin3225** [comment]
I would also find this useful so I made #8194
