### ISSUE TITLE
Confirm bulk action popoup

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#3530]
on the project page, if you perform any action over the jobs, the "Confirm bulk action" popoup is displayed.
The problem is that the popup is displayed like "bellow" the main layer the buttons cannot be pressed.

**My Rundeck detail**

* Rundeck version: Rundeck 3
* install type: war,launcher
* OS Name/version: Windows, MacOS
* DB Type/version: mysql, mssql

**To Reproduce**
1. Go to Job Page
2. On "Job Action Button", Click on "Bulk edit" option
3. select some jobs
4. select some actions 
5. the confirm pop up will be displayed

**Expected behavior**
the popup layer should work

**Screenshots**
<img width="733" alt="screenshot 2018-06-19 12 17 54" src="https://user-images.githubusercontent.com/6034968/41613655-32ce7f30-73c4-11e8-81cf-375a35e54ce2.png">

**Desktop (please complete the following information):**
 - OS: MacOS, Windows 2012
 - Browser: Chrome, Fixefor
 - Version: x

**Comment by sjrd218** [comment]
@ltamaster I think this has been fixed. Can you confirm?

**Comment by jtobard** [comment]
Fixed on previous build
