### ISSUE TITLE
Deleting a parent job deletes/breaks all referenced jobs

### ISSUE THREAD

**Issue by dd5154** [rundeck/rundeck#3537]
Deleting a parent job deletes/breaks all referenced jobs. I have tried removing all references from the job before deleting the parent job and it still causes error. Referenced jobs still show in rundeck, but when they are selected, the following error appears:

An Error Occurred
Error processing GroovyPageView: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <g:render>: Error executing tag <auth:resourceAllowed>: Error executing tag <g:form>: Cannot get property 'extid' on null object

**My Rundeck detail**

* Rundeck version: 2.11.4-1 
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: MariaDB 10

**To Reproduce**
1. Create 'child' job with simple cmd step
2. Create two separate 'parent' jobs that both reference child job
3. Make sure jobs work
4. Delete one 'parent job'
5. Click on 'child' job and error appears

**Expected behavior**
No error on referenced job

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser chrome
 - Version 67.0.3396.87

**Comment by jtobard** [comment]
Fixed in #3655
