### ISSUE TITLE
Provide a way to set per project history retention and allow truncating history

### ISSUE THREAD

**Issue by diwu1989** [rundeck/rundeck#357]
It should be possible to set job history retention per project and be able to clear history from the admin page.

**Comment by huksley** [comment]
I upvote for this. Our rundeck installation is completely scripted and easiest way cleanup is to delete everything and reinstall and repopulate with from scratch. This also helps with responsiveness which degrades when number of history job execution rises.

**Comment by jedblack** [comment]
+1 , would be helpful to trim the history.

**Comment by kayvonr** [comment]
Would also really love to see this feature added in - bulk deleting through the UI takes very long time (for deleting say 15,000 executions)

**Comment by gschueler** [comment]
Added a new trello card for the specific feature of "Execution history retention policy or automatic deletion" https://trello.com/c/OQqroc0A

**Comment by kayvonr** [comment]
Yo - for everyone on this thread, I've found a way to circumvent rundeck UI and API to delete old executions, if you're using an external DB (we're using mysql). It's janky (very janky), but it works, and it's fast, and it doesn't seem to mess up anything in rundeck. Posting because we quickly hit 115 thousand executions, and we needed a quick way to clear the backlog.

* on the rundeck server
** navigate to job directory you want to delete for (e.g. /var/lib/rundeck/logs/rundeck/Project1/job/rundeck_job_id/logs)
** grab the execution IDs
*** ls -ltrh | head -n XXX | awk '{print $9}' | cut -d. -f 1 | uniq > /tmp/delete_ids.txt
**** remember that XXX should be double what you want to delete, as there are 2 files per execution
*** turn those into comma separated 
**** paste -d, -s /tmp/delete_ids.txt > /tmp/delete_ids_comma.txt
*** open that file and delete leading comma and turn into sql query ( DELETE FROM rundeck.execution WHERE id in (...)  )
*** now delete those log files
**** ls -ltrh | head -n XXX | awk '{print $9}' | xargs rm

and then from somewhere
      * mysql -h your_mysql_master -u your_user -pXXX rundeck < /tmp/delete_ids_comma.txt

**Comment by diwu1989** [comment]
From the sounds of that, it sounds like u could just delete * from rundeck.execution

**Comment by unicolet** [comment]
This shell script (written with postgres in mind) should do it:

https://gist.github.com/unicolet/af648a97163ce6b44645

**Comment by jippi** [comment]
+1

**Comment by zolech** [comment]
+1

**Comment by RawTech** [comment]
+1 This is a needed feature for any large scale use cases.

**Comment by tavorserenase** [comment]
I use a bash kludge tested on solaris and linux. Only for version 17 api


NODE="127.0.0.1"
PORT="4440"
PROJECT="odi_collaudo"
RETENTION="5m"
TOKEN="<yourtoken>"

### system variables
timestamp=$(date)
epoch_time=$(date +%s)
egrep_bin="/usr/sfw/bin/ggrep"
#egrep_bin="/usr/bin/egrep"
curl_bin="/usr/bin/curl"
sed_bin="/usr/bin/sed"

purge_all () {
URL="http://${NODE}:${PORT}/api/1/history?project=${PROJECT}"
HISTORY_XML=$(curl -H "X-RunDeck-Auth-Token:$TOKEN" -H "Content-Type: application/xml" -X POST "$URL")
ID_LIST=$(echo $HISTORY_XML | $egrep_bin -o "execution id='*.[0-9]*.'" | $sed_bin "s#'##g;s#.*execution id=\(\)#\1#" | sort | tr '\n' ',' )
purged=$(echo "$ID_LIST" | $egrep_bin -o "," | $egrep_bin -c ",")

echo "$timestamp - Executing complete purge_job_history for project ${PROJECT}"
for ID in ${ID_LIST}
  do
   URL="http://${NODE}:${PORT}/api/12/executions/delete?ids=${ID}"
   $curl_bin -H "X-RunDeck-Auth-Token:$TOKEN" -X POST "$URL" >/dev/null 2>&1
   purged=$((purged+1))
done
echo "Job executions purged:  $purged"
}

purge_date () {
## Check retention
if   [[ "$RETENTION" == *"d"* ]] ; then  EPOCH="86400"
elif [[ "$RETENTION" == *"h"* ]] ; then  EPOCH="3600"
elif [[ "$RETENTION" == *"m"* ]] ; then  EPOCH="60"
elif [[ "$RETENTION" == *"s"* ]] ; then  EPOCH="1"
elif [[ "$RETENTION" == *"ALL"* ]] ; then purge_all
else echo "Specify d,h,m in RETENTION - ex. RETENTION="30d"" ; exit 1
fi

purge_date=$(echo "$epoch_time - (${RETENTION::-1} * $EPOCH)" | bc)

URL="http://${NODE}:${PORT}/api/1/history?project=${PROJECT}&end=$purge_date"
HISTORY_XML=$(curl -H "X-RunDeck-Auth-Token:$TOKEN" -H "Content-Type: application/xml" -X POST "$URL")
ID_LIST=$(echo $HISTORY_XML | $egrep_bin -o "execution id='*.[0-9]*.'" | $sed_bin "s#'##g;s#.*execution id=\(\)#\1#" | sort | tr '\n' ',' )
purged=$(echo "$ID_LIST" | $egrep_bin -o "," | $egrep_bin -c ",")

echo "$timestamp - Executing  purge_job_history for project ${PROJECT} on ${RETENTION}
      Removing $ID_LIST events"

for ID in ${ID_LIST}
  do
   URL="http://${NODE}:${PORT}/api/12/executions/delete?ids=${ID}"
   $curl_bin -H "X-RunDeck-Auth-Token:$TOKEN" -X POST "$URL" >/dev/null 2>&1
   purged=$((purged+1))
done
echo "Job executions purged:  $purged"

}

purge_date

**Comment by DerfOh** [comment]
+1 This would be very nice for orgs with massive run histories as the archive brings the logs with it when moving the project/jobs to new environments.

**Comment by dooblem** [comment]
Nice shell script @unicolet 
I updated it for mysql users (debian/ubuntu oriented).
I also forced the bash interpreter, as it's not working with dash.
```
#!/bin/bash

# setup ~/.pgpass to allow passwordless connection to postgres
# keep last 30 executions for each job
KEEP=30


cd /var/lib/rundeck/logs/rundeck

JOBS=`find . -maxdepth 3 -path "*/job/*" -type d`

for j in $JOBS ; do
        echo "Processing job $j"
        ids=`find $j -iname "*.rdlog" | sed -e "s/.*\/\([0-9]*\)\.rdlog/\1/" | sort -n -r`
	echo $ids
        declare -a JOBIDS=($ids)

        if [ ${#JOBIDS[@]} -gt $KEEP ]; then
          for job in ${JOBIDS[@]:$KEEP};do
             echo " * Deleting job: $job"
             echo "   rm -rf $j/logs/$job.*"
             rm -rf $j/logs/$job.*
             echo "   mysql --defaults-extra-file=/etc/mysql/debian.cnf rundeck -e 'delete from execution where id=$job'"
             mysql --defaults-extra-file=/etc/mysql/debian.cnf rundeck -e "delete from execution where id=$job"
             echo "   mysql --defaults-extra-file=/etc/mysql/debian.cnf rundeck -e 'delete from base_report where jc_exec_id=${job}'"
             mysql --defaults-extra-file=/etc/mysql/debian.cnf rundeck -e "delete from base_report where jc_exec_id='${job}'"
          done
        fi
done
```

**Comment by Dmitry1987** [comment]
Hi @dooblem , did you encounter this during script run?

`-e 'delete from execution where id=118456'
ERROR 1451 (23000) at line 1: Cannot delete or update a parent row: a foreign key constraint fails (`rundeck`.`log_file_storage_request`, CONSTRAINT `FK_trqsa9so0qcv6okcd6fan88yf` FOREIGN KEY (`execution_id`) REFERENCES `execution` (`id`))`

All executions are linked to "log_file_storage_request" table. So the script needs modification I think.. I'll try to solve it and post a new version here (for those who will get this error too, I guess on newer rundeck version it happens)

**Comment by Dmitry1987** [comment]
ok solved it, for anyone who gets this error too (we run clustered mode with logs in S3, maybe this is why my table is a bit different),
just add this before the 1st delete query:
`delete from rundeck.log_file_storage_request where execution_id=$job `
it will delete the "dependent" row and allow to proceed to execution row delete.

Thanks @unicolet  and @dooblem for sharing.

**Comment by dooblem** [comment]
Thanks. You're right, our Rundeck version is pretty old.

**Comment by exjet** [comment]
+1
Having a built in automated solution would be super helpful!

**Comment by calebcall** [comment]
I find it asinine that this functionality is not already there.  Log/job cleanup should be considered an essential "feature" (hate to call it a feature).

**Comment by vidalsysadmin** [comment]
Any news about this feature ?

**Comment by jippi** [comment]
Doubt it will happen, the ticket is "archived" without being fixed :) 

https://trello.com/c/pS6JuMau/10-purge-execution-history

**Comment by gschueler** [comment]
@jippi this is the correct Trello card: https://trello.com/c/OQqroc0A

it is still open.

**Comment by Dmitry1987** [comment]
I forgot to mention, that we keep our logs on S3 bucket, so I just applied lifecycle policy of 30 days and logs get rotated...  so the script takes care of mysql rows of each log, and S3 rotation deleted the old files. for now all this works with no issues :) , but yeah, the feature seems like basic one that I'd expect to be implemented in version 0.0.1  :D

**Comment by lefthand** [comment]
I made some further updates on the shell script posted earlier including DELETES for the workflow tables:
https://gist.github.com/lefthand/6014f0bd108281c4318f21efedefe6b7

**Comment by sanshinanian** [comment]
Please help me. I need to count a certain period of time rundeck of a job update, for example, from 2017-05-01 to 2017-05-03 a job update how many times, how to write this API?
Begin= XX & end= will not use
my mail sry-2004@163.com；thanks

**Comment by ahonor** [comment]
@sanshinanian Can you clarify your question. What do you mean by "job update how many times"?

**Comment by axensec** [comment]
Right now the web interface allows to perform a bulk delete of executions BUT you can only delete 20 executions each time, because each page have a max of 20 items.    
If you want to delete all the executions, the manual process can be slow and annoying.  

I've found a solution to this:
If you open the browser's console in Firefox and check the GET request when accessing the Activity page, you will see that the url is something similar to this:
`http://YOUR-RUNDECK-SERVER.com/project/YOUR_PROJECT/activity?offset=0&max=20`

If you modify this url and increase the `max` value to a number greater than the total amount of executions in the current project, and then paste this new URL in the browser you will get all the executions in one single page and will be able to delete them all at once using the Bulk Delete button at the bottom of the page.

Just sharing this *tip* in case any one need it.

**Comment by calebcall** [comment]
I wouldn't consider 20 at a time a bulk delete. I have more than 100k executions a day and that's growing every day. 20 at a time does nothing for me.

**Comment by soymsk** [comment]
I re-implemented auto purge tool for my use-case (each job has its own max history size, etc..)
https://github.com/soymsk/rundeck_history_purge_tool

but yes, I wish to have this feature in rundeck.

**Comment by suslikas** [comment]
Play with offsets... or make lot of call's via api... This functionality **must be** in core system, not as additional tools. On this moment i use workaround with cron: 

`find /var/lib/rundeck/logs -type f -mtime +5 -name '*.json' -o -name '*.rdlog' -delete`

`delete e, b, w, ws, wws from base_report as b, execution as e, workflow_workflow_step as wws, workflow as w, workflow_step as ws where e.date_started <= NOW() - INTERVAL 5 DAY and wws.workflow_commands_id=w.id and wws.workflow_step_id=ws.id and e.workflow_id=w.id and b.id=e.id;`

**Comment by shamil** [comment]
I use `rundeck-cli` to remove old jobs, here is example script:

```shell
#!/bin/bash -e

# export required vars
export RD_URL=http://localhost:4440 RD_USER=admin RD_PASSWORD=admin RD_HTTP_TIMEOUT=300

# make sure rd command is in the PATH
which rd &>/dev/null

del_executions() {
    local project=$1
    
    while true; do
        rd executions deletebulk -y -m ${RD_OPTION_BATCH:-20} --older ${RD_OPTION_OLDER_THAN:-3d} -p $project || break
        sleep 1s
    done
}

# delete executions for each project
for p in $(RD_FORMAT=json rd projects list | jq -r .[]); do
    del_executions $p
done

exit 0
```

**Comment by dandunckelman** [comment]
Thanks for everyone's contributions here.
- Especially @shamil & @suslikas 

I just got bit by this when we ran out of inodes.
- The rundeck service stopped and I couldn't get it to start back up.
- After rebooting, the service started properly (a lot of inodes were probably cleared).
- I then found that `/var/lib/rundeck/logs` was using `554,995` inodes (our volume has `1,125,452` inodes).  So I started looking for solutions to clear out old logs.

**Comment by looot-ooo** [comment]
Ran into the same issue, so just wanted to summarise what I've been doing so far.

1. Added couple of indexes as described here -- https://groups.google.com/d/msg/rundeck-discuss/W9sYZQK0dW8/psQtpzuqMywJ for the `base_report` and `execution` tables. 
2. Added few other indexes to improve the load times for the activity pages -- https://github.com/rundeck/rundeck/issues/1547#issue-116663692
3. The script by @shamil https://github.com/rundeck/rundeck/issues/357#issuecomment-341955141 to cleanup the older executions
4. Ran the SQL queries that @yobryon shared -- https://github.com/rundeck/rundeck/issues/1654#issuecomment-192058183 (added an index)
5. Did an `OPTIMIZE TABLE` for the `base_report`, `executions` and the three `workflow` tables. 

Once the initial cleanup is done, it would be a good idea to schedule steps `4` & `5` daily/weekly as the case may be.

**Comment by varkey** [comment]
Ran into the same issue, so just wanted to summarise what I've been doing so far.

Added couple of indexes as described here -- https://groups.google.com/d/msg/rundeck-discuss/W9sYZQK0dW8/psQtpzuqMywJ for the base_report and execution tables.
Added few other indexes to improve the load times for the activity pages -- #1547 (comment)
The script by @shamil #357 (comment) to cleanup the older executions
Ran the SQL queries that @yobryon shared -- #1654 (comment) (added an index)
Did an OPTIMIZE TABLE for the base_report, executions and the three workflow tables.
Once the initial cleanup is done, it would be a good idea to schedule steps 4 & 5 daily/weekly as the case may be.

**Comment by Krishnababu505** [comment]
Hello All,

This script works fine for me till yesterday but today it shows deleting jobs but it is keep on executing same steps it's not going to further.

echo " * Deleting job: $job"
 rm -rf $j/logs/$job.*

Deleting job: 3104429
 14:48:45 | | | rm -rf ./XYZ/job/81476133-1da6-40fc-7d3c-abf2caedd1f9/logs/3104429.*

Later it is failing with below timeout error after 2hr

15:29:20 | | | Result: 2147483647

15:29:21 | | | Failed: NonZeroResultCode: Result code was 2147483647
 | ANY04210451 [console] |
 15:29:21 | | | Cancellation while running step [1]

could you please help me what causes this issue. is this caused due to any permission issue ??

Thanks In Advance.
 Regards,
 Krishna

**Comment by gschueler** [comment]
https://docs.rundeck.com/docs/history/version-3.1.0.html#execution-cleaner
