### ISSUE TITLE
Can't use 'rd run' with a job option starting with '@'

### ISSUE THREAD

**Issue by puremourning** [rundeck/rundeck#3590]
**Describe the bug**

`rd run` uses a special syntax for file attachments `@something`. This prevents using string options which start with `@`, like perforce labels.

**My Rundeck detail**

* Rundeck version: 2.10.2
* install type: rpm
* OS Name/version: RedHat 6.5
* DB Type/version: mysql
* RD - Rundeck API Client Tool (v1.0.22) -

**To Reproduce**
1. Create a job with a string option name Label
2. Try and execute the job with `rd run -p PROJECT -j JOB -- -Label @now`

**Expected behavior**
The job option should be set to the value '@now'

**Actual behaviour**
rd run fails with:

```
Input error for [run]: File Option -Label: File cannot be read: now
You can use: "run help" to get help.
```

**Additional context**

Perforce labels are identified as @labelname, @now meaning the head revision.

**Comment by puremourning** [comment]
Turns out you can use `\@now`

**Comment by puremourning** [comment]
I take it back. `\@now` doesn't really work, it just happens that it works with _my_ underlying scripts. This really is a problem, unless there is som eundocumented solution?

**Comment by gschueler** [comment]
I think this is a bug in `rd`, it parses `-opt @value` as intending to upload a file as a file option, however it should have a way to pass a literal `@value` as an option value.

A potential workaround, use API v 17 or earlier.  The file upload processing is only enabled for API v18+, so if you do `export RD_URL=http://server/api/17` you would skip that input processing.

Can you file this on rundeck-cli?

**Comment by puremourning** [comment]
Thanks for the response :) Will do!

**Comment by puremourning** [comment]
Workaround appears to work, thanks. Opened: https://github.com/rundeck/rundeck-cli/issues/186

**Comment by puremourning** [comment]
Close in favour of rundeck-cli issue.
