### ISSUE TITLE
Job Timeout & Kill Job STILL Does Not Halt Job Steps

### ISSUE THREAD

**Issue by dirkniblick** [rundeck/rundeck#3597]
**Describe the bug**
The _Job Timeout_ and  _Kill Job_ features **still** do not actually **kill the remote job** despite #2911 being marked as closed by [Release 2.11.0](http://rundeck.org/news/2018/04/27/rundeck-2.11.0.html).

**My Rundeck detail**

* Rundeck version: 2.11.3-1
* install type: RPM
* OS Name/version: CentOS (server and remote host)
* DB Type/version: MySQL

**To Reproduce**
I created a job which runs a sleep statement (`/bin/sleep 60`) on a remote host (via either a command or inline script) with a timeout set. The sleep command continues to run on the remote host after the job is timed out.  The same is true when using the Kill Job button.

**Expected behavior**
Per [documentation](http://rundeck.org/docs/manual/jobs.html#timeout): "You can set a maximum runtime for a job. If the runtime exceeds this value, the job will be halted (as if a user had killed it.)"  [Also](http://rundeck.org/docs/manual/jobs.html#killing-jobs), "Jobs that are currently running can be Killed immediately."

**Actual behavior**
The execution halts, but the step(s) don't. Now, I realize the language up there doesn't say that the steps are halted, but I would assume that the execution halting while orphaning its steps is not "Expected Behavior" (it certainly wasn't to me).

**Screenshots**
![rundeckkilljobfail](https://user-images.githubusercontent.com/30664752/41994592-8a28b48e-7a14-11e8-8972-b499135e2b45.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: newest

**Comment by dirkniblick** [comment]
It seems there are (still) other reports of this: #1038, #1045, #1238, #2235, #3160, #3008, #2015

**Comment by ProTip** [comment]
Hi @dirkniblick , do you happen to have `Force PTY` checked in the SSH executor settings for the project? This setting will cause commands to be terminated when the SSH session ends(for any reason including the timeout).

**Comment by dirkniblick** [comment]
@ProTip, I ticked that box and now the jobs timeout and kill properly.  Thank you, thank you.

This should be in the Rundeck documentation, folks.

**Comment by fishyimm** [comment]
same here when i checked `Force PTY` in project configuration, running job got terminated(job process) properly for both timeout and kill job manually.

**Comment by kxr0623** [comment]
> Hi @dirkniblick , do you happen to have `Force PTY` checked in the SSH executor settings for the project? This setting will cause commands to be terminated when the SSH session ends(for any reason including the timeout).

Hi, I meet the same problem of failling kill some jobs manully, some time. can you tell me how to set the `Force PTY` in SSH  executor in detaill? I cannot find the configure file and I don't know where to set that for my Rundeck. Thank you.

**Comment by fishyimm** [comment]
Hi @kxr0623 , please check this out https://github.com/rundeck/rundeck/issues/3160#issuecomment-465889767

**Comment by kxr0623** [comment]
> Hi @kxr0623 , please check this out [#3160 (comment)](https://github.com/rundeck/rundeck/issues/3160#issuecomment-465889767)

haha,Thank you for your answer. But I found that my Rundeck version is too old that without the setting of Force PTY....SO the way cannot work for me. Anyway, thank you.

**Comment by fdevans** [comment]
Seems like this is resolved.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team

**Comment by lroehrs** [comment]
@fdevans It would be great to find this option explained in the documentation:

https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html
