### ISSUE TITLE
Add static ordering to job options instead of always sorted by name

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#361]
Allow job options to be ordered in the GUI based on definition order in XML
- [x] add order index to options 
- [x] set index when loading in xml/yaml
- [x] xml preserves input order via @preserveOrder=true attribute
- [x] yaml requires sortIndex property
- [x] update gui to display options by index order
- [x] job execute form
- [x] option summary text
- [x] argstring stored for executions
- [x] work with cascading options, update toposort to preserve index ordering
- [x] preserved when editing job and options
- [x] add documentation

**Comment by ssbarnea** [comment]
It seems that this bug was not solved or there is a regression on the 2.6.1, I see no option to order the options and they are clearly sorted alphabetically instead of the the original order.

**Comment by gschueler** [comment]
@ssbarnea there is not yet GUI support for this, but XML/YAML job definitions can be reordered before import to preserve the option order

* see: [Job XML - Options - preserveOrder](http://rundeck.org/docs/man5/job-xml.html#options)
* see: [Job YAML - Options](http://rundeck.org/docs/man5/job-yaml.html#options)

ref #1002
