### ISSUE TITLE
Scheduled Job does not run regulary

### ISSUE THREAD

**Issue by Wolfram23** [rundeck/rundeck#3611]
**Describe the bug**
A Job which is scheduled to run every day at 2:00 am does not run every day. 

It there a way to see if scheduled job didn't run?

Schedule from job definition export:
```
-<schedule>
<month month="*"/>
<time seconds="0" minute="00" hour="02"/>
<weekday day="*"/>
<year year="*"/>
</schedule>
```
**My Rundeck detail**
* Rundeck version: 2.10.0-1 
* install type: deb
* OS Name/version:  ubuntu 16.04
* DB Type/version:  mysql

**To Reproduce**
?

**Expected behavior**
Job should run every day 2:00 am

**Screenshots**
![runddeckbug](https://user-images.githubusercontent.com/40487826/42035719-ea350efc-7ae3-11e8-98ea-a7acfc8451d5.png)
We updated the schedule on 17.06.2018 from 1:15 to 2:00am. The screenshort is from 28.06.2018.

**Desktop (please complete the following information):**
 - OS: Win 10 Pro 1709
 - Browser Chrome
 - Version 66.0.3359.170

**Comment by rdoering** [comment]
Is there any progress?
