### ISSUE TITLE
Documentation: MS SQL Server not in the section with the other databases

### ISSUE THREAD

**Issue by frachel** [rundeck/rundeck#3616]
The Administrator Guide has a section "Setting up a RDB Datasource", but it doesn't contain the info for SQL Server (which led me to believe it wasn't supported).

[http://rundeck.org/docs/administration/setting-up-an-rdb-datasource.html]()

However - in the Installation Guide, in the "Install on Windows" section, there are instructions for using SQL Server

[http://rundeck.org/docs/administration/installation.html#mssql-as-a-backend]()

I'd suggest moving the info from the Installation guide to the Administrator Guide.

This is in the version 2.11.4 documentation.

**Comment by gschueler** [comment]
Our documentation project has moved to a new repo: https://github.com/rundeck/docs

Do you mind filing this under the issues https://github.com/rundeck/docs/issues there?

Thanks!

**Comment by frachel** [comment]
Recreated in documentation project issue tracker as per above.
