### ISSUE TITLE
Add an API endpoint to perform a simple healthcheck

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#3628]
**Is your feature request related to a problem?**
When implementing F5 load balancer, the available API endpoints may require external "parsing" in order to provide a UP/DOWN flag to check a Rundeck node's status. 

**Describe the solution you'd like**
Currently,  the available `api/14/system/info` endpoint returns a `200 OK` status if the node is up, however, the additional info may be redundant. 
A simple healthcheck endpoint ( API call ) could return a 1=up / 0=down as output value   

**Describe alternatives you've considered**
`system/info` output currently includes an endpoint which redirects to web login:

```<healthcheck href='http://<my_rundeck>/metrics/healthcheck' contentType='application/json' />```

Part of output there, could also work:

 ```{"dataSource.connection.time":{"healthy":true,"message":"Datasource connection healthy with timeout 5 seconds"},"quartz.scheduler.threadPool":{"healthy":true}}```

**Comment by ryancurrah** [comment]
I think this is related to https://github.com/rundeck/rundeck/issues/2938

**Comment by gschueler** [comment]
this was added in 3.0.0 release: https://github.com/rundeck/rundeck/pull/3692

**Comment by monsdar** [comment]
Late to the party, but as I stranded here: Anonymous access to health-check is available at /health now. Docs: https://docs.rundeck.com/rundeck-cloud/administration/cluster/loadbalancer/health-check.html
