### ISSUE TITLE
Key storage: encryption plugin supports migration feature

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#3634]
**Is your feature request related to a problem? Please describe.**

If the key storage/project storage password needs to be changed, support a way to migrate stored data using a new password. The problem is that while new contents are encrypted with the new password, old contents are unreadable.

**Describe the solution you'd like**

One idea:

* add a new "migrationPassword*" configuration setting, allowing retaining the old encryption password for a period of time
* if data cannot be decrypted using the current password, re-attempt it using the migrationPassword
* possibly have a way to re-encrypt the contents using the new password during usage
* possibly have some tool that can mass-convert encrypted contents from old to new password

**Describe alternatives you've considered**

The only workaround for project-storage: export configs manually to plaintext, modify encryption password and restart, re-import configs.
* no workaround for key storage: all passwords/keys have to be re-imported to replace the encrypted contents with newly encrypted content.

**Comment by G3NSVRV** [comment]
+1 customer: 4852
