### ISSUE TITLE
Display/popup message to user for confirmation

### ISSUE THREAD

**Issue by sujipandi** [rundeck/rundeck#3639]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**
Want to display a message to user and get confirmation to proceed further to execute jobs/steps.
For ex : A project contains five jobs and after successful execution of two jobs have to display a message to user and get confirmation from user then trigger the rest of the jobs

**Describe the solution you'd like**
Want to display a message to user and get confirmation to proceed further to execute jobs/steps

**Describe alternatives you've considered**
Need a solution for this issue

**Additional context**
![image](https://user-images.githubusercontent.com/40819681/42273307-73bef45a-7fa6-11e8-94fa-5b8630af9c2c.png)

**Comment by plambert** [comment]
Is this covered by https://trello.com/c/LPnsZ019?

**Comment by xpufx** [comment]
> Is this covered by https://trello.com/c/LPnsZ019?

That card is in the Released deck but I can't find any mention of it in the docs. Any info?
