### ISSUE TITLE
Rundeck Jobs Terminate in 'Incomplete' State

### ISSUE THREAD

**Issue by mcgurksean** [rundeck/rundeck#3640]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: Rundeck 2.11.3-1
* install type: rpm
* OS Name/version: Centos
* DB Type/version: mysql

**To Reproduce**
1. Schedule a Rundeck job via the CRON tab
2. Job executes
3. View job details
4. "incomplete" status displayed beside the build number

**Expected behavior**
Job should either complete successfully or fail (with an appropriate error message)

**Screenshots**
![incomplete_job](https://user-images.githubusercontent.com/1913745/42277285-c3c2177e-7f8e-11e8-85fa-a641025d183b.PNG)

**Desktop (please complete the following information):**
 - OS: Centos
 - Browser: Chrome
 - Version: 67.0.3396.99

**Additional context**
This only happens when the jobs are run via a schedule. When the jobs are run manually, they complete successfully.

**Comment by jyotsna01** [comment]
The rundeck job is left in "Incomplete" state and does not display logs.
