### ISSUE TITLE
rd ui: job "info" button execution show page sometimes doesn't work

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#3645]

**Comment by gschueler** [comment]
https://drive.google.com/file/d/1-K9j0grZ8FWA_cNUjHfTUlVugz3j5z-I/view?usp=sharing

**Comment by gschueler** [comment]
same video https://monosnap.com/file/oZNFRlCS7RwMqlM3MTZXg0ahbwn5ha

**Comment by jessemarple** [comment]
Moving to RD UI 3.1
