### ISSUE TITLE
rd3: gui customization needs tweeking for new nav scheme

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#3673]
Try each of the properties mentioned [here](http://rundeck.org/docs/administration/gui-customization.html) and create a screenshot for each place it is rendered.

Try long text strings (eg, ~100 characters). 

See also https://github.com/rundeck/rundeck/issues/3671

**Comment by jplassnibatt** [comment]
01.rundeck.gui.title: works, but long text messes up the gui in login section and left menu (top and bottom)
02.rundeck.gui.brand.html: works, but long text messes up the gui in login section and left menu
03.rundeck.gui.staticUserResources.enabled: works
04.rundeck.gui.logo: partially works, if the png name has a capital letter at the begin or after a dot, it won't work, for example test.test.png works; Test.test.png won't work; test.Test.png won't work.
05.rundeck.gui.logoHires: wasn't able to test this hi res.
06.rundeck.gui.logo-width: partially works, it is on top of the right section of the GUI
07.rundeck.gui.logo-height: works
08.rundeck.gui.paginatejobs.enabled: works, not needed to set it as 'true'
09.rundeck.gui.paginatejobs.max.per.page: NOT WORKING, it always shows 10, I've tried 15 and 5
10.rundeck.gui.titleLink: works
11.rundeck.gui.helpLink: works
12.rundeck.gui.navbar.background: NOT WORKING
13.rundeck.gui.realJobTree: partially working, real tree is not displayed
14.rundeck.gui.startpage: works, I have tried all options, BUT the default one is 'jobs'
15.rundeck.gui.execution.tail.lines.default: WIP
16.rundeck.gui.execution.tail.lines.max: WIP
17.rundeck.gui.enableJobHoverInfo: NOT WORKING
18.rundeck.gui.login.welcome: works, but long text messes up the gui in login section
19.rundeck.gui.login.welcomeHtml: works, but long text messes up the gui in login section
20.rundeck.gui.errorpage.hidestacktrace: works
21.rundeck.gui.job.description.disableHTML: NOT WORKING
22.rundeck.gui.clusterIdentityInHeader: works
23.rundeck.gui.clusterIdentityInFooter: works

**Comment by gschueler** [comment]
`rundeck.gui.realJobTree`: let's remove this from documentation/3.0

`rundeck.gui.enableJobHoverInfo`: needs to be removed from documentation: the job hover info is removed in 3.0

`rundeck.gui.job.description.disableHTML` vote to remove this as well, this flag was a precaution for admins wary of rendering user html, but the HTML sanitizer works fine.

@ahonor
