### ISSUE TITLE
Add user comments or tags on job executions

### ISSUE THREAD

**Issue by majkinetor** [rundeck/rundeck#3676]
Jobs fail during execution, and when they do, sometimes it is required to take some action - for example report a ticket. It would be great if a team monitoring jobs be communicated when job problem is handled (via interface and/or email notification). 

For example, on failed job execution I would like to leave a note: `Reported on Redmine #2379` or `ignore this error, it rarely shows and is self-fixing`. I would like this note to be visible when execution is reviewed by others and ideally they would receive mail upon note creation.

Additionally, Rundeck job view page could have a new tab with list of notes from all executions, but even without that the feature has a merit.

**Comment by ahonor** [comment]
+1
