### ISSUE TITLE
"On Start" job notification e-mail does not correctly pass value for ${notification.eventStatus} variable

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#3689]
**Describe the bug**
OnStart notification e-mail does not correctly pass value for ${notification.eventStatus} variable, instead the variable name i.e. "${notification.eventStatus}" is shown. 
This happens ONLY for the OnStart e-mail notification, not for OnSuccess or OnFailure.
Only when the Job is run locally (localhost)  AND the local node is NOT included in the current node definition ( only "include local node" selected) 

**My Rundeck detail**

* Rundeck version: 2.11.4
* install type: confirmed in deb, launcher, rpm
* OS Name/version: ubuntu 16.04
* DB Type/version: Mysql ( could not be replicated using other db or H2 )

**To Reproduce**
1. Create a job including _On Start_ and _On Success_ e-mail notifications. 
   Include " ${notification.eventStatus} " in the _e-mail Subject_.
2. Check the _Execute locally_ option
3. Project Node resource should NOT include the local node. Check the _înclude server node_ option to be able to run the job locally.
4. Click `Run Job Now` from the GUI. 
5. First run may not show the error. In that case, click `Edit this Job` and then `Cancel`
6. `Run Job Now` from the GUI. The OnStart e-mail notification will show the variable name instead of its value ONLY for _On Start_ . The _On Success_ notification shows the correct value. 

* The Same behavior occurs when triggering jobs using the API

**Expected behavior**
The e-mail notification Variable should be translated to the correct value: STARTING , SUCCESS, FAILED, etc

**Screenshots**
![image](https://user-images.githubusercontent.com/31705339/42714105-f23c7620-86bf-11e8-9690-63151a81311f.png)

**Additional context**
A "workaround" ( not desired in certain environments eg cluster ) is to explicitly include ALL "localhosts" in node xml file.

**Comment by shlomoa** [comment]
Same symptom, different diagnosis :-)
Happens in referenced jobs that show the status of the parent job (Started) instead of the job it self.
Two proposed solutions: 
1) Avoid sending notifications for referenced jobs.
2) Use the running (child, referenced) job's status, currently not fully supported.
BUILD : 3.0.5-20180828
Linux, Ubuntu
