### ISSUE TITLE
Git plugin doesn't create the branch if it doesn't exist

### ISSUE THREAD

**Issue by jtobard** [rundeck/rundeck#3695]
Git export plugin doesn't create the branch if it doesn't exist.

**My Rundeck detail**

* Rundeck version: 3.0.0
* install type: launcher
* OS Name/version: Mac Os
* DB Type/version: mysql

**To Reproduce**
1. Setup git plugin with a nonexistent branch.
2. Go to job list page.
3. Commit and push changes.
4. Rejected because the plugin tries to write to `master` instead of creates the new branch.

**Expected behavior**
The git plugin could create the new branch based on master or give a better error message.

**Screenshots**
<img width="1037" alt="imagen" src="https://user-images.githubusercontent.com/2894508/42763170-45679fe2-88e0-11e8-8d92-ee6a8e4f9fd4.png">

**Comment by plambert** [comment]
In some cases, the user will want to create a new branch, while in others, the branch might be mispelled.  If it's possible, perhaps we can show an error with a button for "create new branch?"

We'll also need to handle creating the branch on the origin when we push.
