### ISSUE TITLE
r3: AD authentication doesn't work

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#3699]
Using AD authentication on rundeck3 doesn't work. 
It seems the connection works OK, but when you log in with a right credential, GUI sais that the username/password are wrong. No log is shown on service.log.  

If you try to login with wrong credentials, you can see the correct log output on service.log (which I suppose means that the jaas module is connecting OK with the AD server).

Also `-Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG` doesn't seems to work using launcher, I cannot see any debug log.

**My Rundeck detail**

* Rundeck version: 3.0
* install type: launcher
* OS Name/version: MacOS 10.3
* DB Type/version: mysql

**To Reproduce**
1. Configure $RDECK_BASE/server/config/jaas-activedirectory.conf file with AD parameters.
2. Run rundeck with LDAP authentication:
```java  -Dloginmodule.name=activedirectory -Dloginmodule.conf.name=jaas-activedirectory.conf  -Drundeck.jaaslogin=true -jar rundeck-3.0.0-SNAPSHOT.war``` 
3. Try to login with wrong credentias, you will see the correct logs output on the service.log
4. Try to login with right credentias, GUI wont login and no logs will be displayed on service.log

**Expected behavior**
Login with AD should work.

**Screenshots**

* Correct credentials
<img width="505" alt="screenshot 2018-07-16 15 36 15" src="https://user-images.githubusercontent.com/6034968/42779311-1071df90-890e-11e8-9ede-b1d5ae9d42ba.png">

* No log
<img width="1435" alt="screenshot 2018-07-16 15 35 58" src="https://user-images.githubusercontent.com/6034968/42779318-14d98dee-890e-11e8-945b-7911e6283714.png">

* wrong credentials
<img width="539" alt="screenshot 2018-07-16 15 36 36" src="https://user-images.githubusercontent.com/6034968/42779326-19cf9960-890e-11e8-8d89-705620a36ea8.png">

* logs seems OK
<img width="1283" alt="screenshot 2018-07-16 15 36 32" src="https://user-images.githubusercontent.com/6034968/42779329-1e25130a-890e-11e8-8bee-c53a63337311.png">

**Desktop (please complete the following information):**
 - OS: Macos 10.3
 - Browser chrome
 - Version -

**Comment by sjrd218** [comment]
Additional authentication logging can be enabled in dev mode by adding:

```logger 'grails.plugin.springsecurity.web.authentication.GrailsUsernamePasswordAuthenticationFilter',DEBUG,['STDOUT'],false```

to the logback.groovy file, which might provide additional information when debugging these types of issues.

**Comment by sjrd218** [comment]
I set up a samba AD to test against, and the only way it worked for me was to set `forceBindingLogin="true"` in the jaas module for the active directory configuration.

**Comment by gschueler** [comment]
@sjrd218 i was able to debug the issue and have a fix for it
