### ISSUE TITLE
r3: Rundeck3 with oracle DB doesn't work

### ISSUE THREAD

**Issue by ltamaster** [rundeck/rundeck#3700]
Weird errors  using an Oracle 12c database with Rundeck3.
I  used ojdbc8.jar driver and the  custom oracle dialect for rundeck:
https://github.com/jquick/rundeck_oracle_dialect

**My Rundeck detail**

* Rundeck version: Rundeck3
* install type: launcher
* OS Name/version: MacOs 10.13
* DB Type/version: Oracle 12c

**To Reproduce**
1. Configure rundeck-config.properties with oracle connection, for example:

```
dataSource.url = jdbc:oracle:thin:@server:1521:orcl
dataSource.driverClassName = oracle.jdbc.driver.OracleDriver
dataSource.username = RUNDECKUSER
dataSource.password = pasword
dataSource.dialect = com.rundeck.hibernate.RundeckOracleDialect
```

2. Start rundeck
3. First I got errors with index (which I fixed to move one)

For example, for ScheduleExecution Domain class, the name of this index is not valid for oracle: _IDX_SCHEDULED_EXECUTION_PROJECT (underscore is not allowed and the name is too long)

https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/domain/rundeck/ScheduledExecution.groovy#L204

Same for:
https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/domain/rundeck/Storage.groovy#L69
https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/domain/rundeck/Storage.groovy#L70
https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/domain/rundeck/Project.groovy#L38

4.- After fixed that, I got 
```
Hibernate:
    select
        this_.id as y0_
    from
        execution this_
    where
        this_.date_started is not null
        and this_.date_completed is null
        and this_.server_nodeuuid is null
        and this_.date_started<?
        and (
            this_.status is null
            or this_.status<>?
        )
2018-07-16 15:51:48.425  WARN --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 0, SQLState: null
2018-07-16 15:51:48.427 ERROR --- [           main] o.h.engine.jdbc.spi.SqlExceptionHelper   : Failed to validate a newly established connection.
2018-07-16 15:51:48.449 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.hibernate.exception.GenericJDBCException: could not prepare statement

```
For adding the jdbc driver dependencies I first tried using the branch `properties-loader`. I started rundeck with: `java -Dloader.path=server/lib,WEB-INF/lib,WEB-INF/classes,WEB-INF/lib-provided,jdbc  -jar rundeck-3.0.0-SNAPSHOT.war`

I put the JDBC jars on `jdbc` folder 

Then, I built rundeck adding the jars files to the rundeckapp project. I got the same result.

In the second case the error is random , after than I got this error I tried to start Rundeck again and it worked.

**Expected behavior**
Rundeck should work with Oracle DB

**Comment by ltamaster** [comment]
With the defualt dialect, the schema is not created competelly. It has the same behaviour than 2.x

**Comment by gschueler** [comment]
closing this
