### ISSUE TITLE
SSHProtocolFailure: Session.connect: java.net.SocketException: Connection reset on FreeBSD 11.1 Nodes

### ISSUE THREAD

**Issue by DerDummePunkt** [rundeck/rundeck#3723]
**Describe the bug**
Most likely related to https://github.com/rundeck/rundeck/issues/2774

When executing jobs on a node that runs the stable FreeBSD Version 11.1 the jobs sporadically fail with

`Failed to remove remote file: /tmp/jobID-ActivityID-NodeName-dispatch-script.tmp.sh`
`Failed: SSHProtocolFailure: Session.connect: java.net.SocketException: Connection reset` 

The failure rate for this type of failure is around 50% on our FreeBSD 11.1 nodes. The error occurs on any number of jobs, regardless of the details of their individual definition.

Other FreeBSD versions as an OS for nodes have not been tested.
This failure never occurs for nodes which run various Linux distributions or kernel version

**My Rundeck detail**

* Rundeck version: 2.11.3-1
* install type: launcher
* OS Name/version: alpine Linux 3.8
* DB Type/version: postgres

**To Reproduce**
1. run any job that connect to a node that runs FreeBSD v11.1 as its OS

**Expected behavior**
The job executes without a failure

**Comment by yogeshkumark** [comment]
+1
