### ISSUE TITLE
use ldap activedirectory for ordinary user and local file for admin user  

### ISSUE THREAD

**Issue by nauybool** [rundeck/rundeck#3731]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: [2.10.6]
* install type: [launcher]
* OS Name/version: [redhat 7.5]
* DB Type/version: [sqllite ]

I want to use activedirectory  for ordinary user and realm.properties to control acl, and realm.properties for admin 

**my ldap-activedirectory.conf**

activedirectory {
  com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule required
      debug="true"
      contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
      providerUrl="ldap://bsapp.lufax.app:389"
      bindDn="myuser@xxxxx"
      bindPassword="passwd"
      authenticationMethod="simple"
      forceBindingLogin="true"
      userBaseDn="dc=paicdom,dc=local"
      userRdnAttribute="sAMAccountName"
      userIdAttribute="sAMAccountName"
      userPasswordAttribute="unicodePwd"
      userObjectClass="organizationalPerson"
      roleBaseDn="dc=paicdom,dc=local"
      roleNameAttribute="cn"
      roleUsernameMemberAttribute="memberUid"
      roleMemberAttribute="member"
      roleObjectClass="group"
      cacheDurationMillis="300000"
      supplementalRoles="user"
      reportStatistics="true"
      timeoutRead="10000"
      timeoutConnect="20000"
      nestedGroups="false"
      storePass="true";

  org.rundeck.jaas.jetty.JettyAuthPropertyFileLoginModule required
    debug="true"
    file="/wls/applications/rundeck/server/config/realm.properties"
    refreshInterval="60"
    caseInsensitive="true"
    useFirstPass="true"
    tryFirstPass="true";

  org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
    debug="true"
    file="/wls/applications/rundeck/server/config/realm.properties"
    refreshInterval="60"
    caseInsensitive="true"
    useFirstPass="true"
    tryFirstPass="true";
};

**my launcher** 

java  -XX:+UseCompressedOops -Xms4g -Xmx4g -XX:NewSize=2g -XX:MaxNewSize=2g -XX:SurvivorRatio=22 -XX:MetaspaceSize=64M  -XX:MaxMetaspaceSize=512M -Dserver.http.port=8001 -Dserver.web.context=/lothric -Dloginmodule.conf.name=ldap-activedirectory.conf  -Dloginmodule.name=activedirectory  -jar /wls/applications/rundeck/rundeck-launcher-2.10.6.jar

**my realm.properties like this:**
admin:password00,user,admin
myuser:-,user,admin

I can login use "myuser" by ldap ad, but can not login use "admin".....

can anyone help???

**Comment by JesusRo** [comment]
Hi

You may add `-Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=ALL` to have all the relevant info about authentincation process, don't forget to add `debug="true"` to each module.
It should be very clear about where the issue is.

Also not really sure about module ussage, but in case it could help, this is what a have for authentication via LDAP or PAM or File, all "working" at the same time on v2.11
```
RDpropertyfilelogin {

  org.eclipse.jetty.jaas.spi.PropertyFileLoginModule optional
        debug="true"
        file="/##REMOVED##/rundeck/server/config/realm.properties";

    com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule optional
        debug="true"
        contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
        providerUrl="ldap://##REMOVED##:389"
        bindDn="CN=##REMOVED##"
        bindPassword="##REMOVED##"
        authenticationMethod="simple"
        forceBindingLogin="true"
        userBaseDn="DC=##REMOVED##"
        userRdnAttribute="distinguishedName"
        userIdAttribute="sAMAccountName"
        userPasswordAttribute="unicodePwd"
        userObjectClass="user"
        forceBindingLoginUseRootContextForRoles="true"
        roleBaseDn="OU=##REMOVED##"
        roleNameAttribute="sAMAccountName"
        roleMemberAttribute="member"
        roleObjectClass="group"
        roleSearchSubtree="true"
        cacheDurationMillis="300000"
        supplementalRoles="user"
        reportStatistics="true"
        timeoutRead="10000"
        timeoutConnect="20000"
        storePass="true"
        tryFirstPass="true"
        rolePrefix=" Access"
        nestedGroups="true";

  org.rundeck.jaas.jetty.JettyPamLoginModule optional
        debug="true"
        service="sshd"
        supplementalRoles="user"
        storePass="true"
        tryFirstPass="true";

  org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule sufficient
        debug="true"
        tryFirstPass="true"
        file="/##REMOVED##/.rundeck/server/config/realm.properties";
};
```
