### ISSUE TITLE
rd3: When running a Job, which refers an unexistent Storage Key, execution succeeds with no errors ( GUI or logs) 

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#3732]
**Describe the bug**
Execution of a job with a missing Key, referred as an option, succeeds with no errors ( either in GUI or logs, regardless of the LogLevel )
For the same case, in previous versions ( 2.11.x),  job execution FAILS. No further info in GUI. However, `service.log` shows a WARNING message ( in relation to missing key ) and a generic ERROR related to execution failure ( a more specific ERROR info would have been expected ).  

**My Rundeck detail**

* Rundeck version: 3.0.0
* install type: WAR
* OS Name/version: 
* DB Type/version: 

**To Reproduce**
1. Create a Job that includes:  
     - A Job Option > Option Type: Secure > referred to an unexistent Storage path
     - A Step that refers the option ( e.g. an `echo` ) 
( alt. import a job that refers to a storage key into another instance where the same key is not present )

2. Run Job Now >> Execution shows as Succeeded. No error logs

**Expected behavior**
Job execution should FAIL, and a clear message pointing to the missing Key should be expected ( this was the behavior in previous versions)

**Screenshots**
Unexistent Key in Option
![image](https://user-images.githubusercontent.com/31705339/43208912-775e67fe-8ff9-11e8-95c3-05f38c2f8eae.png)

Succeeded Job Execution in 3.0.0
![image](https://user-images.githubusercontent.com/31705339/43208695-fab38446-8ff8-11e8-9ae2-0fcbafa148fc.png)

Same test in 2.11.x (same job) 
![image](https://user-images.githubusercontent.com/31705339/43209640-26ebe844-8ffb-11e8-8b6f-250be86ed196.png)

`service.log` in 2.11.x
![image](https://user-images.githubusercontent.com/31705339/43209228-2010646a-8ffa-11e8-8351-afbbf82930a2.png)
(the logs related to missing Key2 were removed, for clarity)

**Comment by ltamaster** [comment]
https://github.com/rundeck/rundeck/pull/4192
