### ISSUE TITLE
rd3: Rundeck logo not present when app is deployed in a container

### ISSUE THREAD

**Issue by sjrd218** [rundeck/rundeck#3734]
When the Rundeck war is deployed into a container in a context other than the root context, the Rundeck logo does not appear.

**Comment by sjrd218** [comment]
<img width="911" alt="rundeck_-_login" src="https://user-images.githubusercontent.com/36643360/43222939-1dbb8ccc-9017-11e8-9c22-d36edf023e31.png">

**Comment by sjrd218** [comment]
It looks like the url that is referenced in the css defining the background image of the icon uses a `/static/....` path which will not work in a container because the app will be deployed into a context.

**Comment by jessemarple** [comment]
@sjrd218 can we connect on this issue. The logo is now an image, which includes the text and the chevron . . . however, it is still referencing the static/images location. 

If I can get a better idea as to your context I might be able to help solve this.

**Comment by sjrd218** [comment]
This is fixed in the latest build.
