### ISSUE TITLE
latest (3.0.0...) rundeck RPM is not signed?

### ISSUE THREAD

**Issue by jmuf** [rundeck/rundeck#3759]
The latest RPM available from https://bintray.com/rundeck/rundeck-rpm/rundeck/3.0.0.20180727-1.201807272200 is not signed anymore:
```
$ rpm -qip http://dl.bintray.com/rundeck/rundeck-rpm/rundeck-3.0.0.20180727-1.201807272200.noarch.rpm | grep Signature
Signature   : (none)
```
Older versions (such as 2.11.5-1.56.GA)  are indeed signed.
Is this a glitch, or perhaps deliberate to discourage using the -3 prereleases?

**Comment by ProTip** [comment]
Hi @jmuf this is a glitch from changes in package signing. The rpm packages should show as signed now.

**Comment by alphacc** [comment]
thanks, WFM.

**Comment by alphacc** [comment]
Do you think that long term we could have a 2.x and a 3.x repo or you do not plan to support 2.x anymore after 3.X release ?

**Comment by jmuf** [comment]
Confirm OK:
```
$ rpm -qip http://dl.bintray.com/rundeck/rundeck-rpm/rundeck{,-config}-3.0.0.20180727-1.201807272200.noarch.rpm | grep Signature
Signature   : RSA/SHA1, Mon 30 Jul 2018 11:59:38 AM CEST, Key ID 90770e1be2d1065b
Signature   : RSA/SHA1, Mon 30 Jul 2018 12:08:38 PM CEST, Key ID 90770e1be2d1065b
```
