### ISSUE TITLE
Jobs referencing other jobs with importOptions: true aren't imported correctly

### ISSUE THREAD

**Issue by brutus333** [rundeck/rundeck#3760]
**Describe the bug**
If in the job definition I choose importOptions: true and I export to git via SCM Plugin the job definition, when I am trying to import it on another instance the importOptions disappear.
I am using Export UUID Behavior: preserve on source rundeck instance and Import UUID Behavior: archive on destination rundeck instance.

**My Rundeck detail**

* Rundeck version: 2.11.5-1
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: postgres

**To Reproduce**
1. Create one simple job with one option
2. Create another job that reference the job created at step 1 and check Import Options?
3. Setup SCM export plugin
4. Commit jobs definitions
5. On another project (or another instance) setup SCM import plugin with same repo as the one used at step 3.
6. Import jobs and check the result

**Expected behavior**
The definition of imported job should match the source one on Import Options.
The state on the import changes should be clean.

**Screenshots**
![image](https://user-images.githubusercontent.com/6450276/43395252-18b08460-9406-11e8-95ef-c460ffaf01d8.png)

**Desktop (please complete the following information):**
 - OS: Windows 2008
 - Browser: Chrome
 - Version: 66.0

**Additional context**

**Comment by mveroone** [comment]
Could it be fixed by https://github.com/rundeck/rundeck/pull/3442 ?

**Comment by mveroone** [comment]
Duplicate of https://github.com/rundeck/rundeck/issues/3429

**Comment by brutus333** [comment]
Thank you. I will close the issue.
