### ISSUE TITLE
Authentification with a encrypted password don't work

### ISSUE THREAD

**Issue by pchevallereau** [rundeck/rundeck#3768]
**Describe the bug**
Authentification with a encrypted password don't work 

**My Rundeck detail**

* Rundeck version: 3.0.0
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: mariadb/mysql

**To Reproduce**
[](http://rundeck.org/docs/administration/security/authenticating-users.html#propertyfileloginmodule)

1. Encrypt your password with the java tool
2. Insert it in the realm.properties file 
3. Restart rundeck service
4. Try authentification, it's failed

**Expected behavior**
My configuration work on version 2.10.8 but not on 3.0.0

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Firefox
 - Version 52.4.1

**Comment by sjrd218** [comment]
Can you try launching Rundeck with the following system properties and report back the result:
-Drundeck.jaaslogin=true -Dloginmodule.name=RDpropertyfilelogin

**Comment by pchevallereau** [comment]
Hi, 

I have add the -Drundeck.jaaslogin=true in "/etc/rundeck/profile", this permit the connection with a encrypted password.
This point missing in the documentation?

Thanks @sjrd218

**Comment by gschueler** [comment]
@sjrd218 can you make a PR for that change to rundeck/docs ?
