### ISSUE TITLE
resource.xml file is not created

### ISSUE THREAD

**Issue by damlit** [rundeck/rundeck#3770]
It is my first post, so hello world! :)
and sorry for my english, i am learning.
 
**Describe the bug**
When I create project my rundeck 3.0 don’t create this file resource.xml in project folder, when I tried create it self, this didn't work too.
My problem is similar like [HERE](https://github.com/rundeck/rundeck/issues/3185), but I have folder with name of project -> empty folder 'acls' and folder 'etc' with 'project.properties.imported' file. 
I tried solution with that link, but this didn't work too (add `rundeck.projectsStorageType=db` in rundeck-config).
And in etc->project.properties I have lanes about they said
(
`resources.source.1.type=file`
`resources.source.1.config.file=C:/Users/Comarch/Documents/rundeck/projects/${project.name}/etc/resources.xml`
`resources.source.1.config.format=resourcexml`
`resources.source.1.config.includeServerNode=true`
`resources.source.1.config.generateFileAutomatically=true`
).

**My Rundeck detail**
* Rundeck version: 3.0.0
* install type: war
* OS Name/version: Windows 10
* DB Type/version: 

**Expected behavior**
I want file resource.xml when I create new project, that could add news noods.

**Additional context**
On another computer with the same system is the same problem

**Comment by kshitijmotwani** [comment]
Similar problem in Linux RPM install. Someone please help..

**Comment by jmalmin** [comment]
I am also seeing this still today with 3.0.6 version. Please let us know if this intended.

**Comment by ahonor** [comment]
Starting in 3.0, when creating a project a "Local" node source is configured automatically.  This means the file source type must be defined after the project is created.

**Comment by lubry** [comment]
Hi @damlit @kshitijmotwani for reference see this link [https://github.com/rundeck/rundeck/issues/3185](url)

Thanks.

**Comment by fdevans** [comment]
We apologize if this issue was missed.  If you are still experiencing this issue on the current version of Rundeck please let us know by opening a new Issue request with version and steps to reproduce.  If you are an Enterprise customer our support personnel are ready to help.
Thank you,
The Rundeck Team
