### ISSUE TITLE
Job fails if job nodeset intersection is empty

### ISSUE THREAD

**Issue by eblikstad** [rundeck/rundeck#3781]
I'm trying out the new job node intersection in a job step with a job reference. My job fails when the job nodeset intersection is empty even if the nodeset empty continue has been set. The job setting "if node set is empty" does not seem to apply to empty intersection nodesets.

* Rundeck version: 2.10.6
* install type: launcher
* OS Name/version: Windows 2012 R2
* DB Type/version: SQL Server 2016 SP2

**To Reproduce**
1. Create a job B with a inline script which output a text string.
2. Create a job A with a job reference to job B and select create node intersection.
3. In job A add a job filter with at least 2 nodes
4. In job A edit the job reference intersection filter and specify one of the two nodes specified in the job filter
5. Set continue execution for if nodeset is empty in job A & B

**Expected behavior**
The referenced job should run on the node in the resulting intersecting nodeset of the node filter in job A and the referenced job intersection filter.

**Result**
The job fails on the node not in the nodeset intersection.

_No nodes matched for the filters: MultiNodeSelector{nodenames=[]}
Failed dispatching to node test-ebl22: com.dtolabs.rundeck.core.execution.workflow.steps.StepException: No nodes matched for the filters: MultiNodeSelector{nodenames=[]}_

**Comment by dd5154** [comment]
I have a similar issue with a job referencing another job with a single node specified. If the job runs from cron it fails, if I run it manually, it passes.
NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[server]}

Rundeck 3.0.22-20190512
