### ISSUE TITLE
RD3 java.security.auth.login.config or loginmodule.name seems to be ignored

### ISSUE THREAD

**Issue by babs** [rundeck/rundeck#3782]
**Describe the bug**

With java.security.auth.login.config set to the proper file and loginmodule.name pointing to the proper name, it seems it still use the RDpropertyfilelogin definition and the realm file.
Login with realm defined account works, LDAP fails without network traffic (nothing on tcp 636 nor 389)

It was working perfectly on 2.11.x with the same config.

**My Rundeck detail**

* Rundeck version: 3.0.0-20180727
* install type: deb
* OS Name/version: Debian Stretch
* DB Type/version: mariadb

**To Reproduce**

Configure an ldap based auth and try to login.

**Expected behavior**

I'd expect it to connect to my ldap server and try an authentication

**Additional context**

It was working perfectly fine on the very same server, pointing to the very same LDAP before the upgrade from 2.11.4 to 3.0.0.

**Comment by babs** [comment]
same as #3757, `-Drundeck.jaaslogin=true` is mandatory to make it work

**Comment by ecarrascos** [comment]
Hi babs!

[Rundeck 3.0.1 has been released!](http://rundeck.org/news/2018/08/03/rundeck-3.0.1.html) 

This Release includes the [fix that restores the jaas config compatibility with 2.x](https://github.com/rundeck/rundeck/pull/3758). Also, check the [Documentation](http://rundeck.org/docs/administration/security/authenticating-users.html), as it was updated to reflect the changes. Thank you so much for your feedback! 

Eduardo.

**Comment by babs** [comment]
works like a charm, thanks!
