### ISSUE TITLE
Setting "server.http.host" has no effect in 3.0

### ISSUE THREAD

**Issue by paulholden** [rundeck/rundeck#3786]
**Describe the bug**
In previous versions (2.11.5) of Rundeck it was possible to configure the interface to bind to by setting the _server.http.host_ System Property - [ref](http://rundeck.org/2.11.5/administration/installation.html).

This setting no longer appears to have any effect in 3.0

**My Rundeck detail**

* Rundeck version: 3.0.0
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: mysql

**To Reproduce**
1. Set _server.http.host_ in profile configuration file
2. Observe netstat output and see server is bound to all addresses "0.0.0.0"

**Expected behavior**
Rundeck should observe the _server.http.host_ configuration and bind to the correct interface

**Comment by sjrd218** [comment]
Try setting the `server.address` property and let us know if that accomplishes your desired result in 3.0.

**Comment by joscha-alisch** [comment]
We have the same problem with the "server.http.port" system property. Since updating to 3.0, it no longer has an effect as well. Seems like this might be related - if not, I'm happy to create a separate issue.

**Comment by sjrd218** [comment]
@joscha-alisch Try using `server.port` and see if that works. 

The latest grails framework is built on spring boot so we've had to change the way Rundeck initialization works. We may have a few places where we aren't translating the old property to the new. Please let us know if these properties mentioned above work for you. Thanks!

**Comment by chtay** [comment]
I just tried rundeck-3.0.1-20180803 (war version)..and this is what I notice.
The configuration files (profile, framework.properties, preference.properties) has no affect.
Looks like the correct config file now is only "rundeck-config.properties".
The config is case sensitive.

To change the server address (lets say 192.168.1.2), you need to modify the rundeck-config.properties on:
server.address=192.168.1.2

To change the port to lets say 4444, you need to modify the rundeck-config.properties on:
server.port=4444

To change the web context to lets say http(s)://yourserver:4444/rundeck, you need to modify the undeck-config.properties on:
server.contextPath=/rundeck

If you are doing a reverse proxy thing, lets say https://yourserver/rundeck do remember to change the rundeck-config.properties on:
grails.serverURL=https://yourserver/rundeck

**Comment by paulholden** [comment]
Thanks all, I've upgraded to [3.0.5](https://rundeck.org/news/2018/08/28/rundeck-3.0.5.html) this morning and can confirm that _server.http.host_ is now working as expected 👍

**Comment by lightarrow** [comment]
I fixed this issue by setting ports in /etc/rundeck/framework.properties & /etc/rundeck/rundeck-config.properties
