### ISSUE TITLE
Deploying 3.0.1-20180803 on wildfly 13: java.lang.IllegalArgumentException: URI scheme is not \"file\"

### ISSUE THREAD

**Issue by gaetanquentin** [rundeck/rundeck#3787]
Deploying rundeck 3.0.1-20180803 on wildfly 13 (ubuntu, java 8) ,  results in this error:

{"WFLYCTL0062: Composite operation failed and was rolled back. Steps that failed:" => {"Operation step-2" => {"WFLYCTL0080: Failed services" => {"jboss.undertow.deployment.default-server.default-host./rundeck" => "java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: URI scheme is not \"file\"
    Caused by: java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: URI scheme is not \"file\"
    Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is java.lang.IllegalArgumentException: URI scheme is not \"file\"
    Caused by: java.lang.IllegalArgumentException: URI scheme is not \"file\""},"WFLYCTL0288: One or more services were unable to start due to one or more indirect dependencies not being available." => {"Services that were unable to start

Rundeck 2.11 was working fine in wildfly 13.

How to Install:

1. wildfly properties are defined:

rdeck.base=/data/rundeck
RDECK_BASE=/data/rundeck
rundeck.config.location=/data/rundeck/server/config/rundeck-config.properties

(rundeck.config.location was /data/rundeck/etc/rundeck-config.properties with rundeck 2.11)

2. Installing in standalone mode:

The war is in /data/rundeck:
- cd /data/rundeck
- java -jar rundeck.war --installonly

3. Modifying file:
server/config/rundeck-config.properties:

grails.serverURL=https://wildflyURL/rundeck
dataSource.jndiName=java:/jdbc/rundeck

4. Deploying war with jboss-cli.sh.

How to know what URI it is complaining about?

**Comment by gaetanquentin** [comment]
it looks like rdeck.base and rundeck.config.location properties are ignored. A strace shows no access to '/data/rundeck'. 

Instead, a relative application   config file (application.yml, application.properties, application.groovy, or application.xml) is searched , in deployment directory i think.

**Comment by sjrd218** [comment]
@gaetanquentin Thanks for trying Rundeck 3 on Wildfly. It looks like Wildfly uses a customized classloader which didn't work with the Rundeck initialization code. If you want to check out the PR: https://github.com/rundeck/rundeck/pull/3798 it has a fix for this. You'll need to build the war yourself for now if you want to try it out.

Also be sure that you've set the -Drdeck.base system property to your rundeck base directory.
You can do this by putting the line:
```JAVA_OPTS="$JAVA_OPTS -Drdeck.base=/data/rundeck"``` in your $WILDFLY_INSTALL/bin/standalone.conf file.

**Comment by gaetanquentin** [comment]
ok thanks it is deployed, but:

1. wildfly users  are ignored. with RD  2.X, the wildfly admin user account could be used. Now only the RD built-in admin account can be used but 

2. datasource jndiname is ignored in rundeck-config.properties:
#dataSource.url = jdbc:h2:file:/data/rundeck-unstable/server/data/grailsdb;MVCC=true
dataSource.jndiName=java:/jdbc/rundeck

2: config files structure is quite confusing:

 - when running the launcher (java -jar --installonly), it creates config files in RDECK_BASE/server/config:
-rw-rw-r-- 1 wildfly wildfly  160 Aug  9 10:54 jaas-loginmodule.conf
-rw-rw-r-- 1 wildfly wildfly 7038 Aug  9 10:54 log4j.properties
-rw-rw-r-- 1 wildfly wildfly  403 Aug  9 10:54 realm.properties
-rw-rw-r-- 1 wildfly wildfly 1328 Aug  9 11:09 rundeck-config.properties
-rw-rw-r-- 1 wildfly wildfly  178 Aug  9 10:54 ssl.properties

 - when deploying after with wildfly , it creates coinfig files in RDECK_BASE/etc
-r--r--r-- 1 wildfly wildfly  738 Aug  9 10:57 admin.aclpolicy
-r--r--r-- 1 wildfly wildfly 1104 Aug  9 10:57 apitoken.aclpolicy
-rw-rw-r-- 1 wildfly wildfly  510 Aug  9 10:57 cli-log4j.properties
-rw-rw-r-- 1 wildfly wildfly 1928 Aug  9 11:12 framework.properties
-rw-rw-r-- 1 wildfly wildfly 7912 Aug  9 10:57 preferences.properties
-rw-rw-r-- 1 wildfly wildfly  671 Aug  9 10:57 profile
-rw-rw-r-- 1 wildfly wildfly  474 Aug  9 10:57 profile.bat
-rw-rw-r-- 1 wildfly wildfly  855 Aug  9 10:57 project.properties
