### ISSUE TITLE
doc missing - 404

### ISSUE THREAD

**Issue by gaetanquentin** [rundeck/rundeck#3788]
There are erros on the doc site:
http://rundeck.org/docs/administration/configuration-file-reference.html#framework.properties

![image](https://user-images.githubusercontent.com/5774881/43722407-790f596e-9995-11e8-97fe-655cbd48f223.png)

**Comment by gschueler** [comment]
was this a broken link from somewhere else? if you are looking for 2.11 docs, this works: http://rundeck.org/2.11.5/administration/configuration-file-reference.html#framework.properties

if you are looking for 3.0 docs, the new link would be: http://rundeck.org/docs/administration/configuration/configuration-file-reference.html#framework.properties

**Comment by gschueler** [comment]
i have created an issue in @rundeck/docs for this: https://github.com/rundeck/docs/issues/58
