### ISSUE TITLE
Can't Use Log Filter "Data" Plugins in Plugins

### ISSUE THREAD

**Issue by niall-munnelly** [rundeck/rundeck#3793]
**Describe the bug**
See [Rundeck-Discuss](https://groups.google.com/forum/#!topic/rundeck-discuss/lQ5p7b-VV0U), also. I'm successfully extracting "Foo" from a workflow step using the KVP log filter and printing it later in the workflow as "${data.Foo}" - I'd like to reuse this in a script plugin. Rundeck appears to be assigning RD_CONFIG_FOO as literal string '${data.Foo}.'  This isn't the behavior I would expect, given other plugins that use options as defaults, like so:
config:

      - type: String

        default: ${option.Service_Now_Ticket}

        name: Service_Now_Ticket

        title: 'Service Now Ticket'

        description: 'RFC or incident associated with this execution'

        required: true

**My Rundeck detail**

* Rundeck version: 2.11.4
* install type: RPM
* OS Name/version: RHEL
* DB Type/version: postgres

**To Reproduce**
1. Capture output and define a variable with Log Filter Key-Value pair, call it "Foo."
2. Print "${data.Foo} in a subsequent local command to confirm that it does work.
3. Create a script plugin provider config type "string" called FOO that inherits ${data.Foo} as a default
4. Deploy script plugin
5. Add a workflow step to print `env` and look at the RD_* variables
6. You'll see that RD_CONFIG_FOO is literal string "${data.Foo}."

**Expected behavior**
I would expect Log Filter variables to be exposed to the Rundeck plugin (RD_CONFIG) and/or script (RD_OPTION) namespaces.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any
 - Version Any

**Additional context**

**Comment by douz** [comment]
@niall-munnelly did you manage to make this work?
