### ISSUE TITLE
rundeck3 ui improvement on job listing when in multi level groups

### ISSUE THREAD

**Issue by babs** [rundeck/rundeck#3794]
**Is your feature request related to a problem? Please describe.**
When listing jobs in a project where groups and sub groups are used, all the expansion arrows and titles are at the same level

**Describe the solution you'd like**
Is would be nice that at each level arrows and title where slightly indented to better see the levels

**Comment by yankcrime** [comment]
I recently upgraded to 3.0.9 and this has been fixed - there's now a clear visible structure to multi-level jobs.

**Comment by babs** [comment]
I confirm it's fixed :)
