### ISSUE TITLE
com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'dir' used in key specification without a key length

### ISSUE THREAD

**Issue by chtay** [rundeck/rundeck#3797]
My rundeck was upgraded from v2.10.8 to 3.0.1-20180803. Everytime I run/start the rundeck, there is a WARN --- [ main] o.h.t.s.i.ExceptionHandlerLoggedImpl : GenerationTarget encountered exception accepting command : Error executing DDL via JDBC Statement

Somewhere down the error, there is this:
Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: BLOB/TEXT column 'dir' used in key specification without a key length

* Rundeck version: 3.0.1-20180803
* install type: war
* OS Name/version: openSUSE Leap 42.3
* DB Type/version: mysql

When google on that error message, I got this:
------------------------------
The error happens because MySQL can index only the first N chars of a BLOB or TEXT column. So The error mainly happen when there is a field/column type of TEXT or BLOB or those belongs to TEXT or BLOB types such as TINYBLOB, MEDIUMBLOB, LONGBLOB, TINYTEXT, MEDIUMTEXT, and LONGTEXT that you try to make as primary key or index. With full BLOB or TEXT without the length value, MySQL is unable to guarantee the uniqueness of the column as it’s of variable and dynamic size. So, when using BLOB or TEXT types as index, the value of N must be supplied so that MySQL can determine the key length. However, MySQL doesn’t support limit on TEXT or BLOB. TEXT(88) simply won’t work.

The solution to the problem is to remove the TEXT or BLOB column from the index or unique constraint, or set another field as primary key. If you can’t do that, and wanting to place a limit on the TEXT or BLOB column, try to use VARCHAR type and place a limit of length on it. By default, VARCHAR is limited to a maximum of 255 characters and its limit must be specified implicitly within a bracket right after its declaration, i.e VARCHAR(200) will limit it to 200 characters long only.
So suspect it is due to the database table, "storage", the "dir" field is using longtext and the rundeck is trying to set that field as an index key.
------------------------------

When I changed that "dir" field to VARCHAR with 255 long, when rerun the rundeck, no more WARN encountered.
Checking back the table again, and that field is now an index key of "STORAGE_IDX_DIR".

Currently my "storage" table is empty but I not sure whether that field of 255 characters long as any impact or not.

**Comment by gschueler** [comment]
We can either remove the index definition for that field (Storage.dir), or change the size of that field.

**Comment by gschueler** [comment]
duplicates #3785
