### ISSUE TITLE
Calendar in 'Run Job Later' function

### ISSUE THREAD

**Issue by Ehoudry** [rundeck/rundeck#3799]
**Describe the bug**
The calendar doesn't appear when scheduling a job to run later

**My Rundeck detail**

* Rundeck version: Rundeck 3.0.1-20180803 
* install type: rpm
* OS Name/version: CentOS Linux release 7.5.1804
* DB Type/version: mysql

**To Reproduce**
1. Go to a job
2. Click on Run job later
3. Click on the calendar icon
4. A calendar should appear but does not

**Expected behavior**
In 2.10 a graphical calendar appears and help choosing a date

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Macos Sierra or Linux fedora
 - Browser chrome, safari, firefox
 - Version firefox 61.0.1 , Chrome 68.0.3440.84, Safari 11.1.2

**Additional context**

**Comment by gschueler** [comment]
Related: also date options do not work: Add a Job Option of type "Date".  When running the job, the option shows a calendar icon, but clicking it or the option's text field does not show a graphical date selector.
