### ISSUE TITLE
Duplicate job, options lost

### ISSUE THREAD

**Issue by dpomnean** [rundeck/rundeck#3812]
**Describe the bug**
When I go to duplicate a job that has options defined, the duplicated job will lose all job options. Not sure if this is a feature or a bug.

**My Rundeck detail**

* Rundeck version: 2.11.3
* install type: rpm
* OS Name/version: OEL 6.9
* DB Type/version: mysql

**To Reproduce**
1. Click on 'duplicate job' on a job that has options defined.
2. View options section and it will be empty.

**Expected behavior**
Options and values to remain.

**Comment by jtobard** [comment]
This is a duplicate from a closed issue #3384 try the latest version
