### ISSUE TITLE
Rundeckd failed to start after v3.0.1 upgrade

### ISSUE THREAD

**Issue by stanlog** [rundeck/rundeck#3814]
**Describe the bug**
Since I upgrade Rundeck from 2.11.5-1-GA_all to rundeck_3.0.1.20180803-1.201808032143_all, rundeckd failed to start. After few seconds, I have:
```
rundeckd.service: Main process exited, code=exited, status=1/FAILURE
start-stop-daemon: warning: failed to kill 8511: No such process
Stopping rundeckd.
```
Any idea ? I can't find more logs. Can you tell me where I can look for please ?

**My Rundeck detail**

* Rundeck version: 3.0.1
* install type: deb
* OS Name/version: Debian 9
* DB Type/version: mysql

**To Reproduce**
1. upgrade Rundeck from 2.11.5 to 3.0.1 with .deb package
2. say yes to upgrade /etc/rundeck/profile and /etc/rundeck/rundeck-config.properties with the package's version
3. paste mysql connection params from the old rundeck-config.properties to the new rundeck-config.properties file
4. start rundeckd
5. after few seconds, look at this fails :)

Thank you for your help, I don't want to downgrade rundeck, but if I don't find any solution... no choice.

**Comment by sjrd218** [comment]
@pulkitvaishnav Try changing ```-Dloginmodule.conf.name=/etc/rundeck/jaas-loginmodule.conf``` to ```-Dloginmodule.conf.name=jaas-loginmodule.conf``` and see if that works.

**Comment by stanlog** [comment]
Hello,
I found my error, it was the Mysql conf to adapt in rundeck-config.properties with:
dataSource.dbCreate = update
dataSource.url = jdbc:mysql://localhost/rundeck?autoReconnect=true&useSSL=false
dataSource.username=xxxxx
dataSource.password=xxxxx
dataSource.driverClassName=com.mysql.jdbc.Driver

Found in the doc: https://rundeck.org/docs/administration/configuration/database/mysql.html
Thank you so much for your help, and for this amazing tool that is rundeck ;)
