### ISSUE TITLE
413 "Payload Too Large" error when trying to use Preauthenticated Mode with SSO

### ISSUE THREAD

**Issue by raphaelgon** [rundeck/rundeck#3832]
**Describe the bug**
Rundeck returns 413 error message when I sent a Header with too many user´s groups information.

**My Rundeck detail**
Error message.

< HTTP/1.1 413 Request Entity Too Large
< Content-Length: 0
< Connection: close
< Server: Jetty(9.0.7.v20131107)

* Rundeck version: 2.11.5
* install type: launcher
* OS Name/version: CentOS Linux release 7.5.1804 (Core)
* DB Type/version: mysql:5.7.19

**To Reproduce**
1. Setup Rundeck to use "Preauthenticated Mode".
2. Use "curl" to pass the Header information to rundeck:
  X-Remote-User: user1
  X-Remote-User-Group: (my user is member of 340 AD groups)

**Expected behavior**
Rundeck authenticates the user based on the X-Remote-User/X-Remote-User-Group header information.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser : Firefox
 - Version: 61.0.1

**Additional context**
The "Preauthenticated Mode" works if I pass less groups on the X-Remote-User-Group header field.
The group information is extracted from my AD. Is it possible to configure Jetty "requestHeaderSize" to support large headers?

**Comment by sjrd218** [comment]
@raphaelgon Can you try your setup with Rundeck 3.x?

The configuration property: ```server.max-http-header-size=8KB``` can be used to configure the header size. You would put this in your `rundeck-config.properties` file. 8Kb is the default, so if that doesn't work for you try increasing it. This property only exists in Rundeck 3.x.

**Comment by raphaelgon** [comment]
It´s not relevant anymore. Thank you.

**Comment by danifr** [comment]
I was facing this problem too (rundeck v3.3.6), I am suing the puppet-rundeck module that uses the _.groovy_ file instead of the _.properties_.

In order to make it work I edited `/etc/sysconfig/rundeckd` and added:

`RDECK_JVM_SETTINGS="$RDECK_JVM_SETTINGS -Dserver.max-http-header-size="16384"`

That worked like charm!

For completeness: https://groups.google.com/g/rundeck-discuss/c/e71tlJBBw70/m/E0LheCd5AgAJ
