### ISSUE TITLE
Add "Disable all" action for disabling execution and schedule for Jobs

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#3833]
**Is your feature request related to a problem? Please describe.**

When both execution and schedule need to be disabled, it takes multiple clicks in the GUI to perform it.  It would be easier to have a single "Disable Both" option in the Job Actions menu.

**Describe the solution you'd like**

Add an action to the Job Action menu, and Job Bulk Edit menu, to disable/enable both Execution and Scheduling for jobs.

**Additional context**

API support NTH

**Comment by yogeshkumark** [comment]
go to setting -> Execution mode -> Passive. 
This will pause all the job and no jobs will be executed. 

we use this step for our patching purpose.
