### ISSUE TITLE
Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by expz** [rundeck/rundeck#3838]
**Describe the bug**
I run version 3.0.1 but startup only works halfway. The login page does not load, and the log  `/var/log/rundeck/service.log` has an error:

    2018-08-15 15:25:51.817  WARN --- [           main] o.h.t.s.i.ExceptionHandlerLoggedImpl     : GenerationTarget encountered exception accepting command : Error executing DDL via JDBC Statement

    org.hibernate.tool.schema.spi.CommandAcceptanceException: Error executing DDL via JDBC Statement
    at org.hibernate.tool.schema.internal.exec.GenerationTargetToDatabase.accept(GenerationTargetToDatabase.java:67)
    at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlString(AbstractSchemaMigrator.java:524)
    at org.hibernate.tool.schema.internal.AbstractSchemaMigrator.applySqlStrings(AbstractSchemaMigrator.java:470)

Then further down:

    Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Specified key was too long; max key length is 767 bytes

I modified the `dir` column of the `storage` table to be `varchar(720)` from the previous `varchar(2000)`, but the error did not go away. I assume there are columns in other tables which are too long for the indices.

**My Rundeck detail**

* Rundeck version: 3.0.1 from 2018-08-03
* install type: deb
* OS Name/version: debian stretch
* DB Type/version: mysql

**To Reproduce**
1. Run the docker container jordan/rundeck:3.0.1

    docker run -it -p 4440:4440 -p 4443:4443 -e RUNDECK_ADMIN_PASSWORD=x --name rundeck jordan/rundeck:3.0.1

**Expected behavior**
The website should load and there should be no error in the log.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome
 - Version: 67

**Comment by KevinBott** [comment]
@expz This is a common MySQL issue.  Did you create the database yourself, or is it part of the docker image?  What version of MySQL?

I don't know how this will be handled in the docker image, or the install process, but this is what I know from fixing this in MySQL for in-house apps.  

If a unicode character set is used, then even varhar(720) may be too large (multiple bytes per character).  

Check the ROW_FORMAT of the table, it should be DYNAMIC. `select row_format from information_Schema.tables where table_name='storage';` 

Also check `innodb_large_prefix` (should be 'ON') as well as `innodb_file_format` and `innodb_file_format_max`  -- both should be Barracuda.  

Good Luck!  
Kevin

**Comment by ProTip** [comment]
Hi @expz ,

@KevinBott is on the money. MySQL prior to 5.7 had `antelope` as the default file type and this does not support the large key prefixes. For existing tables you can change to Barracuda by specifying `ALTER TABLE `table`  ROW_FORMAT=DYNAMIC;`.
