### ISSUE TITLE
Rundeck fails to start after 3.0.1 Upgrade

### ISSUE THREAD

**Issue by ReinforcedPanda** [rundeck/rundeck#3839]
**Describe the bug**
Upgraded rundeck using yum, and am now getting this error trying to start rundeckd.

> OpenJDK 64-Bit Server VM warning: ignoring option MaxPermSize=256m; support was removed in 8.0
> Error: Could not find or load main class .var.lib.rundeck

**My Rundeck detail**

* Rundeck version: 3.0.1
* install type: yum/rpm
* OS Name/version: CentOS 7.5
* DB Type/version: sqllite

**To Reproduce**
1. Upgrade rundeck from 2.9 to 3.0 using yum on centos.
2. Try to start rundeckd.

**Comment by tylwright** [comment]
@andsantrj figured it out and has a workaround posted here: #3841.

**Comment by gschueler** [comment]
I will close the issue. If you still have this problem in a newer version, please re-open this issue.
