### ISSUE TITLE
Rundeck failing to start after 3.0.1 upgrade

### ISSUE THREAD

**Issue by andsantrj** [rundeck/rundeck#3841]
After the rundeck upgrade to 3.0.1, I cannot start my service anymore.

The error on service.log is:

Error: Could not find or load main class .var.lib.rundeck

Version:
rundeck.noarch                       3.0.1.20180803-1.201808032143 @rundeck-release-bintray
rundeck-config.noarch                3.0.1.20180803-1.201808032143 @rundeck-release-bintray

I Cannot understand what happened on my environment.

**Comment by andsantrj** [comment]
Now I know what happened, when I upgraded to 3.0.1, some parameters inside profile and rundeck-config.properties files were changed.

The new files were renamed to .rpmnew, I just move the .rpmnew to the oficials files, renaming some parametes. Now its working.

**Comment by gschueler** [comment]
I will close the issue. If you still have this problem in a newer version, please re-open this issue.

**Comment by ibaboo** [comment]
Hi @andsantrj I am experiencing the same issue. What parameters did you change to get this working?

**Comment by andsantrj** [comment]
@ibaboo Actually, just rename the .rpmnew files located on /etc/rundeck to correct names, preserve the old files to edit the news file with ALL customized parameters of your environment.

**Comment by ibaboo** [comment]
cool, will try this again
