### ISSUE TITLE
Incrementation of the jobs id

### ISSUE THREAD

**Issue by PeekLeon** [rundeck/rundeck#3844]
**Describe the bug**
Hi,
Job ids do not follow each other. for example I go from job 120 to 126 then 131 ...

**My Rundeck detail**

* Rundeck version: 3.0.1
* install type: rpm
* OS Name/version: Centos 7.5
* DB Type/version: postgres 10

This installation is recent, so I do not have many jobs. So I'm sure there are not multiple jobs running at the same time

**To Reproduce**
Run multiple jobs ...

**Comment by PeekLeon** [comment]
I tested the same version of Rundeck (3.0.1) but without the database postgresql and here the ids are well incremented. Is there a configuration to do on the database?

**Comment by tsde** [comment]
@PeekLeon See my comment https://github.com/rundeck/rundeck/issues/2765#issuecomment-446762642

**Comment by PeekLeon** [comment]
In duplicate with #2765 I closed.
