### ISSUE TITLE
System prop -Dserver.web.context doesn't work. (nginx is broken after upgrade 3.0.1)

### ISSUE THREAD

**Issue by nixmomo** [rundeck/rundeck#3851]
**Describe the bug**
Rundeck is not working behind nginx anymore.

**My Rundeck detail**

* Rundeck version: 3.0.1
* install type: deb
* OS Name/version: Debian stretch
* DB Type/version: build in

**Steps to reproduce**
set grails.serverURL=https://DNS-ALIAS/rundeck in /etc/rundeck/profile
set framework.server.url = http://rundeck-ip:4440
add -Dserver.web.context=/rundeck \
           -Drundeck.jetty.connector.forwarded=true"
in RDECK_JVM section

Nginx config
   location ~ /rundeck(/.*) {
	proxy_pass          http://RUNDECK-IP:4440;
	auth_ldap "Forbidden";
	auth_ldap_servers DL-Host;
	expires off;
	    proxy_send_timeout 540s;
	    proxy_read_timeout 540s;
	proxy_cache_bypass $cookie_nocache $arg_nocache;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header Host $host;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
#proxy_set_header X-Forwarded-Host $host:$server_port;
proxy_set_header X-Forwarded-Host $server_name;
proxy_set_header User-Agent $http_user_agent;
     }

**Expected behavior**
Login Page / Rundeck pages as works in earlier Versions

**Desktop (please complete the following information):**

 - Browser All Browsers

**Additional context**
So why is this setup broken? It works for many years without errors and now i get always 404...
Rundeck shows under /rundeck always a 404page and i am sure this is the error... why is rundeck ignoring -Dserver.web.context=/rundeck  and how can i set this again or what should i change in my setup to get it working again?

I use a ssl connection to my DNS Alias and a internal unsecured connection to rundeck... That works always fine so i cant understand why rundeck dont work anymore

**Comment by gschueler** [comment]
duplicates #3840

**Comment by gschueler** [comment]
Sorry, there are two issues here.  For the `-Drundeck.jetty.connector.forwarded=true` you can use the workaround setting in rundeck-config.properties of `server.useForwardHeaders=true`. 

For the `-Dserver.web.context=/rundeck` issue, the workaround is to set `server.contextPath=/rundeck` in rundeck-config.properties.

I will reopen this and restor the `-Dserver.web.context=/rundeck` behavior.

**Comment by gschueler** [comment]
FYI: additional workaround is to use system properties: `-Dserver.useForwardHeaders=true` and `-Dserver.contextPath=/rundeck`

**Comment by nixmomo** [comment]
Thanks so much!!
server.contextPath= variable works fine...
Why is this not documented?
