### ISSUE TITLE
Rundeck LDAP Group Synchronization

### ISSUE THREAD

**Issue by shehzadshaikh** [rundeck/rundeck#3855]
**Describe the bug**
We have deployed **Rundeck 3.0.1** and configured it to authenticate via LDAP (Active Directory). I am able to authenticate with individual users. Now i want my user to act as admin user for rundeck hence, i have added the group name which i belong to (for instance myOrgAdminGroup) in admin.aclpolicy file under 
**by:
  group: myOrgAdminGroup**
above change doesn't help and produces an error 
You have no authorized access to projects.
Contact your administrator. (User roles: ROLE_myOrgAdminGroup, ROLE_myUserName, and ROLE_all other group i belong to.
If i add another username explicitly in admin.aclpolicy file such as below
**by:
 group: myOrgAdminGroup
 username: myUserName**
then it works and i become an Admin user for rundeck.
 
Here is my **admin.aclpolicy** file
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job:
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: admin
  #username: myUserName

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  project_acl:
    - allow: '*' # allow admin of all project-level ACL policies
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group: admin
  #username: myUserName

and here is my **jaas-activedirectory.conf**
activedirectory {
  com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
        debug="true"
        contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
  providerUrl="ldaps://AD_HOSTNAME:3269"
  bindDn="AD_USER@AD_HOSTNAME"
  bindPassword="PASSWORD"
  authenticationMethod="simple"
  forceBindingLogin="true"
  userBaseDn="DC=example,DC=example,DC=com"
  userRdnAttribute="sAMAccountName"
  userIdAttribute="sAMAccountName"
  userPasswordAttribute="unicodePwd"
  userObjectClass="user"
  roleBaseDn="DC=example,DC=example,DC=com"
  roleNameAttribute="sAMAccountName"
  roleMemberAttribute="member"
  roleObjectClass="group"
  cacheDurationMillis="0"
  supplementalRoles="user"
  reportStatistics="true";
};

**Comment by ecarrascos** [comment]
Hi!

It may be possible that you need to add the configuration in your login module config file:

rolePrefix
Prefix string to remove from role names before returning to the application, e.g. “ROLE_”.

Ref: [Login Module configuration](https://rundeck.org/docs/administration/security/authenticating-users.html#login-module-configuration)

Cheers!

**Comment by shehzadshaikh** [comment]
Thanks for your suggestion, issue seem to be resolved now. 
I just renamed the jaas-activedirectory.conf to jaas-loginmodule.conf

**Comment by ecarrascos** [comment]
Hi!

[Rundeck 3.0.3 has just been released!](http://www.rundeck.org/news/2018/08/24/rundeck-3.0.3.html) Which includes the fix for this issue

Hope it helps!

**Comment by Veera1973** [comment]
Hi,

I am getting below message how to fix it please

You have no authorized access to projects.
Contact your administrator. (User roles: )
