### ISSUE TITLE
unable to navigate to default dashboard view

### ISSUE THREAD

**Issue by ajgeek** [rundeck/rundeck#3862]
I am firsttime user to rundeck, i have installed using launcher in unix shell.i am able to launch the api url but after logi sucessful, it not able to navigate to the default dashboard view, please guide me in this,PFB SS
![rundeck_error](https://user-images.githubusercontent.com/42539624/44383559-b814fb80-a536-11e8-9312-a17e1ac3c782.PNG)

**Describe the bug**

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [e.g. ubuntu 16.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sjrd218** [comment]
Please try installing the latest Rundeck 3 and let us know if you are still having issues.
