### ISSUE TITLE
Rundeck 3: Unable to update SSH Options for Project

### ISSUE THREAD

**Issue by KevinBott** [rundeck/rundeck#3867]
**Describe the bug**
Updates to `SSH Key File Path` or `SSH Key Storage Path` are not persisted when the project is saved.  The initial values cannot be changed once set.  

**My Rundeck detail**
* Rundeck version: 3.0.3
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: mysql 5.6

**To Reproduce**
1. Create a project.
2. Save the project 
3. Edit Configuration on project
4. Set the `SSH Key Storage Path`
5. Save
6. Edit Configuration
7. Check to see if the value persisted.

**Expected behavior**
I expect the changes to be persisted.  

**Screenshots**
None - can try a video capture if it's not reproducible.  

**Desktop (please complete the following information):**
 - OS: MacOS Sierra
 - Browser: Safari, Chrome
 - Version: ?, 68

**Additional context**
I'm running as admin, no other users defined yet.

Project definitions are stored in MySQL.  rundeck.storage(version) column is incrementing when I save the project.  The blob data is changing - this is verified by md5(data), but since it's encrypted I have not idea what's actually changing.  

Brand new install, first time RunDeck user. 

rundeck.access.log show this on Save:
```"POST /resources/saveProject" 10.14.10.118 http admin form 79 TestProject [] (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.106 Safari/537.36)```

rundeck.service.log has:
```2018-08-21 14:07:46.283  WARN --- [tp1964157350-25] o.grails.plugins.web.taglib.FormTagLib   : [actionSubmit] 'name' attribute will be ignored
2018-08-21 14:07:46.283  WARN --- [tp1964157350-25] o.grails.plugins.web.taglib.FormTagLib   : [actionSubmit] 'name' attribute will be ignored
```

And rundeck.audit.log does have some decisions resulting in: `REJECTED_NO_SUBJECT_OR_ENV_FOUND`.

**Comment by sjrd218** [comment]
@KevinBott Could you take 2 screen shots of your project configuration screen? One showing the settings for the default node executor, the other showing the settings for the default node copier?
Please take the captures after you have set the data how you wanted it to be saved.

If you want to create a fake project with fake key paths that simulate your production environment that's fine, but I do need to see the actual values you are putting in the fields.

**Comment by sjrd218** [comment]
It looks like the default node file copier settings are overwriting the settings specified in the default node executor.
