### ISSUE TITLE
Ability to disable step without deleting it

### ISSUE THREAD

**Issue by gaetanquentin** [rundeck/rundeck#3870]
Rundeck 3.0.1:

It would be useful to be able to disable temporary a step without deleting it (so loosing it).

**Comment by Ruko2010** [comment]
I would also love this feature. Especially when developing workflows this would come very handy!

**Comment by ZoeLeah** [comment]
+1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Ruko2010** [comment]
@gaetanquentin in the meantime I have a small workaround. Just create a step that always fails, something like a Script step:
`#!/bin/bash
trap exit 1 ERR
exit 1`

And then place your "paused" Steps behind this one. 
Your Workflow will fail every time, but if you just want to test something, it is a workaround.

**Comment by fdevans** [comment]
Thank you for the idea.  We do have a solution available in the Enterprise version.  Using the Ruleset Workflow strategy it's possible to define the steps you'd like to run/ignore.
