### ISSUE TITLE
Anyone can read password from framework.properties file - rpm package

### ISSUE THREAD

**Issue by maciejbogucki** [rundeck/rundeck#389]
Default rundeck-config-1.5-1.6.GA rpm package has world readable framework.properties which allow every local user to read rundeck passwords.

$ ls -l /etc/rundeck/
razem 44
-rw-r--r-- 1 rundeck rundeck  563 02-22 01:15 admin.aclpolicy
-rw-r--r-- 1 rundeck rundeck  990 02-22 01:15 apitoken.aclpolicy
-rw-r--r-- 1 rundeck rundeck 4797 04-23 08:03 framework.properties
-rw-r--r-- 1 rundeck rundeck  141 02-22 01:15 jaas-loginmodule.conf
-rw-r--r-- 1 rundeck rundeck 4948 02-22 01:15 log4j.properties
-rw-r--r-- 1 rundeck rundeck 1732 02-22 01:15 profile
-rw-r--r-- 1 rundeck rundeck  549 02-22 01:15 project.properties
-rw-r--r-- 1 rundeck rundeck 1018 04-23 07:57 realm.properties
-rw-r--r-- 1 rundeck rundeck  335 02-22 01:15 rundeck-config.properties
drwxrwxr-x 2 rundeck rundeck   27 04-23 07:32 ssl
$ grep framework.server.password /etc/rundeck/framework.properties
framework.server.password = admin
$ rpm -qf /etc/rundeck/framework.properties
rundeck-config-1.5-1.6.GA
$

**Comment by ahonor** [comment]
The `rd` CLI makes this request obsolete
