### ISSUE TITLE
left-hand navigation bar shrinking and resizing 

### ISSUE THREAD

**Issue by gjvc** [rundeck/rundeck#3911]
**summary**

left-hand navigation bar is misbehaving (unnecessarily shrinking and resizing), causing a visually and mentally jarring effect.

**version**

alapeño popper brown book 2018-08-17 / Rundeck 3.0.2-20180817

**steps to setup**

0. install the above version
1. login to the front page via admin / admin
2. click through the welcome page
3. create a new project, if one doesn't already exist.

**steps to reproduce**

1. select a project from the projects dropdown on the top-left.  Note how the navigation menu shrinks to the left and then immediately resizes to its previous size.  This is mentally jarring as one expects the state to change to something new, but the net change is nothing. 
1.1 Bug #1 -- upon selecting a project from the "PROJECTS" menu, the current visual layout should be maintained and there should be no resizing.
2. select an entry from the left-hand navigation column. (after completing step 5 there will be no entry selected and hence no left-pointing indicator arrow on the right of the entry)
2.1 Bug #2 -- upon selecting an entry (dashboard, jobs, nodes, commands, activity, or project settings) in the left-hand navigation menu, the navigation menu shrinks to the left and then immediately resizes to its previous size.
3. Hover the mouse pointer over the ">> RUNDECK" logo top-left and a left / right pointing toggle button appears which is used for pinning or unpinning the left-hand navigation bar, and the above behaviour changes, depending on the state of this toggle.

**suggestions for improvement / resolution**

1. Remove all animation effects.  This is an operations tool and should be sober in its use.
2. When the navigation panel is shrunk and only icons are visible, it should not expand upon hover.
3. When the navigation panel expands, the content pane should move / resize at the same time, not after the navigation panel has finished expanding.

**Comment by gschueler** [comment]
please attach video or screenshots, and information about the OS and browser you are using

**Comment by cukal** [comment]
I would give an arm & a leg to disable all menu animation and just keep the sidebar menu expanded or minimised at all times, perhaps animate only for the Projects & Settings dropdown. But then again, rundeck is probably one of the best/versatile automation tools out there so I don't mind as much 😃 

2 screen recordings, first one with the expanded menu and second with the closed menu. 
Both show the first on-focus animation to open the menu and the second animation is triggered when the mouse is moving to the right again after the click on the menu item. 
When clicking and rapidly moving the mouse to the right the effect is not there, but when clicking, waiting a fraction of a second and moving the mouse to the right it registers the mouse over it and animates opening the sidebar again and that is somewhat confusing/distracting at times. 

[exanpded](https://thewholeshebang.be/rd_menu_animation.mov)
[small_icons](https://thewholeshebang.be/rd_menu_animation2.mov)

MacOS High Sierra / 10.13.06
Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by ahonor** [comment]
@cukal I appreciate the feedback. We are going to look into this and thanks for the videos!

**Comment by gjvc** [comment]
oops - sorry -- didn't mean to close this
