### ISSUE TITLE
Execute rundeck jobs on node

### ISSUE THREAD

**Issue by vinothkumarsubbu** [rundeck/rundeck#3912]
**Describe the bug**
Unable to connect to rundeck node via password authentication.

**Failed: ConfigurationFailure: SSH Password was not set
Execution failed: 8 in project SampleProject: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [<hostname>: ConfigurationFailure: SSH Password was not set + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, Node failures: {<hostname>=[ConfigurationFailure: SSH Password was not set + {dataContext=MultiDataContextImpl(map={}, base=null)} ]}, status: failed]**

**My Rundeck detail**

* Rundeck version: [ e.g. 3.0.3]
* install type: [choose: rpm,]
* OS Name/version: [e.g. Linuex]
* DB Type/version: [ postgres,]

**To Reproduce**

1. Create a new project 
2. Add Node to the server via resources XML use passwod Authentication 
3. Add the password in keyStorage
4. Check the nodes and execute the command.

```
<node
        name="Node1"
        description="Rundeck Dev node1"
        tags=""
        hostname="<hostname>"
        osArch="amd64"
        osFamily="unix"
         osName="Linux"
        osVersion="3.10.0-862.11.6.el7.x86_64"
        username="<username>"
        ssh-pasword-storage-path="keys/node/dev001"
        ssh-authentication="password"/>

```

**Comment by Aljaro** [comment]
Any one has feedback , I have same issue ,I'm stuck to add a node , I am using community edition Rundeck 3.3.2 ?  

Thanks
