### ISSUE TITLE
rd-jobs should have exact match query for job name

### ISSUE THREAD

**Issue by andysteady** [rundeck/rundeck#392]
rd-jobs -g groupname -p projectname returns all jobs that being with projectname. 

Ideally I think it should an exact match.

See: https://groups.google.com/forum/?fromgroups=#!searchin/rundeck-discuss/version$20control/rundeck-discuss/oAx6CKuZ2dk/t2TYxKbD0nYJ

**Comment by Naolador** [comment]
Hi gschueler,

Any update on this issue? I can still see this bug in the latest version of rundeck, we need a exact filter in rd-jobs tool.

Neil

**Comment by ahonor** [comment]
`rd-jobs` is obsolete
