### ISSUE TITLE
RD 3.0.1: Cannot modify node filter 

### ISSUE THREAD

**Issue by gaetanquentin** [rundeck/rundeck#3920]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: 3.0.1
* install type: war/launcher
* OS Name/version: ubuntu 16.04
* DB Type/version:postgres 10

**To Reproduce**
1.Create nodes in yaml files with tags (preprod,production)
2. Create a job , define node filter:
   tags: production+ap0
  click search to test tags and veriffy it works fine
3. Save the job
4. Configure the jobs for execution: see the node count found (in my case with production tags, 2)
   it's ok
5. Now change tags:
   open the job for configuration, change production to preprod. Click search : 1 node, it's ok in my case, the tags is well taken in account
 Save job
6. Go for execution, look at nodes number: 2, like production..not good
 7. Open the job for configuration, it is still 'production'.

New tag conf cannot be saved.

The strange thing, is that it was working: don't know what i have done, it does not work anymore.

**Expected behavior**
Tags modification be taken in account

**Desktop (please complete the following information):**
 - OS: ubuntu bionic 18.04
 - Browser firefox 61

Logs:
Here are differents logs.

[rd-debug-filter-nodes.log.gz](https://github.com/rundeck/rundeck/files/2323941/rd-debug-filter-nodes.log.gz)

**Comment by mzima** [comment]
I think I have the same issue with RD 3.0.5. I can change the node filter within a rundeck job (edit job button), however the change disappears after saving the job.

I'm not able to reproduce this behavior on a fresh installation. There are also no error messages whatsoever ...

**Comment by thomsonac** [comment]
We have the same issue and has become a major roadblock.  The filter is editable but once the job is saved, the filter reverts back to the original value.  The only work-around that we've found is to clone the job to a new job and edit the filter before the first save.

**Comment by gaetanquentin** [comment]
i have exported the jobs and deleted the project, created a new one, and imported yaml definition. I could then change the filters.

**Comment by thomsonac** [comment]
I can't speak for others but I've definitely had this for projects / jobs that were created on 3.x builds

**Comment by gaetanquentin** [comment]
FYI i initialy installed RD 3.01, for the first time on a new host, and imported the projects

**Comment by gaetanquentin** [comment]
sorry i clicked on close issue by mistake

**Comment by gaetanquentin** [comment]
i only used 3.X. i have imported a project from one instance to another.
On the destination instance (a brand new blank one), a have created a new project (since import button is not present until you create a project ...weird, no?) and imported the project, which had a different name.

@jtobard have you looked in my logs?

**Comment by jtobard** [comment]
@gaetanquentin I read your logs but nothing seems out of place.
If this happens in more than one Job, do they have something in common? Any special configuration at project level?
I've tried on 3.0.0, 3.0.1 using PostgreSQL 10 with node file on yaml too, without success so far.

**Comment by thomsonac** [comment]
We're not doing anything special as far as I know.  Front-end is AD based (full admin users), jobs happen to be for Windows servers over WinRM; haven't validated that it happens for Linux-only servers as a result of tags

**Comment by gaetanquentin** [comment]
i just had this problem again and it is worse. I cannot modify node filter in any of  my jobs!
This time i had first the problem with a duplicated job. It was working, the original job was working too,  and it does not work anymore.

**Comment by gaetanquentin** [comment]
audit.log contains these logs:
2018-09-11 11:44:47,832 - Evaluating Decision for: res<kind:node, type:resource> subject<Username:admin Group:build Group:architect Group:admin Group:user Group:deploy> action<read> env<rundeck:auth:env:project:TEST-RUNDECK-EXTERN-SCRIPT>: authorized: false: 	No context matches subject or environment => REJECTED_NO_SUBJECT_OR_ENV_FOUND (0ms)

what does that mean? admin has all rights i think.

**Comment by jtobard** [comment]
This means no rules were found among the ACL policies that match the subject `(user, group)` and context `(project)`  and resource `<kind:node, type:resource>`.
Are you using the default admin user with default ACL policy?

**Comment by gaetanquentin** [comment]
@jtobard yes

**Comment by gaetanquentin** [comment]
@mzima @thomsonac what is your database?
