### ISSUE TITLE
Rundeck 3 : Selection cursor

### ISSUE THREAD

**Issue by Ehoudry** [rundeck/rundeck#3922]
**Describe the bug**
In some rundeck panels, the "text edit" cursor is used instead of the selection cursor :
- graphical calendar edition while choosing a date in "Run Job Later"
- job selection while editing a step in a workflow
- group selection while editing a job

It is the wrong cursor, the selection cursor (hand with a pointing finger) should be used instead.

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [e.g. ubuntu 16.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**
1. Edit a job
2. Add a step
3. Click on Job reference 
4. Click on choose a job
5. The edit cursor is used to select the job

**Expected behavior**
It would be nice to have the selection cursor as elsewhere

**Screenshots**

**Desktop (please complete the following information):**
- OS: Macos Sierra or Linux fedora
- Browser chrome, safari, firefox
- Version firefox 61.0.1 , Chrome 68.0.3440.84, Safari 11.1.2

**Additional context**

**Comment by jessemarple** [comment]
@Ehoudry - you identified your rundeck version as 2.11.3 but the title mentions rundeck 3. which seems to be exhibiting the issue?

**Comment by Ehoudry** [comment]
Sorry I didn't update the field "Rundeck version" where 2.11.3 is the default. The right version is 3.0

**Comment by jessemarple** [comment]
- graphical calendar edition while choosing a date in "Run Job Later" - was resolved in earlier release.
