### ISSUE TITLE
RD3 : session timeout missing

### ISSUE THREAD

**Issue by Daryes** [rundeck/rundeck#3929]
**My Rundeck detail**

* Rundeck version: 3.0.2
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: H2 file

**To Reproduce**
The documentation for RD3 didn't change from the previous version, [it still point](https://rundeck.org/docs/administration/configuration/configuration-file-reference.html#session-timeout) to the file :
`/var/lib/rundeck/exp/webapp/WEB-INF/web.xml `

Problem, as RD3 switched to a WAR file, the directory /var/lib/rundeck/exp/webapp is now empty, as expected from this format.

Does the creation of a web.xml empty file with the xml header and the <session-timeout> tag and value is usable, or another way is required ?

**Comment by gschueler** [comment]
Our documentation project has moved to a new repo: https://github.com/rundeck/docs

I've filed the issue there: https://github.com/rundeck/rundeck/issues/3929

Thanks!

**Comment by gschueler** [comment]
FYI: you can configure session timeout in rundeck-config.properties or via Java System property with `server.session.timeout` (time in seconds)
