### ISSUE TITLE
rd3: Node detail popup missing from execution Definition tab

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#3932]
**Describe the bug**
Clicking on the node that matches the filter does not bring up the node's detail.

**My Rundeck detail**

* Rundeck version: 3.0.3
* install type: launcher
* OS Name/version: Darwin
* DB Type/version: H2

**To Reproduce**
Run a job
1. Go to that job's execution page
2. Click on Definition tab
3. Scroll down to node filter and click a matching node

**Expected behavior**
Popup for node detail should be displayed.

**Screenshots**
Here is the 2.x UI
![image](https://user-images.githubusercontent.com/275924/44694125-9b8a2f00-aa20-11e8-9024-146da3112d03.png)

**Desktop (please complete the following information):**
 - OS: Darwin
 - Browser: Firefox
 - Version: 62

**Comment by gschueler** [comment]
i can see the popups (3.0.5-SNAPSHOT)
