### ISSUE TITLE
Rundeck 3 bug : Most of the GUI Customization are broken

### ISSUE THREAD

**Issue by Antoine-Auffret** [rundeck/rundeck#3936]
**Describe the bug**
We can modify some display features of the Rundeck GUI by setting properties in the rundeck-config.properties. However, with in the UI (Rundeck 3) most of them are broken or doesn't work as expected.
We can find the list of these properties [here](https://rundeck.org/docs/administration/configuration/gui-customization.html) in the doc.

For example : 
- _rundeck.gui.navbar.background_ doesn't change any background color
- _rundeck.gui.brand.html_ doesn't change the brand name
- _rundeck.gui.title_ change only the title near the rundeck version (bottom left) 3.0.4-20180827 but the main title (top left)

**My Rundeck detail**

* Rundeck version: 3.0.4
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: mysql 5.7.23

**To Reproduce**
1. Edit the configuration file rundeck-config.properties
2. Add for instance the property _rundeck.gui.navbar.background=#FF0000_
3. Save the file and restart rundeck
4. Log into rundeck
5. Look at the nav bar color

**Expected behavior**
The nav bar color should change (#FF0000)

**Desktop (please complete the following information):**
 - OS: ubuntu 16.04
 - Browser: firefox
 - Version: 61.0.1

**Additional context**
The goal is to differentiate multiple rundeck instances when we connect/use rundeck (background color, custom title...).
See #3673 (outdated) for more information and screenshots.

**Comment by jessemarple** [comment]
A few of the GUI customizations have changed or been deprecated. We've also added a few of new options.

Changes include: logo
Deprecations include: 2x logo, navbar, brand.html, title
Additions include: logoSmall, instanceName, instanceNameLabelColor, instanceNameLabelTextColor, sidebarColor, sidebarTextColor, sidebarTextActiveColor

I'm including a screengrab of the updated 3.0.x documentation. It's currently making it's way up the release chain and should be available online shortly.

<img width="806" alt="screen shot 2018-08-30 at 4 21 25 pm" src="https://user-images.githubusercontent.com/265904/44877310-94a62b00-ac71-11e8-977e-866061853100.png">

**Comment by Antoine-Auffret** [comment]
Thank you, sounds great.
Can't wait to test this out when it will release !
