### ISSUE TITLE
UI Plugins Not Being Loaded

### ISSUE THREAD

**Issue by kyleflan** [rundeck/rundeck#3946]
**Describe the bug**
UI Plugins are not loaded

**My Rundeck detail**

* Rundeck version: rundeck_3.0.5.20180828-1.201808282140
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: postgres

**To Reproduce**
1. (On build server) `git clone https://github.com/rundeck-plugins/ui-plugin-examples.git`
2. `cd ui-plugin-examples/ && gradle build`
3. `scp ./build/distributions/rundeck-ui-plugin-examples-1.0-plugin.zip user@rundeckserver:/home/user`
4. (On rundeck server) `sudo mv /home/user/rundeck-ui-plugin-examples-1.0-plugin.zip /var/lib/rundeck/libext/`
5. `sudo service rundeckd restart`
6. Access Rundeck via web browser and navigate to the Jobs page.

**Expected behavior**
Hello world, random XKCD image, etc. as described in the [ui-plugin-example](https://github.com/rundeck-plugins/ui-plugin-examples) appear in the UI.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Mac OSX
 - Browser: Chrome
 - Version: Version 68.0.3440.106 (64-bit)

**Additional context**
I have fiddled with the permissions of the rundeck-ui-plugin-examples-1.0-plugin.zip file in /var/lib/rundeck/libext and have set the owner/group as both rundeck and root (restarting after each change), but none of the UI changes were effected. 

I have reviewed the logs at /var/log/rundeck, but they don't have any mention of loading the plugin, much less any failure.

**Comment by jtobard** [comment]
The example is not updated for rd3.0 I'm going to move the issue to that repo: https://github.com/rundeck-plugins/ui-plugin-examples/issues/1

**Comment by kyleflan** [comment]
Does this imply the [Plugin UI Documentation](https://rundeck.org/docs/developer/ui-plugins.html) is also out of date for rd3.0? I've tried building a plugin from scratch following that documentation with the same results.
