### ISSUE TITLE
Is there a way to kill a job running on a different cluster node?

### ISSUE THREAD

**Issue by askmike1** [rundeck/rundeck#3949]
**Describe the bug**
If a job happens to be running on another RD node, I am unable to kill it. The only thing that seems to be able to fix it (if the job is hung) is to restart the rundeck process on the node it is running on. Is there any workaround to this?

**My Rundeck detail**

* Rundeck version: 2.11.3-1
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux Server release 7.5
* DB Type/version: MariaDB

**To Reproduce**
1. Have multiple nodes setup for RD as cluster
2. Get job running on different node
3. Try to kill

**Expected behavior**
Job should be killed regardless of where it is running

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 63

**Additional context**

**Comment by rockandska** [comment]
Related to #2783 too
