### ISSUE TITLE
Apparently unable to delete storage item without refreshing page

### ISSUE THREAD

**Issue by plambert** [rundeck/rundeck#3950]
**Describe the bug**
Helped someone else to create a storage key, and then a few moments later they attempted to delete it.  After confirming the deletion, the key was still there.  Deleted it again, it was still there.  Third time, received an error about an invalid token.  Hit refresh, and it was gone.  Confirmed with another key that the delete works the first time but the UI does not update, which leads to confusion and frustration.

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
Pro 3.0.5
* install type: [choose: rpm,deb,war,launcher]
Not sure (was someone else's install)
* OS Name/version: [e.g. ubuntu 16.04]
Not sure (was someone else's install)
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]
Not sure (was someone else's install)

**To Reproduce**
1. Create a storage key
2. Remove the storage key
3. In this case, the key didn't disappear from the UI.

**Expected behavior**
Changes should always reflect in the UI immediately.  In this case, I suspect it's a browser-specific bug, but am not sure.

**Screenshots**
None available, sorry

**Desktop (please complete the following information):**
 - OS: Windows (version unknown)
 - Browser: Internet Explorer
 - Version: version unknown, looked pretty recent

**Additional context**
Sorry I don't have more to help reproduce, it was a remote help session.

**Comment by gschueler** [comment]
I think this has been observed using IE
