### ISSUE TITLE
Rundeck 3 : Label of options with Remote URL are not displayed

### ISSUE THREAD

**Issue by Ehoudry** [rundeck/rundeck#3951]
**Describe the bug**
The label of an option with a "Remote URL" for "Allowed values" is not displayed. The name of the option is displayed instead.

**My Rundeck detail**
* Rundeck version: Rundeck DSI/SESI 3.0.3-20180824
* install type: rpm
* OS Name/version: CentOS Linux release 7.5.1804
* DB Type/version: mysql

**To Reproduce**
1. Edit a job
2. Add an option with a name and a label
3. Choose "Remote URL" for the "Allowed values" field
4. Save the job
5. Run the job
6. Option name is displayed instead of the option label, for this option

**Expected behavior**
Expect to have the option label displayed

**Screenshots**

**Desktop (please complete the following information):**
- OS: Macos Sierra or Linux fedora
- Browser chrome, safari, firefox
- Version firefox 61.0.1 , Chrome 68.0.3440.84, Safari 11.1.2

**Additional context**

**Comment by joelsdc** [comment]
+1. 

I run into this on `v3.0.5` and latest deb `v3.0.8.20181029-1.201810292220`.

**Comment by brucegivens** [comment]
+1

**Comment by d3vkit** [comment]
This is still an issue as of Rundeck 3.0.14-SNAPSHOT Docker image, would be great to see it resolved.

**Comment by sergiovier** [comment]
+1

**Comment by JaviSP** [comment]
+1
