### ISSUE TITLE
Execution missing text status

### ISSUE THREAD

**Issue by jessemarple** [rundeck/rundeck#3959]
Execution Show status message - e.g. "Failed after 10s at 2:23 pm started . . . ." - is missing the status string.

**Comment by jessemarple** [comment]
It appears that the data that should be coming in from the return value of executionState() and executionStatusString() aren't returning and thus not generating the text in the UI.

**Comment by gschueler** [comment]
@jessemarple the issue is due to css.  the data is set correctly on the dom using `data-execstate` attribute.

It seems like this Less code was not converted to sass:

https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/assets/less/app.less#L94-L233

needs to be added to the scss
