### ISSUE TITLE
Job Reference icon not shown in execution report/summary 

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#3971]
**Describe the bug**

When viewing Execution page and looking at the Report/Summary of nodes, any Job Reference step should show a Job icon.  No icon is shown, just a blank square.

**My Rundeck detail**

* Rundeck version: 3.0.5

**To Reproduce**

Create a job the echoes some output such as "echo hi"
Create another job using a Job Reference step to the first job
Execute the second job

**Expected behavior**

The Summary/Report tab should show an icon for the Job Reference when the node is expanded.

**Screenshots**

![screen shot 2018-08-31 at 1 16 05 pm](https://user-images.githubusercontent.com/55603/44934173-b4485c80-ad20-11e8-8254-f130648dd5ad.png)

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser Chrome

**Additional context**

The problem is due to missing CSS.  the `.rdicon.job` selector was used in original app .less code, is no longer defined.  

Original less code: https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/assets/less/app.less#L329-L333

**Comment by gschueler** [comment]
bump

**Comment by carlosrfranco** [comment]
Still happening in v3.2.5
