### ISSUE TITLE
Ansible: add inventory with 'become privilege' enabled fails

### ISSUE THREAD

**Issue by cukal** [rundeck/rundeck#3973]
**Describe the bug**
When adding nodes via Ansible inventory with "become privilege" enabled the log file file shows: 
```
fatal: [server.com -> localhost]: FAILED! => {"changed": false, "module_stderr": "sudo: a password is required\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```
It's connecting as the ansible user but that user has password-less sudo rights on the node. 
Running a command on the node like ```sudo -u root "whoami"``` works without the error.
I have to disable the "become privilege" otherwise no node/facts are added to Rundeck. 

What is the use of the Privilege Escalation option or for what is it actually used?
Is the idea when running commands/jobs on the node to set them up with ```sudo -u root "command goes here"```?

**My Rundeck detail**
* Rundeck version: Rundeck 3.0.5-20180828
* install type: yum
* OS Name/version: Centos7.4

**To Reproduce**
1. Add Ansible inventory
2. Enable the become privilege
3. select sudo method

**Expected behavior**
No prompting for password as ansible ssh user is in /etc/sudoers with no password config

**Comment by mgamboa** [comment]
That no happen on 3.0.19 possible you need to update you rundeck version mate
