### ISSUE TITLE
rundeckd.conf contains an error preventing proper startup

### ISSUE THREAD

**Issue by damageboy** [rundeck/rundeck#3974]
**Describe the bug**
Commit [22f72f6ffaa4b94303a3fa9fca06064252aab358](https://github.com/rundeck/rundeck/commit/22f72f6ffaa4b94303a3fa9fca06064252aab358) added quotes around `exec $rundeckd`

This means that when trying to start rundeck, `$rundeckd` contains multiple arguments, such as:
```bash
/usr/lib/jvm/jdk-8-oracle-x64/bin/java -Drundeck.jaaslogin=true            -Djava.security.auth.login.config=/etc/rundeck/jaas-activedirectory.conf            -Dloginmodule.name=activedirectory            -Drdeck.config=/etc/rundeck            -Drundeck.server.configDir=/etc/rundeck            -Dserver.datastore.path=/var/lib/rundeck/data/rundeck            -Drundeck.server.serverDir=/var/lib/rundeck            -Drdeck.projects=/var/lib/rundeck/projects            -Drdeck.runlogs=/var/lib/rundeck/logs            -Drundeck.config.location=/etc/rundeck/rundeck-config.properties            -Djava.io.tmpdir=/tmp/rundeck            -Drundeck.server.workDir=/tmp/rundeck            -Dserver.http.port=4440            -Drdeck.base=/var/lib/rundeck  -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server  -jar /var/lib/rundeck/bootstrap/rundeck-3.0.5-20180828.war --skipinstall
```

Unfortunately, quoting this as `"$rundeckd"` causes the bash to try to look for an EXECUTABLE with the name:
`"/usr/lib/jvm/jdk-8-oracle-x64/bin/java -Drundeck.jaaslogin=true            -Djava.security.auth.login.config=/etc/rundeck/jaas-activedirectory.conf            -Dloginmodule.name=activedirectory            -Drdeck.config=/etc/rundeck            -Drundeck.server.configDir=/etc/rundeck            -Dserver.datastore.path=/var/lib/rundeck/data/rundeck            -Drundeck.server.serverDir=/var/lib/rundeck            -Drdeck.projects=/var/lib/rundeck/projects            -Drdeck.runlogs=/var/lib/rundeck/logs            -Drundeck.config.location=/etc/rundeck/rundeck-config.properties            -Djava.io.tmpdir=/tmp/rundeck            -Drundeck.server.workDir=/tmp/rundeck            -Dserver.http.port=4440            -Drdeck.base=/var/lib/rundeck  -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server  -jar /var/lib/rundeck/bootstrap/rundeck-3.0.5-20180828.war --skipinstall"` (Quotes purposely left).

This executable obvisously does NOT exist, and the `service.log` contains:
```bash
/proc/self/fd/9: 6: exec: /usr/lib/jvm/jdk-8-oracle-x64/bin/java -Drundeck.jaaslogin=true            -Djava.security.auth.login.config=/etc/rundeck/jaas-activedirectory.conf            -Dloginmodule.name=activedirectory            -Drdeck.config=/etc/rundeck            -Drundeck.server.configDir=/etc/rundeck            -Dserver.datastore.path=/var/lib/rundeck/data/rundeck            -Drundeck.server.serverDir=/var/lib/rundeck            -Drdeck.projects=/var/lib/rundeck/projects            -Drdeck.runlogs=/var/lib/rundeck/logs            -Drundeck.config.location=/etc/rundeck/rundeck-config.properties            -Djava.io.tmpdir=/tmp/rundeck            -Drundeck.server.workDir=/tmp/rundeck            -Dserver.http.port=4440            -Drdeck.base=/var/lib/rundeck  -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server  -jar /var/lib/rundeck/bootstrap/rundeck-3.0.5-20180828.war --skipinstall: not found
```

The fix should be clearly to get rid of the quoted in:
https://github.com/rundeck/rundeck/blob/master/packaging/debroot/etc/init/rundeckd.conf

**My Rundeck detail**

* Rundeck version: 3.0.5
* install type: deb
* OS Name/version: ubuntu 14.04
* DB Type/version: h2

**To Reproduce**
1. Install rundeck
2. It can't start

**Expected behavior**
It should start

**Additional context**

**Comment by damageboy** [comment]
Do you want me to submit a PR for this?

**Comment by gschueler** [comment]
@damageboy please do if you are able, thank you.

i'm confused why this would pass our basic ci test for install in that case.  

https://github.com/rundeck/rundeck/blob/master/.travis.yml#L82

https://github.com/rundeck/rundeck/blob/master/test/test-docker-install-deb.sh

the tests that are run:

https://github.com/rundeck/rundeck/blob/master/docker/installcommon/scripts/deb-tests.sh

I think we need a better check of the service.log to verify it reaches the "running" state of the app, by grepping for the "Grails application running" text, as we do here https://github.com/rundeck/rundeck/blob/master/test/docker/dockers/rundeck/scripts/start_rundeck.sh#L296

(Bonus points on the PR if you update the tests ;)

**Comment by damageboy** [comment]
@gschueler I'll give it a try :) (re. the tests)

**Comment by gschueler** [comment]
@damageboy if you still are working on a test case 👍 ,  but i made the change so it can be in the next release.

**Comment by damageboy** [comment]
I am on vacation, but will try adding a test case
