### ISSUE TITLE
Calendar Widget in Rundeck 3 Looks Bad

### ISSUE THREAD

**Issue by damageboy** [rundeck/rundeck#3980]
**Describe the bug**
When you click on month selection, you get this:
![image](https://user-images.githubusercontent.com/125730/45084298-a9b60a80-b106-11e8-82eb-87f3a05ae34e.png)

And click the year selection:
![image](https://user-images.githubusercontent.com/125730/45084346-c6ead900-b106-11e8-993a-b642be7d9af7.png)

**My Rundeck detail**

* Rundeck version: 3.0.5
* install type: deb
* OS Name/version: ubuntu 14.04
* DB Type/version: h2

**To Reproduce**
1. Click month/year selection on calendar widget

**Expected behavior**
The widget should look better and allow for selecting in a non-confusing manner.

**Screenshots**
![image](https://user-images.githubusercontent.com/125730/45084298-a9b60a80-b106-11e8-82eb-87f3a05ae34e.png)

And click the year selection:
![image](https://user-images.githubusercontent.com/125730/45084346-c6ead900-b106-11e8-993a-b642be7d9af7.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox/Chrome
 - Version 61/68

**Comment by richiereynolds** [comment]
Yep, click on the time to type one in and it's all over the place.

**Comment by sksirajbasha** [comment]
In which version of rundeck does the calendar exists ?
