### ISSUE TITLE
How to change HMac tokens timeout

### ISSUE THREAD

**Issue by thienhuu1507** [rundeck/rundeck#3981]
** My detail rundeck **
* Rundeck version:  2.5.1
* install type: rpm
* OS Name/version: centos 7
* DB Type/version: postgres in future.

rundeck-2.5.1\rundeckapp\src\groovy\org\rundeck\web\infosec\HMacSynchronizerTokensHolder.groovy
public static final long DEFAULT_DURATION= Long.getLong(HMacSynchronizerTokensHolder.class.name + '.DEFAULT_DURATION', 30 * 60 * 1000L) ? What does this mean for HMac Token timeout? How to check the expiration time?
and 
I try changing HMac tokens timeout by adding this line:
-Dorg.rundeck.web.infosec.HMacSynchronizerTokensHolder.DEFAULT_DURATION=[timeout in ms] 
into /etc/rundeck/profile. But not working for me! 
Help me !

**Comment by dtvuong** [comment]
I also got the similar issue on version 2.5.1.
I've tested on both of Windows environment and CentOS environment, my token is never expired.
I tried to set "rundeck.security.useHMacRequestTokens : true" for ensure but there is nothing difference.
I assume that maybe a bug.
