### ISSUE TITLE
UI issue 3.0.5 : Fields not aligned on a job with options

### ISSUE THREAD

**Issue by mazzella-c** [rundeck/rundeck#3986]
**Describe the bug**
Fields not aligned on a job with options

**My Rundeck detail**

* Rundeck version: 3.0.5
* install type: war
* OS Name/version: SLES 11 SP4
* DB Type/version: mysql

**To Reproduce**
1. Create a job with options
2. When you run the job field one and field 2 are not aligned

**Expected behavior**
Fields should be aligned

**Screenshots**
Ok on 2.11.4
![ui_ok](https://user-images.githubusercontent.com/38751896/45142905-07575f00-b1ba-11e8-819e-6cc24ca065f6.PNG)

Ko on 3.0.5
![ui_ko](https://user-images.githubusercontent.com/38751896/45142917-11795d80-b1ba-11e8-9437-b84de26db386.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser : Chrome/IE/Firefox
 - Version :69/11/62

**Comment by richiereynolds** [comment]
Noticed this too +1

**Comment by jessemarple** [comment]
I believe this is resolved. If its not, please let us know.

**Comment by mazzella-c** [comment]
All good, thank you.
