### ISSUE TITLE
3.0.x and above no longer accepts "refreshInterval" in jaas-loginmodule.conf

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#3987]
**Describe the bug**
jaas-loginmodule.conf authentication type does not accept the refresh interval to update info from realm.propreties:

RDpropertyfilelogin {
        org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
                debug="true";
                refreshInterval="60";
                caseInsensitive="true";
                file="/etc/rundeck/realm.properties";
        org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
                debug="true";
                useFirstPass="true";
                refreshInterval="60";
                caseInsensitive="true";
                file="/etc/rundeck/realm.properties";
};

**My Rundeck detail**

* Rundeck version: tested on 3.0.1 and 3.0.5
* install type: tested on rpm and yum install
* OS Name/version: centos 7
* DB Type/version: default

**To Reproduce**
1. install via yum or deb
2. do standard modifications (hostname to ip)
3. add "refreshInterval="60" to jaas-loginmodule.conf
4. restart rundeck
5. Any changes to realm.properties requires a restart of rundeckd to take effect

**Expected behavior**
Previously, this parameter allowed for the realm.properties file to dynamically be updated and loaded without restarting rundeckd.

**Comment by mazzella-c** [comment]
Same issue here.

**Comment by omniton** [comment]
Sam issue with org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule.

I have following jaas config:

login {
org.rundeck.jaas.jetty.JettyPamLoginModule requisite
    debug="true"
    service="sshd"
    supplementalRoles="readonly"
    storePass="true";

org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
    debug="true"
    useFirstPass="true"
    refreshInterval="60"
    caseInsensitive="true"
    file="/etc/rundeck/realm.properties";
};

Rundeck doesn't see any changes in realm.properties file until restarted

**Comment by dseira** [comment]
Same happen to me with the following `jaas-loginmodule.conf`:

```
RDpropertyfilelogin {

    org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
        debug="false"
        refreshInterval="30"
        file="/etc/rundeck/realm.properties";

};
```

The version of rundeck is `rundeck-3.0.9.20181127-1.201811291844.noarch` in a CentOS 7.5.

**Comment by sjrd218** [comment]
Please see this comment https://github.com/rundeck/rundeck/issues/4268#issuecomment-443211707
