### ISSUE TITLE
Not able to start rundeck after upgrade to 3.0.5 

### ISSUE THREAD

**Issue by jameslee007** [rundeck/rundeck#3991]
**Describe the bug**
Upgraded rundeck 3.0.5.20180828-1.201808282139.noarch from rundeck-2.11.3-1.54.GA.noarch. After Upggrade not able to start rundeck.

**My Rundeck detail**

* Rundeck version: rundeck 3.0.5
* install type: Yum
* OS Name/version: CentOS Linux release 7.4
* DB Type/version:  mysql]

**To Reproduce**
 yum upgrade rundeck rundeck-config

**Expected behavior**
Rundeck to be start normally

**Screenshots**
Getting the below error in service.log
**Error: Could not find or load main class .var.lib.rundeck
Error: Could not find or load main class .var.lib.rundeck**

**Comment by l0calhost** [comment]
Hey, just fell for the same reason. Rundeck 3.x is now started via .war file, not .jar anymore. have a look at /etc/rundeck, there should be a file `profile` and a new one `profile.rpmnew`. Merge your settings from `profile` to `profile.rpmnew` and rename the file.

**Comment by rhughes1** [comment]
@jameslee007 Take a look at this: https://github.com/rundeck/rundeck/issues/3995#issuecomment-420124939

**Comment by jameslee007** [comment]
Thank you I0calhost and rhughes1. I made the changes as mentioned for profile and project.properties files.
Now Rundeck started successfully. Thanks a lot for your help.

**Comment by rhughes1** [comment]
@mfern1 Did you take a look at the comment I pasted above? Also did you need to modify anything in `/etc/sysconfig/rundeckd`?

**Comment by sys-ops** [comment]
In my case the following difference in /etc/rundeck/profile file was the most important after moving from 2.10.2 to 3.0.6.

### Part of the OLD config:
for **jar** in $(find $RDECK_INSTALL/bootstrap -name **'*.jar'**) ; do
  **BOOTSTRAP_CP=${BOOTSTRAP_CP:+$BOOTSTRAP_CP:}$jar**
done

### Part of the NEW config:
for **war** in $(find $RDECK_INSTALL/bootstrap -name **'*.war'**) ; do
  **EXECUTABLE_WAR=$war**
done

No more jar files in $RDECK_INSTALL/bootstrap.

I hope it helps others when searching for differences in the old and new config files.
