### ISSUE TITLE
Cannot kill jobs that are "running" on a dead Rundeck server

### ISSUE THREAD

**Issue by gservat** [rundeck/rundeck#3993]
My Rundeck UI is showing two jobs that are running on a Rundeck server that isn't up anymore. Can't kill the jobs (error: `Execution is running on a different cluster server: f374fe82-6512-4a80-a7b7-f862b8070f69`). How do I get rid of them apart from digging into the DB?

* Rundeck version: [ e.g. 2.11.5-1]
* install type: deb
* OS Name/version: Ubuntu 14.04
* DB Type/version: postgres

**To Reproduce**
1. Start a Rundeck server (referred as "A")
2. Trigger a long running job
3. Kill the server
4. Spin up another Rundeck server (same DB, etc) with a different UUID - referred as "B"
5. You should see the job still appear as "Running" on "A"
6. Try to kill it. It should say that it's running on "A" so you cannot kill them.

**Expected behavior**
There should be a way to force kill jobs.

**Comment by gservat** [comment]
Related to https://github.com/rundeck/rundeck/issues/3949.

**Comment by rockandska** [comment]
Still relevant in 3.2.1-SNAPSHOT

Related to #2783 too
