### ISSUE TITLE
RD 3.0.1: Can't find delete button on jobs

### ISSUE THREAD

**Issue by gaetanquentin** [rundeck/rundeck#3997]
**Describe the bug**
I want to  delete a job. I can't find the delete button on the UI.

**My Rundeck detail**

* Rundeck version: 3.0.1
* install type: war/launcher
* OS Name/version:  ubuntu 16.04
* DB Type/version: postgres 10

**To Reproduce**
1. Create a job an save it
2. Edit it
3. On the below of page, there is only "Save" and Cancel buttons.

**Expected behavior**
There should be a delete button too

Note: there is well a delete button in the "project" menu.
**Screenshots**

below the edit config job:
![image](https://user-images.githubusercontent.com/5774881/45296444-4fe88280-b502-11e8-9b3c-e9dbdae2797a.png)

Job menu:
![image](https://user-images.githubusercontent.com/5774881/45296543-aa81de80-b502-11e8-8a9d-9e298463b428.png)

**Desktop (please complete the following information):**
 - OS: ubuntu bionic 18
 - Browser: firefox 61

**Additional context**
- loggued user is admin

/data/rundeck/server/config/realm.properties:
admin:XXXX,user,admin,architect,deploy,build

/data/rundeck/etc/admin.aclpolicy:
description: Admin project level access control. Applies to resources within a specific project.
context:
  project: '.*' # all projects
for:
  resource:
    - equals:
        kind: job
      allow: [create] # allow create jobs
    - equals:
        kind: node
      allow: [read,create,update,refresh] # allow refresh node sources
    - equals:
        kind: event
      allow: [read,create] # allow read/create events
  adhoc:
    - allow: [read,run,runAs,kill,killAs] # allow running/killing adhoc jobs
  job:
    - allow: [create,read,update,delete,run,runAs,kill,killAs] # allow create/read/write/delete/run/kill of all jobs
  node:
    - allow: [read,run] # allow read/run for nodes
by:
  group: admin

Logs while browsing the UI to find the button::
[rundeck-logs-delete-button.zip](https://github.com/rundeck/rundeck/files/2366527/rundeck-logs-delete-button.zip)

**Comment by gaetanquentin** [comment]
So, i added the delete right to acl:
escription: Admin project level access control. Applies to resources within a specific project.
context:
  project: '.*' # all projects
for:
  resource:
    - equals:
        kind: job
      allow: [create,delete] # allow create jobs

but i don't understand: what is the difference between this:
  resource:
    - equals:
        kind: job
      allow: [create,delete] # allow create jobs

and this:
  job:
    - allow: [create,read,update,delete,run,runAs,kill,killAs] # allow create/read/write/delete/run/kill of all jobs

?

**Comment by gschueler** [comment]
allowing `delete` on `resource: kind: job` is a requirement for deleting *any* jobs.  and adding `delete` on a specific job: allows it for a specific job e.g. matching job name.  If you want to allow deleting all jobs, you need to grant `delete` for both.

more here: https://rundeck.org/docs/administration/security/access-control-policy.html#project-scope-resources-and-actions
