### ISSUE TITLE
Feature Request: Use multiple attributes in node filter

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4013]
Would like to be able to combine attributes in node filter. For example:

Name: .*1A Tags: Internal

Currently, you can only use one attribute at a time:

Name: .*1A

or

Tags: Internal

**Comment by gschueler** [comment]
you can use multiple attributes.  in what way does it not work for you?

**Comment by gtsteffaniak** [comment]
> you can use multiple attributes. in what way does it not work for you?

I tried it again and see it does work, when it wasn't working earlier. I noticed its case sensitive, "Tags" does not return values the same as "tags". this can be closed.
