### ISSUE TITLE
Cannot schedule a later execution if job is currently running

### ISSUE THREAD

**Issue by babs** [rundeck/rundeck#4016]
**Describe the bug**
Cannot schedule a later execution if job is currently running

**My Rundeck detail**

* Rundeck version: 3.0.5-20180828
* install type: deb
* OS Name/version: Debian Dtretch
* DB Type/version: MariaDB

**To Reproduce**
1. Create a long running job (ex: `for i in {1..120}; do echo $SECONDS; sleep 1; done`)
2. Run it
3. While it runs, try to schedule  later execution

**Expected behavior**
Being able to schedule a later execution

**Screenshots**
![image](https://user-images.githubusercontent.com/117580/45576980-0e493600-b87a-11e8-8d67-68a878fa4e45.png)

**Comment by ahonor** [comment]
@babs Does the job definition specify for multiple concurrent executions? See screenshot below:

![image](https://user-images.githubusercontent.com/275924/45577975-b091fb00-b833-11e8-9176-659f243be784.png)

**Comment by babs** [comment]
Multiple execution is disable on this job.
Nevertheless it should not prevent you from scheduling a later execution, taking in consideration that a check is run when the job is triggered, don't you think ?
