### ISSUE TITLE
Inventory w/o hostname usually can't execute even with localexec/script-exec and no refrence to these fields

### ISSUE THREAD

**Issue by donaldguy** [rundeck/rundeck#4017]
I made a project with a script inventory using resourcejson representing a non-computer objects, such that hostname and username were irrelevant fields. I thought about adding them anyway but the node ingest didn't complain so I assumed it was fine

I thought I'd still be able to use localexec or script-exec to perform local actions using the `${node.foo}` values that _were_ output by my inventory script. 

But what I found was that while I got intermittent executions, usually they hung with no nodes running indefinitely. This remained the case switching from Localexec to script-exec and even with Stub.

At the time you scheduled a job and it was gonna hang the `service.log` would get a single bare

```
Exception: java.lang.IllegalArgumentException thrown from the UncaughtExceptionHandler in thread "pool-96-1"
```
but no stracktrace or anything

**My Rundeck detail**

* Rundeck version: 3.0.5
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: h2

**To Reproduce**
1. Create a node inventory script that outputs nodename but not hostname or username
2. Create a project using that inventory and the executor set to Local or Stub or Script with command as "${exec.command}" and interpretor as "/bin/bash -c", (anything that shouldn't _need_ a hostname)
3. Make a Job with a command step.
4. Try to run it a few times

**Expected behavior**
It consistently runs and passes or fails as appropriate for the return value of the script

OR

When a file/dir/script Resource Model fails to include universally required fields, this should be an error

**Comment by donaldguy** [comment]
Once I broke down and just added fixed values for these fields things started working consistently ; I should have tried that earlier as it was my suspicion it was the issue - but I was trying to gather any other evidence. ... I really got nothing.

**Comment by donaldguy** [comment]
Though I will admit I didn't check it as I was doing this work today, https://rundeck.org/docs/man5/resource-json.html **does** list these fields as optional

**Comment by gschueler** [comment]
hostname should be optional.  it used to be required, so there still maybe a validation check for it in some place
