### ISSUE TITLE
Rundeck 3: jobs view should be tree-based, as in Rundeck 2.x

### ISSUE THREAD

**Issue by gjvc** [rundeck/rundeck#4020]
**version**
Rundeck 3

**Expected behavior**
Jobs view should be tree-based, as in Rundeck 2.x

**Observed behavior**
The jobs view is panel-based (perhaps motivated by a "mobile-first" approach). Because of the low-contrast palette used for the panel headings, it is difficult to mentally group the jobs accurately and easily.

**Comment by richiereynolds** [comment]
Yes, the lack of indentation on a long list of jobs make it very tricky to know where you are.
It also takes far more space (double at least?) and hence requires far more vertical scrolling to find the job you want in comparison to 2.x, I like the dropdown menu against each job but in general the interface is much more annoying to use. It appears that an attempt has been made to make it look like a mobile phone app!

**Comment by padraiglennon** [comment]
It would be great if this could be addressed as a priority. I've gotten quite a number of negative/confused remarks from colleagues I'm trying to on-board to rundeck. 

Take for example the following image. Its next to impossible to identify the first PROD3 as a sub-group of ENV_MAINTENANCE group. Almost everyone goes to the second PROD3 sub-group. The 2x tree-based made this an non-issue. 

![image](https://user-images.githubusercontent.com/745557/46369987-53dc7000-c67c-11e8-9012-10252543c85b.png)

**Comment by mickymiek** [comment]
Sounds like an easy fix.
For now I temporarily added a custom css line in a browser extension, but someone might want to contribute it.
Here's the line I used if anyone's interested:
 `#job_group_tree .panel-heading + .sub_group {padding-left: 25px !important}`

**Comment by richiereynolds** [comment]
@mickymiek would something similar work on the nodes page? It also takes twice the vertical space in 3.x as the node description appears on a new line.

**Comment by padraiglennon** [comment]
> Sounds like an easy fix.
> For now I temporarily added a custom css line in a browser extension, but someone might want to contribute it.
> Here's the line I used if anyone's interested:
> `#job_group_tree .panel-heading + .sub_group {padding-left: 25px !important}`

This has made my day.. Thank you so much @mickymiek 

Added this to my nginx config and its actually usable now. It's a pity its needed to be honest. 

`location / {
    sub_filter '</head>' '<style type="text/css">#job_group_tree .panel-heading + .sub_group {padding-left: 25px !important}</style></head>';
    sub_filter_once on;
    proxy_pass http://rundeck;
    proxy_set_header Host $host;
  }`

**Comment by mickymiek** [comment]
@padraiglennon happy to help!
@richiereynolds The node page looks ok to me so I don't really know. Maybe you could provide a screenshot so I can see what you are talking about?

**Comment by Kaldor37** [comment]
Thank you very much for this feature, the ui is much more readable now :)
