### ISSUE TITLE
Option to view nodes as single item per line list as per Rundeck 2.x in Rundeck 3.x

### ISSUE THREAD

**Issue by steveh1980** [rundeck/rundeck#4023]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**
Having multiple nodes listed per line in jobs is not easily visible. Having to run a cmd-f to find nodes is a pain.

**Describe the solution you'd like**
Offer the list view option as it was in Rundeck 2.x

**Comment by gschueler** [comment]
can you screenshot exactly where you are having this problem? thanks

**Comment by Antoine-Auffret** [comment]
The first 3 jobs are in tests folder but not the last 3. The difference isn't very pronounced in Rundeck 3.x I prefer the Rundeck 2.x style for a better visualization.
![rundeck3_folder](https://user-images.githubusercontent.com/26813312/45872301-f7ca3f80-bd8f-11e8-909a-473516ad6737.png)

**Comment by richiereynolds** [comment]
Yes, on the nodes page each node takes up 2 lines, This is really annoying, takes up lots of space, doubles the vertical scrolling required and makes it difficult to copy/paste nodes into other files or an email having used a node filter to produce a list.
In 2x it was like:
>LO.LO1.someBox.account -> description of this node
in 3x it's
>LO.LO1.someBox.account ->
description of this node

This is a definite step backwards, there's no extra information or anythign useful here, it's simply made using the tool harder.
