### ISSUE TITLE
Feature request: Save UI langage choice

### ISSUE THREAD

**Issue by gaetanquentin** [rundeck/rundeck#4024]
RD 3.X:

In the UI user profil , you can select language.
But the choice is not saved and must be set again  each time we open a session.

It would be useful to save the choice.

**Comment by gschueler** [comment]
rundeck 3.0.6 should enable this: https://github.com/rundeck/rundeck/issues/3860

**Comment by gschueler** [comment]
if this is still a problem in the latest release, please reopen this issue, thanks.
