### ISSUE TITLE
RD 3.0.X: when session has timed out, UI behave strangely

### ISSUE THREAD

**Issue by gaetanquentin** [rundeck/rundeck#4034]
in RD 3.0.X (0.1 and 0.5), if in job editing mode, and session has timed out after inactivity:

- you are not loggued out automatically
- instead, when you click on steps or other things to edit them, it does nothing

clicking on UI should redirect to login page when session is timed out.

**Comment by gaetanquentin** [comment]
bug still here with 3.0.22

**Comment by gaetanquentin** [comment]
still here with 3.1.2

- editing logfilter: the popup is shown,
- do nothing and  come back in 10 min
-  you click on save: it does nothing

please logout user when session time is over...

**Comment by carlosrfranco** [comment]
Still happening in v3.2.5
