### ISSUE TITLE
Enhance security by encrypting passwords on realm.properties

### ISSUE THREAD

**Issue by outon** [rundeck/rundeck#4042]
I do not like plain text passwords so, this is a personal opinion, all password should be stored in a cryptic way.

I thing that that every time application starts if we have plain passwords on file **realm.propierties** those passwords should be encrypted on the fly and save the file with encrypted passwords.

So password are never stored on plain text

Before RunDeck is running : **realm.properties** may contains:
admin:admin,user,admin,anvils

After RunDeck startup **realm.properties** is modified to:
admin: CRYPT:adpexzg3FUZAk,user,admin,anvils

**Comment by Daryes** [comment]
You can already crypt yourself the passwords in realm.properties. From the file comments :
````
# Passwords may be clear text, obfuscated or checksummed.  The class
# org.mortbay.util.Password should be used to generate obfuscated
# passwords or password checksums
 ````
The [related documentation](https://rundeck.org/docs/administration/security/authenticating-users.html#propertyfileloginmodule) explains how to call the encryption module : 
````
$ java -jar rundeck-3.0.0.war --encryptpwd Jetty
Required values are marked with: *
Username (Optional, but necessary for Crypt encoding):
jsmith    <-----Type this value
*Value To Encrypt (The text you want to encrypt):
mypass    <-----Type this value
````

The thing that could be useful is supporting more powerful encryption schemes, like AES or similar, for storing passwords.  
On the other hand, Rundeck is also perfectly capable to be linked to Active Directory or a basic LDAP. Thus, removing the task of storing the passwords.

**Comment by outon** [comment]
I already know that way to get an encrypted password and even using the GUI

![image](https://user-images.githubusercontent.com/6525261/45815223-474d3480-bcd8-11e8-8ccb-f1ded54971ea.png)

I am asking for an enhancement for when you start application and find a plain text password on **realm.properties** file to  automatically encrypt it.

I use LDAP but always have this other authentication method on file as a backup... just in case no LDAP.
