### ISSUE TITLE
No login possible, while using multiple authenication methods.

### ISSUE THREAD

**Issue by docbyte86** [rundeck/rundeck#4043]
**Describe the bug**
No login possible, while using multiple authenication methods.
Even LDAP nor local users in realm.properties login is possible.
AS soon as i switch to JettyCashedLdapLoginModule and remove JettyRolePropertyFileLoginModule, login with LDAP is possible.

**My Rundeck detail**

    Rundeck version: 3.0.6-20180917 (also detected in 3.0.5-20180828)
    install type: war
    OS Name/version: RHEL 7.5 (Maipo)
    DB Type/version: Oracle 12c
    Tomcat: 8.5.32
    Java: 1.8.0_181
	
**To Reproduce**

1. Using following JAVA_OPTS:
JAVA_OPTS="$JAVA_OPTS -XX:MaxPermSize=1024m -Xmx8192m -Xms8192m -server -Djavax.net.ssl.trustStore={PATHTOCER} -Djavax.net.ssl.trustStoreType={KEYSTORENAME} -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol -Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG -Drundeck.jaaslogin=true -Djava.security.auth.login.config=$RDECK_BASE/server/config/jaas-ldap.conf -Dloginmodule.name=activedirectory -Drdeck.base=$RDECK_BASE -Drundeck.config.location=$RDECK_BASE/etc/rundeck-config.properties"

2. Content of jaas-ldap.conf:

activedirectory {
com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule sufficient
    debug="true"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="ldaps://{domain controller 1}:636"
    bindDn="{user@domain}"
    bindPassword="{userpassword}"
    authenticationMethod="simple"
    forceBindingLogin="true"
    userBaseDn=""
    userRdnAttribute="sAMAccountName"
    userIdAttribute="sAMAccountName"
    userPasswordAttribute="unicodePwd"
    userObjectClass="{secret value}"
    roleBaseDn="{secret value}"
    roleNameAttribute="cn"
    roleMemberAttribute="member"
    roleObjectClass="group"
    cacheDurationMillis="300000"
    reportStatistics="true"
	storePass="true";

com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule sufficient
    debug="true"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="ldaps://{domain controller 2}:636"
    bindDn="{user@domain}"
    bindPassword="{userpassword}"
    authenticationMethod="simple"
    forceBindingLogin="true"
    userBaseDn=""
    userRdnAttribute="sAMAccountName"
    userIdAttribute="sAMAccountName"
    userPasswordAttribute="unicodePwd"
    userObjectClass="{secret value}"
    roleBaseDn="{secret value}"
    roleNameAttribute="cn"
    roleMemberAttribute="member"
    roleObjectClass="group"
    cacheDurationMillis="300000"
    reportStatistics="true"
	storePass="true";

com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule sufficient
    debug="true"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="ldaps://{domain controller 3}:636"
    bindDn="{user@domain}"
    bindPassword="{userpassword}"
    authenticationMethod="simple"
    forceBindingLogin="true"
    userBaseDn=""
    userRdnAttribute="sAMAccountName"
    userIdAttribute="sAMAccountName"
    userPasswordAttribute="unicodePwd"
    userObjectClass="{secret value}"
    roleBaseDn="{secret value}"
    roleNameAttribute="cn"
    roleMemberAttribute="member"
    roleObjectClass="group"
    cacheDurationMillis="300000"
    reportStatistics="true"
	storePass="true";

com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule sufficient
    debug="true"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="ldaps://{domain controller 4}:636"
    bindDn="{user@domain}"
    bindPassword="{userpassword}"
    authenticationMethod="simple"
    forceBindingLogin="true"
    userBaseDn=""
    userRdnAttribute="sAMAccountName"
    userIdAttribute="sAMAccountName"
    userPasswordAttribute="unicodePwd"
    userObjectClass="{secret value}"
    roleBaseDn="{secret value}"
    roleNameAttribute="cn"
    roleMemberAttribute="member"
    roleObjectClass="group"
    cacheDurationMillis="300000"
    reportStatistics="true"
	storePass="true";

com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule sufficient
    debug="true"
    contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
    providerUrl="ldaps://{domain controller 5}:636"
    bindDn="{user@domain}"
    bindPassword="{userpassword}"
    authenticationMethod="simple"
    forceBindingLogin="true"
    userBaseDn=""
    userRdnAttribute="sAMAccountName"
    userIdAttribute="sAMAccountName"
    userPasswordAttribute="unicodePwd"
    userObjectClass="{secret value}"
    roleBaseDn="{secret value}"
    roleNameAttribute="cn"
    roleMemberAttribute="member"
    roleObjectClass="group"
    cacheDurationMillis="300000"
    reportStatistics="true"
	storePass="true";

org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
    debug="true"
    file="$RDECK_BASE/server/config/realm.properties"
	useFirstPass="true"
	tryFirstPass="true";
};

3. content of realm.properties

admin:admin,user,admin
user:user,user

4. Error while logging in, with Local AND LDAP user.

5. Output from catalina.out

2018-09-20 10:06:35.924 DEBUG --- [nio-8443-exec-3] ailsUsernamePasswordAuthenticationFilter : Updated SecurityContextHolder to contain null Authentication
2018-09-20 10:06:35.925 DEBUG --- [nio-8443-exec-3] ailsUsernamePasswordAuthenticationFilter : Delegating to authentication failure handler grails.plugin.springsecurity.web.authentication.Aj  axAwareAuthenticationFailureHandler@44a6367e
2018-09-20 10:07:46.985 DEBUG --- [nio-8443-exec-7] ailsUsernamePasswordAuthenticationFilter : Request is to process authentication
2018-09-20 10:07:46.990 DEBUG --- [nio-8443-exec-7] ailsUsernamePasswordAuthenticationFilter : Authentication request failed: org.springframework.security.authentication.AuthenticationServic  eException: java.lang.NoClassDefFoundError: org/eclipse/jetty/security/PropertyUserStore ....

**Expected behavior**
Authentfication via corresponding LDAP and local admin user.

**Desktop (please complete the following information):**

    OS: Windows 10
    Browser FireFox
    Version 52.9.0

We used the official documentation from

 https://rundeck.org/docs/administration/security/authenticating-users.html#multiple-authentication-modules
 https://rundeck.org/docs/administration/security/authenticating-users.html#jettyrolepropertyfileloginmodule
 "Combining LDAP with other modules"

**Comment by gtsteffaniak** [comment]
same issue here on 3.0.7

**Comment by sjrd218** [comment]
@docbyte86 @gtsteffaniak Can you try the following:

Copy the `$TOMCAT_BASE/webapps/rundeck-$VERSION/WEB_INF/lib-provided/jetty-security-9.4.11.v20180605.jar` to `$TOMCAT_BASE/webapps/rundeck-$VERSION/WEB_INF/lib/jetty-security-9.4.11.v20180605.jar` then reset your configuration to try the multi-authentication method setup, restart tomcat, and see if it works.

**Comment by gtsteffaniak** [comment]
I actually figured it out. It's a bit confusing without knowing the differences, but according to documentation:

> Modules:
> 
> - **org.rundeck.jaas.jetty.JettyPamLoginModule** authenticates via PAM, can add a default set of roles to authenticated users, and can use local unix group membership for role info.
> - **org.rundeck.jaas.jetty.JettyAuthPropertyFileLoginModule** authenticates via property file, but does not supply user authorization information.
> - **org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule** does not authenticate and only uses authorization roles from a property file. Can be combined with previous modules.

So in your example, you are only using the role login module which does not authenticate. You could add auth login module to login with admin/admin.

Also , just for saving you any trouble, if you have problems with the roleAuth module, try changing "caseInsensitive". Mine only worked when this was set to false.
