### ISSUE TITLE
GUI: left panel arrow

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#4044]
**Describe the bug**
Left panel's arrow is not showing properly

**My Rundeck detail**

* Rundeck version: 3.0.6
* install type: war
* OS Name/version: osx
* DB Type/version: *

**Screenshots**
![captura de pantalla de 2018-09-20 13-09-53](https://user-images.githubusercontent.com/34582874/45832109-6ac3af80-bcd7-11e8-85c0-959b81542ae7.png)

**Desktop (please complete the following information):**
 - Browser FF
 - Version: 62

**Comment by jplassnibatt** [comment]
Looks like this issue is on upgrades to 3.0.6.-

**Comment by jessemarple** [comment]
This is a pro issue. Moving to pro for fix.
