### ISSUE TITLE
Scrolling output log

### ISSUE THREAD

**Issue by cukal** [rundeck/rundeck#4047]
**Is your feature request related to a problem? Please describe.**
Job output does not seems to auto-scroll. We're migrating jobs away from Jenkins to Rundeck but the auto-scroll feature in Jenkins is really nice to follow a long job log output. When executing a job with lots of output I always have to scroll manually down to catch up with the logging output. 
With Jenkins I can start a job, click on the console output (the job log output) and it will auto-scroll with the job-output always showing the what it's doing. 
With Rundeck I have to manually scroll down to see what the logging is doing.

**Describe the solution you'd like**
It would be really great if the job output would auto-scroll the browser window or follow/tail the log output so no manual scrolling is needed. 

**Describe alternatives you've considered**
None.

**Additional context**
Edit: Example: [https://monosnap.com/file/J5n2mmM7S8c7nmCrEKaSiCWXYme0tc](https://monosnap.com/file/J5n2mmM7S8c7nmCrEKaSiCWXYme0tc)

**Comment by jgibbarduk** [comment]
I have the same issue! It used to scroll in Rundeck version 2.xx.x. Please can this be reinstated?

**Comment by Kaldor37** [comment]
Same here, this feature is deeply missed since we migrated to v3 :)

**Comment by alexcasutt** [comment]
+1

**Comment by hs-hub-world** [comment]
+1

**Comment by rg-fine** [comment]
+1

**Comment by nmamn** [comment]
same issue here when migrating from 2.11.X to the latest 3.0 version, could it be please be put back as before ?

**Comment by rdemendoza** [comment]
+1

**Comment by getjack** [comment]
Has anyone an idea where i would find the code to implement this?
https://github.com/rundeck/rundeck/tree/master/rundeckapp ?

**Comment by nmamn** [comment]
> gschueler removed this from the 3.1.0-RC2 milestone on 18 Jul

too bad :-(

**Comment by amartin3225** [comment]
+1

**Comment by rdemendoza** [comment]
+1

**Comment by puremourning** [comment]
@getjack  in `rundeckapp/grails-app/assets/javascripts/executionControl.js` there is a function `scrollToBottom()`. This scrolls the window, but in the new UI the main scrolling element is actually a div named `#main-panel`.

You could try this:

```javascript
    scrollToBottom: function()
    {
        var elem = document.querySelector( '#main-panel' );
        elem.scrollTop = elem.scrollHeight;
    },
```

Note: i haven't tested this and it's probably dodgy for that object to go and find the element in the DOM but running that code in the chrome debugger makes the right part of the screen scroll.

Probably needs an update to the `isAtBottom()` function above too.

**Comment by puremourning** [comment]
Seems to fix it:

```diff
diff --git a/rundeckapp/grails-app/assets/javascripts/executionControl.js b/rundeckapp/grails-app/assets/javascripts/executionControl.js
index 5dee8aa16..ad72d768c 100644
--- a/rundeckapp/grails-app/assets/javascripts/executionControl.js
+++ b/rundeckapp/grails-app/assets/javascripts/executionControl.js
@@ -767,14 +767,16 @@ var FollowControl = function (eid, elem, params) {
     },
     isAtBottom: function()
     {
-        var a = document.documentElement.scrollHeight || document.body.scrollHeight;
-        var b = document.documentElement.scrollTop || document.body.scrollTop;
-        var c = document.documentElement.clientHeight || document.body.clientHeight;
+        var elem = document.querySelector( '#main-panel' );
+        var a = elem.scrollHeight;
+        var b = elem.scrollTop;
+        var c = elem.clientHeight;
         return ((a - b) <= (c*1.1));
     },
     scrollToBottom: function()
     {
-        window.scrollTo(0, document.documentElement.scrollHeight || document.body.scrollHeight);
+        var elem = document.querySelector( '#main-panel' );
+        elem.scrollTop = elem.scrollHeight;
     },
     genDataRowNodes: function(data, tbl) {
         this.reverseOutputTable(tbl);
```

**Comment by stevemsmith** [comment]
Looks like this issue needs re-opened.  I don't see it tracked in the Project tab, but it looks like commits are being added.  Thanks for working on it!  We just upgraded from 2.8.X and miss it dearly.

**Comment by cukal** [comment]
This sadly was a showstopper for us to introduce Rundeck into ops back in 2018.
I really would like to pick it up once more, has this been fixed?

**Comment by puremourning** [comment]
It was fixed, no?

**Comment by bbgmartin** [comment]
I am running rundeck 3.3.10 and it doesn't auto scroll for me.
