### ISSUE TITLE
Conditional Retries: Only Retry Job if Specified Step Fails

### ISSUE THREAD

**Issue by kyleflan** [rundeck/rundeck#4049]
**Is your feature request related to a problem? Please describe.**
A requirement we have is that no more than 4 jobs run per node simultaneously. My initial plan was to set up two steps in a workflow with the first step being a script to check the number of jobs running and return a failure if more than 4 jobs are running and then retry the Rundeck job. However, if the second "main" step fails, it's important that the job NOT retry until the issue can be manually investigated. 

**Describe the solution you'd like**
Add an option to a job step that flags whether the job should be retried if this step fails (e.g. "Retry Job on Step Failure? Yes/No"). By default, this would always be true, but could be set to false for this use case. E.g. A job with two steps, A and B, would retry the job if A failed, but would not retry the job if B failed.

**Describe alternatives you've considered**
I have attempted to use an Error Handler based on the first step (which checks if there is room to run) to use Flow Control to Halt the job. However, you cannot use a Workflow step as an Error Handler for a node step.

A bit of background: I'm evaluating Rundeck as a centralized scheduler to replace individual crontabs on a number of servers. Currently, each server has a set of jobs scheduled via cron, but if server X goes down, all of the jobs scheduled on X quietly fail. I have Rundeck configured using the Random Subset orchestrator to push a job out to only one node, thus fulfilling this centralized scheduler use case, but am not able to completely utilize Rundeck due to the possibility of one node getting randomly selected more than 4 times during peak job demand.

**Comment by remifrazierucsf** [comment]
See also #3153
