### ISSUE TITLE
RD3: var/.install_complete file won't let to upgrade properly

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#4056]
**Describe the bug**
Upgrade from rd2 to rd3 or from rd3 to newer rd3 creates a $rdeck.base/var/.install_complete file, which, if the upgrade went wrong, won't let you upgrade properly even if the issue to upgrade has been fixed.

**My Rundeck detail**
* Rundeck version: from 2.11.5 to 3.0.5 and 3.0.5 to 3.0.6
* install type: war and war+tomcat
* OS Name/version: ubuntu 18.04 and windows 10
* DB Type/version: any

**Expected behavior**
Smooth upgrade process.

**Workaround**
Delete $rdeck.base/var/.install_complete and restart rundeck.

**Comment by gschueler** [comment]
the .install_complete could include the version in the filename, so it doesn't block newer versions during upgrade

**Comment by mlipkin** [comment]
@jplassnibatt When you upgraded from 3.0.5 to 3.0.6, did you do anything other than deploy the new war file in tomcat? The upgrade documentation does not appear to cover upgrading a 3.x version to another 3.x version yet. I've faced several issues upgrading from 3.0.2 to 3.0.6 docker container, fixed most of them but am still seeing an issue or two that I'm worried are not bugs and are actually due to the externalized database not being migrated properly or something along those lines.

**Comment by jplassnibatt** [comment]
Hi @mlipkin 
For upgrades using tomcat, check this https://rundeck.org/3.0.x/upgrading/upgrade-to-rundeck-3.x.html
it will be available in the official documentation in next release.

**Comment by mlipkin** [comment]
thanks @jplassnibatt. If rundeck could include a proper docker container upgrade instructions in their 3.x -> 3.x in the official documentation, that would be greatly helpful. Or at least mentioned in the rundeck/rundeck dockerhub.

**Comment by jplassnibatt** [comment]
Hey @mlipkin, for docker, I think that if you are using proper volume paths and environment variables, you should be ok to use newer versions.
For more specific questions, please log one in in any of these: https://rundeck.org/docs/manual/getting-help.html

**Comment by mlipkin** [comment]
@jplassnibatt Upgrading from docker container 3.0.2 to 3.0.6 caused every single project's project.properties and scm-import/export configs to be wiped out which are stored in the externalized postgres db. Also caused the ssh keys stored in the db to no longer work even though they were still showing, had to reupload them.

**Comment by jplassnibatt** [comment]
@mlipkin that shouldn't happen if you have all set according to the documentation, as this bug is not related to your question, please log one in any of these: https://rundeck.org/docs/manual/getting-help.html
