### ISSUE TITLE
3.0.x web.xml use - alternative method request

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4060]
Since 3.0.x the web.xml file is no longer possible. Our organization had one use for the web.xml that makes it no longer possible on 3.0.x.

Here is our example web.xml
[jetty-web2.txt](https://github.com/rundeck/rundeck/files/2424424/jetty-web2.txt)

This allowed users to be redirected to our internal SSO authentication site. Is there a possibility to configure this via the framework.properties file in a future update?

**Comment by sjrd218** [comment]
@gtsteffaniak Thanks for reporting this issue. Is your custom authenticator a self contained library that you manually drop in as part of your Rundeck installation process?

If you could tell me what Jetty class or interface your `JettyFormAuthenticatorWithSafe` class extends or implements that would also be helpful.

Thanks.

**Comment by gtsteffaniak** [comment]
@sjrd218 Correct, there is a jar file which handles the handoff for authentication with the rundeck servers that we use.

I believe this is the class:
public class JettyFormAuthenticatorWithSafe extends FormAuthenticator.
![image](https://user-images.githubusercontent.com/42989099/46230077-0a62ec80-c32d-11e8-9a79-c58e72904451.png)

**Comment by sjrd218** [comment]
@gtsteffaniak Rundeck 3.0.7 introduces a new way to customize Jetty without a web.xml. You can now programmatically configure the Jetty WebAppContext that Rundeck uses. I have attached a sample project to show how to configure a custom authenticator like you have. [custom-jetty-configurer.zip](https://github.com/rundeck/rundeck/files/2460764/custom-jetty-configurer.zip)

Be aware that when we upgraded from Rundeck 2.x to 3.x the security system changed from container based security, to spring security. You might have to review your custom authentication code and update it to account for this change.

**Comment by gtsteffaniak** [comment]
Great, I will take a look and test it. Thank you for the quick turnaround!

**Comment by gschueler** [comment]
I will close the issue. If you still have this problem, please re-open this issue.
