### ISSUE TITLE
Authentication fails when using groovy configuration file format

### ISSUE THREAD

**Issue by akusei** [rundeck/rundeck#4083]
**Describe the bug**
On a fresh install of rundeck, when you switch to using the groovy config file format (/etc/rundeck/rundeck-config.groovy) and configure **any** `grails` block (even a minimal empty one) like below:

```
grails {
  mail {
  }
}
```

Rundeck will start normally but will always redirect to `/login/auth` which results in a HTTP 403 and an 'Authentication is required' error message and no means to actually login. If you switch back to the normal java .properties file or remove the `grails` block from the .groovy file, rundeck will function properly again; redirecting you to /user/login and providing a login prompt. Attempting to access /user/login directly when you get the 'Authentication is required' error results in another redirect to /login/auth and a 403.

This is a problem because some email configurations require a `grails` block to work properly. This issue happens with an empty grails block or a fully configured grails block.

**My Rundeck detail**

* Rundeck version: 3.0.6-20180917
* install type: deb
* OS Name/version: Ubuntu 18.04
* DB Type/version: default

**To Reproduce**
1. switch to using .groovy config by editing the /etc/default/rundeckd file and add the following line:
`export RDECK_CONFIG_FILE=/etc/rundeck/rundeck-config.groovy`

2. Create a groovy config in /etc/rundeck/rundeck-config.groovy. This is my minimal .groovy config:
```
loglevel.default = "INFO"
rdeck.base = "/var/lib/rundeck"
rss.enabled = false
grails.serverURL = "http://localhost:4440"
dataSource.dbCreate = "update"
dataSource.url = "jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true"
rundeck.log4j.config.file = "/etc/rundeck/log4j.properties"
grails {
  mail {
  }
}
```

3. Change the owner of /etc/rundeck/rundeck-config.groovy to the rundeck user

4. Start/Restart rundeck

5. Access rundeck with a browser: http://localhost:4440

**Expected behavior**
Redirection to a login screen

**Screenshots**
Expected behavior (working with no grail block or with java properties config):
![capture2](https://user-images.githubusercontent.com/12972900/46500948-ec880280-c7d8-11e8-8ed1-219fe6def760.PNG)

Actual behavior (with grails block in groovy config format)
![capture1](https://user-images.githubusercontent.com/12972900/46501010-19d4b080-c7d9-11e8-806e-5a7cfa07e28c.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome, IE Edge, Firefox
 - Version Chrome 68, IE Edge 41, Firefox 62

**Comment by adriankirchner** [comment]
Is there a workaround for this? This bug is still present in 3.0.7 and when using https://github.com/voxpupuli/puppet-rundeck there is no way to use properties over groovy

**Comment by sjrd218** [comment]
@akusei @adriankirchner 
I can reproduce the behavior you've reported. Here's something you can try as a workaround.

Remove the config file environment variable:
```export RDECK_CONFIG_FILE=/etc/rundeck/rundeck-config.groovy```

With Rundeck 3 the configuration files are additive so you don't need to switch between one and the other. This allows you to put only what you need in rundeck-config.groovy and leave the rest in the rundeck-config.properties file.

Please let me know if this works for you.

**Comment by sjrd218** [comment]
@akusei @adriankirchner 
I can reproduce this behavior. As a workaround can you try unsetting the ```RDECK_CONFIG_FILE``` environment variable and restart.

In Rundeck 3 the configuration files are additive so you can put the groovy configuration in the rundeck-config.groovy and leave the rest in the rundeck-config.properties file. 

Please let me know if this workaround allows you to proceed.

**Comment by sjrd218** [comment]
@akusei @adriankirchner
I can reproduce this behavior. As a workaround can you try unsetting the ```RDECK_CONFIG_FILE``` environment variable and restart.

In Rundeck 3 the configuration files are additive so you can put the groovy configuration in the rundeck-config.groovy and leave the rest in the rundeck-config.properties file.

Please let me know if this workaround allows you to proceed.

**Comment by adriankirchner** [comment]
@sjrd218 thank your for your answer. Unfortunately the linked puppet module [does not support the properties file](https://github.com/voxpupuli/puppet-rundeck/issues/15). We'll wait for a fix in Rundeck.

**Comment by sjrd218** [comment]
@adriankirchner You can put all of your configuration in the groovy if you want. After further debugging I think the problem comes when the RDECK_CONFIG_FILE environment variable is set to a groovy file. If you'll take that out of your environment it might work without needing to wait for a fix.
