### ISSUE TITLE
Unable to Save Node Filter

### ISSUE THREAD

**Issue by JimmyTheRustler8** [rundeck/rundeck#4087]
**Describe the bug**
When editing the node filter for a job, the saved job will not update the node list. For example, if I were to filter for all production nodes Prod*, it would list them in the edit job screen, when save is pressed the filter on the "Run Job" page will revert back to the previous node filter i.e. Non-Prod.

However, when an edit is made to the script AND the node filter the node selection screen is updated with the correct list. This issue can be temperamental though as sometimes the nodes will update, but this has been observed in about 1 of every 6 edits of the job.

**My Rundeck detail**

* Rundeck version: 3.0.5-20180828
* install type: RPM (YUM)
* OS Name/version: Red Hat Enterprise Linux Server release 7.5 (Maipo)
* DB Type/version: MySQL

**To Reproduce**
1. Create a job that will execute on multiple nodes.
2. Edit the job but only make changes to the node filter.
3. Save the job.
The changes will not have taken place.

**Expected behavior**
When updating the node list only on the "Edit Job" screen I would expect to see the node filter changes reflected on the "Run Job" screen

**Desktop (please complete the following information):**
 - OS: Windows 7 Enterprise
 - Browser: Chrome
 - Version: 69.0.3497.100 (Official Build) (64-bit)

**Additional context**
This issue has not been seen prior to upgrading to version 3.0.5-20180828.

**Comment by sjrd218** [comment]
This issue was fixed in Rundeck 3.0.6. For reference see #4014.
