### ISSUE TITLE
Misconfigured key storage causes 500 error

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#4104]
**Describe the bug**

If key storage is misconfigured, e.g. the `config.baseDir` is missing due to typo:

~~~
rundeck.storage.provider.1.type=file
rundeck.storage.provider.1.path=/
# the following should use 1 not 2
rundeck.storage.provider.2.config.baseDir=/path/to/store
~~~

Then Rundeck starts up, but requests to key storage api/GUI will result in 500 error.

**My Rundeck detail**

* Rundeck version: 2/3

**To Reproduce**

Use config as above.

**Expected behavior**

Error at startup.

** Suggested solution** 

The StorageTreeFactory should validate the backend or converter plugin configuration using the pluginRegistry.

**Comment by carlosrfranco** [comment]
Still happening on v3.2.5
