### ISSUE TITLE
New ACL Doesn't Grant Permissions

### ISSUE THREAD

**Issue by hila3000** [rundeck/rundeck#4108]
**Describe the bug**
Hi,

I've created and saved a new acl policy.
when logged on with the user in the group that the acl refers to, i get this error-
You have no authorized access to projects.
Contact your administrator. (User roles: nabeel, build, user, deploy)

The user name is nabeel, not sure why it thinks there's also a role named nabeel, since this is what appears in the realm.properties file:
nabeel:password,user,deploy,build

This is the acl I created:

description: allow users in "deploy" and "build" groups to create and run jobs
context:
  project: '.*' # all projects
for:
  resource:
    - equals:
        kind: job
      allow: [read, run] # allow read of all activity (jobs run by all users)
  job: 
    - equals:
        name: create-vs-template
      allow: [read, run]
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: deploy

What's wrong in the configuration, that doesn't let nabeel access anything ? (I tried letting any user in deploy role run only specific job called create-vs-template)

**My Rundeck detail**
Not sure what is expected of me to write here...

* Rundeck version: Rundeck 3.0.6-20180917
* OS Name/version: debian 9

**To Reproduce**
1. create this acl-
description: allow users in "deploy" and "build" groups to create and run jobs
context:
  project: '.*' # all projects
for:
  resource:
    - equals:
        kind: job
      allow: [read, run] # allow read of all activity (jobs run by all users)
  job: 
    - equals:
        name: create-vs-template
      allow: [read, run]
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: deploy

2. create any user in "deploy" role.

3. login with this user and see if you have any access in the application, you should have no authorized access anywhere to projects.

**Expected behavior**
I expect to see the project and the job "create-vs-template", and to be able to run it.

**Desktop (please complete the following information):**
 - OS: rundeck server is on debian 9, I'm using windows 10 pro as the client
 - Browser: chrome
 - Version: Version 69.0.3497.100

Thanks for any help,
Hila

**Comment by hilafish** [comment]
Still relevant

**Comment by hila3000** [comment]
still relevant
