### ISSUE TITLE
Rundeck Plugin Options type prevents saving of node step

### ISSUE THREAD

**Issue by cjmcken** [rundeck/rundeck#4109]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.0.7-20181008 
* install type: rpm
* OS Name/version: centos 7 
* DB Type/version: mysql

I've created a rundeck plugin (in java) with a Property of type "Options", when I then go to save the step inside of the rundeck UI I get an error 500 Server Error with the following stack trace in it:

**Class**
      groovy.lang.MissingMethodException 
**Message**
      No signature of method: [Ljava.lang.String;.replaceAll() is applicable for argument types: (java.lang.String, java.lang.String) values: [\r?\n, ]

Line  |  Method
666  |  doCall                  in rundeck.controllers.WorkflowController$_cleanLineEndings_closure20

**How to Reproduce**
This can be reproduce by creating a rundeck plugin in java and having a property with the type "Property.Type.Options".Then you need to install the plugin and create a job with this as one of the steps. Upon trying to save if you open up the developer console you will notice that the request cannot be made to the backend correctly and throws a server error (code: 500)

**Comment by sjrd218** [comment]
@cjmcken Looks like a bug with the Options property type. Can you use FreeSelect instead?

**Comment by cjmcken** [comment]
For the minute I've been using a String field and using it as a comma separated value using validators

**Comment by skywalke34** [comment]
This is still an issue.  Using a single value will allow the workflow step to save.  However, using >1 values causes an exception error and will not allow you to save the workflow step.
![image](https://user-images.githubusercontent.com/11443283/60736731-427b0980-9f15-11e9-9bbe-b4a035c5dd66.png)
