### ISSUE TITLE
RUNDECK do not start anymore after Upgrade to 3.0.7

### ISSUE THREAD

**Issue by picoroma** [rundeck/rundeck#4110]
After the rundeck upgrade to 3.0.7, I cannot start my service anymore.
I have followed these command to upgrade my RUNDECK: 
https://rundeck.org/downloads.html?__hssc=206669708.8.1539255713358&__hstc=206669708.a106b688208565005214ee0685f6568e.1539103344053.1539103344053.1539255713358.2&__hsfp=3609769803&hsCtaTracking=6c34b5b9-9523-4ad1-814f-6071ab125c5a%7C456206e0-ddce-4ef1-b32b-be92b244ccd4

But after the upgrade was finished, I cannot start the service anymore!
The error on service.log is:
Error: Could not find or load main class .var.lib.rundeck

version : rundeck-3.0.7.20181008-1.201810082316.noarch

I Cannot understand what happened on my environment.

Find this similar issue (but old) : https://github.com/rundeck/rundeck/issues/3841

Regards
P.

**Comment by rhughes1** [comment]
@picoroma Take a look at a comment I posted here... 

https://github.com/rundeck/rundeck/issues/3995#issuecomment-420124939
