### ISSUE TITLE
Job scoped email templates do not work

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4112]
**Describe the bug**
Adding the following email scoping to **rundeck-config.properties** does not affect anything.
```
rundeck.mail.[project].[jobname].template.subject=[custom subject line]
rundeck.mail.[project].[jobname].template.file=[path to template file]
rundeck.mail.[project].[jobname].template.log.formatted=true
```

(sidenote - I am not sure how to format these parameters if the project name or job name has spaces)

**My Rundeck detail**
TESTED ON:
* Rundeck version: 3.0.6 and 3.0.7
* install type: yum
* OS Name/version: centos
* DB Type/version: mysql

**To Reproduce**
After successfully configuring email and testing that it works correctly with status triggers, adding project scoping does not affect anything. I have tested with status triggers and without status triggers.

It appears rundeck is completely ignoring the config parameters.

**Expected behavior**
I would expect the project scope to override the other trigger scopes - but theres not any documentation on how this works. In fact, I would expect there should be a trigger scope added, for example:

```
rundeck.mail.[project].[jobname].[status trigger].template.subject=[custom subject line]
rundeck.mail.[project].[jobname].[status trigger].template.file=[path to template file]
rundeck.mail.[project].[jobname].[status trigger].template.log.formatted=true

```

**Comment by tmarly** [comment]
The config is not so trivial:
- replace [project] by the technical name of your project  (you can find it in the URL, or in the folder /var/rundeck/projects). This is not the project label.
- replace [jobname] by ... the job name ! (edit the job, and you will get the job name as the first form field)

And if there are some spaces, escape them with a backslash.

So, for example: 
```
rundeck.mail.myproject.My\ Job\ Name.template.file=/etc/rundeck/mail/my-template.md
```

And I agree, it would be great to have also the ability to define a trigger.

++
