### ISSUE TITLE
Import Options not working as expected with v3.0.7

### ISSUE THREAD

**Issue by padraiglennon** [rundeck/rundeck#4115]
**Describe the bug**
In the latest version of Rundeck 3.0.7 has introduced some errors with the "import options" feature of referenced jobs. Up to this version a "base job" could have an option called "JOBDATE" for example which is a required option which would be populated from a "calling job" at execution time. 

The latest version however fails the job with the error shown in the screenshot below. I have also added two job definitions which reproduce this error. I believe this is a bug as it wasn't the case before this latest version and I had used the pattern extensively for complex job workflows

Note that the issue only appears if the "Required" flag is set on the Base Job option

**My Rundeck detail**

* Rundeck version: 3.0.7
* install type: rpm
* OS Name/version: RHEL 7.5
* DB Type/version: Postgres 9.6

**To Reproduce**
Import the two jobs as attached. Execute the "Calling Job" providing a value for the JOBDATE option

**Expected behavior**
The date provided in the "Calling Job" option at run time should be passed correctly to the Base Job echoing out the date provided

**Screenshots**
![image](https://user-images.githubusercontent.com/745557/46863321-05af3580-ce0f-11e8-8bd9-6c18da4ccce7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 69 

**Additional context**

[Jobs.zip](https://github.com/rundeck/rundeck/files/2472642/Jobs.zip)

**Comment by padraiglennon** [comment]
Any thoughts on this? Its causing us a lot of issues at the moment

**Comment by ltamaster** [comment]
Hi @padraiglennon,
This PR will fix the issue https://github.com/rundeck/rundeck/pull/4120 
Luis

**Comment by padraiglennon** [comment]
Excellent, Thank you Luis.

**Comment by padraiglennon** [comment]
This is working in recent versions so closing
