### ISSUE TITLE
A "disclaimer" box and config to get the Rundeck login UI

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#4119]
RUNDECK version rundeck-3.0.7-20181008.war
Web Browser: latest firefox and latest chrome.

**Is your feature request related to a problem? Please describe.**
Login message has very small section to be placed.

**Describe the solution you'd like**
This message might be in a particular place/section at login screen

**Additional context**

![captura de pantalla de 2018-10-12 14-28-04](https://user-images.githubusercontent.com/34582874/46884841-95afa800-ce2c-11e8-8a77-d041fc35fbf0.png)

**Comment by gschueler** [comment]
Fixed via https://github.com/rundeck/rundeck/pull/4125
