### ISSUE TITLE
KVD plugin to capture whole block

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#4128]
Rundeck KVD filter actually only is able to capture 1 line of data.
It would be from help it could capture the whole output, e.g. an object from an SQL run step, a full json output, etc.

**Comment by ltamaster** [comment]
https://github.com/rundeck-plugins

**Comment by ltamaster** [comment]
https://github.com/rundeck-plugins/multiline-regex-datacapture-filter
