### ISSUE TITLE
Feature request : hide unmodifyable job options, such as secrets

### ISSUE THREAD

**Issue by jgibart** [rundeck/rundeck#4135]
I am using options with a default value from the key storage  to pass secrets to my jobs, but these should not be overridable when executing running jobs.
Actually I 'd even would like them not to appear on the job launch screen.

Could you please add a hidden job options attribute for an option we dont wish users to modify ?

Or is there another way to pass secrets without using job options ?

**Comment by HectorNS** [comment]
This would be so helpfully, we are using now in our company Rundeck to give jobs to other teams, but people complain about these "useless" options, but they are necessary for us to store secret passwords.

Is there any chance to hide these options in the run job screen?

**Comment by Chupaka** [comment]
Yep, we need this to be hidden, please.

**Comment by gschueler** [comment]
added in https://github.com/rundeck/rundeck/pull/4472

**Comment by Chupaka** [comment]
Just wanted to mention a workaround for those who are still on version before 3.0.14:

You may create a new job with only necessary options, and make that job execute your main job with those options.
