### ISSUE TITLE
new nodes not recognized

### ISSUE THREAD

**Issue by MarcoSchaar** [rundeck/rundeck#4136]
**Describe the bug**
when adding new node into resource.xml, no updates in nodes per project

**My Rundeck detail**

* Rundeck version: 3.0.7-20181008
* install type:  rpm
* OS Name/version: redhat 7.5
**To Reproduce**
1. add new node to resource.xml
2. node not recognized

**Expected behavior**
node listed

**Comment by reinerrdeck** [comment]
could you see your resources.xml file?

**Comment by MarcoSchaar** [comment]
got it resolved meanwhile by correcting the ssh-keypath for attached nodes
