### ISSUE TITLE
Failed: SSHProtocolFailure: channel is not opened .... JSCH default timeout 

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#4137]
**Describe the bug**
When connecting to a node using JSCH, connection timeouts with the following error: `Failed: SSHProtocolFailure: channel is not opened.` This does not correlate to parameters set up in `sshd_config` and/or `framework.properties` .

**My Rundeck detail**

* Rundeck version: tested  2.11.7 ( related code is no different in 3.0.x )
* install type: 
* OS Name/version: 

**To Reproduce**

1. Direct SHH to remote node  (takes around 15-20 sec to complete successfully due to network/protocols/etc ). Password auth used.

2. In Rundeck , run a simple command against the same node ( configured with JSCH as node executor) . Connection takes takes the same time and finally timeouts with error: `Failed: SSHProtocolFailure: channel is not opened.` ( password auth  )

3. Change Node executor to, e.g., OpenSSH, run same command against same node. Connection takes the same time but succeeds.

**Expected behavior**
Timeout should honor values configured in `sshd_config` and/or `framework.properties` .

**Additional context**
The defaut timeout for SSH Channel opening seems to be low and cannot be changed

ref:
[https://github.com/rundeck/rundeck/blob/48b0c71381225096ac67943c1d81a94dfe3436d1/core/src/main/java/com/dtolabs/rundeck/core/tasks/net/ExtSSHExec.java#L459](url)

**Comment by oOHenry** [comment]
@gschueler any updates? I'm facing this bug too at version: 3.0.22.

**Comment by suslikas** [comment]
Same bug "SSHProtocolFailure: timeout in waiting for rekeying process" on **3.1.2.20190927-1**

**Comment by fdevans** [comment]
This is likely still an issue in he current version, but can someone please confirm?

**Comment by uday3110** [comment]
Yes I am running into this issue. @gschueler can you please advise here.

**Comment by fdevans** [comment]
We will schedule time in an upcoming sprint to look into it further.
