### ISSUE TITLE
RD3 GUI: When displaying overview page with a big amount of projects ( over 15 ) the last ones may not load "configure" and  "create job" buttons correctly

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#4149]
**Describe the bug**
The "Projects" overview page may not display correctly the interface buttons ,"configure" and  "create job", for the last projects in the list.

**My Rundeck detail**

* Rundeck version: 3.0.7
* install type: WAR

**To Reproduce**

1. Log into a Rundeck instance with over 15 projects

2. Click on "Home" to list all the Projects

3. After a while ( "spinning wheels" icon) projects load into visible window

4. Scroll down to display more projects, "spinning wheels" persist not loading "configure" and  "create job" buttons correctly

**Expected behavior**
After scrolling to see the remaining projects, the remaining projects should load the buttons initially outside of the viewport.

**Screenshots**
Chrome
![image](https://user-images.githubusercontent.com/31705339/47374700-f6f53800-d6c4-11e8-803d-732abc997853.png)

Firefox
![image](https://user-images.githubusercontent.com/31705339/47374794-260ba980-d6c5-11e8-91e6-dd430e3ea5aa.png)

Internet Explorer
![image](https://user-images.githubusercontent.com/31705339/47374978-9adee380-d6c5-11e8-8cad-75826160f8bc.png)

Microsoft Edge
![image](https://user-images.githubusercontent.com/31705339/47375058-cf529f80-d6c5-11e8-93fc-d8e4e67ebce2.png)

**Desktop (please complete the following information):**
 - OS: Linux , Windows
 - Browser: Firefox, Chrome, IE, Edge
 
**Additional context**
As a "workaround" zooming out and back in usually displays the elements correctly.

**Comment by mazzella-c** [comment]
Same issue here.

**Comment by benruset** [comment]
Happening on 3.0.16, too. I have 30 projects. Only the first 12 projects fully load - everything else just sits and spins until I zoom in and out. Using MacOS Mojave with Safari and Firefox.

I don't know if it matters but I am terminating SSL on an AWS internal ELB for my Rundeck instance.

**Comment by beakerman29** [comment]
I can confirm it is still an issue on 3.0.20 as well. I have 30 projects as well

**Comment by sebastianbello** [comment]
Persists in 3.1 RC1 

https://zoom.us/j/162124708
![image](https://user-images.githubusercontent.com/31705339/59710444-fd499e80-91d6-11e9-828a-0f4785fd5ab9.png)
