### ISSUE TITLE
define the behavior for a schedule job in which the previous execution has not yet finished

### ISSUE THREAD

**Issue by dportabella** [rundeck/rundeck#415]
is there a possibility to chose whether a scheduled job should run or not if the previous run has not yet finished?

that is, i have a scheduled job that runs every day at 10am.
what happens if the today at 10am the job of yesterday has not yet finished?
will it launch another job in parallel?
will it wait until it finished?
will it cancel the executing today?

is there the possibility to configure which of these options do we want for a given job?

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
