### ISSUE TITLE
Load project nodes on Rundeck startup / initialisation with 

### ISSUE THREAD

**Issue by tdhulster** [rundeck/rundeck#4154]
**Trello-dev-board** 
couldn't find anything similar

**Context**
Rundeck + rundeck-ansible-plugin : https://github.com/Batix/rundeck-ansible-plugin

**Feature / problem**
Rundeck doesn't start fetching Nodes from Projects/Jobs when the Rundeck instance starts/initialises when using the rundeck-ansible-plugin.

It only starts fetching nodes as soon you click on a particular Job inside one of the projects when using the rundeck-ansible-plugin

According to the rundeck-ansible-plugin team this has nothing to do with the plugin itself : https://github.com/Batix/rundeck-ansible-plugin/issues/210

**Solution**
A solution where Rundeck loads its nodes as soon as the container has started when using the rundeck-ansible plugin.

**Comment by gschueler** [comment]
Can you post the rundeck version, install type, and database type/version you are using, @tdhulster ?

The behavior changed between rundeck 2 and 3, for new installs, see https://github.com/rundeck/rundeck/issues/3675

if you are using 2, you can  set `rundeck.nodeService.nodeCache.firstLoadAsynch=false`
