### ISSUE TITLE
Job page running tab is not shown directly

### ISSUE THREAD

**Issue by svenvNL** [rundeck/rundeck#4157]
**Describe the bug**
When opening a job, under "Activity for this Job" "running" is the first tab, the details are not shown. When you click "recent" and "running" again, the details are shown

**My Rundeck detail**

* Rundeck version: 3.0.6-20180917
* install type: war
* OS Name/version: CentOS 7.5
* DB Type/version: postgres

**To Reproduce**
1. Go to a job
2. scroll down to "Activity for this Job"
3. Details for "running", the initial tab, are not shown.
4. click "recent", and then "running", details are shown

**Expected behavior**
Details are directly shown

**Screenshots**
Inital load
<img width="804" alt="screen shot 2018-10-26 at 16 18 28" src="https://user-images.githubusercontent.com/13982006/47572326-f8c83100-d93a-11e8-888e-9a3945171721.png">

After clicking "recent", and then "running"
<img width="802" alt="screen shot 2018-10-26 at 16 18 49" src="https://user-images.githubusercontent.com/13982006/47572354-0b426a80-d93b-11e8-8c59-b16397c0046c.png">

**Desktop (please complete the following information):**
 - OS: macOS High Sierra
 - Browser Chrome
 - Version 69.0.3497.100

**Additional context**

**Comment by reinerrdeck** [comment]
If you set "follow execution" box you can see the job execution more detailed on screen, but if you don't set "follow execution" you can see a progress bar in this tab to follow up.

![screenshot_2](https://user-images.githubusercontent.com/43051294/47653297-f9450f80-db66-11e8-9ead-7ba3c31f68b1.png)
