### ISSUE TITLE
Question regarding base URL for rundeck

### ISSUE THREAD

**Issue by tejinderss** [rundeck/rundeck#4166]
Sorry I didn't find a better place to ask this but is it possible to host rundeck on a base URL like /rundeck so that all the requests come under that path like /rundeck/menu/home /rundeck/assets etc? Thanks

**Comment by sjrd218** [comment]
The documentation for this is located here: https://rundeck.org/docs/administration/configuration/system-properties-configuration.html

What you'll want to do is edit your `rundeck-config.properties` file and set the following properties:
```
server.contextPath=/rundeck
grails.serverURL=http://yourhostname:4440/rundeck
```
You'll also want to edit your `framework.properties` file to add the /rundeck suffix to the `framework.server.url` property:
```
framework.server.url=http://yourhostname:4440/rundeck
```
