### ISSUE TITLE
Feature request: Improve the indentation for the "group job list" menu.

### ISSUE THREAD

**Issue by eduardolmedeiros** [rundeck/rundeck#4168]
Hi Rundeck Team,

Currently, the group job list is not following the correct "indentation". It could be fixed just increasing the ident to the right side.

The current configuration is not flexible when you have multiples sub-groups in place.

Follow bellow a link for the image to illustrate this feature request. (img right side)
[rundeck-group-list-job](https://i.imgur.com/KjSJsUD.png)

**Comment by gaetanquentin** [comment]
i agree: the lack of identiation make things very confusing:

which one is a subgroup of which one?:
![image](https://user-images.githubusercontent.com/5774881/48058927-0d68bc80-e1b8-11e8-96b6-72cfa2ade087.png)

**Comment by brtknr** [comment]
+1 this is the most confusing things about the interface right now when there are lots of jobs categorised into groups and subgroups

**Comment by hs-hub-world** [comment]
+1

**Comment by brtknr** [comment]
The issue appears to be have been addressed on `Rundeck 3.0.9-20181127`

**Comment by gaetanquentin** [comment]
it has been fixed
