### ISSUE TITLE
Dashboard is only displaying the label.

### ISSUE THREAD

**Issue by mlamutt** [rundeck/rundeck#4174]
**Describe the bug**
After installing  to v3 the dashboard screen on all my projects only display the label. 

**My Rundeck detail**

* Rundeck version: 3.0.8-20181029
* install type: war
* OS Name/version: Win2012 r2
* DB Type/version: internal

**To Reproduce**
1. Go to 'projects'
2. Click on 'dashboard"
3. See error - Page displays the label in the header (same line as the system gear, and the user Icon).  The rest of the panel is blank.  

**Expected behavior**
My understanding is that the dashboard should show the project description, Readme and executions summary. I Have tried adding MOTD and readme statements, and neither show up.

**Screenshots**
![11-1-2018 1-01-18 pm](https://user-images.githubusercontent.com/30131225/47873237-970b3980-de08-11e8-967f-651211d0d048.jpg

**Desktop (please complete the following information):**

**Additional context**
Add any other context about the problem here.  I saw the same issue with v3.0.7, so I have upgraded to 3.0.8.  I am also seeing the same behavior with imported projects and newly created projects.

thanks

**Comment by jaromirrivera** [comment]
I have the same exact issue.

**Comment by jaromirrivera** [comment]
I was able to resolve my issue by adding https:// in the grailsUrl option in rundeck-config.properties.

Previously I had just http://. I have an nginx proxy that is handling SSL and therefore thought that the https was not required in the rundeck-config.properties file but it is.
