### ISSUE TITLE
job state conditional is not working since rundeck 2.9.x

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#4178]
**Describe the bug**
Job state conditional is not working as expected.
Last working version was rundeck-launcher-2.8.4.jar

**My Rundeck detail**

* Rundeck version: since rundeck-launcher-2.9.1.jar
* install type: launcher
* OS Name/version: ubuntu 18.04
* DB Type/version: h2

**To Reproduce**
See screenshots.

**Expected behavior**
Not keep running next steps after the job conditional fails to check condition.

**Screenshots**
JOB STEP CONDITION CONFIG:
![captura de pantalla de 2018-11-05 13-07-07](https://user-images.githubusercontent.com/34582874/48010246-fcf30c00-e0fb-11e8-93af-7e35a57d676d.png)

ls script command should not be run:
![captura de pantalla de 2018-11-05 13-01-30](https://user-images.githubusercontent.com/34582874/48010227-f2d10d80-e0fb-11e8-8337-8a8d26e9cc76.png)

**Comment by gschueler** [comment]
The plugin needs to set "Halt=true" in order to halt the workflow if the test does not match.

**Comment by jplassnibatt** [comment]
@gschueler we've tried all combinations for halt and fail check boxes in job state conditional, indeed it halt when it is selected, but the status is always "Succeeded", below is the results using the old an new 3.0.9 fix from @jtobard 


  | halt | fail | status | next step
-- | -- | -- | -- | --
rd2 2.9.1 | y | y | succeeded | n
  | y | n | succeeded | n
  | n | y | succeeded | y
  | n | n | succeeded | y
rd3 fix 3.0.9 | y | y | failed | n
  | y | n | succeeded | n
  | n | y | failed | n
  | n | n | succeeded | y

**Comment by gschueler** [comment]
check this update https://github.com/rundeck/rundeck/pull/4235
