### ISSUE TITLE
Killing parent job doesn't kill running child jobs ( in 3.0.x , not able to kill parent job )

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#4179]
**Describe the bug**
When running a Job as  "Job Reference" within a  `Parent Job`, killing the `Parent Job` does not kill the `child job`(s).
Behavior, in 3.0.x is slightly "worse": you cannot KILL `parent` job using the "kill job" button. However, it shows as "killed" after workflow is "completed"
 
**My Rundeck detail**

* Rundeck version: 2.11.7 and 3.0.8
* install type: any
* OS Name/version: Linux, Windows
* DB Type/version: Any

**To Reproduce**

1. Create a **`Child Job`** with a single step: `sleep 30` , and "On Success" notification (any) . Have this job dispatched to a remote node.

2. Create a **`Parent Job`** that calls the **`Child Job`** as Job Reference step. 

3. Run **`Parent Job`**

4. Kill **`Parent Job`** with the `Kill Job`button

5. In Rundeck 3.0.x the Job does not get "killed" when pressing "Kill Job" button. Neither is the **`Child Job`** . However, Final Status is "Killed" 

6. In Rundeck 2.11.7 the **' Parent Job`** is killed , however the **`Child Job`** keeps running. You may note this when the "On Success" notification is received after `Sleep 30`. **`Child Job`** status appears as "Mixed".

**Expected behavior**
When pressing the "Kill Job" button for the **`Parent Job`**, the job should be killed, and **`Child Job`** as well.

**Screenshots**

**RD 3.0.8** ( Parent job shown as Killed after it was "completed" )
![image](https://user-images.githubusercontent.com/31705339/48026072-d8ab2580-e123-11e8-9005-787a29210c3a.png)

On Success Notification for Child Job received AFTER execution finished ( not "killed" )
![image](https://user-images.githubusercontent.com/31705339/48026999-60922f00-e126-11e8-9fbf-7c7d3c9a20cb.png)

**RD 2.11.7**  ( Parent job shown as Killed after it was "completed" )
![image](https://user-images.githubusercontent.com/31705339/48026108-f2e50380-e123-11e8-8e9f-faca4cb1db92.png)

On Success Notification received AFTER complete execution finished ( despite showing as "killed")
![image](https://user-images.githubusercontent.com/31705339/48026230-3b042600-e124-11e8-876a-f7e73ca32d70.png)

**Additional context**

The same behavior occurrs when dispatching to Linux or Windows nodes and using different Node Executors, setting Target Nodes in **`Child Job`** or dispatching the workflow in **`Parent Job`**

**Comment by Daryes** [comment]
Though this was fixed in 2.x, but I felt on this today, having Rundeck v3.0.9 not killing its child process when running a shell command (same behavior for local or remote)
