### ISSUE TITLE
Option to Enable/Disable notifications for Referenced Jobs

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#4182]
**Is your feature request related to a problem? Please describe.**
Since v2.11 notifications are triggered for Referenced Jobs. 
In previous versions, Notifications were NOT triggered in Referenced jobs. 

Currently, both requirements coexist for different users:  
- Have Notifications triggered by referenced jobs, 
and 
- Only notifications at the parent job to work.

**Describe the solution you'd like**
An option/ flag to have referenced job's notifications enabled/ disabled may be required in order to be able to implement both use cases.

**Describe alternatives you've considered**
- Per- project option to enable/ disable notifications in referenced jobs
- Flag in the "Job Reference" Step to enable/ disable notifications in the Referenced Job 

**Additional context**
"Excess of notifications" may not be the desired behavior in some use cases. However, notifications may be used as "milestones" for the workflow.

**Comment by Mapel88** [comment]
+1
