### ISSUE TITLE
Always reroute to http://somewhere/rundeck/user/login, when using apache with reverse proxy for https

### ISSUE THREAD

**Issue by chtay** [rundeck/rundeck#4201]
Always reroute to http://somewhere/rundeck/user/login, when using apache with reverse proxy for https

Rundeck using:
rundeck-3.0.8-20181029.war
OS:
openSUSE Leap 42.3

On rundeck-3.0.1-20180803.war, do not have such problem. When changing to the above version, each time going to:
https://somewhere/rundeck, it is rerouted to http://somewhere/rundeck/user/login

Tried using -Dserver.useForwardHeaders=true and still the same. Add "server.useForwardHeaders=true in rundeck-config.properties, and still the same.

Right now, I am using Apache's "Rewrite" function to force all http://somewhere/rundeck/* to https://somewhere/rundeck/* instead and it works.
So, if anyone encountered the same problem, might want to try this instead.
Here is my apache's setting:

EDIT: somehow it chopped off the rest of the post, so I cut and paste it as new message below:

**Comment by chtay** [comment]
<IfModule mod_rewrite.c>
RewriteEngine On
RewriteCond %{HTTPS} !=on
RewriteRule ^/?rundeck/(.*) https://%{SERVER_NAME}/rundeck/$1 [R,L]
</IfModule>

<Location /rundeck>
 <IfModule mod_proxy.c>
     ProxyPass              http://localhost:4440/rundeck
     ProxyPassReverse http://localhost:4440/rundeck
  </IfModule>
</Location>

**Comment by cflee** [comment]
I don't run with the context root/path prefix `/rundeck`, but to get something like this (TLS termination on a reverse proxy, then HTTP to Rundeck itself) working, in `rundeck-config.properties` I had to set both `server.useForwardHeaders=true` and also `grails.serverURL=https://somewhere/rundeck`.

**Comment by chtay** [comment]
Hi ProTip
I checked both my vhosts.d files and all apache config, and I did not see any "X-Forwarded" thing.
So, most likely it is not set. I not sure whether will it be any default or not.
My Apache version on openSUSE Leap 42.3 is 2.4.23-19.1
