### ISSUE TITLE
Automated SCM configuration import from filesystem into database

### ISSUE THREAD

**Issue by shoelzle** [rundeck/rundeck#4215]
**Is your feature request related to a problem? Please describe.**
I'm migrating my project definition from the filesystem to rundeck's database by changing rundeck.projectsStorageType in the rundeck-config.properties from filesystem to db.
This works just fine, however the SCM configuration is not automatically imported into the database.

**Describe the solution you'd like**
Please include the SCM configuration into the automated import process.

**Comment by shoelzle** [comment]
This is still relevant.

**Comment by mveroone** [comment]
I faced this issue when upgrading from 2.11 to 3.1.2.  
Didn't noticed the projectStorage migrated from filesystem to db and didn't understand why I lost scm...
