### ISSUE TITLE
Grails MaxUploadSize should be configurable for Docker 

### ISSUE THREAD

**Issue by kirrmann** [rundeck/rundeck#4216]
The Docker image generates the rundeck-config.properties with each start. Because of this we cannot override the config by e.g. mounting an updated file, which is necessary to add options to successfully upload Rundeck archives larger than 25MB.

e.g.
```
grails.controllers.upload.maxFileSize=52428800
grails.controllers.upload.maxRequestSize=52428800
```

To set this options there should be corresponding ENV variables exposed or an ENV variable to include another config file (which would be the more general approach).

**Comment by ProTip** [comment]
Thanks @kirrmann ! I'm going to look to get this added, as well as expedite "escape hatches". Thus far the configuration plumbing is not really a public API, but I'd like to get it to where missing configuration can be more easily composed with the generated config, and perhaps even allowing generated config to be replaced more easily.
