### ISSUE TITLE
How to call job1 out put to job2 input in rundeck

### ISSUE THREAD

**Issue by korerajesh** [rundeck/rundeck#4217]
Hi Team 

I want to call job1 output to job2 input in Rundeck tool 
please help me out how to creates jobs 

Thanks

**Comment by michaeljohn32** [comment]
Here is an example of what you need to do.  Copy the output below and call it [somename].yaml:

**Comment by korerajesh** [comment]
Where we can upload this script exactly .

Thanks

**Comment by michaeljohn32** [comment]
If you haven't yet, create a project (like this doc: https://rundeck.org/docs/administration/projects/create-new-project.html)

Once you are on the main project screen, click on `jobs` and then in the upper right hand corner, click on `job options`.  Then, click on `upload definition`.  Choose `YAML format` and leave the rest of the options at their defaults.  Browse to the file you created from above and then click `Upload`
