### ISSUE TITLE
Display the execution options used for the job by default 

### ISSUE THREAD

**Issue by emiliohh** [rundeck/rundeck#4218]
**Is your feature request related to a problem? Please describe.**
It would be convenient to display the execution options used for the job by default instead of having to click on the "i" button.

**Describe the solution you'd like**
Always show options values used without having to press the "i" button

**Comment by emiliohh** [comment]
![image](https://user-images.githubusercontent.com/29556854/48627536-925f8d00-e993-11e8-97f8-c5ae0e173589.png)

**Comment by sebastianbello** [comment]
The option to select the default behavior for the "i" (info)  ( show/hide details )  could be useful, in order for the GUI to behave as in previous releases ( 2.x)

**Comment by jplassnibatt** [comment]
Fixed, at least in 3.1.2

![Captura de pantalla de 2019-11-13 18-34-38](https://user-images.githubusercontent.com/34582874/68806286-53b2f000-0644-11ea-8bd8-7ddacca414cd.png)
