### ISSUE TITLE
mask passwords at project level

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#4223]
Mask password option is only available at job basis.
There is a request to enable the option also at a project level basis.

**Comment by akhilesh0** [comment]
+1

**Comment by gschueler** [comment]
This should also be a framework level global that can be set as the default behavior for all projects

**Comment by gschueler** [comment]
fyi: there is already a place to add the log filters when executing jobs, basically you would just need to check the config and add it here: https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/services/rundeck/services/ExecutionService.groovy#L1009
