### ISSUE TITLE
No log output when running "commands"

### ISSUE THREAD

**Issue by ZoeLeah** [rundeck/rundeck#4225]
**Describe the bug**
No log output is shown, when running adhoc commands.

**My Rundeck detail**

* Rundeck version: 2.0.8
* install type: war
* OS Name/version: RHEL 7.5
* DB Type/version: oracle

**To Reproduce**
1. Go to 'Projects -> Commands'
2. Select a node
3. Run command e.g. 'ls -lah'
4. See error "Execution has no log output"

**Expected behavior**
Show the log ouput.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 52.9.0

**Comment by TenchiMayo** [comment]
Same here.

**Comment by ZoeLeah** [comment]
If I change the LOGLEVEL in rundeck-config.properties from WARN to DEBUG I get an output.

**Comment by Hronom** [comment]
I still see it in 3.3.5

**Comment by kdebisschop** [comment]
You only need to change to INFO, not DEBUG.

When I did a clean install of 3.3.10 the value created in rundeck-config.properties was INFO -- I womder if the default changed at some point and older installs might have preserved a less than functional default?
