### ISSUE TITLE
How to add notes ni rundeck 3.0.8 version 

### ISSUE THREAD

**Issue by korerajesh** [rundeck/rundeck#4237]
Hi Team 

How to add nodes in rundeck 8.0.3 version.
Please provide me step by step process 

Thanks in advance

**Comment by reinerrdeck** [comment]
Hi korerajesh,

After creating the project you can:

1) Go to the left panel and click on "Project Settings"
2) Click on "Edit Nodes"
3) Click on "Configure Nodes" button (Up, right)
4) Click on "Add Sources" button.
5) Select "+File" option.
6) In format select "resourcexml" option, on "File path" field set the path of the project (usually inside of your project), include "resources.xml" at the end. Ensure to select "Generate", "Include Server Node " and "Writeable" checkboxes and Click on "Save" button.

In this file you can add nodes following this:

https://rundeck.org/docs/man5/resource-xml.html

Hope it helps!

**Comment by korerajesh** [comment]
Thanks for quick update 

after clicking "+File" option Its showing local servers option, I want to run remote servers 

Please guide me to add remotes servers.

One more thing do I need to create any xml file in rundeck server end ?



Thanks in advance

**Comment by reinerrdeck** [comment]
Hi korerajesh,

You can add remote servers adding entries on resources.xml file, here a little example:

```
<project>
<node name="localhost" description="Rundeck server node" tags="" hostname="localhost" osArch="amd64" osFamily="unix" osName="Linux" osVersion="2.6.21.7-2.fc8xen" username="rundeck"/>
<node name="rundeck node2" description="Rundeck node2" tags="node2" hostname="10.1.0.1" osArch="amd64" osFamily="unix" osName="Linux" osVersion="3.11.10-03111015-generic" username="yourusername" ssh-keypath="/var/lib/rundeck/node2.key"/>
</project>
```

You can add as many entries as remote servers you have.

The XML file I should be inside the project that you have created in rundeck.

BR!

**Comment by korerajesh** [comment]
got it 

Thanks for quick response
