### ISSUE TITLE
enhancement - tie-in to ARA

### ISSUE THREAD

**Issue by dyioulos** [rundeck/rundeck#4258]
We use Ansible Run Analysis (ARA) tool to list, and get details about, playbook runs.  It's just another useful tool in our Ansible arsenal (as is Rundeck!).  While it records information when playbooks are run from the CLI, it doesn't pick up playbooks run from Rundeck.  Might the Rundeck devs consider creating a hook between Rundeck and ARA?

**Comment by dmsimard** [comment]
Hi @dyioulos !

Enabling ARA requires two things:
- Installing ARA (``pip install ara``)
- Telling Ansible to use ARA (``export ANSIBLE_CALLBACK_PLUGINS=$(python -m ara.setup.callback_plugins)`` or ``callback_plugins=<path>`` in ``ansible.cfg``)

That is enough to get playbook data recorded to a local database in ``~/.ara/ansible.sqlite``.
The web interface is passive, it only reads from the database -- it requires write privileges for legacy reasons.
The web interface can be hosted anywhere, so long as it has access to the database.

I've never used Rundeck before but I looked around a bit.

They install the Ansible APK here:
https://github.com/Batix/rundeck-ansible-plugin/blob/7efe2deb7ee629676019c1beda9806763315431c/Dockerfile#L13-L18

And they set an environment variable here:
https://github.com/Batix/rundeck-ansible-plugin/blob/7efe2deb7ee629676019c1beda9806763315431c/Dockerfile#L4

I suggest opening an issue in https://github.com/Batix/rundeck-ansible-plugin, maybe they can help !

**Comment by dyioulos** [comment]
+1

--------------------------------------------
On Sun, 1/20/19, mergeable[bot] <notifications@github.com> wrote:

 Subject: Re: [rundeck/rundeck] enhancement - tie-in to ARA (#4258)
 To: "rundeck/rundeck" <rundeck@noreply.github.com>
 Cc: "dyioulos" <dyioulos@yahoo.com>, "Mention" <mention@noreply.github.com>
 Date: Sunday, January 20, 2019, 4:42 AM
 
 There haven't been much
 activity here. This is stale. Is it still relevant? This is
 a friendly reminder to please resolve it. :-)
 
 —
 You are receiving this because you were mentioned.
 Reply to this email directly, view
 it on GitHub, or mute
 the thread.
