### ISSUE TITLE
Broken Link: "Option Model Provider" link to documentation when adding job option

### ISSUE THREAD

**Issue by skywalke34** [rundeck/rundeck#4259]
**Describe the bug**
Link to documentation returns 404 error.
Location of Link is Jobs > Create New Job > Options: Allowed Values  ?Rundeck User Guide - Option model provider.
![image](https://user-images.githubusercontent.com/11443283/49245544-de68f380-f3cf-11e8-8e8f-6acc7c5652ed.png)

**My Rundeck detail**

* Rundeck version: 3.0.8-Snapshot
* install type: Docker

**To Reproduce**
1. Go to 'Jobs'
2. Click on 'Create New Job'
3. Scroll down to 'Options: Allowed Values'
4. Click on link to documentation >> https://rundeck.org/docs/manual/jobs.html?utm_source=rundeckprocluster&utm_medium=3.0.8-SNAPSHOT%20Linux%20java%201.8.0_181&utm_campaign=helplink&utm_content=editOpts%2Fedit#option-model-provider

**Expected behavior**
Link should point to https://rundeck.org/docs/manual/defining-job-options.html#option-model-provider

**Comment by lukasged** [comment]
It's still broken for me in the case of Rundeck 3.1.2

**Comment by overag3** [comment]
Same issue in version 3.2.2
