### ISSUE TITLE
Broken Help Docs Link: Create New Job > Send Notification (All types go 404)

### ISSUE THREAD

**Issue by skywalke34** [rundeck/rundeck#4263]
**The Bug**
The Help Doc links for **Create Job > Send Notifications > Send Email**  when sending emails return 404 errors for the following events:
   1. On Success
   2. On Failure
   3. On Start
   4. Average Duration Exceeded
   5. On Retryable Failure

**Rundeck version**: RundeckPro Cluster 3.0.8-SNAPSHOT
**install type**: Docker Container

**To Reproduce**
1. Go to 'Jobs > Create New Job'
2. Scroll down to Send Notification and click Yes
3. Select 'Send Email'
4. Click on small right arrow circle for 'Help Docs'
**Result** 404 - Not Found >> https://rundeck.org/docs/administration/configuration-file-reference.html#custom-email-templates

**Expected behavior**
Link should open https://rundeck.org/docs/administration/configuration/email-settings.html#custom-email-templates

**Screenshots**
**Note - Not all errors are shown below, but you get the drift...**
![image](https://user-images.githubusercontent.com/11443283/49254748-4ecf3f00-f3e7-11e8-8dbc-310229488f2a.png)
![image](https://user-images.githubusercontent.com/11443283/49254793-70c8c180-f3e7-11e8-956e-fde8e853d79d.png)

**Comment by le-co** [comment]
Hello @skywalke34 

I reproduced your test in version 3.0.10-SNAPSHOT and it worked correctly.

This problem has been fixed.
