### ISSUE TITLE
(UI issue) Can't close Schedule Job window -ver 3.0

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#4265]
**Describe the bug**
When clicking Run Job Later -> then clicking date/time to pick a date time the lable 'The time must be in the future' prevents the user from closing the 'Set Start Time' window. 

**My Rundeck detail**
* Rundeck version: 3.0.8-20181029
* install type: rpm
* OS Name/version: Centos 7
* DB Type/version: Default (none)

**To Reproduce**
1. Go to Any JOB
2. Click on the Run Job Later button (located at the lower right corner)
3. Click on the DateTime picker twice to close the date/time window.
4. you'll notice you can't close the "Set start Time" window. you are stuck....

**Expected behavior**
Be able to close the "Set Start Time" by clicking away from it -? or put a close button above the title -?

**Screenshots**
![rundeck-ui-issue-2018-11-29_17-07-50](https://user-images.githubusercontent.com/20629911/49262018-7202ea00-f3f9-11e8-955f-53dc61f3df0c.png)

**Desktop (please complete the following information):**
 - OS: Windows 7
 - Browser Chrome
 - Version Latest (as of today)

**Comment by sebastianbello** [comment]
+1  This issue is still happening on in 3.0.22
