### ISSUE TITLE
Hot reload of realm.properties still doesn't work in 3.0.9

### ISSUE THREAD

**Issue by omniton** [rundeck/rundeck#4268]
**Describe the bug**
The fix from #3987 doesn't work unfortunately 

**My Rundeck detail**
* Rundeck version: [3.0.9]
* install type: [rpm]
* OS Name/version: [rhel 7.6]
* DB Type/version: [mysql]

**jaas configuration**
org.eclipse.jetty.jaas.spi.PropertyFileLoginModule sufficient
    debug="true"
    refreshInterval="60"
    hotReload="true"
    file="/etc/rundeck/realm.properties";

org.rundeck.jaas.jetty.JettyPamLoginModule requisite
    debug="true"
    service="sshd"
    supplementalRoles="readonly"
    storePass="true";

org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule required
    debug="true"
    refreshInterval="60"
    hotReload="true"
    useFirstPass="true"
    caseInsensitive="true"
    file="/etc/rundeck/realm.properties";

no users update, no roles update

**Comment by markp1980** [comment]
I got excited then when I thought this was fixed - having to restart the application to refresh a user password is not good. I am hoping this can be looked at urgently.

**Comment by sjrd218** [comment]
You will need to change the first login module you are using from: `org.eclipse.jetty.jaas.spi.PropertyFileLoginModule`
to: `org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule`

The Jetty module you have specified no longer uses the `hotReload` or `refreshInterval` properties.

**Comment by gtsteffaniak** [comment]
@sjrd218 The 3.0.9 update looks rather substantial, thanks for all the work.

Our implementation also uses `org.rundeck.jaas.jetty.JettyRolePropertyFileLoginModule`. Is there a reloadable version of this?

After updating to 3.0.9 new users in the realm.properties file can login but the roles do not update until rundeck is restarted it seems.

**Comment by Ehoudry** [comment]
Same thing using com.dtolabs.rundeck.jetty.jaas.JettyCombinedLdapLoginModule. Roles are not updated whithout restarting when changing them in realm.properties.

**Comment by sjrd218** [comment]
@gtsteffaniak @Ehoudry Thanks for the feedback. I have created a PR to update the JettyRolePropertyFileLoginModule to support hot reloading as well. In the next release you'll be able to add the `hotReload` property to that module and it will hot reload the roles.
