### ISSUE TITLE
Docker & Vmware Integrated Containers entry.sh

### ISSUE THREAD

**Issue by usscarter** [rundeck/rundeck#4270]
**Describe the bug**
When attempting to boot docker on vSphere integrated containers, the process fails. I am unsure of if there is really anything that can be done on your side? The error it gives before crashing out is no such file or directory. Server error from portlayer: stat docker-lib/entry.sh: no such file or directory

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
* install type: Docker
* OS Name/version: vSphere Integrated Containers / PhotonOS
* DB Type/version: MYSQL

**To Reproduce**
Deploy from rundeck/rundeck

**Expected behavior**
Deploy works

**Screenshots**
Maximum number of retries exceeded. Failure: Service https://172.31.0.220:2376/v1.24/containers/667b3934a6b00e3c16524d1d85ee341c05479a43b79fe007c9dcb56403644827/start returned error 500 for POST. id 174699 message Server error from portlayer: stat docker-lib/entry.sh: no such file or directory; Reason: {"message":"Server error from portlayer: stat docker-lib/entry.sh: no such file or directory"}

**Additional context**

**Comment by admun** [comment]
I am seeing the same error when deploying rundeck/rundeck:3.0.12 on k8s with rancher.

here's my deployment.yml

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: rundeck
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: rundeck
    spec:
      volumes:
           - name: rundeck-home
             emptyDir: {}
      containers:
        - name: rundeck
          image: rundeck/rundeck
          env:
            - name: RUNDECK_GRAILS_URL
              value: http://rundeck.somehere.net
          ports:
            - name: http-port
              containerPort: 4440
          volumeMounts:
            - name: rundeck-home
              mountPath: /home/rundeck

**Comment by admun** [comment]
I opened and later found out what I did wrong, see https://github.com/rundeck/rundeck/issues/4403

Turns out i add a volume that overwrite the existing one, so docker-lib/entry.sh is hidden

**Comment by ProTip** [comment]
Great, thanks for the update!
