### ISSUE TITLE
Changes lost in "framework.properties" on docker container restart

### ISSUE THREAD

**Issue by enydrueda** [rundeck/rundeck#4275]
**Describe the bug**
Hi, I am testing the official docker image, mounting the following volumes:
- /home/rundeck/server/config/
- /home/rundeck/libext

If I do a change  in /home/rundeck/etc/framework.properties and restart the container, I will lost the changes.

Am I doing something wrong?

I am creating the container with the following script:

docker run \
	-d \
	-p 4440:4440 \
	-v /rundeck/libext:/home/rundeck/libext \
	-v /rundeck/data:/home/rundeck/server/data \
	-v /rundeck/config/:/home/rundeck/server/config/ \
	-v /rundeck/etc/:/home/rundeck/etc \
	--name rundeck \
	rundeck/rundeck:3.0.8

Thanks!

**Comment by enydrueda** [comment]
I decided to use an installation rundeck rpm, because the problem with the image of the docker

**Comment by ProTip** [comment]
The image utilizes a templating system to generate the configuration files at startup. Most of the settings can be driven from environment variables as listed on the [Docker Hub page](https://dockerhub.com/r/rundeck/rundeck). Beyond that the templates can be replaced or added too. There is an example with more information in the [Docker Zoo](https://github.com/rundeck/docker-zoo/tree/master/config).
