### ISSUE TITLE
Rundeck api to retrieve rundeck output

### ISSUE THREAD

**Issue by korerajesh** [rundeck/rundeck#4279]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by korerajesh** [comment]
Can we retrieve the output of the job through api in rundeck

**Comment by gschueler** [comment]
yes, see https://rundeck.org/docs/api/index.html#execution-output
