### ISSUE TITLE
3.x: Job "Definition" tab in the GUI is Showing Incorrect Schedule Information

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#4284]
**Describe the bug**
When scheduling a job execution to ,e.g., every other day , the "Definition" tab in the GUI is showing as scheduled ALL days.
 
**My Rundeck detail**

* Rundeck version:  3.x  
* install type: any

**To Reproduce**
1. Create a job 
2. Schedule to run repeatedly. Mon, Wed, Fri at 00:00
3. Save.
4. Select "Definition" tab. Job appears as scheduled all weekdays ( just a graphic issue, saved schedule is correct).  

**Expected behavior**
"Definition" tab should show the correct Days as selected in the Schedule

**Screenshots**
_Saved Schedule in 3.x_
![image](https://user-images.githubusercontent.com/31705339/49456520-07222c00-f7c8-11e8-9917-5bfff82b04c4.png)

_Schedule Shown in "Definition" tab v.3.x_
![image](https://user-images.githubusercontent.com/31705339/49456642-2f118f80-f7c8-11e8-9cfd-368e54ab8f3d.png)

_Same View in 2.x_
![image](https://user-images.githubusercontent.com/31705339/49456773-7009a400-f7c8-11e8-9d53-0f64c58152ca.png)

**Comment by fgutierrezz** [comment]
This is also reproduced in 3.0.20 PRO enterprise

**Comment by sebastianbello** [comment]
+1
