### ISSUE TITLE
missing icon in custom plugin

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#4298]
**Describe the bug**
The custom icon.png shows as broken pic.

**My Rundeck detail**

* Rundeck version: 3.0.9
* install type: launcher
* OS Name/version:  ubuntu 18.04
* DB Type/version: any

**To Reproduce**
1. Create a custom plugin v1.2
2. plugin.yaml content has:
```
providers:
  - name: echo hello world
```
3. Check the plugin where you select it, for example, as a Node Step in "Add a Step" section.

**Expected behavior**
To show the custom icon.png from the plugin's resources folder.

**Screenshots**

![captura de pantalla de 2018-12-11 12-26-29](https://user-images.githubusercontent.com/34582874/49810955-03028b00-fd41-11e8-84f4-4f48ffe96348.png)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: chrome
 - Version 71.0.3578.80 (Build oficial) beta (64 bits)

**Additional context**
Debug info:
```
Property [name] of class [class com.dtolabs.rundeck.app.support.PluginResourceReq] with value [echo hello world] does not match the required pattern [^[-a-zA-Z0-9\._:]+$]
```

**Workaround**
Avoid SPACES in the providers/name attribute.

**Comment by sjrd218** [comment]
Are you able to attach the zipped plugin?

**Comment by jplassnibatt** [comment]
@sjrd218 plugins shared internally.

**Comment by gschueler** [comment]
we have validation of the plugin resource request input data, needs to be loosened
