### ISSUE TITLE
Env var configuration override

### ISSUE THREAD

**Issue by hprotzek** [rundeck/rundeck#4308]
I am working on a Helm chart to deploy Rundeck with the official Docker image on k8s. The helm deployment is done with Terraform and I would like to deploy Rundeck in one module and in  another create projects and jobs. Therefore I have to create an access token during installation. With the current setup, this means I have to override the docker-lib entry script to modify the framework.properties.

It would be much simpler, if it would be possible to override any system config like `rundeck.tokens.file` with env vars.

**Comment by dandunckelman** [comment]
Same problem when I try to use this as part of my docker-compose setup. I rely on the Rundeck server using the same API token so my other service can talk to it.

But thanks @hprotzek for mentioning the `docker-lib/entry.sh`. That shortened my hunt for a workaround.

**Comment by ProTip** [comment]
Hello,

We can add that option into the framework properties template. In the meantime there are two options I might suggest:

### Compose Config
Although the configuration system is not currently documented and may change, there is a "designed" method for adding extra configuration in derived containers. You can add extra Remco templates to the container under `/etc/remco/{resources.d,templates}` and they will be included during startup. Although this approach isn't _simple_, it is how we build our enterprise containers internally from `rundeck/rundeck`, and would also be the recommended approach for bundling extra plugins with their configuration.

Here is an example resource:
https://github.com/rundeck/rundeck/blob/master/docker/official/remco/resources.d/rundeck-config-storage.properties.toml

And the dest would be:
`dst = "${REMCO_TMP_DIR}/framework/myconfig.properties`

### Username/Password
This may not work for your needs, however the API can work with the admin username and password. Currently this is how we provision our trial Rundeck instances.
