### ISSUE TITLE
Error 500 trying to access job (on project/.../job/show/..)

### ISSUE THREAD

**Issue by shlomosh** [rundeck/rundeck#4318]
**Describe the bug**
While trying to access a specific job Rundeck returns with "ERROR 500". This only occurs on specific job (other jobs can be viewed). I had this problem in the past, and the only way to recover from it was to delete the job from the job-list page and re-upload it.

**My Rundeck detail**

* Rundeck version: 3.0.8
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: H2

**To Reproduce**
1. Access -
https://<rundeck-hostname>:4443/project/<rundeck-project>/job/show/<job-uuid>
2. See error 500

**Additional context**
I captured the Rundeck log when requesting the above -

[rundeck.log](https://github.com/rundeck/rundeck/files/2689359/rundeck.log)

**Comment by NapoSky** [comment]
+1 here

**My Rundeck detail**

- Rundeck version: 3.0.23 (was the same in 3.0.22)
- install type: deb
- OS Name/version: Debian 8.11
- DB Type/version: MySQL 5.7

I didn't copy/paste my log because It's mostly the same as @shlomosh sent.

**Comment by NapoSky** [comment]
Still the same with Rundeck 3.1.0.

**Comment by NapoSky** [comment]
Still the same with Rundeck 3.1.2.
