### ISSUE TITLE
Load a keystorage value by passing the path into an option

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#4321]
Request to load a key storage value by passing the path into the option.
The secure options expect the input to be a password. the "default storage path" allows that password to be loaded from key storage, but it doesn't support directly loading a password by sending a key path into the option of a child job. The option value can't be used anymore in a Ruleset once passed.

Possibly a plugin could be written to take a key path as input (via job option), and load the key storage value and do something with it.

**Comment by jtobard** [comment]
https://github.com/rundeck-plugins/data-utils
