### ISSUE TITLE
UUID validation and Autocomplete in Job Reference Workflow step

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#4337]
**Is your feature request related to a problem? 
When adding a Job Reference Workflow Step, selecting the JobName makes the UUID corresponding to the selected Job to be updated automatically.  However, if you initially add the UUID to select the Job Reference, the Job Name IS NOT updated accordingly. And more, in case you update the Job Reference by changing the UUID, the selected Job ( JobName) remains unchanged and the UUID is not validated. This may cause the Job Reference to point to an invalid UUID/job or (worst scenario) to an incorrect Job ( if UUID is valid ) that may cause undesired effects.

**Describe the solution you'd like**
Currently, the "jobName" field auto-completes according to the Jobs available in the selected project and the UUID corresponding to the selected job fills up the "UUID" field. A solution may be to have autocomplete work the other way around, i.e.  when selecting a UUID, valid options may show up and Job Name completes accordingly. 

Also, a confirmation may be desired if the current selection is changed to a valid/invalid UUID.

**Comment by frachel** [comment]
The whole way that UUID and Name are both used as the key under different circumstances seems to be an underlying issue. The whole rigmarole I have to to through doing the importing (you detailed it from my support ticket in another Issue I saw). 

Is there a reason UUID is ever user-editable? Seems it should be hidden and used at the internal reference to a job everywhere. Deleting the uuid (which I have to do for a project import) now uses the Job Name as the key, so I can't change the Name of a job or the job-reference will no longer work.

The solution I'd like to see is that you never type or use the UUID (in the GUI at least) - you select a Job Reference from a dropdown, and that's it. When job details are loaded (ie, you're editing the parent job) the Job Name of the Job Reference is retrieved based on the UUID. That way if I changed the textual name of the reference Job, I'll see the new name in my steps, whereas now you see the old name.
