### ISSUE TITLE
[ Give the ability to use Key Storage secrets on remote nodes ]

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#4339]
Hi,

I'm using version 2.10.8-1 on Centos 7 with an RPM based installation of Rundeck.

I have tried the Key Storage functionnality to store an API password.
I'm using this password inside a bash script to authenticate against a remote API.

It works fine but only when I launch the Job with "Execute localy".
I have tried to select a remote node and the secure variable containing the password is not present.

I also tried to run the Job on my local node, but by using the "Dispatch to nodes" option and then the secure variable is populated from the key storage.

I then tried to switch my key storage to DB, rebooted my rundeck instance but no luck.

Is it possible to use the secrets stored in the Key Storage plugin, on remote nodes ?

Thanks for your help and merry Christmas :-)

Jérôme

**Comment by jerome83136** [comment]
Hi,
Some news about this ?
Regards

**Comment by jerome83136** [comment]
Hi guys,
Any news ?

**Comment by JesusRo** [comment]
Hi @jerome83136,

Not 100% sure (would need more details about your script and how you use the key) but it sounds familiar to me.
Take look on https://github.com/rundeck/rundeck/issues/3210, in particular to plambert's comment:
> 
> 
> Many default installations of the OpenSSH server do not pass environment variables from the client to the server. Adding `AcceptEnv RD_*` to `/etc/ssh/sshd_config` on the target nodes will allow them to be passed without allowing non-Rundeck variables (which can have unexpected consequences).
> 
> If that's not an option, either pass the options you need via command line arguments, or via `@option.name@` substitution.

Regarsds :)
