### ISSUE TITLE
Jobs fail but notify as STARTING status in the email subject since upgrade to 3.x

### ISSUE THREAD

**Issue by biguphpc** [rundeck/rundeck#4342]
**Describe the bug**
Since the upgrade to 3.x some jobs (not all) that are set to send an email on FAILURE sends a "STARTING" status in the subject instead of FAILURE. These jobs only are set to only notify on failure.

**My Rundeck detail**

* Rundeck version: 3.0.9
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: postgres

**Expected behavior**
Notifications should be sent with the FAILURE status in subject line instead to reflect the actual status of the job. This is not only a cosmetic issue as these emails could bypass filters set by customers based on status text.

**Additional context**
- Job has not options and two steps
- Job is set to notify only on failure

config:
```
If a step fails: Run remaining steps before failing.Strategy: Node First
Node: | Execute on the server node:
Timeout | 60m
```
Job failed with this error 
```
Result: 1
Failed: NonZeroResultCode: Result code was 1
```
email subject received:
```
STARTING [project] my-job
```

**Comment by cerilawley** [comment]
Looks like the average duration exceeded emails have the same issue.

Job Definition
`- defaultTab: summary
  description: ''
  executionEnabled: true
  id: bd328a9f-6048-4015-a47e-a8a9e14d51aa
  loglevel: INFO
  name: Avg Duration email test
  nodeFilterEditable: false
  notification:
    onavgduration:
      email:
        recipients: ceri.lawley@simplyhealth.co.uk
  notifyAvgDurationThreshold: 1m
  scheduleEnabled: true
  sequence:
    commands:
    - script: |-
        #!/bin/bash

        sleep 240s
        echo "Slept for 4 mins"
    keepgoing: false
    strategy: node-first
  uuid: bd328a9f-6048-4015-a47e-a8a9e14d51aa`

Email Subject
`STARTING [TTD] /Avg Duration email test`

**Comment by biguphpc** [comment]
This is not at stale and still happens with the latest Rundeck version
