### ISSUE TITLE
Failed: SSHProtocolFailure: Algorithm negotiation fail

### ISSUE THREAD

**Issue by GeorgeLopes** [rundeck/rundeck#4349]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: [ Rundeck 2.11.4-1  and  3.0.11-20181221]
* install type: [rpm]
* OS Name/version: [Amazon Linux 2018.3]
* DB Type/version: [mysql ]

**To Reproduce**
Start a new job after created a new access key.

**Expected behavior**
Job executed normally

**Additional context

15:59:01 | [workflow] beginExecuteNodeStep(TransferUser-Staging): NodeDispatch: CommandItem{command=[1 words]}
-- | --
15:59:01 | Using ssh key storage path: keys/rundeck
15:59:01 | Starting SSH Connection: rundeck@zoop-transfers.staging.zoop.tech (TransferUser-Staging)
15:59:01 | Using stored private key data.
15:59:01 | Set timeout to 0
15:59:01 | Connecting to zzhostname:22
15:59:01 | Connecting to zzhostname port 22
15:59:01 | Connection established
15:59:01 | Remote version string: SSH-2.0-OpenSSH_7.4
15:59:01 | Local version string: SSH-2.0-JSCH-0.1.54
15:59:01 | CheckCiphers: aes256-ctr,aes192-ctr,aes128-ctr,aes256-cbc,aes192-cbc,aes128-cbc,3des-ctr,arcfour,arcfour128,arcfour256
15:59:01 | CheckKexes: diffie-hellman-group14-sha1,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521
15:59:01 | CheckSignatures: ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
15:59:01 | SSH_MSG_KEXINIT sent
15:59:01 | SSH_MSG_KEXINIT received
15:59:01 | kex: server: diffie-hellman-group-exchange-sha256,curve25519-sha256@libssh.org,gss-gex-sha1-,gss-group1-sha1-,gss-group14-sha1-
15:59:01 | kex: server: ecdsa-sha2-nistp256,ssh-ed25519,ssh-rsa,rsa-sha2-512,rsa-sha2-256
15:59:01 | kex: server: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
15:59:01 | kex: server: aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,chacha20-poly1305@openssh.com
15:59:01 | kex: server: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
15:59:01 | kex: server: hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,umac-128-etm@openssh.com
15:59:01 | kex: server: none,zlib@openssh.com
15:59:01 | kex: server: none,zlib@openssh.com
15:59:01 | kex: server:
15:59:01 | kex: server:
15:59:01 | kex: client: ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group14-sha1,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group1-sha1
15:59:01 | kex: client: ssh-rsa,ssh-dss,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521
15:59:01 | kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
15:59:01 | kex: client: aes128-ctr,aes128-cbc,3des-ctr,3des-cbc,blowfish-cbc,aes192-ctr,aes192-cbc,aes256-ctr,aes256-cbc
15:59:01 | kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
15:59:01 | kex: client: hmac-md5,hmac-sha1,hmac-sha2-256,hmac-sha1-96,hmac-md5-96
15:59:01 | kex: client: none
15:59:01 | kex: client: none
15:59:01 | kex: client:
15:59:01 | kex: client:
15:59:01 | Disconnecting from hostnamechanged port 22
15:59:01 | SSH command execution error: SSHProtocolFailure: Algorithm negotiation fail
15:59:01 | Failed: SSHProtocolFailure: Algorithm negotiation fail
15:59:01 | [workflow] finishExecuteNodeStep(TransferUser-Staging): NodeDispatch: SSHProtocolFailure: Algorithm negotiation fail

**Comment by GeorgeLopes** [comment]
Have some options to force one cipher?

**Comment by GeorgeLopes** [comment]
[root@rundeck security]# ll
total 120
-rw-r--r-- 1 root root  1273 Nov  2 22:47 blacklisted.certs
lrwxrwxrwx 1 root root    41 Jan  2 17:30 cacerts -> ../../../../../../../etc/pki/java/cacerts
-rw-r--r-- 1 root root  2466 Nov  2 22:47 java.policy
-rw-r--r-- 1 root root 37592 Jan  1  2014 java.security
-rw-r--r-- 1 root root 40869 Jan  1  2014 java.security.rpmnew
-rw-r--r-- 1 root root  8409 Mar 18  2014 jce_policy-8.zip
-rw-rw-r-- 1 root root  3035 Dez 20  2013 local_policy.jar
-rw-r--r-- 1 root root   139 Nov  2 23:03 nss.cfg
drwxr-xr-x 4 root root  4096 Jan  2 17:30 policy
drwxrwxr-x 2 root root  4096 Dez 20  2013 UnlimitedJCEPolicyJDK8
-rw-rw-r-- 1 root root  3023 Dez 20  2013 US_export_policy.jar

**Comment by GeorgeLopes** [comment]
installed JCE and restarted the application, need to restart server?

**Comment by DerDanilo** [comment]
How do we solve this officially? JCE doesn't seem to be a working solution since it should be integrated with latest java packages.

**Comment by oktayaa** [comment]
Is there a workaround to solve this today as an end user?

**Comment by siilike** [comment]
Use the script exec/copy instead of jsch:

```
service.FileCopier.default.provider=script-copy
service.NodeExecutor.default.provider=script-exec
plugin.script-copy.default.command=scp ${file-copy.file} ${node.username}@${node.hostname}\:${file-copy.destination}
plugin.script-exec.default.command=ssh -o "StrictHostKeyChecking no" ${node.username}@${node.hostname} ${exec.command}
plugin.script-exec.default.shell=bash -c
```

**Comment by captnbp** [comment]
With Rundeck 3.3.2 (in official Docker image):

Jcsh still fails with these settings on the target SSH node (/etc/ssh/sshd_config):
```
HostKey /etc/ssh/ssh_host_ed25519_key
KexAlgorithms curve25519-sha256@libssh.org
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com
```

Just tried with the workaround and a ssh key file (so not stored in the key-store):
```
plugin.script-copy.default.command=scp -i /home/rundeck/server/data/rundeck.key -o StrictHostKeyChecking\=no ${file-copy.file} ${node.username}@${node.hostname}\:${file-copy.destination}
plugin.script-copy.default.remote-filepath=${node.destdir}/${file-copy.filename}
plugin.script-exec.default.command=ssh -i /home/rundeck/server/data/rundeck.key -o StrictHostKeyChecking\=no ${node.username}@${node.hostname} ${exec.command}
plugin.script-exec.default.shell=bash -c
project.description=benoit
project.disable.executions=false
project.disable.schedule=false
project.execution.history.cleanup.batch=500
project.execution.history.cleanup.enabled=true
project.execution.history.cleanup.retention.days=60
project.execution.history.cleanup.retention.minimum=50
project.execution.history.cleanup.schedule=0 0 0 1/1 * ? *
project.jobs.gui.groupExpandLevel=1
project.label=benoit
project.name=benoit
project.output.allowUnsanitized=false
project.ssh-authentication=privateKey
project.ssh-command-timeout=0
project.ssh-connect-timeout=0
project.ssh-key-passphrase-storage-path=keys/sshPassphrase
project.ssh-key-storage-path=keys/rundeck.key
project.ssh-keypath=/home/rundeck/server/data/rundeck.key
resources.source.1.type=local
resources.source.2.config.file=server/data/nodes.yml
resources.source.2.config.format=resourceyaml
resources.source.2.config.generateFileAutomatically=true
resources.source.2.config.writeable=true
resources.source.2.type=file
service.FileCopier.default.provider=script-copy
service.NodeExecutor.default.provider=script-exec
```
The bad thing with this is I can't use the ssh key passphrase from the key-store...

Hope there will be an official solution with Jcsh.

**Comment by a-oishi** [comment]
"OpenSSH Node Execution Plugins" can solve this issue as an alternate solution.
https://docs.rundeck.com/docs/administration/projects/node-execution/openssh.html#plugin-configuration-properties

**Comment by DerDanilo** [comment]
> "OpenSSH Node Execution Plugins" can solve this issue as an alternate solution.
> https://docs.rundeck.com/docs/administration/projects/node-execution/openssh.html#openssh-node-execution-plugins

The problem with this was in the past that `ed` ssh keys could not be used. Additionally it have had problems with connecting to ssh hardened nodes.

**Comment by bluikko** [comment]
It still does not work with sshd configured to use only modern ciphers/kex/mac... huoh.
