### ISSUE TITLE
Jobs with Notifications hang when backend is using mssql

### ISSUE THREAD

**Issue by adnanqureshi0280** [rundeck/rundeck#4356]
**Describe the bug**
If Rundeck backend is changed from H2 to mssql, any jobs that send notifications get stuck and prevents viewing of the job or the Activity screen until Rundeck is completed restarted.

**My Rundeck detail**

* Rundeck version: 3.0.11
* install type: war
* OS Name/version: Windows Server 2016
* DB Type/version: mssql version 2016 (mssql-jdbc-7.0.0.jre8.jar under %RDECK_BASE%\server\lib)

**To Reproduce**
1. Create brand new SQL database for Rundeck
2. Create a new job
3. Send Notification? answer Yes
4. On Success check Send Email
5. Create job
6. Run the job and it never completes
7. Go to Activity and it will load forever

**Expected behavior**
Job should run successfully, send an email, and allow viewing Activity screen

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 71.0.3578.98

**Additional context**

**Comment by sylbae** [comment]
I recently switched from H2 to MSSQL and I am facing a similar issue... Except that notification is not necessary required to be enabled in my case to produce the problem. Some of my jobs (I have not identified yet the common pattern) do successful execute each step but still will not properly exit... job stucks as still running even though there is nothing to run anymore. And as you mentioned it is required to restart Rundeck to resolve the problem.


**My Rundeck detail**

- Rundeck version: 3.0.9 then 3.0.11 (same problem on both versions)
- install type: war
- OS Name/version: Linux RHEL 6.9
- DB Type/version: MSSQL version 2012 (sqljdbc42.jar under %RDECK_BASE%\server\lib)
