### ISSUE TITLE
Rundeck 3.0.9 scheduled job is failing and succeeding

### ISSUE THREAD

**Issue by chethanym** [rundeck/rundeck#4357]
**Expected behavior**
We are facing an issue(might be a bug with rundeck version) like we are scheduled a rundeck job to run for every 6 hours it was fine with the previous version after upgrading to the 3.0.9 the job is failing with in a second after starting the job by the following error.

```12:00:00 [chethanym@host2.domain.com _][ERROR] com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=host2.domain.com, dominant=false, }}
12:00:00 [chethanym@host2.domine.com _][ERROR] 	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.validateNodeSet(NodeFirstWorkflowExecutor.java:421)
12:00:00 [chethanym@host2.domine.com _][ERROR] 	at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowExecutor.executeWorkflowImpl(NodeFirstWorkflowExecutor.java:90)
12:00:00 [chethanym@host2.domine.com _][ERROR] 	at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowExecutor.executeWorkflow(BaseWorkflowExecutor.java:222)
12:00:00 [chethanym@host2.domain.com_][ERROR] 	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.runWorkflow(WorkflowExecutionServiceThread.java:83)
12:00:00 [chethanym@host2.domain.com _][ERROR] 	at com.dtolabs.rundeck.core.logging.LoggingManagerImpl$MyPluginLoggingManager.runWith(LoggingManagerImpl.java:148)
12:00:00 [chethanym@host2.domain.com _][ERROR] 	at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:74)
12:00:00 [chethanym@host2.domain.com _][ERROR] Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=host2.domine.com, dominant=false, }}
```
After 9 minutes the same job is succeeding without any error. And if we run the job manually there is no job failure but the job failing only for Scheduled job. we configured email for every job start, failure and success. now we are getting mail like job is started, job is failed, job is succeeded(for scheduled job).

**Screenshots**

*
![image](https://user-images.githubusercontent.com/35649420/50685632-f58aa900-103f-11e9-8679-615736719e63.png)
*Desktop:-

 - OS: Mac
 - Browser: chrome
 - Version: 71.0.3578.98 (Official Build) (64-bit)

**Comment by sylbae** [comment]
I am facing same issue... I have a couple of jobs running every 30 mn... There were running fine until recent upgrade to v3.0.9... Since it does randomly fail... When it happens, I get same NodesetEmptyException error.
