### ISSUE TITLE
CHild job is not taking the dynamic node filter from parent job

### ISSUE THREAD

**Issue by Saticppro** [rundeck/rundeck#4358]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 
* install type: (rpm,deb,war,launcher?)
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**

**How to Reproduce**

**Comment by Saticppro** [comment]
rundeck version 3.0.8
install type rpm
OS Name Linux

**Comment by Saticppro** [comment]
When I am calling the rundeck job with node filter, the first job is being executed but the workflow job i.e., child job is failing with there are no matching nodes. I have tried with and without overriding the node filters, but the issue is same. I have used the same filter for both parent job and child job

**Comment by Saticppro** [comment]
Hi Can someone please address this

**Comment by puremourning** [comment]
I think you should complete the issue template with a minimal reproducible test case.
