### ISSUE TITLE
Failed to start execution: org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not prepare statement; uncategorized SQLException for SQL

### ISSUE THREAD

**Issue by BornTKill** [rundeck/rundeck#4359]
**Describe the bug**
I've migrated from 2.10.8-1 to Rundeck 3.0.11-20181221 (on a new platform) by exporting et reimporting xml jobs.
Backend is local mysql server (same version and configuration as it is on 2.10.8-1 platform).

When a lot of jobs triggered at the same times, many fails with :

Failed to start execution: org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not prepare statement; uncategorized SQLException for SQL [select schedulede0_.id as id1_15_0_, schedulede0_.version as version2_15_0_, schedulede0_.log_output_threshold as log_outp3_15_0_, schedulede0_.do_nodedispatch as do_noded4_15_0_, schedulede0_.next_execution as next_exe5_15_0_, schedulede0_.date_created as date_cre6_15_0_, schedulede0_.node_keepgoing as node_kee7_15_0_, schedulede0_.node_exclude_os_arch as node_exc8_15_0_, schedulede0_.uuid as uuid9_15_0_, schedulede0_.node_include as node_in10_15_0_, schedulede0_.success_on_empty_node_filter as success11_15_0_, schedulede0_.node_exclude_os_version as node_ex12_15_0_, schedulede0_.timeout as timeout13_15_0_, schedulede0_.node_exclude_precedence as node_ex14_15_0_, schedulede0_.node_exclude_name as node_ex15_15_0_, schedulede0_.notify_avg_duration_threshold as notify_16_15_0_, schedulede0_.day_of_week as day_of_17_15_0_, schedulede0_.node_include_os_version as node_in18_15_0_, schedulede0_.node_exclude_os_name as node_ex19_15_0_, schedulede0_.retry as retry20_15_0_, schedulede0_.group_path as group_p21_15_0_, schedulede0_.filter as filter22_15_0_, schedulede0_.scheduled as schedul23_15_0_, schedulede0_.orchestrator_id as orchest24_15_0_, schedulede0_.node_threadcount_dynamic as node_th25_15_0_, schedulede0_.node_include_name as node_in26_15_0_, schedulede0_.multiple_executions as multipl27_15_0_, schedulede0_.time_zone as time_zo28_15_0_, schedulede0_.rduser as rduser29_15_0_, schedulede0_.node_include_os_name as node_in30_15_0_, schedulede0_.node_exclude as node_ex31_15_0_, schedulede0_.node_rank_order_ascending as node_ra32_15_0_, schedulede0_.nodes_selected_by_default as nodes_s33_15_0_, schedulede0_.node_include_os_arch as node_in34_15_0_, schedulede0_.loglevel as logleve35_15_0_, schedulede0_.node_exclude_os_family as node_ex36_15_0_, schedulede0_.execution_enabled as executi37_15_0_, schedulede0_.max_multiple_executions as max_mul38_15_0_, schedulede0_.node_include_os_family as node_in39_15_0_, schedulede0_.last_updated as last_up40_15_0_, schedulede0_.retry_delay as retry_d41_15_0_, schedulede0_.workflow_id as workflo42_15_0_, schedulede0_.exec_count as exec_co43_15_0_, schedulede0_.month as month44_15_0_, schedulede0_.hour as hour45_15_0_, schedulede0_.log_output_threshold_action as log_out46_15_0_, schedulede0_.arg_string as arg_str47_15_0_, schedulede0_.user_role_list as user_ro48_15_0_, schedulede0_.total_time as total_t49_15_0_, schedulede0_.node_rank_attribute as node_ra50_15_0_, schedulede0_.server_nodeuuid as server_51_15_0_, schedulede0_.default_tab as default52_15_0_, schedulede0_.node_exclude_tags as node_ex53_15_0_, schedulede0_.seconds as seconds54_15_0_, schedulede0_.ref_exec_count as ref_exe55_15_0_, schedulede0_.node_threadcount as node_th56_15_0_, schedulede0_.node_include_tags as node_in57_15_0_, schedulede0_.job_name as job_nam58_15_0_, schedulede0_.schedule_enabled as schedul59_15_0_, schedulede0_.year as year60_15_0_, schedulede0_.day_of_month as day_of_61_15_0_, schedulede0_.node_filter_editable as node_fi62_15_0_, schedulede0_.log_output_threshold_status as log_out63_15_0_, schedulede0_.description as descrip64_15_0_, schedulede0_.minute as minute65_15_0_, schedulede0_.project as project66_15_0_ from scheduled_execution schedulede0_ where schedulede0_.id=?]; SQL state [null]; error code [0]; [quartzScheduler_Worker-125] Timeout: Pool empty. Unable to fetch a connection in 10 seconds, none available[size:51; busy:51; idle:0; lastwait:10000].; nested exception is org.apache.tomcat.jdbc.pool.PoolExhaustedException: [quartzScheduler_Worker-125] Timeout: Pool empty. Unable to fetch a connection in 10 seconds, none available[size:51; busy:51; idle:0; lastwait:10000].

I try to "tune jdbc" but nothing changed :

cat /etc/rundeck/rundeck-config.groovy

loglevel.default = "INFO"
rdeck.base = "/var/lib/rundeck"
rss.enabled = "false"
rundeck.log4j.config.file = "/etc/rundeck/log4j.properties"

rundeck.security.useHMacRequestTokens = true
rundeck.security.apiCookieAccess.enabled = true

dataSource {
  dbCreate = "update"
  url = "jdbc:mysql://localhost:3306/rundeck?autoReconnect=true"
  driverClassName = "com.mysql.jdbc.Driver"
  username = "rundeck"
  password = "xxxxxx"
  dialect = ""
}

dataSource.pooled=true
dataSource.properties.removeAbandoned=true
dataSource.properties.removeAbandonedTimeout=60
dataSource.properties.testOnBorrow=true

grails.serverURL = "https://rundeck.xxx.com"
grails.mail.default.from="rundeck@xxx.com"
rundeck.clusterMode.enabled = "true"
rundeck.executionMode = "active"

rundeck.projectsStorageType = "db"
quartz.threadPool.threadCount = "150"

rundeck.storage.provider."1".type = "db"
rundeck.storage.provider."1".path = "/"

rundeck.security.authorization.preauthenticated.enabled = "false"
rundeck.security.authorization.preauthenticated.attributeName = "REMOTE_USER_GROUPS"
rundeck.security.authorization.preauthenticated.delimiter = ":"
rundeck.security.authorization.preauthenticated.userNameHeader = "X-Forwarded-Uuid"
rundeck.security.authorization.preauthenticated.userRolesHeader = "X-Forwarded-Roles"
rundeck.security.authorization.preauthenticated.redirectLogout = "false"
rundeck.security.authorization.preauthenticated.redirectUrl = "/oauth2/sign_in"

rundeck.execution.logs.streamingWriterPlugins=LogstashPluginLogger
rundeck.api.tokens.duration.max="0"

**My Rundeck detail**

* Rundeck version: Rundeck 3.0.11-20181221
* install type: deb
* OS Name/version: Debian 9.6
* DB Type/version: mysql : percona-server-server-5.5.62

**Comment by BornTKill** [comment]
Dear,

Anyone to help me ?

**Comment by puremourning** [comment]
it looks like the query is timing out with 51 concurrent requests:

> Timeout: Pool empty. Unable to fetch a connection in 10 seconds, none available[size:51; busy:51; idle:0; lastwait:10000].

is there a perf issue on your mysql server?

**Comment by shoelzle** [comment]
Hello,

I'm running into the same issue:
```
Caused by: org.apache.tomcat.jdbc.pool.PoolExhaustedException: [quartzScheduler_Worker-5] Timeout: Pool empty. Unable to fetch a connection in 10 seconds, none available[size:50; busy:50; idle:0; lastwait:10000].
```

The connection limit of my database is set to 100, therefore I guess the limit is set somewhere in rundeck or in it's used libraries.

Rundeck: 3.0.8-20181029
OS: Debian 9 stretch
DB: PostgreSQL 9.6

**Comment by ahonor** [comment]
@BornTKill does this bug occur for any kind of job or jobs that call jobref steps?

**Comment by BornTKill** [comment]
Hello!

Thank you for your reply @ahonor.
All my jobs are just one step with ssh remote command.

**Comment by BornTKill** [comment]
Dear @ahonor,

Can you update me on the situation ?
Sorry for bothering you.

Best regards.

**Comment by shoelzle** [comment]
@BornTKill , the PoolExhausted is thrown, if the maximum allowed connections is reached. It seems the default is set to 50: https://github.com/rundeck/rundeck/blob/262dffb45ca705d985e03703f7dabbfc8ee36797/rundeckapp/grails-app/conf/application.groovy#L58

This property can be overridden in the rundeck-config file:
```
dataSource.properties.maxActive = 100
```

In my case this helped.

Best Regards

**Comment by BornTKill** [comment]
Dear,

I ve apply this param in the dataSource {} instead of using dataSource.properties.maxActive = 100.
No error since 10.00 AM. Wait and See.

**Comment by kaitcoa** [comment]
Hey guys,

I just received issues with Quartz scheduler, even my threadCount was set to 100. 
quartz.threadPool.threadCount = 100.
Probably upgrade the machine to more RAM and set that threadCount to a higher value. 
Any other suggestions maybe?

**Comment by shoelzle** [comment]
@kaitcoa , could you post the exception/error message you're getting ?

**Comment by kaitcoa** [comment]
> Failed to start execution: org.springframework.jdbc.UncategorizedSQLException: Hibernate operation: could not prepare statement; uncategorized SQLException for SQL [select schedulede0_.id as id1_15_0_, schedulede0_.version as version2_15_0_, schedulede0_.log_output_threshold as log_outp3_15_0_, schedulede0_.do_nodedispatch as do_noded4_15_0_, schedulede0_.next_execution as next_exe5_15_0_, schedulede0_.date_created as date_cre6_15_0_, schedulede0_.node_keepgoing as node_kee7_15_0_, schedulede0_.node_exclude_os_arch as node_exc8_15_0_, schedulede0_.uuid as uuid9_15_0_, schedulede0_.node_include as node_in10_15_0_, schedulede0_.success_on_empty_node_filter as success11_15_0_, schedulede0_.node_exclude_os_version as node_ex12_15_0_, schedulede0_.timeout as timeout13_15_0_, schedulede0_.node_exclude_precedence as node_ex14_15_0_, schedulede0_.node_exclude_name as node_ex15_15_0_, schedulede0_.notify_avg_duration_threshold as notify_16_15_0_, schedulede0_.day_of_week as day_of_17_15_0_, schedulede0_.node_include_os_version as node_in18_15_0_, schedulede0_.node_exclude_os_name as node_ex19_15_0_, schedulede0_.retry as retry20_15_0_, schedulede0_.group_path as group_p21_15_0_, schedulede0_.filter as filter22_15_0_, schedulede0_.scheduled as schedul23_15_0_, schedulede0_.orchestrator_id as orchest24_15_0_, schedulede0_.node_threadcount_dynamic as node_th25_15_0_, schedulede0_.node_include_name as node_in26_15_0_, schedulede0_.multiple_executions as multipl27_15_0_, schedulede0_.time_zone as time_zo28_15_0_, schedulede0_.rduser as rduser29_15_0_, schedulede0_.node_include_os_name as node_in30_15_0_, schedulede0_.node_exclude as node_ex31_15_0_, schedulede0_.node_rank_order_ascending as node_ra32_15_0_, schedulede0_.nodes_selected_by_default as nodes_s33_15_0_, schedulede0_.node_include_os_arch as node_in34_15_0_, schedulede0_.loglevel as logleve35_15_0_, schedulede0_.node_exclude_os_family as node_ex36_15_0_, schedulede0_.execution_enabled as executi37_15_0_, schedulede0_.max_multiple_executions as max_mul38_15_0_, schedulede0_.node_include_os_family as node_in39_15_0_, schedulede0_.last_updated as last_up40_15_0_, schedulede0_.retry_delay as retry_d41_15_0_, schedulede0_.workflow_id as workflo42_15_0_, schedulede0_.exec_count as exec_co43_15_0_, schedulede0_.month as month44_15_0_, schedulede0_.hour as hour45_15_0_, schedulede0_.log_output_threshold_action as log_out46_15_0_, schedulede0_.arg_string as arg_str47_15_0_, schedulede0_.user_role_list as user_ro48_15_0_, schedulede0_.total_time as total_t49_15_0_, schedulede0_.node_rank_attribute as node_ra50_15_0_, schedulede0_.server_nodeuuid as server_51_15_0_, schedulede0_.default_tab as default52_15_0_, schedulede0_.node_exclude_tags as node_ex53_15_0_, schedulede0_.seconds as seconds54_15_0_, schedulede0_.ref_exec_count as ref_exe55_15_0_, schedulede0_.node_threadcount as node_th56_15_0_, schedulede0_.node_include_tags as node_in57_15_0_, schedulede0_.job_name as job_nam58_15_0_, schedulede0_.schedule_enabled as schedul59_15_0_, schedulede0_.year as year60_15_0_, schedulede0_.day_of_month as day_of_61_15_0_, schedulede0_.node_filter_editable as node_fi62_15_0_, schedulede0_.log_output_threshold_status as log_out63_15_0_, schedulede0_.description as descrip64_15_0_, schedulede0_.minute as minute65_15_0_, schedulede0_.project as project66_15_0_ from scheduled_execution schedulede0_ where schedulede0_.id=?]; SQL state [null]; error code [0]; [quartzScheduler_Worker-85] Timeout: Pool empty. Unable to fetch a connection in 10 seconds, none available[size:50; busy:50; idle:0; lastwait:10000].; nested exception is org.apache.tomcat.jdbc.pool.PoolExhaustedException: [quartzScheduler_Worker-85] Timeout: Pool empty. Unable to fetch a connection in 10 seconds, none available[size:50; busy:50; idle:0; lastwait:10000].

Hey @shoelzle heres the output of errors.

**Comment by ProTip** [comment]
Hi @kaitcoa ,

It looks like your database connection pool has run dry. Do you have many jobs running at the same time? You may need to set `dataSource.properties.maxActive=100` in `rundeck-config.properties` (or possibly your tomcat config if using tomact) in order to allow for more database connections.

**Comment by kaitcoa** [comment]
@ProTip Thank you mate, will try that way!

**Comment by ProTip** [comment]
We have also added a number of fixes to reduce connection usage and long-held connections. Please reopen if issue occurs in `>=3.0.19`

**Comment by venkategowdap** [comment]
@MegaDrive68k :  Thank you ..Let me try this ..
