### ISSUE TITLE
Average job duration as variable

### ISSUE THREAD

**Issue by rgarrigue** [rundeck/rundeck#4362]
**Is your feature request related to a problem? Please describe.**

I've a backup job. I'ld like to disable some monitoring while it's running, but only for a fixed duration, just in case. Using something like 120% of the average job duration would be perfect. But it seems there's no ${job.averageDuration} variable.

**Describe the solution you'd like**

Please add a ${job.averageDuration} option with the same value as displayed in the stats. 

**Describe alternatives you've considered**

Scraping web page, too messy. Getting the value myself from the database, can't do that, executing on another node than rundeck itself.

I can (and I will until this FR is implemented, if it is) change my job to downtime the monitoring before backup and remove downtime once finished. Or use an arbitrary fixed value. But that's risky in the first case, if something happen to rundeck during the hours-long backup. And arbitrary value will be forgotten until it wake up someone in the middle of the night 6 months later.

**Additional context**

Might as well add number of execution & success rate while you're doing this, I can think of some use case for it, like integration with third party stats tool or whatever.

**Comment by ajk17** [comment]
We were just looking for something similar to use for our timeout value.  It would be good to have an average duration variable so we could put something like 2*${job.averageDuration} in the timeout variable so the job would fail out if it's taking too long/hanging.

**Comment by ilovemysillybanana** [comment]
Don't know if we had to open up another issue but I'd love to also have the current running time so we can compare it to the average running time. I.E if the job is usually done in 4 hours but it still running 6 hours after that I'd like to set up an alert.
