### ISSUE TITLE
getAuthContextForSubject :Cannot get AuthContext Without Subject Rundeck Issue

### ISSUE THREAD

**Issue by Rajat4440** [rundeck/rundeck#4368]
I am using Rundeck 2.7.0 jar in my linux production servers for scheduling purpose.

I have assigned around 3072 mb memory for rundeck process in profile file.

It runs perfectly for 2 days than suddenly i got above error mentioned in Title and my job stops running. 

Please any one tell what is latest stable version i should use so that above issues should not come. 

Should i use Rundeck -3.0.11 ?

Please help i am stuck with production issue.

What is solution for above issue . I am using default auth mechanism given by Rundeck Team.Why this issue is coming.

**Comment by alex067** [comment]
Ran into the same issue as OP on 3.0.19, restarting the server did not help, however it was ran on a docker container and restarting the container fixed the issue
