### ISSUE TITLE
Configuration of temporary directory for file uploading not working.

### ISSUE THREAD

**Issue by snhughes** [rundeck/rundeck#4369]
**Describe the bug**
When creating a "File" option in a job to upload a file, the file is available in "/var/lib/rundeck/upload" in the target server by default.
Reading the description of the "Temporary File" plugin (Settings -> List Plugins -> File Upload Plugins), it says that the temporary directory can be changed by adding the following lines to the properties files:

rundeck-config.properties:   rundeck.fileupload.plugin.type=filesystem-temp
framework.properties:    framework.plugin.FileUploadPluginService.filesystem-temp.basePath=_value_

I have added these lines with _value_ being /var/tmp but it is still using the default /var/lib/rundeck/upload.

**My Rundeck detail**

* Rundeck version: 2.11.3
* install type: rpm
* OS Name/version: REL 7.4
* DB Type/version:  Don't know :(

**To Reproduce**
1. Add the following line to rundeck-config.properties: 
  rundeck.fileupload.plugin.type=filesystem-temp
2. Add the following line to framework.properties:
   framework.plugin.FileUploadPluginService.filesystem-temp.basePath=/var/tmp
3. Restart Rundeck
4. Create a new job
5. Add an option with "Option Type" set to "File"
6. Add a step to run a bash script with the following line:
  echo @file.file_to_upload@ 
 
**Expected behavior**
I would expect that @file.file_to_upload@ would be a folder in /var/tmp. However, it is still using /var/lib/rundeck/upload. This is a problem when the target servers don't have the /var/lib/rundeck folder. The file doesn't get uploaded.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser: Chrome
 - Version: 71

**Comment by gschueler** [comment]
dev note: 
1. FileUpload plugins are not configured correctly using framework properties at https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/services/rundeck/services/FileUploadService.groovy#L83
2. "FileUploadPluginService" service name needs to be renamed to "FileUpload" in temp file implementation, and added to ServiceTypes

**Comment by snhughes** [comment]
Update/Correction: It seems I misunderstood some the description for @file.file_to_upload@. I thought it was a location on the target server but it's a location on the rundeck server that is running the job. I managed to get my upload done by scp from the rundeck to the targets. However, I still have the problem of not being able to change the temp directory.
Thanks.

**Comment by jothoma1** [comment]
Hi,
is there a way to make temporary directory for upload work on Windows server with openssh ? 
I tried to make it work on a windows 2019 with openssh. But the plugin wants to copy my file on c:\var\lib\rundeck\var\upload and it did not work

**Comment by ProTip** [comment]
Fixed by #4656
