### ISSUE TITLE
RD 3 : preauthentication with Tomcat always redirects to /user/login

### ISSUE THREAD

**Issue by fredericbarrau** [rundeck/rundeck#4374]
After migrating to 3.X, preauthenticated mode with tomcat always redirect to /user/login, asking for a password.
Frustrating thing is that `rundeck.access.log` is even showing the username (fbarrau here) provided by preauthentication when showing traces of the user/login pages:

```
[2019-01-10 09:00:03,365] "GET /rundeck/user/login" 10.11.6.214 https fbarrau form 139 ? [] (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15)
[2019-01-10 09:00:03,837] "GET /rundeck/static/images/rundeck-full-logo-black.png" 10.11.6.214 https fbarrau form 8 ? [image/png] (Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.0.2 Safari/605.1.15)
```

so the username provided by preauthentication is somehow grabbed by rundeck, but the realm authentication is still triggering.
 
Configuration is pretty much what is described in the [rundeck documentation](https://docs.rundeck.com/docs/administration/security/authenticating-users.html#preauthenticated-mode) : tomcat + rundeck.war with AJP, groups are provided by mod_lookup_identity. This setup has worked fine on dozens of platform with rundeck 2.X.

Rundeck log shows that preauthenticated mode is enabled:

```
2019-01-10 09:23:50.158  INFO --- [ost-startStop-1] rundeckapp.BootStrap                     : Starting Rundeck 3.0.11-20181221 (2018-12-22) ...
2019-01-10 09:23:50.163  INFO --- [ost-startStop-1] rundeckapp.BootStrap                     : using rdeck.base config property: /projet/rundeck
2019-01-10 09:23:50.172  INFO --- [ost-startStop-1] rundeckapp.BootStrap                     : loaded configuration: /projet/rundeck/server/config/framework.properties
2019-01-10 09:23:50.258  INFO --- [ost-startStop-1] rundeckapp.BootStrap                     : RSS feeds disabled
2019-01-10 09:23:50.259  INFO --- [ost-startStop-1] rundeckapp.BootStrap                     : Using builtin realm authentication
2019-01-10 09:23:50.263  INFO --- [ost-startStop-1] rundeckapp.BootStrap                     : Preauthentication is enabled
2019-01-10 09:23:50.296  INFO --- [ost-startStop-1] rundeckapp.BootStrap                     : Rundeck is ACTIVE: executions can be run.
2019-01-10 09:23:50.444  INFO --- [ost-startStop-1] rundeckapp.BootStrap                     : Rundeck startup finished in 369ms
```

Our **rundeck-config.properties**  has the following lines:

```
# Enable Pre-Authentication configuration
rundeck.security.authorization.preauthenticated.enabled=true
rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
rundeck.security.authorization.preauthenticated.delimiter=:
```

What I have tried, unsuccessfully so far:

* add `rundeck.jaaslogin = false` in the **rundeck-config.properties**.
* add these lines in **rundeck-config.properties**: 
  ```
  rundeck.security.authorization.containerPrincipal.enabled=false
  rundeck.security.authorization.container.enabled=false
  ```
* setting property file auth as optional:
  ```
  RDpropertyfilelogin {
    org.eclipse.jetty.jaas.spi.PropertyFileLoginModule optional
    debug="true"
    file="/projet/rundeck/server/config/realm.properties";
  };
  ```

* Rundeck version: 3.0.8 - 3.0.11
* install type: rundeck war + tomcat 7.0.68 + java opendfk 1.8.0_191
* OS Name/version: Centos 7
* DB Type/version: mariadb

**Comment by sjrd218** [comment]
@fredericbarrau What system properties do you have set on your tomcat server?

**Comment by fredericbarrau** [comment]
Here is the **server.xml** I use for our rundeck instances:

```
<xml<?xml version='1.0' encoding='utf-8'?>

<Server port="8005" shutdown="SHUTDOWN" address="localhost">
  <Listener className="org.apache.catalina.startup.VersionLoggerListener" />

  <Listener className="org.apache.catalina.core.AprLifecycleListener" SSLEngine="on" />
  <Listener className="org.apache.catalina.core.JasperListener" />
  <Listener className="org.apache.catalina.core.JreMemoryLeakPreventionListener" />
  <Listener className="org.apache.catalina.mbeans.GlobalResourcesLifecycleListener" />
  <Listener className="org.apache.catalina.core.ThreadLocalLeakPreventionListener" />

  <GlobalNamingResources>
    <Resource name="UserDatabase" auth="Container"
              type="org.apache.catalina.UserDatabase"
              description="User database that can be updated and saved"
              factory="org.apache.catalina.users.MemoryUserDatabaseFactory"
              pathname="conf/tomcat-users.xml" />
  </GlobalNamingResources>

  <Service name="Catalina">

    <!-- Define an AJP 1.3 Connector on port 8009 -->
    <Connector port="8009" protocol="AJP/1.3"
               redirectPort="4440" connectionTimeout="29" tomcatAuthentication="false" />

    <!-- You should set jvmRoute to support load-balancing via AJP ie :
    <Engine name="Catalina" defaultHost="localhost" jvmRoute="jvm1">
    -->
    <Engine name="Catalina" defaultHost="localhost">
     <Realm className="org.apache.catalina.realm.LockOutRealm">
       <Realm className="org.apache.catalina.realm.UserDatabaseRealm"
               resourceName="UserDatabase"/>
      </Realm>

      <Host name="localhost"  appBase="webapps"
            unpackWARs="true" autoDeploy="false">

        <Valve className="org.apache.catalina.valves.AccessLogValve" directory="logs"
               prefix="rundeck_access_log." suffix=".log"
               pattern="%h %l %u %t &quot;%r&quot; %s %b" />

      </Host>
    </Engine>
  <Connector port="4440" protocol="HTTP/1.1" connectionTimeout="28"></Connector>
</Service>
</Server>
```

Nothing customized appart from that. Would you need anything else ?

**Comment by kbens** [comment]
@fredericbarrau did this fix work for you? I'm still seeing this behavior on 3.3. I'm taking a deeper look now and will report back what I find.

**Comment by fredericbarrau** [comment]
> @fredericbarrau did this fix work for you? I'm still seeing this behavior on 3.3. I'm taking a deeper look now and will report back what I find.

Haven't been able to test it with Tomcat. I changed the setup of our Rundeck instances by using the RPM package of rundeck (with the embedded Jetty), which works fine in preauthenticated mode.

**Comment by kbens** [comment]
OK, thanks. One last question... For preauth with the RPM install, are you passing with AJP or just via Headers, like shown below?? 

```
rundeck.security.authorization.preauthenticated.userNameHeader=X-Forwarded-Uuid
rundeck.security.authorization.preauthenticated.userRolesHeader=X-Forwarded-Roles
```

**Comment by fredericbarrau** [comment]
> OK, thanks. One last question... For preauth with the RPM install, are you passing with AJP or just via Headers, like shown below??
> 
> ```
> rundeck.security.authorization.preauthenticated.userNameHeader=X-Forwarded-Uuid
> rundeck.security.authorization.preauthenticated.userRolesHeader=X-Forwarded-Roles
> ```

We are using headers (using the configuration you shown),  provided by our reverse-proxy (apache here), which manages the authentication part.

**Comment by kbens** [comment]
Thanks for the information. Yes, I had success with headers but couldn't get it to work with Tomcat and passing via AJP. I opened a new issue for this. https://github.com/rundeck/rundeck/issues/7193
