### ISSUE TITLE
3.0.11 : Cannot create job : The request did not include a valid token, or the token has expired.

### ISSUE THREAD

**Issue by Daryes** [rundeck/rundeck#4383]
**Describe the bug**
When creating a new job, I can open the create job UI, add steps to the new job, saving the steps, but Rundeck refuses  to save a new option/variable, or save the new job itself, with the following error :
````
The request did not include a valid token, or the token has expired. Please try your request again. 
````
The error itself is not visible, only appears in the http response, through the browser dev tools.

Also, it's worth nothing the audit log accept the action :
````
2019-01-13 20:13:46,097 - Evaluating Decision for: res<name:test_project, type:project> subject<Username:admin Group:build Group:architect Group:admin Group:user Group:deploy> action<read> env<rundeck:auth:env:application:rundeck>: authorized: true: GRANTED, reason: GRANTED, evaluations:       ACLRule</etc/rundeck/admin.aclpolicy[2][type:project][rule: 1]>{'Admin, all access.' context={application='rundeck'} type='project' for: { group='admin'} allow=[*]} GRANTED for action read => GRANTED (0ms)
````
  
  
This aside, from time to time I'm able to create a job after a restart, but it I'm multi-tabbing on rundeck, when the second browser tab shows a panel with an active auto-refresh (ie, the current `Jobs` panel), the create option won't be working. And this time, the valid token error will be visible.

**My Rundeck detail**

* Rundeck version: 3.0.11
* install type: deb
* OS Name/version: Ubuntu 18.04
* DB Type/version: H2 file

**Browser detail**
Firefox 64.0.2 (win64)

**Comment by Daryes** [comment]
Additional note : when going back to 3.0.5, I got some of the jobs I tried to create appearing in the list.
On 3.0.5, I still had trouble to add new variables (sometimes the first, sometimes the second var) when creating the job, but I could add more variable when editing an existing job.  
Switching back to 3.0.11, the job is editable, but no variable can be added : same valid token error.
When creating a new job, only one variable can be added, the second variable won't be accepted.

**Comment by Daryes** [comment]
Might have a lead about this bug, and if I'm not mistaken, it's linked to this issue #4240 .  
While trying to create a new jobs, I entered a command step with this : `sudo su - user -c "" `  
Nothing between the quotes, I intended to fill it later. Added a variable, and saved the job.  

That's where the fun begins.  
Note that I never quit the job editor, still in edit mode on the same job.  
- Going back to editing the job, I can add an option, but I can't save it  
_nothing new here._
- Editing the command step, filling it with `sudo su - user -c "command 1" ` , and saving the step.
- In the job editor, the step is visible as : `1. (cmd) sudo su - user -c "command 1" ` 
- I click on it to change it, and the step editor fill the text box with the initial value :   
`sudo su - user -c "" `  
WHAT ????
- Filling it with `sudo su - user -c "commd 2" `, and saving the step.  
- In the job editor, the step is visible as : `1. (cmd) sudo su - user -c "commd 2" `  
_As expected, no problem here_
- I click on it to change it again, the step editor fill with `sudo su - user -c "" `  
AGAIN ????
- Click on cancel without any change, and now the step is visible as :  
`1. (cmd) sudo su - user -c "command 1" ` 
WHAT ???? O_o

**Comment by reinerrdeck** [comment]
Only to confirm, which java version do you have?

java -version

**Comment by reinerrdeck** [comment]
You can test adding:

rundeck.security.useHMacRequestTokens=false

On your /etc/rundeck/rundeck-config.properties file and try again.

**Comment by Daryes** [comment]
Set the setting, full rundeck restart, no change, still the error : 
````
x The request did not include a valid token, or the token has expired. Please try your request again. 
````
Which is not visible, only found thought the browser network activity in the dev tools.

I'm currently using the LDAP provider, and the following settings aside the mail config and the H2 database :
````
rundeck.api.tokens.duration.max=0

server.session.timeout=36000

rundeck.security.useHMacRequestTokens=false
````

Also, another information that might help : 
every 5 mins, a monitoring job is ran polling Rundeck API about the number of projects, existing jobs, and current executions status (running, error, ...)  
This is done using an API Token created under the admin user (hence the token duration parameter set to 0)  

By the way, while searching, I found this previous Rundeck issue : #960 which is exactly the problem I'm having.

**Comment by reinerrdeck** [comment]
To discard, please tests disabling LDAP Auth (using realm.properties authentication) and try again.

Also, you can test it using another browser like Chrome or Opera?

**Comment by Daryes** [comment]
Tried both, even with IE11, no change.

Found the problem : Rundeck is behind a reverse proxy with a ssl cert. When connecting directly to the Rundeck instance, the UI was working correctly.
Problem is, when using the reverse proxy, half the UI works as expected : I can launch jobs, halt them, view the execution log and clear them. Some things like the autorefresh are broken
Didn't have any problem before, the conf is still the same as with Rundeck v2.x

Reverse proxy config related information :
rundeck-config.properties :
````
server.useForwardHeaders=true
grails.serverURL=https://rundeck.<domain>
````

apache vhost conf (the ssl cert is in a global section)
````
Define VHOST_CONF_NAME rundeck

<VirtualHost *:80 *:8080>
        ServerName ${VHOST_CONF_NAME}.<domain>

        # mandatory https redirect
        RewriteEngine On
        RewriteRule (.*) https://%{HTTP_HOST}%{REQUEST_URI} [NE,END,R=302]
</VirtualHost>

<VirtualHost *:443 *:40443>
        ServerName ${VHOST_CONF_NAME}.<domain>

        SSLEngine on

        RewriteEngine On
        RewriteOptions Inherit

        ErrorLog "${APACHE_LOG_DIR}/${VHOST_CONF_NAME}_error.log"
        CustomLog "${APACHE_LOG_DIR}/${VHOST_CONF_NAME}_access.log" combined

        ProxyRequests Off
        ProxyPreserveHost On
        ProxyPass /server-status !
        ProxyPass "/" "http://<rundeck host>:4440/"
        ProxyPassReverse "/" "http://<rundeck host>:4440/"

</VirtualHost>

````

**Comment by Daryes** [comment]
It might be possible something is amiss, especially as there are some header insertions, but no header change is done to the proxied application. It would also help to have the headers used by Rundeck to investigate.

this aside, I've launched a job with a single command : `sleep 10m`  
and opened 2 browser pages on this job execution, one through the proxy, the other directly connected to Rundeck.  

Here are the header exchanges (first line for the connection and the exchange types)
````
direct access / Request
Host: ##server.domain##:4440
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate
Referer: http://##server.domain##:4440/project/rundeck/execution/show/6236
x-rundeck-ajax: true
X-Requested-With: XMLHttpRequest
DNT: 1
Connection: keep-alive
Cookie: rundeck.LOCALE=en_US; JSESSIONID=node011xsdac2i83677zqbtvze8pg327.node0
------------------------------------------------------------------------------------
direct access / response
HTTP/1.1 200 OK
Date: Fri, 25 Jan 2019 19:01:29 GMT
X-Application-Context: application:production:4440
Content-Type: application/json;charset=utf-8
Transfer-Encoding: chunked
````

````
reverse proxy / request
Host: ##rundeck.domain##
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:64.0) Gecko/20100101 Firefox/64.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: fr-FR,fr;q=0.8,en-US;q=0.5,en;q=0.3
Accept-Encoding: gzip, deflate, br
Referer: https:// ##rundeck.domain##/project/rundeck/execution/show/6236
x-rundeck-ajax: true
X-Requested-With: XMLHttpRequest
DNT: 1
Connection: keep-alive
Cookie: rundeck.LOCALE=en_US; JSESSIONID=node0l60c3gfroedfft36zyon3caf1.node0
------------------------------------------------------------------------------------
reverse proxy / response
HTTP/1.1 200 OK
Date: Fri, 25 Jan 2019 19:00:34 GMT
Server: Apache
X-Application-Context: application:production:4440
Content-Type: application/json;charset=utf-8
Cache-Control: max-age=2592000
Expires: Sun, 24 Feb 2019 19:00:34 GMT
Vary: Accept-Encoding,User-Agent
Content-Encoding: gzip
Strict-Transport-Security: max-age=15768000;includeSubdomains
Content-Length: 335
Keep-Alive: timeout=10, max=28
Connection: Keep-Alive
````

Also, some interesting things : 
* in the Rundeck property, `grails.serverURL=` is set to the reverse proxy DNS, and not the rundeck instance. Yet the browser page connected to the instance:port with an URL pointing directly to the execution has no problem working and refreshing automatically the page.
* the header `X-Application-Context:` is always set to  `application:production:4440` . Why the 4440 ? It's the current Rundeck instance port, but the connection is using the reverse proxy, and the same is done in Rundeck configuration.
* the 2 browser tabs  get each second an ajax response with a code 200, and some data in JSON.  
No error is returned, always a httpd code 200. Yet, the tab using the reverse proxy always get the exact same JSON data, which is not refreshed until F5 is pressed. For example, those elements will never change : `execDuration`, `updateTime` and `executionState` even 20 sec after the job is completed, while they will be updated correctly in real timeon the browser tab using the rundeck instance:port
