### ISSUE TITLE
ACL help link broken

### ISSUE THREAD

**Issue by reinerrdeck** [rundeck/rundeck#4385]
**Describe the bug**
ACL Documentation link is broken.

**My Rundeck detail**

* Rundeck version: 3.0.11
* install type: WAR
* OS Name/version: Xubuntu 18.10

**To Reproduce**
1. Go to 'Settings'
2. Click on 'Access control'
3. Click on 'Create ACL policy'
4. Click on 'Help'
5. Click on 'Access Control Policy'
4. See 404 error (broken link: https://docs.rundeck.com/docs/administration/access-control-policy.html)

**Expected behavior**
New tab on https://docs.rundeck.com/docs/administration/security/access-control-policy.html

**Additional context**
Rundeck discuss thread related: https://groups.google.com/forum/#!topic/rundeck-discuss/RcAA-SGYqhU

**Comment by aparedero** [comment]
@reinerrdeck Thanks for creating issue. next time I'll post here any issues

**Comment by ProTip** [comment]
I have fixed this particular broken link with a redirect. We will likely need to continue the discussion around wider strategy in the Docs issue.
