### ISSUE TITLE
server.session.timeout setting not working with Tomcat installation

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#4390]
server.session.timeout setting which is set in rundeck-config.properties does not work with Rundeck in Tomcat installations

**Comment by ZoeLeah** [comment]
-Dserver.session.timeout = 3600 does not work in setenv.sh either

**Comment by ZoeLeah** [comment]
Changing the value for session-timeout in the $CATALINA_HOME/conf/web.xml has solved our problem.

e.g. <session-timeout>480</session-timeout> for 8h

**Comment by gschueler** [comment]
Updated documentation: https://github.com/rundeck/docs/pull/204
