### ISSUE TITLE
Node-executor not override on inline script

### ISSUE THREAD

**Issue by jlmontes1697** [rundeck/rundeck#4392]
**Describe the bug**

When executing a remote command, it does using the variable node-executor of the node. When you execute "Script - Execute an inline script" it does not use node's node-executor variable, it uses the projects's node-executor variable, it does not use node override.

Mi project is with winrm and the projects has linux machine with node-executor=ssh.
When exec "Script - Execute an inline script" use winrm provider.

**My Rundeck detail**

* Rundeck version: [ e.g. 3.0.12]
* install type: rpm
* OS Name/version: CentOS Linux release 7.5.1804 (Core)
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**
1. Configure an project with winrm
2. Add linux server
3. Execute a job "Script - Execute an inline script"
4. See error winrm

**Expected behavior**
The variable node-executor override the project's variable

**Comment by reinerrdeck** [comment]
Did you select "dispatch to nodes" pointing to the Linux server on your job?
