### ISSUE TITLE
error to create a job

### ISSUE THREAD

**Issue by guinaum** [rundeck/rundeck#4397]
**Describe the bug**

when I create a job, in any project, the error is displayed:
An Error Occurred
Workflow is empty
Error Details 
Error 500: Internal Server Error

**My Rundeck detail**

* Rundeck 3.0.7-20181008

* install type: [choose: rpm]
* HOST: 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"

* DB Type/version: [mysql]

**To Reproduce**
1. Go to 'project'
2. Click on 'job action'
3. Click on 'new job'
4. complete the options click on "create"
5. Error: An Error Occurred
Workflow is empty
Error Details 
Error 500: Internal Server Error

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/46823363/51402773-96479100-1b35-11e9-954e-2636b376a092.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Browser [chrome, safari]

**Additional context**
Complete error
An Error Occurred
Workflow is empty
Error Details 
Error 500: Internal Server Error
URI
/project/ptl_gitlab/job/save
Class
java.lang.Exception
Message
Workflow is empty
Trace
    Line | Method
->>  140 | createExecutionItemForWorkflow in rundeck.services.ExecutionUtilService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   3636 | validateWorkflowStrategyPlugin in rundeck.services.ScheduledExecutionService
|   3440 | $tt___dovalidate . . . . . . . in     ''
|     94 | doInTransaction                in grails.gorm.transactions.GrailsTransactionTemplate$2
|    133 | execute . . . . . . . . . . .  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                        in grails.gorm.transactions.GrailsTransactionTemplate
|   3102 | $tt___dosave . . . . . . . . . in rundeck.services.ScheduledExecutionService
|     94 | doInTransaction                in grails.gorm.transactions.GrailsTransactionTemplate$2
|    133 | execute . . . . . . . . . . .  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                        in grails.gorm.transactions.GrailsTransactionTemplate
|   2562 | doCall . . . . . . . . . . . . in rundeck.controllers.ScheduledExecutionController$_save_closure82
|    272 | withForm                       in grails.artefact.Controller$Trait$Helper
|    250 | withForm . . . . . . . . . . . in     ''
|   2556 | save                           in rundeck.controllers.ScheduledExecutionController
|    223 | invoke . . . . . . . . . . . . in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke                         in org.grails.core.DefaultGrailsControllerClass
|     90 | handle . . . . . . . . . . . . in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch                     in org.springframework.web.servlet.DispatcherServlet
|    901 | doService . . . . . . . . . .  in     ''
|    970 | processRequest                 in org.springframework.web.servlet.FrameworkServlet
|    872 | doPost . . . . . . . . . . . . in     ''
|    846 | service                        in     ''
|    865 | handle . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHolder
|   1655 | doFilter                       in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    215 | doFilter . . . . . . . . . . . in org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|   1642 | doFilter                       in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | run . . . . . . . . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs                           in javax.security.auth.Subject
|    105 | doFilter . . . . . . . . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1642 | doFilter                       in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     55 | doFilterInternal . . . . . . . in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|   1642 | doFilter                       in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke                         in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter . . . . . . . . . . . in     ''
|    331 | doFilter                       in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter . . . . . . . . . . . in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter                       in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter                       in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter                       in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter                       in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run                            in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs . . . . . . . . . . . . . in javax.security.auth.Subject
|    105 | doFilter                       in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter                       in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter                       in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter                       in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter                       in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal               in org.springframework.security.web.FilterChainProxy
|    177 | doFilter . . . . . . . . . . . in     ''
|   1642 | doFilter                       in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal . . . . . . . in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|   1642 | doFilter                       in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal . . . . . . . in org.grails.web.filters.HiddenHttpMethodFilter
|   1642 | doFilter                       in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    533 | doHandle . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler
|    146 | handle                         in org.eclipse.jetty.server.handler.ScopedHandler
|    548 | handle . . . . . . . . . . . . in org.eclipse.jetty.security.SecurityHandler
|    132 | handle                         in org.eclipse.jetty.server.handler.HandlerWrapper
|    257 | nextHandle . . . . . . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1595 | doHandle                       in org.eclipse.jetty.server.session.SessionHandler
|    255 | nextHandle . . . . . . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1317 | doHandle                       in org.eclipse.jetty.server.handler.ContextHandler
|    203 | nextScope . . . . . . . . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|    473 | doScope                        in org.eclipse.jetty.servlet.ServletHandler
|   1564 | doScope . . . . . . . . . . .  in org.eclipse.jetty.server.session.SessionHandler
|    201 | nextScope                      in org.eclipse.jetty.server.handler.ScopedHandler
|   1219 | doScope . . . . . . . . . . .  in org.eclipse.jetty.server.handler.ContextHandler
|    144 | handle                         in org.eclipse.jetty.server.handler.ScopedHandler
|    132 | handle . . . . . . . . . . . . in org.eclipse.jetty.server.handler.HandlerWrapper
|    531 | handle                         in org.eclipse.jetty.server.Server
|    352 | handle . . . . . . . . . . . . in org.eclipse.jetty.server.HttpChannel
|    260 | onFillable                     in org.eclipse.jetty.server.HttpConnection
|    281 | succeeded . . . . . . . . . .  in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    102 | fillable                       in org.eclipse.jetty.io.FillInterest
|    118 | run . . . . . . . . . . . . .  in org.eclipse.jetty.io.ChannelEndPoint$2
|    333 | runTask                        in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    310 | doProduce . . . . . . . . . .  in     ''
|    168 | tryProduce                     in     ''
|    126 | run . . . . . . . . . . . . .  in     ''
|    366 | run                            in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    762 | runJob . . . . . . . . . . . . in org.eclipse.jetty.util.thread.QueuedThreadPool
|    680 | run                            in org.eclipse.jetty.util.thread.QueuedThreadPool$2
^    748 | run . . . . . . . . . . . . .  in java.lang.Thread

**Comment by gschueler** [comment]
This was fixed https://github.com/rundeck/rundeck/issues/4026
Please try using Rundeck 3.0.8.  If this remains a problem, please reopen the issue.
