### ISSUE TITLE
Problem with SCM Plugin

### ISSUE THREAD

**Issue by csimader** [rundeck/rundeck#4399]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [e.g. ubuntu 16.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**
1. Enable SCM Plugin (Git Import/ Git Export)
2. Restart rundeck
3. SCM Plugin is disabled again

**Expected behavior**
We have enabled the SCM Plugin for local Git if we restart rundeck service the plugin is not enabled automatically.

**Desktop (please complete the following information):**
 - OS: Linux 4.1.12-94.3.9.el7uek.x86_64
 - chrome,
 - 3.0.11

**Additional context**
Is this a normal behavior that the SCM plugin is disabled after restart? Is there a config to enabled plugins automatically?
Thanks for any answer / recommendation

**Comment by jtobard** [comment]
This is not the expected behavior, but it can happen if there is an error when activating the plugin, do you have any error log when you start the service?

**Comment by csimader** [comment]
You are right there is a error like this;
rundeck.services.ScmService              : Failed to initialize SCM export plugin git-export for 1-Scheduler-Prod: Failed fetch from the repository: Path does not exist: keys/rundeckgit
INFO   | jvm 1    | 2019/01/21 15:17:19 |
INFO   | jvm 1    | 2019/01/21 15:17:19 | com.dtolabs.rundeck.plugins.scm.ScmPluginException: Failed fetch from the repository: Path does not exist: keys/rundeckgit
but in the file exists - it's shown in the ; if we enable the scm plugin it works without errors;
![image](https://user-images.githubusercontent.com/8567019/51479987-254fe580-1d90-11e9-8854-1320b0aa1868.png)

**Comment by csimader** [comment]
the projects are imported not created from scratch;
found if we choose the key in the configuration again the SCM plugin works as expacted - 
so just import is not engough? 
Workaround would be to touch each project and choose the key again will take a while we have over 60projects...

**Comment by csimader** [comment]
our issue is solved with our workaround by touching all our projects;
Analyze show this was since we add ACL's to the probjects and this has a site effect to our SCM configuration;
User has both roles admin and users and the user role is not allowed to read keys/storage by this deny rundeck is not able to read our key;
Solution: Remove user role from user, touch each project and reconfig the SCM Plugin
