### ISSUE TITLE
Rundeck jobs fails inside of rundeck, but runs successfully via CLI as rundeck user

### ISSUE THREAD

**Issue by refriedjello** [rundeck/rundeck#4401]
**Describe the bug**
Running a job from the Rundeck WebUI fails, but when running the same commands from the CLI as the rundeck user, it succeeds.

Rundeck job is is dispatched to localhost, calling an ansible playbook, that runs a docker module "docker_image_facts". Docker server (CE) is installed locally (same host as rundeck).

**My Rundeck detail**

Rundeck version: 3.0.11-20181221
* install type: RPM
* OS Name/version: CentOS 7.6.1810
* DB Type/version: H2

**Playbook detail**

Running with or without the "become" commands did not change outcome.

```
---
- hosts: $(servername)
  strategy: debug
  connection: local
  become: yes
  become_user: rundeck
  tasks:
    - name: Inspect a single image
      docker_image_facts:
        name: $(container_name)
        debug: yes
```

**Expected behavior**
Job returns zero error code, and lists details about the named container

**Error detail**

Error connecting: Error while fetching server API version: ('Connection aborted.', error(13, 'Permission denied'))

**Job run details**

(see attached)

**Additional context**
Running the procArgs manually from CLI works fine w/o issue. Ran while logged in as "rundeck" user, with sudo, and as my user account. My account and the rundeck account are members of the "docker" usergroup.
[rundeck-docker-error.txt](https://github.com/rundeck/rundeck/files/2780864/rundeck-docker-error.txt)

**Comment by refriedjello** [comment]
I solved this problem. Issue was that I did not reboot my VM running Rundeck/Docker after adjusting group memberships, as noted in the post-install instructions (oops!).

https://docs.docker.com/install/linux/linux-postinstall/

Is someone able to shed some light on why this happened? Rundeck daemon started before the rundeck user was added to the docker group, so it didn't get the proper group permissions? A bit curious why per those instructions it seems like an issue related to just VMs, and not bare-metal servers.

**Comment by ProTip** [comment]
That is curious; I'm not aware of anything particular about VMs that would require a reboot...

Generally speaking, supplemental group membership does not get re-evaluated for running processes so they must be restarted for that to take effect. It most cases restarting the session/process should suffice.
