### ISSUE TITLE
Using wildcards for implementing ACLs for Jobs

### ISSUE THREAD

**Issue by docbyte86** [rundeck/rundeck#4410]
Hello all,

we have Rundeck 3.0.12-20190114 installed on our system and are working with different user groups. We have to define specific ACLs for accessing Jobs in different job groups. The only option we currently have is to enter the ACL code, as follows:

for:
  job:
    - match:
        name: 'JobGroupA Jobname 1'
      allow: [view,run]
    - match:
        name: 'JobGroupA Jobname 2'
      allow: [view,run]
    - match:
        name: 'JobGroupB Jobname 1'
      allow: [view,run]
    - match:
        name: 'JobGroupB Jobname 2'
      allow: [view,run]
    - match:
        name: 'JobGroupC Jobname 5'
      allow: [view,run]

The maintaining of those ACLs costs a lot of efforts and the overview is quite difficult.

It would be useful if it will be possible to use wildcards or "contains" instead of match/equal, as for tags.
The use of

**Comment by gschueler** [comment]
the `match:` comparison does a regular expression match, so you can include wildcards, see the [Type Rules section of the  ACLPOLICY documentation](https://docs.rundeck.com/docs/man5/aclpolicy.html#type-rules)

Also if you want to check the job group you need to use the `group:` entry instead of `name:`

**Comment by docbyte86** [comment]
Hello,

Thanks for your reply.

We have a job named "Infotext Generator". Access by using following ACL:

for:
  job:
    - match:
        name: 'Infotext Generator'
      allow: [view,run]

But how to grand access to all Jobs, beginning with "Infotext" ? How wildcards will be used?

**Comment by reinerrdeck** [comment]
The best way is grouping your jobs in groups and use `group:` entry in your ACL.
