### ISSUE TITLE
bulk delete selection for executions issue

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#4416]
When performing a bulk delete for executions, clicking on select all in the first page, and then navigating to the second page, on the second page it's not possible to select more executions.

Also, when returning back to the first page, the selection is still active, but when clicking on delete it does not delete the selection anymore.

Tested on Rundeck Pro 3.0.12 any installation any OS.

**Comment by jessemarple** [comment]
Reviewed Jan 23 2019

**Comment by carlosrfranco** [comment]
PR already merged on 18 Apr
https://github.com/rundeck/rundeck/pull/4673
