### ISSUE TITLE
Bulk delete doesn't check for references

### ISSUE THREAD

**Issue by rlueckl** [rundeck/rundeck#4418]
**Describe the bug**
When trying to delete a job from the "Jobs" page (`/project/$PROJECTNAME/jobs`) Rundeck doesn't check for job references. Clicking on the job, then deleting checks for references (`/project/$PROJECTNAME/job/show/$UUID`).

See also issue #257 and merge #3115.

**My Rundeck detail**

* Rundeck version: Rundeck 3.0.12-20190114
* install type: deb
* OS Name/version: Debian Stretch 9.6
* DB Type/version: postgres

**To Reproduce**
Steps to reproduce the behavior (see first screenshot):
1. Create two jobs. Reference the first job in the second as node step.
2. Click on "Jobs"
3. Click on the arrow ("Click for Job Actions") of the first (referenced) job
4. Click on "Delete this Job"
5. Popup "Confirm Bulk Job Modification" appears asking for confirmation, but **no references** listed!

Result: all other jobs referencing the deleted job(s) become broken.

**Expected behavior**
Same behavior expected as in the following workflow (see second screenshot):
1. Create two jobs. Reference the first job in the second as node step.
2. Click on "Jobs"
3. Click on the name of the first job
4. Click on the hamburger icon on the right side
5. Click on "Delete this Job"
4. Popup "Really delete this Job?" appears asking for confirmation, listing all references to this job.

**Screenshots**
![delete_bulk](https://user-images.githubusercontent.com/10848041/51675867-3c334980-1fd5-11e9-97c7-eddbb40985b9.png)

![delete_single](https://user-images.githubusercontent.com/10848041/51675866-3b9ab300-1fd5-11e9-986d-d5ea2d2172fb.png)

**Comment by reinerrdeck** [comment]
Confirmed, using 3.0.12.

**Comment by rlueckl** [comment]
Any news?
