### ISSUE TITLE
ZipException when deploying 3.x WAR in Tomcat

### ISSUE THREAD

**Issue by kristian-lesko** [rundeck/rundeck#4420]
**Describe the bug**
When deploying a Rundeck 3.x WAR to Tomcat, the following exception happens:
`2019-01-24 14:31:41.577  WARN --- [ost-startStop-1] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is java.security.PrivilegedActionException: java.util.zip.ZipException: zip file is empty`

**My Rundeck detail**

* Rundeck version: 3.0.13 (happens on 3.0.1 & 3.0.9 as well)
* install type: WAR (in Tomcat)
* OS Name/version: CentOS 7
* DB Type/version: Postgres (happens with default DB config as well)

**To Reproduce**
1. Install _tomcat_.
2. Download the installation `.war` file into Tomcat `webapps` directory.
3. (Optional) Unpack the `.war` into a folder; however, Tomcat itself does this
4. Run Tomcat.

**Expected behavior**
Tomcat should start without errors.

**Desktop**
Irrelevant; UI cannot be accessed because application does not start correctly.

**Additional context**
The issue happened for me both when upgrading from Rundeck 2.11 (which worked without issues) and when trying to deploy the new Rundeck 3 from scratch. 
Perhaps the error message is misleading and means something else, but I wasn't able to find any `.zip` file in the installation that would be obviously empty or bad. Also, sometimes the message altered to `java.util.zip.ZipException: error in opening zip file`. I wasn't able to find any mention of filename of the zip that failed to open, though.

**Comment by sjrd218** [comment]
@kristian-lesko  The most probable cause of this issue is that the rdeck.base location is not writable by the tomcat user process. Please make sure that you have launched tomcat with the -Drdeck.base system property set to a location on your file system to which the tomcat user has full access.

**Comment by bsloeserwij** [comment]
I have the same issue. 
My rdeck.base is owned by the tomcat user, has permissions 777 (for testing only) and selinux is disabled. This issue still appears.

**Comment by kristian-lesko** [comment]
@sjrd218 many thanks for your response.

I was actually deploying a tomcat war that was not owned by `tomcat`; however, it seemed to be unpacked to a subdirectory without issues. Even after setting its owner to tomcat, I still get the exact same "zip file is empty" exception.

The owner of the rdeck.base directory was owned by tomcat all along; it worked without any changes with the 2.11.8 version.

**Comment by sjrd218** [comment]
@kristian-lesko Looks like Tomcat is doing something unexpected with the first run initialization code. You can manually run the install process like this: `java -Drdeck.base=/path/to/rundeck/base -jar rundeck.war --installonly` Once you have the rdeck.base directory exploded, you should be able to start Tomcat and get Rundeck going. You'll need to disable selinux as well because it prevents the system from correctly initializing and running Rundeck.
