### ISSUE TITLE
cannot open git-upload-pack

### ISSUE THREAD

**Issue by ZoeLeah** [rundeck/rundeck#4426]
**Describe the bug**
Error Message: Failed cloning the repository from https://<HOST>/<REPO>.git/: https://<HOST>/<REPO>.git/: cannot open git-upload-pack 

**My Rundeck detail**

* Rundeck version: 3.0.12-20190114
* install type: war
* OS Name/version: RHEL 7.6
* DB Type/version: oracle

**To Reproduce**
1. Go to 'Setup SCM Plugin: Git Export'
2. Enter 'https://<HOST>/<REPO>.git' on Git URL
3. Setup

**Expected behavior**
A successful configuration.

**Comment by FedeHAL** [comment]
If you are behind a proxy, try setting it into de java command to start rundeck:
