### ISSUE TITLE
A comma character in the `nodename` field of a RESOURCE-JSON causes node to be skipped during jobs

### ISSUE THREAD

**Issue by McNutnut** [rundeck/rundeck#4428]
**Describe the bug**
Nodes with commas in the `nodename` field of a RESOURCE-JSON file are skipped during job execution.

**My Rundeck detail**

* Rundeck version: 3.0.13-20190123 
* install type: rpm
* OS Name/version: CentOS 7.6
* DB Type/version: H2

**To Reproduce**
1. Fresh install
2. Create a RESOURCE-JSON file locally on the Rundeck server (/etc/rundeck/nodes.json for example) with the following contents: [nodes-json.txt](https://github.com/rundeck/rundeck/files/2798454/nodes-json.txt)
3. Create a new project (Projects -> New Project)
4. Add a File Node Source to the project (Project Settings -> Edit Notes... -> Configure Nodes -> Add Source -> File) pointing it to your created file from step 2
5. [Create a job](https://github.com/rundeck/rundeck/files/2798458/Test_Job-xml.txt) that has a single Local Command step which runs a simple `echo Running for ${node.name}` command to print out the node name
6. Run the job against both of the two included nodes
7. Job with a comma in the nodename is skipped/ignored

**Expected behavior**
Nodes selected for execution should not be skipped

**Screenshots**
Job preparing to run:
![runningjob](https://user-images.githubusercontent.com/16924607/51780987-39655100-20c8-11e9-8268-e48df5262a40.PNG)

Job executed:
![jobrun](https://user-images.githubusercontent.com/16924607/51780983-31a5ac80-20c8-11e9-8dc8-3b8f0e49af0f.PNG)

Notice that "Test Node, Comma Name" is missing from execution

**Desktop (please complete the following information):**
 - OS: Windows 10 Build 1803
 - Browser: Firefox

 - Version: 64.0.2

**Comment by gschueler** [comment]
Comma character in node names needs to be either escaped properly or disallowed

workaround for now is to not use a comma in the node name
