### ISSUE TITLE
URL Source node does't work using GitHub

### ISSUE THREAD

**Issue by reinerrdeck** [rundeck/rundeck#4429]
**Describe the bug**

Following this: 

https://docs.rundeck.com/docs/administration/projects/resource-model-sources/built-in-plugins-file-directory-url-script.html#url-source

The URL Source node definition doesn't work using GitHub to storage node definition.

**My Rundeck detail**

* Rundeck version: 3.0.13
* install type: WAR
* OS Name/version: Xubuntu 18.10
* DB Type/version: h2

**To Reproduce**
1. Create a new project.
2. Go to "Project Settings" > "Edit Nodes"
3. Add new URL Source with Github URL like: https://raw.githubusercontent.com/myuser/repository/master/resources.xml (tested using wget)
4. Save.
5. The nodes do not appear in the project even full rundeck restart.

**Expected behavior**
Show the nodes defined in the XML file on Github.

**Notes**
- service.log doesn't show anything about this.
- I tested using web server and works, but not using GitHub.

**Comment by ahonor** [comment]
Also take a look at https://github.com/rundeck-plugins/git-plugin

**Comment by reinerrdeck** [comment]
Works like a charm! Thanks!!
