### ISSUE TITLE
Very large Rundeck.audit.log

### ISSUE THREAD

**Issue by luisrivas35** [rundeck/rundeck#4435]
**My Rundeck detail**
Rundeck version: 3.0.11
Install type: N/A
OS Name/version: Linux
DB Type/version: MySql

**To Reproduce**
Create a new project.
Go to "Rundeck.audit.log" file located on $RDECK_BASE/server/log/rundeck.audit.log

**Please describe.**
This audit.log file is supposed to keep all ACL authorizations movements for the Rundeck server, but the amount of information is too much.

**Describe the solution you'd like**
It could be to have the options to:
- the only audit rejected actions
- only audit specific kind of events (let the customer manage kind of white-list)

**Comment by gschueler** [comment]
Two issues:

1. Fix a possible issue where audit checks are logged twice (due to system vs project level checks)
2. Improve granularity of audit logs, and if possible configuration via log4j
