### ISSUE TITLE
change rundeck-config property

### ISSUE THREAD

**Issue by ibaboo** [rundeck/rundeck#4437]
Hi

I am testing you docker image which is great. I would like to know if it is possible to change configs in rundeck-config via a docker environment variable?

For now I am trying to change "rundeck.projectsStorageType=db"
to rundeck.projectsStorageType=filesystem

Any suggestions ? I want to avoid building a new docker image

**Comment by cedrico2016** [comment]
Hi @ibaboo , 
i did something similar in one of my projects. 
you can achieve that in a littlte bit tricky way. That means you define your env variables as you want. in the rundeck-config you can set "random" values to the target properties. 
After that you should have to modify a little bit the run script of the docker image, to set those variables with the "sed" command.

1-  Define somethnig like this in your properties file : ``` rundeck.projectsStorageType=DB_VAL``` 
2 - Define your env variable in the dockerfile or where ever you shoul like :  DB_VAL=filesystem  
3- Modify the  /etc/init.d/run script, before the  rundeck daemon is started, and add a like like : 
``` sed -i "s~DB_VAL~$DB_VAL~g" /etc/rundeck/jaas-ldap.conf ```  
Regards,

**Comment by ProTip** [comment]
Hello @ibaboo ,

There is an undocumented environment variable that can set that: `RUNDECK_PROJECTSSTORAGETYPE`.

Here is where it gets rendered from the template: https://github.com/rundeck/rundeck/blob/master/docker/official/remco/templates/rundeck-config-storage.properties#L51

Be aware though that unless docker volumes are used the data will be lost if/when the container is stopped. Please post help requests and usage questions to the rundeck-discuss mailing list http://groups.google.com/group/rundeck-discuss, thank you!

**Comment by ibaboo** [comment]
@cedrico2016  thanks.
@ProTip  thank you for the info. I will use the mailing list in future for these sort of questions  as i am sure I will have many more :)
