### ISSUE TITLE
Use JAAS authentication (LDAP) together with the Preauthenticated Mode

### ISSUE THREAD

**Issue by cedrico2016** [rundeck/rundeck#4438]
Currently when the JaaS authentication (e.g with LDAP in our case) is enabled together with the preauthenticated mode, only the preautheticated mode is considered and the JaaS module is ignored. 
In our case, we are using the LDAP JaaS module because of the possibilty of the synchronaization with the LDAP Server. As our users are logging in through HTTP Header Forwarding, we are not taking advantage at all of our LDAP Server. 

Such a feature will be very interessting because it should be possible to have the preauthenticated taking advantage in the same time of the synchronization with the LDAP Server.

**Comment by reinerrdeck** [comment]
Hi!

If you configure Rundeck against LDAP Server and set your Apache/NGINX to send X-Forwarded-Uuid and X-Forwarded-Roles HTTP headers with some valid LDAP user/role, Rundeck takes the LDAP user profile (pre-authentication using LDAP).

I did reproduce using NGINX, in nginx.conf (location section):

```    
        location /rundeck {
            # http headers for pre-authenticated mode
            proxy_set_header X-Forwarded-Uuid YourLDAPuser;
            proxy_set_header X-Forwarded-Roles admin,users; # LDAP user rol.

            # real rundeck location
    	    proxy_pass http://localhost:4440/;
        }
```

In rundeck-config.properties i added this:

```
# preauthenticaded mode
rundeck.security.authorization.preauthenticated.enabled=true
rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
rundeck.security.authorization.preauthenticated.delimiter=,
rundeck.security.authorization.preauthenticated.userNameHeader=X-Forwarded-Uuid
rundeck.security.authorization.preauthenticated.userRolesHeader=X-Forwarded-Roles
```

Hope it helps!

**Comment by reinerrdeck** [comment]
Hi, 

Right now only I did log in, we follow up the request here:

https://github.com/rundeck/rundeck/issues/946
