### ISSUE TITLE
AttachLogInline notification plugin

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4440]
Rundeck 3.0.13 added "email notification enhancement" functionality which linked to [code pull](https://github.com/rundeck/rundeck/pull/4365/files/ece504ee637e9c2ce75d85758ef261b92a0dbfff#diff-7c0af42b7418a4cfa6558c80b306ec26)

Although, when testing this functionality, I am unable to get it to work. I have custom email templates enabled for this job and have tried these variables:
```
${attachLogInline} 
${execution.attachLogInline}
```

Is there a different variable format? I don't see any documentation on this.

**Comment by gschueler** [comment]
did you try `${logoutput.data}`?

**Comment by gschueler** [comment]
@ltamaster can you add documentation for this feature to https://github.com/rundeck/docs

**Comment by gtsteffaniak** [comment]
@gschueler 

That's it. Worked perfectly. Thank you.

**Comment by gtsteffaniak** [comment]
@gschueler @reinerrdeck 

One slight enhancement recommendation:
`${logoutput.data}` should be set to blank/null if it is not chosen in the rundeck UI. Because we use the same email templates regardless of how the logout is set and seeing "${logoutput.data}" in the email when we did not choose to attach it is confusing.

example 
![image](https://user-images.githubusercontent.com/42989099/52067477-435fd780-2540-11e9-9e0a-d4cd69929c3e.png)

**Comment by gtsteffaniak** [comment]
@gschueler Great, thanks for checking this. Perhaps it would be better to have a "default" value for ${logoutput.data}, which would get replaced if there is data. That way the user could even set the default value to their preference.
