### ISSUE TITLE
Slow job execution [Race condition workaround - Thread.sleep 2s]

### ISSUE THREAD

**Issue by jbguerraz** [rundeck/rundeck#4456]
**Describe the bug**
Job executions are taking 2 seconds (instead of 90ms for the very first execution).
https://github.com/rundeck/rundeck/commit/c91d7e0b92fbbe8f716717223c8ed6f5f0bc2c6a forces Rundeck to wait for 2 seconds if somehow the execution was not found (in our case, after very first executions, it systematically waits for 2 seconds, retries, gets the data, and finally, moves ahead).
~Instead of a sleep, a lock mechanism would probably helps to wait the very minimum of time.~ 

**My Rundeck detail**

* Rundeck version: 3.0.13
* install type: war
* OS Name/version: alpine linux (k8s)
* DB Type/version: postgres

**To Reproduce**
1. ~Get a _slow_ datasource (or, somehow, delay the writes) :)~ use postgres (probably other db as well) => we use a docker container with official postgres image to reproduce the issue
2. Import job https://gist.github.com/jbguerraz/c88dfa1a4254c1709ba6e29bb15e1fd4#file-gistfile1-txt
3. Run the job ~few~ several (tons of) times (actually, ` watch -n 0.1 "curl -X POST  http://localhost:4440/api/16/job/the-job-id/executions\?authtoken\=thetoken"` is very good at reproducing the issue)
4. See the 2 seconds duration for some of the job executions

**Expected behavior**
The execution won't be blocked for 2 seconds (* needed retries) but instead will wait for the execution to be available for reading.

**Comment by jbguerraz** [comment]
( related to #193 #190 )

**Comment by jbguerraz** [comment]
We started today to tackle that one. Hopefully we will have something by tomorrow.

**Comment by jbguerraz** [comment]
Actually it's not a race condition between "write" and "read"  ("read" - `get()` - is always executed after "write"  - `save()`).
The issue lives in the Hibernate usage. The `save(flush:true)` actually doesn't makes the data available to another transaction as said here https://github.com/grails/grails-core/issues/10836#issuecomment-338644612 
We first implemented a locking mechanism; it helped since there is no more sleep. We moved from a **30 seconds pipeline (about 14 jobs) to a 1.4 second pipeline!!!** , but, this locking stuff is not a proper fix (at the end, it's doing nothing more than a smaller sleep actually).

**Comment by jbguerraz** [comment]
For the record, reproduced with MySQL 8 but not with MySQL 5.7

**Comment by jbguerraz** [comment]
After discussing it with Hibernate community, it sounds like that issue is related to the way Hibernate is used by Rundeck more than an Hibernate/Oracle(/Postgres/MySQL 8) bug.

Since MySQL 5.7 saved our performances, for now, this issue is of less importance on our side

**Comment by jbguerraz** [comment]
FTR: actually, MySQL 5.7 also fall into this execution not found case, but pretty rarely (8 times over about 3000 executions)

**Comment by gschueler** [comment]
Another method might be: use "gorm events" to listen to the `afterInsert` event for Execution objects with a central bean. the ExecutionJob would query that bean if the execution is not found, and give it a handler to trigger it to proceed when the event is received (or immediately if it was already received)

**Comment by jbguerraz** [comment]
:+1:  thank you @carlosrfranco !
