### ISSUE TITLE
Framework logs never get rotated

### ISSUE THREAD

**Issue by camaer** [rundeck/rundeck#4467]
**Describe the bug**
The log dir under '/var/lib/rundeck/logs' from the framework logs never gets rotated or cleaned up which fills the disk.

**My Rundeck detail**

* Rundeck version: [3.0.5-20180828]
* install type: [deb]
* OS Name/version: [ubuntu 16.04]
* DB Type/version: [mysql]

**Expected behavior**
Maybe a way to remove old logs past X date like log4j.properties is doing.
Can they be cleaned manually without impact ?

Thanks

**Comment by reinerrdeck** [comment]
Meanwhile you can use logrotate like this https://github.com/rundeck/rundeck/issues/866#issuecomment-369515396

Logrotate Reference: https://www.thegeekstuff.com/2010/07/logrotate-examples/

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
