### ISSUE TITLE
Add "Retry Passed Nodes" option similar to Retry Failed Nodes

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#4473]
It would be great to have an option to Retry Passed Nodes..

![image](https://user-images.githubusercontent.com/20629911/52497452-f8bb0c80-2b8a-11e9-87c9-06c1dc90f75e.png)

Thank you!

**Comment by ahonor** [comment]
@hs-hub-world interesting. Would you mind giving a use case as an example?

**Comment by hs-hub-world** [comment]
Of course.
Some times we might scan for machines for particular file/process/attribute/etc.. and for those that failed because either Winrm was not configured or Powershell script simply failed, or the file/process was not found, etc..  but the script did succeeded on the some we would love to zoom in on the passed machines and run additional/other scripts to save time without hitting all the other/failed machines. Hope that makes sense.

**Comment by gschueler** [comment]
@hs-hub-world do you mean you want to retry only on the successful nodes?

**Comment by hs-hub-world** [comment]
Hi @gschueler.  Yes, that's correct. we should have the option to retry only on "successfully" machines.  For example, we might search for nodes that are running a specific process, once identified then we want to concentrate only on those nodes, the failed nodes should be ignored.
