### ISSUE TITLE
Ad-Hoc commands portability (Problems with quotes)

### ISSUE THREAD

**Issue by daviddaal74** [rundeck/rundeck#4478]
**Describe the bug**
Some Ad-Hoc commands run correctly as a "script step", but when copying the same command and trying to execute it as a "command step" or in the "Ad-Hoc Commands" tab it does not run and throws errors due to the quotes, so the command must be modified in order to run properly. This prevents commands from being portable causing re-work, confusion, and resistance to using the platform.

**My Rundeck detail**

* Rundeck version: 2.4.4 PRO CLUSTER
* install type: Mixed
* OS Name/version: RHEL 7
* DB Type/version: MariaDB

**To Reproduce**

1.- Run next command as "Command step"
sed -i '/\[mysqld\]/a datadir=/data/mariadb' /tmp/server.cnf

2.- Run same command as "script step"
#! /bin/bash
sed -i '/\[mysqld\]/a datadir=/data/mariadb' /tmp/server.cnf

3.- When run as Script step it runs successfully, when run as Command step it throws following error
sed: -e expression #1, char 11: expected \ after `a', `c' or `i'

4.- The Ad-Hoc command must be modified (adding additional quotes) in order to run properly as "Command step"

**Expected behavior**
The Ad-Hoc command should run as Command Step and Script Step without modifications, so Ad-Hoc commands can be portable

**Screenshots**

![ad-hoc](https://user-images.githubusercontent.com/36861296/52537358-ba694d00-2d44-11e9-89aa-85d038a85ee2.jpg)

**Comment by gschueler** [comment]
related #602
