### ISSUE TITLE
API version 18 above not working 

### ISSUE THREAD

**Issue by happicamper** [rundeck/rundeck#4480]
**Describe the bug**
Using a call via cURL to run a job with a parameter "/api/18/" the command returns with an error: 
`{"timestamp":1549855717796,"status":405,"error":"Method Not Allowed","message":"Method Not Allowed","path":"/api/18/job/9b7bc48f-62d5-4452-998e-cfe8292a95f1/run"}%`
However, when using /api/1-13 it works but I wanted to use the features on api version 18.

**My Rundeck detail**

* Rundeck version: [3.0.13]
* install type: [yum]
* OS Name/version: [centos 7]
* DB Type/version: [mysql]

**To Reproduce**
1. Curl command to run a job with /api/18 and above

**Expected behavior**
It should execute successfully like when using /api/2/

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacSierra]
 - Browser [Chrome]
 - Version [71]

**Additional context**

**Comment by sjrd218** [comment]
API versions > 13 require that particular call to be a POST. If you add -XPOST to your curl command it will work.

**Comment by happicamper** [comment]
@sjrd218 ah yeah found out that works! Thank you.
