### ISSUE TITLE
Rundeck SCM Export/Import setup fails with cryptic "null" message

### ISSUE THREAD

**Issue by damageboy** [rundeck/rundeck#4483]
**Describe the bug**
When I (re-)setup Git SCM Export or Import on version 3, I get the following error:

![image](https://user-images.githubusercontent.com/125730/52573434-d3483000-2e22-11e9-9926-c5be242b1ec4.png)

 Failed fetch from the repository: null 

There is no other visible log message from Rundeck on the sevice.log file or anywhere else on /var/log/rundeck

**My Rundeck detail**

* Rundeck version: 3.0.13
* install type: deb
* OS Name/version: ubuntu 18.04
* DB Type/version: mysql

**To Reproduce**
1. Go to project
2. Click on Setup Git Export/Import
3. Punch in working credentials

**Expected behavior**
Should work or report 

**Screenshots**

![image](https://user-images.githubusercontent.com/125730/52573434-d3483000-2e22-11e9-9926-c5be242b1ec4.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version 65

**Additional context**
The same git credential work from command line as the rundeck user using the same .ssh public key

**Comment by jtobard** [comment]
@damageboy can you paste more information about your setup in order to reproduce it. 
I'll like to improve that message if we can see where it happens.

**Comment by damageboy** [comment]
Sure.. anything specific?

**Comment by jtobard** [comment]
@damageboy A screenshot of the SCM setup page could work to try to reproduce it.

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
