### ISSUE TITLE
Timezone in execution log output

### ISSUE THREAD

**Issue by tintranvan** [rundeck/rundeck#4486]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: 2.11.5
* install type: rpm
* OS Name/version: Ubuntu 16.04
* DB Type/version: MariaDB

**To Reproduce**

We did notice that we have different time when we compare the log output time of the node (at the start of the log line) with the downloaded log output (txt file).
We attached some screenshots.
We did check the time / time zone configurations on all our VMs and rundeck docker containers. Everything looks good so far. So we have no idea why this is happening.
This is problem is not job specific or rundeck specific. We did notice it on all our rundeck instances with all the job log outputs.

**Screenshots**

<img width="933" alt="1 - copy" src="https://user-images.githubusercontent.com/44957667/52758607-868b7180-303b-11e9-958b-af8914cbda5d.PNG">

<img width="940" alt="3" src="https://user-images.githubusercontent.com/44957667/52758579-6eb3ed80-303b-11e9-9d5b-c60e53fddbb4.PNG">

<img width="907" alt="2" src="https://user-images.githubusercontent.com/44957667/52758584-72477480-303b-11e9-8523-06f99f052a67.PNG">

**Comment by reinerrdeck** [comment]
Issue confirmed under 3.0.13 with H2 and PostgreSQL.

**Comment by reinerrdeck** [comment]
Related:

https://groups.google.com/forum/#!topic/rundeck-discuss/mS3PMB3ezFE

https://groups.google.com/forum/#!topic/rundeck-discuss/5VJoKsY8i3E

**Comment by squirrelchew** [comment]
same issue in 3.0.20, activity history vs current-running.
project/<project>/execution/show/<run_nr> is the page to see this:

![image](https://user-images.githubusercontent.com/32274759/56814009-cf159700-6803-11e9-9f7f-4f44f9800b49.png)

some times are listed in server time, UTC, and other are listed in America/Chicago, which is my local machine time.  Nowhere on the server is America/Chicago configured.
