### ISSUE TITLE
Error 500: Internal Server Error

### ISSUE THREAD

**Issue by jesusUABC97** [rundeck/rundeck#4490]
Describe the bug
Trying to run any job with any kind of step or configuration causes the same error
"javax.servlet.ServletException"

Says its caused by the following
"Could not resolve view with name 'downloadOutput' in servlet with name 'grailsDispatcherServlet'"

**My Rundeck detail**

Rundeck version: 3.0.13-20190123
install type: rpm
OS Name/version: CentOS 7

**To Reproduce**
1. Go to Jobs
2. Create any job
3. Add any kind of step
4. Run error
5. Run job

This is the whole trace generated by the error

` Line | Method
->>  108 | doFilter         in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     55 | doFilterInternal in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     -1 | call             in javax.servlet.FilterChain$doFilter
|     67 | doFilterInternal in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    111 | doFilterInternal in org.springframework.boot.actuate.trace.WebRequestTraceFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke           in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter . . . . in     ''
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter . . . . in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter         in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilterInternal in grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter . . . . in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter . . . . in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter . . . . in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|     -2 | doPrivileged     in java.security.AccessController
|    422 | doAs . . . . . . in javax.security.auth.Subject
|    105 | doFilter         in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter         in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter         in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter         in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter         in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal in org.springframework.security.web.FilterChainProxy
|    177 | doFilter . . . . in     ''
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal in org.grails.web.filters.HiddenHttpMethodFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    197 | doFilterInternal in org.springframework.web.filter.CharacterEncodingFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | doFilterInternal in org.springframework.web.filter.CorsFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    103 | doFilterInternal in org.springframework.boot.actuate.autoconfigure.MetricsFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    533 | doHandle         in org.eclipse.jetty.servlet.ServletHandler
|    146 | handle . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|    548 | handle           in org.eclipse.jetty.security.SecurityHandler
|    132 | handle . . . . . in org.eclipse.jetty.server.handler.HandlerWrapper
|    257 | nextHandle       in org.eclipse.jetty.server.handler.ScopedHandler
|   1595 | doHandle . . . . in org.eclipse.jetty.server.session.SessionHandler
|    255 | nextHandle       in org.eclipse.jetty.server.handler.ScopedHandler
|   1317 | doHandle . . . . in org.eclipse.jetty.server.handler.ContextHandler
|    203 | nextScope        in org.eclipse.jetty.server.handler.ScopedHandler
|    473 | doScope . . . .  in org.eclipse.jetty.servlet.ServletHandler
|   1564 | doScope          in org.eclipse.jetty.server.session.SessionHandler
|    201 | nextScope . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|   1219 | doScope          in org.eclipse.jetty.server.handler.ContextHandler
|    144 | handle . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|    132 | handle           in org.eclipse.jetty.server.handler.HandlerWrapper
|    531 | handle . . . . . in org.eclipse.jetty.server.Server
|    352 | handle           in org.eclipse.jetty.server.HttpChannel
|    260 | onFillable . . . in org.eclipse.jetty.server.HttpConnection
|    281 | succeeded        in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    102 | fillable . . . . in org.eclipse.jetty.io.FillInterest
|    118 | run              in org.eclipse.jetty.io.ChannelEndPoint$2
|    333 | runTask . . . .  in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    310 | doProduce        in     ''
|    168 | tryProduce . . . in     ''
|    126 | run              in     ''
|    366 | run . . . . . .  in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    762 | runJob           in org.eclipse.jetty.util.thread.QueuedThreadPool
|    680 | run . . . . . .  in org.eclipse.jetty.util.thread.QueuedThreadPool$2
^    748 | run              in java.lang.Thread

Caused by PrivilegedActionException: null
->>   -2 | doPrivileged     in java.security.AccessController
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    422 | doAs             in javax.security.auth.Subject
|    105 | doFilter . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     55 | doFilterInternal in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     -1 | call             in javax.servlet.FilterChain$doFilter
|     67 | doFilterInternal in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    111 | doFilterInternal in org.springframework.boot.actuate.trace.WebRequestTraceFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke           in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter . . . . in     ''
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter . . . . in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter         in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilterInternal in grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter . . . . in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter . . . . in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter . . . . in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|     -2 | doPrivileged     in java.security.AccessController
|    422 | doAs . . . . . . in javax.security.auth.Subject
|    105 | doFilter         in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter         in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter         in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter         in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter         in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal in org.springframework.security.web.FilterChainProxy
|    177 | doFilter . . . . in     ''
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal in org.grails.web.filters.HiddenHttpMethodFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    197 | doFilterInternal in org.springframework.web.filter.CharacterEncodingFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | doFilterInternal in org.springframework.web.filter.CorsFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    103 | doFilterInternal in org.springframework.boot.actuate.autoconfigure.MetricsFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    533 | doHandle         in org.eclipse.jetty.servlet.ServletHandler
|    146 | handle . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|    548 | handle           in org.eclipse.jetty.security.SecurityHandler
|    132 | handle . . . . . in org.eclipse.jetty.server.handler.HandlerWrapper
|    257 | nextHandle       in org.eclipse.jetty.server.handler.ScopedHandler
|   1595 | doHandle . . . . in org.eclipse.jetty.server.session.SessionHandler
|    255 | nextHandle       in org.eclipse.jetty.server.handler.ScopedHandler
|   1317 | doHandle . . . . in org.eclipse.jetty.server.handler.ContextHandler
|    203 | nextScope        in org.eclipse.jetty.server.handler.ScopedHandler
|    473 | doScope . . . .  in org.eclipse.jetty.servlet.ServletHandler
|   1564 | doScope          in org.eclipse.jetty.server.session.SessionHandler
|    201 | nextScope . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|   1219 | doScope          in org.eclipse.jetty.server.handler.ContextHandler
|    144 | handle . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|    132 | handle           in org.eclipse.jetty.server.handler.HandlerWrapper
|    531 | handle . . . . . in org.eclipse.jetty.server.Server
|    352 | handle           in org.eclipse.jetty.server.HttpChannel
|    260 | onFillable . . . in org.eclipse.jetty.server.HttpConnection
|    281 | succeeded        in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    102 | fillable . . . . in org.eclipse.jetty.io.FillInterest
|    118 | run              in org.eclipse.jetty.io.ChannelEndPoint$2
|    333 | runTask . . . .  in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    310 | doProduce        in     ''
|    168 | tryProduce . . . in     ''
|    126 | run              in     ''
|    366 | run . . . . . .  in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    762 | runJob           in org.eclipse.jetty.util.thread.QueuedThreadPool
|    680 | run . . . . . .  in org.eclipse.jetty.util.thread.QueuedThreadPool$2
^    748 | run              in java.lang.Thread

Caused by ServletException: Could not resolve view with name 'downloadOutput' in servlet with name 'grailsDispatcherServlet'
->> 1266 | render           in org.springframework.web.servlet.DispatcherServlet
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1041 | processDispatchResult in     ''
|    984 | doDispatch . . . in     ''
|    901 | doService        in     ''
|    970 | processRequest . in org.springframework.web.servlet.FrameworkServlet
|    861 | doGet            in     ''
|    687 | service . . . .  in javax.servlet.http.HttpServlet
|    846 | service          in org.springframework.web.servlet.FrameworkServlet
|    790 | service . . . .  in javax.servlet.http.HttpServlet
|    865 | handle           in org.eclipse.jetty.servlet.ServletHolder
|   1655 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    215 | doFilter         in org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | run              in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|     -2 | doPrivileged . . in java.security.AccessController
|    422 | doAs             in javax.security.auth.Subject
|    105 | doFilter . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     55 | doFilterInternal in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     -1 | call             in javax.servlet.FilterChain$doFilter
|     67 | doFilterInternal in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    111 | doFilterInternal in org.springframework.boot.actuate.trace.WebRequestTraceFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke           in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter . . . . in     ''
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter . . . . in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter         in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilterInternal in grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter . . . . in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter . . . . in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter . . . . in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|     -2 | doPrivileged     in java.security.AccessController
|    422 | doAs . . . . . . in javax.security.auth.Subject
|    105 | doFilter         in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter         in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter         in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter         in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter         in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal in org.springframework.security.web.FilterChainProxy
|    177 | doFilter . . . . in     ''
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal in org.grails.web.filters.HiddenHttpMethodFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    197 | doFilterInternal in org.springframework.web.filter.CharacterEncodingFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | doFilterInternal in org.springframework.web.filter.CorsFilter
|    107 | doFilter . . . . in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    103 | doFilterInternal in org.springframework.boot.actuate.autoconfigure.MetricsFilter
|    107 | doFilter         in org.springframework.web.filter.OncePerRequestFilter
|   1642 | doFilter . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    533 | doHandle         in org.eclipse.jetty.servlet.ServletHandler
|    146 | handle . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|    548 | handle           in org.eclipse.jetty.security.SecurityHandler
|    132 | handle . . . . . in org.eclipse.jetty.server.handler.HandlerWrapper
|    257 | nextHandle       in org.eclipse.jetty.server.handler.ScopedHandler
|   1595 | doHandle . . . . in org.eclipse.jetty.server.session.SessionHandler
|    255 | nextHandle       in org.eclipse.jetty.server.handler.ScopedHandler
|   1317 | doHandle . . . . in org.eclipse.jetty.server.handler.ContextHandler
|    203 | nextScope        in org.eclipse.jetty.server.handler.ScopedHandler
|    473 | doScope . . . .  in org.eclipse.jetty.servlet.ServletHandler
|   1564 | doScope          in org.eclipse.jetty.server.session.SessionHandler
|    201 | nextScope . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|   1219 | doScope          in org.eclipse.jetty.server.handler.ContextHandler
|    144 | handle . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|    132 | handle           in org.eclipse.jetty.server.handler.HandlerWrapper
|    531 | handle . . . . . in org.eclipse.jetty.server.Server
|    352 | handle           in org.eclipse.jetty.server.HttpChannel
|    260 | onFillable . . . in org.eclipse.jetty.server.HttpConnection
|    281 | succeeded        in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    102 | fillable . . . . in org.eclipse.jetty.io.FillInterest
|    118 | run              in org.eclipse.jetty.io.ChannelEndPoint$2
|    333 | runTask . . . .  in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    310 | doProduce        in     ''
|    168 | tryProduce . . . in     ''
|    126 | run              in     ''
|    366 | run . . . . . .  in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    762 | runJob           in org.eclipse.jetty.util.thread.QueuedThreadPool
|    680 | run . . . . . .  in org.eclipse.jetty.util.thread.QueuedThreadPool$2
^    748 | run              in java.lang.Thread`

**Comment by Romainj1** [comment]
I had the same problem, running rundeck on Debian9.
I achieved to solve the problem by uncommenting the 
"grails.serverURL=http://localhost:4440" line in the /etc/rundeck/rundeck-config.properties

I wanted to avoid unpleasant redirecting behaviour from Rundeck, but it seems that removing that parameter has some side-effect.

**Comment by weslleycamilo** [comment]
@Romainj1  suggestion worked for me too.  Thanks.

**Comment by sjrd218** [comment]
@jesusUABC97 I am unable to reproduce this issue in later versions of Rundeck. Are you still experiencing this issue?

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
