### ISSUE TITLE
Active Directory authentication client returns bad credentials

### ISSUE THREAD

**Issue by marcioyoshida** [rundeck/rundeck#4491]
**Describe the bug**
Once Active Directory is configured for authentication, GUI returns Invalid username and password.
Upon looking services.log a solid error is seen: Authentication request failed: org.springframework.security.authentication.BadCredentialsException: Bad credentials

**My Rundeck detail**

* Rundeck version: tried both 3.0.6 and 3.0.13
* install type: rpm install
* OS Name/version: CentOS Linux release 7.5.1804 (Core) 
* DB Type/version: mysql under haproxy
Also
JVM IMPLEMENTATIONVERSION : 25.201-b09
NAME : Java HotSpot(TM) 64-Bit Server VM  VENDOR : Oracle Corporation
VERSION : 1.8.0_201

**To Reproduce**
1. Clean install
2. Configure /etc/rundeck/profile with parameters as

RDECK_JVM="-Djava.security.auth.login.config=/etc/rundeck/jaas-activedirectory.conf \
           -Dloginmodule.name=activedirectory \
           -Drdeck.config=$RDECK_CONFIG \
           -Drundeck.server.configDir=$RDECK_SERVER_CONFIG \
           -Dserver.datastore.path=$RDECK_SERVER_DATA/rundeck \
           -Drundeck.server.serverDir=$RDECK_INSTALL \
           -Drdeck.projects=$RDECK_PROJECTS \
           -Drdeck.runlogs=$RUNDECK_LOGDIR \
           -Drundeck.config.location=$RDECK_CONFIG_FILE \
           -Djava.io.tmpdir=$RUNDECK_TEMPDIR \
           -Drundeck.server.workDir=$RUNDECK_WORKDIR \
           -Dserver.http.port=$RDECK_HTTP_PORT \
           -Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG \
           -Drdeck.base=$RDECK_BASE"

3. Configure jaas-activedirectory.conf as
activedirectory {
com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
debug="true"
contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
providerUrl="ldap://companydc.local:3268"
bindDn="CN=svc_rundeck2,OU=Services,OU=company,DC=companydc,DC=local"
bindPassword="runDec2018"
authenticationMethod="simple"
forceBindingLogin="true"
userBaseDn="DC=companydc,DC=local"
derUrl="ldap://companydc.local:3268"
userRdnAttribute="sAMAccountName"
userIdAttribute="sAMAccountName"
userPasswordAttribute="unicodePwd"
userObjectClass="user"
roleBaseDn="DC=companydc,DC=local"
roleNameAttribute="cn"
roleMemberAttribute="member"
roleObjectClass="group"
cacheDurationMillis="300000"
reportStatistics="true";
};

**Expected behavior**
An authentication with the same configuration as above with an earlier version 2.10.4 happened to succeed.

**Screenshots**

Errorlog services.log

<img width="792" alt="bad credentials error" src="https://user-images.githubusercontent.com/18469770/52671121-635ca700-2f01-11e9-93c6-108753a97cc7.PNG">

System Configuration loaded

<img width="594" alt="system configuration" src="https://user-images.githubusercontent.com/18469770/52671132-6b1c4b80-2f01-11e9-92a1-87aac3f2410c.PNG">

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version 71.0

**Additional context**
Many configurations tryouts were made, returning the same solid error
* Java provider from OpenJdk to Oracle Jvm
* RD Version upgrade
* AD User recreation

**Comment by sjrd218** [comment]
@marcioyoshida Try adding: `-Drundeck.jaaslogin=true` to your RDECK_JVM system properties and see if that helps.

**Comment by marcioyoshida** [comment]
@sjrd218  Added the parameter and, more oddly, it did not started the JVM. I played with the parameters on different line positions, but it seems it did not accepted the parameter.

Error log
[Rundeck-AD-error-service.log](https://github.com/rundeck/rundeck/files/2861372/Rundeck-AD-error-service.log)

Profile configuration
<img width="669" alt="parameter added ad rundeck issue" src="https://user-images.githubusercontent.com/18469770/52730470-95721580-2fa2-11e9-9306-39ae290156c4.PNG">

**Comment by sjrd218** [comment]
@marcioyoshida That stacktrace seems to indicate your jaas conf file is invalid. I think that's good progress because at least it's trying to use your jaas configuration now.

**Comment by marcioyoshida** [comment]
I had it mistakenly commented with '#'. And, as magic, it authenticated with AD user. 
@sjrd218, appreciate your guidance. Best regards, cheers.
