### ISSUE TITLE
Unable to execute powershell scripts on remote node

### ISSUE THREAD

**Issue by gangadhar01a** [rundeck/rundeck#4494]
**Describe the bug**

We have configured a project on rundeck with following settings
Default node executor: WinRM
Default node file copier: Stub
I am able to execute the remote commands on all windows nodes. I have powershell scripts on NFS share, and by using "Stub" as "Default node file copier" I am able to execute the scripts on few of the nodes without having any issues.

Problem: Rundeck unable to execute the same powershell scripts on most of the windows nodes. However, I am able to execute the commands on all nodes.

Are there any settings need to be updated on windows machine?

**My Rundeck detail**

* Rundeck version: [ 2.11.3-1]
* install type: [rpm]
* OS Name/version: [centos 7]
* DB Type/version: [choose: mysql ]

**To Reproduce**
set up project with
Default node executor: WinRM
Default node file copier: Stub
Workflow has the following command to execute 
powershell.exe -File "//corpshares/tech/servicerestart.ps1" 
(servicerestart.ps1 - Script placed on share)
Executing the above powershell script on 8 of the windows machines
**Expected behavior**
Rundeck has to execute the powershell script on all windows nodes

**Actual behavior**
Powershell script has been executed only on 2 nodes

**Screenshots**

**Comment by gangadhar01a** [comment]
<img width="1394" alt="screen shot 1940-11-23 at 10 56 34 pm" src="https://user-images.githubusercontent.com/23003116/52692767-acb8f080-2f19-11e9-93be-747724430508.png">
Attaching the picture which shows the error message

**Comment by gangadhar01a** [comment]
<img width="1237" alt="screen shot 1940-11-23 at 10 59 37 pm" src="https://user-images.githubusercontent.com/23003116/52693588-f0145e80-2f1b-11e9-9ed6-27bce2dd4082.png">
Command on same working executed without any problem

**Comment by gangadhar01a** [comment]
@sjrd218 Can you please guide me in right direction to troubleshoot the issue.

**Comment by sjrd218** [comment]
@gangadhar01a Can you post the full text of one of your error messages?

**Comment by gschueler** [comment]
@gangadhar01a the problem is that you need to use a file copier plugin that copies the file to remote nodes.  "Stub" does not do that, it is a "dummy" plugin only for testing.  The lastest overthere-winrm plugin includes a file copier implementation, but you can use any type you need.

**Comment by gangadhar01a** [comment]
@sjrd218 pasting the full text here
"

[overthere-winrm:prod-sb-wmsapp2.hautelook.local] failed: WinRM Error: Error when sending request to https://prod-sb-wmsapp2.hautelook.local:5986/wsman Request: <?xml version="1.0" encoding="UTF-8"?>  <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">   <env:Header>     <a:To xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">https://prod-sb-wmsapp2.hautelook.local:5986/wsman</a:To>     <a:ReplyTo xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">       <a:Address mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address>     </a:ReplyTo>     <w:MaxEnvelopeSize xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="true">153600</w:MaxEnvelopeSize>     <a:MessageID xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">uuid:6AAF4FAC-F43C-45CE-8427-7DC80DD9E975</a:MessageID>     <w:Locale xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="false" xml:lang="en-US"/>     <p:DataLocale xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd" mustUnderstand="false" xml:lang="en-US"/>     <w:OperationTimeout xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd">PT60.000S</w:OperationTimeout>     <a:Action xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" mustUnderstand="true">http://schemas.microsoft.com/wbem/wsman/1/windows/shell/Receive</a:Action>     <w:SelectorSet xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd">       <w:Selector Name="ShellId">B6125934-64A2-4553-A3BD-7FABCF7814B2</w:Selector>     </w:SelectorSet>     <w:ResourceURI xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="true">http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd</w:ResourceURI>   </env:Header>   <env:Body>     <rsp:Receive xmlns:rsp="http://schemas.microsoft.com/wbem/wsman/1/windows/shell">       <rsp:DesiredStream CommandId="4455ECB4-E696-4CB2-A27E-5027948BE047">stdout stderr</rsp:DesiredStream>     </rsp:Receive>   </env:Body> </env:Envelope>  Response: [EMPTY]
--
16:54:33 |   | Failed: WinRMProtocolError: WinRM Error: Error when sending request to https://prod-sb-wmsapp2.hautelook.local:5986/wsman Request: <?xml version="1.0" encoding="UTF-8"?>  <env:Envelope xmlns:env="http://www.w3.org/2003/05/soap-envelope">   <env:Header>     <a:To xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">https://prod-sb-wmsapp2.hautelook.local:5986/wsman</a:To>     <a:ReplyTo xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">       <a:Address mustUnderstand="true">http://schemas.xmlsoap.org/ws/2004/08/addressing/role/anonymous</a:Address>     </a:ReplyTo>     <w:MaxEnvelopeSize xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="true">153600</w:MaxEnvelopeSize>     <a:MessageID xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing">uuid:6AAF4FAC-F43C-45CE-8427-7DC80DD9E975</a:MessageID>     <w:Locale xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="false" xml:lang="en-US"/>     <p:DataLocale xmlns:p="http://schemas.microsoft.com/wbem/wsman/1/wsman.xsd" mustUnderstand="false" xml:lang="en-US"/>     <w:OperationTimeout xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd">PT60.000S</w:OperationTimeout>     <a:Action xmlns:a="http://schemas.xmlsoap.org/ws/2004/08/addressing" mustUnderstand="true">http://schemas.microsoft.com/wbem/wsman/1/windows/shell/Receive</a:Action>     <w:SelectorSet xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd">       <w:Selector Name="ShellId">B6125934-64A2-4553-A3BD-7FABCF7814B2</w:Selector>     </w:SelectorSet>     <w:ResourceURI xmlns:w="http://schemas.dmtf.org/wbem/wsman/1/wsman.xsd" mustUnderstand="true">http://schemas.microsoft.com/wbem/wsman/1/windows/shell/cmd</w:ResourceURI>   </env:Header>   <env:Body>     <rsp:Receive xmlns:rsp="http://schemas.microsoft.com/wbem/wsman/1/windows/shell">       <rsp:DesiredStream CommandId="4455ECB4-E696-4CB2-A27E-5027948BE047">stdout stderr</rsp:DesiredStream>     </rsp:Receive>   </env:Body> </env:Envelope>  Response: [EMPTY]
"

**Comment by gangadhar01a** [comment]
@gschueler Appreciate for your time, we are using stub since couple of years and it has been working on 75 prod servers except few VM's which have been provisioned recently. Are there any recommendation or suggestions to troubleshoot the issue?

**Comment by gangadhar01a** [comment]
@gschueler As you mentioned I have used overthere plugin to copy and execute scripts to remote node. Unfortunately, we still have same issue 

([overthere-winrm:prod-sb-wmsapp1.hautelook.local] failed: WinRM Error: Error when sending request to https://prod-sb-wmsapp1.hautelook.local:5986/wsman). 

I am pasting the project configuration file here

"#Thu Feb 14 09:16:29 PST 2019
#edit below
project.description=
project.disable.executions=false
project.disable.schedule=false
project.file-copy-destination-dir=C\:\\Users\\rundeck.svc\\remote\\
project.jobs.gui.groupExpandLevel=1
project.label=
project.name=WMS
project.nodeCache.delay=30
project.nodeCache.enabled=true
project.plugin.NodeExecutor.WinRMexe.allowoverride=all
project.plugin.NodeExecutor.WinRMexe.authtype=plaintext
project.plugin.NodeExecutor.WinRMexe.pass=*******
project.plugin.NodeExecutor.WinRMexe.shell=powershell
project.plugin.NodeExecutor.WinRMexe.user=hautelook-servr\\rundeck.svc
project.plugin.NodeExecutor.WinRMexe.winrmport=5985
project.winrm-auth-type=kerberos
project.winrm-cert-trust=all
project.winrm-cmd=CMD
project.winrm-connection-timeout=45000
project.winrm-hostname-trust=all
project.winrm-password-storage-path=keys/demo/rundeck
project.winrm-protocol=https
project.winrm-user-option=rundeck
resources.source.1.config.cache=true
resources.source.1.config.timeout=30
resources.source.1.type=url
resources.source.2.config.file=/var/rundeck/projects/wms/etc/wmsresources.xml
resources.source.2.config.format=resourcexml
resources.source.2.config.generateFileAutomatically=false
resources.source.2.config.includeServerNode=false
resources.source.2.config.requireFileExists=false
resources.source.2.type=file
service.FileCopier.default.provider=overthere-winrm
service.NodeExecutor.default.provider=overthere-winrm"

I have also cross checked the following things on remote node
- rundeck service account exist in local admin group
- WinRM required ports are open (5985, 5986)
- WinRM service running

**Comment by gangadhar01a** [comment]
winrm config on remote node:

PS C:\Windows\system32> winrm g winrm/config
Config
    MaxEnvelopeSizekb = 500
    MaxTimeoutms = 60000
    MaxBatchItems = 32000
    MaxProviderRequests = 4294967295
    Client
        NetworkDelayms = 5000
        URLPrefix = wsman
        AllowUnencrypted = false
        Auth
            Basic = true
            Digest = true
            Kerberos = true
            Negotiate = true
            Certificate = true
            CredSSP = false
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        TrustedHosts
    Service
        RootSDDL = O:NSG:BAD:P(A;;GA;;;BA)(A;;GR;;;IU)S:P(AU;FA;GA;;;WD)(AU;SA;GXGW;;;WD)
        MaxConcurrentOperations = 4294967295
        MaxConcurrentOperationsPerUser = 1500
        EnumerationTimeoutms = 240000
        MaxConnections = 300
        MaxPacketRetrievalTimeSeconds = 120
        AllowUnencrypted = false
        Auth
            Basic = true
            Kerberos = true
            Negotiate = true
            Certificate = false
            CredSSP = false
            CbtHardeningLevel = Relaxed
        DefaultPorts
            HTTP = 5985
            HTTPS = 5986
        IPv4Filter = * [Source="GPO"]
        IPv6Filter = * [Source="GPO"]
        EnableCompatibilityHttpListener = false
        EnableCompatibilityHttpsListener = false
        CertificateThumbprint
        AllowRemoteAccess = true [Source="GPO"]
    Winrs
        AllowRemoteShellAccess = true
        IdleTimeout = 7200000
        MaxConcurrentUsers = 10
        MaxShellRunTime = 2147483647
        MaxProcessesPerShell = 25
        MaxMemoryPerShellMB = 1024
        MaxShellsPerUser = 30
