### ISSUE TITLE
HTTP Workflow Plugin

### ISSUE THREAD

**Issue by andsantrj** [rundeck/rundeck#4496]
Rundeck 3.0.13-20190123
rpm
Amazon Linux 2018.03
H2

HTTP Plugin not Appearing on create job page.

I am using the project from (https://github.com/ohioit/rundeck-http-plugin.git)

I always edit the correct version of rundeck on pom.xml, but I can't install this plugin on the last rundeck version.

Anyone knows whether there's some issue about this.

**Comment by sjrd218** [comment]
@andsantrj If you go to your "List Plugins" page does the plugin show up? I just tried installing it on master and it seems to work just fine.

**Comment by andsantrj** [comment]
@sjrd218 

Actually Not, I can't see anything on rundeck log, this is my pom release section:    

<properties>
        <rundeckVersion>3.0.13-20190123</rundeckVersion>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <outputDirectory>${project.build.directory}</outputDirectory>
    </properties>

Generate a file (rundeck-http-plugin-1.0.6.jar) put on libext directory, but nothing, I can't see the plugin on list plugin page.

A whole sector of the company depends on it :(

**Comment by sjrd218** [comment]
@andsantrj You have no messages in your service log that indicate that plugin did not get loaded because it's invalid?

**Comment by andsantrj** [comment]
@sjrd218 Doing a search, I've found this on service.log:

service.log:2019-02-12 20:17:15.235 ERROR --- [tp1331459452-22] c.d.r.s.plugins.RundeckPluginRegistry    : Plugin edu.ohio.ais.rundeck.HttpWorkflowStepPlugin for service: WorkflowStep was not found
service.log:2019-02-12 20:17:15.237 ERROR --- [tp1331459452-22] rundeck.services.PluginService           : WorkflowStep not found: edu.ohio.ais.rundeck.HttpWorkflowStepPlugin

**Comment by andsantrj** [comment]
@sjrd218 

The problem was the permission on the directory, fixed it and it is working great.

Thank you for the attention.
