### ISSUE TITLE
Getting Warning " Not prompting as we are not in interactive mode"

### ISSUE THREAD

**Issue by netwninja** [rundeck/rundeck#4506]
Hello Team, 

I am running Ansible controller and Rundeck on the same node.  Then I am creating a simple JOB with one step in it. 

Rundeck 3.0.13-20190123
Ansible 2.7.7

Workflow
1st step cd / ; ansible-playbook /playbooks/ts-jun1.yml
execute locally 

The playbook looks likes as shown below and it has VAR prompt and the execution of the playbook fails with below warning " [WARNING]: Not prompting as we are not in interactive mode". 

```
PLAY [Getting Post changes outputs from Juniper nodes] *************************

08:26:56 |   |   |  
08:26:56 |   |   | TASK [tshoot-jun : Show CMD] ***************************************************
08:26:56 |   |   | Friday 15 February 2019  16:26:56 +0000 (0:00:00.316)       0:00:00.316 *******
08:26:56 |   |   | [WARNING]: Not prompting as we are not in interactive mode
08:27:10 |   |   | fatal: [br1]: FAILED! => {"changed": false, "msg": "None\r\n                ^\r\nunknown command.\r\n\r\nansible@phxbr1> "}
08:27:10 |   |   | ...ignoring
08:27:11 |   |   | fatal: [TestJunos]: FAILED! => {"changed": false, "msg": "None\r\n                 ^\r\nunknown command.\r\n\r\nansible@TestSRX> "}
08:27:11 |   |   | ...ignoring
08:27:13 |   |   | fatal: [br2]: FAILED! => {"changed": false, "msg": "None\r\n                ^\r\nunknown command.\r\n\r\nansible@phxbr2> "}
08:27:13 |   |   | ...ignoring


- name: Getting Post changes outputs from Juniper nodes
  hosts: junos
  gather_facts: false
  vars_prompt:
    - name: "show_cmd"
      prompt: "what cmd you want to run"
      private: no
  
  roles: 
    - tshoot-jun

```

Any ideas how to fix this or is it a limitation on Rundeck version i am currently using?

Thank you

**Comment by gschueler** [comment]
Rundeck executions don't offer any interactive behavior.  Perhaps you can pass an argument to your playbook instead of using an interactive var prompt.

**Comment by AkashicSeer** [comment]
So WTF does this dumbass warning mean and how the hell do we get vagrant in "interactive mode" ???????? I hate moronic errors and warnings that leave you scouring the internet for hours trying to figure out shit that should be EASY AND CLEARLY DOCUMENTED

**Comment by AkashicSeer** [comment]
This warning is as useless as saying "Apple jacks, pelican shit" Nonsesne is all it is

**Comment by stjohnfinn** [comment]
I agree with Akashic Seer because there is no documentation on the internet for this.
