### ISSUE TITLE
Rundeck stuck at Login Page

### ISSUE THREAD

**Issue by happicamper** [rundeck/rundeck#4513]
**Describe the bug**
Before upgrading from 3.0.8 to 3.0.13, Rundeck server is easily logged in after typing user and password in the Login page, then redirects to the project list. After the upgrade, it will be stuck in the Login page. I need to remove the `/user/login` from the URL `https://rundeckserver.com` in order to redirect to the Project page `https://rundeckserver.com/menu/home`

**My Rundeck detail**

* Rundeck version: [ 3.0.13 ]
* install type: [yum]
* OS Name/version: [centos 7]
* DB Type/version: [mysql]

**To Reproduce**
1. Upgraded 3.0.8 to 3.0.13 via yum upgrade rundeck rundeck-config
2. Go to https://rundeckserver.com/user/login
3. Type in the correct user and password.
4. It will be stuck in the Login after clicking the Log In.

**Expected behavior**
It should be redirected to : https://rundeckserver/menu/home

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS]
 - Browser [Chrome]
 - Version [72]

**Additional context**

**Comment by NiTRoeSE** [comment]
I can confirm, same problem here.

**Comment by pkoelemij** [comment]
I can confirm, same problem here.

**Comment by ProTip** [comment]
Hi @happicamper ,

Are you running Rundeck behind a TLS terminating reverse proxy? Are you receiving any errors in the browser developer console or network tab?

Thanks!

**Comment by happicamper** [comment]
Hi there@ProTip 
I'm using reverse proxy Nginx.
Upon checking the browser's console, here's the error:
`Refused to send form data to '<URL>' because it violates the following Content Security Policy directive: "form-action 'self'".`

**Comment by zodman** [comment]
@happicamper  this solve that issue #4417

**Comment by happicamper** [comment]
@zodman Thank you very much, it seems that solves the problem.
1. I have added the protocol  `X-Forwarded-Proto` on both HTTP and HTTPS block in Nginx Proxy.
2. Added `-Drundeck.jetty.connector.forwarded=true` on profile config.
As @SergeyBear stated.

**Comment by aneesh121** [comment]
> ProxyRequests On
> ProxyPreserveHost On
> RequestHeader set X-Forwarded-Proto "https"
> ProxyPass “/rundeck”  "http://myhost.com:8080"
> ProxyPassReverse "/rundeck"  "http://myhost.com:8080"

**Comment by Alffhan63** [comment]
> @happicamper this solve that issue [#4417 (comment)](https://github.com/rundeck/rundeck/issues/4417#issuecomment-457548602)

nice
