### ISSUE TITLE
rundeck access for LDAP user with too many roles is slow

### ISSUE THREAD

**Issue by sankeerthsuru** [rundeck/rundeck#4514]
**Describe the bug**
Below is my rundeck config:
~~~
ldap {
    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
      debug="true"
      contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
      providerUrl="ldaps://ldap-auth.prod.jp.local:636"
      bindDn="cn=proxyagent,ou=profile,o=******.co.jp "
      bindPassword="******"
      authenticationMethod="simple"
      forceBindingLogin="true"
      userBaseDn="ou=people,ou=account,ou=development,o=******.co.jp"
      userRdnAttribute="uid"
      userIdAttribute="uid"
      userPasswordAttribute="userPassword"
      userObjectClass="posixAccount"
      roleBaseDn="ou=authgroup,ou=development,o=*****.co.jp"
      roleNameAttribute="cn"
      roleMemberAttribute="member"
      roleObjectClass="groupOfMembers";
};
~~~

Some of the LDAP group users has too many roles and it is taking too much time for login 
When i try to check the services.log for that particular ldap group users, it shows too many roles for user.
Is my configuration  ok or i have to make any changes to restict the rundeck to check for a specified role?

**My Rundeck detail**

* Rundeck version: [ 3.0.9]
* install type: [rpm]
* OS Name/version: [Centos 7]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**Comment by gschueler** [comment]
How many ACL Policies do you have? How many roles are shown for the user?

**Comment by sankeerthsuru** [comment]
Hi @gschueler ,
Thanks for responding.
I have created one ACL for user using the LDAP group he is part of. He is able to access it succesfully. But the issue is it takes 3 to 5 minutes for logging in.From "services.log" file i can see that for this particular user there are lot of roles in LDAP and i suspect that is the reason for delay. I have attached services.log file details, can you please check and help me to find a solution for quick login.

[services_log_user.pdf](https://github.com/rundeck/rundeck/files/2892316/services_log_user.pdf)

**Comment by sankeerthsuru** [comment]
> How many ACL Policies do you have? How many roles are shown for the user?
Hi @gschueler ,
Thanks for responding.
I have created one ACL for user using the LDAP group he is part of. He is able to access it succesfully. But the issue is it takes 3 to 5 minutes for logging in.From "services.log" file i can see that for this particular user there are lot of roles in LDAP and i suspect that is the reason for delay. I have attached services.log file details, can you please check and help me to find a solution for quick login.
[services_log_user.pdf](https://github.com/rundeck/rundeck/files/2892320/services_log_user.pdf)
