### ISSUE TITLE
Import Archive button missing in Admin page 

### ISSUE THREAD

**Issue by huegelc** [rundeck/rundeck#4517]
**Describe the bug**
According to https://docs.rundeck.com/docs/administration/maintenance/backup-and-recovery.html#import-an-archive there should be a Import Archive link in the admin menu

**My Rundeck detail**

* Rundeck version: [Rundeck 3.0.13-20190123 ]
* install type: [choose: deb]
* OS Name/version: bionic
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**
1. Go to 'Front page...'
2. Click on '.Admin'
3. See error

<img width="249" alt="screenshot 2019-02-19 at 00 21 33" src="https://user-images.githubusercontent.com/6955465/52980839-6281b480-33dc-11e9-8b54-abcf5e1f515e.png">

**Comment by jtobard** [comment]
That option is now on the sidebar.
I'm moving this to rundeck/docs issues.

<img width="661" alt="imagen" src="https://user-images.githubusercontent.com/2894508/53014214-92ee4080-3426-11e9-955c-04960f3a2768.png">

**Comment by huegelc** [comment]
Wait, that means that I have to create the project manually and then import the archive?

**Comment by jtobard** [comment]
That's right

**Comment by huegelc** [comment]
Can you help me understand why you need to create the same project manually just to import it afterwards from the backup file?

**Comment by huegelc** [comment]
That wasn't meant ironic ;)

**Comment by gaetanquentin** [comment]
https://github.com/rundeck/rundeck/issues/4011
