### ISSUE TITLE
API Scheduler Takeover: Internal Server Error 500

### ISSUE THREAD

**Issue by marcioyoshida** [rundeck/rundeck#4524]
**Describe the bug**

Upon http requesting the /api/14/scheduler/takeover an 500: Internal Server Error is returned

**My Rundeck detail**

* Rundeck version: 3.0.13-20190123
* install type: rpm install
* OS Name/version: CentOS 7.5.1804 
* DB Type/version: mysql under haproxy

**To Reproduce**

0. Use API request tool like Postman
1. Configure Token
2. Fill body request with

~~~.xml
 <takeoverSchedule>
    <server all="true"/>
</takeoverSchedule>
~~~

3. Request http: API api/14/scheduler/takeover

HTTP Request

~~~
PUT /api/14/scheduler/takeover HTTP/1.1
Host: zonzo03.acme.intranet:4440
X-Rundeck-Auth-Token: Tv3zMQ3qKie6wMae1TjEzDPglli20wlw
Content-Type: application/x-www-form-urlencoded
cache-control: no-cache
Postman-Token: c0dd034a-0af2-4051-9da7-67f99ec07836
<takeoverSchedule>
    <server all="true"/>
</takeoverSchedule>------WebKitFormBoundary7MA4YWxkTrZu0gW--
~~~

**Expected behavior**

Upon requesting this API  an operation error should be returned at least. 

**Screenshots**
![image](https://user-images.githubusercontent.com/18469770/53125716-5f520a00-353d-11e9-8768-b89d46449b70.png)

[rundeck 500.txt](https://github.com/rundeck/rundeck/files/2886567/rundeck.500.txt)

**Additional context**

Attempt to script a node takeover.

**Comment by marcioyoshida** [comment]
Config files attached:

[profile.txt](https://github.com/rundeck/rundeck/files/2886589/profile.txt)
[rundeck-config.properties.txt](https://github.com/rundeck/rundeck/files/2886590/rundeck-config.properties.txt)
[framework.properties.txt](https://github.com/rundeck/rundeck/files/2886591/framework.properties.txt)

**Comment by gschueler** [comment]
If you are sending XML content, your request should say `Content-Type: application/xml`

**Comment by marcioyoshida** [comment]
@gschueler, yes, I see it now. Thanks for pinpointing it. Regards, Marcio
