### ISSUE TITLE
Slow GUI loading

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4531]
All job-related pages take an extended period of time to load on a production rundeck instance of ours.

```
Machine with slow loading:
* Rundeck version: 3.0.12
* install type: RPM
* OS Name/version: Oracle linux 7
* DB Type/version: mySQL
```
problem: takes 18 seconds to fully load a specific job page. see browser debugging:
![rundeckcap](https://user-images.githubusercontent.com/42989099/53255792-004edb00-368c-11e9-9995-e675cb88c107.PNG)
![rundeckcap2](https://user-images.githubusercontent.com/42989099/53255797-0349cb80-368c-11e9-9213-f597d72799a4.PNG)

I have exported and moved all jobs and activities to a fresh rundeck instance on a seperate machine which does not see this issue.

```
Machine without issue:
* Rundeck version: 3.0.12
* install type: RPM
* OS Name/version: Centos 6
* DB Type/version: mySQL
```

I believe the duplication of the project on another server eliminates the following possible causes:

- activity load impact
- ACL load impact
- Database related issues.

The only thing that I could think could cause this is network - but I wouldn't expect network to cause this large of an issue, the connection speed is adequate. So, what is "ace-bundle-" that is taking so long to load?
![image](https://user-images.githubusercontent.com/42989099/53256300-23c65580-368d-11e9-8859-56288b33bc75.png)

Note: I have tested this on multiple machines with Firefox and Chrome.

**Comment by gtsteffaniak** [comment]
This was determined to be network related. Closing.

**Comment by umomany** [comment]
We are experiencing the same problem.
@gtsteffaniak, did you figure out the main cause of this issue ?

**Comment by gtsteffaniak** [comment]
@umomany

Due to our VPN connection. 100% due to network connectivity.
