### ISSUE TITLE
Cannot run file option on Cluster Mode balancer, file is not available

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/rundeck#4532]
**Describe the bug**
I'm currently using a Rundeck on Cluster mode on two nodes with pgsql, and with load balancer configuration to run a job in another cluster member when the first is on high load. I've created a job with a file option where I just do cat to the uploaded file and this crash when it is executed on another node that I'm not logged in.

Failed to start execution: rundeck.services.FileUploadServiceException: File is not available: 3e4462b9-27dc-4ced-8887-001bf3ae185f

**My Rundeck detail**

* Rundeck version: Rundeck Cluster 2.3.6 and 3.0.13 tested
* install type: rpm/jar tested
* OS Name/version: ubuntu 18.04 and CentOS 7.6.1810
* DB Type/version: PostgreSQL 9.2.24

**To Reproduce**
1. On Rundeck Cluster, with at least two Cluster Members, with load balancer configuration, Create New Job
2. Add File Option, set up as required
3. Create an exec Step to cat the file, e.g. cat ${file.option}

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Screenshots attached internally (3676)

**Comment by jessemarple** [comment]
Filed on Rundeck Pro
