### ISSUE TITLE
Session.connect: java.security.SignatureException: Invalid encoding for signature

### ISSUE THREAD

**Issue by george110487** [rundeck/rundeck#4538]
**Describe the bug**
This java security error (SignatureException: Invalid encoding for signature) appears sporadic and to different nodes when running a job, manually or scheduled.
Most of the jobs are having scripts (.bat or .ps1) that must be transferred by rundeck to node, then run it.
Job is crashing on the first node when trying to copy a script file via scp, sending ssh command, or can crash when finished work on first node and passing to the next one, then cannot connect to that node.
I made java update to last version (8 update 201), but no change in the jobs behavior.
It continues to return these sporadic errors which are very annoying.

ERRORS:
"
Failed dispatching to node XXX: [jsch-scp] Failed copying the file: Session.connect: java.security.SignatureException: Invalid encoding for signature
Execution failed: 1538 in project XYZ: [Workflow result: , step failures: {3=JobFailed: Job [613f97ea-d89f-4821-8bbc-9c4966c8c0e7] failed}, Node failures: {XXX=[]}, status: failed]
"

"
Failed: SSHProtocolFailure: Session.connect: java.security.SignatureException: Invalid encoding for signature
Execution failed: 1521 in project XYZ: [Workflow result: , step failures: {3=JobFailed: Job [613f97ea-d89f-4821-8bbc-9c4966c8c0e7] failed}, Node failures: {XXX=[]}, status: failed]
"

**My Rundeck detail**

* Rundeck version: 3.0.13
* install type: war
* OS Name/version: Windows Server 2012 R2
* DB Type/version: mysql
* Java Type/version: 8 update 201

**To Reproduce**
1. Go to 'Projects'
2. Click on 'JobName'
3. Scroll down to 'Jobs'
4. Run your desired job
5. Expected to run fine every time, but suddenly, from time to time, returns java security exception errors

**Expected behavior**
I expect that jobs to run correctly every time, as no change is made on rundeck server or to dispatch nodes.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Browser Version: 72

**Additional context**

**Comment by gschueler** [comment]
This might be the cause: https://sourceforge.net/p/jsch/bugs/111/

If so we perhaps just need to upgrade jsch library, which has been updated and according to some comments in that issue solves the problem

**Comment by gschueler** [comment]
ref #4562

**Comment by george110487** [comment]
@gschueler Really thanks for implication! 
I will wait 3.0.17 version release to put in action and feedback to you. 

Greetings,
George

**Comment by george110487** [comment]
@gschueler - I see that 3.0.19 is already available for download, but in the milestone I can't see if issue with "Invalid encoding for signature" is included (Upgrade Jsch library to latest (0.1.55) ). It was added by you in 3.0.18 but milestone for it is not finished.

Can you please bring some light to me? 

Thanks,
George

**Comment by sjrd218** [comment]
@george110487 The PR to update the jsch library was merged. Please try out 3.0.19 and let us know if it fixes your issue.

**Comment by george110487** [comment]
@sjrd218 Thanks for update! 👍  I just installed the new version. 
I will let you know if issue still persists. It came sporadically until now, so it should never appear again. 
We'll see :)
