### ISSUE TITLE
Unexpected strings show in Node Selection

### ISSUE THREAD

**Issue by jervislam0911** [rundeck/rundeck#4540]
**Describe the bug**
Unexpected strings show in Node Selection.

In job page, from the section where you select your nodes. There are extra string "zilch found: null/null [:]" appended to all the nodename.

**My Rundeck detail**

* Rundeck version: [3.0.16-20190223]
* install type: [rpm]
* OS Name/version: [Centos 7]
* DB Type/version: [File system]

**To Reproduce**
1. Go to your project and pick any jobs
2. Scroll down to 'Nodes' sections and expend "Matched Nodes"
3. See weird string nodename + "zilch found: null/null [:]"

**Expected behavior**
just nodename should be showed

**Screenshots**
![image](https://user-images.githubusercontent.com/14086195/53345637-5b2e3f80-38e3-11e9-8bfa-2b0f7d2611de.png)

**Desktop (please complete the following information):**
 - OS: [windows 8]
 - Browser [chrome]
 - Version [72.0.3626.119]

**Comment by mazzella-c** [comment]
I have the same issue with 3.0.16

**Comment by bhababu** [comment]
I also have same issue with 3.0.16

**Comment by gschueler** [comment]
this duplicates #4541
