### ISSUE TITLE
Does not apply recursion of variable values between job options

### ISSUE THREAD

**Issue by jbanda15** [rundeck/rundeck#4547]
**Describe the bug**
When I try to get variable values between job options, I don't have recursion.

**My Rundeck detail**

    * Rundeck version: Rundeck Pro Cluster 2.4.5 and 3.0.14

**To Reproduce**

A global variable has been declared in the rundeck-config.properties file:
`project.globals.options.dir3=/opt/rundeck/projects/Datacenter_Management/options/doc-cases/3631`
When I call it, it is as follows:
`${globals.project.options.dir2}/f5_SDK_Utilities`

In one job, the Option Plugin_Option_Dir is hard-coded to a global option and a string (in this case, the plugin name). As you'll see, Plugin_Option_Dir is being read literally, and not expanding as I would expect.

**Expected behavior**
The global variable does get expanded

**Comment by reinerrdeck** [comment]
Hi @jbanda15 

Please put a Job Definition to reproduce.

**Comment by jbanda15** [comment]
This is the job definition:

`- defaultTab: summary`
  `description: ''`
`  executionEnabled: true`
`  id: c2e7aa8f-9c9f-45f1-a78f-ee7bb4324d91`
`  loglevel: INFO`
`  name: job-GO-3631-2.0`
`  nodeFilterEditable: false`
`  options:`
`  - enforced: true`
`    name: Plugin_Option_Dir`
`    required: true`
`    value: ${globals.project.options.dir2}/f5_SDK_Utilities`
 `   values:`
 `   - ${globals.project.options.dir2}/f5_SDK_Utilities`
 ` - enforced: true`
 `   name: Material`
 `   value: file:${option.Plugin_Option_Dir.value}/materials.json`
 `   valuesUrl: file:${option.Plugin_Option_Dir.value}/materials.json`
 ` scheduleEnabled: true`
 ` sequence:`
 `   commands:`
 `   - description: Echo new project opts dir`
 `     exec: echo "globals.project.options.dir2=${globals.project.options.dir2}"`
 `   - description: Dump contents of ${globals.project.options.dir2}`
 `     exec: find ${globals.project.options.dir2} -ls`
 `   - description: Echo new Plugin_Option_Dir`
 `     exec: echo "Plugin_Option_Dir=${option.Plugin_Option_Dir}"`
 `   - description: Dump contents of ${option.Plugin_Option_Dir}`
 `     exec: find ${option.Plugin_Option_Dir} -ls`
 `   - description: Echo selected material.`
 `     exec: echo "Material=${option.Material}"`
 `   keepgoing: false`
 `   strategy: node-first`
 ` uuid: c2e7aa8f-9c9f-45f1-a78f-ee7bb4324d91`

And the screenshots:

![n1-projectconfig](https://user-images.githubusercontent.com/45765283/53812989-57319b80-3f3b-11e9-81b3-98c5bb603628.png)
![n2-runjob](https://user-images.githubusercontent.com/45765283/53812993-5993f580-3f3b-11e9-9565-df3501561653.png)
![n3-editoption](https://user-images.githubusercontent.com/45765283/53812996-5d277c80-3f3b-11e9-84cd-c3b4537a65b8.png)

**Comment by reinerrdeck** [comment]
The value is inaccessible via options but can use it directly:

First step: I used globals directly.
Second step: I used though the option.

![screenshot_20190306_173729](https://user-images.githubusercontent.com/43051294/53913242-a8c05000-4039-11e9-91a6-d8f75de0266d.png)

**Comment by MegaDrive68k** [comment]
That's doesn't happen on 3.1.0 :-)

**Comment by MegaDrive68k** [comment]
That's doesn't happen on 3.1.0 :-)

**Comment by jbanda15** [comment]
This issue was fixed in the 3.1.0 release.

In the 3.0.14 version the behavior was:
![global vars 3 0 14](https://user-images.githubusercontent.com/45765283/65461919-1b084e80-de2b-11e9-8bc1-dc684cafcea8.png)

And in the 3.1.0 version the behavior was:
![global vars 3 1](https://user-images.githubusercontent.com/45765283/65461928-1e9bd580-de2b-11e9-96ca-7e7ed070879b.png)

In the last release does apply recursion of variable values between job options.
