### ISSUE TITLE
Flow control unable to fail job.

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4549]
Adding flow control filter cannot fail job. If a step fails, the job will always succeed if a flow control is added. Checking the "Fail" box does not affect job status.

![image](https://user-images.githubusercontent.com/42989099/53453630-50120700-39ea-11e9-8319-611407510349.png)

tested on
Version: 3.0.12 - 3.0.16
Database: H2 and mysql

**Comment by gschueler** [comment]
can you include more of your job definition? thanks

**Comment by gtsteffaniak** [comment]
@gschueler see xml:

<joblist>
  <job>
    <defaultTab>output</defaultTab>
    <description></description>
    <dispatch>
      <excludePrecedence>true</excludePrecedence>
      <keepgoing>true</keepgoing>
      <rankOrder>ascending</rankOrder>
      <successOnEmptyNodeFilter>false</successOnEmptyNodeFilter>
      <threadcount>1</threadcount>
    </dispatch>
    <executionEnabled>true</executionEnabled>
    <group>test</group>
    <id>eea76939-abc8-4d6d-b344-a01ff91ed31a</id>
    <loglevel>INFO</loglevel>
    <name>test</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <nodefilters>
      <filter>.*</filter>
    </nodefilters>
    <nodesSelectedByDefault>true</nodesSelectedByDefault>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='true' strategy='sequential'>
      <command>
        <errorhandler>
          <step-plugin type='flow-control'>
            <configuration>
              <entry key='fail' value='true' />
              <entry key='halt' value='false' />
            </configuration>
          </step-plugin>
        </errorhandler>
        <plugins />
        <script><![CDATA[#!/bin/bash
echo hello
echo history
exit 1]]></script>
        <scriptargs />
      </command>
      <pluginConfig>
        <LogFilter type='key-value-data'>
          <config>
            <logData>true</logData>
            <name>test</name>
            <regex>hi</regex>
          </config>
        </LogFilter>
      </pluginConfig>
    </sequence>
    <uuid>eea76939-abc8-4d6d-b344-a01ff91ed31a</uuid>
  </job>
</joblist>
