### ISSUE TITLE
Batch jobs vs Long running services

### ISSUE THREAD

**Issue by normanlmfung** [rundeck/rundeck#4551]
hi there,
There are two kinds of jobs:
a. **Batch jobs** that start and finishes in minutes or even hours
b. **Long running services** that never ends
I'm having problem with (b).

In my job config, i used "Command" step to kick start my long running service via command prompt. All good. However, under _"Activity for this job" \ "running"_ - RunDeck is reporting the job is stuck in "**Running**" state (As supposed to "**Succeeded**").
After awhile, it's reporting a confusing a job completion of 8000%

Fact with long running services RunDeck status stuck in "Running" state leads to other problems:
a) Next executions would not start unless you manually "Kill" the running executions first (This was resolved by setting "Multiple Executions" to True
b) you can click "Kill Job", in which case the job steps would be reported as "Failed". This is misleading as the job steps did not failed: We simply wanted to "Stop" the long running service..
Am I not most well informed on how to configure RunDeck for Long running services?

Also way my Command step works is:
   `C:\myapp\Launcher.bat`

In launcher.bat, 
    `call dotnet myDotNetCoreApp.dll --Env Production --StopTime 0:11:00:00`

As you can see, two processes spawned:
**First:** cmd.exe (with arg = Launcher.bat)
**Second:** dotnet.exe 

When you **"Kill Job"**, RunDeck only kill `"cmd.exe Launcher.bat"`. The `dotnet.exe` process spawned would be **orphaned**.

**Comment by ahormazabal** [comment]
Hi @devvvy 

To get Rundeck to correctly start your service process in the background, the best option would be to [manage it as a windows service](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/windows-service?view=aspnetcore-2.2), and use Rundeck to run commands to start/stop the service.

When you use the ‘call’ command to start your service its process will stay executing on foreground forever, therefore Rundeck will wait in “running” state until the process finishes by itself or gets killed.

If you still don’t wish to configure your service as a windows service and need a function similar to ‘call’ but running the process on background, allowing rundeck to finish the job successfully while the service continues running, you can use the [‘start’](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/start) command.
