### ISSUE TITLE
[enhancement] Allow log filtering for execution level logs

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4556]
Allow log filter for execution log events such as failed file copy:
![image](https://user-images.githubusercontent.com/42989099/53523001-3f709800-3aa1-11e9-81f6-0556337e880b.png)

Currently all execution level logs will show no matter what filters are applied.

**Comment by gschueler** [comment]
Can you clarify what you mean? do you wish to remove those log lines from the output?

**Comment by gtsteffaniak** [comment]
@gschueler Correct, Execution level logs, such as details about a copy file failure should be filterable.

For example, some jobs have a filecopy option that might not be used. If it's not used, I would like the ability to filter an error message created by a blank file.

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
