### ISSUE TITLE
Bulk job delete via API with JSON params fails

### ISSUE THREAD

**Issue by kristian-lesko** [rundeck/rundeck#4557]
**Describe the bug**
Bulk job deletion via Rundeck API fails when either `ids` or `idlist` (or both) is provided in the request body in JSON format, while `curl` with the same query parameters (directly in URL) works correctly.
The failing `curl` command was like this:
> curl -u admin:password http://rundeck/api/17/jobs/delete -d '{"ids": ["aaaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee", "aaaaaaaaa-bbbb-cccc-dddd-ffffffffffff"]}' -X DELETE -H 'Content-Type: application/json' -H 'Accept: text/json'

The error was:
> {
    "apiversion": 30,
    "error": true,
    "errorCode": "api.error.parameter.required",
    "message": "parameter \"Any of: ids, idlist\" is required"
}

While this `curl` command passed correctly:
> curl -u admin:password "http://rundeck/api/17/jobs/delete?ids=aaaaaaaaa-bbbb-cccc-dddd-eeeeeeeeeeee&ids=aaaaaaaaa-bbbb-cccc-dddd-ffffffffffff" -X DELETE -H 'Content-Type: application/json' -H 'Accept: text/json'

**My Rundeck detail**
* Rundeck version: 3.0.16
* install type: WAR
* OS Name/version: CentOS 7
* DB Type/version: Postgres

**To Reproduce**
1. Create a job.
2. Find the UUID of the job.
3. Run the delete `curl` command against Rundeck API as described above.

**Expected behavior**
The required parameter should be recognized as present in the request, and the corresponding job(s) should be deleted.

**Additional context**
Seems to happen on all API versions; I tried replacing the version `17` in the request with the most recent `30` but the result was identical.

**Comment by gschueler** [comment]
I think you should be using `POST` method when there is a request body. Using `DELETE` method will work if there is no request body (i.e. using query parameters), but I believe the body is ignored.

**Comment by gschueler** [comment]
I filed an issue on rundeck/docs to update that API documentation with that information: https://github.com/rundeck/docs/issues/219

**Comment by kristian-lesko** [comment]
@gschueler thank you; it seems to make sense. What confused me was that we used it this way with Rundeck 2 and it worked. But updating the documentation should definitely clear it up.

**Comment by gschueler** [comment]
@kristian-lesko i think perhaps the behavior changed for rundeck 3
