### ISSUE TITLE
Connection to a node through public key authentification

### ISSUE THREAD

**Issue by rmjstn** [rundeck/rundeck#4561]
**Description**
SSH connection to a node through public key authentification doesn't work.

**My Rundeck detail**

* Rundeck version: [3.0.13]
* install type: [RPM]
* OS Name/version: [CentOS 7.3]
* DB Type/version: [PostgreSQL ]

**To Reproduce**
1. From the command line, the rundeck user can open an ssh connection to the node using the public key authentification
2. I store the public key in the Key Storage
3. I didn't find in the documentation the node configuration for public key authentification (only private key or password) : https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html
4. I don't know how to use this properties : PreferredAuthentications (publickey) and ssh-config-KEY

Thanks,

Rémy

**Comment by gschueler** [comment]
For SSH key authentication, you need to store the private key on the rundeck server key storage, and set the authentication method to "privateKey".  The public key needs to be added to the "authorized_keys" on the target node.

You can either set the default private key to use in the Project Configuration page, or specify it on the node attributes. See https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html#ssh-private-key-storage

**Comment by rmjstn** [comment]
Hi,

Thanks for your answer. 
Sorry, there's something I can't implement correctly in the configuration or I don't understand.

- rundeck linux user (Rundeck server) has a private and a public key
- ssh configuration right on Rundeck node 
- rundeck user from Rundeck server can connect to Rundeck node using ssh public key authentification 
- from Rundeck server "ssh rundeck@"Rundeck node" id" works
- I define the private key of the rundeck linux user (Rundeck server) in the Key Storage
- I deduce that in order to connect to the Rundeck node, the job use this private key
- I've got this error : 

```
Executing command on node: infra_test01, NodeEntryImpl{tags=[], attributes={nodename=infra_test01, hostname=infra_test01, ssh-key-storage-path=keys/rundeck, description=infra_test01, osName=GNU/Linux, ssh-authentication=privateKey, username=rundeck}, project='null'}
[workflow] beginExecuteNodeStep(infra_test01): NodeDispatch: ScriptFileItem{script=[14 chars]}
--
13:02:19 |   |   | Using ssh key storage path: keys/rundeck
13:02:19 |   |   | copying file: '/var/lib/rundeck/var/tmp/dispatch4045958259826025765.tmp' to: 'infra_test01:/tmp/45-180-infra_test01-dispatch-script.tmp.sh'
13:02:19 |   |   | Using stored private key data.
13:02:19 |   |   | invalid privatekey: [B@43b7a033
```
- I have however defined the content of the node file /var/lib/rundeck/.ssh/id_rsa in the Key Storage.

This is an extract of the node definition : 

```
infra_test01:
  description: infra_test01
  hostname: infra_test01
  nodename: infra_test01
  osName: GNU/Linux
  username: rundeck
  ssh-authentication: privateKey
  ssh-key-storage-path: keys/rundeck
```

There's something I don't understand, I don't see what...

Thanks,

Rémy

**Comment by rmjstn** [comment]
Hi,

I think I found out where my problem comes from.
I use Vault and SignMyKey to create an SSH CA Certificate Signing Key (id_rsa-cert.pub). I found [there](https://github.com/rundeck/rundeck/issues/1467) that the Jsch library does not support that feature.

Is there a way to connect to the node using an SSH CA Certificate Signing Key ?

Thanks,

Rémy

**Comment by rmjstn** [comment]
Hi,

It works with the OpenSSH Node Executor. With this configuration : 

```
node-executor: ssh-exec
file-copier: ssh-copier
ssh-authentication: privateKey
ssh-keyfile: /var/lib/rundeck/.ssh/id_rsa
```
I have to made a change in [this file](https://github.com/rundeck-plugins/openssh-node-execution/blob/master/contents/ssh-exec.sh) : privateKey vs privatekey. I'll do a PR later.

Rémy

**Comment by ahonor** [comment]
@rmjstn thanks for checking the OpenSSH Node Executor. I was going to suggest trying that. Looking forward to the PR.

**Comment by Followthevu** [comment]
I got the same error using the SSH plugin for the node execution, however if i use SSHJ it works.
Same keys on both.
Is there more documentation on the regular SSH plugin? like what account it uses and what permissions does it need to access the keys?

**Comment by ledufakademy** [comment]
same issue this is really , the blackhole sun !!

**Comment by pleegor** [comment]
> Hi,
> 
> I think I found out where my problem comes from. I use Vault and SignMyKey to create an SSH CA Certificate Signing Key (id_rsa-cert.pub). I found [there](https://github.com/rundeck/rundeck/issues/1467) that the Jsch library does not support that feature.
> 
> Is there a way to connect to the node using an SSH CA Certificate Signing Key ?
> 
> Thanks,
> 
> Rémy

Working on the same issue now. Did you end up adding key signing every time you need to ssh or in your case signed keys have no ttl?
