### ISSUE TITLE
Error when trying to uninstall.

### ISSUE THREAD

**Issue by sboulianne** [rundeck/rundeck#4573]
Can you fix your uninstall/upgrade script ASAP ?
choco uninstall rundeck
Chocolatey v0.10.12-beta-3-gb65f586
Uninstalling the following packages:
rundeck
Removing 'exp' and 'lib' folders from 'C:\rundeck\server'
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\rundeck\server\exp' because it does not exist.

rundeck v3.0.16
Removing C:\rundeck
Removing environment variable
Skipping auto uninstaller - No registry snapshot.

I have the same error when I tried to upgrade.
Removing 'exp' and 'lib' folders from 'C:\rundeck\server'
ERROR: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\rundeck\server\exp' because it does not exist.

**Comment by gschueler** [comment]
we don't maintain the Chocolatey package, please contact the maintainer
