### ISSUE TITLE
Running "tab" of a job's activity is always empty

### ISSUE THREAD

**Issue by nmamn** [rundeck/rundeck#4574]
**Describe the bug**
On a job's page, the "running" tab is always empty, even if a long running job is currently running.
It was working fine on 2.11.X, it's no longer working in version 3.0.16

**My Rundeck detail**

* Rundeck version: [ e.g. 3.0.16]
* install type: war
* OS Name/version: Ubuntu 16.04.6
* DB Type/version: mysql

**To Reproduce**
1. Start a "long running job" (ie > 30s)
2. In the tab "Activity for this job" at the bottom of the page, the "running" tab is empty with : "No running executions found"
3. Try to click on "recent" of "failed", it displays fine, try to go back to "running", it's still empty
4. Job is displaying fine in the "activity" global view

**Expected behavior**
The job was displaying fine in the running tab before 3.0.16 (can't say if it was working in 3.0.0. though ...)

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser : Firefox 
 - Version : latest

**Additional context**
Thanks a lot :-) Do not hesitate to ask more details if needed

**Comment by reinerrdeck** [comment]
I can confirm this issue.

On 3.0.6:

![iss1](https://user-images.githubusercontent.com/43051294/53755258-d750f600-3e94-11e9-8351-4980d0ea0181.png)

On 3.0.16:

![iss2](https://user-images.githubusercontent.com/43051294/53755268-dcae4080-3e94-11e9-87fa-316e262fc20e.png)

**Comment by nmamn** [comment]
FYI I'm trying to track this one down a little bit more

It's displaying fine in 3.0.13 (even if the "running" tab is not displaying anything at first as already said in another bug report I believe, but just by clicking on "recent" and going back to "running" displays the job fine)

Will try to update to each version between 3.0.13 and 3.0.16 to narrow it down.

**Comment by ProTip** [comment]
This was fixed by #4576 in `3.0.17`.
