### ISSUE TITLE
Date picker not working as expected.

### ISSUE THREAD

**Issue by NFDWADM** [rundeck/rundeck#4578]
**Describe the bug**
When creating a date option for a job the date field (before being clicked on) says the output format will be `"mm/dd/yy HH:MM"`. After clicking on date the date field itself says the format is `"MM/DD/YYYY hh:mm a"`

When running the job after having picked a date the actual output in the script is f.ex.:

> 2019-03-13T21:09:00+01:00

--

**My Rundeck detail**

* Rundeck version: Rundeck 3.0.9-20181127
* install type: war
* OS Name/version: Rhel 6.9

**To Reproduce**
1. Create a job
2. Create a date variable
3. Write a script that echoes the date variable
4. Run script

**Expected behavior**
The script shows `"mm/dd/yy HH:MM"`.

**Comment by ProTip** [comment]
I'm also seeing odd behavior. If I select a date it will use one format. However, if I open the picker it will revert he format and if I click off the picker it will keep the different format:

https://monosnap.com/file/qUe4TrCMYF8ax0QUeY8ev69R9Hhd8B
