### ISSUE TITLE
Job creation fails because unrelated project does not exist

### ISSUE THREAD

**Issue by kristian-lesko** [rundeck/rundeck#4579]
**Describe the bug**
When a project (let's call it `project1`) was deleted in our Rundeck 3 installation, trying to create a new job in _any_ other project failed with the following error:
> Project does not exist: project1

**My Rundeck detail**

* Rundeck version: 3.0.16
* install type: WAR
* OS Name/version: CentOS 7
* DB Type/version: Postgres

**To Reproduce**
1. Create two projects
2. Delete one of them
3. Try to create a new job in the other project

**Expected behavior**
Deletion of one project should not affect the other projects.

**Screenshots**
<img width="1679" alt="rundeckprojecterrror" src="https://user-images.githubusercontent.com/17571374/53797076-bc828e00-3f35-11e9-86a6-e8b8240e44b4.png">

**Additional context**
I wasn't able to reproduce this again on a different installation; even on the same installation, if a different project is deleted, it doesn't affect the other projects. Also, when I re-created the deleted project with the name reported in the error, job creation worked again.

**Comment by nmamn** [comment]
Hi,

Apparently the same as #4502 and #3905

**Comment by reinerrdeck** [comment]
Hi @nmamn 

Yes,  is the same issue as https://github.com/rundeck/rundeck/issues/4502 and https://github.com/rundeck/rundeck/issues/3905

The workaround right now is restarting Rundeck Service.

**Comment by gschueler** [comment]
closing as duplicate
