### ISSUE TITLE
project configuration not overwritten when importing archive

### ISSUE THREAD

**Issue by boudekerk** [rundeck/rundeck#4582]
**Describe the bug**
When importing this archive, and selecting *Import Project Configuration*, contrary to the description, the project.properties weren't overwritten. This used to work fine with 2.x

**My Rundeck detail**

* Rundeck version: 3.0.16
* install type: deb
* OS Name/version: Debian
* DB Type/version: mysql

**To Reproduce**
1. Create a new project
2. Project settings -> Edit configuration -> Edit Configuration File: make a change, add a resource for example
3. Project settings -> Export archive
4. Check that it contains the updated: rundeck-PROJECTNAME/files/etc/project.properties
5. Create a new project
6. Project settings -> Import archive: Check *Import Project Configuration* is selected
7. Import the archive
7. Project settings -> Edit configuration -> Edit Configuration File: Note that this does not contain the change above

**Expected behavior**
The project.properties have been overwritten with the properties stored in the archive

**Additional context**
We use an template (archive) to bootstrap new projects, this archive contains both some jobs and the following file:
rundeck-PROJECTNAME/files/etc/project.properties

**Comment by reinerrdeck** [comment]
I can replicate the issue, only happens when Rundeck store projects on the database.

**Comment by ProTip** [comment]
Fixed by #4672
