### ISSUE TITLE
Rundeck jobs behavior on scheduling and killing

### ISSUE THREAD

**Issue by george110487** [rundeck/rundeck#4584]
**Describe the bug**
I encountered 2 situations with Rundeck jobs, which for me are important:

1) Setting scheduled job at desired HH:mm, it will not be scheduled like intended, HH:mm:00 sec. 
It will add random seconds after, which is pretty annoying because I use a pretty precise scheduling of many jobs, one after the other, and I can't make it because running can be delayed, depends how many seconds are added to that desired minute.

2) Killing a job which was in running or scheduled for a later time, will send me notification like job was failed. I use On Failure notification over mail. 
I would need to differentiate Failure from Kill. 
Maybe Notification on Kill would be good, if any option for this scope isn't already included yet in Rundeck.

**My Rundeck detail**

* Rundeck version: [3.0.16]
* install type: [war]
* OS Name/version: [Windows Server 2012 R2]
* DB Type/version: [mysql]

**To Reproduce 1) Scheduled Job **
1. Go to 'Jobs'
2. Click on 'Job'
3. Scroll down to 'Run job later'
4. Choose desired Date and Time -> Click on Schedule Job
5. Go to 'Activity' and check starting time for your scheduled job

**To Reproduce 2) Kiling Job **
1. Go to 'Jobs'
2. Click on 'Edit this Job'
3. Scroll down to 'Send Notification'
4. On Failure -> Check Send Mail -> Insert details
5. Kill a running or scheduled job will send Failed notification

**Expected behavior 1) Scheduled Job **
I would expect to have HH;mm and 00 seconds when I schedule a job at desired time, otherwise, I would expect to see also "seconds" field available to choose, for a more precise scheduling.

**Expected behavior 2) Killing Job **
I would expect to have different options for sending Notifications when job Failed or Killed

**Desktop (please complete the following information):**

- OS: Windows 10
- Browser: Chrome
- Browser Version: 72

**Comment by reinerrdeck** [comment]
Hi @george110487 

About your first issue:

I can test under Windows 10 and Linux and can't reproduce your issue, but exist an issue from Microsoft that can repair some clock behavior can be affect Rundeck, check that:

https://social.technet.microsoft.com/Forums/en-US/a10099f6-2cd7-40ab-9e7f-22e9484c4e23/windows-10-clock-keeps-changing?forum=win10itprohardware

On Windows:

![win1](https://user-images.githubusercontent.com/43051294/53901415-b071fb80-401d-11e9-8532-7e00d3314915.png)

On Linux:

![lnx1](https://user-images.githubusercontent.com/43051294/53901394-a3eda300-401d-11e9-9910-bb66efc31cac.png)

About your second issue, sas you known, a this moment you can see the message:

"• Killed after 4s by admin - View Output »" 

But sounds good for an enhacement.

Regards.

**Comment by george110487** [comment]
@reinerrdeck Thanks for your kind explanations!

1) Tried fixing time issue with recommendations from technet, seems that has no effect. Maybe something over domain is changing the time, a GPO or similar task, and this I can't control... I can live with it. Is a maximum delay of 59 seconds, which must be taken in consideration for very precise scheduling

2) Would be great if separate Notification for Killed jobs can be implemented. Can be seen from mail subject if failed job was really failed or manually killed by user.

Greetings,
George
