### ISSUE TITLE
HTML log view not working properly in Chrome browser

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4591]
Somewhere between 3.0.12 and 3.0.16 and issue with the HTML output started occurring only for chrome. If you try to run a job with the HTML view, it downloads a file instead (rather than opening a new page).

Here is the file contents:

```
<html>
                <head>
                <title></title>
                </head>
                <body>
                <div class="container">
                <div class="row">
                <div class="col-sm-12">
                Waiting for Execution log...
                </div>
                <script>
                setTimeout(function(){
                   window.location.reload(1);
                }, 5000);
                </script>
                </body>
                </html>
```
The file is the job execution ID without any ".html" filename

I confirmed this was an issue for multiple different machines running chrome for rundeck 3.0.16. I verified it was working fine on the other rundeck instance I had setup 3.0.12.

NOTE: This is not an issue for any rundeck version on firefox and internet explorer. Only Chrome.

**Comment by sjrd218** [comment]
This should be fixed in 3.0.17.
