### ISSUE TITLE
informative box behind menu

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#4597]
**Describe the bug**
informative box behind menu

**My Rundeck detail**

* Rundeck version: 3.0.16
* install type: deb
* OS Name/version: ubuntu 18.04
* DB Type/version: any

**To Reproduce**
When checking node info.

**Expected behavior**
box info on top or right side of left menu

**Screenshots**

![image](https://user-images.githubusercontent.com/34582874/53969508-af050980-40d7-11e9-9fb1-81e683c9c07f.png)

**Desktop**
 - OS: ubuntu 18.04
 - Browser: chrome
 - Version: Versión 73.0.3683.56

**Comment by jtobard** [comment]
fixed by #4660
