### ISSUE TITLE
LDAPS not working on Rundeck 3.0.16

### ISSUE THREAD

**Issue by ghost** [rundeck/rundeck#4601]
**Describe the bug**
Secure LDAP connection (LDAPS) cannot be established following the how-to under:
https://docs.rundeck.com/docs/administration/security/authenticating-users.html#communicating-over-secure-ldap-ldaps

`Error message: PKIX path validation failed`

**My Rundeck detail**

* Rundeck version: 3.0.16
* install type: rpm,
* OS Name/version: rhel 7.5
* DB Type/version: postgres

**To Reproduce**
1. : Do the steps to configure LDAPS described under: https://docs.rundeck.com/docs/administration/security/authenticating-users.html#communicating-over-secure-ldap-ldaps

**Expected behavior**
LDAPS connection can be established based on the stores described in /etc/rundeck/ssl/ssl.properties

**Additional context**
I had to manually pass the keystore and truststore as JVM Options:
RDECK_JVM_OPTS="-Djavax.net.ssl.keyStore=${RDECK_CONFIG}/ssl/keystore -Djavax.net.ssl.keyStorePassword=${CERT_STORE_PASS} -Djavax.net.ssl.trustStore=${RDECK_CONFIG}/ssl/truststore -Djavax.net.ssl.trustStorePassword=${CERT_STORE_PASS}"

Setting RUNDECK_WITH_SSL=true is not sufficient, even though the stores are being used by Rundeck, because HTTPS is working!

**Comment by Romainj1** [comment]
I also had problems setting up LDAPs, as Java's way of dealing keyStore is a bit hard. I recommend using a proxy like stunnel to setup your ldaps.
