### ISSUE TITLE
Running Child Jobs with a Parent Job fails to execute any job after the 1st with MSSQL backend

### ISSUE THREAD

**Issue by identifi-awilliamson** [rundeck/rundeck#4603]
**Describe the bug**
Attempting to run two child jobs from a parent job. When running the parent job, the first child job runs successfully, but the second child job never begins. The entire system becomes unresponsive and the only option is either shutdown the service or wait upwards of 20 minutes. 

Each child job is using pyWinRM to remotely execute against Windows nodes. Again, this works regardless of which job is the first workflow step, and each job runs separately (outside of the context of being run as a child job by a parent job). 

I am using a Microsoft SQL Server 2017 backend with the mssql-jdbc-7.0.0.jre8.jar driver. This seems to work in all other tests so far. If I remove the MSSQL backend, then I can't recreate the failure. All Workflow Job steps execute in order as expected. 

**My Rundeck detail**

* Rundeck version: Rundeck 3.0.7-20181008
* install type: [choose: deb]
* OS Name/version: [ debian Debian GNU/Linux 9 (stretch)"]
* DB Type/version: [choose: mssql]
* MSSQL Version: [MS Sql Server 2017]
* JDBC Driver Version: [mssql-jdbc-7.0.0.jre8.jar ]

**To Reproduce**
1. Configure MSSQL backend
2. Create a parent job that runs two child jobs as Workflow steps against remote Windows Servers
3. Run the parent job
4. Site becomes unresponsive, 2nd job waits in the Up Next status for 20+ minutes until service is restarted, or attempting to login from another browser session which shows the attached error. 

**Expected behavior**
The child job workflow steps should run as expected.

**Error Message**
`Error 500: Internal Server Error
URI
/project/WebServerHosts/jobs
Class
org.apache.tomcat.jdbc.pool.PoolExhaustedException
Message
could not prepare statement
Caused by
[qtp1076262627-282] Timeout: Pool empty. Unable to fetch a connection in 10 seconds, none available[size:50; busy:50; idle:0; lastwait:10000].
Trace
    Line | Method
->>   47 | convert                                in org.hibernate.exception.internal.StandardSQLExceptionConverter
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    111 | convert                                in org.hibernate.engine.jdbc.spi.SqlExceptionHelper
|    182 | prepareStatement . . . . . . . . . . . in org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate
|    148 | prepareQueryStatement                  in org.hibernate.engine.jdbc.internal.StatementPreparerImpl
|   1934 | prepareQueryStatement . . . . . . . .  in org.hibernate.loader.Loader
|   1903 | executeQueryStatement                  in     ''
|   1881 | executeQueryStatement . . . . . . . .  in     ''
|    925 | doQuery                                in     ''
|    342 | doQueryAndInitializeNonLazyCollections in     ''
|   2622 | doList                                 in     ''
|   2464 | listUsingQueryCache . . . . . . . . .  in     ''
|   2426 | list                                   in     ''
|    109 | list . . . . . . . . . . . . . . . . . in org.hibernate.loader.criteria.CriteriaLoader
|   1787 | list                                   in org.hibernate.internal.SessionImpl
|    363 | list . . . . . . . . . . . . . . . . . in org.hibernate.internal.CriteriaImpl
|    385 | uniqueResult                           in     ''
|    144 | executeUniqueResultWithProxyUnwrap . . in grails.orm.HibernateCriteriaBuilder
|   1704 | invokeMethod                           in org.grails.orm.hibernate.query.AbstractHibernateCriteriaBuilder
|   1586 | get . . . . . . . . . . . . . . . . .  in     ''
|    124 | hasDirectory                           in rundeck.services.DbStorageService
|     58 | hasDirectory . . . . . . . . . . . . . in com.dtolabs.rundeck.core.storage.ResolvedExtTree
|     46 | hasDirectory                           in org.rundeck.storage.impl.DelegateTree
|     44 | hasDirectory . . . . . . . . . . . . . in org.rundeck.storage.impl.StringToPathTree
|     71 | $tt__listDirPaths                      in rundeck.services.ConfigStorageService
|     94 | doInTransaction . . . . . . . . . . .  in grails.gorm.transactions.GrailsTransactionTemplate$2
|    133 | execute                                in org.springframework.transaction.support.TransactionTemplate
|     91 | execute . . . . . . . . . . . . . . .  in grails.gorm.transactions.GrailsTransactionTemplate
|    183 | listStoredPolicyPaths                  in rundeck.services.AuthorizationService
|    159 | loadStoredPolicies . . . . . . . . . . in     ''
|    142 | getStoredPolicies                      in     ''
|     82 | getRoleList . . . . . . . . . . . . .  in     ''
|    709 | getFrameworkRoles                      in rundeck.services.FrameworkService
|     35 | getUserRoles . . . . . . . . . . . . . in org.rundeck.web.infosec.ContainerRoleSource
|    120 | doCall                                 in rundeck.interceptors.SetUserInterceptor$_createAuthSubject_closure2
|    118 | createAuthSubject . . . . . . . . . .  in rundeck.interceptors.SetUserInterceptor
|     48 | before                                 in     ''
|     77 | preHandle . . . . . . . . . . . . . .  in org.grails.plugins.web.interceptors.GrailsInterceptorHandlerInterceptorAdapter
|    133 | applyPreHandle                         in org.springframework.web.servlet.HandlerExecutionChain
|    962 | doDispatch . . . . . . . . . . . . . . in org.springframework.web.servlet.DispatcherServlet
|    901 | doService                              in     ''
|    970 | processRequest . . . . . . . . . . . . in org.springframework.web.servlet.FrameworkServlet
|    861 | doGet                                  in     ''
|    846 | service . . . . . . . . . . . . . . .  in     ''
|    865 | handle                                 in org.eclipse.jetty.servlet.ServletHolder
|   1655 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    215 | doFilter                               in org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | run                                    in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs . . . . . . . . . . . . . . . . . in javax.security.auth.Subject
|    105 | doFilter                               in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     55 | doFilterInternal                       in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke . . . . . . . . . . . . . . . . in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter                               in     ''
|    331 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter                               in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter . . . . . . . . . . . . . . . in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter . . . . . . . . . . . . . . . in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run . . . . . . . . . . . . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs                                   in javax.security.auth.Subject
|    105 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter . . . . . . . . . . . . . . . in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter . . . . . . . . . . . . . . . in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy
|    177 | doFilter                               in     ''
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal                       in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal                       in org.grails.web.filters.HiddenHttpMethodFilter
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    533 | doHandle                               in org.eclipse.jetty.servlet.ServletHandler
|    146 | handle . . . . . . . . . . . . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|    548 | handle                                 in org.eclipse.jetty.security.SecurityHandler
|    132 | handle . . . . . . . . . . . . . . . . in org.eclipse.jetty.server.handler.HandlerWrapper
|    257 | nextHandle                             in org.eclipse.jetty.server.handler.ScopedHandler
|   1595 | doHandle . . . . . . . . . . . . . . . in org.eclipse.jetty.server.session.SessionHandler
|    255 | nextHandle                             in org.eclipse.jetty.server.handler.ScopedHandler
|   1317 | doHandle . . . . . . . . . . . . . . . in org.eclipse.jetty.server.handler.ContextHandler
|    203 | nextScope                              in org.eclipse.jetty.server.handler.ScopedHandler
|    473 | doScope . . . . . . . . . . . . . . .  in org.eclipse.jetty.servlet.ServletHandler
|   1564 | doScope                                in org.eclipse.jetty.server.session.SessionHandler
|    201 | nextScope . . . . . . . . . . . . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|   1219 | doScope                                in org.eclipse.jetty.server.handler.ContextHandler
|    144 | handle . . . . . . . . . . . . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|    132 | handle                                 in org.eclipse.jetty.server.handler.HandlerWrapper
|    531 | handle . . . . . . . . . . . . . . . . in org.eclipse.jetty.server.Server
|    352 | handle                                 in org.eclipse.jetty.server.HttpChannel
|    260 | onFillable . . . . . . . . . . . . . . in org.eclipse.jetty.server.HttpConnection
|    281 | succeeded                              in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    102 | fillable . . . . . . . . . . . . . . . in org.eclipse.jetty.io.FillInterest
|    291 | onFillable                             in org.eclipse.jetty.io.ssl.SslConnection
|    151 | succeeded . . . . . . . . . . . . . .  in org.eclipse.jetty.io.ssl.SslConnection$3
|    102 | fillable                               in org.eclipse.jetty.io.FillInterest
|    118 | run . . . . . . . . . . . . . . . . .  in org.eclipse.jetty.io.ChannelEndPoint$2
|    333 | runTask                                in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    310 | doProduce . . . . . . . . . . . . . .  in     ''
|    168 | tryProduce                             in     ''
|    126 | run . . . . . . . . . . . . . . . . .  in     ''
|    366 | run                                    in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    762 | runJob . . . . . . . . . . . . . . . . in org.eclipse.jetty.util.thread.QueuedThreadPool
|    680 | run                                    in org.eclipse.jetty.util.thread.QueuedThreadPool$2
^    748 | run . . . . . . . . . . . . . . . . .  in java.lang.Thread

Caused by PoolExhaustedException: [qtp1076262627-282] Timeout: Pool empty. Unable to fetch a connection in 10 seconds, none available[size:50; busy:50; idle:0; lastwait:10000].
->>  403 | getTargetConnection                    in org.springframework.jdbc.datasource.LazyConnectionDataSourceProxy$LazyConnectionInvocationHandler
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    376 | invoke                                 in     ''
|    240 | invoke . . . . . . . . . . . . . . . . in org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy$TransactionAwareInvocationHandler
|    146 | doPrepare                              in org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5
|    172 | prepareStatement . . . . . . . . . . . in org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate
|    148 | prepareQueryStatement                  in org.hibernate.engine.jdbc.internal.StatementPreparerImpl
|   1934 | prepareQueryStatement . . . . . . . .  in org.hibernate.loader.Loader
|   1903 | executeQueryStatement                  in     ''
|   1881 | executeQueryStatement . . . . . . . .  in     ''
|    925 | doQuery                                in     ''
|    342 | doQueryAndInitializeNonLazyCollections in     ''
|   2622 | doList                                 in     ''
|   2464 | listUsingQueryCache . . . . . . . . .  in     ''
|   2426 | list                                   in     ''
|    109 | list . . . . . . . . . . . . . . . . . in org.hibernate.loader.criteria.CriteriaLoader
|   1787 | list                                   in org.hibernate.internal.SessionImpl
|    363 | list . . . . . . . . . . . . . . . . . in org.hibernate.internal.CriteriaImpl
|    385 | uniqueResult                           in     ''
|    144 | executeUniqueResultWithProxyUnwrap . . in grails.orm.HibernateCriteriaBuilder
|   1704 | invokeMethod                           in org.grails.orm.hibernate.query.AbstractHibernateCriteriaBuilder
|   1586 | get . . . . . . . . . . . . . . . . .  in     ''
|    124 | hasDirectory                           in rundeck.services.DbStorageService
|     58 | hasDirectory . . . . . . . . . . . . . in com.dtolabs.rundeck.core.storage.ResolvedExtTree
|     46 | hasDirectory                           in org.rundeck.storage.impl.DelegateTree
|     44 | hasDirectory . . . . . . . . . . . . . in org.rundeck.storage.impl.StringToPathTree
|     71 | $tt__listDirPaths                      in rundeck.services.ConfigStorageService
|     94 | doInTransaction . . . . . . . . . . .  in grails.gorm.transactions.GrailsTransactionTemplate$2
|    133 | execute                                in org.springframework.transaction.support.TransactionTemplate
|     91 | execute . . . . . . . . . . . . . . .  in grails.gorm.transactions.GrailsTransactionTemplate
|    183 | listStoredPolicyPaths                  in rundeck.services.AuthorizationService
|    159 | loadStoredPolicies . . . . . . . . . . in     ''
|    142 | getStoredPolicies                      in     ''
|     82 | getRoleList . . . . . . . . . . . . .  in     ''
|    709 | getFrameworkRoles                      in rundeck.services.FrameworkService
|     35 | getUserRoles . . . . . . . . . . . . . in org.rundeck.web.infosec.ContainerRoleSource
|    120 | doCall                                 in rundeck.interceptors.SetUserInterceptor$_createAuthSubject_closure2
|    118 | createAuthSubject . . . . . . . . . .  in rundeck.interceptors.SetUserInterceptor
|     48 | before                                 in     ''
|     77 | preHandle . . . . . . . . . . . . . .  in org.grails.plugins.web.interceptors.GrailsInterceptorHandlerInterceptorAdapter
|    133 | applyPreHandle                         in org.springframework.web.servlet.HandlerExecutionChain
|    962 | doDispatch . . . . . . . . . . . . . . in org.springframework.web.servlet.DispatcherServlet
|    901 | doService                              in     ''
|    970 | processRequest . . . . . . . . . . . . in org.springframework.web.servlet.FrameworkServlet
|    861 | doGet                                  in     ''
|    846 | service . . . . . . . . . . . . . . .  in     ''
|    865 | handle                                 in org.eclipse.jetty.servlet.ServletHolder
|   1655 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    215 | doFilter                               in org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | run                                    in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs . . . . . . . . . . . . . . . . . in javax.security.auth.Subject
|    105 | doFilter                               in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     55 | doFilterInternal                       in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke . . . . . . . . . . . . . . . . in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter                               in     ''
|    331 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter                               in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter . . . . . . . . . . . . . . . in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter . . . . . . . . . . . . . . . in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run . . . . . . . . . . . . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs                                   in javax.security.auth.Subject
|    105 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter . . . . . . . . . . . . . . . in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter . . . . . . . . . . . . . . . in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter . . . . . . . . . . . . . . . in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter                               in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal . . . . . . . . . . . in org.springframework.security.web.FilterChainProxy
|    177 | doFilter                               in     ''
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal                       in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal                       in org.grails.web.filters.HiddenHttpMethodFilter
|   1642 | doFilter . . . . . . . . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    533 | doHandle                               in org.eclipse.jetty.servlet.ServletHandler
|    146 | handle . . . . . . . . . . . . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|    548 | handle                                 in org.eclipse.jetty.security.SecurityHandler
|    132 | handle . . . . . . . . . . . . . . . . in org.eclipse.jetty.server.handler.HandlerWrapper
|    257 | nextHandle                             in org.eclipse.jetty.server.handler.ScopedHandler
|   1595 | doHandle . . . . . . . . . . . . . . . in org.eclipse.jetty.server.session.SessionHandler
|    255 | nextHandle                             in org.eclipse.jetty.server.handler.ScopedHandler
|   1317 | doHandle . . . . . . . . . . . . . . . in org.eclipse.jetty.server.handler.ContextHandler
|    203 | nextScope                              in org.eclipse.jetty.server.handler.ScopedHandler
|    473 | doScope . . . . . . . . . . . . . . .  in org.eclipse.jetty.servlet.ServletHandler
|   1564 | doScope                                in org.eclipse.jetty.server.session.SessionHandler
|    201 | nextScope . . . . . . . . . . . . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|   1219 | doScope                                in org.eclipse.jetty.server.handler.ContextHandler
|    144 | handle . . . . . . . . . . . . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|    132 | handle                                 in org.eclipse.jetty.server.handler.HandlerWrapper
|    531 | handle . . . . . . . . . . . . . . . . in org.eclipse.jetty.server.Server
|    352 | handle                                 in org.eclipse.jetty.server.HttpChannel
|    260 | onFillable . . . . . . . . . . . . . . in org.eclipse.jetty.server.HttpConnection
|    281 | succeeded                              in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    102 | fillable . . . . . . . . . . . . . . . in org.eclipse.jetty.io.FillInterest
|    291 | onFillable                             in org.eclipse.jetty.io.ssl.SslConnection
|    151 | succeeded . . . . . . . . . . . . . .  in org.eclipse.jetty.io.ssl.SslConnection$3
|    102 | fillable                               in org.eclipse.jetty.io.FillInterest
|    118 | run . . . . . . . . . . . . . . . . .  in org.eclipse.jetty.io.ChannelEndPoint$2
|    333 | runTask                                in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    310 | doProduce . . . . . . . . . . . . . .  in     ''
|    168 | tryProduce                             in     ''
|    126 | run . . . . . . . . . . . . . . . . .  in     ''
|    366 | run                                    in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    762 | runJob . . . . . . . . . . . . . . . . in org.eclipse.jetty.util.thread.QueuedThreadPool
|    680 | run                                    in org.eclipse.jetty.util.thread.QueuedThreadPool$2
^    748 | run . . . . . . . . . . . . . . . . .  in java.lang.Thread
`

**Comment by jtobard** [comment]
This looks like a deadlock problem fixed on 3.0.12, you can try installing the latest release to see if this is still a problem.

**Comment by identifi-awilliamson** [comment]
Thanks - just updated and initial testing looks good!
