### ISSUE TITLE
Job with Flow Control with Halt option enabled doesn't work when called by another job.  

### ISSUE THREAD

**Issue by fgutierrezz** [rundeck/rundeck#4605]
**Describe the bug**
Job with Flow Control with Halt option enabled doesn't work when called by another job.  
![Halt_Job_definition](https://user-images.githubusercontent.com/30966360/54059576-65501800-41d8-11e9-94ed-e1618b9b1ca8.png)

**My Rundeck detail**

* Rundeck version: 3.0.7 , 2,11.10, 3.0.9
* install type: launcher
* OS Name/version: ubuntu 16.04
* DB Type/version: H2

**To Reproduce**
1. Import both jobs 
2. Execute the job Halt, this stop the job successfully
3. Execute the job "HaltWorkflow". 
The output shows the workflow in job "Halt" is not interrupted. 
Expected behavior:
- You don't see You should not see this message
- You don't see YOu should NOT see this other step either

Actual behavior:
- [OK] You don't see "You should not see this message"
- [NOT OK] You DO see "YOu should NOT see this other step either"
![execution_parentJob_HaltWorkflow](https://user-images.githubusercontent.com/30966360/54059524-42bdff00-41d8-11e9-9dd6-9b02662b4ee8.png)

**Expected behavior**
Is expected the referenced job to be interrupted. 

**Additional context**
screenshot and job definition attached

[Halt.zip](https://github.com/rundeck/rundeck/files/2947698/Halt.zip)

**Comment by jtobard** [comment]
The problem here is the Flow control plugin is succeeding even with `Fail=yes`.
Actually, the Fail with Halt is working inverted, if you set `Fail=false` it fails and interrupts the parent flow.

**Comment by puremourning** [comment]
I don’t fully understand the fix and the test proves nothing. Iirc the job halted and failed if run independently and not when run as a job reference step.

**Comment by jtobard** [comment]
@puremourning in the end it wasn't a problem only with referenced jobs, the Flow Control step didn't _fail correctly_ with that setup (Halt + Fail)

**Comment by puremourning** [comment]
Strange. In my custom workflow step I am calling Halt( false ). From the case:

> ANyway I was testing it and found that while it successfully called "getFlowControl().halt( false )", the jobs continued runing anyway.

**Comment by puremourning** [comment]
The problem is that calling halt with any value does not halt the parent workflow, which is what i want

**Comment by vikashkmr31** [comment]
After halting job , can we rerun from the halt step
