### ISSUE TITLE
to show full date when "Run Job Later" option is used

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#4611]
**Describe the bug**
Can the scheduled date be displayed in execution and activity tab?

**My Rundeck detail**

* Rundeck version: 3.0.16
* install type: war
* OS Name/version: ubuntu 18.04
* DB Type/version: any

**To Reproduce**
1. Go to a job
2. Click on "Run Job Later"
3. Go to Activity tab, see behavior as shown in pic1
4. Go to the execution number, see behavior as shown in pic2

**Expected behavior**
To see full scheduled date.

**Screenshots**
pic1.

![Captura de pantalla de 2019-03-11 19-46-45](https://user-images.githubusercontent.com/34582874/54163416-c7f31f00-4437-11e9-8703-c6625ed9f7ca.png)

pic2.

![Captura de pantalla de 2019-03-11 19-47-11](https://user-images.githubusercontent.com/34582874/54163363-82365680-4437-11e9-8992-2f3bdad55223.png)

**Desktop (please complete the following information):**
 - OS: Linux, ubuntu 18.04
 - Browser: chrome
 - Version: 73.0.3683.56

**Comment by jplassnibatt** [comment]
Clarification:
day of the test: 11 of march 2019
pic1, shows schedule hour only, missing minutes and year (only in the informative popup window is showed correctly)
pic2, shows schedule for hour and minutes, but missing year (only in the informative popup window is showed correctly)

**Comment by gschueler** [comment]
please review behavior of  3.1

**Comment by jplassnibatt** [comment]
Fixed in 3.1
