### ISSUE TITLE
Child Job does not get killed immediately after killing Parent job

### ISSUE THREAD

**Issue by drodriguez-rundeck** [rundeck/rundeck#4612]
**Describe the bug**
When running a Job as "Job Reference" within a Parent Job, killing the Parent Job does not kill the child job(s) immediately. 

**My Rundeck detail**

* Rundeck version: 3.0.16 Enterprise
* install type: Tested on war, deb and rpm
* OS Name/version: Ubuntu 18.04.1 and Centos 7

**To Reproduce**

Let's say we have 3 jobs (Parent, Child1, and Child2). 

Parent Job executes a "sleep 10" command on a remote node, when finished, Parent Job calls Child1 which executes a "sleep 20" on remote node too, and after this, Child1 calls Child2 which executes a "sleep 30" also on a remote node. All jobs are nested.

Parent (sleep 10) ---> Child1 (sleep 20)---> Child2 (sleep 30)

When killing Parent Job in the middle of the execution of Child1, let's say 9 seconds after Child1 started, Child1 does not get killed immediately, it continues the execution of "sleep 20" until it finishes. Child2 is not executed (as expected). 

**Expected behavior**
Child Job should get killed immediately after killing Parent Job

**Comment by jtobard** [comment]
This is no longer an issue thanks to the changes recently introduced in 3.0.19 to the behavior in the referenced jobs and in 3.0.20 to executions.
