### ISSUE TITLE
TransactionSystemException when dispatching a job step

### ISSUE THREAD

**Issue by kristian-lesko** [rundeck/rundeck#4616]
**Describe the bug**
When running a job on Rundeck 3, a `TransactionSystemException` is raised and visible in the log output, in place of a correct dispatch of a job step to a node.

**My Rundeck detail**

* Rundeck version: 3.0.17
* install type: WAR
* OS Name/version: CentOS 7
* DB Type/version: Postgres

**To Reproduce**
It happens quite randomly. However, in addition to this error, many of our teammates have reported slowness and weird behavior of the UI.
1. Run a job on Rundeck 3.

**Expected behavior**
Dispatch of a job step to a node should work without issues.

**Additional context**
We use Tomcat 7.

Log output:
> Failed dispatching to node X:
org.springframework.transaction.TransactionSystemException: Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection

**Comment by sjrd218** [comment]
@kristian-lesko Can you post a full stacktrace of an occurrence of this error? Also please send your database connection pool settings.

**Comment by kristian-lesko** [comment]
@sjrd218 I'm sorry but I don't have any other logs left over (I've already terminated the subject VM).

I'm not sure what's meant by "database connection pool settings", but these are all the settings I have for the database:
```
dataSource.dbCreate = update
dataSource.url = jdbc:h2:file:<db path>;MVCC=true;TRACE_LEVEL_FILE=4

# Use PostgreSQL as data source
dataSource.driverClassName = org.postgresql.Driver
dataSource.dbCreate = update
dataSource.url = jdbc:postgresql://<DB address>
```
