### ISSUE TITLE
Job stuck at waiting for execution

### ISSUE THREAD

**Issue by kristian-lesko** [rundeck/rundeck#4617]
**Describe the bug**
When running a job on Rundeck 3, it may keep waiting for execution to start but never actually run. We have jobs stuck for as much as 12+ hours in this way.

Once this happens on a Rundeck server, it seems to keep happening on all jobs that are started.

**My Rundeck detail**

* Rundeck version: 3.0.17
* install type: WAR
* OS Name/version: CentOS 7
* DB Type/version: Postgres

**To Reproduce**
1. Deploy a Rundeck 3 server
2. Run some jobs
3. Issue will start happening eventually

**Expected behavior**
Jobs should not get stuck.

**Additional context**
We use Tomcat 7.

**Comment by ahonor** [comment]
Is this a scheduled job @kristian-lesko ?

**Comment by kristian-lesko** [comment]
@ahonor The first time I noticed it, it was indeed on a scheduled job. However, running a job (either the scheduled one or another one) manually then triggered the same issue,

**Comment by DiegoQueiroz** [comment]
Same problem here. I used Rundeck 2.x for years and this never happened.
The logs did not help. Important to cite that the Timeout setting is never triggered, which means the job gets stucked before any attempt to start it (I have to manually kill it).

I was using Rundeck 3.0.8. I updated it to Rundeck 3.0.22 to see if something changes.

**Comment by ahonor** [comment]
@DiegoQueiroz, Can you describe your job definition? Is it a single job or one with jobref steps to other jobs. Is the Timeout for the parent job?

**Comment by DiegoQueiroz** [comment]
Sure. My job has a single step that run a remote command in a node (via SSH). There is also an error handler to run another command in the same node (to kill the process case it times out).

When the problem happens, I see nothing running in the remote server (the command wasn't started) and the error handler is never triggered.

**Comment by ahonor** [comment]
@DiegoQueiroz, the ssh command never begins? This is via a Command step in the job? Is this random occurrence or can you reproduce it at will?

**Comment by DiegoQueiroz** [comment]
Yes, it doesn't start and it displays nothing in Log output (only a message saying the job is preparing to start, or something).

After I kill the job, when I check it in the Activity menu, it appears as "aborted" (not failed) and states the execution summary and the log output aren't available (they're not simple empty, they're unavailable). For me this means the step never started.

This problem I'm describing usually happens often (each 2 days or so), but I really can't reproduce it at will. Important to cite that since I updated the server (yesterday), I didn't experienced the problem again. But it is still under observation.

**Comment by ahonor** [comment]
@DiegoQueiroz if you find this state again, take a java thread dump.

**Comment by DiegoQueiroz** [comment]
How can I do that?

**Comment by DiegoQueiroz** [comment]
@ahonor the problem happened again. How can I provide a thread dump?

**Comment by ahonor** [comment]
@DiegoQueiroz You can take a java thread dump by running `kill -3 <pid>` on the PID of the Rundeck running java process.

**Comment by wadelu** [comment]
still facing this issue with Rundeck 3.2.9 to 3.3.6

**Comment by Shinku-Chen** [comment]
vim /etc/default/rundeckd
RDECK_JVM_SETTINGS="$RDECK_JVM_SETTINGS -Xmx4096m -Xms1024m"

low mem cause slow ssh connect speed
