### ISSUE TITLE
Which version of postgresql is supported by Rundeck 2.x and 3.x ?

### ISSUE THREAD

**Issue by hmalinov** [rundeck/rundeck#4618]
Issue type: Question

Which version of postgresql is supported by Rundeck 2.x and 3.x ?
I check https://docs.rundeck.com/docs/administration/configuration/database/postgres.html, but could not  find an answer.

Thank you.

**Comment by sjrd218** [comment]
@hmalinov Have you tried a version that didn't work for you? Generally, any version that is supported by hibernate should work just fine.
