### ISSUE TITLE
SCM Git plugins ignore Strict Host Key Checking value

### ISSUE THREAD

**Issue by jimmy-scott** [rundeck/rundeck#4620]
**Describe the bug**
SCM Git Import/Export fails to setup or enable if git host is not in known_hosts.

**My Rundeck detail**

* Rundeck version: 3.0.17
* install type: docker
* OS Name/version: docker @ ubuntu 16.04
* DB Type/version: H2

**To Reproduce**
1. Go to 'Setup SCM' > 'Git Export' > 'Configure'
2. Fill in git ssh url (ssh://git@gitrepo/home/git/my-repo.git)
3. Set 'Authentication' > 'SSH: Strict Host Key Checking' to 'no'
4. Setup

**Error message**
Failed cloning... UnknownHostKey: gitrepo. RSA fingerprint is ...

**Comment by zolvaring** [comment]
I still experience the exact reported issue in Rundeck 3.10-20190731, on configuring a new project for scm imports "setup" fails with the following message:

`Failed fetch from the repository: ssh://<repo>: UnknownHostKey: <host address>. RSA key fingerprint is <fingerprint>`

Of course manually adding the host key works, but this is a dynamic environment, I am severely confused what the `disable strict key checking` option is if it's not supposed to prevent this situation.

**Comment by gaetanquentin** [comment]
same pb with rd 3.1.0

**Comment by gaetanquentin** [comment]
and is there a way to reload know_hosts keys dynamicaly? adding git scm server needs to add key in know_hosts, but apparently rundeck has to be restarted to read it.
