### ISSUE TITLE
Make password utilitlity field Value To Encrypt to type password

### ISSUE THREAD

**Issue by ckaiser79** [rundeck/rundeck#4624]
**Is your feature request related to a problem? Please describe.**

I am working in a team with about 15 persons, where 3 of them move regulary to new teams. When I need to grant them access to rundeck, I need to open the password utlity tool (https://ecom-buildmaster.lx.hosts.intra/rundeck/passwordUtility/index) and let them enter their password. Before they enter their password I change the type of the password field from type text to type password, so I cannot see the value of the password in plain text during typing.

I see the encrypted password values copy them and start a rundeck job to add these new user data in the files ``server/config/realm.properties``. 

I dislike the password to be visible during typing by default.

**Describe the solution you'd like**

1. The minimum idea is just to make the password field to ``<input type="password">`` by default. So you cannot see the typed secret.
2. Even better: use two fields to enter the password, this way you can be sure, there is no typo in the password field.
3. Best for my case, but just nice to have: Let the user select roles on this page as well and add a button "Save local user" to let him save its credentials and roles in the realm.properties just by clicking a button.

**Describe alternatives you've considered**

If there exists something similar already, please give me a hint. Thanks.

**Additional context**

Rundeck Version 3.0.8-20181029

**Comment by sjrd218** [comment]
@ckaiser79 Please download the attached file and rename it to a .jar extension. Then put it in your $RD_BASE/server/lib directory and restart your Rundeck instance. You will have a new encoder on the Password Utility page called "Hidden Input" that satisfies your first and second request. 

We will not implement the 3rd request on the password utility page as if falls more under the category of user management and is outside the scope of the Password Utility page.

[hidden-input-password-encrypter.zip](https://github.com/rundeck/rundeck/files/3023048/hidden-input-password-encrypter.zip)

**Comment by ckaiser79** [comment]
Works thanks for the solution and sorry for the late response.

**Comment by ckaiser79** [comment]
Just an additional comment. As you see in the grahic below, MD5 is gone (which might be ok) but the label is wrong. Anyway using the calculated values works to login.

![grafik](https://user-images.githubusercontent.com/11504021/56279160-e53a9d80-6107-11e9-994b-0d8a41f47b9a.png)

**Comment by sjrd218** [comment]
@ckaiser79 Yeah, I saw that after I sent the file. When 3.0.21 comes out it will have this new form built in and that issue fixed.

**Comment by falloutphil** [comment]
In case it helps anyone else if you want to use this fix on a Debian package install - I found I had to create:
/var/lib/rundeck/lib

And put the renamed zip in there.  I chown'd the directory and jar to rundeck account.

Took me a bit of trial and error to work that out (there is no server directory) :-)

Version tested on: 3.0.9-20181127 

Thanks ver much for the fix - @sjrd218
