### ISSUE TITLE
UI progress bar : display issue

### ISSUE THREAD

**Issue by nmamn** [rundeck/rundeck#4625]
**Describe the bug**
Progress bars dot not display correctly. See screenshots
I have checked #3775 and it seems maybe related, but it's definitely here.
![rdk_activity_tab](https://user-images.githubusercontent.com/20321572/54348968-8e463200-464a-11e9-9606-ba71bbccbd1b.png)
![rdk_log_output](https://user-images.githubusercontent.com/20321572/54348969-8e463200-464a-11e9-8ffb-638e579dbf59.png)

**My Rundeck detail**

* Rundeck version: 3.0.16
* install type: war
* OS Name/version: Ubuntu 16.04
* DB Type/version: mysql

**Desktop (please complete the following information):**
 - OS: Windows 10 / Ubuntu 18.04, same issue
 - Browser : Firefox 65 / Chrome 72, same issue

Thanks a lot,

Nicolas

EDIT : it was already happening in 3.0.13

**Comment by jessemarple** [comment]
I'm fairly certain that this is resolved by 3.1.
