### ISSUE TITLE
SCM Plugin Job are not imported

### ISSUE THREAD

**Issue by csimader** [rundeck/rundeck#4626]
**Describe the bug**
If we modify the Job group on our test instance and commit the changes into Git;
and execute the steps on prod
a.) fetch remote changes
b.) pull remote changes
c.) import remote changes
The job was deleted - but not imported - so we execute task c - import remote changes again 
then the job is created;

**My Rundeck detail**

* Rundeck version: [ 3.0.17 Test and 3.0.16 on Prod]
* install type: [war]
* OS Name/version: [linux 4.1.12-94.3.9.el7uek.x86_64]
* DB Type/version: [mysql]

**To Reproduce**
1. Change Job-group Prod to Prod-stage
2. Click on Commit changes to Git
3. Switch to the other Rundeck instance 
4. Go to the Project
5. Fetch Remote Changes
6. Pull Remote Changes
7. Import Remote Changes
->The renamed job was removed 
8. Import Remote Changes (again)
-> New renamed job are imported successful

**Expected behavior**
Avoid the task 7 - why do we need to import twice?

**Screenshots**
![Prod_import_remote_changes](https://user-images.githubusercontent.com/8567019/54356079-0157a480-465b-11e9-9187-b651a89cfd28.jpg)
![Prod_import_remote_changes_02](https://user-images.githubusercontent.com/8567019/54356088-07e61c00-465b-11e9-906e-5e6a8b08034b.jpg)
![Prod_import_remote_changes_04](https://user-images.githubusercontent.com/8567019/54356096-0d436680-465b-11e9-96d9-86ed2f2e62e6.jpg)
![Prod_instance_jobdefinition_01](https://user-images.githubusercontent.com/8567019/54356114-13394780-465b-11e9-899b-c41825e0cac1.jpg)

**Desktop (please complete the following information):**
 - OS: [Win10]
 - Browser [chrome]

**Additional context**
Is this the normal behavior that the import must be twice if we change the Job-Groupe?
One step for the delete and one for the import?

**Comment by reinerrdeck** [comment]
In my case, GitHub get all Jobs from remote repo and get the first change and later SCM detects the change (SCM offers the option of getting the old or the new version) is the same behavior? At the moment of import always you can select the last change job.

**Comment by csimader** [comment]
No we can't old or new version - we get just the deleted job and the import 
![Prod_import_remote_changes_06](https://user-images.githubusercontent.com/8567019/54514882-8bee1b80-495b-11e9-8157-a0e71071129b.jpg)
After choose the import; just the delete action are done and we have to import the job again;
![Prod_import_remote_changes_07](https://user-images.githubusercontent.com/8567019/54514960-c8217c00-495b-11e9-8c09-3e0a5004de83.jpg)
![Prod_import_remote_changes_08](https://user-images.githubusercontent.com/8567019/54514992-dc657900-495b-11e9-8538-4c8ab5a8fe4d.jpg)
![Prod_import_remote_changes_09](https://user-images.githubusercontent.com/8567019/54515008-ee471c00-495b-11e9-94a4-3dc0777cd9bd.jpg)

**Comment by reinerrdeck** [comment]
This is the expected behavior, because Rundeck saves an internal Job history in a "own layer", maybe in the future, this function can be done in one step.

**Comment by csimader** [comment]
If this is the expected behavior we accept it and will import twice if we rename the group's;
