### ISSUE TITLE
Feature Flag to Disable Community News

### ISSUE THREAD

**Issue by jbanda15** [rundeck/rundeck#4633]
**Describe the behavior expected.**
I have a request, I looking for a way to disable community news on Rundeck 3.X 

**The solution**
Community news button should not work. It will be just an icon. This is for security.

**The screenshots:**
![community news](https://user-images.githubusercontent.com/45765283/54480662-c47de000-4809-11e9-9a35-f17c1cb6a687.png)

**Comment by gschueler** [comment]
closed in https://github.com/rundeck/rundeck/pull/4661
