### ISSUE TITLE
Ldap Fails java.lang.IllegalArgumentException: user should not exist

### ISSUE THREAD

**Issue by ropachec** [rundeck/rundeck#4634]
Hi guys!
After configurate rundeck for ldap integration I'm with error:
I'm use Oracle OUD - LDAP Server

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.security.provisioning.InMemoryUserDetailsManager]: Co
nstructor threw exception; nested exception is java.lang.IllegalArgumentException: user should not exist
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:154)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:122)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:271)
        ... 31 common frames omitted
Caused by: java.lang.IllegalArgumentException: user should not exist

My profile file:

export RDECK_JVM="-Djava.security.auth.login.config=/etc/rundeck/jaas-ldap.conf \
        -Dloginmodule.name=ldap \
        -Drdeck.config=$RDECK_CONFIG \
        -Drundeck.server.configDir=$RDECK_SERVER_CONFIG \
        -Dserver.datastore.path=$RDECK_SERVER_DATA/rundeck \
        -Drundeck.server.serverDir=$RDECK_INSTALL \
        -Drdeck.projects=$RDECK_PROJECTS \
        -Drdeck.runlogs=$RUNDECK_LOGDIR \
        -Drundeck.config.location=$RDECK_CONFIG/rundeck-config.properties \
        -Djava.io.tmpdir=$RUNDECK_TEMPDIR \
        -Drundeck.server.workDir=$RUNDECK_WORKDIR \
        -Dserver.http.port=$RDECK_HTTP_PORT \
        -Drdeck.base=$RDECK_BASE"

My Jaas-ldap.conf file

ldap {
    com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
      debug="true"
      contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
      providerUrl="ldap://server:389"
      bindDn="cn=user,dc=mycompany,dc=com,dc=br"
      bindPassword=""
      authenticationMethod="simple"
      forceBindingLogin="false"
      userBaseDn="ou=Users,o=Rundeck,dc=mycompany,dc=com,dc=br"
      userRdnAttribute="cn"
      userIdAttribute="cn"
      userPasswordAttribute="userPassword"
      userObjectClass="person"
      roleBaseDn="ou=Grupos,o=Rundeck,dc=mycompany,dc=com,dc=br"
      roleNameAttribute="cn"
      roleUsernameMemberAttribute="uniquemembe"
      roleMemberAttribute="uniquemembe"
      roleObjectClass="groupOfUniqueMember"
      cacheDurationMillis="300000"
      supplementalRoles="user"
      reportStatistics="true"
      timeoutRead="10000"
      timeoutConnect="20000"
      nestedGroups="false";
};

Rundeck VERSION : 3.0.5-20180828
Install type: RPM

**Comment by sjrd218** [comment]
Please add `-Drundeck.jaaslogin=true` to your profile and try again.

**Comment by ropachec** [comment]
Thanks man!!! After include the line I had success!!!
