### ISSUE TITLE
Enhancement Request: Search for installed plugins

### ISSUE THREAD

**Issue by skywalke34** [rundeck/rundeck#4636]
**Please describe.**
It can be confusing to the user trying to verify which plugins are installed.
Clicking System > Installed Plugins presents groups of plugins based on Rundeck plugin types.  There isn't a search function to see if a certain plugin is installed (at least not on this page).
Also, just discovered there is some light documentation of the plugins, but wasn't obvious and wasn't exactly sure how to use it.
![image](https://user-images.githubusercontent.com/11443283/54576558-56c6e500-49be-11e9-9f91-6ff769a9f6da.png)

If a user selects System > Find Plugins, one can see that a plugin is installed and the provided plugin type, but attempting to use the search function for a specific name only returned errors. (Screenshot below)
![image](https://user-images.githubusercontent.com/11443283/54577016-c2f61880-49bf-11e9-9ce2-a390182b2f10.png)
Attempted to use the search function, but it returns errors it isn't a valid search field not intuitive to this novice user.  (very likely user error!)(screenshot below)
![image](https://user-images.githubusercontent.com/11443283/54577045-ddc88d00-49bf-11e9-8e3d-b50d62318a08.png)

**Describe the solution you'd like**
Would like to be able to search a specific plugin, or return all plugins containing a certain name. Everything matching Kubernetes plugins, or all *nixy plugins from the Find Plugins page.
![image](https://user-images.githubusercontent.com/11443283/54577210-7bbc5780-49c0-11e9-8ba9-1032abc8685c.png)

Would like the installed plugin list to include all the functions available as they are seen in the job workflows.  For example, I see 20 different Kubernetes node step, and 19 *nixy steps I could use in a job, but there doesn't seem to be a way to see how they are associated within the Kubernetes plugin or *nixy plugin.  If the documentation link for each plugin was here, super bonus points.
![image](https://user-images.githubusercontent.com/11443283/54576786-174cc880-49bf-11e9-9718-9f78c7c97b53.png)

**Describe alternatives you've considered**
Merging the "Find Plugins" and "Installed Plugins" into something plugin focused.. like a.. marketplace.

**Additional context**
This request originated from a need to see if a specific plugin was still installed after container rebuild. 
 Wanted to search for (*nixy / command / try-until).  The only way I could verify it existed was in the jobs > edit job > workflow add step.

**Comment by jessemarple** [comment]
Resolved by 3.1.0
