### ISSUE TITLE
Duplicate run ID's and both executions failing with no log outputs

### ISSUE THREAD

**Issue by manikandaan** [rundeck/rundeck#4637]
Describe the bug
Two executions having same rundeck execution number and both failing with no logs available for the first job triggered after new deployment. 

My Rundeck detail

* Rundeck version: 3.0.13
* install type: docker image
* OS Name/version: ubuntu 16.04
* DB Type/version: mysql

To Reproduce
1. Deploy the rundeck using the docker image and wait for the rundeck to comeup. 
2. First job triggerred either from bamboo or manually from rundeck fails with no log output. There are two executions for same job and happens only after everytime rundeck is deployed. 
3. Both executions does not take long to finish.
4. Workaround is to trigger the same job again which works. 

Expected behavior
Execution must finish properly like any other successful job

Screenshots
screenshots attached
<img width="1433" alt="Screenshot 2019-03-19 at 10 43 35 a m" src="https://user-images.githubusercontent.com/31492741/54601701-9978d380-4a37-11e9-9ee7-1e21f928e158.png">
<img width="1427" alt="Screenshot 2019-03-19 at 10 43 11 a m" src="https://user-images.githubusercontent.com/31492741/54601702-9978d380-4a37-11e9-819c-c61d00af9e32.png">

Desktop (please complete the following information):
 - OS: ios
 - Browser Chrome, Firefox
 - Version 61.0.3163.100,  	65.0.1

Additional context
Not every first deploy after new rundeck deployment fails with this error making the issue intermittent.

**Comment by ProTip** [comment]
Hi @manikandaan ,

When the job fails is there anything relevant looking in the Docker container output(stack trace, etc)?

**Comment by manikandaan** [comment]
Hello,

We store the rundeck logs to S3, and on verifying those for the incomplete/failed ones I could find only the rundeck.execution.log with the mention it is 'incomplete'. On the other hand, a job which has finished successfully had 3 logs associated with it including rundeck.execution.log, output log and the state json log. 

Execution log between a succeeded and failed one is no different except the status. 

snippet from succeeded job execution log file. 
`<executions>
  <execution id='3418989'>
    <jobId>b5b73490-a44c-4f68-9312-3cce9a2c0ac7</jobId>
    <dateStarted>2019-03-22T21:27:04Z</dateStarted>
    <dateCompleted>2019-03-22T21:29:11Z</dateCompleted>
    <status>succeeded</status>
    <outputfilepath>output-3418989.rdlog</outputfilepath>
    <failedNodeList />
    <succeededNodeList />
    <abortedby />
    <cancelled>false</cancelled>
    <argString>-subdomain ****</argString>
    <loglevel>INFO</loglevel>
    <doNodedispatch>false</doNodedispatch>
    <executionType>user</executionType>
    <project>usm-mssp</project>
    <user>admin</user>`

snippet from failed job execution log file

`<executions>
  <execution id='3418137'>
    <jobId>b5b73490-a44c-4f68-9312-3cce9a2c0ac7</jobId>
    <dateStarted>2019-03-22T19:32:04Z</dateStarted>
    <dateCompleted>2019-03-22T19:32:38Z</dateCompleted>
    <status>incomplete</status>
    <outputfilepath>output-3418137.rdlog</outputfilepath>
    <failedNodeList />
    <succeededNodeList />
    <abortedby />
    <cancelled>false</cancelled>
    <argString>-subdomain ****</argString>
    <loglevel>INFO</loglevel>
    <doNodedispatch>false</doNodedispatch>
    <executionType>user</executionType>
    <project>usm-mssp</project>
    <user>admin</user>
    <workflow keepgoing='false' strategy='node-first'>`

![Screenshot 2019-03-25 at 11 34 48 a m](https://user-images.githubusercontent.com/31492741/54917102-f5899f00-4ef2-11e9-85df-4cb53f0285cf.png)
![Screenshot 2019-03-25 at 11 34 15 a m](https://user-images.githubusercontent.com/31492741/54917104-f5899f00-4ef2-11e9-881b-baa2da5a5138.png)

**Comment by manikandaan** [comment]
Were you able to reproduce this error?

**Comment by ProTip** [comment]
Hi @manikandaan ,

We use our Docker images heavily internally for testing and other applications and I don't believe we have run into this before. The closest I have seen has been jobs in-flight failing when the Rundeck is re-deployed as it does not currently gracefully stop jobs when signaled to exit. With the current information we are unable to reproduce the issue, however this may help narrow it down:

* Our Docker image is configured to output all logs to stdout by default. These are separate from the execution logs and would include any errors Rundeck itself encounters. Are you able to detect any errors and/or stack traces in this log when the execution fails?
* Were you able to reproduce this issue on the latest version of Rundeck(currently 3.0.18)?
* Would you be able to post a sanitized yaml export of the job that is failing?

Thanks!

**Comment by manikandaan** [comment]
Hello, 

Think I have found the problem. Rundeck takes few mins to restart and come backup after it says the deployment is complete. Problem was we were triggering a job on rundeck from bamboo assuming the new deployment would have finished but actually it gets kicked off on the existing version and after 3 to 4 mins when Rundeck goes down and comes back the bamboo is still retrying as part of the same job and now it continues on the newer version of rundeck. 

So this is the reason we had same job id's and the logs being flushed since RD is being restarted while a job triggered from bamboo is still in progress. I found this after going through the stacktrace of RD service logs and thanks for pointing out that. I have now mitigated the issue by allowing it to sleep for 3 minutes after RD is being deployed and before any job could be executed on it. 

This boils back to the issue you said where RD does not gracefully stop the running jobs when it is being redeployed, if it does then we might not be facing this problem. Do you know if there will be a fix provided for it? 

Thanks

**Comment by ProTip** [comment]
Hello,

I thought I would just drop a few thoughts in here. Graceful shutdown has come up before, however some users will run jobs that take hours to finish. A lot of provisioning systems will not wait hours for the instance to shutdown..

One solution would be to have the provisioning system disable executions on the Rundeck instance, then poll it until the running executions are zero or some other criteria is met. This could be done through the provisioning scripts, or perhaps a custom Kubernetes controller, or etc.

An enhancement to Rundeck could be the ability to mark jobs as idempotent or otherwise "resumable". Among other benefits, this could allow Rundeck to restart abandoned jobs when it starts up instead of flagging them as failed.
