### ISSUE TITLE
Retry Failed Nodes doesn't bring in failed nodes if Change the Target Nodes option was used

### ISSUE THREAD

**Issue by dabest1** [rundeck/rundeck#4639]
**Describe the bug**
Retry Failed Nodes action does not retry any failed nodes if the job was defined without nodes, but was executed with Change the Target Nodes option enabled and a list of nodes supplied from there.

**My Rundeck detail**
* Rundeck version: 3.0.8-20181029
* install type: rpm
* OS Name/version: Amazon Linux
* DB Type/version: mysql

**To Reproduce**
1. Create a job without any nodes, which runs some script.
2. Run the job with Change the Target Nodes option enabled and supply a list of nodes.
3. Need to have some nodes that will fail.
4. Select Retry Failed Nodes action and no nodes will be selected in new execution.

**Expected behavior**
New execution upon selecting Retry Failed Nodes action, should still bring in failed nodes to retry, even if the nodes are not saved in the job, but where selected at run time.

**Additional context**
Error message:
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{}

**Comment by KroolData** [comment]
We're having same issue on older version and we've been waiting for a fix...
https://github.com/rundeck/rundeck/issues/2942 should be same, I guess.

So this means that the issue hasn't been solved on the latest version yet?
