### ISSUE TITLE
web.xml - roles authentication for 3.0.x

### ISSUE THREAD

**Issue by pandrian** [rundeck/rundeck#4646]
**Describe the bug**
I was happy that the reload of rundeckd service is not required anymore From 3.0.x 
but noticed on newer versions on 3.0.x the web.xml file is no longer possible as I understood. 

we use the web.xml to specify the roles there and then assign those roles in realm.properties for each user. Is there any other way do this now?

Thanks!

**My Rundeck detail**

* Rundeck version: Rundeck 2.10.8-1 
* install type: rpm
* OS Name/version: Centos7
* DB Type/version: mysql

**Comment by sjrd218** [comment]
@pandrian In Rundeck 3.x you no longer have to go through the extra step of configuring roles in the web.xml file. You can configure roles directly in the realm.properties file as documented here: https://docs.rundeck.com/docs/administration/security/authenticating-users.html#propertyfileloginmodule
