### ISSUE TITLE
Rundeck does not recognize profile after authentication in ldap 

### ISSUE THREAD

**Issue by aroldoreis** [rundeck/rundeck#4649]
Hi, Guys
After to make an configuration between Rundeck and LDAP (OUD oracle) when performed the logon, My user doesn't have privileges, same being in the admin groups.

Msg recebive afert logon:

" You have no authorized access to projects.
Contact your administrator. (User roles: user) "

Runcek Version 3.0.16

My jaas-ldap.conf

ldap {
com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule required
debug="true"
contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
providerUrl="ldap://server:389"
bindDn="cn=test,dc=Vinks-QA,dc=com,dc=br"
bindPassword="mypassword"
authenticationMethod="simple"
forceBindingLogin="true"
forceBindingLoginUseRootContextForRoles="true"
userBaseDn="ou=Users,o=Rundeck,dc=Vinks-QA,dc=com,dc=br"
userRdnAttribute="cn"
userIdAttribute="cn"
userPasswordAttribute="userPassword"
userObjectClass="person"
roleBaseDn="ou=Grupos,o=Rundeck,dc=Vinks-QA,dc=com,dc=br"
roleNameAttribute="cn"
roleMemberAttribute="uniquemember"
roleUsernameMemberAttribute="uniquemember"
roleSearchSubtree="true"
roleObjectClass="groupOfUniqueNames"
cacheDurationMillis="300000"
reportStatistics="true"
supplementalRoles="user"
timeoutRead="10000"
timeoutConnect="20000"
nestedGroups="false";

};

My profile rundeck

RDECK_INSTALL="${RDECK_INSTALL:-/var/lib/rundeck}"
RDECK_BASE="${RDECK_BASE:-/var/lib/rundeck}"
RDECK_CONFIG="${RDECK_CONFIG:-/etc/rundeck}"
RDECK_CONFIG_FILE="${RDECK_CONFIG_FILE:-$RDECK_CONFIG/rundeck-config.properties}"
RDECK_SERVER_BASE="${RDECK_SERVER_BASE:-$RDECK_BASE}"
RDECK_SERVER_CONFIG="${RDECK_SERVER_CONFIG:-$RDECK_CONFIG}"
RDECK_SERVER_DATA="${RDECK_SERVER_DATA:-$RDECK_BASE/data}"
RDECK_PROJECTS="${RDECK_PROJECTS:-$RDECK_BASE/projects}"
RUNDECK_TEMPDIR="${RUNDECK_TEMPDIR:-/tmp/rundeck}"
RUNDECK_WORKDIR="${RUNDECK_TEMPDIR:-$RDECK_BASE/work}"
RUNDECK_LOGDIR="${RUNDECK_LOGDIR:-$RDECK_BASE/logs}"
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx4096m -Xms4096m -XX:MaxMetaspaceSize=256m -server}"
RDECK_TRUSTSTORE_FILE="${RDECK_TRUSTSTORE_FILE:-$RDECK_CONFIG/ssl/truststore}"
RDECK_TRUSTSTORE_TYPE="${RDECK_TRUSTSTORE_TYPE:-jks}"
JAAS_LOGIN="${JAAS_LOGIN:-true}"
JAAS_CONF="${JAAS_CONF:-$RDECK_CONFIG/jaas-loginmodule.conf}"
LOGIN_MODULE="${LOGIN_MODULE:-RDpropertyfilelogin}"
RDECK_HTTP_PORT=${RDECK_HTTP_PORT:-4440}
RDECK_HTTPS_PORT=${RDECK_HTTPS_PORT:-4443}

export RDECK_JVM="-Djava.security.auth.login.config=/etc/rundeck/jaas-ldap.conf 
-Dloginmodule.name=ldap 
-Drundeck.jaaslogin=true 
-Drdeck.config=$RDECK_CONFIG 
-Drundeck.server.configDir=$RDECK_SERVER_CONFIG 
-Dserver.datastore.path=$RDECK_SERVER_DATA/rundeck 
-Drundeck.server.serverDir=$RDECK_INSTALL 
-Drdeck.projects=$RDECK_PROJECTS 
-Drdeck.runlogs=$RUNDECK_LOGDIR 
-Drundeck.config.location=$RDECK_CONFIG/rundeck-config.properties 
-Djava.io.tmpdir=$RUNDECK_TEMPDIR 
-Drundeck.server.workDir=$RUNDECK_WORKDIR 
-Dserver.http.port=$RDECK_HTTP_PORT 
-Drdeck.base=$RDECK_BASE"

My ldif.file 

 dn: cn=admin,ou=Grupos,o=Rundeck,dc=mycompany,dc=com,dc=br objectClass: groupofuniquenames objectClass: top uniquemember: cn=80557658,ou=Users,o=Rundeck,dc=mycompany,dc=com,dc=br

dn: cn=architect,ou=Grupos,o=Rundeck,dc=mycompany,dc=com,dc=br objectClass: groupofuniquenames objectClass: top uniquemember: cn=80020676,ou=Users,o=Rundeck,dc=mycompany,dc=com,dc=br

dn: cn=build,ou=Grupos,o=Rundeck,dc=mycompany,dc=com,dc=br objectClass: groupofuniquenames objectClass: top uniquemember: cn=80020676,ou=Users,o=Rundeck,dc=mycompany,dc=com,dc=br

dn: cn=deploy,ou=Grupos,o=Rundeck,dc=mycompany,dc=com,dc=br objectClass: groupofuniquenames objectClass: top uniquemember: cn=80020676,ou=Users,o=Rundeck,dc=mycompany,dc=com,dc=br

dn: cn=operators,ou=Grupos,o=Rundeck,dc=mycompany,dc=com,dc=br objectClass: groupofuniquenames objectClass: top uniquemember: cn=80020676,ou=Users,o=Rundeck,dc=mycompany,dc=com,dc=br

dn: cn=user,ou=Grupos,o=Rundeck,dc=mycompany,dc=com,dc=br objectClass: groupofuniquenames objectClass: top uniquemember: cn=80020676,ou=Users,o=Rundeck,dc=mycompany,dc=com,dc=br

**Comment by aroldoreis** [comment]
update.

**Comment by ropachec** [comment]
Hi Aroldo!

Set the parameters:

forceBindingLoginUseRootContextForRoles="true"
nestedGroups=true

Att: Rogério Pacheco :)

**Comment by aroldoreis** [comment]
Thank Rogerio, after altered. Now it's possible t to make correct login
