### ISSUE TITLE
api job import with dupeOption=update issue

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#4662]
When trying to import a job using the API with the dupeOtion=update and preserve UUID getting an error that the job UUID already exists instead of updating it.

Here is the output after running the command

cwf@cwf-Inspiron-15-7000-Gaming:~/rundeck3017_2$ curl POST -F xmlBatch=@"jobs2.xml" -H X-Rundeck-Auth-Token:duq8QkHnjTkMG14a85MJIA7Dj5QUHkHI http://localhost:4441/api/30/project/api_export/jobs/import -H dupeOption=update -H uuidOption=preserve
curl: (6) Could not resolve host: POST
<result success='true' apiversion='30'>
  <succeeded count='0' />
  <failed count='1'>
    <job index='1'>
      <name>test_job2</name>
      <group></group>
      <project>api_export</project>
      <error>Cannot create a Job with UUID bda32945-06fa-48f2-9bbf-fdf0c0983e7e: a Job already exists with this UUID. Change the UUID or delete the other Job.
Validation errors: Cannot create a Job with UUID bda32945-06fa-48f2-9bbf-fdf0c0983e7e: a Job already exists with this UUID. Change the UUID or delete the other Job.</error>
    </job>
  </failed>
  <skipped count='0' />

**Comment by carlosrfranco** [comment]
Try to change the sending of the options as form parameters (using -F) and not as header parameters (-H).
`curl -X POST -F xmlBatch=@"jobs2.xml" -H X-Rundeck-Auth-Token:duq8QkHnjTkMG14a85MJIA7Dj5QUHkHI http://localhost:4441/api/30/project/api_export/jobs/import -F dupeOption=update -F uuidOption=preserve`

**Comment by cwaltherf** [comment]
Thank you Carlos, that worked!
