### ISSUE TITLE
Use Global Variable to webhook

### ISSUE THREAD

**Issue by alphainets** [rundeck/rundeck#4664]
I tried to use global variable to pass the server ip to api webhook in rundeck, but it is not working.

global variable is added to /var/rundeck/projects/<project>/etc/project.properties

I can echo the global variable by echo $(global.<variable>)

but when adding to webhook, it is not working
http://${global.<variable>}/

Am I doing this correctly? or this feature is not currently supported? 

I saw the last update #2055 said it is okay, but not sure why my case is not working.

Thanks for the help~

![image](https://user-images.githubusercontent.com/33946142/55208306-bfad2900-5218-11e9-8d13-9b644d2758eb.png)

**Comment by reinerrdeck** [comment]
Duplicate: https://github.com/rundeck/rundeck/issues/2055
