### ISSUE TITLE
Default DB change

### ISSUE THREAD

**Issue by 11sma** [rundeck/rundeck#4665]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**
The default db is H2. If rundeck crashes the db file may be corrupted after this. Then if you have'not backup you lose all. 

**Describe the solution you'd like**
The default db configuration be a postgres or mysql db, more stable.

**Describe alternatives you've considered**
Do a backup of h2 db daily, but can be difficult to assure the db is corrupted when the error occurs.

**Additional context**
Sorry if similar feature request exists or worse... it's implemented that default (in my version June 2018 was not).

**Comment by reinerrdeck** [comment]
Hi 11sma,

H2 database is only for development and testing. New versions have a message that warns about the H2 use and recommends the move to a more robust database engine in production environments.

![Screenshot_1](https://user-images.githubusercontent.com/43051294/55258247-13cc0380-5241-11e9-89a1-3b943485b913.png)

![Screenshot_2](https://user-images.githubusercontent.com/43051294/55258253-16c6f400-5241-11e9-93ae-8cda93357ff5.png)

Regards.

**Comment by 11sma** [comment]
Didn't see that... Thanks!!
