### ISSUE TITLE
Jobs are not getting replicated to Seconday Rundeck from Primary

### ISSUE THREAD

**Issue by msachikanta** [rundeck/rundeck#4668]
**Describe the bug**
I have configured rundeck database relpication (Master-Slave), When I created a new job in Primary its not getting replicated to Secondary Rundeck.

**My Rundeck detail**
* Rundeck version: 2.11.5-1
* install type: rpm
* OS Name/version: Redhat Enterprise Linux 7.5
* DB Type/version: mariadb

**Comment by reinerrdeck** [comment]
Hi @msachikanta 

Seems a database problem instead Rundeck problem. Check your database replication setup.

Greetings.
