### ISSUE TITLE
Unable to pass options/arguments via json RestAPI

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#4683]
I am trying to use Json with Rest API to do Post with Json paylod/body which contains the job options/arguments. I understand the minimum required api version is 18 according to this document https://docs.rundeck.com/docs/api/  but no matter what I do I am unable to pass the results to the job. Could you please review the images below and let me know what am I doing wrong -?

Rundeck Version: 3.0.17-20190311
OS: Centos 7

![image](https://user-images.githubusercontent.com/20629911/55484430-55600400-55dd-11e9-992d-80ce78605423.png)

![image](https://user-images.githubusercontent.com/20629911/55484437-5abd4e80-55dd-11e9-9ba5-aa1db6f4b7c2.png)

![image](https://user-images.githubusercontent.com/20629911/55484448-5f820280-55dd-11e9-9ebe-4b7a1ea93c8d.png)

![image](https://user-images.githubusercontent.com/20629911/55484451-61e45c80-55dd-11e9-90c3-de5dd79c52f7.png)

![image](https://user-images.githubusercontent.com/20629911/55484463-64df4d00-55dd-11e9-80dc-5da617117942.png)

```
#initialize hash
$Params =@{}
$ops    =@{}

#Add properties to OPS with hash value
$ops.optA='TestFromRestAPIA'
$ops.optB='TestFromRestAPIB'

#Add properties to Params and associated OPS to options property
$Params.loglevel='DEBUG'
$Params.options=$ops

#produce json output -> For Debug purposes only.
$Params  |ConvertTo-json


#use Invoke-RestMthod Post with Body 
$(Invoke-RestMethod -uri "http://<rundeckserver>:4440/api/24/job/409b0a63-bb53-4cad-af11-b7c982c679b0/run?authtoken=<user-api-token>" -Method Post -Body {$Params  |ConvertTo-Json}  -ContentType 'application/json')|select * |fl

 

Thank you!
HS
```

**Comment by reinerrdeck** [comment]
Hi,

I did make a little example with this job definition:

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='opt1' value='hello' />
        <option name='opt2' value='world' />
      </options>
    </context>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>6ea276a1-67ee-4111-bf99-dcb392e8940d</id>
    <loglevel>INFO</loglevel>
    <name>JobTest</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "${option.opt1} ${option.opt2}"</exec>
      </command>
    </sequence>
    <uuid>6ea276a1-67ee-4111-bf99-dcb392e8940d</uuid>
  </job>
</joblist>
```

Here how to run the job using options with Curl:

`curl --data-urlencode "argString=-opt1 hello -opt2 there" http://localhost:4440/api/30/job/6ea276a1-67ee-4111-bf99-dcb392e8940d/run?authtoken=zGklTf7lmwVDqWPp7FXBKULxSozbZvv0`

And if you go to Activity section you can see that execution was succeeded:

![issue](https://user-images.githubusercontent.com/43051294/55599626-02966180-572f-11e9-84a7-cf7e3d73566e.png)

Hope it helps!

**Comment by reinerrdeck** [comment]
Maybe you need to pass the options with argString:

"argString=-opt1 hello -opt2 there"

Using curl, for example, pass it this:

`curl --data-urlencode "argString=-opt1 hello -opt2 there" http://localhost:4440/api/30/job/6ea276a1-67ee-4111-bf99-dcb392e8940d/run?authtoken=zGklTf7lmwVDqWPp7FXBKULxSozbZvv0`

**Comment by JesusRo** [comment]
Hi guys,
I was using that API call for a long time and did not have that issue (calling from nodejs, php & curl), however was able to reproduce with the ps code provided.
It's something with the way $Params is build
As a test, you can do 
```
#initialize hash
$Params =@{}
$ops    =@{}

#Add properties to OPS with hash value
$ops.optA='TestFromRestAPIA'
$ops.optB='TestFromRestAPIB'

#Add properties to Params and associated OPS to options property
$Params.loglevel='DEBUG'
$Params.options=$ops

#produce json output -> For Debug purposes only.
$Params  | ConvertTo-json

#Do not use the object, just type a json string
$Params2 = '{"options":{"optA":"TestFromRestAPIA","optB":"TestFromRestAPIB"},"loglevel":"DEBUG"}'
$Params2

#use Invoke-RestMthod Post with Body 
$(Invoke-RestMethod -uri "http://<rundeckserver>:4440/api/24/job/409b0a63-bb53-4cad-af11-b7c982c679b0/run?authtoken=<user-api-token>" -Method Post -Body $Params2  -ContentType 'application/json')|select * |fl
```

With that, I have the correct answer
```xml
...
                    <name>Wait</name>
                           <group></group>
                           <project>PlayGround</project>
                           <description></description>
                           <options>
                             <option name="Option2" value="Default2" />
                             <option name="Option1" value="Default1" />
                             <option name="optA" value="TestFromRestAPIA" />
                             <option name="optB" value="TestFromRestAPIB" />
                           </options>
                         </job>
                         <description>echo This is the first option @option.Option1@
                     echo This is the second option @option.Option2@ [... 2 steps]</description>
                         <argstring>-Option1 Default1 -Option2 Default2 -optA TestFromRestAPIA -optB TestFromRestAPIB</argstring>
                       </execution>
                     </executions>
...
```

**Comment by hs-hub-world** [comment]
Thanks for the reply, @reinerrdeck & @JesusRo. In case anyone else is interested the solution for PS is to use the -compress option and change the curly braces to parenthesis.   This totally works:

#initialize hash
$Params =@{}
$ops    =@{}

#Add properties to OPS with hash value
$ops.optA='TestFromRestAPIA'
$ops.optB='TestFromRestAPIB'

#Add properties to Params and associated OPS to options property
$Params.loglevel='DEBUG'
$Params.options=$ops

#produce json output -> For Debug purposes only.
$Params  |ConvertTo-json -Compress

#use Invoke-RestMthod Post with Body 
$(Invoke-RestMethod -uri "http://<rundeckserver>:4440/api/24/job/409b0a63-bb53-4cad-af11-b7c982c679b0/run?authtoken=<user-api-token>" -Method Post -Body ($Params | ConvertTo-json -Compress)  -ContentType 'application/json')|select * |fl

##Optionally you could also do this
$Params  = $Params  |ConvertTo-json -Compress
$(Invoke-RestMethod -uri "http://<rundeckserver>:4440/api/24/job/409b0a63-bb53-4cad-af11-b7c982c679b0/run?authtoken=<user-api-token>" -Method Post -Body $Params  -ContentType 'application/json')|select * |fl

 Thanks again for your help on this, guys!
