### ISSUE TITLE
Internal Server Error after Upgrade from 3.0.16 to 3.0.19

### ISSUE THREAD

**Issue by mirkoknoll** [rundeck/rundeck#4685]
**Describe the bug**
Trying to go the a projects job causes error 500:

Handler dispatch failed; nested exception is java.lang.IncompatibleClassChangeError: Method com.dtolabs.rundeck.core.authorization.providers.EnvironmentalContext.forProject(Ljava/lang/String;)Ljava/util/Set; must be InterfaceMethodref constant

Same problem with 3.0.17, last running version 3.0.16

**My Rundeck detail**

* Rundeck version: 3.0.19-20190327
* install type: war
* OS Name/version: Debian 9
* DB Type/version: H2 embedded database

**To Reproduce**
1. Go to Projects
2. Click on every existing project
3. See error

**Expected behavior**
See existing jobs in project

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 73

**Additional context**
Error 500: Internal Server Error
URI
/project/< project >/jobs
Class
java.lang.IncompatibleClassChangeError
Message
Handler dispatch failed; nested exception is java.lang.IncompatibleClassChangeError: Method com.dtolabs.rundeck.core.authorization.providers.EnvironmentalContext.forProject(Ljava/lang/String;)Ljava/util/Set; must be InterfaceMethodref constant
Caused by
Method com.dtolabs.rundeck.core.authorization.providers.EnvironmentalContext.forProject(Ljava/lang/String;)Ljava/util/Set; must be InterfaceMethodref constant

    Line | Method
->>  137 | authorizeProjectResources in org.rundeck.app.authorization.RundeckAuthContextEvaluator
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    413 | doCall           in rundeck.services.FrameworkService$_authorizeProjectResources_closure9
|     99 | time . . . . . . in com.codahale.metrics.Timer
|     57 | withTimer        in org.grails.plugins.metricsweb.MetricService
|    412 | authorizeProjectResources in rundeck.services.FrameworkService
|    668 | listWorkflows    in rundeck.controllers.MenuController
|    467 | jobsFragment . . in     ''
|    296 | jobs             in     ''
|    223 | invoke . . . . . in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke           in org.grails.core.DefaultGrailsControllerClass
|     90 | handle . . . . . in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch       in org.springframework.web.servlet.DispatcherServlet
|    901 | doService . . .  in     ''
|    970 | processRequest   in org.springframework.web.servlet.FrameworkServlet
|    861 | doGet . . . . .  in     ''
|    846 | service          in     ''
|    865 | handle . . . . . in org.eclipse.jetty.servlet.ServletHolder
|   1655 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    215 | doFilter . . . . in org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | run . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs             in javax.security.auth.Subject
|    105 | doFilter . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     55 | doFilterInternal in org.springframework.boot.web.filter.ApplicationContextHeaderFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke           in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter . . . . in     ''
|    331 | doFilter         in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter . . . . in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter         in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilterInternal in grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter         in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter         in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter         in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run              in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs . . . . . . in javax.security.auth.Subject
|    105 | doFilter         in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter         in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter         in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter         in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter         in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal in org.springframework.security.web.FilterChainProxy
|    177 | doFilter . . . . in     ''
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal in org.grails.web.filters.HiddenHttpMethodFilter
|   1642 | doFilter         in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    533 | doHandle . . . . in org.eclipse.jetty.servlet.ServletHandler
|    146 | handle           in org.eclipse.jetty.server.handler.ScopedHandler
|    548 | handle . . . . . in org.eclipse.jetty.security.SecurityHandler
|    132 | handle           in org.eclipse.jetty.server.handler.HandlerWrapper
|    257 | nextHandle . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1595 | doHandle         in org.eclipse.jetty.server.session.SessionHandler
|    255 | nextHandle . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1317 | doHandle         in org.eclipse.jetty.server.handler.ContextHandler
|    203 | nextScope . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|    473 | doScope          in org.eclipse.jetty.servlet.ServletHandler
|   1564 | doScope . . . .  in org.eclipse.jetty.server.session.SessionHandler
|    201 | nextScope        in org.eclipse.jetty.server.handler.ScopedHandler
|   1219 | doScope . . . .  in org.eclipse.jetty.server.handler.ContextHandler
|    144 | handle           in org.eclipse.jetty.server.handler.ScopedHandler
|    132 | handle . . . . . in org.eclipse.jetty.server.handler.HandlerWrapper
|    531 | handle           in org.eclipse.jetty.server.Server
|    352 | handle . . . . . in org.eclipse.jetty.server.HttpChannel
|    260 | onFillable       in org.eclipse.jetty.server.HttpConnection
|    281 | succeeded . . .  in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    102 | fillable         in org.eclipse.jetty.io.FillInterest
|    291 | onFillable . . . in org.eclipse.jetty.io.ssl.SslConnection
|    151 | succeeded        in org.eclipse.jetty.io.ssl.SslConnection$3
|    102 | fillable . . . . in org.eclipse.jetty.io.FillInterest
|    118 | run              in org.eclipse.jetty.io.ChannelEndPoint$2
|    333 | runTask . . . .  in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    310 | doProduce        in     ''
|    168 | tryProduce . . . in     ''
|    126 | run              in     ''
|    366 | run . . . . . .  in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    762 | runJob           in org.eclipse.jetty.util.thread.QueuedThreadPool
|    680 | run . . . . . .  in org.eclipse.jetty.util.thread.QueuedThreadPool$2
^    836 | run              in java.lang.Thread

**Comment by mirkoknoll** [comment]
Looks like an issue with used SAPJVM, with OpenJDK it is working. :-(

**Comment by lookshe** [comment]
Having the same problem with 3.0.20 using OpenJDK 11 in Ubuntu 18.04.
Switching to OpenJDK 8 solved the issue.
