### ISSUE TITLE
Adding vault-plugin configuration to the template

### ISSUE THREAD

**Issue by dwardu89** [rundeck/rundeck#4692]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**
Currently the only way to override the storage template file is to mount the volume and overwrite the existing properties files to get the values passed in. I currently want to add vault-plugin to the rundeck docker image. I want to run it 

**Describe the solution you'd like**
The solution would be to add the configuration in the rundeck-config-storage.properties and have remco set it up.

**Describe alternatives you've considered**
Mounting the configuration directly and ignoring the remco templates outright.

**Additional context**

**Comment by ltamaster** [comment]
Hi @dwardu89 
Did you check this example?
https://github.com/rundeck-plugins/vault-storage/tree/master/test/docker/dockers/rundeckvault/remco/templates

Luis
