### ISSUE TITLE
Python script execution crash if uses Chinese characters

### ISSUE THREAD

**Issue by reinerrdeck** [rundeck/rundeck#4695]
**Describe the bug**
At the moment to execute a Python script that uses Chinese characters the job fails with this error  (called directly in step or inline script):

![error](https://user-images.githubusercontent.com/43051294/55760832-4fc64c00-5a2b-11e9-993c-1a903bd479ec.png)

But if I call the script directly on Powershell:

![ps](https://user-images.githubusercontent.com/43051294/55760947-ac296b80-5a2b-11e9-958a-cdc1dc3465cc.png)

Tried without success:

1) Change Windows language/charset.
2) This conf: https://github.com/rundeck/rundeck/commit/cb97644fcd42de6682e2f114143ea4f689154c9d
3) And this configuration: https://groups.google.com/d/msg/rundeck-discuss/3lVTgfu_7EA/v3FxJL7jAwAJ (passing _-Dfile.encoding_ on RDECK_JVM variable in profile.bat)

**My Rundeck detail**

* Rundeck version: 3.0.19
* install type: WAR
* OS Name/version: Windows 10/ Windows Server
* DB Type/version: H2

**To Reproduce**

1. Run this Python script directly on Powershell:

```
print(系列的註冊機)
```

Or this:

```
import sys

original=("系列的註冊機")
convert=(original.encode('utf-8'))
final=convert.decode("utf-8", "backslashreplace")

print(final)
```

2. Call the script from a Rundeck Job like this:
```
<joblist>
  <job>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>199f91a9-c0e9-4c1f-8a6e-bf6499e6637b</id>
    <loglevel>INFO</loglevel>
    <name>Test1</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>python c:\scripts\main.py</exec>
      </command>
    </sequence>
    <uuid>199f91a9-c0e9-4c1f-8a6e-bf6499e6637b</uuid>
  </job>
</joblist>
```

Or this:

```
<joblist>
  <job>
    <defaultTab>output</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>b5608082-8506-4120-8a16-16eaf9411416</id>
    <loglevel>INFO</loglevel>
    <multipleExecutions>true</multipleExecutions>
    <name>Test2</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>false</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <script><![CDATA[python c:\scripts\main.py]]></script>
        <scriptargs />
      </command>
    </sequence>
    <uuid>b5608082-8506-4120-8a16-16eaf9411416</uuid>
  </job>
</joblist>
```

**Expected behavior**
Chinese characters must show correctly.

**Desktop (please complete the following information):**
 - OS: Windows 10 1809 64 bit.
 - Browser Mozilla Firefox 66.0.2

**Additional context**
Issue related: https://groups.google.com/forum/?nomobile=true#!topic/rundeck-discuss/dDLQhy9wpAQ

And maybe this: https://github.com/rundeck/rundeck/issues/4291

**Comment by ProTip** [comment]
I don't believe this is a bug per say, just an oddity in how consoles, code pages, and Python interact on Windows.

Interestingly on my system Powershell defaults to code page `437` and the print does not work:
```
PS C:\Users\gregz\Downloads\rundeck> chcp
Active code page: 437
PS C:\Users\gregz\Downloads\rundeck> python .\main.py
Traceback (most recent call last):
  File ".\main.py", line 2, in <module>
    print("\u7cfb\u5217\u7684\u8a3b\u518a\u6a5f")
  File "C:\Users\gregz\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 0-5: character maps to <undefined>
```

However, if I change this to `utf8`, `65001`:
```
PS C:\Users\gregz\Downloads\rundeck> chcp 65001
Active code page: 65001
PS C:\Users\gregz\Downloads\rundeck> python .\main.py
■■■■■■
```

Powershell still will not render it, but I believe that's a font issue.

## Fix
Tell Python to output utf8:
```
set PYTHONIOENCODING=utf8 && python main.py
```

Rundeck will also need to be run with `-Pfile.encoding=utf8` at least on my system or the log output will not render the characters in the browser, nor will it for any logs generated prior to setting the encoding to `utf8`.

**Comment by reinerrdeck** [comment]
Awesome @ProTip that works nicely.

Thanks a lot!
