### ISSUE TITLE
Rundeck - OnPrem to AWS migration

### ISSUE THREAD

**Issue by agnivla** [rundeck/rundeck#4696]
Issue type: Bug report/Enhancement Request

**My On-Prem Rundeck detail**

* Rundeck version: 2.6.9
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version: Rhel 6.9
* DB Type/version: mysql? postgres? h2?.. H2

**Expected Behavior**
I am working in a project to migrate on-prem rundeck into Aws. Planning to leverage mysql db for HA.
* Rundeck version: 2.11.9
* install type: (rpm,deb,war,launcher?) launcher
* OS Name/version: Ec2
* DB Type/version: mysql? postgres? h2?:  Mysql RDS

As per the documentation it looks like we can only store projects , keys details into db but not the resources (nodes,jobs etc) related to the project. Could you kindly confirm the same? 
If my understanding is correct then we also need to take backup of file system where nodes and jobs info get stored ? How can we make approach for HA incase rundeck server ec2 terminates.

**Comment by reinerrdeck** [comment]
That's correct @agnivla if you are using some XML file to define your nodes you must be back up, to HA features you need an Enterprise version, check that:

https://docs.rundeck.com/3.0.20/administration/cluster/index.html

Hope it help!

**Comment by rtkgjacobs** [comment]
Setup Git / SCM sync as an alternative approach perhaps. 

https://docs.rundeck.com/docs/administration/projects/scm/git-plugin.html
