### ISSUE TITLE
ENH: Include file attachments in E-mail notifications

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#4706]
**Is your feature request related to a problem? Please describe.**

Use case: 
Job gathers data and creates a file with the required info.  
It is desired to have that file attached to the "OnSuccess" ( or other )  notification e-mail. 

**Describe the solution you'd like**

Be able to add an external file ( a specific file located in the target server ) as an attachment, to the e-mail notification. 

**Additional context**
There is a similar feature, eg., in Jenkins to have a File produced during execution, attached as a "post Build" action.

**Comment by G3NSVRV** [comment]
+1
