### ISSUE TITLE
Cognito MFA in front of Rundeck - Logout users 

### ISSUE THREAD

**Issue by drodriguez-rundeck** [rundeck/rundeck#4707]
After setting up Cognito MFA auth in front of Rundeck using Amazon ALB,  users are unable to log out properly from Rundeck, the user session does not expire and is able to log back in without typing credentials.

According to ALB documentation, "when an application needs to log out an authenticated user, it should set the expiration time of the authentication session cookie to -1 and redirect the client to the IdP logout endpoint (if the IdP supports one)"

All of these things have to be done by the application itself (Rundeck)

**Describe the solution you'd like**
Be able to log out from Rundeck and get user's session killed.

**Comment by joshgreenwood15** [comment]
@drodriguez-rundeck I am very interested in how your setup works with AWS cognito. I have been trying to implement something very similar. Any advice or suggestions would be greatly appreciated thanks
