### ISSUE TITLE
Upgrade to platimum

### ISSUE THREAD

**Issue by wggit** [rundeck/rundeck#4713]
**Describe the bug**
Currently we are using community edition. However, we might be thinking of upgrading to platinum version. Does anyone know what does it involves in upgrade process?
Thank you in advance.

**My Rundeck detail**

* Rundeck version: 3.0.17
* install type: war
* OS Name/version:RHL
* DB Type/version: oracle

**To Reproduce**
N/A

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
 N/A

**Additional context**
N/A

**Comment by jorn-k** [comment]
This should be relatively easy for you.  Best bet is too install the Rundeck Enterprise binary anew, and move your projects over to it. The sales and onboarding folks can ensure you are guided through the process. Have you spoken to anybody in the Sales org at Rundeck to discuss? If not, tell me where you are located and I'd be happy to help make an introduction.

**Comment by wggit** [comment]
Thank you Jorn. Yes we have reached out to sales folks.
