### ISSUE TITLE
Every log load taking ~30 seconds

### ISSUE THREAD

**Issue by Ultimation** [rundeck/rundeck#4716]
**Describe the bug**
After a job, going through any log line, regardless of the length of that through the gui is taking approximately 30 seconds to load. 

I can see the post for /execution/tailExecutionOutput/16354.json appearing in the rundeck access logs at the *end* of the 30 seconds.

The job log is about 10M in total. 

**My Rundeck detail**

* Rundeck version: 3.0.8
* install type: rpm
* OS Name/version: Centos 7.5
* DB Type/version: mysql

**Expected behavior**
Not wait 30 seconds

**Additional context**
![image](https://user-images.githubusercontent.com/873755/56153365-e5bf2100-5fad-11e9-98c3-cd031788d94b.png)

Manually getting https://<URL>?/execution/tailExecutionOutput/16354.json?offset=0&maxlines=500&compacted=true&nodename=<node>&stepctx=2 
also suffers the 30 second delay.

**Comment by Ultimation** [comment]
Restarting the service decreased this time to about 10 seconds.

**Comment by Ultimation** [comment]
Upgraded to latest hotfix today Rundeck 3.0.22-20190512 and issue is still there. Also upgraded system memory as I saw it was getting busy. 

Using the "log output" tab with by node view is much faster and our workaround for now.

**Comment by fdevans** [comment]
Check out our latest release 3.2.7 with an updated Event Viewer in Beta.
