### ISSUE TITLE
log4j2 support

### ISSUE THREAD

**Issue by chrislan16** [rundeck/rundeck#4720]
Issue type: Enhancement Request

**My Rundeck detail**

* Rundeck version: 3.0.20-20190408
* install type: deb
* OS Name/version: Debian 9.8
* DB Type/version: h2 (default)

**Expected Behavior**
I want to use json format logging in combination with ELK.
Is there a plan to upgrade to log4j2 in the near future?

**How to Reproduce**
In log4j.properties:
Edit:
log4j.logger.com.dtolabs.rundeck.core.authorization=info, audit, audit-json
Add:
log4j.appender.audit-json=org.apache.log4j.FileAppender
log4j.appender.audit-json.file=/var/log/rundeck/rundeck.audit.json
log4j.appender.audit-json.append=true
log4j.appender.audit-json.layout=org.apache.log4j.JsonLayout

During rundeck restart you get folloging log entry in service.log:
log4j:ERROR Could not instantiate class [org.apache.log4j.JsonLayout].

**Comment by abraxxa** [comment]
What's the status of this issue? We'd really need structured logging support. Thanks!

**Comment by gschueler** [comment]
added in rundeck 3.3.0
