### ISSUE TITLE
Chain "Jobs" (Not Job step)

### ISSUE THREAD

**Issue by devvvy** [rundeck/rundeck#4721]
So I understand in **"Job"** definition we can define **"Workflow steps"**, that workfow steps can be executed one after another: 
https://docs.rundeck.com/docs/manual/creating-job-workflows.html

However, can we chain "Jobs"? One job start only when dependent jobs completed (Successfully or failed)?
Thanks

**Comment by reinerrdeck** [comment]
Yes, you can do it via API / RD CLI wrapped on some bash script or creating a "Parent Job"  (that verify the dependencies) execute the "Child Jobs" via Job Reference.

**Comment by devvvy** [comment]
Thanks yes !

**Comment by yyx100** [comment]
yes.  you can setup a job of jobs to do this.  I believe if you pick "Sequential" strategy , and "stop at fail step" will achieve what you are describing.
