### ISSUE TITLE
WinRMcpPython generate wrong filepath thus execution fails

### ISSUE THREAD

**Issue by iandrianov77** [rundeck/rundeck#4723]
**Describe the bug**
My job calls a script from url to be executed on windows node. 
![image](https://user-images.githubusercontent.com/43052149/56328512-2a74c480-6134-11e9-9860-9f57c96b4501.png)

winrm-filecopier.py actually copied file to windows host but with bug. The path to temp file script report is not actual path where temp script has been created. 

this is error output
```
[workflow] beginExecuteNodeStep(rundeck3ps): NodeDispatch: ScriptURLItem{label='get-cluster_status, urlString='http://rundeck3ps.illumio.com/config/ocp/powershell/CLUSTER_DEPLOYEMENT_JOBS/get-cluster_status.psm1'}
Requesting URL: http://rundeck3ps.illumio.com/config/ocp/powershell/CLUSTER_DEPLOYEMENT_JOBS/get-cluster_status.psm1
[WinRMcpPython] executing: [python, -u, /var/lib/rundeck/libext/cache/py-winrm-plugin-1.0.10/winrm-filecopier.py, ${node.hostname}, /var/lib/rundeck/var/cache/ScriptURLNodeStepExecutor/a7bfc7822a51ffa483a389c9b99c78e2e6970010.temp, C:\WINDOWS\TEMP\141-1822-rundeck3ps-a7bfc7822a51ffa483a389c9b99c78e2e6970010.temp.ps1]
[WinRMcpPython]: result code: 0
[WinRMcpPython]: result filepath: C:\WINDOWS\TEMP\141-1822-rundeck3ps-a7bfc7822a51ffa483a389c9b99c78e2e6970010.temp.ps1
[WinRMPython] execCommand started, command: powershell -file 'C:\WINDOWS\TEMP\141-1822-rundeck3ps-a7bfc7822a51ffa483a389c9b99c78e2e6970010.temp.ps1 -loopbackid 1231231231232342342qw3'
[WinRMPython] executing: [[python, -u, /var/lib/rundeck/libext/cache/py-winrm-plugin-1.0.10/winrm-exec.py, ${node.hostname}]]

```

![image](https://user-images.githubusercontent.com/43052149/56328726-2301eb00-6135-11e9-9380-347c2fcb740e.png)

**My Rundeck detail**

* Rundeck version:3.0.12-20190114 
* install type: deb
* OS Name/version: ubuntu 18.04

**Comment by ltamaster** [comment]
Hi @iandrianov77 ,
Which python version are you using?

Thanks
Luis

**Comment by ltamaster** [comment]
@iandrianov77 ,

You can try the new version of the plugin, I have another case that was fixed with the last one.

Luis

**Comment by iandrianov77** [comment]
Thanks for getting back Luis, just to save research time – would you have a “one-liner” code to update plugin?

**Comment by ltamaster** [comment]
You need to download it from the release page and copy it to `libext` folder on rundeck installation 
https://github.com/rundeck-plugins/py-winrm-plugin/releases/tag/2.0.1

**Comment by iandrianov77** [comment]
Luis – that helped. Thank you.
