### ISSUE TITLE
wrong message in cluster mode

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#4727]
Issue type: Bug report
**Related to #3805**

**My Rundeck detail**

* Rundeck version: 3.0.20
* install type: rpm
* OS Name/version: centos7
* DB Type/version: mysql 5.7, oracle 12
* Browser: FF 66.0.2 (64-bit) - Chrome 74.0.3729.75 (Build oficial) beta (64 bits)

**Pictures:** left side: instance1; right side: instance2

**Expected Behavior**
To work as when a "partial log" plugin is configured.
(Maybe a button to go to `Log Output` tab is needed here)

![image (1)ed](https://user-images.githubusercontent.com/34582874/56368531-9a7f5b00-61c5-11e9-9697-fe493fda588c.png)

When click in the `Log Output` tab
![image (1)](https://user-images.githubusercontent.com/34582874/56367290-ee3c7500-61c2-11e9-9b6b-5e1a829e4564.png)

**How to Reproduce**
Run a job in an instance and check the live output in another instance, you'll see a message: `Execution Summary and Report detail is not available.` and a button `View Log Output`, the button is working fine and leads to the `Log Output` tab, the yellow message shouldn't be there.

![Captura de pantalla de 2019-04-18 10-01-46](https://user-images.githubusercontent.com/34582874/56367465-4e331b80-61c3-11e9-8bae-ca6ec8c79dcd.png)

When the `View Log Output` button is clicked:

![Captura de pantalla de 2019-04-18 10-02-33](https://user-images.githubusercontent.com/34582874/56367507-5e4afb00-61c3-11e9-8d35-0b59cc259eae.png)

**Comment by gschueler** [comment]
@jplassnibatt it seems the state information ("Nodes" and info under Report/Monitor tab) is not available. are you saying that the state info was available, and that the yellow message is incorrect?

**Comment by jplassnibatt** [comment]
@gschueler yes, the yellow message is incorrect, this got fixed in 3.1.0.
