### ISSUE TITLE
无法登陆

### ISSUE THREAD

**Issue by renmcc** [rundeck/rundeck#4734]
login:1 Refused to send form data to 'http://172.16.10.50:4440/' because it violates the following Content Security Policy directive: "form-action 'self'".

**Comment by sticky-note** [comment]
File: $RDECK_BASE/etc/rundeck-config.properties.
grails.serverURL needs to be equal to the URL used to connect to rundeck web server
related to #4417

**Comment by gschueler** [comment]
duplicates #4417
