### ISSUE TITLE
Docker: support for plugins

### ISSUE THREAD

**Issue by imperator-maximus** [rundeck/rundeck#4739]
support for plugins in docker-compose would be nice.
I tried to mount plugin jar directly to libext but it does not work.
I have not found a solution for this so this might be useful for docker-support. Otherwise it would be nice if someone can show me a solution or workaround. Thanks.

**Comment by ltamaster** [comment]
Hi @imperator-maximus ,
Not sure if this example can be useful
https://github.com/rundeck-plugins/openssh-bastion-node-execution/tree/master/docker

https://github.com/rundeck-plugins/openssh-bastion-node-execution/blob/master/docker/rundeck/Dockerfile#L22

Luis

**Comment by ProTip** [comment]
Hi @imperator-maximus ,

Further to the comment from @ltamaster , we also have two examples of plugin bundling in the in the [Docker Zoo here](https://github.com/rundeck/docker-zoo#plugin-bundling).
