### ISSUE TITLE
origDescription is still referrenced in _upload.gsp but removed from ScheduledExecution.groovy entity

### ISSUE THREAD

**Issue by mrubes** [rundeck/rundeck#4749]
**Describe the bug**
 "Error processing GroovyPageView: [views/scheduledExecution/upload.gsp:28] Error executing tag <g:render>: [views/scheduledExecution/_uploadForm.gsp:89] Error executing tag <g:enc>: No such property: origDescription for class: rundeck.ScheduledExecution"

This is caused by referencing scheduledExecution.origDescription property in _upload.gsp. The property has been already removed from ScheduledExecution.groovy

**My Rundeck detail**

* Rundeck version: 3.0.16
* install type: war
* OS Name/version: Ubuntu 18.04
* DB Type/version: postgres

**To Reproduce**
1. Create a simple job and download its definition in YAML
2, Go to upload new job definition
3. Select Preserve UUID and skip 
4. Press upload with previously unchanged YAML
5. See error

![before](https://user-images.githubusercontent.com/10106126/56644726-8a132880-667c-11e9-958f-ca73101e294a.png)
![error](https://user-images.githubusercontent.com/10106126/56644725-8a132880-667c-11e9-8220-467bf2587c7c.png)

**Expected behavior**
The error should not be shown

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chromium
 - Version 73

**Comment by carlosrfranco** [comment]
Still happens in the 3.2.5 version
