### ISSUE TITLE
After upgrading rundeck the folders server-lib and server-sbin are not created

### ISSUE THREAD

**Issue by fgutierrezz** [rundeck/rundeck#4753]
**Describe the bug**
When upgrading rundeck the folders $RDECK_BASE/server/lib/ and $RDECK_BASE/server/sbin/ are not recreated 

**My Rundeck detail**

* Rundeck version: 3.0.17, 3.0.20 
* install type: launcher
* OS Name/version: ubuntu 18.04 and Windows 2012R2
* DB Type/version: any

**To Reproduce**
1. Go to rundeck folder
2. Remove source folders. 
rm -rf $RDECK_BASE/server/exp/ $RDECK_BASE/server/lib/ $RDECK_BASE/server/sbin/ $RDECK_BASE/tools/

3. Perform to re create the folder. 
java -jar rundeck-3.X.war --installonly

4. The following folders $RDECK_BASE/server/lib/ and $RDECK_BASE/server/sbin/ are not created

**Expected behavior**
It's expected files/folders are created

**Screenshots**
Attached

**Additional context**
To fix, I have removed the file  $RDECK_BASE/var/.install_complete-missing-ver 
then, performend the "java -jar rundeck-3.X.war --installonly" again and the files/folders are created fine.

**Comment by gschueler** [comment]
`$RDECK_BASE/var/.install_complete-missing-ver` @sjrd218 this seems like somehow the app version is not being correctly used in the file name?
