### ISSUE TITLE
Remote job execution

### ISSUE THREAD

**Issue by devvvy** [rundeck/rundeck#4758]
hello
Can we install RunDeck **"master"** one server - and "probes" or **"slaves"** on couple other servers. RunDeck "master" will route jobs to "slaves" on other servers?
This sound like "Remote Job Executions" which is only available in **RunDeck Pro**? Please kindly confirm...? Thanks

https://docs.rundeck.com/docs/administration/configuration/remote-job-execution-pro.html

**Comment by gschueler** [comment]
Yes, this is the Remote Job Executions feature of Rundeck Enterprise. You can get a trial license to try it out. https://www.rundeck.com/
