### ISSUE TITLE
Fuzzy search for nodes

### ISSUE THREAD

**Issue by alex067** [rundeck/rundeck#4762]
Please add the ability to fuzzy search our available nodes. 

It's a bit of an annoyance to type the full node name. It'd be helpful to be able to type the first 2, 3 letters of the node, and have a list show up for available nodes that match the search pattern.

**Comment by hs-hub-world** [comment]
Fyi the search uses regex.  You can do stuff like this: 
(Note the dot and astriks so)

Node.*      Show anything starting with Node

.*NOD.*       Show anything containing NOD

Or to filter by filed name, use the field name colon, space and the same search criteria.

name: .*Node.*
Etc...

One thing to note EVERTHING is case sensitive. Hence keep all the fields/values same case type (ie lower case).
 
You can use pipe |     For  'or' 

Hope it helps.

**Comment by gschueler** [comment]
for more information, see https://docs.rundeck.com/docs/manual/node-filters.html
