### ISSUE TITLE
Allow Mail notification to use defined Folder / File to be attached. 

### ISSUE THREAD

**Issue by fgutierrezz** [rundeck/rundeck#4766]
**Is your feature request related to a problem? Please describe.**
Related with > https://github.com/rundeck/rundeck/issues/1348

It will be good to select folder/file at project level 

**Describe the solution you'd like**
* Add option to include a regex option to match files (ex: xyz_<timestamp>) to include as attachment in the notification. This should automatically scan/detect files in any other sub folder structures based on latest updated time stamp .
* Allow configuring Email notification at Project level. 
* Allow configuring Email notification for all projects.

**Describe alternatives you've considered**
* Allow user to select folder and file to be imported in the email notification .

**Comment by jtobard** [comment]
The capability to configure notification at project and framework level is something we want to include and is covered by this enhancement request: #4558

But this can be achieved by creating a custom notification plugin:

 * Add option to include a regex option to match files (ex: xyz_) to include as attachment in the notification. This should automatically scan/detect files in any other sub folder structures based on latest updated time stamp .
