### ISSUE TITLE
winrm-exec.py line 163 in errorread session._clean_error_msg sys.stderr.read

### ISSUE THREAD

**Issue by iandrianov77** [rundeck/rundeck#4767]
**Describe the bug**

WinRM plugin successfully execute PowerShell script, no error reported by rundeck, however, logs show this errors:

Traceback (most recent call last): File "/var/lib/rundeck/libext/cache/py-winrm-plugin-2.0.1/winrm-exec.py", line 163, in errorread=session._clean_error_msg(sys.stderr.read()) File "/var/lib/rundeck/libext/cache/py-winrm-plugin-2.0.1/winrm_session.py", line 71, in _clean_error_msg " error message: %s" % (e)) TypeError: 'unicode' does not have the buffer interface

![image](https://user-images.githubusercontent.com/43052149/56932884-6005a000-6a9a-11e9-8e2d-9af88e82229a.png)

**My Rundeck detail**

Rundeck 3.0.12-20190114 
* install type: [rpm]
* OS Name/version: [e.g. ubuntu 18.04]

**To Reproduce**
Steps to reproduce the behaviour:
Run the PowerShell script by defining URL:
![image](https://user-images.githubusercontent.com/43052149/56932808-09986180-6a9a-11e9-943f-714d4d40440c.png)

**Comment by ltamaster** [comment]
Hi @iandrianov77 

Can you share some info about your environment?

* python version
* windows remote version

Thanks
Luis

**Comment by iandrianov77** [comment]
Luis, thank you for follow-up. Please close this issue – the problem was with encoding. My web node hosting script is windows IIS, so somehow encoding got messed up, thus there were some illegal character in script body.
Hopefully error reporting will become more descriptive.

**Comment by ltamaster** [comment]
Hi @iandrianov77 

Anyway, I have been working on fixing encoding issues, the next version will have improvements.

Luis
