### ISSUE TITLE
ssh timeout not set in copy phase of execute an inline script

### ISSUE THREAD

**Issue by ericlc** [rundeck/rundeck#4771]
**Describe the bug**
SSH timeout is not working properly on jobs with 'execute an inline script' step. Apparently the problem is in the copy phase of the script which should be applied the ssh timeout too but its not working as expected.

**My Rundeck detail**

* Rundeck version: 3.0.12-20190114
* install type: rpm
* OS Name/version: rhel 7.5
* DB Type/version: mysql

**To Reproduce**
1. Configure the ssh timeout. For example in framework.properties
framework.ssh.timeout = 5000
framework.ssh-connection-timeout = 5000
2. Create a job with 'execute an inline script' step
3. Run the job on debug mode in a host that should not have timeout problem
4. Check the difference in the ssh timeout between the copy phase and execute phase
5. Run the job on debug mode in a host that should have timeout problem
6. Check if the job will timeout after approximately 2 minutes not respecting the ssh timeout

**Expected behavior**

Check the difference between the copy and execute phase of ssh timeout in the host that should not have the timeout problem

copying file: '/var/lib/rundeck/var/tmp/dispatch8515710014679849922.tmp' to: 'host1:/tmp/3-34-host1-dispatch-script.tmp.sh'
**Set timeout to 0**
Starting SSH Connection: root@host1 (host1)
**Set timeout to 5000**

Check the ssh timeout in the host that should have the timeout problem. It will fail on the copy phase but with a default timeout approximately of 2 minutes

copying file: '/var/lib/rundeck/var/tmp/dispatch2451955308101379941.tmp' to: 'host2:/tmp/4-35-host2-dispatch-script.tmp.sh'
**Set timeout to 0**

Rundeck should set the timeout on the copy phase too.

**Screenshots**

**Additional context**

**Comment by reinerrdeck** [comment]
Also happens on 3.0.21.
