### ISSUE TITLE
Render Formatted data from command output

### ISSUE THREAD

**Issue by bran2k7** [rundeck/rundeck#4773]
**Describe the bug**
I have a job that has one step that executes locally on the rundeck server. The command produces output to the stdout that the rundeck log output GUI captures. I am trying to render the json portions of the output through something like:
```
print("#BEGIN:RUNDECK:DATATYPE:application/json", flush=True)
print(json, flush=True)
print("#END:RUNDECK:DATATYPE", flush=True)
```
all I see though is the two lines surrounding the stringified json in the log output

**My Rundeck detail**

* Rundeck version: 3.0.13
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: postgres

**Expected behavior**
I was expecting to have the data rendered through the JSON Content Converter

**Desktop (please complete the following information):**
 - OS: OSX 10.13.6
 - Browser firefox
 - Version 66.0.3

**Additional context**
I don't currently have any render formatted data log filters applied, but when I did have one for JSON applied instead of:

> #BEGIN:RUNDECK:DATATYPE:application/json
> {'this':'is', 'some':'json'}
> #END:RUNDECK:DATATYPE

I would see:

> #BEGIN:RUNDECK:DATATYPE:application/json
> {'this':'is', 'some':'json'}

missing the: #END:RUNDECK:DATATYPE

**Comment by gschueler** [comment]
can you include the job definition?

**Comment by bran2k7** [comment]
`- defaultTab: summary
  description: Runs through all required config automation steps
  executionEnabled: true
  id: f90a1aab-a145-4ffc-b3d5-38e5b255ac7b
  loglevel: INFO
  name: Autoconfigdeck
  nodeFilterEditable: false
  scheduleEnabled: true
  sequence:
    commands:
    - description: acfgd
      exec: acfgd ${job.name} ${job.execid} -v ${job.loglevel}
      plugins:
        LogFilter: []
    keepgoing: false
    pluginConfig:
      LogFilter:
      - config:
          bgcolor: yellow
          regex: .*WARNING (.+)$
        type: highlight-output
      - config:
          fgcolor: red
          regex: .*ERROR (.+)$
        type: highlight-output
      - config:
          fgcolor: red
          mode: bold
          regex: .*CRITICAL (.+)$
        type: highlight-output
    strategy: node-first
  timeZone: America/Denver
  uuid: f90a1aab-a145-4ffc-b3d5-38e5b255ac7b`

**Comment by bran2k7** [comment]
I recently upon reading more into the documentation added:
```
LogFilter
    - config: {}
       type: render-datatype
```
I didn't realize you could add an empty render-datatype. With this the log output doesn't show the
>#BEGIN:RUNDECK:DATATYPE:application/json
>#END:RUNDECK:DATATYPE
but the json still just shows as one long string. No rendering.

**Comment by JesusRo** [comment]
Indeed, you need to add the render-datatype filter then, it will reads #BEGIN:RUNDECK:DATATYPE and you can use more than once/one type on your step.

I use this a lot and I found some tools that doesn't really format very well the json objects
Can you check your json format?

Example of what I'm talking about:
```yaml
    - description: Show json
      plugins:
        LogFilter:
        - config:
            striped: 'false'
          type: render-datatype
      script: |-
        echo "Working"
        echo "#BEGIN:RUNDECK:DATATYPE:application/json"
        echo '{"this":"is", "some":"json"}'
        echo "#END:RUNDECK:DATATYPE"

        echo "Not working"
        echo "#BEGIN:RUNDECK:DATATYPE:application/json"
        echo "{'this':'is', 'some':'json'}"
        echo "#END:RUNDECK:DATATYPE"
```
![image](https://user-images.githubusercontent.com/12175711/57059658-9a4b8900-6cb6-11e9-9135-e4e70d9ccffc.png)

**Comment by bran2k7** [comment]
That might be it. My json all shows as having single quotes around all the strings. I wasn't aware that JSON was supposed to have double quotes for its' strings instead of allowing single quotes until now.
seems python print() results in the latter, not working type.

**Comment by bran2k7** [comment]
using json.dumps(json) inside the print is what is needed. A bit annoying but if single quotes isn't JSON then rundeck is doing the right thing
