### ISSUE TITLE
Passing Value on Job GUI Field via URL

### ISSUE THREAD

**Issue by happicamper** [rundeck/rundeck#4776]
I would like to create a button from another application that contains a URL with something like this: 
https://myrundeck/project/myproject/job/show/0092310213?option.myfield=123
Which `myfield` is an option field on my Rundeck job.
I'd like to pre-populated that field with dynamic value gathered from another application and show it via GUI.

However, upon testing, that URL isn't possible and looking for a way how to do it on Rundeck GUI.

Thank you in advance always Rundeck team.

**Comment by reinerrdeck** [comment]
Hi @noahcampbell ,

You can make a Rundeck API call for that using GET/POST like this:

https://www.taniarascia.com/how-to-connect-to-an-api-with-javascript/

Here an example about how to call Rudeck API using options and values:

https://stackoverflow.com/a/54593735/10426011

You can check complete Rundeck API reference here:

https://docs.rundeck.com/docs/api/

Here you have a lot of Rundeck API examples here:

https://documenter.getpostman.com/view/95797/rundeck/7TNfX9k#intro

Regards!

**Comment by JesusRo** [comment]
Hey @reinerrdeck 

I think the idea of @happicamper is not to call Rundeck in background (on an AJAX call) but ability to redirect the user to a job with pre-filled information passed via URL.

Kind of this:
![image](https://user-images.githubusercontent.com/12175711/57024765-b1966200-6c35-11e9-9ee5-231f01010ce3.png)

isn't it?

**Comment by reinerrdeck** [comment]
Hey @happicamper and @JesusRo 

Works passing that on URL:

`http://myhost:4440/project/MyProject/job/show/49d64d2e-6cc5-457e-8b9f-eaaf0944d6e5?argString=-OptionName+ValueAsYouWant`

Cheers!

**Comment by happicamper** [comment]
@reinerrdeck Thank you very much and hey look! that StackOverflow query was asked by me and answered by you again lol. Now it works!

@JesusRo  Thank you for pointing it out precisely.

**Comment by happicamper** [comment]
@reinerrdeck Sorry for this additional query, please tell me if I need to open a new issue about this. 
Can I also pre-select the target node using Rundeck GUI? 
I'd like to select one or few of them out of 80+ nodes.

**Comment by reinerrdeck** [comment]
@happicamper 

Sure, a good option for that is create a Job that "receive" the node name using an option and passing that using argString like:

`http:myhost:4440/project/MyProject/job/show/ab698597-9753-4e98-bdab-90ebf395b0d0?argString=-opt1+ValueAsYouWant%20-thenode+titan`

The %20 is a url encode for space, argString need space to pass multiple options, but i tested using space directly and works too:

`http:myhost:4440/project/MyProject/job/show/ab698597-9753-4e98-bdab-90ebf395b0d0?argString=-opt1+ValueAsYouWant -thenode+mynode`

Here I leave an example job definition:

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='opt1' />
        <option name='thenode' />
      </options>
    </context>
    <defaultTab>summary</defaultTab>
    <description></description>
    <dispatch>
      <excludePrecedence>true</excludePrecedence>
      <keepgoing>false</keepgoing>
      <rankOrder>ascending</rankOrder>
      <successOnEmptyNodeFilter>false</successOnEmptyNodeFilter>
      <threadcount>5</threadcount>
    </dispatch>
    <executionEnabled>true</executionEnabled>
    <id>ab698597-9753-4e98-bdab-90ebf395b0d0</id>
    <loglevel>INFO</loglevel>
    <name>MyJob</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <nodefilters>
      <filter>${option.thenode}</filter>
    </nodefilters>
    <nodesSelectedByDefault>true</nodesSelectedByDefault>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='parallel'>
      <command>
        <exec>echo "i am at ${node.name}"</exec>
      </command>
      <command>
        <exec>echo ${option.opt1}</exec>
      </command>
    </sequence>
    <uuid>ab698597-9753-4e98-bdab-90ebf395b0d0</uuid>
  </job>
</joblist>
```

Use it as you want.

Cheers!

**Comment by gschueler** [comment]
FYI: there is another way to pass the options, you can use `?opt.name=value&opt.name2=value2` in the URL string.  See https://github.com/rundeck/rundeck/pull/2209

**Comment by gschueler** [comment]
https://github.com/rundeck/docs/pull/246

**Comment by happicamper** [comment]
@reinerrdeck I'm kind of confuse sorry. I've tried uploading your definition but sadly isn't valid as I import it. I want to achieve this kind of goal:
![Screen Shot 2019-05-07 at 9 46 30 am](https://user-images.githubusercontent.com/18710305/57266099-33124800-70ad-11e9-9986-7e04d88ef751.png)
Can I use something like` argNode `or `filter` on URL to pre-select different nodes? 
example: https://rundeck/project/myproject/job/show/123456?argString=-myoption+1234&nodefilter=myspecificNodeName
Thank you so much for your help.

**Comment by reinerrdeck** [comment]
Hi @happicamper 

I mean to use an option in the Node filter textbox when to define or edit your job, then, at the moment of pass the variable via URL the job can use that as a defined node.

![Screenshot_20190507_145418](https://user-images.githubusercontent.com/43051294/57325694-a2516180-70d8-11e9-9830-21df700d95e8.png)

Greetings.

**Comment by happicamper** [comment]
@reinerrdeck It makes sense now, I have achieved my goal. Thank you very much, cheers! 🍺
