### ISSUE TITLE
LDAP DEBUG messages always show no matter what set on the configuration file

### ISSUE THREAD

**Issue by reinerrdeck** [rundeck/rundeck#4778]
**Describe the bug**
DEBUG messages always keep on although set debug="false"  on LDAP config (jaas-ldap.conf).

**My Rundeck detail**

* Rundeck version: 3.0.21
* install type: WAR
* OS Name/version: KDE Neon 5.15.4
* DB Type/version: H2

**To Reproduce**
1. Set debug="false" on LDAP Config.
2. See the log and you can see DEBUG messages.

**Expected behavior**
DEBUG info should disappear with set debug="false" on LDAP config.

**Desktop (please complete the following information):**
 - OS: KDE Neon 5.15.4
 - Browser: Firefox
 - Version: 66.0.3

**Additional context**
Related: https://groups.google.com/forum/#!topic/rundeck-discuss/c4COdZuKxKQ

**Comment by mazzella-c** [comment]
I confirm this issue on 3.0.21 but it's been present for a long time.

**Comment by yks0000** [comment]
@mazzella-c  Please update if this is planned in next release.

**Comment by yks0000** [comment]
@reinerrdeck @mazzella-c Please update this bug fix is included in latest 3.0.24.

**Comment by MegaDrive68k** [comment]
@yks0000 

It's available for 3.1.0-RC2 (the second release candidate for 3.1.0).

Check this:

https://bintray.com/rundeck/maven/rundeck/#

Regards.

**Comment by mazzella-c** [comment]
Still present on 3.1.0.

**Comment by yks0000** [comment]
@gschueler @reinerrdeck @MegaDrive68k 

This is still not included in release 3.1.3 as per https://docs.rundeck.com/3.1.3/history/3_1_x/version-3.1.3.html#bug-fixes

**Comment by MegaDrive68k** [comment]
Hi @yks0000 and @mazzella-c 

What message are you seeing?

I tested (under 3.1.3/3.2.0-RC2) using  `debug="true"` and  `debug="false"` in the LDAP config file, and I see the difference.

With `debug="false"`

![Screenshot_1](https://user-images.githubusercontent.com/51376003/70563234-a19c1480-1b6c-11ea-9b94-de59825def87.png)
`
With `debug="true"

![Screenshot_2](https://user-images.githubusercontent.com/51376003/70563238-a4970500-1b6c-11ea-8471-fb6a381fdba8.png)

Consider that the DEBUG messages emitted by the GrailsUsername filter are not related to LDAP.

Hope it helps!

**Comment by yks0000** [comment]
Thanks @MegaDrive68k. I see it is GrailsUsernamePasswordAuthenticationFilter which is emitting all groups. LDAP debug is no more there.

**Comment by mazzella-c** [comment]
Thanks @MegaDrive68k. Is it possible to do the same thing for GrailsUsernamePasswordAuthenticationFilter ? I can't find any option to turn off DEBUG mode on that.
