### ISSUE TITLE
SSH connections remain open after job ends

### ISSUE THREAD

**Issue by gtsteffaniak** [rundeck/rundeck#4779]
I have noticed there are certain cases where the SSH session will remain active after a job ends. This can also be seen on the UI as well as the backend process view. here is an example:

![image](https://user-images.githubusercontent.com/42989099/57028557-04a3f100-6c05-11e9-8a0a-6d7299d6a046.png)

`rundeck  31636 62562  0 Apr29 ?        00:00:00 /bin/bash /var/lib/rundeck/libext/cache/openssh-node-execution-1.0.3/ssh-exec.sh bridge 104.254.176.107 /tmp/29536-45673-T70734RDFDNQ3A-dispatch-script.tmp.bat
rundeck  31642 31636  0 Apr29 ?        00:00:00 sshpass -f /tmp/.ssh-exec/ssh-passfile.bridge@104.254.176.107.OLmX0 ssh -p 22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=quiet -o ConnectTimeout=10 -o StrictHostKeyChecking=no bridge@104.254.176.107 /tmp/29536-45673-T70734RDFDNQ3A-dispatch-script.tmp.bat
rundeck  31643 31642  0 Apr29 pts/22   00:00:00 ssh -p 22 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o LogLevel=quiet -o ConnectTimeout=10 -o StrictHostKeyChecking=no bridge@104.254.176.107 /tmp/29536-45673-T70734RDFDNQ3A-dispatch-script.tmp.bat
`

OS: Oracle linux
Rundeck ver: 3.0.19

**Comment by ltamaster** [comment]
Hi @gtsteffaniak 

What kind of command/script are you running on the remote nodes?

Thanks
Luis

**Comment by gtsteffaniak** [comment]
@ltamaster The job runs a node step job reference to another job with a batch script and another job reference.

It appears to only happen to jobs with job references.
