### ISSUE TITLE
Options from URL not filled when job is schedule

### ISSUE THREAD

**Issue by isaacban** [rundeck/rundeck#4781]
**Describe the bug**
In a job using options data retrieved from a service.
The option is set to the data returned by webservice when the job is ran manually but to the default option value when scheduled.

**My Rundeck detail**
* Rundeck version: [ 3.0.21-20190424 ]
* install type: [war]
* OS Name/version: [CentOS Linux release 7.6.1810 (Core)]
* DB Type/version: [h2]

**To Reproduce**
1. Create a job with option 'servers' whose value is a remote URL.
I use something like that https://rundeckhost/getservers.py?type=http&env=test
2. When the job is ran manually, 
the 'servers' option is filled with webservice data.
3. When the job is scheduled 
the 'servers' option is filled with the default value or not filled if no default value was set.

**Expected behavior**
The option should be populated with webservice data in both case.
At least scheduled and manual job should behave the same way.
 
**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Firefox]
 - Version [67]

** Additional information
Seem to be related with #1675

**Comment by reinerrdeck** [comment]
Reproduced on 3.0.21,

If run manually forced to URL values, get only the remote the values:

![Screenshot_20190507_001312](https://user-images.githubusercontent.com/43051294/57271328-12220680-705d-11e9-918a-ece7c38ebdf7.png)

But if set "Schedule to run repeatedly?" and "Enforced from Allowed Values" pointing to remote URL get the default value (or nothing if don't define).

Here my job def:

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option enforcedvalues='true' name='os' valuesUrl='http://192.168.33.70/hello.cgi?server=titan' />
      </options>
    </context>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>4f1ee042-ea35-4cb0-bc5c-6f95882d4b43</id>
    <loglevel>INFO</loglevel>
    <name>JobRemoteCGI</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <schedule>
      <month month='*' />
      <time hour='0/1' minute='0/1' seconds='0/10' />
      <weekday day='*' />
      <year year='*' />
    </schedule>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "the operaring system of server is: ${option.os}"</exec>
      </command>
    </sequence>
    <uuid>4f1ee042-ea35-4cb0-bc5c-6f95882d4b43</uuid>
  </job>
</joblist>
```

**Comment by sebastianbello** [comment]
The issue also exists since  2.4.x through 3.1 RC1
