### ISSUE TITLE
All referenced jobs show "Job Not Found" after upgrade

### ISSUE THREAD

**Issue by biguphpc** [rundeck/rundeck#4785]
**Describe the bug**
When a job references other job as steps, these steps show "Job Not Found". This is a pretty bad regression. it happens to ALL the jobs. Fortunately it seems like the steps are still running ok.

Happened since we upgraded Rundeck from 3.0.9 to 3.0.21.
![image](https://user-images.githubusercontent.com/2192458/57181310-92771a80-6e57-11e9-8e70-d4fdbe0dbb49.png)

**My Rundeck detail**

* Rundeck version: 3.0.21-20190424
* install type: [choose: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: postgres

**To Reproduce**
1. Select a job referencing other jobs as steps 
2. Click on 'Definition'
3. All steps show an orange  (Job not found)

**Expected behavior**
Jobs should be found

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: chrome

**Additional context**
Possible issue could be that when the job is edited, by default "UUID Use Jobs UUID to search jobs is selected" instead of "Name". This should be automatically figured out by rundeck on upgrade when a UUID is not present but the name is.

![image](https://user-images.githubusercontent.com/2192458/57181317-a28efa00-6e57-11e9-86ae-d60bd5cd4b61.png)

**Comment by biguphpc** [comment]
Just wanted to confirm editing the step and switching back to "Name" makes it back to normal in the web UI (the job is found). It's just very scary to see all steps display "Job Not Found" for any reference not using UUID (there's 400+ jobs in this state for us)

**Comment by gtsteffaniak** [comment]
Again?

**Comment by gschueler** [comment]
@gtsteffaniak if you are asking why two commits, it is because I cherry-picked the fix onto the 3.0.x branch as well as master (which is now 3.1.0 snapshot)
