### ISSUE TITLE
UI issue, Side panel disapears when browser width is less than 1080

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#4790]
I have two monitor setups (Landscape & Portrait). When moving the chrome browser with Rundeck over to Portrait the side panel disappears, I can see the panel moves towards the right side of the screen and it disappears. Looks like the panel is only visible when the browser window width size is greater than 1080px.

**My Rundeck detail**
Rundeck version: 3.0.21-20190424
* install type: [choose: rpm]
* OS Name/version: [Centos 7]

**To Reproduce**
manually resize the browser window width (shrink it) and you'll see the side panel disappears.

**Expected behavior**
I think the side panel should remain no matter the size of the width.

See image below, no Panel.
![image](https://user-images.githubusercontent.com/20629911/57254687-bc227400-7006-11e9-89ca-f197f9c1bd1e.png)

After expanding the window width size the panel shows up.
![image](https://user-images.githubusercontent.com/20629911/57254735-d78d7f00-7006-11e9-8953-c06cd9255fa7.png)

Thank you
HS

**Comment by reinerrdeck** [comment]
Hi, if you press the horizontal bars icon (Up to Right) you can see the same options

![Screenshot_20190506_170130](https://user-images.githubusercontent.com/43051294/57255021-ccdfe380-7020-11e9-9fef-c3d6acabb499.png)

![Screenshot_20190506_170157](https://user-images.githubusercontent.com/43051294/57255027-cea9a700-7020-11e9-83cc-a5c877c882df.png)


This is part of a responsive web system.

Regards.

**Comment by hs-hub-world** [comment]
Ack. Thanks.
Wouldn't it make sense to keep the bars icon (panel menu) on the left side so it does not confuse the users -? now we are shifting to the right side takes a sec to adjust to it, just my two cents. I wonder what others think -?
