### ISSUE TITLE
UI - Adhoc Command node info drop-down cannot be dismissed

### ISSUE THREAD

**Issue by skywalke34** [rundeck/rundeck#4791]
**Bug Description**
When selecting node to display information details (see screenshots), I can select a filter, which changes the nodes displayed.  The node information dropdown is orphaned and cannot be dismissed without reloading the entire page.
**Screenshots**
![image](https://user-images.githubusercontent.com/11443283/57263155-f0a92680-702c-11e9-8c86-cf9d01a38c5e.png)
![image](https://user-images.githubusercontent.com/11443283/57263159-f7379e00-702c-11e9-80cd-f418e1925eab.png)
![image](https://user-images.githubusercontent.com/11443283/57263167-fef74280-702c-11e9-8239-d6ab01600ee6.png)

**My Rundeck detail**

* Rundeck version: 3.1.0-SNAPSHOT
* install type: Docker
* DB Type/version: MariaDB

**To Reproduce**
1. Go to 'Commands'
2. Click on 'Show all nodes'
3. Click on node to see information drop-down
4. Select a +tag (this will automatically update the nodes matched, and will move the node label for which the dropdown was previously attached)

**Expected behavior**
Selecting a tag within the node information dropdown should also clear the node information 

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser chrome
 - Version latest

**Comment by mazzella-c** [comment]
I have the same issue with 3.0.21

**Comment by hs-hub-world** [comment]
I have the same issue.

Thanks
HS

**Comment by hs-hub-world** [comment]
Same as this: https://github.com/rundeck/rundeck/issues/4703

**Comment by gschueler** [comment]
this duplicates #4703
