### ISSUE TITLE
MOTD does not respect project configuration settings

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#4795]
**Describe the bug**

Here's an example MOTD
![image](https://user-images.githubusercontent.com/275924/57317449-f8a8ab00-70ac-11e9-97c2-0666f393bd80.png)

The Project configuration page allows a user to specify where the MOTD should be displayed.
![image](https://user-images.githubusercontent.com/275924/57317431-edee1600-70ac-11e9-8e1d-1b7f84636a65.png)

The MOTD is not displayed in the project list.
![image](https://user-images.githubusercontent.com/275924/57317488-0f4f0200-70ad-11e9-8b5f-75e2edfc7daa.png)

**My Rundeck detail**

* Rundeck version: 3.1.0-snapshot
* install type: war
* OS Name/version: Macos
* DB Type/version: h2

**To Reproduce**
1. Create an MOTD
2. Click the "show on project list" and save
3. Go to home page
4. MOTD will not be seen

**Expected behavior**
The MOTD should be displayed on the configured pages.
We should add a 3rd checkbox to show MOTD on every page 

**Desktop (please complete the following information):**
 - OS: Macos
 - Browser: Firefox
 - Version: 67

**Additional context**

**Comment by ltamaster** [comment]
this seems resolved @ahonor, right?

**Comment by ltamaster** [comment]
I reproduced it in 3.2.3

**Comment by MegaDrive68k** [comment]
Still happening on 3.3.0-PREVIEW2.

**Comment by MegaDrive68k** [comment]
Still happening on 3.3.6:

Conf:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/101771742-2a73c600-3ac9-11eb-9283-bef2ef81f1ce.png)

Project Home Page:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/101771744-2c3d8980-3ac9-11eb-992c-a24ec06753e0.png)

**Comment by eagle-rr** [comment]
Within the project settings; I have the following:
- project.gui.motd.display=projectList,projectHome,navbar

I then create a file on the local filesystem and use rd client to update the motd:
- /bin/rd projects readme put --motd --file <motd_file> --project <project_name>

I do see the motd when looking at the project list and the icon on the navigation bar.  However, I do not see the motd on the project home page.

If I log into the gui and navigate to the project settings --> edit message of the day panel, change nothing, and click on the "save" button; the motd now appears on the project home page.

When I log out of Rundeck and back into Rundeck; the motd does not appear again on the project home page.

This is Rundeck 3.3.7.20201208-1 (community edition).
