### ISSUE TITLE
Error getting service provider detail for ResourceModelSource/file

### ISSUE THREAD

**Issue by jrose84** [rundeck/rundeck#4804]
**Describe the bug**
After upgrading from 3.0.19 to 3.0.21, I can no longer edit nodes from webUI
Error message when I choose source: Error getting service provider detail for ResourceModelSource/file

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3] 3.0.21
* install type: [choose: rpm,deb,war,launcher] rpm
* OS Name/version: [e.g. ubuntu 16.04] CentOS Linux release 7.6.1810 (Core)
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ] 5.7.22-22-log Percona Server

**To Reproduce**
1. Go to any project
2. Click on Project Settings
3. Click on Edit Nodes
4. Click on Sources

**Expected behavior**
The ability to edit my YAML nodes file

**Screenshots**
![image](https://user-images.githubusercontent.com/31623865/57421330-56d2ac80-71d9-11e9-92db-7ff5f7533b97.png)
![image](https://user-images.githubusercontent.com/31623865/57421338-5e925100-71d9-11e9-8b6f-3e81b9aa9c01.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Google Chrome
 - Version [e.g. 22] Version 74.0.3729.131 (Official Build) (64-bit)

**Additional context**
N/A

**Comment by jrose84** [comment]
I also tried installing a clean instance in a sanbox environment and noting the issue persists. Not sure how to resolve...

**Comment by gschueler** [comment]
can you paste your project configuration (as it pertains to the resource model configuration?)

**Comment by gschueler** [comment]
are there any errors in the browser javascript console?

**Comment by jrose84** [comment]
sure!

`#Thu May 09 12:43:51 EDT 2019
#edit below
project.description=Common tasks for Performance Environment
project.disable.executions=false
project.disable.schedule=false
project.jobs.gui.groupExpandLevel=1
project.label=PRF
project.name=PRF
project.nodeCache.delay=30
project.nodeCache.enabled=true
project.nodeCache.firstLoadSynch=true
project.ssh-authentication=privateKey
project.ssh-command-timeout=0
project.ssh-connect-timeout=0
project.ssh-keypath=/home/rundeck/.ssh/id_rsa
resources.source.1.config.file=/var/rundeck/nodes/perf.yml
resources.source.1.config.format=resourceyaml
resources.source.1.config.generateFileAutomatically=true
resources.source.1.config.includeServerNode=false
resources.source.1.config.requireFileExists=true
resources.source.1.config.writeable=true
resources.source.1.type=file
service.FileCopier.default.provider=jsch-scp
service.NodeExecutor.default.provider=jsch-ssh`

**Comment by jrose84** [comment]
does this help?
![image](https://user-images.githubusercontent.com/31623865/57471086-62b18380-7258-11e9-983f-f3704d79d1e6.png)

**Comment by gschueler** [comment]
hmm, does your rundeck base URL include a `/rundeck` context path?

**Comment by jrose84** [comment]
yeah, defined in several places

**Comment by gschueler** [comment]
ok, i think there is a bug in the javascript which is not using the correct URL path

**Comment by jrose84** [comment]
how do we fix?

**Comment by jrose84** [comment]
also, the node files are stored local, so not sure why it's looking via URL

**Comment by jrose84** [comment]
also, not sure if this helps, but we put rundeck behind apache reverse proxy (hence why the URL is port 80 and not 4440)

**Comment by jrose84** [comment]
apache config
```
CustomLog /var/log/httpd/access_log combined
ErrorLog /var/log/httpd/proxy/rundeck/error_log
CustomLog /var/log/httpd/proxy/rundeck/access_log combined
ProxyPass /rundeck http://njrndk01.kligerweiss.net:4440/rundeck
ProxyPassReverse /rundeck http://njrndk01.kligerweiss.net:4440/rundeck
ProxyRequests Off

RedirectMatch ^/$ /rundeck

# Local reverse proxy authorization override
<Proxy http://njrndk01.kligerweiss.net:4440/rundeck*>
        Order deny,allow
        Allow from all
</Proxy>
```
again, not sure if it helps, but since the issue appears to be with broken URL and 404 errors, figured it couldn't hurt to share

**Comment by jrose84** [comment]
FYI - removed web context from rundeck config, adjusted apache proxy settings, and this seems to be a valid workaround

**Comment by gschueler** [comment]
@jrose84 yes, running without web context path will fix it.

I'm fixing the bug for next release.
