### ISSUE TITLE
"more/less" link not correct

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#4809]
Rundeck version: 3.0.21-20190424
The "more/less" link always shows 'Less" instead of changing between More/Less.

![image](https://user-images.githubusercontent.com/20629911/57480212-efa60e00-7253-11e9-9364-805325a25cf1.png)

Thank you,
HS

**Comment by reinerrdeck** [comment]
Hi @hs-hub-world,

I tested with the same version but can't see that behavior, what Browser and version do you use?

![Screenshot_20190509_153539](https://user-images.githubusercontent.com/43051294/57481654-94cedf80-7270-11e9-8862-dff60486289e.png)

![Screenshot_20190509_153718](https://user-images.githubusercontent.com/43051294/57481656-96000c80-7270-11e9-985c-c23bd4e95f88.png)

Regards!

**Comment by gschueler** [comment]
i reproduced it, when jobs are in a group
