### ISSUE TITLE
feature request: show Activity for all Projects

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#481]
Hi,

i would like to see all the activities of all projects on the acivity page.
please extend the search filter with a project checkbox.

**Comment by klj613** [comment]
+1

**Comment by Bendihossan** [comment]
+1

**Comment by Cenhinen** [comment]
+1

**Comment by siraajahmed** [comment]
+1

**Comment by padraiglennon** [comment]
+1

**Comment by mrala** [comment]
Are there any plans on implementing this feature?

**Comment by ahonor** [comment]
@mrala yes it is on the roadmap but we haven't an ETA for it.

**Comment by mrala** [comment]
@ahonor, would you mind if I took a shot at it? Looks like it would need to be implemented [here](https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/controllers/rundeck/controllers/ReportsController.groovy)?

**Comment by ajk17** [comment]
+1 - found a similar request here - https://github.com/rundeck/rundeck/issues/4048.  I had mentioned it in a Webinar and was about to log the same enhancement request.

**Comment by jessemarple** [comment]
Closed in lieu of #4048.
