### ISSUE TITLE
Failed: SSHProtocolFailure: invalid privatekey: [B@63399dc3

### ISSUE THREAD

**Issue by manojfim** [rundeck/rundeck#4813]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: Rundeck 3.0.21-20190424
* install type: (rpm,deb,war,launcher?): war
* OS Name/version: 
* DB Type/version: mysql? postgres? h2?..

**Expected Behavior**
Added a node and stored the private key. The expectation is I could run command in my remote node.

**How to Reproduce**
After running a command in remote node, it is throwing below error
Failed: SSHProtocolFailure: invalid privatekey: [B@63399dc3

**Comment by reinerrdeck** [comment]
HI @manojfim 

You do include the first and the last line of your key in key store?:

`-----BEGIN RSA PRIVATE KEY-----`

and this:

`-----END RSA PRIVATE KEY-----`

Also, make sure that you're using the JSch supported ciphers:

http://www.jcraft.com/jsch/

Greetings!

**Comment by manojfim** [comment]
Thanks for responding so quickly. I was using OPENSSH format key. when i switched to RSA it worked.

**Comment by tebriel** [comment]
In case anyone comes here looking for this answer, `ssh-keygen -p -m PEM -f /path/to/openssh/key` will re-write the private key in the correct format.

**Comment by ledufakademy** [comment]
> In case anyone comes here looking for this answer, `ssh-keygen -p -m PEM -f /path/to/openssh/key` will re-write the private key in the correct format.

thank you , rebuild my ssh key was do the job  , but strangly sometimes SSH acces was working , sometimes not  like that  :

```
<ourhost.tux.com> (255, '', 'Load key "/tmp/rundeck/ansible-runner1689007418017758328id_rsa": invalid format\r\nansibleUser@ourhost.tux.com: Permission denied (publickey).\r\n')

fatal: [ourhost.tux.com]: UNREACHABLE! => {

 "changed": false, 

 "msg": "Failed to connect to the host via ssh: Load key \"/tmp/rundeck/ansible-runner1689007418017758328id_rsa\": invalid format\r\nansibleUser@ourhost.tux.com: Permission denied (publickey).", 

 "unreachable": true

}
```

**Comment by nneul** [comment]
This is an old thread, but I wasted a bunch of time following rabbit trails on this. In case it helps anyone hitting this with a google search - make sure your framework ssh key has "BEGIN RSA PRIVATE KEY" instead of "BEGIN OPENSSH PRIVATE KEY". The latter will not work. You will need to convert it with: 

`ssh-keygen -p -f /var/lib/rundeck/.ssh/id_rsa -m pem`

or similar.

**Comment by aharden** [comment]
Per https://github.blog/2021-09-01-improving-git-protocol-security-github/, on 2022-Mar-15 deprecated the use of certain types of RSA keys, which affected the deploy keys we use for Rundeck SCM to/from GitHub.  After finding that the GitHub-documented & recommmended Ed25519-type keys were not compatible with Rundeck/JSch, I found that that ECDSA keys were.  The keys that worked for me were generated with:

`ssh-keygen -t ecdsa -m PEM`

**Comment by viniciusczar** [comment]
Thanks guys!
Remember, you need to define the user in the node mappings, my example: username.default=ubuntu; You can check in: https://docs.rundeck.com/docs/manual/projects/resource-model-sources/aws.html#advanced-configuration-options
