### ISSUE TITLE
Open Source Rundeck Functionallity 

### ISSUE THREAD

**Issue by mgamboa** [rundeck/rundeck#4818]
**Describe the solution you'd like**
Would be great to have all the features of rundeck enterprise on the community edition because at this moment the community is missing a lot of advantage against enterprise

**Describe alternatives you've considered**
as consideration, we are looking to move to stackstorm as from opensource perspective is all out of the box and have support also

**Additional context**
we think rundeck needs to offer support for the software opensource no actually obligate to the user buy license for something that possible we never use feature that possible we don't need at all and we need more the support to implement the software an have no lock or minimal plugins compare to enterprise it's doesn't matter if rundeck want to make money you can do it via support subscriptions and no per features that would be available from opensource and enterprise also

**Comment by hs-hub-world** [comment]
Hey @mgamboa I have been using Rundeck for a long time (many years), but after reviewing Stackstorm (for the first time) looks like the open source version is more feature reach especially with the workflows.  I know the Rundeck team is doing a great job and they have come a very long way introducing many new features and enhancements. But there are always small/annoying bugs and every time you feel the next release is going to be the solid version it just introduces more bugs.  Again, I am not trying to 'ding' the Rundeck team they have been great all these years, but I think better QA automation testing would be great before it's released to the public and/or ready for commercial use ;)

If possible could you please share what you use Rundeck for and for how long -? 
Which features of Rundeck inspired you most -?

Thanks,
HS

**Comment by mgamboa** [comment]
Well i using rundeck for more than 1 year already the only issue is in my new company i just get the taste of enterprise you know workflow, VMware inventory , slack notifications etc  something that on opensource doesn't exist at all that would be great to have all the features as Opensource and more features that enterprise and just pay per support no per features, just look like fedora and rhel ,  fedora is the opensource of rhel  have same features of rhel but fedora is going more advance in software that rhel and redhat offer subscription for support if you don't want to buy you can also use CentOS that is 1:1 rhel clone means they are really OpenSource software and that is the reason why they are great also, as you said rundeck is great product and the people putting the effort on it is great but great would be have full product that we can use and when we have problem any company is much comfortable to buy the support,

**Comment by padraiglennon** [comment]
@ahonor @gschueler any thoughts on this? I also inquired about the possibility of getting some support on the open source product a few months ago but didn't get much of a response to be honest. Seems like an lost opportunity for some revenue stream from an end-user point of view. 

I've also been using Rundeck for about 2.5 years now and like the product but it does feel that there isn't a huge amount of community input/voice apart from issue reporting and a small number of enhancements being requested. I would like to know what are the plans for Rundeck in the near/medium term. I'm asking because I'd like to help, but not knowing what's being planned is making it hard. 

I strongly suspect there are others like me who would like to help out more and provide some feedback on the future direction of the product. 

Apologies in advance if the above is taken as being dismissive in any way towards the product as that isn't my intention at all.

**Comment by ahonor** [comment]
Hi all. Support only isn't something we are able to offer at this time but I do want to learn more about the specific features you found important or useful in Enterprise that are missing in OSS. Some plugins are OSS but not bundled by default in the community version while a few are currently only in the Enterprise bundle. Also, curious about use case and integration needs you are targeting Rundeck.

**Comment by padraiglennon** [comment]
Hi Alex

Some things I'd like to know progress on/plans for: 
- Enhanced workflow capabilities e.g. #916 
- Simplified ACL editing in the OSS core version
- Insight on how container/kubernetes integration will be enhanced over the next year or so? 
- Tighter integration with other CI/CD tools? esp. Git/Jenkins 
- UI short/medium term plans?

Other items: 
- Possibility of setting up a central area to share useful job definitions? xml/yaml format
- Are there specific areas were the community could help focus on? e.g. UI Testing/ Documentation?

Like I outlined in my previous mail it would be good to get some direction from you guys on how you see the product evolving. The community can give some feedback but it would be good to hear from your point of view as well.

**Comment by ahonor** [comment]
@padraiglennon I appreciate these questions. The first two I will come back to. The remaining 5 I would like to ask a bit more about.

* Container and kubernetes integration will be continued to be enhanced. Not sure if you are trying our official images or plugins yet. We use docker and K8s internally for dev/test, and demos. We host our "test drive" online demo via K8s, too. We automate how we do some of the provisioning through our integration. How would you like to see it enhanced?
* How do you need the GH/Jenkins integration to work? I am guessing GH/Jenkins firing a Rundeck job? I know people need webhook support. Webhooks are something we want to do.
* We have short and medium term ideas for the UI. 3.1 will introduce some general improvements. Architecturally, the UI is being re-tooled to use a more componentized Vue.js based front end. Rundeck supports the idea of UI plugins which offers interesting potential. We want to start showing that off. They are basically, just HTML, JS and CSS but you can insert them just about anywhere on the page to inject something.
* We are setting up a content portal that will let you share useful job definitions. We are slowly launching that behind the scenes now. 3.1 will show integration between a plugin repository and Rundeck server instances. You can set up your own private repos, too. Besides plugins, the content portal will accept job examples, videos, howtos, etc. Hosting user generated content should be possible end of summer.
* The community can absolutely help us focus on UI Testing and Documentation. The Documentation is ok for reference docs but it needs a lot more for guides and howtos. We can also improve other core parts of User and Admin docs. Getting a sense of priority will help tremendously. Also, we encourage any direct help. UI Testing is something we began adding for 3.0.x but we have a lot more coverage to add. That is something everyone could help with given a doc describing the process for those.

Regarding the enhanced workflow and simplified ACL, we did add some support for those in our commercial product and are getting customer feedback. ACLs are beginning to evolve in general. The community version can present a text editor for the ACL and has syntax validation while the commercial product has a more wizard style UI. We are seeing a real need for templating ACLs. For example, there is the general pattern like "make a user/team that can just run jobs in project X." Another is "make a user/team that can administer projects." These ACL patterns are really a combination of rules that might span system resources (storage keys) and project resources (nodes, jobs, events). It would be great to really make these patterns more supported as higher level templates of some kind.

Conditionally running steps will definitely be supported in the community product. A big part to support that idea was introducing data capture. That is still a relatively new feature that should be better documented with examples. Data capture was necessary to parse results used for conditional checks, too. We have learned about some usage patterns from our commercial users that would be good to apply across the board.

**Comment by fdevans** [comment]
Closing this Open Issue since there hasn't been any additional feedback.  Please continue to let us know how we can improve. 
Thank you,
The Rundeck Team
