### ISSUE TITLE
Enhancement Request: Add functionality to enable/disable PTY properties.

### ISSUE THREAD

**Issue by jbanda15** [rundeck/rundeck#4821]
**Is your feature request related to a problem? Please describe.**
There are some jobs that can't be executed when they have a property in True status and others that need be in False status.
The property is exactly `project.always-set-pty=true` which helps for jobs that are executed in the background using commands or scripts, and expect the processes to be killed when the ssh session ends.
In the case doesn't use "Force PTY", the process tree on the remote node might remain running after the ssh session ends.
So, the jobs have to need to have the setting defined and also removed within the project to get certain things to work.

**Describe the solution you'd like**
Maybe, have an option for that, either through some property in the node or configurable by each job.

**Describe alternatives you've considered**
I could edit and set the properties in TRUE status but figured the UI might have it and prevent the remote node still running after the ssh session ends.

**Comment by gschueler** [comment]
A node attribute `always-set-pty` can be defined to always use a particular value on a node, e.g.:

`<node name="mynode" always-set-pty="true"/>`

If you set the project config option, the node value will override it, so you could default it to `true` in the project, but set it to `false` on a particular node. (or vice versa)
