### ISSUE TITLE
Version/Author no longer showing for plugins when viewed via menu/plugins page

### ISSUE THREAD

**Issue by fishikles** [rundeck/rundeck#4828]
**Describe the bug**

Rundeck version: Rundeck 3.0.20-20190408 
install type: warinstall type: war
OS Name/version: RHEL 6.9
DB Type/version: mysql Ver 14.14 Distrib 5.7.18-ndb-7.5.6, for Linux (x86_64) using EditLine wrapper

1. Go to menu/plugins
2. Click on any plugin category
3. Look on the right side
4. See no version or author details for any plugins
![Issue_v3 0 20](https://user-images.githubusercontent.com/26172585/58006292-a9686e80-7adf-11e9-9ebb-9b95a8c11bff.JPG)

The details of the plugin should be shown, as they where in Rundeck 2.11.4-1
![Issue_v2 11 4](https://user-images.githubusercontent.com/26172585/58006315-b4bb9a00-7adf-11e9-8343-53bb7db82393.JPG)

 - OS: Win7
 - Browser FireFox
 - Version 66.0.4

This looks to have been introduced in #4393, the grails-app/views/menu/plugins.gsp file need to be updated to reference fileMetadata not metadata:
https://github.com/rundeck/rundeck/blob/451f08de20de5c1389a4d3fdf9af2837b74b2798/rundeckapp/grails-app/views/menu/plugins.gsp#L157

**Comment by jtobard** [comment]
In rundeck 3.2.0-SNAPSHOT this changed, check next release for this.

![image](https://user-images.githubusercontent.com/2894508/66841669-6e5c5100-ef40-11e9-83b6-3ff971cba38f.png)
