### ISSUE TITLE
Executions In the last day not loading "off screen"

### ISSUE THREAD

**Issue by jadestorm** [rundeck/rundeck#4829]
**Describe the bug**
We have quite a few projects in our instance, and a number of them don't fit onto the front page after logging into Rundeck.  In 2.x, once we scrolled down, they would load ajax-style.  We upgraded to 3.0.21 and now, strangely enough, only the ones that fit on the visible page actually load.  If we scroll down, it just sits there with the spinning loading icon.  Semi amusingly, if I ctrl-R and am very ambitious with trying to scroll down quickly, I tend to be able to sneak in a few.  Additional notes below.

**My Rundeck detail**

* Rundeck version: 3.0.21
* install type: rpm
* OS Name/version: RedHat Enterprise Linux 7.6
* DB Type/version: mysql

**To Reproduce**
1. Start by having a lot of projects, more than can fit on the visible front page at one time
2. Log into Rundeck
3. Note that the visible projects load their status ok  (X failed, that kind of thing)
4. Scroll down and note that the rest do not load

**Expected behavior**
All projects execution information loads on the front page.

**Screenshots**
[Rundeck Front Page](https://i.imgur.com/SN9Yq4o.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox, Chrome, Edge
 - Version 66.0.5, 74.0.3729.157, no idea

**Additional context**
Once additional note -- I opened the web developer toolbar and watched for errors and found the following that are of potential interest:

Loading failed for the <script> with source “https://example.org/rundeck/assets/static/manifest.js”.
(home:258:1 and home:206:1)

XML Parsing Error: syntax error
Location: https://example.org/rundeck/menu/home
Line Number 1, Column 1:
(home:1:1 happens multiple times though)

Could not build a valid `moment` object from input.   (vue-moment.js:4485)

No new javascript errors appear to occur as I scroll down to the non-loaded projects.

**Comment by mazzella-c** [comment]
see https://github.com/rundeck/rundeck/issues/4149

**Comment by jadestorm** [comment]
Crap I apparently fail at search.  :)  Thanks!  Feel free to close this and I will follow the other!

**Comment by jadestorm** [comment]
I'm going to go ahead and close this one since there's already another open.
