### ISSUE TITLE
Admin profile page not should show all tokens from DB . 

### ISSUE THREAD

**Issue by fgutierrezz** [rundeck/rundeck#4831]
**Describe the bug**
It will be good to limit when the token table contains many rows. 

**My Rundeck detail**

* Rundeck version: 3.0.21 Cluster
* install type: launcher
* OS Name/version: ubuntu 18.04
* DB Type/version: postgres

**Expected behavior**
No errors expected

**Additional context**
when a high number of tokens its observer high CPU usage

**Comment by ahonor** [comment]
How many is too many rows?

**Comment by fgutierrezz** [comment]
With around 8000 tokens rows rundeck profile page becomes unstable and unresponsive, unable to open any rundeck link . The following screenshot was taken after 1 or 2 minutes, it shows what happen and not responding when clicking on the show token button. 

![Captura de pantalla de 2019-05-16 19-25-25](https://user-images.githubusercontent.com/30966360/57893432-e3502100-7810-11e9-8631-7e5e34595ac2.png)

After some minutes the page is blank

![Captura de pantalla de 2019-05-16 19-33-04](https://user-images.githubusercontent.com/30966360/57893564-7b4e0a80-7811-11e9-92ce-18b71e5e6c32.png)
