### ISSUE TITLE
UI Issues

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#4836]
* Rundeck version: 3.0.22-20190512
Centos 7

**Below please find general UI issues:**

#1
When creating a new project (there is no cancel button)
![image](https://user-images.githubusercontent.com/20629911/57960539-2c11e380-78be-11e9-928f-354c96d18b75.png)

#2
When clicking the ? help button next to the Search from the Commands window the pop-up never goes away. 
![image](https://user-images.githubusercontent.com/20629911/57960570-5368b080-78be-11e9-8552-c0470b7eb3a0.png)

#3
There is no cancel/close button for the Set Start Time schedule. Can't click away.  Users don't know how to close the window. Not user-friendly.
![image](https://user-images.githubusercontent.com/20629911/57960597-76936000-78be-11e9-91b2-fc326a872848.png)

#4
When modifying the Nodes during Job Run the users are confused, they can't tell which machines the command is going to run against -?
![image](https://user-images.githubusercontent.com/20629911/57960717-40a2ab80-78bf-11e9-9981-9785d12d455f.png)

![image](https://user-images.githubusercontent.com/20629911/57960846-fcfc7180-78bf-11e9-9e45-f3be8b9209ed.png)

#5 Plugins do not show version number
![image](https://user-images.githubusercontent.com/20629911/57960892-3fbe4980-78c0-11e9-999f-14cce1b3e087.png)

#6
When hovering the mouse over the Link the links change it shows extra stuff when clicking on the link it takes you somewhere else...
![image](https://user-images.githubusercontent.com/20629911/57962570-456e5c00-78cd-11e9-99ff-9310bf1ad64f.png)

(Below image with the mouse over the link)
![image](https://user-images.githubusercontent.com/20629911/57962578-82d2e980-78cd-11e9-8801-d52fcc8f8ad3.png)

#7
Web title shows "Now Running"  even after the job is completed.

![image](https://user-images.githubusercontent.com/20629911/57963133-e01e6900-78d4-11e9-85e2-ba341f67a91c.png)

Thank you
HS

**Comment by gschueler** [comment]
thanks

**Comment by gschueler** [comment]
for issue 6) you can disable this with a config flag `rundeck.feature.workflowDynamicStepSummaryGUI.enabled=false`, however we should either improve the behavior of it or have that toggle in a better place

**Comment by gschueler** [comment]
issue 5) the plugin ui has been updated
