### ISSUE TITLE
Jobs that runs longer than an hour causes the next ob db connection to force close

### ISSUE THREAD

**Issue by alim-rax** [rundeck/rundeck#4839]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: 3.0.13
* install type: rpm
* OS Name/version: RHEL 6
* DB Type/version: oracle

**To Reproduce**
If the 1st job that takes longer than 1 hour to run, the following job that uses db connection gets force close with the following error

2019-05-16 22:28:11.275  WARN --- [pool-9-thread-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : SQL Error: 17002, SQLState: 08006
2019-05-16 22:28:11.275 ERROR --- [pool-9-thread-1] o.h.engine.jdbc.spi.SqlExceptionHelper   : IO Error: Connection reset
2019-05-16 22:28:11.282 ERROR --- [pool-9-thread-1] o.s.t.support.TransactionTemplate        : Application exception overridden by rollback exception

We've added dataSource.properties.removeAbandonedTimeout=24000, which is 24,000 seconds. But still jobs takes longer than this still fails.

**Comment by ProTip** [comment]
Hi @alim-rax ,

Several issues related to database connections being held open during job execution have been resolved since `3.0.13`. Are you able to reproduce with the latest version?

Thanks,
   -Greg

**Comment by alim-rax** [comment]
Hi @ProTip,

I was using latest version and had to downgraded to this version to get it start up probably. I should also mentioned I’m using oracle 11g

I’ll give that a try to use latest version again

Thanks
Alex

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
