### ISSUE TITLE
Option enforced with allowd values from remote url not validating

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#4847]
[jobs_and_json_files.zip](https://github.com/rundeck/rundeck/files/3199896/jobs_and_json_files.zip)
When creating an Option with "Enforced from Allowed Values" enabled as "Remote URL",
passing a non-allowed value from a Parent job does not fail the job.

But when passing a non-allowed value from type "list" it fails the job as expected.

Attaching example jobs and screenshots for illustration.
![output_with_list](https://user-images.githubusercontent.com/36487101/58052926-1867b680-7b24-11e9-8e18-c51dd9801f9e.png)
![output_with_url](https://user-images.githubusercontent.com/36487101/58052930-1aca1080-7b24-11e9-88bb-4da252056ac9.png)

**Comment by cwaltherf** [comment]
created from case https://rundeck.desk.com/agent/case/4435

**Comment by EugenePapkou** [comment]
It might be related to this issues as well:
https://github.com/rundeck/rundeck/issues/4781
https://github.com/rundeck/rundeck/issues/4842
