### ISSUE TITLE
Allow using different URL in the Path for Plugin "github-script-plugin"

### ISSUE THREAD

**Issue by fgutierrezz** [rundeck/rundeck#4851]
Created From Ticket # : 4428

Will be useful to set a different Path URL. Actually, it's not possible to modify the URL since it always using the default URL "//api.github.com" 

Current Github Path  : owner/repo

Expected Github Path :   URL/owner/repo

![Captura de pantalla de 2019-05-21 11-12-13](https://user-images.githubusercontent.com/30966360/58108834-88c11700-7bba-11e9-895d-2458ac9f0e8e.png)

**Comment by fgutierrezz** [comment]
Duplicated issue

**Comment by ltamaster** [comment]
@fgutierrezz
This plugin is for github.
Checking gitlab API, seems to be different than github, so setting the URL as proposed won't work.
