### ISSUE TITLE
Job State Conditional not false when referencing second job

### ISSUE THREAD

**Issue by KajMoroz** [rundeck/rundeck#4854]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.0.20.20190408
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux Server release 7.6
* DB Type/version: mysql

**Expected Behavior**

When running Job B from Job A, Job State Conditional says that Job B is currently not running.

**How to Reproduce**

Create a job that runs another job, and then a job state conditional halting on the second job running. The job will not be halted by the invoked second job.

**Comment by reinerrdeck** [comment]
Hi @KajMoroz ,
Can you provide a job definition to take a look?
Regards!
