### ISSUE TITLE
Options - Cannot Enforce From Allowed Values When an Option Value Plugin is Used

### ISSUE THREAD

**Issue by dutchrapley** [rundeck/rundeck#4857]
**Describe the bug**
I cannot use a custom Option Values plugin and enforce an option selection to be restricted to the values provided by my plugin.

**My Rundeck detail**
* Rundeck version: 3.0.22
* install type: deb
* OS Name/version: ubuntu 18.04
* DB Type/version: H2

**To Reproduce**
1. Create a script based Option Values Plugin
2. Choose you plugin for Allowed Values
3. Select Restrictions > Enforce from Allowed Values
4. Click Save

When you click save, there is an error **Allowed values (list or remote URL) must be specified if values are enforced** and my Option Value plugin disappears as an option for Allowed Values.

**Expected behavior**
The new option should save.

**Screenshots**
![image](https://user-images.githubusercontent.com/25286/58214639-57744400-7cab-11e9-8d48-fd3fbb693a37.png)

![image](https://user-images.githubusercontent.com/25286/58214692-8db1c380-7cab-11e9-8c4a-26ffbdfba69d.png)

**Additional context**
EditOptsController.groovy
![image](https://user-images.githubusercontent.com/25286/58214916-70312980-7cac-11e9-8084-99cdae328a2c.png)

**Comment by ltamaster** [comment]
same as https://github.com/rundeck/rundeck/issues/4732

**Comment by dutchrapley** [comment]
Releated to https://github.com/rundeck/rundeck/issues/4732
