### ISSUE TITLE
Preauthenticated roles header should handled quoted values.

### ISSUE THREAD

**Issue by rayward** [rundeck/rundeck#4865]
**Describe the bug**
If the roles supplied in the preauth roles header are quoted, then they are interpreted verbatim which causes a mismatch with ACL policies.

**My Rundeck detail**

* Rundeck version: 3.0.22.20190512-1.201905130100
* install type: deb
* OS Name/version: Debian Jessie 8.11
* DB Type/version: mysql

**To Reproduce**
1. Enable preauthentication
2. Create ACL policy for a project with a multi-word group name, eg. `Technical Operations`
3. Login to Rundeck supplying the roles in the header like so:
```
X-Forwarded-Roles: "admin","Technical Operations","Support Team"
```
4. Note that user will not have access to the expected project
5. Groups shown in the user profile will be shown with the literal quotes:
- `"admin"`
- `"Technical Operations"`
- `"Support Team"`

**Expected behavior**
Quotes/double-quotes should be stripped from each extracted role.

Rundeck should be more tolerant of varying formats of multi-value headers and be able to extract quoted values. Could the `QuotedStringTokenizer` be utilised, or perhaps a CSV parser?

**Screenshots**

<img width="732" alt="Screen Shot 2019-05-24 at 9 57 42 am" src="https://user-images.githubusercontent.com/1217111/58293859-a84e7e80-7e0a-11e9-9ffa-ac3400b25227.png">

<img width="967" alt="Screen Shot 2019-05-24 at 9 57 51 am" src="https://user-images.githubusercontent.com/1217111/58293863-ab496f00-7e0a-11e9-8394-ed5fbdff1e33.png">

**Additional context**
Using https://github.com/vouch/vouch-proxy which supplies the value for the preauth headers.

**Comment by gschueler** [comment]
is there documentation on the exact syntax used by vouch? do you know if there is any standard for this?

**Comment by rayward** [comment]
Here's the particular place where Vouch generates multi-value headers for claims from the oauth provider - https://github.com/vouch/vouch-proxy/blob/master/handlers/handlers.go#L216

Here's some references from the HTTP 1/1.

https://tools.ietf.org/html/rfc7230#section-3.2.2

> A recipient MAY combine multiple header fields with the same field name into one "field-name: field-value" pair, without changing the semantics of the message, by appending each subsequent field value to the combined field value in order, separated by a comma. 

https://tools.ietf.org/html/rfc7230#section-3.2.6 

>  A string of text is parsed as a single value if it is quoted using double-quote marks.
> 
>      quoted-string  = DQUOTE *( qdtext / quoted-pair ) DQUOTE
>      qdtext         = HTAB / SP /%x21 / %x23-5B / %x5D-7E / obs-text
>      obs-text       = %x80-FF
> 

So quoting field values seems valid, though Vouch is on the very liberal side, quoting everything regardless of whether its necessary (and doesn't handle escaping as far as I can see).
