### ISSUE TITLE
[3.0.x] manifest.js 404 Not Found

### ISSUE THREAD

**Issue by DiegoQueiroz** [rundeck/rundeck#4873]
When I open any page on Rundeck (snapshot) it try to load a file called `manifest.js` that doesn't exist in the server.

I have several servers and all present the same problem, so I feel it is easily reproducible. Apparently this causes no harm, but it should be fixed (the file should be included or the reference to it should be removed).

**Comment by gschueler** [comment]
I believe this is fixed in the current 3.1 snapshot, but should be backported for 3.0
