### ISSUE TITLE
Docker image not available for Rundeckpro/team:3.0.22

### ISSUE THREAD

**Issue by fluopotter** [rundeck/rundeck#4877]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.0.22
* install type: docker image
* OS Name/version: Centos
* DB Type/version: mysql

**Expected Behavior**
Pull image not work for 3.0.22 with : docker pull rundeckpro/team:3.0.22

Error : Error response from daemon: manifest for rundeckpro/team:3.0.22 not found

Image pull ok for :
docker pull     rundeckpro/enterprise:3.0.22
docker pull rundeck/rundeck:3.0.2

**How to Reproduce**
Just pull from rundeckpro/team:3.0.22

**Comment by ProTip** [comment]
Hi @fluopotter ,

`Team` has been superseded by `Enterprise` and `3.0.21` was the last build. If you need a license or other support please [contact support](https://support.rundeck.com/).
