### ISSUE TITLE
Whitelabel Error Page appears for /error

### ISSUE THREAD

**Issue by am312** [rundeck/rundeck#4878]
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue May 28 12:24:24 EDT 2019
There was an unexpected error (type=Method Not Allowed, status=405).
Method Not Allowed

APIVERSION : 30
BUILD : 3.0.19-20190327
BUILDGIT : v3.0.19-0-g7267264
VERSION : 3.0.19-20190327

**Comment by gschueler** [comment]
fixed by https://github.com/rundeck/rundeck/pull/4897
