### ISSUE TITLE
Rundeck's Activity Filter Documentation

### ISSUE THREAD

**Issue by davizucon** [rundeck/rundeck#4880]
**Describe the bug**
Rundeck's Activity Filter Documentation

**My Rundeck detail**

* Rundeck version: [2.11.3]
* install type: [deb]
* OS Name/version: [ubuntu 16.04]
* DB Type/version: [mysql]

**To Reproduce**
1. Go to Activity Tab
2. Try to fill some data in Filter or ad hoc
3. Click on Filter

I just don't know what fill in fields , for example, filter by some parameter.

Docs: https://docs.rundeck.com/docs/manual/activity.html

**Comment by reinerrdeck** [comment]
Hi @davizucon 

You can filter executions by user, ad-hoc command, etc... For example, if you want to see only executions of "admin" user: you can put "admin" on "user" textbox and click on "Filter" button to see that. 

Check that, is the 2.11.3 specific documentation for activity filters:

https://docs.rundeck.com/2.11.3/manual/activity.html

Regards!

**Comment by davizucon** [comment]
Hi @reinerrdeck,
   Thanks for clarification, can you exemplify how to use ad-hoc command ?

Thanks

**Comment by reinerrdeck** [comment]
Hi @davizucon 

Ad-Hoc command works like as you're in front of the terminal, you can put any command, for example, "uname -a" (pointing to local or remote server/s) and you can see the result. Is useful in case that you can test your steps or send commands to your nodes directly.

You have more information here:

https://docs.rundeck.com/2.11.3/manual/commands.html

Cheers!
