### ISSUE TITLE
Error on Converting Rundeck Config File Properties to Groovy

### ISSUE THREAD

**Issue by happicamper** [rundeck/rundeck#4882]
I've tried converting my rundeck-config.properties to rundeck-config.groovy with the format instructed written on the documentation.

* Rundeck version: 3.0.22
* install type: RPM
* OS Name/version: CentOS 7
* DB Type/version: mysql

To reproduce:
1. Edited `rundeck-config.properties` to use groovy format.
2. Edited `/etc/rundeck/profile` changed line with `rundeck-config.properties` to `rundeck-config.groovy`
2. Restarted Rundeck `service rundeckd restart`
3. Error will be:
`2019-05-29 12:05:49.590  WARN --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'application': Initialization of bean failed; nested exception is groovy.lang.MissingMethodException: No signature of method: java.lang.Integer.call() is applicable for argument types: (script15591027494041100518902$_run_closure2$_closure3$_closure5$_closure6$_closure7) values: [script15591027494041100518902$_run_closure2$_closure3$_closure5$_closure6$_closure7@78d6692f]
Possible solutions: wait(), abs(), any(), wait(long), each(groovy.lang.Closure), and(java.lang.Number)
2019-05-29 12:05:49.669 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed`

**Expected behavior**
Running well with the new Rundeck groovy file.

**Desktop (please complete the following information):**
 - OS: macOS Mojave
 - Browser: Google Chrome
 - Version: 74.0.3729.169

**ADDITIONAL INFO**
`rundeck-config.properties` file:
```
rdeck.base=/var/lib/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
# change hostname here
grails.serverURL=https:/my-rundeck.com
dataSource.dbCreate = update
#dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true
dataSource.url=jdbc:mysql://X.X.X.X/rundeckdb?autoReconnect=true
dataSource.username=rundeckuser
dataSource.password=XXXXXX
dataSource.driverClassName=com.mysql.jdbc.Driver
rundeck.log4j.config.file = /etc/rundeck/log4j.properties
rundeck.api.tokens.duration.max = 0

# Enables DB for Project configuration storage
rundeck.projectsStorageType=db

# Encryption for project config storage
rundeck.config.storage.converter.1.type=jasypt-encryption
rundeck.config.storage.converter.1.path=projects
rundeck.config.storage.converter.1.config.password=XXXXXX

# Enable DB for Key Storage
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=keys

# Enable DB for Key Storage
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=keys
rundeck.storage.converter.1.config.password=XXXXXX
```

`rundeck-config.groovy` file:
```
rdeck.base="/var/lib/rundeck"

/*rss.enabled if set to true enables RSS feeds that are public (non-authenticated) */
rss.enabled="false"
/* change hostname here*/
grails.serverURL="https://my-rundeck.com"

dataSource{
  dbCreate = "update"
  url="jdbc:mysql://X.X.X.X/rundeckdb?autoReconnect=true"
  username="rundeckuser"
  password="XXXXXX"
  driverClassName="com.mysql.jdbc.Driver"
}

rundeck.log4j.config.file = "/etc/rundeck/log4j.properties"
rundeck.api.tokens.duration.max = "0"

/* Enables DB for Project configuration storage*/
rundeck.projectsStorageType="db"

/* Encryption for project config storage*/
rundeck{
  config{
    storage{
      converter{
        1{
          type="jasypt-encryption"
          path="projects"
          config{
            password="XXXXXX"
          }
        }
      }
    }
  }
  storage{
    provider{
      1{
        type="db"
        path="keys"
        config{
          password="XXXXXX"
        }
      }
    }
  }
}
```

Thank you in advance Rundeck team.

**Comment by gschueler** [comment]
try quoting the `1` used in the storage converter configuration:

~~~
rundeck{
  config{
    storage{
      converter{
        '1'{
          type="jasypt-encryption"
          path="projects"
          config{
            password="XXXXXX"
          }
        }
      }
    }
  }
  storage{
    provider{
      '1'{
        type="db"
        path="keys"
        config{
          password="XXXXXX"
        }
      }
    }
  }
}
~~~

**Comment by happicamper** [comment]
Sorry for the delay.
@gschueler that fixes the issue, thanks!
