### ISSUE TITLE
Api reports incorrect execution status

### ISSUE THREAD

**Issue by alex067** [rundeck/rundeck#4892]
**Describe the bug**
The execution endpoint is reporting incorrect execution states for the wrong nodes.

I ran three job executions, where they only contain 1 step, and an error handler for that step. The step is executed on a remote node, which is an ec2 instance., and it just runs a remote script. The error handler runs a local command.

Job 1: fail the step, and succeed on the error handling step. 

Job 2: fail the step, and fail the error handling.

Job 3: success on the step, error handling does not get triggered.

When I use the execution endpoint: "api/14/execution/[ID]/state", the json object is not making much sense. 

Job 1: 
~~~
{'executionId': 3292, 'serverNode': '81ecf3222cb2', 'nodes': {'ec2': [{'executionState': 'SUCCEEDED', 'stepctx': '1'}]}, 'executionState': 'FAILED', 'updateTime': '2019-05-31T18:46:05Z', 'startTime': '2019-05-31T18:46:03Z', 'completed': True, 'endTime': '2019-05-31T18:46:05Z', 'allNodes': ['ec2'], 'stepCount': 1, 'steps': [{'duration': 1719, 'parameterStates': {}, 'executionState': 'SUCCEEDED', 'stepctx': '1', 'startTime': '2019-05-31T18:46:03Z', 'updateTime': '2019-05-31T18:46:05Z', 'id': '1', 'endTime': '2019-05-31T18:46:05Z', 'nodeStates': {'ec2': {'duration': 1719, 'meta': {'failureReason': 'NonZeroResultCode', 'resultCode': 127}, 'executionState': 'SUCCEEDED', 'startTime': '2019-05-31T18:46:03Z', 'updateTime': '2019-05-31T18:46:05Z', 'endTime': '2019-05-31T18:46:05Z'}}, 'nodeStep': True}], 'targetNodes': ['ec2']}
~~~

Why is this saying that, the job has a SUCCEEDED execution state for the ec2 node? When it failed on the ec2 node? The job was able to run the error handling, which is a local command, however for the local server node it shows execution state "FAILED"

Job 2:
~~~
{'executionId': 3305, 'serverNode': '81ecf3222cb2', 'nodes': {'ec2': [{'executionState': 'FAILED', 'stepctx': '1'}]}, 'executionState': 'FAILED', 'updateTime': '2019-05-31T20:32:29Z', 'startTime': '2019-05-31T20:32:28Z', 'completed': True, 'endTime': '2019-05-31T20:32:29Z', 'allNodes': ['ec2'], 'stepCount': 1, 'steps': [{'duration': 1737, 'parameterStates': {}, 'executionState': 'FAILED', 'stepctx': '1', 'startTime': '2019-05-31T20:32:28Z', 'updateTime': '2019-05-31T20:32:29Z', 'id': '1', 'endTime': '2019-05-31T20:32:29Z', 'nodeStates': {'ec2': {'duration': 1736, 'meta': {'failureReason': 'IOFailure', 'resultCode': 127}, 'executionState': 'FAILED', 'errorMessage': 'java.io.IOException: Cannot run program "lsasdfadf": error=2, No such file or directory', 'startTime': '2019-05-31T20:32:28Z', 'updateTime': '2019-05-31T20:32:29Z', 'endTime': '2019-05-31T20:32:29Z'}}, 'nodeStep': True}], 'targetNodes': ['ec2']}
~~~

This response is inline with what happened. It failed on the step, and failed the error handling.

Job 3: 
~~~
{'executionId': 3313, 'serverNode': '81ecf3222cb2', 'nodes': {'ec2': [{'executionState': 'SUCCEEDED', 'stepctx': '1'}]}, 'executionState': 'SUCCEEDED', 'updateTime': '2019-05-31T20:38:53Z', 'startTime': '2019-05-31T20:38:52Z', 'completed': True, 'endTime': '2019-05-31T20:38:53Z', 'allNodes': ['ec2'], 'stepCount': 1, 'steps': [{'duration': 1647, 'parameterStates': {}, 'executionState': 'SUCCEEDED', 'stepctx': '1', 'startTime': '2019-05-31T20:38:52Z', 'updateTime': '2019-05-31T20:38:52Z', 'id': '1', 'endTime': '2019-05-31T20:38:53Z', 'nodeStates': {'ec2': {'duration': 1647, 'executionState': 'SUCCEEDED', 'startTime': '2019-05-31T20:38:52Z', 'updateTime': '2019-05-31T20:38:53Z', 'endTime': '2019-05-31T20:38:53Z'}}, 'nodeStep': True}], 'targetNodes': ['ec2']}
~~~

This response is also inline with what happened. The step succeeded, and the error handling did not get called. Although it says SUCCEEDED for the local node, I guess we can interpret that has an overall success. 

**My Rundeck detail**

* Rundeck version: Rundeck 3.0.19-20190327
* install type: launcher 
* OS Name/version: Ubuntu 17.04
* DB Type/version: postgres

**To Reproduce**
Create a job that executes a step on a remote node, with a local command for error handling. Execute the job in three different states: Fail on remote node, succeed on error handling. Fail on both remote and local. Succeed on remote, doesn't matter for error handling.

**Expected behavior**
When the job fails the step, but succeeds on the local command / error handling, the response json from the execution endpoint should reflect that correctly.

{'executionId': 3305, 'serverNode': '81ecf3222cb2', 'nodes': {'ec2': [{'executionState': 'FAILED', 'stepctx': '1'}]}, 'executionState': 'SUCCEEDED', '... }

**Comment by MegaDrive68k** [comment]
Confirmed, also happens on 3.1.0-RC2 version.

### **ON 3.0.19**

**_excecution ok with error handler:_**

`{"executionId":5,"nodes":{"node00":[{"stepctx":"1","executionState":"SUCCEEDED"}]},"serverNode":"titan","executionState":"SUCCEEDED","completed":true,"targetNodes":["node00"],"allNodes":["node00"],"stepCount":1,"updateTime":"2019-07-31T18:13:38Z","startTime":"2019-07-31T18:13:37Z","endTime":"2019-07-31T18:13:38Z","steps":[{"nodeStates":{"node00":{"executionState":"SUCCEEDED","startTime":"2019-07-31T18:13:37Z","updateTime":"2019-07-31T18:13:38Z","duration":621,"endTime":"2019-07-31T18:13:38Z"}},"parameterStates":{},"id":"1","stepctx":"1","nodeStep":true,"executionState":"SUCCEEDED","startTime":"2019-07-31T18:13:37Z","updateTime":"2019-07-31T18:13:37Z","duration":622,"endTime":"2019-07-31T18:13:38Z"}]}`

**_execution error with error handler:_**

`{"executionId":6,"nodes":{"node00":[{"stepctx":"1","executionState":"SUCCEEDED"}]},"serverNode":"titan","executionState":"FAILED","completed":true,"targetNodes":["node00"],"allNodes":["node00"],"stepCount":1,"updateTime":"2019-07-31T18:14:16Z","startTime":"2019-07-31T18:14:15Z","endTime":"2019-07-31T18:14:16Z","steps":[{"nodeStates":{"node00":{"executionState":"SUCCEEDED","startTime":"2019-07-31T18:14:15Z","updateTime":"2019-07-31T18:14:16Z","duration":1237,"endTime":"2019-07-31T18:14:16Z","meta":{"resultCode":127,"failureReason":"NonZeroResultCode"}}},"parameterStates":{},"id":"1","stepctx":"1","nodeStep":true,"executionState":"SUCCEEDED","startTime":"2019-07-31T18:14:15Z","updateTime":"2019-07-31T18:14:15Z","duration":1239,"endTime":"2019-07-31T18:14:16Z"}]}`

**_excecution error without error handler:_**

`{"executionId":8,"nodes":{"node00":[{"stepctx":"1","executionState":"FAILED"}]},"serverNode":"titan","executionState":"FAILED","completed":true,"targetNodes":["node00"],"allNodes":["node00"],"stepCount":1,"updateTime":"2019-07-31T18:17:41Z","startTime":"2019-07-31T18:17:41Z","endTime":"2019-07-31T18:17:41Z","steps":[{"nodeStates":{"node00":{"executionState":"FAILED","startTime":"2019-07-31T18:17:41Z","updateTime":"2019-07-31T18:17:41Z","duration":611,"endTime":"2019-07-31T18:17:41Z","errorMessage":"Remote command failed with exit status 127","meta":{"resultCode":127,"failureReason":"NonZeroResultCode"}}},"parameterStates":{},"id":"1","stepctx":"1","nodeStep":true,"executionState":"FAILED","startTime":"2019-07-31T18:17:41Z","updateTime":"2019-07-31T18:17:41Z","duration":612,"endTime":"2019-07-31T18:17:41Z"}]}`

### **ON 3.1.0-RC2**

**_excecution ok with error handler:_**

`{"executionId":1,"nodes":{"node00":[{"stepctx":"1","executionState":"SUCCEEDED"}]},"serverNode":"titan","executionState":"SUCCEEDED","completed":true,"targetNodes":["node00"],"allNodes":["node00"],"stepCount":1,"updateTime":"2019-07-31T22:31:03Z","startTime":"2019-07-31T22:31:02Z","endTime":"2019-07-31T22:31:03Z","steps":[{"nodeStates":{"node00":{"executionState":"SUCCEEDED","startTime":"2019-07-31T22:31:02Z","updateTime":"2019-07-31T22:31:03Z","duration":906,"endTime":"2019-07-31T22:31:03Z"}},"parameterStates":{},"id":"1","stepctx":"1","nodeStep":true,"executionState":"SUCCEEDED","startTime":"2019-07-31T22:31:02Z","updateTime":"2019-07-31T22:31:02Z","duration":944,"endTime":"2019-07-31T22:31:03Z"}]}`

**_execution error with error handler:_**

`{"executionId":2,"nodes":{"node00":[{"stepctx":"1","executionState":"SUCCEEDED"}]},"serverNode":"titan","executionState":"FAILED","completed":true,"targetNodes":["node00"],"allNodes":["node00"],"stepCount":1,"updateTime":"2019-07-31T22:33:01Z","startTime":"2019-07-31T22:33:00Z","endTime":"2019-07-31T22:33:01Z","steps":[{"nodeStates":{"node00":{"executionState":"SUCCEEDED","startTime":"2019-07-31T22:33:00Z","updateTime":"2019-07-31T22:33:01Z","duration":1298,"endTime":"2019-07-31T22:33:01Z","meta":{"resultCode":127,"failureReason":"NonZeroResultCode"}}},"parameterStates":{},"id":"1","stepctx":"1","nodeStep":true,"executionState":"SUCCEEDED","startTime":"2019-07-31T22:33:00Z","updateTime":"2019-07-31T22:33:01Z","duration":1301,"endTime":"2019-07-31T22:33:01Z"}]}`

**_excecution error without error handler:_**

`
{"executionId":3,"nodes":{"node00":[{"stepctx":"1","executionState":"SUCCEEDED"}]},"serverNode":"titan","executionState":"SUCCEEDED","completed":true,"targetNodes":["node00"],"allNodes":["node00"],"stepCount":1,"updateTime":"2019-07-31T22:34:31Z","startTime":"2019-07-31T22:34:31Z","endTime":"2019-07-31T22:34:31Z","steps":[{"nodeStates":{"node00":{"executionState":"SUCCEEDED","startTime":"2019-07-31T22:34:31Z","updateTime":"2019-07-31T22:34:31Z","duration":603,"endTime":"2019-07-31T22:34:31Z"}},"parameterStates":{},"id":"1","stepctx":"1","nodeStep":true,"executionState":"SUCCEEDED","startTime":"2019-07-31T22:34:31Z","updateTime":"2019-07-31T22:34:31Z","duration":605,"endTime":"2019-07-31T22:34:31Z"}]}`
