### ISSUE TITLE
Rundeck returns a HTTP 404 trying to load assets/prototype/scriptaculous.js

### ISSUE THREAD

**Issue by jfillman** [rundeck/rundeck#4893]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [e.g. ubuntu 16.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by gschueler** [comment]
Can you post the rundeck version?

**Comment by jfillman** [comment]
Rundeck Pro 3.0.20-20190408

**Comment by gschueler** [comment]
note: need to cherrypick https://github.com/rundeck/rundeck/pull/4963/commits/56731c5c5d74ac4889083b92d0601c5489f59c3d
