### ISSUE TITLE
Rundeck returns a HTTP 404 trying to load /assets/bootstrap.min.css.map

### ISSUE THREAD

**Issue by jfillman** [rundeck/rundeck#4894]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [e.g. ubuntu 16.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by gschueler** [comment]
Can you post the rundeck version you are using, @?

**Comment by jfillman** [comment]
Sorry Greg. I should have done that to begin with.

Rundeck Pro 3.0.20-20190408

James Fillman
Systems Architect

Central 1 Credit Union
1441 Creekside Drive
Vancouver, British Columbia, Canada
V6J 4S7

jfillman@central1.com<mailto:jfillman@central1.com>
T: 604.730.6328

**Comment by gschueler** [comment]
note for fix: the bootstrap.min.css defines a sourceMappingURL which does not exist
