### ISSUE TITLE
Get user variables

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#4900]
Can I get the login user who executes the job directly in the job? Is this a function?

**Comment by puremourning** [comment]
${job.user.name}

**Comment by gschueler** [comment]
Please post help requests and usage questions to the rundeck-discuss mailing list http://groups.google.com/group/rundeck-discuss, thank you!

You can also get more information and links to other ways to get help here: http://rundeck.org/help.html
