### ISSUE TITLE
Job steps of type 'Job Reference' not being run after upgrade

### ISSUE THREAD

**Issue by mcgurksean** [rundeck/rundeck#4902]
**Describe the bug**
Job steps of type 'Job Reference' not being run after upgrade

**My Rundeck detail**

* Rundeck version: 3.0.21
* install type: deb
* OS Name/version: Centos 6.7
* DB Type/version: h2

**To Reproduce**
1. Click on 'Job Actions'
2. Select 'New Job'
3. Add a step of type 'Job Reference'
4. Select an existing job by using the project selector and “Choose a Job...” button
5. Click on 'Create' to save the job 
6. Run the job

**Expected behavior**
All the steps in the job are successfully executed.
The results of the successful execution can be seen in the Rundeck logs

**Screenshots**

![prsurundeck rpa01](https://user-images.githubusercontent.com/1913745/58867275-0d7b5d00-86b2-11e9-99c6-ce6ce6998405.jpg)

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 R2
 - Browser Google chrome
 - Version Version 74.0.3729.169

**Additional context**
This happened after the version of Rundeck was upgraded from 2.5.3 to 3.0.21

**Comment by mcgurksean** [comment]
**Screenshots**

![prsurundeck rpa01](https://user-images.githubusercontent.com/1913745/58867275-0d7b5d00-86b2-11e9-99c6-ce6ce6998405.jpg)

**Comment by mcgurksean** [comment]
N.B. As per the screenshot, the state of these job steps post-execution is 'not started'

**Comment by gschueler** [comment]
Can you post the following information related to your issue?

* Job definition (xml or yaml)
* Execution state file ("123.state.json") for the execution you screenshotted
* Any error messages found in the rundeck server log ("service.log") if present
* Any error messages in the web browser JS console if present

thanks

**Comment by mcgurksean** [comment]
Job definition:

`<joblist>
  <job>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>6a3f42ea-b915-421b-9343-9fb64dcec128</id>
    <loglevel>DEBUG</loglevel>
    <name>Call Echo Command</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo 'this is a test'</exec>
      </command>
      <command>
        <jobref group='Support' name='Echo' nodeStep='true' project='Tech_Ops-SSH'>
          <arg line='&apos;this is another test&apos;' />
          <uuid>fd529f69-6a87-4a4f-9e4a-551d5ad0a604</uuid>
        </jobref>
      </command>
    </sequence>
    <uuid>6a3f42ea-b915-421b-9343-9fb64dcec128</uuid>
  </job>
</joblist>`

Debug log output:

`08:43:51 [smcgurk@localhost _][VERBOSE] [workflow] Begin execution: node-first
08:43:51 [smcgurk@localhost _][VERBOSE] preparing for sequential execution on 1 nodes
08:43:51 [smcgurk@localhost _][VERBOSE] Executing command on node: localhost, NodeEntryImpl{tags=[], attributes={nodename=localhost, hostname=localhost, osVersion=2.6.32-573.el6.x86_64, osFamily=unix, osArch=amd64, description=Rundeck server node, osName=Linux, username=rundeck}, project='null'}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Start EngineWorkflowExecutor
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Update conditional state: {before.step.1=true, after.step.1=false}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] start conditions for step [1]: []
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Update conditional state: {after.step.2=false, before.step.2=true}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] start conditions for step [2]: [(after.step.1 == 'true')]
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Create rule engine with rules: RuleEngine{ruleSet=[Rule: Conditions([(after.step.1 == 'true')]) => DataState{state={step.2.start=true}}, Rule: Conditions([(workflow.keepgoing == 'false'), (step.any.state.failed == 'true')]) => DataState{state={workflow.done=true}}, Rule: Conditions([(step.any.flowcontrol.halt == 'true')]) => DataState{state={workflow.done=true}}, Rule: Conditions([]) => DataState{state={step.1.start=true}}]}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Create workflow engine with state: StateLogger{state=DataState{state={job.url=http://rundeckserver.domain.com:4440/project/Releng/execution/follow/90970, job.id=6a3f42ea-b915-421b-9343-9fb64dcec128, after.step.2=false, job.loglevel=DEBUG, node.os-name=Linux, after.step.1=false, job.retryInitialExecId=0, node.hostname=localhost, node.os-family=unix, job.user.name=smcgurk, node.tags=, node.description=Rundeck server node, node.username=rundeck, job.name=Call Echo Command, job.successOnEmptyNodeFilter=false, job.executionType=user, job.wasRetry=false, job.project=Releng, before.step.1=true, before.step.2=true, job.username=smcgurk, node.os-arch=amd64, job.retryAttempt=0, workflow.id=6f5d59fd-2231-4c03-82f3-2869a0450d1b, node.os-version=2.6.32-573.el6.x86_64, workflow.keepgoing=false, job.execid=90970, node.name=localhost, job.serverUrl=http://rundeckserver.domain.com:4440/, job.threadcount=1}}}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Begin: Workflow begin
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] WillProcessStateChange: saw state changes: {workflow.state=started}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Update conditional state: {workflow.state=started}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Update conditional state: {step.1.start=true}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] DidProcessStateChange: applied state changes and rules (changed? true): StateLogger{state=DataState{state={job.url=http://rundeckserver.domain.com:4440/project/Releng/execution/follow/90970, job.id=6a3f42ea-b915-421b-9343-9fb64dcec128, after.step.2=false, job.loglevel=DEBUG, node.os-name=Linux, after.step.1=false, workflow.state=started, job.retryInitialExecId=0, node.hostname=localhost, node.os-family=unix, job.user.name=smcgurk, node.tags=, node.description=Rundeck server node, node.username=rundeck, job.name=Call Echo Command, job.successOnEmptyNodeFilter=false, job.executionType=user, job.wasRetry=false, job.project=Releng, before.step.1=true, step.1.start=true, before.step.2=true, job.username=smcgurk, node.os-arch=amd64, job.retryAttempt=0, workflow.id=6f5d59fd-2231-4c03-82f3-2869a0450d1b, node.os-version=2.6.32-573.el6.x86_64, workflow.keepgoing=false, job.execid=90970, node.name=localhost, job.serverUrl=http://rundeckserver.domain.com:4440/, job.threadcount=1}}}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] WillRunOperation: operation starting: Step{stepNum=1, label='null'}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] LoopProgress: Pending(2) => run(1), skip(0), remain(1)
08:43:51 [smcgurk@localhost 1][VERBOSE] [workflow] Begin step: 1,NodeDispatch
08:43:51 [smcgurk@localhost 1][VERBOSE] 1: Workflow step executing: CommandItem{command=[2 words]}
08:43:51 [smcgurk@localhost 1][VERBOSE] preparing for sequential execution on 1 nodes
08:43:51 [smcgurk@localhost 1][VERBOSE] Executing command on node: localhost, NodeEntryImpl{tags=[], attributes={nodename=localhost, hostname=localhost, osVersion=2.6.32-573.el6.x86_64, osFamily=unix, osArch=amd64, description=Rundeck server node, osName=Linux, username=rundeck}, project='null'}
08:43:51 [rundeck@localhost 1][VERBOSE] [workflow] beginExecuteNodeStep(localhost): NodeDispatch: CommandItem{command=[2 words]}
08:43:51 [rundeck@localhost 1][VERBOSE] using charset: null
08:43:51 [rundeck@localhost 1][VERBOSE] Current OS is Linux
08:43:51 [rundeck@localhost 1][VERBOSE] Adding reference: ant.PropertyHelper
08:43:51 [rundeck@localhost 1][VERBOSE] Project base dir set to: /var/lib/rundeck
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_LOGLEVEL=DEBUG
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_ID=6a3f42ea-b915-421b-9343-9fb64dcec128
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_NODE_OS_NAME=Linux
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_USERNAME=smcgurk
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_NODE_HOSTNAME=localhost
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_NODE_OS_FAMILY=unix
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_EXECID=90970
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_NODE_USERNAME=rundeck
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_URL=http://rundeckserver.domain.com:4440/project/Releng/execution/follow/90970
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_NODE_TAGS=
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_PROJECT=Releng
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_NAME=Call Echo Command
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_NODE_OS_ARCH=amd64
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_NODE_OS_VERSION=2.6.32-573.el6.x86_64
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_SERVERURL=http://rundeckserver.domain.com:4440/
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_NODE_NAME=localhost
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_EXECUTIONTYPE=user
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_THREADCOUNT=1
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_WASRETRY=false
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_RETRYATTEMPT=0
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_SUCCESSONEMPTYNODEFILTER=false
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_USER_NAME=smcgurk
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_JOB_RETRYINITIALEXECID=0
08:43:51 [rundeck@localhost 1][VERBOSE] Setting environment variable: RD_NODE_DESCRIPTION=Rundeck server node
08:43:51 [rundeck@localhost 1][VERBOSE] Executing '/bin/sh' with arguments:
'-c'
'echo this is a test'

The ' characters around the executable and arguments are
not part of the command.

08:43:51 [rundeck@localhost 1][VERBOSE] Execute:Java13CommandLauncher: Executing '/bin/sh' with arguments:
'-c'
'echo this is a test'

The ' characters around the executable and arguments are
not part of the command.

08:43:51 [rundeck@localhost 1][NORMAL] this is a test
08:43:51 [rundeck@localhost 1][VERBOSE] Setting project property: 1559637831222.node.localhost.LocalNodeExecutor.result -> 0
08:43:51 [rundeck@localhost 1][VERBOSE] [workflow] finishExecuteNodeStep(localhost): NodeDispatch: Succeeded
08:43:51 [smcgurk@localhost 1][VERBOSE] 1: Workflow step finished, result: Dispatch successful (1 nodes)
08:43:51 [smcgurk@localhost 1][VERBOSE] [workflow] Finish step: 1,NodeDispatch
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] OperationSuccess: operation succeeded: StepSuccess{stepNum=1, stepResultCapture=StepResultCapture{stepResult=Dispatch successful (1 nodes), stepSuccess=true, statusString='null', controlBehavior=null, resultData=MultiDataContextImpl(map={ContextView(step:1, node:localhost)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:localhost)=BaseDataContext{{exec={exitCode=0}}}}, base=null)}, newState=DataState{state={step.1.completed=true, step.any.state.success=true, before.step.1=false, step.1.state=success, after.step.1=true}}}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] WillProcessStateChange: saw state changes: {step.any.state.success=true, before.step.1=false, step.1.state=success, after.step.1=true, step.1.completed=true}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Update conditional state: {step.any.state.success=true, before.step.1=false, step.1.state=success, after.step.1=true, step.1.completed=true}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Update conditional state: {step.1.start=true, step.2.start=true}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] DidProcessStateChange: applied state changes and rules (changed? true): StateLogger{state=DataState{state={job.url=http://rundeckserver.domain.com:4440/project/Releng/execution/follow/90970, job.id=6a3f42ea-b915-421b-9343-9fb64dcec128, after.step.2=false, job.loglevel=DEBUG, step.any.state.success=true, node.os-name=Linux, after.step.1=true, step.2.start=true, workflow.state=started, job.retryInitialExecId=0, node.hostname=localhost, node.os-family=unix, job.user.name=smcgurk, node.tags=, node.description=Rundeck server node, node.username=rundeck, job.name=Call Echo Command, step.1.state=success, job.successOnEmptyNodeFilter=false, job.executionType=user, step.1.completed=true, job.wasRetry=false, job.project=Releng, before.step.1=false, step.1.start=true, before.step.2=true, job.username=smcgurk, node.os-arch=amd64, job.retryAttempt=0, workflow.id=6f5d59fd-2231-4c03-82f3-2869a0450d1b, node.os-version=2.6.32-573.el6.x86_64, workflow.keepgoing=false, job.execid=90970, node.name=localhost, job.serverUrl=http://rundeckserver.domain.com:4440/, job.threadcount=1}}}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] WillRunOperation: operation starting: Step{stepNum=2, label='null'}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] LoopProgress: Pending(1) => run(1), skip(0), remain(0)
08:43:51 [smcgurk@localhost 2][VERBOSE] [workflow] Begin step: 2,NodeDispatch
08:43:51 [smcgurk@localhost 2][VERBOSE] 2: Workflow step executing: JobReferenceItem{jobIdentifier='fd529f69-6a87-4a4f-9e4a-551d5ad0a604', project='Tech_Ops-SSH', nodeStep=true}
08:43:51 [smcgurk@localhost 2][VERBOSE] preparing for sequential execution on 1 nodes
08:43:51 [smcgurk@localhost 2][VERBOSE] Executing command on node: localhost, NodeEntryImpl{tags=[], attributes={nodename=localhost, hostname=localhost, osVersion=2.6.32-573.el6.x86_64, osFamily=unix, osArch=amd64, description=Rundeck server node, osName=Linux, username=rundeck}, project='null'}
08:43:51 [rundeck@localhost 2][VERBOSE] [workflow] beginExecuteNodeStep(localhost): NodeDispatch: JobReferenceItem{jobIdentifier='fd529f69-6a87-4a4f-9e4a-551d5ad0a604', project='Tech_Ops-SSH', nodeStep=true}
08:43:51 [rundeck@localhost 2][VERBOSE] [workflow] finishExecuteNodeStep(localhost): NodeDispatch: Succeeded
08:43:51 [smcgurk@localhost 2][VERBOSE] 2: Workflow step finished, result: Dispatch successful (1 nodes)
08:43:51 [smcgurk@localhost 2][VERBOSE] [workflow] Finish step: 2,NodeDispatch
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] OperationSuccess: operation succeeded: StepSuccess{stepNum=2, stepResultCapture=StepResultCapture{stepResult=Dispatch successful (1 nodes), stepSuccess=true, statusString='null', controlBehavior=null, resultData=MultiDataContextImpl(map={}, base=null)}, newState=DataState{state={after.step.2=true, step.any.state.success=true, before.step.2=false, step.2.state=success, step.2.completed=true}}}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] WillProcessStateChange: saw state changes: {after.step.2=true, step.any.state.success=true, before.step.2=false, step.2.state=success, step.2.completed=true}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Update conditional state: {after.step.2=true, step.any.state.success=true, before.step.2=false, step.2.state=success, step.2.completed=true}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Update conditional state: {step.1.start=true, step.2.start=true}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] DidProcessStateChange: applied state changes and rules (changed? true): StateLogger{state=DataState{state={job.url=http://rundeckserver.domain.com:4440/project/Releng/execution/follow/90970, job.id=6a3f42ea-b915-421b-9343-9fb64dcec128, after.step.2=true, job.loglevel=DEBUG, step.any.state.success=true, node.os-name=Linux, after.step.1=true, step.2.start=true, workflow.state=started, job.retryInitialExecId=0, node.hostname=localhost, node.os-family=unix, job.user.name=smcgurk, node.tags=, node.description=Rundeck server node, node.username=rundeck, job.name=Call Echo Command, step.1.state=success, step.2.completed=true, job.successOnEmptyNodeFilter=false, job.executionType=user, step.1.completed=true, job.wasRetry=false, job.project=Releng, before.step.1=false, step.1.start=true, before.step.2=false, job.username=smcgurk, node.os-arch=amd64, job.retryAttempt=0, workflow.id=6f5d59fd-2231-4c03-82f3-2869a0450d1b, node.os-version=2.6.32-573.el6.x86_64, workflow.keepgoing=false, job.execid=90970, node.name=localhost, job.serverUrl=http://rundeckserver.domain.com:4440/, job.threadcount=1, step.2.state=success}}}
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] LoopProgress: Pending(0) => run(0), skip(0), remain(0)
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] EndOfChanges: No more state changes expected, finishing workflow.
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] WillShutdown: Workflow engine shutting down (interrupted? false)
08:43:51 [smcgurk@localhost _][VERBOSE] [wf:6f5d59fd-2231-4c03-82f3-2869a0450d1b] Complete: Workflow complete: [Step{stepNum=1, label='null'}: StepSuccess{stepNum=1, stepResultCapture=StepResultCapture{stepResult=Dispatch successful (1 nodes), stepSuccess=true, statusString='null', controlBehavior=null, resultData=MultiDataContextImpl(map={ContextView(step:1, node:localhost)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:localhost)=BaseDataContext{{exec={exitCode=0}}}}, base=null)}, newState=DataState{state={step.1.completed=true, step.any.state.success=true, before.step.1=false, step.1.state=success, after.step.1=true}}}, Step{stepNum=2, label='null'}: StepSuccess{stepNum=2, stepResultCapture=StepResultCapture{stepResult=Dispatch successful (1 nodes), stepSuccess=true, statusString='null', controlBehavior=null, resultData=MultiDataContextImpl(map={}, base=null)}, newState=DataState{state={after.step.2=true, step.any.state.success=true, before.step.2=false, step.2.state=success, step.2.completed=true}}}]
08:43:51 [smcgurk@localhost _][VERBOSE] [workflow] Finish execution:  node-first: [Workflow result: , Node failures: {localhost=[]}, status: succeeded]
`

Execution file state:

`{"executionId":91018,"nodes":{"localhost":[{"stepctx":"1","executionState":"SUCCEEDED"},{"stepctx":"2/1","executionState":"NOT_STARTED"}]},"serverNode":"localhost","executionState":"SUCCEEDED","completed":true,"targetNodes":["localhost"],"allNodes":["localhost"],"stepCount":2,"updateTime":"2019-06-05T08:02:48Z","startTime":"2019-06-05T08:02:48Z","endTime":"2019-06-05T08:02:48Z","steps":[{"nodeStates":{"localhost":{"executionState":"SUCCEEDED","startTime":"2019-06-05T08:02:48Z","updateTime":"2019-06-05T08:02:48Z","duration":408,"endTime":"2019-06-05T08:02:48Z"}},"parameterStates":{},"id":"1","stepctx":"1","nodeStep":true,"executionState":"SUCCEEDED","startTime":"2019-06-05T08:02:48Z","updateTime":"2019-06-05T08:02:48Z","duration":410,"endTime":"2019-06-05T08:02:48Z"},{"hasSubworkflow":true,"workflow":{"executionState":"SUCCEEDED","completed":true,"targetNodes":["localhost"],"allNodes":["localhost"],"stepCount":1,"updateTime":"2019-06-05T08:02:48Z","startTime":"2019-06-05T08:02:48Z","endTime":"2019-06-05T08:02:48Z","steps":[{"nodeStates":{"localhost":{"executionState":"NOT_STARTED","startTime":null,"updateTime":null,"duration":-1,"endTime":"2019-06-05T08:02:48Z"}},"parameterStates":{},"id":"1","stepctx":"2/1","nodeStep":true,"executionState":"NOT_STARTED","startTime":null,"updateTime":null,"duration":-1,"endTime":"2019-06-05T08:02:48Z"}]},"parameterStates":{},"id":"2","stepctx":"2","nodeStep":true,"executionState":"SUCCEEDED","startTime":"2019-06-05T08:02:48Z","updateTime":"2019-06-05T08:02:48Z","duration":9,"endTime":"2019-06-05T08:02:48Z"}]`

**Comment by mcgurksean** [comment]
No errors in the service.log file

**Comment by gschueler** [comment]
can you include as well the job definition for the referenced job "Support/Echo" ? 
Are the jobs in the same project?

**Comment by mcgurksean** [comment]
Job definition for Support/ Echo Job:

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='message'>
          <description>The message to be echoed</description>
        </option>
      </options>
    </context>
    <description>Just output something</description>
    <executionEnabled>true</executionEnabled>
    <group>Support</group>
    <id>fd529f69-6a87-4a4f-9e4a-551d5ad0a604</id>
    <loglevel>INFO</loglevel>
    <name>Echo</name>
    <nodeFilterEditable>true</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <node-step-plugin type='localexec'>
          <configuration>
            <entry key='command' value='echo "Message from: " ${job.serverUrl} " - " ${option.message}' />
          </configuration>
        </node-step-plugin>
      </command>
    </sequence>
    <uuid>fd529f69-6a87-4a4f-9e4a-551d5ad0a604</uuid>
  </job>
</joblist>
```

Jobs are in 2 different projects - 1 is in project 'Releng' and 1 in project 'Tech_Ops-SSH'

**Comment by MegaDrive68k** [comment]
Hi @mcgurksean,

What Java JDK version do you use in your current Rundeck instance?

You can see that doing:

`java -version`

Rundeck 3.0.X requires JDK 1.8 to works.

Greetings!

**Comment by mcgurksean** [comment]
Hi there,

Many thanks for the reply.

Java version detailed below:

```
$ java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b04)
OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
```

**Comment by mcgurksean** [comment]
Yes - that's probably it.

With the upgrade to version 3.0.21, the ACL syntax changed so I modified some of the ACL rules.

What should I be looking out for in the rules?

**Comment by MegaDrive68k** [comment]
@mcgurksean 

Check that the user/group have access to your reference/referenced project and jobs, make sure that the users/groups can read and execute it.

You can test without restriction first an re-write your ACL, here you have a good starting point:

https://docs.rundeck.com/docs/administration/security/access-control-policy.html

And good example:

https://stackoverflow.com/questions/42958922/rundeck-acl-limit-user-to-only-see-specific-groups-in-project

Regards!

**Comment by mcgurksean** [comment]
@MegaDrive68k Thanks for this!

Just one question:

If **I** (as a user or group) have access to the referenced project/ job 'Support/ Echo' (I know this because I am able to execute it successfully) but the 'Releng/ Call Echo Command' project/ job is not able to call it then where should I be looking to make changes in the ACL?

**Comment by mcgurksean** [comment]
@MegaDrive68k  After looking at issue #[3443](https://github.com/rundeck/rundeck/issues/3443) ('Job step skipped for no apparent reason'), I have changed the Workflow Strategy on the referenced job from 'Node First' to 'Sequential' and it is now working as expected.
