### ISSUE TITLE
Review reverted fix for #4269

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#4905]
While reviewing the PR for a fix that didn't involve reverting the changes to fix #4269 introduced in #4522, I ended up reviewing those changes as well and discovered the precise reason(I hope!) it caused the issue we are seeing with the stale project settings. I also believe we should revert those changes and tackle the lock timeout issue separately if it re-appears.
 
PR #4522 introduced a new `withNewTransaction` closure [here](https://github.com/rundeck/rundeck/pull/4522/files#diff-7bf7c6a1d5fb256a3a46a7101cf128cbR290). Unfortunately this has two effects:
1. It bypasses the current hibernate session and transaction, instead opening up a transaction on a new connection. The transaction is not "nested" or piggy-backed onto the current transaction.
2. It caused the return [here](https://github.com/rundeck/rundeck/pull/4522/files#diff-7bf7c6a1d5fb256a3a46a7101cf128cbR313) to be the return for the new closure, not the return for the outer closure. Now `saveStorage` always returns false, and the save occurs again inside a `withSession` also bypassing the current session/transaction.

So after these changes _all_ `saveStorage` calls end up outside the existing session/transaction and the storage, if previously loaded, becomes stale in the outer session.

When saving the project config the project storage manager, after storing the configuration, invalidates the project cache and causes it to reload [here](https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/services/rundeck/services/ProjectManagerService.groovy#L445-L446). My testing shows that even though the database is hit due to using dynamic finders underneath(and it returns the new data becuase we use READ_COMMITTED), hibernate stills returns the object that was loaded into the session earlier.

Because the update was saved out of the current session, the object loaded into the cache is stale. At this point subsequent visits to the edit project settings page will cause the stale object in the project cache to be used to populate the form fields.

There are a few ways I came up with to "make it work", but I suspect the storage service may be the wrong layer to be making decisions about what should and shouldn't be participating in a transaction if we can help it. It would take control of transactional boundaries and participation away from the higher layers, and it may cause nuanced state issues like this one in unexpected places.

_Originally posted by @ProTip in https://github.com/rundeck/rundeck/issues/4742#issuecomment-497910227_

**Comment by fdevans** [comment]
@gschueler What's the latest on this?

**Comment by Dmitry1987** [comment]
just stumbled upon an issue updating project configs, it doesn't save settings no matter what, restarted the service a few times, verified all file permissions, is it a database problem?  
our version is 
```
Rundeck 3.2.8-20200608
```
