### ISSUE TITLE
RDK Cluster : scheduled job on node A killed on node B : still launched

### ISSUE THREAD

**Issue by nmamn** [rundeck/rundeck#4916]
Hi,

It's been a couple of time we're seing this behaviour, and we think we've narrowed it down.

**Describe the bug**
We have a 2 nodes cluster.
A job was scheduled to run on node A, and a user killed this job. However he was connected to node B. Seemingly it seemed ok. The job appeared in the activity tab as killed.

However, the job was launched anyway by node A at the desired time.

In the activity TAB, we can see both executions (the one being killed, the one launched anyway) with the same ID. See screenshot below 👍 

![rdk_same_id](https://user-images.githubusercontent.com/20321572/59020946-3aaf4300-884b-11e9-8756-a7cb14dea55a.png)

**My Rundeck detail**

* Rundeck version: 3.0.17
* install type: launcher
* OS Name/version: Ubuntu 16.04
* DB Type/version: mysql

**To Reproduce**
1. On a cluster, schedule a job to run in X hours, it will be scheduled on the node you're connected to
2. Connect to the other node by whichever way you want
3. kill the job
4. the job will still be triggered by the first node, despite a trace being present in the activity tab

Thanks a lot

**Comment by MegaDrive68k** [comment]
Reproduced on 3.0.22.

![issuerdk](https://user-images.githubusercontent.com/51376003/59231251-08d11000-8bae-11e9-9c08-1804f45abaa2.png)

Greetings.

**Comment by MegaDrive68k** [comment]
In my case under 3.1.0-RC2:

1. Create the job with a single step, run it from cluster member A.
2. From cluster member B kill the same job under execution.

Execution ID shows duplicated with "OK" status.

![Screenshot_20190725_175441](https://user-images.githubusercontent.com/51376003/61912680-d2a2e200-af08-11e9-835c-c6a59332c83c.png)
