### ISSUE TITLE
Node filter doesn't return matched nodes

### ISSUE THREAD

**Issue by rsridivya** [rundeck/rundeck#4920]
**Describe the bug**
Node filter doesn't return matched nodes when a regular expression is given.

**My Rundeck detail**

* Rundeck version: [ e.g. 3.0.19]
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [e.g. ubuntu 16.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**
1. Go to 'edit job'
2. Scroll down to 'Node Filter.'
3. Include a regex (name: *se-prom*)
4. Check if the nodes are displayed under Matched Nodes

**Expected behavior**
When i give a regex as above (name: "se-prom*) , it displays the nodes matching se-prom pattern under Matched Nodes

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome

**Additional context**
I tried formats like 
*se-prom*
/se-prom/
/*se-prom*/
name: se-prom*
Followed all formats included in https://docs.rundeck.com/docs/manual/nodes.html#node-filtering, but none of them worked.
Can you please help me how I have to include the filter. Does it need any configuration to adjust the filters. 
Is there any bug related to node filters for rundeck version 3.0.19.
Thanks.

**Comment by rsridivya** [comment]
Found answer

**Comment by NFDWADM** [comment]
@rsridivya It would be nice if you could share your solution.
