### ISSUE TITLE
Print all data values known to job, ignorant of keys

### ISSUE THREAD

**Issue by achilds-vela** [rundeck/rundeck#4927]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**
Hello all, I'd like a way to just print all the known data values from a log filter at a certain step in the job, like in a script.

**Describe the solution you'd like**
I know how to print a data value when I know the key (example `echo @data.my_key@`), but it'd be nice to have a way to print all data values known to a job at some step in the job. Something like the following syntax for example:

`echo "@data.*@"`

**Describe alternatives you've considered**

**Additional context**

**Comment by gschueler** [comment]
Have you tried the "Log Data" step? it does exactly this.
