### ISSUE TITLE
ed25519 SSH keys and keys created with -o option not working

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#4954]
**Describe the bug**
Hi guys

I'm having problems getting newer SSH key features working with rundeck. Am I doing something wrong or are they not supported? For example:

Keys created with the **ssh-keygen -o** flag result in a **_Failed: SSHProtocolFailure: invalid privatekey_** error

Keys created with the **ssh-keygen -t ed25519** flag result in a **_Failed: SSHProtocolFailure: invalid privatekey_** error

The only option which seems to work are standard rsa keys which aren't the greatest option for security nowadays. Gitlab summarises it well here: https://docs.gitlab.com/ee/ssh/ 

Thanks!
**My Rundeck detail**

* Rundeck version: Latest
* OS Name/version: ubuntu 18.04
* DB Type/version: mysql

**Comment by MegaDrive68k** [comment]
Hi @menathor 

Rundeck uses JSch library, right now it does not support ed25519 keys.

You can see that in this Google Groups thread.

https://groups.google.com/forum/#!topic/rundeck-discuss/an9OKLUfMD8

Try with OpenSSH keys.

Regards!

**Comment by menathor** [comment]
Hi @MegaDrive68k 

Ah that would explain it, thanks for the info! Have you had any experience with using the OpenSSH plugin? Just wondering if there is any rundeck functionality or features I won't be able to use with it vs. the build in jsch node executor. 

Thanks again!

**Comment by menathor** [comment]
@MegaDrive68k Oops never mind, I didn't notice the fact that the openssh executor comes preinstalled :P. All good and working well, thanks again

**Comment by menathor** [comment]
Sorry, I spoke to soon. The OpenSSH executor doesn't work with -t ed25519 or -o option either. Instead of throwing an error it just times out. Standard RSA key pairs work.

It's don't think it's a problem with my OpenSSH configuration because I'm able to log in to nodes manually using ed25519 key / -o signed key pairs.

**Comment by quinndiggity** [comment]
> In an effort to focus on bugs and issues that impact currently supported versions of Rundeck, we have elected to notify GitHub issue creators if their issue is classified as stale and close the issue. An issue is identified as stale when there have been no new comments, responses or other activity within the last 12 months. If a closed issue is still present please feel free to open a new Issue against the current version and we will review it. If you are an enterprise customer, please contact your Rundeck Support to assist in your request.
> Thank you, The Rundeck Team

This is ridiculous
