### ISSUE TITLE
Update documentation dispatching to nodes

### ISSUE THREAD

**Issue by dpomnean** [rundeck/rundeck#4968]
**Describe the bug**
Some documentation is out of date and needs to be updated to reflect the newer options.

**To Reproduce**
https://docs.rundeck.com/docs/manual/creating-jobs.html#node-dispatching-and-filtering

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/17032114/59630466-5fd96680-9113-11e9-94ca-cd81a12b5e93.png)

**Comment by jessemarple** [comment]
Issue moved to [rundeck/docs #270](https://github.com/rundeck/docs/issues/270) via [**ZenHub**](https://www.zenhub.com/)
