### ISSUE TITLE
`Select all` only select first element in bulk delete executions

### ISSUE THREAD

**Issue by jairov4** [rundeck/rundeck#4969]
**Describe the bug**
In the activity panel, the select all button will only select the first entry in bulk delete mode.

**My Rundeck detail**

* Rundeck version: 3.0.22, 3.0.21
* install type: docker
* OS Name/version: debian
* DB Type/version: mysql

**To Reproduce**
1. Go to activity
2. Click on bulk delete
3. Click select all
4. See error: the first element is selected only

**Expected behavior**
Select all should select all entries of the filtered view

**Desktop (please complete the following information):**
 - OS: Mac OS Mojave
 - Browser: Chrome, Safari, Firefox

**Comment by MegaDrive68k** [comment]
Also happens on 3.0.23 WAR.

**Comment by zoredache** [comment]
Replicated

Chrome reports this error in javascript console

    activity?offset=380&max=20:530 Uncaught ReferenceError: ko is not defined
        at HTMLInputElement.<anonymous> (activity?offset=380&max=20:530)
        at Function.each (jquery-5393bf5931b3c4e7052edeec0d67327b.js:657)
        at init.each (jquery-5393bf5931b3c4e7052edeec0d67327b.js:266)
        at HTMLSpanElement.bulkEditSelectAll (activity?offset=380&max=20:528)
        at HTMLSpanElement.dispatch (jquery-5393bf5931b3c4e7052edeec0d67327b.js:5095)
        at HTMLSpanElement.elemData.handle (jquery-5393bf5931b3c4e7052edeec0d67327b.js:4766)

Firefox reports this error in javascript console

    ReferenceError: ko is not defined activity:530:17
        bulkEditSelectAll https://rundeck.example.org/project/N/activity?offset=380&max=20:530
        jQuery 2
        bulkEditSelectAll https://rundeck.example.org/project/N/activity?offset=380&max=20:528
        jQuery 2
            dispatch
            handle

**Comment by MegaDrive68k** [comment]
Solved on 3.1-RC2 :-)

**Comment by MegaDrive68k** [comment]
Solved on 3.1.0/3.1.1.
