### ISSUE TITLE
rd-acl 3.0.*: Error: Could not find or load main class com.dtolabs.rundeck.core.cli.acl.AclTool

### ISSUE THREAD

**Issue by gaetanquentin** [rundeck/rundeck#4971]
**Describe the bug**
the cli $RDECK_BASE/tools/bin/rd-acl can't be run

**My Rundeck detail**

* Rundeck version: 3.0.22
* install type: war
* OS Name/version: Ubuntu 16.04.5 LTS
* DB Type/version: postgres 10
* java: OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)

**To Reproduce**
1. on rundeck user account shell: export RDECK_BASE=/data/rundeck-prod
2. bash -x /data/rundeck-prod/tools/bin/rd-acl
3. see results below

**Expected behavior**
rd-acl be executed

**Results**
<pre>
+ '[' -n '' -a '' = Windows_NT ']'
+++ dirname /data/rundeck-prod/tools/bin/rd-acl/
++ cd /data/rundeck-prod/tools/bin/../..
++ pwd
+ PDIR=/data/rundeck-prod
+ '[' -r /data/rundeck-prod/etc/framework.properties ']'
+ . /data/rundeck-prod/etc/profile
++ JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
++ JAVA_CLASS_PATH=/usr/share/java
++ export JAVA_HOME
++ RDECK_BASE=/data/rundeck-prod
++ RDECK_JVM='-classpath /usr/share/java -Drundeck.jaaslogin=true -Dloginmodule.name=RDpropertyfilelogin -Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG'
++ export RDECK_BASE RDECK_JVM
+ '[' /data/rundeck-prodX = X ']'
+ exec java -classpath /usr/share/java -Drundeck.jaaslogin=true -Dloginmodule.name=RDpropertyfilelogin -Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG -classpath -Duser.java_home=/usr/lib/jvm/java-8-openjdk-amd64 -Drdeck.base=/data/rundeck-prod com.dtolabs.rundeck.core.cli.acl.AclTool
Error: Could not find or load main class com.dtolabs.rundeck.core.cli.acl.AclTool
</pre>

**Questions**
-classpath ${CLI_CP}  : where is defined CLI_CP?

**Comment by MegaDrive68k** [comment]
Hi @gaetanquentin 

Check that Rundeck can read the **/etc/rundeck/profile** file and is well configured.

It's similar to this issue:

https://github.com/rundeck/rundeck/issues/2241

Regards!

**Comment by gaetanquentin** [comment]
@MegaDrive68k  it does , as the output show it ^^
As i said: where is defined the CLI_CP variable, needed to define the classpath?

**Comment by MegaDrive68k** [comment]
@gaetanquentin 

You can see the CLI_CP defined in the profile file, like:

```
CLI_CP=
for i in `ls $LIBDIR/*.jar`
do
 CLI_CP=${CLI_CP}:${i}
done
export CLI_CP
```

Can you post your profile file to take a look?

Regards!

**Comment by gaetanquentin** [comment]
I had to create it myself, since the war installation mode do not create it:
So there is no CLI_CP variable.

#Environment variables for shell tools
JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
JAVA_CLASS_PATH="/usr/share/java"

export JAVA_HOME

RDECK_BASE=/data/rundeck-lab
RDECK_JVM="-classpath $JAVA_CLASS_PATH -Drundeck.jaaslogin=true -Dloginmodule.name=RDpropertyfilelogin -Dcom.dtolabs.rundeck.jetty.jaas.LEVEL=DEBUG -Dserver.http.host=\"172.18.12.10\""
export RDECK_BASE RDECK_JVM

**Comment by MegaDrive68k** [comment]
Hi @gaetanquentin 

That's the default profile file in my test environment, please compare it:

```
RDECK_BASE=/path/yo/your/rundeck/war
export RDECK_BASE

JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
export JAVA_HOME

PATH=$JAVA_HOME/bin:$RDECK_BASE/tools/bin:$PATH
export PATH

export JAVA_CMD=$JAVA_HOME/bin/java

if test -n "$JRE_HOME"
then
   unset JRE_HOME
fi

LIBDIR=$RDECK_BASE/tools/lib

CLI_CP=
for i in `ls $LIBDIR/*.jar`
do
 CLI_CP=${CLI_CP}:${i}
done
export CLI_CP

#
# Set min/max heap size
#
export RDECK_JVM="$RDECK_JVM -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server"

export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=$RDECK_BASE/etc/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"

umask 002
```

Regards!

**Comment by gaetanquentin** [comment]
i integrated  the block below in my profile:

"LIBDIR=$RDECK_BASE/tools/lib

CLI_CP=
for i in `ls $LIBDIR/*.jar`
do
 CLI_CP=${CLI_CP}:${i}
done
export CLI_CP"

there are still missing files, not installed by the war install:
/data/rundeck-lab/tools/bin/rd-acl 
log4j:ERROR Could not read configuration file [/data/rundeck-lab/etc/cli-log4j.properties].
java.io.FileNotFoundException: /data/rundeck-lab/etc/cli-log4j.properties (No such file or directory)

**Comment by ProTip** [comment]
Hi @gaetanquentin ,

Certain files are only copied into place during the first run. [War installation documentation](https://docs.rundeck.com/docs/administration/install/launcher.html) includes steps to ensure Rundeck is booted at least once to complete the process.

This _is_ a bit funky and unfortunately `$RDECK_BASE/etc/profile` is one of the files that only gets copied in to place on the first run and not during an `--installonly`.

**Comment by gaetanquentin** [comment]
And etc/cli-log4j.properties ?

**Comment by MegaDrive68k** [comment]
@gaetanquentin 

`cli-log4j.properties` is a configuration file and it's created at the first run.

https://docs.rundeck.com/docs/administration/configuration/configuration-file-reference.html#cli-log4j.properties

Regards!

**Comment by gaetanquentin** [comment]
> @gaetanquentin
> 
> `cli-log4j.properties` is a configuration file and it's created at the first run.
> 
> https://docs.rundeck.com/docs/administration/configuration/configuration-file-reference.html#cli-log4j.properties
> 
> Regards!

but it didn't, with the war installation.

So how can i generate it now?

**Comment by MegaDrive68k** [comment]
Hi, here the file content, maybe is good idea recreate it.

```
#
#
log4j.rootCategory=ERROR, stdout

#
# stdout - ConsoleAppender
#
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%-5p %c{1}: %m%n

#
# plainStdout - ConsoleAppender which
# doesnt provide any timestamps, etc
#
log4j.appender.plainStdout=org.apache.log4j.ConsoleAppender
log4j.appender.plainStdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.plainStdout.ConversionPattern=%m%n
```

Hope it helps!

**Comment by gaetanquentin** [comment]
> Hi, here the file content, maybe is good idea recreate it.
> 
> ```
> #
> #
> log4j.rootCategory=ERROR, stdout
> 
> #
> # stdout - ConsoleAppender
> #
> log4j.appender.stdout=org.apache.log4j.ConsoleAppender
> log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
> log4j.appender.stdout.layout.ConversionPattern=%-5p %c{1}: %m%n
> 
> #
> # plainStdout - ConsoleAppender which
> # doesnt provide any timestamps, etc
> #
> log4j.appender.plainStdout=org.apache.log4j.ConsoleAppender
> log4j.appender.plainStdout.layout=org.apache.log4j.PatternLayout
> log4j.appender.stdout.plainStdout.ConversionPattern=%m%n
> ```
> 
> Hope it helps!

yes it helps. now rd-acl works fine.

the war installer should create it if missing, even in install-only mode.
