### ISSUE TITLE
'Mask Passwords' doesn't work with echo command

### ISSUE THREAD

**Issue by menathor** [rundeck/rundeck#4981]
**Describe the bug**
Hi all. The _Mask Passwords_ log filter option doesn't work when running the following command:
`echo username:'@option.password@' | sudo chpasswd`

When the command fails, the unmasked password is displayed in the log. However, the filter works correctly when running the same command as a script.

**My Rundeck detail**

* Rundeck version: latest
* OS Name/version: ubuntu 18.04
* DB Type/version: mysql

**Comment by jessemarple** [comment]
Have you tried putting the ```mask password``` filter on the job as a global instead of on the workflow step?

**Comment by menathor** [comment]
Hey @jessemarple 

That seems to have done the trick, thanks!

**Comment by f-r-o-g** [comment]
Hi,
I am running into the same issue but it doesn't seem to work.
I used a _script_ step.
Either
`echo username: @option.pw@`
or line
`echo username: $RD_OPTION_PW`
do not mask the password.


**My Rundeck detail**

Rundeck version: 3.0.23
OS Name/version: redhat 7.6
DB Type/version: H2

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
