### ISSUE TITLE
Project title in page banner does not respect rundeck.gui.startpage

### ISSUE THREAD

**Issue by Nessworthy** [rundeck/rundeck#4997]
**Describe the bug**
When `rundeck.gui.startpage` is set away from the default (in this case, `jobs`), the project title in the banner at the top of the page still links to the project's dashboard.

Possibly not a bug, but a little confusing!

**My Rundeck detail**

* Rundeck version: 3.0.21-20190424
* install type: rpm
* OS Name/version: Amazon Linux (4.14.104-95.84.amzn2.x86_64)
* DB Type/version: MySQL

**To Reproduce**
1. Add `rundeck.gui.startpage = jobs`  in `rundeck-config.properties`
2. Restart rundeck.
3. Create a project.
4. Select project in menu, notice that it goes to the jobs page.
5. Select project name in header of page, notice that it goes to the project dashboard.

**Expected behavior**
The link in the header to go to the jobs page (or expected documentation saying that the banner isn't affected by that setting)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75.0.3770.100 (x64 stable)

**Comment by MegaDrive68k** [comment]
Hi @Nessworthy 

According to this:

https://docs.rundeck.com/docs/administration/configuration/gui-customization.html

Using

`rundeck.gui.startpage = jobs`

You can set the default page at the moment of selecting the project in the **left menu**.

(Tested on 3.0.21)

Cheers!
