### ISSUE TITLE
 Node Enhancer feature is not working

### ISSUE THREAD

**Issue by carlosrfranco** [rundeck/rundeck#5004]
**Describe the bug**
Rundeck was not able to process the enhancement in the node although it is possible to configure on "Edit Node" view.

**My Rundeck detail**
--

**To Reproduce**
- Install a node enhancer plugin on rundeck
- Config the node enhancer on "Edit Node" view
- Note that the nodes were not enhanced

**Expected behavior**
The plugin should make the enhancement if configured

**Comment by gschueler** [comment]
issue occurs if using filesystem project config
