### ISSUE TITLE
Job Options Remote URL not compatible with Oracle REST Data Services formatting

### ISSUE THREAD

**Issue by g10chy** [rundeck/rundeck#5015]
Issue type: Enhancement Request

* Rundeck version: 2.4.4 
* install type: (rpm,deb,war,launcher?) rpm
* OS Name/version: Red Hat 7.2
* DB Type/version: PostgreSQL

I am using Oracle REST Data Services to dynamically generate JSON results based on SQL queries from an Oracle Database. The data in the Oracle database is very dynamic and therefore JSON files are not suitable here.
The Oracle REST standard is to return the results within items object as per below:

{
  "items": [
    {
      "name": "Live",
      "value": "Live"
    },
    {
      "name": "Being Built",
      "value": "Being Built"
    },
    {
      "name": "Decommissioned",
      "value": "Decommissioned"
    },
    {
      "name": "Unknown",
      "value": "Unknown"
    }
  ]
}

Can Rundeck be changed to account for this? 
Using JQ I can easily filter the items results to get the Rundeck compatible format but there is no way to do this in Rundeck directly as it only accepts a URL.

Thanks,
Chris

**Comment by ltamaster** [comment]
Hi @g10chy 

The remote url needs something like this
```
[
  {"name":"X Label", "value":"x value", "selected": true},
  {"name":"Y Label", "value":"y value"},
  {"name":"A Label", "value":"a value", "selected": true}
]
```

You can create an option value plugin to format  Oracle REST  outout

https://docs.rundeck.com/docs/developer/12-option-values-plugins.html#java-plugin-type

Luis

**Comment by g10chy** [comment]
Hi @ltamaster

Unfortunately, this is not going to help me. 
I need it to be more dynamic as I heavily rely on the "Variable expansion in remote URLs" feature.

Is there is a way I can write a plugin that just always transforms/filters the JSON response?

Thanks,
Chris

**Comment by ltamaster** [comment]
Hi @g10chy ,
Maybe this can help you:

https://github.com/rundeck/plugin-bootstrap

```rundeck-plugin-bootstrap -n OptionPlugin -t java -s Option -d /plugin
```
