### ISSUE TITLE
"Retry failed nodes" does not preserve option values

### ISSUE THREAD

**Issue by tanji** [rundeck/rundeck#5025]
**Describe the bug**
When using "Retry failed nodes", job options are not preserved and are reset to default, unlike "Run again" which correctly preserves options.

**My Rundeck detail**

* Rundeck version: 3.0.22
* install type: deb
* OS Name/version: Debian Stretch
* DB Type/version: MySQL

**To Reproduce**
1. Go to 'Show Execution' and get a job that had failed nodes
2. Click on 'Run again'
3. Options have kept their values during "Run Job" phase
4. Go back and Click on 'Retry failed nodes'
5. Job options are set to job defaults

**Expected behavior**
Job option values should be preserved for "Retry failed nodes" option.

**Screenshots**
N/A

**Desktop (please complete the following information):**
Irrelevant. Happens on various browsers and OSes

**Additional context**
N/A

**Comment by MegaDrive68k** [comment]
Hi @tanji 

Sounds good for an enhancement.

**Comment by amartin3225** [comment]
I would also find this useful!
