### ISSUE TITLE
Cannot start rundeckd service after a restart - status failed

### ISSUE THREAD

**Issue by razdapa** [rundeck/rundeck#5038]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.0.23-20190619
* install type: deb
* OS Name/version: debian 9.9
* DB Type/version: mysql

**Expected Behavior**

Starting rundeckd.service.
_______________________________________________________

Hi, 
The rundeckd.service has been restarted while a job was running, since then we can't restart the service.

We succeeded to start rundeckd.service , after disabling the service and reboot the server.

After a start of the service status appeared to be running and  failed shortly after, i suspect a java process crash...

![image](https://user-images.githubusercontent.com/52664985/60816095-3b642d80-a199-11e9-9a94-028b0afb3e60.png)

**Here the service.log :** 

2019-07-05 11:57:10.318 ERROR --- [eduler_Worker-1] rundeck.services.ExecutionUtilService    : Execution failed: 268 in project Operis: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [testeric: NonZeroResultCode: Remote command failed with exit status 1 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:testeric)=BaseDataContext{{exec={exitCode=1}}}, ContextView(node:testeric)=BaseDataContext{{exec={exitCode=1}}}}, base=null)} ]}, Node failures: {testeric=[NonZeroResultCode: Remote command failed with exit status 1 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:testeric)=BaseDataContext{{exec={exitCode=1}}}, ContextView(node:testeric)=BaseDataContext{{exec={exitCode=1}}}}, base=null)} ]}, status: failed]
2019-07-05 11:59:20.295  INFO --- [      Thread-19] rundeckapp.BootStrap                     : Rundeck Shutdown detected

**Here the /etc/rundeck/profile :**

prog="rundeckd"
[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
[ -e /etc/default/$prog ] && . /etc/default/$prog

RDECK_INSTALL="${RDECK_INSTALL:-/var/lib/rundeck}"
RDECK_BASE="${RDECK_BASE:-/var/lib/rundeck}"
RDECK_CONFIG="${RDECK_CONFIG:-/etc/rundeck}"
RDECK_CONFIG_FILE="${RDECK_CONFIG_FILE:-$RDECK_CONFIG/rundeck-config.properties}"
RDECK_SERVER_BASE="${RDECK_SERVER_BASE:-$RDECK_BASE}"
RDECK_SERVER_CONFIG="${RDECK_SERVER_CONFIG:-$RDECK_CONFIG}"
RDECK_SERVER_DATA="${RDECK_SERVER_DATA:-$RDECK_BASE/data}"
RDECK_PROJECTS="${RDECK_PROJECTS:-$RDECK_BASE/projects}"
RUNDECK_TEMPDIR="${RUNDECK_TEMPDIR:-/tmp/rundeck}"
RUNDECK_WORKDIR="${RUNDECK_TEMPDIR:-$RDECK_BASE/work}"
RUNDECK_LOGDIR="${RUNDECK_LOGDIR:-$RDECK_BASE/logs}"
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server}"
RDECK_TRUSTSTORE_FILE="${RDECK_TRUSTSTORE_FILE:-$RDECK_CONFIG/ssl/truststore}"
RDECK_TRUSTSTORE_TYPE="${RDECK_TRUSTSTORE_TYPE:-jks}"
JAAS_LOGIN="${JAAS_LOGIN:-true}"
JAAS_CONF="${JAAS_CONF:-$RDECK_CONFIG/jaas-loginmodule.conf}"
LOGIN_MODULE="${LOGIN_MODULE:-RDpropertyfilelogin}"
RDECK_HTTP_PORT=${RDECK_HTTP_PORT:-4440}
RDECK_HTTPS_PORT=${RDECK_HTTPS_PORT:-4443}

if [ -z "$JAVA_CMD" ] && [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ] ; then
  JAVA_CMD=$JAVA_HOME/bin/java
  PATH=$PATH:$JAVA_HOME/bin
  export JAVA_HOME
elif [ -z "$JAVA_CMD" ] ; then
  JAVA_CMD=java
fi

for jar in $(find $RDECK_INSTALL/cli -name '*.jar') ; do
  CLI_CP=${CLI_CP:+$CLI_CP:}$jar
done
for war in $(find $RDECK_INSTALL/bootstrap -name '*.war') ; do
  EXECUTABLE_WAR=$war
done

RDECK_JVM="-Drundeck.jaaslogin=/etc/rundeck/jaas-activedirectory.conf \		
           -Djava.security.auth.login.config=/etc/rundeck/jaas-activedirectory.conf \
           -Dloginmodule.name=activedirectory \
           -Drdeck.config=$RDECK_CONFIG \
           -Drundeck.server.configDir=$RDECK_SERVER_CONFIG \
           -Dserver.datastore.path=$RDECK_SERVER_DATA/rundeck \
           -Drundeck.server.serverDir=$RDECK_INSTALL \
           -Drdeck.projects=$RDECK_PROJECTS \
           -Drdeck.runlogs=$RUNDECK_LOGDIR \
           -Drundeck.config.location=$RDECK_CONFIG_FILE \
           -Djava.io.tmpdir=$RUNDECK_TEMPDIR \
           -Drundeck.server.workDir=$RUNDECK_WORKDIR \
           -Dserver.http.port=$RDECK_HTTP_PORT \
           -Drdeck.base=$RDECK_BASE"

if [ -n "$RUNDECK_WITH_SSL" ] ; then
  RDECK_JVM="$RDECK_JVM -Drundeck.ssl.config=$RDECK_SERVER_CONFIG/ssl/ssl.properties -Dserver.https.port=${RDECK_HTTPS_PORT}"
fi

unset JRE_HOME

umask 002

rundeckd="$JAVA_CMD $RDECK_JVM $RDECK_JVM_OPTS -jar $EXECUTABLE_WAR --skipinstall"

rundeckd="$JAVA_CMD $RDECK_JVM $RDECK_JVM_OPTS -jar $EXECUTABLE_WAR --skipinstall"

___________________

Thanks you for you answers and sorry for the bad english ;)

**Comment by MegaDrive68k** [comment]
Hi @razdapa 

Just to check, what Java version are you using?

Regards!

**Comment by Itsatsu** [comment]
Hi, I'm his colleague
we have openjdk 1.8.0_212

 java -version
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b03-2~deb9u1-b03)
OpenJDK 64-Bit Server VM (build 25.212-b03, mixed mode)

thanks you for you answers

**Comment by MegaDrive68k** [comment]
@razdapa and @Itsatsu 

Can you send the service.log stack trace (at the moment of starting the service) to take a look?

Thanks!

**Comment by Itsatsu** [comment]
When starting, the service fails directly without writing to service.log

Thanks

**Comment by MegaDrive68k** [comment]
Please share the output of, to get any clue about that.

`journalctl -u rundeckd.service`

Regards!

**Comment by razdapa** [comment]
![image](https://user-images.githubusercontent.com/52664985/60864984-58ded900-a225-11e9-9ddf-85499e958476.png)

**Comment by Itsatsu** [comment]
hi, here is the result :
root@vmrundeck:~# journalctl -u rundeckd.service
-- Logs begin at Tue 2019-07-09 10:36:55 CEST, end at Tue 2019-07-09 10:43:01 CEST. --
juil. 09 10:36:59 vmrundeck.operis.champlan systemd[1]: Starting LSB: rundeck job automation console...
juil. 09 10:37:00 vmrundeck.operis.champlan rundeckd[449]: Starting rundeckd.
juil. 09 10:37:00 vmrundeck.operis.champlan rundeckd[449]: done.
juil. 09 10:37:00 vmrundeck.operis.champlan systemd[1]: Started LSB: rundeck job automation console.
juil. 09 10:37:09 vmrundeck.operis.champlan systemd[1]: rundeckd.service: Main process exited, code=exited, status=1/FAILURE
juil. 09 10:37:09 vmrundeck.operis.champlan rundeckd[910]: start-stop-daemon: warning: failed to kill 496: No such process
juil. 09 10:37:09 vmrundeck.operis.champlan rundeckd[910]: Stopping rundeckd.
juil. 09 10:37:09 vmrundeck.operis.champlan rundeckd[910]: done.
juil. 09 10:37:09 vmrundeck.operis.champlan systemd[1]: rundeckd.service: Unit entered failed state.
juil. 09 10:37:09 vmrundeck.operis.champlan systemd[1]: rundeckd.service: Failed with result 'exit-code'.
juil. 09 10:42:15 vmrundeck.operis.champlan systemd[1]: Starting LSB: rundeck job automation console...
juil. 09 10:42:15 vmrundeck.operis.champlan rundeckd[1093]: Starting rundeckd.
juil. 09 10:42:15 vmrundeck.operis.champlan rundeckd[1093]: done.
juil. 09 10:42:15 vmrundeck.operis.champlan systemd[1]: Started LSB: rundeck job automation console.
juil. 09 10:42:15 vmrundeck.operis.champlan systemd[1]: rundeckd.service: Main process exited, code=exited, status=1/FAILURE
juil. 09 10:42:15 vmrundeck.operis.champlan rundeckd[1118]: start-stop-daemon: warning: failed to kill 1105: No such process
juil. 09 10:42:15 vmrundeck.operis.champlan rundeckd[1118]: Stopping rundeckd.
juil. 09 10:42:15 vmrundeck.operis.champlan rundeckd[1118]: done.
juil. 09 10:42:15 vmrundeck.operis.champlan systemd[1]: rundeckd.service: Unit entered failed state.
juil. 09 10:42:15 vmrundeck.operis.champlan systemd[1]: rundeckd.service: Failed with result 'exit-code'.

thanks!

**Comment by MegaDrive68k** [comment]
Hi @razdapa and @Itsatsu,

I reproduced your issue partially and the main advice is to leave the profile file by default if you need set parameters to JVM please use /etc/defaults/rundeckd instead editing /etc/rundeck/profile file directly, this is explained here:

https://docs.rundeck.com/docs/administration/configuration/system-properties-configuration.html#rpm-and-deb

Basically, this is for avoiding an upgrade or config problem. I leave the default /etc/rundeck/profile content for Debian based installations:

```
# default rundeck profile file
prog="rundeckd"
[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
[ -e /etc/default/$prog ] && . /etc/default/$prog

RDECK_INSTALL="${RDECK_INSTALL:-/var/lib/rundeck}"
RDECK_BASE="${RDECK_BASE:-/var/lib/rundeck}"
RDECK_CONFIG="${RDECK_CONFIG:-/etc/rundeck}"
RDECK_CONFIG_FILE="${RDECK_CONFIG_FILE:-$RDECK_CONFIG/rundeck-config.properties}"
RDECK_SERVER_BASE="${RDECK_SERVER_BASE:-$RDECK_BASE}"
RDECK_SERVER_CONFIG="${RDECK_SERVER_CONFIG:-$RDECK_CONFIG}"
RDECK_SERVER_DATA="${RDECK_SERVER_DATA:-$RDECK_BASE/data}"
RDECK_PROJECTS="${RDECK_PROJECTS:-$RDECK_BASE/projects}"
RUNDECK_TEMPDIR="${RUNDECK_TEMPDIR:-/tmp/rundeck}"
RUNDECK_WORKDIR="${RUNDECK_TEMPDIR:-$RDECK_BASE/work}"
RUNDECK_LOGDIR="${RUNDECK_LOGDIR:-$RDECK_BASE/logs}"
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server}"
RDECK_TRUSTSTORE_FILE="${RDECK_TRUSTSTORE_FILE:-$RDECK_CONFIG/ssl/truststore}"
RDECK_TRUSTSTORE_TYPE="${RDECK_TRUSTSTORE_TYPE:-jks}"
JAAS_LOGIN="${JAAS_LOGIN:-true}"
JAAS_CONF="${JAAS_CONF:-$RDECK_CONFIG/jaas-loginmodule.conf}"
LOGIN_MODULE="${LOGIN_MODULE:-RDpropertyfilelogin}"
RDECK_HTTP_PORT=${RDECK_HTTP_PORT:-4440}
RDECK_HTTPS_PORT=${RDECK_HTTPS_PORT:-4443}

if [ -z "$JAVA_CMD" ] && [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ] ; then
  JAVA_CMD=$JAVA_HOME/bin/java
  PATH=$PATH:$JAVA_HOME/bin
  export JAVA_HOME
elif [ -z "$JAVA_CMD" ] ; then
  JAVA_CMD=java
fi

for jar in $(find $RDECK_INSTALL/cli -name '*.jar') ; do
  CLI_CP=${CLI_CP:+$CLI_CP:}$jar
done
for war in $(find $RDECK_INSTALL/bootstrap -name '*.war') ; do
  EXECUTABLE_WAR=$war
done

RDECK_JVM="-Drundeck.jaaslogin=$JAAS_LOGIN \
           -Djava.security.auth.login.config=$JAAS_CONF \
           -Dloginmodule.name=$LOGIN_MODULE \
           -Drdeck.config=$RDECK_CONFIG \
           -Drundeck.server.configDir=$RDECK_SERVER_CONFIG \
           -Dserver.datastore.path=$RDECK_SERVER_DATA/rundeck \
           -Drundeck.server.serverDir=$RDECK_INSTALL \
           -Drdeck.projects=$RDECK_PROJECTS \
           -Drdeck.runlogs=$RUNDECK_LOGDIR \
           -Drundeck.config.location=$RDECK_CONFIG_FILE \
           -Djava.io.tmpdir=$RUNDECK_TEMPDIR \
           -Drundeck.server.workDir=$RUNDECK_WORKDIR \
           -Dserver.http.port=$RDECK_HTTP_PORT \
           -Drdeck.base=$RDECK_BASE"
#
# Set min/max heap size
#
RDECK_JVM="$RDECK_JVM $RDECK_JVM_SETTINGS"
#
# SSL Configuration - Uncomment the following to enable.  Check SSL.properties for details.
#
if [ -n "$RUNDECK_WITH_SSL" ] ; then
  RDECK_JVM="$RDECK_JVM -Drundeck.ssl.config=$RDECK_SERVER_CONFIG/ssl/ssl.properties -Dserver.https.port=${RDECK_HTTPS_PORT}"
fi

unset JRE_HOME

umask 002

rundeckd="$JAVA_CMD $RDECK_JVM $RDECK_JVM_OPTS -jar $EXECUTABLE_WAR --skipinstall"
```

And here an example how to pass JVM args using the /etc/defaults/rundeckd file, for example configuring an OpenLDAP auth:

```
# /etc/defaults/rundeckd
RDECK_JVM_OPTS="-Drundeck.jaaslogin=true \
       -Djava.security.auth.login.config=/etc/rundeck/jaas-ldap.conf \
       -Dloginmodule.name=ldap"
```

Let me know if works in your case.

Cheers!

**Comment by Itsatsu** [comment]
The server is running again, I am making the change on my prod server tonight. 

Thank you Rundeck team, see you soon.

**Comment by razdapa** [comment]
Thank you very much !
