### ISSUE TITLE
Unable to remove last step from Job and no warning message is shown 

### ISSUE THREAD

**Issue by fgutierrezz** [rundeck/rundeck#5039]
**Describe the bug**
The issue occurs when you  from the job. 

**My Rundeck detail**

* Rundeck version: [3.x]
* install type: [choose: launcher]
* OS Name/version: [Any]
* DB Type/version: [postgres ]

**To Reproduce**
1. Create a project > Job > and add 1 step
2. Edit the Job and try to remove the step.
3. Click on Definition of the job, you will see the same steps. 

**Expected behavior**
It's expected to see a warning or error message if it is not possible to remove all steps. 

**Screenshots**
Attached

**Existing job trying to remove last step**
![empty_workflow](https://user-images.githubusercontent.com/30966360/60831941-bec95300-a188-11e9-8568-cc2c503470c9.png)
![existing_step_not_removed](https://user-images.githubusercontent.com/30966360/60831954-c2f57080-a188-11e9-857e-f1de00ae179c.png)

**New job with no Steps**
An error like the following should appear. 
![When_using_new_job](https://user-images.githubusercontent.com/30966360/60832493-fe446f00-a189-11e9-87cc-fe4503bcaee5.png)

**Comment by gschueler** [comment]
still present
