### ISSUE TITLE
drop down menu follows the scroll of the page

### ISSUE THREAD

**Issue by Itsatsu** [rundeck/rundeck#5045]
**Describe the bug**
the drop-down menu goes down with the page

**My Rundeck detail**

* Rundeck version: 3.0.23-20190619
* install type: deb
* OS Name/version: debian 9.9
* DB Type/version: mysql
* openjdk version "1.8.0_212"

**To Reproduce**
1. Go to edit job
2. Scroll down to Workflow
2.  Add command to job whith rundeck variable"${option}"
4. See drop-down menu
5 scroll down or up
6 look at the menu go down and go up with the page

**Expected behavior**
the scroll hangs on the drop-down menu

**Screenshots**
![Capture](https://user-images.githubusercontent.com/16906985/61053854-a22e5480-a3ee-11e9-94ef-55f7c96082c6.PNG)

**Desktop**
 - OS: windows 7
 - Browser firefox 
 - Version 60.8.0esr (32 bits)

**Comment by MegaDrive68k** [comment]
Also happens on 3.1.0-RC2.
