### ISSUE TITLE
Rundeck job running duplicate execute job schedular 

### ISSUE THREAD

**Issue by yogeshkumark** [rundeck/rundeck#5053]
**Describe the bug**
 we are getting duplicate trigger during the same period. same minute with different seconds 

**My Rundeck detail**
ck 2.9.4-1 caffe latte hotpink briefcase 2017-10-13
* Rundeck version: [ e.g. 2.11.3]ck 2.9.4-1 caffe latte hotpink briefcase 2017-10-13
* install type: [choose: rpm,deb,war,launcher] rpm
* OS Name/version: [e.g. ubuntu 16.04]: 
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**
1.	The schedule is * 4/5 ** - meaning runs every 5 minutes, starts on the 4th.  So the job should have been kicked off at 14-JUL-19 01.09.00.000000000 PM instead of 14-JUL-19 01.13.43.000000000 PM.

**Expected behavior**

**Screenshots**
 

**Desktop (please complete the following information):**

**Additional context**
a.	Question: why didn’t the job kick off at 01.09.00?  What I see here is that it took more than 4 minutes to trigger the job after the expected trigger time.  
Run deck log tells the job kicked off at 01:13:28 UTC (9:13:28 EDT) instead of 1:09.

2.	If the run time takes longer than 5 minutes, the job has an issue.  But I have not seen anything that takes longer 3 minutes and some seconds.

**Comment by yogeshkumark** [comment]
This issue happened only on one server and only on one job. 
we tried to rename the job , still we have the same issue.

**Comment by jessemarple** [comment]
Have you run this job on other servers/instances of Rundeck?

Have you tried creating the job over again from scratch - e.g. the same job concepts and requirements, but a new job?
