### ISSUE TITLE
FAQ steps to change the default session timeout duration are wrong for RD3

### ISSUE THREAD

**Issue by emiliohh** [rundeck/rundeck#5055]
Issue type: Bug report

The Faq steps to change the default session timeout duration are correct for RD2. 

The web.xml file is not exposed in RD3 so we should either specify that those steps are correct for RD2 or replace them for correct steps for RD3.

https://github.com/rundeck/rundeck/wiki/Faq#how-do-i-change-the-default-session-timeout-duration

**Comment by gschueler** [comment]
updated faq to link to docs page, and mention `server.session.timeout`
