### ISSUE TITLE
Resource abuse with the profile file

### ISSUE THREAD

**Issue by kaiwangchen** [rundeck/rundeck#506]
The profile file, /etc/rundeck/profile with OS packaging or etc/profile with self-contained launcher, is the used by both server and clients to configure java launcher, which export these environment variables: the server uses JAVA_HOME, RDECK_JVM, BOOTSTRAP_CP; the clients use RDECK_JVM as well, and several client-only ones: JAVA_CMD, RDECK_HOME, RDECK_BASE, CLI_CP, RDECK_SSL_OPTS, and RUNDECK_CLI_TERSE.

The problem is RDECK_JVM is a shared one, so this line applies to clients as well which is obviously resource abuse:

RDECK_JVM="$RDECK_JVM -Xmx1024m -Xms256m -server"

We'd better use distinct variables to hold the Java launcher args, for example:

RDECK_JVM=...
RDECK_SERVER_JVM="$RDECK_JVM -Xmx1024m -Xms256m -server"
RDECK_CLIENT_JVM="$RDECK_JVM ..."

This issue is extracted from https://groups.google.com/forum/#!topic/rundeck-discuss/WDGH9U-jONI

**Comment by ahonor** [comment]
The `rd` CLI avoids this problem of having to share the same profile with the server.
