### ISSUE TITLE
Allow notifications to receive context variables / Ref: #4838 

### ISSUE THREAD

**Issue by fgutierrezz** [rundeck/rundeck#5061]
**Is your feature request related to a problem? Please describe.**
I will be useful to allow notifications to include context variables 

**Describe the solution you'd like**
Allow context variables to be passed in notifications. 

**Describe alternatives you've considered**
I tried using exported global vars (using `export-var` workflow step) and captured data (using `key-value-data` log filter) in notification however is not able to read the variables in the notification

Current output
 headers={Accept=application/json, application/javascript, text/javascript, foo=${export.newval}, trigger=success, fel=${data.value*}

Example output expected 
 headers={Accept=application/json, application/javascript, text/javascript, foo=12345, trigger=success, fel=12345

**Additional context**
example included using http notification call 

[ContextVariables_notifications.yaml.txt](https://github.com/rundeck/rundeck/files/3402415/ContextVariables_notifications.yaml.txt)
.

**Comment by hayssamnoweir** [comment]
**Problem**
- Enhancement not fully working in the recent Rundeck release.
- Global and captured variables are not evaluated in the HTTP notification plugin.

**Rundeck version**
- 3.2.5-20200403

**Example**
 [Job definition](https://github.com/rundeck/rundeck/files/4504230/data_in_notifications.yaml.txt)
