### ISSUE TITLE
Git Plugin:  import-jobs action should cause be error when no jobs are specified

### ISSUE THREAD

**Issue by blinkesto** [rundeck/rundeck#5064]
**Describe the bug**
Running 

java -jar  rundeck-cli-1.1.7-all.jar projects scm  perform --integration import --action import-jobs --project TestProject1

doesn't import the jobs from git

Running the job action from UI works.

**My Rundeck detail**

* Rundeck version: 3.0.23-20190619
* install type: rpm
* OS Name/version: RHEL 8
* DB Type/version: H2

**To Reproduce**
1. Setup a project with SCM import
2. Run the above command

Gives:
# Action import-jobs was successful.
# Result: SCM import Action was Successful: import-jobs

**Expected behavior**
Should update the jobs in project

**Screenshots**

**Desktop (please complete the following information):**
 - OS: ios
 - Browser : N/A
 - Version 10.14.5

**Additional context**

**Comment by gschueler** [comment]
The import-jobs action expects a list of jobs to import:
 you can either query the status of jobs using the `rd projects scm inputs` action and determine which items to include using `--item` flag to specify a comma-separated list, *or* you can simply use the `--allinputs` or `--alltracked` or `-alluntracked` flags: see the `rd projects scm perform help`  .

However, I think the `import-jobs` should also have an error if you don't specify anything to import, so i consider this a bug in the git plugin as well.

**Comment by blinkesto** [comment]
Thanks for the info.  I tried all the options listed for "perform help" but it still seems to run but not actually update.  

These are the commands I tried:

 java -jar  bin/rundeck-cli-1.1.7-all.jar projects scm  perform --integration import --action import-jobs --allitems --project TestProject1

java -jar  bin/rundeck-cli-1.1.7-all.jar projects scm  perform --integration import --action import-jobs --alltracked --project TestProject1 

Still get:

# Action import-jobs was successful.
# Result: SCM import Action was Successful: import-jobs

But in UI it shows the job needs to be updated.
