### ISSUE TITLE
SSL truststore path is misconfigured by default in OS packages

### ISSUE THREAD

**Issue by kaiwangchen** [rundeck/rundeck#507]
The client tools such as rd-jobs depend on the profile to get java launcher options, and the following is for clients to load truststore to connect the server via https:

<pre>
export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=$RDECK_BASE/ssl/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"
</pre>

However, with OS packaging the truststore is evaluated as /var/lib/rundeck/ssl/truststore, while the meant location should be /etc/rundeck/ssl/truststore as suggested by ssl.properties. 

As a result, one will get this complaint:

Error: Error making server request to https://localhost:4443: Error occurred while trying to authenticate to server: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

With -Djavax.net.debug=all (see http://docs.oracle.com/javase/1.5.0/docs/guide/security/jsse/ReadDebug.html), one can tell the failure of loading truststore.

This issue is extraced from https://groups.google.com/forum/#!topic/rundeck-discuss/WDGH9U-jONI

**Comment by mathieuchateau** [comment]
Hello,

sorry to open back this from the ashes. I am using latest version on Rundeck (2.5.2-1), and try now to use cli command. I have this same issue:

```Java
Error: Error making server request to http://localhost:4440: Error occurred while trying to authenticate to server: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty
```
But RDECK_SSL_OPTS is correct based on previous comment here:

    export RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=/etc/rundeck/ssl/truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"

I am doing SSL offloading, may it be related ? 
This file is missing: /etc/rundeck/ssl/truststore

```Shell
[root@myserver ~]# ll /etc/rundeck/ssl/
total 4
-rw-r--r--. 1 rundeck rundeck 158 Jul  7 20:04 ssl.properties
```
