### ISSUE TITLE
Copy file from Linux Host to Windows Host

### ISSUE THREAD

**Issue by ZoeLeah** [rundeck/rundeck#5072]
**Describe the bug**
We are trying to copy a file from Linux to Windows and it failes:
Begin copy 28 bytes to node se1-adm-p059.ads.schwarz: /opt/ecordk/tmp/test.txt -> F:\Transfer
Traceback (most recent call last):
File "/opt/ecordk/data/rundeck/libext/cache/py-winrm-plugin-2.0.1/winrm-filecopier.py", line 266, in <module>
quiet=quiet)
File "/opt/ecordk/data/rundeck/libext/cache/py-winrm-plugin-2.0.1/winrm-filecopier.py", line 142, in winrm_upload
raise WinRmError(script, code, stdout, stderr)
__main__.WinRmError: Remote execution of "add-content -value $([System.Convert]::FromBase64String("bC1wYWlldGwtYXMwMQpsLXFhaWV0bC1hczAxCg==")) -encoding byte -path F:\Transfer" failed with exit code 1. STDOUT: . STDERR: 'powershell' is not recognized as an internal or external command,
operable program or batch file.
.
failed: [WinRMcpPython]: external script failed with exit code: 1

**My Rundeck detail**

* Rundeck version: 3.0.23
* install type: war
* OS Name/version: RHEL 7.6
* DB Type/version: Oracle

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox 
 - Version 60.8.0esr

**Comment by MegaDrive68k** [comment]
Hi @ZoeLeah 

Can you share an example job definition to test it?

Regards!

**Comment by ZoeLeah** [comment]
Sure

`- defaultTab: output
  description: null
  executionEnabled: true
  group: Tests
  id: 4debc79d-435d-46a2-aeaf-fd36286ca0c3
  loglevel: INFO
  name: S_E_Kopiert eine Datei von Rundeck auf Windows
  nodeFilterEditable: false
  nodefilters:
    dispatch:
      excludePrecedence: true
      keepgoing: false
      rankOrder: ascending
      successOnEmptyNodeFilter: false
      threadcount: '1'
    filter: 'name: se1-adm-p059.ads.schwarz'
  nodesSelectedByDefault: true
  scheduleEnabled: true
  sequence:
    commands:
    - exec: dir
    - configuration:
        destinationPath: F:\Transfer\
        echo: 'true'
        recursive: 'false'
        sourcePath: /opt/ecordk/tmp/test.txt
      nodeStep: true
      type: copyfile
    keepgoing: false
    strategy: node-first
  uuid: 4debc79d-435d-46a2-aeaf-fd36286ca0c3
`

**Comment by ltamaster** [comment]
Hi @ZoeLeah,

Can you share your python version?

Also, what is the version of the remote windows? 

Thanks
Luis

**Comment by ZoeLeah** [comment]
Hi @ltamaster,

our python version is 2.7 and the remote host is a Windows Server Server 2016.

Cheers,
Ronnie

**Comment by ZoeLeah** [comment]
The job fails with the following message:

`Traceback (most recent call last):
File "/opt/ecordk/data/rundeck/libext/cache/py-winrm-plugin-2.0.3/winrm-filecopier.py", line 373, in <module>
quiet=quiet)
File "/opt/ecordk/data/rundeck/libext/cache/py-winrm-plugin-2.0.3/winrm-filecopier.py", line 210, in winrm_upload
raise WinRmError(script, code, stdout, stderr)
__main__.WinRmError: Remote execution of "add-content -value $([System.Convert]::FromBase64String("d3JpdGUtaG9zdCAidGVzdCINCmdldC1wcm9jZXNzDQo=")) -encoding byte -path ~/.tmp\59982-11746934-se1-adm-p059.ads.schwarz-dispatch-script.tmp.ps1" failed with exit code 1. STDOUT: . STDERR: 'powershell' is not recognized as an internal or external command,
operable program or batch file.
.`

**Comment by ltamaster** [comment]
Hi @ZoeLeah ,

Can you try with a simple command?, like this:

<img width="590" alt="Captura de pantalla 2019-09-06 16 00 13" src="https://user-images.githubusercontent.com/6034968/64456974-70203280-d0bf-11e9-8ce9-917a333847ce.png">

Thanks
