### ISSUE TITLE
Rundeck User Summary Page Duplicates Users

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#5082]
**Describe the bug**
When users are authenticating via LDAP (I don't believe LDAP is the issue here), and when the username letter case varies Rundeck records each username as a new/unique name. 

**My Rundeck detail**
* Rundeck version: 3.0.24-20190719
* install type:  rpm
* OS Name/version: centos 7
* DB Type/version: default

**To Reproduce**
Login with the same user with a different case. For example, if your user name is "jdoe"
first login as jdoe, then jDoe, then Jdoe, then JDOE, then JdOe and each time you'll see a new user in the List of Rundeck Users page.  

**Expected behavior**
Regardless of the user case it should show the same user. Maybe during username comparison /validation always cast it (.ToLower()) == <username> etc...?

**Screenshots**
Sorry, no screenshots

**Comment by hs-hub-world** [comment]
one suggestion might be to always replace username to all lowercase every time a user logs-in from the web <username> text box before authenticating and maintain/keep the same name during the active session.

**Comment by jtobard** [comment]
Can you try the latest version 3.1?, this looks like this closed issue: https://github.com/rundeck/rundeck/issues/4764
