### ISSUE TITLE
@option autocomplete in scripts sometimes adds "@option." twice and extra "@"

### ISSUE THREAD

**Issue by menathor** [rundeck/rundeck#5083]
**Describe the bug**
Hi guys

If some characters are typed after **@option.** and then an item is selected from the autocomplete dropdown menu, **@option.** is inserted again at the beginning and an extra "@" is added at the end

**My Rundeck detail**

* Rundeck version: latest
* OS Name/version: ubuntu 18.04
* DB Type/version: mysql

**To Reproduce**
For the example option **@option.hello_world@**

1. Type **@option.hel** in a script
2. Select **@option.hello_world@** from the auto complete dropdown menu
3. The result will be **@option.@option.hello_world@@**

Cheers

**Comment by MegaDrive68k** [comment]
Also happens on 3.1.0-RC2

![Screenshot_20190726_112035](https://user-images.githubusercontent.com/51376003/61962411-6de29880-af97-11e9-9527-577acbd213ab.png)
