### ISSUE TITLE
Delay in org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy

### ISSUE THREAD

**Issue by yogeshkumark** [rundeck/rundeck#5085]
**Describe the bug**
I am using Rundeck in my project we are getting more wait time on the below call.
we are monitoring the 
DB and Remote calls
1) org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy
JDBC Exit Call
Time	80ms
From	rundeck-prod
To	Oracle-Oracle Database 12c Enterprise Edition Release 12.2.0.1.0 - 64bit Production
Details	GET POOLED CONNECTION FROM DATASOURCE
Properties
Query Type	Datasource.GetConnection
2) 
**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]Rundeck 2.9.4-1 caffe latte hotpink briefcase 2017-10-13
* install type: [choose: rpm,deb,war,launcher]:rpm
* OS Name/version: [e.g. ubuntu 16.04]: cent os 
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ] Oracle 

**To Reproduce**
we are using the APPD and configured the rundeck in it. 
1) while monitoring the jobs we are seing 2 issues 
a) 	java.lang.Thread:join  - Delay of 2000ms to 32000ms 
parent class - 
--org.quartz.simpl.SimpleThreadPool$WorkerThread 
---rundeck.quartzjobs.ExecutionJob$saveState
----rundeck.quartzjobs.ExecutionJob$saveState
--	rundeck.quartzjobs.ExecutionJob$_saveState_closure4$doCall:call
b) org.springframework.jdbc.datasource.TransactionAwareDataSourceProxy - 3000ms to 32000ms . 

**Expected behavior**
The pool connection should not wait for more time, the connection should be faster, 
**Screenshots**
![image](https://user-images.githubusercontent.com/545004/61860500-b04c9c80-aee7-11e9-9896-d48e6c7f5f45.png)
![image](https://user-images.githubusercontent.com/545004/61860682-f86bbf00-aee7-11e9-927d-cdcb5825d78c.png)

![image](https://user-images.githubusercontent.com/545004/61860568-ceb29800-aee7-11e9-8815-ac3e9662372c.png)

**Desktop (please complete the following information):**

**Additional context**

**Comment by jessemarple** [comment]
Are you able to reproduce this issue with the latest version of Rundeck?

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
