### ISSUE TITLE
OS packages should be signed and the rundeck.repo gpgcheck enabled

### ISSUE THREAD

**Issue by kaiwangchen** [rundeck/rundeck#509]
http://rundeck.org/downloads.html includes installation instructions with OS packages, such as

<pre>
yum install java-1.6.0
rpm -Uvh http://repo.rundeck.org/latest.rpm
yum install rundeck 
</pre>

However, the installed rundeck.repo is missing gpgkey and not gpgcheck-enabled. The packages are not signed either.

<pre>
[rundeck-release]
name=Rundeck - Release
baseurl=http://repo.rundeck.org/repo/rundeck/1/release
gpgkey=http://repo.rundeck.org/repo/RPM-GPG-KEY-RunDeck.org
gpgcheck=0
</pre>

A use may expect the official repository signed.

This issue is extracted from https://groups.google.com/forum/#!topic/rundeck-discuss/WDGH9U-jONI

**Comment by touzoku** [comment]
This issue is quite critical for us, actually. Can somebody take a look into it?

**Comment by gschueler** [comment]
added signed version of 2.5.1 rpms to bintray, updated http://repo.rundeck.org/latest.rpm to set gpgcheck=1, added public key to website http://rundeck.org/keys
