### ISSUE TITLE
Feature request: Variable storage

### ISSUE THREAD

**Issue by menathor** [rundeck/rundeck#5092]
Hi guys!

It would be great to be able to store certain variables for use in any project or job. For example a software path or admin email that is used in multiple scripts. As far as I'm aware, global variables are only for the current / parent job and can't be saved?

Something that functions exactly like key storage and saves the variables in /var/lib/rundeck/var/storage/variables (no need for encryption) would be perfect. Perhaps they could be referenced using @variable.xxxx@

Right now I've created my own /var/lib/rundeck/var/storage/variables folder and am storing variables as text files, then calling them using VARIABLE=$(cat /var/lib/rundeck/var/storage/variables/myvariable). Not clean, but it saves me from having to update multiple scripts when something changes.

Being able to do this natively in the gui would be awesome

Cheers!

**Comment by puremourning** [comment]
you can set globals in `project.properties` and use them with `${global.my_variable}`

**Comment by menathor** [comment]
@puremourning This made my morning, thank you! I see that they can be set in framework.properties as well. Can't believe I missed that.
