### ISSUE TITLE
Include the rundeck-cli in Docker image

### ISSUE THREAD

**Issue by zoredache** [rundeck/rundeck#5093]
**Is your feature request related to a problem? Please describe.**

I use the [rundeck docker image](https://hub.docker.com/r/rundeck/rundeck/).  It would be nice to be able to use the rundeck cli tool `rd` without having to create my own image.

**Describe the solution you'd like**

Include the `rd` command in the image.

**Describe alternatives you've considered**

The alternative is obviously to build my own image based on the rundeck image, but from my point of view, it seems like it would be generally useful to have the tool be as part of the official image.

Another alternative, would be to possibly make an separate official image just for the rundeck cli?

**Comment by MegaDrive68k** [comment]
Hi @zoredache 

Also, you can build your own Rundeck image using Dockerfile, like this:

https://github.com/ltamaster/rundeck-vault-docker/blob/master/rundeck/Dockerfile

Check the line:

`RUN apt-get -y install rundeck-cli`

Cheers!
