### ISSUE TITLE
Mass delete job executions

### ISSUE THREAD

**Issue by jothoma1** [rundeck/rundeck#5097]
**Describe the bug**
I would like to delete a lot of executions of a job.
When i select "Bulk Delete" and then "Select All" nothing is selected so i can't delete all
I have to delete one by one but i have more thant 2000 executions :(
**My Rundeck detail**

* Rundeck version: 3.0.24
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: 

**To Reproduce**
1. Go to a job
2. Click on Executions / Bulk Delete / Select All

**Expected behavior**
All executions selected

**Comment by MegaDrive68k** [comment]
Hey @jothoma1,

Did you mean from the Jobs tab?

If you select "Activity for this Job" > "by you" (or "recent") > "bulk delete" button and later "Select All" works (using 3.0.24). 

![Screenshot_20190729_225939](https://user-images.githubusercontent.com/51376003/62097368-9945db80-b254-11e9-9f93-b002f84d44ad.png)

But if it's from Activity panel we have that issue (solved for 3.1.0-RC2):

https://github.com/rundeck/rundeck/issues/4969

Regards!

**Comment by fdevans** [comment]
If there are still gaps in the feature set please feel free to open an enhancement request against the current version of Rundeck with your ideas.
Thank you, 
The Rundeck Team
