### ISSUE TITLE
Not able to access options provided by rundeck api inside rundeck script

### ISSUE THREAD

**Issue by shubhs2060** [rundeck/rundeck#5107]
**Describe the bug**
I have a url created using rundeck api with some params

Eg:http://localhost:4440/api/1/job/5455ad9e-8a5/run?option.name="test"

And I want to use the params from api into my rundeck script
Can I use it with echo $RD_OPTION_NAME

**My Rundeck detail**

* Rundeck version: 3.0.23-20190619
* install type: deb
* OS Name/version: ubuntu 16.04
* DB Type/version: postgres

**To Reproduce**
Create a rundeck api
Eg: http://localhost:4440/api/1/job/5455ad9e-8a5c-4661/run?option.name="test"
1. Go to 'Rundeck'
2. Click on 'Create job'
3. Scroll down to 'Add step'
4. try to access params using ${option.name}

**Expected behavior**
I want to access the value whatever is supplied with the url

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser :chrome
 - Version 23

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @shubhs2060 

Did you mean about how to run your job using API call with options? for that, use it like this:

`curl --data-urlencode "argString=-opt1 value" http://localhost:4440/api/29/jobyou/run?authtoken=your-user-token`

I did an example that works with the curl API call above:

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='opt1' />
      </options>
    </context>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>e938b29c-eb37-466f-bd4a-129cbac193fc</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo ${option.opt1}</exec>
      </command>
    </sequence>
    <uuid>e938b29c-eb37-466f-bd4a-129cbac193fc</uuid>
  </job>
</joblist>
```

If you want to use option value on some inline script you can use @option.youroption@ format, on an "external bash script" $RD_OPTION_YOUROPTION.

Hope it  helps!

Regards.

**Comment by shubhs2060** [comment]
I am passing the options to rundeck api url using Postman 
and trying to access it inside a shell script inside rundeck
The url is something like -> http://localhost:4440/api/1/job/5455ad9e-8a5/run?option.name="test"

**Comment by MegaDrive68k** [comment]
Hi @shubhs2060 

The best way to passing options to Rundeck with Postman is to use x-www-form-urlencoded.

I use this job definition (it uses inline-script but works with "external" script):

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='opt1' />
      </options>
    </context>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>92f1e849-73c8-487d-be14-7599f4f3fbb6</id>
    <loglevel>INFO</loglevel>
    <name>JobTest</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <script><![CDATA[echo @option.opt1@]]></script>
        <scriptargs />
      </command>
    </sequence>
    <uuid>92f1e849-73c8-487d-be14-7599f4f3fbb6</uuid>
  </job>
</joblist>
```

In the Postman side, I use this (change by your hostname, user token, job ID and import it):

```
curl -X POST \
  http://hyperion:4440/api/31/job/92f1e849-73c8-487d-be14-7599f4f3fbb6/run \
  -H 'Accept: application/json' \
  -H 'Content-Type: application/json' \
  -H 'Postman-Token: 52f0198b-436f-46e2-9c6d-02af01a16f8b' \
  -H 'X-Rundeck-Auth-Token: L1ZePzysidsYimSE0Dh7LPZ7yrRSPHZ8' \
  -H 'cache-control: no-cache' \
  -d 'argString=-opt1%20value&undefined='
```

Set the common heads, make sure that you're passing the auth key using X-Rundeck-Auth-Token, check:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/65358144-3ecf5880-dbcf-11e9-9f24-9e969015b43d.png)

Pass the options using Body -> x-www-form-urlencoded and add argString as key and your option on the value in this way: -optionname value-that-youwant, check this:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/65358616-6bd03b00-dbd0-11e9-99cc-5efaeceacf3d.png)

And finally, the job with option runs succeded if you're clicking on "Send":

![Screenshot_4](https://user-images.githubusercontent.com/51376003/65358349-b9987380-dbcf-11e9-8f2e-5743cf70ef91.png)


Anyway, you have a lot of options of Rundeck API with Postman here:

https://documenter.getpostman.com/view/95797/rundeck/7TNfX9k?version=latest

Greetings!

**Comment by shubhs2060** [comment]
Hey 
Can you let me Know what have you written in your Rundeck Script so that it prints value as the answer

**Comment by shubhs2060** [comment]
No Problem got it thanks !
