### ISSUE TITLE
deb upgrade from 3.0.21 to 3.1.0 fails due to missing rundeck-config.properties

### ISSUE THREAD

**Issue by adriankirchner** [rundeck/rundeck#5115]
**Describe the bug**
When upgrading from 3.0.21 to 3.1.0 via apt combined with using rundeck-config.groovy instead of rundeck-config.properties the process fails.

**My Rundeck detail**

* Rundeck version: 3.0.21 to 3.1.0
* install type: deb / apt
* OS Name/version: ubuntu 18.04
* DB Type/version: mysql

**To Reproduce**
1. install rundeck < 3.1.0 via apt / deb
2. hit `apt-get install rundeck` to trigger upgrade to 3.1.0

**Expected behavior**
I expected the process to upgrade my current rundeck installation to 3.1.0.

**Additional context**
```bash
apt-get install rundeck
Reading package lists... Done
Building dependency tree
Reading state information... Done
rundeck is already the newest version (3.1.0.20190731-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n]
Setting up rundeck (3.1.0.20190731-1) ...
usermod: no changes
rundeck.server.uuid = 9b97b5f5-45a7-48fd-ac6e-8fda56eb058a
sed: can't read /etc/rundeck/rundeck-config.properties: No such file or directory
dpkg: error processing package rundeck (--configure):
 installed rundeck package post-installation script subprocess returned error exit status 2
Errors were encountered while processing:
 rundeck
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Workaround**
1) Disable the following sed commands in `/var/lib/dpkg/info/rundeck.postinst`
```
sed -i -E 's/^rundeck\.storage\.converter\.([0-9]+)\.config\.password=default\.encryption\.password$/rundeck.storage.converter.\1.config.password='"$STORAGE_PASS"'/' "$DIR/rundeck-config.properties"
sed -i -E 's/^rundeck\.config\.storage\.converter\.([0-9]+)\.config\.password=default\.encryption\.password$/rundeck.config.storage.converter.\1.config.password='"$STORAGE_PASS"'/' "$DIR/rundeck-config.properties"
```
2) Run `openssl rand -hex 8` to obtain a password
3) Add the following lines to your rundeck-config.groovy and replace the password placeholder
```
rundeck.config.storage.converter."1".config.password=$PASSWORD
rundeck.storage.converter."1".config.password=$PASSWORD
```
4) finish the upgrade by hitting `apt-get install rundeck` again

**Comment by nmamn** [comment]
I agree, same problem here

**Comment by gschueler** [comment]
ref https://github.com/rundeck/packaging/pull/5

**Comment by ProTip** [comment]
There is a new package revision out that checks for the file before attempting to modify it.
