### ISSUE TITLE
Error 500: Internal Server Error after saving a job

### ISSUE THREAD

**Issue by ZoeLeah** [rundeck/rundeck#5116]
**Describe the bug**
Error 500: Internal Server Error

URI
    /rundeck/project/MicroStrategy/job/update
Class
    java.sql.SQLException
Message
    could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement
Caused by
    ORA-00060: deadlock detected while waiting for resource 

**My Rundeck detail**

* Rundeck version: 3.1.0
* install type: war
* OS Name/version: RHEL 7.6
* DB Type/version: oracle

**To Reproduce**
1. Edit a Job and save it

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox
 - Version 60.8.0esr

**Comment by ZoeLeah** [comment]
[trace.txt](https://github.com/rundeck/rundeck/files/3457473/trace.txt)

**Comment by ZoeLeah** [comment]
Does anyone have any idea how to solve the problem?

**Comment by sjrd218** [comment]
@ZoeLeah does the job you're saving have options?

**Comment by ZoeLeah** [comment]
We can not save a job anymore.  Whether with or without options.

Cheers,
Ronnie

**Comment by sethrice** [comment]
I've run into this as well. I had to manually recreate the jobs by copying and pasting each setting from screen to screen. Simply duplicating the job with the option in the UI wasn't a fix.

I also have found I've had to save the job after adding each option, and each step. For new jobs and old jobs. Which is very annoying, but less annoying than when you get to add the last step, and notice all the options you added or changed, but didn't save yet are gone.

I also had an event happen where I added a step, then edited an option. Without saving after each edit. Only to scroll down and find the step I just added was gone. I re-added the step, and found that after saving it, and going back in, that both steps were present. But the option change didn't take. All kinds of funky bugs scurrying forth. I've also found sometimes hitting the back button when you get errors after saving, and then trying to save again, though you get the error again, helps. But I haven't been able to consistently reproduce the desired saving effect.

**Comment by ZoeLeah** [comment]
What helps is to export the job, edit it and then upload it.

**Comment by jessemarple** [comment]
It appears this issue has been abandoned or the the OP has moved on. Our policy is to close issues where no response has been made in 30 days. If you feel as though we have closed this in error or the issue still persists, please reopen the issue.
