### ISSUE TITLE
TAGS are no longer available

### ISSUE THREAD

**Issue by ZoeLeah** [rundeck/rundeck#5117]
**Describe the bug**
The TAGS are no longer available in the jobs.

**My Rundeck detail**

* Rundeck version: 3.1.0
* install type: war (with tomcat 9)
* OS Name/version: RHEL 7.6
* DB Type/version: oracle

**To Reproduce**
Job Source:
[S_E_Kill_mstr_adm.zip](https://github.com/rundeck/rundeck/files/3457596/S_E_Kill_mstr_adm.zip)

**Expected behavior**
List of TAGS

**Screenshots**
![2019-08-01 17_53_34-SWAT DVLP Rundeck - S_E_Kill mstr_adm](https://user-images.githubusercontent.com/35896948/62308259-62a2d780-b485-11e9-9494-59351f9c8603.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 60.8.0esr

**Comment by winnieoursbrun** [comment]
+1

**Comment by jplassnibatt** [comment]
The issue is still on 3.1.2.-

**Comment by brrratz** [comment]
+1
Same here, sorting out the hosts by tags was perfect. Especially if you started the "node design" with this feature.
