### ISSUE TITLE
Enforced from Allowed Values fail when option value is used in Remote URL

### ISSUE THREAD

**Issue by maturbet** [rundeck/rundeck#5120]
Enforced from Allowed Values fail if a previous option value is used in Remote URL for a second value : 

> Option OPT2 value: prdgfc01 was not in the allowed values: []

**My Rundeck detail**
* Rundeck version: 3.1.0-20190731
* install type: WAR
* OS Name/version: Debian GNU/Linux 9 (stretch)
* DB Type/version: mysql

**To Reproduce**
1. Simple first option OPT1  : type text, no restriction
2. Second option OPT2 (type text) with Allowed Values from Remote URL
3. Use OPT1 value in this URL
4. Choose restriction : Enforced from Allowed Values
5. On page choosing options, OPT2 chow the good list from URL if OPT1 is filled in
6. The restriction  fail with empty list on clic "Run Job Now"

The job is OK with previous version of Rundeck (3.0.22-20190512)

**Screenshots**
![Sélection_001](https://user-images.githubusercontent.com/28108356/62355620-a7735080-b50f-11e9-80f3-4d5be66fd60a.png)
![Sélection_002](https://user-images.githubusercontent.com/28108356/62356700-f621ea00-b511-11e9-8328-bb226c4be33f.png)

**Comment by MegaDrive68k** [comment]
Hi @maturbet 

Can you share your job definition to take a look? following your steps all seems ok from here (Using 3.1 WAR on Linux).

Thanks!

**Comment by maturbet** [comment]
> Hi @maturbet
> 
> Can you share your job definition to take a look? I followed your steps but all seems ok from here (Using 3.1 WAR on Linux).
> 
> Thanks!


[TEST_MATU.yaml.txt](https://github.com/rundeck/rundeck/files/3491351/TEST_MATU.yaml.txt)

**Comment by MegaDrive68k** [comment]
Hi @maturbet 

Can you test this Job Def? I tried but seems normal:

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='OPT1' required='true' />
        <option enforcedvalues='true' name='OPT2' required='true' valuesUrl='http://httpbin.org/${option.OPT1.value}' />
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <group>test</group>
    <id>3aac80e3-db5b-405c-9c8b-c48ca8f88b08</id>
    <loglevel>INFO</loglevel>
    <name>TEST MATU 9</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <description>OPT1</description>
        <node-step-plugin type='localexec'>
          <configuration>
            <entry key='command' value='echo ${option.OPT1}' />
          </configuration>
        </node-step-plugin>
      </command>
      <command>
        <description>OPT2</description>
        <node-step-plugin type='localexec'>
          <configuration>
            <entry key='command' value='echo ${option.OPT2}' />
          </configuration>
        </node-step-plugin>
      </command>
    </sequence>
    <uuid>3aac80e3-db5b-405c-9c8b-c48ca8f88b08</uuid>
  </job>
</joblist>
```

![Screenshot_1](https://user-images.githubusercontent.com/51376003/64725514-1d71bc80-d4ab-11e9-8f44-3156d5c3d31b.png)

Kind Regards!

**Comment by jkempa** [comment]
Duplicate with: #5167

**Comment by maturbet** [comment]
It's OK with this job definition but still KO using mine URL.

Differences I saw : URL syntax & jison returned format

**Comment by maturbet** [comment]
Still KO with Rundeck 3.1.2

**Comment by jeanslw** [comment]
Me too! 3.1.0 - 3.1.2

**Comment by Alex-So** [comment]
The same issue is reproducible for me on

**Rundeck version**: 3.1.3-20191204
**Install type**: rpm
**OS Name/version**: CentOS 6

Steps to reproduce are the same as in bug description, with some **additional details**:
**OPT_1** = 2019 (it's the only possible value for the option - "**Default value**"=="**Allowed Values**" and choosen "**Enforced from Allowed Values**")
**OPT_2** = https://testserver.com/api/options/${option.OPT_1.value}/list

Before running the job all properties are visible in the drop-down list. But after pushing "Run Job Now" I have the same error:
**Option OPT_2 value: value1 was not in the allowed values: []**

Real Url, which tries to call **OPT_2** after launching the job is - https://testserver.com/api/options//list
So for some reasons **${option.OPT_1.value}** becomes "" (empty string)

If change **OPT_2** from "**Enforced from Allowed Values**" to "**None**" and choose **OPT_2** before launching the job - No issues.

**Comment by maturbet** [comment]
Hello,

I still reproduce it with Rundeck 3.2.0-20191218

**Comment by MegaDrive68k** [comment]
Hi guys, 

Can you test with this Job Def?

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option enforcedvalues='true' name='OPT1' required='true' valuesUrl='http://ip.jsontest.com' />
        <option enforcedvalues='true' name='OPT2' required='true' valuesUrl='https://httpbin.org/anything/${option.OPT1.value}' />
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>ac418776-7093-4589-b93a-d0a01fc02de0</id>
    <loglevel>INFO</loglevel>
    <name>test-json-options</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <description>ECHO 1</description>
        <exec>echo ${option.OPT1}</exec>
      </command>
      <command>
        <description>ECHO 2</description>
        <exec>echo ${option.OPT2}</exec>
      </command>
    </sequence>
    <uuid>ac418776-7093-4589-b93a-d0a01fc02de0</uuid>
  </job>
</joblist>
```

It works for me, maybe it's something related to JSON response?

**Comment by Alex-So** [comment]
Hello @MegaDrive68k, 

Very strange, but even your code above doesn't work for me on:
**Rundeck version**: 3.2.0-20191218
**Install type**: rpm
**OS Name/version**: CentOS 6
**Browser**: Chrome (79.0.3945.88), FF (71.0)

![Screenshot_3](https://user-images.githubusercontent.com/11671276/71367415-a8d01300-25ad-11ea-9a2a-6aa5f2b3622b.png)

> Can you provide an example of that output of your remote service to test?
**OPT_2** = https://testserver.com/api/options/${option.OPT_1.value}/list
the output is a simple JSON array:
`["2018", "2000", "1989", "1977", "1969", "1954", "1940"]`

As List Delimiter for **OPT_2** set comma (,)

**Comment by tonton1728** [comment]
Hello,
We faced the same problem and we spent couple hours trying to figure a way around this and we found a way. As far as our investigation goes, we noticed that when rundeck validate the value, it make a new call to the option provider but for some reason this call is made without filling the value (ex : option.OPT_1.value) and if the option provider answers with a HTTP 200. He takes the result for the authorized options to  compare with. In our case, we were able to modify the option provider to reply HTTP 404 if the options values are empty and there rundeck makes a second call with the correct values and so we get the expected behavior.
Hopes it can help stucked people and dev to fix this issue

**Comment by maturbet** [comment]
Hello @MegaDrive68k ,

Your exemple is OK choosing non empty elements (headers,method,origin,url)
@Alex-So : "data" is empty and OPT2 is required ;)

But as @Alex-So , it is still ko with a simple json's array (using square brackets and not curly brackets)

**Comment by maturbet** [comment]
Thanks a lots @tonton1728 !

You permited me to find an easy way.
Now, if OPT1's value is empty, the json is no longer an empty list but a null return.
It fix the problem !

**Comment by lenaing** [comment]
Hello, @MegaDrive68k ,
Is it possible to reopen this issue ?

As stated by @tonton1728 , Rundeck (3.1.3-20191204 & 3.2.0 maybe) makes two calls, one with empty parameters then, upon receiving a 404 HTTP Code, makes another one with parameters filled in this time.

Kind regards,

**Comment by carlgevans** [comment]
We are also seeing this with v3.2.1-20200113, it was ok in v3.0.x something prior to the upgrade.

Option VLANID value: 2 was not in the allowed values: [] 

This is a sample of the JSON. we are not using option values in this particular URL.

[
  {
    "name": "Default VLAN, Do Not Use", 
    "value": 1
  }, 
  {
    "name": "Test", 
    "value": 2
  }
]

**Comment by gmcdev** [comment]
I think I'm facing this issue, although I don't see the @tonton1728 workaround: The validation request to`/scheduledExecution/loadRemoteOptionValues` has the `selectedValue` and all the correct options. But the validation still throws [see screenshot]

<img width="1577" alt="rundeck-issue" src="https://user-images.githubusercontent.com/987118/73602596-9f7e8280-452b-11ea-9d43-372617c51280.png">

Am I doing something wrong?? I'm blocked~
