### ISSUE TITLE
User is not redirected to homepage after successful login

### ISSUE THREAD

**Issue by lukasged** [rundeck/rundeck#5122]
**Describe the bug**
When a user logs-in successfully, he's not redirected to the homepage of the projects list, it does nothing instead (stays at `/user/login`).

**My Rundeck detail**

* Rundeck version: `3.1.0-20190731`
* install type: rpm
* OS Name/version: Linux/CentOS 7
* DB Type/version: `h2`

**To Reproduce**
1. Go to '/menu/home'
2. Enter correct credentials
2. Click on 'Log In'
4. See that nothing happens

**Expected behavior**
Automatic redirection to the homepage (`/menu/home`) after login.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 75

**Additional context**
I also tried with Microsoft Edge browser and the result is that the browsers stays at `/user/login` but shows a blank page instead.
Then I also tried with Mozilla Firefox 67 and everything worked as expected (got redirected automatically to `/menu/home`)

**Comment by lukasged** [comment]
Also, when the issue happens using Chrome, I can see the following error message in its console:
```
Refused to send form data to 'http://${RUNDECK_URL}/' because it violates the following Content Security Policy directive: "form-action 'self'".
```

**Comment by paulholden** [comment]
@lukasged - see solution to the CSP violation here https://github.com/rundeck/rundeck/issues/4417#issuecomment-457548602

**Comment by lukasged** [comment]
thanks @paulholden, in my case it was enough to just add `-Drundeck.jetty.connector.forwarded=true` for `RUNDECK_JVM` 👍
