### ISSUE TITLE
Node filter save not working inside job edit

### ISSUE THREAD

**Issue by ronaveva** [rundeck/rundeck#5123]
**Describe the bug**
Issue type: Bug report

Save node filter does nothing inside the job edit page.

**My Rundeck detail**

* Rundeck version: 3.1.0-SNAPSHOT
* install type: war
* OS Name/version: pop-os 19.04
* DB Type/version: h2

**To Reproduce**
1. Go into any job edit page
2. Press Node tab
3. Enter a node filter
4. Click "Save Filter"

**Expected behavior**
A pop up should appear to allow the node filter to be saved.

**Screenshots**

![image](https://user-images.githubusercontent.com/50217398/62374504-1ea5e600-b50a-11e9-93d6-4270506a8cc0.png)

**Desktop (please complete the following information):**
 - OS: pop-os 19.04
 - Browser Firefox
 - Version 67.0.4

**Comment by MegaDrive68k** [comment]
Clicking on that button nothing happens (on 3.1 final release).

On 3.0.26 through happens on "Command" link.

The expected pop up (on 3.0.26):

![Screenshot_1](https://user-images.githubusercontent.com/51376003/65348371-5dc1f080-dbb7-11e9-8394-a08a5f2b9ec1.png)

Expected saved filter:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/65348388-69adb280-dbb7-11e9-9083-b8b94a99282a.png)

**Comment by ProTip** [comment]
Does not appear in the commands screen either.

**Comment by gschueler** [comment]
note: "Save filter" was not a feature of the job editor UI in 3.0 or earlier.  The "Save filter" menu item is probably incorrectly rendered in the job edit page.  the fix would be to add a toggle it off in the job edit page using a boolean parameter.  we can revisit adding that feature in the future, but the bug in this case seems to be that the menu item is incorrectly present

**Comment by jessemarple** [comment]
@gschueler - would the fix then be to remove "Save Filter" from everywhere with the exception of the Nodes page?

**Comment by gschueler** [comment]
@jessemarple i think so, in 3.0 only the Nodes page provides the UI for modifying or saving Node Filters

**Comment by MegaDrive68k** [comment]
Save Filter is present on the command page.

![Screenshot_1](https://user-images.githubusercontent.com/51376003/92755432-30d79200-f362-11ea-8b8e-a0e9def423fc.png)
