### ISSUE TITLE
Incorrect time on job activity page

### ISSUE THREAD

**Issue by paulholden** [rundeck/rundeck#5125]
**Describe the bug**
See following screenshot (the job was executed at 00:15 BST):

![Rundeck time](https://user-images.githubusercontent.com/1126541/62409414-b66d0800-b5ce-11e9-8924-986654b1fbdd.png)

The _Start time_ column shows the time as 11:15:20 pm, presumably because it hasn't applied the timezone offset.

The correct time is listed three times on the page, although using three wildly different formats.

**My Rundeck detail**

* Rundeck version: 3.1.0.20190731-2
* install type: deb
* OS Name/version: Ubuntu 16.04
* DB Type/version: MySQL 5.7.27

**To Reproduce**
1. Execute a job
2. View the execution log
3. Confirm that the time(s) listed are each correct

**Comment by MegaDrive68k** [comment]
Confirmed.

On 3.1.0:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/62489567-0dbcd500-b795-11e9-8081-e3e56f8e42f3.png)

On 3.0.24:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/62489925-11049080-b796-11e9-835f-e20ea1d9bbee.png)

**Comment by ahormazabal** [comment]
Fixed timezone offset at: https://github.com/rundeck/rundeck/pull/5213

**Comment by paulholden** [comment]
Thanks all, looks better in 3.1.1.20190923-1 👍

**Comment by cwaltherf** [comment]
Seing different Time Formats with Rundeck 3.3.2

![image](https://user-images.githubusercontent.com/36487101/94069485-10c6ba80-fdc7-11ea-8419-bb467ac37ef6.png)

**Comment by nvalenzuela20** [comment]
Tested @cwaltherf
