### ISSUE TITLE
Scheduled jobs cannot read secrets from key storage

### ISSUE THREAD

**Issue by lukasged** [rundeck/rundeck#5127]
**Describe the bug**
Scheduled jobs cannot read secrets from key storage.
I have a job that uses a secret password which is stored in the Rundeck key storage. In Rundeck versions 2.x I have been using this job both with a schedule and also with manual executions and it was always working fine. Now with Rundeck 3.x, the scheduled executions fail with the following message:
```
org.quartz.JobExecutionException: org.quartz.SchedulerException: Job threw an unhandled exception. [See nested exception: rundeck.services.ExecutionServiceValidationException: Option ********* is required, but storage value from "keys/******/******" could not be read.]
```

However, when I run this job manually, it works as expected, without changing anything else.

**My Rundeck detail**

* Rundeck version: `3.1.0.20190731-2`
* install type: rpm
* OS Name/version: Linux/CentOS 7
* DB Type/version: h2

**To Reproduce**
1. Create a secret in the Rundeck key storage
2. Use the previously created secret as an option for a Rundeck job
3. Schedule the job to run periodically
4. See that the job executions don't appear in the activity log, and the error shown in the description appears in Rundeck's output logs.

**Expected behavior**
The job is able to get secrets from key storage both in manual execution mode and in scheduled executions.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 75

**Comment by MegaDrive68k** [comment]
Hi @lukasged 

I tried to reproduce your issue (3.1.0 under Centos 7)  but seems ok.

Maybe you've got an ACL on your job that blocks the key access?

https://docs.rundeck.com/docs/administration/security/key-storage.html#acl-policies

Kind Regards.

**Comment by lukasged** [comment]
Hi @MegaDrive68k , thanks for reviewing it. 

For whatever reason, after Rundeck restart, this issue dissapeared without modifying the ACL policies (I only had an ACL policy for admin user to have full privileges and then another ACL policy for a limited user with lower privileges).

I'll close this issue for now. 

If the issue happens again, I'll review my ACL policies and if nothing helps, re-open the ticket.

Thanks again and sorry for the inconvenience.
