### ISSUE TITLE
Choose assigned groups for statically defined tokens

### ISSUE THREAD

**Issue by lukasged** [rundeck/rundeck#5128]
**Is your feature request related to a problem? Please describe.**
I statically define API tokens following the instructions at https://docs.rundeck.com/docs/administration/configuration/configuration-file-reference.html .

The problem is that, apparently, I can only choose the user associated with these tokens. The associated group is automatically `api_token_group` (at least in my case for the Rundeck version `3.1.0-20190731`)

**Describe the solution you'd like**
A possibility to choose also the group for static API tokens.

**Describe alternatives you've considered**
I'm just using the usernames for now, but it would be more convenient if I could also use the groups.

**Comment by sjrd218** [comment]
@lukasged 
Have you tried using the format: `username,role1,role2: token_string`

**Comment by lukasged** [comment]
thanks for the tip @sjrd218, I tried it and it works!

I don't see it documented anywhere though, it should probably be mentioned in https://docs.rundeck.com/docs/administration/configuration/configuration-file-reference.html .
