### ISSUE TITLE
Gui customisation options

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#5129]
Hi guys,

Would it be possible to add a few basic gui customisation options? For example, I'm loving most of the new 3.1.0 layout (great work!) but I'm really missing the table layout on the jobs page. I've got a couple of projects with a lot of jobs and I'm finding the grouping harder to see in the new format.

Or alternatively if the group names were slightly larger and bolder (not lighter) than the job names, it would help.

Cheers!

**Comment by fdevans** [comment]
Check out the options available with our GUI plugins.  If there are still gaps feel free to open a new issue with more details what you'd like to customize.
