### ISSUE TITLE
Anonymous access to /api/25/metrics/healthcheck

### ISSUE THREAD

**Issue by lukasged** [rundeck/rundeck#5132]
**Is your feature request related to a problem? Please describe.**
It would be very convenient if there was an easy way to configure anonymous access to `/api/25/metrics/healthcheck` (e.g. for load balancer health checks, Kubernetes health probes ...)

**Describe the solution you'd like**
An easy way to configure anonymous access to `/api/25/metrics/healthcheck`

**Describe alternatives you've considered**
I saw that there was a discussion in https://groups.google.com/forum/#!topic/rundeck-discuss/OGiVvhnX2yo suggesting to modify the `web.xml` like the following:
```
<security-constraint>
  <web-resource-collection>
    <web-resource-name>Metrics</web-resource-name>
    <url-pattern>/metrics/*</url-pattern>
  </web-resource-collection>
</security-constraint>
```

But is this still valid? There's no easier way to achieve that?

**Comment by getjack** [comment]
Hi there,
my team got the same issues when upgrading to 3.1.x . I was unable to find any documentation that there was a change in behavior. The only information i got was from the endpoint itself:

`{"error":true,"apiversion":32,"errorCode":"api.error.item.unauthorized","message":"Not authorized for action \"Read System Metrics\" for Rundeck "}`

From my understanding i would create an acl for that user but there is no documentation regarding API acls. halp please :(

**Comment by MatrixCrawler** [comment]
Is it possible that you have to define read access to system for anonymous?

https://github.com/rundeck/rundeck/blob/341f5d193e20d0bf326353b87acee1e512453747/rundeckapp/grails-app/controllers/rundeck/controllers/ApiController.groovy#L85

**Comment by rockandska** [comment]
Hi,

Since web.xml is no longer available since 3.0.0, what is the correct method to achieve an anonymous access to health-check please ?

**Comment by sagor999** [comment]
Workaround to this is to create a token that has access to API.  
ACL policy:  

> description: API Application level access control
> context:  
>   application: 'rundeck'  
> for:  
>   resource:  
>     - equals:  
>         kind: system  
>       allow: [read] # allow read of system info  
> by:  
>   group: api_token_metrics_group

Then create token with group name: `api_token_metrics_group`  
Then to access your healthcheck endpoint:  
`/api/25/metrics/healthcheck?authtoken=<your_token_here>`

**Comment by fdevans** [comment]
To maintain the security of the solution we will not be adding anonymous access.  @sagor999 has a reasonable alternative using API keys and ACLs.

**Comment by monsdar** [comment]
Late to the party, but as I stranded here: Anonymous access to health-check is available at /health now. Docs: https://docs.rundeck.com/rundeck-cloud/administration/cluster/loadbalancer/health-check.html
