### ISSUE TITLE
Duration of job executions is just displayed as 'a few seconds'

### ISSUE THREAD

**Issue by lukasged** [rundeck/rundeck#5133]
**Is your feature request related to a problem? Please describe.**
When I switched from Rundeck 2.x to Rundeck 3.x, I noticed that the activity list for the jobs shows the execution duration always as `a few seconds`, because my jobs always take less than a minute to run. In Rundeck 2.x it was displaying the real amount of seconds.
**Describe the solution you'd like**
The job activity list should show the real duration of the jobs (or there should at least be an option to choose if one wants to show the real value or just `a few seconds`). It would help identifying issues faster. For now, in order to see the real duration of a job, you need to check the details of that exact job, so it's not so fast to compare the duration of many job executions.

![image](https://user-images.githubusercontent.com/5601295/62529945-eb33c600-b83f-11e9-9145-76f6f90cbefb.png)

**Comment by sebastianbello** [comment]
+1 .   This issue was  also reported / associated to a Support Case

**Comment by yoretech** [comment]
**To add to @lukasged illustration and a request for the return of the previous layout.**

**Thank you**

**Previous (pre-3.1 display) showing a run time of 23 seconds**

![3 0ActivityOutput](https://user-images.githubusercontent.com/46457681/65105767-67c3d380-d9ac-11e9-9f1e-ad5295390c44.png)

**vs**

**Current 3.1x display, showing the same run as a few seconds**

![3 1ActivityOutput](https://user-images.githubusercontent.com/46457681/65105782-76aa8600-d9ac-11e9-9a03-78bccd86c98e.png)
