### ISSUE TITLE
Scheduling using crontab displays warning

### ISSUE THREAD

**Issue by praveenag** [rundeck/rundeck#5134]
**Describe the bug**
Unable to schedule rundeck using crontab feature

**My Rundeck detail**

* Rundeck version: Rundeck 3.1.0-20190731 
* install type: docker
* OS Name/version: Debian 4.19.0-0.bpo.5-amd64

**To Reproduce**
1. Go to 'Any job that is triggered manually'
2. Click on 'Edit Job > Goto Schedule tab > Crontab'
3. Enter `0 00 04 ? * TUE-SAT *`
4. Save
5. Goto Jobs 
6. It displays that the job will never be executed with a warning sign

Whereas if you schedule the job for the same time frame using simple tab - Enter time, Click days of the week and save
1. Goto Jobs
2. It doesnt display the warning and instead shows when its next scheduled for

**Expected behavior**
It should behave the same way whether i add the schedule using crontab or simple tab

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Firefox

**Comment by MegaDrive68k** [comment]
Hey @praveenag,

I tried to reproduce your issue following your steps but all seems OK (from Docker and "normal instance"), any clue on logs?

![Screenshot_1](https://user-images.githubusercontent.com/51376003/62550788-d1db4b80-b838-11e9-8909-22ee98e8bbd8.png)

Regards!

**Comment by praveenag** [comment]
@MegaDrive68k Sorry for the delayed response, The actual issue turned out to be even more weirder. I have an updated steps to reproduce and a gif showing you the same problem

1. Create a job that is scheduled to run(doesn't matter what)
2. Check whether it's scheduled to run
3. Edit something mundane about the job(like description) + Save
4. Notice that the job now says it will `Never` be run

![rundeck-scheduling-issue](https://user-images.githubusercontent.com/339793/62717198-5aa1e500-b9fb-11e9-809f-246846c3e69e.gif)

**Comment by MegaDrive68k** [comment]
Thanks for the GIF example @praveenag!

You're right, confirmed on 3.1.0 Docker image, on WAR doesn't happen.

![Screenshot_20190808_121354](https://user-images.githubusercontent.com/51376003/62719451-06383e80-b9d6-11e9-8ee5-a8006e248957.png)
