### ISSUE TITLE
Rundeck API documentation page, no scroll bar

### ISSUE THREAD

**Issue by dpomnean** [rundeck/rundeck#5136]
**Describe the bug**
Accessing the Rundeck api page loads without a horizontal scroll bar. Text is cut off.

Tested in firefox and chrome, giving the same behavior.

https://docs.rundeck.com/docs/api/

**Screenshots**
![image](https://user-images.githubusercontent.com/17032114/62572464-c2bcc380-b861-11e9-8b2a-216b30fb4239.png)

**Comment by gschueler** [comment]
thanks, this should be fixed, ref https://github.com/rundeck/docs/pull/287
