### ISSUE TITLE
API /api/21/project/<proj>/jobs returning incorrect results

### ISSUE THREAD

**Issue by puremourning** [rundeck/rundeck#5137]
**Describe the bug**

We're testing our deployments on rundeck 3.0.23, upgrading from 2.11.10. Our regression tests are failing because it is unable to find the Job ID for a particular job using the API.

The test requests the API endpoint as follows:

* /api/21/project/<project>/jobs
* Headers: Accept application/json, Content-Type application/json, X-RunDeck-Auth-Token <token>
* Payload: 

```
			                          {
			                              "groupPathExact":"AutoDeploy",
			                              "jobExactFilter":"RunTestSingle"
			                          }
```

The result is a list of _all_ jobs, but it should be max 1 job.

**My Rundeck detail**

* Rundeck version: 3.0.23
* install type: rpm
* OS Name/version: RHEL 6.5
* DB Type/version: mysql

**To Reproduce**

Run our regression tests that use this API after reloading all jobs in the project.

I attempted to repeat using postman, but i get the correct result using postman and curl.

The regression  tests first _reload all jobs_ , then run this API call almost immediately after, so could that be a case ?

**Expected behavior**

Only jobs matching the filter supplied in the API are returned.

**Additional context**

Output:

```

%INFO: Running TestAddServerASHWeekend on system XIT-TEST1
--
16:36:10 |   |   | %RUN: AutoDeploy/RunTestSingle
16:36:10 |   |   | - %ARG: -SYSTEM                   XIT-TEST1
16:36:10 |   |   | - %ARG: -HOST1                    ukwok-pc1385-vpc7
16:36:10 |   |   | - %ARG: -Test                     TestAddServerASHWeekend
16:36:10 |   |   | Request GET https://ukwok-pc1385-vpc:4440/api/21/project/XIT-TEST/jobs (type application/json) with X-RunDeck-Auth-Token <snip> Content-length 205 Content-type application/json Accept application/json
16:36:10 |   |   | Data: '
16:36:10 |   |   | {
16:36:10 |   |   | "groupPathExact":"AutoDeploy",
16:36:10 |   |   | "jobExactFilter":"RunTestSingle"
16:36:10 |   |   | }
16:36:10 |   |   | '
16:36:10 |   |   | Response Code: 200
16:36:10 |   |   | Response: '[{"href":"https://ukwok-pc1385-vpc:4440/api/31/job/27e60a04-4790-41cd-a5cb-3b26ea779ca7","id":"27e60a04-4790-41cd-a5cb-3b26ea779ca7","scheduleEnabled":true,"scheduled":false,"enabled":true,"permalink":"https://ukwok-pc1385-vpc:4440/project/XIT-TEST/job/show/27e60a04-4790-41cd-a5cb-3b26ea779ca7","group":"Install","description":"Add a new global region to an existing system","project":"XIT-TEST","name":"Add region to system"}, <snip 100s more entries that shouldn't match!>]'
```
As you can see, the request is valid, but the response includes job in the "Install" group, not the "AutoDeploy" group (in fact it seems to include all the jobs, ignoring the filter)

**Comment by puremourning** [comment]
Correction. I have reproduced it.

The issue happens when the request is a GET. 

If i issue a POST, which i was doing from postman, the result is correct.

Will update the issue.

**Comment by puremourning** [comment]
Passing the parameters as request arguments works. I guess using GET this way is foolish and probably shouldn't have worked before.

**Comment by puremourning** [comment]
Actually, this is clearly a regression in behaviour (the API doc says this query should be a GET)

**Comment by jtobard** [comment]
In the [documentation](https://docs.rundeck.com/docs/api/#listing-jobs) it is specified that it is a `GET` method and `groupPathExact` and `jobExactFilter` are **parameters**.
Since using the url `/api/V/project/<project>/jobs?groupPathExact=<group>&jobExactFilter=<name>` works It cannot be considered a bug.

**Comment by puremourning** [comment]
Ok so the change in behaviour was intentional?
