### ISSUE TITLE
No route to host for node

### ISSUE THREAD

**Issue by edwrd-t-justice** [rundeck/rundeck#5138]
Getting error "No route to host" when running a job.

11:42:35 | No route to host (Host unreachable)

**My Rundeck detail**

* Rundeck version: 3.0.5-20180828
* install type: RPM
* OS Name/version: CentOS release 6.10 (Final)
* DB Type/version: postgres

**To Reproduce**
Run a job against a set of nodes. All nodes but one will work. Example node config below

`<node name="server1.domain"
        description="Node 1"
        tags="client"
        hostname="server1.domain"
        osFamily="unix"
        osName="Linux"
        username="pdf"/>
`
`
 <node name="server2.domain"
        description="Node 2"
        tags="client"
        hostname="server2.domain"
        osFamily="unix"
        osName="Linux"
        username="pdf"/>
`

**Expected behavior**
Job will be able to run against all nodes. Only this one is reporting an issue when running jobs against it. I can also login as the rundeck user to the server that is failing via ssh directly

[rundeck@rundeckhost ~]$ ssh pdf@server1.domain
Last login: Wed Aug  7 12:42:56 2019 from rundeckhost
[pdf@node1 ~]$ exit

[rundeck@rundeckhost ~]$ ping -c3 server1.domain
PING server1.domain (IP) 56(84) bytes of data.
64 bytes from server1.domain (IP): icmp_seq=1 ttl=64 time=0.162 ms

12:08:11 | server1.domain | Failed: ConnectionFailure: No route to host (Host unreachable)
-- | -- | --
12:08:11 | Rundeckhost | Execution failed: 3620 in project Canada: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [server1.domain: ConnectionFailure: No route to host (Host unreachable) + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:server1.domain)=BaseDataContext{{exec={exitCode=-1}}}, ContextView(node:server1.domain)=BaseDataContext{{exec={exitCode=-1}}}}, base=null)} ]}, Node failures: {server1.domain=[ConnectionFailure: No route to host (Host unreachable) + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:server1.domain)=BaseDataContext{{exec={exitCode=-1}}}, ContextView(node:server1.domain)=BaseDataContext{{exec={exitCode=-1}}}}, base=null)} ]}, status: failed]

**Comment by edwrd-t-justice** [comment]
Sorry if my obfuscating info makes this harder to work with. I'll try to provide as much as possible when needed.

**Comment by MegaDrive68k** [comment]
Hi @edwrd-t-justice 

Can you test sending a command with an SSH connection from Rundeck instance? (i mean, using "commands" tab from the left menu). 

Something like `ssh pdf@server1.domain ls -ltr`

Kind regards!

**Comment by edwrd-t-justice** [comment]
This lead to the fix!!

That command exposed this:

`
ssh c09.domain.com ls -ltr

15:53:24 | c14.domain.com | 1. Command | Host key verification failed.
-- | -- | -- | --
15:53:24 |   |   | Failed: NonZeroResultCode: Remote command failed with exit status 255
`

Found the entry for the server in question in the **~/.ssh/known_hosts** of the rundeck server under the **rundeck** user. 

Deleted that entry and ssh'd again using the configured user, accepted the new host entry, and done. 

Able to run command now.

**Comment by edwrd-t-justice** [comment]
Thanks Mega. Any idea why **no route to host** was shown, rather than **host key verification**? Once you exposed that i was able to fix it quickly.
