### ISSUE TITLE
HTML sanitizer always enabled in notifications emails

### ISSUE THREAD

**Issue by jeantoulza** [rundeck/rundeck#5140]
**Describe the bug**
HTML sanitizer is always enabled in notifications emails when sent as inline even if it's disabled in framework, project properties and log render. This prevents the same output from being displayed on both the web interface and by email.

**My Rundeck detail**

* Rundeck version: 3.1.0-20190731
* install type: war
* OS Name/version: Debian 10
* DB Type/version: h2

**To Reproduce**
1. Have a workflow output the following HTML: `<table style="background-color: #000"></table>`

**Expected behavior**
Expect to see table colored in black in both log output (web interface) and in inline email.

**Screenshots**
Can provide if needed

**Comment by Ikizo** [comment]
Same problem here
