### ISSUE TITLE
Resource model generator with quoted args

### ISSUE THREAD

**Issue by amendlik** [rundeck/rundeck#5147]
**Describe the bug**
When calling a resource model generator script with arguments, quoted arguments are always delimited by spaces, and quoted spaces are ignored.

See amendlik/salt-gen-resource#5

This issue was reported by a user of the [Salt resource model generator](https://github.com/amendlik/salt-gen-resource), but the problem seems to be caused by Rundeck in the way it parses command line arguments before passing them to the resource model generator scripts.

Specifically, the problem is caused by this line: https://github.com/rundeck/rundeck/blob/master/core/src/main/java/com/dtolabs/rundeck/core/resources/ScriptResourceUtil.java#L335

**To Reproduce**
1. Install the [Salt resource model generator](https://github.com/amendlik/salt-gen-resource)
2. Configure it as follows:
```
resources.source.1.config.args=--log-file-level=debug -s -a environment -C 'G@region:SV and G@roles:webapp or G@roles:api or G@roles:job'
resources.source.1.config.file=/rundeck/scripts/SaltGenResource.py
resources.source.1.config.format=resourceyaml
resources.source.1.config.interpreter=sudo
resources.source.1.type=script
```
3. `'G@region:SV and G@roles:webapp or G@roles:api or G@roles:job'` should all be passed as a single argument with embedded spaces.
4. The Salt log file reveals that the argument was space-delimited and passed as multiple arguments.

**Expected behavior**
`'G@region:SV and G@roles:webapp or G@roles:api or G@roles:job'` should all be passed as a single argument with embedded spaces.

**Additional context**

**Comment by Mapel88** [comment]
Additional info:
When using 'Quote Interpreter Args' option the command passes properly according to the logs, but fails with "command not found" error.
`sudo: /rundeck/scripts/SaltGenResource.py -s -a environment,region,roles -t roles,environment,region -C 'G@region:SV and P@roles:(api|webapp)': command not found
`
This error is received with any argument when using 'Quote Interpreter Args' option.
