### ISSUE TITLE
Create Token endpoint does not respond with JSON content when 'Content-Type: application/json' request header is specified without 'Accept' header

### ISSUE THREAD

**Issue by remd** [rundeck/rundeck#5156]
**Describe the bug**
The [API documentation](https://docs.rundeck.com/3.0.23/api/index.html#xml-and-json) states:
```
If an “Accept” header is not specified, then the response will be either the same format as the request content (for POST, or PUT requests), or XML by default.
```

However, this is not true for the Create Token endpoint (and possibly other endpoints?). Even when the POST request specifies `Content-Type: application/json` and sends a JSON request body, the API returns an XML-formatted response unless an `Accept: application/json` header is also specified with the request. This behavior contradicts the API documentation.

**My Rundeck detail**
* Rundeck version: 3.0.23-20190619
* Install type: rpm
* OS Name/version: Oracle Linux Server 7.5
* DB Type/version: Oracle 11.2.0.4

**To Reproduce**
1. Authenticate via `/j_security_check` to get a `JSESSIONID` cookie back
2. Using the JSESSIONID cookie for authentication, call `/api/31/tokens` specifying `Content-Type` as `application/json` and specifying no `Accept` header:
```
curl -v -k --request POST \
   --url https://localhost:4443/api/31/tokens \
   --header 'Accept:' \
   --header 'Content-Type: application/json' \
   --cookie JSESSIONID=node014vwzhwogmcskgsqc8vi5htc128.node0 \
   --data '{
    "user": "username",
    "roles": "*"
}'
```

**Expected behavior**
The response body should be JSON-formatted even if no `Accept` header was specified since the request body was JSON and the request header `Content-Type` was specified as `application/json`. This would match the behavior of sending `Accept: application/json` with the request. For example:
```
> POST /api/31/tokens HTTP/1.1
> Host: localhost:4443
> User-Agent: curl/7.54.0
> Cookie: JSESSIONID=node014vwzhwogmcskgsqc8vi5htc128.node0
> Accept: application/json
> Content-Type: application/json
> Content-Length: 44
>
< HTTP/1.1 201 Created
< Date: Wed, 14 Aug 2019 20:32:04 GMT
< X-Frame-Options: deny
< X-XSS-Protection: 1
< X-Content-Type-Options: nosniff
< Content-Security-Policy: default-src 'none' ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; style-src 'self' 'unsafe-inline' ; img-src * ; font-src 'self' data: ; connect-src 'self' https://api.rundeck.com ; form-action 'self' ;
< X-Application-Context: application:production:4440
< Content-Type: application/json;charset=utf-8
< Transfer-Encoding: chunked
<
{"user":"username","token":"8iPsRShuJZFk8exhndqZFSBvjaELGtzF","id":"d242cde0-9542-4ddd-9e52-ba9b2d575c73","creator":"username","expiration":"2019-09-13T20:32:04Z","roles":["cn=Development","dc=myorg","readonly","dc=com","ou=bind_groups","cn=Utility"],"expired":false}
```

**Actual behavior**
```
> POST /api/31/tokens HTTP/1.1
> Host: localhost:4443
> User-Agent: curl/7.54.0
> Cookie: JSESSIONID=node014vwzhwogmcskgsqc8vi5htc128.node0
> Content-Type: application/json
> Content-Length: 44
>
< HTTP/1.1 201 Created
< Date: Wed, 14 Aug 2019 20:25:34 GMT
< X-Frame-Options: deny
< X-XSS-Protection: 1
< X-Content-Type-Options: nosniff
< Content-Security-Policy: default-src 'none' ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; style-src 'self' 'unsafe-inline' ; img-src * ; font-src 'self' data: ; connect-src 'self' https://api.rundeck.com ; form-action 'self' ;
< X-Application-Context: application:production:4440
< Content-Type: text/xml;charset=utf-8
< Transfer-Encoding: chunked
<
<?xml version="1.0" encoding="UTF-8"?><token user="username" token="EzGWa5GorVAGld2ktF8mVmafXPuUUUZC" id="3484674c-fb00-4925-9688-29993a709ab7" creator="username"><expiration>2019-09-13T20:25:34Z</expiration><roles><role>cn=Development</role><role>dc=myorg</role><role>readonly</role><role>dc=com</role><role>ou=bind_groups</role><role>cn=Utility</role></roles><expired>false</expired></token>
```

**Desktop:**
 - OS: macOS 10.13.6 (High Sierra)
 - Browser: `curl 7.54.0 (x86_64-apple-darwin17.0) libcurl/7.54.0 LibreSSL/2.0.20 zlib/1.2.11 nghttp2/1.24.0`

**Additional context**
N/A

**Comment by MegaDrive68k** [comment]
Hi @remd 

Thanks for your feedback! Meanwhile you can do it (using user token):

`curl --location --request GET --URL http://yourhost:4440/api/31/tokens --header "Accept: application/json" --header "X-Rundeck-Auth-Token: UbsU61kUMZTwQCpRipAAM0yqBpqoNUEA"`

Answer (as example, using application/json):

`[{"user":"admin","id":"684f0bf0-e6eb-4f14-a16f-0dfee3927b70","creator":"admin","expiration":"2019-09-19T20:41:51Z","roles":["admin","user"],"expired":false}]`

Answer (using application/xml):

`<?xml version="1.0" encoding="UTF-8"?><tokens user="" allusers="true" count="1"><token user="admin" id="684f0bf0-e6eb-4f14-a16f-0dfee3927b70" creator="admin"><expiration>2019-09-19T20:41:51Z</expiration><roles><role>admin</role><role>user</role></roles><expired>false</expired></token></tokens>`

Kind regards.

**Comment by MegaDrive68k** [comment]
Meanwhile you can use:

```
curl --location --request GET "http://yourhost:4440/api/31/tokens" \
  --header "Accept: application/json" \
  --header "X-Rundeck-Auth-Token: user token"
```

Greetings!

**Comment by MegaDrive68k** [comment]
This issue still happens on 3.1.2.
