### ISSUE TITLE
RD 3.1.0: Job schedule will never fire after editing only the steps

### ISSUE THREAD

**Issue by babs** [rundeck/rundeck#5159]
**Describe the bug**
After editing only steps of a job and saving, it enters in a "Job schedule will never fire" state without further details on why.
To circumvent the issue, I have to disable job scheduling and re-enable it.

Note 1: that it's not a cosmetic issue, the job really doesn't fire when expected.
Note 2: that if I also edit the scheduling of the job (change an option or the time), the job is perfectly rescheduled.

**My Rundeck detail**

* Rundeck version: 3.1.0
* install type: deb
* OS Name/version: Debian Stretch
* DB Type/version: MariaDB

**To Reproduce**
1. Add or edit a step of a perfectly scheduled job
2. Save the job
4. See the NEVER tag and the job never executes.

**Expected behavior**
The job to be scheduled as exprected :)

**Screenshots**
After editing the workflow:
![image](https://user-images.githubusercontent.com/117580/63083251-8b78a180-bf48-11e9-9ca1-1be9810550e5.png)

After disable/enable schedule:
![image](https://user-images.githubusercontent.com/117580/63083343-c549a800-bf48-11e9-9b54-bc5486fa650e.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser chromium
 - Version 76.0.3809.87

**Comment by tigerlee** [comment]
+1

**Comment by MegaDrive68k** [comment]
Hi @babs and @tigerlee 

And here the pull request:

https://github.com/rundeck/rundeck/pull/5145

You can follow the original issue.

https://github.com/rundeck/rundeck/issues/5134

Cheers!
