### ISSUE TITLE
Option "OptionName" value: "valueuforoption" was not in the allowed values: []

### ISSUE THREAD

**Issue by jkempa** [rundeck/rundeck#5167]
**BUG Description**
In case of URL option values, if there is a dependency on other option, something goes wrong when the option is restricted to "Enforced from Allowed Values " -> the job does not start due to checking the allowed values.
This is a new behavior in this version. In the version before it has been correctly working.

**My Rundeck detail**
* Rundeck version: 3.1.0-20190731 
* install type: rpm (rundeck-3.1.0.20190731-3.noarch)
* OS Name/version: Red Hat Enterprise Linux Server release 7.6 (Maipo)
* DB Type/version: H2 (Rundeck default)

**To Reproduce**
1. Create the first Job Option based on URL with "Enforced from Allowed Values"
2. Create the second Job Option based on URL with values depended on the choose of first option with "Enforced from Allowed Values"
3. start job

**Comment by wep-p** [comment]
+1

**Comment by MegaDrive68k** [comment]
Hi @jkempa 

Did you saw this behavior? https://github.com/rundeck/rundeck/issues/5131

Kind regards.

**Comment by jkempa** [comment]
Yes, the same behavior in that version if you try to change/remake the Options from jobs defined in the previous versions of rundeck.

**Comment by wep-p** [comment]
I get the same error after upgrading rundeck to 3.1.0. The jobs ran perfectly fine on the older versions 3.0.2x.

**Comment by MegaDrive68k** [comment]
We will follow here: https://github.com/rundeck/rundeck/issues/5131

You can see the fix ready for the next version here:

https://github.com/rundeck/rundeck/pull/5146

Regards!

**Comment by jeanslw** [comment]
+1,#5120
