### ISSUE TITLE
Logging in on Chrome doesn't redirect to main page

### ISSUE THREAD

**Issue by jsmith-mim** [rundeck/rundeck#5175]
**Describe the bug**
When users log in to our Rundeck instance using Google Chrome (or another Chromium-based browser such as Brave), they should be redirected to the main Rundeck interface, but they aren't. However, they are able to access it successfully by deleting `/user/login` from the URL.

Firefox does not exhibit this behavior.

**My Rundeck detail**

* Rundeck version: 3.1.0.20190731
* install type: RPM
* OS Name/version: CentOS 7
* DB Type/version: MariaDB

**To Reproduce**
1. Browse to https://rundeck.domainname.com using Google Chrome or a Chromium-based browser
2. Log in using the login form
3. Note that no output is shown on the screen, and the user is not redirected from https://rundeck.domainname.com/user/login to https://rundeck.domainname.com

**Expected behavior**
The user should be redirected to the main Rundeck interface.

**Screenshots**
Not helpful in this case.

**Desktop (please complete the following information):**
 - OS: Windows, macOS, Linux
 - Browser: Chrome, Brave
 - Version: Latest

**Additional context**
Our Rundeck instance is sitting behind an Nginx reverse proxy.

**Comment by ericjsilva** [comment]
I have observed the same behavior on our install. Also using Chrome behind a reverse proxy.

**Comment by MegaDrive68k** [comment]
Hi @jsmith-mim and @ericjsilva,

Please check this: https://github.com/rundeck/rundeck/issues/5122#issuecomment-518161272

Hope it helps!

**Comment by jsmith-mim** [comment]
@MegaDrive68k Thanks! The solution in #4417 worked for me.

**Comment by ericjsilva** [comment]
@MegaDrive68k Thanks!. Solution in $4417 worked for me as well.

**Comment by benjamincotta** [comment]
Ive read #4417 and #5122 and I have literally no idea what any of that that means or how to do what is suggested!! HELP

**Comment by ericjsilva** [comment]
> Ive read #4417 and #5122 and I have literally no idea what any of that that means or how to do what is suggested!! HELP

@benjamincotta in the `profile` file in your Rundeck installation (e.g., `/etc/rundeck/profile`) you need to add the line `-Drundeck.jetty.connector.forwarded=true` to the `RDECK_JVM` arguments.

**Comment by dorancemc** [comment]
Adding this parameter on rundeck-config.properties file solves the issue `server.useForwardHeaders=True`
