### ISSUE TITLE
edit default jsch-ssh node-executor fields not working

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#5183]
**Describe the bug**
Looks similar to #2107

**My Rundeck detail**

* Rundeck version: [Rundeck 3.1.0-20190731]
* install type: rpm and war
* OS Name/version: ubuntu 18.04 and centos7
* DB Type/version: H2 and mysql.5.6

**To Reproduce**
1. Create new default project and save it (it will be a jsch-ssh)
2. Edit it to change "Default Node Executor" tab's "SSH Key File path" or "SSH Authentication" fields.
3. Save it.
4. Edit it again and you'll see that changes weren't saved (i.e. SSH Authentication keeps as privateKey)

**Expected behavior**
"Default Node Executor" Changes to be saved.

**Additional context**
If you edit the "Default File Copier", the changes there, will be applied in "Default Node Executor"

**Workaround**
Manually edit the project's configuration file.

**Comment by markkuit** [comment]
Still happening on v3.2.2-15-g86ed80f.

**Comment by ltamaster** [comment]
same as https://github.com/rundeck/rundeck/issues/3867

**Comment by carlosrfranco** [comment]
It seems the same issue fixed by this PR https://github.com/rundeck/rundeck/pull/6434
@jplassnibatt can you confirm if this issue still happening on latest version?

**Comment by jplassnibatt** [comment]
@carlosrfranco , not in 3.3.5 nor 3.3.6rc3.-
