### ISSUE TITLE
Change API Docs Navigation!

### ISSUE THREAD

**Issue by alex067** [rundeck/rundeck#5185]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**
The new design for the API documentation makes it frustrating to navigate. The sidebar does not scroll until you're at the bottom of the page, and the top navbar takes up a lot of room.

**Describe the solution you'd like**
Allow us to scroll the side bar separately from the main section, and hide the top navbar when we're scrolling down. Only show the top nav bar when the user scrolls up.

**Comment by gschueler** [comment]
this should be fixed
