### ISSUE TITLE
User's first/last name can't contain certain regional characters.

### ISSUE THREAD

**Issue by mkmet** [rundeck/rundeck#5188]
**Describe the bug**
User's first/last name can't contain common Czech/Slovak characters as š, č, ť, ř, etc.

When trying to edit this manually via web GUI, this error message will appear: "Property [lastName] of class [class rundeck.User] with value [Xxxš] does not match the required pattern [^[a-zA-Z0-9À-ÖØ-öø-ÿ\s\.,\(\)-]+$]"

For users with First/Last name containing those characters. First name, last name and email are not synchronized from LDAP. For users without those characters, synchronization works fine probably because they're failing the same regexp.

**My Rundeck detail**

* Rundeck version: 3.1.0-20190731
* install type: deb
* OS Name/version: Ubuntu 18.04.3
* DB Type/version: MariaDB 10.1.41

**To Reproduce**
Try to change first/last name to a name containing letters with caron (examples in the description) and try to save or try to sync user with such first/last name from LDAP.

**Expected behavior**
Users with such names should be able to synchronize via LDAP and be saved in profile edit successfully.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 76

**Comment by MegaDrive68k** [comment]
This issue still happens on 3.1.2.

**Comment by MegaDrive68k** [comment]
It still happens in 3.2.0-SNAPSHOT.
