### ISSUE TITLE
How to do REST cli in a step? How to execute groovy script in a workflow step, with embeded rundeck groovy?

### ISSUE THREAD

**Issue by gaetanquentin** [rundeck/rundeck#5195]
Env:
 RD 3.1
 ubuntu 18.04

3 Questions:

 I would like to get information from an external microservice with REST connexions.

1. What is the prefered way to do it in rundeck in a workflow step (not a node step)?

2.  I have a  groovy script:  how to use it in  a workflow step  , and it is possible to use the rundeck embeded groovy engine?

3. Is it possible to use grails directly?

**Comment by sjrd218** [comment]
You can write your workflow step plugin using Groovy. When you install the plugin, it will use the version of Groovy that is shipped with Rundeck.

Here's a template project to get your started: https://github.com/sjrd218/SampleGroovyWorkflowStep

**Comment by gaetanquentin** [comment]
> You can write your workflow step plugin using Groovy. When you install the plugin, it will use the version of Groovy that is shipped with Rundeck.
> 
> Here's a template project to get you started: https://github.com/sjrd218/SampleGroovyWorkflowStep

ok so there is no simple method to call external groovy script without developping a specific plugin...

**Comment by sjrd218** [comment]
That's correct.

**Comment by gschueler** [comment]
You can run any type of script as a Script Step, however you need to have the interpreter installed locally on the system that is the target of the step. If the job runs locally (no node dispatch), you need the interpreter installed locally, and if you want it to work on a remote node you need groovy installed on the remote node.
