### ISSUE TITLE
3.1 - Activity panel 

### ISSUE THREAD

**Issue by Ehoudry** [rundeck/rundeck#5197]
**Is your feature request related to a problem? Please describe.**
In Rundeck 3.1 Activity panel has changed. The column displaying the job metioned only the job name, missing the information of the group the job belongs to.
In the case where the same name is used mutltiple time across different groups it is impossible to make the difference between them in this report panel.

**Describe the solution you'd like**
It is important to retrieve the complete information about job name and group in this column just like it was in 3.0

**Comment by jessemarple** [comment]
@Ehoudry - there are a few activity tables in panels in use throughout rundeck. Would you send us a screen grab of the page with the panel/table to help narrow it down. thank you!

**Comment by Ehoudry** [comment]
![Capture d’écran 2019-09-26 à 08 38 32](https://user-images.githubusercontent.com/42180498/65664340-6db75580-e039-11e9-830b-790269e1a407.png)

**Comment by Ehoudry** [comment]
For the purpose I wrote tojobs : Reports/Integration/test and Reports/Production/test. After launching both of them, they appears in the "Activity for jobs" panel with no way to know the group from which they belong to. Same result when you choose "Activity" on the left side of the screen.

**Comment by Ehoudry** [comment]
Resolving this issue is mandatory for me in order to ugrade from 3.0 to 3.1. Do you plan to restore the old good way activities are reported ? Giving user the ability to configure what they want to see on a report could be another solution. Thanks, hope to ear from you soon :-)
Eric

**Comment by ahonor** [comment]
@Ehoudry it makes a lot of sense. That will need to be added to the next newer version of Rundeck
