### ISSUE TITLE
couldn't integrate with jenkins. 

### ISSUE THREAD

**Issue by slavhare** [rundeck/rundeck#5203]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [e.g. ubuntu 16.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by sjrd218** [comment]
@slavhare Looks like the details of the issue you're trying to report might not have made it. Can you use the template above to tell us the Rundeck version you are using, and how you are trying to integrate Jenkins. Any error logs or error screenshots would be very helpful. Thanks!
