### ISSUE TITLE
ACL for storage with deny using notBy only supports single group

### ISSUE THREAD

**Issue by pburm** [rundeck/rundeck#5206]
**Describe the bug**
When using a deny action for a storage path with notBy, the documentation examples show that multiple groups are supported, but only single group works. When using single group, that group is NOT denied, when using multiple groups, All groups ARE denied

**My Rundeck detail**

* Rundeck version: 3.1.1
* install type: war
* OS Name/version: ubuntu 16.04 (CF)
* DB Type/version: mssql

**To Reproduce**
1. create acl for a storage path using deny action e.g. keys/somepath/.*
2. use notBy and include 2 groups
3. log in with user that is in one of the groups
4. notice that user cannot see any keys in the keys/somepath location

**Expected behavior**
membership in any of the groups listed should prevent the deny

**Desktop (please complete the following information):**
 - OS: macOS 10.13.6
 - Browser chrome
 - Version 76

**Additional context**
example acl:

---
description: 'Deny wrong group'
context:
  application: 'rundeck'
for:
  storage:
     - match:
        path: 'keys/testpath/.*'
       deny: [create,update,read,delete]
notBy:
    group: ['group1','group2']

**Comment by pburm** [comment]
This may be more of a documentation issue, as using single string regex with the multiple groups works e.g. group: '(group1|group2)'

**Comment by jtobard** [comment]
@pburm actually the list `group: ['group1','group2']` means you need to have both groups to be excluded, users without group1 and group2 are going to be denied access to that storage, but users with only one of those groups and not the other are excluded

**Comment by joulaud** [comment]
Documentation should be improved on this. Indeed "notBy group" seems to work differently than e.g. "notBy username".

If I understand correctly (I did not test all the cases so do not believe me blindly and check yourself).

With a policy like this :
```
for:
  node:
    - deny: 'run'
      equals:
        rundeck_server: 'true'
notBy:
...
```

Deny run to all but the users present in both groupA *and* groupB. Users only in groupA or only in groupB will be effectively denied to run.
```
notBy:
  group:
     - groupA
     - groupB
```

Deny run to all but the users present in groupA *or* groupB :
```
notBy:
  group: 'groupA|groupB'
```
