### ISSUE TITLE
UI - Jobs Option - Enhancement - Radio and Checkbox

### ISSUE THREAD

**Issue by jumah35** [rundeck/rundeck#5209]
Hi,

It could be great to have two other input type : 

- a radio box :
![RD-Option-Radio](https://user-images.githubusercontent.com/49312201/64420694-21af6b80-d0a0-11e9-9a50-09a2c9c1ec87.png)

- a checkbox to validate or not a single option 
![RD-Option-Checkbox](https://user-images.githubusercontent.com/49312201/64420747-3db30d00-d0a0-11e9-8450-b132795a0c26.png)

Thank you 
Ju

**Comment by RayquazID** [comment]
Would like to See this
