### ISSUE TITLE
my job doesnot really work

### ISSUE THREAD

**Issue by zychappy** [rundeck/rundeck#5218]
my job doesnot really work
* Rundeck version: [ Rundeck 3.1.0-20190731]
* install type: [war]
* OS Name/version: [ubuntu 16.04]

the node and job are set up normally,
the job add an inline script like below:
`nohup ./myprogram &`
then run the job ,it show success,but myprogram does not run when I check in the node.

**Comment by MegaDrive68k** [comment]
Hi @zychappy 

Can you run your job on Debug mode (and share the output) to get more clues?

Kind regards!

**Comment by MegaDrive68k** [comment]
It works in this way:

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>85a20a50-33d6-4b3b-b853-b5d0229df57e</id>
    <loglevel>INFO</loglevel>
    <name>Nohup</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>nohup /home/user/script.sh &gt; /home/user/nohup.something</exec>
      </command>
    </sequence>
    <uuid>85a20a50-33d6-4b3b-b853-b5d0229df57e</uuid>
  </job>
</joblist>
```

Source: https://stackoverflow.com/a/30182887/10426011
