### ISSUE TITLE
NonZeroResultCode: Result code was 127

### ISSUE THREAD

**Issue by inphadalem** [rundeck/rundeck#5219]
**Describe the bug**
I'm trying to create simple 'Hello World' job in Rundeck. 
1. I have created .bat file as below, and save it on my local drive
@echo Hello All.
@pause
2. If I call this bat file from task scheduler its working fine
3. If I call same file from Rundeck , its giving me error as below:

13:45:54 | [workflow] Begin step: 1,NodeDispatch
-- | --
13:45:54 | 1: Workflow step executing: CommandItem{command=[2 words]}
13:45:54 | preparing for sequential execution on 1 nodes
13:45:54 | Executing command on node: d07def4f59be, NodeEntryImpl{tags=[], attributes={nodename=d07def4f59be, hostname=d07def4f59be, osVersion=3.10.0-1062.1.1.el7.x86_64, osFamily=unix, osArch=amd64, description=Rundeck server node, osName=Linux}, project='null'}
13:45:54 | [workflow] beginExecuteNodeStep(d07def4f59be): NodeDispatch: CommandItem{command=[2 words]}
13:45:54 | using charset: null
13:45:54 | Current OS is Linux
13:45:54 | Adding reference: ant.PropertyHelper
13:45:54 | Project base dir set to: /home/rundeck
13:45:54 | Setting environment variable: RD_JOB_ID=
13:45:54 | Setting environment variable: RD_JOB_USERNAME=inphadalem
13:45:54 | Setting environment variable: RD_NODE_HOSTNAME=
13:45:54 | Setting environment variable: RD_JOB_URL=http://rundeck.tetrapak.com/project/MadhuriProject/execution/follow/289
13:45:54 | Setting environment variable: RD_JOB_PROJECT=MadhuriProject
13:45:54 | Setting environment variable: RD_JOB_NAME=HelloWorld2
13:45:54 | Setting environment variable: RD_NODE_OS_ARCH=amd64
13:45:54 | Setting environment variable: RD_NODE_OS_VERSION=3.10.0-1062.1.1.el7.x86_64
13:45:54 | Setting environment variable: RD_NODE_NAME=
13:45:54 | Setting environment variable: RD_JOB_THREADCOUNT=1
13:45:54 | Setting environment variable: RD_JOB_RETRYATTEMPT=0
13:45:54 | Setting environment variable: RD_JOB_USER_NAME=inphadalem
13:45:54 | Setting environment variable: RD_JOB_LOGLEVEL=DEBUG
13:45:54 | Setting environment variable: RD_NODE_OS_NAME=Linux
13:45:54 | Setting environment variable: RD_JOB_SERVERUUID=a14bc3e6-75e8-4fe4-a90d-a16dcc976bf6
13:45:54 | Setting environment variable: RD_NODE_OS_FAMILY=unix
13:45:54 | Setting environment variable: RD_JOB_EXECID=289
13:45:54 | Setting environment variable: RD_NODE_USERNAME=
13:45:54 | Setting environment variable: RD_NODE_TAGS=
13:45:54 | Setting environment variable: RD_JOB_SERVERURL=http://rundeck.tetrapak.com/
13:45:54 | Setting environment variable: RD_JOB_EXECUTIONTYPE=user
13:45:54 | Setting environment variable: RD_JOB_WASRETRY=false
13:45:54 | Setting environment variable: RD_JOB_SUCCESSONEMPTYNODEFILTER=false
13:45:54 | Setting environment variable: RD_JOB_RETRYINITIALEXECID=0
13:45:54 | Setting environment variable: RD_NODE_DESCRIPTION=Rundeck server node
13:45:54 | Executing '/bin/sh' with arguments: '-c' 'cmd C:\Madhuri\HelloJobs\hello.bat'  The ' characters around the executable and arguments are not part of the command.
13:45:54 | Execute:Java13CommandLauncher: Executing '/bin/sh' with arguments: '-c' 'cmd C:\Madhuri\HelloJobs\hello.bat'  The ' characters around the executable and arguments are not part of the command.
13:45:54 | /bin/sh: cmd: command not found
13:45:55 | Setting project property: 1568103354642.node.d07def4f59be.LocalNodeExecutor.result -> 127
13:45:55 | Result: 127
13:45:55 | Failed: NonZeroResultCode: Result code was 127
13:45:55 | [workflow] finishExecuteNodeStep(d07def4f59be): NodeDispatch: NonZeroResultCode: Result code was 127
13:45:55 | 1: Workflow step finished, result: Dispatch failed on 1 nodes: [d07def4f59be: NonZeroResultCode: Result code was 127 + {dataContext=MultiDataContextImpl(map={ContextView(node:d07def4f59be)=BaseDataContext{{exec={exitCode=127}}}, ContextView(step:1, node:d07def4f59be)=BaseDataContext{{exec={exitCode=127}}}}, base=null)} ]
13:45:55 | [workflow] Finish step: 1,NodeDispatch

==============================================================
**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise

**Comment by MegaDrive68k** [comment]
Hi @inphadalem 

At the moment of edit your job, set "Invocation String" (under "Advanced" button)  to "cmd.exe" and "File Extension" to ".bat" and try again.

Hope it helps!

**Comment by inphadalem** [comment]
Hi, it has been resolved after adding target node properly. Thank you for your support.
