### ISSUE TITLE
Not able to select nodes by tag in 3.1.0

### ISSUE THREAD

**Issue by chad-barensfeld-exa** [rundeck/rundeck#5237]
**Describe the bug**
After upgrading from 3.0 to 3.1, job node execution selector to longer has the tags associated with the nodes. In 3.0 I could select a group of nodes based on tags, was this removed in 3.1 or is there a way to re-enable this? 

**My Rundeck detail**

* Rundeck version: 3.1.0
* install type: official docker
* OS Name/version: official docker
* DB Type/version: mysql

**To Reproduce**
1. Go to Job
2. Scroll down to 'Nodes'
4. Tags no longer a selector

**Expected behavior**
Node tags as selector when running a job

**Screenshots**

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Chrome
 - Version: Latest

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @chad-barensfeld-exa 

We'll follow your issue here: 

https://github.com/rundeck/rundeck/issues/5117

Regards!
