### ISSUE TITLE
An inline script job notification will attach the inline script

### ISSUE THREAD

**Issue by oj43085** [rundeck/rundeck#5242]
**Describe the bug**
Create a test job that executes an inline script and configure an email notification to be sent on success. 

The email will contain the inline script. 

But there is no option to attach inline script. 

**My Rundeck detail**

* Rundeck version: rundeck-3.1.0.20190731-3-src.rpm
* install type: RPM
* OS Name/version: CentOS Linux release 7.6.1810 (Core) 
* DB Type/version: Postgresql 

**To Reproduce**
1. Create a New Job
2. Add one workflow step Inline script. 

My case is print("Hello World")

3. Configuration notification to send on success to your mailbox.

4. Run the job

5. In your mailbox the inline script will be there.

**Expected behavior**
The inline script should not be attached. 

**Screenshots**

https://ibb.co/jzhhxdh

**Desktop (please complete the following information):**
 - OS: Windows 10 Home
 - Browser Chrome 
 - Version 77.0.3865.75 (Official Build) (64-bit)

**Additional context**

**Comment by MegaDrive68k** [comment]
Related: 

https://groups.google.com/forum/#!topic/rundeck-discuss/nLe3_2h9hkI

(As a workaround you can use E-mail templates).

Regards.
