### ISSUE TITLE
Node View: Node Filter Buttons for Tags Should Retain Case

### ISSUE THREAD

**Issue by dutchrapley** [rundeck/rundeck#5250]
**Describe the bug**
The node view provides convenient buttons to build node filters based on tags. The issue is that these node filter buttons upcase the tags, when in fact node filters are case sensitive. The upcase styling does not affect the tag filter that the button generates.

**My Rundeck detail**

* Rundeck version: 3.1.0
* install type: deb
* OS Name/version: ubuntu 18.04

**To Reproduce**
1. Create nodes with the same tag value, using different a different case on each one
2. See that multiple tag filter buttons are created, all looking exactly the same

**Expected behavior**
Tag filter buttons should retain original case.

**Screenshots**
![image](https://user-images.githubusercontent.com/25286/64883845-4bcbd500-d62e-11e9-8a19-d4f8b1247f8f.png)
![image (2)](https://user-images.githubusercontent.com/25286/64883895-61d99580-d62e-11e9-999c-1c654ba62a52.png)

**Comment by gaddman** [comment]
I'd prefer if tags filtered case-insensitively, ie your two examples were consolidated into a single 'DEV' tag which displayed nodes with the 'dev', 'DEV', and 'Dev' tags. But whichever choice is made, the the current interface is confusing and needs to change.

**Comment by gaddman** [comment]
Still an issue in version 3.3.9

**Comment by gaddman** [comment]
Fixed in v4.5.0 via #7768
