### ISSUE TITLE
Docker: Add environment variable to set admin credentials

### ISSUE THREAD

**Issue by xyker** [rundeck/rundeck#5257]
**Is your feature request related to a problem? Please describe.**
Currently the container gets deployed with default admin/admin credentials.  I believe there should be an environment variables similar to RUNDECK_DATABASE_USERNAME and RUNDECK_DATABASE_PASSWORD to set different usernames / passwords.

**Describe the solution you'd like**
Recommend creating a RUNDECK_ADMIN_USERNAME and RUNDECK_ADMIN_PASSWORD environmental variable.

**Comment by ltamaster** [comment]
Hi @xyker 

You can do this extending the base image and creating your own template 

Here you can find a similar example
https://github.com/rundeck/docker-zoo/tree/master/config

Luis

**Comment by Nkmol** [comment]
@ltamaster I might be missing this, but I cannot see anything related to settings these default credentials through my own image. Neither in the [base image](https://github.com/rundeck/rundeck/blob/master/docker/ubuntu-base/Dockerfile) nor in any of the [specialized ](images https://github.com/rundeck/rundeck/blob/master/docker/official/Dockerfile)

An equivalent question has been asked here https://github.com/rundeck/docker-zoo/issues/10

**Comment by bfreeds** [comment]
@Nkmol I'm wondering the same, how did you end up resolving this in your setup?

**Comment by bfreeds** [comment]
For anyone who may come by this issue - I believe mounting the `config/realm.properties` is the way to go.

**Comment by MegaDrive68k** [comment]
For future references [here](https://groups.google.com/g/rundeck-discuss/c/sya3vljcsco/m/_ZN71uJKAQAJ) you can find a way to do this. Greetings!
