### ISSUE TITLE
Systemctl does not stop all process in redhat

### ISSUE THREAD

**Issue by shaunakmandal86** [rundeck/rundeck#5268]
Hi all,

I am starting a service using systemctl ,but I am facing issue to stop the service in redhat system.

the service file I am creating :

[Unit]
Description=/home/agenttest
After=syslog.target

[Service]
ExecStart=/bin/bash /home/agenttest/service/test.sh
SuccessExitStatus=143
TimeoutStopSec=10
 KillMode=mixed

[Install]
WantedBy=multi-user.target

in test.sh I am using below command :

sudo /home/ec2-user/jdk1.8.0_211/jre/bin/java -jar /home/agenttest/service/agent.jar --spring.config.location=classpath:/test.properties,/home/agenttest/service/test.properties --server.port=8081

the service successfully started :
![test](https://user-images.githubusercontent.com/37165092/65117772-f4e84600-da07-11e9-8383-e55cb9c06c32.png)

But when I stop the service using systemctl stop <service_name> command ,all processes are not getting stopped.

I am seeing the issue in redhat only.For other Linux system it is working fine.

Also I have used the KillMode=mixed to other properties like control-group, process, mixed not noting work properly.

Please help.

Thanks in advance!

**Comment by MegaDrive68k** [comment]
Hi @shaunakmandal86 

Can you post the service.log content to get some clue about that?

Kind regards.

**Comment by shaunakmandal86** [comment]
When I am doing journalctl -u <service_name>

I am getting bellow log:

Oct 01 09:31:35 ip-100-65-1-211.ec2-internal systemd[1]: Started /home/agenttest.
Oct 01 09:31:35 ip-100-65-1-211.ec2-internal sudo[15517]: root : TTY=unknown ; PWD=/ ; USER=root ; COMMAND=/home/ec2-user/jdk1.8.0_211/jre/bin/java ->
Oct 01 09:31:35 ip-100-65-1-211.ec2-internal sudo[15517]: pam_unix(sudo:session): session opened for user root by (uid=0)
Oct 01 09:31:42 ip-100-65-1-211.ec2-internal bash[15516]:   .   ____          _            __ _ _
Oct 01 09:31:42 ip-100-65-1-211.ec2-internal bash[15516]:  /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
Oct 01 09:31:42 ip-100-65-1-211.ec2-internal bash[15516]: ( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
Oct 01 09:31:42 ip-100-65-1-211.ec2-internal bash[15516]:  \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
Oct 01 09:31:42 ip-100-65-1-211.ec2-internal bash[15516]:   '  |____| .__|_| |_|_| |_\__, | / / / /
Oct 01 09:31:42 ip-100-65-1-211.ec2-internal bash[15516]:  =========|_|==============|___/=/_/_/_/
Oct 01 09:31:42 ip-100-65-1-211.ec2-internal bash[15516]:  :: Spring Boot ::        (v2.1.2.RELEASE)
Oct 01 09:31:42 ip-100-65-1-211.ec2-internal bash[15516]: 09:31:42.958 [main] INFO  c.f.c.agent.main.AgentApplication - Starting AgentApplication v0.>
Oct 01 09:31:42 ip-100-65-1-211.ec2-internal bash[15516]: 09:31:42.961 [main] INFO  c.f.c.agent.main.AgentApplication - No active profile set, fallin>
Oct 01 09:31:53 ip-100-65-1-211.ec2-internal bash[15516]: 09:31:53.621 [main] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecke>
Oct 01 09:31:56 ip-100-65-1-211.ec2-internal bash[15516]: 09:31:56.240 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat initialized with port(s>
Oct 01 09:31:56 ip-100-65-1-211.ec2-internal bash[15516]: 09:31:56.598 [main] INFO  o.a.catalina.core.StandardService - Starting service [Tomcat]
Oct 01 09:31:56 ip-100-65-1-211.ec2-internal bash[15516]: 09:31:56.598 [main] INFO  o.a.catalina.core.StandardEngine - Starting Servlet engine: [Apac>
Oct 01 09:31:56 ip-100-65-1-211.ec2-internal bash[15516]: 09:31:56.663 [main] INFO  o.a.c.core.AprLifecycleListener - The APR based Apache Tomcat Nat>
Oct 01 09:31:57 ip-100-65-1-211.ec2-internal bash[15516]: 09:31:57.392 [main] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initializing Spring embedded>
Oct 01 09:31:57 ip-100-65-1-211.ec2-internal bash[15516]: 09:31:57.392 [main] INFO  o.s.web.context.ContextLoader - Root WebApplicationContext: initi>
Oct 01 09:31:59 ip-100-65-1-211.ec2-internal bash[15516]: 09:31:59.905 [MLog-Init-Reporter] INFO  com.mchange.v2.log.MLog - MLog clients using slf4j >
Oct 01 09:32:00 ip-100-65-1-211.ec2-internal bash[15516]: 09:32:00.188 [main] INFO  com.mchange.v2.c3p0.C3P0Registry - Initializing c3p0-0.9.5 [built>
Oct 01 09:32:05 ip-100-65-1-211.ec2-internal bash[15516]: 09:32:05.801 [main] INFO  o.s.s.c.ThreadPoolTaskExecutor - Initializing ExecutorService 'ap>
Oct 01 09:32:08 ip-100-65-1-211.ec2-internal bash[15516]: 09:32:08.370 [main] INFO  o.s.s.c.ThreadPoolTaskScheduler - Initializing ExecutorService 't>
Oct 01 09:32:08 ip-100-65-1-211.ec2-internal bash[15516]: 09:32:08.674 [main] INFO  o.s.b.a.e.web.EndpointLinksResolver - Exposing 16 endpoint(s) ben>
Oct 01 09:32:11 ip-100-65-1-211.ec2-internal bash[15516]: 09:32:11.479 [main] INFO  o.s.b.w.e.tomcat.TomcatWebServer - Tomcat started on port(s): 808>
Oct 01 09:32:11 ip-100-65-1-211.ec2-internal bash[15516]: 09:32:11.482 [main] INFO  c.f.c.agent.main.AgentApplication - Started AgentApplication in 3>
Oct 01 09:32:41 ip-100-65-1-211.ec2-internal bash[15516]: 09:32:41.050 [https-jsse-nio-8082-exec-4] INFO  o.a.c.c.C.[Tomcat].[localhost].[/] - Initia>
Oct 01 09:32:41 ip-100-65-1-211.ec2-internal bash[15516]: 09:32:41.050 [https-jsse-nio-8082-exec-4] INFO  o.s.web.servlet.DispatcherServlet - Initial>
Oct 01 09:32:41 ip-100-65-1-211.ec2-internal bash[15516]: 09:32:41.067 [https-jsse-nio-8082-exec-4] INFO  o.s.web.servlet.DispatcherServlet - Complet>
Oct 01 09:36:11 ip-100-65-1-211.ec2-internal systemd[1]: Stopping /home/agenttest...
Oct 01 09:36:11 ip-100-65-1-211.ec2-internal systemd[1]: Stopped /home/agenttest.




But the process is still running on port
