### ISSUE TITLE
Allow groovy script execution directly, like in jenkins

### ISSUE THREAD

**Issue by gaetanquentin** [rundeck/rundeck#5279]
**Describe the solution you'd like**
It would be great to execute groovy scripts directly in workflow jobs. As Rundeck is a groovy application, it would be useful to be able to write  groovy scripts and access rundeck engine easily, like in jenkins. Currently, the only way to add groovy is to create a plugin, which is too specific and need ide and other complexity.

**Describe alternatives you've considered**
plugins are too complicated and specific: one plugin for one script?? No way.

**Comment by sjrd218** [comment]
@gaetanquentin Can you try this plugin and tell me if it's what you're looking for: https://github.com/sjrd218/groovy-script

**Comment by gaetanquentin** [comment]
hi @sjrd218 thanks a lot. i have tried it with 3.1.0 but it looks like the step is not called. 

Will try again on monday.

**Comment by gaetanquentin** [comment]
so after verification, the step is not visible on the node output, i need to click on the log output to see its results.

**Comment by sjrd218** [comment]
@gaetanquentin When convenient could you send me a screen shot of what you're seeing?

**Comment by gschueler** [comment]
One reason we don't do this already, is that allowing arbitrary groovy scripts within the Rundeck server JVM is thoroughly insecure.  e.g. the groovy script `System.exit(1)` will shut down the server.  See the "security warning" on this page: <https://wiki.jenkins.io/display/JENKINS/Jenkins+Script+Console>.

Jenkins has a [script security](https://plugins.jenkins.io/script-security) plugin that uses a sandbox technique to whitelist/blacklist certain methods from being called.  Perhaps a potential rundeck plugin could use that kind of technique, or even build off the jenkins plugin code.

**Be aware that providing carte blanche script execution within the JVM is a huge security hole.**

**Comment by gaetanquentin** [comment]
> One reason we don't do this already, is that allowing arbitrary groovy scripts within the Rundeck server JVM is thoroughly insecure. e.g. the groovy script `System.exit(1)` will shut down the server. See the "security warning" on this page: https://wiki.jenkins.io/display/JENKINS/Jenkins+Script+Console.
> 
> Jenkins has a [script security](https://plugins.jenkins.io/script-security) plugin that uses a sandbox technique to whitelist/blacklist certain methods from being called. Perhaps a potential rundeck plugin could use that kind of technique, or even build off the jenkins plugin code.
> 
> **Be aware that providing carte blanche script execution within the JVM is a huge security hole.**

I understand.
However it would be a shame not to benefit from the power of groovy and the rundeck engine.

**Comment by gaetanquentin** [comment]
> @gaetanquentin When convenient could you send me a screen shot of what you're seeing?
Definition:
![image](https://user-images.githubusercontent.com/5774881/65408015-7bc06880-dde4-11e9-8b5e-d85e2cdd0762.png)

Node output: (the groovy step is not listed)
![image](https://user-images.githubusercontent.com/5774881/65408084-9db9eb00-dde4-11e9-85d3-1e45c9109d38.png)

Log output: the groovy step is shown:
![image](https://user-images.githubusercontent.com/5774881/65408152-c8a43f00-dde4-11e9-871d-f701d0ca9bc3.png)

**Comment by sjrd218** [comment]
@gaetanquentin The reason it wasn't appearing is because it is a workflow step plugin. I have added a node step plugin to the repo posted above. If you pull the new version and build, you'll have both a node step and a workflow step plugin that can execute groovy scripts.

**Comment by gaetanquentin** [comment]
@sjrd218 ok it appears now thanks

it is nomal that configuration map is empty?

```
def dataContext =  context.getDataContext();

println "Context:"
dataContext.each { entry -> println "$entry.key : $entry.value" }

println "Configuration:"
configuration.each { entry -> println "$entry.key : $entry.value" }
```

**Comment by sjrd218** [comment]
That's normal. There's probably no reason for that variable in this plugin. I'll remove it.

**Comment by gaetanquentin** [comment]
is there a way to get data.* variables created by "key value data"  log filters?
