### ISSUE TITLE
Rundeck Hashicorp vault SSL

### ISSUE THREAD

**Issue by wggit** [rundeck/rundeck#5283]
Hello,

I am using Rundeck 3.0.20-20190408 and Hashicorp vault Vault 1.0.2.
I have Rundeck accessing Vault on http working for a while.

When enabled https on Vault, Rundeck is not able to connect to vault.

Here is vault configuration:

cat config.json
{
"listener": [{
"tcp": {
"address" : "0.0.0.0:7051",
"tls_disable" : 0,
"tls_cert_file" : "/etc/vault/hostname.crt",
"tls_key_file" : "/etc/vault/hostname.key"
}
}],
"api_addr": "https://hostname:7051",
"storage": {
"file": {
"path" : "path/vault/vault-data"
}
},
"max_lease_ttl": "10h",
"default_lease_ttl": "10h",
"ui":true,
}

Rundeck configuration: rundeck-config.properties

rundeck.storage.provider.1.type=vault-storage
rundeck.storage.provider.1.path=keys
rundeck.storage.provider.1.config.prefix=rundeck
rundeck.storage.provider.1.config.secretBackend=secret
rundeck.storage.provider.1.config.address=https://vault_hostname:7051
rundeck.storage.provider.1.config.token=token_value

Error in Rundeck log: 

Encountered error while writing data to Vault com.bettercloud.vault.rest.RestException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

Vault error in server log :
http: TLS handshake error from rundeck_host_ip:55068: remote error: tls: unknown certificate

If any one can help.
Thank you

**Comment by MegaDrive68k** [comment]
Hi @wggit 

Maybe you need to configure correctly your Keystore/Trustore

Please take a look:

https://github.com/rundeck-plugins/rundeck-ec2-nodes-plugin/issues/75

Kind regards.

**Comment by wggit** [comment]
Thank you let me give a try.

**Comment by wggit** [comment]
Thank you I tried couple of things but gives error
http: TLS handshake error from rundeck_host_ip:55068: remote error: tls: unknown certificate

**Comment by wggit** [comment]
https://github.com/hashicorp/vault/issues/7523 - issue fixed
