### ISSUE TITLE
Flag to Disable Community News is not working in 3.x 

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#5286]
**Describe the bug**
Flag to Disable _Community News_ is not working as described in #4633 -> #4661  

**My Rundeck detail**

* Rundeck version: 3.x ( 3.1.0 , 3.1.1 SNAP ) 
* install type: any

**To Reproduce**
1. Add `rundeck.communityNews.disabled = 'true'` to `rundeck-config.properties`
2. Restart Rundeck
3. `Community News` is present

**Expected behavior**
`rundeck.communityNews.disabled = 'true'`  should disable (hide) `Community News`

**Screenshots**

- [ ] rundeck-config.properties
![image](https://user-images.githubusercontent.com/31705339/65455289-4edc7780-de1d-11e9-9951-0de0396cdbcc.png)

- [ ] Community News is enabled
![image](https://user-images.githubusercontent.com/31705339/65455178-13da4400-de1d-11e9-8333-4430f8888e78.png)

**Comment by sjrd218** [comment]
Setting the `rundeck.communityNews.disabled = 'true'` is not designed to hide the community news sidebar menu. 

If community news is `disable=true` the user is sent to the Rundeck website to get the community news. If it is not set or set to `disabled=false` then the user will see a list of community news items inside the app.
