### ISSUE TITLE
HOW TO KILLING OR ABORTING A JOB USING AN API

### ISSUE THREAD

**Issue by Muriloalgar2019** [rundeck/rundeck#5291]
I would like to know if I can STOP or ABORT (KILL JOB) using an API on Rundeck version 2.5 ... I can't find this API anywhere. Can anyone help me?

**Comment by MegaDrive68k** [comment]
Hi @Muriloalgar2019,

Check this:

https://docs.rundeck.com/docs/api/#aborting-executions

Also, you can kill the job using RD CLI, check this (executions -> kill):

https://rundeck.github.io/rundeck-cli/commands/

Greetings!
