### ISSUE TITLE
filtering hosts by tags improvement 

### ISSUE THREAD

**Issue by tsolodov** [rundeck/rundeck#5294]
**Is your feature request related to a problem? Please describe.**
I have not found a way how to filer nodes with logic tagA AND tagB:
Scenario:
host A: tags [tagA,tagB]
host B: tags [tagA]
host C: tags [tagB]

How to filter hosts with tagA AND tagB?

**Describe the solution you'd like**
tags: tagA & tags: tagB should show **host A** only. Currently rundeck uses OR logic for selecting hosts.

**Describe alternatives you've considered**
N/A

**Comment by niall-munnelly** [comment]
Does this no longer work?

https://docs.rundeck.com/docs/manual/node-filters.html

a +-separated list of values to AND together
e.g. a+b (match node with both tags a and b)

Or are you describing a different need?

**Comment by tsolodov** [comment]
my bad. Thank you!
