### ISSUE TITLE
can't rename project name

### ISSUE THREAD

**Issue by dadayoo** [rundeck/rundeck#5295]
Hello, I'm running with Rundeck 3.1.1
recently i want to rename project
but...only thing i can do is modify project Lable and Description, can't find way to rename it
am i missing something?
thanks!

**Comment by MegaDrive68k** [comment]
Hi @dadayoo 

That's a good enhancement requested before. Right now if you really want to change the project name a good alternative is to create a new project and import your jobs to your new project.

We follow this request from here: https://github.com/rundeck/rundeck/issues/579

Thanks for your feedback!

Regards!

**Comment by dadayoo** [comment]
> Hi @dadayoo
> 
> That's a good enhancement requested before. Right now if you really want to change the project name a good alternative is to create a new project and import your jobs to your new project.
> 
> We follow this request from here: #579
> 
> Thanks for your feedback!
> 
> Regards!

thanks for your relpy～ that's good way
i have another question which is how to rename or delete jobgroup under project , i did't find button
😆

**Comment by niall-munnelly** [comment]
The only way I’ve been able to effect this is using `rd:`

1. List the  jobs to a file
2. Edit that file with sed, awk, etc
3. Delete the jobs on the Rundeck server
4. Upload the updated job definitions.

Once you get used it and write some scripts, it’s not too bad, but bulk-editing the job groups in the UI would be pretty awesome.

**Comment by dadayoo** [comment]
> Hi @dadayoo
> 
> That's a good enhancement requested before. Right now if you really want to change the project name a good alternative is to create a new project and import your jobs to your new project.
> 
> We follow this request from here: #579
> 
> Thanks for your feedback!
> 
> Regards!

hi,  i have another question which is how to rename or delete jobgroup under project , i did't find button , thanks!
