### ISSUE TITLE
Option Validation with URLs not working

### ISSUE THREAD

**Issue by ahamilto** [rundeck/rundeck#5314]
We are seeing the exact same behavior as #5030 but in a newer version of Rundeck

**My Rundeck detail**

* Rundeck version: 3.1.2.20190927
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: postgres

**To Reproduce**
    Create a job with an option using Remote URL
    Restrict using Enforced from Allowed Values
    Required yes
    Add any step.
    Save the job.
    Run the job selecting any value from the list of options.

**Expected behavior**
The job runs successfully

**Screenshots**
See attached: Option option_name value: /mnt/share/NodalSuite/nightly_qa_deployments/QA13.json was not in the allowed values: [] 

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version 68.0.2

**Context
We saw the same bug in 3.1.0.20190731-3 as well.

**Comment by ahamilto** [comment]
![rundeck-option-validation-failure](https://user-images.githubusercontent.com/69139/65900361-daa55500-e383-11e9-84d2-283acecf0805.png)

**Comment by MegaDrive68k** [comment]
I used this Job Definition using httpbin.org:

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option enforcedvalues='true' name='myopt' required='true' valuesUrl='http://httpbin.org/ip' />
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description>Issue 5314 job.</description>
    <executionEnabled>true</executionEnabled>
    <id>7d1f8787-fe67-470a-a048-5a1e43255142</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo ${option.myopt}</exec>
      </command>
    </sequence>
    <uuid>7d1f8787-fe67-470a-a048-5a1e43255142</uuid>
  </job>
</joblist>
```

On 3.0.26:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/65906663-52ca4580-e399-11e9-8433-79414d4282ea.png)

On 3.1.2:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/65906682-56f66300-e399-11e9-9596-5801c4ca4bfa.png)

Related: https://github.com/rundeck/rundeck/issues/5120

**Comment by dnut** [comment]
Reproduced with 3.1.2-20190927 

This is a pretty serious problem since now half of our jobs are broken and most people at our organization do not have permission to modify them.
