### ISSUE TITLE
Job not failing after processing Error Handler

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/rundeck#5318]
# Describe the bug
Rundeck doesn't give status failed when I run a Job using ErrorHandler and Run remaining steps on workflow.

# My Rundeck detail

* Rundeck version: 3.1.2
* install type: WAR
* OS Name/version: CentOS 7
* DB Type/version: H2

# To Reproduce
Set up a Job with the following configuration:

**Workflow**
If a step fails: **Run remaining steps before failing.**

**Step 1**
Command: **exit 1**

**ErrorHandler (Step 1)**
Command: **echo Running ErrorHandler**

**Step 2**
Command: **Running Step 2**

# Expected behaviour
Fail Status at the end of the Execution

# Screenshots
### Normal Behaviour
![NormalJob](https://user-images.githubusercontent.com/11720535/65915027-ebb48d00-e3a8-11e9-8945-ff47c6010d6b.png)
-------------------------------------------------------------
### Bug
![BugJob](https://user-images.githubusercontent.com/11720535/65915026-e9eac980-e3a8-11e9-9adc-9316c7fc4882.png)

# Desktop (please complete the following information):
 - OS: Windows 10 Home x64, Build 1903
 - Browser: Opera GX
 - Version: LVL1 (core: 63.0.3368.55666)

# Additional context
[NormalJobBehaviour.zip](https://github.com/rundeck/rundeck/files/3673345/NormalJobBehaviour.zip)
[BugJob.zip](https://github.com/rundeck/rundeck/files/3673346/BugJob.zip)

**Comment by jtobard** [comment]
This is the expected behavior, you can check the documentation: https://docs.rundeck.com/docs/manual/job-workflows.html#error-handlers
