### ISSUE TITLE
The log output execution is overlapped and scrollbars disappear

### ISSUE THREAD

**Issue by luisrivas35** [rundeck/rundeck#5320]
**Describe the bug**
When you run a job, the log output execution of the job is altered and overlapped and the horizontal scrollbars disappear

**My Rundeck detail**

* Rundeck version: 3.0.26
* install type: War
* OS Name/Version: RHEL 7.6
* DB Type/version: ORACLE

**To Reproduce**

Steps to reproduce the behaviour:
1. Go to job execution section of Rundeck
2. Click on follow execution box and choose "Log Output"
3. Click on "Run job now"
4. See the error. The execution result is overlapped

**Expected behaviour**
The job output can be read as normal and you can use the scrollbars
![image001](https://user-images.githubusercontent.com/43067588/65937795-52f92e00-e3f7-11e9-8ac4-ab64455feaed.png)

**Screenshots**
image1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome 
 - Version 77.0.3865.90

**Comment by jessemarple** [comment]
In order to test this, please load the following Job definition YAML.

Please note you will need to change the file extension from .txt to .dtd
[very_long_line copy.txt](https://github.com/rundeck/rundeck/files/3740492/very_long_line.copy.txt)
