### ISSUE TITLE
SSO and SAML supported in community version

### ISSUE THREAD

**Issue by wggit** [rundeck/rundeck#5321]
Does latest Rundeck community version supports SAML and SSO integration?

Thank you.

**Comment by MegaDrive68k** [comment]
Hi @wggit 

SSO is only Enterprise Feature:

https://docs.rundeck.com/docs/administration/security/single-sign-on.html

For Community, you can use some authentication protocol like oauth2 in front of a proxy (like Nginx) to redirect to Rundeck instance.

Regards.

**Comment by flypenguin** [comment]
https://sso.tax ... :/
