### ISSUE TITLE
Turn off script details in email notification

### ISSUE THREAD

**Issue by eroji** [rundeck/rundeck#5335]
I have jobs in Rundeck 3.1.2-20190927 that have scripts embedded. With the email notification turned on, it's showing the entire content of the script in the details section of the notification. There does not seem to have any options to turn this off.

**Comment by MegaDrive68k** [comment]
Hi @eroji 

You can use email templates for that, check this thread please:

https://groups.google.com/forum/#!topic/rundeck-discuss/nLe3_2h9hkI

We'll follow the issue from here:

https://github.com/rundeck/rundeck/issues/5242

Best regards and thanks for your feedback!
