### ISSUE TITLE
Notification URL token expansion rendering issue

### ISSUE THREAD

**Issue by kaminek** [rundeck/rundeck#5337]
**Describe the bug**
Job related variable (token) not rendered.

**My Rundeck detail**

* Rundeck version: [ v3.0.12-0-g581db52 ]
* install type:  [deb]
* OS Name/version: [18.04.2]
* DB Type/version: [ mysql ]

**To Reproduce**
1. Install  [JSON Webhook POST](https://github.com/tinoji/rundeck-json-webhook-plugin)
2. Go to job notification
3. Enable and fill `JSON Webhook POST Webhook in the JSON format` with the url:
```
http://localhost:5000/notification?id=${job.execid}&exectype=${job.executionType}&name=${job.name}&group=${job.description}&project=${job.project}&user=${execution.user}&trigger=${notification.trigger}
```

**Expected behavior**
Rendering job variables context properly

**Screenshots**
```
127.0.0.1 - - [03/Oct/2019 14:43:13] "POST /notification?id=291&exectype=user&name=test_notifs&group=${job.description}&project=CRON&user=${execution.user}&trigger=${notification.trigger} HTTP/1.1" 200 -
```

**Comment by jessemarple** [comment]
Please follow up with the plugin author.
