### ISSUE TITLE
Cannot persist the whole contents of /home/rundeck/server/config when running Rundeck as a docker container

### ISSUE THREAD

**Issue by diegocejas** [rundeck/rundeck#5344]
Hi, I'm trying to run a Rundeck as a docker container with Ansible and I'm not able to persist all the files that are created inside **/home/rundeck/server/config**. Some permissions issues are preventing files like "realm.properties" (among others)  from being created when the container is executed for the first time and I cannot find any way to fix it other than creating the container without any mounted volumes, copying the config files and then destroying the current container, copying the config files to my host and recreating the container with the config folder mounted to that folder inside  my host.

I tried by modifying the permissions on the host side by allowing user/group/all with rwx permissions at every level of "/srv/rundeck/server/config" but that doesn't help either.

This is the task in my playbook calling the docker_container module (I get the same behavior if I just run "docker run.... -v  /srv/rundeck/server/config:/home/rundeck/server/config....)
What am I doing wrong? Is there any existing proper way for persisting the "config" folder when running Rundeck as a docker container?

Critical values have been replaced with XXXXXXXX:

- name:  Create Rundeck docker container
      tags: 
        - rundeck
      docker_container:
        name: rundeck
        image: rundeck/rundeck:SNAPSHOT
        restart_policy: always
        state: started
        recreate: yes
        ports: 
         - "4440:4440"
        env:
          RUNDECK_GRAILS_URL                    : XXXXXXXXXXX
          RUNDECK_DATABASE_URL               : XXXXXXXXXX
          RUNDECK_DATABASE_DRIVER        : XXXXXXXXXXXXX
          RUNDECK_DATABASE_USERNAME : XXXXXXXXXXX
          RUNDECK_DATABASE_PASSWORD : XXXXXXXXXXXXXX
         volumes:
             -  /srv/rundeck/server/config:/home/rundeck/server/config

**My Rundeck detail**

* Rundeck version: rundeck/rundeck:SNAPSHOT
* install type: docker container
* OS Name/version: Ubuntu 16.04.6 LTS (EC2 instance on AWS)
* DB Type/version: I'm using MariaDB on RDS in AWS

**To Reproduce**
Just try to use rundeck/rundeck:SNAPSHOT with "docker run" mounting any folder of your host  to /home/rundeck/server/config inside the container.
Afterwards, try to login in the GUI with the default admin/admin as user/password. You will notice that the credentials won't be accepted at all. It seems like the user is not created when the container is created due to this mounting issue.

**Expected behavior**
All the configuration files should be created automatically at first container creation.

**Comment by ProTip** [comment]
Hello, this has been open for quite some time without anyone able to reproduce or further reports. Please open a new issue if this issue persists in the latest Rundeck release.

**Comment by diegocejas** [comment]
7 months and no replies?

**Comment by rdehouss** [comment]
I'm experiencing the exact same issue.
When mounting a host directory to `/home/rundeck/server/config`, it "only" creates the following files:
`artifact-repositories.yaml  jaas-loginmodule.conf       log4j2.properties           rundeck-config.properties`
When not mounting, it has the following:
`artifact-repositories.yaml  jaas-loginmodule.conf  log4j2.properties  realm.properties  rundeck-config.properties  ssl.properties`
with `realm.properties` and `ssl.properties` in 775

And then, like the OP mentioned, it starts but you cannot authenticate (which is normal since 2 files are missing, including the one that contains the credentials...)

I don't understand why

**Comment by smacz42** [comment]
I have been able to reproduce on version 3.2.9. @ProTip, can you please let me know if you would prefer me to copy @diegocejas 's bug report into a new issue, or reopen this bug report?

**Comment by smacz42** [comment]
Opened the above since this impacted even more files in other directories.
