### ISSUE TITLE
SSH to solaris server fails on key size

### ISSUE THREAD

**Issue by RogEnk** [rundeck/rundeck#5355]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: RUNDECK 3.1.0-20190731
* install type: (rpm,deb,war,launcher?) RPM
* OS Name/version: Oracle Linux 7.3
* DB Type/version: Postgres

**Expected Behavior**
Execute remote commands via SSH

**Actual Behavior**
Failed: SSHProtocolFailure: Session.connect: java.security.InvalidAlgorithmParameterException: DH key size must be multiple of 64, and can only range from 512 to 8192 (inclusive). The specific key size 2047 is not supported

**How to Reproduce**
Attempt to connect to any pre Solaris 11 host

**Rundeck V2.x workaround**:
Replace jsch-0.1.55.jar with jsch-0.1.53.jar

**Comment by RogEnk** [comment]
Would really appreciate if anyone could provide some guidance on how I can work around this issue please, I have 1,200 Solaris systems to look after, and upgrading is unfortunately out of the question.

**Comment by ahonor** [comment]
@RogEnk You'll probably be better off using openssh directly for those nodes. You could try this: https://github.com/rundeck-plugins/openssh-node-execution which wraps SSH CLI.
Alternatively, you could use https://docs.rundeck.com/docs/administration/projects/node-execution/script.html#custom-command-and-script-execution-with-the-script-plugin

**Comment by RogEnk** [comment]
@ahonor that worked perfectly, went with the openssh option after installing sshpass.
Thank you!

**Comment by ahonor** [comment]
@RogEnk glad it worked well :)
