### ISSUE TITLE
Passing multiple arguments to job via api

### ISSUE THREAD

**Issue by wep-p** [rundeck/rundeck#5356]
**Describe the bug**
When I want to pass option values to a rundeck job, it seem like only the first query argument is passed to rundeck. In my case the auth token and an argument for an option field. 

The api call works perfectly fine if I use a curl command like this: 

`curl -X POST -H 'X-Rundeck-Auth-Token: tOkenId' https://rundeckserver.de/api/33/job/*job_id/run?option.hosts=server%2Ede`

or

`curl -X POST --data-urlencode "argString=-hosts server.de" https://rundeckserver.de/api/33/job/*job_id/run?authtoken=tOkenId`

But as I´m intending to use the webhook function in Bitbucket to automatically call a job after a merge, I need an URL call instead of a curl command. 

`https://rundeckserver.de/api/33/job/*job_id/run?authtoken=tOkenId&option.hosts=server%2Ede`

I tried serveral variations, but it only triggers the job without passing the option. If I pass the option first and the auth token second, it shows error code='unauthorized'. 

**My Rundeck detail**

* Rundeck version:  Rundeck 3.1.2-20190927 - mozzarella stick plum pushpin 2019-09-27 
* install type: war
* OS Name/version: SLES12 SP2
* DB Type/version: postgres

**Expected behavior**
Pass multiple parameter to rundeck jobs via api

**Comment by MegaDrive68k** [comment]
Hi @wep-p 

Check this comment:

https://github.com/rundeck/rundeck/issues/1176#issuecomment-248853675

Hope it helps!

**Comment by wep-p** [comment]
Hi @MegaDrive68k 
thx for the quick response. It seems that it is not possible to send POST parameters via URL request.
