### ISSUE TITLE
"Run this job again with the same options" does not run the job again with the same options.

### ISSUE THREAD

**Issue by nemoo** [rundeck/rundeck#5368]
Execution > Run Again: caption text: "Run this job again with the same options" does not run the job again with the same options.

* Rundeck version: Rundeck 3.1.0-20190731 
* install type: docker image rundeck/rundeck:3.1.0
* OS Name/version: ?
* DB Type/version:  postgres

**To Reproduce**
- Create a job with no options
- Trigger the job via an api call to rundeck. In the call, set option "foo" to value "bar".
- Open execution details: https://rundeck.acme.com/project/xyz/execution/show/123
- Observe that rundeck displays that the job was executed with option "foo" set to value "bar".
- Observe that rundeck displays as hover text of the Run Again button:  "Run this job again with the same options".
- Click on "Run Again" >  "Run Job Now"

**Actual behaviour**
The job is run again **without any** options.

**Expected behavior**
The job is run again with the option "foo" set to value "bar".

**Comment by MegaDrive68k** [comment]
Hi @nemoo 

I try to reproduce (tested with WAR and Docker Image) and the options keep before use "Run Again" > "Run Job Now".

![Screenshot_1](https://user-images.githubusercontent.com/51376003/66602017-96823380-eb7f-11e9-9892-6fa704751c39.png)

Maybe I missed any detail to reproduce your issue?

Thanks!

**Comment by nemoo** [comment]
I have more details now. 
The options are kept if the options are configured explicitly for the job.
The options are not kept if they were provided by the system that triggered the job but not configured explicitly in the job.

So I understand now why the options not have been used for the next run in my case.

This behaviour is ok for me, it just would have helped me if it was explicitly stated. Maybe we can tell the user about it in a modified popup text: 
Instead of "Run this job again with the same options" => "Run this job again. Pre-fill configured job options."

**Comment by ProTip** [comment]
Hi @nemoo ,

I haven't been able to reproduce this myself. Would you be able to update the reproduction steps in the issue template with the exact steps required to reproduce and attach a sample job if available?

Thanks!

**Comment by nemoo** [comment]
I updated the original description. Hope it is clearer now. As I said in my last comment, a more descriptive hover message on the 'Run Again' button would probably be sufficient to reduce future confusion.

**Comment by MegaDrive68k** [comment]
Reproduced.

With this job definition (without options):

```
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>269cbab5-3fe4-4997-bed9-217d6104c767</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "hi"</exec>
      </command>
    </sequence>
    <uuid>269cbab5-3fe4-4997-bed9-217d6104c767</uuid>
  </job>
</joblist>
```

And this API Call:

```
curl --location --request POST "http://localhost:4440/api/32/job/269cbab5-3fe4-4997-bed9-217d6104c767/run" \
  --header "Accept: application/json" \
  --header "X-Rundeck-Auth-Token: u9ZFFw00QTNVNnoomVxihErZopQSf6Np" \
  --header "Content-Type: application/json" \
  --data "{\"argString\":\"-arg1 val1 \"}" \
```

Result:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/66773127-bc1b7f80-ee94-11e9-915c-4d2a4ec2cdad.png)

Maybe need some option validation based on Jobs to avoid this.

Thanks @nemoo and @ProTip

**Comment by ProTip** [comment]
This _is_ curious. I'm not sure if passing in extra job options is a feature or undefined behaviour..

The, without looking at the code, "Run Again" probably has no concept of passing those extra options back through to the API.

**Comment by jtobard** [comment]
Checking this, is the right behavior, the run job again filling the options but in this case the job has no options to fill. The `argString` parameter aren't really options, just a hackish way to create one use only options.

The proper way to do this is to create hidden options on the job.

Using hidden options you get the same behavior, you can't set them using the GUI but you can change the default value via API.

Taking the example of @MegaDrive68k :

```xml
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='arg1' value='no'>
          <hidden>true</hidden>
        </option>
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>269cbab5-3fe4-4997-bed9-217d6104c767</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "hi"</exec>
      </command>
    </sequence>
    <uuid>269cbab5-3fe4-4997-bed9-217d6104c767</uuid>
  </job>
</joblist>
```
adding
```xml
<context>
      <options preserveOrder='true'>
        <option name='arg1' value='no'>
          <hidden>true</hidden>
        </option>
      </options>
    </context>
```

You can retry and get the option properly filled.
