### ISSUE TITLE
ERROR 405 method not allowed rundeck

### ISSUE THREAD

**Issue by Muriloalgar2019** [rundeck/rundeck#5372]
Hello guys!!

I'm trying to execute an API on Rundeck version 32. But when I start the link the ERROR 405 appears.
I know that it's about configuration, but I can't find the solution anywhere. The number server is OK, the port is OK and I have already configurated the authtoken.

Can anyone please help me?? 
(I'm sorry about my english, I'm native brazilian)

This is the API: 
http://3.230.103.45:4440/api/32/job/b2f3d1e3-241d-4cb5-adb1-db3aa9c0d5c3/run?authtoken=UE5y3aHbkPFZK3nD955gTrW4WpmAW0ON

**Comment by MegaDrive68k** [comment]
Hi @Muriloalgar2019 

How do you call the Rundeck API, I tested with:

**Comment by Muriloalgar2019** [comment]
Thanks for your coment! 

In POST I can execute it. 
How can I execute this job in GET ?? Am I able to do this in version 32?

**Comment by Muriloalgar2019** [comment]
> Hi @Muriloalgar2019
> 
> How do you call the Rundeck API? I tested with:
> 
> `curl --location --request POST http://localhost:4440/api/32/job/3398f5a9-f541-462b-aaea-2e0bae4b1867/run?authtoken=4yEDPJpF50UY0cZwCdoDipUOO0ejmsax`
> 
> And works.
> 
> You can see a lot of examples here:
> 
> https://documenter.getpostman.com/view/95797/rundeck/7TNfX9k?version=latest#intro
> 
> Hope it helps!

**Comment by BraxtonLowers** [comment]
I found another simple mistake that can lead to the same 405 HTTP status code: trying to hit an endpoint unencrypted when it should be secured.

For example, making a request to `http://localhost:4440` instead of `https://localhost:4440`
