### ISSUE TITLE
Gui Editing for Ansible Resource Model Source

### ISSUE THREAD

**Issue by deitChi** [rundeck/rundeck#5380]
I've implemented Rundeck in a few locations as a frontend for Ansible. However, usually, that does still require CLI management of the Ansible Inventory (hosts) file.

I know that a while ago the "File" Node source has been implemented to have an 'Edit' functionality. Would it be possible to add a similar feature for Ansible?

**Comment by MegaDrive68k** [comment]
Sounds good! Please suggest it [here](https://github.com/Batix/rundeck-ansible-plugin/issues). Thanks!
