### ISSUE TITLE
GUI - Unable to Delete User API Tokens with large role list

### ISSUE THREAD

**Issue by yoretech** [rundeck/rundeck#5384]
**Describe the bug**
On the User Profile Page API Tokens section, if a token has a large number of roles or many roles with long names, the Roles column will push/move the Delete button off-screen. The only way to access the delete button is to Scale the Browser window down.

**My Rundeck detail**
* Rundeck version: 3.0.26-20190829 º 3.1.2-20190927 
* install type: rpm
* OS Name/version: Centos 7
* DB Type/version: MySQL

**To Reproduce**
Create a User with many roles, goto Profile page, and create an API token for the user that has all the roles - see attached.

**Expected behavior**
We expect the column to be truncated/wrapped (similar to how it works in the First Name, Last Name, and Groups of the User Profile in the section above) Perhaps the integration of a Horizontal scroll bar would be helpful as well.

**Screenshots**
v.3.0x
**Firefox**
![GH-3 0-TokenFirefox](https://user-images.githubusercontent.com/46457681/66856721-3105bc80-ef5c-11e9-8e99-d5ee140373d8.png)
![GH-3 0-TokenFirefox67percent](https://user-images.githubusercontent.com/46457681/66856718-306d2600-ef5c-11e9-9262-f8244358e9e4.png)
**Chrome**
![GH-3 0-TokenChrome](https://user-images.githubusercontent.com/46457681/66856719-306d2600-ef5c-11e9-9308-2c0c57d2bf10.png)
![GH-3 0-TokenChrome67percent](https://user-images.githubusercontent.com/46457681/66856720-306d2600-ef5c-11e9-89c4-e7509516921b.png)

v.3.1x
**Firefox**
![GH-3 1-TokenFirefox](https://user-images.githubusercontent.com/46457681/66856770-4c70c780-ef5c-11e9-9101-ad25772d2acf.png)
![GH-3 1-TokenFirefox67percent](https://user-images.githubusercontent.com/46457681/66856772-4c70c780-ef5c-11e9-94d5-93a009e282bc.png)
**Chrome**
![GH-3 1-TokenChrome](https://user-images.githubusercontent.com/46457681/66856768-4c70c780-ef5c-11e9-94d1-53404e064cd7.png)
![GH-3 1-TokenChrome67percent](https://user-images.githubusercontent.com/46457681/66856769-4c70c780-ef5c-11e9-8943-afc0d48725bd.png)

**Desktop:**
 - OS: Ubuntu 18.04 or Windows 10
 - Browser Chrome 77 and Firefox 69

**Comment by ProTip** [comment]
Fixed in #5459
