### ISSUE TITLE
Class path contains multiple SLF4J bindings

### ISSUE THREAD

**Issue by NicolasDEVOUGE** [rundeck/rundeck#5395]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: Rundeck 3.0.7-20181008
* install type: deb
* OS Name/version: Ubuntu 16.04.5 LTS
* DB Type/version: mysql
* WinRm version latest

**To Reproduce**
1. Start my WinRM job 
2. Error appear

**Expected behavior**

The log error say : 

11:15:02 | SLF4J: Class path contains multiple SLF4J bindings.
-- | --
11:15:02 | SLF4J: Found binding in [jar:file:/var/lib/rundeck/bootstrap/rundeck-3.0.7-20181008.war!/WEB-INF/lib/logback-classic-1.1.11.jar!/org/slf4j/impl/StaticLoggerBinder.class]
11:15:02 | SLF4J: Found binding in [jar:file:/var/lib/rundeck/libext/cache/rundeck-winrm-plugin-1.3.6-SNAPSHOT/20191018111029000-9/lib/slf4j-nop-1.6.3.jar!/org/slf4j/impl/StaticLoggerBinder.class]
11:15:02 | SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
11:15:02 | SLF4J: Actual binding is of type [org.slf4j.helpers.NOPLoggerFactory]

**Screenshots**
![image](https://user-images.githubusercontent.com/1253901/67082620-c641c480-f199-11e9-8edf-2a363c00bec4.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 r2
 - Browser opera or chrome
 - Version latest

**Comment by MegaDrive68k** [comment]
Hi @hackman61 

Can you share which Java version do you have?

`java -version`

Thanks!

**Comment by hackman61** [comment]
Hello :

java -version
openjdk version "1.8.0_222"
OpenJDK Runtime Environment (build 1.8.0_222-8u222-b10-1ubuntu1~18.04.1-b10)
OpenJDK 64-Bit Server VM (build 25.222-b10, mixed mode)

**Comment by sjrd218** [comment]
This is fixed with rundeck-winrm-plugin-1.3.8.
