### ISSUE TITLE
Context variables not parsed in key storage path using Required=yes

### ISSUE THREAD

**Issue by Behzadb** [rundeck/rundeck#5397]
**Describe the bug**
I cannot use [this](https://github.com/rundeck/rundeck/pull/3420) feature.

https://github.com/rundeck/rundeck/issues/2092

**My Rundeck detail**

* Rundeck version: 3.1.2-20190927
* install type: docker
* OS Name/version: ubuntu 16.04
* DB Type/version: postgres

**To Reproduce**
1. Create a key storage based on a context variable 
2. Try to use it in a job
3. Run the job
4. storage value from 'keys/user/${job.username}/password'  could not be read

**Expected behavior**
When key path contains a context variable, Rundeck replace it with its value. For example:
keys/user/${job.username}/password --> keys/user/admin/password

**Comment by MegaDrive68k** [comment]
Hi @Behzadb 

I tried with this job definition and seems to work (under Docker and WAR based installation), can you post a job definition example to test?

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='opt1' secure='true' storagePath='keys/${job.username}/passwd' valueExposed='true' />
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>464a2764-efb2-4f65-a01f-5a7704ff55aa</id>
    <loglevel>INFO</loglevel>
    <name>PrintPassword</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo ${option.opt1}</exec>
      </command>
    </sequence>
    <uuid>464a2764-efb2-4f65-a01f-5a7704ff55aa</uuid>
  </job>
</joblist>
```

(with a password stored at keys/admin/passwd)

Thanks a lot!

**Comment by Behzadb** [comment]
Hi @MegaDrive68k , I think I found the problem thanks to your example.
My option checked as a required option. I wonder if it is a bug or not but the expected behavior would be to first check user input, if it does not exist then check for the storage path and then failed.
Currently, if the option checked as required and user not enter any value Rundeck will not check for the specified path.

An example job would be:

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='password' required='true' secure='true' storagePath='keys/user/${job.username}/password' valueExposed='true' />
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>a1c210d0-43c7-490e-8bc5-0f7563e64c92</id>
    <loglevel>INFO</loglevel>
    <name>test option</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo ${option.password}</exec>
      </command>
    </sequence>
    <uuid>a1c210d0-43c7-490e-8bc5-0f7563e64c92</uuid>
  </job>
</joblist>
```
Thank you.
