### ISSUE TITLE
HOW TO REMAIN THE SAME TOKEN KEY ON RUNDECK

### ISSUE THREAD

**Issue by Muriloalgar2019** [rundeck/rundeck#5401]
Hello, guys!!

I'm trying to execute an API token on RUNDECK version 3.1.0.
Recently I've found out that I will have to change the TOKEN each period of time. If I create a token today I will have to change it in 30 days.

Does anyone know if I can fix it permanently on RUNDECK version 3.1.0 ?? Can  anyone help me?
(sorry about my English, I'm brazilian)

**Comment by MegaDrive68k** [comment]
Hi @Muriloalgar2019 

You can set the following configuration in your rundeck-config.properties file:

`rundeck.api.tokens.duration.max=0`

And restart Rundeck service.

More info here:

https://docs.rundeck.com/docs/administration/configuration/config-file-reference.html#security

Hope it helps!

**Comment by Muriloalgar2019** [comment]
Yess. It works! I did not know that configuration.
Thanks for your help @MegaDrive68k
