### ISSUE TITLE
GUI - not convenient the correlate to log output 

### ISSUE THREAD

**Issue by luisrivas35** [rundeck/rundeck#5403]
**Describe the issue**
When having a large screen, the new GUI is not very convenient when reviewing the log generated by each job output against multiple servers. The fact the server name is displayed on the right makes very difficult to correlate the output with a given server. 

![case5329](https://user-images.githubusercontent.com/43067588/67362171-d7dfef00-f540-11e9-9058-34cd75b35d92.png)

**My Rundeck detail**

* Rundeck version: Entreprise 3.1.2
* install type: WAR
* OS Name/Version: RHEL 6.x
* DB Type/version: MSSQL

**To Reproduce**

1. Run a job as usual
2. Click on Activity section
3. See the output.

**Expected behaviour**

Having a proportional space to the output, so we could have a better correlate the results.

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: chrome

**Comment by fdevans** [comment]
The current version has an updated Log Viewer.  Check it out and see if helps.
