### ISSUE TITLE
Rundeck 2.6.1 Preauth mode gives error getAuthContextForSubject: Cannot get AuthContext without subject 

### ISSUE THREAD

**Issue by josemanimala** [rundeck/rundeck#5404]
**Describe the bug**
Enabling preauth mode gives the error `getAuthContextForSubject: Cannot get AuthContext without subject `

**My Rundeck detail**

* Rundeck version: 2.6.1
* install type: deb
* OS Name/version: ubuntu 18.04 LTS
* DB Type/version: Builtin

**To Reproduce**
1. Enable preauth by adding config params in /etc/rundeck/rundeck-config.properties
2. Remove auth constraint from /var/lib/rundeck/exp/webapp/WEB-INF/web.xml

**Expected behavior**
After auth redirects, UI shows the user as signed in with options to create projects, run jobs etc.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 69

**Additional context**
```
java.lang.RuntimeException: getAuthContextForSubject: Cannot get AuthContext without subject
	at rundeck.services.FrameworkService.getAuthContextForSubject(FrameworkService.groovy:611)
	at rundeck.controllers.MenuController.home(MenuController.groovy:894)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:565)
```

**Comment by ProTip** [comment]
Hi @josemanimala ,

The issue template has been filled out to indicate Rundeck `2.6.1` was used; is this accurate?

Rundeck `2.6.1` is four years old this month and no longer supported.. Are you able to reproduce this issue on the latest version of Rundeck?


Thanks,
   -Greg

**Comment by josemanimala** [comment]
Thanks @ProTip. We will upgrade to a newer version. 
My tests on a brand new rundeck install with 3.1.2 shows the user/roles correctly but I get REJECTED_NO_SUBJECT_OR_ENV_FOUND in the logs and the UI says I am unauthorized.
Would you know why this could be? I was hoping that mapping a user to the default admin group would grant me admin privilege

**Comment by josemanimala** [comment]
Never mind, admin.aclpolicy was missing from the install
