### ISSUE TITLE
Wrong HTTP response code based on action

### ISSUE THREAD

**Issue by booshlinux** [rundeck/rundeck#5423]
**Describe the bug**
200 HTTP response on an action that is unauthorized

**My Rundeck detail**

* Rundeck version: 3.0.23
* install type: deb
* OS Name/version: Ubuntu 18.04

**To Reproduce**
1. Send an API call to bulk delete executions with a user that does not have permissions to do so within that project
2. Examine the HTTP code vs. the API response:

```
$VAR1 = {
          'requestCount' => 1,
          'failures' => [
                          {
                            'message' => 'Unauthorized: Delete execution in project xyz',
                            'id' => '63937'
                          }
                        ],
          'failedCount' => 1,
          'successCount' => 0,
          'allsuccessful' => bless( do{\(my $o = 0)}, 'JSON::PP::Boolean' )
        };
$VAR1 = 200;             <----- HTTP Code
$VAR1 = '200 OK';     <----- Status line
```

**Expected behavior**
A 403 forbidden HTTP code. Heres an example of a user trying to list API tokens for another user without proper permission:
```
$VAR1 = {
          'apiversion' => 31,
          'error' => bless( do{\(my $o = 1)}, 'JSON::PP::Boolean' ),
          'errorCode' => 'api.error.item.unauthorized',
          'message' => 'Not authorized for action "admin" for User xyz'
        };
$VAR1 = '403';                        <------ Correct HTTP Code
$VAR1 = '403 Forbidden';       <------ Correct Status line
```
If there is a reason for this that I am not aware of please let me know.

**Comment by MegaDrive68k** [comment]
If call metrics with  a user that does not have permissions to do:

`curl -v --location --request GET "http://localhost:4440/api/33/metrics/metrics" --header "Accept: application/json" --header "X-Rundeck-Auth-Token: PCRdR4DsvkUzUoHfULIiavADh181B8ba"`

With this result (ERROR 403):

```
*   Trying 127.0.1.1...
* TCP_NODELAY set
* Connected to localhost (127.0.1.1) port 4440 (#0)
> GET /api/33/metrics/metrics HTTP/1.1
> Host: localhost:4440
> User-Agent: curl/7.58.0
> Accept: application/json
> X-Rundeck-Auth-Token: PCRdR4DsvkUzUoHfULIiavADh181B8ba
> 
< HTTP/1.1 403 Forbidden
< Date: Fri, 25 Oct 2019 18:06:45 GMT
< X-Frame-Options: deny
< X-XSS-Protection: 1
< X-Content-Type-Options: nosniff
< Content-Security-Policy: default-src 'none' ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; style-src 'self' 'unsafe-inline' ; img-src * ; font-src 'self' data: ; connect-src 'self' https://api.rundeck.com ; form-action 'self' ;
< X-Application-Context: application:production:4440
< Set-Cookie: JSESSIONID=node01sptxolix4b8nssriwe1z8rne21.node0; Path=/; HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Content-Type: application/json;charset=utf-8
< X-Rundeck-API-Version: 33
< Transfer-Encoding: chunked
```

If do the same thing to bulk delete executions (with the same unauthorized user):

```
curl -v --location --request POST "http://localhost:4440/api/33/executions/delete" \
  --header "Accept: application/json" \
  --header "X-Rundeck-Auth-Token: PCRdR4DsvkUzUoHfULIiavADh181B8ba" \
  --header "Content-Type: application/json" \
  --data "{\"ids\": [ 1, 2, 3 ] }"

```

Rundeck API returns code 200:

```
*   Trying 127.0.1.1...
* TCP_NODELAY set
* Connected to localhost (127.0.1.1) port 4440 (#0)
> POST /api/33/executions/delete HTTP/1.1
> Host: localhost:4440
> User-Agent: curl/7.58.0
> Accept: application/json
> X-Rundeck-Auth-Token: PCRdR4DsvkUzUoHfULIiavADh181B8ba
> Content-Type: application/json
> Content-Length: 21
> 
* upload completely sent off: 21 out of 21 bytes
< HTTP/1.1 200 OK
< Date: Fri, 25 Oct 2019 17:30:13 GMT
< X-Frame-Options: deny
< X-XSS-Protection: 1
< X-Content-Type-Options: nosniff
< Content-Security-Policy: default-src 'none' ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; style-src 'self' 'unsafe-inline' ; img-src * ; font-src 'self' data: ; connect-src 'self' https://api.rundeck.com ; form-action 'self' ;
< X-Application-Context: application:production:4440
< Set-Cookie: JSESSIONID=node01ir1cyecs2u9in51ddtp54cpg18.node0; Path=/; HttpOnly
< Expires: Thu, 01 Jan 1970 00:00:00 GMT
< Content-Type: application/json;charset=utf-8
< Transfer-Encoding: chunked
< 
* Connection #0 to host localhost left intact
{"requestCount":3,"allsuccessful":false,"successCount":0,"failedCount":3,"failures":[{"message":"Unauthorized: Delete execution in project ProjectONE","id":1},{"message":"Unauthorized: Delete execution in project ProjectONE","id":2},{"message":"Unauthorized: Delete execution in project ProjectONE","id":3}]}
```

**Comment by sjrd218** [comment]
The bulk delete execution API can be used to delete executions from multiple projects. A user might not have authorization to delete from one project where they might have that authority in another. The response is designed to be able to communicate both success and failure in the case where ids from multiple projects are sent. 200 seems to be a valid response code.

**Comment by booshlinux** [comment]
To me that sounds like a flaw in the design of the API. In my opinion, Bulk deletes should be limited to one project. This way HTTP codes can reflect correct responses. This is how the rest of the API is developed, so I don't see a reason why this one route should be a "one-off".

A 200 response on a unauthorized action is poor design.

**Comment by TheLastProject** [comment]
In my case, I'm doing a bulk delete where every single delete fails because unauthorized, yet I still get HTTP 200. I believe in the case where everything is unauthorized, there is no unclarity about if it was successful or not, and at least that case should always give HTTP 403.

I would personally prefer getting an error HTTP code if ANY of the deletes fails, so you know "oh, this wasn't completely successful" just from the HTTP response, but at very least when all fail it should definitely give HTTP 403.

**Comment by booshlinux** [comment]
I'm unaware of this use case anywhere else within Rundeck, But I believe the 207 multi status response code would fit most appropriately here.

**Comment by TheLastProject** [comment]
@booshlinux That sounds perfect to me, yeah.

I'm imagining this as follows now:
All success: 200
All unauthorized: 403
All already deleted: 404
Mix of statuses: 207

**Comment by booshlinux** [comment]
That sounds good to me as well.
