### ISSUE TITLE
Multiple Execution=no not enforced when called via Job Reference

### ISSUE THREAD

**Issue by falloutphil** [rundeck/rundeck#5428]
**Describe the bug**

"Multiple Executions?" option set to "No" in the Edit or Create Job webpage, should stop any parallel executions, but it is _not_ enforced when the second execution is via a **job reference step**.

**My Rundeck detail**

    Rundeck version: 3.0.9-20181127
    install type: deb
    OS Name/version: ubuntu 18.04

**To Reproduce**

Create a long running job (Job X) and set:
Multiple Executions? No
Limit Multiple Executions? 1 (this shouldn't be necessary given the above but seems to be)

Satisfy yourself that multiple executions are indeed blocked.

Create a new job (Job Y) that calls the long running job  (Job X) via a Job Reference Step.

Observe that even with the long running job X in mid-execution, by executing the new job Y in parallel, and thus the long running job is executed twice at the same time, via the job reference step.  This is despite it being explicitly forbidden in the long running job settings.

**Expected behavior**

Job Reference to execute X from Y should be queued until the long running job X completes.

Also the fixer needs to think about the many permutations and combinations this throws up - manual start + job reference, automated start + job reference, 2 different job references, or even a chain of job references calling other job references and so on - all possible execution triggers must have sight of the current run state through a common interface, so none of these scenarios leads to job settings being circumvented.

As a wider suggestion - _any_ attempt at multiple execution (via any combination of GUI or Job Reference Step) should _optionally_ be set to **queue** jobs rather than error and give-up.   Failing the job is crude and harder to work with in complex automated setups.  When many jobs contain many job references we don't want them to clash, but we don't want them to fail either.  So testing for any clash at each and every job reference execution time (rather than parent job execution time) and queuing rather than failing when the job is already running would allow the system to resolve the clashes seamlessly without limiting the client by resorting to throwing errors.

That said I'd really appreciate if you could also describe or provide a patch for any workaround until it's fixed properly?  Even if it was to just force a crude failure if any job execution request that contained a further job reference to any currently running job - this would keep the system stable and safe for clients to use in the short-term, even if the queuing idea is far superior?

Thanks!

**Comment by MegaDrive68k** [comment]
I leave the two jobs to reproduce:

JobX:

```
<joblist>
  <job>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>71362ae7-6262-4829-992f-8f73d9403a4e</id>
    <loglevel>INFO</loglevel>
    <maxMultipleExecutions>1</maxMultipleExecutions>
    <name>JobX</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>sleep 15; echo "done!"</exec>
      </command>
    </sequence>
    <uuid>71362ae7-6262-4829-992f-8f73d9403a4e</uuid>
  </job>
</joblist>
```

JobY:

```
<joblist>
  <job>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>3cf2ca63-1fda-4b5f-b2b3-308f8c049966</id>
    <loglevel>INFO</loglevel>
    <name>JobY</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <jobref name='JobX' nodeStep='true'>
          <uuid>71362ae7-6262-4829-992f-8f73d9403a4e</uuid>
        </jobref>
      </command>
    </sequence>
    <uuid>3cf2ca63-1fda-4b5f-b2b3-308f8c049966</uuid>
  </job>
</joblist>
```

![Screenshot_1](https://user-images.githubusercontent.com/51376003/67762121-77aaea80-fa23-11e9-9e90-238408dc849c.png)

Tested on 3.0.9, also occur on 3.1.2.

Thanks for your feedback @falloutphil

**Comment by Pixelartist** [comment]
Just discovered the same.

**Comment by jprudent** [comment]
Same here. I'll have to rely on a distributed lock somewhere :/

**Comment by lukasged** [comment]
Just discovered it, still happens with Rundeck version `3.1.2-20190927` :(

**Comment by RymRabehi** [comment]
Still happens on rundeck version Rundeck `3.2.3-20200221`

**Comment by jtobard** [comment]
this is not a bug, this is the design of referenced jobs, a referenced execution is part of the parent execution not is own execution.

**Comment by hg77** [comment]
As a workaround:
Do not set up your step as a job reference. Instead use command/script step to invoke the rd CLI:
```
rd run -f -i [job uuid]
```

if it is already running, it will fail with:
```
Error: Execution had a conflict: Job "wait_job" {{Job XXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXX}} is currently being executed {{Execution 12833}}
[code: api.error.execution.conflict; APIv34]
Could not create resource: 409 Conflict
```

`rd` needs some [configuration for password/user](https://rundeck.github.io/rundeck-cli/configuration/), so this is a bit more involved.
