### ISSUE TITLE
Simple Object format for Remote Job Options does not work in 3.x

### ISSUE THREAD

**Issue by askmike1** [rundeck/rundeck#5435]
**Describe the bug**
When a remote url is passed in for job option in the simple object format:
`{"name1":"value1","name2":"value2"}`
it does not work with Rundeck v3.x

If it is in the json array format:
`[{"name": "name1", "value":"value1"},{"name": "name2", "value": "value2"}]`
it does work.

This happens when `Enforce from allowed values` is set

This has just started to be an issue with v3.x even though the documentation still shows simple object format should work. The error given is:
`Option SimpleObject value: value2 was not in the allowed values: []`

**My Rundeck detail**

* Rundeck version: tested failure with 3.1.2-20190927 & 3.1.0-20190731
* Rundeck version: tested success with 2.11.0
* install type: RPM
* OS Name/version: Red Hat Enterprise Linux Server release 7.6
* DB Type/version: MariaDB

**To Reproduce**
Set a job option to have remote URL with the following format
`{"name1":"value1","name2":"value2"}`
Also ensure that `Enforce from allowed values` is set

**Expected behavior**
It should allow a valid option to be passed in

**Screenshots**
![image](https://user-images.githubusercontent.com/5392342/67888089-e458de80-fb22-11e9-9de8-8b80ce6ff71f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 78

**Additional context**
N/A

**Comment by MegaDrive68k** [comment]
Hi @askmike1 

Seem the same behavior of this issue: https://github.com/rundeck/rundeck/issues/5314

Regards.

**Comment by askmike1** [comment]
Yep, sorry I was searching open issues, didn't search the closed ones. I'm assuming that will make it into the next release?

**Comment by MegaDrive68k** [comment]
@askmike1 

You can check the merge here: https://github.com/rundeck/rundeck/pull/5325 Should be ready for the next release.

We will follow any update in the "original" thread: https://github.com/rundeck/rundeck/issues/5314

Thank for your feedback!
