### ISSUE TITLE
forceBindingLogin doesn't work with restrictive ldap config

### ISSUE THREAD

**Issue by johnburbridge** [rundeck/rundeck#544]
Copy / past of my message to the Rundeck group for some background on the issue. I have a patch for this ready to go and will be submitting it shortly.

Thanks!
JB

> I'm trying to harden the LDAP server we're using for Rundeck and am having little success with getting users to authenticate.
> 
> More specifically, we had Rundeck working with a non-secured LDAP server (no acls, no rules) and after adding some restrictions we are no longer able login. The new, more restrictive LDAP configuration allows only rootDn connections from the same host (Rundeck and LDAP are on the same box) and limits all authenticated user accounts to read-only.  Our olc rules:
> 
> ```
> olcAccess: {0}to dn.base="cn=Manager,<baseDn>"
>     by peername.regex=<eth0 ip address> auth
>     by peername.regex=127\.0\.0\.1 auth
>     by users none
>     by * none
> olcAccess: {1}to attrs=userPassword
>     by * auth
> olcAccess: {2}to *
>     by users read
>     by anonymous auth
> ```
> 
> We can verify that everything is working as expected with ldapsearch / ldapmodify but after implementing the above rules we started getting the following exception from Rundeck while attempting to login:

```
javax.naming.NoPermissionException: [LDAP: error code 50 - Insufficient Access Rights]
```

> The stack trace points to com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule.findUser(), line 584 as being the culprit:

```
NamingEnumeration results = _rootContext.search(_userBaseDn, filter, filterArguments, ctls);
```

> From what I can tell by stepping through the code, findUser() is being called before the user has been authenticated and the _rootContext doesn't have a currentDn set either. LDAP server logs confirm the search is being attempted by an anonymous user and that no longer works after limiting read access to authenticated users only (as expected).
> 
> Our ldap module configuration:

```
ldap {
      com.dtolabs.rundeck.jetty.jaas.JettyCachingLdapLoginModule sufficient
        debug="true"
        contextFactory="com.sun.jndi.ldap.LdapCtxFactory"
        providerUrl="ldaps://servername:636"
        authenticationMethod="simple"
        forceBindingLogin="true"
        userBaseDn="cn=users,ou=rundeck,<baseDn>"
        userRdnAttribute="uid"
        userIdAttribute="cn"
        userPasswordAttribute="userPassword"
        userObjectClass="inetOrgPerson"
        roleBaseDn="ou=groups,ou=rundeck,<baseDn>"
        roleNameAttribute="cn"
        roleMemberAttribute="member"
        roleObjectClass="groupOfNames"
        cacheDurationMillis="0"
        reportStatistics="true";
};
```

> According to the docs, setting forceBindingLogin="true" should "bind as the user that is authenticating, otherwise bind as the manager and perform a search to verify user password" which is exactly what we want, but that's not happening. I noticed there was an option to use bindUser and bindPassword, so I tried setting those to a user that has search perms and voilá... everything worked. The searches are performed using the bindUser instead of the credentials provided during login... but this, however, isn't what we wanted. What we were really aiming for was the user supplying the credentials to be used instead of a hard-coded user in the module.

**Comment by cstewart87** [comment]
Running into this issue now, is there a workaround for this?  Using version 2.6.4-1.  Goal is to not include hardcoded binduser creds in the config, but instead allow the bind to happen with the authenticating user's creds.
