### ISSUE TITLE
Project description containing exclamation mark cannot be saved

### ISSUE THREAD

**Issue by Chupaka** [rundeck/rundeck#5446]
**Describe the bug**
When I try to save a project with exclamation mark added to its description, it doesn't show any errors but when you go back to settings, you see that description was not changed.

**My Rundeck detail**

* Rundeck version: Rundeck 3.1.2-20190927

**To Reproduce**
1. Go to 'Project Settings -> Edit Configuration...'
2. Add '!' char to project Description.
3. Click 'Save'
4. See NO error
5. Go to 'Project Settings -> Edit Configuration...'
6. See that Description was not changed.

**Expected behavior**
Either project description should be changed or some error should be thrown.

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.6
 - Browser Chrome
 - Version 78

**Comment by Chupaka** [comment]
Well, if I go to "Edit configuration file..." after the edit, I see that it contains new description with "!" changed to "\!", but GUI still shows previous description.

**Comment by MegaDrive68k** [comment]
Hi @Chupaka 

I tried to reproduce your issue under WAR based installation but it seems that works OK adding "!" in the project description. You can share what kind of instance do you have  (DEB, RPM, WAR) and if you have Rundeck with some database as backend?

Thanks!

**Comment by Chupaka** [comment]
@MegaDrive68k it's RPM installation connecting to MySQL 5.7 in GCP CloudSQL.
```
# rpm -qa |grep rundeck
rundeck-repo-4-0.noarch
rundeck-3.1.2.20190927-1.noarch
```

**Comment by MegaDrive68k** [comment]
Confirmed following the same steps of https://github.com/rundeck/rundeck/issues/5446#issue-516119417

Description changed:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/68031472-7afbdb80-fc9a-11e9-8026-bb53665dfc1f.png)

And the result:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/68031475-7c2d0880-fc9a-11e9-9304-6b10f1948d6a.png)

![Screenshot_2](https://user-images.githubusercontent.com/51376003/68031479-7df6cc00-fc9a-11e9-9fe5-5fbe0f997ca9.png)

NOTE: that doesn't happen on WAR based installation.

![Screenshot_5](https://user-images.githubusercontent.com/51376003/68031867-42103680-fc9b-11e9-9c6e-c2fed1827c58.png)

![Screenshot_6](https://user-images.githubusercontent.com/51376003/68031870-43416380-fc9b-11e9-90e5-26b379e090ec.png)

![Screenshot_7](https://user-images.githubusercontent.com/51376003/68031875-450b2700-fc9b-11e9-963c-e93102a7d85c.png)



Thanks for your feedback @Chupaka!
