### ISSUE TITLE
Hot reload of realm.properties still doesn't work in 3.1.2

### ISSUE THREAD

**Issue by rduser1337** [rundeck/rundeck#5451]
**Describe the bug**
ReloadablePropertyFileLoginModule seems to ignore changes to realm.properties made while the Rundeck server is running, i.e. hot reloading doesn't actually occur.

**My Rundeck detail**

* Rundeck version: 3.1.2
* Install type: Launcher via Docker image
* OS Name/version: Official Rundeck Docker image
* DB Type/version: mysql

**To Reproduce**
I did check this https://github.com/rundeck/rundeck/issues/4763 and update my jaas-loginmodule.conf config as follows:

```
rundeck {
    org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule required
        debug="true"
        hotReload="true"
        refreshInterval="5"
        file="/home/rundeck/server/config/realm.properties";

}
```

Changes in realm.properties (new users added, password changed) are not reloaded by the module.

Looks like in `setupPropertyUserStore` of ReloadablePropertyFileLoginModule.java the `refreshInterval` was not set before calling `start`: https://github.com/rundeck/rundeck/blob/0a5da63c4edad686cad40799e482f722c1df64ad/rundeckapp/src/main/groovy/org/rundeck/jaas/jetty/ReloadablePropertyFileLoginModule.java#L67

The `_reloadEnabled` is set to `true` by default so adding hotReload="true" in the config is not necessary.

**Comment by MegaDrive68k** [comment]
Hi @rduser1337 


Try with:

```
RDpropertyfilelogin {
   org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule required
   debug="true"
   refreshInterval="5"
   hotReload="true"
   file="/home/m68k/Rundeck/ver/3.1.2/server/config/realm.properties";
};
```

Instead of:

```
rundeck {
    org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule required
        debug="true"
        hotReload="true"
        refreshInterval="5"
        file="/home/rundeck/server/config/realm.properties";

}
```

And make sure that you're launching Rundeck with `-Drundeck.jaaslogin=true` param (check this: https://docs.rundeck.com/docs/administration/security/authentication.html#step-2-specify-login-module).

Related issue: https://groups.google.com/forum/#!topic/rundeck-discuss/XkC4wsFi2PA

Regards!

**Comment by rduser1337** [comment]
Doesn't work for me. Did you try to add new user or modify password in realm.properties file then login without restarting rundeckd?

**Comment by MegaDrive68k** [comment]
hi @rduser1337 

Yes, with this jaas-loginmodule.conf:

```
RDpropertyfilelogin {
   org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule required
   debug="true"
   refreshInterval="5"
   hotReload="true"
   file="/home/user/rundeck/3.1.2/server/config/realm.properties";
};
```

And launch with:

`java -Drundeck.jaaslogin=true -jar rundeck-3.1.2-20190927.war`

Check how you launch the war file.

Kind regards.

**Comment by rduser1337** [comment]
Thanks @MegaDrive68k. I found the issue related to weird docker with NFS volume. It's confirmed that this works with configuration mention in the latest docs: https://docs.rundeck.com/docs/administration/security/authentication.html#propertyfileloginmodule (no need `hotReload` and `refreshInterval`). My working configuration with Rundeck docker:

```
rundeck {
    org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule required
    debug="true"    
    file="/home/rundeck/server/config/realm.properties";
};
```

**Comment by mengzheyou** [comment]
Hi, @rduser1337  

For docker container deployment, I changed file `jaas-loginmodule.conf`, and restart the container, it always revert this file to blelow contents:  

```





rundeck {

    org.eclipse.jetty.jaas.spi.PropertyFileLoginModule required
        debug="true"
        file="/home/rundeck/server/config/realm.properties";

};
```

So, I can not set it to `org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule`, had you meet this problem ?

**Comment by zerr0s** [comment]
Hello,

@mengzheyou have you found a solution ? I have exactly the same issue.

**Comment by mengzheyou** [comment]
> Hello,
> 
> @mengzheyou have you found a solution ? I have exactly the same issue.

Sorry, I have no solution for this issue (can not work in Container deploy), but for the native package deploy (deb), it works.

**Comment by javierverb** [comment]
> Hi @rduser1337
> 
> Try with:
> 
> ```
> RDpropertyfilelogin {
>    org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule required
>    debug="true"
>    refreshInterval="5"
>    hotReload="true"
>    file="/home/rundeck/server/config/realm.properties";
> };
> ```
> 
> Instead of:
> 
> ```
> rundeck {
>     org.rundeck.jaas.jetty.ReloadablePropertyFileLoginModule required
>         debug="true"
>         hotReload="true"
>         refreshInterval="5"
>         file="/home/rundeck/server/config/realm.properties";
> 
> }
> ```
> 
> And make sure that you're launching Rundeck with `-Drundeck.jaaslogin=true` param. Check this: https://docs.rundeck.com/docs/administration/security/authentication.html#step-2-specify-login-module
> 
> Related issue: https://groups.google.com/forum/#!topic/rundeck-discuss/XkC4wsFi2PA
> 
> I tested under 3.1.2 and works OK.
> 
> Regards!

its works on rundeck v4.x! Thanks!
