### ISSUE TITLE
Job cascade options fails being referenced from another job

### ISSUE THREAD

**Issue by ejercitonegro** [rundeck/rundeck#5457]
**Describe the bug**
The job gives a Java error (java.io.FileNotFoundException). Job X has two cascade options, Cluster and Datastore, Datastore depends on the value chosen in Cluster, which reloads a json file based on the chosen value. If the job is executed in isolation, it ends without errors. If it is referenced from another job, it receives the variables correctly and performs all the functions, however in the log it throws Java errors making reference to the fact that the Datastore option that depends on Cluster is not well formed because it does not receive the variable as it can be seen in the screenshots, but as I say, at the execution level it works correctly..

**My Rundeck detail**

* Rundeck version: 3.1.2-20190927
* install type: rpm
* OS Name/version: RHEL 7.7
* DB Type/version: mysql

**To Reproduce**

**Expected behavior**
The same as if the job is executed in isolation, without being referenced.

**Screenshots**
![Captura_1](https://user-images.githubusercontent.com/57437700/68287319-d1925c80-0082-11ea-87b7-bc434a7e4a1b.PNG)
![Captura_2](https://user-images.githubusercontent.com/57437700/68287333-d6efa700-0082-11ea-99b8-a863f897da01.PNG)
![Captura_3](https://user-images.githubusercontent.com/57437700/68287343-dbb45b00-0082-11ea-92ef-cb91711a91b9.PNG)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chorme

Is this a BUG? It was working fine before upgrading to 3.1.2. Am I doing something wrong?

**Comment by MegaDrive68k** [comment]
Hi @ejercitonegro 

Can you share a Minimal Reproducible Example (Job definition example) to test your issue between Rundeck versions?

Thanks a lot!

**Comment by ejercitonegro** [comment]
hi @MegaDrive68k 

This is my main JOB, which calls another JOB passing the variables 'cluster' and 'datastore'
![1](https://user-images.githubusercontent.com/57437700/68372867-fb5e8880-0141-11ea-8129-d86edb005def.PNG)

This is the cluster referenced job option:
![2](https://user-images.githubusercontent.com/57437700/68372864-fac5f200-0141-11ea-9587-c68218c777e4.PNG)

This is the datastore referenced job option, it uses cluster option value to create the filename (cascade option):
![3](https://user-images.githubusercontent.com/57437700/68372866-fb5e8880-0141-11ea-98be-7680ac0d74e0.PNG)

When you use this job in isolation, without being referenced, it executes normally, without  showing any error. If its executed from another job (referenced) it show java error referencing the datastore option not being well formed but executing correctly

**Comment by mashwino** [comment]
Hi,
I'm experiencing the same kind of problem, but with the version 3.2.0-20191218
Job1 has remote file cascading options set like this:
PROJECT= file:/home/rundeck/options/project.json
MEMBER= file:/home/rundeck/options/${option.PROJECT.value}/member.json

If I run Job1, no problem, the files are found and the cascading is working.

Now I make Job2 in an other project (I didn't try with the 2 jobs in the same project):
PROJECT_ORIGIN=myprojet
MEMBER_ORIGIN=Myself
calling referenced Job1 with the 2 options as argument:
-PROJECT ${option.PROJECT_ORIGIN.value} -MEMBER {option.MEMBER_ORIGIN.value}

When I launch Job2, before executing the first step of Job1, the output shows a very long stacktrace starting by:
java.io.FileNotFoundException: /home/rundeck/options/member.json (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at sun.reflect.GeneratedConstructorAccessor474.newInstance(Unknown Source)
        ...

The complete [stacktrace.pdf](https://github.com/rundeck/rundeck/files/4048391/stacktrace.pdf)
_Remarks:_
- Those jobs are working fine in 3.0.22, when upgraded to 3.2.0, all the jobs having a cascade option got this option prefixed by a /:
3.0.22: MEMBER= file:/home/rundeck/options/${option.PROJECT.value}/member.json
3.2.0:  MEMBER= file:/home/rundeck/options//${option.PROJECT.value}/member.json
Removing this second slash does not change anything.
If you look at the error, normally, if the variable is not expanded for any reason, you will get the error message with a double slash in place of the variable like /home/rundeck/options//project.json ...
May be a clue ...


- The job is running correctly, all the steps are done, but with a so long stacktrace on the output display the jobs are hard to run.

**Comment by mashwino** [comment]
Hi,
just a quick addon, this is working in 3.0.26 and not working in version > 3.1.0
Thank you.
