### ISSUE TITLE
Rundeck execution arguments do not wrap

### ISSUE THREAD

**Issue by ahamilto** [rundeck/rundeck#5458]
**Describe the bug**
The arguments to rundeck executions wrap off the screen and can no longer be read or searched for.

**My Rundeck detail**

* Rundeck version: 3.1.2.20190927-1
* install type: rpm
* OS Name/version: CentOS 7.7.1908
* DB Type/version: postgres

**To Reproduce**
1. Create a job that takes longer string arguments (for example, file paths).
2. Run the job

**Expected behavior**
We expect to see a list of arguments to the job; with them wrapping to new lines or being horizontally scrollable if necessary

**Screenshots**
will be attached.

**Desktop (please complete the following information):**
 - OS: Fedora
 - Browser Firefox
 - Version: 69

**Comment by ahamilto** [comment]
![Screenshot_2019-11-06 Rundeck - Deploy Full Environment (JSON)](https://user-images.githubusercontent.com/69139/68316776-0359f200-0088-11ea-8631-04635d111301.png)

**Comment by MegaDrive68k** [comment]
Confirmed.

3.1.2:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/68327097-76289480-00ab-11ea-931e-c0593bb3a559.png)

3.0.26 works OK:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/68327255-bf78e400-00ab-11ea-9a81-0f06c184fd7d.png)





Thanks for your feedback @ahamilto!
