### ISSUE TITLE
Some fields did not save in 'Default node executor' form

### ISSUE THREAD

**Issue by mikesuding** [rundeck/rundeck#5462]
**Describe the bug**
When I change the 'SSH authentication' value, it doesn't seem to save. See video recording if needed.

**My Rundeck detail**

* Rundeck version: 3.1.2
* install type: RPM
* OS Name/version: CentOS 7
* DB Type/version: mysql

**To Reproduce**
1. Go to any Project...
2. pull down 'project settings'
3. Click on 'Edit configuration'
3. Click on 'SSH authentication' to change it to 'password'
4. Click save
5. come back in here and it doesn't save the change 

**Expected behavior**
I expect it will save the new setting

**Screenshots**
I will attach a screenshot

**Desktop (please complete the following information):**
 - Windows 2016
 - Browser chrome
 - Version 78

**Additional context**
The workaround is to 'edit configuration file' but you have to know the keywords and syntax.
![bug1](https://user-images.githubusercontent.com/23124354/68345552-770af780-00a6-11ea-9a9d-2b5f4c7dc8ed.png)

**Comment by MegaDrive68k** [comment]
Confirmed.

Tested on WAR based installation.

Also happens on 3.0.26,

Thanks for your feedback @mikesuding!
