### ISSUE TITLE
Project build error  : Cannot invoke method tokenize() on null object in rundeck:grails-spa

### ISSUE THREAD

**Issue by faissalwise** [rundeck/rundeck#5475]
**Describe the bug 

Build error when I run the project locally in windows whit the command line using: gradlew.bat build

Configure project :
Building version 3.2.0-SNAPSHOT

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':rundeck:grails-spa'.
> Cannot invoke method tokenize() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.7/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 28s

**Comment by faissalwise** [comment]
![image](https://user-images.githubusercontent.com/7318523/68489907-54b0df80-0248-11ea-8844-6f7cd36a3556.png)

**Comment by dejan-siedle** [comment]
Hi, I got the same error.
After researching a little bit it turns out that the node version is not found within the build.gradle file of the grails-spa project. I do not know the reason why `project.hasProperty('node.install')` does not work properly on my windows environment but the workaround, for me, was to set the values manually:
`
node{
    download = false
    version = '13.3.0'
}
`
Best regards Dejan

**Comment by tangyong** [comment]
I got the same error while building v3.2.3 from source using git clone.


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':rundeckapp:grails-spa'.
> Cannot invoke method tokenize() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 46s

**Comment by sjrd218** [comment]
@faissalwise Please try building from the latest version on windows.
