### ISSUE TITLE
api.error.item.doesnotexist - Project does not exist

### ISSUE THREAD

**Issue by askmike1** [rundeck/rundeck#5477]
**Describe the bug**
Step 1: Makes a POST call to `SITE/api/13/projects` to create a new project. Call is successful (200 ok response)
Step 2: Sleeps for 60 seconds
Step 3: Makes a GET call to `SITE/api/1/project/PROJECT_NAME` to confirm the project exists (loops until successful)
Step 4: Makes a POST call to `SITE/api/14/project/PROJECT_NAME/acl/admin.aclpolicy` to create an ACL on the project

Result: `{"error":true,"apiversion":32,"errorCode":"api.error.item.doesnotexist","message":"Project does not exist: PROJECT_NAME"}`

I've added steps 2 & 3 to try and help, but even when I can confirm the project exists, it still errors out on ACL creation. Sometimes it gets past ACL creation and fails on job creation. results are incosistent, sometimes working, sometimes failing.

This worked perfectly on v2.11.x and breaks as of at least 3.1.0

**My Rundeck detail**

* Rundeck version: 3.1.0-20190731
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux Server release 7.6 (Maipo)
* DB Type/version: MySQL

**To Reproduce**
See above

**Expected behavior**
Once project is created, further API commands on that project should work

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 76

**Additional context**
N/A

**Comment by gschueler** [comment]
what is the output from "POST call to SITE/api/13/projects" ? a response of `200` is odd, it should return `201` ("CREATED") code, if the project is successfully created.

**Comment by askmike1** [comment]
Sorry you are correct, it is a 201. The response body is:

```
{"url":"https://SITE/api/32/project/PROJECT_NAME","name":"PROJECT_NAME","description":"","config":{"resources.source.1.config.format":"resourcejson","service.NodeExecutor.default.provider":"jsch-ssh","project.name":"PROJECT_NAME","project.jobs.gui.groupExpandLevel":"1","resources.source.1.config.generateFileAutomatically":"true","project.disable.schedule":"false","resources.source.1.config.file":"/var/rundeck/projects/rundeck.json","project.disable.executions":"false","project.ssh-keypath":"KEYPATH","project.label":"PROJECT_NAME","resources.source.1.type":"file","project.nodeCache.delay":"30","service.FileCopier.default.provider":"jsch-scp","project.ssh-command-timeout":"0","resources.source.1.config.includeServerNode":"true","project.ssh-connect-timeout":"0","project.ssh-authentication":"privateKey","resources.source.1.config.writeable":"true","project.gui.readme.display":"projectHome","project.gui.motd.display":"projectHome","project.nodeCache.enabled":"true","resources.source.1.config.requireFileExists":"false"}}
```

**Comment by sjrd218** [comment]
@askmike1 What is the value of `rundeck.projectsStorageType` in your rundeck configuration?

**Comment by askmike1** [comment]
@sjrd218 `rundeck.projectsStorageType=db`
