### ISSUE TITLE
Unexpected behavior when killing a job that includes Job References in the workflow

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#5478]
**Describe the bug**
When "killing" a job which includes Job References as Workflow steps, the subsequent steps after the one running when "killed" ..take about a second (each) to show, first as "running", then as "failed". 

If the Same job references are added as "Node Steps" the behavior is, as expected, the currently running step shows as failed and all subsequent steps instantly marked as "Not Started" 

**My Rundeck detail**

* Rundeck version: same behavior 3.0.x, 3.1.x, 3.2 snap
* install type: any

**To Reproduce**

1. Create a simple job that runs any step ( eg  command , invoke a script, etc) 
2. Create a Second Job with 5 JobRef workflow steps, that reference the job from step 1, running in sequence. 
3. Run the Job ( select "node" view for ease )
4. While, eg, step 2 is running "Kill" the execution.
5. Step 2 will be marked as Failed
6. Step 3 will be marked as Failed ( after a few seconds )
7. The same until al steps are "failed" 

**Expected behavior**
The "killed" step should be marked as "Failed" and subsequent steps as "Not Started" ( immediately) 

**Screenshots**

Simple workflow ( no JobRef ) is "killed" at step 2 -> expected
![image](https://user-images.githubusercontent.com/31705339/68503525-d2252180-0241-11ea-8851-5cd6d4d70ce1.png)

Workflow consisting of Job reference Node Steps is "killed" at step 2 -> expected
![image](https://user-images.githubusercontent.com/31705339/68503858-9474c880-0242-11ea-9ada-3bdf61d5c2ed.png)

Workflow consisting of Job reference Workflow Steps is "killed" at step 2 -> subsequent steps sequentially show as  Running and then Failed
![image](https://user-images.githubusercontent.com/31705339/68504011-ec133400-0242-11ea-896a-55e94bb5059d.png)

**Additional context**
Created from Subscriber case # 34823

**Test Jobs ( rename to XML )**
[run_remote_command_bug_jobs.txt](https://github.com/rundeck/rundeck/files/3826114/run_remote_command_bug_jobs.txt)

**Comment by sebastianbello** [comment]
( Test jobs used - rename to .xml )
[run_remote_command_bug_jobs.txt](https://github.com/rundeck/rundeck/files/3826108/run_remote_command_bug_jobs.txt)

**Comment by jtobard** [comment]
Indeed there's a delay in killing referenced jobs of workflow type, as a workaround to get the expected output you have two choices:

1. mark the option `Stop at the failed step`:
![image](https://user-images.githubusercontent.com/2894508/69644238-27837000-1043-11ea-8b90-c2dbc7a64de1.png)

2. Use strategy sequential:
![image](https://user-images.githubusercontent.com/2894508/69644265-32d69b80-1043-11ea-8fa9-299175af9ce8.png)
