### ISSUE TITLE
checkbox in Key Storage not working

### ISSUE THREAD

**Issue by tuxisma** [rundeck/rundeck#5480]
**Describe the bug**
I'm not able to activate checkbox
**My Rundeck detail**

* Rundeck version:  3.1.2
* install type: yum
* OS Name/version: CentOS 7
* DB Type/version: postgres

**To Reproduce**
1. Go to the top right
2. Click on the gear menu
3. Scroll down to 'Key Storage'
4. Click 'Add or Upload a Key'
5. Click on 'Do not overwrite a file with the same name.'
6. See error, not able to activate the checkbox

**Expected behavior**
Checkbox activated

**Screenshots**
![image](https://user-images.githubusercontent.com/612047/68504464-ddfced80-0219-11ea-950c-ae202271020e.png)

**Desktop:**
 - OS: CentOS 7
 - Browser [chrome]
 - Version [78.0.3904.87]

**Comment by MegaDrive68k** [comment]
Confirmed.

Occurs from 3.0.X, 3.1.X and 3.2-SNAPSHOT.

Under 2.10/2.11 works OK.

Thanks for you feedback @tuxisma!
