### ISSUE TITLE
rundeck-config.groovy requires rundeck.feature true/false values to be strings not booleans

### ISSUE THREAD

**Issue by falloutphil** [rundeck/rundeck#5486]
**Describe the bug**

I have just updated from 3.0.9 -> 3.1.2.

Following this guide to setup access to Rundeck's offical plugin repo:
https://docs.rundeck.com/docs/administration/configuration/repository.html

Thus adding the following to /etc/rundeck/rundeck-config.groovy

rundeck.feature.repository.enabled=true
rundeck.feature.repository.localSearchOnly=false

I get no "Plugins" menu under the cog (I am an admin), nor do I an option for "Find Plugins".  I do however see "Installed Plugins" and "Upload Plugin".

I also tried adding the /opt config - this didn't help (my guess is this isn't necessary anyway):

rundeck.repository.plugins.provider.1.type=file
#This must match the storageTreePath below
rundeck.repository.plugins.provider.1.path=/installedPlugins
rundeck.repository.plugins.provider.1.config.baseDir=/opt/repository

#Must match the path previously specified in the storage tree configuration
rundeck.feature.repository.installedPlugins.storageTreePath=/installedPlugins

No errors in service.log or rundeck.log

What am I missing?

Any other log files to check or how else to diagnose issue?

**My Rundeck detail**

* Rundeck version: 3.1.2
* install type: deb
* OS Name/version: Ubuntu 18.04

**Expected behavior**

Ability to find, download and install plugins from official Rundeck Repository.

**Comment by sjrd218** [comment]
@falloutphil Try: `rundeck.feature.repository.enabled='true'` there seems to be a bug where the config only recognizes the string 'true' instead of the boolean value.

**Comment by falloutphil** [comment]
@sjrd218 thank you - this fixed the issue, but agree it's a bug.

Note also that a similar workaround is necessary to enable webhooks:
rundeck.feature.webhooks.enabled='true'

I will change the title of the issue accordingly.

**Comment by ProTip** [comment]
Fixed in #5483
