### ISSUE TITLE
No jarfiles under /var/lib/rundeck/bootstrap

### ISSUE THREAD

**Issue by devinnasar** [rundeck/rundeck#5493]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 3.1.2-20190927
* install type: rpm
* OS Name/version: Amazon Linux AMI release 2018.03
* DB Type/version: h2

**Expected Behavior**
There should be a number of jarfiles in /var/lib/rundeck/boostrap, including 'jetty-security....jar', which is necessary for obfuscating passwords in ssl.properties. No files appear there when calling `ls -lah /var/lib/rundeck/bootstrap`

Furthermore, a search of the entire hard drive reveals no such files.

**How to Reproduce**

Is this behavior intentional for this version of Rundeck, and if so, why was documentation not created to reflect the new paradigm before making the update? Thank you.

**Comment by MegaDrive68k** [comment]
Hi @devinnasar 

Can you check at `/var/lib/rundeck/cli/lib`?

Consider that in 3.1 the jetty encryption usage is integrated in the WAR launcher file at `/var/lib/rundeck/bootstrap/rundeck-3.1.2-20190927.war` file with:

`java -jar rundeck-3.1.2-20190927.war --encryptpwd Jetty`

Take a look:

https://stackoverflow.com/questions/58495654/automating-rundeck-password-md5-generation

Hope it helps!
