### ISSUE TITLE
Error handler setting to not emit error messages

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#550]
Some users like to write assert style workflow logic and do not want to see error messages printed for the assertion. For example, assertServiceIsUp might be written to have a command step that calls `pgrep procname` with that step's error handler running another command step that runs `startup procname`. 
End users will be confused to see stderr or error messages from the failed command.
Eg,

```
 Result: 1
 Failed: NonZeroResultCode: Result code was 1
```

Mentioned in Meetup SF#1.

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
