### ISSUE TITLE
Activity page: Save Filter doesn't work

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#5501]
**Describe the bug**
The "Save Filter" button on the Activity page doesn't work

**My Rundeck detail**

* Rundeck version: 3.2

**To Reproduce**
1. Go to 'Activity page'
2. Click on 'Search...', enter a query, and click "Save as a Filter"
3. nothing happens

**Expected behavior**
Prompt to enter name of filter and save it.

**Comment by jessemarple** [comment]
<img width="708" alt="Screen Shot 2019-11-15 at 5 19 51 PM" src="https://user-images.githubusercontent.com/265904/68979800-8d166780-07cc-11ea-94f5-7fca54fd4f20.png">
<img width="619" alt="Screen Shot 2019-11-15 at 5 20 06 PM" src="https://user-images.githubusercontent.com/265904/68979801-8d166780-07cc-11ea-9398-e6cac656727a.png">
<img width="692" alt="Screen Shot 2019-11-15 at 5 20 11 PM" src="https://user-images.githubusercontent.com/265904/68979802-8d166780-07cc-11ea-98e3-6f23fd4cd536.png">
