### ISSUE TITLE
Job with one worfklow step  has a misleading delete behavior

### ISSUE THREAD

**Issue by willianm** [rundeck/rundeck#5516]
**Describe the bug**
I have a job with only one workflow step. The UI allows me to delete the workflow step and save the Job. However, if I reopen the Job, the workflow step will still be there.

**My Rundeck detail**

* Rundeck version: 3.1.2
* install type: Official Docker Image
DB Type/version: mysql

**To Reproduce**
1. Create a Job
2. Add a workflow step
3. Save the Job
4. Edit the Job and remove the only workflow step.
5. Save
6. Reopen the Job
7. The workflow step will still be there. <-- Confusing.

**Expected behavior**
I was expecting that the UI would either reject the change or delete the workflow step.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 78.0.3904.97 (Official Build) (64-bit)

**Comment by MegaDrive68k** [comment]
Confirmed, also happens on 3.2.0-SNAPSHOT
 
After deleting the step and click on the "Save" button, Rundeck deletes the step, doesn't show some warning like "the job needs at least one step" and if edit the job again, the step keeps.

Thanks for your feedback @willianm
