### ISSUE TITLE
Rundeck plugins for mainframe jobs

### ISSUE THREAD

**Issue by venkategowdap** [rundeck/rundeck#5529]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**
We are looking  for PLugin for rundeck to receive trigger from mainframe so that Rundeck flow can kickstart
**Describe the solution you'd like**
Once the source mainframe jobs are completed trigger should go to rundeck jobs flow .

**Describe alternatives you've considered**
Control-M Scheduling tool have feature to trigger jobs in COntrol-m Once received completion notification.

**Additional context**
None

**Comment by venkategowdap** [comment]
please let us know any update on my issue ..

**Comment by MegaDrive68k** [comment]
Hi @venkategowdap 

You can call Rundeck using the API from your Mainframe, for example, to start a job passing some parameters, etc. For that you need cURL tool. You can check the complete cURL reference for z/OS here (check the Chapter 5):

ftp://ftp.www.ibm.com/s390/zos/pdfs/hpu4st03.pdf

Rundeck API reference:

https://docs.rundeck.com/docs/api/rundeck-api.html

You have a lot of API examples (with their Postman/cURL calls):

https://documenter.getpostman.com/view/95797/rundeck/7TNfX9k?version=latest

Greetings!

**Comment by venkategowdap** [comment]
@MegaDrive68k : Thank you ..let me try and come back on this

**Comment by vaxvms** [comment]
@venkategowdap the java rd client is running ok under z/OS USS
