### ISSUE TITLE
How to user project.name as bash variable 

### ISSUE THREAD

**Issue by RanganathNangineni** [rundeck/rundeck#5531]
I want to use project.name ( Which is the project name ) as a bash varibale in one of the scripts.
How can I get that ?
is it - 
$PROJECT_NAME / $RD_PROJECT / $RD_PROJECT_NAME ?

**Comment by MegaDrive68k** [comment]
Hi @RanganathNangineni 

The variable is $RD_JOB_PROJECT

I did an example using inline script:

```
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description>Project name example.</description>
    <executionEnabled>true</executionEnabled>
    <id>3398f5a9-f541-462b-aaea-2e0bae4b1867</id>
    <loglevel>INFO</loglevel>
    <name>ProjectName</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <orchestrator>
      <configuration>
        <count>1</count>
      </configuration>
      <type>subset</type>
    </orchestrator>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <script><![CDATA[echo "the project is: $RD_JOB_PROJECT"]]></script>
        <scriptargs />
      </command>
    </sequence>
    <uuid>3398f5a9-f541-462b-aaea-2e0bae4b1867</uuid>
  </job>
</joblist>
```

And the result:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/69342266-ead20600-0c49-11ea-8ca9-d47ade4525f4.png)

If you need that value on remote nodes, keep on mind this:

https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html#passing-environment-variables-through-remote-command

Hope it helps!
