### ISSUE TITLE
Add Docker plugin to official Docker image

### ISSUE THREAD

**Issue by sburlappp** [rundeck/rundeck#5538]
**Is your feature request related to a problem? Please describe.**
There doesn't seem to be a way to use the official Docker image to manage a Docker environment without customizing it to add the Docker plugin. This seems like an oversight, since that would be an obvious way to use that pre-built image.

**Describe the solution you'd like**
Add the Docker plugin to the default image.

**Describe alternatives you've considered**
I was just testing out Rundeck on Docker to see if it was worthwhile, but this makes me want to go looking for other options again.

**Additional context**
If adding plugins to the Docker image was easier, this wouldn't be a problem.

**Comment by ltamaster** [comment]
Hi @sburlappp 

You can extend the official image and install the plugin

for example
https://github.com/rundeck/docker-zoo/blob/master/config/Dockerfile#L5

Another option is using the new plugin repository.
Using the rd cli you can upload and install plugins
https://docs.rundeck.com/docs/administration/configuration/repository.html#install-plugin

Luis

**Comment by fdevans** [comment]
Closed per workaround provided.  If there are still gaps in the feature set please feel free to open an enhancement request against the current version of Rundeck with your ideas.
Thank you, 
The Rundeck Team
