### ISSUE TITLE
SAML Support

### ISSUE THREAD

**Issue by rnsc** [rundeck/rundeck#5576]
**What the issue is:**
We're phasing out our LDAPS backend and Rundeck not implementing SAML authentication is an issue.

**What we'd like:**
I'd like to be able to use SAML authentication to authenticate against Azure AD without having to use an LDAPS backend.

**What we looked at:**
We've looked at an oAuth proxy, but it's not really ideal, as we want to have authenticated users in our Rundeck with clearly defined ACL policies based on our AD groups.

**Comment by scottfuhrman** [comment]
We have same requirement, need SAML 2 for SSO.

**Comment by guilhermevini** [comment]
Same
