### ISSUE TITLE
Run Job Webhook Plugin - node filter does not apply

### ISSUE THREAD

**Issue by hkhail** [rundeck/rundeck#5588]
**Describe the bug**

I've created a Run Job Webhook as per:
https://docs.rundeck.com/docs/manual/webhooks/run-job.html#usage

I picked the "Webhook Run Job" webhook event plugin and choose a job to execute.
I left all the other fields blank.

When I launch the following command:
curl -i -H 'Content-Type: application/json' -X POST 'https://rundeck:4440/api/33/webhook/H0Ui0DIZoIXFF9exOZnFbsPFGEJl5wLf' -d '{"filter","hostname"}'

It does not apply the filter and the job is still executed on all the hosts.

**My Rundeck detail**

* Rundeck version: 3.1.3
* install type: war
* OS Name/version: Redhat 7
* DB Type/version: postgres

**Expected Behavior**
Calling the webhook runs the job only on a defined node

**Comment by MegaDrive68k** [comment]
Hi @hkhail 

You need to define a data variable in your webhook definition like this:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/71209544-92af1380-228a-11ea-9023-d54b0063d191.png)

Now you can call the webhook in this way (check the data section):

`curl -H "Content-Type: application/json" -X  POST -d '{"field1":"node.*"}' http://yourinstance:4440/api/33/webhook/sJefoW7CxFKNvsdyuAj6ogmrBNLnMxt5#ExampleWebhook`

Hope it helps!

**Comment by hkhail** [comment]
Hi @MegaDrive68k,

It works. Thanks a lot for your help.

H.
