### ISSUE TITLE
Import job from xml references to another project in the same instance

### ISSUE THREAD

**Issue by vikasmewara** [rundeck/rundeck#5605]
**Describe the bug**
I have exported a list of jobs from an instance of Rundeck and imported it to another instance to a new project. There are some job definitions in the import file which is similar to jobs in another project in the same instance.
I have chosen the below option "Remove UUIDs" and "Always create a new job" while importing, but the issue still persists. I verified the job definitions and it is pointing to the new project.
The workaround I could figure out is, go the job and edit (not make any changes) and SAVE it. which fixes the issue and points to the new project.

**My Rundeck detail**

* Rundeck version: 2.11.4-1
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: NAME="Oracle Linux Server 6.10"
* DB Type/version: Oracle

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @vikasmewara 

If you run this job on a project and import it later to another, you obtain the name of the first one?

```
<joblist>
  <job>
    <defaultTab>summary</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>076f736d-cb58-4fb3-aec9-2ebfe099fa3d</id>
    <loglevel>INFO</loglevel>
    <name>ProjectNAME</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo ${job.project}</exec>
      </command>
    </sequence>
    <uuid>076f736d-cb58-4fb3-aec9-2ebfe099fa3d</uuid>
  </job>
</joblist>
```

Also, you can provide more information about your instance? What kind of installation are you using? (WAR, RPM orDEB) Some database as backend?

Greetings!

**Comment by vikasmewara** [comment]
I am actually using the "rd" tool to import the jobs and then using the xml option to upload the job into another project.
# rd jobs list -f <path_to_directory>/jobs.xml -p <project_name>

**Comment by MegaDrive68k** [comment]
Hi @vikasmewara 

I tried with the following steps (on 2.11.4):

1) Create some jobs.
2) Export with `rd jobs list -f <path_to_directory>/jobs.xml -p <project_name>`
3) Import via GUI.

And all seems normal, maybe I need to check something? Can you describe all steps to reproduce your issue? (with a simple job definition)

Also, can you check your service.log file to find some clues about that?

Thanks!!

**Comment by vikasmewara** [comment]
Hi @MegaDrive68k ,

Thanks for the reply.
I tried almost what you mentioned above, but there is some catch there.

I will explain the whole scenario here.
I have a Rundeck server which has below Projects in it:
a. DEV
b. DEV-Admin

I try to add another Project called PROD which has exported jobs from another project in a file called jobs.xml. I use the same command which you mentioned above to import the xml file via GUI.
Now the issue is seen where few jobs in the DEV project are exactly same to those in the newly created PROD project. 
So when I go inside the job definition and click on multiple sub definitions in it, it redirects to the one present in DEV and not PROD.
In order to verify, I edit the job and see the configuration of the jobs are correct and pointing to PROD project itself. Now as soon as I save that with no changes, Bang!! the issue is resolved. Now it not redirecting to the DEV project job, it is referencing the PROD project.

So, since I have 100's of such job, how do I import it in a better way to avoid the issue.

**Comment by puremourning** [comment]
Does the exported jobs xml contain job refs referenced by UUID or by name?

**Comment by vikasmewara** [comment]
it has both UUID and name, but while importing I disable the option to import UUIDs.
Please see the attachment with the options I selected while importing.
![image](https://user-images.githubusercontent.com/58939101/71159977-b6636100-226c-11ea-81d9-69849a4c77e5.png)
