### ISSUE TITLE
SSH Multiplexing

### ISSUE THREAD

**Issue by richiereynolds** [rundeck/rundeck#5609]
Setting up TCP connections is slow and many of them getting created and disappearing very fast tends to upset networks.

SSH multiplexing is fast and makes rundeck jobs run a lot faster however it's not supported with the inbuilt JSCH ssh implementation.
JSCH makes using key storage, passphrase, agent forwarding etc. easy. Configuring all that with OpenSSh and multiple users with different credentials isn't easy.

I'd like to be able to recreate the multiplexing created with OpenSSH .ssh/config like:
Host *
    ControlPath ~/.ssh/controlmasters/%r@%h:%p
    ControlMaster auto
    ControlPersist 10m
in JSCH.

**Describe alternatives you've considered**
OpenSSH, easy to configure the multiplexing, much harder to configure the other features JSCH provides by default such as allowing passphrase encryted keys and key forwarding.

**Comment by ltamaster** [comment]
Hi @richiereynolds ,

Have you tried https://github.com/rundeck-plugins/openssh-node-execution ?

Luis

**Comment by richiereynolds** [comment]
Hi @ltamaster ,

I don't think that gives us any more than just using the node-executor/file-copier attributes and using opsn ssh on the box itself. We already have scripts that allow key/passphrase retrieval from key storage. The part that's difficult to do using open ssh is ssh agent forwarding which this plugin doesn't seem to help with either. Plus this pluging adds yet another dependency, sshpass which we don't want to install.

Our problem is that we want ssh-agent forwarding, which JSCH gives us for free but is difficult to configure nicely with openssh (either using the installed version on the box or the plugin you metnioned)
And we want multiplexing which JSCH doesn't provide.

Each implementation is missing something the other has.

**Comment by binaryfire** [comment]
@richiereynolds I'm trying to improve SSH performance and am considering switching to OpenSSH despite the shortcomings. My research suggests its faster for other reasons too (ed25519 keys are faster than RSA, and jsch has more overhead in general).

I'm not using agent forwarding or passphrases. Do you know of any other issues I might run into with the OpenSSH plugin?
