### ISSUE TITLE
add a job reference from another project

### ISSUE THREAD

**Issue by schast** [rundeck/rundeck#561]
Hi,

i would like to add job references to jobs in other projects.
then you could add global jobs in a global project and include them in other projects as a workflow or node step.

**Comment by jcardali** [comment]
Bumping this because it would be a great feature, sadly doesn't seem like it will happen

**Comment by hmalinov** [comment]
+1

**Comment by kallqvist** [comment]
+1

**Comment by sillkongen** [comment]
+1

**Comment by michnmi** [comment]
+1

**Comment by matejhasul** [comment]
+1

**Comment by stuartTombola** [comment]
+1
