### ISSUE TITLE
rundeck behind apache SSL reverse proxy

### ISSUE THREAD

**Issue by yo34** [rundeck/rundeck#5619]
I am using rundeck behind an apache https reverse proxy. 

When browsing to https://my_server/rundeck it returns the location : **http://my_server/rundeck/user/login**

**So https become http**

I read a lot work arround .. but ..

**Here is the linux process** , i am using **/appli/rundeck/server/sbin/rundeckd start**

 java -Dserver.web.context=/rundeck -Dserver.contextPath=/rundeck -Dserver.http.port=4440 -Drundeck.jetty.connector.forwarded=true -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server -jar /appli/rundeck/rundeck-3.1.2-20190927.war

**rundeck-config.properties** contains
grails.serverURL=https://my_server/rundeck

**Here is my shell 's variable** :

export RDECK_BASE=/appli/rundeck/
export RUNDECK_WITH_SSL=true

**here is my apache conf** : 

ProxyPass /rundeck http://my_server:4440/rundeck
ProxyPassReverse /rundeck http://my_server:4440/rundeck

**Comment by yo34** [comment]
ok found

**Comment by zerr0s** [comment]
Hello, can you post the solution please ?? I have the same problem actually using a docker image
