### ISSUE TITLE
Problem / request

### ISSUE THREAD

**Issue by nicoman132** [rundeck/rundeck#5630]
Hi guys i need to figure out a job where the email send deppend of a value on one of the steps is this posible?

Example:

if a == 1
then
SEND EMAIL
else
DONT SEND EMAIL.

**Comment by niall-munnelly** [comment]
Rundeck Enterprise ruleset plugin offers this capability and I use it often, but I don’t know if it’s yet part of the free/open source distribution.

https://github.com/rundeck/rundeck/issues/916

**Comment by niall-munnelly** [comment]
Following up on my last email, it’s easy enough to execute what you described even without Enterprise’s ruleset strategy. You would capture the data from a previous step’s log filter and refer to it in your next step as something like “@data.FOO@“ in an inline script or “${data.FOO}” in a command step or n*xy script step. I wouldn’t call it intuitive, but it’s definitely doable.

**Comment by jessemarple** [comment]
Thank you @niall-munnelly. Those are excellent options.
