### ISSUE TITLE
小白请教，Groovy SQL command executor

### ISSUE THREAD

**Issue by tszhang2** [rundeck/rundeck#5631]
who can help me
怎么安装插件可以在 创建project时设置Groovy SQL command executor，我想要实现可以连接数据库进行数据查询

**Comment by fgutierrezz** [comment]
How to install this complement "Groovy SQL Command executor"

**Comment by jtobard** [comment]
If you mean this: https://github.com/strdn/rundeck-jdbc-executor-plugin
You can follow the instructions on that plugin page: https://github.com/strdn/rundeck-jdbc-executor-plugin#install

**Comment by MegaDrive68k** [comment]
Hi @tszhang2 

For Rundeck Enterprise you've SQLRunner Step Plugin, please take a look:

https://download.rundeck.com/plugins/sqlrunner-step-plugin.html

Greetings.

**Comment by wtt20182018** [comment]
Hi @tszhang2
Did you solve your problem? I donot have a directory name bootstrap introduced in https://github.com/strdn/rundeck-jdbc-executor-plugin
How do you solve it finally?

**Comment by MegaDrive68k** [comment]
Hi @wtt20182018 

You just need to download the file: https://github.com/strdn/rundeck-jdbc-executor-plugin/releases/download/0.1/rundeck-jdbc-executor-plugin-0.1.jar

And save it on "libext" directory (usually at /var/lib/rundeck/libext)

Hope it helps!

**Comment by wtt20182018** [comment]
> Hi @wtt20182018
> 
> You just need to download the file: https://github.com/strdn/rundeck-jdbc-executor-plugin/releases/download/0.1/rundeck-jdbc-executor-plugin-0.1.jar
> 
> And save it on "libext" directory (usually at /var/lib/rundeck/libext)
> 
> Hope it helps!

Thanks! It works!

**Comment by tszhang2** [comment]
thanks!
