### ISSUE TITLE
Send Notification from a job which was called as a workflow step

### ISSUE THREAD

**Issue by Alexander-Hagemeier** [rundeck/rundeck#5660]
Hello everyone,

I'm not quite sure if this is a feature request or if this behavior already exists and I wasn't able to find it/use it correctly.

I have created a job and enabled "Send Notification?". An email will be send every time the job succeeds. It works well when i trigger the job manually.

Now I have added this job as a workflow step to another job and the email won't be send. It seems that in the workflow step not the job itself is triggered but the commands are merged.

Is there another way to have the email send?

Kind regards,
Alex

**Comment by ahonor** [comment]
@Alexander-Hagemeier what version are you using?

**Comment by Alexander-Hagemeier** [comment]
@ahonor I'm using Rundeck 2.9.3-1
