### ISSUE TITLE
White page after project create on fresh Debian install according to rundeck website instructions

### ISSUE THREAD

**Issue by psy-mann** [rundeck/rundeck#5668]
Hi,

if i follow the instructions of 
https://docs.rundeck.com/docs/administration/install/linux-deb.html#open-source-rundeck
for Debian and using Debian 10. It comes a white page after project create 
the first project over WebUI. The Browser HAR file have some HTTP 500errors.
And the rundeck log some Java fails.

This problem is because Debian 10 use openjdk 11 by default. 
Except the user wants to explicate oracle java and adjust this.

As I have written here before:
https://github.com/rundeck/rundeck/issues/4996#issuecomment-570793692

The repos on debian 10 will automatically install java 11 (openjdk-11-jre-headless). So here must rundeck inform that must a manuell install for debian 10 in the docs. Or the package manager must
change the dependencies for deb systems to openjdk-8-jre.

I think this is because debian 10 now always uses openjava by default when the user
does not wear it separately.

I have now installed openjdk-8-jre manually on debian 10 before i used the rundeck guide.
Now it runs without errors.

Please fix the dependencies it looks like there is only java8-runtime here in rundack packages.
And Debian 10 use for it default openjdk-11-jre.

Best Regards

**Comment by MegaDrive68k** [comment]
Hi @psy-mann,

Java 8 is the  main requirement for Rundeck, check this:

https://docs.rundeck.com/docs/administration/install/system-requirements.html#java

Java 8 and Java 10 can coexist in the same Debian 10 box, for that follow this:

```
# openjdk 8 (for debian 10)
wget -qO - https://adoptopenjdk.jfrog.io/adoptopenjdk/api/gpg/key/public | apt-key add -
add-apt-repository --yes https://adoptopenjdk.jfrog.io/adoptopenjdk/deb/
apt-get update; apt-get install adoptopenjdk-8-hotspot

# to select the default java
update-alternatives --config java
```

Regards!
