### ISSUE TITLE
RunDeck 3.x.x: with more than 5000 jobs, loading Jobs page is very slow (4 minutes)

### ISSUE THREAD

**Issue by maurosaitta** [rundeck/rundeck#5685]
**Describe the bug**
With more than 5000 Jobs, the Jobs page is loaded very slowly: 4 minutes
Jobs are organized into groups and sub groups with max 3 levels

**Setup Considereations**
I've applied these tuning:

profile:
...
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx4096m -Xms1024m -XX:MaxMetaspaceSize=512m -server -XX:MaxPermSize=512m}"
...

/etc/security/limits.conf:
rundeck hard nofile 65535
rundeck soft nofile 65535

echo 65535 > /proc/sys/fs/file-max

I also tried this suggested solution found into a forum: 

rundeck.gui.paginatejobs.enabled = true
rundeck.gui.paginatejobs.max.per.page = 500

This change is the only one that has generated an improvement in the page loading but it does not make usability easier. 
gui.paginatejobs consider the sum of total jobs into groups, so if the sum of the max.per.page jobs is contained within fewer groups than the total number of groups, only the groups containing the max.per.page jobs will be displayed

**My Rundeck detail**

* Rundeck version: 3.2.0-20191218
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux Server release 7.6 (Maipo)
* DB Type/version: PostgresSQL 10.10

**To Reproduce**
1. Install a fresh Rundeck 3.2.0
2. Configure Rundeck with postgresql (or mysql or h2 DB; the behavior it is the same)
3. Import the entire project from a previous export from RundeDeck 2.11.7-1 (exluding Executions)
4. Click on JOBS. (and wait....)

**Expected behavior**

**Screenshots**
Expected output but loaded in 4 minutes:
![image](https://user-images.githubusercontent.com/37838699/72073113-8e0cd680-32ef-11ea-9071-f6ebf8224e68.png)

The Jobs page output with rundeck.gui.paginatejobs.enabled = true and rundeck.gui.paginatejobs.max.per.page = 500
![image](https://user-images.githubusercontent.com/37838699/72073279-e5ab4200-32ef-11ea-8d5d-4d213783d48f.png)

**Desktop (please complete the following information):**
 - OS: Linux Mint (ubuntu based)
 - Browser: Firefox 71.0

**Comment by maurosaitta** [comment]
Nobody have a suggestion?

**Comment by sjrd218** [comment]
Major improvements introduced with #5779. Will be available in next release.
