### ISSUE TITLE
Jobs page in rundeck not loading when there are more than 40k jobs

### ISSUE THREAD

**Issue by ajaysanthosh** [rundeck/rundeck#5687]
**Describe the bug**
Jobs page in rundeck not loading when there are more than 40k jobs

**My Rundeck detail**

* Rundeck version: 3.1.2-20190927
* install type: rpm
* OS Name/version: rhel 7.7
* DB Type/version: postgres

**To Reproduce**
1. We have around 50k jobs in a project, We also have other jobs in which we have around similar number of jobs.
2. On Clicking the Projects page the jobs page is not loaded and i get the below error in the rundeck.log

logging.DisablingLogWriter [Thread-163] ERROR rundeck.services.logging.DisablingLogWriter - Failed addEvent for FSStreamingLogWriter(execution:321190), disabling. Java heap space

I have increased the heap size from 1024M to 2048M, but still the loading of the page is very slow and almost never happens for close to 30 minutes.

**Comment by MegaDrive68k** [comment]
Hi  @ajaysanthosh 

Can you test setting pagination for jobs using `rundeck.gui.paginatejobs.enabled=true` and `rundeck.gui.paginatejobs.max.per.page=30` at rundeck-config.properties file and restart Rundeck?, check this:

https://docs.rundeck.com/docs/administration/configuration/gui-customization.html

Hope it helps!

**Comment by ajaysanthosh** [comment]
Thanks @MegaDrive68k . I have tried the same and have now restricted the job entries to 2500 per page.

I would need to delete these job entries as they are mostly history. Is there a way to delete only jobs that are history and not in schedule. I have around 50k entries

**Comment by MegaDrive68k** [comment]
Hi @ajaysanthosh 

To delete jobs you can do it through API, integrated into some custom script, check this example:

https://documenter.getpostman.com/view/95797/rundeck/7TNfX9k?version=latest#4d6e1616-08a7-1bd6-632f-01354936e438

To delete bulk executions ( and gain performance in your instance), you can use RD CLI (https://rundeck.github.io/rundeck-cli/) tool.

Syntax:

`rd executions deletebulk -n [job_name] -p [project]`

Or use this bash script based on Rundeck API:

https://gist.github.com/shamil/1f6524f06210252c7d13d0deb169bdc2

Main advice: test anything in a dev/test environment first.

I hope it helps!
