### ISSUE TITLE
after uploading a job, some options in "action" menu are showing 404/405 errors

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#5696]
**Describe the bug**
After uploading a job, some options in the "action" button menu are showing 404/405 errors.

**My Rundeck detail**

* Rundeck version: 3.2 OSS and 3.1.4 ENTERPRISE
* install type: war
* OS Name/version: ubuntu 18.10
* DB Type/version: h2

**To Reproduce**
1. Go to jobs
2. Click on "job actions"
3. Select "upload definition"
4. Choose file
5. Select one and Upload it.
6. Click on top right "actions" button
7. If "duplicate this job to other project" (OPTION FOR ENTERPRISE) is selected ---> error 404
8. If "disable schedule" (when job has schedule) is selected ---> error 405
9. If "disable execution" is selected ---> error 405
10.  Other options work fine.

**Screenshots**

![image](https://user-images.githubusercontent.com/34582874/72108010-56af2180-3311-11ea-80ef-0de1e51308a3.png)

**Comment by gschueler** [comment]
band-aid fix would be to disable/remove those actions from the menu in this page
