### ISSUE TITLE
"Choose A Job ..." in Webhook Management is not returning the list of jobs

### ISSUE THREAD

**Issue by willianm** [rundeck/rundeck#5700]
**Describe the bug**
I'm trying to test the new Webhook Management feature, but when I try to use the Run Job Handler, it doesn't list my jobs.

**My Rundeck detail**

* Rundeck version: 3.2.0
* Install Type: Docker
* DB Type/version: mysql
* Auth: Preauthenticated with NGINX auth module

**To Reproduce**
1. Create a Job and make sure it can run succesfully
2. Go to Webhooks management and create  Webhook
3. Select the Run Job handler
4. Click on Choose A Job ... button
5. The recently created job will not be there

**Expected behavior**
I was expecting to see the job I've created on step 1

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Version 79.0.3945.117 (Official Build) (64-bit)

**Additional context**
I've notice there is a call to the api (api/26/project/test/jobs?groupPath=*) using cookie authentication. In this case it is returning an empty array.
When I change to use X-Rundeck-Auth-Token, then the api returns the Job.

I'm using Preauthenticated mode with NGINX configured to do OAuth2. I'm not sure if this influences in the API behavior.

Regards,
Willian.

**Comment by sjrd218** [comment]
@willianm Another user reported a similar behavior with a setup that resembles yours. Can you look at #5471 to see if your issue might be the same?

**Comment by willianm** [comment]
@sjrd218 You are right, it is the same issue. In order to fix, I've modified the NGINX configuration to do auth_request when the cookie header is present.
I thought the APIs would accept only Token or Password authentication. That's why I didn't enable the auth_request there.

Thanks for finding the issue for me. I'm still learning on how to contribute in  GitHub. Next time I'll also search for closed issues.
