### ISSUE TITLE
Unable to execute script resource due to missing tmp directory

### ISSUE THREAD

**Issue by FalcoSuessgott** [rundeck/rundeck#5701]
**Describe the bug**
I collect my nodes through a python script. I was not able to execute the script until I created /tmp/rundeck with rundeck:rundeck as owner. 

The rundeck-daemon is started with:
`RUNDECK_TEMPDIR="${RUNDECK_TEMPDIR:-/tmp/rundeck}"`

Yet this directory has not been created by the rpm installation:

```
rpm -ql rundeck-3.1.3.20191204-1.noarch
/etc/rc.d
/etc/rc.d/init.d
/etc/rc.d/init.d/rundeckd
/etc/rundeck
/etc/rundeck/admin.aclpolicy
/etc/rundeck/apitoken.aclpolicy
/etc/rundeck/cli-log4j.properties
/etc/rundeck/framework.properties
/etc/rundeck/jaas-loginmodule.conf
/etc/rundeck/log4j.properties
/etc/rundeck/profile
/etc/rundeck/project.properties
/etc/rundeck/realm.properties
/etc/rundeck/rundeck-config.properties
/etc/rundeck/ssl
/etc/rundeck/ssl/ssl.properties
/etc/rundeck/system-job_reader.aclpolicy_template
/etc/rundeck/system-job_runner.aclpolicy_template
/etc/rundeck/system-job_viewer.aclpolicy_template
/etc/rundeck/system-job_writer.aclpolicy_template
/etc/rundeck/system-project_admin.aclpolicy_template
/var/lib/rundeck
/var/lib/rundeck/.ssh
/var/lib/rundeck/bootstrap
/var/lib/rundeck/bootstrap/rundeck-3.1.3-20191204.war
/var/lib/rundeck/cli
/var/lib/rundeck/cli/bin
/var/lib/rundeck/cli/bin/rd-acl
/var/lib/rundeck/cli/lib
/var/lib/rundeck/cli/lib/ant-1.8.3.jar
/var/lib/rundeck/cli/lib/ant-jsch-1.8.3.jar
/var/lib/rundeck/cli/lib/ant-launcher-1.8.3.jar
/var/lib/rundeck/cli/lib/commons-beanutils-1.9.4.jar
/var/lib/rundeck/cli/lib/commons-cli-1.0.jar
/var/lib/rundeck/cli/lib/commons-codec-1.10.jar
/var/lib/rundeck/cli/lib/commons-collections-3.2.2.jar
/var/lib/rundeck/cli/lib/commons-httpclient-3.1.jar
/var/lib/rundeck/cli/lib/commons-lang-2.6.jar
/var/lib/rundeck/cli/lib/commons-logging-1.2.jar
/var/lib/rundeck/cli/lib/converter-jackson-2.6.1.jar
/var/lib/rundeck/cli/lib/dom4j-2.1.1.jar
/var/lib/rundeck/cli/lib/guava-24.1.1-jre.jar
/var/lib/rundeck/cli/lib/jackson-annotations-2.10.1.jar
/var/lib/rundeck/cli/lib/jackson-core-2.10.1.jar
/var/lib/rundeck/cli/lib/jackson-databind-2.10.1.jar
/var/lib/rundeck/cli/lib/jaxen-1.1.6.jar
/var/lib/rundeck/cli/lib/jsch-0.1.55.jar
/var/lib/rundeck/cli/lib/jsch.agentproxy.connector-factory-0.0.9.jar
/var/lib/rundeck/cli/lib/jsch.agentproxy.core-0.0.9.jar
/var/lib/rundeck/cli/lib/jsch.agentproxy.jsch-0.0.9.jar
/var/lib/rundeck/cli/lib/jsch.agentproxy.pageant-0.0.9.jar
/var/lib/rundeck/cli/lib/jsch.agentproxy.sshagent-0.0.9.jar
/var/lib/rundeck/cli/lib/jsch.agentproxy.usocket-jna-0.0.9.jar
/var/lib/rundeck/cli/lib/jsch.agentproxy.usocket-nc-0.0.9.jar
/var/lib/rundeck/cli/lib/log4j-1.2.17.jar
/var/lib/rundeck/cli/lib/okhttp-3.12.0.jar
/var/lib/rundeck/cli/lib/okio-1.15.0.jar
/var/lib/rundeck/cli/lib/protobuf-java-3.5.1.jar
/var/lib/rundeck/cli/lib/retrofit-2.6.1.jar
/var/lib/rundeck/cli/lib/rundeck-core-3.1.3-20191204.jar
/var/lib/rundeck/cli/lib/rundeck-storage-api-3.1.3-20191204.jar
/var/lib/rundeck/cli/lib/rundeck-storage-conf-3.1.3-20191204.jar
/var/lib/rundeck/cli/lib/rundeck-storage-data-3.1.3-20191204.jar
/var/lib/rundeck/cli/lib/snakeyaml-1.17.jar
/var/lib/rundeck/data
/var/lib/rundeck/libext
/var/lib/rundeck/libext/attribute-match-node-enhancer-v0.1.3.jar
/var/lib/rundeck/libext/aws-s3-model-source-v1.0.2.jar
/var/lib/rundeck/libext/multiline-regex-datacapture-filter-1.0.0.jar
/var/lib/rundeck/libext/openssh-node-execution-1.0.3.zip
/var/lib/rundeck/libext/py-winrm-plugin-2.0.3.zip
/var/lib/rundeck/libext/rundeck-ansible-plugin-2.5.0.jar
/var/lib/rundeck/libext/rundeck-copyfile-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-flow-control-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-git-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-jasypt-encryption-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-job-state-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-localexec-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-object-store-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-orchestrator-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-script-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-source-refresh-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-stub-plugin-3.1.3-20191204.jar
/var/lib/rundeck/libext/rundeck-upvar-plugin-3.1.3-20191204.jar
/var/lib/rundeck/logs
/var/lib/rundeck/var
/var/lib/rundeck/var/tmp
/var/lib/rundeck/var/tmp/pluginJars
/var/lib/rundeck/work
/var/log/rundeck
```
I suggest either to change the default rundeck tmp dir location, or change the spec-file so that 
`/tmp/rundeck` gets actually created during the installation.

Furthermore the Exception was quite misleading. It said:

```
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: 
failed to execute: /var/lib/rundeck/libext/spacewalk_to_rundeck_json.py: 
java.io.IOException: No such file or directory
```
Rundeck found the File and actually executed it, but as explained earlier wasnt able to execute due to the missing tmp-directory. Maybe we should adjust the Exception to a more understandable Exception Message

**My Rundeck detail**
```
rpm -qa | grep rundeck
rundeck-3.1.3.20191204-1.noarch
```

* install type: rpm
* OS Name/version: CentOS 7.6
* DB Type/version: psql

**Comment by gangadhar01a** [comment]
@FalcoSuessgott Are you using stub plugin to copy the scirpt?

**Comment by niall-munnelly** [comment]
I can see why you might expect the RPM to create /tmp/rundeck on the Rundeck server, although I don’t know how valuable that would be in practice. /tmp is noexec in a lot of places, so the directory likely has to be changed by many users. That said, there’s no way the RPM can create a directory on your remote nodes for you.

Do you manage your inventory with a configuration management tool like puppet? We just ensure that the suitable tmpdir is created on all servers, and that path is set up as the default target dir in all our nodes’ definitions.

It’s important to remember that Rundeck’s just copying your inline scripts and remote plugins with SCP; there’s no other magic going on there. If you can’t copy a file to a nonexistent directory with SCP, then Rundeck can’t, either.

Next to using something like Puppet or Chef, your fastest solution will probably be to set up a job that creates your target temporary directory and configure your nodes to use that directory.

**Comment by FalcoSuessgott** [comment]
Thanks @gangadhar01a and @niall-munnelly  for the response.

I think you might have misunderstood my point and I may didn't explain it good enough.

I'm not talking about jobs that are executed on remote nodes. The described error occurs while trying to use a [python script](https://gist.github.com/FalcoSuessgott/ebd0f0518a82a781911018fcfb38b343)  as a node resource script on my Rundeck host, that collects all nodes from our spacewalk-server via the spacewalk-api in JSON. Here are the corresponding Rundeck Docs: https://docs.rundeck.com/docs/administration/projects/resource-model-sources/builtin.html#script-source

When the Rundeck application tries to execute that resource script, I see in in `rundeck.log`: 

```
com.dtolabs.rundeck.core.resources.ResourceModelSourceException: 
failed to execute: /var/lib/rundeck/libext/spacewalk_to_rundeck_json.py: 
java.io.IOException: No such file or directory
```

Which can be read like the script `/var/lib/rundeck/libext/spacewalk_to_rundeck_json.py` does not exist. Which is quite misleading, then what actually happens is, that the script cannot be executed because of the missing `$RUNDECK_TEMPDIR`. 

Rundecks default `$RUNDECK_TEMPDIR` is `/tmp/rundeck`. (https://docs.rundeck.com/docs/administration/configuration/system-properties.html#environment-variables-defaults). I expect that `/tmp/rundeck` is going to be created during the installation of Rundeck through RPMs. But that isn't the case.

So the question is: should we change the Rundeck RPM-spec-file so that `/tmp/rundeck` gets actually created, because obviously Rundeck relies on that directory?

Can you follow me, or am I missing something?

**Comment by niall-munnelly** [comment]
Ah, okay, I follow you, now. Your detail about populating your resources with a python script made me think you were talking about remote executions. Sorry!

**Comment by puremourning** [comment]
Just hit this exact issue, resource model provider script failing (silently) with IOException, even though the script clearly exists. ANd solution of `mkdir /tmp/rundeck` fixed it.
