### ISSUE TITLE
Upload plugin artifact to private repository fails

### ISSUE THREAD

**Issue by sjrd218** [rundeck/rundeck#5702]
**Describe the bug**
Attempting to upload a plugin artifact to a private repo configured in Rundeck results in an error. The stacktrace shows a mismatched yaml library as the cause.

**My Rundeck detail**

* Rundeck version: any version greater than 3.1.0

**To Reproduce**
Configure a private repository.
Try to add a plugin to the repo using the api.

**Expected behavior**
Plugin upload succeeds.

**Comment by lightarrow** [comment]
Hey ! I am seeing a lot of great merges and Fixes here :)
I am looking forward to upgrading to the current release.
Thanks for taking this Further.
