### ISSUE TITLE
RD_OPTION_XXXX not available when using remote machines

### ISSUE THREAD

**Issue by rockandska** [rundeck/rundeck#5709]
**Describe the bug**
The options send to a job via webhooks seem to be only available in a job if the job is run locally and not when using dispatch on remote nodes.
When taking a look at execution details for a job who has run, we could see the "options" listed in the left pane (so the job seems to have receive them) but will not be present as RD_OPTION_XXXX variables as they are available when the job is run locally.

**My Rundeck detail**

* Rundeck version: 3.2.1-SNAPSHOT
* install type: docker official
* OS Name/version: ubuntu 18.04
* DB Type/version: postgres

**To Reproduce**
1. Create a job who execute `declare -p` and ask to run this job on a remote node
2. Create a `run-job` webhook who call our previously created job with options coming from the json payload : `-test ${data.test}`
3. Call this webhook with a valid json corresponding to the options previously configured in the webhook : `{ "test" : "test" }`
4. The options will be present in the execution detail for the execution of the job but will be not available as RD_OPTION_XXXX

**Expected behavior**
Having RD_OPTION_XXXX available as if we run the job locally

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser : firefox
 - Version : 71

**Comment by niall-munnelly** [comment]
I don’t think this is unique to webhooks; you’ll see it in remote script plugins, too.

You need to configure your remote machine’s sshd to accept RD env variables:

https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html#passing-environment-variables-through-remote-command

You may not get this cleared with your infosec team or other admins; I work around it by explicitly passing options as arguments to the scripts in my plugins and not relying on RD_* envvars.

**Comment by rockandska** [comment]
Thanks @niall-munnelly for pointing me at the right place in the docs.

I was thinking that Rundeck was able to parse "RD_OPTION_XXXX" before sending the command and add those vars itself to the command without the need to modify sshd_config.

Wouldn't be doable to automatically add all RD_OPTION_ vars to the command ?

**Comment by niall-munnelly** [comment]
Rundeck would need to parse/eval the script variables before copying them to the remote machines, and while I can’t say how difficult that would be to implement, I know it doesn’t now - at least, not in a plugin context. We do see it in online scripts where RD_OPTION_FOO is @option.foo@, so maybe it’s not beyond the realm of possibility.
