### ISSUE TITLE
Inline script not executing

### ISSUE THREAD

**Issue by gangadhar01a** [rundeck/rundeck#5714]
**Describe the bug**
We have a bash inline script which was executed successfully without any issue and we are not sure what exactly has been changed but the following error has resulted whenever executed the job

09:07:39 | [stub] copy local file to node rundeck: /tmp/0-1054-rundeck-dispatch-script.tmp.sh
-- | --
09:07:39 | chmod: cannot access ‘/tmp/0-1054-rundeck-dispatch-script.tmp.sh’: No such file or directory
09:07:39 | Result: 1
09:07:39 | Failed: NonZeroResultCode: Result code was 1

I have read about stub plugin, as per my findings this plugin will execute the script without copying to the machine but the log output showing it's trying to cop the scipt. 
**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
rundeck 3.2.1-20200113
* install type: [choose: rpm,deb,war,launcher]
RPM
* OS Name/version: [e.g. ubuntu 16.04]
CentOS 7
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]
MySql

**Comment by MegaDrive68k** [comment]
Hi @gangadhar01a 

You can define the destination copy file path different to  `/tmp`, take a look at this:

https://github.com/rundeck/rundeck/issues/1112#issuecomment-99139536

Hope it helps!

**Comment by gangadhar01a** [comment]
Let me try @MegaDrive68k
