### ISSUE TITLE
How to connect rundeck to mysql

### ISSUE THREAD

**Issue by manishalankala** [rundeck/rundeck#5717]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: 3.
* install type: wget https://dl.bintray.com/rundeck/rundeck-deb/rundeck_3.2.1.20200113-1_all.deb
dpkg -i rundeck_3.2.1.20200113-1_all.deb
* OS Name/version: [e.g. ubuntu 18]
* DB Type/version: [mysql or mariadb]

**To Reproduce**
vi /etc/rundeck/framework.properties 
framework.server.name = servername
framework.server.hostname = servername
framework.server.port = 4440
framework.server.url = http://servername:4440

service rundeckd restart

vi /etc/rundeck/realm.properties

admin:admin
admin:password

vi /etc/rundeck/rundeck-config.properties
dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true
dataSource.url = jdbc:mysql://servername:3306/
dataSource.username=rundeckuser
dataSource.password=your-password
dataSource.driverClassName=com.mysql.jdbc.Driver

# Restart rundeck
service rundeckd restart

**Expected behavior**

what has to be given here and what else changes  to be done on rundeck-config.properties for connecting my db

dataSource.url = jdbc:mysql://servername:3306/

**Screenshots**
![image](https://user-images.githubusercontent.com/33985509/72731028-16626580-3b93-11ea-9c87-962f4cf936f6.png)

**Desktop (please complete the following information):**
 - OS: [e.g. windows]
 - Browser [e.g. chrome]
 - Version [e.g. ]

**Additional context**

cat rundeck-config.properties
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/var/lib/rundeck

###rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
### change hostname here
grails.serverURL=http://servername:4440
dataSource.dbCreate = update
dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true

### Encryption for key storage
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=keys

rundeck.storage.converter.1.type=jasypt-encryption
rundeck.storage.converter.1.path=keys
rundeck.storage.converter.1.config.encryptorType=custom
rundeck.storage.converter.1.config.password=b2072afcd0b3879c
rundeck.storage.converter.1.config.algorithm=PBEWITHSHA256AND128BITAES-CBC-BC
rundeck.storage.converter.1.config.provider=BC

### Encryption for project config storage
rundeck.projectsStorageType=db

rundeck.config.storage.converter.1.type=jasypt-encryption
rundeck.config.storage.converter.1.path=projects
rundeck.config.storage.converter.1.config.password=b2072afcd0b3879c
rundeck.config.storage.converter.1.config.encryptorType=custom
rundeck.config.storage.converter.1.config.algorithm=PBEWITHSHA256AND128BITAES-CBC-BC
rundeck.config.storage.converter.1.config.provider=BC

rundeck.log4j.config.file = /etc/rundeck/log4j.properties

rundeck.feature.repository.enabled=true

java --version
openjdk version "1.8.0_232"
OpenJDK Runtime Environment (build 1.8.0_232-8u232-b09-0ubuntu1~18.04.1-b09)
OpenJDK 64-Bit Server VM (build 25.232-b09, mixed mode)

mysql -V
mysql  Ver 15.1 Distrib 10.1.43-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

rundeck version
rundeck_3.2.1

**Comment by MegaDrive68k** [comment]
Hi @manishalankala 

You need to provide the connection string in your rundeck-config.properties file, like this:


Check this:

https://docs.rundeck.com/docs/administration/configuration/database/mysql.html#install-mysql

**Comment by manishalankala** [comment]
CREATE DATABASE rundeck CHARACTER SET utf8;
CREATE USER 'rundeck'@'serverip' IDENTIFIED BY 'rundeck';
GRANT ALL PRIVILEGES ON  rundeck.* TO 'rundeck'@'serverip';
FLUSH PRIVILEGES;

i did try to change my mysql configuration file

/etc/mysql/mysql.conf.d#

bind address : serverip

but still i see localhost
![image](https://user-images.githubusercontent.com/33985509/72889036-1dae7e00-3d0f-11ea-95fa-5811a0eed235.png)

it worked as when i gave  localhost instead a server ip


![image](https://user-images.githubusercontent.com/33985509/72888738-6e71a700-3d0e-11ea-9c59-9ca0d5b66318.png)
