### ISSUE TITLE
Improve active directory support to just require domain

### ISSUE THREAD

**Issue by josephholsten** [rundeck/rundeck#572]
When using Jenkins, it is possible to have complete active directory integration simply from the domain.

I'm not entirely sure how this works, but you should be able to use DNS SRV record discovery for `_ldap._tcp.{domain}` to discover LDAP servers for the domain. I'm pretty sure they bind using the username/password used for sign in. Then I believe they use `CN=Users,DC=example,DC=net` for user base DN and `CN=Groups,DC=example,DC=net` for role base DN.

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
