### ISSUE TITLE
Container JAAS_LDAP optional settings do not result in a valid configuration file

### ISSUE THREAD

**Issue by cammoraton** [rundeck/rundeck#5731]
**Describe the bug**
For the official docker container, the remco template doesn't render a valid jaas-loginmodule.conf when any of  the optional settings roleUsernameMemberAttribute, ignoreRoles, storePass, clearPass, useFirstPass, tryFirstPass, userLastNameAttribute, userFirstNameAttribute, userEmailAttribute or nestedGroups is set. The resulting scope change results in unintended behavior.

It also doesn't wrap any of these settings in quotes as the other variables do. The practical impact is a broken ldap and being unable to map emails, displaynames, and the like correctly. It also results in a completely broken rundeck if the environmental variables are not wrapped in quote.
 
**My Rundeck detail**

* Rundeck version: 3.2.0
* install type: Docker
* OS Name/version: CentOS 7
* DB Type/version: postgres

**To Reproduce**
1. Instantiate an instance of rundeck with any of:
- RUNDECK_JAAS_LDAP_USERLASTNAMEATTRIBUTE=somevalue
- RUNDECK_JAAS_LDAP_USERFIRSTNAMEATTRIBUTE=somevalue
- RUNDECK_JAAS_LDAP_USEREMAILATTRIBUTE=somevalue
2. Inspect the resulting configuration file via execing into the container(e.g. via docker exec -it rundeck /bin/sh) and see the spacing and quote errors in /home/rundeck/server/config/jaas-loginmodule.conf
3. Configure valid LDAP with valid role bindings and the above wrapped in quotes.
4. Attempt to login.

**Expected behavior**
For things to work as documented.

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser: Google Chrome
 - Version  79.0.3945.117 

**Additional context**

**Comment by cammoraton** [comment]
Attempted to fix this in https://github.com/rundeck/rundeck/pull/5732

**Comment by gschueler** [comment]
fixed by #5732
