### ISSUE TITLE
Enforced from Allowed Values fails  when option value is used in Remote URL (persists)

### ISSUE THREAD

**Issue by sebastianbello** [rundeck/rundeck#5733]
**Describe the bug**
Enforced from Allowed Values fails if a previous option value is used in Remote URL for a second value. 

Original issue was closed/ addressed : 
https://github.com/rundeck/rundeck/issues/5120

However, the issue persists in versions 3.1.3 / 3.2.1 ( and newer )when using a specific setup:
https://github.com/rundeck/rundeck/issues/5120#issuecomment-564461091

**My Rundeck detail**

* Rundeck version: 3.1.3 / 3.2.1 ( and newer ) 
* install type:  Any
* OS Name/version: Ubuntu 16.04 (Any) 
* DB Type/version: Any

**To Reproduce**

1. Simple first option OPT1 : type text, no restriction
2. Second option OPT2 (type text) with Allowed Values from Remote URL
3. Use OPT1 value in this URL
4. Choose restriction : Enforced from Allowed Values
5. On page, choosing options, OPT2 shows the correct list from URL if OPT1 is filled in
6. The restriction fails with an empty list on clic "Run Job Now"

**Additional context**

Additional info regarding the persistent issue in: 
https://github.com/rundeck/rundeck/issues/5120#issuecomment-569629307

( internal info also provided via mail )

**Comment by carlgevans** [comment]
We are also seeing this with v3.2.1-20200113, it was ok in v3.0.x something prior to the upgrade.

Option VLANID value: 2 was not in the allowed values: []

This is a sample of the JSON. we are not using option values in this particular URL.

[
{
"name": "Default VLAN, Do Not Use",
"value": 1
},
{
"name": "Test",
"value": 2
}
]
