### ISSUE TITLE
Rundeck not able to send email

### ISSUE THREAD

**Issue by EswanthNTS** [rundeck/rundeck#5751]
**Describe the bug**
Rundeck not able to send email

**My Rundeck detail**
My Rundeck is not able to send email notifications as my jobs are getting succeeded since i am using Rundeck in the docker container
Image used:  jordan/rundeck:latest
My jobs are getting succeeded only thing is i am not able to send emails 
![image](https://user-images.githubusercontent.com/43998903/73664099-bc839480-4696-11ea-8e3c-289c71affc74.png)

Below is my config file please check 
![image](https://user-images.githubusercontent.com/43998903/73664616-9dd1cd80-4697-11ea-9f6a-2324dfaa06d1.png)

**Comment by MegaDrive68k** [comment]
Hi @EswanthNTS 

You need to provide this information:

```
grails.mail.host=smtp.yourserver.com
grails.mail.port=25
grails.mail.username=your-smtp-server-username
grails.mail.password=your-smtp-server-password
```

In your capture, I can see only `grails.mail.host` and` grails.mail.port`.

Take a look at this:

https://docs.rundeck.com/docs/administration/configuration/email-settings.html#email-settings

Greetings!
