### ISSUE TITLE
connect jetty logging into the log4j stack

### ISSUE THREAD

**Issue by josephholsten** [rundeck/rundeck#576]
While attempting to debug a incorrect configuration in our ldap authn, I had the hardest time trying to turn on debug logs from [JettyCachingLdapLoginModule](https://github.com/dtolabs/rundeck/blob/v1.6.2/rundeck-launcher/rundeck-jetty-server/src/main/java/com/dtolabs/rundeck/jetty/jaas/JettyCachingLdapLoginModule.java#L580). 

Turns out that while the jetty logger is writing to stdout, it is not going through any of loggers attached to the stdout console appender defined in my local log4j.properties. 

Instead, it's using the embedded jetty logging, per http://docs.codehaus.org/display/JETTY/Debugging. Thus the only way to turn up the jetty logging is to add the `-DDEBUG` flag to the command line.

This should probably be replaced with the normal logging stack.

**Comment by gschueler** [comment]
I will close the issue. If you still have this problem, please re-open this issue.
