### ISSUE TITLE
Switch default node executor to OpenSSH instead of jsch

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#5772]
Hi guys,

I've been following the development of jsch (waiting for features like ed25519 key support etc) and it seems pretty much non-existant now: https://sourceforge.net/projects/jsch/files/. The last update was in Nov 2018.

Would it make sense to switch to OpenSSH as the default node executor now? Are there any performance benefits to staying with jsch (since it's native java)?

Cheers

**Comment by puremourning** [comment]
Using openSSH makes a bunch of stuff harder to use like keys and pass phrases and the ssh agent. 

Richard explains it quite well here: https://github.com/rundeck/rundeck/issues/5609

**Comment by binaryfire** [comment]
I see, thanks. That's a shame. I hadn't even considered multiplexing- that would provide a nice performance bump in certain situations too.
