### ISSUE TITLE
Move or rename jobs process

### ISSUE THREAD

**Issue by uvaidbi** [rundeck/rundeck#579]
I had to move and rename 40 jobs to a different tree but under the same Projects/platform but the only option i see is to do this manually. I wish there is a command or any process to do this in a better way .

Is there a command or anything that i can use move the jobs ?

**Comment by fdevans** [comment]
In an effort to focus on bugs and issues that impact currently supported versions of Rundeck, we have elected to notify GitHub issue creators if their issue is classified as stale and close the issue. An issue is identified as stale when there have been no new comments, responses or other activity within the last 12 months. If a closed issue is still present please feel free to open a new Issue against the current version and we will review it. If you are an enterprise customer, please contact your Rundeck Support to assist in your request.
Thank you, The Rundeck Team
