### ISSUE TITLE
[eduler_Worker-5] rundeck.services.ExecutionService  : Failed while starting execution: 11732183

### ISSUE THREAD

**Issue by venkategowdap** [rundeck/rundeck#5792]
Hi Team , 

While Executing one of Scheduled job, am getting below error from Rundeck 3.0.x .
Please let us know any input on this issue .

2020-02-11 01:00:03.081 ERROR --- [eduler_Worker-5] rundeck.services.ExecutionService        : Failed while starting execution: 11732183

org.springframework.dao.DataAccessResourceFailureException: Hibernate operation: could not prepare statement; SQL [select schedulede0_.id as id1_15_0_, schedulede0_.version as version2_15_0_, schedulede0_.do_nodedispatch as do_noded3_15_0_, schedulede0_.log_output_threshold as log_outp4_15_0_, schedulede0_.next_execution as next_exe5_15_0_, schedulede0_.date_created as date_cre6_15_0_, schedulede0_.calendar as calendar7_15_0_, schedulede0_.node_keepgoing as node_kee8_15_0_, schedulede0_.node_exclude_os_arch as node_exc9_15_0_, schedulede0_.uuid as uuid10_15_0_, schedulede0_.node_include as node_in11_15_0_, schedulede0_.success_on_empty_node_filter as success12_15_0_, schedulede0_.node_exclude_os_version as node_ex13_15_0_, schedulede0_.timeout as timeout14_15_0_, schedulede0_.change_request as change_15_15_0_, schedulede0_.node_exclude_precedence as node_ex16_15_0_, schedulede0_.node_exclude_name as node_ex17_15_0_, schedulede0_.notify_avg_duration_threshold as notify_18_15_0_, schedulede0_.calendar_hour as calenda19_15_0_, schedulede0_.day_of_week as day_of_20_15_0_, schedulede0_.node_include_os_version as node_in21_15_0_, schedulede0_.node_exclude_os_name as node_ex22_15_0_, schedulede0_.retry as retry23_15_0_, schedulede0_.cron_array as cron_ar24_15_0_, schedulede0_.filter as filter25_15_0_, schedulede0_.group_path as group_p26_15_0_, schedulede0_.scheduled as schedul27_15_0_, schedulede0_.orchestrator_id as orchest28_15_0_, schedulede0_.node_threadcount_dynamic as node_th29_15_0_, schedulede0_.node_include_name as node_in30_15_0_, schedulede0_.multiple_executions as multipl31_15_0_, schedulede0_.time_zone as time_zo32_15_0_, schedulede0_.rduser as rduser33_15_0_, schedulede0_.node_include_os_name as node_in34_15_0_, schedulede0_.node_exclude as node_ex35_15_0_, schedulede0_.node_rank_order_ascending as node_ra36_15_0_, schedulede0_.nodes_selected_by_default as nodes_s37_15_0_, schedulede0_.node_include_os_arch as node_in38_15_0_, schedulede0_.loglevel as logleve39_15_0_, schedulede0_.advanced_schedule_enabled as advance40_15_0_, schedulede0_.node_exclude_os_family as node_ex41_15_0_, schedulede0_.execution_enabled as executi42_15_0_, schedulede0_.max_multiple_executions as max_mul43_15_0_, schedulede0_.node_include_os_family as node_in44_15_0_, schedulede0_.last_updated as last_up45_15_0_, schedulede0_.retry_delay as retry_d46_15_0_, schedulede0_.workflow_id as workflo47_15_0_, schedulede0_.exec_count as exec_co48_15_0_, schedulede0_.month as month49_15_0_, schedulede0_.hour as hour50_15_0_, schedulede0_.log_output_threshold_action as log_out51_15_0_, schedulede0_.arg_string as arg_str52_15_0_, schedulede0_.user_role_list as user_ro53_15_0_, schedulede0_.total_time as total_t54_15_0_, schedulede0_.node_rank_attribute as node_ra55_15_0_, schedulede0_.server_nodeuuid as server_56_15_0_, schedulede0_.default_tab as default57_15_0_, schedulede0_.node_exclude_tags as node_ex58_15_0_, schedulede0_.seconds as seconds59_15_0_, schedulede0_.ref_exec_count as ref_exe60_15_0_, schedulede0_.node_threadcount as node_th61_15_0_, schedulede0_.node_include_tags as node_in62_15_0_, schedulede0_.job_name as job_nam63_15_0_, schedulede0_.calendar_minute as calenda64_15_0_, schedulede0_.schedule_enabled as schedul65_15_0_, schedulede0_.year as year66_15_0_, schedulede0_.day_of_month as day_of_67_15_0_, schedulede0_.node_filter_editable as node_fi68_15_0_, schedulede0_.log_output_threshold_status as log_out69_15_0_, schedulede0_.description as descrip70_15_0_, schedulede0_.minute as minute71_15_0_, schedulede0_.project as project72_15_0_ from scheduled_execution schedulede0_ where schedulede0_.id=?]; The connection attempt failed.; nested exception

**My Rundeck detail**

* Rundeck version: 3.0.x
* install type: War
* OS Name/version: Linux
* DB Type/version: PostgresDB

**Comment by MegaDrive68k** [comment]
Hi @venkategowdap 

Try this: 

https://github.com/rundeck/rundeck/issues/4359#issuecomment-473498265

Seems the same issue.

Regards!

**Comment by venkategowdap** [comment]
@MegaDrive68k : am not using dataSource.properties.maxActive property at all (dataSource.properties.maxActive=100 ) . Is that good to limit this way ..?

**Comment by z079449** [comment]
@MegaDrive68k : The  #4359 issue related to pool count .  In our issue poot is good and its simply throwing "Hibernate operation: could not prepare statement;" error and execution is failing . Any tool bug related to this issue ?

Thanks
Venkat

> Hi @venkategowdap
> 
> Try this:
> 
> [#4359 (comment)](https://github.com/rundeck/rundeck/issues/4359#issuecomment-473498265)
> 
> It seems the same issue.
> 
> Regards!

**Comment by z079449** [comment]
> @MegaDrive68k : The #4359 issue related to pool count . In our issue poot is good and its simply throwing "Hibernate operation: could not prepare statement;" error and execution is failing . Any tool bug related to this issue ?
> 
> Thanks
> Venkat
> 
> > Hi @venkategowdap
> > Try this:
> > [#4359 (comment)](https://github.com/rundeck/rundeck/issues/4359#issuecomment-473498265)
> > It seems the same issue.
> > Regards!

@MegaDrive68k :  In #4359 issue , they are facing pool empty issue ( copied from that issue )  , but in our issue we have enough pool ( pool count is 200 ) . We also faced this earlier and after increasing , pool count issue resolved for us .
****[quartzScheduler_Worker-125] Timeout: Pool empty. Unable to fetch a connection in 10 seconds, none available[size:51; busy:51; idle:0; lastwait:10000].****  

Now , we are facing  **"could not prepare statement; SQL "** issue ( below i copied the portion of the issue) very frequently .
Please help me with this issue ..

org.springframework.dao.DataAccessResourceFailureException: Hibernate operation: could not prepare statement; SQL [select schedulede0_.id as id1_15_0_, schedulede0_.version as version2_15_0_, schedulede0_.do_nodedispatch as
Thanks
Venkat

**Comment by z079449** [comment]
@MegaDrive68k :  We have rundeck configuration set at side and Rundeck as DB Max Count is 300 and Pool Count also 300. ..Still we are getting this issue : ailed to start execution: org.springframework.dao.DataAccessResourceFailureException: Hibernate operation: could not prepare statement; SQL [select schedulede0_.id as id1_15_0_, schedulede0_.version as version2_15_0_, schedulede0_.do_nodedispatch as do_noded3_15_0_, schedulede0_.log_output_threshold as log_outp4_15_0_, schedulede0_.next_execution as next_exe5_15_0_, schedulede0_.date_created as date_cre6_15_0_, schedulede0_.calendar as calendar7_15_0_, schedulede0_.node_keepgoing as node_kee8_15_0_, schedulede0_.node_exclude_os_arch as node_exc9_15_0_, schedulede0_.uuid as uuid10_15_0_, schedulede0_.node_include as node_in11_15_0_, schedulede0_.success_o
 The connection attempt failed.; nested exception is org.postgresql.util.PSQLException: The connection attempt failed.

**Comment by ProTip** [comment]
@z079449 What is your quartz pool thread count set to? How many database connections are active when this error occurs?

**Comment by z079449** [comment]
@ProTip :  Quartz pool thread count is set to 300 ..When we got this problem active was count 80 out of Max Count 300

**Comment by ProTip** [comment]
I would recommend the following:

* Set max active connections to three times the thread pool count: `900`
* Ensure postgres is configured with `max_connections = 900`; the default is `100`
* Rundeck needs a lot of file handles so make sure the soft and hard open file limits _for the Rundeck server user_ are set high(I might even put it over `1000000` so it never causes a problem): https://docs.rundeck.com/docs/administration/maintenance/tuning-rundeck.html#file-descriptors .

**Comment by duduhandelman** [comment]
Greg.
Recently I needed to increase the fd limit on Ubuntu and found out that using systemd has it's own limit maximum tasks so it was blocking as well.
At the end I have set the default value in systemd for all services.

Thanks David.


Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by z079449** [comment]
@ProTip :  Thanks ..let me apply these changes and get back with result .

**Comment by z079449** [comment]
@ProTip :  We took staggered approach and applied max_connections = 600 and file handles to 65000 but still some issue , hope we need to increase to your number and see ..Thanks
