### ISSUE TITLE
Allow grails.serverURL parameter to be optional to support multiple URLs

### ISSUE THREAD

**Issue by nikosmeds** [rundeck/rundeck#5795]
**Is your feature request related to a problem? Please describe.**

I would like Rundeck to be available via multiple URLs/DNS records.

We have Rundeck in a private subnet and HAProxy in a public subnet. I would like to:
- access Rundeck directly via DNS record for itself (e.g. allows `rd` CLI tool to configure projects/jobs locally on the server)
- access Rundeck indirectly via DNS record for HAProxy (e.g. allows company staff access to Rundeck without access to private subnet)

Removing `grails.serverURL=` parameter from `/etc/rundeck/rundeck-config.properties` allows us to login from either, however jobs will no longer run.

```
$ less /var/log/rundeck/service.log
java.lang.IllegalStateException: Attribute absolute='true' specified but no grails.serverURL set in Config
```

There appears to be no means of overriding the `absolute='true'` attribute.

**Describe the solution you'd like**

Add support for overriding the `absolute='true'` attribute.

**Describe alternatives you've considered**

- installing a local proxy (e.g nginx) on the server and set `grails.serverURL` to `localhost` (perhaps works? - but requires additional services)
- moving Rundeck to public subnet and allowing staff to directly access

Both alternatives are outside of the scope of Rundeck configuration. Would love to see support for multiple URLs added!

**Comment by niall-munnelly** [comment]
+1 here, but it's something I asked about in January 2019 and was advised that it's not possible.
