### ISSUE TITLE
A way to modify node resources

### ISSUE THREAD

**Issue by akumarcn1503** [rundeck/rundeck#5804]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**
Currently, I can't find a way to modify a node's attributed easily. 
 
**Describe the solution you'd like**
I would like to modify(add/remove/change) a node's attributed in an easy way like from a node's details pages.  
<img width="416" alt="Screenshot 2020-02-19 at 2 20 43 PM" src="https://user-images.githubusercontent.com/53426603/74818155-2309e300-5324-11ea-826a-1e141d5ef107.png">
I would like to change decision attribute from here, or add/remove new/existing attrs.

**Describe alternatives you've considered**
I looked at node enhancer plugin, but on digging further I found that it stores a list of changes to be applied which may create problems on adding new sources. It doesn't actually modify node resources.

**Comment by fdevans** [comment]
We are working on a new Node Source plugin that will be released sometime in Q2 to address this.  To be notified please sign up for our Release Notes on https://www.rundeck.com/rundecker using the "Get Notified" buttong.
