### ISSUE TITLE
log4j issue within docker/openshift

### ISSUE THREAD

**Issue by pdev77** [rundeck/rundeck#5805]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: Rundeck 3.1.2-20190927 
* install type: https://hub.docker.com/r/rundeck/rundeck:3.1.2
* OS Name/version: na
* DB Type/version: mariadb

**Expected Behavior**
If file is chosen as logging strategy - log to file and not to console.

**How to Reproduce**
Chosen logging stretegy is 'file', set by env var:RUNDECK_LOGGING_STRATEGY=file
The remco template says:
`# Enable logging for everything. Rarely useful`
`log4j.rootLogger=warn, stdout {% if strategy == "FILE" %}, file{% endif %}`

1) The following is observed on the console:
`log4j:ERROR Could not instantiate appender named "file".`

2) its not possible to control the on/off element of this 'rarely useful' logging without overriding the remco template anyway

3) Whatever the configuration, the following is always seen on the console:
`log4j:WARN No appenders could be found for logger (com.dtolabs.rundeck.core.plugins.JarPluginScanner).`
`log4j:WARN Please initialize the log4j system properly.`
`log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig  for more info.`

**Comment by pdev77** [comment]
Issue still present in rundeck 3.2.9

**Comment by fdevans** [comment]
Hi @pdev77.  Our current version is 3.3.9. If you can confirm it's still an issue there we can reopen the ticket.  

> Note: In 3.3 series we are now using log4j2.
