### ISSUE TITLE
Unable to build - Can not connect to Ryuk

### ISSUE THREAD

**Issue by cloudguy23** [rundeck/rundeck#5806]
**Describe the bug**
Unable to build from source on CentOS 7.

**My Rundeck detail**

* Rundeck version: 3.2.2-20200204
* install type: source
* OS Name/version: centos 7
* DB Type/version: n/a

**To Reproduce**
Attempting to build rundeck.    I've created the attached Vagrant file to setup the environment.   

```
## cd /rundeck
vagrant up

> Configure project :
Building version 3.2.2-SNAPSHOT

> Task :rundeckapp:copyPluginLibs
copying plugin libs

> Task :plugins:object-store-plugin:test

org.rundeck.plugin.objectstore.tree.ObjectStoreTreeWithDirectAccessDirSourceTest > classMethod FAILED
    java.lang.IllegalStateException at ObjectStoreTreeWithDirectAccessDirSourceTest.groovy:38

38 tests completed, 1 failed

> Task :plugins:object-store-plugin:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':plugins:object-store-plugin:test'.
> There were failing tests. See the report at: file:///vagrant/plugins/object-store-plugin/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.8/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 1m 13s
156 actionable tasks: 11 executed, 145 up-to-date

Publishing build scan...
https://gradle.com/s/kqcknhmc5nlb4
```

Scan reports back 
`:plugins:object-store-plugin:test » org.rundeck.plugin.objectstore.tree.ObjectStoreTreeWithDirectAccessDirSourceTest » classMethod (0.025s)
Can not connect to Ryuk`

Scan is available at https://gradle.com/s/kqcknhmc5nlb4 

**Expected behavior**
Successful build.

**Screenshots**
n/a

**Desktop (please complete the following information):**
n/a

Vagrantfile:
```
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
  
    # Customize the amount of memory on the VM:
    vb.memory = "4096"
  end
  config.vm.provision "shell", inline: <<-SHELL
    ## https://github.com/rundeck/rundeck/wiki/Building-and-Testing
    sudo yum -y install epel-release
    sudo yum -y install java-1.8.0-openjdk java-1.8.0-openjdk-devel \
      git pandoc ghc-pandoc ghc-pandoc-citeproc net-tools docker
    sudo systemctl enable docker
    sudo systemctl start docker
    curl -sL https://rpm.nodesource.com/setup_12.x | sudo bash -
    sudo yum install -y nodejs
    curl -sL https://dl.yarnpkg.com/rpm/yarn.repo | sudo tee /etc/yum.repos.d/yarn.repo
    sudo yum install -y yarn
    export JAVA_HOME=$(dirname $(dirname $(readlink $(readlink $(which javac)))))
    export TESTCONTAINERS_RYUK_DISABLED=true
    ## https://www.bountysource.com/issues/64136846-can-not-connect-to-ryuk-at-localhost
    ## https://github.com/testcontainers/testcontainers-java/issues/700
    cd /vagrant
    sudo ./gradlew build  
    # cd packaging && make rpm
  SHELL
end
```

**Comment by sjrd218** [comment]
The object store plugin tests use Testcontainers to provide a dockerized minio server to test against. It appears that your vagrant configuration has explicitly disabled Testcontainers (`export TESTCONTAINERS_RYUK_DISABLED=true`). You may need to use a different method to build Rundeck.

**Comment by cloudguy23** [comment]
@sjrd218 I appreciate your feedback..   I'm not attempting to deviate from build procs published on the wiki.   At this point just want to get a stable recepie to build the thing consistently vs. reinventing the wheel.   

`TESTCONTAINERS_RYUK_DISABLED=true` was in response to the Ryuk error above.   Didn't help.   I'm asking what is the "official" build recipe for rundeck...

**Comment by ProTip** [comment]
Hi @cloudguy23 ,

Docker is currently required for a `./gradlew build` to complete with all tests; I have updated the Wiki to reflect the requirement.

Our "official" build recipes are encapsulated in TravisCI and CircleCI configurations:
[Rundeck TravisCI](https://github.com/rundeck/rundeck/blob/master/.travis.yml)
[Rundeck CircleCI](https://github.com/rundeck/rundeck/blob/master/.circleci/config.yml)
[Rundeck Packaging(rpm/deb)](https://github.com/rundeck/packaging-core/blob/master/.travis.yml)

That said `./gradlew build`, or `./gradlew -x check build` to skip tests, should be sufficient to produce the usable `war` file in `rundeck/rundeckapp/build/libs`.

**Comment by gschueler** [comment]
@cloudguy23 performing `export` followed by `sudo` is likely not going to work, the environment variable will not be available to the gradle process.  you should use `sudo TESTCONTAINERS_RYUK_DISABLED=true ./gradlew build`

**Comment by cloudguy23** [comment]
@gschueler Thanks for catching that.  Ran as suggested, built the WAR file successfully..  Thank you!

**Comment by cloudguy23** [comment]
@ProTip Thanks for clarifying / update.   With respect to packaging, the recommenced recipe in the wiki is not longer valid given travis.yml?  I'm looking to build an RPM.
