### ISSUE TITLE
SCM export plugin can't see changes in jobs

### ISSUE THREAD

**Issue by leshik** [rundeck/rundeck#5808]
**Describe the bug**

After the initial configuration, the SCM export plugin was working and I was able to commit my jobs to Github repo. Then I needed to conduct some experiments with jobs.

I duplicated one of the jobs and made some changes there. Then I changed all other jobs that were referencing the first job to reference the second, experimental job. Committed changes to Github successfully.

Then I deleted the first job and renamed the experimental job to the name of the first one. Then updated its name in referencing jobs (not sure it was necessary as it was referred by UUID, but anyway). After that, again, I was able to successfully commit changes to Github, but noticed that the definition for the experimental job (which was renamed) wasn't deleted. SCM export simply didn't delete the definition for the deleted job.

I cloned the repo to my local machine, deleted this definition, and force pushed back. After that, no matter what I do Rundeck doesn't see any changes to any jobs. I tried to delete the SCM folder, disable/enable SCM export, cleanup & even redeploy the whole container – nothing helps. I see the repo is cloned to the SCM folder and has the correct history, I can download the job definition and compare it manually with the git version and it obviously has changes, but Rundeck is unable to pick them up.

Thus there are 2 issues:

1. SCM export doesn't delete non-existent definitions from git;
2. SCM export can't see changes in jobs when they are obviously present.

**My Rundeck detail**

* Rundeck version: `3.2.2`
* install type: `official Docker image launched on AWS fargate`
* DB Type/version: `mysql`

**Additional context**

SCM export configuration:

```
Committer Name: ${user.fullName}
Committer Email: ${user.email}
Export UUID Behavior: preserve
Synchronize Automatically: true
Create Branch if it doesn't exist: Yes
Base branch on: master
File Path Template: ${job.project}/${job.group}${job.name}.${config.format}
Base Directory: var/scm/MyProject
Git URL: ssh://git@github.com/myname/rundeck-definitions.git
Branch: master
SSH: Strict Host Key Checking: no
SSH Key Storage Path: keys/github/rundeck/scm-key
Format: yaml
Fetch Automatically: true
```

**Comment by fdevans** [comment]
@leshik There are quite a few updates we are doing in the forthcoming 3.4.0 version of Rundeck for the SCM plugins.  Hopefully those will address your issues here as well.
