### ISSUE TITLE
Regression: json with "selected" flag cannot be used as default value in required options

### ISSUE THREAD

**Issue by luflow** [rundeck/rundeck#5810]
**Describe the bug**
At the moment the feature implemented in #4694 respective #2531 doesn't work anymore - it just throws an error `ERROR rundeck.controllers.EditOptsController - getRemoteJSON error: Cannot get property 'project' on null object` in the logs

Seems like the object declared on this line is null? https://github.com/rundeck/rundeck/blob/master/rundeckapp/grails-app/controllers/rundeck/controllers/EditOptsController.groovy#L565

**My Rundeck detail**

* Rundeck version: 3.2.2
* install type: rpm
* OS Name/version: ubuntu 16.04
* DB Type/version: mysql

**To Reproduce**
Steps to reproduce the behavior: Reproduce a setting like described in #2531 
1. Create a new job with an option
2. Add a json file as `Remote URL`
3. Enable `Required`
4. Add sheduling to task
5. Save
6. See error on screen "Specify a Default Value for Required options when the Job is scheduled.
" and the exception error in the log.

**Expected behavior**
The job should be saved and the next scheduled execution uses all json item that are marked "selected" as default option.

**Comment by jothoma1** [comment]
Same here with Rundeck 3.2.5

**Comment by jothoma1** [comment]
Hello, nobody have this bug ? we cannot schedule our jobs with remote URL

**Comment by christi3k** [comment]
We are also encountering this issue and it is a significant one for us. It occurs on Rundeck ver **3.3.0** as well as 3.2.2-20200204. We are using **Ubuntu 18.04.4 LTS** via bintray .deb install with MySQL. 

In our case we are able to configure the job just fine via the Rundeck UI. We accomplish this either by specifying a default value or by making the option not required. However, when scheduling is enabled for the job it errors out. There's nothing in the UI to indicate this is happening, but there are errors in `service.log` (see below).

I've created a simple job to demonstrate the issue:

```xml
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option enforcedvalues='true' name='my_option_remote' valuesUrl='file://${rundeck.basedir}/remote_options.json' />
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <group>scheduling-issues</group>
    <id>b87fc331-8a99-4958-862b-079c34f7cf4c</id>
    <loglevel>INFO</loglevel>
    <name>bash job with options (remote file list)</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <schedule>
      <dayofmonth />
      <month day='*' month='*' />
      <time hour='*' minute='0/2' seconds='0' />
      <year year='*' />
    </schedule>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <script><![CDATA[echo $RD_OPTION_MY_OPTION_REMOTE]]></script>
        <scriptargs />
      </command>
    </sequence>
    <uuid>b87fc331-8a99-4958-862b-079c34f7cf4c</uuid>
  </job>
</joblist>
```

Here are the contents of `remote_options.json`:

```json
[
  {
    "name": "apples",
    "value": "apples",
    "selected": true
  },
  {
    "name": "oranges",
    "value": "oranges"
  },
  {
    "name": "strawberries",
    "value": "strawberries"
  }
]
```

When run mannually via the Rundeck UI, the job completes successfully and the output is `apples`. However, scheduled executions generate the following error in `service.log`:

```
[2020-07-07T18:30:00,055] ERROR quartzjobs.ExecutionJob - Unable to start Job execution: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
java.lang.IllegalStateException: No thread-bound request found: Are you referring to request attributes outside of an actual web request, or processing a request outside of the originally receiving thread? If you are actually operating within a web request and still receive this message, your code is probably running outside of DispatcherServlet: In this case, use RequestContextListener or RequestContextFilter to expose the current request.
```

(There is significantly more info in the subsequent java stacktrace. Let me know if any of that would be useful and I will attach.)

The only workaround we have identified so far is to have the rundeck job ingest the options file manually.
