### ISSUE TITLE
SCM Import shows 'N tracked files were deleted'

### ISSUE THREAD

**Issue by lukasged** [rundeck/rundeck#5815]
**Describe the bug**
When using the SCM plugin to sync with Git, after configuring a project and importing the jobs, if the SCM settings are changed (e.g. different Git branch to pull from), then after another import from the new Git config, the interface is always showing a message about deleted tracked files (`N tracked file(s) were deleted`) and there doesn't seem to be anything to do about it. I don't see the old files on the server.

**My Rundeck detail**

* Rundeck version: `3.1.2.20190927`
* install type: rpm
* OS Name/version: Linux/CentOS 7
* DB Type/version: MySQL

**To Reproduce**
1. Configure Rundeck to import the jobs from Git (SCM plugin)
2. Import the jobs from Git
3. Edit the SCM configuration to pull from another repo or branch, which would involve removing some of the jobs that were tracked by the previous configuration
4. Import the jobs after the config change
5. Observe that Rundeck now shows the SCM message `N tracked file(s) were deleted`

**Expected behavior**
After changing the SCM configuration, the changes should be imported and the Rundeck interface shouldn't show any message.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 80

**Comment by fdevans** [comment]
We are working on updating these plugins.  We will see if we can replicate these issues and if so address them.
