### ISSUE TITLE
Unable to add a simple node on default ubuntu install

### ISSUE THREAD

**Issue by richstokes** [rundeck/rundeck#5816]
Installed the latest via the .deb file

Looks like it uses the .db for storage, so no projects dir is created. As a result there is no way to add a resources.xml file to define a standalone node.

It looks like the only option is to load in nodes from some kind of external list which is way overkill for what we need. 

Is there another way to simply add an SSH-able node?

**Comment by MegaDrive68k** [comment]
@richstokes 

You can use any path for resources.xml file, just make sure that the "rundeck" user can reach it.

Greetings.

**Comment by richstokes** [comment]
Thanks, I'm kind of stunned that you have to manually generate XML to add a node. Seems like one of the core tasks someone would need to do and you have to jump through hoops to make it happen.
