### ISSUE TITLE
Rundeck access to Linux nodes with ssh & password

### ISSUE THREAD

**Issue by chetanzade** [rundeck/rundeck#5818]
Could you please help me below approaches for connecting to Linux nodes?
1. Connect to nodes with just ssh key & no password (It is Possible)
2. Connect to nodes with no ssh key & just password (It is possible)
**3. Connect to nodes with ssh key & Password  - Is it Possible?**

If yes, what can be done to achieve this?
If no, is it possible for Rundeck Team to come up with some approach to do this?

Approach 3 is required to fulfill the system security policies 
If the policy is implemented, Rundeck cannot connect to nodes.

Could someone help me with this?

**Comment by MegaDrive68k** [comment]
Hi @chetanzade 

Take a look at this:

https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html#ssh-private-key-passphrase

Don't forget to see how to set your node in your node definition:

https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html#ssh-private-key-passphrase-with-a-job-option

Hope it helps!
