### ISSUE TITLE
During upgrade, show in the logs when it's upgrading the DB

### ISSUE THREAD

**Issue by nmamn** [rundeck/rundeck#5819]
Hi,

We just upgraded from 3.1.1 to 3.2.1, and it went smoothly, thanks for the hard work guys.

We just had a quick fear because after a couple of minutes, rundeck was still not back up. It appears it was actually probably upgrading its DB schema.

Would it be possible to drop a line in the logs saying "DB upgrade process in progress" and "DB upgrade process completed" when appropriate?

Thanks a lot,

Nicolas

**Comment by fdevans** [comment]
@imad6639 something to consider for your project for 3.4.0
