### ISSUE TITLE
Limit number of nodes dispatched within filter

### ISSUE THREAD

**Issue by jhmartin** [rundeck/rundeck#582]
Consider a number node-filter component, such that if my node filter matches 10 nodes, I say dictate that the command be dispatched to just 1 (or more), either in sorted or random order. Useful when utilizing a pool of machines that can accept a given command.

It'd also be useful for a command failure to trigger a retry on another node.

**Comment by gtowey** [comment]
This is a feature I also want.  My use case is that I have a pool of hosts which can run commands but I only want the command run once.  I currently have to specify a hostname, but it would be much more robust to simple say `role: myrole limit: 1` So I don't have to update the hostname on all my jobs if a single host happens to be down.

**Comment by puremourning** [comment]
Assuming I understood, You can use the random subset orchestrator with max of 1. This execs on one from the node filter (randomly). Or you can write an orchestrator plug-in to do what you need.

**Comment by gtowey** [comment]
Awesome, thanks for the tip.  I will try that.
