### ISSUE TITLE
Is it possible to display job run time in local timezone instead of UTC?

### ISSUE THREAD

**Issue by richstokes** [rundeck/rundeck#5829]
Looks like all jobs/results are listed in UTC. Cant see any option to use local timezone for the display. is it possible?

**Comment by MegaDrive68k** [comment]
Hi @richstokes 

Take a look at this:

https://github.com/rundeck/rundeck/issues/2072#issuecomment-252400455

Cheers!

**Comment by richstokes** [comment]
Cool - I guess a feature request would be more appropriate then. Seems like it would be a more sensible default for rundeck to detect the local timezone automatically?
