### ISSUE TITLE
Node tags can't be expanded when the job has over 60 tags 

### ISSUE THREAD

**Issue by jervislam0911** [rundeck/rundeck#5841]
**Describe the bug**

Node tags can't be expanded when the job has over 60+ tags 

**My Rundeck detail**

* Rundeck version: [3.2.1]
* install type: [rpm]
* OS Name/version: [Centos 7]
* DB Type/version: [H2]

**To Reproduce**

Loading almost 200 nodes with total 60+ tags from inventory

**Expected behavior**
Node tag section can be expanded

**Screenshots**
![image](https://user-images.githubusercontent.com/14086195/75597924-42141d80-5a66-11ea-8347-30e16de356b6.png)

**Desktop (please complete the following information):**
 - OS: [windows server 2016]
 - Browser [chrome, ie, edge]
 - Version [79.0.3945.130]

**Additional context**
Using ansible inventory plugin

**Comment by MegaDrive68k** [comment]
It also happens with 40 tags ("show all" button doesn't work).

Thanks for your feedback @jervislam0911

**Comment by aegiap** [comment]
We also hit this issue with a job with 115 tags. We are migrating to rundeck 3.3.3 from 2.8.2 and the same job in the old version showed the list of node tags. On the 3.3.3 version we cannot even expand the '115 tags'.

**Comment by ahamlinman** [comment]
We are experiencing this following upgrades from 3.0.27, and have confirmed that it exists in 3.1.6 and 3.2.9.

It seems like [the element's onclick handler](https://github.com/rundeck/rundeck/blob/6b1a71e493563f4339618d5acfef51b3aaaf4d21/rundeckapp/grails-app/views/framework/_tagsummary.gsp#L28) relies on Prototype, which is apparently in the process of being removed. The browser console reports:

```
Uncaught TypeError: Element.toggle is not a function
```

I can confirm that loading Prototype on the page (literally pasting prototype.js into the browser console, to get around CSP) resolves the issue.

**Comment by nue-melexis** [comment]
same for us, this really makes life hard when you wanna choose many nodes
