### ISSUE TITLE
Login does not redirect to menu/home

### ISSUE THREAD

**Issue by davidnmbond** [rundeck/rundeck#5843]
**Describe the bug**
Login does not correctly redirect to menu/home

**My Rundeck detail**

* Rundeck version: 3.2.3
* install type: rpm
* OS Name/version: Centos 8
* DB Type/version: in-built

**To Reproduce**
1. Fresh install via dnf;
2. Update framework.properties;
3. start service;
4. visit http://FQDN:4440;
5. login with admin/admin

**Expected behavior**
Redirect to menu/home

**Actual behavior**
Login succeeds, but there is no redirect, leading the user to believe that login failed.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome latest
 - Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by MegaDrive68k** [comment]
Hi @davidnmbond 

Did you edit the `grails.serverURL` on the `rundeck-config.properties` file with the hostname name?

Regards!

**Comment by davidnmbond** [comment]
@MegaDrive68k - absolutely, this was the problem!  Thank you.

Perhaps it would be easier if there was only one place to configure this change and/or the two should be compared on startup and a warning shown in the UI if they differ?
