### ISSUE TITLE
API: Use the PUT HTTP method to modify full objects

### ISSUE THREAD

**Issue by davidnmbond** [rundeck/rundeck#5844]
**Is your feature request related to a problem? Please describe.**
Using the API, the "update" actions use the "POST" HTTP method.  This is non-standard, and very confusing.

**Describe the solution you'd like**
All "modify-the-object" actions should be implemented such that they use the HTTP PUT method.

**Describe alternatives you've considered**
N/A

**Additional context**
See [https://www.restapitutorial.com/lessons/httpmethods.html](https://www.restapitutorial.com/lessons/httpmethods.html) for info on how to use standard HTTP methods.

**Comment by orubel** [comment]
This should be simple to do. Greg if you need help with this, I maintain several of the Grails API plugins even up to 3.X. Let me know if you need a hand.

**Comment by orubel** [comment]
wow. I guess Rundeck isn't even updating their product anymore.
