### ISSUE TITLE
API: Add PATCH support for updating single fields

### ISSUE THREAD

**Issue by davidnmbond** [rundeck/rundeck#5845]
**Is your feature request related to a problem? Please describe.**
When updating an object, it is currently necessary to send the whole object in the HTTP body.  This is both inefficient and can lead to concurrency issues when multiple clients are modifying objects at the same time.

**Describe the solution you'd like**
The API should provide PATCH support for modifying individual fields.

**Describe alternatives you've considered**
N/A

**Additional context**
See [https://www.restapitutorial.com/lessons/httpmethods.html](https://www.restapitutorial.com/lessons/httpmethods.html) for how to correctly implement the PATCH HTTP method.

**Comment by orubel** [comment]
So PATCH is kinda a large feature request in alot of ways in that you are asking that the RESOURCE allowed the be edited ONE FIELD at a time. This isn't a widely implemented HTTP METHOD.

Could you explain what you are trying to do first?

**Comment by fdevans** [comment]
@davidnmbond let's include this in our next catch up call. Thanks for the suggestion.
