### ISSUE TITLE
Job argument should be usable for response file of HTTP Request

### ISSUE THREAD

**Issue by aimtsou** [rundeck/rundeck#5856]
**Is your feature request related to a problem? Please describe.**
I am using the HTTP Request step to get some data from an API. As a job you can have arguments passed in the url of the HTTP Request or to the body if needed but you cannot have the argument set for the response of the HTTP Request to a file. My rundeck version is 2.11.5-1

**Describe the solution you'd like**
Save to dynamic file according to an argument given. tick print response to a file and set
file destination to ie: /var/tmp/${option.source}.json

**Comment by fdevans** [comment]
To focus our efforts on more recent releases we are going to close this request.  If there are still gaps in the feature set of a current product version (3.2.5 today) please feel free to open an enhancement request against that version with your ideas.
Thank you, 
The Rundeck Team
