### ISSUE TITLE
Passing Job context variables ${option.xx} into the email notification template default or custom

### ISSUE THREAD

**Issue by luisrivas35** [rundeck/rundeck#5863]
**Describe the bug**
The job context variables are not supposed to pass inside the default or custom templates in the notification emails. However, they actually pass when the status of the job is "running"

**My Rundeck detail**

* Rundeck version: 3.2.3
* install type: WAR
* OS Name/Version: ubuntu 18.04]
* DB Type/version: Mysql

**To Reproduce**
1. Configuring the feature email notification in rundeck-config.properties to use a custom email template. 
2. Do not specify any trigger status to the notification
3. Habilitate the email notification feature in the Rundeck GUI
4. Implementing any job context variables, ex. ${option.opt1} and  ${option.opt2}

**Screenshots**
- Two output using job context variables

With status succeeded, variables do not pass
![mails1](https://user-images.githubusercontent.com/43067588/76072207-50869b80-5f76-11ea-8e19-c6743b3a41d1.png)

With status running, variables pass
![mails2](https://user-images.githubusercontent.com/43067588/76072220-54b2b900-5f76-11ea-982f-8ba0dab11b27.png)

**Comment by luisrivas35** [comment]
Here, the two example jobs used to test it:
Test:
- defaultTab: output
  description: ''
  executionEnabled: true
  id: a384b587-62b0-42ee-a92e-22881ed38a89
  loglevel: INFO
  name: test
  nodeFilterEditable: false
  notification:
    onsuccess:
      email:
        recipients: lrivas@rundeck.com
        subject: ${execution.status}
      plugin:
        configuration:
          action: -opt1${option.task} -opt2${option.city}
          event: ${execution.status}
          job: ${job.id}
        type: mynotification
  notifyAvgDurationThreshold: null
  options:
  - label: City
    name: city
    required: true
    values:
    - Santiago
    - Viña
    - Serena
    - Coquimbo
    valuesListDelimiter: ','
  - label: Task to do
    name: task
    required: true
    values:
    - Review
    - Diagnose
    - Clean
    - Rebuild
    valuesListDelimiter: ','
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - jobref:
        args: -opt1 ${option.city} -opt2 ${option.task}
        group: ''
        name: test1
        nodeStep: 'true'
        uuid: 3fa2a962-047c-426d-8a5c-eb044d9e7781
    keepgoing: false
    strategy: node-first
  uuid: a384b587-62b0-42ee-a92e-22881ed38a89

Test1:
- defaultTab: output
  description: ''
  executionEnabled: true
  id: 3fa2a962-047c-426d-8a5c-eb044d9e7781
  loglevel: INFO
  name: 'test1 '
  nodeFilterEditable: false
  notification:
    onsuccess:
      email:
        recipients: admin@rundeck.com
        subject: ${execution.status}
  notifyAvgDurationThreshold: null
  options:
  - name: opt1
  - name: opt2
  plugins:
    ExecutionLifecycle: {}
  scheduleEnabled: true
  sequence:
    commands:
    - exec: echo "The Task to do is...."  ${option.opt2}
    - exec: echo "The City is....:"  ${option.opt1}
    keepgoing: false
    strategy: node-first
  uuid: 3fa2a962-047c-426d-8a5c-eb044d9e7781

**Comment by jtobard** [comment]
Is not possible to reproduce this issue, the options works fine using the default configuration or using custom template.
