### ISSUE TITLE
Redirection Rundeck via tomcat

### ISSUE THREAD

**Issue by Guiilliian** [rundeck/rundeck#5866]
**Describe the bug**

Hi, I install rundeck on CentOS Linux release 7.4, I want to change the access http adress because my IP and hostname is not saved in DNS of Domain. 

I change this parameters in **_rundeck-config.properties_** file 

`grails.serverURL=http://**myip:4440**`

But I have again the prob. 
I also test to edit this parameters in this file : **_framework.properties_**  but it did not work. 

```
framework.server.port = **4440**
framework.server.url = http://**myip:4440**
```
My port 4440 is open and java is ok on. 
When i click on my application on the tomcat interface the authentification interface of rundeck work but after I have the error on all web browser

Any personn can help me ? 

My Rundeck detail

Rundeck version: [ e.g. 2.11.3]
install type: war via tomcat 8.5
OS Name/version: rundeck-3.2.3-20200221

**Comment by MegaDrive68k** [comment]
Hi @Guiilliian 

Following this: 

https://docs.rundeck.com/docs/administration/install/tomcat.html#rundeck-as-a-tomcat-servlet

You need to set `grails.serverURL` with the tomcat rundeck app path, for example: `http://mytomcathost-or-ip:8080/rundeck`

Don't forget to add:

`server.contextPath=/rundeck`

Regards!
