### ISSUE TITLE
Icons on top right are not aligned

### ISSUE THREAD

**Issue by teopost** [rundeck/rundeck#5867]
The config and user icons on the top right corner are not aligned

**Screenshots**

![immagine](https://user-images.githubusercontent.com/2573389/76234151-a171ea80-6229-11ea-8fe4-d9b40790a851.png)

**Rundeck**
 - Version: Rundeck 3.2.1-20200113

**Desktop**
 - OS: macOS Catalina
 - Browser: Firefox 
 - Version: 73.0.1 (64bit)

**Comment by fdevans** [comment]
Thanks @teopost
