### ISSUE TITLE
Fresh Install Not Showing Projects after Login/Logout

### ISSUE THREAD

**Issue by eagle-rr** [rundeck/rundeck#5874]
**Describe the bug**
After a fresh new installation of Rundeck 3.2.2 on OL7; the initial login with default admin userid shows:
-  "{0} Project|{0} Projects" just above "New Project+" button
- Spinning circles/icons just above "Execution|Executions In the last day 0, 'text-primary': totalFailedCount()<1 }" ({0} Failed)" panel and to the right of "Loading Projects".

Even if I click on "New Project+" button and define a new project; I no longer see it if I logout and back in.  After logging back in, I see the same errors above and nothing available in the "Projects" pull-down.

**My Rundeck detail**

* Rundeck version: 3.2.2 
* install type: rpm (rpm -ivh rundeck-3.2.2.20200204-1.noarch.rpm)
* OS Name/version: Oracle Linux 7.7
* DB Type/version: h2 (for initial install)

**To Reproduce**
1. rpm -ivh rundeck-3.2.2.20200204-1.noarch.rpm
2. Go to url: http://<server_fqdn>:4440/
3. Login as built-in admin userid
4. Encounter the above errors.  Create a new project, login, and logout.  See same above odd home screen.

**Expected behavior**
When I have tried out earlier Rundeck releases at previous jobs; the home screen, creating projects, logging in and out, etc. all worked similar to User Guide and Administration Guide for Rundeck.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Internet Explorer

**Additional context**
As my desktop is different than the rundeck server, I have updated the entries in /etc/rundeck/framework.properties and /etc/rundeck/rundeck-config.properties with the fqdn of the server running the fresh Rundeck installation.

**/etc/rundeck/rundeck-config.properties**
```
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/var/lib/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
# change hostname here
# grails.serverURL=http://localhost:4440
grails.serverURL=http://<fqdn>:4440
dataSource.dbCreate = update
dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true

# Encryption for key storage
rundeck.storage.provider.1.type=db
rundeck.storage.provider.1.path=keys

rundeck.storage.converter.1.type=jasypt-encryption
rundeck.storage.converter.1.path=keys
rundeck.storage.converter.1.config.encryptorType=custom
rundeck.storage.converter.1.config.password=e6c7ff5995aca091
rundeck.storage.converter.1.config.algorithm=PBEWITHSHA256AND128BITAES-CBC-BC
rundeck.storage.converter.1.config.provider=BC

# Encryption for project config storage
rundeck.projectsStorageType=db

rundeck.config.storage.converter.1.type=jasypt-encryption
rundeck.config.storage.converter.1.path=projects
rundeck.config.storage.converter.1.config.password=e6c7ff5995aca091
rundeck.config.storage.converter.1.config.encryptorType=custom
rundeck.config.storage.converter.1.config.algorithm=PBEWITHSHA256AND128BITAES-CBC-BC
rundeck.config.storage.converter.1.config.provider=BC

rundeck.log4j.config.file = /etc/rundeck/log4j.properties

rundeck.feature.repository.enabled=true
```
**/etc/rundeck/framework.properties**
```
# framework.properties -
#

# ----------------------------------------------------------------
# Rundeck server connection information
# ----------------------------------------------------------------

# framework.server.name = localhost
# framework.server.hostname = localhost
# framework.server.port = 4440
# framework.server.url = http://localhost:4440

framework.server.name = <fqdn>
framework.server.hostname = <fqdn>
framework.server.port = 4440
framework.server.url = http://<fqdn>:4440

# ----------------------------------------------------------------
# Installation locations
# ----------------------------------------------------------------

rdeck.base=/var/lib/rundeck

framework.projects.dir=/var/lib/rundeck/projects
framework.etc.dir=/etc/rundeck
framework.var.dir=/var/lib/rundeck/var
framework.tmp.dir=/var/lib/rundeck/var/tmp
framework.logs.dir=/var/lib/rundeck/logs
framework.libext.dir=/var/lib/rundeck/libext

# ----------------------------------------------------------------
# SSH defaults for node executor and file copier
# ----------------------------------------------------------------

framework.ssh.keypath = /var/lib/rundeck/.ssh/id_rsa
framework.ssh.user = rundeck

# ssh connection timeout after a specified number of milliseconds.
# "0" value means wait forever.
framework.ssh.timeout = 0
```

**Comment by eagle-rr** [comment]
Additionally, I do have the following installed:
```
java -version
openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)
```

**Comment by MegaDrive68k** [comment]
HI @eagle-rr 

Your instance is behind of proxy server?

Regards.

**Comment by DigitalxMonk** [comment]
I am also having this issue on IE only, Chrome & FireFox load everything. I have Rundeck 3.2.6, running on Tomcat 8.5.54.  I have tried both behind a httpd reverse proxy and directly to tomcat.

Please let me know if you ever determined a fix or workaround for this issue.  Thanks!

**Comment by eagle-rr** [comment]
My problem was due to using very old browser from our jump server.  After installing the latest Firefox, all worked fine.
