### ISSUE TITLE
Referenced jobs have started checking options via options provider

### ISSUE THREAD

**Issue by richiereynolds** [rundeck/rundeck#5875]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [e.g. ubuntu 16.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by puremourning** [comment]
@richiereynolds youbforgot to complete the issue template.
