### ISSUE TITLE
ERROR: Ansible IO failure: Cannot run program "ansible-playbook"

### ISSUE THREAD

**Issue by m-garrido** [rundeck/rundeck#5880]
**Describe the bug**
rundeck-ansible plugin is deployed in docker official image.
But, it can't be use because ansible package isn't installed.

**My Rundeck detail**

* Rundeck version: 3.2.1
* install type: Docker
* DB Type/version: postgres

**To Reproduce**
Docker run and launch a ansible playbook.

**Expected behavior**
Running the playbook with ansible.

**Additional context**
After configuring a ansible inventory as nodes, i have this error:
ERROR: Ansible IO failure: Cannot run program "ansible-playbook" 

I would like to know if it's planned to deploy ansible package by default in docker images.

**Comment by MegaDrive68k** [comment]
Hi @m-garrido 

You need to extend the image, I use this Dockerfile, feel free to modify it if you like:

```
FROM rundeck/rundeck:3.2.3

MAINTAINER yourname <your@email.net>

ENV ANSIBLE_HOST_KEY_CHECKING=false
ENV RDECK_BASE=/home/rundeck
ENV MANPATH=${MANPATH}:${RDECK_BASE}/docs/man
ENV PATH=${PATH}:${RDECK_BASE}/tools/bin

RUN sudo apt-get -y update \
  && sudo apt-get -y --no-install-recommends install ca-certificates python3-pip sshpass \
  && sudo -H pip3 --no-cache-dir install --upgrade pip setuptools \
  && sudo -H pip3 --no-cache-dir install ansible==2.9.2 \
  && sudo rm -rf /var/lib/apt/lists/* \
  && mkdir -p ${PROJECT_BASE}/etc/ \
  && sudo mkdir /etc/ansible
```

Hope it helps!

**Comment by m-garrido** [comment]
Thank you for the help. Yes, this workaround should works.
I think it would be helpfull if ansible client is deployed by default.
