### ISSUE TITLE
When use rd run job --follow can cause exception due to "Infinity"

### ISSUE THREAD

**Issue by jbanda15** [rundeck/rundeck#5886]
When using the API for paging, specifically --follow, it would through the output of a running job can return "Infinity".
The presented error is the following:
`com.fasterxml.jackson.core.JsonParseException: Non-standard token 'Infinity': enable JsonParser.Feature.ALLOW_NON_NUMERIC_NUMBERS to allow`

`at [Source: okhttp3.ResponseBody$BomAwareReader@7690781; line: 1, column: 191]`

I really haven't clear how we can replicate this behavior using Rundeck Cluster. After many tests, I couldn't get the "Infinity" log

**My Rundeck detail**

* Rundeck Enterprise v3.2.0-20191218
* RPM method
* RedHat7
* MySQL server v5.7.27

Related issue:
[https://github.com/rundeck/rundeck-cli/issues/257](https://github.com/rundeck/rundeck-cli/issues/257)

**Comment by gschueler** [comment]
I believe this was fixed in 3.2.9/3.3.0 https://github.com/rundeck/rundeck/pull/6234
