### ISSUE TITLE
Client GPU consumption very high when displaying running job

### ISSUE THREAD

**Issue by mveroone** [rundeck/rundeck#5888]
**Describe the bug**
When viewing a running Job, even without progress bar, Browser GPU consumption skyrockets

**My Rundeck detail**

* Rundeck version: 3.2.0
* install type: rpm
* OS Name/version: CentOS 7.5
* DB Type/version: MySQL (default CentOS Mariadb version)

**To Reproduce**
1. start a job, making sure it'll last more than the average
2. Using Chrome, display the Job running page
3. Check Chrome/Windows Task Manager => GPU process uses 100% 
4. As soon as job finishes, consumption goes back to zero

**Expected behavior**
A way smaller consumption considering we're not displaying anything complex

**Screenshots**
![image](https://user-images.githubusercontent.com/44051537/76775625-e6f06380-67a5-11ea-9d56-d8077f9c4ab0.png)

**Desktop (please complete the following information):**
 - OS: Latest Windows 10 64bit (1909 build)
 - Browser Chrome
 - Version 80.0.3987.132 (Official Build) (64-bit)
 - Display is a 4K LCD touchscreen on a Dell Precision 5510 Laptop, CPu is a Xeon E3-1505M, GPU is a Quadro M1000M... nothing cheap.

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @mveroone 

Do you see the same behavior on Firefox or Opera?

Regards.

**Comment by mveroone** [comment]
Hi,
Thanks for the quick reply.

Actually, I had never tried, but I can't even display pages correctly on Firefox (Activity empty, Job parameters do not load fully, several console errors)
![image](https://user-images.githubusercontent.com/44051537/76831197-2a3ee680-6827-11ea-8ae8-cb0474d023b3.png)

It could be because our company has us locked in Firefox ESR 45.5 though =/ Even gmail refuses to display

I have a similar behaviour on Edge, though. As long as the small rotating circle animation beside "Running" on nodes is displayed, GPU rises to 100%. Funny enough though, while Chrome does uses partially my GPU, Edge uses only my integrated CPU VGA capabilities.

**Comment by MegaDrive68k** [comment]
Hi @mveroone 

Testing over NVIDIA GPU in Windows, Chrome and Opera processes show more or less 5% of use (we are agree that Rundeck java process doesn't use any GPU resource).

![image_gpu](https://user-images.githubusercontent.com/51376003/77072353-5051bb80-69cc-11ea-8ff5-a9e5f27cdd16.png)

![nuevo](https://user-images.githubusercontent.com/51376003/77074338-7af14380-69cf-11ea-80f1-bab807cb2182.gif)

I think that is a driver/browser/browser add-on issue.

1) Keep updated your Operating System, Browser and GPU drivers. 
2) Try using a "clean" Chrome installation (without add ons).
3) Also, try disabling browser hardware acceleration.

Regards!

**Comment by mveroone** [comment]
Alright, thanks for te investigation. I'm overwhelmed with issues right now but i'll have a look in a few days.

Hardware acceleration : already tried, it deports all the graphic load to my integrated GPU

Drivers are up to date, so I'll bet on a problem with a chrome extension. i'll try disabling all of them.
