### ISSUE TITLE
An exception occurred applying plugin request [id: 'org.dvaske.gradle.git-build-info', version: '0.8']

### ISSUE THREAD

**Issue by tangyong** [rundeck/rundeck#5890]
**Describe the bug**
While building rundeck 3.2.3 from source, after executing ./gradlew clean build, the following exception happened,

* What went wrong:
An exception occurred applying plugin request [id: 'org.dvaske.gradle.git-build-info', version: '0.8']
> Failed to apply plugin [id 'org.dvaske.gradle.git-build-info']
   > No signature of method: org.gradle.internal.logging.slf4j.OutputEventListenerBackedLogger.warning() is applicable for argument types: (org.codehaus.groovy.runtime.GStringImpl) values: [Git repository not found for rundeck-rundeck-65db560]
     Possible solutions: warn(java.lang.String), wait(), wait(long), warn(java.lang.String, [Ljava.lang.Object;), warn(java.lang.String, java.lang.Object), warn(java.lang.String, java.lang.Throwable)

**My Rundeck detail**
Rundeck v3.2.3
java version "13.0.2" 2020-01-14
Java(TM) SE Runtime Environment (build 13.0.2+8)
Java HotSpot(TM) 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

* Rundeck version: [ v3.2.3]
* install type: [choose: source building]
* OS Name/version: [e.g. Cygwin]
* DB Type/version: [choose: mysql]

**To Reproduce**
1.  wget --no-check-certificate https://github.com/rundeck/rundeck/tarball/v3.2.3
2.  tar xvzf v3.2.3
3. ./gradlew clean build

**Expected behavior**
building successful

**Screenshots**
![1](https://user-images.githubusercontent.com/187414/76814231-2f0a9700-6835-11ea-9a6f-fbfb29504fd2.png)

**Desktop (please complete the following information):**
 - OS: [Windows 10]

**Comment by tangyong** [comment]
[Update]

After changing 

plugins {
    id 'com.gradle.build-scan' version '1.13'
    id "org.dvaske.gradle.git-build-info" version "0.8"
}   into

plugins {
    id 'com.gradle.build-scan' version '1.13'
    id "org.dvaske.gradle.git-build-info" version "0.9"
}
,   building can continue.

**Comment by MegaDrive68k** [comment]
Hi @tangyong 

Rundeck need Java  8, check the requirements: 

https://github.com/rundeck/rundeck/wiki/Building-and-Testing

Regards.

**Comment by tangyong** [comment]
> Hi @tangyong
> 
> Rundeck need Java 8, check the requirements:
> 
> https://github.com/rundeck/rundeck/wiki/Building-and-Testing
> 
> Regards.

Sure, however, this issue is fixed by gitting clone rundeck rather than using tarball.

Thanks!
