### ISSUE TITLE
Highlight filter for console output

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#59]
Provide a means to define colorizing/highlighting text effects for console output. Might be an old comparison but see http://linux.die.net/man/1/swatch

(c/o botchagalupe)

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/139)

Original Creator: Alex-SF

**Comment by ahonor** [comment]
Implemented by log filter plugins in 2.9.0: https://github.com/rundeck/rundeck/issues/2577
