### ISSUE TITLE
Cookies expiration

### ISSUE THREAD

**Issue by petrkle** [rundeck/rundeck#5916]
**Describe the bug**
I set long server.session.timeout, but rundeck set cookies without expiration date. Users must login after every broser close.

Headers from server:

Set-Cookie: JSESSIONID=node0gtmqpfijkaoby5wvy3jcova7176.node0; Path=/; HttpOnly

**My Rundeck detail**

* Rundeck version: 3.2.4-20200318
* install type: deb
* OS Name/version: Debian GNU/Linux 10 (buster)
* DB Type/version: mysql

**To Reproduce**
1. Go to rundeck login page
2. Logon
3. Close browser
4. Go to rundeck login page
5. You are logeed out

**Expected behavior**
After browser close and new start rundeck web should be still logged in. No need log in after every browser close.

I think, that Set-Cookie header should looke like:
Set-Cookie: JSESSIONID=node0gtmqpfijkaoby5wvy3jcova7176.node0;  expires=Sun, 26-May-2020 11:57:50 GMT; Path=/; HttpOnly

**Desktop**
 - OS: Slackware Linux
 - Browser Chrome, Firefox
 - Version: latest stable version

**Comment by MegaDrive68k** [comment]
Hi @petrkle 

Maybe you need to check the "Restore Session" option in your browser?

![Screenshot_2](https://user-images.githubusercontent.com/51376003/77771244-3ac03f80-7025-11ea-9343-362392ff63f2.png)

Happy Slacking and Regards!

**Comment by petrkle** [comment]
Hi @MegaDrive68k,

nice workaround, but cookie is still marked for deletion at browser session end.

![expiration](https://user-images.githubusercontent.com/545514/77831037-f750f880-712c-11ea-83a8-cefcdd425057.png)

**Comment by askmike1** [comment]
I have the same issue, the cookie is set to expire "when the browsing session ends", it doesn't seem to be honoring the server.servlet.session.timeout (I'm on 3.3.4)
