### ISSUE TITLE
null value in options list

### ISSUE THREAD

**Issue by gnmancini** [rundeck/rundeck#5921]
Creating a rundeck's job, adding a variable with a list of allowed values it does not take the default null variable when I did not chose any of the value list. (for that variable I've selected required none and restrictions none).

My Rundeck detail:
Rundeck version: 2.10.4-1
install type: rpm
OS Name/version: CentOS 7.6.1810
DB Type/version: mysql

1. Create a new job.
2. Add a variable with a list of possible values.
3. Call a curl interacting with any api accepting null variables for that variable.

Expected behavior
The variable should take the null variable as a default value when you do not select any values from the list.

Thanks

**Comment by MegaDrive68k** [comment]
Hi @gnmancini 

Can you post a example job definition and you cURL call to test?

Thanks!

**Comment by fdevans** [comment]
Hi @gnmancini Rundeck 2.10.4-1 is quite old.  Can you confirm your issue on a current version of Rundeck and post back to us if there is still an issue please?
