### ISSUE TITLE
Option: The user has to explicitly select target nodes

### ISSUE THREAD

**Issue by VivianeHonda** [rundeck/rundeck#5922]
![Rundeckbug](https://user-images.githubusercontent.com/62887804/77935353-386e1780-72a9-11ea-8133-f3f2527263c4.jpg)
**Describe the bug**
When the option in Node Selection is: "The user has to explicitly select target nodes".

If the user does not specify the node, the complete inventory is being sent. Even if you have put a filter in the JOB it is not being respected and all the servers in the inventory are running

This error can be reproduced in two Rundeck's version

**My Rundeck detail**

* Rundeck version: 2.10.6-1 and 3.0.23
* install type: rpm
* DB Type/version: postgres

**To Reproduce**
Steps attachment to reproduce the behavior 

**Expected behavior**
If Node is zero, the entire inventory should not be sent by default.
And if it has a filter the same should be respected.

**Comment by MegaDrive68k** [comment]
Hi @VivianeHonda 

I'm trying to reproduce the issue (on Rundeck 2.10.6 and 3.2.4) but cannot see the same behavior (with "zero" nodes the job can't be dispatched).

![Screenshot_1](https://user-images.githubusercontent.com/51376003/78294690-2c7c9280-7501-11ea-95ea-fbe55855c00c.png)

Can you share an example Job Definition to adapt and see the behavior?

I'm using this definition:

```xml
<joblist>
  <job>
    <description></description>
    <dispatch>
      <excludePrecedence>true</excludePrecedence>
      <keepgoing>false</keepgoing>
      <rankOrder>ascending</rankOrder>
      <successOnEmptyNodeFilter>false</successOnEmptyNodeFilter>
      <threadcount>1</threadcount>
    </dispatch>
    <executionEnabled>true</executionEnabled>
    <id>6ffedf9b-e199-4e31-b553-bedf66d29d9d</id>
    <loglevel>INFO</loglevel>
    <name>helloworld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <nodefilters>
      <filter>tags: websrv</filter>
    </nodefilters>
    <nodesSelectedByDefault>false</nodesSelectedByDefault>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='parallel'>
      <command>
        <exec>echo hi</exec>
      </command>
      <command>
        <exec>echo bye</exec>
      </command>
    </sequence>
    <uuid>6ffedf9b-e199-4e31-b553-bedf66d29d9d</uuid>
  </job>
</joblist>
```

Thanks.

**Comment by VivianeHonda** [comment]
Hello,

Thank you very much for the quick return.

Follow:
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option enforcedvalues='true' name='runtime' required='true' value='V36SP07F01' values='V36SP06F03,V36SP07F01,V37SP01F01' />
      </options>
    </context>
    <defaultTab>summary</defaultTab>
    <description>This CRQ configure all application in last version runtime</description>
    <dispatch>
      <excludePrecedence>true</excludePrecedence>
      <keepgoing>false</keepgoing>
      <rankOrder>ascending</rankOrder>
      <successOnEmptyNodeFilter>false</successOnEmptyNodeFilter>
      <threadcount>1</threadcount>
    </dispatch>
    <executionEnabled>true</executionEnabled>
    <group>Upgrade Runtime</group>
    <id>0354a40f-db11-4c39-8971-dca85c0c914c</id>
    <loglevel>INFO</loglevel>
    <name>changeRuntime</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <nodefilters>
      <filter>tags: chq*.*,mobi*.*,pay*.*,SPP*.* nodename: dmg*.* </filter>
    </nodefilters>
    <nodesSelectedByDefault>false</nodesSelectedByDefault>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='parallel'>
      <command>
        <step-plugin type='com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep'>
          <configuration>
            <entry key='ansible-become' value='false' />
            <entry key='ansible-disable-limit' value='false' />
            <entry key='ansible-extra-vars' value='runtime: ${option.runtime}' />
            <entry key='ansible-playbook' value='${globals.project_home}/${globals.project_workspace}_${globals.execution_env}/CRQ000005367641/changeRuntime.yml' />
          </configuration>
        </step-plugin>
      </command>
    </sequence>
    <uuid>0354a40f-db11-4c39-8971-dca85c0c914c</uuid>
  </job>
</joblist>

**Comment by VivianeHonda** [comment]
[changeRuntime (3).txt](https://github.com/rundeck/rundeck/files/4425873/changeRuntime.3.txt)

Thank you very much for the quick return.

I'm putting in attachment

**Comment by MegaDrive68k** [comment]
Hi @VivianeHonda 

I think I reproduced your issue and it seems an ansible configuration issue.

I used this ansible-playbook:

```yaml
    - name: this is a hello-world example
      hosts: all
      tasks:
        - name: create a file called '/home/vagrant/testfile.txt' with the content 'hello world'.
          copy:
            content: hello world
            dest: /home/vagrant/testfile.txt
```

With this Job Definition (is a modification of your job def):

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description>This CRQ configure all application in last version runtime</description>
    <dispatch>
      <excludePrecedence>true</excludePrecedence>
      <keepgoing>false</keepgoing>
      <rankOrder>ascending</rankOrder>
      <successOnEmptyNodeFilter>false</successOnEmptyNodeFilter>
      <threadcount>1</threadcount>
    </dispatch>
    <executionEnabled>true</executionEnabled>
    <group>Upgrade Runtime</group>
    <id>0354a40f-db11-4c39-8971-dca85c0c914c</id>
    <loglevel>INFO</loglevel>
    <name>changeRuntime</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <nodefilters>
      <filter>tags: the.*</filter>
    </nodefilters>
    <nodesSelectedByDefault>false</nodesSelectedByDefault>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='parallel'>
      <command>
        <step-plugin type='com.batix.rundeck.plugins.AnsiblePlaybookWorkflowStep'>
          <configuration>
            <entry key='ansible-base-dir-path' value='/etc/ansible' />
            <entry key='ansible-become' value='false' />
            <entry key='ansible-disable-limit' value='false' />
            <entry key='ansible-playbook' value='/home/user/playbooks/simple_test.yml' />
            <entry key='ansible-ssh-passphrase-option' value='option.password' />
            <entry key='ansible-ssh-use-agent' value='false' />
          </configuration>
        </step-plugin>
      </command>
    </sequence>
    <uuid>0354a40f-db11-4c39-8971-dca85c0c914c</uuid>
  </job>
</joblist>
```

This is my ansible inventory (three nodes with "the_farm" as a tag):

```bash
# test ssh farm
[the_farm]
192.168.33.20
192.168.33.21
192.168.33.22
```

If you check the default node executor ("Project Settings" > "Edit Configuration" and click on "Default Node Executor") probably you haven't selected the "Generate Inventory" checkbox.

![Screenshot_1](https://user-images.githubusercontent.com/51376003/78518421-68785780-778e-11ea-82ee-626d792e3c63.png)

And if you run the job as you described in the first message:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/78518446-7e861800-778e-11ea-96a8-4263c36e69ac.png)

Certainly, the playbook runs in all ansible inventory:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/78518457-834acc00-778e-11ea-8c22-1e0fefa9996a.png)

But if you select "Generate Inventory":

![Screenshot_4](https://user-images.githubusercontent.com/51376003/78518516-b0977a00-778e-11ea-833e-50915ca2bfb2.png)

The job honors the filter defined in your job definition:

![Screenshot_5](https://user-images.githubusercontent.com/51376003/78518536-bbeaa580-778e-11ea-921b-eec2eceb69a4.png)

Please try that and confirm.

Hope it helps!

**Comment by VivianeHonda** [comment]
Hello,

I do tests, already return with the result

Once again, thanks for the quick response

**Comment by VivianeHonda** [comment]
When performing the tests, we faced another problem:

In our projects, we make the connection with the servers via CyberArk.

The connection information is in the global variables within the inventory, an example of our inventory:

[all: vars]
ansible_user = xxxxxx
appID = xxxxx
apiUser = xxx

[UKC_R4-PRO_DC1-CARD]
server serverType = xxx was_version = xxx
server serverType = xxx was_version = xxx

[UKC_R4-PRO_DC1-CARD: vars]
entity = xxxx
gsenv = xxxx

When we enable the option "Generate Inventory", the global variables "[all: vars]" are blank. When we disable the option "Generate Inventory" the global variables come with value.

Is there any other configuration that we should apply with this one?

Here is the error that appears in the log:
WARNING: Failed to fetch password for hosts:
server (reason: ansible_user or app_id undefined)
server (reason: ansible_user or app_id undefined)

**Comment by VivianeHonda** [comment]
I'll do a new test with this information

**Comment by VivianeHonda** [comment]
Hello, this other ticket says it works when the NodeFilter is empty, but for our case, I could not leave the NodeFilter empty, since the user has to select where he wants to run the JOB.

When "Generate Inventory" is enabled, rundeck is using yml inventory plugin to parse the Inventory to json.
