### ISSUE TITLE
 Cannot get AuthContext without subject 

### ISSUE THREAD

**Issue by jtobard** [rundeck/rundeck#5927]
**Describe the bug**
If at the login page you press repeteadly the `Log In` button you see an error 500 page and you can't log out unless you enter manually the logout method in the URL: `user/logout`

**My Rundeck detail**

* Rundeck version: 3.2.4
* install type: war
* OS Name/version: ubuntu
* DB Type/version: mysql

**To Reproduce**
1. Try to login, fill user and pass
2. Click on 'Log In' multiple times
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/2894508/78051458-17aecc00-7354-11ea-8a58-ef2fbc2232d9.png)

**Desktop (please complete the following information):**
 - OS: linux
 - Browser latest chrome

**Additional context**
Similar to https://github.com/rundeck/rundeck/issues/4368 but is just the user in the browser that is stuck not the entire server as described there. Other similar issue: https://github.com/rundeck/rundeck/issues/3219

**Comment by sjrd218** [comment]
The login button can only be clicked once now, which prevents this error.
