### ISSUE TITLE
Project Description no longer supports underscores

### ISSUE THREAD

**Issue by askmike1** [rundeck/rundeck#5936]
**Describe the bug**
Project Description no longer supports underscores

**My Rundeck detail**

- Rundeck version:  3.2.1-20200113
- install type: (rpm,deb,war,launcher?) rpm
- OS Name/version: RHEL7/AWS
- DB Type/version: mysql? postgres? h2?.. MariaDB

**To Reproduce**
Via GUI:

1. Update a project's description to include underscore
2. Save
3. Go back into project configuration
4. Underscore is gone (all changes are gone)

Via API:

1. Create a project with description containing an underscore
2. API returns 200 as if it worked
3. Project was not created

(Removing underscore makes it work)

**Expected behavior**
Project description should be updated if there is an underscore in it

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 78

**Additional context**
N/A

Migrated from https://github.com/rundeck/rundeck/issues/3389

**Comment by fdevans** [comment]
Thanks for reposting Mike.  We'll take a look into this.

**Comment by MegaDrive68k** [comment]
Hi @askmike1 

I tested on 3.2.1 and at the moment of creating a new project with underscore at description field I get this error (but I can edit and save with underscores later):

![Screenshot_2](https://user-images.githubusercontent.com/51376003/78416702-266ddb00-7601-11ea-88f7-c8d625ce84b7.png)

But testing on 3.2.5 I can create a project with underscores at the same textbox without problems, can you try it with 3.2.5?

Thanks!

**Comment by sjrd218** [comment]
Fixed in #5755
