### ISSUE TITLE
CHANGELOG.md outdated

### ISSUE THREAD

**Issue by getjack** [rundeck/rundeck#5940]
**Describe the bug**
This is not really a bug but more a process problem. The master branch contains a CHANGELOG.md file which seems to be outdated (it shows the changes from 3.1.x) as the latest version 3.2.5 is not mentioned there. Furthermore, no information that the file will no longer be maintained is also missing.

Please clarify where we can find a changelog for this project.

**Comment by MegaDrive68k** [comment]
Hi @getjack 

You can follow all changes from here:

https://docs.rundeck.com/docs/history/3_2_x/version-3.2.5.html

If you see the left menu, you can select each Rundeck version and check any change/improvement.

Regards.
