### ISSUE TITLE
Job Execution Cleanup process creates many tmp files

### ISSUE THREAD

**Issue by jimr6007** [rundeck/rundeck#5943]
**Describe the bug**
50,000 plus files at /tmp/rundeck
with about 5000 executions per day I'm currently seeing about 50k execution-....xml files under /tmp/rundeck

would like to understand what's going on there, how often are those cleaned up, is this normal expected behavior etc.

**My Rundeck detail**

* Rundeck version: Rundeck 3.2.3-20200221
* install type: RPM
* OS Name/version: CentOS 7
* DB Type/version: postgres

**To Reproduce**
run jobs

**Expected behavior**
an understanding of what's going on in /tmp related to Rundeck

**Comment by MegaDrive68k** [comment]
Hi @jimr6007 

Can you share your `framework.properties` file and `rundeck-config.properties` file to check it (both at `/etc/rundeck` path)? Please change any sensitive information.

Thanks.

**Comment by jimr6007** [comment]
sure, both included below
just to be clear, I'm not suggesting this is a "bug", I expect this is normal behavior
I just want to understand what the config options are and what are the recommendations
how much stuff gets put at /tmp, how often is it cleanup etc.

thanks !

**framework.properties**
# framework.properties -
#

# ----------------------------------------------------------------
# Rundeck server connection information
# ----------------------------------------------------------------

framework.server.name = rundeck
framework.server.hostname = *********
framework.server.port =******
framework.server.url = *******

# ----------------------------------------------------------------
# Installation locations
# ----------------------------------------------------------------

rdeck.base=/var/lib/rundeck

framework.projects.dir=/var/rundeck/projects
framework.etc.dir=/etc/rundeck
framework.var.dir=/var/lib/rundeck/var
framework.tmp.dir=/var/lib/rundeck/var/tmp
framework.logs.dir=/var/lib/rundeck/logs
framework.libext.dir=/var/lib/rundeck/libext

# ----------------------------------------------------------------
# SSH defaults for node executor and file copier
# ----------------------------------------------------------------

framework.ssh.keypath = /var/lib/rundeck/.ssh/id_rsa
framework.ssh.user = rundeck

# ssh connection timeout after a specified number of milliseconds.
# "0" value means wait forever.
framework.ssh.timeout = 0


# ----------------------------------------------------------------
# Auto generated server UUID: ************
# ----------------------------------------------------------------
rundeck.server.uuid = ************





**rundeck-config.properties:**
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO

rdeck.base=/var/lib/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false

# change hostname here
grails.serverURL=********
grails.mail.host=********
grails.mail.port=2=******
grails.mail.default.from=*******

dataSource.driverClassName = org.postgresql.Driver
dataSource.url = jdbc:postgresql://localhost/rundeck
dataSource.username = rundeckuser
dataSource.password = **********

quartz.threadPool.threadCount = 30

rundeck.gui.startpage=jobs

rundeck.api.tokens.duration.max=0

rundeck.log4j.config.file = /etc/rundeck/log4j.properties

server.useForwardHeaders=true

**Comment by MegaDrive68k** [comment]
Hi again @jimr6007 

Another question: your current instance (3.2.3) is an upgrade from a previous version? In that case, which version?

Thanks!

**Comment by jimr6007** [comment]
yes, many upgrades, from way back years ago, at least 4 years, we try to stay current

**Comment by MegaDrive68k** [comment]
Hi @jimr6007 to keep digging this, also I need to take a look at your `profile` file (in the same `/etc/rundeck` path, as always, change any sensitive info). Thanks again!

**Comment by jimr6007** [comment]
Before I send you anything else, did you understand my last point? 
That is, maybe this is expected behavior and if so, can you give me more specific details on what happens, how many files should I expect, how often are they cleaned up?

Or, perhaps you are saying, "no" this is not expected.

Am i right about that?

**Comment by jimr6007** [comment]
prog="rundeckd"
[ -e /etc/sysconfig/$prog ] && . /etc/sysconfig/$prog
[ -e /etc/default/$prog ] && . /etc/default/$prog

RDECK_INSTALL="${RDECK_INSTALL:-/var/lib/rundeck}"
RDECK_BASE="${RDECK_BASE:-/var/lib/rundeck}"
RDECK_CONFIG="${RDECK_CONFIG:-/etc/rundeck}"
RDECK_CONFIG_FILE="${RDECK_CONFIG_FILE:-$RDECK_CONFIG/rundeck-config.properties}"
RDECK_SERVER_BASE="${RDECK_SERVER_BASE:-$RDECK_BASE}"
RDECK_SERVER_CONFIG="${RDECK_SERVER_CONFIG:-$RDECK_CONFIG}"
RDECK_SERVER_DATA="${RDECK_SERVER_DATA:-$RDECK_BASE/data}"
RDECK_PROJECTS="${RDECK_PROJECTS:-$RDECK_BASE/projects}"
RUNDECK_TEMPDIR="${RUNDECK_TEMPDIR:-/tmp/rundeck}"
RUNDECK_WORKDIR="${RUNDECK_TEMPDIR:-$RDECK_BASE/work}"
RUNDECK_LOGDIR="${RUNDECK_LOGDIR:-$RDECK_BASE/logs}"
RDECK_JVM_SETTINGS="${RDECK_JVM_SETTINGS:- -Xmx1024m -Xms256m -XX:MaxMetaspaceSize=256m -server}"
RDECK_TRUSTSTORE_FILE="${RDECK_TRUSTSTORE_FILE:-$RDECK_CONFIG/ssl/truststore}"
RDECK_TRUSTSTORE_TYPE="${RDECK_TRUSTSTORE_TYPE:-jks}"
JAAS_LOGIN="${JAAS_LOGIN:-true}"
JAAS_CONF="${JAAS_CONF:-$RDECK_CONFIG/jaas-loginmodule.conf}"
LOGIN_MODULE="${LOGIN_MODULE:-RDpropertyfilelogin}"
RDECK_HTTP_PORT=${RDECK_HTTP_PORT:-4440}
RDECK_HTTPS_PORT=${RDECK_HTTPS_PORT:-4443}


# If no JAVA_CMD, try to find it in $JAVA_HOME
if [ -z "$JAVA_CMD" ] && [ -n "$JAVA_HOME" ] && [ -x "$JAVA_HOME/bin/java" ] ; then
  JAVA_CMD=$JAVA_HOME/bin/java
  PATH=$PATH:$JAVA_HOME/bin
  export JAVA_HOME
elif [ -z "$JAVA_CMD" ] ; then
  JAVA_CMD=java
fi

# build classpath without lone : that includes .
for jar in $(find $RDECK_INSTALL/cli -name '*.jar') ; do
  CLI_CP=${CLI_CP:+$CLI_CP:}$jar
done
for war in $(find $RDECK_INSTALL/bootstrap -name '*.war') ; do
  EXECUTABLE_WAR=$war
done

RDECK_JVM="-Drundeck.jaaslogin=$JAAS_LOGIN \
           -Djava.security.auth.login.config=$JAAS_CONF \
           -Dloginmodule.name=$LOGIN_MODULE \
           -Drdeck.config=$RDECK_CONFIG \
           -Drundeck.server.configDir=$RDECK_SERVER_CONFIG \
           -Dserver.datastore.path=$RDECK_SERVER_DATA/rundeck \
           -Drundeck.server.serverDir=$RDECK_INSTALL \
           -Drdeck.projects=$RDECK_PROJECTS \
           -Drdeck.runlogs=$RUNDECK_LOGDIR \
           -Drundeck.config.location=$RDECK_CONFIG_FILE \
           -Djava.io.tmpdir=$RUNDECK_TEMPDIR \
           -Drundeck.server.workDir=$RUNDECK_WORKDIR \
           -Dserver.http.port=$RDECK_HTTP_PORT \
           -Drdeck.base=$RDECK_BASE"


#
# Set min/max heap size
#
RDECK_JVM="$RDECK_JVM $RDECK_JVM_SETTINGS"
#
# SSL Configuration - Uncomment the following to enable.  Check SSL.properties for details.
#
if [ -n "$RUNDECK_WITH_SSL" ] ; then
 RDECK_JVM="$RDECK_JVM -Drundeck.ssl.config=$RDECK_SERVER_CONFIG/ssl/ssl.properties -Dserver.https.port=${RDECK_HTTPS_PORT}"
fi

unset JRE_HOME

umask 002

rundeckd="$JAVA_CMD $RDECK_JVM $RDECK_JVM_OPTS -jar $EXECUTABLE_WAR --skipinstall"

**Comment by MegaDrive68k** [comment]
Hi @jimr6007 

That's not expected. The executions logs must be stored at `/var/lib/rundeck/logs/rundeck/YourProject/job/YourJobID/logs` path. On 3.2.3 fresh install, I can't see those files at `/tmp/rundeck` path, then I want to simulate your scenario closely.

Thanks for the info!

**Comment by jimr6007** [comment]
Thanks for helping me track this down. I actually thought this was something simple, perhaps just a config issue AND I noticed it while working with my test/qa setup which is a clean vanilla install of the latest. Then I started looking at my production env which has been around for years, many upgrades, lots of history etc and I noted 50k files at /tmp/rundeck.

I need to do more investigation, I used to think I knew where logs lived on the filesystem but not I'm seeing very confusion things when I look at the UI and places on the file system where I thought logs might be.

Also to note is the "history" of the execution cleanup in my prod environment. Way back, couple years ago I guess, the only way to clean up was via the API and that still required some manual DB cleanup. 

Fast forward to today and we have as you know, "automatic" cleanup scheduling options via the GUI and a much improved RD command line (which I'm sure just makes API calls).

The automatic GUI based cleanup scheduling was actually broken recently but I think that's fixed now.

At the moment I'm doing execution cleanup via RD cli and a shell script, run via Rundeck of course.

So there's more detail on the history but I did not go in to detail here on the "confusing" things I'm seeing at the file system.

Let me investigate a bit further so I can clearly note the exact details.

**Comment by MegaDrive68k** [comment]
Hi @jimr6007 

I reproduced the issue, i'll post more details soon.

Thanks for your feedback!

**Comment by jimr6007** [comment]
there's also this fyi that I noted last night:
https://github.com/rundeck/rundeck/wiki/FAQ#how-do-i-specify-a-new-temp-directory-for-rundeck

https://github.com/rundeck/rundeck/wiki/FAQ

**Comment by jimr6007** [comment]
Here is the important part of my daily executions cleanup, this is run against each project. But this does not correspond with what I see in /tmp/rundeck.

My "bulk delete" is "older than 14 days" but at /tmp/rundeck I'm seeing the last 10 days worth.

rd executions deletebulk -R -y -m ${RD_OPTION_BATCH:-200} --older ${RD_OPTION_OLDER_THAN:-14d} -p $project >/dev/null || break

and the output of the most recent cleanup run, no errors as far as I can tell:


01:00:01 | Starting delete of executions for project: AdServing-Production
-- | --
01:00:01 | deleting batch of 200 - Tue Apr 7 05:00:01 UTC 2020
01:00:06 | deleting batch of 200 - Tue Apr 7 05:00:06 UTC 2020
01:00:07 | No executions found to delete
01:00:12 | Starting delete of executions for project: BackupDBs
01:00:12 | deleting batch of 200 - Tue Apr 7 05:00:12 UTC 2020
01:00:25 | deleting batch of 200 - Tue Apr 7 05:00:25 UTC 2020
01:00:26 | No executions found to delete
01:00:31 | Starting delete of executions for project: Client-Log-Moving
01:00:31 | deleting batch of 200 - Tue Apr 7 05:00:31 UTC 2020
01:01:15 | deleting batch of 200 - Tue Apr 7 05:01:15 UTC 2020
01:01:57 | deleting batch of 200 - Tue Apr 7 05:01:57 UTC 2020
01:02:39 | deleting batch of 200 - Tue Apr 7 05:02:39 UTC 2020
01:03:22 | deleting batch of 200 - Tue Apr 7 05:03:22 UTC 2020
01:04:04 | deleting batch of 200 - Tue Apr 7 05:04:04 UTC 2020
01:04:46 | deleting batch of 200 - Tue Apr 7 05:04:46 UTC 2020
01:05:05 | deleting batch of 200 - Tue Apr 7 05:05:05 UTC 2020
01:05:06 | No executions found to delete
01:05:11 | Starting delete of executions for project: DBCheckReplication
01:05:11 | deleting batch of 200 - Tue Apr 7 05:05:11 UTC 2020
01:06:02 | deleting batch of 200 - Tue Apr 7 05:06:02 UTC 2020
01:06:54 | deleting batch of 200 - Tue Apr 7 05:06:54 UTC 2020
01:07:45 | deleting batch of 200 - Tue Apr 7 05:07:45 UTC 2020
01:08:36 | deleting batch of 200 - Tue Apr 7 05:08:36 UTC 2020
01:09:27 | deleting batch of 200 - Tue Apr 7 05:09:27 UTC 2020
01:10:18 | deleting batch of 200 - Tue Apr 7 05:10:18 UTC 2020
01:11:09 | deleting batch of 200 - Tue Apr 7 05:11:09 UTC 2020
01:11:22 | deleting batch of 200 - Tue Apr 7 05:11:22 UTC 2020
01:11:23 | No executions found to delete
01:11:28 | Starting delete of executions for project: Datamart
01:11:28 | deleting batch of 200 - Tue Apr 7 05:11:28 UTC 2020
01:11:33 | deleting batch of 200 - Tue Apr 7 05:11:33 UTC 2020
01:11:34 | No executions found to delete
01:11:39 | Starting delete of executions for project: Datamart_Dev
01:11:39 | deleting batch of 200 - Tue Apr 7 05:11:39 UTC 2020
01:11:43 | deleting batch of 200 - Tue Apr 7 05:11:43 UTC 2020
01:11:44 | No executions found to delete
01:11:49 | Starting delete of executions for project: Gitlab
01:11:49 | deleting batch of 200 - Tue Apr 7 05:11:49 UTC 2020
01:12:01 | deleting batch of 200 - Tue Apr 7 05:12:01 UTC 2020
01:12:02 | No executions found to delete
01:12:07 | Starting delete of executions for project: Hadoop
01:12:07 | deleting batch of 200 - Tue Apr 7 05:12:07 UTC 2020
01:12:44 | deleting batch of 200 - Tue Apr 7 05:12:44 UTC 2020
01:13:20 | deleting batch of 200 - Tue Apr 7 05:13:20 UTC 2020
01:13:56 | deleting batch of 200 - Tue Apr 7 05:13:56 UTC 2020
01:14:31 | deleting batch of 200 - Tue Apr 7 05:14:31 UTC 2020
01:15:06 | deleting batch of 200 - Tue Apr 7 05:15:06 UTC 2020
01:15:41 | deleting batch of 200 - Tue Apr 7 05:15:41 UTC 2020
01:16:18 | deleting batch of 200 - Tue Apr 7 05:16:18 UTC 2020
01:16:53 | deleting batch of 200 - Tue Apr 7 05:16:53 UTC 2020
01:17:21 | deleting batch of 200 - Tue Apr 7 05:17:21 UTC 2020
01:17:25 | deleting batch of 200 - Tue Apr 7 05:17:25 UTC 2020
01:17:26 | No executions found to delete
01:17:31 | Starting delete of executions for project: PIQ_Infrastructure
01:17:31 | deleting batch of 200 - Tue Apr 7 05:17:31 UTC 2020
01:18:32 | deleting batch of 200 - Tue Apr 7 05:18:32 UTC 2020
01:18:57 | deleting batch of 200 - Tue Apr 7 05:18:57 UTC 2020
01:18:58 | No executions found to delete
01:19:03 | Starting delete of executions for project: Production-Servers-Backup
01:19:03 | deleting batch of 200 - Tue Apr 7 05:19:03 UTC 2020
01:19:40 | deleting batch of 200 - Tue Apr 7 05:19:40 UTC 2020
01:19:41 | No executions found to delete
01:19:46 | Starting delete of executions for project: ProductionRollingRestarts
01:19:46 | deleting batch of 200 - Tue Apr 7 05:19:46 UTC 2020
01:19:47 | No executions found to delete
01:19:52 | Starting delete of executions for project: Rundeck_maintenance
01:19:52 | deleting batch of 200 - Tue Apr 7 05:19:52 UTC 2020
01:19:56 | deleting batch of 200 - Tue Apr 7 05:19:56 UTC 2020
01:19:57 | No executions found to delete
01:20:02 | Starting delete of executions for project: Vmware-ESXi
01:20:02 | deleting batch of 200 - Tue Apr 7 05:20:02 UTC 2020
01:20:21 | deleting batch of 200 - Tue Apr 7 05:20:21 UTC 2020
01:20:22 | No executions found to delete

**Comment by MegaDrive68k** [comment]
Confirmed.

Steps to reproduce (tested on 3.2.3 and 3.2.5):

1. Create any scheduled job and save it.
2. Open a terminal and check the `/tmp/rundeck` directory content in real-time with `watch -n0.1 ls`

![Screenshot_3](https://user-images.githubusercontent.com/51376003/78727922-fb86ce00-7903-11ea-8240-61e9ad412a0c.png)

Also, check the `service.log` in another terminal with `tail -f /var/log/rundeck/service.log`

3. Leave the scheduled job running some minutes and see in Activity panel that the job executions run normally.
4. Now, go to GUI, edit the Project Settings and activate "Execution History Clean" in this way:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/78727566-fe34f380-7902-11ea-8af4-914e7f8c8173.png)

5. Wait some minutes and later the XML files are generated in `/tmp/rundeck` directory (left terminal):

![Screenshot_2](https://user-images.githubusercontent.com/51376003/78727716-77cce180-7903-11ea-81e9-1e1dd9092020.png)

XML file content:

```xml
<executions>
  <execution id='6500'>
    <jobId>1b4867d3-6948-493a-809a-037585f71dac</jobId>
    <dateStarted>2020-04-07T19:54:21Z</dateStarted>
    <dateCompleted>2020-04-07T19:54:21Z</dateCompleted>
    <status>succeeded</status>
    <outputfilepath>output-6500.rdlog</outputfilepath>
    <failedNodeList />
    <succeededNodeList>192.168.33.11</succeededNodeList>
    <abortedby />
    <cancelled>false</cancelled>
    <argString />
    <loglevel>INFO</loglevel>
    <doNodedispatch>false</doNodedispatch>
    <executionType>scheduled</executionType>
    <project>Project5943</project>
    <user>admin</user>
    <workflow keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "hi"</exec>
      </command>
    </workflow>
    <fullJob>
      <scheduleEnabled>true</scheduleEnabled>
      <dispatch>
        <threadcount>1</threadcount>
        <keepgoing>false</keepgoing>
        <successOnEmptyNodeFilter>false</successOnEmptyNodeFilter>
        <excludePrecedence>true</excludePrecedence>
        <rankOrder>ascending</rankOrder>
      </dispatch>
      <nodefilters>
        <filter>name: node00</filter>
      </nodefilters>
      <defaultTab>nodes</defaultTab>
      <description></description>
      <uuid>1b4867d3-6948-493a-809a-037585f71dac</uuid>
      <executionEnabled>true</executionEnabled>
      <sequence keepgoing='false' strategy='node-first'>
        <command>
          <scriptfile>/var/lib/rundeck/myscript.sh</scriptfile>
          <fileExtension>.sh</fileExtension>
          <scriptargs />
          <scriptinterpreter>/bin/bash</scriptinterpreter>
        </command>
        <command>
          <exec>echo hi</exec>
        </command>
        <command>
          <scriptargs />
          <script><![CDATA[echo inline]]></script>
        </command>
      </sequence>
      <schedule>
        <time seconds='0/10' minute='*' hour='*' />
        <weekday day='*' />
        <month month='*' />
        <year year='*' />
      </schedule>
      <loglevel>INFO</loglevel>
      <name>HelloWorld</name>
      <nodesSelectedByDefault>true</nodesSelectedByDefault>
      <nodeFilterEditable>false</nodeFilterEditable>
      <id>1b4867d3-6948-493a-809a-037585f71dac</id>
    </fullJob>
  </execution>
</executions>
```

**NOTE 1:** The `service.log` file not shows any relevant information at the moment of file generation.
**NOTE 2:** The XML files seems generated a bit before the time defined in the "Execution History Clean" cron.

Thanks to @jimr6007 and @RomainQuinaud (https://github.com/rundeck/rundeck/issues/5910) for the feedback!

**Comment by jimr6007** [comment]
although this now appears to be a bug, I had originally opened this issue wanting to know what files I should actually expect to see under /tmp.

could you clarify that for me please?

I guess that maybe I would see things like "execution-62686828359889207510211223.xml" for "in progress" jobs. Is that correct?

Also wanted to confirm that which you probably already know. This issue with /tmp files is definitely related to Execution History Clean, or cleaning up executions via the API or the RD cli. In my case the time stamps of all the files under /tmp correspond exactly with my Rundeck job that runs every 12 hours and via a shell script calls RD cli to do bulk execution deletes.

And I guess this is all somehow related to the work done for:
https://github.com/rundeck/rundeck/issues/5274

For now is it safe to delete files from /tmp?

**Comment by RomainQuinaud** [comment]
Hey 
Thank you very much for you investigations on this @MegaDrive68k
As far as I know,  @jimr6007  it's safe to delete the files (we have a workaround to delete these files every 10 minutes). We did not experience any issue deleting these.
Looking forward to get it fixed in a future release :)
Have a great day !
