### ISSUE TITLE
Preauthentication : accept mail,firstname,lastname

### ISSUE THREAD

**Issue by mathieuchateau** [rundeck/rundeck#5947]
**Is your feature request related to a problem? Please describe.**
Users can log on through preauthentication, but mail, firstname and lastname attribute are not populated.

**Describe the solution you'd like**
As we can already map user & roles, allows to map variable containing these 3 missing attributes
rundeck.security.authorization.preauthenticated.userEmailHeader=X-Remote-User-Email
rundeck.security.authorization.preauthenticated.userFirstNAmeHeader=X-Remote-User-FirstName
rundeck.security.authorization.preauthenticated.userLastNAmeHeader=X-Remote-User-LastName

**Additional context**
Using:
-Rundeck 3.2.5
-Apache with mod_proxy & kerberos
-Using mod_lookup_identity to get attributes, groups mail & co

**Comment by karann-jain** [comment]
+1

**Comment by mxmo0rhuhn** [comment]
This would be very important in my eyes since users can otherwise barely use some important self-service features of rundeck in my eyes.

**Comment by qadv** [comment]
+1

**Comment by dusty73** [comment]
+1

**Comment by ebah80** [comment]
+1

**Comment by lukasreichart** [comment]
this feature would be very important to my organization ... +1

**Comment by bluikko** [comment]
It would be cool if RunDeck could use preauthenticated mode for authentication but still continue to use LDAP for authorization i.e. query LDAP for groups and the info like e-mail etc.
