### ISSUE TITLE
UI and API break after upgrade to v3.2.5

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#5950]
**Describe the bug**

I've been trying to troubleshoot this for hours but can't see anything wrong on my end... I'm currently running Rundeck 3.1.0-20190731 and everything works fine. I can access the GUI and also curl http://localhost:4440.

However when I update to the latest version (v3.2.5) the GUI stops working and curling http://localhost:4440 fails. But the strange thing is that the rundeckd service is up and running fine.

I restored from a previous snapshot and updated all packages _except_ rundeck and rundeck-cli to confirm something else wasn't the cause. Everything continued to work fine. It's only when I upgrade the rundeck package that things go weird.

Is this a known issue with 3.2.5? Or are there some configuration values that need to be changed? Nothing is mentioned in the documentation.

**My Rundeck detail**

* Rundeck version: 3.1.0-20190731
* OS Name/version: Ubuntu 18.04
* DB Type/version: mysql

**Comment by gschueler** [comment]
what install and upgrade process did you use?

when you say the GUI stops working, what do you mean? no response? or a broken UI?

**Comment by MegaDrive68k** [comment]
Hi @binaryfire 

Also, any clue checking the service.log file when tou try to access? (at /var/log/rundeck directory).

Thanks.

**Comment by binaryfire** [comment]
@gschueler Just **apt-get update** + **apt-get upgrade** And yeah, no response at all. Curl also says "connection refused" after updating. It's as though the service isn't running, but it is. 

@MegaDrive68k Nothing unusual in service.log as far as I can see

**Comment by MegaDrive68k** [comment]
Hi @binaryfire, just to discard, that upgrade includes a Java JDK? (for example from jdk8 to jdk11).

Greetings.

**Comment by binaryfire** [comment]
Hi @MegaDrive68k 

No, jdk is still 1.8.0_242. I'm thinking it might be easier to just re-image the server, install a fresh copy of Rundeck and copy over the database. I'm not sure what else to try!

**Comment by fdevans** [comment]
Hopefully this has been resolved.  Let us know if there's still an issue with the current version.
