### ISSUE TITLE
How do i do pbrun on rundeck job

### ISSUE THREAD

**Issue by sujansonly** [rundeck/rundeck#5951]
**Describe the bug**
Looking for details to do pbrun on remote node job execution

**My Rundeck detail**

* Rundeck version: Rundeck 3.1.2-20190927 
* install type: 
* OS Name/version: Linux
* DB Type/version: Oracle

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi,

Check this plugin:

https://github.com/ahonor/powerbroker-node-executor

Regards.
