### ISSUE TITLE
UI optimization (Project List Page)

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#5958]
Hi Team, Whenever we go to the project list page it takes a sec to load the failed counters. In addition, when the failed counters are loaded it adds an extra gap between the projects, this makes it harder to interact with the UI since the projects are shift down. 

![image](https://user-images.githubusercontent.com/20629911/79049559-2eb5af80-7bd9-11ea-9414-b1b599e855bd.png)

Thank you!
HS

**Comment by fdevans** [comment]
We are working on improvements to the Project page in 3.3.4 and 3.3.5.  Let us know after those releases if this is better.
