### ISSUE TITLE
Job State Conditonal project and group/name parsing buggy

### ISSUE THREAD

**Issue by falloutphil** [rundeck/rundeck#5959]
**Describe the bug**

Various group/name and project parsing issues with Job State Conditional.

When testing for running of a job nested in one or more groups and with whitespace in it's name Rundeck returns:
Job was not found: Not found

The same job referenced by UUID works fine (this is the workaround).

Testing various combinations of other group/name yields:
test - works
test word - works
Batch/test word - fails
Batch/test - works
Batch/Another Group/test word - fails

Also when referencing by group/name the log gives UUID:
{{Job abcd12345-a1234-4321-a123-6326cb123456}} is RUNNING . Expected NOT RUNNING

I'd expect it to give the Job Name in the log if the group/name was used to reference it. 

Also when referencing a job in another project the output suggested it wasn't picking up this setting.

Job was not found: Not found
Execution failed: 6513 in project FOOBAR:

Where FOOBAR was not the specified project to look-up the job we are conditional on, but rather the project containing Job State Conditional Workflow itself.

**My Rundeck detail**

* Rundeck version: 3.1.2-20190927 
* install type: deb
* OS Name/version: ubuntu 18.04

**Comment by MegaDrive68k** [comment]
Hi @falloutphil 

Can you share an example Job Definition to test?

I tested with the following job definitions and works (under 3.1.2 and 3.2.5 DEB/WAR):

Hello World (the job with  nested groups):

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <group>My Batch/my group</group>
    <id>54e64aa5-aaa2-4d74-acb2-5370698f1546</id>
    <loglevel>INFO</loglevel>
    <name>Hello World</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "hi"</exec>
      </command>
    </sequence>
    <uuid>54e64aa5-aaa2-4d74-acb2-5370698f1546</uuid>
  </job>
</joblist>
```
The job that verifies Hello World with Job State  Conditional:

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>27dde959-d698-4c08-8982-30037422b0fb</id>
    <loglevel>INFO</loglevel>
    <name>Verificator</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <step-plugin type='job-state-conditional'>
          <configuration>
            <entry key='condition' value='Equals' />
            <entry key='executionState' value='Succeeded' />
            <entry key='fail' value='false' />
            <entry key='halt' value='false' />
            <entry key='jobName' value='My Batch/my group/Hello World' />
          </configuration>
        </step-plugin>
      </command>
      <command>
        <exec>echo "verified!"</exec>
      </command>
    </sequence>
    <uuid>27dde959-d698-4c08-8982-30037422b0fb</uuid>
  </job>
</joblist>
```

![Screenshot_1](https://user-images.githubusercontent.com/51376003/79125044-79ffc780-7d6b-11ea-8feb-e1a82da45acf.png)

Thanks!

**Comment by MegaDrive68k** [comment]
I reproduced the issue right now, more details soon, thanks @falloutphil

**Comment by falloutphil** [comment]
Hi @MegaDrive68k 

Thanks for taking a look.

I've come back to this and spent an hour trying to reproduce this and I can't.  I'm baffled as I managed to produce this over a number of scenarios a few weeks ago - even recreating it from scratch with simple jobs - alas I didn't save these broken jobs down as xml so I have no reference anymore.

I wonder if there is a sequence of events to trigger a state where the job look-up doesn't work, but since neither you nor I can reproduce this reliably I will close this for now. 

If it happens again I will save down the xmls and ensure it is reproducible with the xmls before re-reporting.  Apologies for not capturing this, I assumed it was trivial to reproduce, but this no longer seems to be the case.
