### ISSUE TITLE
Deadlocks

### ISSUE THREAD

**Issue by tomdeblende** [rundeck/rundeck#5961]
Since a few days, we get a lot of deadlocks in our logs. Jobs are not executing. We tried the configuration change in https://github.com/rundeck/rundeck/issues/4255, to no avail.

**My Rundeck detail**

* Rundeck version: 3.2.5
* install type: rpm
* OS Name/version: Amazon Linux 2018.03
* DB Type/version: h2

Excerpt from logs attached.
[rundeck_service.log](https://github.com/rundeck/rundeck/files/4468837/rundeck_service.log)

**Comment by jtobard** [comment]
Hi @tomdeblende, what is the volume of operations of your instance? Approximate number of projects / jobs and how many executions per hour do you have? 
Just to try to replicate your environment

**Comment by tomdeblende** [comment]
Hi @jtobard! Thanks for your reply! There is only one project in use. It has 195 jobs. almost all of them kick off a shell command to start one or more EC2 instances. A lot of those run around the same time in the morning though. They run just once per day, sometimes they need one or two tries due to aws api throttling.

**Comment by MegaDrive68k** [comment]
Hi @tomdeblende 

I'm trying to reproduce the issue with a lot of jobs concurrently on H2 without success, but the main advice is moving to a "real" database like MySQL or PostgreSQL for example. If you want to run a lot of jobs or need scale your projects definitely you need a database as backend.

H2 is only for testing, here you have a good starting point:

https://docs.rundeck.com/docs/administration/configuration/database/

Here more info:

https://docs.rundeck.com/docs/administration/install/system-requirements.html#database

Regards!

**Comment by tomdeblende** [comment]
Switched to mysql, haven't had any issues since. Thanks!
