### ISSUE TITLE
Cant list or search for new plugins. 

### ISSUE THREAD

**Issue by dkscroggs** [rundeck/rundeck#5972]
Error Accessing Plugins
Plugins may not be an active feature in your Rundeck install.

**My Rundeck detail**

* Rundeck version: [ 3.2.5]
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [docker image]

**To Reproduce**
1. Go to settings
2. Click on plugins
3. Scroll down to find plugins
4. see error Error Accessing Plugins
Plugins may not be an active feature in your Rundeck install.

see plugin search page 

**Screenshots**
![image](https://user-images.githubusercontent.com/42246307/79389209-edeccc00-7f33-11ea-812a-25b81cd9a503.png)

**Comment by sjrd218** [comment]
@dkscroggs Do you see an error in your server logs that says something about a communication failure?

**Comment by dkscroggs** [comment]
@sjrd218 I think I found the issue:

[2020-04-15 22:00:35.176] ERROR ConnectionPool --- [           main] Unable to create initial connections of pool.

org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-199]

I was running 3.1 without issues but no webhooks in it, so I changed to 3.2.5.using the h2 db:

pertinent config from rundeck-config.properties

dataSource.dbCreate = update
dataSource.url = jdbc:h2:file:/home/rundeck/server/data/grailsdb;MVCC=true
dataSource.username =
dataSource.password =

**Comment by sjrd218** [comment]
You might have a zombie process that is keeping the database open. Make
sure you have all Rundeck process shut down then bring it back up again.

**Comment by dkscroggs** [comment]
this is on a fresh pod, killed and brought server back up this is the only things running in the pod:

USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
rundeck       82  0.0  0.0  19984  3812 pts/0    Ss   21:56   0:00 /bin/bash
rundeck      179  0.0  0.0  36128  3268 pts/0    R+   23:09   0:00  \_ ps fauxww
rundeck        1  0.0  0.0  19760  3256 ?        Ss   20:59   0:00 /bin/sh -c echo <redacted>$,user,admin,architect,deploy,build > /home/rundeck/server/config/realm.properties && /home/rundeck/docker-lib/entry.sh
rundeck        6  2.2  4.5 19052588 704884 ?     Sl   20:59   2:57 java -XX:+UnlockExperimentalVMOptions -XX:MaxRAMFraction=1 -XX:+UseCGroupMemoryLimitForHeap -Dloginmodule.conf.name=jaas-loginmodule.conf -Dloginmodule.name=rundeck -Drundeck.jaaslogin=true -Drundeck.jetty.connector.forwarded=true -jar rundeck.war

**Comment by sjrd218** [comment]
@dkscroggs Do you have an old lock file in the dir: `/home/rundeck/server/data/` or the persistent directory that you have that mapped to in your docker config?

I would highly recommend upgrading your database to a server db like Postgresql. Using h2 with docker is not a recommended configuration.

**Comment by fdevans** [comment]
@dkscroggs Just checking back in on this.  Were you able to resolve your issue?

**Comment by abassanini** [comment]
I had the same problem.  I resolved it configuring the correct `grails.serverURL`
I was using: `grails.serverURL=http://localhost:4440` but my rundeck is published using Apache Mod_Proxy with SSL, so I changed the variable to `grails.serverURL=https://server.domain.com` and it is working now

Hope it helps someone

**Comment by ifelsefi** [comment]
Hello,

I am having the same problem with Rundeck 3.3.10 and 3.3.11 running in Kubernetes using a [helm chart.](https://artifacthub.io/packages/helm/dwardu-helm-charts/rundeck) 

I have the plugins present in the Rundeck container, with user rundeck owning them, but this error still appears.

```
rundeck@rundeck-77f8c57f7-fdgfw:~$ pwd
/home/rundeck

rundeck@rundeck-77f8c57f7-fdgfw:~$ ls -tlr ~/
total 172520
-rw-rw-r-- 1 rundeck root 176619423 Apr  6 23:35 rundeck.war
drwxrwxr-x 2 rundeck root      4096 Apr  6 23:35 user-assets
drwxrwxr-x 1 rundeck root      4096 Apr  6 23:35 server
drwxr-xr-x 3 rundeck root      4096 Apr  6 23:35 docker-lib
drwxrwsrwt 3 root    1000       100 Apr  7 14:41 extra
drwxrwxr-x 1 rundeck root      4096 Apr  7 14:42 etc
drwxr-xr-x 4 rundeck root      4096 Apr  7 14:42 repository
drwxrwsrwx 3 rundeck root      4096 Apr  7 14:42 libext
drwxr-xr-x 2 rundeck root      4096 Apr  7 14:42 projects
drwxrwxr-x 1 rundeck root      4096 Apr  7 14:43 var
rundeck@rundeck-77f8c57f7-fdgfw:~$ ls -ltr libext/

total 18068
-rw-r--r--  1 rundeck root  285834 Apr  7 14:42 kubernetes-plugin-2.0.4.zip
-rw-r--r--  1 rundeck root  291891 Apr  7 14:42 rundeck-ansible-plugin-3.1.0.jar
-rw-r--r--  1 rundeck root   29677 Apr  7 14:42 py-winrm-plugin-2.0.12.zip
-rw-r--r--  1 rundeck root 4852707 Apr  7 14:42 aws-s3-model-source-v1.0.6.jar
-rw-r--r--  1 rundeck root  293772 Apr  7 14:42 openssh-node-execution-2.0.1.zip
-rw-r--r--  1 rundeck root    9118 Apr  7 14:42 multiline-regex-datacapture-filter-1.0.0.jar
-rw-r--r--  1 rundeck root    9775 Apr  7 14:42 attribute-match-node-enhancer-v0.1.5.jar
-rw-r--r--  1 rundeck root 5471787 Apr  7 14:42 sshj-plugin-v0.1.1.jar
-rw-r--r--  1 rundeck root   19177 Apr  7 14:42 rundeck-stub-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root   16314 Apr  7 14:42 rundeck-script-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root    7141 Apr  7 14:42 rundeck-localexec-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root    6377 Apr  7 14:42 rundeck-job-state-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root    5895 Apr  7 14:42 rundeck-copyfile-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root  130689 Apr  7 14:42 rundeck-jasypt-encryption-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root    4102 Apr  7 14:42 rundeck-flow-control-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root 3903636 Apr  7 14:42 rundeck-object-store-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root   12929 Apr  7 14:42 rundeck-orchestrator-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root    2453 Apr  7 14:42 rundeck-source-refresh-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root 3100930 Apr  7 14:42 rundeck-git-plugin-3.3.11-rc2-20210406.jar
-rw-r--r--  1 rundeck root    3450 Apr  7 14:42 rundeck-upvar-plugin-3.3.11-rc2-20210406.jar
drwxr-sr-x 22 rundeck root    4096 Apr  7 14:43 cache

```

I do not see any error in logs that suggest communication issues.   I am using MariaDB backend without problems. 

Can you please help?

**Comment by fdevans** [comment]
@ifelsefi Can you please confirm the previously suggested fixes?  What database version are you using, have you checked for the lock file suggested by @sjrd218, properly set the grails.url?

Note: 3.3.11 isn't released as of today. It's still in QA.

**Comment by marceloats** [comment]
> I had the same problem. I resolved it configuring the correct `grails.serverURL`
> I was using: `grails.serverURL=http://localhost:4440` but my rundeck is published using Apache Mod_Proxy with SSL, so I changed the variable to `grails.serverURL=https://server.domain.com` and it is working now
> 
> Hope it helps someone

This worked for me as well
