### ISSUE TITLE
SSH user configuration is ignored in Ansible Resource Model Source

### ISSUE THREAD

**Issue by ilyakruchinin** [rundeck/rundeck#5975]
When configuring "Edit Nodes" and editing "Ansible Resource Model Source" and pointing it to a file with Ansible vmware_vm_inventory configuration, the "SSH Connection" -> "SSH User" GUI item is ignored by Rundeck.
All the nodes become available in Rundeck with the default (rundeck@HOST) username, instead of the configured (SSH User = myuser) username

* Rundeck version: 3.2.5 (was the same issue on 3.2.4 as well)
* install type: deb]
* OS Name/version: Ubuntu 18.04 with latest patches applied
* DB Type/version: H2

1. Go to 'Project Settings' -> 'Edit Nodes' -> 'Ansible Resource Model Source' - 'Edit'
2. Configure 'ansible inventory File path' to point to 'inventory.vmware.yml'
3. Set 'Gather Facts' to 'False'
4. In 'SSH Connection' section, set 'SSH Authentication to privateKey, set **'SSH User'** to **'myuser'** and set 'SSH Key File path' to correct key. Click 'Save'
5. Edit 'inventory.vmware.yml' as per https://docs.ansible.com/ansible/latest/plugins/inventory/vmware_vm_inventory.html. Save the file.
6. Click 'Save' in the 'Edit Nodes' GUI. Wait for a few minutes

**Expected behavior**
After a few minutes the 'NODES' -> 'All nodes' -> 'Show all nodes' should display a list of all VMware nodes retrieved from vCenter with USER@HOST column displaying 'myuser@IP'

**Actual behaiour**
The list of nodes is displayed (retrived from vCenter), but the USER@HOST column has 'rundeck@IP' for all nodes (instead of the expected 'myuser@IP')

**Screenshots**
3 screenshots attached

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 80

**Additional context**
Because of the bug, fact checking (Gather Facts) cannot be done by Rundeck and incorrect user is used by default in Rundeck inventory for all nodes

![user-configured](https://user-images.githubusercontent.com/16409780/79415402-ad06bd00-7ff0-11ea-8b46-898795b5c2c7.png)
![user-rundeck](https://user-images.githubusercontent.com/16409780/79415412-b3953480-7ff0-11ea-9a0a-aab0198f7202.png)
![user-vcentercreds](https://user-images.githubusercontent.com/16409780/79415416-b7c15200-7ff0-11ea-8f19-9f0f65bfece4.png)

**Comment by MegaDrive68k** [comment]
Hi @ilyakruchinin 

I see the same behavior, please open a new issue here:

https://github.com/Batix/rundeck-ansible-plugin/issues

Thanks!
