### ISSUE TITLE
resource model Format: resourcejson does not load big files

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#5988]
**Describe the bug**

When trying to load a "resourcejson" file for node resources that are sized around 1.4 MB, it shows an error in the service log and doesn't get loaded.

**My Rundeck detail**

Tested with Rd 3.0.16, Rd 3.1.2 and Rd 3.2.5

Expected behavior
Load the nodes in the node views of the Rundeck GUI

**Steps to reproduce;**
Create a resource model file with Format: resourcejson
![image](https://user-images.githubusercontent.com/36487101/79806320-1f9bd380-8336-11ea-961e-411b71e2beca.png)

After saving the settings, you'll see this error message in the service.log:
2020-04-19 20:16:02,687 ERROR ProjectNodeSupport - Cannot get nodes from [ProjectNodeSupport.LoadedSource(index=2, type=file)]: null

And no nodes will be loaded in the nodes view:
![image](https://user-images.githubusercontent.com/36487101/79806550-a9e43780-8336-11ea-8345-e374c2bc6caa.png)

![image](https://user-images.githubusercontent.com/36487101/79810739-aace9680-8341-11ea-95b2-1b99fc857eec.png)

If you load the same file with Format: "resourceyaml", even a bigger file, it will show no error message in the service.log and the nodes will be loaded.
![image](https://user-images.githubusercontent.com/36487101/79806668-f3cd1d80-8336-11ea-8c2a-c5a16ca1f5e0.png)

![image](https://user-images.githubusercontent.com/36487101/79810620-722ebd00-8341-11ea-9f8e-31e75e6f3460.png)

nodes.json file is uploaded to this Github issue for reproducing purposes.
[nodes.json.zip](https://github.com/rundeck/rundeck/files/4506897/nodes.json.zip)

**Comment by carlosrfranco** [comment]
It seems that the JSON file has a syntax error that causes this failure to load nodes.
When I try to use this JSON without changes I have this:
![error_saving_json_file](https://user-images.githubusercontent.com/7209908/80372866-92430c80-886a-11ea-8790-51ed87a3c230.png)

and, on the nodes page I have this result:

![error_show_nodes](https://user-images.githubusercontent.com/7209908/80372909-a555dc80-886a-11ea-8fa1-a44100468af8.png)

But, when I remove this comma in the last lines of JSON file:

![fixing_json_file](https://user-images.githubusercontent.com/7209908/80372990-c4ed0500-886a-11ea-9418-0a130b455eb6.png)

So, the nodes was loaded without error:

![no_error_json_file](https://user-images.githubusercontent.com/7209908/80373061-dfbf7980-886a-11ea-9507-560fbcd0c492.png)



So, could you please confirm if this change in JSON fixes the issue? Let me know if the error persists. 

Thanks

**Comment by carlosrfranco** [comment]
Reproduced with a file over 4Mb

**Comment by cwaltherf** [comment]
Hello Carlos, please remove that ponit. Please contact me for further details. Thanks!
