### ISSUE TITLE
the installonly option is not working properly

### ISSUE THREAD

**Issue by dportabella** [rundeck/rundeck#599]
```
$ rundeck_launcher=rundeck-launcher-1.6.2.jar
$ rundeck_server_http_port=14440
$ rundeck_server_https_port=14443
$ rundeck_download_url=http://download.rundeck.org/jar/$rundeck_launcher
$ export RDECK_BASE=$HOME/bin/rundeck
$ mkdir -p $RDECK_BASE 
$ cd $RDECK_BASE    
$ wget -O"$rundeck_launcher" "$rundeck_download_url"
$ java "-Dserver.http.port=$rundeck_server_http_port" "-Dserver.https.port=$rundeck_server_https_port"  -jar "$rundeck_launcher" --installonly
$ ./server/sbin/rundeckd start
```

---

this fails, because it requires directories etc and var to be present. 
i think that the "--installonly" option should also create etc and var directories.

also, it sets ./server/config/rundeck-config.properties:
 grails.serverURL=http://Mac4c.local:14440

but it does not set ./etc/preferences.properties:
 server.http.port=14440

so, running "./server/sbin/rundeckd start" will use the default port 4440.

---

in my opinion, the "--installonly" option should also create all the etc files (./etc/preferences.properties and others).

why are these etc files created when launching the application, instead of during the installation phase?
and, once these files are created, are they ever modified by the application?

**Comment by kampka** [comment]
Is there any chance to get this fixed in the near future?
Not having a working installer makes it pretty cumbersome to install rundeck in an unattended / automated fashion on non-deb/rpm systems.

**Comment by fdevans** [comment]
In an effort to focus on bugs and issues that impact currently supported versions of Rundeck, we have elected to notify GitHub issue creators if their issue is classified as stale and close the issue. An issue is identified as stale when there have been no new comments, responses or other activity within the last 12 months. If a closed issue is still present please feel free to open a new Issue against the current version and we will review it. If you are an enterprise customer, please contact your Rundeck Support to assist in your request.
Thank you, The Rundeck Team
