### ISSUE TITLE
"Log Output" on large output eats up all the memory

### ISSUE THREAD

**Issue by kyok0** [rundeck/rundeck#5992]
**Describe the bug**
Clicking "Log Output" where you have: 

- large amount of servers
- large output for each server

will slowly make the UI unusable as it keeps loading output of each server into memory, even if you click away back to "Report". (See screenshots)

**My Rundeck detail**

* Rundeck version: 3.0.21-20190424
* install type: rpm
* OS Name/version: Centos 7
* DB Type/version: mysql

**To Reproduce**
1. Go to "Log Output" 
2. Click back to "Report"
3. Check chrome network tab
4. See that API calls are still being made. If you have large data to work with, this will become a problem as it keeps filling up the memory with data that you are not observing any more. 

**Expected behavior**
Clicking away from "Log Output" should stop all API calls in order to avoid performance degradation

**Screenshots**
![Screenshot 2020-04-23 at 12 12 38](https://user-images.githubusercontent.com/20028942/80088602-06c13700-855d-11ea-9807-6d437e99de5b.png)
![Screenshot 2020-04-23 at 11 55 42](https://user-images.githubusercontent.com/20028942/80088636-12acf900-855d-11ea-9e3e-27c96ec9d7a8.png)

**Desktop (please complete the following information):**
 - OS: osx
 - Browser: Chrome (but observable in multiple browsers)
 - Version: 81.0.4044.92

**Additional context**
Although stopping calls when clicking away from "Log Output" will help with the above issue, if you actually want to use "Log Output", it will not be usable after a while, if you're dealing with large outputs. 

One solution, especially for jobs that are no longer running, would be to load only items you have scrolled past. (That is, if  you still want to make Log Output load/expand everything..)
This would help make the "Log Output" perform better when working with large data, and relief the backend of doing unnecessary queries. 

However, the issue is still present if you want to use "Log Output" to tail the output in real time. 
It just won't work for large outputs. 

If you require additional information, let me know. 

Thanks, 
Ivan

**Comment by fdevans** [comment]
Thanks for the feedback. We have an improved Log Output Viewer on our roadmap.

**Comment by fdevans** [comment]
Have you tried the latest Log Viewer?  Please provide feedback on that newer version and let us know in a new issue.
