### ISSUE TITLE
Webhook job plugin not allowing custom uuid

### ISSUE THREAD

**Issue by laubstein** [rundeck/rundeck#5998]
**Describe the bug**
While trying to set the job with uuid `this_is_a_test` to a webhook, I receive the message: 

> Invalid value: Expected 36 characters, saw input: 'this_is_a_test'

**My Rundeck detail**

* Rundeck version: 3.2.5
* install type: launcher
* OS Name/version: Centos
* DB Type/version: postgres

**To Reproduce**
1. Go to a 'Project'
2. Click on 'Webhook'
3. Click on 'add'
4. Choose the plugin 'Run Job'
5. Select a job with custom uuid
6. Click on 'Create Webhook'
7. See error

**Expected behavior**
Webhook created

**Comment by MegaDrive68k** [comment]
Reproduced on 3.2.6.

![Screenshot_3](https://user-images.githubusercontent.com/51376003/80525508-5b025780-895f-11ea-8ac8-a4e59a7c93d2.png)


Thanks @laubstein for the feedback!
