### ISSUE TITLE
Job activity list is empty when the job has a custom uuid

### ISSUE THREAD

**Issue by laubstein** [rundeck/rundeck#5999]
**Describe the bug**
Job activity list is empty when the job has a custom uuid.

**My Rundeck detail**

* Rundeck version: 3.2.5
* install type: launcher
* OS Name/version: Centos
* DB Type/version: postgres

**To Reproduce**
1. Go to a 'Project'
2. Create a job with custom id (e.g.: `this_is_a_test`)
3. Execute the job
4. Go to the job page
5. Click on 'Activity'
6. See the empty list

**Expected behavior**
A list with one line.

**Screenshots**

![image](https://user-images.githubusercontent.com/457100/80242841-6a6e6180-863c-11ea-8a6e-5637ca8baea8.png)

![image](https://user-images.githubusercontent.com/457100/80242861-6fcbac00-863c-11ea-9898-6683c4193dfe.png)

**Comment by MegaDrive68k** [comment]
Hi @laubstein 

This issue is reported here: https://github.com/rundeck/rundeck/issues/5194

Thanks for your feedback.

**Comment by laubstein** [comment]
Ouch!

thks @MegaDrive68k ... I've send a pull request with the fix that (#6000)
