### ISSUE TITLE
Jobs migrated from Rundeck2 to Rundeck 3 have "search by UUID" option set by default.

### ISSUE THREAD

**Issue by elioe** [rundeck/rundeck#6001]
**Describe the bug**
When a referenced Jobs using the name but not UUID in Parent Job Rundeck version 2.X (specifically 2.4.11) when the job is migrated/imported into a Rundeck version 3.2.5 on the **Select job by** section its appears selected by UUID and it's not available.

**My Rundeck detail**

* Rundeck version: 3.2.5
* install type: rpm, war
* OS Name/version:  ubuntu 18.04
* DB Type/version: MySQL - H2

**Expected behavior**
The Jobs remains referenced by Name.

**Screenshots**
![image_004](https://user-images.githubusercontent.com/48806282/80269056-7bd65e80-867a-11ea-82b9-158f8cb3cca6.png)

![image_005](https://user-images.githubusercontent.com/48806282/80269061-885ab700-867a-11ea-9922-57e65fd2b0f3.png)

![image_006](https://user-images.githubusercontent.com/48806282/80269067-927cb580-867a-11ea-9b5c-02af6b099645.png)

![image_008](https://user-images.githubusercontent.com/48806282/80269078-9f99a480-867a-11ea-9df6-6ecbb2783949.png)

![image_007](https://user-images.githubusercontent.com/48806282/80269080-a58f8580-867a-11ea-861d-5fcad7dc8f4e.png)

![image_009](https://user-images.githubusercontent.com/48806282/80269185-57c74d00-867b-11ea-89c2-6bd36d604679.png)

![image_010](https://user-images.githubusercontent.com/48806282/80269186-5bf36a80-867b-11ea-8f18-cf2ea028c877.png)

**Additional context**
Reviewing the yaml file with the job definition for the Rundeck version 3.x uses a **useName: 'true'** argument when a child job is referenced by Name that is not used by Rundeck 2.x

**Comment by carlosrfranco** [comment]
I could not reproduce the error where the child job is not found. Despite the option to search for the child job by UUID is shown as marked when editing referenced job step, the parent job is executed normally, as long as the child jobs are imported before or after the parent job was imported. Do you have more info to share that I need to consider on this case?

This is my exported job from Rundeck 2.4:
![job_exported_from_r2](https://user-images.githubusercontent.com/7209908/80409579-7c037380-889f-11ea-9bed-3699991321f7.png)

and this is the state of the referenced job when editing on Rundeck 3.2.5 after importing the job:
![editing_joob_imported_to_r3](https://user-images.githubusercontent.com/7209908/80409619-8f164380-889f-11ea-84a8-73b96c4d0be5.png)

And this is the result after run job:
![result_executing_parent_job_imported_to_rd3](https://user-images.githubusercontent.com/7209908/80409690-aead6c00-889f-11ea-90ad-d67926ddcf17.png)

The only case that the error **job not found** happened is when the child jobs was not imported on Rundeck 3
