### ISSUE TITLE
Rundeck Database default H2 crashes most of the time between shutdowns and power on.

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/rundeck#6003]
**Describe the bug**
Rundeck Database default H2 crashes most of the time between shutdowns and power on.

In my env, I have the constant issue where I use a clean H2 database and this in normal usage and a couple of "restarts" gets corrupt.

```
org.h2.jdbc.JdbcSQLNonTransientConnectionException: File corrupted while reading record: null. Possible solution: use the recovery tool [90030-199]
```
```
Caused by: java.lang.IllegalStateException: File corrupted in chunk 38089, expected page length 4..3072, got 1644167184 [1.4.199/6]
```

**My Rundeck detail**

* Rundeck version: 3.2.5
* install type: RPM, WAR
* OS Name/version: CentOS 7, gpt ext4
* DB Type/version: H2

**To Reproduce**
Steps to reproduce the behaviour:
Use H2 database normally, turn off your machine and turn on a couple of times with the Rundeck Service on boot. Eventually, this database got corrupt.

**Expected behaviour**
Should not get corrupt?

**Screenshots**
[service.log](https://github.com/rundeck/rundeck/files/4542260/service.log)
[recovery-using-h2-1.4.199.log](https://github.com/rundeck/rundeck/files/4542264/recovery-using-h2-1.4.199.log)
[recovery-using-h2-1.4.200.log](https://github.com/rundeck/rundeck/files/4542265/recovery-using-h2-1.4.200.log)
[build.log](https://github.com/rundeck/rundeck/files/4542284/build.log)
[test.zip](https://github.com/rundeck/rundeck/files/4542290/test.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10, build 1909
 - Browser: Opera GX
 - Version: LVL1 (core: 67.0.3575.130)

**Additional context**
I've been working on the fix replacing the default h2 library embedded on the WAR (1.4.199) with the latest version (1.4.200) because is a known issue from versions 196-199, based on [this Github Issue](https://github.com/h2database/h2database/issues/709#issuecomment-559012179), modifying on the file:

https://github.com/rundeck/rundeck/blob/3243b5627c8b24642e521c38b5903b34209aa9dc/rundeckapp/build.gradle#L132

Building with: `./gradlew clean build -x test -x integrationTest`

And use the War file with a modified version of the rundeck-config.properties file removing the MVCC, because is not needed anymore from 1.4.198, based on [this Github Issue](https://github.com/h2database/h2database/issues/2198#issuecomment-545003114), on the following line:

https://github.com/rundeck/rundeck/blob/3243b5627c8b24642e521c38b5903b34209aa9dc/rundeckapp/templates/config/rundeck-config.properties.template#L10

**Where Rundeck Starts normally and without any problems even using this "corrupted h2 database".**

I tested also creating keys, ACL, projects, jobs, run jobs, using the Database, and all works perfectly.

I also modified the following files to build without the flags **-x test** and **-x integrationTest**, deleting the MVCC flags:

```
        modified:   docker/official/README.md
        modified:   docker/official/remco/templates/rundeck-config.properties
        modified:   rundeckapp/metricsweb/grails-app/conf/DataSource.groovy
        modified:   rundeckapp/templates/config/rundeck-config.properties.template
        modified:   test/docker/dockers/rundeck/scripts/start_rundeck.sh
        modified:   test/docker/dockers/tomcat/rundeck-config.properties
```

But I got some issues related to Docker tests:

```
java.lang.IllegalStateException: Could not find a valid Docker environment. Please see logs and check configuration
```

I tried **-x test** and I got build successfully:

```
BUILD SUCCESSFUL in 5m 55s
199 actionable tasks: 196 executed, 3 up-to-date
```

h2 1.4.200 changelog
https://h2database.com/html/changelog.html

**Comment by G3NSVRV** [comment]
https://h2database.com/html/changelog.html

**Comment by G3NSVRV** [comment]
tried -x and I got build successful:

```
BUILD SUCCESSFUL in 5m 55s
199 actionable tasks: 196 executed, 3 up-to-date
```

**Comment by fdevans** [comment]
Assigned Schueler and Zapp for review

**Comment by ProTip** [comment]
@G3NSVRV Is this still an issue? I believe h2 may have been updated since this was opened.

**Comment by G3NSVRV** [comment]
@ProTip I decompress the latest version of Rundeck (3.3.10) and it looks that you are still using the same old H2 driver:

 ```shell
g3nsvrv@DESKTOP-QSHPCR7:/mnt/d/Personal/Downloads/rundeckpro$ jar xvf rundeckpro-enterprise-3.3.10-20210301.war

rundeckpro$ find $PWD -name h2*.jar
/mnt/d/Personal/Downloads/rundeckpro/WEB-INF/lib/h2-1.4.199.jar
```

**Comment by ProTip** [comment]
Mitigation steps have been taken in https://github.com/rundeck/rundeck/pull/6881 to reduce shutdown errors. 

We are on the second-to-last patch release of H2 which has not seen a new release in over a year. The latest release conflicts with Grails GORM so it has not been updated.

File corruption is a common theme and topic with H2(including in `1.4.200`; https://github.com/h2database/h2database/issues?q=is%3Aissue+is%3Aopen+corrupt . It's one of the reasons we do not support it for production installations. Our end-to-end testing is either using MySQL or moving towards it.

It's unlikely we will pursue h2 corruption issues further at this time.
