### ISSUE TITLE
API : ping/pong inconsistent with other calls

### ISSUE THREAD

**Issue by xavier8854** [rundeck/rundeck#6018]
**Describe the bug**
GET /api/25/metrics/ping returns plain text

**My Rundeck detail**
All versions affected

* Rundeck version: 3.2.6
* install type: rpm
* OS Name/version: RHEL 7.7
* DB Type/version: mariadb 5.5

**To Reproduce**
Send a GET /api/25/metrics/ping toRundeck
It returns pong in plain text

**Expected behavior**
Should return a json or xml response in order to remain consistent with ALL others API calls

**Desktop (please complete the following information):**
 - OS: Ubuntu 19.10
 - Browser n/a
 - Version n/a

**Comment by MegaDrive68k** [comment]
Hi @xavier8854 

That's expected behavior, if you check the documentation, you can see that response is text-plain by design:

https://docs.rundeck.com/docs/api/rundeck-api.html#metrics-ping

Regards!
