### ISSUE TITLE
Webhooks - custom response

### ISSUE THREAD

**Issue by KonradHolubek** [rundeck/rundeck#6019]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Describe the solution you'd like**
In webhooks, I would like to be able to make a custom http header response. Currently, when an app/service makes a POST to the rundeck webhook URL, rundeck responds with a classic "200 ok" header. 

However, certain apps require a custom response. As an example, to subscribe to slack events, Slack POST a request with a challenge parameter, and the endpoint (Rundeck) must respond with the challenge value (link : https://api.slack.com/events/url_verification).

When using Nodejs, this is how I solve this issue : 
`router.post('/events', async (req, res) => {
    let status = 200
    res.status(status).send(req.body.challenge)
})`

So in rundeck webhook management, I would imagine a 3rd option (example: Log events, Run Jobs, Custom response) where I could input a custom status and body response to incoming webhook events.

**Comment by fdevans** [comment]
Hi @KonradHolubek.  [Webhook Event Plugins](https://docs.rundeck.com/docs/developer/16-webhook-plugins.html#about) can be written to handle these types of custom responses.  At some point in the future we will look into a Slack handler.
