### ISSUE TITLE
preserve quotes used in commands

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#602]
If a command has a quoted string e.g. `echo " hi there"`, the quotes are interpreted when read by rundeck, but not preserved literally on output.  Current rules require double-quoting of input strings to emit literal quotes: http://rundeck.org/docs/manual/job-workflows.html#quoting-arguments-to-steps

Suggested enhancement to make this more intuitive:

if an argument string has spaces and is not quoted (and is does not contain variable expansion like `${option.value}`, it should be emitted quotes added

**Comment by span** [comment]
I also ran into this when trying to execute salt commands as Rundeck jobs. I worked around it putting my commands in as scripts instead, which is not ideal since I would like to see the commands clearly.

Example:
Command in Rundeck: sudo salt -G "os:Ubuntu" cmd.run "apt-get update"
Command deployed on node: sudo salt -G os:Ubuntu cmd.run apt-get update

The resulting command is not valid and the salt command thus fails.

**Comment by gschueler** [comment]
@span for simple quoted strings, try an extra set of single quotes, e.g. `sudo salt -G "'os:Ubuntu'" cmd.run "'apt-get updated'"`

**Comment by sparr** [comment]
Chiming in to say that I find this behavior exceptionally non-intuitive. I just spent far more time than I should have needed to, figuring out that rundeck was stripping quotes out of my commands.

**Comment by looprock** [comment]
I'm migrating a command line job from 1.6 to 2.5 (yeah, big jump I know), and it appears the double quotes aren't being honored anymore.


This is the command line:
/var/lib/rundeck/scripts/createvms.test -u ${option.user} -s "Small VM" -p devbox -r NULL -n ${option.hostname} -c preprod -d

If I output in the script I see -s is only being interpreted as only 'Small'.

If I change the command line to:
/var/lib/rundeck/scripts/createvms.test -u ${option.user} -s '"Small VM"' -p devbox -r NULL -n ${option.hostname} -c preprod -d (wrapping the whole thing in single quotes)

Things work as they used to in 1.6.

I've been poking around and the workflow quotes section matches in 1.6 and 2.5 (and 2.4 before that). Does anyone have an idea what might be going on?

I have ~500 commandline options I'm going to need to modify if I can't figure this out, which I'm not looking forward to. Thanks!

**Comment by kcd83** [comment]
Try

'/var/lib/rundeck/scripts/createvms.test -u ${option.user} -s "Small VM" -p
devbox -r NULL -n ${option.hostname} -c preprod -d'

I still get caught out by this too

**Comment by looprock** [comment]
Ok given this ticket was opened in Dec of 2013 I'm guessing there will be no resolution. I had to fix 351 entries, so if anyone else has this issue hopefully this will help:

https://gist.github.com/looprock/33df34b896357ecf0c45

**Comment by stevesobol** [comment]
I'm running into this problem with a Windows server. I am testing the operating environment to make sure Rundeck can speak to the Windows box because I just installed a copy of the BitVise SSH server -- it can, and it can run this command successfully, executing Blat.exe to send a simple email message...

c:\blat\full\blat.exe c:\temp.txt -to steve@lobosstudios.com -p SteveTest -subject "TestMessage"

but not this one with a space in the subject

c:\blat\full\blat.exe c:\temp.txt -to steve@lobosstudios.com -p SteveTest -subject "Test Message"

Looking at the job's output, I see this:

Blat v3.2.4 (build : Feb 24 2015 21:29:33)
32-bit Windows, Full, Unicode

Blat saw and processed these options, and was confused by the last one...
    -to steve@lobosstudios.com
    -subject Test
    Message
Do not understand argument: Message
Windows console utility to send mail via SMTP or post to usenet via NNTP
by P.Mendes,M.Neal,G.Vollant,T.Charron,T.Musson,H.Pesonen,A.Donchey,C.Hyde
  http://www.blat.net
syntax:
  Blat <filename> -to <recipient> [optional switches (see below)]

So obviously Blat isn't seeing the quotes around the message subject.

Is there any chance of this ever being fixed? Why has it been ignored for 18 months??

**Comment by nathfy** [comment]
trying todo a curl post with json command and ran into this - solution at the mo is to use " then ' then text, then ' and a final ". eg:

curl -H "'Content-Type: application/json'" -H "Accept-Encoding: gzip, deflate" -H "'Accept: */*'" -H "'Connection: keep-alive'" --data-binary "'{'jsonKey':false}'" --fail --compressed "'http://url.com'";

Thanks

**Comment by gschueler** [comment]
related: #836 #1291 #1406

**Comment by vvchik** [comment]
plus this issue from rundeck-winrm also about it https://github.com/rundeck-plugins/rundeck-winrm-plugin/issues/22

@gschueler looks like it problem come from automatic quoting.
may be will be good to add some flag for skipping auto quotation?

**Comment by vvchik** [comment]
Well I tried to do in on linux also 
same behavior 
for example I want to set following parameter for local script: 
```(New-Object System.Net.WebClient).DownloadFile('${option.url}', '${option.destination}')```
I receiveng:
```(New-Object 'System.Net.WebClient).DownloadFile('"'"'http://10.10.10.5:8081/folder/file.zip'"'"',' 'C:\destfolder\file.zip)'```

Why it doesn't work as described here http://rundeck.org/docs/manual/jobs.html#quoting-arguments-to-steps??? 
@gschueler may you please, help with that?

**Comment by esoc24** [comment]
@vvchik  Are you still having this issue? I'm receiving something similar and would like to know if you were able to resolve it.

**Comment by vvchik** [comment]
I mostly working with Windows now. And created my own plugin to work with Windows, it have a lot advances and also able to avoid quotation problem. https://github.com/NetDocuments/rd-winrm-plugin

**Comment by esoc24** [comment]
Awesome! I'll give it a go. Thanks for the quick response.

**Comment by ambikads** [comment]
Can someone help? I can't get the below to work
`host=`echo ${node.hostname}|awk -F":" '{print $1}'``

**Comment by iaingblack** [comment]
I wrote a script for "Resource Model Source" generation and a local script generated the YAML required to set the nodes. My script had parameters and some required spaces which were then split. To get it to work I had to set the command interpreter to be;

 /bin/sh -c

The script worked afterwards. Just in case anyone has a similar issue, it took a while to hunt down and solve as I tried many double quotes, combinations etc with no luck Once that was set it worked as it should on a command line (ie script.py param1 "param2 with spaces" param3)

**Comment by thenewwazoo** [comment]
I have been bitten by this bug today. I am trying to run a very simple command:
`dmesg -T | grep "Out of memory"`
and I cannot find an incantation that does not eat quotes or otherwise munge the command. Forget using regular expressions. Triple-quotes and quoted-quotes break the shell in ways that fail silently and undiagnoseably.

**Comment by xeor** [comment]
Same here... Using winrm the plugin (https://github.com/NetDocuments/rd-winrm-plugin)

**Comment by greatvovan** [comment]
It is sooo misleading... And it is still open.

**Comment by gaetanquentin** [comment]
2013 .. and this problem is still here (3.1.2) where is the doc about quoting?

**Comment by georgek** [comment]
The doc on quoting appears to have disappeared. So not only is this still a problem, I have no idea how to work around it.

**Comment by fdevans** [comment]
@georgek - This is the new documentation location.
https://docs.rundeck.com/docs/manual/node-steps/builtin.html#quoting-arguments-to-steps

rundeck.org moved to docs.rundeck.com a while ago, but the paths are generally the same and the search function found it pretty quickly.

**Comment by juresaht2** [comment]
The solutions posted here do not work for `cut -d' ' -f3` I either get a syntax error or I get cut complaining about more than 1 charaacter.

**Comment by unicolet** [comment]
I'm having a problem with quotes where rundeck _always_ quotes job options.  
For example I have a job which runs a command and I'd like to be able to supply the full arguments to the program using a single workflow option that the user can be customize on the fly. Let's say the program is `ls` and I'd like to run it with `-la /tmp` where `-la /tmp` is a single job option. Another user might instead want to run with `-lah /var/cache`, etc. The arguments would be passed to the rundeck job with `${option.arguments}`.

Currently rundeck will always wrap `${option.arguments}` in quotes so `ls` would be ultimately run as: `ls '-la /tmp'` which is not going to work, unfortunately.

I've read this issue a few times, and I'm still not quite sure if the problem I described is the same referenced in this issue. By comparing this issue age and the [commit that changed rundeck behavior](https://github.com/rundeck/rundeck/blame/fb246d8461d60e81574e7057d5a34c3c94356759/core/src/main/java/com/dtolabs/rundeck/core/utils/ScriptExecUtil.java#L348-L352) (at least for my use case) I think it might be. If it's not please direct to either open a new issue or an existing one.

If it is then I'd like to share a WIP I have that adds support for using `${unquotedoption.option_name}` to rundeck in place of `${option.option_name}`. The difference is that `${unquotedoption.option_name}` will not wrap the value in quotes as rundeck does by default. The changes are in: https://github.com/rundeck/rundeck/compare/main...unicolet:unquoteoption_support?expand=1

you can see and compare the behavior in these 2 unit tests: [`main...unicolet:unquoteoption_support?expand=1`#diff-d4a1ab2cd4](https://github.com/rundeck/rundeck/compare/main...unicolet:unquoteoption_support?expand=1#diff-d4a1ab2cd4ed74d413c7fa457add943c48c43c8eb66d60c1a2e0315af602e53cR90-R107)

`./gradlew test` passes without errors as of now

Let me know your thoughts, I'd be extremely happy to contribute back a little :-)

**Comment by gaddman** [comment]
Great work @unicolet, I've encountered exactly this problem and it's very frustrating, requiring some fragile workarounds to strip quotes while hoping none of them were intended. Your proposal would definitely work for my use cases - both simple commands like your example, and passing commands to a custom node executor.

**Comment by unicolet** [comment]
@gaddman well, then let me update my branch and open a PR before it gets too old. Thanks for the feedback, appreciate you took the time :-)
