### ISSUE TITLE
Webhook timeout since 3.2.6

### ISSUE THREAD

**Issue by mazzella-c** [rundeck/rundeck#6023]
**Describe the bug**

We send notifications to a webhook on success or failure for some job but since 3.2.6 we are seeing this message in our logs :

`ERROR NotificationService --- [duler_Worker-75] Notification failed [onsuccess,succeeded,177271]; URL http://someserver: Unable to POST notification after 1 tries: success for execution 177271 (succeeded): Error making request: Read timed out`

When we go on the Apache server on the other side the call is ok but it takes a very long time to proceed, around 15 seconds. I can't find anything that may explain this behaviour in the 3.2.6 changelog.

If we rollback to 3.2.5 then we don't get this warning anymore in logs.

**My Rundeck detail**

* Rundeck version: 3.2.6
* install type: war
* OS Name/version: Redhat 7.7
* DB Type/version: Postgre 11.6

**Expected behavior**
No warnings in logs because the call is ok

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 76

**Comment by MegaDrive68k** [comment]
Hi @mazzella-c 

If you test against a "test webhook" service like https://webhook.site (or another testing service in your organization) on both versions you obtain the same behavior?

I'm trying to reproduce the issue with the following job definition on 3.2.5 WAR and 3.2.6 WAR and works well  (if you like to test on webhooks.site, you need to change the webhook URL generated dynamically by the service).

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>91032b58-b6da-4943-9fd5-c78d4171f61a</id>
    <loglevel>INFO</loglevel>
    <name>TestWebhooksNotifications</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <notification>
      <onsuccess>
        <webhook urls='https://webhook.site/the-webhook-id' />
      </onsuccess>
    </notification>
    <notifyAvgDurationThreshold />
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "testing"</exec>
      </command>
    </sequence>
    <uuid>91032b58-b6da-4943-9fd5-c78d4171f61a</uuid>
  </job>
</joblist>
```

Kind regards.

**Comment by mazzella-c** [comment]
Hello @MegaDrive68k,

My server has no internet access so I can't test outside my organization.

We've been able to dig deeper this issue and it appears to be more complicated than I thought.

The warning only occurs when we have the following scenario :

- On job start we call a webhook that triggers job with API (/api/18/job/{job_uuid}/executions) => done in a few milliseconds

- Once the job is over Rundeck tells it's done with the webhook success notification.

- Always on the same job, another run with different parameters is triggered with API =>we get the readout warning because it lasts for 15 seconds for an unknown reason.

- The success webhook finally comes to our server, everything is ok.

If we launch a job that does not chain others executions of the same job there is no issue.
We are pretty sure it's linked to 3.2.6 because when we rollback to 3.2.5 the issue is gone.

I'm not even sure it's linked to webhooks in fact, maybe something linked to #5971 ?

**Comment by cantin-f** [comment]
Hi, I work with mazzela-c on this problem.

I will try to give more informations.
I'm in charge of a python application that use rundeck API and webhook.
Python versin is 3.7 and using the module Request for easier HTTP call.

The exact scenario is :

1. PythonApp ask API for execution of a job X (/api/18/job/{jobX_uuid}/executions), call is ms
2. Rundeck run the job, and send the success notification via webhook to PythonApp
3. PythonApp receive the success webhook and immediately ask for another execution (/api/18/job/{jobX_uuid}/executions), before answering the webhook with HTTP code 200

This is this second API call that is 15 seconds long. 15 seconds is the read timeout of the core python libhttp it seems. After 15s, lib http python go on without errors considering the server will never send more information. If I put a read timeout on the Requests lib, over the core htttp, it stop in error.
Rundeck has receive the execution API call because the executions is done and the second job success webhook is received (sometime before we finish the 15 seconds execution API call).

It seems there is a hole on what rundeck send in this case.

It happens EVERY time we play this scenario, only in 3.2.6. Never seen before, no change on PythonApp side.

**Comment by MegaDrive68k** [comment]
Hi @mazzella-c and @cantin-f

I used this python app (very rudimentary, just to test) and I see a normal behavior on 3.2.5 and 3.2.6, works in this way: if you run the app runs a bsic web server that launches the rundeck job "with webhook notification" if receive a GET request (for example accessing using a browser), the job notification webhook call the same app ad that launches a second job. The Python app and the Rundeck server are on different machines.

```python
from http.server import HTTPServer, BaseHTTPRequestHandler
from io import BytesIO
import requests

# host definition
rdeck_instance = "192.168.33.11"
rdeck_port = "4440"
rdeck_api = "35"
rdeck_token = "kUMQqzREbjnXVPbpb9LImaQozcEJYPQN"

# first job (with webhook)
rdeck_job1_id = "fc4e028e-1c21-4a03-915a-223fceb9ff57"

# the second job
rdeck_job2_id = "481b8add-0233-490e-ab6a-c105c81af445"

class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b'Any GET request is a call to first job')

        # execute the first job if receive a GET request
        s = requests.Session()
        r = s.post("http://" + rdeck_instance +  ":" + rdeck_port +"/api/" + rdeck_api + "/job/" + rdeck_job1_id + "/executions?authtoken=" + rdeck_token,headers = {'Accept': 'application/json'})

        # print data (for debug)
        print ('##### JOB ONE ########')
        print (r.status_code)
        print (r.url)
        print ('######################')
                    

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length)
        self.send_response(200)
        self.end_headers()
        response = BytesIO()
        response.write(b'This is POST request. ')
        response.write(b'Received: ')
        response.write(body)
        self.wfile.write(response.getvalue())

       # and call another job if receive POST request
        if response.write(body):
            # execute the second job
            s = requests.Session()
            r = s.post("http://" + rdeck_instance +  ":" + rdeck_port +"/api/" + rdeck_api + "/job/" + rdeck_job2_id + "/executions?authtoken=" + rdeck_token,headers = {'Accept': 'application/json'})

        # print data (for debug)
        print ('##### JOB TWO ########')
        print (r.status_code)
        print (r.url)
        print ('######################')
                    
httpd = HTTPServer(('192.168.33.14', 8000), SimpleHTTPRequestHandler)
httpd.serve_forever()
```

![Screenshot_3](https://user-images.githubusercontent.com/51376003/81872858-a1071000-9548-11ea-97ef-cc6a1be0db1c.png)

Maybe I'm forgetting some detail to reproduce?

Kind Regards!

**Comment by cantin-f** [comment]
Hi, Thank you for your effort with this issue.

I change slighlty your code in order to reproduce (bottom of this post).
The main change is using only one job with "multiple executions = YES" and adding datetime to see in the log when it takes 15 seconds.

The workflow is :
- run the pythonapp
- send a GET on pythonapp => you go into an infinite loop where the job execute himself again when the webhook arrive. This works well, "instant" api response
- send another GET to pythonapp => now all api execution call takes 15 seconds

Not exactly our real llife workflow but the issue looks the same. Only happen on 3.2.6, this works well in 3.2.5. Reproduce 90% percent of my tries..

The log when you call the second GET

```
10.221.70.83 - - [14/May/2020 11:04:42] "POST /success HTTP/1.1" 200 -
##### JOB TWO ########
2020-05-14 11:04:42.829042
200
2020-05-14 11:04:42.860245
######################
10.221.70.83 - - [14/May/2020 11:04:43] "POST /success HTTP/1.1" 200 -
##### JOB TWO ########
2020-05-14 11:04:43.360496
200
2020-05-14 11:04:43.391700
######################
10.221.70.83 - - [14/May/2020 11:04:43] "POST /success HTTP/1.1" 200 -
##### JOB TWO ########
2020-05-14 11:04:43.891951
200
2020-05-14 11:04:43.907553
######################
**10.221.38.198 - - [14/May/2020 11:04:43] "GET / HTTP/1.1" 200 -**
##### JOB ONE ########
2020-05-14 11:04:43.907553
200
2020-05-14 11:04:43.939756
######################
10.221.70.83 - - [14/May/2020 11:04:44] "POST /success HTTP/1.1" 200 -
##### JOB TWO ########
2020-05-14 11:04:44.472211
200
2020-05-14 11:04:59.521360
######################
10.221.70.83 - - [14/May/2020 11:04:59] "POST /success HTTP/1.1" 200 -
##### JOB TWO ########
2020-05-14 11:04:59.521360
200
2020-05-14 11:05:14.568114
######################
```

The code to use

```
from http.server import HTTPServer, BaseHTTPRequestHandler
from io import BytesIO
import requests
import datetime

# host definition
rdeck_instance = "192.168.33.11"
rdeck_port = "4440"
rdeck_api = "35"
rdeck_token = "kUMQqzREbjnXVPbpb9LImaQozcEJYPQN"

# unique job (with webhook)
rdeck_job1_id = "fc4e028e-1c21-4a03-915a-223fceb9ff57"


class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b'Any GET request is a call to first job')

        # execute the first job if receive a GET request
        s = requests.Session()
        r = s.post("http://" + rdeck_instance +  ":" + rdeck_port +"/api/" + rdeck_api + "/job/" + rdeck_job1_id + "/executions?authtoken=" + rdeck_token,headers = {'Accept': 'application/json'})

        # print data (for debug)
        print('##### JOB ONE ########')
        print(datetime.datetime.now())
        print(r.status_code)
        print(datetime.datetime.now())
        print('######################')
                    

    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length)
        self.send_response(200)
        self.end_headers()
        response = BytesIO()
        response.write(b'This is POST request. ')
        response.write(b'Received: ')
        response.write(body)
        self.wfile.write(response.getvalue())

       # and call another job if receive POST request
        if response.write(body):
            # execute the second job
            s = requests.Session()
            r = s.post("http://" + rdeck_instance +  ":" + rdeck_port +"/api/" + rdeck_api + "/job/" + rdeck_job1_id + "/executions?authtoken=" + rdeck_token,headers = {'Accept': 'application/json'})

        # print data (for debug)
        print('##### JOB TWO ########')
        print(datetime.datetime.now())
        print(r.status_code)
        print(datetime.datetime.now())
        print('######################')


httpd = HTTPServer(('192.168.33.14', 8000), SimpleHTTPRequestHandler)
httpd.serve_forever()
```

**Comment by mazzella-c** [comment]
To be complete we had issues reported in ticket #3989 when we moved form v2 to v3. The fix had been applied when 3.0.12 was released but we still had warnings in our logs when we launched job via the workflow as described above :

`2019-01-28 14:38:40.341 WARN --- [duler_Worker-63] rundeck.services.ExecutionService : Caught ConcurrencyFailureException, will retry updateScheduledExecStatistics for 21737
2019-01-28 14:38:40.342 WARN --- [duler_Worker-63] rundeck.quartzjobs.ExecutionJob : Execution 21737 update job stats (48): failed (attempts=1/5), retrying in 6366ms
2019-01-28 14:38:46.723 WARN --- [duler_Worker-63] rundeck.quartzjobs.ExecutionJob : Execution 21737 update job stats (48): completed after (attempts=2/5)`

We also applied the fix as stated [here](https://docs.rundeck.com/news/2019/01/14/rundeck-3.0.12.html) but those warnings have been persistent until the last release which cleared those messages for good.

This issue seems to be definitely linked with those previous ones, #5971 seems to be a good candidate to investigate.

**Comment by jtobard** [comment]
related? https://github.com/rundeck/rundeck/issues/5961

**Comment by MegaDrive68k** [comment]
Confirmed.

I saw the same behavior on 3.2.6+MySQL (works well on 3.2.5+MySQL).

**Steps to reproduce:**

1) On server A, put the following Python App and run with Python 3, the app listens to the port 8000 TCP awaiting some GET request (some access through a web browser for example).

```python
from http.server import HTTPServer, BaseHTTPRequestHandler
from io import BytesIO
import requests
import datetime

# host definition
rdeck_instance = "192.168.33.11"
rdeck_port = "4440"
rdeck_api = "35"
rdeck_token = "kUMQqzREbjnXVPbpb9LImaQozcEJYPQN"

# unique job (with webhook)
rdeck_job1_id = "fc4e028e-1c21-4a03-915a-223fceb9ff57"

class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b'Any GET request is a call to first job')

        # execute the first job if receive a GET request
        s = requests.Session()
        r = s.post("http://" + rdeck_instance +  ":" + rdeck_port +"/api/" + rdeck_api + "/job/" + rdeck_job1_id + "/executions?authtoken=" + rdeck_token,headers = {'Accept': 'application/json'})

        # print data (for debug)
        print('##### JOB ONE ########')
        print(datetime.datetime.now())
        print(r.status_code)
        print(datetime.datetime.now())
        print('######################')
                    
    def do_POST(self):
        content_length = int(self.headers['Content-Length'])
        body = self.rfile.read(content_length)
        self.send_response(200)
        self.end_headers()
        response = BytesIO()
        response.write(b'This is POST request. ')
        response.write(b'Received: ')
        response.write(body)
        self.wfile.write(response.getvalue())

       # and call another job if receive POST request
        if response.write(body):
            # execute the second job
            s = requests.Session()
            r = s.post("http://" + rdeck_instance +  ":" + rdeck_port +"/api/" + rdeck_api + "/job/" + rdeck_job1_id + "/executions?authtoken=" + rdeck_token,headers = {'Accept': 'application/json'})

        # print data (for debug)
        print('##### JOB TWO ########')
        print(datetime.datetime.now())
        print(r.status_code)
        print(datetime.datetime.now())
        print('######################')

httpd = HTTPServer(('192.168.33.14', 8000), SimpleHTTPRequestHandler)
httpd.serve_forever()
```

2) On server B, run Rundeck 3.2.6 configured agains MySQL as backend with the following job:

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>336afbf1-eceb-4cd6-9ee7-eccf87a48778</id>
    <loglevel>INFO</loglevel>
    <multipleExecutions>true</multipleExecutions>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <notification>
      <onsuccess>
        <webhook urls='http://192.168.33.14:8000' />
      </onsuccess>
    </notification>
    <notifyAvgDurationThreshold />
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "hi"</exec>
      </command>
    </sequence>
    <uuid>336afbf1-eceb-4cd6-9ee7-eccf87a48778</uuid>
  </job>
</joblist>
```

3) Access to server A python app from any browser (http://server-a-ip:8000), that's generates a loop between the job and webhook notification that post with this result:

```bash
##### JOB ONE ########
2020-05-14 14:59:13.234968
200
2020-05-14 14:59:13.234998
######################
192.168.33.11 - - [14/May/2020 14:59:14] "POST / HTTP/1.1" 200 -
##### JOB TWO ########
2020-05-14 14:59:15.074025
200
2020-05-14 14:59:15.074047
######################
192.168.33.11 - - [14/May/2020 14:59:15] "POST / HTTP/1.1" 200 -
##### JOB TWO ########
2020-05-14 14:59:16.004790
200
2020-05-14 14:59:16.004825
######################
192.168.33.11 - - [14/May/2020 14:59:16] "POST / HTTP/1.1" 200 -
##### JOB TWO ########
2020-05-14 14:59:16.887097
200
2020-05-14 14:59:16.887130
######################
```

4) If refreshing the browser pointing to Server A Python App, then you can see the following error with a delay of Notification (in my case six or seven seconds):

```bash
[2020-05-14 14:37:29.924] ERROR NotificationService --- [duler_Worker-10] Notification failed [onsuccess,succeeded,25]; URL http://192.168.33.14:8000: Unable to POST notification after 1 tries: success for execution 25 (succeeded): Error making request: Read timed out
```

If you test on 3.2.5 that's doesn't happen.

**Important:** if you try the same test on 3.2.6+H2, you can see the following (huge) error:

[error.txt](https://github.com/rundeck/rundeck/files/4629231/error.txt)

Thanks a lot, @mazzella-c, @cantin-f, and @jtobard!
