### ISSUE TITLE
Unable to save / create webhook

### ISSUE THREAD

**Issue by rcapliez** [rundeck/rundeck#6026]
**Describe the bug**
When I try to create a webhook, I can't save the definition and I can't see any error message.

**My Rundeck detail**

* Rundeck version: 3.2.6
* install type: docker
* OS Name/version: Ubuntu 16.04.6 LTS
* DB Type/version: postgresql

**To Reproduce**
When I try to create a webhook, I can't save the definition and I can't see any error message.

UI : click on "Create webhook" ... nothing occurs

With a client like Postman : return code 200 but the resquest only return "[]" and not "Webhook saved" as mentionned in the documentation.

Body :

{
    "config": {
        "jobId": "f18e1246-8d0c-40b9-abb4-c7538ac51152"
    },
    "enabled": true,
    "eventPlugin": "webhook-run-job",
    "name": "job_sanity_check",
    "project": "MYPROJ_ADMIN",
    "roles": "webhook,admin,user",
    "user": "admin"
}

Log file (extract) :

[2020-05-06 09:54:24.132] ERROR GrailsExceptionResolver --- [tp770190328-444] IllegalArgumentException occurred when processing request: [GET] /webhook/admin/save
  | Invalid action name: index. Stacktrace follows:
  |  
  | java.lang.IllegalArgumentException: Invalid action name: index
  | at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
  | at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
  | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
  | at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
  | at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
  | at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
  | at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
  | at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
  | at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
  | at javax.security.auth.Subject.doAs(Subject.java:422)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter.doFilterInternal(RundeckSecurityHeadersFilter.groovy:67)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
  | at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
  | at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
  | at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter.doFilterInternal(GrailsHttpPutFormContentFilter.groovy:54)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
  | at javax.security.auth.Subject.doAs(Subject.java:422)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
  | at org.rundeck.security.RundeckPreauthenticationRequestHeaderFilter.doFilter(RundeckPreauthenticationRequestHeaderFilter.groovy:44)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
  | at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
  | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
  | at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
  | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
  | at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  | at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
  | at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
  | at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
  | at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
  | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  | at org.eclipse.jetty.server.Server.handle(Server.java:494)
  | at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
  | at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
  | at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  | at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
  | at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
  | at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
  | at java.lang.Thread.run(Thread.java:748)
  |  
  | [2020-05-06 09:54:25.960] ERROR StackTrace --- [tp770190328-445] Full Stack Trace:
  |  
  | java.lang.IllegalArgumentException: Invalid action name: index
  | at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
  | at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
  | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
  | at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
  | at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
  | at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
  | at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
  | at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
  | at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
  | at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
  | at java.security.AccessController.doPrivileged(Native Method)
  | at javax.security.auth.Subject.doAs(Subject.java:422)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at javax.servlet.FilterChain$doFilter.call(Unknown Source)
  | at org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter.doFilterInternal(RundeckSecurityHeadersFilter.groovy:67)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
  | at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
  | at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
  | at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter.doFilterInternal(GrailsHttpPutFormContentFilter.groovy:54)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
  | at java.security.AccessController.doPrivileged(Native Method)
  | at javax.security.auth.Subject.doAs(Subject.java:422)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
  | at org.rundeck.security.RundeckPreauthenticationRequestHeaderFilter.super$3$doFilter(RundeckPreauthenticationRequestHeaderFilter.groovy)
  | at sun.reflect.GeneratedMethodAccessor549.invoke(Unknown Source)
  | at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  | at java.lang.reflect.Method.invoke(Method.java:498)
  | at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
  | at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
  | at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
  | at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
  | at org.rundeck.security.RundeckPreauthenticationRequestHeaderFilter.doFilter(RundeckPreauthenticationRequestHeaderFilter.groovy:44)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
  | at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
  | at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
  | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
  | at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
  | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
  | at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  | at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
  | at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
  | at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
  | at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
  | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  | at org.eclipse.jetty.server.Server.handle(Server.java:494)
  | at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
  | at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
  | at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  | at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
  | at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
  | at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
  | at java.lang.Thread.run(Thread.java:748)
  |  
  | [2020-05-06 09:54:25.960] ERROR StackTrace --- [tp770190328-445] Full Stack Trace:
  |  
  | java.lang.IllegalArgumentException: Invalid action name: index
  | at org.grails.core.DefaultGrailsControllerClass.invoke(DefaultGrailsControllerClass.java:187)
  | at org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter.handle(UrlMappingsInfoHandlerAdapter.groovy:90)
  | at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
  | at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
  | at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
  | at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)
  | at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
  | at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:852)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1604)
  | at org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter.doFilter(WebSocketUpgradeFilter.java:226)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
  | at javax.security.auth.Subject.doAs(Subject.java:422)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter.doFilterInternal(RundeckSecurityHeadersFilter.groovy:67)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:317)
  | at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:127)
  | at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:91)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:114)
  | at grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter.doFilter(UpdateRequestContextHolderExceptionTranslationFilter.groovy:64)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter.doFilterInternal(GrailsHttpPutFormContentFilter.groovy:54)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter.doFilter(GrailsAnonymousAuthenticationFilter.groovy:54)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter.doFilter(RememberMeAuthenticationFilter.java:158)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:170)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1.run(JaasApiIntegrationFilter.java:96)
  | at javax.security.auth.Subject.doAs(Subject.java:422)
  | at org.springframework.security.web.jaasapi.JaasApiIntegrationFilter.doFilter(JaasApiIntegrationFilter.java:105)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:200)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.authentication.preauth.AbstractPreAuthenticatedProcessingFilter.doFilter(AbstractPreAuthenticatedProcessingFilter.java:121)
  | at org.rundeck.security.RundeckPreauthenticationRequestHeaderFilter.doFilter(RundeckPreauthenticationRequestHeaderFilter.groovy:44)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter.doFilter(MutableLogoutFilter.groovy:64)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at grails.plugin.springsecurity.web.SecurityRequestHolderFilter.doFilter(SecurityRequestHolderFilter.groovy:58)
  | at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:331)
  | at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:214)
  | at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:177)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.grails.web.servlet.mvc.GrailsWebRequestFilter.doFilterInternal(GrailsWebRequestFilter.java:77)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.grails.web.filters.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:67)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1591)
  | at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:542)
  | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
  | at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:536)
  | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:235)
  | at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1581)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
  | at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1307)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
  | at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:482)
  | at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1549)
  | at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
  | at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1204)
  | at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
  | at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
  | at org.eclipse.jetty.server.Server.handle(Server.java:494)
  | at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:374)
  | at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:268)
  | at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
  | at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
  | at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
  | at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
  | at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:367)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:782)
  | at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:918)
  | at java.lang.Thread.run(Thread.java:748)
  |  
  | [2020-05-06 09:54:25.975] ERROR GrailsExceptionResolver --- [tp770190328-445] IllegalArgumentException occurred when processing request: [GET] /webhook/admin/save
  | Invalid action name: index. Stacktrace follows:

**Comment by sjrd218** [comment]
From the posted stacktrace it appears that you are trying to do a GET request to `/webhook/admin/save` which is not valid. 

What happens if you try to POST to `/webhook/admin/save`? 

In general it is preferred to use the API endpoints rather than the internal app endpoints to do API type functions. 

Docs for the webhook API can be found here. https://docs.rundeck.com/docs/api/rundeck-api.html#add-a-webhook

**Comment by rcapliez** [comment]
Hi 

Yes I have seen this "GET" occurence in the log file. But I don't understand where does it come from ...

The verb I use in Postman is "POST" on https://myserver/api/35/project/DBAPI_ADMIN/webhooks

with the following JSON :

{
    "config": {
        "jobId": "f18e1246-8d0c-40b9-abb4-c7538ac51152"
    },
    "enabled": true,
    "eventPlugin": "webhook-run-job",
    "name": "job_sanity_check",
    "project": "MYPROJ_ADMIN",
    "roles": "webhook,admin,user",
    "user": "admin"
}


and using the UI, I do not have to precise POST or GET, do you agree ?

That's why I don't undertand which event triggers this GET ...
