### ISSUE TITLE
SSH authentication for job fails when job runs scheduled

### ISSUE THREAD

**Issue by maxluchterhand1** [rundeck/rundeck#6028]
**Describe the bug**
When I manually run jobs, everything works as expected. When a scheduled job runs, the SSH authentication fails. 

Manual start:

> 18:56:26 | <host05> ESTABLISH SSH CONNECTION FOR USER: root
> -- | --
> 18:56:26 | <host05> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/tmp/ansible-runner8231708274701050065id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/rundeck/.ansible/cp/5a7674f7a7 host05 '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
> 18:56:26 | <host05> (0, b'/root\n', b'')

Scheduled start:

> 11:00:04 | <host05> ESTABLISH SSH CONNECTION FOR USER: root
> -- | --
> 11:00:04 | <host05> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o 'IdentityFile="/tmp/ansible-runner867851438201763667id_rsa"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="root"' -o ConnectTimeout=10 -o ControlPath=/home/rundeck/.ansible/cp/5a7674f7a7 host05 '/bin/sh -c '"'"'echo ~root && sleep 0'"'"''
> 11:00:05 | <host05> (255, b'', b'Permission denied (publickey,gssapi-keyex,gssapi-with-mic,password).\r\n')

**My Rundeck detail**

* Rundeck version: 3.2.6-20200427
* install type: dockerized
* OS Name/version: dockerized (Docker running on CentOS 8, Kernel: 4.18.0-147.8.1.el8_1.x86_64)
* DB Type/version: mysql

**To Reproduce**
1. Create a job whose workflow consist of one inline playbook.
2. For that workflow step, specify SSH authentication type privatekey, SSH user root, and provide the corresponding SSH key from within rundecks key storage.
3. Run that job, manual and scheduled.

**Expected behavior**
The job behaves in the same way, no matter if started manually or scheduled.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Brave
 - Version: 1.8.86

**Comment by maxluchterhand1** [comment]
The issue stopped occuring when converting the SSH private key into PEM (RSA) format, it originally was openssh format.

**Comment by MegaDrive68k** [comment]
For future references check [this](https://docs.rundeck.com/docs/administration/projects/node-execution/ssh.html#ssh-key-generation). Greetings.
