### ISSUE TITLE
Missing Check All button

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6029]
When clicking on the play button next to the job name/link the "Check All" button is not visible

![image](https://user-images.githubusercontent.com/20629911/81346492-37ca5d00-906f-11ea-9d5d-f09d038a2b74.png)

![image](https://user-images.githubusercontent.com/20629911/81346502-3c8f1100-906f-11ea-8c14-43e9f96f00e6.png)

Instead, if you click on the job link you see the Check All button.
![image](https://user-images.githubusercontent.com/20629911/81346574-5af50c80-906f-11ea-8ae1-51e9f381e896.png)

Rundeck Info:
APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.2.5-20200403
BUILDGIT : v3.2.5-0-g31c833d
SERVERUUID :
VERSION : 3.2.5-20200403

**Comment by MegaDrive68k** [comment]
Hi,

Are you using some browser extension or Rundeck plugin for that "check all" button?

Maybe this?

https://github.com/theque5t/rundeck-ui-mods

Regards.

**Comment by hs-hub-world** [comment]
You know what, @MegaDrive68k  I think you might be right. It's been a while and I totally forgot that feature was a plugin (not native in Rundeck).  I'll create an issue in the other repo.

Thank you!
