### ISSUE TITLE
Rackspace plugin

### ISSUE THREAD

**Issue by marianogg9** [rundeck/rundeck#605]
Hi guys.
I have a rackspace environment that I want to manage via rundeck. I already got a complete list of my servers in .json format and now I need to create a job in rundeck. The thing is I don't know how to. Is there a plugin or some tool to import my .json config file to rundeck?
Thanks!!

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
