### ISSUE TITLE
Rundeck does not by default store project config in the database

### ISSUE THREAD

**Issue by jimr6007** [rundeck/rundeck#6053]
**Describe the bug**
Rundeck does not by default store project config in the database
contrary to what it says here: https://docs.rundeck.com/docs/administration/projects/configuration.html

Doc's regarding project storage are confusing.

And this is really important because one of the big reasons to use the db is to increase security a bit, not have passwords and keys sitting on the file system. But, if you can't wrap your mind around how this is supposed to work...

**My Rundeck detail**
rundeck-3.2.6-20200427.war 
war
CentOS 7.8
Postgres

**To Reproduce**
Install as described here: https://docs.rundeck.com/docs/administration/install/jar.html
Setup Postgres and adjust Rundeck config accordingly
Create a new project and note that the config for the project is stored at ~/projects 

**Expected behavior**
project configs stored in the db

I discovered this issue in the process of trying to config key storage and project config storage to all/both be in the db but the docs are very confusing. Add in trying to config the jasypt encryption and the docs and trying to follow along will bring you to tears :)

For example we have:
https://docs.rundeck.com/docs/administration/projects/configuration.html which says you should:
rundeck.projectsStorageType=db

but also we have the info here: https://docs.rundeck.com/docs/administration/configuration/plugins/configuring.html#storage-plugins

which indicates I should use something like:
[prefix].1.type=db
[prefix].1.path=/

And then if say, ok, let's try encryption, ha, ha ....

**Comment by fdevans** [comment]
@jimr6007 thank you for the feedback.  We are actively working on this and streamlining other setup/configuration tasks.  Hoping to have something later this year.
