### ISSUE TITLE
Rundeck 409 Conflict for Project Jobs

### ISSUE THREAD

**Issue by snegri** [rundeck/rundeck#6056]
I have recently run into an issue when using the rundeck-ansible-plugin where whenever I click on the jobs in my Rundeck project the page hangs and will never load. In an attempt to find out what was going on inside the Rundeck server, I made an api request to get job info from my project.

I did this using this command:
```
curl -vvvv --location --request POST 'http://<our rundeck server ip>/api/27/job/1671075a-5dc3-4438-bfdc-d6124d3af42e' \
                --header 'Accept: application/json' \
                --header 'X-Rundeck-Auth-Token: <my auth token>' \
                --header 'Content-Type: application/json' \
                | python3 -m json.tool
```
In response, I get a 409 conflict. 

In addition to this error, trying edit the node configuration and remove and re-add the Ansible Resource Model Source node plugin results in the page hanging after clicking "save".

Things I have tried to fix it:
- Archiving the project, and re-adding it under a different name without importing configurations/executions/etc. After a bit of time, this results in job pages hanging and empty node resources

- Deleting the project entirely and uploading the jobs using their job yaml files. When doing this I added the project under a new name, re created the configuration, and then uploaded the job yamls. This still results in hanging job pages and empty node resources.

I have another ansible project on our Rundeck and it is using the same job yamls and Ansible Resource Model Source and it has no errors. 

Solving this would be much appreciated because I keep having to delete my project and rename it only to be able to work on it for a little while before it have to delete it and add it again. My guess is there seems to be a duplicate of the project files on our Rundeck server, hence the 409 conflict, but I can't seem to resolve it. Thanks in advance for your help!

**Comment by MegaDrive68k** [comment]
Hi @snegri 

Can you provide your Rundeck version to test it?

Thank you.

**Comment by snegri** [comment]
Thanks for your response!

Our Rundeck version is 3.0.8.

**Comment by MegaDrive68k** [comment]
Hi @snegri 

I'm trying to reproduce your issue, can you post the service.log output at the moment of "GUI freeze"/409 response? (edit any potentially sensitive information).

Thanks!
