### ISSUE TITLE
Ansible plugin install should be optional

### ISSUE THREAD

**Issue by jimr6007** [rundeck/rundeck#6061]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**
Trying to test rundeck-ansible plugin with my own mods to the plugin but each time I restart Rundeck it pulls in version 3.10 of the plugin.

Tried all the settings in rundeck-config.properties but those seem to be ignored

rundeck.feature.repository.localSearchOnly=true
rundeck.feature.repository.enabled=false

**Describe the solution you'd like**

either remove the ansible plugin from build.yaml making install of that plugin optional or explain to me how I can override the version of the ansible plugin and have that "stick" on a restart

**Describe alternatives you've considered**

**Additional context**

**Comment by fdevans** [comment]
@jimr6007 How are you launching Rundeck?  WAR/RPM/Docker?

**Comment by jimr6007** [comment]
war file via systemd script
what I discovered though was that if you drop a more recent version of a plugin in libext the Rundeck java process magically picks up the newer version

I have both of these in my libext right now:
rundeck-ansible-plugin-3.1.1.jar
rundeck-ansible-plugin-3.1.0.jar 

via the Rundeck UI, https://..../artifact/index/configurations, it's says version 3.1.1

I think some log files support that theory as well

Not sure how Rundeck decides which one to use though. 
Is it just based on the version number in the filename?
Or I'd guess more likely Rundeck looks at some metadata in the plugin jar file?
