### ISSUE TITLE
Option value plugin - the values are not sorted

### ISSUE THREAD

**Issue by mikesuding** [rundeck/rundeck#6068]
When you use an option value plugin, the values don't show sorted in pulldown item

**My Rundeck detail**

* Rundeck version: 3.2.1
* install type: deb and war both
* OS Name/version: ubuntu 18 LTS and Windows 2016
* DB Type/version: MS-SQL

**To Reproduce**
1. On option settings click Sort Values:  YES
2. Open the job and pulldown the menu to see they are not sorted

**Expected behavior**
The values in the pulldown should be sorted

**Screenshots**
![image](https://user-images.githubusercontent.com/23124354/82159087-af06aa80-9840-11ea-8694-66132a46e632.png)

**Desktop:**
 - OS: Mac
 - Browser: chrome 81

**Comment by mikesuding** [comment]
I just tested the Remote URL too. That does not show sorted either.
![image](https://user-images.githubusercontent.com/23124354/82382528-fcba1900-99e0-11ea-9b02-1e52c9e3fe18.png)

**Comment by gschueler** [comment]
It looks like the "Sort Values" currently only applies for any manually entered values in the list, not to plugin values or remote url values.  The boolean value of "Sort Values" is also not exported with the option definition.  So basically that Sort Values really means "sort the values i entered when this is saved" :(

**Comment by gschueler** [comment]
If your remote Json is just a basic json object like {"key1":"value1","key2":"value2"} then the keys will be rendered sorted in the UI. Rundeck sorts the keys of json object response automatically.  If the json result is a List of any type, the ordering will not be sorted.
