### ISSUE TITLE
Rundeck Crashes after fresh install and first project creation

### ISSUE THREAD

**Issue by patrickave** [rundeck/rundeck#6077]
**Describe the bug**
I ran fresh install of the latest package.  All was well and logge din for the first time.  I created my first project and then the service crashed completed.

https://gist.github.com/patrickave/8869ccf54f03c4d8cd6465232faaefdb

I then restart the service and log in after it comes back up.
It takes pretty long to log in.  I noticed his happens if i run this as a WAR, local db or even local mysql.
Since it crashed during the project creation, I can't get into the listed projects.
The new project is there but when I click into it errors out as well.

I tested the WAR and also the docker container.  I noticed the same thing happening across the board.

I also noticed that I had to chancel the login and it reverts back to localhost instead of the defined URL path i gave.  I can leave it to local host and try running a reverse proxy but thats not ideal.

I can provide more info if needed.

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)

Thanks
Pat

**My Rundeck detail**

* Rundeck version: Rundeck 3.2.7-20200515 (2020-05-15)
* install type: deb
* OS Name/version: debian 10 buster
* DB Type/version: mysql

**Comment by MegaDrive68k** [comment]
Hi @patrickave 

Which JDK version are you using?

You can see that doing `java -version`

Thanks.

**Comment by patrickave** [comment]
@MegaDrive68k 
So sorry - forgot to include it.  I updated main post as well.

openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Debian-3deb10u1)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Debian-3deb10u1, mixed mode, sharing)

**Comment by MegaDrive68k** [comment]
Hi @patrickave 

Move to Java 8 (OpenJDK or Oracle implementation), this is a specific Rundeck requirement.

https://docs.rundeck.com/docs/administration/install/system-requirements.html#java

Greetings!

**Comment by patrickave** [comment]
@MegaDrive68k - i figured it would be compatible with the JREv11 but this also proves how much i dislike java. 👍 
Thank you!  It works now.
