### ISSUE TITLE
Docker Pull not working

### ISSUE THREAD

**Issue by RolandSM** [rundeck/rundeck#6081]
[(https://hub.docker.com/r/rundeck/rundeck/)]

The Docker Pull Command:
`docker pull rundeck:rundeck`
ist not working because :latest is missins?

**Comment by MegaDrive68k** [comment]
Hi @RolandSM 

You can pull any specific version with:

`docker pull rundeck/rundeck:3.2.7`

Or the latest build with:

`docker pull rundeck/rundeck:SNAPSHOT`

Regards!

**Comment by RolandSM** [comment]
Yes I know and until today I handle it so.
I update Container via Portainer and there is a nice mechanism which goes to the :latest Tag.
Most of my containers are build with rundeck/rundeck which means :latest or rundeck/rundeck:latest so this works.
But if the container was build with a specific version like rundeck/rundeck:3.2.7 this is not working...

**Comment by fdevans** [comment]
Please let us know and reopen if you are still experiencing this. We can't seem to replicate.
