### ISSUE TITLE
MySQL master-master replication is broken by the projects Execution History Clean

### ISSUE THREAD

**Issue by chisanovici** [rundeck/rundeck#6082]
**Describe the bug**
We have set all our Rundeck projects with "Execution History Clean" enabled to with the following settings:
- Days to keep executions: 5
- Minimum executions to keep: 50
- Maximum size of the deletion: 500
- Schedule clean history job: every day at: 12:00 PM (0 0 0 1/1 * ? *)

**My Rundeck detail**

* Rundeck version: rundeck-3.2.6.20200427-1.noarch
* install type: rpm
* OS Name/version: CentOS 7.7
* DB Type/version: MariaDB mariadb-5.5.64-1.el7.x86_64, INNODB storage
* MariaDB - mysql master - master replication between two rundeck nodes (cluster implementation)
* Project storage: DB
* Execution log storage: files on NFS shared partition between two rundeck nodes (cluster implementation)
* AVI Vantage VIP in front of the two Rundeck servers sending all the requests back to the fastest response node on 4440.

**To Reproduce**
1. Every day at 12:05 PM (a pattern I saw for a week already), because of the Execution History Clean enabled for projects - I presume, we end up in broken master - master mysql replication with errors like below for tables executions, workflow, workflow_workflow_step:
```
Last_Error: Could not execute Delete_rows event on table rundeck.workflow_workflow_step; Can't find record in 'workflow_workflow_step', Error_code: 1032; handler error HA_ERR_KEY_NOT_FOUND; the event's master log mysql-bin.000007, end_log_pos 35310638
```

PS: In case you need additional info please let me know.

Thank you,
Ionut

**Comment by chisanovici** [comment]
Hust upgraded Rundeck two days ago and this issue is present in rundeck-3.2.7 as well

**Comment by stephen-hames** [comment]
This is affecting us as well.   Note: we aren't using master-master replication, but "traditional" mysql master -> slave replication, using row based binlog format.

Rundeck version: 3.3.3, rpm installation
OS Centos 7.9
Mysql 5.7.31, InnoDB
Project Storage: DB
Execution Log Storage, local FS
