### ISSUE TITLE
${DATE:format} : usage of colon impossible 

### ISSUE THREAD

**Issue by Leon59250** [rundeck/rundeck#6084]
**Describe the bug**
Probleme with date format. Impossible to use colon in date pattern

**My Rundeck detail**

* Rundeck version: 3.2.3
* install type: war
* OS Name/version:  ubuntu 16.04
* DB Type/version:  mssql

**To Reproduce**

1. Create a job
2. Go to workflow tab
3. Add an option
	option type : text
	Option Name : DATE_SUPPORTED
	default value : ${DATE:yyyy-MM-dd'T'HH:mm:ss'Z'}
4. Add a step type script

	put this into the step :

	echo "test unitaires"
	echo "@option.DATE_SUPPORTED@"

5. Save all

**Expected behavior**
I want to see the date formatted as is : "yyyy-MM-dd'T'HH:mm:ss'Z'"

**Error**
when I execute this job I have this error message :

An Error Occurred
No signature of method: ch.qos.logback.classic.Logger.warn() is applicable for argument types: (java.lang.NumberFormatException) values: [java.lang.NumberFormatException: For input string: ":yyyy-MM-dd'T'HH:mm"] Possible solutions: warn(java.lang.String), warn(java.lang.String, [Ljava.lang.Object;), warn(java.lang.String, java.lang.Object), warn(java.lang.String, java.lang.Throwable), warn(org.slf4j.Marker, java.lang.String), wait()

and this is detailed error message

Error 500: Internal Server Error
URI
/rundeck/project/test/job/index
Class
groovy.lang.MissingMethodException
Message
No signature of method: ch.qos.logback.classic.Logger.warn() is applicable for argument types: (java.lang.NumberFormatException) values: [java.lang.NumberFormatException: For input string: ":yyyy-MM-dd'T'HH:mm"] Possible solutions: warn(java.lang.String), warn(java.lang.String, [Ljava.lang.Object;), warn(java.lang.String, java.lang.Object), warn(java.lang.String, java.lang.Throwable), warn(org.slf4j.Marker, java.lang.String), wait()
Trace
    Line | Method
->> 1974 | $tt__expandDateStrings   in rundeck.services.ExecutionService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     94 | doInTransaction          in grails.gorm.transactions.GrailsTransactionTemplate$2
|    133 | execute . . . . . . . .  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                  in grails.gorm.transactions.GrailsTransactionTemplate
|   2370 | $tt__int_createExecution in rundeck.services.ExecutionService
|     94 | doInTransaction          in grails.gorm.transactions.GrailsTransactionTemplate$2
|    133 | execute . . . . . . . .  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                  in grails.gorm.transactions.GrailsTransactionTemplate
|   2459 | $tt__createExecution . . in rundeck.services.ExecutionService
|     94 | doInTransaction          in grails.gorm.transactions.GrailsTransactionTemplate$2
|    133 | execute . . . . . . . .  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                  in grails.gorm.transactions.GrailsTransactionTemplate
|   2081 | $tt__retryExecuteJob . . in rundeck.services.ExecutionService
|     94 | doInTransaction          in grails.gorm.transactions.GrailsTransactionTemplate$2
|    133 | execute . . . . . . . .  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                  in grails.gorm.transactions.GrailsTransactionTemplate
|   2030 | $tt__executeJob . . . .  in rundeck.services.ExecutionService
|     94 | doInTransaction          in grails.gorm.transactions.GrailsTransactionTemplate$2
|    133 | execute . . . . . . . .  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                  in grails.gorm.transactions.GrailsTransactionTemplate
|   3032 | scheduleJob . . . . . .  in rundeck.controllers.ScheduledExecutionController
|   2905 | doCall                   in rundeck.controllers.ScheduledExecutionController$_runOrScheduleJob_closure98
|    272 | withForm . . . . . . . . in grails.artefact.Controller$Trait$Helper
|    250 | withForm                 in     ''
|   2904 | runOrScheduleJob . . . . in rundeck.controllers.ScheduledExecutionController
|   2894 | runJobNow                in     ''
|    223 | invoke . . . . . . . . . in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke                   in org.grails.core.DefaultGrailsControllerClass
|     90 | handle . . . . . . . . . in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch               in org.springframework.web.servlet.DispatcherServlet
|    901 | doService . . . . . . .  in     ''
|    970 | processRequest           in org.springframework.web.servlet.FrameworkServlet
|    872 | doPost . . . . . . . . . in     ''
|    846 | service                  in     ''
|    852 | handle . . . . . . . . . in org.eclipse.jetty.servlet.ServletHolder
|   1604 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    226 | doFilter . . . . . . . . in org.eclipse.jetty.websocket.server.WebSocketUpgradeFilter
|   1591 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | run . . . . . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs                     in javax.security.auth.Subject
|    105 | doFilter . . . . . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1591 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal . . . . in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|   1591 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    317 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke                   in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter . . . . . . . . in     ''
|    331 | doFilter                 in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter . . . . . . . . in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter                 in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilterInternal         in grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter
|    331 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter                 in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter                 in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter                 in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run                      in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs . . . . . . . . . . in javax.security.auth.Subject
|    105 | doFilter                 in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter                 in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter                 in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter                 in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter                 in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal         in org.springframework.security.web.FilterChainProxy
|    177 | doFilter . . . . . . . . in     ''
|   1591 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal . . . . in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|   1591 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal . . . . in org.grails.web.filters.HiddenHttpMethodFilter
|   1591 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    542 | doHandle . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler
|    143 | handle                   in org.eclipse.jetty.server.handler.ScopedHandler
|    536 | handle . . . . . . . . . in org.eclipse.jetty.security.SecurityHandler
|    127 | handle                   in org.eclipse.jetty.server.handler.HandlerWrapper
|    235 | nextHandle . . . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1581 | doHandle                 in org.eclipse.jetty.server.session.SessionHandler
|    233 | nextHandle . . . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1307 | doHandle                 in org.eclipse.jetty.server.handler.ContextHandler
|    188 | nextScope . . . . . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|    482 | doScope                  in org.eclipse.jetty.servlet.ServletHandler
|   1549 | doScope . . . . . . . .  in org.eclipse.jetty.server.session.SessionHandler
|    186 | nextScope                in org.eclipse.jetty.server.handler.ScopedHandler
|   1204 | doScope . . . . . . . .  in org.eclipse.jetty.server.handler.ContextHandler
|    141 | handle                   in org.eclipse.jetty.server.handler.ScopedHandler
|    127 | handle . . . . . . . . . in org.eclipse.jetty.server.handler.HandlerWrapper
|    494 | handle                   in org.eclipse.jetty.server.Server
|    374 | handle . . . . . . . . . in org.eclipse.jetty.server.HttpChannel
|    268 | onFillable               in org.eclipse.jetty.server.HttpConnection
|    311 | succeeded . . . . . . .  in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    103 | fillable                 in org.eclipse.jetty.io.FillInterest
|    426 | onFillable . . . . . . . in org.eclipse.jetty.io.ssl.SslConnection$DecryptedEndPoint
|    320 | onFillable               in org.eclipse.jetty.io.ssl.SslConnection
|    158 | succeeded . . . . . . .  in org.eclipse.jetty.io.ssl.SslConnection$2
|    103 | fillable                 in org.eclipse.jetty.io.FillInterest
|    117 | run . . . . . . . . . .  in org.eclipse.jetty.io.ChannelEndPoint$2
|    336 | runTask                  in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    313 | doProduce . . . . . . .  in     ''
|    171 | tryProduce               in     ''
|    129 | run . . . . . . . . . .  in     ''
|    367 | run                      in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    782 | runJob . . . . . . . . . in org.eclipse.jetty.util.thread.QueuedThreadPool
|    918 | run                      in org.eclipse.jetty.util.thread.QueuedThreadPool$Runner
^    748 | run . . . . . . . . . .  in java.lang.Thread

**Comment by Leon59250** [comment]
You can this see too : https://github.com/rundeck/rundeck/issues/4242

**Comment by julien-jean** [comment]
We get the same issue using rundeck 3.3.9-20210201.

`${DATE:dd-MM-YYYY HH:mm:ss}` as input will cause the following 500 error:

```
No signature of method: org.apache.logging.slf4j.Log4jLogger.warn() is applicable for argument types: (NumberFormatException) values: [java.lang.NumberFormatException: For input string: ":dd-MM-YYYY HH:mm"] Possible solutions: warn(java.lang.String), warn(java.lang.String, [Ljava.lang.Object;), warn(java.lang.String, java.lang.Object), warn(java.lang.String, java.lang.Throwable), warn(org.slf4j.Marker, java.lang.String), wait()
```

<details>
<summary>Stack trace content</summary>
<br>

```
    Line | Method
->> 2049 | $tt__expandDateStrings   in rundeck.services.ExecutionService
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     43 | invoke                   in jdk.internal.reflect.DelegatingMethodAccessorImpl
|     94 | doInTransaction . . . .  in grails.gorm.transactions.GrailsTransactionTemplate$2
|    140 | execute                  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute . . . . . . . .  in grails.gorm.transactions.GrailsTransactionTemplate
|   2447 | $tt__int_createExecution in rundeck.services.ExecutionService
|     43 | invoke . . . . . . . . . in jdk.internal.reflect.DelegatingMethodAccessorImpl
|     94 | doInTransaction          in grails.gorm.transactions.GrailsTransactionTemplate$2
|    140 | execute . . . . . . . .  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                  in grails.gorm.transactions.GrailsTransactionTemplate
|   2537 | $pub__createExecution .  in rundeck.services.ExecutionService
|     43 | invoke                   in jdk.internal.reflect.DelegatingMethodAccessorImpl
|     94 | doInTransaction . . . .  in grails.gorm.transactions.GrailsTransactionTemplate$2
|    140 | execute                  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute . . . . . . . .  in grails.gorm.transactions.GrailsTransactionTemplate
|   2156 | $tt__retryExecuteJob     in rundeck.services.ExecutionService
|     43 | invoke . . . . . . . . . in jdk.internal.reflect.DelegatingMethodAccessorImpl
|     94 | doInTransaction          in grails.gorm.transactions.GrailsTransactionTemplate$2
|    140 | execute . . . . . . . .  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                  in grails.gorm.transactions.GrailsTransactionTemplate
|     43 | invoke . . . . . . . . . in jdk.internal.reflect.DelegatingMethodAccessorImpl
|   2105 | $tt__executeJob          in rundeck.services.ExecutionService
|     43 | invoke . . . . . . . . . in jdk.internal.reflect.DelegatingMethodAccessorImpl
|     94 | doInTransaction          in grails.gorm.transactions.GrailsTransactionTemplate$2
|    140 | execute . . . . . . . .  in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                  in grails.gorm.transactions.GrailsTransactionTemplate
|   2886 | scheduleJob . . . . . .  in rundeck.controllers.ScheduledExecutionController
|     43 | invoke                   in jdk.internal.reflect.DelegatingMethodAccessorImpl
|   2759 | doCall . . . . . . . . . in rundeck.controllers.ScheduledExecutionController$_runOrScheduleJob_closure91
|     43 | invoke                   in jdk.internal.reflect.DelegatingMethodAccessorImpl
|    272 | withForm . . . . . . . . in grails.artefact.Controller$Trait$Helper
|    250 | withForm                 in     ''
|   2758 | runOrScheduleJob . . . . in rundeck.controllers.ScheduledExecutionController
|   2748 | runJobNow                in     ''
|    223 | invoke . . . . . . . . . in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke                   in org.grails.core.DefaultGrailsControllerClass
|     90 | handle . . . . . . . . . in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|   1040 | doDispatch               in org.springframework.web.servlet.DispatcherServlet
|    943 | doService . . . . . . .  in     ''
|   1006 | processRequest           in org.springframework.web.servlet.FrameworkServlet
|    909 | doPost . . . . . . . . . in     ''
|    883 | service                  in     ''
|    755 | handle . . . . . . . . . in org.eclipse.jetty.servlet.ServletHolder
|   1617 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     96 | run . . . . . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    423 | doAs                     in javax.security.auth.Subject
|    105 | doFilter . . . . . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|   1604 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal . . . . in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|   1604 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    320 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke                   in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter . . . . . . . . in     ''
|    334 | doFilter                 in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    119 | doFilter . . . . . . . . in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter                 in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    334 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter                 in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    334 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter                 in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    334 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter                 in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    334 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run                      in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    423 | doAs . . . . . . . . . . in javax.security.auth.Subject
|    105 | doFilter                 in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    334 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter                 in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    334 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter                 in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    334 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter                 in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    334 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter                 in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    334 | doFilter . . . . . . . . in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    215 | doFilterInternal         in org.springframework.security.web.FilterChainProxy
|    178 | doFilter . . . . . . . . in     ''
|   1604 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     77 | doFilterInternal . . . . in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|   1604 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|     67 | doFilterInternal . . . . in org.grails.web.filters.HiddenHttpMethodFilter
|   1604 | doFilter                 in org.eclipse.jetty.servlet.ServletHandler$CachedChain
|    545 | doHandle . . . . . . . . in org.eclipse.jetty.servlet.ServletHandler
|    143 | handle                   in org.eclipse.jetty.server.handler.ScopedHandler
|    590 | handle . . . . . . . . . in org.eclipse.jetty.security.SecurityHandler
|    127 | handle                   in org.eclipse.jetty.server.handler.HandlerWrapper
|    235 | nextHandle . . . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1607 | doHandle                 in org.eclipse.jetty.server.session.SessionHandler
|    233 | nextHandle . . . . . . . in org.eclipse.jetty.server.handler.ScopedHandler
|   1297 | doHandle                 in org.eclipse.jetty.server.handler.ContextHandler
|    188 | nextScope . . . . . . .  in org.eclipse.jetty.server.handler.ScopedHandler
|    485 | doScope                  in org.eclipse.jetty.servlet.ServletHandler
|   1577 | doScope . . . . . . . .  in org.eclipse.jetty.server.session.SessionHandler
|    186 | nextScope                in org.eclipse.jetty.server.handler.ScopedHandler
|   1212 | doScope . . . . . . . .  in org.eclipse.jetty.server.handler.ContextHandler
|    141 | handle                   in org.eclipse.jetty.server.handler.ScopedHandler
|    127 | handle . . . . . . . . . in org.eclipse.jetty.server.handler.HandlerWrapper
|    500 | handle                   in org.eclipse.jetty.server.Server
|    383 | lambda$handle$1 . . . .  in org.eclipse.jetty.server.HttpChannel
|    547 | dispatch                 in     ''
|    375 | handle . . . . . . . . . in     ''
|    270 | onFillable               in org.eclipse.jetty.server.HttpConnection
|    311 | succeeded . . . . . . .  in org.eclipse.jetty.io.AbstractConnection$ReadCallback
|    103 | fillable                 in org.eclipse.jetty.io.FillInterest
|    117 | run . . . . . . . . . .  in org.eclipse.jetty.io.ChannelEndPoint$2
|    336 | runTask                  in org.eclipse.jetty.util.thread.strategy.EatWhatYouKill
|    313 | doProduce . . . . . . .  in     ''
|    171 | tryProduce               in     ''
|    129 | run . . . . . . . . . .  in     ''
|    388 | run                      in org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread
|    806 | runJob . . . . . . . . . in org.eclipse.jetty.util.thread.QueuedThreadPool
|    938 | run                      in org.eclipse.jetty.util.thread.QueuedThreadPool$Runner
^    834 | run . . . . . . . . . .  in java.lang.Thread
```

</details>
