### ISSUE TITLE
Error renaming Jobs, file duplication occurs on local folder

### ISSUE THREAD

**Issue by FedeHAL** [rundeck/rundeck#6088]
**Describe the bug**
When renaming a job (using SCM plugin) the new job gets updated on the GUI but in the git local folder a new file is created but the old remains in place and then both files gets commited to the repository.

**My Rundeck detail**

* Rundeck version: 3.2.6-20200427
* install type: war
* OS Name/version: RedHat 7.7
* DB Type/version: postgres

**To Reproduce**
1. Edit a job, and change destination folder for example from "folderA/folderB" to "folderA/folderC" and save.
2. The job is moved or created on the new folder on rundeck and it doesn't show in the original folder.
3. Go to your server and check the local folder on RUNDECK_HOME/projects/PROJECT_NAME/scm/ and verify that 2 files exists on both folders.
4. When commiting and pushing the changes both files go to the remote repository.

**Expected behavior**
When renaming a job the original file should be deleted.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: macos
 - Browser safari
 - Version 13.1

**Additional context**
This seems to happen for a while now, we have been using RUNDECK for almost a year now, and this behaviour is consistent in all versions that we installed, and using Github or Gitlab as SCM destination.

**Comment by MegaDrive68k** [comment]
Hi @FedeHAL 

I reproduced the issue partially (after renaming the job groups, SCM directories keeps the previous directory plus the new one) but at the moment of push changes to remote repo, I can select only the actual one (not the previous folder). Also, on remote repo, I see only the job with the new group after the push changes. Maybe I'm missing something?

**Comment by FedeHAL** [comment]
I've tested it again, and I end up with the 2 jobs on the repo when commited/pushed
