### ISSUE TITLE
Activity Date Filter not working

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6089]
Activity Date filter (Start After + Start Before) not working as expected -?
Please see image below:

![image](https://user-images.githubusercontent.com/20629911/83278444-7774f800-a188-11ea-9710-6e679d727c27.png)

RUNDECK
APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.2.7-20200515
BUILDGIT : v3.2.7-0-g45103d6
SERVERUUID :
VERSION : 3.2.7-20200515

Thank you
HS

**Comment by MegaDrive68k** [comment]
Confirmed, I see the same behavior, using a date in the future (after 2020/06/15), Rundeck shows all jobs

![Screenshot_1](https://user-images.githubusercontent.com/51376003/83311030-f9424100-a1db-11ea-8479-b3886a019c1a.png)

Thanks for your feedback @hs-hub-world
