### ISSUE TITLE
Parameter has wrong value during job execution

### ISSUE THREAD

**Issue by SaltySolomon** [rundeck/rundeck#6095]
**Describe the bug**
I have a parameter that is called "additional parameters" for well, additional paramters, usually that field is empty unless its a specific case, lately without me changing anything it added that additional parameters to jobs that don't have said parameter which ends up with the job failing.

I am executing a python script and I am passing the job parameters as environment variables.

**My Rundeck detail**

* Rundeck version: 3.2.2
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: Postgres

**To Reproduce**
Not quite sure how to reproduce it due to not knowing the source of the issue

**Expected behavior**
If the parameter is empty or does not exist that paramter shouldn't be filled for job execution

**Additional context**
Planning to upgrade to latest version on Thursday when there is a maintance window.

**Comment by lightarrow** [comment]
Have you tried using job options? 
if "RD_JOB_PROJECT" in os.environ:
    rundeck_job_project = os.getenv("RD_JOB_PROJECT")
I have yet to run into any issues when working this way in python.

**Comment by SaltySolomon** [comment]
I now "fixed" the issue for me, by always passing that parameter when executing the base job with the more specific job. That way I get the correct value unlike if I got a set parameter in the base job and havin the paramter empty in the specific job.
