### ISSUE TITLE
Error 500 after changing project.disable.executions or project.disable.schedule parameters in project.properties

### ISSUE THREAD

**Issue by MegaDrive68k** [rundeck/rundeck#6101]
**Describe the bug**
Error 500 if editing `project.disable.executions` or `project.disable.schedule` parameters in `project.properties `file, occur on 3.2.7, and 3.2.8-SNAPSHOT.

**My Rundeck detail**

* Rundeck version: 3.2.7 / 3.2.8-SNAPSHOT
* install type: WAR
* OS Name/version: Ubuntu 20.04
* DB Type/version: H2

**To Reproduce**

1. Create a Project.
2. Go to Project Settings > Edit Configuration > Edit Configuration File (up to right button).
3. Change `project.disable.executions` or `project.disable.schedule` values and save it.
4. See error.

**Expected behavior**

Save the parameters on `project.properties` file.

**Screenshot**

![Screenshot_1](https://user-images.githubusercontent.com/51376003/83777574-94fa0400-a657-11ea-96cf-4c7bf1b4e6a1.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 76.0.1

**Additional context**

Full-stack error:

[328.txt](https://github.com/rundeck/rundeck/files/4731001/328.txt)

**Comment by jtobard** [comment]
3.3.0-SNAPSHOT confirmed too

**Comment by gschueler** [comment]
(note: #6139 is the same issue for 3.3)

**Comment by gschueler** [comment]
fixed by https://github.com/rundeck/rundeck/pull/6149
