### ISSUE TITLE
Enable use of standard SSH Agent

### ISSUE THREAD

**Issue by gtie** [rundeck/rundeck#6104]
**Is your feature request related to a problem? Please describe.**
For better security isolation, we are controlling an SSH Agent and associated key loading externally (through a systemd unit). The SSH Agent socket is then available to the rundeck user/process to freely use. This works well for shell scripts started as Rundeck jobs. It does not work for SCM/Git syncronisation - Rundeck's git/ssh client is not able to use the already running and loaded up key agent/socket.

**Describe the solution you'd like**
Enable Rundeck to use a pre-existing SSH Agent via a socket path, following the SSH_AUTH_SOCK

**Describe alternatives you've considered**
??

**Additional context**
Most *nix applications are happily using a system SSH Agent (usually, through a unix socket specified via the SSH_AUTH_SOCK environment variable). Rundeck is unfortunately not able to do so.

**Comment by mannahusum** [comment]
@gtie Have you solved this issue, or have you just worked around it by doing everything with local scripts?

**Comment by VasoVV** [comment]
This feature is also helpful when using multiple SSH keys (e.g. RSA key for outdated instances)
