### ISSUE TITLE
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ConfigMap): unknown field "type" in io.k8s.api.core.v1.ConfigMap

### ISSUE THREAD

**Issue by naveenkumarsp** [rundeck/rundeck#6106]
Unable to deploy the rundeck using helm chart.error received when trying to install :

Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ConfigMap): unknown field "type" in io.k8s.api.core.v1.ConfigMap

naveen@ubuntu:~ $  helm install automation incubator/rundeck
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(ConfigMap): unknown field "type" in io.k8s.api.core.v1.ConfigMap
naveen@ubuntu:~ $  kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:38:50Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
naveen@ubuntu:~ $  helm version
version.BuildInfo{Version:"v3.1.2", GitCommit:"d878d4d45863e42fd5cff6743294a11d28a9abce", GitTreeState:"clean", GoVersion:"go1.13.8"}
naveen@ubuntu:~ $

**Comment by aroq** [comment]
Same here.
