### ISSUE TITLE
`command` key is missing in /api/35/execution/<num>/output/

### ISSUE THREAD

**Issue by goodwillcoding** [rundeck/rundeck#6115]
**Describe the bug**
`command` key is missing in output (json) when calling "/api/35/execution/<num>/output/" as per documentation https://docs.rundeck.com/docs/api/rundeck-api.html#execution-output

**My Rundeck detail**

* Rundeck version: 3.2.7-20200515
* install type: deb
* OS Name/version: ubuntu 20.04
* DB Type/version: h2

**To Reproduce**
1. Issue API call to /api/35/execution/<execution num>/output/

**Expected behavior**
`command` key shoudl be present

**Comment by MegaDrive68k** [comment]
Reproduced and happening on 3.3.7:

With the following API call

```bash
#!/bin/sh

# protocol
protocol="http"

# basic rundeck info
rdeck_host="localhost"
rdeck_port="4440"
rdeck_api="36"
rdeck_token="wI1u51y4BfG8Nh8pIJo1KihwsuypDfBx"

# specific api call info
rdeck_job="b886e611-6b5f-4491-95a2-0ec9d974f7bc"

# api call
curl -s --location --request GET "$protocol://$rdeck_host:$rdeck_port/api/$rdeck_api/execution/1/output"
  --header "Accept: application/json" \
  --header "X-Rundeck-Auth-Token: $rdeck_token" \
  --header "Content-Type: application/json" | jq
```

I obtain:

```json
{
  "id": "1",
  "offset": "377",
  "completed": true,
  "execCompleted": true,
  "hasFailedNodes": false,
  "execState": "succeeded",
  "lastModified": "1608560842000",
  "execDuration": 1222,
  "percentLoaded": 98.43342036553526,
  "totalSize": 383,
  "retryBackoff": 0,
  "clusterExec": false,
  "serverNodeUUID": "046b41e4-8e1c-447d-9bfa-f93ac063d090",
  "compacted": false,
  "entries": [
    {
      "time": "11:27:22",
      "absolute_time": "2020-12-21T14:27:22Z",
      "log": "hi",
      "level": "NORMAL",
      "stepctx": "1",
      "node": "localhost"
    }
  ]
}
```

The command [entry](https://docs.rundeck.com/docs/api/rundeck-api.html#output-content) is missing.

**Comment by sideshowcecil** [comment]
We are facing the same issue for Rundeck version 3.3.10, any news on the fix?
