### ISSUE TITLE
"Unable to parse posted JSON data"  

### ISSUE THREAD

**Issue by wrogrammer** [rundeck/rundeck#6119]
**Describe the bug**
When I'm requesting the Webhook generated by Webhook Management I'm receiving: 
```
{
    "err": "Unable to parse posted JSON data"
}
```

**My Rundeck detail**

* The installed version of Rundeck is 3.3.0.
* Docker

**To Reproduce**
Request POST to Webhook without data parameter.

**Expected behavior**
200 Status Code

**Comment by sjrd218** [comment]
Try posting an empty json document to the endpoint `{}`

**Comment by wrogrammer** [comment]
I was trying and it is working. I'm using the external system and I'm not able to send additional data. 

I can use only the URL format: eg. 
/api/35/webhook/<ID>#test

**Comment by wrogrammer** [comment]
It's working now.
Thanks @sjrd218 !
