### ISSUE TITLE
Problem using node variables in inline script

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#612]
Hello,
I need to get the content of custom node variables which I have set in my ressources.xml as it:

 <node name="localhost" description="Rundeck server node" tags="" hostname="localhost" osArch="i386" osFamily="unix" osName="Linux" osVersion="3.2.0-4-486" username="rundeck"> <attribute name="node-executor" value="system-ssh-executor"/> <attribute name="ssh-test" value="false"/> <attribute name="was-cluster-num" value="0"/> <attribute name="was-p01-gameoflife-cluster" value="gameoflife_p01"/> </node>

This is just an example based on my "localhost" node.

Consider I want to use the custom var: "was-p01-gameoflife-cluster"

My problem is that I first have to "write" the variable and then I want to get its value.

To write the variable, I use other variables : iP0X and APPLI

Here is an example inline script:

-----------------------SCRIPT
# ! /bin/bash

APPLI="scrutmydocs"
iP0X="p01"

echo "node.was-p01-gameoflife-cluster= " @node.was-p01-gameoflife-cluster@ --> this works and echoes "gameoflife_p01" which is correct.

CLUSTER=@node.was-$iP0X-$APPLI-cluster@  --> there I write my variable (the result is "was-p01-gameoflife-cluster" which is correct.

CLUSTER=`echo @node.was-$iP0X-$APPLI-cluster@`  --> there I store my rewrited variable.

echo "WASCLUSTERNAME= "$WASCLUSTERNAME  --> there I try to display the result but it results in: 

echo "node All= " @node.*@ --> there I try to display all node's variables but it does not work. Normal ? (seen it in the documentation)
-----------------------/SCRIPT

The execution result follows:

10:51:15    localhost >     Step 1  node.was-p01-gameoflife-cluster=  gameoflife_p01
    10:51:15            WASCLUSTERNAME= 
    10:51:15            node All=  @node.*@

Any idea.
In now that is a "special" need but I will try to provide any usefull information if it can help.

Thanks by advance
Best regards and Happy new year !!!
Jérôme

**Comment by SydOps** [comment]
Thanks to explain the 1-2-3 ways
