### ISSUE TITLE
GPG error: https://rundeck.bintray.com/rundeck-deb  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61

### ISSUE THREAD

**Issue by djdole** [rundeck/rundeck#6125]
**Rundeck detail**

* Rundeck version: N/A
* install type: Advanced Package Tool
* OS Name/version: Ubuntu 20.04LTS
* DB Type/version: N/A

**To Reproduce**
Via: https://docs.rundeck.com/docs/administration/install/linux-deb.html#install-with-apt-get

1. 
```
echo "deb https://rundeck.bintray.com/rundeck-deb /" | sudo tee -a /etc/apt/sources.list.d/rundeck.list
```
2. 
```
curl 'https://bintray.com/user/downloadSubjectPublicKey?username=bintray' | sudo apt-key add -
```
3.  
```
sudo apt-get update 
```

**Expected behavior**
Apt repository should be updated.

**Actual behavior**
```
Reading package lists... Done                                               
W: GPG error: https://rundeck.bintray.com/rundeck-deb  Release: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 379CE192D401AB61
E: The repository 'https://rundeck.bintray.com/rundeck-deb  Release' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

**Comment by Rajpratik71** [comment]
This is minor issue related to public key verification .  If due to this if you are not able to install rundeck package using apt , then 
Do 
1. apt-get --allow-unauthenticated update

2. apt-get --allow-unauthenticated install rundeck-cli
