### ISSUE TITLE
BUG in UI during def edit option selection

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6128]
To reproduce the bug follow these steps:

Edit any job def:
Edit multiple options by Clicking on the option label. Note: must be multiple options.
in this case we have Option-1 and Option-2 in edit mode.

![image](https://user-images.githubusercontent.com/20629911/84449730-16770680-ac03-11ea-94ed-10108cb0d1b0.png)

![image](https://user-images.githubusercontent.com/20629911/84449829-5b9b3880-ac03-11ea-8022-28ff22b3eb79.png)

![image](https://user-images.githubusercontent.com/20629911/84450037-ec721400-ac03-11ea-9e04-ba60c2726f2a.png)

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world 

Which Rundeck version are you using?

Thanks!

**Comment by hs-hub-world** [comment]
Hi @MegaDrive68k 
Here you go...

RUNDECK
APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.2.8-20200608
BUILDGIT : v3.2.8-20200608-0-g7e632f5
SERVERUUID :
VERSION : 3.2.8-20200608

Thanks,
HS
