### ISSUE TITLE
Rundeck 3.3.0-PREVIEW2 doesn't start on Tomcat 8.5.x/9.0.x

### ISSUE THREAD

**Issue by MegaDrive68k** [rundeck/rundeck#6132]
**Describe the bug**

Rundeck doesn't start on Tomcat (3.3.0-PREVIEW2). That occurs with Tomcat 8.5.x and 9.0.x.

**My Rundeck detail**

* Rundeck version: 3.3.0-PREVIEW2
* install type: WAR(on Tomcat 8.5.54 and 9.0.34)
* OS Name/version: Ubuntu 20.04 LTS
* DB Type/version: H2

**To Reproduce**

1. Install Rundeck 3.3.0 WAR file on Tomcat following [this](https://docs.rundeck.com/docs/administration/install/tomcat.html#installation-on-linux).
2. Rundeck doesn't start in the same way of 3.2.x/3.1.x/3.0.x branches (catalina.out included at the end of this ticket).

**Expected behavior**

Rundeck must start normally on Tomcat.

**Additional context**

Catalina.out on Tomcat 8.5.54 [330-tomcat8.txt](https://github.com/rundeck/rundeck/files/4772651/330-tomcat8.txt)

Catalina.out on Tomcat 9.0.34 [330-tomcat9.txt](https://github.com/rundeck/rundeck/files/4772653/330-tomcat9.txt)

**Comment by sjrd218** [comment]
@MegaDrive68k can you try this again on the latest snapshot? I just booted a 3.3.x on tomcat yesterday.

**Comment by gschueler** [comment]
note: circle ci includes tomcat 8 and 9 tests which have passed.  they are configured here: 

https://github.com/rundeck/rundeck/blob/master/test/docker/test-api-tomcat.sh
https://github.com/rundeck/rundeck/blob/master/test/docker/docker-compose-tomcat-test.yml
https://github.com/rundeck/rundeck/tree/master/test/docker/dockers/tomcat

**Comment by gschueler** [comment]
I notice the linked docs also refer to tomcat 7 which is no longer supported in rundeck 3.3.0.  I think likely the docs are not correct somehow

**Comment by MegaDrive68k** [comment]
UPDATE: on Tomcat 9.0.10 works fine, seems a problem related to some Tomcat change. Thanks @sjrd218
