### ISSUE TITLE
Job Conditional Reports Previous Job "Never Run"

### ISSUE THREAD

**Issue by JSylvia007** [rundeck/rundeck#6135]
**Describe the bug**
I have a Job that calls other jobs as sort of a main run-file.  I execute a preliminary check, which sets some values on a management server that I have to ensure I don't get any erroneous alerts due to the updates being run.

The preliminary job executes fine, but the conditional that comes right after it, ALWAYS outputs the status of:

{{UUID}} is NOT RUNNING AND previously NEVER. Expected NOT RUNNING AND 'Succeeded'

No matter what I do, I can't figure out if either I'm doing something wrong or if I just have something misconfigured, or if the conditionals are just broken.  This is a small install for my homelab of about 10 servers, so I'm running with the default database back end, not MySQL or something else, so I don't know if that's an issue.

**My Rundeck detail**

* Rundeck version: Rundeck 3.2.8-20200608
* install type: deb
* OS Name/version: Ubuntu 18.04
* DB Type/version: H2? (whatever the default is)

**To Reproduce**
1. Create a new Job
2. Add a new workflow step for an existing job
3. Add a new workflow step for a job conditional that checks the status of the previous job
4. Execute job, job halts with above error about the first job never executing

**Expected behavior**
The conditional should detect that the job has just executed successfully and continue to the rest of the jobs.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83.0.4103.97 (Official Build) (64-bit)

**Comment by MegaDrive68k** [comment]
Hi @JSylvia007 

Can you share an example to test? I tested with the following example jobs (feel free to modify it).

HelloWorld job:

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <group>test1</group>
    <id>0bdd6fe5-addb-4051-b072-bb4430130a80</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "hello world"</exec>
      </command>
    </sequence>
    <uuid>0bdd6fe5-addb-4051-b072-bb4430130a80</uuid>
  </job>
</joblist>
```

CheckerJob (With a Job Step Conditional step, expects that HelloWorld job with a successful execution):

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <group>test1</group>
    <id>c6f2be75-81e8-4f8e-ba35-234d5c8a97d6</id>
    <loglevel>INFO</loglevel>
    <name>CheckerJob</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "starting..."</exec>
      </command>
      <command>
        <step-plugin type='job-state-conditional'>
          <configuration>
            <entry key='condition' value='Equals' />
            <entry key='executionState' value='Succeeded' />
            <entry key='fail' value='true' />
            <entry key='halt' value='true' />
            <entry key='jobName' value='test1/HelloWorld' />
            <entry key='jobProject' value='${job.project}' />
            <entry key='jobUUID' value='0bdd6fe5-addb-4051-b072-bb4430130a80' />
            <entry key='running' value='false' />
          </configuration>
        </step-plugin>
      </command>
    </sequence>
    <uuid>c6f2be75-81e8-4f8e-ba35-234d5c8a97d6</uuid>
  </job>
</joblist>
```

If the job never runs before:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/84666742-75809800-aeef-11ea-90c1-a7783d42ce53.png)

If the job runs before (Job State Conditional expectation).

![Screenshot_1](https://user-images.githubusercontent.com/51376003/84666754-79acb580-aeef-11ea-8ab4-0cd9e073bfa7.png)

**Comment by JSylvia007** [comment]
@MegaDrive68k - Do you think it could be because I have it in the same "playlist" job?

As you can see the 00 job pulls together multiple other jobs, one of which is 01.00 (details also immediately below).  01.00 runs an embedded script, and then returns to 00, where it then goes to the conditional that errors that 01.00 never executed.

**'01.00 - Prepare for Updates'**
```
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>6653c234-c46d-43aa-bc9a-9f0a5c7338f9</id>
    <loglevel>INFO</loglevel>
    <name>01.00 - Prepare for Updates</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <script><![CDATA[#!/bin/bash

SSH_CMD="ssh -n -o StrictHostKeyChecking=no -o LogLevel=quiet"
DOMAIN="mydomain.com"

$SSH_CMD myuser@myserver.$DOMAIN "/root/scripts/zabbixRunApt/checkAptMaintWindow.sh"]]></script>
        <scriptargs />
      </command>
    </sequence>
    <uuid>6653c234-c46d-43aa-bc9a-9f0a5c7338f9</uuid>
  </job>
</joblist>
```
**00 - Perform Updates**
```
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>804bf197-3a77-4d75-8e70-05e827a55253</id>
    <loglevel>INFO</loglevel>
    <name>00 - Perform Updates</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <notification>
      <onfailure>
        <email attachLog='true' attachLogInFile='true' recipients='root@mydomain.com' subject='[RUNDECK - MyDomain] -- Failure: ${job.name}' />
      </onfailure>
      <onsuccess>
        <email recipients='root@mydomain.com' subject='[RUNDECK - MyDomain] -- Success: ${job.name}' />
      </onsuccess>
    </notification>
    <notifyAvgDurationThreshold />
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <jobref name='01.00 - Prepare for Updates'>
          <uuid>6653c234-c46d-43aa-bc9a-9f0a5c7338f9</uuid>
        </jobref>
      </command>
      <command>
        <description>Is the environment prepared?</description>
        <step-plugin type='job-state-conditional'>
          <configuration>
            <entry key='condition' value='Equals' />
            <entry key='executionState' value='Succeeded' />
            <entry key='fail' value='true' />
            <entry key='halt' value='true' />
            <entry key='jobUUID' value='6653c234-c46d-43aa-bc9a-9f0a5c7338f9' />
            <entry key='running' value='false' />
          </configuration>
        </step-plugin>
      </command>
      <command>
        <jobref name='01.01 - Run and Install Updates on Node' nodeStep='true'>
          <uuid>51f4fcb8-11c7-4cc4-aad9-1b90a2101dc7</uuid>
        </jobref>
      </command>
      <command>
        <description>Have updated completed successfully?</description>
        <step-plugin type='job-state-conditional'>
          <configuration>
            <entry key='condition' value='Equals' />
            <entry key='executionState' value='Succeeded' />
            <entry key='fail' value='false' />
            <entry key='halt' value='true' />
            <entry key='jobUUID' value='51f4fcb8-11c7-4cc4-aad9-1b90a2101dc7' />
            <entry key='running' value='false' />
          </configuration>
        </step-plugin>
      </command>
      <command>
        <jobref name='01.01 - Run and Install Updates on Node' nodeStep='true'>
          <uuid>51f4fcb8-11c7-4cc4-aad9-1b90a2101dc7</uuid>
        </jobref>
      </command>
      <command>
        <description>Have updated completed successfully?</description>
        <step-plugin type='job-state-conditional'>
          <configuration>
            <entry key='condition' value='Equals' />
            <entry key='executionState' value='Succeeded' />
            <entry key='fail' value='false' />
            <entry key='halt' value='true' />
            <entry key='jobUUID' value='51f4fcb8-11c7-4cc4-aad9-1b90a2101dc7' />
            <entry key='running' value='false' />
          </configuration>
        </step-plugin>
      </command>
      <command>
        <jobref name='01.02 - APP01 Specific Updates'>
          <uuid>2f154d66-5915-441f-9909-0ae3e3f43a1a</uuid>
        </jobref>
      </command>
      <command>
        <description>Are we ready to reboot?</description>
        <step-plugin type='job-state-conditional'>
          <configuration>
            <entry key='condition' value='Equals' />
            <entry key='executionState' value='Succeeded' />
            <entry key='fail' value='false' />
            <entry key='halt' value='true' />
            <entry key='jobUUID' value='2f154d66-5915-441f-9909-0ae3e3f43a1a' />
            <entry key='running' value='false' />
          </configuration>
        </step-plugin>
      </command>
      <command>
        <jobref name='02 - Rolling Reboots'>
          <uuid>0e5d27f4-e42f-484a-b0a4-fafc4dda609d</uuid>
        </jobref>
      </command>
    </sequence>
    <uuid>804bf197-3a77-4d75-8e70-05e827a55253</uuid>
  </job>
</joblist>
```

**Comment by JSylvia007** [comment]
@MegaDrive68k - So... I added your two test jobs into a new project...  When I manually execute them in the correct order, it works fine.  I then created a "playbook" job that simply references the two jobs and runs them one after the other...

If I *DON'T* delete the execution results, the playbook job works fine...  If I delete the previous execution history, it again fails until I run the first job again manually.

This leads me to believe that something is happening when running the jobs back to back with a parent job calling them, and that it's not actually checking the ACTUAL last run, but simply the last "single" run.

**Comment by MegaDrive68k** [comment]
Hi @JSylvia007 

If you have a Job Reference Step based workflow, you must take the parent job status (even the child job is executed through a parent job, Rundeck is designed that way).

Regards!

**Comment by JSylvia007** [comment]
@MegaDrive68k - Ahhh!!! So for each of my conditionals, I just check the "playbook" job each time?  Wouldn't that fail the "is not running" check?

**Comment by MegaDrive68k** [comment]
@JSylvia007 

You're using Job Step Conditional against itself, The best approach is to use against the parent job (to check the last execution status), check the description: 'Assert that another Job is or is not running or the state of its most recent execution.' (like my first example but pointing to parent job that calls a child).

**Comment by JSylvia007** [comment]
@MegaDrive68k - That's what I had in the original and it still failed.  I guess I'm missing the point.

My current test config is as follows (using your two testing jobs).
Job 1 - HelloWorld
Job 2 - CheckerJob
Job 3 - Runs HelloWorld then CheckerJob (and CheckerJob is set to check HelloWorld)

In that setup, Job 3 fails.

Can you please help me how I should configure that to work?  In my actual example, what I need to have happen, is to make sure that "HelloWorld" has been run, is no longer running, and that it completed successfully before continuing on in the workflow.  I'm using it as a gate.  In the lager workflow I have a couple more checkpoints that are exactly the same, and I assume if it could get that far would suffer from the same issue.  Sorry, and I'm sure you're getting frustrated, but I'm obviously missing something LOL and I really want to learn what that is.

**Comment by MegaDrive68k** [comment]
@JSylvia007

Basically run Job 3 outside the parent job (you're calling the job state conditional step in the same parent job).

Maybe the best approach to your use case is to run the HelloWorld job via [RD-CLI](https://rundeck.github.io/rundeck-cli/) on inline-script step (to give the chance to Job State Conditional to evaluate an external execution) like this thread: https://groups.google.com/d/msg/rundeck-discuss/zuj3dG8oa68/ZLoKgoeyAwAJ

And in this way, you can see the HelloWorld executions, not only from some parent job.

I have an example:

HelloWord:

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>dd33434e-5b6e-40e1-88b0-e9b5b52a3801</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "hello world!"</exec>
      </command>
    </sequence>
    <uuid>dd33434e-5b6e-40e1-88b0-e9b5b52a3801</uuid>
  </job>
</joblist>
```

CheckerFakeParentJob (Executes HelloWorld vi RD-CLI and evaluate that execution later):

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>a90ec790-b856-4f00-8b66-2f37da1d00cb</id>
    <loglevel>INFO</loglevel>
    <name>CheckerFakeParentJob</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "starting"</exec>
      </command>
      <command>
        <fileExtension>.sh</fileExtension>
        <script><![CDATA[# print a message
echo "running HelloWorld job"

# run the hello world job via RD-CLI to get the individual execution and evaluate later
rd run -j HelloWorld -p ProjectEXAMPLE

# some time depending of job
sleep 3

# print a message
echo "done"]]></script>
        <scriptargs />
        <scriptinterpreter>/bin/bash</scriptinterpreter>
      </command>
      <command>
        <step-plugin type='job-state-conditional'>
          <configuration>
            <entry key='condition' value='Equals' />
            <entry key='executionState' value='Succeeded' />
            <entry key='fail' value='true' />
            <entry key='halt' value='true' />
            <entry key='jobUUID' value='dd33434e-5b6e-40e1-88b0-e9b5b52a3801' />
            <entry key='running' value='false' />
          </configuration>
        </step-plugin>
      </command>
    </sequence>
    <uuid>a90ec790-b856-4f00-8b66-2f37da1d00cb</uuid>
  </job>
</joblist>
```

Result:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/84693581-b8556680-af15-11ea-8a99-8586e00f5de8.png)

**Comment by JSylvia007** [comment]
@MegaDrive68k - Ok... So... This is getting closer, but how do I wait to continue instead of just failing.  In my example, the first prep job might take a minute or so, so I'd rather not just "fake it" with an arbitrary sleep amount, that's wasteful.

**Comment by JSylvia007** [comment]
@MegaDrive68k - It's not as elegant as being able to track the node tasks in the job individually as the parent job runs, BUT, it executes exactly as I'd expect it!
