### ISSUE TITLE
CURRENT LOGGED USER feature missing from User Manager/User Summary (3.3.0-PREVIEW2)

### ISSUE THREAD

**Issue by runwaldo** [rundeck/rundeck#6140]
**Describe the bug**
"Current logged user" feature is missing from the new "User Manager/User Summary" view even after adding the following line to rundeck-config.properties:

`rundeck.gui.userSummaryShowLoggedUsersDefault=true
`

**My Rundeck detail**

* Rundeck version: 3.3.0-PREVIEW2 
* install type: WAR
* OS Name/version: Ubuntu 20.04 
* DB Type/version: Mysql

**To Reproduce**
1. Add `rundeck.gui.userSummaryShowLoggedUsersDefault=true
` to your rundeck-config.properties file (not mandatory as this should be on by default)
2. Start Rundeck
3. Go to Gear Icon > User Manager > User Summary
4. Notice Current Logged User box is not present

**Expected behavior**
User Manager/ User Summary view must display a "Current Logged User" box in order to filter users by this criteria.

**Screenshots**
Without `rundeck.gui.userSummaryShowLoggedUsersDefault=true
` added to rundeck-config.properties file:

![Screenshot from 2020-06-16 05-40-40](https://user-images.githubusercontent.com/56878531/84758836-f6916b00-af93-11ea-90f1-1fb9cf30d062.png)

With `rundeck.gui.userSummaryShowLoggedUsersDefault=true
` added to rundeck-config.properties file:

![Screenshot from 2020-06-16 05-44-39](https://user-images.githubusercontent.com/56878531/84759282-83d4bf80-af94-11ea-856f-38bf4694b747.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 
 - Browser Firefox 77.0.1

**Comment by gschueler** [comment]
add `rundeck.gui.userSummaryShowLoginStatus=true` to the config, to enable login status
