### ISSUE TITLE
API listing running executions for all projects broken since 3.2.6

### ISSUE THREAD

**Issue by mazzella-c** [rundeck/rundeck#6144]
**Describe the bug**

We've been using for years Rundeck API to list running executions (https://docs.rundeck.com/docs/api/rundeck-api.html#listing-running-executions).

`curl -sS -H 'Content-Type: application/json' -X GET ${RUNDECK_URL}/api/${API_VERSION}/project/*/executions/running?authtoken=${RUNDECK_KEY_API}` was perfectly working until 3.2.6 was released.

The joker * is no longer recognized and generates a stack trace in log. However it's working if we call a specific project.

**My Rundeck detail**

* Rundeck version: 3.2.7
* install type: war
* OS Name/version: Redhat 7.8
* DB Type/version: Postgre 11

**To Reproduce**
API call listing running executions using *

**Expected behavior**
Being able to list running executions for all projects.

**Desktop**
 - OS : Windows
 - Browser : Firefox
 - Version : 77.0.1

**Additional context**

Full stack trace : [stack_trace.txt](https://github.com/rundeck/rundeck/files/4791340/stack_trace.txt)

**Comment by MegaDrive68k** [comment]
Hi @mazzella-c 

Thanks for your feedback, we'll follow that issue from here:

https://github.com/rundeck/rundeck/issues/6069

Regards!
