### ISSUE TITLE
UI glitch in Jobs activity when using long options names

### ISSUE THREAD

**Issue by mazzella-c** [rundeck/rundeck#6145]
**Describe the bug**
When using long or several option names in jobs, display is truncated in "Activity for jobs"
![screen](https://user-images.githubusercontent.com/38751896/84881830-af3bd500-b08e-11ea-92cc-c92ff77cab7a.PNG)
**My Rundeck detail**

* Rundeck version: 3.2.7
* install type: war
* OS Name/version: Redhat 7.8
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**
Create a job with several options names or long options and run it. 
**Expected behavior**
Display should be correct.

**Desktop**
 - OS: Windows
 - Browser : Firefox
 - Version : 77.0.1

**Comment by MegaDrive68k** [comment]
Confirmed,

On Activity page:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/84939516-74489a00-b0ac-11ea-8eec-7a1ce8cd5f0a.png)

And Job list page:

![Screenshot_4](https://user-images.githubusercontent.com/51376003/84939509-701c7c80-b0ac-11ea-9489-f63d59366453.png)

Also happening on 3.3.0-PREVIEW2.

Thanks for your feedback @mazzella-c!

**Comment by ProTip** [comment]
Appears to be related to a 17 year old bug in FireFox: https://bugzilla.mozilla.org/show_bug.cgi?id=221154 .
