### ISSUE TITLE
Wrong Rundeck behaviour with some jobs with custom UUID

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/rundeck#6150]
## Describe the bug
If you have Rundeck with custom job UUID using only numbers, e.g. "job1 uuid=1 id=1, job2 uuid=2 id=2", Rundeck will start to show you crossing information between jobs, e.g. "job1 uuid=2 id=1, job2 uuid=1 id=2", job2 will show the information of the job1" and vice-versa.

## My Rundeck detail

* Rundeck version: 3.2.7
* install type: rpm/war/deb
* OS Name/version: CentOS 7
* DB Type/version: MySQL 5.7

## To Reproduce
1. Create two jobs with uuid 1 and uuid 2
2. On the database or though apicall change the values of the uuid job1 uuid=2, job2 uuid=1
4. See error entering to the desired job.

## Expected behavior
Don't happen?

## Screenshots
**On all the screenshots below, I clicked the first Job (job1).**
### Before:
![image](https://user-images.githubusercontent.com/11720535/85031737-07d1a780-b14d-11ea-9b4d-99927e85c271.png)
![image](https://user-images.githubusercontent.com/11720535/85031218-69dddd00-b14c-11ea-8f79-ec0b55ae375a.png)
![2020-06-18_10h15_01](https://user-images.githubusercontent.com/11720535/85031365-942f9a80-b14c-11ea-9f0f-a78f47383c9e.png)

### After
![image](https://user-images.githubusercontent.com/11720535/85031786-1750f080-b14d-11ea-80f4-6e9208871973.png)
![image](https://user-images.githubusercontent.com/11720535/85031568-d6f17280-b14c-11ea-86e4-020803e28661.png)
![image](https://user-images.githubusercontent.com/11720535/85031429-aa3d5b00-b14c-11ea-8b06-5813734cc3fa.png)

## Desktop (please complete the following information):
 - OS: Windows 10 build 1909
 - Browser: Opera GX, LVL1 (core: 68.0.3618.142)

## Additional context
https://github.com/rundeck/rundeck/blob/cc1b9dab5370c99c59cb933dbc80f1c0fe3ae448/rundeckapp/grails-app/services/rundeck/services/ScheduledExecutionService.groovy#L1032

**Comment by jtobard** [comment]
Some notes about this, we can start limiting that the new jobs that are created have a format similar to UUID and throwing warnings when importing jobs with an invalid format to eventually reach mandatory compliance of the UUID format and restriction when importing an invalid UUID

**Comment by gschueler** [comment]
@jtobard is this fixed via your earlier change?

**Comment by jtobard** [comment]
@gschueler no, got a w.i.p. for this but is on hold by now, the users change the custom uuid to avoid this problem by now

**Comment by jtobard** [comment]
this need documentation about risk of using number instead of uuid, moved from bug to need-documentation

**Comment by fdevans** [comment]
@chrismcg14 Didn't we address this already?

**Comment by chrismcg14** [comment]
@fdevans I do not believe so. None of this looks familiar to me.
