### ISSUE TITLE
grailsdb location appears appears to be tied to the  rundeck home directory GCOS field

### ISSUE THREAD

**Issue by connaryscott** [rundeck/rundeck#617]
We had an issue when upgrading to 1.6.2-1.5.GA where grailsdb gets written to ~rundeck/rundeck directory, example shown here is the home directory for rundeck which will be shown is not explicitly defined anywhere else, however, a grailsdb files show up:

<pre>
[cscott2@rundeckrk1v ~]$ rpm -q rundeck
rundeck-1.6.2-1.5.GA
[cscott2@rundeckrk1v ~]$ getent passwd rundeck
rundeck:VAS:10075:10003:rundeck:/home/rundeck:/usr/local/bin/shell
[cscott2@rundeckrk1v ~]$ ls -l  ~rundeck/rundeck/grailsh2.*
-rw-rw-r-- 1 rundeck webadmin    49360 Jan 14 15:23 /home/rundeck/rundeck/grailsh2.71287.log.db
-rw-rw-r-- 1 rundeck webadmin 25722928 Jan 14 15:23 /home/rundeck/rundeck/grailsh2.data.db
-rw-rw-r-- 1 rundeck webadmin  7618608 Jan 14 15:23 /home/rundeck/rundeck/grailsh2.index.db
-rw-rw-r-- 1 rundeck webadmin   166982 Jan 13 17:01 /home/rundeck/rundeck/grailsh2.trace.db

/home/rundeck/rundeck/grailsh2.lobs.db:
total 16
-rw-rw-r-- 1 rundeck webadmin 5520 Jan 13 15:14 1.t97.lob.db
-rw-rw-r-- 1 rundeck webadmin 5520 Jan 13 15:17 2.t97.lob.db
</pre>

This is either an upgrade issue that I did not catch or perhaps there is something inadvertently tied to the rundeck account?

Took some wild guesses with no results on what does this:

<pre>
[rundeck@rundeckrk1v ~]$ grep -Ri grailsdb /var/rundeck
[rundeck@rundeckrk1v ~]$ grep -Ri grailsdb /var/lib/rundeck
[rundeck@rundeckrk1v ~]$ grep -Ri grailsdb /etc/rundeck
</pre>

We have temporarily implemented a symlink for this location as it is too large for that path.

**Comment by ahonor** [comment]
Reopen if this is still a concern
