### ISSUE TITLE
GUI: no spaces in dashboard's execution info

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#6195]
**Describe the bug**
3.2.8 vs 3.3.0 rc1

**My Rundeck detail**

* Rundeck version: 3.3.0 snapshot and rc1
* install type: war
* OS Name/version: ubuntu 20.04]
* DB Type/version: mysql

**Screenshots**
![rc1](https://user-images.githubusercontent.com/34582874/85877638-734af300-b7a5-11ea-8858-05dd62f85abb.png)

**Comment by fdevans** [comment]
This also happens on System Report

**Comment by MegaDrive68k** [comment]
Still happening on 3.3.2-SNAPSHOT:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/89933630-55164680-dbdd-11ea-9d3b-ab676b33fcf9.png)

**Comment by fdevans** [comment]
Still on 3.3.5 as well.
Possible also associated to header row on System Report page being squished too.

**Comment by gschueler** [comment]
@fdevans i think I fixed spacing in 3.3.5-rc2 https://github.com/rundeck/rundeck/pull/6549

**Comment by MegaDrive68k** [comment]
Confirmed, works OK on 3.3.5-RC2:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/96156369-5cace100-0ee7-11eb-9273-70a871af895c.png)

**Comment by fdevans** [comment]
Closed
