### ISSUE TITLE
Failed to start execution: org.springframework.dao.DataAccessResourceFailureException: Hibernate operation: could not prepare statement; SQL

### ISSUE THREAD

**Issue by z079449** [rundeck/rundeck#6196]
Failed to start execution: org.springframework.dao.DataAccessResourceFailureException: Hibernate operation: could not prepare statement; SQL [select schedulede0_.id as id1_15_0_, schedulede0_.version as version2_15_0_, schedulede0_.do_nodedispatch as do_noded3_15_0_, schedulede0_.log_output_threshold as log_outp4_15_0_, schedulede0_.next_execution as next_exe5_15_0_, schedulede0_.date_created as date_cre6_15_0_, schedulede0_.calendar as calendar7_15_0_, schedulede0_.node_keepgoing as node_kee8_15_0_, schedulede0_.node_exclude_os_arch as node_exc9_15_0_, schedulede0_.uuid as uuid10_15_0_, schedulede0_.node_include as node_in11_15_0_, schedulede0_.success_on_empty_node_filter as success12_15_0_, schedulede0_.node_exclude_os_version as node_ex13_15_0_, schedulede0_.timeout as timeout14_15_0_, schedulede0_.change_request as change_15_15_0_, schedulede0_.node_exclude_precedence as node_ex16_15_0_, schedulede0_.node_exclude_name as node_ex17_15_0_, schedulede0_.notify_avg_duration_threshold as notify_18_15_0_, schedulede0_.calendar_hour as calenda19_15_0_, schedulede0_.day_of_week as day_of_20_15_0_, schedulede0_.node_include_os_version as node_in21_15_0_, schedulede0_.node_exclude_os_name as node_ex22_15_0_, schedulede0_.retry as retry23_15_0_, schedulede0_.cron_array as cron_ar24_15_0_, schedulede0_.filter as filter25_15_0_, schedulede0_.group_path as group_p26_15_0_, schedulede0_.scheduled as schedul27_15_0_, schedulede0_.orchestrator_id as orchest28_15_0_, schedulede0_.node_threadcount_dynamic as node_th29_15_0_, schedulede0_.node_include_name as node_in30_15_0_, schedulede0_.multiple_executions as multipl31_15_0_, schedulede0_.time_zone as time_zo32_15_0_, schedulede0_.rduser as rduser33_15_0_, schedulede0_.node_include_os_name as node_in34_15_0_, schedulede0_.node_exclude as node_ex35_15_0_, schedulede0_.node_rank_order_ascending as node_ra36_15_0_, schedulede0_.nodes_selected_by_default as nodes_s37_15_0_, schedulede0_.node_include_os_arch as node_in38_15_0_, schedulede0_.loglevel as logleve39_15_0_, schedulede0_.advanced_schedule_enabled as advance40_15_0_, schedulede0_.node_exclude_os_family as node_ex41_15_0_, schedulede0_.execution_enabled as executi42_15_0_, schedulede0_.max_multiple_executions as max_mul43_15_0_, schedulede0_.node_include_os_family as node_in44_15_0_, schedulede0_.last_updated as last_up45_15_0_, schedulede0_.retry_delay as retry_d46_15_0_, schedulede0_.workflow_id as workflo47_15_0_, schedulede0_.exec_count as exec_co48_15_0_, schedulede0_.month as month49_15_0_, schedulede0_.hour as hour50_15_0_, schedulede0_.log_output_threshold_action as log_out51_15_0_, schedulede0_.arg_string as arg_str52_15_0_, schedulede0_.user_role_list as user_ro53_15_0_, schedulede0_.total_time as total_t54_15_0_, schedulede0_.node_rank_attribute as node_ra55_15_0_, schedulede0_.server_nodeuuid as server_56_15_0_, schedulede0_.default_tab as default57_15_0_, schedulede0_.node_exclude_tags as node_ex58_15_0_, schedulede0_.seconds as seconds59_15_0_, schedulede0_.ref_exec_count as ref_exe60_15_0_, schedulede0_.node_threadcount as node_th61_15_0_, schedulede0_.node_include_tags as node_in62_15_0_, schedulede0_.job_name as job_nam63_15_0_, schedulede0_.calendar_minute as calenda64_15_0_, schedulede0_.schedule_enabled as schedul65_15_0_, schedulede0_.year as year66_15_0_, schedulede0_.day_of_month as day_of_67_15_0_, schedulede0_.node_filter_editable as node_fi68_15_0_, schedulede0_.log_output_threshold_status as log_out69_15_0_, schedulede0_.description as descrip70_15_0_, schedulede0_.minute as minute71_15_0_, schedulede0_.project as project72_15_0_ from scheduled_execution schedulede0_ where schedulede0_.id=?]; The connection attempt failed.; nested exception is org.postgresql.util.PSQLException: The connection attempt failed.

**Describe the bug**
We are getting  "Failed to start execution: org.springframework.dao.DataAccessResourceFailureException: Hibernate operation: could not prepare statement; SQL"  error very frequently in our Rundeck . The pool count and DB max count everything is good .

**My Rundeck detail**

* Rundeck version: 3.0.10
* install type: ,war
* OS Name/version: CentOs
* DB Type/version: postgres

please look into this issue and let me know how can we proceed ?

Thanks
Venkat

**Comment by sjrd218** [comment]
Based on the last line from your posted exception: `The connection attempt failed.; nested exception is org.postgresql.util.PSQLException: The connection attempt failed.` It seems that Rundeck cannot contact your database.

**Comment by venkategowdap** [comment]
@sjrd218 : Thanks ,  The DB Max Active count is set to 300 , still we need to do something from config side .?

**Comment by sjrd218** [comment]
Perhaps you've maxed out the connections on the db server? Might be worth reviewing your config on your postgres db.

**Comment by venkategowdap** [comment]
Anything specific related to this problem on DB config side , please share some more insights on this .  
Thanks

**Comment by z079449** [comment]
@sjrd218 and all :  We have set DB max count 300 for both Rundeck and DB .... Wait time also good at our Rundeck Config end ..Still we are facing this issue ..
