### ISSUE TITLE
Misinterpreted ANSI escape sequence

### ISSUE THREAD

**Issue by greg0ire** [rundeck/rundeck#6198]
**Describe the bug**
`1;38;5;113` is interpreted as blinking bold black text

**My Rundeck detail**

* Rundeck version: e.g. 3.2.4-20200318
* install type: unsure
* OS Name/version: unsure
* DB Type/version: unsure

**To Reproduce**
1. Go to "Commands"
2. Pick a node
3. Execute `echo -e "\033[1;38;5;113mThis is a test\033[0m"`. To achieve that, it seems you have to type in `echo -e '"\033[1;38;5;113mThis is a test\033[0m"'`
3. Look at the output
4. Compare with the color and formatting you have when you do 3 in your own terminal

**Expected behavior**
Green, not blinking text

![green](https://user-images.githubusercontent.com/657779/86003906-c8d80780-ba12-11ea-9ee3-9f148b09437f.png)

**Screenshots**

![Peek 2020-06-29 14-11](https://user-images.githubusercontent.com/657779/86003911-cb3a6180-ba12-11ea-809f-dfdeff9693c9.gif)

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 77.0

**Additional context**
[`5` means "blink"](https://stackoverflow.com/questions/4842424/list-of-ansi-color-escape-sequences) but the above does not cause blinking in my terminal.

SO says:

> 38       ║  Set foreground color          ║  Next arguments are `5;<n>` or `2;<r>;<g>;<b>`, see below                

So `1;38;5;113` should be interpreted as bold, Set foreground color to `113` (which is green)

**Comment by MegaDrive68k** [comment]
Reproduced, also happening on 3.2.8

![Screenshot_3](https://user-images.githubusercontent.com/51376003/86019519-b4851200-b9f4-11ea-84bd-7144c1c4fc02.png)

Works in this way:
`
echo -e '"\033[1;32mThis is a test\033[0m"'`

![Screenshot_4](https://user-images.githubusercontent.com/51376003/86020096-776d4f80-b9f5-11ea-8390-0225259d79df.png)


Thanks for your feedback @greg0ire!

**Comment by greg0ire** [comment]
@MegaDrive68k thank you for the workaround, but I would also want it to work with the more complicated `1;38;5;113`, because that's what the library I use (here `symfony/console`) uses. Please note that this library is very widely used in the PHP world, and that this bug probably affects a lot of folks.

Why did you remove the `status:reproduced` label BTW?

**Comment by gschueler** [comment]
I think the combination of `1;` (bold) and the `38;5;113` (256 color setting) is not getting interpreted correctly.  If you remove the bold, it seems to work `echo '"\033[38;5;113mThis is a test\033[0m"'`.
this is a bug
