### ISSUE TITLE
Authentication Issue / HTTP ERROR 403 !role

### ISSUE THREAD

**Issue by mzima** [rundeck/rundeck#620]
The following (slightly changed) realm.properties and admin.aclpolicy leads to a "HTTP ERROR 403" message after logging in with user "testuser". The same configuration works fine with Rundeck 1.6.2. Happens also with LDAP authentication.

Environment:
- Rundeck 2.0.0-beta1
- Rundeck 2.0.0-snapshot (rundeck2 branch / commit 5761abd52a50a2c0e90831b1b6a52c1d40288a0e)
#### realm.properties:

``` html
admin:admin,user,admin
user:user,user
testuser:pass,testgroup
```
#### admin.aclpolicy

``` html
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job: 
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: testgroup

---

description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
by:
  group: testgroup
```
#### Error Message (user: testuser)

``` html
HTTP ERROR 403

Problem accessing /. Reason:

    !role

Powered by Jetty://
```

**Comment by kondalonline** [comment]
I had the same issue. Thank you ahonor !!

**Comment by tekgroup** [comment]
Hi,

Installed Rundeck on windows by deploying the war file on a windows/tomcat server. I am getting the login page and as soon as i enter the credentials(admin/admin), it is displaying the error

**HTTP Status 403 - Access to the requested resource has been denied**

Admin.aclpolicy
****
description: admin, all access.
context:
 project: '.*' # all projects
for:
 resource:
   - allow: '*' # allow read/create all kinds
 adhoc:
   - allow: '*' # allow read/running/killing adhoc jobs
 job: 
   - allow: '*' # allow read/write/delete/run/kill of all jobs
 node:
   - allow: '*' # allow read/run for all nodes
by:
 group: admin
 
---
 
description: admin, all access.
context:
 application: 'rundeck'
for:
 resource:
   - allow: '*' # allow create of projects
 project:
   - allow: '*' # allow view/admin of all projects
 project_acl:
   - allow: '*' # allow admin of all project-level ACL policies
 storage:
   - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
 group: admin
****

tomcat users
****
role rolename="admin"/>
role rolename="admin-gui"/>
role rolename="manager-gui"/>
role rolename="manager-jmx"/>
user username="admin" password="admin" roles="manager-gui"/>
****

Here are my Files in the Rundeck Root Directory:

Directory of F:\rundeckpro

DIR>          .
DIR>          ..
DIR>          etc
DIR>          libext
DIR>          projects
DIR>          var

 Directory of F:\rundeckpro\etc

DIR>          .
DIR>          ..
admin.aclpolicy
apitoken.aclpolicy
framework.properties
rundeck-config.properties
rundeckrealm.properties
               5 File(s)          3,385 bytes

**Comment by tekgroup** [comment]
I don't have the Realm.properties file anywhere

**Comment by ahonor** [comment]
@tekgroup realm.properties is only for the launcher.jar or rpm/deb installs. If you are deploying to Tomcat it will be tomcat-users.xml. I notice the F:\rundeckpro path. Are you using Pro?

**Comment by tekgroup** [comment]
Yeah. i am using a pro

**Comment by tekgroup** [comment]
Is there anything that i am missing..

**Comment by ahonor** [comment]
@tekgroup create an account at the http://support.rundeck.com site and you can get additional help there.

**Comment by tekgroup** [comment]
Sure. Thank you..

**Comment by ultimatehem** [comment]
Hi @ahonor is it possible to add more than one user role like user and readuser where i can assign execute privilege to user and readonly previlege to readuser like bleow .

 <security-role>
                <role-name>user</role-name>
                <role-name>readuser</role-name>
        </security-role>

**Comment by ahonor** [comment]
@ultimatehem yes, that is possible

**Comment by ultimatehem** [comment]
@ahonor Could you please guide me how to achieve it . When i define two roles user and readuser it isn't working as expected
