### ISSUE TITLE
Plugins in .ZIP fomrat not being updated correctly using the Rundeck GUI

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#6201]
**Describe the bug**
Rundeck Plugins in .Zip format are not being correctly updated using the Rundeck GUI.

**My Rundeck detail**

* Rundeck version: [ 3.2.X]
* install type: [.war]
* OS Name/version: [ubuntu 16.04]
* DB Type/version: [DB2 ]

**To Reproduce**
1. Go to 'Gear Icon - Upload Plugin'
2. Select the Plugin to update and install
3. Go to Gear Icon - Installed Plugins and check the Plugin Version.
4. The Plugin still shows Version 1

**Expected behavior**
The Plugin should be updated to version 1.1

**Screenshots**
1.Plugin Version 1 is already installed
![image](https://user-images.githubusercontent.com/36487101/86046329-09d41a00-ba1b-11ea-82f4-bef26182a929.png)

2. We update the Plugin uploading V1.1
![image](https://user-images.githubusercontent.com/36487101/86046402-2a03d900-ba1b-11ea-9f5d-cf15ae0e9a60.png)

3. We see a message that the Plugin was installed
![image](https://user-images.githubusercontent.com/36487101/86046875-fb3a3280-ba1b-11ea-8bb8-171010fd2039.png)

4. Checking the Installed Plugins, we can see that the Plugin Version is still V 1.
![image](https://user-images.githubusercontent.com/36487101/86046913-07be8b00-ba1c-11ea-9714-0abee3c1a368.png)

5. After restarting the Rundeck service, the Plugin gets updated corrected in the Rundeck GUI.
![image](https://user-images.githubusercontent.com/36487101/86046944-1442e380-ba1c-11ea-8f2b-16ec3967ce6e.png)

**Additional context**
Once the rundeck service is restarted, is Plugin gets updated correctly

It seems that the expected behavior should be also that the Plugin gets updated just changing the Version Field in the .yaml file of the Plugin, not being necessary to change the name of the directory that's going to be compressed with the .zip extension.

**Comment by niall-munnelly** [comment]
Just a little additional information here - it's not possible to update a plugin in situ via the UI; when I upload a .zip plugin with the same name and different version in plugin.yaml, Rundeck Enterprise 3.2.7 returns an error that says the plugin is already installed.


![git-6201](https://user-images.githubusercontent.com/17707275/86049892-f461ee80-ba20-11ea-97d4-84025d9b3f01.png)
