### ISSUE TITLE
All running executions are not displayed

### ISSUE THREAD

**Issue by alixleger** [rundeck/rundeck#6206]
**Describe the bug**
Hi, we recently migrated to Rundeck 3.2.8 and before we used the 2.11.11. The problem is that we have more than 20 running executions per project but our Activity UI only show the 20 most recent without pagination. So it's now difficult for us to detect abnormal long running jobs. There is the paging returned by our "project/{project}/executions/running" endpoint : https://pastebin.com/vq8F9Swc 
Is it normal to have by default a pagination for jobs already done but not for those which are in the course of execution? Is there a way to have this pagination? Because we had that pagination in 2.11.11.

**My Rundeck detail**

* Rundeck version: 3.2.8
* OS Name/version: Debian
* DB Type/version: mysql

**To Reproduce**
1. Go to Activity
2. Have more than 20 running executions

**Expected behavior**
A list of all running executions with pagination.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Firefox

**Comment by MegaDrive68k** [comment]
Hi @alixleger 

Try Adding this line on your `rundeck-config.properties` fie:

`rundeck.pagination.default.max=50`

Restart Rundeck service and try again.

![Screenshot_2](https://user-images.githubusercontent.com/51376003/86259529-204cb380-bb8a-11ea-8747-a1ac18991b18.png)

Regards!

**Comment by alixleger** [comment]
Hi @MegaDrive68k,
Okay but if I do that I will have all my currently running executions in one page, and if one day I have more than 50 running executions, I will have to increase that value and retart again the service...
Is that no longer possible to paginate running executions ?

**Comment by MegaDrive68k** [comment]
Hi @alixleger 

You're right, I'm tried with a lot of running executions and the Activity only shows that executions on the same page (limited with the default value). 

Related: https://github.com/rundeck/rundeck/pull/5469

Thanks for your feedback!
