### ISSUE TITLE
Too much space on /mnt/resource/rundeck  for execution-xxxxx.xml

### ISSUE THREAD

**Issue by reziel84** [rundeck/rundeck#6210]
I have a problem with space on disk under /mnt/resource/rundeck, there's a lot of files called ./execution-123456.xml and i don't know in which way they are created. space on disk for this folder is of 19gb, too much.
it's possibile that's an issue related to Execution History Clean?

**My Rundeck detail**

* Rundeck version: 3.2.1-20200113
* install type: rpm
* OS Name/version: Rhel 7.4
* DB Type/version: h2

I would like to clear this space because it's really too much. I just clear /var/lib/rundeck with clear history, but i don't know in which way i can clean also folder under mnt.
P.s. i read that some people have same files under /tmp/rundeck but i don't have this folder, why?
Please can anyone help me?

thanks

**Comment by MegaDrive68k** [comment]
Hi @reziel84 

Seems related to this issue: https://github.com/rundeck/rundeck/issues/5943#issuecomment-610671469

That bug is fixed right now.

Can you test using the latest Rundeck version? (3.2.8 at this moment).

Regards.

**Comment by reziel84** [comment]
> 
> 
> Hi @reziel84
> 
> Seems related to this issue: [#5943 (comment)](https://github.com/rundeck/rundeck/issues/5943#issuecomment-610671469)
> 
> That bug is fixed right now.
> 
> Can you test using the latest Rundeck version? (3.2.8 at this moment).
> 
> Regards.

hi megadrive68k
thanks for your fast reply.
i just update rundeck to version 3.3 just right now.
there is anything else that i can do to clean that directory?

**Comment by MegaDrive68k** [comment]
Hi @reziel84 

Your executions logs are stored at `/var/lib/rundeck/logs/rundeck/YourProject/job/YourJobID/logs, you can delete those xml files generated at /mnt/resource/rundeck (it's part of that bug).

Greetings.

**Comment by reziel84** [comment]
Hi @MegaDrive68k 
Correct.....my xml file are under /var/lib...... please see the picture
![immagine](https://user-images.githubusercontent.com/25266466/86895025-2d2a5380-c104-11ea-9ae7-17da1108619c.png)

ok so at this point i can delete /mnt/resource/rundeck/.xml files, right?
last question, can i delete this files by hand simply rm -rf or i just make some other operations on the database or some other stuff?
my idea is: shutdown rundeckd service, delete all files under folder, restart the service, correct?
sorry for my many many questions but this is a production server and i'm very afraid to make operations on this VM :)

**Comment by MegaDrive68k** [comment]
Yes, you can delete XML files on /mnt/resource/rundeck/ that's part of https://github.com/rundeck/rundeck/issues/5943 bug.

**Comment by reziel84** [comment]
niceeee
i just delete all xml file under resource/rundeck and now that's folder from 17gb become 600mb :), really nice.
thanks for your support @MegaDrive68k , i really appreciate your work.
