### ISSUE TITLE
Rundeck 3.3.0 doesn't start on Windows at the first launch (JDK8 and JDK11)

### ISSUE THREAD

**Issue by MegaDrive68k** [rundeck/rundeck#6214]
**Describe the bug**

Rundeck 3.3.0 doesn't start at the first launch on Windows-based systems (tested on JDK8 and JDK11).

**My Rundeck detail**

* Rundeck version: 3.3.0
* install type: WAR
* OS Name/version: Windows Server 2019
* DB Type/version: H2

**To Reproduce**

1. Download 3.3.0 WAR.
2. Launch with `java -jar rundeck-3.3.0-20200701.war`
3. See the following error: 

[java-error.txt](https://github.com/rundeck/rundeck/files/4864970/java-error.txt)

**Additional context**

Launching Rundeck 3.3.0 for the second time seems to launch correctly (with some warnings):

![Screenshot_4](https://user-images.githubusercontent.com/51376003/86372854-c105a680-bc50-11ea-8c9b-2a95ed42bca6.png)

**Comment by mikesuding** [comment]
I have seen this too. If possible the confusing warning text should be avoided even if it's not fatal.
