### ISSUE TITLE
3.3.0: project description verification stricter?

### ISSUE THREAD

**Issue by BuJo** [rundeck/rundeck#6219]
**Describe the bug**
After upgrading Rundeck from latest 3.2.x to 3.3.0, the Application failed to start.

```
[2020-07-06T09:10:30,227] ERROR boot.SpringApplication [main] - Application run failed
grails.validation.ValidationException: Validation Error(s) occurred during save():
- Field error in object 'rundeck.Project' on field 'description': rejected value [API Gateway & related projects];
arguments [description,class rundeck.Project,API Gateway & related projects,^[a-zA-Z0-9\p{L}\p{M}\s\.,\(\)_-]+$]; default message [Property [{0}] of class [{1}] with value [{2}] does not match the required pattern [{3}]]
```

I could not find this in the 3.3 upgrade document.

**My Rundeck detail**

* Rundeck version: 3.3.0
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: mysql

**To Reproduce**
1. Go to any project `/etc/project.properties`
2. Revise description to contain a `&`
3. Restart Rundeck

**Expected behavior**
I did expect the changed behavior to be either documented or backwards compatible.

**Additional context**
I modified the property files by hand and Rundeck started again, so all is well.

**Comment by MegaDrive68k** [comment]
Hi @BuJo 

I'm trying to reproduce your issue (from 3.2.8 to 3.3.0 on MySQL 5), can you provide a single "hello world" example project to test? (containing a `&` on the description).

Thanks!

**Comment by BuJo** [comment]
Thank you for looking at it, I restored a state from before the upgrade from backup.  I will put a 'before and after' inside the zip.

[api.zip](https://github.com/rundeck/rundeck/files/4901590/api.zip)

It might be strongly related to https://github.com/rundeck/rundeck/issues/6220 if somehow the storage mechanism changed and different validation rules apply.

**Comment by BuJo** [comment]
Let's close this issue, nobody else seems to have run into this problem.
