### ISSUE TITLE
3.3.0: imported projects not accessable

### ISSUE THREAD

**Issue by BuJo** [rundeck/rundeck#6220]
**Describe the bug**
After upgrading from latest 3.2.x to 3.3.0 some projects were no longer available.

```
[2020-07-06T09:49:22,378] ERROR services.ScheduledExecutionService [pool-2-thread-2] - Job not rescheduled in project Team2: 0de20a8c-f1a4-4ee0-b342-14ed8a929fbe: Project does
 not exist: Team2
java.lang.IllegalArgumentException: Project does not exist: Team2
```

It turned out that all projects where the configuration was named `project.properties.imported` were unavailable both from the frontend as well as backend.

I renamed all the property files to not contain .imported on a hunch:

```
find /var/lib/rundeck/projects/ -name project.properties.imported | sed 's/.imported//' | xargs -I{} echo mv {}.imported {}
```

The projects are now available again and can be used, but I'm quite uneasy..
Rundeck complains:

```
WARN  services.ProjectManagerService [main] - Filesystem project Team2, marked as imported. Rename etc/project.properties to etc/project.properties.imported
```

I'm unsure what to do, I have not found anything related to that in the upgrade documentation.

**My Rundeck detail**

* Rundeck version: 3.3.0
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: mysql

**To Reproduce**
1. Have an old 3.2.x Rundeck instance with projects marked as imported
2. Upgrade to 3.3.0
3. Login and view projects
4. Imported projects are not shown in GUI and existing Jobs cannot execute because projects missing

**Expected behavior**
Projects should be available even if marked as imported and property file is named `project.properties.imported`.

**Additional context**
The instance is quite old and has had many upgrades over the years, this might very well be something related to our specific instance.  The current warnings make me quite uneasy, I'm considering rolling back but I'm unsure if that's possible or if I have to roll back to the last VM snapshot.

**Comment by MegaDrive68k** [comment]
Hi @BuJo,

This usually happens when you back to store your projects on the filesystem (for example from any previous configuration that saved your projects on databases before)  without renaming the `project.properties.imported`  (this is what happened to me on my tests and is expected behavior). Did you change anything on` rundeck-config.properties` file before upgrade to 3.3.0?

Can you share your `rundeck-config.properties` file content to take a look? (please hide/change any sensitive information).

Thanks!

**Comment by BuJo** [comment]
Thank you for looking at it.

```
-rw-r-----. 1 rundeck rundeck 813  6. Dez 2018  /etc/rundeck/rundeck-config.properties
```

The installation is from 2017, the change in 2018 was to add the api-token duration.

```
#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/var/lib/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
# change hostname here
grails.serverURL=https://rundeck.example.com
dataSource.dbCreate = update
dataSource.url = jdbc:mysql://localhost/rundeck?autoReconnect=true
dataSource.username=rundeck
dataSource.password=X
dataSource.driverClassName=com.mysql.jdbc.Driver
rundeck.log4j.config.file = /etc/rundeck/log4j.properties
grails.mail.host=smtp.example.com
grails.mail.port=25

rundeck.storage.provider.1.type = file
rundeck.storage.provider.1.config.baseDir = /var/lib/rundeck/var/storage
rundeck.storage.provider.1.path = /
rundeck.api.tokens.duration.max = 0
```

I'm unsure about having projects on disk versus in the database, I'm not sure we ever made a conscious decision on that.

**Comment by BuJo** [comment]
Oh, and due to the linked ticket I now see that the files have automatically been renamed to .imported again.  I haven't tried restarting Rundeck since, but that makes me nervous as well, maybe the projects will be missing again after that..

**Comment by MegaDrive68k** [comment]
Hi @BuJo 

Specify the location of your projects with `rundeck.projectsStorageType=filesystem` on your `rundeck-config.properties` file.

So, stop your rundeck instance, on your `rundeck-config.properties` file add  this line: `rundeck.projectsStorageType=filesystem`, rename the `project.properties.imported `to `project.properties`, and relaunch Rundeck. That worked in my environment :-)

Take a look at this:

https://docs.rundeck.com/docs/administration/projects/configuration.html#storage-types

**Comment by BuJo** [comment]
That sounds like that should fix it and eases my worries.

It does not seem to have changed with 3.3, the document seems to suggest 2.11.  Not having read the commits/source I cannot tell what change in 3.3 actually resulted in this behaviour.  Is this something that more people will fall into, or is our project simply the odd one?  If the former, perhaps the 3.3 changelog could warn about it.

**Comment by BuJo** [comment]
Let's close the issue, nobody else seems to have run into the problem.
