### ISSUE TITLE
pass parameter job reference

### ISSUE THREAD

**Issue by ext94053** [rundeck/rundeck#6221]
**Describe the bug**

I want to pass as a parameter a variable introduced as an option in the main job that will later be used in another job passed as a job reference in the main job

**My Rundeck detail**

* Rundeck version: [ e.g. 3.2.8]
* install type: [choose: war]
* OS Name/version: [e.g. Red hat Linux 5]
* DB Type/version: [N/A ]

**To Reproduce**
1. Job A with a option.name = fecha
2. In job A create a global variable with option.name = fecha
3. I create in workflow job A, an job reference to job B with parameter ${export.fecha}
4. In job B I need to recover the value ${export.fecha}
5. I can't get the value to appear in the job execution (job reference B in A)

**Expected behavior**

retrieve the value of the variable

Thanks a lot!!

**Comment by MegaDrive68k** [comment]
Hi @ext94053 

The easiest way to do that is passing the option/data/export value as an argument to Job B (Child job). I leave a working example:

Job A (Parent Job, check carefully the job reference step):

```xml
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='fecha' value='11/01/1990'>
          <dateFormat>DD/MM/YYYY</dateFormat>
          <isDate>true</isDate>
        </option>
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>f91568bd-0c6e-4b43-b234-2dd829f91a44</id>
    <loglevel>INFO</loglevel>
    <name>JobA</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "Parent job date: ${option.fecha}"</exec>
      </command>
      <command>
        <jobref name='JobB' nodeStep='true'>
          <arg line='-childdate ${option.fecha}' />
          <uuid>159d8067-d2b3-49e0-99cf-74498f04fcfc</uuid>
        </jobref>
      </command>
    </sequence>
    <uuid>f91568bd-0c6e-4b43-b234-2dd829f91a44</uuid>
  </job>
</joblist>
```

Job B (Child Job):

```xml
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='childdate' value='10/10/2019'>
          <dateFormat>DD/MM/YYYY</dateFormat>
          <isDate>true</isDate>
        </option>
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>159d8067-d2b3-49e0-99cf-74498f04fcfc</id>
    <loglevel>INFO</loglevel>
    <name>JobB</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "Child job date: ${option.childdate}"</exec>
      </command>
    </sequence>
    <uuid>159d8067-d2b3-49e0-99cf-74498f04fcfc</uuid>
  </job>
</joblist>
```

Greetings!

**Comment by ext94053** [comment]
Its works!!!

Thanks a lot

**Comment by ext94053** [comment]
The easiest way to do that is passing the option/data/export value as an argument to Job B (Child job). I leave a working example:

Job A (Parent Job, check carefully the job reference step):

<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='fecha' value='11/01/1990'>
          <dateFormat>DD/MM/YYYY</dateFormat>
          <isDate>true</isDate>
        </option>
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>f91568bd-0c6e-4b43-b234-2dd829f91a44</id>
    <loglevel>INFO</loglevel>
    <name>JobA</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "Parent job date: ${option.fecha}"</exec>
      </command>
      <command>
        <jobref name='JobB' nodeStep='true'>
          <arg line='-childdate ${option.fecha}' />
          <uuid>159d8067-d2b3-49e0-99cf-74498f04fcfc</uuid>
        </jobref>
      </command>
    </sequence>
    <uuid>f91568bd-0c6e-4b43-b234-2dd829f91a44</uuid>
  </job>
</joblist>
Job B (Child Job):

<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='childdate' value='10/10/2019'>
          <dateFormat>DD/MM/YYYY</dateFormat>
          <isDate>true</isDate>
        </option>
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>159d8067-d2b3-49e0-99cf-74498f04fcfc</id>
    <loglevel>INFO</loglevel>
    <name>JobB</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "Child job date: ${option.childdate}"</exec>
      </command>
    </sequence>
    <uuid>159d8067-d2b3-49e0-99cf-74498f04fcfc</uuid>
  </job>
</joblist>
