### ISSUE TITLE
Starting Rundeck with a JDK 11+ runtime reports Illegal reflective access errors

### ISSUE THREAD

**Issue by sjrd218** [rundeck/rundeck#6225]
When Rundeck is started on a JVM that supports the Java module system an error similar to the following will be written to the startup log.

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedConstructor$1 (jar:file:/C:/Users/stephen/rdktst/rundeck-3.3.1-SNAPSHOT.war!/WEB-INF/lib/groovy-2.5.6.jar!/) to constructor java.nio.file.attribute.PosixFilePermission(java.lang.String,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedConstructor$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

Desired behavior: No illegal reflective access messages written to the logs

**Comment by MegaDrive68k** [comment]
Happening on 3.3.2-RC2.

![Screenshot_1](https://user-images.githubusercontent.com/51376003/90416306-4e298100-e080-11ea-92ab-6c764260c26d.png)

**Comment by Timoses** [comment]
We see this as well:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedConstructor$1 (jar:file:/home/rundeck/rundeck.war!/WEB-INF/lib/groovy-2.5.6.jar!/) to constructor sun.nio.ch.FileChannelImpl(java.io.FileDescriptor,java.lang.String,boolean,boolean,boolean,java.lang.Object)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedConstructor$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```


Using rundeck container image 3.4.2 .

**Comment by Kenny-JTK** [comment]
`
WARNING: All illegal access operations will be denied in a future release

WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedConstructor$1

WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedConstructor$1 (jar:file:/home/rundeck/rundeck.war!/WEB-INF/lib/groovy-2.5.6.jar!/) to constructor sun.nio.ch.FileChannelImpl(java.io.FileDescriptor,java.lang.String,boolean,boolean,boolean,java.lang.Object)

WARNING: An illegal reflective access operation has occurred
`
Can confirm this behavior in container 3.4.5

**Comment by nublaii** [comment]
`Grails application running at http://localhost:4440 in environment: production
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedConstructor$1 (jar:file:/var/lib/rundeck/bootstrap/rundeck-3.4.6-20211110.war!/WEB-INF/lib/groovy-2.5.6.jar!/) to constructor sun.util.calendar.ZoneInfo(java.lang.String,int)
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedConstructor$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release`
Still there with DEB install on ubuntu 20.04 with version 3.4.6

**Comment by dla-meyer** [comment]
Still seeing this on RD 4.11.0, when trying to invoke https://github.com/rundeck/plugin-bootstrap

JVM
openjdk 11.0.17 2022-10-18
OpenJDK Runtime Environment (build 11.0.17+0-suse-150000.3.86.2-x8664)
OpenJDK 64-Bit Server VM (build 11.0.17+0-suse-150000.3.86.2-x8664, mixed mode)

OS
ARCH : amd64
NAME : Linux
VERSION : 5.3.18-150300.59.106-default
SUSE Linux Enterprise Server 15 SP3

<pre>
user@host:~> rundeck-plugin-bootstrap -V
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/var/lib/rundeck-pb/rundeck-plugin-bootstrap-shadow-0.4.9/lib/rundeck-plugin-bootstrap-0.4.9-all.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
1.1
user@host:~> 
</pre>
