### ISSUE TITLE
Rundeck 3.3.0 node filter broken in Firefox

### ISSUE THREAD

**Issue by Ziemowit-LH** [rundeck/rundeck#6230]
**Describe the bug**
Nodes query in Project -> Commands broken after upgrade from 3.2.8 to Rundeck 3.3.0
"**An Error Occurred**
Error processing GroovyPageView: getAuthContextForSubjectAndProject: Cannot get AuthContext without project"
Happens in Firefox, but not in Chrome.

**My Rundeck detail**
* Rundeck version: 3.3.0
* install type: war
* OS Name/version: Windows Server 2012 R2, Windows 10 1909
* DB Type/version: none/builtin

**To Reproduce**
Install fresh Rundeck 3.3.0, war release..
Create first project.
Click "Commands", then "Filter" -> "Show all nodes"

**Expected behavior**
Should show all nodes, does not.

**Screenshots**
Directly after entering Commands:
![commands1-beforeFilter](https://user-images.githubusercontent.com/68000627/86903371-88ae0e80-c10f-11ea-9007-92bcbfc3f209.gif)
After choosing Filter -> Show all nodes:
![commands2-afterFilter-showAll](https://user-images.githubusercontent.com/68000627/86903375-8a77d200-c10f-11ea-9911-914eff3ed614.gif)
ZIP archive with logs from server/logs and var/logs:
[logs4 onclick show all nodes.zip](https://github.com/rundeck/rundeck/files/4889857/logs4.onclick.show.all.nodes.zip)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 68.9.0esr (64-bit)

**Additional context**

**Comment by MegaDrive68k** [comment]
Confirmed,

Only happening with Firefox 68.9 ESR, I tested using Firefox 78.0.1 (Rundeck 3.3.0 + OpenJDK 11 on Windows Server 2019) and works well.

Thanks for your feedback @Ziemowit-LH
