### ISSUE TITLE
Rundeck 3.3.0 - log viewer broken in firefox

### ISSUE THREAD

**Issue by damienbertau** [rundeck/rundeck#6232]
**Describe the bug**
The execution log doesn't display well on firefox (ok for chrome) on a fresh install of rundeck 3.3.0

**My Rundeck detail**

* Rundeck version: 3.3.0
* install type: deb
* OS Name/version: debian 9/10
* DB Type/version: H2 (testing instance)
* openjdk-11-jdk

**To Reproduce**
1. Go to 'job execution' project/XXX/execution/show/1
2. Click on 'View/nodes/Log Excution'
3. Nothing happen

**Expected behavior**
A clickable Log Output button to display the log

**Screenshots**
![image](https://user-images.githubusercontent.com/48449139/86930088-e1dd6880-c136-11ea-935a-f6897f7e1539.png)

**Desktop (please complete the following information):**
 - OS: debian 9/10
 - Browser firefox
 - Version 68.10.0esr and 78.0.1

**Additional context**
Same job with chrome is ok
![image](https://user-images.githubusercontent.com/48449139/86931497-78f6f000-c138-11ea-9e3d-ae73b5f7070b.png)

Same behavior on a fresh install on local testing instance :
http://localhost:4440/project/XXX/execution/show/1#nodes

**Comment by MegaDrive68k** [comment]
Confirmed,

Happening with Firefox ESR, with 78.0.1 works normally.

Firefox 78.0.1:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/86947007-3540be00-c119-11ea-8ad5-fb499fc6f4de.png)

Firefox 68.10.0-ESR:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/86947013-3671eb00-c119-11ea-9aaf-3480670959f6.png)

Related: https://github.com/rundeck/rundeck/issues/6230

Thanks for your feedback @damienbertau!

**Comment by mazzella-c** [comment]
We have the same behaviour with Chrome 78, it's ok with version 83.

**Comment by ProTip** [comment]
Hi @mazzella-c ,

Out of curiosity(product dev research), what is your requirement for Chrome 78? Thanks!

**Comment by mazzella-c** [comment]
Some ugly legacy software company claimed everything was ok with that version so our users are stuck and it's even worse with Firefox which is in version 60.5 ESR for the same reason...

**Comment by damienbertau** [comment]
Thanks @ProTip , i confirm that it is fixed in 3.3.1
