### ISSUE TITLE
Project ACL's are gone after upgrading to v3.3

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6239]
All of our **project ACL** setting files are no longer visible from the UI. But the ACL from the settings are still in place. 

RUNDECK
APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.3.0-20200701
BUILDGIT : v3.3.0-0-g66e3ef7
SERVERUUID :
VERSION : 3.3.0-20200701

![image](https://user-images.githubusercontent.com/20629911/86970962-2c55e980-c125-11ea-981f-ae8a6b733fbe.png)

Thanks,
HS

**Comment by gschueler** [comment]
what was your previous version?

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world 

What browser (and version) are you using?

Regards.

**Comment by hs-hub-world** [comment]
@gschueler  previous version: 3.2.8
https://github.com/rundeck/rundeck/releases/tag/v3.2.8

@MegaDrive68k  Browser Google Chrome: Version 83.0.4103.116
![image](https://user-images.githubusercontent.com/20629911/86979609-9dea6380-c136-11ea-9000-91e9057193ec.png)

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world 

Testing this issue (upgrading from 3.2.8 to 3.3.0 on RPM/DEB using H2/MySQL) I can see Project ACLs on Rundeck 3.3.0, so, I  have more questions to reproduce the issue:

1) What kind of instance do you have? (repository RPM/DEB, single package RPM/DEB, WAR base installation, or Docker image).
2) What Operating System and version do you have?
3) Which upgrade process did you follow?
4) What Database backend and version do you use with Rundeck?
5) What JDK version are you using? (`java -version`)
6) Any clue at the `service.log` file at the moment of access to the Project ACL page?

Thanks!

**Comment by MegaDrive68k** [comment]
I get the same bug on WAR based installation. 

Steps to reproduce:

1) Run Rundeck 3.2.8 war file (`java -jar rundeck-3.2.8-20200608.war`).
2) Create a new project, go to Projects Settings > Access Control, and create a new Project ACL.
3) Stop Rundeck.
4) Upgrade WAR file with Rundeck 3.3.0 war and relaunch (`java -jar undeck-3.3.0-20200701.war`).
5) Select the project and go to Project Settings > Access Control.
6) ACL in the list is gone.

[output.txt](https://github.com/rundeck/rundeck/files/4897329/output.txt) (accessing on Project ACL page).

Reproduced on Ubuntu 20.04 and Windows Server 2019.

Thanks for your feedback @hs-hub-world!

**Comment by hs-hub-world** [comment]
I think I found the problem.
looks like before version 3.3.0 project ACL's were saved in the yaml file 

![image](https://user-images.githubusercontent.com/20629911/87056567-aa180480-c1ba-11ea-814e-68d5c9984ca8.png)


But now when I create new Project ACL with the same name:
- it does not complain aclpolicy file already exists
- it does not save any new aclpolicy to disk
- so it must mean that aclpolicy's are saved somewhere else/some other format -?

@MegaDrive68k  to answer some of your questions:
the server is: CentOS Linux release 7.5.1804 (Core)
openjdk version "1.8.0_252"
OpenJDK Runtime Environment (build 1.8.0_252-b09)
OpenJDK 64-Bit Server VM (build 25.252-b09, mixed mode)
We upgrade rundeck using yum: yum update rundeck -y

We are using:
[System Report.pdf](https://github.com/rundeck/rundeck/files/4897703/System.Report.pdf)
[Development Mode] Usage of H2 database 
Please see attached PDF for more details.

Thanks,
HS

**Comment by gschueler** [comment]
I think this is the problem: the default for "projectsStorageType" changed to "db" for rundeck 3.3.0, which means resources for project configuration like ACLs are stored in the DB now. There is a process to convert old filesystem based project config to the DB storage, however, the ACLs are not getting copied.
