### ISSUE TITLE
Authentication using LDAPS request ignores truststore configured in ssl.properies

### ISSUE THREAD

**Issue by genna1966** [rundeck/rundeck#6268]
**Describe the bug**
Authentication using LDAPS request ignores truststore configured in ssl.properies file and uses   /etc/pki/java/cacerts instead
 
**My Rundeck detail**

* Rundeck version: [3.2.8]
* install type: [rpm]
* OS Name/version: [Centos 7]
* DB Type/version: [h2]

**To Reproduce**
Configure RunDeck  to run with SSL as per doco.
Create jks  keystore/truststore  and define it in <RUNDECkHOME>/ssl/ssl.properteis 
Ensure Rundeck is running with SSL
Configure auth to use LDAPS as per Doco. Import AD certificate into truststore specified  in  ssl.properteis
Thes is from the doco:

> ... but the LoginModule describe above requires that the AD certificate or organizations CA certificate be placed in a truststore. The truststore provided with rundeck /etc/rundeck/ssl/truststore is used for the local communication between the cli tools and the rundeck server

.
"
Our ssl.properties file:
keystore=/etc/rundeck/ssl/amo1rfisorcas01.fnfis.com.jks
keystore.password=*******
key.password=********
truststore=/etc/rundeck/ssl/amo1rfisorcas01.fnfis.com.jks
truststore.password=******

AD certificates ( both server and root) are imported  into truststore
When trying to login via RunDeck web UI interface  getting this error in service.log:
"
 javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
"
After enabling ssl debug ( adding -Djavax.net.debug=ssl,handshake to command line) I'm seeing this in log 

_[2020-07-14 13:37:15.007] DEBUG GrailsUsernamePasswordAuthenticationFilter --- [qtp139374530-53] Request is to process authentication
Inaccessible trust store: /usr/lib/jvm/java-1.8.0-openjdk-1.8.0.252.b09-2.el7_8.x86_64/jre/lib/security/jssecacerts
**trustStore is: /etc/pki/java/cacerts**
trustStore type is: jks_

Indicating that  default java truststore is used.  

This is very undesirable  since we have to re-import  certs every time java is patched 

**Expected behavior**
A truststore defined in ssl.properties to be used for LDAPS communication 

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @genna1966 

By default, Rundeck uses the Java cacert, to take the truststore you need to define at launch using `-Djavax.net.ssl.trustStore=/path/to/your/truststore` on your `rundeckd`file. Can you test adding that on your `/etc/sysconfig/rundeckd` file like this:

```
RDECK_JVM_OPTS="-Drundeck.jaaslogin=true \
       -Djava.security.auth.login.config=/etc/rundeck/jaas-ldap.conf \
       -Dloginmodule.name=ldap
       -Djavax.net.ssl.trustStore=/path/to/truststore"
```

More info here: https://docs.rundeck.com/docs/administration/configuration/system-properties.html#rpm-and-deb

Hope it helps!
