### ISSUE TITLE
Update httpclient library to support SNI (SSL for name-based virtual hosts)

### ISSUE THREAD

**Issue by dtreskunov** [rundeck/rundeck#627]
I'm using Apache as reverse SSL proxy for Rundeck, and I run several services on the same IP and port. Using SSL is possible via SNI (Server Name Information extension). But `commons-httpclient/commons-httpclient/3.0.1` which is used by Rundeck doesn't support SNI, which makes client code such as `rd-jobs` get SSL errors.

SNI support was recently (https://issues.apache.org/jira/browse/HTTPCLIENT-1119) added to the httpcomponents client. Would you consider migrating to `org.apache.httpcomponents/httpclient/4.3.2`?

Thanks.

**Comment by ahonor** [comment]
`rd-jobs` is obsolete
