### ISSUE TITLE
Entering rundeck in https does not show the nodes available. While in http it works

### ISSUE THREAD

**Issue by mezamoe** [rundeck/rundeck#6270]
**Describe the bug**
When entering rundeck using https protocol and clicking on Nodes (on the menu on the left) no nodes are shown

**My Rundeck detail**

* Rundeck version: [ 3.2.8]
* install type: [latest container/Docker Compose]
* DB Type/version: [choose: mysql]

**To Reproduce**
1. Login to rundeck using https
2. Click on 'Nodes'

**Expected behavior**
Access rundeck using http and by clicking on Nodes you will see the list of nodes

**Screenshots**

**Desktop (please complete the following information):**
 - Browser [any browser]

**Additional context**
this is with https
![image](https://user-images.githubusercontent.com/32204156/87433829-1004f180-c5ea-11ea-8773-fdf74e834eef.png)

and this with http
![image](https://user-images.githubusercontent.com/32204156/87434158-67a35d00-c5ea-11ea-8749-4220a65c0ba9.png)

**Comment by MegaDrive68k** [comment]
Hi @mezamoe 

If you are using some proxy/exit in front of Rundeck make sure that the `RUNDECK_GRAILS_URL` parameter is pointing to proxy/webserver Rundeck exit. Also, you can test this Docker project to test: https://github.com/rundeck/rundeck/issues/6242#issuecomment-656257705 (i used the same but using Rundeck 3.2.8 to test):

![Screenshot_1](https://user-images.githubusercontent.com/51376003/87479641-d6d47d80-c5f9-11ea-972c-fb1386204502.png)

You can check more about Rundeck official Docker image here: https://hub.docker.com/r/rundeck/rundeck

Regards!

**Comment by mezamoe** [comment]
yes, I do have a proxy.. I'll do that and let you know

**Comment by mezamoe** [comment]
I found out that the proxy is a container httpd on the same server, so address is the same

**Comment by mezamoe** [comment]
the proxy is a httpd container on same server, so not the problem. I used the script published in that https://github.com/rundeck/rundeck/issues/6242 and that fixed it. Many thanks
