### ISSUE TITLE
Node source list empty in UI

### ISSUE THREAD

**Issue by mifiki** [rundeck/rundeck#6278]
**Describe the bug**
Node source list empty in UI

**My Rundeck detail**

* Rundeck version: 3.3.0-20200701
* install type: deb
* OS Name/version: ubuntu 18.04

**To Reproduce**
1. Install fresh Rundeck 3.3.0 on Ubuntu 18.04 as per official guide
2. Create a project
3. Click on "Project settings -> Edit Nodes...", choose "Sources"
4. See the empty list (on screenshot)

**Expected behavior**
We should see a list of node sources

**Screenshots**
![image](https://user-images.githubusercontent.com/4659992/87620718-f36ed380-c727-11ea-8a9c-6c76f5055008.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 83

**Comment by MegaDrive68k** [comment]
Hi @mifiki 

Make sure that `grails.serverURL` (`rundeck-config.properties` file, usually at` /etc/rundeck` path) is pointing to proxy/webserver rundeck exit URL, check this thread: 

https://groups.google.com/g/rundeck-discuss/c/I94cVxK_6kQ

And this. https://github.com/rundeck/rundeck/issues/5087

Regards!

**Comment by mifiki** [comment]
> Hi @mifiki
> 
> Make sure that `grails.serverURL` (`rundeck-config.properties` file, usually at` /etc/rundeck` path) is pointing to proxy/webserver rundeck exit URL, check this thread:
> 
> https://groups.google.com/g/rundeck-discuss/c/I94cVxK_6kQ
> 
> And this. #5087
> 
> Regards!

Thank you for you answer.
Rundeck was running behind nginx, and `grails.serverURL` was set to localhost. Problem was solved after setting it to external domain name.

Thanks again for helping, I would just like to mention that this issue appears to be very common (after some internet search) and the solutions is not obvious at all. Probably this needs to be fixed in default installation - as other Rundeck features work out of box, this also should.
