### ISSUE TITLE
rundeck opensource repo size mismatch due to package mistakenly being in folder

### ISSUE THREAD

**Issue by jakegroves** [rundeck/rundeck#6282]
Issue type: Bug

**My Rundeck detail**

* Rundeck version: Not installed yet
* install type: deb
* OS Name/version: Debian Stretch
* DB Type/version: postgres

**Expected Behavior**
Able to mirror repo `deb https://rundeck.bintray.com/rundeck-deb /`

**How to Reproduce**
Use a mirror management tool such as aptly
create mirror

```
aptly mirror create -architectures="amd64" -with-sources=false sw-rundeck-opensource-debian https://rundeck.bintray.com/rundeck-deb /
aptly mirror update -ignore-signatures sw-rundeck-opensource-debian
Downloading https://rundeck.bintray.com/rundeck-deb//Release...
Downloading & parsing package files...
Downloading https://rundeck.bintray.com/rundeck-deb//Packages.bz2...
Building download queue...
Download queue: 1 items (58.58 MiB)
Downloading https://rundeck.bintray.com/rundeck-deb/rundeck-2.0.4-1-GA.deb...
ERROR: unable to update: download errors:
  https://rundeck.bintray.com/rundeck-deb/rundeck-2.0.4-1-GA.deb: size check mismatch 279 != 61428996

```

The problem is the package is in a folder when it should not be. rundeck version 2.0.4-1 is the only package in a folder of the same name so softwares will download the folder and get size mismatch.
The package needs re-adding to the mirror correctly

**Comment by mxey** [comment]
@gschueler Any update on this?
