### ISSUE TITLE
Running a command with "space delimited" multi-valued attributes fails.

### ISSUE THREAD

**Issue by agarwalpranab** [rundeck/rundeck#6287]
**Describe the bug**
I was working on some command execution and used "space delimited" multi-valued attributes for the purpose. This was failing. After that I created a test job.

`ls -l <space delimited multivalued attributes>`

This fails with the error too. I tried running this command on the command line just to be sure that it works.

`ls -l /var /usr` and this worked without issues.

**My Rundeck detail**
* Rundeck version: 3.3.0
* install type: docker
* OS Name/version: N/A
* DB Type/version: Internal

**To Reproduce**
1. Create a multi-valued option (space delimited) to take in path parameters
2. Create a job to execute the command ls -l and pass the option attribute created above.
3. Set it to execute on local server
4. Save
5. Execute the job
6. Pass /var and /usr as 2 parameters
7. See the error.

**Expected behavior**
The command should list files/directories for both /var and /usr

**Screenshots**
Error in UI
![RundeckError](https://user-images.githubusercontent.com/19178503/87891934-f860b980-ca7e-11ea-8512-f9aff6759bd0.png)

Running the same command in terminal
![RunningCommandFromCommandLine](https://user-images.githubusercontent.com/19178503/87891956-0a425c80-ca7f-11ea-9d5c-c6ec29d6b6d8.png)

**Desktop (please complete the following information):**
 - OS: MacBook
 - Browser Firefox
 - Version 78.0.2

**Additional context**
NOTE: The same job works correctly if only 1 attribute is set like `/var` in the UI.

Error Message:
```
ls: cannot access '/ /var': No such file or directory
Result: 2
Failed: NonZeroResultCode: Result code was 2
Execution failed: 3 in project QRoC_Operations: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [3bb5459ee224: NonZeroResultCode: Result code was 2 + {dataContext=MultiDataContextImpl(map={ContextView(node:3bb5459ee224)=BaseDataContext{{exec={exitCode=2}}}, ContextView(step:1, node:3bb5459ee224)=BaseDataContext{{exec={exitCode=2}}}}, base=null)} ]}, Node failures: {3bb5459ee224=[NonZeroResultCode: Result code was 2 + {dataContext=MultiDataContextImpl(map={ContextView(node:3bb5459ee224)=BaseDataContext{{exec={exitCode=2}}}, ContextView(step:1, node:3bb5459ee224)=BaseDataContext{{exec={exitCode=2}}}}, base=null)} ]}, status: failed]
```

**Comment by MegaDrive68k** [comment]
Hi @agarwalpranab 

Reproduced on command step.

It works using inline-script step, take a look at this job definition:

```
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option delimiter=' ' multivalued='true' name='directories' />
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>e1e2b1d6-f7f7-41d9-afa8-c61bcabef85b</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <fileExtension>.sh</fileExtension>
        <script><![CDATA[ls @option.directories@]]></script>
        <scriptargs />
        <scriptinterpreter>/bin/bash</scriptinterpreter>
      </command>
    </sequence>
    <uuid>e1e2b1d6-f7f7-41d9-afa8-c61bcabef85b</uuid>
  </job>
</joblist>
```

![Screenshot_1](https://user-images.githubusercontent.com/51376003/87946903-a0bb5180-ca70-11ea-860f-5e03769dcf26.png)

Hope it helps!

**Comment by agarwalpranab** [comment]
Hi @MegaDrive68k 

Thank you for your prompt response. Really appreciate it.

Is the method you suggested an official response for rundeck?

I was aware of the workaround that you proposed as I had read about it in user forum. I am trying to proceed with that method. But I was expecting that this is fixed for a regular command itself. This is something that will be coming up often and I believe there should be a fix for this.

If this is not a supported method, this should be listed in the documents, when discussing about the "Multi-valued" attributes and the work around should be made available in the docs.

This helps in readily ingesting the solution as-is rather than trying and failing and trying to figure out why it happened.

My two cents.

Thank you.

Regard
Pranab
