### ISSUE TITLE
Rundeck SSL Enabled Container

### ISSUE THREAD

**Issue by john77eipe** [rundeck/rundeck#6289]
**Rundeck Admin Console not accessible**

Unable to get SSL enabled Rundeck instance up and running. Vising https://0.0.0.0:4443 returns unable to connect.

**My Rundeck detail**

* Rundeck version: 3.2.1
* install type: docker container
* OS Name/version: default
* DB Type/version: default

**To Reproduce**
1. Run using Official Docker but setting SSL to be true
`
docker run --name rundeck-test -v data:/home/rundeck/server/data -p 4440:4443 -e RUNDECK_WITH_SSL=true -e SERVER_URL=https://0.0.0.0:4443 -e DEFAULT_ADMIN_USER=admin -e DEFAULT_ADMIN_PASSWORD=password -d rundeck/rundeck:3.2.1
`
2. Visit URL https://0.0.0.0:4443 on your browser 

**Expected behavior**
Admin dashboard should load without issues

**Desktop (please complete the following information):**
 - OS:Mac
 - Browser: Firefox

**Comment by MegaDrive68k** [comment]
Hi @john77eipe 

Take a look at this: https://github.com/rundeck/rundeck/issues/6242#issuecomment-656257705

Regards!

**Comment by john77eipe** [comment]
Thanks a ton @MegaDrive68k
