### ISSUE TITLE
Global Variable not working when single node exeuction fails...

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6290]
_(I know you will have many questions around this problem so let this be the initial post and I'll address the questions as they come)._

I am not sure if this is the correct behavior of Rundeck, but when a single node execution fails none of the other "successful" node executing "Global Variables" is set and passed to the caller job when using collated values (i.e. ${data.keyvalue*})

![image](https://user-images.githubusercontent.com/20629911/87899531-57361c80-ca06-11ea-84bc-c82080bb68d9.png)

Job-1 workflow first step captures key value "fileinfo"
![image](https://user-images.githubusercontent.com/20629911/87898689-be060680-ca03-11ea-8591-1f6f258a7bce.png)

Then Job-1 workflow Step-2 exports the captured value into global variable group "export"
![image](https://user-images.githubusercontent.com/20629911/87898500-26081d00-ca03-11ea-8378-d2c97c5ae0c7.png)

Up to this point, everything works fine. 

Problem:
if any of the node executions fail the Global Variable with collated value is empty in Job-1

![image](https://user-images.githubusercontent.com/20629911/87899489-35d53080-ca06-11ea-90bd-c97879737429.png)

So, with that said, I wish the run Again had an option to Retry Successful Nodes as an option:
Plus we don't have a way to exclude failed nodes from the reference step. 
![image](https://user-images.githubusercontent.com/20629911/87899421-fd355700-ca05-11ea-99d5-85001b41378a.png)

RUNDECK
APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.3.0-20200701
BUILDGIT : v3.3.0-0-g66e3ef7
SERVERUUID :
VERSION : 3.3.0-20200701

**Comment by fuwj1994** [comment]
Rundeck Version : 3.3.0-20200701

I also have the same issue, now my emails received are both like this:
![image](https://user-images.githubusercontent.com/11691787/89302603-9d91a980-d69d-11ea-89ff-e67b0f035871.png)
