### ISSUE TITLE
Empty option text field keeps reverting back to default value, is empty value possible -?

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6293]
Option text field when removing default value trying to submit empty value it keeps reverting back to the default value.

![image](https://user-images.githubusercontent.com/20629911/88085768-2b688300-cb3b-11ea-8236-73cb904c267f.png)

![image](https://user-images.githubusercontent.com/20629911/88085919-62d72f80-cb3b-11ea-827c-3d2ad405ace7.png)

![image](https://user-images.githubusercontent.com/20629911/88086014-8601df00-cb3b-11ea-9907-ed6b173d9e9f.png)

APIVERSION : 35
BASE : /var/lib/rundeck
BUILD : 3.3.0-20200701
BUILDGIT : v3.3.0-0-g66e3ef7
SERVERUUID :
VERSION : 3.3.0-20200701

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world 

Good catch, I see the same behavior, even on 3.3.1-SNAPSHOT.

Regards!
