### ISSUE TITLE
Updating a JOB Crontab Schedule doesn't save new value

### ISSUE THREAD

**Issue by ruiplcorreia** [rundeck/rundeck#6304]
**Description:**
Cannot update schedule on the Jobs/deployments, editing an existing job after the update and changing only the year on the crontab doesn't keep the new time.

**Rundeck Details:**

* Rundeck version: 3.3.0
* install type: war
* OS Name/version: SUSE Linux Enterprise Server 12 SP5
* DB Type/version: postgres

**To Reproduce**
1. Go to Jobs -> Deployments
2. Click on the Job to edit and pick the Schedule tab
3. Change the Crontab value (in this case just the year) and save
4. New value is only kept the first time, if you edit a second time it does not keep the value.

**Expected behavior**
The new schedule should be always kept on the crontab field.

**Screenshots**
![image](https://user-images.githubusercontent.com/68696199/88295906-ee94bb80-ccf5-11ea-8b22-6cb3185d5f31.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 84.0.4147.89 (Official Build) (64-bit)

**Comment by booshlinux** [comment]
Can confirm, the time remaining icon also reflects previous values set
![Screenshot_2020-07-23_08-50-24](https://user-images.githubusercontent.com/33703686/88301262-a65ba600-ccc1-11ea-8e66-9b4ef6ddb15e.png)

This job was originally set to run every 24 hours. I have changed it to run every 15 minutes, which through the job history I can confirm that it is indeed ran every 15 minutes. The screenshot above displays the old time.

**Comment by MegaDrive68k** [comment]
Hi @ruiplcorreia and @booshlinux 

Your 3.3.0 instance is upgraded from another old instance? In that case, which version?

Regards!

**Comment by ruiplcorreia** [comment]
Hi @MegaDrive68k,

Upgraded instance from version 3.2.8.

Regards

**Comment by booshlinux** [comment]
I upgraded from 3.2.6.

Thanks @MegaDrive68k

**Comment by MegaDrive68k** [comment]
I reproduced but in this way:

1) Create a scheduled job with a single schedule:
![Screenshot_1](https://user-images.githubusercontent.com/51376003/88318183-5e03ae80-cce8-11ea-9d95-2187a1d0b899.png)

2) The job is scheduled normally:
![Screenshot_2](https://user-images.githubusercontent.com/51376003/88318204-652abc80-cce8-11ea-979d-2216f7ec2f69.png)

3) Edit the job:
![Screenshot_3](https://user-images.githubusercontent.com/51376003/88318213-678d1680-cce8-11ea-90e5-82061aef06e6.png)

4) The job doesn't change the scheduled time:
![Screenshot_4](https://user-images.githubusercontent.com/51376003/88318241-6d82f780-cce8-11ea-854e-3a626ac97c50.png)

**Comment by booshlinux** [comment]
That describes the bug I'm seeing perfectly.

**Comment by ruiplcorreia** [comment]
Any planned release to deliver this fix?

**Comment by gschueler** [comment]
I'm unable to reproduce this using 3.3.3 release @MegaDrive68k

**Comment by MegaDrive68k** [comment]
Hi @gschueler 

The issue occurs when you use job definitions from Rundeck 3.0/3.1/3.2 ([check](https://github.com/rundeck/rundeck/issues/6304#issuecomment-663135922) the "NOTE 1").

I tested with the following job dfinition (from Rundeck 3.0.X) under 3.3.3 release and the issue persist:

```xml
<joblist>
  <job>
    <defaultTab>summary</defaultTab>
    <description>Regex and data passing demo.</description>
    <executionEnabled>true</executionEnabled>
    <id>a0daf1e3-e918-43dc-b232-bc46a7a287b6</id>
    <loglevel>INFO</loglevel>
    <name>Regex</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>env</exec>
      </command>
      <command>
        <exec>echo ${data.SHELL}</exec>
      </command>
      <command>
        <exec>echo ${data.USER}</exec>
      </command>
      <command>
        <exec>echo ${data.PWD}</exec>
      </command>
      <pluginConfig>
        <LogFilter type='key-value-data'>
          <config>
            <logData>true</logData>
            <regex>^(SHELL|USER|PWD)\s*=\s*(.+)$</regex>
          </config>
        </LogFilter>
      </pluginConfig>
    </sequence>
    <uuid>a0daf1e3-e918-43dc-b232-bc46a7a287b6</uuid>
  </job>
</joblist>
```

If you set "simple schedule" and save, re-edit the job to switch to "crontab schedule" and save again, the job keeps with the first save ("simple schedule").
