### ISSUE TITLE
Log output stuck at 0% on successful execution

### ISSUE THREAD

**Issue by lennyxc** [rundeck/rundeck#6309]
**Describe the bug**
Upon successful execution of the job, the log output view is stuck at 0%. Viewing Execution Log -> View text or View HTML works however.
![stuckat0](https://user-images.githubusercontent.com/4071776/88351082-2fef9000-cd23-11ea-93ea-9dc3766b32fb.PNG)

**My Rundeck detail**

* Rundeck version: 3.3.0
* install type: deb
* OS Name/version: debian 10
* DB Type/version: H2

**To Reproduce**
1. Run a job that has a default tab of Log Output
2. Jub succeed but log output stuck at 0%

**Expected behavior**
Expecting a log output of lines instead of stuck at 0%.

**Screenshots**
See screenshot above

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84.0.4147.89

**Comment by MegaDrive68k** [comment]
Hi @lennyxc 

I'm trying to reproduce your issue. Can you try clearing all browser data and launch the job again? (or test on another browser without any plugin).

Also, can you provide some basic job that keeps that execution on 0%?

Thanks!

**Comment by ProTip** [comment]
Hi @lennyxc ,

Could you also check the developer console for any errors that might be in there? That would be a huge help.

Thanks!

**Comment by lennyxc** [comment]
Hi @MegaDrive68k and @ProTip ,

I ran a few variations with your request, think indeed a resource is not loading but unsure as to why. Here's the list of errors

For the chrome version listed in issue (note this is after running the job successfully, but errors appear on any page, eg: project home, all job listing, job, job output):
![chrome](https://user-images.githubusercontent.com/4071776/88443509-9689b200-cde6-11ea-9fc6-3d413b5b5d09.PNG)


For a fresh installation of latest firefox (same pages/flow as above in chrome test):
![firefox](https://user-images.githubusercontent.com/4071776/88443250-8cb37f00-cde5-11ea-8793-afa3910dac4a.PNG)

For IE 11.9* (stuck on projects view):
![ie11 9](https://user-images.githubusercontent.com/4071776/88443337-e1ef9080-cde5-11ea-91df-105f1243668b.PNG)


Basic Job definition: grep of a log file

Some properties that may be relevant for this issue:
_framework.properties_
framework.server.name = sub.domain.com
framework.server.hostname = sub.domain.com
framework.server.port = 4440
framework.server.url = http://sub.domain.com:4440

_rundeck-config.properties_
grails.serverURL=http://sub.domain.com:4440
dataSource.dbCreate = update
dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true

**Comment by MegaDrive68k** [comment]
Hi @lennyxc 

Can you test setting the `grails.serverURL` parameter with the proxy rundeck exit URL? Seems that you're facing this: https://github.com/rundeck/rundeck/issues/6278 or this: https://github.com/rundeck/rundeck/issues/6270

Regards.

**Comment by lennyxc** [comment]
Thanks for helping me navigate @MegaDrive68k,

I solved this issue with one change in nginx: 

Changed from proxy_pass http://sub.domain.com:4440/; to proxy_pass http://localhost:4440/;

Hopefully this helps others!
