### ISSUE TITLE
Git import triggers an error on service.log

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/rundeck#6310]
## Describe the bug
Git import triggers an error on service.log. The job is imported correctly, this is a message on the service.log only.

## My Rundeck detail

* Rundeck version: 3.3.1 SNAPSHOT
* install type: WAR
* OS Name/version: CentOS 7
* DB Type/version: H2

## To Reproduce
1. Configure SCM Import and Export to the same repo
2. Upload this job in the repo
[ExampleJob.xml.txt](https://github.com/rundeck/rundeck/files/4974420/ExampleJob.xml.txt)
3. Import the new changes from Rundeck
4. See error on service.log only

## Expected behavior
Don't see the error

## Screenshots
![2020-07-24_18h05_26](https://user-images.githubusercontent.com/11720535/88439337-f1b4a800-cdd8-11ea-9f08-8fe786294109.png)
```
[2020-07-24T18:04:21,331] ERROR events.EventSubscriberTrigger - Error triggering event [jobChanged] for subscriber [grails.events.subscriber.MethodSubscriber(public java.lang.Object rundeck.services.JobEventsService.jobChanged(rundeck.services.StoredJobChangeEvent))]: Active Connection is required
java.lang.IllegalArgumentException: Active Connection is required
```
[service.log](https://github.com/rundeck/rundeck/files/4974425/service.log)

## Desktop (please complete the following information):
 - OS: Windows 10 build 1909
 - Browser: Opera GX
 - Version: LVL2 (core: 68.0.3618.206)

**Comment by gschueler** [comment]
this actually fails to serialize the job changes for scm
