### ISSUE TITLE
Rundeck Job Replication plugin not pushing changes to remote Rundeck

### ISSUE THREAD

**Issue by G3NSVRV** [rundeck/rundeck#6311]
## Describe the bug
Rundeck Job Replication plugin not pulling changes to remote Rundeck. New Jobs can be pushed, deleted jobs are pushed automatically into the Remote Rundeck **but not modifications.**

## My Rundeck detail
* Rundeck version: 3.3.1 SNAPSHOT
* install type: WAR
* OS Name/version: CentOS 7
* DB Type/version: H2

## To Reproduce
1. Create Project on Rundeck A and create a dummy job
2. Create the same Project on Rundeck B
3. Create an API Token on the Rundeck B and configure the Rundeck A for Job Replication to Rundeck B with the API Token that was previously created
4. Push the Job to replicate it on Rundeck B
5. Modify the Job adding a new workflow Step
6. Check if Rundeck suggest new changes to be pushed, and check if the Job was automatically changed on the Rundeck B.

## Expected behavior
Push the changes.

## Screenshots
![2020-07-24_18h33_54](https://user-images.githubusercontent.com/11720535/88440556-532a4600-cddc-11ea-9f47-d94dd6089d0e.png)
![2020-07-24_18h34_04](https://user-images.githubusercontent.com/11720535/88440557-54f40980-cddc-11ea-9f4c-d43f92fe9613.png)
![2020-07-24_18h34_20](https://user-images.githubusercontent.com/11720535/88440560-56253680-cddc-11ea-92dd-78fb3d5fda50.png)

## Desktop (please complete the following information):
 - OS: Windows 10 build 1909
 - Browser: Opera GX
 - Version: LVL2 (core: 68.0.3618.206)

**Comment by fdevans** [comment]
Please retest this on 3.3.2 after SCM fixes in that release

**Comment by fdevans** [comment]
Moved to rundeckpro repository
