### ISSUE TITLE
Blank page appears when opening project

### ISSUE THREAD

**Issue by kazumasa-kusaba** [rundeck/rundeck#6313]
**Describe the bug**
Project details are not loaded in Dashboard page. And when I open the project page, a blank page appears.

**My Rundeck detail**

* Rundeck version: 3.2.7
* install type: deb
* OS Name/version: Ubuntu 18.04 LTS
* DB Type/version: H2

**To Reproduce**
1. Log in
2. See error (I can see details of the project that will never finish loading)
3. Choose some project
4. See error (a blank space appears)

**Screenshots**
<img width="908" alt="image" src="https://user-images.githubusercontent.com/17498982/88449264-6858b080-ce80-11ea-866f-a74d676038ff.png">

**Desktop (please complete the following information):**
 - OS: macOS Catalina 10.15.6
 - Safari 13.1.2

**Additional context**
* I checked the config files, but I couldn't solve this problem.
* Reinstalling Rundeck was the only solution.
* The setting of the reverse proxy with Nginx may have been related.

**Comment by MegaDrive68k** [comment]
Hi @kazumasa-kusaba 

Which java version are you using? You can check it with `java -version`.

Greetings.

**Comment by kazumasa-kusaba** [comment]
Hi @MegaDrive68k

I tried typing the command.
Below is the result.

>$ java -version
>openjdk version "11.0.8" 2020-07-14
>OpenJDK Runtime Environment (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1)
>OpenJDK 64-Bit Server VM (build 11.0.8+10-post-Ubuntu-0ubuntu118.04.1, mixed mode, sharing)
 
Greetings.

**Comment by MegaDrive68k** [comment]
Hi @kazumasa-kusaba 

Rundeck 3.2.X needs JDK 8 to run correctly. Rundeck 3.3.X supports JDK 8 and JDK 11.

Hope it helps!

**Comment by kazumasa-kusaba** [comment]
Hi @MegaDrive68k

Thank you for the useful information.

Now, my environment is difficult to change JDK version.

So, I'm using it as it is for a while.

Thank you!

**Comment by MegaDrive68k** [comment]
Hey @kazumasa-kusaba 

Then try upgrading your instance with Rundeck 3.3.0, that's Java 11 compatibe :-)

Regards!
