### ISSUE TITLE
feature/enhancement : optimization for Dockerfiles using debian package manager tweaks

### ISSUE THREAD

**Issue by Rajpratik71** [rundeck/rundeck#6315]
**Is your feature request related to a problem? Please describe.**
No . It is not related to problem . It is optimization tweak for docker images build using dockerfiles

**Describe the solution you'd like**

By default, Ubuntu or Debian based "apt" or "apt-get" system installs recommended but not suggested packages .

By passing "--no-install-recommends" option, the user lets apt-get know not to consider recommended packages as a dependency to install.

This results in smaller downloads and installation of packages .

Refer to blog at [Ubuntu Blog](https://ubuntu.com/blog/we-reduced-our-docker-images-by-60-with-no-install-recommends) .

**Comment by ProTip** [comment]
Hi @Rajpratik71 ,

Thanks for this.. We are aware of that option however without an analysis of size savings, as well as a list of packages that would get left out and what the impact would be on users if they "went missing" there wouldn't be much appetite for this change ATM.

A few of these are testing containers internal to project development as well.
