### ISSUE TITLE
Pages do not automatically transition after logging in with a smartphone

### ISSUE THREAD

**Issue by kazumasa-kusaba** [rundeck/rundeck#6317]
**Describe the bug**
Pages do not automatically transition after logging in with a smartphone.

**My Rundeck detail**

* Rundeck version: 3.2.7
* install type: deb
* OS Name/version: Ubuntu 18.04 LTS
* DB Type/version: H2
* Java Versinon: openjdk version "11.0.8" 2020-07-14

**To Reproduce**
1. Go to Login page with a smartphone
2. Enter ID and password
3. Press the'Log in' button
4. See error (Page does not transition)

**Screenshots**
![image_resize](https://user-images.githubusercontent.com/17498982/88470857-cb0f8200-cf3c-11ea-9d2e-98590be5259d.png)

**Smartphone (please complete the following information):**
 - OS: iOS 13.5.1 (iPhone 11)
 - Browser Safari 13.1.1 and Chrome 84.0.4147.71 (Both have the same result)

**Additional context**
* When I click the RUNDECK icon, the page will transition.
* I'm not sure if similar problems will occur on Android. (I don't have Android devices...)
* PC Brower (Safari and Chrome) does not cause same problems.

**Comment by MegaDrive68k** [comment]
Hi @kazumasa-kusaba 

Check this comment https://github.com/rundeck/rundeck/issues/6313#issuecomment-663937944

Regards!

**Comment by kazumasa-kusaba** [comment]
Hi @MegaDrive68k

Thank you for the useful information.

Please check this comment [#6313 (comment)](https://github.com/rundeck/rundeck/issues/6313)

Thank you!
