### ISSUE TITLE
No errors if using not valid project description after editing

### ISSUE THREAD

**Issue by dldrk** [rundeck/rundeck#6319]
**Describe the bug**
After editing project description with invalid characters, it saves with old description in simple config but new (and not valid one) in Edit Configuration file. No errors at service.log.

The bug does not happen when creating the project at first time, but when editing.

![image](https://user-images.githubusercontent.com/58412426/88569471-79342e00-d008-11ea-855c-9c092c2bcc9c.png)

**My Rundeck detail**

* Rundeck version: 3.3.1
* install type: rpm/deb/war
* OS Name/version: Centos7/UbuntuXenial
* DB Type/version: mysql-5.7

**To Reproduce**
1. Create new project with simple description, i.e: test123 > Save project.
2. Go to Edit Project settings and edit description with not valid characters, i.e: '"\#\!;`~\=?[({><
3. Click save.
4. See there is no errors.
5. In simple view it can be seen the old description (test123) but in Advanced view the invalid one.

**Expected behavior**
Rundeck showing an error when using not valid characters and showing the same values on both simple/advanced project config views.

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Firefox
 - Version 78.0.2

**Comment by MegaDrive68k** [comment]
Still on 3.4.2-rc1.

**Comment by drdpa** [comment]
Still on 4.5.0
