### ISSUE TITLE
Maintain the static rank order than ascending or descending . 

### ISSUE THREAD

**Issue by chikalaka0516** [rundeck/rundeck#6328]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 2.0.2.7.1
* install type: (rpm,deb,war,launcher?) - war 
* OS Name/version: 12.2
* DB Type/version: mysql? postgres? h2?..mysql

**Expected Behavior**

input - node3,node1,node 2 
expecteed order - node3,node2,node1

**How to Reproduce**
input - node3,node1,node 2 

rank filter - ascending -- execution order would be node1,node2,node3
rank filter - descending - execution order would be node3,node2,node1

**Comment by MegaDrive68k** [comment]
Hi @chikalaka0516,

You can check a way to do that here: https://stackoverflow.com/a/63137864/10426011

Hope it helps!
