### ISSUE TITLE
Update from 3.3.0 to 3.3.1 causes errors with DB connection

### ISSUE THREAD

**Issue by rmueck** [rundeck/rundeck#6333]
**Description**
After updating from 3.3.0 to 3.3.1 Rundeck is no longer working.

**My Rundeck detail**

* Rundeck version: [ 3.3.0 -> 3.3.1]
* install type: deb
* OS Name/version: Debian / 9.13
* DB Type/version: mysql/mariadb (10.4)

**To Reproduce**
1. dpkg -i rundeck_3.3.1.20200727-1_all.deb
2. starting rundeckd
3. See errors:
~~~sh

#> tail /var/log/daemon.log
Aug  1 14:48:19 rddebi001 mysqld[617]: 2020-08-01 14:48:19 627 [Warning] Aborted connection 627 to db: 'rundeck' user: 'rundeck' host: 'localhost' (Got an error reading communication packets)
~~~

~~~sh
# service rundeckd status
● rundeckd.service - LSB: rundeck job automation console
   Loaded: loaded (/etc/init.d/rundeckd; generated; vendor preset: enabled)
   Active: failed (Result: exit-code) since Sun 2020-08-02 08:26:26 CEST; 1min 11s ago
     Docs: man:systemd-sysv-generator(8)
 Main PID: 4436 (code=exited, status=143)

Aug 02 07:53:56 debi01 rundeckd[4426]: Starting rundeckd.
Aug 02 07:53:56 debi01 rundeckd[4426]: done.
Aug 02 07:53:56 debi01 systemd[1]: Started LSB: rundeck job automation console.
Aug 02 08:26:26 debi01 systemd[1]: Stopping LSB: rundeck job automation console...
Aug 02 08:26:26 debi01 rundeckd[5967]: Stopping rundeckd.
Aug 02 08:26:26 debi01 rundeckd[5967]: done.
Aug 02 08:26:26 debi01 systemd[1]: rundeckd.service: Main process exited, code=exited, status=143/n/a
Aug 02 08:26:26 debi01 systemd[1]: Stopped LSB: rundeck job automation console.
Aug 02 08:26:26 debi01 systemd[1]: rundeckd.service: Unit entered failed state.
Aug 02 08:26:26 debi01 systemd[1]: rundeckd.service: Failed with result 'exit-code
~~~

**Expected behavior**
Update successful. Rundeck working

**Desktop (please complete the following information):**
 - OS: Linux Mint 20
 - Browser Vivaldi

**Comment by MegaDrive68k** [comment]
Hi @rmueck 

I tested upgrading 3.3.0 to 3.3.1 with MySQL and works normally, maybe you're facing [this](https://dba.stackexchange.com/a/40962) on your database? Can you test that solutions on your database backend?

Regards!

**Comment by rmueck** [comment]
> Hi @rmueck
> 
> I tested upgrading 3.3.0 to 3.3.1 with MySQL and works normally, maybe you're facing [this](https://dba.stackexchange.com/a/40962) on your database? Can you test that solutions on your database backend?
> 
> Regards!

Hi @MegaDrive68k 
thank you for the tip. Unfortunately it did not work. I also tried to drop the rundeck db and recreate it regarding RD docs but 
still the same issue. With H2 as database 3.3.1 is running fine. 

Regards!

**Comment by rmueck** [comment]
Finally found the solution! 

- stopped rundeckd service
- performed the update to 3.3.1 (`dpkg -i rundeck_3.3.1.20200727-1_all.deb`)
- changed /etc/rundeck-config.properties:

```
-dataSource.url = jdbc:mysql://localhost/rundeck?autoReconnect=true&useSSL=false
+dataSource.url = jdbc:mysql://localhost/rundeck?serverTimezone=Europe/Berlin

-dataSource.driverClassName=com.mysql.jdbc.Driver
+dataSource.driverClassName=com.mysql.cj.jdbc.Driver

+dataSource.properties.autoReconnect=true
+dataSource.properties.useSSL=false
```
- started rundeckd service sucessfully
