### ISSUE TITLE
Job import/export removes failOnDisable: true

### ISSUE THREAD

**Issue by ajxb** [rundeck/rundeck#6335]
Hi,

I believe I have encountered the same problem as rundeck/rundeck-cli#201 with the failOnDisable option, when I upload a number of jobs that were exported from another system to a new target system, the failOnDisable flag is reset when it was set to true in the yaml file and on the source machine.

I've spotted that if I move the `failOnDisable: true` setting to be an element of the `jobref:` map and import the option is correctly retained.

I'm using the following:
* RunDeck 2.11.8
* RunDeck 1.1.0.SNAPSHOT-1

**Comment by gschueler** [comment]
similar to https://github.com/rundeck/rundeck/issues/3429 the issue exists for the `failOnDisable` flag for job reference
