### ISSUE TITLE
Can't view execution logs after upgrading from 3.2.9 to 3.3.x

### ISSUE THREAD

**Issue by leshik** [rundeck/rundeck#6337]
**Describe the bug**

After upgrading to 3.3.1 (same thing with 3.3.0) from 3.2.9 I can't view execution logs anymore.
The following error is shown in Google Chrome console:
```
{"error":"Not authorized for action \"view\" for Execution 14547","id":"14547","offset":"0","completed":false}
```
Rolling back to 3.2.9 resolves the issue.

**My Rundeck detail**

* Rundeck version: 3.3.1
* install type: Docker official
* DB Type/version: MySQL

**Additional context**

Might be related to #6070.

**Comment by MegaDrive68k** [comment]
Hi, 

Your instance is behind a reverse proxy or similar? you can try [this](https://github.com/rundeck/rundeck/issues/6292#issuecomment-674753355).

Hope it helps!

**Comment by thomsonac** [comment]
We are running it behind a local apache reverse proxy.  Unfortunately adding -Drundeck.jetty.connector.forwarded=true didn't fix the issue nor did adding rundeck.server.useForwardHeaders=true to rundeck-config.properties

Thanks for the suggestion!  Happy to try anything at this point- it's pretty frustrating especially considering the original Issue (6292) was marked as fixed

**Comment by leshik** [comment]
@MegaDrive68k it's the same as `RUNDECK_SERVER_FORWARDED` env for Docker, which is already set. Doesn't help.

**Comment by leshik** [comment]
The issue was with my setup, not Rundeck, closing.
