### ISSUE TITLE
Error 500: Internal Server Error after saving a job

### ISSUE THREAD

**Issue by Payback159** [rundeck/rundeck#6340]
**Describe the bug**

Error 500: Internal Server Error
URI
/rundeckpro/project/wgcp/job/update
Class
com.microsoft.sqlserver.jdbc.SQLServerException
Message
could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception.LockAcquisitionException: could not execute statement
Caused by
Transaction (Process ID 987) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.

Trace
    Line | Method
->>  232 | convertHibernateAccessException in org.springframework.orm.hibernate5.SessionFactoryUtils
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|    755 | convertHibernateAccessException in org.springframework.orm.hibernate5.HibernateTransactionManager
|    590 | doCommit . . . . . . . . . . .  in     ''
|    765 | processCommit                   in org.springframework.transaction.support.AbstractPlatformTransactionManager
|    734 | commit . . . . . . . . . . . .  in     ''
|    150 | execute                         in org.springframework.transaction.support.TransactionTemplate
|     91 | execute . . . . . . . . . . . . in grails.gorm.transactions.GrailsTransactionTemplate
|   1870 | doCall                          in rundeck.controllers.ScheduledExecutionController$_update_closure55
|    272 | withForm . . . . . . . . . . .  in grails.artefact.Controller$Trait$Helper
|    250 | withForm                        in     ''
|   1857 | update . . . . . . . . . . . .  in rundeck.controllers.ScheduledExecutionController
|    223 | invoke                          in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke . . . . . . . . . . . .  in org.grails.core.DefaultGrailsControllerClass
|     90 | handle                          in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch . . . . . . . . . .  in org.springframework.web.servlet.DispatcherServlet
|    901 | doService                       in     ''
|    970 | processRequest . . . . . . . .  in org.springframework.web.servlet.FrameworkServlet
|    872 | doPost                          in     ''
|    846 | service . . . . . . . . . . . . in     ''
|     96 | run                             in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs . . . . . . . . . . . . .  in javax.security.auth.Subject
|    105 | doFilter                        in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|     67 | doFilterInternal . . . . . . .  in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|    317 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke . . . . . . . . . . . .  in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter                        in     ''
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter                        in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter . . . . . . . . . . .  in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilterInternal . . . . . . .  in grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter . . . . . . . . . . .  in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter . . . . . . . . . . .  in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter . . . . . . . . . . .  in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run . . . . . . . . . . . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs                            in javax.security.auth.Subject
|    105 | doFilter . . . . . . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter . . . . . . . . . . .  in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter . . . . . . . . . . .  in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter . . . . . . . . . . .  in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter . . . . . . . . . . .  in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal . . . . . . .  in org.springframework.security.web.FilterChainProxy
|    177 | doFilter                        in     ''
|     77 | doFilterInternal . . . . . . .  in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|     67 | doFilterInternal                in org.grails.web.filters.HiddenHttpMethodFilter
|    130 | doFilter . . . . . . . . . . .  in org.springframework.boot.web.support.ErrorPageFilter
|     66 | access$000                      in     ''
|    105 | doFilterInternal . . . . . . .  in org.springframework.boot.web.support.ErrorPageFilter$1
|    123 | doFilter                        in org.springframework.boot.web.support.ErrorPageFilter
|   1149 | runWorker . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor
|    624 | run                             in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run . . . . . . . . . . . . . . in java.lang.Thread

Caused by LockAcquisitionException: could not execute statement
->>  123 | convert                         in org.hibernate.exception.internal.SQLStateConversionDelegate
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|     42 | convert                         in org.hibernate.exception.internal.StandardSQLExceptionConverter
|    111 | convert . . . . . . . . . . . . in org.hibernate.engine.jdbc.spi.SqlExceptionHelper
|     97 | convert                         in     ''
|    207 | executeUpdate . . . . . . . . . in org.hibernate.engine.jdbc.internal.ResultSetReturnImpl
|     45 | addToBatch                      in org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch
|   3325 | delete . . . . . . . . . . . .  in org.hibernate.persister.entity.AbstractEntityPersister
|   3562 | delete                          in     ''
|     98 | execute . . . . . . . . . . . . in org.hibernate.action.internal.EntityDeleteAction
|    589 | executeActions                  in org.hibernate.engine.spi.ActionQueue
|    463 | executeActions . . . . . . . .  in     ''
|    337 | performExecutions               in org.hibernate.event.internal.AbstractFlushingEventListener
|     39 | onFlush . . . . . . . . . . . . in org.hibernate.event.internal.DefaultFlushEventListener
|   1295 | flush                           in org.hibernate.internal.SessionImpl
|    468 | managedFlush . . . . . . . . .  in     ''
|   3159 | flushBeforeTransactionCompletion in     ''
|   2352 | beforeTransactionCompletion . . in     ''
|    491 | beforeTransactionCompletion     in org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl
|    147 | beforeCompletionCallback . . .  in org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl
|     38 | access$100                      in     ''
|    231 | commit . . . . . . . . . . . .  in org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl
|     65 | commit                          in org.hibernate.engine.transaction.internal.TransactionImpl
|    582 | doCommit . . . . . . . . . . .  in org.springframework.orm.hibernate5.HibernateTransactionManager
|    765 | processCommit                   in org.springframework.transaction.support.AbstractPlatformTransactionManager
|    734 | commit . . . . . . . . . . . .  in     ''
|    150 | execute                         in org.springframework.transaction.support.TransactionTemplate
|     91 | execute . . . . . . . . . . . . in grails.gorm.transactions.GrailsTransactionTemplate
|   1870 | doCall                          in rundeck.controllers.ScheduledExecutionController$_update_closure55
|    272 | withForm . . . . . . . . . . .  in grails.artefact.Controller$Trait$Helper
|    250 | withForm                        in     ''
|   1857 | update . . . . . . . . . . . .  in rundeck.controllers.ScheduledExecutionController
|    223 | invoke                          in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke . . . . . . . . . . . .  in org.grails.core.DefaultGrailsControllerClass
|     90 | handle                          in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch . . . . . . . . . .  in org.springframework.web.servlet.DispatcherServlet
|    901 | doService                       in     ''
|    970 | processRequest . . . . . . . .  in org.springframework.web.servlet.FrameworkServlet
|    872 | doPost                          in     ''
|    846 | service . . . . . . . . . . . . in     ''
|     96 | run                             in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs . . . . . . . . . . . . .  in javax.security.auth.Subject
|    105 | doFilter                        in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|     67 | doFilterInternal . . . . . . .  in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|    317 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke . . . . . . . . . . . .  in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter                        in     ''
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter                        in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter . . . . . . . . . . .  in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilterInternal . . . . . . .  in grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter . . . . . . . . . . .  in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter . . . . . . . . . . .  in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter . . . . . . . . . . .  in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run . . . . . . . . . . . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs                            in javax.security.auth.Subject
|    105 | doFilter . . . . . . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter . . . . . . . . . . .  in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter . . . . . . . . . . .  in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter . . . . . . . . . . .  in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter . . . . . . . . . . .  in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal . . . . . . .  in org.springframework.security.web.FilterChainProxy
|    177 | doFilter                        in     ''
|     77 | doFilterInternal . . . . . . .  in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|     67 | doFilterInternal                in org.grails.web.filters.HiddenHttpMethodFilter
|    130 | doFilter . . . . . . . . . . .  in org.springframework.boot.web.support.ErrorPageFilter
|     66 | access$000                      in     ''
|    105 | doFilterInternal . . . . . . .  in org.springframework.boot.web.support.ErrorPageFilter$1
|    123 | doFilter                        in org.springframework.boot.web.support.ErrorPageFilter
|   1149 | runWorker . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor
|    624 | run                             in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run . . . . . . . . . . . . . . in java.lang.Thread

Caused by SQLServerException: Transaction (Process ID 987) was deadlocked on lock resources with another process and has been chosen as the deadlock victim. Rerun the transaction.
->>  259 | makeFromDatabaseError           in com.microsoft.sqlserver.jdbc.SQLServerException
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
|   1547 | getNextResult                   in com.microsoft.sqlserver.jdbc.SQLServerStatement
|    548 | doExecutePreparedStatement . .  in com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement
|    479 | doExecute                       in com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement$PrepStmtExecCmd
|   7344 | execute . . . . . . . . . . . . in com.microsoft.sqlserver.jdbc.TDSCommand
|   2713 | executeCommand                  in com.microsoft.sqlserver.jdbc.SQLServerConnection
|    224 | executeCommand . . . . . . . .  in com.microsoft.sqlserver.jdbc.SQLServerStatement
|    204 | executeStatement                in     ''
|    426 | executeUpdate . . . . . . . . . in com.microsoft.sqlserver.jdbc.SQLServerPreparedStatement
|    204 | executeUpdate                   in org.hibernate.engine.jdbc.internal.ResultSetReturnImpl
|     45 | addToBatch . . . . . . . . . .  in org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch
|   3325 | delete                          in org.hibernate.persister.entity.AbstractEntityPersister
|   3562 | delete . . . . . . . . . . . .  in     ''
|     98 | execute                         in org.hibernate.action.internal.EntityDeleteAction
|    589 | executeActions . . . . . . . .  in org.hibernate.engine.spi.ActionQueue
|    463 | executeActions                  in     ''
|    337 | performExecutions . . . . . . . in org.hibernate.event.internal.AbstractFlushingEventListener
|     39 | onFlush                         in org.hibernate.event.internal.DefaultFlushEventListener
|   1295 | flush . . . . . . . . . . . . . in org.hibernate.internal.SessionImpl
|    468 | managedFlush                    in     ''
|   3159 | flushBeforeTransactionCompletion in     ''
|   2352 | beforeTransactionCompletion     in     ''
|    491 | beforeTransactionCompletion . . in org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl
|    147 | beforeCompletionCallback        in org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl
|     38 | access$100 . . . . . . . . . .  in     ''
|    231 | commit                          in org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl
|     65 | commit . . . . . . . . . . . .  in org.hibernate.engine.transaction.internal.TransactionImpl
|    582 | doCommit                        in org.springframework.orm.hibernate5.HibernateTransactionManager
|    765 | processCommit . . . . . . . . . in org.springframework.transaction.support.AbstractPlatformTransactionManager
|    734 | commit                          in     ''
|    150 | execute . . . . . . . . . . . . in org.springframework.transaction.support.TransactionTemplate
|     91 | execute                         in grails.gorm.transactions.GrailsTransactionTemplate
|   1870 | doCall . . . . . . . . . . . .  in rundeck.controllers.ScheduledExecutionController$_update_closure55
|    272 | withForm                        in grails.artefact.Controller$Trait$Helper
|    250 | withForm . . . . . . . . . . .  in     ''
|   1857 | update                          in rundeck.controllers.ScheduledExecutionController
|    223 | invoke . . . . . . . . . . . .  in org.grails.core.DefaultGrailsControllerClass$MethodHandleInvoker
|    188 | invoke                          in org.grails.core.DefaultGrailsControllerClass
|     90 | handle . . . . . . . . . . . .  in org.grails.web.mapping.mvc.UrlMappingsInfoHandlerAdapter
|    967 | doDispatch                      in org.springframework.web.servlet.DispatcherServlet
|    901 | doService . . . . . . . . . . . in     ''
|    970 | processRequest                  in org.springframework.web.servlet.FrameworkServlet
|    872 | doPost . . . . . . . . . . . .  in     ''
|    846 | service                         in     ''
|     96 | run . . . . . . . . . . . . . . in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs                            in javax.security.auth.Subject
|    105 | doFilter . . . . . . . . . . .  in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|     67 | doFilterInternal                in org.rundeck.grails.plugins.securityheaders.RundeckSecurityHeadersFilter
|    317 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    127 | invoke                          in org.springframework.security.web.access.intercept.FilterSecurityInterceptor
|     91 | doFilter . . . . . . . . . . .  in     ''
|    331 | doFilter                        in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    114 | doFilter . . . . . . . . . . .  in org.springframework.security.web.access.ExceptionTranslationFilter
|     64 | doFilter                        in grails.plugin.springsecurity.web.UpdateRequestContextHolderExceptionTranslationFilter
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilterInternal                in grails.plugin.springsecurity.web.filter.GrailsHttpPutFormContentFilter
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     54 | doFilter                        in grails.plugin.springsecurity.web.filter.GrailsAnonymousAuthenticationFilter
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    158 | doFilter                        in org.springframework.security.web.authentication.rememberme.RememberMeAuthenticationFilter
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    170 | doFilter                        in org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     96 | run                             in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter$1
|    422 | doAs . . . . . . . . . . . . .  in javax.security.auth.Subject
|    105 | doFilter                        in org.springframework.security.web.jaasapi.JaasApiIntegrationFilter
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    200 | doFilter                        in org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     64 | doFilter                        in grails.plugin.springsecurity.web.authentication.logout.MutableLogoutFilter
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    105 | doFilter                        in org.springframework.security.web.context.SecurityContextPersistenceFilter
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|     58 | doFilter                        in grails.plugin.springsecurity.web.SecurityRequestHolderFilter
|    331 | doFilter . . . . . . . . . . .  in org.springframework.security.web.FilterChainProxy$VirtualFilterChain
|    214 | doFilterInternal                in org.springframework.security.web.FilterChainProxy
|    177 | doFilter . . . . . . . . . . .  in     ''
|     77 | doFilterInternal                in org.grails.web.servlet.mvc.GrailsWebRequestFilter
|     67 | doFilterInternal . . . . . . .  in org.grails.web.filters.HiddenHttpMethodFilter
|    130 | doFilter                        in org.springframework.boot.web.support.ErrorPageFilter
|     66 | access$000 . . . . . . . . . .  in     ''
|    105 | doFilterInternal                in org.springframework.boot.web.support.ErrorPageFilter$1
|    123 | doFilter . . . . . . . . . . .  in org.springframework.boot.web.support.ErrorPageFilter
|   1149 | runWorker                       in java.util.concurrent.ThreadPoolExecutor
|    624 | run . . . . . . . . . . . . . . in java.util.concurrent.ThreadPoolExecutor$Worker
^    748 | run                             in java.lang.Thread

**My Rundeck detail**

* Rundeck version: 3.2.3-20200221
* install type: war
* OS Name/version: sles12.5
* DB Type/version: mssql

**To Reproduce**
1. Go to 'job definition'
2. Click on 'save job'

**Expected behavior**
That the job is saved with the made changes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Chrome 84.0.4147.105

**Additional context**

**Comment by Payback159** [comment]
Duplicate of #5116

**Comment by fdevans** [comment]
Let us know if you are still running into this and can replicate it.
