### ISSUE TITLE
Rundeck server private keys exposed using RD_* env vars on remote SSH nodes

### ISSUE THREAD

**Issue by MegaDrive68k** [rundeck/rundeck#6343]
**Describe the bug**

`RD_CONFIG_SSH_KEY_STORAGE_PATH` and `RD_NODEEXECUTOR_SSH_KEY_STORAGE_PATH` environment variables exposed (on JCSH or OpenSSH node executors).

**My Rundeck detail**

* Rundeck version: 3.3.1
* install type: WAR
* OS Name/version: Ubuntu 20.04
* DB Type/version: H2

**To Reproduce**

1. Configure the Rundeck server adding: `SendEnv RD_*` to` /etc/ssh/ssh_config` file.
2. Configure remote SSH server adding: `AcceptEnv RD_*` to `etc/ssh/sshd_config` file.
3. Create a new Rundeck Project.
4. Create a job that involves some script execution (and set "run on debug mode").
5. Run the job.
6. `RD_CONFIG_SSH_KEY_STORAGE_PATH `and `RD_NODEEXECUTOR_SSH_KEY_STORAGE_PATH `environment variables are exposed.

**Expected behavior**

`RD_NODEEXECUTOR_SSH_KEY_STORAGE_PATH` and `RD_CONFIG_SSH_KEY_STORAGE_PATH` must be hidden for security reasons.

**Comment by gschueler** [comment]
closed by #6427
