### ISSUE TITLE
Poor Performance of the Web Interface after Update

### ISSUE THREAD

**Issue by wep-p** [rundeck/rundeck#6344]
**Describe the bug**
After Updating Rundeck from version 3.2.8 to 3.3.0 (or 3.3.1), the performance of the Web Interface dropped drastically. Especially when editing job definitions or displaying log output, it takes 3-4 times longer than the older releases. 
Before it worked great performance- and stability wise. 

**My Rundeck detail**

* Rundeck version: Rundeck 3.3.0/ 3.3.1
* install type: war
* OS Name/version: SLES12 SP5
* DB Type/version: postgres

**Comment by MegaDrive68k** [comment]
Hi @wep-p 

Can you share browser developer mode screenshot (console and network tabs) to check which elements cause that slowness?

Regards.

**Comment by wep-p** [comment]
Hi @MegaDrive68k ,

I´m using Chrome 83.0.4103.116 (Official Build) (64-Bit). The perfomance issues occur also using Firefox. 

Looking into the console and network tabs, the missing vendor.js seems to be the problem. 

![rundeck_error](https://user-images.githubusercontent.com/54305075/89764530-d8a83880-daf4-11ea-9afe-f6e914f6f760.png)

**Comment by dbk-rabel** [comment]
+1

**Comment by csimader** [comment]
+1

**Comment by wep-p** [comment]
What seems to be the problem are the many old plugin versions inside the libext dir. We rolled out every release since 3.0.28 and these old files never got deleted. 


![image](https://user-images.githubusercontent.com/54305075/94679468-71527c00-0320-11eb-86cc-18ff07f81566.png)


After deleting all versions of **rundeck-jasypt-encryption-plugin** except the newest version, die performance got back to normal pre update. (asset is still missing of course tho)

many thanks to @sjrd218 for pointing out that the old versions need to be removed.
