### ISSUE TITLE
Pre-Authentication Mode Roles passes in headers are duplicated

### ISSUE THREAD

**Issue by karann-jain** [rundeck/rundeck#6345]
**Describe the bug**
When comma separated roles are passed on header X-Forwarded-Roles, duplicate roles are showed on UI.
e.g.,

Passed: X-Forwarded-Roles: role1, role2, role3
Shown:
role1, role2, role3,role1,role2,role3

**My Rundeck detail**

* Rundeck version: 3.3.0
* install type: Docker
* DB Type/version: mysql

**To Reproduce**
1. Login using pre-authenticated mode with roles passed on headers.
2. Go to '/user/profile'
4. See duplicate roles are shown

**Expected behavior**
Only single occurrence of role should be displayed under profile. Logs also print duplicates while processing acl for the user.

**Comment by MegaDrive68k** [comment]
Confirmed (tested passing roles via headers with NGINX):

Pre auth config using docker image on 3.2.8:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/89461773-70470900-d73a-11ea-8bf0-a8ffcdf34e6e.png)

Pre auth config using docker image on 3.3.0:

![Screenshot_4](https://user-images.githubusercontent.com/51376003/89461865-8ce34100-d73a-11ea-8cd6-8f5340d05cef.png)

Pre auth config using docker image on 3.3.1:

![Screenshot_5](https://user-images.githubusercontent.com/51376003/89462017-cc119200-d73a-11ea-98d3-62dfb18cf131.png)

Thanks for your feedback @karann-jain!

**Comment by alepinzon** [comment]
@MegaDrive68k  Does this behavior cause some issues with the ACLs? Or we can use it with that bug? Do you have in your roadmap fix the issue? thanks!
