### ISSUE TITLE
Font Awesome Icon not working in Node Enhancers

### ISSUE THREAD

**Issue by renardguill** [rundeck/rundeck#6365]
**Describe the bug**
When i set a Font Awesome icon on Node Enhancers settigns, i see a square inplace the Font Awesome icon. But work with glyphicons.

**My Rundeck detail**

* Rundeck version: 3.3.1
* install type: deb
* OS Name/version: Ubuntu 20.04
* DB Type/version: mariadb

**To Reproduce**
1. Go to 'Node Enhancers' on 'Edit Nodes...' menu
2. Click on 'Enhancers' Tab
3. Add a new node enhancers of icon type
4. I Set : 

> - Attribute Name: osName
> - Attribute Value: Linux
> - Icon Name: fa-linux

5. I save
6. i see a square inplace the Font Awesome icon in the Nodes view.

**Expected behavior**
See the Font Awesome icon

**Screenshots**
![Screenshot](https://github.com/renardguill/dist/raw/master/2020-08-12_12h40_57.png "Screenshot")

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 84.0.4147.105

**Comment by renardguill** [comment]
I seen that the **fa-linux** icon is part of the set **Brands Style (fab)**.
When i set an other icon from an other set, like **fa-server** from **Solid Style (fas)** set, it working !

Is the **Brands Style (fab)** are available on Rundeck ?

**Comment by gschueler** [comment]
yes you can, but it requires prefix "fab-" for the icons.  Try using Icon Name: `fab-linux`
