### ISSUE TITLE
Duration exceeded emails being sent early

### ISSUE THREAD

**Issue by bf86** [rundeck/rundeck#6372]
Duration exceeded notification emails are sending when the job completes, even before the timeout threshold. I'm using absolute threshold only. Changing the threshold has no effect, however if I create a new job with a new UUID and the same settings that resolves it. I don't know how to reproduce this, but I've seen it happen with several jobs in the past year or so.

Rundeck version: 3.2.7 (from Rundeck Docker image)
Ubuntu 18.04
mysql

**Comment by coconitro** [comment]
Have noticed similar behavior across our cluster on a number of jobs. Its intermittent and hard to track down. Haven't been able to know where to begin debugging honestly.
