### ISSUE TITLE
war Startup error

### ISSUE THREAD

**Issue by qicaihuoyan** [rundeck/rundeck#6379]
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedConstructor$1 (jar:file:/data/servers/rundeck/rundeck-3.3.1-20200727.war!/WEB-INF/lib/groovy-2.5.6.jar!/) to constructor javax.security.auth.login.Configuration()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedConstructor$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

Don't know what setting it is related to?

**Comment by MegaDrive68k** [comment]
Hi @qicaihuoyan 

Please follow your issue from here: https://github.com/rundeck/rundeck/issues/6378

Thanks for your feedback!
