### ISSUE TITLE
Running executions are not showing in the Jobs section

### ISSUE THREAD

**Issue by manticora17** [rundeck/rundeck#6384]
**Describe the bug**
Running executions are only visible in the project activity and activity for that specific job. Only completed executions are visible in the Jobs section. 

**My Rundeck detail**
* Rundeck version: 3.3.1
* install type: war
* OS Name/version: ubuntu 18.04
* DB Type/version: postgres

**To Reproduce**
1. Run a job.
2. Go to Jobs section on the left side panel.
3. Running execution isn't there.
4. Wait for job to finish - completed execution will appear in the jobs section.

**Expected behavior**
Running executions are visible in the jobs section.

**Screenshots**
Running execution in the specific job activity:
 ![Screen Shot 2020-08-18 at 5 02 40 PM](https://user-images.githubusercontent.com/37708597/90565398-dc7f2f00-e174-11ea-8fa6-ec43a71eb47f.png)

Running execution in the project activity:
![Screen Shot 2020-08-18 at 5 03 18 PM](https://user-images.githubusercontent.com/37708597/90565370-d0936d00-e174-11ea-9d4b-3bfef7ff30a0.png)

Only completed executions shown in the jobs sections:
![Screen Shot 2020-08-18 at 5 02 55 PM](https://user-images.githubusercontent.com/37708597/90565436-e99c1e00-e174-11ea-8aa1-cbb6b06bb195.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Firefox
 - Version: 79.0

**Comment by MegaDrive68k** [comment]
Confirmed. Also happening on Rundeck 3.3.2.

Thanks for the feedback @manticora17!

**Comment by sparr** [comment]
This is notable in the use case where you press enter after entering a job option, which runs the job but takes you back to the jobs list.
