### ISSUE TITLE
Rundeck Windows as a Windows service not loading ssl properties

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#6397]
**Describe the bug**
While running the Windows Rundeck Service, which calls the start_rundeck.bat file, it does not load correctly the SSL properties to run with an HTTPS certificate. 

Changing the line in the $RdeckBase/etc/profile.bat file

set RDECK_SSL_OPTS="-Djavax.net.ssl.trustStore=%RDECK_BASE%\etc\truststore -Djavax.net.ssl.trustStoreType=jks -Djava.protocol.handler.pkgs=com.sun.net.ssl.internal.www.protocol"

to

set RDECK_SSL_OPTS=-Drundeck.ssl.config=%RDECK_BASE%\server\config\ssl.properties -Dserver.https.port=4443

fixes the issue.

**My Rundeck detail**

* Rundeck version: tested with Rundeck 3.3.2 or older versions
* install type: .war for Windows
* OS Name/version: Windows any version
* DB Type/version: any 

**To Reproduce**
1. Install Rundeck as a service with SSL options
2. Start the Rundeck service
3. Check the service.log, Rundeck will start on port 4440 without SSL options

**Expected behavior**
Rundeck should load the specified SSL options defined in the profile.bat file

**Screenshots**

**Desktop (please complete the following information):**
 - Ubuntu 20.04 
 - Browser chrome, safari

**Comment by nvalenzuela20** [comment]
In the documentation for how install Rundeck in Windows there is a step that specifies that a `start_rundeck.bat` should be created, and that  the user needs to add the option `%RDECK_SSL_OPTS%` to it, but this is  not necessary if the user doesn't want to activate SSL

![image](https://user-images.githubusercontent.com/35808955/98372507-a1c2bf80-201c-11eb-9ac6-0dcd945da5ff.png)
