### ISSUE TITLE
api/29/executions/metrics leads to "A server error occurred"

### ISSUE THREAD

**Issue by rdoering** [rundeck/rundeck#6399]
**Describe the bug**
When I send a request to get the system wide metrics I receive the a 500 response.

**My Rundeck detail**

* Rundeck version: 3.3.1
* install type: dep
* OS Name/version: Ubuntu 16.04.7 LTS
* DB Type/version: mysql

**To Reproduce**
1. Send Request
GET /api/29/executions/metrics HTTP/1.1
X-Rundeck-Auth-Token: 5q9cOp******************
Accept: application/json
User-Agent: PostmanRuntime/7.26.3
Cache-Control: no-cache
Host: ******************
Accept-Encoding: gzip, deflate, br
Connection: keep-alive

2. Receive response
HTTP/1.1 500 Server Error
Date: Tue, 25 Aug 2020 06:05:44 GMT
Server: Apache/2.4.18 (Ubuntu)
X-Frame-Options: deny
X-XSS-Protection: 1
X-Content-Type-Options: nosniff
Content-Security-Policy: default-src 'none' ; script-src 'self' 'unsafe-inline' 'unsafe-eval' ; style-src 'self' 'unsafe-inline' ; img-src * ; font-src 'self' data: ; connect-src 'self' https://api.rundeck.com ; form-action 'self' ;
Content-Type: application/json
Connection: close
Transfer-Encoding: chunked
{"error":"A server error occurred"}

**Expected behavior**
receice 200-response

**Screenshots**

**Additional context**
[rundeck-trace.txt](https://github.com/rundeck/rundeck/files/5121643/rundeck-trace.txt)

**Comment by MegaDrive68k** [comment]
Hi @rdoering 

Can you share your API call? I tested (on Rundeck 3.3.1 and 3.3.2) with the following API call and works:

```bash
curl -s --location --request GET 'http://localhost:4440/api/35/metrics' \
--header 'Accept: application/json' \
--header 'X-Rundeck-Auth-Token: AYsyglgoIbmbb6f8QDrrWcvkwRBKJ9xV' \
--header 'Content-Type: application/json'
```

Putting that on a bash script and combining with [jq](https://stedolan.github.io/jq/) tool using   `myscript.sh | jq` I obtain:

```json
{
  "_links": {
    "metrics": {
      "href": "http://localhost:4440/api/35/metrics/metrics"
    },
    "ping": {
      "href": "http://localhost:4440/api/35/metrics/ping"
    },
    "threads": {
      "href": "http://localhost:4440/api/35/metrics/threads"
    },
    "healthcheck": {
      "href": "http://localhost:4440/api/35/metrics/healthcheck"
    }
  }
}
```

Also, you can use [RD CLI](https://rundeck.github.io/rundeck-cli/) to get metrics easily (in-depth, RD CLI is a Rundeck API abstraction).

`rd metrics list`

Output:

```bash
# 4 metric endpoints:
metrics
ping
threads
healthcheck
```

Hope it helps!

**Comment by rdoering** [comment]
@MegaDrive68k 
If you prefer curl, here is my request:
```
curl --location --request GET 'https://*************/api/29/executions/metrics' \
--header 'X-Rundeck-Auth-Token: 5q9cOpOL***************' \
--header 'Accept: application/json' \
--header 'Cookie: JSESSIONID=node017289n8vhd**********.node0'
```
But the result is still the same `{"error":"A server error occurred"}`. 

It seems we have a It-Works-on-My-Machine error :-/. I dont know how to analyse this problem deeper, but I can say, that the API-endpoint on /api/25/metrics works like a charm.

**Comment by MegaDrive68k** [comment]
Hi @rdoering 

Testing with Postman worked in this way:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/91230086-e6ff7280-e6f8-11ea-8c71-c34fe2b81660.png)

Code generates by Postman:

```bash
curl --location --request GET 'http://hyperion:4440/api/35/executions/metrics' \
--header 'X-Rundeck-Auth-Token: jJaIrxYhFAjKV7JwXDPYR9W3oBEP3j75' \
--header 'Cookie: JSESSIONID=node0192k3c1geez8inczkyh68mf652.node0'
```

**Comment by rdoering** [comment]
Hi @MegaDrive68k 

I am able to access the rundeck API as seen here:
![2020-09-01 10_25_11-Postman](https://user-images.githubusercontent.com/1110248/91826661-2e788800-ec3e-11ea-8a7a-772da183d09f.png)

I also still using the API to export and import jobs .

But when I request "/api/29/executions/metrics" It fails
![2020-09-01 10_23_27-Postman](https://user-images.githubusercontent.com/1110248/91827024-9e870e00-ec3e-11ea-9d7a-7098a35f76e2.png)

It is failing, if remove the header "Accept", also.

Do you have a hint how to debug this problem on the end of rundeck?

Thanks

**Comment by rdoering** [comment]
I guess this ticket can be close while it duplicates #5730
