### ISSUE TITLE
Rundeck should be package aware

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#64]
When handling the raw job definitions, rundeck should be aware of the underlying package mechanism.  

For example, if a job is defined and owned by an rpm package, rundeck should be sensitive to this and:
- Identify the version-release for the job
- Track when a new package is available
- Track if a job has changed from it's original definition in the rpm
- Possibly allow the rpm to be repackaged with the changes

This will likely need to support dpkg as well and probably tgz for those without a packaging discipline.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/17)

Original Creator: Noah Campbell

**Comment by ahonor** [comment]
Rundeck should not be aware of the packaging mechanism.
