### ISSUE TITLE
No tools dir after Upgrade

### ISSUE THREAD

**Issue by xeon1400** [rundeck/rundeck#6404]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.3.2
* install type: (rpm,deb,war,launcher?): war
* OS Name/version: SLES 12 SP5
* DB Type/version: mysql? postgres? h2?..: MariaDB

**Expected Behavior**
While upgrading from 3.2.3 to 3.3.2 with the --installonly command on the war file, no tools folder is created. So rundeck can't start correctly. There is also no tools folder after we manually unzipped the war file. 

**How to Reproduce**
Install 3.3.2 with war file.

**Comment by MegaDrive68k** [comment]
Hi @xeon1400 

`tools` directory are removed on 3.3.X branch, the `rd-acl `tool now is part of RD-CLI (check [this](https://docs.rundeck.com/docs/upgrading/upgrading-to-rundeck-3.3.html#rd-acl-tool-removed), [this](https://github.com/rundeck/rundeck/pull/5920) and [this](https://rundeck.github.io/rd-ext-acl/)). Which process are you followed to upgrade your instance? You can take a look at [this](https://docs.rundeck.com/docs/upgrading/upgrading.html#runnable-war).

Regards!
