### ISSUE TITLE
Poor performance after upgrading to rundeck >= 3.3.0 (missing asset)

### ISSUE THREAD

**Issue by wep-p** [rundeck/rundeck#6411]
After Updating Rundeck from version 3.2.8 to any version above 3.3.0, the web interface takes really long to load and react to input. 

**Load times** for accessing the same job:

version   **3.2.8**: Load: 1.59 s
version **>3.3.0**: Load: 4.97 s

**Load times** for editing the same job:

version   **3.2.8**: Load: 1.56 s
version **>3.3.0**: Load: 7.82 s

I had absolutely no issues prior until upgrading to the new engine in 3.3.0. The newer releases 3.3.1 and 3.3.2 unfortunately 
didn´t improve anything. The only difference I cant spot in the network console is the missing **vendor.js** asset. 

**Rundeck version: Rundeck 3.3.0/ 3.3.1/3.3.2
install type: war
OS Name/version: SLES12 SP5
DB Type/version: postgres**

**Steps to reproduce the behavior:**
Everytime you open a new site in the browser. 

**Browser** chrome version 83.0.4103.116 (64-Bit), firefox 68.4.2esr (64-Bit)

**Screenshots**:

![rundeck_asset](https://user-images.githubusercontent.com/54305075/91399127-b4ab5d80-e83d-11ea-9c00-7feebdc58912.png)

**Comment by MegaDrive68k** [comment]
Hi @wep-p 

Confirmed that missing files:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/91455149-bd0c9400-e84f-11ea-89ca-6de14afb20b5.png)

Related: https://github.com/rundeck/rundeck/issues/6344

**Comment by wep-p** [comment]
hi @MegaDrive68k ,

yes our rundeck instance is clustered and uses a HAproxy to distribute the load.

**rundeck-config.properties:**

#loglevel.default is the default log level for jobs: ERROR,WARN,INFO,VERBOSE,DEBUG
loglevel.default=INFO
rdeck.base=/opt/rundeck

#rss.enabled if set to true enables RSS feeds that are public (non-authenticated)
rss.enabled=false
server.address=server.de
grails.serverURL=https://server.de

dataSource.dbCreate = update

dataSource.driverClassName = org.postgresql.Driver
dataSource.url = jdbc:postgresql://server.de
dataSource.username=rundeck
dataSource.password=pass


#cluster mode
rundeck.clusterMode.enabled=true
rundeck.projectsStorageType=db

#for usage with reverse proxy
server.useForwardHeaders=true

#Pre Auth mode settings
rundeck.security.authorization.preauthenticated.enabled=false
rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
rundeck.security.authorization.preauthenticated.delimiter=,
#Header from which to obtain user name
rundeck.security.authorization.preauthenticated.userNameHeader=X-Forwarded-Uuid
#Header from which to obtain list of roles
rundeck.security.authorization.preauthenticated.userRolesHeader=X-Forwarded-Roles
#Redirect to upstream logout url
rundeck.security.authorization.preauthenticated.redirectLogout=false
rundeck.security.authorization.preauthenticated.redirectUrl=/oauth2/sign_in

rundeck.log4j.config.file=/opt/rundeck/server/config/log4j.properties
rundeck.security.syncLdapUser=true

rundeck.api.tokens.duration.max=0
server.session.timeout=10800

rundeck.feature.webhooks.enabled= true

**Comment by padraiglennon** [comment]
I'm seeing this as well behind an nginx reverse proxy. After upgrading I'm missing the "View Options" settings icon as shown here. Not sure if that is related

**Pre 3.3 Upgrade:**
![image](https://user-images.githubusercontent.com/745557/92239076-4eb07d00-eeb2-11ea-84f6-f9549b964803.png)

**Post 3.3 Upgrade:**
![image](https://user-images.githubusercontent.com/745557/92239119-62f47a00-eeb2-11ea-9413-19b6a867fb92.png)

**Comment by csimader** [comment]
same problem on our site too - RD version 3.3.1
![image](https://user-images.githubusercontent.com/8567019/94014823-56c25500-fdac-11ea-96c2-0a0c898b1752.png)

**Comment by wep-p** [comment]
What seems to be the problem are the many old plugin versions inside the libext dir. We rolled out every release since 3.0.28 and these old files never got deleted. 


![image](https://user-images.githubusercontent.com/54305075/94679468-71527c00-0320-11eb-86cc-18ff07f81566.png)


After deleting all versions of **rundeck-jasypt-encryption-plugin** except the newest version, die performance got back to normal pre update. (asset is still missing of course tho)

many thanks to @sjrd218 for pointing out that the old versions need to be removed.
