### ISSUE TITLE
"sync: ignoring all arguments" warning message on script step (only on 3.3.3)

### ISSUE THREAD

**Issue by MegaDrive68k** [rundeck/rundeck#6449]
**Describe the bug**

`sync: ignoring all arguments` always appears when using script-step on Rundeck 3.3.3, it seems only a warning message, the script works OK.

**My Rundeck detail**

* Rundeck version: 3.3.3
* install type: WAR/RPM/Docker
* OS Name/version: Ubuntu 20.04.1
* DB Type/version: H2

**To Reproduce**

1. Create a job with a script-step, the job must be dispatched to a remote SSH node.
2. Run the job.
3. Check the output, always appears `sync: ignoring all arguments` warning at the beginning.

**Expected behavior**

No warnings on output.

**Screenshots**

![Screenshot_3](https://user-images.githubusercontent.com/51376003/93267995-e0599d80-f782-11ea-98c0-e4869ff4a760.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.1
 - Browser: Firefox
 - Version: 80.0.1

**Additional context**

This warning doesn't appear on Rundeck 3.3.2. 
The message disappears adding  `enable-sync="false"` attribute on node definition (resource.xml).

**Comment by jaumealg** [comment]
Hi,

I got a similar error on 
CentOS release 6.10 (Final)
Linux 2.6.32-754.23.1.el6.x86_64 
Running Rundeck 3.3.3

The scripts are launched to series v7r3 and worked fine but now I got
"bsh: sync: not found"

and job stops

If I add enable-sync="false" attribute on node definition (resource.xml) then the job continues but I got errors as per "command not found"

but if I execute manually the copied script on the destination machine it works without problems

Rlgds,
Jaume.

**Comment by G3NSVRV** [comment]
Failed with custom plugin:

`14:10:21 [PSExe-CUSTOMPLUGIN]: result code: 1, success: false`

```log
[workflow] beginExecuteNodeStep(hidden.domain): NodeDispatch: ScriptFileItem{label='Windows', script=[4151 chars]}
14:10:16 [PSScript-CUSTOMPLUGIN] executing: [/usr/bin/powershell, /var/lib/rundeck/libext/cache/powershell-plugin-custom/ps-filecopier.ps1, -Filepath, /var/lib/rundeck/var/tmp/dispatch9052946776722089587.tmp, -Destpath, /tmp/19-7879238-hidden.domain-dispatch-script.tmp.ps1]
14:10:17 [PSScript-CUSTOMPLUGIN]: result code: 0
14:10:17 [PSScript-CUSTOMPLUGIN]: result filepath: /tmp/19-7879238-hidden.domain-dispatch-script.tmp.ps1
14:10:17 [PSExe-CUSTOMPLUGIN] execCommand started, command: chmod +x /tmp/19-7879238-hidden.domain-dispatch-script.tmp.ps1
14:10:17 [PSExe-CUSTOMPLUGIN] executing: [[/usr/bin/powershell, /var/lib/rundeck/libext/cache/powershell-plugin-custom/ps-nodeexecutor.ps1]]
14:10:17 [PSExe-CUSTOMPLUGIN]: result code: 0, success: true
14:10:17 [PSExe-CUSTOMPLUGIN] execCommand started, command: sync /tmp/19-7879238-hidden.domain-dispatch-script.tmp.ps1
14:10:17 [PSExe-CUSTOMPLUGIN] executing: [[/usr/bin/powershell, /var/lib/rundeck/libext/cache/powershell-plugin-custom/ps-nodeexecutor.ps1]]
14:10:18 running sync /tmp/19-7879238-hidden.domain-dispatch-script.tmp.ps1 on hidden.domain as DOMAIN\HIDDEN_USER
14:10:21 The term 'sync' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
14:10:21 [PSExe-CUSTOMPLUGIN]: result code: 1, success: false
14:10:21 Failed: NonZeroResultCode: [PSExe-CUSTOMPLUGIN] Result code: 1
14:10:21 [workflow] finishExecuteNodeStep(hidden.domain): NodeDispatch: NonZeroResultCode: [PSExe-CUSTOMPLUGIN] Result code: 1
```

**Comment by gschueler** [comment]
@carlosrfranco

**Comment by carlosrfranco** [comment]
@gschueler Was created a PR to disablethe sync command by default and remove the command argument to avoid this warning message https://github.com/rundeck/rundeck/pull/6456

**Comment by gschueler** [comment]
@G3NSVRV does that node have osFamily=windows ?

**Comment by gschueler** [comment]
@jaumealg do you mean you still had errors when you set `enable-sync="false"`?

**Comment by G3NSVRV** [comment]
@gschueler they are using their own node executor / filecopier plugin but yes:
`"os-name": "windows",`

**Comment by gschueler** [comment]
@G3NSVRV try adding os-family=windows, i think that skips the entire sync code

**Comment by carlosrfranco** [comment]
@gschueler @G3NSVRV enable-sync=false should be enough to skip sync command but using os-family=windows will ensure that the commands chmod and sync will be skipped.

**Comment by jaumealg** [comment]
> @jaumealg do you mean you still had errors when you set `enable-sync="false"`?

Hi,

Yes, setting it to false the scripts that previously were working now are failing when we start them form Rundeck. But if we run them on the iSeries box they're working fine.

Rgds,

**Comment by gschueler** [comment]
@jaumealg can you run the jobs in DEBUG mode to get more insight into the error?

**Comment by jaumealg** [comment]
> @jaumealg can you run the jobs in DEBUG mode to get more insight into the error?

Yes, I've already done, output attached to the message.
Anyway I think the problem is related to passing variables to the script as I tested one without passing variables and it worked and the one I pass variables did not work also it did not as a command

i.e. if I send this command it works
`qsh -c '/inf/liblist.sh'` 

but if I send 
`qsh -c '/tmp/148-19519-hqdev_M32-Kernel.sh M32 Productive Y'`

it does not work

Rgds,
Jaume
[Actualiza Kernel-20200918-090618.txt](https://github.com/rundeck/rundeck/files/5247652/Actualiza.Kernel-20200918-090618.txt)

**Comment by gschueler** [comment]
@jaumealg ok, i think that is a separate issue (regarding command quoting), you can try this `qsh -c "'/tmp/148-19519-hqdev_M32-Kernel.sh M32 Productive Y'"` (i.e, wrap the single-quotes with double-quotes). I think that is unrelated to the "synch" problem

**Comment by jaumealg** [comment]
> @jaumealg ok, i think that is a separate issue (regarding command quoting), you can try this `qsh -c "'/tmp/148-19519-hqdev_M32-Kernel.sh M32 Productive Y'"` (i.e, wrap the single-quotes with double-quotes). I think that is unrelated to the "synch" problem

I thought that was the problem but already tested anyway the script has worked almost for 2 years
if I send the command you say the result is 
`qsh: 001-0014 Command /tmp/148-19519-hqdev_M32-Kernel.sh not found.`

also I've tried with different combinations of quotations
but as I mention the job worked for months without any problem it's one of the most used in our rundeck
