### ISSUE TITLE
Rundeck 3.0.16 image found some vulnerabilities while scanning the image through Atrifactory X-ray scanner

### ISSUE THREAD

**Issue by anilsaini1212** [rundeck/rundeck#6453]
Hi ,Have a Good Day , we are using the Rundeck 3.0.16 image from hub.docker.com in our Env
We found some vulnerabilities while scanning the image through Atrifactory X-ray scanner

![rundeck](https://user-images.githubusercontent.com/39952553/93451739-30587180-f8f5-11ea-830b-77e565a0d0b5.PNG)

Please have look 

Thanks 
Anil

**Comment by fdevans** [comment]
Hi Anil. Version 3.0.16 is a few years old at this point. Our current version is 3.3.3.  All of these issues are covered in the current release.
