### ISSUE TITLE
Rundeck version 3.3.2: Unable to check huge logs from GUI

### ISSUE THREAD

**Issue by RakeshBharadwaj** [rundeck/rundeck#6469]
**Describe the bug**
We are unable to check the logs in GUI if they are in huge size, the message itself is self-explanatory.

``` 🐋 49.23MiB is a whale of a log! 🐋
Select a download option above to avoid sinking the ship.
Log content may be truncated ```

But we were able to see these logs in 2.11 and 3.0.24 versions. We wanted to know if there is a parameter that could set this or if this is a bug?

**My Rundeck detail**

* Rundeck version: 3.3.2
* install type: rpm
* OS Name/version: Oracle Linux 6
* DB Type/version: Oracle


**Expected behavior**
The logs should be visible from the UI irrespective of the size of the log


**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

<img width="1080" alt="Screenshot 2020-09-21 at 4 17 38 PM" src="https://user-images.githubusercontent.com/34433655/93758476-25b81800-fc26-11ea-98ce-5fa9e9fd6bd7.png">

**Comment by MegaDrive68k** [comment]
Hi @RakeshBharadwaj 

Add `rundeck.feature.legacyExecOutputViewer.enabled=true` on your `rundeck-config.properties` file (usually at `/etc/rundeck` path) to enable the legacy viewer and restart your instance. Same of: https://github.com/rundeck/rundeck/issues/6223

Regards!

**Comment by lcfrancoi** [comment]
> Hi @RakeshBharadwaj
> 
> Add `rundeck.feature.legacyExecOutputViewer.enabled=true` on your `rundeck-config.properties` file (usually at `/etc/rundeck` path) to enable the legacy viewer and restart your instance. Same of: #6223
> 
> Regards!

We have a similar problem, the loading keeps running and no Download button appears

This solution works for Rundeck version 4.2.1?
