### ISSUE TITLE
Git plugin not using provided SSH key

### ISSUE THREAD

**Issue by DeLoWaN** [rundeck/rundeck#6475]
**Describe the bug**
Hello, the Git plugin when using SSH to authenticate is not using the key configured in the SSH Key Storage Path plugin field. Instead, it uses the SSH key defined in the node-executor.

**My Rundeck detail**

* Rundeck version: 3.3.2 (but also tested in 3.2.1)
* install type: deb (via https://github.com/jjethwa/rundeck/blob/master/Dockerfile)
* OS Name/version: Debian Stretch
* DB Type/version: mysql

**To Reproduce**
1. Create an SSH key
2. Configure an Git export in Rundeck with that key
3. Add that key to the remote Git provider (in my case Gitlab)
4. Click setup
5. You get an auth failed
6. Add the key configured in the default node executor
7. Click setup
8. It works...

**Expected behavior**
The system must used the key provided in the plugin configuration

**Additional info**
I created a new project for this test, with default configuration (then the default node executor SSH)

**Comment by MegaDrive68k** [comment]
Hi @kalumkalac 

You can test it using the [official docker image](https://hub.docker.com/r/rundeck/rundeck) :-)

I did it with the following steps:

1. Put the Rundeck user private key on Rundeck Key Storage.

2. Put the Rundeck user public key on your GitLab account (I used [GitHub](https://docs.github.com/en/enterprise/2.15/user/articles/adding-a-new-ssh-key-to-your-github-account) but you can do the [same](https://docs.gitlab.com/ee/ssh/) on GitLab).

3. Configure [SCM](https://docs.rundeck.com/docs/administration/projects/scm/#scm) Export in the following way:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/94031641-7a2dd580-fd95-11ea-8058-a3df660107d7.png)

4. Now you can export your jobs to your GIT repo.

Hope it helps!

**Comment by EugenMayer** [comment]
I have the same issues after migrating from bitbucket ( server ) to github.com - both are using an SSH based authentication.

While i used `ssh://git@domain:port/path` with bitbucket .. this leads to an fetch-issue when used with github ( which is very odd already ), so `ssh://git@github.com/company/rundeck` fails with

```
Failed cloning the repository from ssh://git@github.com:company/rundeck.git: Exception caught during execution of fetch command 
```

Using `git://github.com/company/rundeck` fails with 

```
Failed cloning the repository from git//github.com:company/rundeck.git: Invalid remote: origin
```

My key is a file-upload key directly from my .ssh folder which works when using on the cli, so no way i got an newlines or wrong character in during c&p.

**Comment by EugenMayer** [comment]
Ok the reasons for me was https://github.com/rundeck/rundeck/issues/4813#issuecomment-491297009 .. and that is very unfortunate since there is 0 documentation about that, neither as field doc nor anywhere else. This should be documented right when selecting the private field i guess

**Comment by EugenMayer** [comment]
I addition, you are must not provide the protocol, you do not use `git://` or `ssh://` you use what you get from the github clone page directly `git@github.com:company/repo.git` - again very unusual especially when considering the field help, which is entirely missleading in this case ( once again)

**Comment by DeLoWaN** [comment]
I ended up not using the Git plugin so I won't spend any more time on that issue. Thank you for your analysis @EugenMayer I hope it will be usefull to other people.

**Comment by EugenMayer** [comment]
why are you closing this issue? even though you are not using this plugin anymore, others might do an are interested in a fix for that?

**Comment by mfreeman451** [comment]
having the same issue, looks like some people been experiencing this for 5 years.

**Comment by Aj7Ay** [comment]
Facing the same issue 
even if i use rsa keys and added to key storage and gitlab
