### ISSUE TITLE
Execution logs shows multible HHH90000022 warnings

### ISSUE THREAD

**Issue by csimader** [rundeck/rundeck#6482]
**Describe the bug**
After upgrade from 3.1. to 3.3.1

**My Rundeck detail**

* Rundeck version: [ 3.3.1]
* install type: [war]
* OS Name/version: [Linux -64]
* DB Type/version: [mysql]

**To Reproduce**
Just run a job - Waring 
HHH90000022: Hibernate's legacy org.hibernate.Criteria API is deprecated; use the JPA javax.persistence.criteria.CriteriaQuery instead
are shown everytime - every job

**Expected behavior**
we add to $RD_HOME/rundeck/server/config/log4j.properties
log4j.logger.org.hibernate=ERROR,stdout
log4j.additivity.org.hibernate=false

Without any change - warings are shown

**Screenshots**

![image](https://user-images.githubusercontent.com/8567019/94013846-f8e13d80-fdaa-11ea-949e-facfedd1ade4.png)

**Comment by MegaDrive68k** [comment]
Hi @csimader 

Remember that 3.3.X uses log4j2, take a look at [this](https://docs.rundeck.com/docs/upgrading/upgrading-to-rundeck-3.3.html#log4j-2-notes).

Also, check your `log4j2.properties` file and make sure you have the following entries:

```
logger.hibernate.name = org.hibernate.orm.deprecation
logger.hibernate.level = error
logger.hibernate.additivity = false
logger.hibernate.appenderRef.stdout.ref = STDOUT
```

Hope it helps!

**Comment by csimader** [comment]
Solved my problem by change log4j.properties to log4j2.properties.
The Doc.:
..
If you are using the launcher or war in a container, the first time you run Rundeck 3.3.x a log4j2.properties file will be created for you.
..
is not fully correct - log4j2.properties was not created - we must create the file.
Thanks for fast help
Christian

**Comment by csimader** [comment]
thanks @MegaDrive68k problem is solved
