### ISSUE TITLE
cant authorize LDAP user to a particular project 

### ISSUE THREAD

**Issue by avnban1988** [rundeck/rundeck#6487]
**Describe the bug**

**My Rundeck detail**

* Rundeck version: [ e.g. 2.11.3]
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [e.g. ubuntu 16.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @avnban1988 

Check [this](https://groups.google.com/g/rundeck-discuss/c/IbbNezfKOwA/m/JwPeq3ceAQAJ) ACL example. And [here](https://stackoverflow.com/questions/64038546/rundeck-with-ldap-and-project-wise-security) an explanation about LDAP+ACL configuration with example.

Hope it helps!

**Comment by avnban1988** [comment]
Is there a way to authenticate with LDAP and authorize from Rundeck like using realm.properties
