### ISSUE TITLE
not working plugin rundeck-jdbc-executor-plugin

### ISSUE THREAD

**Issue by ext94053** [rundeck/rundeck#6499]
rundeck-jdbc-executor-plugin

Describe the bug
I create job with rundeck-jdbc-executor-plugin but not working

My Rundeck detail

Rundeck version: 3.2.8
install type: jar
OS Name/version: Red Hat Linux 6
DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]
To Reproduce

Install Plugin
Copy ojdbc6.jar and groovy-sql-2.4.11.jar in tools/lib
Create Job with step "Groovy sql script executor"
Execute the job

The error is Failed: ConfigurationFailure: com.dtolabs.rundeck.core.plugins.configuration.ConfigurationException: Unknown database type:null

**Comment by MegaDrive68k** [comment]
Hi @ext94053 

Please open a new issue on the plugin author GitHub space [here](https://github.com/strdn/rundeck-jdbc-executor-plugin/issues).

It seems that need an update.

Regards!
