### ISSUE TITLE
2.0: OutOfMemory after use of FileCopier plugin

### ISSUE THREAD

**Issue by Shadoka** [rundeck/rundeck#650]
I'm running RunDeck 2.0.0 on Solaris 11 with Java 1.6.0_51 and I'm getting these exceptions after using the FileCopier Plugin:
http://pastebin.com/17Q0NXx4

This error occurred independently from the file size, I tried a 800MB file as well as a 100MB file.

I increased the available JVM-Memory to 1 GB after this incident, which should be sufficient for the management of two nodes, but the outcome was the same.

I also keep receiving such errors randomly in the log file:
http://pastebin.com/aabcaXsg

**Comment by ahonor** [comment]
Rundeck now requires java 1.8+
