### ISSUE TITLE
Slow memory leak with heap?

### ISSUE THREAD

**Issue by xi-ao** [rundeck/rundeck#6517]
**Describe the bug**

We're having trouble leaving the Rundeck server up for more than a few days (usually 8-9 with 4 GB of RAM). If we don't restart it regularly, we end up with a `java` process eating up almost 100% of the CPU and more or less a crash (GUI not responding, jobs not started, etc.).  
After analysis, it seems to be caused by the GC when getting short on memory (heap).

We have ~100 jobs with approx. 50% scheduled. Some are run every 15m, some others only once a day or so.

We have ~10 nodes where the real actions are performed via scripts, triggered via Rundeck. Some daily scripts may produce a few megabytes of log (roughly from 1 to 20).

Things we tried:
- Increase allocated memory (from 1 GB to 4GB now, it just delays the crash)
- Stop attaching logs to notification emails (no visible change)
- Pruning executions more aggressively (we still have between 200K and 300K executions in the table but it's "normal")
- Update Rundeck to the latest version available, hoping it would help, because we always had this issue in the past (we started with version ~2.3 and updated several times).

The JVM is now closely monitored using Prometheus so we can anticipate when the crash is going to occur. The screenshots below may help understanding how it happens. At the time they were taken we can estimate we still have 2 to 3 days before restarting the server.

**My Rundeck detail**

* Rundeck version: 3.3.1
* install type: deb
* OS Name/version: Ubuntu 16.04.6
* DB Type/version: mysql
* Command:
  ```
  java -Drundeck.jaaslogin=true
  -Djava.security.auth.login.config=/etc/rundeck/jaas-loginmodule.conf
  -Dloginmodule.name=RDpropertyfilelogin
  -Drdeck.config=/etc/rundeck
  -Drundeck.server.configDir=/etc/rundeck
  -Dserver.datastore.path=/var/lib/rundeck/data/rundeck
  -Drundeck.server.serverDir=/var/lib/rundeck
  -Drdeck.projects=/var/lib/rundeck/projects
  -Drdeck.runlogs=/var/lib/rundeck/logs
  -Drundeck.config.location=/etc/rundeck/rundeck-config.properties
  -Djava.io.tmpdir=/tmp/rundeck
  -Drundeck.server.workDir=/tmp/rundeck
  -Dserver.http.port=4440
  -Drdeck.base=/var/lib/rundeck
  -Drundeck.jetty.connector.forwarded=true
  -Xmx4096m
  -Xms256m
  -XX:MaxMetaspaceSize=256m
  -server
  -jar /var/lib/rundeck/bootstrap/rundeck-3.3.1-20200727.war
  --skipinstall
  ```

**Screenshots**
From the last restart (no crash yet):
![Screenshot_2020-10-02 JVM dashboard (batch) - Grafana](https://user-images.githubusercontent.com/1862773/94893220-f2c41e80-0486-11eb-86c0-c567a31be70e.png)
![Screenshot_2020-10-02 JVM dashboard (batch) - Grafana(1)](https://user-images.githubusercontent.com/1862773/94893221-f35cb500-0486-11eb-9974-9e588ee6854c.png)
![Screenshot_2020-10-02 JVM dashboard (batch) - Grafana(2)](https://user-images.githubusercontent.com/1862773/94893218-f2c41e80-0486-11eb-8a44-a57f1cce3d60.png)
![Screenshot_2020-10-02 JVM dashboard (batch) - Grafana(3)](https://user-images.githubusercontent.com/1862773/94893216-f22b8800-0486-11eb-8e1f-4fc23fac874b.png)

The last run until crash (which occurred a few days ago):
![Screenshot_2020-10-02 JVM dashboard (batch) - Grafana(4)](https://user-images.githubusercontent.com/1862773/94893779-42efb080-0488-11eb-9d22-16705a5dfb07.png)
![Screenshot_2020-10-02 JVM dashboard (batch) - Grafana(5)](https://user-images.githubusercontent.com/1862773/94893780-43884700-0488-11eb-8e07-8ee73c47151c.png)
![Screenshot_2020-10-02 JVM dashboard (batch) - Grafana(6)](https://user-images.githubusercontent.com/1862773/94893777-42efb080-0488-11eb-9436-c75b798a8a03.png)
![Screenshot_2020-10-02 JVM dashboard (batch) - Grafana(7)](https://user-images.githubusercontent.com/1862773/94893775-42571a00-0488-11eb-9cc2-5df3b47043d0.png)

I hope I didn't miss any important info. I'll add more if needed.

Regards

**Comment by xi-ao** [comment]
We've just updated Rundeck to 3.3.4. We'll see how it's doing in the next days.

**Comment by fdevans** [comment]
There will be more performance improvements in the 3.3.5 release as well.

**Comment by xi-ao** [comment]
Since the update to 3.3.4, here's how it's going:

![image](https://user-images.githubusercontent.com/1862773/96218891-f925c080-0f85-11eb-849d-8dc2900fb502.png)

![image](https://user-images.githubusercontent.com/1862773/96218937-1195db00-0f86-11eb-964e-b0b4046ee68b.png)

![image](https://user-images.githubusercontent.com/1862773/96218970-1f4b6080-0f86-11eb-8e2c-2ec23a90c4da.png)

As visible on the first screen, the heap is still slowly increasing. Maybe slower than before, but we can't be too conslusive as we also changed some jobs scheduling in the meantime.

**Comment by xi-ao** [comment]
Although I don't want to sound over-optimistic, it does seem better with version 3.3.4 since I can now see some significant memory release each time the occupation rises above 50%.

![image](https://user-images.githubusercontent.com/1862773/96687255-ee04d300-137f-11eb-8324-8f30ce4489ae.png)

We've also changed a lot of jobs scheduling on our side so it might not be a 100% accurate observation.

**Comment by xi-ao** [comment]
Up for 16 days now and counting. Seems to be okay.  
GC now seems to free up enough memory when needed.

![image](https://user-images.githubusercontent.com/1862773/97534705-be2a8080-19ba-11eb-8eeb-34c37f7bd20d.png)

![image](https://user-images.githubusercontent.com/1862773/97534713-c1257100-19ba-11eb-920b-c94bb7741561.png)
