### ISSUE TITLE
SetUp new schedule on specific day (or month) don't work anymore

### ISSUE THREAD

**Issue by philjov** [rundeck/rundeck#6533]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.3.3
* install type: rpm
* OS Name/version: OL 7.8 (RedHat like)
* DB Type/version: PG 10.6

**Expected Behavior**

New Job / Schedule to run repeatedly = Yes / uncheck "every day" or "every month"
=> select days of the week, or month of the year

**How to Reproduce**

When you uncheck "every day" or "every month" the list of days/months don't apprears

Workaround: build a crontab manually / Prefered by Linux SysAd but sound like Chinese for end user.

**Comment by MegaDrive68k** [comment]
Confirmed:

On 3.1.X:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/95334290-4cac5600-0884-11eb-8783-92e112e926fa.png)

On 3.2.X:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/95334296-4f0eb000-0884-11eb-93d3-33737ac3023c.png)

On 3.3.3:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/95334306-51710a00-0884-11eb-8a1a-1ac8802a9243.png)

Thanks for your feedback @philjov

**Comment by arpsyapathy** [comment]
@philjov @gschueler @ProTip 
Hi! I have same problem on 3.4.1 Community version
