### ISSUE TITLE
vendor.js is not hosted

### ISSUE THREAD

**Issue by halradaideh** [rundeck/rundeck#6538]
**Describe the bug**
after upgrading rundeck from 3.2 to 3.3, rundeck start to behave really slow

i noticed that from the browser that vendor.js is not found on the server

Request URL: https://rundeck-sc.atypon.com/assets/static/vendor.js

**My Rundeck detail**

* Rundeck version: [ e.g. 3.3.3]
* install type: docker-container
* DB Type/version: mysql

**Screenshots**
![image](https://user-images.githubusercontent.com/43438708/95436678-c748a480-095c-11eb-913d-e00ac847008a.png)

**Desktop**
 - OS: Ubuntu
 - Browser chrome

**Comment by MegaDrive68k** [comment]
Hi @halradaideh 

Check [this](https://github.com/rundeck/rundeck/issues/6411#issuecomment-701330906) solution. Looks like the same issue.

Hope it helps!

**Comment by MegaDrive68k** [comment]
Hi @halradaideh 

Check [this](https://github.com/rundeck/rundeck/issues/6411#issuecomment-701330906) solution. Looks like the same issue.

Hope it helps!

**Comment by halradaideh** [comment]
> Hi @halradaideh
> 
> Check [this](https://github.com/rundeck/rundeck/issues/6411#issuecomment-701330906) solution. Looks like the same issue.
> 
> Hope it helps!

nope, it did not

i am using docker version of rundeck and the directory have the up-to-date plugins there only
![image](https://user-images.githubusercontent.com/43438708/95457091-0be23900-0979-11eb-8080-bac55e27bf7c.png)

**Comment by halradaideh** [comment]
@gschueler  any thoughts ?

**Comment by MegaDrive68k** [comment]
Hi @halradaideh 

Your rundeck instance is behind of proxy server? I see the same behavior (only on Chrome, on Firefox works normally). But I fix it setting `RUNDECK_GRAILS_URL` docker parameter with Rundeck proxy exit URL (like [this](https://groups.google.com/g/rundeck-discuss/c/I94cVxK_6kQ/m/0a3PPyygAwAJ)) . Anyway, the vendor.js file still missing.

Regards.

**Comment by halradaideh** [comment]
it is proxied behind Traefik ingress controller in kubernetes ( it is deployed in kubernetes )

btw, it was working before the upgrade on version 3.2.0, after the upgrade to 3.3.x it start to stuck at loading

the parameter is defined properly ..
