### ISSUE TITLE
Separated email for multiple email notification recipients

### ISSUE THREAD

**Issue by 0xbentang** [rundeck/rundeck#6566]
**Describe the bug**
In email notifications we can specifiy multiple recipients by a comma
However, when the email is sent, it's sending an email to each recipient, instead of sending one single email to both recipients

**My Rundeck detail**

* Rundeck version: [ e.g. 3.3.3]
* install type: [docker]
* OS Name/version: [e.g. ubuntu 18.04]
* DB Type/version: [mysql]

**To Reproduce**
1. Go to Notifications
2. Enable **On Start** email
3. **To:** a@email.com,b@email.com (send to 2 different email addresses)
4. Got 2 emails for each recipient

**Expected behavior**
There should only be one single email

**Screenshots**
N/A

**Comment by yjacknewton** [comment]
I have this too.
I want rundeck to send a single email to all recipients
