### ISSUE TITLE
Default "Enter" key not working on Search window

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6571]
This was working fine until we upgraded to the latest version 3.3.4. We were able to press "Enter" during the Job search window. 
Now we have to click the Search button not so efficient ;)

![image](https://user-images.githubusercontent.com/20629911/96510617-a4e34080-1212-11eb-9ba8-6d45f585d258.png)

![image](https://user-images.githubusercontent.com/20629911/96510702-c9d7b380-1212-11eb-8dac-6eec047cc788.png)

Thank you,
HS

**Comment by hs-hub-world** [comment]
Looks like the same is happening on the Node Filter. When entering the override node pressing "Enter" key does not do anything. 
![image](https://user-images.githubusercontent.com/20629911/96511130-77e35d80-1213-11eb-92be-3f0fb34d13c8.png)

**Comment by MegaDrive68k** [comment]
True. It would be good to improve the search experience with the Enter key.

Thanks for your feedback @hs-hub-world!
