### ISSUE TITLE
Support for management of rundeck instances across multiple data centers

### ISSUE THREAD

**Issue by btck30351** [rundeck/rundeck#6581]
IMPORTANT: Please search the existing Issues and look at the [Trello board](https://trello.com/b/sn3g9nOr/rundeck-development) for your idea before posting.

**Is your feature request related to a problem? Please describe.**
Let's say we have dc1 and dc2.

Right now we don't have a way to manage jobs with a single GUI

We have to: login rundeck at dc1 to modify dc1 jobs,

and login rundeck at dc2 to modify dc2 jobs

**Describe the solution you'd like**
Provide a way to connect rundeck instances across DCs, then we can label the job to decide which rundeck instance to execute the job

**Describe alternatives you've considered**
* enterprise cluster seems to have similar feature, but it's more like intra-dc, not inter-dc

* adding all jobs to dc1 and make them execute on nodes at dc2 is not an option, as it will impose higher risk of network disconnection

**Additional context**

**Comment by fdevans** [comment]
Hi @btck30351.  Clustering support including all these features is available in the Enterprise version of Rundeck.
