### ISSUE TITLE
What is the command used for building the docker image which is in Dockerhub?

### ISSUE THREAD

**Issue by sandeeprapido** [rundeck/rundeck#6597]

**Comment by fdevans** [comment]
Lots of content on our docs site.

https://docs.rundeck.com/docs/administration/install/docker.html#open-source-rundeck

**Comment by sandeeprapido** [comment]
The documentation tells how to run the docker image that is in docker hub. I  have made some changes in the code and want to build an image. Can I get the exact command for that?

**Comment by fdevans** [comment]
Look into the /docker sub folder of the repository.

**Comment by sandeeprapido** [comment]
There are multiple directories. Which docker file I should build?

**Comment by sandeeprapido** [comment]
```
./gradlew officialBuild
```
This command creates an official docker image.
