### ISSUE TITLE
SCM Unable to push to Remote Git SCM

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6598]
We are using TFS with GIT for our SCM repo server. We are using the TFS/GIT with many other platforms without any issue such as VS Code, AWX, Ansible, etc... But for some reason with Rundeck we are unable to push to a remote site. All other SCM funcationlaity works fine with Rundeck only **Remote Push** fails.
Note, all the GIT commands work without any issues directly from the console, I am able to pull, push, fetch when running as the "rundeck" user. So it does not seem to be git and TFS related issue. 

Could you please assist - where else can I check for more errors -?

![image](https://user-images.githubusercontent.com/20629911/98020386-ccf8a500-1db7-11eb-977d-0058738939ca.png)

Rundeck Console Service Logs
![image](https://user-images.githubusercontent.com/20629911/98020584-0c26f600-1db8-11eb-8bdb-a226f7b771a2.png)

![image](https://user-images.githubusercontent.com/20629911/98020732-41334880-1db8-11eb-98d1-eb4a410c6728.png)

Rundeck Version:
![image](https://user-images.githubusercontent.com/20629911/98021113-c0c11780-1db8-11eb-95c9-458c228d4699.png)

![image](https://user-images.githubusercontent.com/20629911/98021158-cdde0680-1db8-11eb-9a44-1a366fea5a92.png)

Thank you!
HS

**Comment by Aj7Ay** [comment]
Facing Same issue
even Gitlab is not working if we add private keys and public keys and used PAT aswell and tried all the ways 
now using GitHub facing same issue
