### ISSUE TITLE
make "file-copy-destination-dir" property setting settable at framework and project level

### ISSUE THREAD

**Issue by mumblez** [rundeck/rundeck#660]
Hi Guys,

As a request, it would be nice to have the property 'file-copy-destination-dir' settable at the framework and project levels, atm it has to be set per node.

Many Thanks
Yusuf

**Comment by ahonor** [comment]
@mumblez 

This is possible at these levels

node: `file-copy-destination-dir`
project: `project.file-copy-destination-dir.$OS_FAMILY`
project: `project.file-copy-destination-dir`
fwk: `framework.file-copy-destination-dir.$OS_FAMILY`
fwk: `framework.file-copy-destination-dir`
