### ISSUE TITLE
"Node Executor configuration was invalid: Invalid provider type: local, not found" [versions 3.3.5, 3.3.4]

### ISSUE THREAD

**Issue by efo1291** [rundeck/rundeck#6614]
**Describe the bug**
When I choose Default Node Executor as **Local** give me a message: "_Node Executor configuration was invalid: Invalid provider type: local, not found_". So I can't use locally.
I have the plugin installed on fresh installation (3.3.5) but not working. On previously versions like 3.3.3, 3.3.0 have worked successfully!

**My Rundeck detail**

* Rundeck version: [ 3.3.5, 3.3.4]
* install type: [apt]
* OS Name/version: [ubuntu 18.04]
* DB Type/version: [jdbc ]

**To Reproduce**
1. Create a simple project with Default Node Executor as **Local**
2. After creating, click on Project Setting > Edit Configuration
3. See error: Node Executor configuration was invalid: Invalid provider type: local, not found

**Expected behavior**
I should be able runs locally, but I can't. 

**Screenshots**
Error: 
![image](https://user-images.githubusercontent.com/44806604/98441432-02193600-20dd-11eb-81a1-b30323fdb7f1.png)

Edit Configuration File:
![image](https://user-images.githubusercontent.com/44806604/98442165-dfd5e700-20e1-11eb-8eb3-c70dd0cb6da1.png)

Installed Plugin GUI: 
![image](https://user-images.githubusercontent.com/44806604/98441477-4efd0c80-20dd-11eb-8e24-49ed7f906429.png)

Libext:
![image](https://user-images.githubusercontent.com/44806604/98441740-021a3580-20df-11eb-9be6-dc5ea45822d0.png)

Locations: 
![image](https://user-images.githubusercontent.com/44806604/98441608-2f1a1880-20de-11eb-8248-c9b344dd46e0.png)

Java:
![image](https://user-images.githubusercontent.com/44806604/98441828-92587a80-20df-11eb-887a-9ecf5f296f28.png)

**Additional context**
I tested in some different versions:
- 3.3.4: same error
- 3.3.3: work successfully
- 3.3.0: work successfully
- 3.2.3: work successfully

**Comment by MegaDrive68k** [comment]
Confirmed, 

Also happening on 3.3.5.

![Screenshot_1](https://user-images.githubusercontent.com/51376003/98537650-513fa200-2268-11eb-82c9-f876d9cb1d9d.png)

[service.log](https://github.com/rundeck/rundeck/files/5510193/service.log)

Thanks for your feedback @efo1291!

**Comment by MegaDrive68k** [comment]
Still happening on 3.3.6.

**Comment by ronaveva** [comment]
Stub node executor shows the same issue.

![imagen](https://user-images.githubusercontent.com/50217398/99537138-0de0e400-298a-11eb-86b0-57458cff1311.png)


Note: looks like executors with no properties required shows this error.

**Comment by efo1291** [comment]
Still happening on 3.3.7.

**Comment by MegaDrive68k** [comment]
Still happening on 3.3.8-rc6.
