### ISSUE TITLE
Rundeck Job View List plugin installation issue

### ISSUE THREAD

**Issue by roboragi** [rundeck/rundeck#6617]
**Bug description/detail**
Hi, I can't install properly Job View List plugin in Plugin Repositories. 

After installing the plugin, you can see below that Rundeck successfully installed the plugin.
![image](https://user-images.githubusercontent.com/51732178/98751861-e2934d80-23fb-11eb-85c5-ebd6536c67cf.png)

Then I checked my project to see the table list view but I can't seem to find it anywhere in my Project.
So I went back to Plugin Repositories, then you can see below that the plugin was not installed though I've clearly installed it before. 
![image](https://user-images.githubusercontent.com/51732178/98751988-39008c00-23fc-11eb-97d8-c19b379323bd.png)

There are no errors that I can see in **service.log**

**My Rundeck detail**
1. Rundeck version: **3.3.5**
2. install type: **war**
3. OS Name/version: **Windows 10 Enterprise 64-bit (10.0, Build 18363)**
4. DB Type/version: **PostgreSQL**

**To Reproduce**
1. Click the gear icon at the right most corner of Rundeck UI
2. Click Plugins, then click Find Plugins
3. Type "Job List View" in the search bar
4. Click install
5. Refresh the page and then once again, type "Job List View" in the search bar

**Expected behavior**
The plugin is "successfully" installed but after refreshing, you will see that the plugin was not installed. 

**Screenshots**
You can refer to the screenshots above I've pasted in **Bug description/detail** section.

**Desktop (please complete the following information):**
 - OS: **Windows 10 Enterprise 64-bit (10.0, Build 18363)**
 - Browser: **Chrome**
 - Version: **Version 86.0.4240.193 (Official Build) (32-bit)**

**Comment by MegaDrive68k** [comment]
Confirm,

That's an odd issue, the [plugin](https://github.com/rundeck-plugins/ui-job-list) cache content isn't created and only happens on Windows-based systems.

Thanks for your feedback @roboragi!
