### ISSUE TITLE
When "sort values" is selected for an option, it doesn't save to the file definition or sort the items when rendered

### ISSUE THREAD

**Issue by FedeHAL** [rundeck/rundeck#6618]
**Describe the bug**
I select "sort values" for an option in a form, save the form, and when I check the form XML/YAML I don't see it on the file, also the option items don't get sorted.

**My Rundeck detail**

* Rundeck version: 3.3.5
* install type: rpm
* OS Name/version: CentOS8
* DB Type/version: postgresql

**To Reproduce**
1. Edit a form, go to workflow.
2. Edit an option, select "sort values".
3. Save the form.
4. Export as XML/YAML.
5. Check file.

**Expected behavior**
The option gets sorted and the file reflects the option selected.

**Screenshots**

Code exported:
```
  - description: Select the environment where to deploy the new VM.
    enforced: true
    label: Environment
    name: environment
    required: true
    valuesUrl: http://localhost:1888/cgi-bin/getOpt.py?opt=env
```

From the gui:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/66088961/98818663-a1ef0080-240a-11eb-9080-7be2c30ebbd5.png">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser safari
 - Version 14

**Additional context**

**Comment by MegaDrive68k** [comment]
Confirmed,

Steps to reproduce:

1) Create a new job with a list option and set "Sort Values" -> "Yes".

![Screenshot_1](https://user-images.githubusercontent.com/51376003/98824336-f34ebe00-2411-11eb-94a8-4d3e16b36d26.png)

2) Export the job and delete the job from the Rundeck instance.

3) Import the saved job, "Sort Values" is defined as "No":

![Screenshot_2](https://user-images.githubusercontent.com/51376003/98824382-05306100-2412-11eb-8bd3-19ea6baea55e.png)

Thanks a lot for your feedback @FedeHAL!
