### ISSUE TITLE
issue editing Node Executor and File Copier for a project

### ISSUE THREAD

**Issue by cwaltherf** [rundeck/rundeck#6620]
**Describe the bug**
When using different settings for the Node Executor and the File copier setting up a project, for example password and privateKey, after saving the project the settings does not remain as they where set.

**My Rundeck detail**

* Rundeck version: Rundeck 3.3.6
* install type: any
* OS Name/version: Ubuntu 20.04 
DB Type/version: any

**To Reproduce**
1. Create a new Project
2. Set up the Node Executor, for example, to use privateKey and SSH Key Storage Path and create a File Copier to use Password and set a SSH Password Storage Path
3. Create the Project
4. Edit the Project and check the Node Executor Settings and the File Copier Settings
The Node Executor and the File Copier are showing the SSH Authentication as password type and also both have settings in the SSH Key Storage PAth and SSH Password Storage Path fields.

**Expected behavior**
Saving the project should save the provided settings for the Node Executor and the File Copier
**Screenshots**

Node Executor settings to save:
![image](https://user-images.githubusercontent.com/36487101/98872815-f8356100-2455-11eb-85d1-f788e48afd89.png)

File Copier settings to save:
![image](https://user-images.githubusercontent.com/36487101/98872831-01263280-2456-11eb-85ce-9b8658328560.png)

Node Executor Settings after saving the Project:
![image](https://user-images.githubusercontent.com/36487101/98872881-19964d00-2456-11eb-8597-86daa7678263.png)

File Copier Settings after saving the Project:
![image](https://user-images.githubusercontent.com/36487101/98872912-2adf5980-2456-11eb-9f6f-0d14c51c1c3f.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu 20.04]
 - Browser [chrome]

**Comment by elioe** [comment]
Still happening in 3.3.10 version

**Comment by ronaveva** [comment]
This is the expected current behavior, documentation has been added to reflect this.
The UI is misleading, a future enhancement is needed to handle multiple plugins with the same properties key name

https://github.com/rundeck/docs/pull/933
