### ISSUE TITLE
Retry on another node

### ISSUE THREAD

**Issue by sfgxuan** [rundeck/rundeck#6624]
Here's the usage situation (Rundeck Version 2.9.3-1):

1. I'm running a Rundeck server with two nodes (node1 and node2)
2. Then I have a job config to run on node1
3. but execution on node1 may fail (ie. power off, network error, os env not correct)

so here's the feature I needed: 
when node1 fail, the job could retry on node2.

I have try the Orchestrator with Random Subset, but it's not exactly the feature I want, it only random choice a node, no matter if a node ever has a failed execution

**Comment by MegaDrive68k** [comment]
Hi @sfgxuan,

You can create a job with a bash script into on [script-step](https://docs.rundeck.com/docs/manual/node-steps/builtin.html#script-step) calling Rundeck the API (or use [RD CLI](https://rundeck.github.io/rundeck-cli/)) which evaluates the last execution on a node on a variable like the following example (i have used [jq](https://stedolan.github.io/jq/) to get the job id and status):
 
```bash
# run the job on node1 and obtain the job id. This call uses a option to pass to a node filter.
execid=$(curl -H accept:application/json --data-urlencode "argString=-thenode node1" http://your_rundeck:4440/api/36/job/your_job_id/run?authtoken=your_user_token | jq -r '.id')

# and later the status
status=$(curl --location --request GET "http://your_rundeck::4440/api/36/execution/$execid/state?authtoken=your_user_token" | jq -r '.executionState')
```

So, depending of `$status` [value](https://docs.rundeck.com/docs/manual/07-executions.html#completed), you can run the same job on node2.

Hope it helps!
