### ISSUE TITLE
Progress bar big log stuck -1%

### ISSUE THREAD

**Issue by ronaveva** [rundeck/rundeck#6625]
**Describe the bug**
When the log file is too big and rundeck offers the download option intead of show the log, the progress bar gets stuck in -1% (the job finishes ok, is just the progress bar)

**My Rundeck detail**

* Rundeck version: 3.3.6
* install type: war
* OS Name/version: ubuntu 20.04
* DB Type/version: h2

**To Reproduce**

1. Create a job that can generate a large log file (tried with 3.61mb)
2. Go to the execution log output

**Expected behavior**
The progress bar should not be there.

**Screenshots**

![imagen](https://user-images.githubusercontent.com/50217398/99253827-2fa66380-27f0-11eb-9114-ea7363d35e45.png)

**Comment by MegaDrive68k** [comment]
Still happening on 3.3.7-RC2

![Screenshot_2](https://user-images.githubusercontent.com/51376003/101231826-918a1880-368c-11eb-8eec-175fa625631e.png)

**Comment by gschueler** [comment]
fixed in 3.4.0

**Comment by gschueler** [comment]
ref https://github.com/rundeck/rundeck/pull/7055
