### ISSUE TITLE
Inconsistent time zone display in Rundeck UI when system timezone is UTC

### ISSUE THREAD

**Issue by JongleurNin** [rundeck/rundeck#6626]
**Describe the bug**
Some dates and times displayed in the application use UTC, and others use local time of the server (or perhaps the time zone of the user's browser), even within the same screen. This is confusing to users who need to verify when a job is next scheduled to execute, and when a job last executed.

**My Rundeck detail**
* Rundeck version: 3.3.6-rc4-20201109 (onion ring rosybrown knight)
* build.core.git.branch: refs/tags/v3.3.6-rc4, HEAD
* build.core.git.commit: 4c0f02c52cb4150726c794612e385ffb3ccc0ecd
* build.core.git.description: v3.3.6-rc4-0-g4c0f02c
* build.ident: 3.3.6-rc4-20201109

* Install type: war, via Docker
* OS Name/version: 18.04.4 LTS (Bionic Beaver), Dockerized
* Time zone of Dockerized OS: UTC (verified by using `docker container exec -it rundeck /bin/bash
`, then `date` command once attached.
* DB Type/version: mssql

**To Reproduce**
1. Log into Rundeck, create a project and some jobs within it.
2. Enable some jobs for scheduled execution.
3. From the jobs list, verify that the number of hours until the next execution are correct.
4. Mouse over the "in <xx>h <yy>m" portion and verify that the OS system time zone (or perhaps always UTC?) is used for the time
![image](https://user-images.githubusercontent.com/7306738/99302610-73a36380-2804-11eb-90f8-6c66decd0520.png)
5. View the job details.
6. Verify that there is a mixture of Rundeck server OS (or UTC?) dates and local browser dates comingled within the same screen.
![image](https://user-images.githubusercontent.com/7306738/99303208-63d84f00-2805-11eb-93bc-1bce7586020f.png)

**Expected behavior**
In steps 4 and 6, all times (and timezones) should be displayed in the user's local timezone, based on the browser time zone settings (which in turn are often based, by default, on the time zone settings of the OS of the user who is accessing Rundeck).

**Screenshots**
![image](https://user-images.githubusercontent.com/7306738/99302610-73a36380-2804-11eb-90f8-6c66decd0520.png)

![image](https://user-images.githubusercontent.com/7306738/99303208-63d84f00-2805-11eb-93bc-1bce7586020f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 1909 (OS Build 18363.1139)
 - Browser: Microsoft Edge (Chromium Version)
 - Version: 86.0.622.69 (Official build) (64-bit)

**Additional context**
This makes it confusing for users to tell when their jobs will run next, and when they ran in the past. Our users span the entire world in terms of time zones, so TZ display that depends on the time zone of the server hosting Rundeck should never be displayed as is, always converted to the user's browser's time zone.

**Comment by MegaDrive68k** [comment]
Hi @JongleurNin 

This issue is reported here: https://github.com/rundeck/rundeck/issues/6582

And here the WIP fix: https://github.com/rundeck/rundeck/pull/6587

Thanks for your feedback!
