### ISSUE TITLE
Unable to display all scheduled jobs

### ISSUE THREAD

**Issue by billbok** [rundeck/rundeck#6630]
Hello, 

I have several ten scheduled jobs and I can't display these jobs through the interface. I am limited to the last 20 scheduled jobs.

**My Rundeck detail**

* Rundeck version: 3.2.7
* install type: war
* OS Name/version: centos 7
* DB Type/version: mysql

**To Reproduce**
1. Create 30 scheduled jobs
2. Click on Activity
3. You can't see all scheduled job and you can't filter by scheduled job

ex: 
I've 91 scheduled jobs in <my_project> project

$ **rd executions query -m 100 -p <my_project> -s running**
Paged results 0 - 91 (of 91 by 100).
1929740 scheduled 2020-12-10T11:05:0
....

but in the GUI:

![Capture d’écran de 2020-11-19 12-14-48](https://user-images.githubusercontent.com/12501919/99659255-e14bcb80-2a60-11eb-9cd0-42389a36ab4e.png)

**Comment by MegaDrive68k** [comment]
Hi @billbok 

It seems the same as https://github.com/rundeck/rundeck/issues/6206

Regards.

**Comment by billbok** [comment]
Hi,

Indeed, it is the same problem ...
Sorry, I had yet searched if the bug had not been reported ...

Should I close this issue?

Regards,

**Comment by MegaDrive68k** [comment]
Done :-)

We will follow up on the original [thread](https://github.com/rundeck/rundeck/issues/6206).

Thanks a lot!
