### ISSUE TITLE
Deactivating of an sheduled job doesn't work

### ISSUE THREAD

**Issue by sheepchen** [rundeck/rundeck#6631]
**Describe the bug**
Hi.
I have a Job that runs a script on differend Servers. This is all fine.
At the moment I dont want to run the job (but not delete it!).

I have set the following schedule-options:

 Schedule to run repeatedly? yes
(cron style)
Enable Scheduling? No
Enable Execution? No

**My Rundeck detail**
* Rundeck version: 3.3.2

**To Reproduce**
Create Task like run bashscript on servers.
Then let the job run via scheduler some times (in my case every 10 minutes [0 00/10 * ? * * *])
Then set "Enable Scheduling? No"

**Expected behavior**
Job should not run at sheduled time.

**real behaviour**
Job runs as "Enable Scheduling" is activated.

**Additional context**
deactivating "Schedule to run repeatedly" is a solution, but this removes the entry in 'cron style time'

**Comment by MegaDrive68k** [comment]
Hi @sheepchen 

Could you try with the latest Rundeck version? It seems [this](https://github.com/rundeck/rundeck/issues/6357) fixed issue.

Regards.

**Comment by sheepchen** [comment]
Hi,
thanks for the fast reply.

Unfortunally its not so easy. There are multiple teams on the rundeck server with hundreds of jobs. 
I created a ticket by the team that maintain the rundeck server but this can take weeks/month.

This ticket can be closed.

Thanks :)
