### ISSUE TITLE
Preauthentication mode + Token authentication at the same time

### ISSUE THREAD

**Issue by fuero** [rundeck/rundeck#6636]
What I want to accomplish: have preauthentication and token authentication working at the same time

What I did:

I set up a rundeck instance in preauthentication mode, which works fine for authenticating users.

Authenticating with a token though doesn't seem to work in that mode. Am I missing something here?
Disabling preauth allows the token authentication to succeed.

Furthermore, the complete setup adds apache as reverse proxy + shibboleth sp and adds another problem:

I'd need a "redirectLogin" property similar to "redirectLogout/redirectUrl", as I can either enforce a Shibboleth session or wait for the user to be redirected to /Shibboleth.sso/Login to properly initiate the login flow.

For now, It's set up to force authentication via Shibboleth when accessing "/menu".

**Comment by fukawi2** [comment]
@fuero Did you ever figure this out?
