### ISSUE TITLE
Sorting job options from remote url

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6637]
Hi, is it possible to sort the job options from a remote URL -?  Right now I can't figure out how the sorting works it's neither alphabet nor numeric -? Is there some kind of manual override to persist remote key/value order -?

Thank you,
HS

**Comment by ProTip** [comment]
@hs-hub-world There may not be any sorting going on. If you use the _name value list_ format are you able to control the order? ie:

```
[
  {"name":"X Label", "value":"x value"},
  {"name":"Y Label", "value":"y value"},
  {"name":"A Label", "value":"a value"}
]
```

**Comment by hs-hub-world** [comment]
@ProTip  Thank you Greg, that helped, I had the "name" and "value" orders mixed up.
in case anyone else goes through it.

##incorrect
[
    {"value":"X Label", "name":"x value"},
    {"value":"Y Label", "name":"y value"},
    {"value":"A Label", "name":"a value"}
]

##correct
[
    {"name":"X Label", "value":"x value"},
    {"name":"Y Label", "value":"y value"},
    {"name":"A Label", "value":"a value"}
]


issue: 
In Powershell I was initializing empty hash ($ResObj =@{}) then dynamically associating properties, I guess that would not keep the property orders. Now I am initializing the hash with properties ($ResObj = "" | select name,value)
In the image below if you uncomment first line and comment second line you'll see the problem.
![image](https://user-images.githubusercontent.com/20629911/102628939-54e40580-40ff-11eb-8d3d-e9239641e740.png)
return  ConvertTo-Json @($ResArtifactList)
