### ISSUE TITLE
SCM Import status reset after restart

### ISSUE THREAD

**Issue by LoneGumMan** [rundeck/rundeck#6651]
**Describe the bug**
The SCM (git) import status of jobs are reset after Rundeck instance is restarted.

**My Rundeck detail**
* Rundeck version: 3.3.1 
* install type: official Docker image, rundeck/rundeck:3.3.1 (reproducible 3.3.6 as well)
* OS Name/version: RHEL 7.7
* DB Type/version: posgtresql

**To Reproduce**
1. Create a new project; configure SCM to import job definition from a git repository: 
  a. pull automatically
  b. fetch automatically
  c. UUID Import behavior: remove
  d. No SCM export.
2. Navigate to 'JOBS' page, perform the initial import.
3. All jobs should be sync'd up, no pending "SCM Import Actions" under the "Job Actions" drop down
4. Restart the server
5. Navigate to the "JOBS" page of the project
6. Click on "Job Actions", Wait for SCM Import Actions to finish loading
7. Observe:
   a. all jobs are marked with a question mark icon, "Not Tracked for SCM Import" 
   b. there is a blue exclamation mark next to "Job Actions", "N unimported file(s) found, N traked files(s) were deleted"
   c. "Job Actions" -> "Import Remote Changes" is enabled

**Expected behavior**
1. Given no change was made to a job's definition in the source git repo, a job should retain its "imported" status after restart.
2. If a job has changed in source git repo, it should be highlighted as requiring import, as per normal behavior.

**Screenshots**
After restart, jobs are shown as requiring import (apologies for the obfuscation) 
![image](https://user-images.githubusercontent.com/3841317/100843597-8b8e0f00-34b5-11eb-8bf9-38f83d57d4f0.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 86

**Additional context**
1. Rundeck container is started mounting host volumes for "/home/rundeck/.config" and "/home/rundeck/projects" so SCM related storage is persistent between restart. 
2. Tried without the backing volume as well, same observation
3. Also tried with setting "Fetch: Auto" + "Pull: Manual" in SCM Import. Same observation.

**Comment by LoneGumMan** [comment]
Did anyone have any luck reproducing this? 
Having all the job definition forgotten on every restart is quite inconvenient.

I am still seeing the same behavior with 3.3.10 docker image, i.e. `rundeck/rundeck:3.3.10`

**Comment by josemrs** [comment]
Sorry to say, this has happened to us, we added a script to reimport jobs on restart. Sorry I cannot be more helpful

**Comment by cdstg** [comment]
Started happening to me on 3.40 but after import now I get 
Delete needed X tracked files were deleted and I cant see a way  out of this

**Comment by jjethwa** [comment]
Ran into this on my setup. 

Add `rundeck.server.uuid` to your framework.properties.  You can get your server UUID from the System Report page.
```
rundeck.server.uuid = <YOUR_CURRENT_RUNDECK_UUID>
```
