### ISSUE TITLE
yum update updates the configuration files of rundeck & unable to revert back

### ISSUE THREAD

**Issue by smoolya17** [rundeck/rundeck#6652]
The Production Rundeck server installation runs in this environment:

CentOS Linux release 7.7.1908 (Core)
Rundeck 3.1.2-20190927

I apply `yum update` and the rundeck server alongwith dependencies & configuration files get updated to the latest version. This resulted in rundeck job failures, & resulted in a downtime of around 1 hour and the failover to complete. Is there a way to restore rundeck back to the same original condition ?

**Describe alternatives you've considered**
Since the server is in cloud, we launched a backup ami & disk to relaunch all the services running on the server & restore it.

**Comment by MegaDrive68k** [comment]
Hi @smoolya17 take a look at [this](https://access.redhat.com/solutions/29617). Also, always keep safe your instance with some [backup](https://docs.rundeck.com/docs/administration/maintenance/backup.html#backup) policy.
