### ISSUE TITLE
Add variable with all options

### ISSUE THREAD

**Issue by S0LERA** [rundeck/rundeck#6656]
Issue type: Enhancement Request

**My Rundeck detail**
* Rundeck version: 3.3.7
* install type: (rpm)
* OS Name/version: Centos 7
* DB Type/version: mysql

Hello,
I think it would be great if you could access a "dictionary" with all the options that are stated in a job. So that from a script, for example, you can iterate on all the options without having to reference a specific one. A multi-valued option is discarded because you can not work with lists of safe values.

For example, in python script:
```
for option in @options@:
    print(option.name)
    print(option.value)
```

**Comment by gaddman** [comment]
Yeah, this would help for using options in a jinja template. Likewise, it would be great to have the job and node attributes as dictionaries. I guess a workaround is to get them from the environment variables, eg:
```
import os
allvars = os.environ
job={key[7:]:value for key,value in allvars.items() if key.startswith('RD_JOB_')}
node={key[8:]:value for key,value in allvars.items() if key.startswith('RD_NODE_')}
option={key[10:]:value for key,value in allvars.items() if key.startswith('RD_OPTION_')}
print(job)
print(node)
print(option)
```

**Comment by S0LERA** [comment]
Hi, any updates on this?
