### ISSUE TITLE
Builder GPG key expired

### ISSUE THREAD

**Issue by BastienM** [rundeck/rundeck#6657]
**Describe the bug**
The GPG key of the builder is expired since yesterday.

**To Reproduce**
1. Download the GPG key from `https://docs.rundeck.com/keys/BUILD-GPG-KEY-Rundeck.org.key` or `https://bintray.com/user/downloadSubjectPublicKey?username=rundeck`
2. Check the key details

**Expected behavior**
Expect the key to not be expired.

**Screenshots**
Started with our Ansible role having issue importing the key
```sh
failed: [default] (item={'url': 'http://rundeck.org/keys/BUILD-GPG-KEY-Rundeck.org.key', 'id': '85E9DBC74FCB329EDEDADD2E90770E1BE2D1065B'}) => {"ansible_loop_var": "item", "changed": false, "id": "85E9DBC74FCB329EDEDADD2E90770E1BE2D1065B", "item": {"id": "85E9DBC74FCB329EDEDADD2E90770E1BE2D1065B", "url": "http://rundeck.org/keys/BUILD-GPG-KEY-Rundeck.org.key"}, "msg": "key does not seem to have been added"}
```

Then downloading and checking locally the key
```sh
$ wget https://docs.rundeck.com/keys/BUILD-GPG-KEY-Rundeck.org.key
$ gpg --dry-run --with-fingerprint BUILD-GPG-KEY-Rundeck.org.key  
gpg: WARNING: no command supplied.  Trying to guess what you mean ...
pub   rsa4096 2015-06-04 [SC] [expired: 2020-12-02]
uid           Rundeck Build (automated builds) <build@rundeck.org>
sub   rsa4096 2015-06-04 [E] [expired: 2020-12-02]
```

**Additional context**
Target OS : Debian Buster

**Comment by ProTip** [comment]
@BastienM Thank you for reporting this. The key has been extended and re-uploaded!

**Comment by sephiroth1395** [comment]
The key is OK on rundeck.com but I still get an expired key from bintray.com.  Moreover, I still cannot update the repo for this very reason.
