### ISSUE TITLE
Preauth headers authenticate with ldap authorize

### ISSUE THREAD

**Issue by matthiasblomme** [rundeck/rundeck#6661]
I have a question regarding preauth headers AND authorization via ldap groups.
Is it at all possible to combine the preautheanticated headers with only the user name, and then use ldap lookup to retreive the groups and use these groups to authorize users for specific projects.

It appears that you have to specify both the userNameHeader and the userRolesHeader in order to be allowed to login.

My setup works, I'm able to login via ldap or via preauth headers, but I'm looking for a way to use the preauth headers just to login/authenticate, and use the LDAP plugin to actual get my groups from ldap and use these groups to grant access to certain projects.

**Comment by sjrd218** [comment]
You can accomplish what you are wanting by implementing your own User Group Source Plugin(https://docs.rundeck.com/docs/developer/13-user-group-source-plugin.html#about). Your User Group Source plugin would take the username passed to it, do the group lookup off your ldap server, then return the groups from the plugin.

**Comment by smiller171** [comment]
I've been trying to implement a User Group Source plugin, but the functionality seems to be completely broken, at least for script plugins, and it's not even on the list of supported script plugins despite its own documentation page stating that you can use a script plugin.

https://docs.rundeck.com/docs/developer/01-plugin-development.html#script-plugin-development
