### ISSUE TITLE
Rundeck SCM import plugin not working. Jobs are marked as "Not tracked for SCM import". SCM export is working as expected

### ISSUE THREAD

**Issue by dhillon414** [rundeck/rundeck#6665]
Issue type: Bug report/Enhancement Request

Modified code is copied from GIT to local checkout directory but its not getting reflected in Job's definition. If I do mouseover on Job its showing "Export status : Clean, Not tracked for SCM import"
-->

**My Rundeck detail**

* Rundeck version:  3.3.5
* install type: (rpm,deb,war,launcher?) : war
* OS Name/version:  Linux 7
* DB Type/version: Oracle 19c

**Expected Behavior**
Modified code on git should get reflected to rundeck job's definition.

**How to Reproduce**
Modify code on git lab.
Its get copied to local check out directory but rundeck job still showing old definition.

**Comment by MegaDrive68k** [comment]
Hi @dhillon414 

Could you test with a fresh test instance? Your instance is a single WAR instance? no special configuration?

I tested with Gitlab repository and works ok (on 3.3.5 and 3.3.6):

![Screenshot_1](https://user-images.githubusercontent.com/51376003/101786286-81cf6180-3adc-11eb-8f0e-b520a544b6ad.png)

![Screenshot_2](https://user-images.githubusercontent.com/51376003/101786293-83008e80-3adc-11eb-94f8-31d30c6adfe0.png)

Regards!
