### ISSUE TITLE
SCM icons lost after 3.3.7 upgrade

### ISSUE THREAD

**Issue by gaddman** [rundeck/rundeck#6668]
**Describe the bug**
With the SCM import or export enabled in versions prior to 3.3.7 a blue or green icon would show next to the job name, indicating whether it could be committed to or pulled from SCM. Since upgrading from 3.3.6 to 3.3.7 the blue/green icons have been replaced by a + symbol, and hovering says 'undefined'. The icons used to also appear next to the Job Actions button, and they have gone (no + symbol here).

**My Rundeck detail**

* Rundeck version: 3.3.7
* install type: rpm
* OS Name/version: RHEL7
* DB Type/version: mysql

**To Reproduce**
1. Add SCM to a project
2. Click on Jobs
3. Wait 1-2 seconds
4. ➕ symbol appears, indicating job may be committed to SCM.

**Screenshots**
Previous behaviour:
![image](https://user-images.githubusercontent.com/1311209/101821203-83586280-3b8c-11eb-94ca-e3b11bc35716.png)

New behaviour:
![image](https://user-images.githubusercontent.com/1311209/101826016-4ba0e900-3b93-11eb-98d9-5041e118dd70.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Firefox / Edge

**Comment by MegaDrive68k** [comment]
Confirmed,

Configuring the SCM import the appears the "+" icon with the "undefined" mouse over text.

![Screenshot_2](https://user-images.githubusercontent.com/51376003/101952991-53cf4780-3bd8-11eb-9101-76c0c6ab86a3.png)

Thanks for your feedback @gaddman!

**Comment by MegaDrive68k** [comment]
Still happening on 3.3.9-rc6.

**Comment by leshik** [comment]
Very inconvenient. Is this going to be fixed in the 3.3.8 release?
