### ISSUE TITLE
Very difficult to trace output to exact job step in rundeck v2.0

### ISSUE THREAD

**Issue by andysteady** [rundeck/rundeck#667]
Rundeck 2.0 introduced step descriptions, however only the step description from the first level of job hierarchy is displayed.

The step numbering has been removed from the output. It used to be possible to see that it was 4.8.2.1 for example, and I could navigate through the job hierarchy to get to the exact step that was giving a particular piece of output.

Now its very difficult to trace a piece of output back to the exact step

**Comment by dennis-benzinger-hybris** [comment]
+1 Currently it is difficult for our users to report our developers where exactly a job failed.
