### ISSUE TITLE
Yaml editor not working when using literal sign

### ISSUE THREAD

**Issue by antonvdl** [rundeck/rundeck#6670]
**Describe the bug**
Using the literal sign (|) in Yaml syntax breaks the UI.

Breaks on a javascript function (cannot read property 'replace' of undefined)

token: "string",
regex: /[|>][-+\d]*(?:$|\s+(?:$|#))/,
onMatch: function(e, t, n, r) {
r = r.replace(/ #.*/, "");

**My Rundeck detail**

* Rundeck version: 3.3.7
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: H2

**To Reproduce**
1. Go to New job / Job edit
2. Click on Workflow
3. Add a Workflow step of type Ansible Playbook Inline
3. Scroll down to Extra variables
4. Make sure syntax is Yaml
5. Type some yaml code, and then include a | sign

**Expected behavior**
This literal sign (|) should be working fine in yaml syntax blocks.

**Screenshots**
![rundeck-literal-sign](https://user-images.githubusercontent.com/54950142/101915453-f205e200-3bc5-11eb-9d6d-d97fd6c507d9.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.88

**Additional context**
The problem has not been seen in version 3.3.2
The reproduction of the issue has been done in a clean installed environment.

**Comment by antonvdl** [comment]
Just tested all releases since 3.3.2 on CentOS.
The issue is present since version 3.3.4

**Comment by MegaDrive68k** [comment]
Confirmed, using the "|" character break all YAML editor, following [these](https://github.com/rundeck/rundeck/issues/6670#issue-762399852) steps.

Thanks for your feedback @antonvdl! Could you file this issue [here](https://github.com/Batix/rundeck-ansible-plugin/issues), please?

Regards!

**Comment by ProTip** [comment]
@ltamaster This may be related to the prototype change a while back?

**Comment by antonvdl** [comment]
@MegaDrive68k it seems to be in Rundeck, not the plug-in.
The k8s plugin has the same issue.

Seems te be related to this commit:

Replace brace with ace-builds
https://github.com/rundeck/rundeck/commit/186aea9ab3c35cd9dd45dc05777eb182b8014262

**Comment by ltamaster** [comment]
@ProTip yes it looks like that, I can take a look

**Comment by antonvdl** [comment]
This issue seems to be resolved in version 3.3.10 (not sure about previous versions)
