### ISSUE TITLE
Cannot install on fresh server.

### ISSUE THREAD

**Issue by gmyx** [rundeck/rundeck#6675]
**Describe the bug**
Unable to install on clean / new server

**My Rundeck detail**

* Rundeck version: 3.3.7
* install type: tired apt-get, downloaded .deb
* OS Name/version: Ubuntu 18.04.5
* DB Type/version: None yet

**To Reproduce**
Follow the instructions on your download page:
1. wget ....
2. apt-get install openjdk-8-jdk-headless
3. dpkg -i rundeck_3.3.7.20201208-1_all.deb

**Expected behavior**
Rundeck installed without issue

**Screenshots**
```
rundeck@rundeck:/tmp$ sudo dpkg -i rundeck_3.3.7.20201208-1_all.deb
Selecting previously unselected package rundeck.
(Reading database ... 77270 files and directories currently installed.)
Preparing to unpack rundeck_3.3.7.20201208-1_all.deb ...
Unpacking rundeck (3.3.7.20201208-1) ...
Setting up rundeck (3.3.7.20201208-1) ...
usermod: user rundeck is currently used by process 1949
dpkg: error processing package rundeck (--install):
 installed rundeck package post-installation script subprocess returned error exit status 8
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.43) ...
Errors were encountered while processing:
 rundeck
```

**Additional context**
Tired with Azure VM, Vm on own machine. Even tried Windows version and could not install.

Edit: re-pasted the log from first attempt instead of subsequent attemps

**Comment by MegaDrive68k** [comment]
Hi @gmyx 

Checking this line:

`Unpacking rundeck (3.3.7.20201208-1) over (3.3.7.20201208-1) ...`

It seems that the package it's already installed. And the following line:

`usermod: user rundeck is currently used by process 1998`

it seems that "rundeck" user is already created and used an OS process (maybe an active Rundeck instance?).

On a fresh system (doing `dpkg -i rundeck_3.3.7.20201208-1_all.deb`)  you can see:

```bash
Selecting previously unselected package rundeck.
(Reading database ... 122663 files and directories currently installed.)
Preparing to unpack rudeck_3.3.7.20201208-1_all.deb ...
Unpacking rundeck (3.3.7.20201208-1) ...
Setting up rundeck (3.3.7.20201208-1) ...
Adding group rundeck....done
Adding system user rundeck....done
Processing triggers for systemd (245.4-4ubuntu3.3) ...
```

Best regards.

**Comment by gmyx** [comment]
That is what I get when I copy the second attempt instead of the first. But the error I get is the same. Exit status 8. I will re-create the VM and the error and capture the correct output.

**Comment by gmyx** [comment]
Updated log: (will update OP as well)

```
rundeck@rundeck:/tmp$ sudo dpkg -i rundeck_3.3.7.20201208-1_all.deb
Selecting previously unselected package rundeck.
(Reading database ... 77270 files and directories currently installed.)
Preparing to unpack rundeck_3.3.7.20201208-1_all.deb ...
Unpacking rundeck (3.3.7.20201208-1) ...
Setting up rundeck (3.3.7.20201208-1) ...
usermod: user rundeck is currently used by process 1949
dpkg: error processing package rundeck (--install):
 installed rundeck package post-installation script subprocess returned error exit status 8
Processing triggers for ureadahead (0.100.0-21) ...
Processing triggers for systemd (237-3ubuntu10.43) ...
Errors were encountered while processing:
 rundeck

```

**Comment by gmyx** [comment]
Oh...... my user name on that VM is rundeck. Could that be interfering? Time to test that.

**Comment by MegaDrive68k** [comment]
Use a different name for your user, the deb package creates a specific user named "rundeck".

**Comment by gmyx** [comment]
Thanks. PIBKAC. It works as expected now.
