### ISSUE TITLE
variable not read in url list option

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#6676]
**Describe the bug**
email variable not read in url option list

**My Rundeck detail**

* Rundeck version: 3.3.7
* install type: war
* DB Type/version: mysql, h2

**To Reproduce**
1. Set email for user profile.
2. Create a job with option and remote url for allowed values like: http://testurl/email=${job.user.email}&user=${job.user.name}
3. Add a step: echo http://testurl/email=${job.user.email}&user=${job.user.name}
4. Save it, see error:

![image](https://user-images.githubusercontent.com/34582874/102242835-43b9af80-3ed9-11eb-9cef-3107327735d2.png)

**Expected behavior**
Get value from `${job.user.email}` as you get from `${job.user.name}`

**Screenshots**
Variable is ok, output is fine from echo:

![image](https://user-images.githubusercontent.com/34582874/102243138-97c49400-3ed9-11eb-8218-692b3c14b346.png)

**Comment by jbanda15** [comment]
Replicated.
![JobPage](https://user-images.githubusercontent.com/45765283/102262206-81c2cd80-3ef1-11eb-8b2b-5351535a023a.png)
![LogOutput](https://user-images.githubusercontent.com/45765283/102262217-86878180-3ef1-11eb-933a-f9fbea921729.png)


My Rundeck detail

- Rundeck version: 3.3.7
- Install method: WAR
- DB Type: MySQL, H2
