### ISSUE TITLE
What is the plus sign next to the job -?

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6682]
Hi Guys,
just upgraded rundeck to the latest version 3.3.7 and we are seeing "+" plus sign next to each job. not sure what is that about -?

![image](https://user-images.githubusercontent.com/20629911/102447601-2bcf5200-3fe5-11eb-901a-ae1b9ff81750.png)

![image](https://user-images.githubusercontent.com/20629911/102447650-44d80300-3fe5-11eb-87c6-80d7c76d544e.png)

Thank you,
HS

**Comment by gaddman** [comment]
Broken SCM icons, fixed in 3.3.9, see #6735
