### ISSUE TITLE
Commands page shows JS/HTML error

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6686]
RUNDECK
APIVERSION : 36
BASE : /var/lib/rundeck
BUILD : 3.3.7-20201208
BUILDGIT : v3.3.7-0-g330c6fe
SERVERUUID : 57946b2b-b731-4f00-8e27-b826a61fea00  globe-57
VERSION : 3.3.7-20201208

simply loading the page we see these errors:

![image](https://user-images.githubusercontent.com/20629911/102534937-5c9e9e00-405c-11eb-9074-a0f2f0935411.png)

Thanks,
HS

**Comment by MegaDrive68k** [comment]
Confirmed and happening on 3.1, 3.2, and 3.3 branches:

Dev console on Firefox (3.3.7):

![Screenshot_3](https://user-images.githubusercontent.com/51376003/102540453-d307c400-408d-11eb-9f43-4eff3caf7e05.png)

On 3.0 branch (3.0.26):

![Screenshot_4](https://user-images.githubusercontent.com/51376003/102540489-ddc25900-408d-11eb-887c-1de189e2aea6.png)

Thanks for your feedback @hs-hub-world!
