### ISSUE TITLE
notification "send webhook": user:password@url format not working

### ISSUE THREAD

**Issue by jplassnibatt** [rundeck/rundeck#6690]
**Describe the bug**
When setting a "send webhook" notification using format user:password@url, it is not working.

**My Rundeck detail**

* Rundeck version: 3.3.7
* install type: war
* OS Name/version: linuxmint 20.04
* DB Type/version: mysql, h2

**To Reproduce**
1. Go to job's notification job
2. Add url in user:password@url format (webhook to jenkins for example)
3. Run it
4. See error in service.log
    [2020-12-22T13:04:38,081] ERROR services.NotificationService - Notification failed [onsuccess,succeeded,5]; URL http://user:TOKEN@url/job/triggered.build.from.rundeck/build?token=TOKEN: Unable to POST notification after 1 tries: success for execution 5 (succeeded): server response: 403 Forbidden

**Expected behavior**
Same format is working fine using "http notification" notification and from command line (curl)

**Comment by MegaDrive68k** [comment]
Confirmed,

With the following cURL call works well:

```
curl -X -POST http://user:token-string@host:4440/job/triggered.build.from.rundeck/build?token=12345
```

But doesn't work on Webhook notification.
