### ISSUE TITLE
All Job hangs with Oracle DB.

### ISSUE THREAD

**Issue by wadelu** [rundeck/rundeck#6698]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.2.9 ~ 3.3.6
* install type: Docker
* OS Name/version:  Red Hat Enterprise Linux Server release 7.9 (Maipo)
* DB Type/version: Oracle Database 19c Enterprise Edition Release 19.0.0.0.0

**Expected Behavior**
Jobs and Adhoc CMD both should been run correctly.

**How to Reproduce**
1.  Setup Rundeck with Oracle DB;
2.  Create any new Job with K8s plugin and set this job run @node;
3.  Launch job @k8s node;
4.  Job hangs and shows "Waiting for execution to start...".

We also tried with Rundeck CLI, and run with Adhoc cmd, still facing this issue, any job or cmd cannot be executed.

**Comment by MegaDrive68k** [comment]
Hi @wadelu 

Which k8 plugin version are you using?

Can you share the `service.log` content at the moment of launch the job?

Regards.

**Comment by wadelu** [comment]
Hi @MegaDrive68k ,

Thx for you response! We tested with K8s plugin 2.0.1.

All logs file size is 0, and there is no service.log file.
> rundeck@tooling-rd-ora-589bd4b858-jvb97:~/server/logs$ ll
> total 12
> drwxrwxr-x. 2 rundeck root 4096 Dec  8 23:15 ./
> drwxrwxr-x. 1 rundeck root 4096 Dec  8 23:15 ../
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.access.log*
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.api.log*
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.audit.log*
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.cleanup.log*
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.executions.log*
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.jobs.log*
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.log*
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.options.log*
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.project.log*
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.storage.log*
> -rwxrwxr-x. 1 rundeck root    0 Dec  8 23:15 rundeck.webhooks.log*

And we can found hanging executions:
> rundeck@tooling-rd-ora-589bd4b858-jvb97:~$ rd executions list
> Credentials for URL: http://127.0.0.1:4440
> Enter username (blank for token auth): admin
> Enter password:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by retrofit2.Platform (file:/var/lib/rundeck-cli/rd-cli-tool-shadow-1.3.4/lib/rundeck-cli-1.3.4-all.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
> WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> # Running executions: 1 items
> 2802 running 2021-01-05T00:00:01Z - http://127.0.0.1:4440/project/PROD-BIZ/execution/show/2802 job 5117256a-9f55-4d00-ac7a-cfec248eb253 /Test Connection to Ts-utils

**Comment by wadelu** [comment]
And if we kill the execution and run again with with debug , still freezed and no log generated:

> rundeck@tooling-rd-ora-589bd4b858-jvb97:~/libext/cache/kubernetes-plugin-2.0.1$ rd run -l debug -i 5117256a-9f55-4d00-ac7a-cfec248eb253 -f
> Credentials for URL: http://127.0.0.1:4440
> Enter username (blank for token auth): admin
> Enter password:
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by retrofit2.Platform (file:/var/lib/rundeck-cli/rd-cli-tool-shadow-1.3.4/lib/rundeck-cli-1.3.4-all.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
> WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> # Execution started: [2842] 5117256a-9f55-4d00-ac7a-cfec248eb253 /Test Connection to Ts-utils <http://127.0.0.1:4440/project/PROD-BIZ/execution/show/2842>
>

**Comment by wadelu** [comment]
And if we execution adhoc cmd, still freeze, I thins it's not k8s related issues.

> rundeck@tooling-rd-ora-589bd4b858-jvb97:~/libext/cache/kubernetes-plugin-2.0.1$ rd adhoc -f -K -r -v cat /etc/hosts
> WARNING: An illegal reflective access operation has occurred
> WARNING: Illegal reflective access by retrofit2.Platform (file:/var/lib/rundeck-cli/rd-cli-tool-shadow-1.3.4/lib/rundeck-cli-1.3.4-all.jar) to constructor java.lang.invoke.MethodHandles$Lookup(java.lang.Class,int)
> WARNING: Please consider reporting this to the maintainers of retrofit2.Platform
> WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
> WARNING: All illegal access operations will be denied in a future release
> # Started execution 2826 running 2021-01-05T07:27:11Z - http://127.0.0.1:4440/project/PROD-BIZ/execution/show/2826 adhoc cat /etc/hosts
>

**Comment by MegaDrive68k** [comment]
Hi @wadelu 

I mean, you can see the `service.log` doing:

`docker logs -f <your_container_name>`

And check the output at the moment of launch the job.

Best regards.

**Comment by wadelu** [comment]
[rundeck-oracle.console.log](https://github.com/rundeck/rundeck/files/5771357/rundeck-oracle.console.log)
Hi @MegaDrive68k  , Pls kindly find out the console output, as attached file.

**Comment by wadelu** [comment]
Hi @MegaDrive68k  and team, any update for this?
