### ISSUE TITLE
Authentication failure connecting to a specific node

### ISSUE THREAD

**Issue by TeodorCa** [rundeck/rundeck#6706]
Issue type: Bug report/Enhancement Request
**Described problem**

Hi there 

I am trying to run some commands via a job created in Rundeck on a remote machine.
But the problem I'm facing is that I cannot connect to the specific machine, and I get the following error : 

Authentication failure connecting to node: "homelnx". Make sure your resource definitions and credentials are up to date. 

I mention the fact that I configured the connection via privateKey in more than 1 way : 
1st : 
In project settings - Default Node Executor : 
SSH Key File path : /var/rundeck/keys/id_rsa

2nd : 
In project settings - Default Node Executor : 
SSH Key File path : /home/runmed/.ssh/id_rsa

I also uploaded the private key in 2 ways : 
1st : copy/paste contents
2nd : upload the id_rsa file

Also, the targeted machine was declared in multiple ways in the resoruces.xml * file : 
* resources.xml was created manual by me and stored in the next location : /var/rundeck/resources/resources.xml

1st : 
```
<project>
  <node name="homelnx" description="Rundeck server node" tags="project=TestHomelnx" hostname="homelnx" osArch="amd64" osFamily="unix" osName="Linux" osVersion="2.6.32-504.16.2.el6.x86_64" username="fusion"/>
</project>
```

2nd : 
```
<project>
  <node name="homelnx" description="Rundeck server node" tags="project=TestHomelnx" hostname="homelnx" osArch="amd64" osFamily="unix" osName="Linux" osVersion="2.6.32-504.16.2.el6.x86_64" username="fusion" ssh-authentication="privateKey" ssh-key-storage-path="keys/id_rsa"/>
</project>
```
 
Can someone point me into the right direction? 
Thank you !

**My Rundeck detail**

* Rundeck version: 3.3.7
* install type: WAR
* OS Name/version: CentOS7 
* DB Type/version: Postgres 12.3

**Expected Behavior**

Successful connection to the remote machine

**How to Reproduce**

- Login to Rundeck
- Go to a project 
- Try to run a job in that project that involves running commands on a remote machine

**Comment by MegaDrive68k** [comment]
Hi @TeodorCa 

Take a look at [this](https://github.com/rundeck/rundeck/issues/6022#issuecomment-624678947).

**Comment by TeodorCa** [comment]
Thanks @MegaDrive68k, now it works. It seems that it was necessary to add the public key of the machine that has Rundeck installed on it, in the authorized_keys file on the remote machine.
