### ISSUE TITLE
Webhook is not able to query by hostname

### ISSUE THREAD

**Issue by barra51** [rundeck/rundeck#6707]
**Describe the bug**
working with webhooks, Rundeck is not able to query using the filter "hostname" under Node filter option. Response is:
```
com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:74)
Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{includes={name=-hostname,node-0025.com, dominant=true, }}
No matched nodes: NodeSet{includes={name=-hostname,node-0025.com, dominant=true, }}
```

**My Rundeck detail**

* Rundeck version: 3.3.5
* install type: rpm
* OS Name/version: Amazon Linux 2
* DB Type/version: H2 database

**To Reproduce**
1. Go to Webhooks
2. Fill the requested data
3. Fill fields ***options*** and ***Node filter*** respectively with:
```
-raw ${raw} -event_type ${data.event_type}
```
```
-hostname ${data.host}
```
4. See error in job execution.

**Expected behavior**
Rundeck webhook should be able to catch the hostname filter. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: External
 - Browser Chrome
 - Version  88.0.4324.47

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @barra51 

You can use a single option to use the node filter, for example, for the following job:

```xml
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='mynodes' value='hyperion' />
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <dispatch>
      <excludePrecedence>true</excludePrecedence>
      <keepgoing>false</keepgoing>
      <rankOrder>ascending</rankOrder>
      <successOnEmptyNodeFilter>false</successOnEmptyNodeFilter>
      <threadcount>1</threadcount>
    </dispatch>
    <executionEnabled>true</executionEnabled>
    <id>e7ba29f5-1447-4f7d-b9eb-4e5be8fa0ce3</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <nodefilters>
      <filter></filter>
    </nodefilters>
    <nodesSelectedByDefault>true</nodesSelectedByDefault>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "hello world"</exec>
      </command>
    </sequence>
    <uuid>e7ba29f5-1447-4f7d-b9eb-4e5be8fa0ce3</uuid>
  </job>
</joblist>
```

Following [this](https://docs.rundeck.com/docs/manual/webhooks/run-job.html#configuration):

![Screenshot_1](https://user-images.githubusercontent.com/51376003/104332256-bf098380-54ce-11eb-968f-cf92d00035da.png)

You can call the webhook in this way:

```bash
curl -H "Content-Type: application/json" -X POST -d '{"field1":"node01"}' http://localhost:4440/api/37/webhook/qGSpyuIPLUVJ4h0IV8Wi0X3XeqSQlqG1#Test
```

To run on a specific node:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/104332589-190a4900-54cf-11eb-90ce-93054874f30e.png)

You can use the node filter normally.

Hope it helps!

**Comment by barra51** [comment]
This is exactly I was looking for! Thank you so much @MegaDrive68k
