### ISSUE TITLE
Host changes to localhost after first login

### ISSUE THREAD

**Issue by vega113** [rundeck/rundeck#671]
How to reproduce:
1. Install rundeck  on CentOS using "Yum RPM Install " instructions at http://rundeck.org/downloads.html
2. Start the service with service rundeckd start
3. Navigate to http://yourhost.com:4440
4. Login with admin/admin
Expected result: The login is successful and the dashboard is displayed.
Actual result: the host is changed to http://localhost:4440/menu/home (instead of http://yourhost.com:4440/menu/home) and there's obviously "page cannot be displayed" browser error.

Please note that running rundeck by downloading the rundeck-launcher-2.0.1.jar and running with "java -jar rundeck-launcher-2.0.1.jar" works fine.

**Comment by jonatanblue** [comment]
Same issue on Ubuntu 14.04, installing 2.4.2-1 from deb

Server running inside AWS VPC, kept redirecting me to localhost. Workaround:
Ensure /etc/hosts has entry
<private ip> <private dns name>

Set rails.serverURL=http://<private dns name>:4440

**Comment by ashish235** [comment]
Still having the same issue with 2.5.0 on CentOS 7. Any ETA on this issue please? I can't move ahead with using Rundeck with my existing ansible infrastructure until this is fixed.

**Comment by mathieuchateau** [comment]
Hello,

it's not version 2.5.0 fault, neither centos one.

You need to customize your setup
/etc/rundeck-config.properties
update grails.serverURL=https://name_or_dns_alias

/etc/framework.properties
update framework.rundeck.url=https://name_or_dns_alias

Append :xxx if not on default port (:4440 by default)


Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-04-30 15:31 GMT+02:00 ashish235 <notifications@github.com>:

**Comment by ashish235** [comment]
Thanks @mathieuchateau saved me a lot of troubles, I did some sanity and it seems to be working.

**Comment by vega113** [comment]
As already mentioned, just deleting grails.serverURL also works - at least for me.

**Comment by huksley** [comment]
As of 2.5.2 this is an open issue.
I`ve changed rundeck-config.properties, setting grails.serverURL=http://internet.site/rundeck 
I`ve changed framework.properties, setting framework.server.url = http://internet.site
It is not working:
```
huksley@internet.site:~$ wget http://internet.site/rundeck/
--2015-08-12 01:18:22--  http://internet.site/rundeck/
Resolving internet.site (internet.site)... 192.168.1.1
Connecting to internet.site (internet.site)|192.168.1.1|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://localhost:4440/rundeck/user/login;jsessionid=hue5yaxsg0ez1b624u7kzpz6d [following]
```

**Comment by mathieuchateau** [comment]
Hello,

why /rundeck/ in url and serverurl?
You should apopend :4440 as you are not on port 80 in rundeck config

Cordialement,
Mathieu CHATEAU
http://www.lotp.fr

2015-08-12 0:23 GMT+02:00 Ruslan Gainutdinov <notifications@github.com>:

**Comment by huksley** [comment]
Hi Mathieu!
I am hosting it behind apache (httpd acting as reverse proxy).
It is part of larger project and i a, running it under prefix /rundeck/ not in the root url.

**Comment by abrahamrhoffman** [comment]
netstat shows listening on 0.0.0.0:4440 but remote hosts cannot connect. iptables is clear... anyone have any ideas?

**Comment by madhusudhanane** [comment]
Couldn't connect to port 4440 , this port is open in security group , but still couldn't telnet to it

[root@PDXA-DEV-FAB01 rundeck]# netstat -ane |grep 4440
tcp        0      0 :::4440                     :::*                        LISTEN      568        69267499

2016-02-02 20:17:38.337:INFO:/:Initializing Spring FrameworkServlet 'grails'
2016-02-02 20:17:38.364:INFO:oejs.AbstractConnector:Started SelectChannelConnector@0.0.0.0:4440

**Comment by abrahamrhoffman** [comment]
Same issue - anyone had any luck fixing this?

**Comment by isuftin** [comment]
I am having a similar issue in that I can connect via localhost to port 4440  and can curl 'http://127.0.0.1:4440' but no content is returned. When telnetting, I am seeing I am hitting Jetty.

```
# telnet localhost 4440
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
helo
HTTP/1.1 400 Bad Request
Content-Length: 0
Connection: close
Server: Jetty(7.6.0.v20120127)

Connection closed by foreign host.
```

```
# curl localhost:4440
#
(no content received)
```

**Comment by penugondasaiteja** [comment]
Thanks for info dude. @gschueler  Appreciate it :)

**Comment by gautamsomani** [comment]
Issue still persists for Debian 7 OS, Rundeck version 2.6.7-1-GA. 
Solved the issue by commenting out #grails.serverURL=http://localhost:4440
in /etc/rundeck/rundeck-config.properties as RamiKishan suggested, and it worked.

**Comment by ronindesign** [comment]
+1

**Comment by angystardust** [comment]
In order to let rundeck work behind an Apache reverse-proxy, you should set the `server.web.context` system property in the` /etc/rundeck/profile` configuration file (please, notice the last 2 lines):

```
export RDECK_JVM="-Djava.security.auth.login.config=/etc/rundeck/jaas-ad.conf \
        -Dloginmodule.name=multiauth \
        -Drdeck.config=/etc/rundeck \
        -Drdeck.base=/var/lib/rundeck \
        -Drundeck.server.configDir=/etc/rundeck \
        -Dserver.datastore.path=/var/lib/rundeck/data \
        -Drundeck.server.serverDir=/var/lib/rundeck \
        -Drdeck.projects=/var/rundeck/projects \
        -Drdeck.runlogs=/var/lib/rundeck/logs \
        -Drundeck.config.location=/etc/rundeck/rundeck-config.properties \
        -Djava.io.tmpdir=$RUNDECK_TEMPDIR \
        -Dserver.web.context=/rundeck"

```

**Comment by mramanathan** [comment]
For those installing from .jar file, this thread (post by Wyx on May 27,2015) will be useful:

http://stackoverflow.com/questions/37389717/how-to-install-rundeck-in-ubuntu

**Comment by steven-tan** [comment]
This is still an issue as of v2.7.3

For now going to comment it out as noted above and move on.  If it's going to remain busted, may be worth at least mentioning it in the docs.

**Comment by roneybd85** [comment]
I have tried  ubuntu 16.04 with Rundeck 1.8.3 . I tried everything stated here but with no luck

**Comment by vega113** [comment]
Did you try to delete grails.serverURL?

**Comment by roneybd85** [comment]
I tried it commented it out @vega113

**Comment by andrewm659** [comment]
I am facing the same issue on CetnOS 7 (latest).  I can comment out the grails.serverURL but ti braeks RunDeck.

`INFO  BootStrap: Rundeck is ACTIVE: executions can be run.
INFO  BootStrap: Rundeck startup finished in 709ms
2017-07-17 19:05:34.772:INFO:/:main: Initializing Spring FrameworkServlet 'grails'
2017-07-17 19:05:34.855:INFO:oejsh.ContextHandler:main: Started o.e.j.w.WebAppContext@41a374be{/,file:/var/lib/rundeck/exp/webapp/,AVAILABLE}{/var/lib/rundeck/exp/webapp}
2017-07-17 19:05:34.901:INFO:oejs.ServerConnector:main: Started ServerConnector@10ab976b{HTTP/1.1}{0.0.0.0:4440}
2017-07-17 19:05:48.056:INFO:/:qtp1480010240-18: Initializing Spring FrameworkServlet 'grails-errorhandler'

Session terminated, killing shell...2017-07-17 19:06:11.556:INFO:oejs.ServerConnector:Thread-1: Stopped ServerConnector@10ab976b{HTTP/1.1}{0.0.0.0:4440}
2017-07-17 19:06:11.557:INFO:/:Thread-1: Destroying Spring FrameworkServlet 'grails-errorhandler'
2017-07-17 19:06:12.344:INFO:/:Thread-1: Closing Spring root WebApplicationContext
2017-07-17 19:06:12.355:INFO:oejsh.ContextHandler:Thread-1: Stopped o.e.j.w.WebAppContext@41a374be{/,file:/var/lib/rundeck/exp/webapp/,UNAVAILABLE}{/var/lib/rundeck/exp/webapp}
 ...killed.
WARNING: HTTPS is not enabled, specify -Drundeck.ssl.config=/var/lib/rundeck/server/config/ssl.properties to enable.
2017-07-17 19:06:16.389:INFO:oejs.Server:main: jetty-9.0.7.v20131107
2017-07-17 19:06:19.066:INFO:oejw.StandardDescriptorProcessor:main: NO JSP Support for /, did not find org.apache.jasper.servlet.JspServlet
`

**Comment by sinksc** [comment]
Would love to see hostname detection with the yum rpm install so we don't have to manually update grails.serverURL. Manually updating it works fine, but cleaning that up would make for a seamless install. Just adding myself as a "+1" on this.

**Comment by rajeshgit221** [comment]
Hi All,
Installed rundeck and changed from local host to ipaddress in below two places but still i get the "this site can't be reached" error, not sure whats going on, can someone help me with this issue ?

1. rundeck-config.properties
2. framework.properties
Error when i tried to login using http://ipaddress:4440/
This site can’t be reached
"ipaddress took too long to respond."
ERR_CONNECTION_TIMED_OUT

Thanks in Advance...

**Comment by getSurreal** [comment]
Geez! 4 years without resolving this simple issue?

**Comment by dkarapanos** [comment]
Would be nice if it was at least mentioned in the manual. Where to change the "localhost".

**Comment by sjrd218** [comment]
In your rundeck-config.properties file try setting the `server.host` property to be the hostname of your system. See if that achieves the desired result.

**Comment by ajgeek** [comment]
any one please help or guide me with this tool . i am using rundeck for first time . i am able to login into the api but after login its says page not found . not redirecting to the defualt dashboard view.
![rundeck_error](https://user-images.githubusercontent.com/42539624/44336783-22c22a80-a496-11e8-9dee-dd879b443225.PNG)
Please refer to the snapshot.

**Comment by kishan-1234** [comment]
I am running rundeck using docker. Using the docker image from hub 3.0.13. Its having same redirection issue and inside /etc/ no rundeck folder is present. Can anyone help please help me with this?

**Comment by meirim-pt** [comment]
> I am running rundeck using docker. Using the docker image from hub 3.0.13. Its having same redirection issue and inside /etc/ no rundeck folder is present. Can anyone please help me with this?


docker exec -it tst_rundeck_1 /bin/bash
cd /etc/remco/templates
sed 's/127.0.0.1/myhost.domain/' rundeck-config.properties > rundeck-config.properties1
cp rundeck-config.properties1 rundeck-config.properties
sed 's/127.0.0.1/myhost.domain/' framework.properties  >framework.properties1
cp framework.properties1 framework.properties

docker restart tst_rundeck_1 

Firefox:http://myhost.domain:4440

admin/admin
pressed login twice(?)

**Comment by ProTip** [comment]
Hi @kishan-1234 ,

The environment variable `RUNDECK_GRAILS_URL` as documented on the [Docker image page](https://cloud.docker.com/u/rundeck/repository/docker/rundeck/rundeck) is used to set the URL for the application. This defaults to `http://127.0.0.1:4440`, however you can change it to localhost or whichever URL the user is expected to access Rundeck at. [This example](https://github.com/rundeck/docker-zoo/blob/master/cloud/docker-compose.yml#L13) in the Docker Zoo changes it to localhost port 80 for running behind an nginx proxy.

This configuration setting maps to the `grails.serverURL=` setting in `rundeck-config.properties` which should be set for non-Docker installations. Anyone having redirect issues on login should verify first that this setting is set to the valid URL and that it matches the desired location.

I'm going to go ahead and close this for now as the discussion has wondered a bit and the issue has become a catch-all for configuration questions :) Please direct any usage and configuration questions to the [Rundeck Discussion Group](https://groups.google.com/forum/#!forum/rundeck-discuss).

**Comment by arnabdutta2194** [comment]
I am facing the following error: Connection refused (Connection refused) when I am running a rundeck job to 5 Windows Nodes. Please help if possible anyone.

**Comment by fdansey-ostmodern** [comment]
I got around the same problem (of rundeck running behind nginx) by using the application setting:
`RUNDECK_GRAILS_URL = /.`
such that the UI forms API calls using the same host that the user is accessing the page with.

**Comment by RaveenBouy** [comment]
> I just comment the #grails.serverURL=http://localhost:4440
> in /etc/rundeck/rundeck-config.properties and it works great now ..
> 
> good luck!

I Can't believe this issue still exists! Almost gave up using Rundeck. 
Anyways thanks for the workaround!!

**Comment by krpovmu** [comment]
@fdansey-ostmodern It worked for me when you put your external hostname 
`RUNDECK_GRAILS_URL=http://xxxx.xxxxx.xxx`

**Comment by esfateev** [comment]
Cant' imagine, issue still actual. Installation method - docker.
Package Version  - 3.3.7....

**Comment by raghavendar-ts** [comment]
This comment is off the topic. What the "A" represent in the hostname PDXA-DEV-FAB01 (specifically in PDXA). PDX is the airport code which I am familiar with. What does "A" signify?

**Comment by kevinadhiguna** [comment]
I ran to this issue when using  docker-compose.yml [here](https://github.com/rundeck/docker-zoo/blob/master/mysql/docker-compose.yml).

To solve the problem, I added `RUNDECK_GRAILS_URL: ${RUNDECK_GRAILS_URL:-localhost:4440}` in environment section of docker-compose.yml. This worked but I wanted to add environment variable to handle the URL, so it looked like this :  
`RUNDECK_GRAILS_URL: ${RUNDECK_GRAILS_URL:-localhost:4440}`

The whole `docker-compose.yml` is : 

```yml
version: '3'

services:
    rundeck:
        image: rundeck/rundeck:SNAPSHOT
        # links:
        #   - mysql
        depends_on:
          - mysql
        environment:
            RUNDECK_DATABASE_DRIVER: org.mariadb.jdbc.Driver
            RUNDECK_DATABASE_USERNAME: ${RUNDECK_DATABASE_USERNAME:-rundeck}
            RUNDECK_DATABASE_PASSWORD: ${RUNDECK_DATABASE_PASSWORD:-rundeck}
            RUNDECK_DATABASE_URL: ${RUNDECK_DATABASE_URL:-jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false}
            # Add 'RUNDECK_GRAILS_URL' to avoid host changing to localhost (see more : https://github.com/rundeck/rundeck/issues/671)
            # 'RUNDECK_GRAILS_URL' can be remote IP address, such as 43.133.23.165 or hostname, like https://mywebsite.com
            RUNDECK_GRAILS_URL: ${RUNDECK_GRAILS_URL:-localhost:4440}
        # volumes:
        #   - ${RUNDECK_LICENSE_FILE:-/dev/null}:/home/rundeck/etc/rundeckpro-license.key
        ports:
          - 4440:4440
    mysql:
        image: mysql:5.7
        # expose:
        #   - 3306
        ports:
          - 3306:3306
        environment:
          MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
          MYSQL_DATABASE: ${MYSQL_DATABASE:-rundeck}
          MYSQL_USER: ${MYSQL_USER:-rundeck}
          MYSQL_PASSWORD: ${MYSQL_PASSWORD:-rundeck}
        volumes:
          - dbdata:/var/lib/mysql

volumes:
    dbdata:
```


Also, this is the `.env` file that includes environment variables and thier values : 

```env
RUNDECK_DATABASE_USERNAME=rundeck
RUNDECK_DATABASE_PASSWORD=rundeck
RUNDECK_DATABASE_URL=jdbc:mysql://mysql/rundeck?autoReconnect=true&useSSL=false
RUNDECK_GRAILS_URL=https://mywebsite.com
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=rundeck
MYSQL_USER=rundeck
MYSQL_PASSWORD=rundeck
```

Feel free to change the value of `RUNDECK_GRAILS_URL` in `.env`.

You can have a look here to check them all, including how to run the docker-compose and its setup : 
- [Rundeck - MySQL](https://github.com/kevinadhiguna/jiyu/tree/master/rundeck/rundeck-mysql)
- [Rundeck - H2 (embedded database)](https://github.com/kevinadhiguna/jiyu/tree/master/rundeck/rundeck-h2)

**Comment by shotarry** [comment]
> > I am running rundeck using docker. Using the docker image from hub 3.0.13. Its having same redirection issue and inside /etc/ no rundeck folder is present. Can anyone please help me with this?
> 
> docker exec -it tst_rundeck_1 /bin/bash cd /etc/remco/templates sed 's/127.0.0.1/myhost.domain/' rundeck-config.properties > rundeck-config.properties1 cp rundeck-config.properties1 rundeck-config.properties sed 's/127.0.0.1/myhost.domain/' framework.properties >framework.properties1 cp framework.properties1 framework.properties
> 
> docker restart tst_rundeck_1
> 
> Firefox:http://myhost.domain:4440
> 
> admin/admin pressed login twice(?)

I have just logged in in github to say thank you, you are a hero.

**Comment by alessandroAmedei** [comment]
I installed rundeck using docker and this worked for me:
`docker run --name some-rundeck -p 4440:4440 -e RUNDECK_GRAILS_URL=http://X.Y.Z.W:4440 -d -v data:/home/rundeck/server/data rundeck/rundeck:4.17.1
`
