### ISSUE TITLE
I can not visit the login page when I follow the steps from the documentation

### ISSUE THREAD

**Issue by DDKatch** [rundeck/rundeck#6710]
**Describe the bug**
I saw an error page when I tried to visit `http://<hostname>:4440` however I followed the steps from the documentation.

**My Rundeck detail**

* Rundeck version: 3.3.7-20201208
* install type: war
* OS Name/version: mac OS Catalina Version 10.15.5 (19F101)
* DB Type/version: -

**To Reproduce**
1. Downoad the rundeck-3.3.7-20201208.war
2. Run `java -jar rundeck-3.3.7-20201208.war`
3. Try to open the link `http://<hostname>:4440` in your browser
4. See error(in the Screenshots section)

**Expected behavior**
I have to see the login page.

**Screenshots**
<img width="1198" alt="Screen Shot 2021-01-07 at 2 48 21 AM" src="https://user-images.githubusercontent.com/14095146/103834081-85321a80-5093-11eb-99d5-9161ecb421c9.png">

**Desktop (please complete the following information):**
 - OS: mac OS Catalina Version 10.15.5 (19F101)
 - Browser: Google Chrome Version 87.0.4280.88 (Official Build) (x86_64)
 - hostname: mbmist

**Additional context**
Actually, I have fixed the issue by changing
`server.address=mbmist`
to 
`server.address=localhost`
in *server/config/rundeck-config.properties* file so I finally saw the login page
<img width="1397" alt="Screen Shot 2021-01-07 at 3 01 40 AM" src="https://user-images.githubusercontent.com/14095146/103834534-b6f7b100-5094-11eb-89bf-23e47ea13232.png">

Adding the *mbmist* to the **Search Domains** also fixed the issue
<img width="674" alt="Screen Shot 2021-01-07 at 3 05 13 AM" src="https://user-images.githubusercontent.com/14095146/103834745-53ba4e80-5095-11eb-9301-e85ee19f1c54.png">
<img width="1393" alt="Screen Shot 2021-01-07 at 3 04 43 AM" src="https://user-images.githubusercontent.com/14095146/103834750-574dd580-5095-11eb-9f73-75276ea96070.png">

**Comment by MegaDrive68k** [comment]
Also, if you want to access to your instance from any network node use:

`server.address=0.0.0.0` on your `rundeck-config.properties` file.

Check [this](https://docs.rundeck.com/docs/administration/install/windows.html#configuring-rundeck).
