### ISSUE TITLE
Exporting jobs with inline script gets mangled if tab spaces are used

### ISSUE THREAD

**Issue by agarwalpranab** [rundeck/rundeck#6714]
Issue type: Bug report

NOTE: 
1. This happens with only yaml export and not with xml export.
2. This happens when you copy-paste the script from another editor, that honors tabs as tab character.

**My Rundeck detail**

* Rundeck version: 3.3.6
* install type: (rpm,deb,war,launcher?): docker
* OS Name/version: Debian
* DB Type/version: mysql? postgres? h2? h2

**Expected Behavior**
When the job is exported, it is expected that the indentation is maintained for the inline bash scripts. This may be achieved by converting tab character to spaces by default.

**How to Reproduce**
Create a job with 1 inline script.
Copy paste a bash script that has tab spaces in the script.
Save the job and export yaml file.

Open the yaml file in any editor. The script will all be mangled to be displayed in 1 single line.

**Comment by MegaDrive68k** [comment]
Hi @agarwalpranab 

Which editor are you using to copy the script? I tested with VSCode and Gedit and the script indentation is saved correctly.

Regards!

**Comment by agarwalpranab** [comment]
Good day MegaDrive

I used BBEdit for this to copy the bash script and pasted it on rundeck bash editor. My BBEdit is set to indent tabs (and not spaces), which I believe can be done with other editors too.

I will grab a sample code and send attach the file here in a bit.
