### ISSUE TITLE
Job Options (how to set default current Date)

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#6718]
Hi, How to set the default current date for a job option -?

![image](https://user-images.githubusercontent.com/20629911/103999973-7494a980-5152-11eb-8395-a0285d6ba05f.png)

![image](https://user-images.githubusercontent.com/20629911/104000071-9726c280-5152-11eb-913e-45a9c0ad29ef.png)

Thank you!
HS

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world 

Using this job definition:

```xml
<joblist>
  <job>
    <context>
      <options preserveOrder='true'>
        <option name='my_birthday' value='${DATE:MM/DD/YYYY}'>
          <dateFormat>MM/DD/YYYY</dateFormat>
          <isDate>true</isDate>
        </option>
      </options>
    </context>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>26932242-7143-4c4e-b2e6-95739c1acd0f</id>
    <loglevel>INFO</loglevel>
    <name>HelloWorld</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>echo "${option.my_birthday}</exec>
      </command>
    </sequence>
    <uuid>26932242-7143-4c4e-b2e6-95739c1acd0f</uuid>
  </job>
</joblist>
```

I see the same orange textbox:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/104190868-79c85180-53fb-11eb-8c25-420670394b18.png)
But at the moment of run the job, works as expected:

![Screenshot_2](https://user-images.githubusercontent.com/51376003/104190879-7d5bd880-53fb-11eb-96ff-7ba60c4c6c5c.png)

Is the same behavior in your case?

Regards!

**Comment by hs-hub-world** [comment]
As always - thanks for the quick reply @MegaDrive68k.  actually I was hoping the date would be visible at the page when we are preparing to run the job - before clicking Run Job button. For two reasons:
- 1 user needs to know/see what date it's going to be passed to the job before executing.
- 2 when there is a reference to that Job Option Value by another Job Option the referenced job option does not see the correct date and it throws error. (i.e. remote url option call, passing as argument) 

Hope that makes sense.
Thank you
HS
