### ISSUE TITLE
Webhook in Job with json format need successfulNodes information

### ISSUE THREAD

**Issue by Shinku-Chen** [rundeck/rundeck#6726]
XML format has successfulNodes info,but json havnt

**Comment by Shinku-Chen** [comment]
Rundeck 3.3.8-20210111

**Comment by MegaDrive68k** [comment]
Hi @Shinku-Chen 

Could you elaborate? Could you share an example of your Webhook call?

Greetings!

**Comment by Shinku-Chen** [comment]
{"body":"{\"trigger\":\"start\",\"status\":\"running\",\"executionId\":377822,\"execution\":{\"id\":377822,\"href\":\"http://localhost:4440/project/ADX/execution/follow/377822\",\"permalink\":null,\"status\":\"running\",\"project\":\"ADX\",\"executionType\":\"user\",\"user\":\"com\",\"date-started\":{\"unixtime\":1611029626000,\"date\":\"2021-01-19T04:13:46Z\"},\"job\":{\"id\":\"2592d528-b878-4cae-9b9f-a1145a954931\",\"averageDuration\":9773,\"name\":\"发布测试Prometheus\",\"group\":\"服务器/测试环境/AD_Prometheus项目\",\"project\":\"ADX\",\"description\":\"\",\"options\":{\"IS_INIT\":\"NO\",\"GIT_TREE\":\"master\",\"opt_name\":\"ad-prometheus\"},\"href\":\"http://localhost:4440/api/37/job/2592d528-b878-4cae-9b9f-a1145a954931\",\"permalink\":\"http://localhost:4440/project/ADX/job/show/2592d528-b878-4cae-9b9f-a1145a954931\"},\"description\":\"job: c75e8f12-d87a-4270-865f-8f9e2d3164bf -- -GIT_URL \\\"git.ol.com/taad/${option.opt_name}\\\" [... 8 steps]\",\"argstring\":\"-GIT_TREE master -IS_INIT NO -opt_name ad-prometheus\",\"serverUUID\":\"1b80c821-4c69-4312-a6e4-060bce9298a0\"}}","headerParameters":{},"headers":{"content-length":"1016","content-type":"application/json; charset=UTF-8","host":"service-f.sh.apigw.tencentcs.com","requestsource":"APIGW","user-agent":"Jakarta Commons-HttpClient/3.1","x-api-requestid":"eb98acdf5b27c683a6aab093766ed779","x-api-scheme":"https","x-b3-traceid":"eb98acdf5b27c683a6aab093766ed779","x-qualifier":"$DEFAULT","x-rundeck-notification-execution-id":"377822","x-rundeck-notification-execution-status":"running","x-rundeck-notification-trigger":"start"},"httpMethod":"POST","path":"/WorkWeChat","pathParameters":{},"queryString":{"id":"0c42d1ed-4a4e-4cf1-be3a-d20caf69fa46"},"queryStringParameters":{},"requestContext":{"httpMethod":"ANY","identity":{},"path":"/WorkWeChat","serviceId":"service-b49gpptb","sourceIp":"182.92.1.1","stage":"release"}}

@MegaDrive68k
