### ISSUE TITLE
[Success notification] Sometimes send success notification twice

### ISSUE THREAD

**Issue by syuancheng** [rundeck/rundeck#6728]
**Describe the bug**
As is show in the below, I configure webhook on success. but actually I receive the post request twoce, you can see the same two XML notification.
![image](https://user-images.githubusercontent.com/45323956/104884525-77d53400-59a1-11eb-92cb-40f2b255c300.png)

![image](https://user-images.githubusercontent.com/45323956/104883780-3e4ff900-59a0-11eb-9f28-13eb583a98ca.png)

**My Rundeck detail**

* Rundeck version: 3.3.6-20201111
* install type: [choose: rpm,deb,war,launcher]
* OS Name/version: [e.g. ubuntu 16.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @syuancheng 

I'm trying to reproduce your issue on 3.3.6 / 3.3.8 (against webhook.info service) and works as expected. Do you have only one rundeck instance running that job?

Regards!
