### ISSUE TITLE
Database unlimited growth when regularily reimporting jobs

### ISSUE THREAD

**Issue by mveroone** [rundeck/rundeck#6731]
**Describe the bug**
The workflow/workflow_steep/workflow_workflow_step tables grow unlimitedly when jobs are recreated regularily

**My Rundeck detail**

* Rundeck version: 3.2.1 (reproduced in 3.4.4 too)
* install type: rpm
* OS Name/version: RHEL 7.9
* DB Type/version: MariaDB 5.6

**To Reproduce**
1. Create a project with a couple jobs.
2. Save the job definitions via scm export once.
3. reimport jobs regularily from this definition every hour for days
4. tables workflow/workflow_steep/workflow_workflow_step keep growing (7-15 million lines each in our case)

**Expected behavior**
These tables should only have a few hundred lines at most with our setup where we have ~15-20 projects with 50-70 jobs each.

**Screenshots**
![image](https://user-images.githubusercontent.com/44051537/105158154-f353f400-5b0d-11eb-8873-c2f7d6f6106b.png)

**Desktop (please complete the following information):**
N/A

**Additional context**
we import jobs using this command every hour for 95% of the server's jobs.
```
    rd jobs load -F yaml -r -p $project -f ${IMPORT_FILE}
```

**Comment by mveroone** [comment]
Note that I've  tried to refine which lines to keep in these tables and to purge the extraneous ones but I failed to find which column made them "the real ones" or from which other table find the relevant id's.

In the end the bug is probably that recreating a job using this rd command (and thus the API behind it) doesn't clean the previous workflow_steps.

**Comment by MegaDrive68k** [comment]
Hi @mveroone 

Could you check the database size if you clean all executions? (or some executions). You can configure the Execution History Clean [feature](https://docs.rundeck.com/docs/manual/project-settings.html#execution-history-clean) (available on 3.2.1).

Regards.

**Comment by mveroone** [comment]
Hi @MegaDrive68k ,
I already have execution cleaning on all my projects, configured to keep only 60 days or 500 executions maximum across ~20 projects. But the tables I'm mentioning (`workflow_*` are relative to the project jobs not executions I believe. (but I may be wrong ?)
Does the cleaning feature produce any logs I could search for to confirm this hypothesis ?

Thanks for the input any way.

**Comment by MegaDrive68k** [comment]
Hi @mveroone 

By design, those tables store execution data, check the table size without executions on a test environment of course (at least fewer executions).

Greetings!

**Comment by MegaDrive68k** [comment]
Hi @mveroone 

You can add `hibernate.show_sql=true` line to your `rundeck-config.properties` file (and restart your instance) to see all database activity on service.log (`tail -f /var/log/rundeck/service.log`).

Regards.

**Comment by mveroone** [comment]
> Hi @mveroone
> 
> By design, those tables store execution data, check the table size without executions on a test environment of course (at least fewer executions).
> 
> Greetings!

Also, I do believe they hold more than that because when i tried to purge some data from them, I ended up having jobs (not executions, jobs) with no workflow steps anymore !

Note that I have ~7000 lines in the `execution` table which seems normal, while having 15 millions in `workflow_*` table doesn't.

**Comment by mveroone** [comment]
I've done another attempt for analysis on our preproduction instance.
I've verified execution cleaning is correctly set up on all projects, and for example running this script doesn't produce a single DELETE query :
https://gist.github.com/guzmanbraso/c45ac5c2ab743c09bf7b5bcbe43e1bde

Yet my workflow_step table holds 17 million lines and the MySQL partition is growing over 25GB now...
The response times of rundeck are still okay and the space isn't really an issue, but it's getting harder to backup the database (and longer to restore it) for seamingly no reason.

And sorry I missed your latest message :
> You can add hibernate.show_sql=true line to your rundeck-config.properties file (and restart your instance) to see all database activity on service.log (tail -f /var/log/rundeck/service.log).

I've tried to enable GENERAL_LOG in MariaDB but it's very verbose. Can you let me know during which process you're interested to see the log, so I only enable it for a short duration ?

**Comment by mveroone** [comment]
hey @MegaDrive68k,  any idea on when I should enable SQL logging ? as I said, it might be very verbose if I just let it on for hours...

**Comment by mveroone** [comment]
Hey.
I'm still having my databases growing uncontrollably, and I don't know what to do about it =/
My only idea would be to reinstall everything from scratch, so my DB isn't a relic from a 2.x version with wrong column order etc...

**Comment by MegaDrive68k** [comment]
Hi @mveroone 

You're right, I think that a good approach is to use a fresh database with the latest Rundeck version (3.3.10 at this moment) and set up the [execution history clean](url) feature to manage a lot of executions (if you have a lot of executions that information is stored in the database, so, a good practice is to use that feature), the gap between 2.9 and 3.2 is big.

Make sure to backup all your data first, please take a look at [this](https://docs.rundeck.com/docs/administration/maintenance/backup.html#project-import-and-export) and [this](https://docs.rundeck.com/docs/administration/maintenance/backup.html#export-import-keys).

Regards.

**Comment by mveroone** [comment]
Hey MegaDrive68k (my boss loves your handle btw)
We have already automated the deployment of rundeck, its ssh keys, the creation of projects and any job dependencies, so it should be quick to do.
The only things we need to sort out are all monitoring and reporting that gather data from rundeck's database, as we can't afford a downtime, we'll build it on a new VM with new IP. But that's our concern =)
I'll let you know if it helps, but it'll take a couple monthes to know if it did, while the execution log refills and starts being cleaned.

**Comment by Z3r0Sum** [comment]
@MegaDrive68k and @mveroone we're experiencing something very similar with our Rundeck (now on version 3.3.5).  

> I think that a good approach is to use a fresh database with the latest Rundeck version (3.3.10 at this moment)

Are we saying that if we've been using the same database throughout the Rundeck upgrade process (which we have dating back to <2.9) this will cause issues with the cleaning execution functionality or some other internal operation keeping the `workflow` related tables sizes in check?  Is there anything we can update in the schema to overcome this hurdle if it exists?  It seems like a quick and dirty solution is to perform a cascading truncate on the `workflow` table, which will also wipe everything in `workflow_step` and `workflow_workflow_step` tables and cleanup any remnants from the `execution` and `scheduled_execution` tables.  Curious on your thoughts, thanks in advance.

**Comment by mveroone** [comment]
Following up on this, I have recreated one of our most active Rundeck servers from scratch, using the latest stable version available and importing as little as possible from the previous server. All install automation was rewritten, no project import occured, only recreation.
Yet, after 2 month of run, the growth is still here. the  workflow_step table is 4 millions rows large and growing.

I'm pretty sure it's due to how we keep our projects' job definition up to date. Every hour, we re-import all jobs from a SCM export yaml files using `rd job load` I think there is a cleaning post-task that is missing in this process and new workflow_steps are being recreated 24 times a day for 14 different projects (that share job definitions but not config files and activity)

**Comment by mveroone** [comment]
Hey @rundeck I'm pretty sure we've bumped into a real bug here. I've went as far as I could deciphering your codebase but it's getting beyond my skillset at this point.
May we have some assistance please ?

**Comment by MegaDrive68k** [comment]
Reproduced, reimporting the same job multiple times the DB size grows (Reported before on Rundeckpro repository)

Using rd-cli over H2:

<img width="665" alt="Screen Shot 2021-09-29 at 11 24 13" src="https://user-images.githubusercontent.com/51376003/135288833-ff614515-0031-4d8a-808f-2e191093fc2d.png">

Happening on 3.4.4 too.

**Comment by mveroone** [comment]
Hi. This bug is almost a year old.
The consequence of that is that some DB are so big that the migration code from 3.2 to 3.3+ times out after 90min no matter how we optimize the MySQL server.
We'll have to reinstall the whole servers to start from fresh DB but it'll happen again next time a version change modifies the database...

Any update on the investigation ?

**Comment by MegaDrive68k** [comment]
Hi!

On the latest version (4.1.0 at this moment) this issue is fixed:

![Screen Shot 2022-04-27 at 10 47 18](https://user-images.githubusercontent.com/51376003/165548541-7eabb2d2-f425-4a6d-9e4a-7ba9aed51217.png)

Regards!

**Comment by derekl-beep** [comment]
Hi @MegaDrive68k, we still run into the same issue after upgrading to a newer rundeck.

My Rundeck detail
Rundeck version: 4.7.0 (reproduced in our previous 3.3.5 too)
install type: docker (rundeck/rundeck:4.7.0)
OS Name/Version: Fedora36
DB Type/version: Postgres 14.5

Do you have an idea why this is the case?

This is the table row count before & after re-importing all jobs once. The growth is ~ the number of jobs. 
The same row count on all three tables - `workflow`, `workflow_step`, and `workflow_workflow_step`.

![image](https://user-images.githubusercontent.com/58062710/202954662-3469c1aa-42d1-4ae6-98f7-463f82cd33a1.png)

**Comment by derekl-beep** [comment]
Hi @MegaDrive68k, following the above comment, I took a further look into the issue. As I re-import the jobs with rundeck-cli using this command `rd projects scm perform -A -a import-jobs -i import -p <project>`

- The version of scheduled_executions is increased by 1 
- new workflows and workflow steps are created and linked to the scheduled_executions

These, thus, make the tables grow. Do you know if these are the expected behaviors?
