### ISSUE TITLE
Problem running aws command from UI (rundeck)

### ISSUE THREAD

**Issue by picoroma** [rundeck/rundeck#6741]
I recently updated to rundeck 3.3.8 and after some days some of my JOBS stops working (on localhost !).
After some analysis, I discovered that the awscli command, "aws" is not more recognized correctly.
For example, If  I run "aws -help" (without quote) from rundeck server command line, it works correctly
BUT
If I run the same command from rundeck UI it do not work and give me this error:
_bash: aws: command not found
Failed: NonZeroResultCode: Remote command failed with exit status 127_

I have also updated to latest version of RUNDECK - But NO changes...
Others simple command like (id, whoami, pwd, ps etc etc) works fine
but aws don't !

**My Rundeck detail**

* Rundeck version: [ 3.3.8 - 3.3.9]
* install type: [choose: rpm]
* OS Name/version: [CentOS 7]
* DB Type/version: [mysql]

**Screenshots**
<img width="716" alt="Screenshot_2" src="https://user-images.githubusercontent.com/23618664/105626707-cf582180-5e31-11eb-8cfd-e335defba5a0.png">

**Desktop (please complete the following information):**
 - OS: [win10]
 - Browser [chrome]
 - Version [87]

**Additional context**

**Comment by MegaDrive68k** [comment]
Hi @picoroma 

Could you confirm if the `aws` command is available for the rundeck user? You see the same error if you call `awscli` using the full binary path?

![rdeck](https://user-images.githubusercontent.com/51376003/105707129-34268100-5ef1-11eb-8f2b-96d5a5379c3c.png)


Greetings.

**Comment by picoroma** [comment]
Hi The command "aws" is available for rundeck user.
I solved byself the problem.
I found out that if I use "localhost" as node name - this DO NOT work.
If I use "rundeck" instead (that is the hostname of my rundeck server) this WORK as expected.
