### ISSUE TITLE
Couldn’t follow symbolic link error issue while building using Mac Catalina OS

### ISSUE THREAD

**Issue by venkategowdap** [rundeck/rundeck#6742]
Hi Team , 

My build is failing with below issues when am trying to build , please suggest me any solution 

Issue type:  Rundeck build issue with Mac Catalina OS

 Task :rundeck:grails-spa:npmInstall FAILED
FAILURE: Build failed with an exception.
* What went wrong:
Failed to capture snapshot of output files for task ‘:rundeck:grails-spa:npmInstall’ property ‘$1’ during up-to-date check.
> Could not list contents of ‘Rundeck/rundeckapp/grails-spa/node_modules/.bin/not-in-publish’. Couldn’t follow symbolic link.

**My Rundeck detail**

* Rundeck version: 3.3.6

* OS Name/version: Mac Catalina OS

**Comment by MegaDrive68k** [comment]
Hi @venkategowdap 

Did you follow [these](https://stackoverflow.com/a/61553419/10426011) steps?

Regards.

**Comment by venkategowdap** [comment]
@MegaDrive68k :  Yes , i did all suggested earlier but still we are getting the same error ....am building locally with my My Mac OS catalina ... Any specific file/folder or dependency we need to address here ?
