### ISSUE TITLE
Configure usersync from docker image environment variables

### ISSUE THREAD

**Issue by frmrm** [rundeck/rundeck#6744]
**Is your feature request related to a problem? Please describe.**
Syncing user attributes when in preauth mode is a feature supported when writing your own config file from scratch, but not when using docker image environment variables.

**Describe the solution you'd like**
I'd like to be able to configure preauth mode user sync from docker image environment variables.

**Describe alternatives you've considered**
Sobbing.

**Additional context**
This seems like a pretty straightforward way to enhance the user experience of running Rundeck from the Docker image, but let me know if I'm way off base.

**Comment by monsdar** [comment]
Is it just me or is this nowhere to be documented? I found `RUNDECK_PREAUTH_USERSYNC_ENABLED` and `RUNDECK_PREAUTH_USERSYNC_EMAIL` by going through issues and code, but Env-var-names for `userFirstNameHeader` or `userLastNameHeader` are missing.
