### ISSUE TITLE
Community News "Subscribe" button does nothing

### ISSUE THREAD

**Issue by MegaDrive68k** [rundeck/rundeck#6747]
**Describe the bug**
Trying to subscribe on the Community News modal and pressing the "Subscribe" button does nothing, tested on Firefox and Chrome.

**My Rundeck detail**

* Rundeck version: 3.3.8, 3.3.9-rc2
* install type: WAR
* OS Name/version: Pop!_OS 20.10 (Ubuntu based distro).
* DB Type/version: H2

**To Reproduce**
1. Go to the Community News link (down to left).
2. Click on Subscribe red button (up to right).
3. Enter any email address on the email textbox.
4. Click on Subscribe modal red button.
5. The modal does nothing.

**Expected behavior**
An action/message confirming the subscription.

**Comment by fdevans** [comment]
fixed
