### ISSUE TITLE
CPU Profile / CPU Contention 

### ISSUE THREAD

**Issue by ReklessSVT** [rundeck/rundeck#6759]
Trying to figure out what the CPU Profile and CPU Contention links are for. When you click them they download something called pprof with no file extension and 0kb file size.

This is found under host:port/metrics/ in the browser.
![Capture](https://user-images.githubusercontent.com/75340571/106326371-5e0dd980-624a-11eb-9d02-c07e1d18cdd6.PNG)

**My Rundeck detail**

* Rundeck version: 3.3.1

![Capture](https://user-images.githubusercontent.com/75340571/106326371-5e0dd980-624a-11eb-9d02-c07e1d18cdd6.PNG)

**Comment by MegaDrive68k** [comment]
Confirmed. Also happening on 3.3.8.

**Comment by MegaDrive68k** [comment]
Still happening on 3.4.0-SNAPSHOT
