### ISSUE TITLE
Pagination does not work in a group, missing "next / prev" links

### ISSUE THREAD

**Issue by nmamn** [rundeck/rundeck#6764]
**Describe the bug**
Pagination with setting `rundeck.gui.paginatejobs.max.per.page` works fine on the homepage of a project, however it does not work inside a group. There is no way to navigate to the next / prev pages, and thus only the value of `rundeck.gui.paginatejobs.max.per.page` jobs are displayed. Other jobs are not listed / cannot be reached.

**My Rundeck detail**

* Rundeck version: 3.3.8
* install type: war
* OS Name/version: Ubuntu 18.04
* DB Type/version: mysql

**To Reproduce**
1. Create a new project and name it "Rundeck" for instance
2. Set `rundeck.gui.paginatejobs.enabled: true` and `rundeck.gui.paginatejobs.max.per.page` to 10
3. Create 11 jobs and add them under the "group1" group inside this "Rundeck" project
4. Navigate to RDK_URL/project/Rundeck/jobs to display all groups / jobs => pagination is there 👍 we can navigate to the next page
![RDK_all_jobs](https://user-images.githubusercontent.com/20321572/106744747-743be100-6620-11eb-9d99-c91ed058488b.png)
5. Navigate to RDK_URL/project/Rundeck/jobs/group1 to display only the jobs under "group1" => pagination is not there, only the first 10 jobs are displayed
![RDK_all_jobs_from_group1](https://user-images.githubusercontent.com/20321572/106744781-80c03980-6620-11eb-8b5c-653f0d49f756.png)

**Expected behavior**
We should be able to navigate to next / prev page even if we are in the context of a group of jobs (same for subgroups etc.)

Thanks a lot :-)

Nicolas

**Comment by MegaDrive68k** [comment]
Reproduced, also happening on 3.3.9-rc4.

Thanks for your feedback @nmamn!

**Comment by nmamn** [comment]
That's funny, I just noticed that I reported the exact same bug one year ago ^^

https://github.com/rundeck/rundeck/issues/5820
