### ISSUE TITLE
Jobs ran within jobs are duplicating runs.

### ISSUE THREAD

**Issue by I12crash** [rundeck/rundeck#6765]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.3.9
* install type: rpm
* OS Name/version: Oracle Linux 7.9
* DB Type/version: mysql  Ver 15.1 Distrib 10.4.17-MariaDB, for Linux (x86_64) using readline 5.1

**Expected Behavior**
Jobs called within another job should execute each called job in serial.

**How to Reproduce**
Since we have updated to 3.3.9 using yum, we have seen all jobs that reference other jobs duplicating the runs. The duplication is not reflected in the definition or the workflow and occurs on adhoc and scheduled runs.

![Rundeck](https://user-images.githubusercontent.com/14820807/106752885-f1536000-65f8-11eb-91ec-107d197d4605.PNG)

**Comment by MegaDrive68k** [comment]
Hi @I12crash 

I'm trying to reproduce your case without success, can you share the service.log output at the moment of execution? Also, could you share a minimal reproducible job definition example to test?

Thanks!

**Comment by I12crash** [comment]
@MegaDrive68k We may have resolved our issue. We switched to Oracle JDK (shouldn't have made a difference) from Open JDK and updated to 3.3.9-1. I'll follow up tomorrow morning and close this if the issue is resolved.

**Comment by I12crash** [comment]
This can be closed. We seem to have a deeper issue we need to work on, we're no longer seeing the duplicated referenced job runs.
