### ISSUE TITLE
Uploading YAML job with empty options doesn't remove the old ones

### ISSUE THREAD

**Issue by maximeburri** [rundeck/rundeck#6774]
**Describe the bug**
When a job is created with some defined options and is exported in YAML job, removing the YAML `option` field or enforcing to empty array (`options:[]`) doesn't delete the old options.

**My Rundeck detail**

* Rundeck version: 3.3.5
* install type: war
* OS Name/version: Windows 7
* DB Type/version: default

**To Reproduce**
1. Upload the job YAML definition _v1_
<pre><code>
- defaultTab: nodes
  <b>description: v1</b>
  group: group_test
  loglevel: INFO
  name: test_remove_option
  <b>options:
  - delimiter: ','
    description: opt1
    enforced: true
    multivalued: true
    name: opt1
    required: true
    values:
    - val1
    - val2
    valuesListDelimiter: ','</b>
  sequence:
    commands:
    - exec: ls -lha
    keepgoing: false
    strategy: node-first
</pre></code>
>  _Everything works as exepcted here_
2. Upload the same job YAML definition, with description to _v2_ and an added option _opt2_
<pre><code>
- defaultTab: nodes
  <b>description: v2</b>
  group: group_test
  loglevel: INFO
  name: test_remove_option
  options:
  - delimiter: ','
    description: opt1
    enforced: true
    multivalued: true
    name: opt1
    required: true
    values:
    - val1
    - val2
    valuesListDelimiter: ','
  <b>- delimiter: ','
    description: opt2
    enforced: true
    multivalued: true
    name: opt2
    required: true
    values:
    - val1
    - val2
    valuesListDelimiter: ','</b>
  sequence:
    commands:
    - exec: ls -lha
    keepgoing: false
    strategy: node-first
</pre></code>
> _This is okay, the second option is added._
3. Upload the same job YAML definition, with description to _v3_ and set options to empty array to remove them
<pre><code>
- defaultTab: nodes
  <b>description: v3</b>
  group: group_test
  loglevel: INFO
  name: test_remove_option
  <b>options: []</b>
  sequence:
    commands:
    - exec: ls -lha
    keepgoing: false
    strategy: node-first
</pre></code>
> **The option _opt1_ and _opt2_ are always there even if the field _options_ is removed.**

**Expected behavior**
The options should be removed

**Screenshots**
![Capture](https://user-images.githubusercontent.com/5551924/107482824-81a51e00-6b80-11eb-8784-e4e187cfe3b0.PNG)

**Desktop:**
 - OS: win7
 - Browser: all
 - Version: ...

**Additional context**
Finding that using the rundeck java CLI to upload YAML jobs but tested with the GUI via the upload button. It is problematic when you use the API to upload some YAML jobs automatically with some script.

**Comment by MegaDrive68k** [comment]
Reproduced following the [same](https://github.com/rundeck/rundeck/issues/6774#issue-805288302) steps.

Thanks for the feedback @maximeburri!

**Comment by maximeburri** [comment]
Thank you @MegaDrive68k for taking charge of this problem and for reproducing it.

Do you plan to solve this issue ?
