### ISSUE TITLE
X-FORWARDED-PORT is ignored

### ISSUE THREAD

**Issue by EmFl** [rundeck/rundeck#6776]
**Describe the bug**

I'm running rundeck fronted by an apache reverse proxy that handles authentication via oauth. This apache reverse proxy is also fronted by a load balancer. Because apache is not running as root, it runs on port 8443. This means that my current setup is:
Load balancer (443) -> Apache (8443 + ssl termination) -> Rundeck (4440)
I've set the:
- RUNDECK_GRAILS_URL to my public url (so with https on port 443) 
- RUNDECK_SERVER_FORWARDED to true

I've also tried on apache side to set the ProxyPreserveHost, X-Forwarded-Host, X-Forwarded-Port, X-Forwarded-Proto but none seem to impact any of this.

On first access to rundeck, I get to /redirect_uri after successfully authenticating but then this gives me a 302 to my public url on port 8443 (so the port for my apache reverse proxy).

My guess is that rundeck somehow appends the source port to the redirect uri to determine the public url on first access but I was hoping that X-Forwarded-Port would be honored (even though this isn't in the RFC).

It seems that jetty handles this: https://github.com/eclipse/jetty.project/pull/3972

**My Rundeck detail**

* Rundeck version: 3.3.6 
* install type: docker

**Expected behavior**
I would expect rundeck to honor X-Forwarded-Port or stick to grails.url parameters and not append the port based on the source connection.

**Comment by ProTip** [comment]
Hi @EmFl ,

Our Docker Zoo [Cloud Example](https://github.com/rundeck/docker-zoo/tree/master/cloud) utilizes `RUNDECK_SERVER_FORWARDED` along with a reverse proxy to go from `80` to `4440`. I've also run end-to-end encryption with an intermediate terminating proxy internally.

Is it possible the the the apache proxy is not forwarding or appending to the appropriate `X-Forwarded` headers and is instead replacing or otherwise mangling them?

Thanks,
   -Greg

**Comment by EmFl** [comment]
Hey, thanks for getting back to me on this.
I've reconfirmed that the headers are all properly set by replacing rundeck by something that dumps headers behind the reverse proxy:
```
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Forwarded-For: {{my_public_ip}}
X-Forwarded-Host: {{rundeck_public_url}}
X-Forwarded-Server: {{rundeck_public_url}}
Connection: Keep-Alive
```

You can see this issue only when your public port is different than your reverse proxy port so this might not be a problem for many people... 

But this is easy to test even without something fronting your reverse proxy:
- if you force your reverse proxy to set X-Forwarded-Port to 9999 for example, then you can see that rundeck still redirects to 443 (or whatever the port the reverse proxy is running on)

Thanks

**Comment by EmFl** [comment]
Hello,
Have you been able to reproduce this on your end ?
Thanks
