### ISSUE TITLE
Issues with Key Storage where you can put both key types with the same path/name

### ISSUE THREAD

**Issue by jgarces-pd** [rundeck/rundeck#6779]
# Issue type: Bug report

## My Rundeck detail

* Rundeck version: 3.3.9 Community / PRO
* install type: WAR / RPM
* OS Name/version: Ubuntu 20.10 / CentOS7
* DB Type/version: H2

## Expected Behavior
Overwrite the file and replace the key type, warning it, or denying.

## How to Reproduce
- Create a Key under the Storage Vault of Rundeck, e.g. keys/something as password
- Create a new key using the same path and name as private key

## Screenshot
![2021-02-11_13h26_01](https://user-images.githubusercontent.com/74255967/107666966-e1c5be00-6c6d-11eb-8bd0-4d298a2c876c.png)

**Comment by MegaDrive68k** [comment]
Confirmed.

**Comment by jgarces-pd** [comment]
printing the value doesn't do anything (blank):
![image](https://user-images.githubusercontent.com/74255967/107667194-1b96c480-6c6e-11eb-96dc-1eaee5a3bf1b.png)
![image](https://user-images.githubusercontent.com/74255967/107667263-2cdfd100-6c6e-11eb-9fec-8a8b81d6993e.png)
![image](https://user-images.githubusercontent.com/74255967/107667308-38cb9300-6c6e-11eb-8998-f08e0fb3c470.png)
