### ISSUE TITLE
Unable to save Method option of 'Send Webhook' in JOB Notification 

### ISSUE THREAD

**Issue by hidehara** [rundeck/rundeck#6792]
**Describe the bug**
When I try to create a webhook, I can't save the Method (POST/GET) selection.

**My Rundeck detail**

* Rundeck version: 3.3.9 OSS and ENTERPRISE (under trial)
* install type: war
* OS Name/version: Windows Server 2012 R2
* DB Type/version: H2 integrated

**To Reproduce**
1. Go to a job's 'Notifications'
2. Click on 'Add Notification' in On Start or Any
3. Select 'Send Webhook' from 'Notification Type'
4. Filling URL, PayloadFormat, Method
5. Click 'Save' of 'Edit Notification'. After this, I can see correct setting on list of Notification with Method
6. Click 'Save' of 'Edit Job'
7. Come back to the job's 'Notifications'
8. Now selected Method is lost. If I Edit it, value of Method is ' --None Selected--'

**Expected behavior**
keep selecting value

**Screenshots**
After click 'Save' of 'Edit Notification'. looks good.
![Rundeck_job_notification_after_save-of_notification](https://user-images.githubusercontent.com/4308281/108188737-4643ba00-7153-11eb-85a1-ddd37a0761e3.png)

But After come back to the job's 'Notifications'. Method selection was lost.

![Rundeck_job_notification_when_comeback](https://user-images.githubusercontent.com/4308281/108188665-30ce9000-7153-11eb-8010-8cd75d7e544f.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2012 R2 (Japanese Edition)
 - Browser Chrome
 - Version (Latest)

**Comment by jfath** [comment]
Same issue here

**Comment by yatt** [comment]
I also have encountered same matter.

**My Rundeck detail**

* Rundeck version: 3.3.10-20210301
* install type: rpm
* OS Name/version: CentOS 7.9 (2009)
* DB Type/version: H2 integrated

**Desktop (please complete the following information):**
 - OS: Windows10 Pro
 - Browser Chrome
 - Version 89.0.4389.90

**Comment by xavier8854** [comment]
Plussed
Rundeck 3.3.11 rpm/RHEL7
DBType MariaDB

**Comment by MegaDrive68k** [comment]
Confirmed on 3.3.12 / 3.4.0-RC3.

Thanks for your feedback @hidehara!
