### ISSUE TITLE
Specific schedule on a job : not correctly restored

### ISSUE THREAD

**Issue by tazou** [rundeck/rundeck#6793]
**Describe the bug**
Hello,
On a job configured with a schedule with the "crontab" tab and a pattern like "*/5", if I edit the job, disable the schedule, save the job, edit the job again and enable the schedule, then the previous configuration is lost.

If I do the same procedure with the "Simple" tab, the configuration is not lost.

**My Rundeck detail**

* Rundeck version: 3.3.6.20201111-1
* install type: deb
* OS Name/version: Debian 9.13
* DB Type/version: postgres

**To Reproduce**
1. Go to edit a job
2. Setup the schelude with : 0 */5 * ? * * * (rundeck will execute the job every 5 minutes)
3. Save (All is working)
4. Edit the job again, disable the schedule option and save the job.
5. Edit the job again, enable the schedule, then the crontab tab doesn't contain the previous informations (0 */5 * ? * * *) but "0 00 00 ? * * *" instead.

**Expected behavior**
The job must backup the correct crontab.

**Screenshots**
The configured crontab : 
![image](https://user-images.githubusercontent.com/6482957/108211719-59439380-712d-11eb-966e-c1a3afd09a4b.png)

The bug after : 
![image](https://user-images.githubusercontent.com/6482957/108197623-eaf5d580-711a-11eb-8074-fe27d704d2f2.png)

Thanks,
Best regards.

**Comment by MegaDrive68k** [comment]
Hi @tazou 

That behavior is expected, if you save disabling the schedule on the job definition, the job now is saved without any cron defined (and you can check it if you download the job definition).

A good way to manage this is to set your schedule and use the "disable schedule" option on the "Actions" button (jobs page).

Hope it helps!

**Comment by tazou** [comment]
Hello,
thanks for your answer.
I don't find this option sorry. Is it only on the Rundeck enterprise version ?
Thanks.

**Comment by MegaDrive68k** [comment]
Hi @tazou 

Go to the jobs page, and put the pointer to the right of the screen (to the right of each job), you can see a button named "Actions" (the button is visible passing the pointer in that section) there you can disable the schedule.

![Untitled](https://user-images.githubusercontent.com/51376003/110344172-fe0a1000-800b-11eb-84de-ddc5dae83f28.png)

Greetings!

**Comment by tazou** [comment]
Hello,
thanks for your help.
I already look at this part, but it doesn't contain the "Disable schedule" option.
You can see my screenshot here : 
![image](https://user-images.githubusercontent.com/6482957/110438641-e045b500-80b6-11eb-8e84-b23c4ce960fb.png)

Maybe this option is not present on the rundeck version 3.3.6.20201111-1 ?
Or maybe must I setup a special option on my /etc/rundeck/rundeck-config.properties file ?

Bests regards.

**Comment by MegaDrive68k** [comment]
Hi @tazou

Check your ACLs, maybe some rule is denying the schedule toggle actions. Like this [thread](https://groups.google.com/g/rundeck-discuss/c/85LmqUFhB5s).

Greetings!

**Comment by hs-hub-world** [comment]
FYI - I believe a job must have the schedule setup/enabled in order for the Disable Schedule button to appear.

![image](https://user-images.githubusercontent.com/20629911/111638780-e5da8380-87b7-11eb-8774-f3c8d34bb515.png)

but, regardless - I agree with @tazou it should maintain the settings no matter what (or at the minimum must prompt the user to warn settings will be lost.)

Thanks,
HS

**Comment by tazou** [comment]
Hi, thank you !
I'll check my ACL asap and I'll give you feedback.
Regards,
Guillaume.

**Comment by tazou** [comment]
Hi @hs-hub-world 
Thank you ! I corrected my ACL and now I have the menu you showed !
Thanks :)
Regards,
Guillaume.
