### ISSUE TITLE
[2.0.1-1]  variable substitution adding quotes breaking windows command via winRM

### ISSUE THREAD

**Issue by spokrandt** [rundeck/rundeck#681]
when i execute this via winrm it fails with an error
`C:\Windows\System32\inetsrv\appcmd add site /name:Staging /physicalPath:"C:\inetpub\wwwroot\${option.Directory}" /bindings:https://:8443`

But running this completes
`C:\Windows\System32\inetsrv\appcmd add site /name:Staging /physicalPath:"C:\inetpub\wwwroot\approot-a” /bindings:https://:8443`

here is the error:

```
ERROR ( message:The identifier is not supported in the current command usage.  You specified "'/physicalPath:C:\inetpub\wwwroot\approot-a'". )
[overthere-winrm:10.0.0.146] failed: exit code: 87
Failed: NonZeroResultCode: [overthere-winrm] result code: 87 
```

looked closer at the debug logs and for some reason rundeck is putting '' around the /physicalPath:"C:\inetpub\wwwroot\approot-a” if I use the ${option.Directory} variable 

here is the string after substitution
`C:\Windows\System32\inetsrv\appcmd add site /name:Staging '/physicalPath:"C:\inetpub\wwwroot\approot-a"' /bindings:https://:8443`

then windows pukes, winrm returns the windows error to rundeck...

**Comment by gMickey** [comment]
Hi!
I'm also running into this issue, single quoting in windows cmd shell causes `The filename, directory name, or volume label syntax is incorrect.`
