### ISSUE TITLE
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: MultiNodeSelector{nodenames=[server231]}

### ISSUE THREAD

**Issue by wep-p** [rundeck/rundeck#6813]
**Describe the bug**
This error seemingly appears at random, for all kind of jobs which executed successfully hundred times before and after. It doesnt matter if the Projekt/Job is executed locally (stub) or on remote nodes via ssh/scp configuration. We updated rundeck through various versions since 3.0.21 to the latest release 3.3.8 and the error always kept appearing at maybe 5% to 10% of the executions. After re-executing after this error, the job always runs successfully. As we are intending to use Rundeck as an automation tool mostly via api, this random behaviour makes it hard to integrate at the moment.  

**My Rundeck detail**

* Rundeck version: 3.x.x - 3.3.8
* install type: war
* OS Name/version: SLES 12 / SLES 15
* DB Type/version: postgres

![image](https://user-images.githubusercontent.com/54305075/108966608-ab7d3b00-767e-11eb-84b1-98e43e0a358c.png)

**Comment by MegaDrive68k** [comment]
Hi @wep-p 

Are you using a specific node cache configuration? could you try [this](https://github.com/rundeck/rundeck/issues/2942#issuecomment-360573113)?

Greetings.
