### ISSUE TITLE
Queue to schedue jobs to run in serial?

### ISSUE THREAD

**Issue by falloutphil** [rundeck/rundeck#6814]
**Describe the solution you'd like**
I'd like to be able to have an end-user schedule a bunch of jobs, and have them run in serial/sequence, unattended overnight.  This cannot be done with a single job with multiple reference job steps, as the inputs, order, and type of was job would differ each and every night

Instead each job could be scheduled on its own by the end-user - this would be added to the drop-down to right of the "Run Job Now" button.  At the moment this already supports running jobs a future calendar event, but where jobs must be run in serial, this is inefficient as ample time must be left between job schedules to avoid overlap.

The schedule may contain multiple runs of the same job and/or different jobs.  Jobs would be run in serial or in parallel depending on settings within that job dictating if multiple runs are allowed at once - otherwise it would queue and wait.

**Describe alternatives you've considered**
We're looking at writing the plugin ourselves (I assume none exists?) to do this - if it's possible to write a queue based scheduled and a plugin to edit the contents on the run-job menu in Groovy?  Any advice or comments on this would be greatly received.  If it's impossible or very difficult to do via plugin we would look to write a separate web service to handle the queue and allow this via calls to Rundeck API - but it would be nicer to have the whole thing inside Rundeck proper.  

Any thoughts?

**Comment by MathewHouse** [comment]
Related to @falloutphil issue it would be helpful to see where each job is running (on what Node). If we kick off several jobs at the same time we want to rapidly see the Node usage. I can understand that Rundeck can't easily display the Node usage details (CPU/memory/etc.) however, on my side, having the Node name where the job runs on the **"Activity" page**  would help a lot.

**Comment by ahormazabal** [comment]
Job Queue implemented on Rundeck Enterprise 3.4.0
https://docs.rundeck.com/docs/history/3_4_x/version-3.4.0.html#job-queuing-enterprise
