### ISSUE TITLE
Password utility only suggests broken algorithms for property file authentication provider

### ISSUE THREAD

**Issue by NattyNarwhal** [rundeck/rundeck#6817]
**Describe the bug**

The documentation for the property file implies that it only supports some weak, broken algorithms like crypt or md5, as this is what the password utility generates. I don't know if this is an intrinsic limitation of the authentication provider, or the documentation and tooling neglecting to mention better and more appropriate algorithms.

I have the impression the property file provider is only intended for small dev/test installations, but that doesn't mean they should have compromised security.

**My Rundeck detail**

* Rundeck version: 3.3.9
* install type: war
* OS Name/version: i 7.4
* DB Type/version: h2

**To Reproduce**

Attempt to create a new password hash (in password utility or `--encryptpwd`)

**Expected behavior**

A better hashing algorithm (i.e bcrypt)

**Screenshots**

The [relevant page in the docs](https://docs.rundeck.com/docs/administration/security/authentication.html#propertyfileloginmodule) if it changes;

![Screenshot from 2021-02-24 18-18-11](https://user-images.githubusercontent.com/3161292/109073653-1190af00-76cd-11eb-8a99-4b91d5c2b710.png)

**Additional context**

[crypt](https://en.wikipedia.org/wiki/Crypt_%28Unix%29#Breaking_crypt(1)_encryption) and [MD5](https://en.wikipedia.org/wiki/MD5#Security) have been known to have been broken for years. Casual use of them hurts my confidence in the software.

**Comment by ProTip** [comment]
Hi @NattyNarwhal ,

In general we do not recommend using `realm.properties` in production. Within the context of `realm.properties` though, do you have any specific concerns utilizing `md5` to hash a secure, random password with high entropy?

**Comment by NattyNarwhal** [comment]
Sorry for not replying earlier. I'm certainly not a crypto expert, but I would think anything I say about this isn't radical.

I do understand your recommendations on auth providers. We've been testing mostly in development environments, but we've experimented with a small production deployment; in those cases, the platform we're deploying to doesn't support PAM, and few run LDAP (or if they do, don't expose it to that part of infra). So the realm file should be OK in that scenario, but we're open to getting a better replacement. Regardless of where it's deployed (dev/prod), I would hope that the password hashing is better than MD5. Using it today makes me raise my eyebrows a little.

MD5 isn't really an appropriate fit regardless of if it's been broken or not; it's designed for quick and unsalted hashing, which is good for file integrity, bad for passwords. Its use for secure contexts like TLS has been [deprecated](https://tools.ietf.org/id/draft-lvelvindron-tls-md5-sha1-deprecate-01.html).

Algorithms designed for hashing like bcrypt or argon2 (not vouching for anything specific) specifically factor in salting (so you can't just make rainbow tables) and intentionally being slow (to prevent brute forcing).

**Comment by NattyNarwhal** [comment]
And to add, I'm really not sure why crypt and obfuscate are even suggested; crypt has been broken for eons (just run john the ripper) and obsfuscate isn't even any kind of cryptographic thing. I assume these came out of a library?
