### ISSUE TITLE
2.11.14 upgrade and MySQL issues

### ISSUE THREAD

**Issue by jfarcher** [rundeck/rundeck#6819]
Hi,
I'm running into numerous errors and wondered if anyone can help.

I've got a rundeck service at the moment, its on 2.11.14 running inside an ubuntu 16.04 docker on OpenJDK JRE 8
Its connected to a MySQL database (on AWS RDS)

All this is running fine, but I would obviously like to upgrade both the Docker image to 20.04 and Rundeck to a later version.

Rather than just upgrade in place I wanted to take a copy of everything and do it in a sandbox first, however I seem to be having no end of issues in doing so.

My setup:

VM running Ubuntu 20.04 with OpenJDK JRE 8 installed and Rundeck 2.11.14 installed using deb packages
If I start Rundeck I get the login page and all looks good.

I then spun up a second VM running MySQL and setup a database and user who has privileges to that database.
I double checked I could connect from the original VM and all was good.

I then reconfigured Rundeck to use the mysql database as its source with the following in /etc/rundeck/rundeck-config.properties
```
#dataSource.url = jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true
dataSource.url = jdbc:mysql://192.168.1.140/rundeck?autoReconnect=true&useSSL=false
dataSource.username=dave
dataSource.password=balderdash123
dataSource.driverClassName=com.mysql.jdbc.Driver
```

upon restarting rundeckd there are messages that rundeck cannot create connections to the database server.
Along the lines of:
`Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.`

Now I know the above config works normally as this is the same as in the running version I first mentioned.

My second set of issues come with the upgrade.
I can never get Rundeck to start properly after upgrades. I've tried numerous packages and configurations. Spinning up brand new VMs each time to make sure I'm working from a clean install.

I will follow up with the log outputs from an upgrade.

**Comment by fdevans** [comment]
Hi @jfarcher.  Our current version is 3.3.9.  Since the 2.x timeframe we have made a lot of improvements to the upgrade process between patch versions.  The jump from 2.x to 3.x does require a bit of work, but it will likely be the best solution to using the latest Ubuntu/MySQL.

**Comment by jfarcher** [comment]
Hi,
Thanks for your reply, yes that’s why I’m hoping to get us up to the latest versions just seems to be a challenge getting there at the moment.

I was wondering whether someone had seen the same issues I am.

Jon
