### ISSUE TITLE
ACL: Need to restart rundeck to see list of projects

### ISSUE THREAD

**Issue by dekiesel** [rundeck/rundeck#6821]
**Describe the bug**
When definining a new `.aclpolicy`-file I need to restart rundeck to be able to see allowed projects.
**My Rundeck detail**

* Rundeck version: [ 3.3.7]
* install type: [choose: war via docker]
* OS Name/version: [the one your docker container uses]
* DB Type/version: [choose: mysql ]

**To Reproduce**
1. Create a new policy file that allows the user to read all projects (used the one from the doc and added `read``to the project
2. Wait for the new policy file to be visible in rundeck
3. log in as the user/a user of the group
4. See that the project list is empty
**Expected behavior**
The projects list should contain the projects the user has access to without restarting rundeck.

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Brave]
 - Version [e.g. 1.20.108]

**Comment by MegaDrive68k** [comment]
Hi @dekiesel 

Could you test with the latest version (3.3.9 at this moment)? It seems the same behavior of [this](https://github.com/rundeck/rundeck/issues/6736) fixed issue.

Regards!

**Comment by dekiesel** [comment]
Hi @MegaDrive68k 

I just tested with 3.3.9, installed via docker and the issue persists. 

I started a new container and made sure there were only 2 aclpolicy files (the one I need to set up and the one for admin) and with both I had to restart rundeck to see the project list.

**Comment by MegaDrive68k** [comment]
Hi @dekiesel 

You're right. I checked and that is expected behavior if you upload the ACL files manually after Rundeck startup, alternatively, you can use the GUI or the [API](https://docs.rundeck.com/docs/api/rundeck-api.html#create-an-acl-policy) / [RD-CLI](https://rundeck.github.io/rundeck-cli/) to create it and take the effect immediately.

Regards.

**Comment by tbe** [comment]
Wie have the same issue, even after uploading an ACL file via the GUI.

```  
[2021-10-01T18:11:31,095] WARN  authorization.LoggingAuthorization - Evaluating Decision for: res<type:resource, kind:plugin> subject<Username:inc63700 Group:inc63700> action<read> env<rundeck:auth:env:application:rundeck>: authorized: 
false: REJECTED, reason: REJECTED, evaluations:         ACLRule</rundeck/rundeck/rundeck/etc/inc63700.aclpolicy[1][type:project][rule: 1]>{​​​​​​​​'generated' context={​​​​​​​​application='rundeck'}​​​​​​​​ type='project' equals , resource={​​​​​​​​name=INC63700}​​​​​​​​ for:
{​​​​​​​​ group='inc63700'}​​​​​​​​ allow=[read]}​​​​​​​​ REJECTED for action read => REJECTED (0ms)
```
 
```    
$ rd acl test  --dir /rundeck/rundeck/rundeck/etc -c application -p INC63700 -g inc63700  -a read 
# WARNING: RD_INSECURE_SSL=true, no hostname or certificate trust verification will be performed
The decision was: allowed
The test passed
```

After a restart, the ACL works as expected.
