### ISSUE TITLE
Bintray OSS repo systematically returns error 403

### ISSUE THREAD

**Issue by sephiroth1395** [rundeck/rundeck#6824]
**Describe the bug**
Since the beginning of 2021, I systematically get an error 403 whenever I attempt update APT versus the bintray OSS repo.  Same behaviour is met when attempting to download the deb directly from a web browser.
This prevents me from updating from release 3.3.6.

**My Rundeck detail**

* Rundeck version: 3.3.6
* install type: deb
* OS Name/version: Debian 10
* DB Type/version: MySQL

**To Reproduce**
Attempt to download anything from the bintray OSS repo.

**Expected behavior**
Download succeeds.

**Screenshots**
```
Err https://rundeck.bintray.com/rundeck-deb  Release
  403  Forbidden [IP: 3.121.249.232 443]
Hit http://apt.puppetlabs.com buster InRelease
E: The repository 'https://rundeck.bintray.com/rundeck-deb  Release' no longer has a Release file.
E: Failed to download some files
W: Failed to fetch https://rundeck.bintray.com/rundeck-deb/Release: 403  Forbidden [IP: 3.121.249.232 443]
E: Some index files failed to download. They have been ignored, or old ones used instead.
```

**Comment by jouveits** [comment]
Same issue for the rpm repository on bintray: https://dl.bintray.com/rundeck/rundeck-rpm/

**Comment by 5gmt** [comment]
Unable to newly install rundeck to Amazon linux due to https://dl.bintray.com/rundeck/rundeck-rpm/repodata/repomd.xml returns 403.

**Comment by wufpack00** [comment]
Confirmed that we are seeing the same thing while attempting to upgrade to 3.3.7

**Comment by gschueler** [comment]
Note: bintray is [shutting down](https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/). We are working on setting up a replacement for future releases.

I'm not sure if this issue is related to that, or to rate-limiting or something, but we are investigating.

Thanks for the reports!

**Comment by fdevans** [comment]
I contacted BinTray and it seems there was an unresolved billing issue.  They have cleared it up on their end and the error notice that was showing on our account is now gone.  If someone is willing to try and confirm that the 403 errors are cleared up I can offer stickers to anyone up for testing it.

**Comment by cgahlon** [comment]
Still not working.  May take a bit to propagate through their systems.  I tested by trying to view the repomd.xml.asc file. 
 Link for convenience: https://dl.bintray.com/rundeck/rundeck-rpm/repodata/repomd.xml.asc

**Comment by sephiroth1395** [comment]
Really appreciate the issue was taken care of so quickly!  It does not work (yet?) but I'll give it a shot again at my next updates round.

**Comment by parker2037** [comment]
This issues appears to be back. Currently receiving a 403 for https://dl.bintray.com/rundeck/rundeck-rpm/repodata/repomd.xml

**Comment by MegaDrive68k** [comment]
Hi @parker2037 

Bintray is on maintenance right now :-)

You can check the status [here](https://status.bintray.com/).

Regards.

**Comment by parker2037** [comment]
My mistake - thank you!
