### ISSUE TITLE
[2.0.1-1] Start the server for the first time does not allow import archive

### ISSUE THREAD

**Issue by lmayorga1980** [rundeck/rundeck#683]
I am trying to build a local vagrant box with rundeck but i can't find a way to import a _.jar_ archive from the first time it runs rundeck.  Maybe there is a command line?.

**Comment by lmayorga1980** [comment]
@gschueler 

Wondering if there is a way to import a .jar file from a command line even when the project already exists.

**Comment by gschueler** [comment]
@lmayorga1980 you can use the api to import an archive, the project must already exist.  There is not any api/cli tool to create a new project directly from an archive, it requires two steps to create the project, then import the archive

**Comment by lmayorga1980** [comment]
@gschueler it seems what I need. Can you point me to the right location?

**Comment by gschueler** [comment]
Here is the API documentation: http://rundeck.org/docs/api/index.html#project-archive-import

**Comment by lmayorga1980** [comment]
@gschueler wondering if that would be the same as importing the **.jar** file from the project section

**Comment by gschueler** [comment]
@lmayorga1980 yes it is

**Comment by ahonor** [comment]
Reopen if this is still a concern
