### ISSUE TITLE
Seeing json error in response - even though rundeck job was triggered successfully

### ISSUE THREAD

**Issue by agarg136** [rundeck/rundeck#6834]
Issue type: Bug report/Enhancement Request

Able to send a request to rundeck job and get it triggered. However, the response is showing a json error - instead of proper json message with status.

{"level":"debug","ts":"2021-03-07T11:00:30.080-0500","caller":"decider/service.go:394","message":"Response ","trace_id":"0431690a-7044-4d09-8da9-e5325ca192a7","resError":"json: unsupported type: func() (io.ReadCloser, error)"}

**My Rundeck detail**

* Rundeck version:  3.2.8
* install type: (rpm,deb,war,launcher?) rpm 
* OS Name/version:   Mac
* DB Type/version: mysql? postgres? h2?..  postgres

**Expected Behavior**
Hi, I am trying to trigger a rundeck job and parse the response back.
I am able to get the job triggered with the code below but the response I am getting seems to point out an error with the json

**How to Reproduce**

Hi, I am trying to trigger a rundeck job and parse the response back.
I am able to get the job triggered with the code below but the response I am getting seems to point out an error with the json

This is how I am sending the request:-

url = env.Config().RunDeck().Address() + "/" + env.Config().RunDeck().JobId() + "/run?format=json"

if req, err = http.NewRequest("POST", url, bytes.NewBuffer(body)); err != nil {
	response.New(http.StatusBadRequest).Error("Bad Request").Write(w, r)
	return
}
req.Header.Add("X-RunDeck-Auth-Token", env.Config().RunDeck().AuthToken())
req.Header.Add("Accept", "application/json")
req.Header.Add("Content-Type", "application/json")

client := &http.Client{}
if resp, err = client.Do(req); err != nil {
	panic(err)
}
env.Logger().Debug("Response ", zap.Any("res", resp))

response.New(http.StatusFound).Result("Request submitted to trigger job on runDeck").Write(w, r)
This sends post request body to rundeck and triggers the job. However, I do not see a json response as I expected. Instead, I get this error message:-

{"level":"debug","ts":"2021-03-07T11:00:30.080-0500","caller":"decider/service.go:394","message":"Response ","trace_id":"0431690a-7044-4d09-8da9-e5325ca192a7","resError":"json: unsupported type: func() (io.ReadCloser, error)"}

Could anyone suggest what could be wrong here ?

**Comment by gschueler** [comment]
if you try the same thing with the rundeck cli tool (or using Curl), do you get the expected response? this seems like an error in the Go library perhaps

**Comment by agarg136** [comment]
Yeah, I see the response when I call the rundeck job url directly via POSTMAN.  It is when I invoke the POST using http.Post via golang is when I see the response as empty. Net.http is a standard package and I would expect it to be able to handle this.
As I read somewhere that rundeck posts the status of the job invocation on one of the other “notifications” end-point  so I was wondering if this was a rundeck issue.  Would you have a sample code on how should a client invoke the rundeck job which has a boy in the post request as well .
I could confirm if that still gives an issue or not..

From: Greg Schueler ***@***.***>
Date: Monday, March 15, 2021 at 2:44 PM
To: rundeck/rundeck ***@***.***>
Cc: Garg, Alok (Contractor) ***@***.***>, Author ***@***.***>
Subject: Re: [rundeck/rundeck] Seeing json error in response - even though rundeck job was triggered successfully (#6834)

if you try the same thing with the rundeck cli tool (or using Curl), do you get the expected response? this seems like an error in the Go library perhaps
