### ISSUE TITLE
Notifications Tab of the Job is not showing the values

### ISSUE THREAD

**Issue by babvin** [rundeck/rundeck#6857]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version:  3.3.10
* install type: (rpm,deb,war,launcher?) yum
* OS Name/version: NAME="Oracle Linux Server"
VERSION="7.9"
ID="ol"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.9"
PRETTY_NAME="Oracle Linux Server 7.9"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:oracle:linux:7:9:server"
HOME_URL="https://linux.oracle.com/"
BUG_REPORT_URL="https://bugzilla.oracle.com/"

ORACLE_BUGZILLA_PRODUCT="Oracle Linux 7"
ORACLE_BUGZILLA_PRODUCT_VERSION=7.9
ORACLE_SUPPORT_PRODUCT="Oracle Linux"
ORACLE_SUPPORT_PRODUCT_VERSION=7.9

* DB Type/version: mysql? postgres? h2?.. Postgress

**Expected Behavior**
When I go to the Notification tab and click on "Add Notification" I should get a window to configure the notification. 

**How to Reproduce**
NA - just installed via yum and unable to configure the notifications
<img width="719" alt="rundeck" src="https://user-images.githubusercontent.com/30034691/110786626-5eaa7e80-8292-11eb-8b9c-b058b1384778.png">

**Comment by MegaDrive68k** [comment]
Hi @babvin 

I'm trying to reproduce the issue. Your Rundeck instance is running behind some proxy/webserver? maybe you're facing this [issue](https://github.com/rundeck/rundeck/issues/5087). Could you share the browser dev console? (please hide any potentially sensitive information).

Thanks!

**Comment by babvin** [comment]
It's working after following the solution. Thank you!
https://github.com/rundeck/rundeck/issues/5087#issuecomment-515485568
