### ISSUE TITLE
dispatch cli tool should require -F option

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#686]
instead of defaulting to execute on server node

**Comment by gschueler** [comment]
@ahonor closing this issue in rundeck, do you think it should be copied to rundeck-cli?

**Comment by ahonor** [comment]
@gschueler -F to follow adhoc execution?

**Comment by gschueler** [comment]
requiring `-F/--filter` when you run `adhoc` command, instead of dispatching to server node by default
