### ISSUE TITLE
Rundeck doesn't auto start after reboot

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#6883]
Hi all

I'm running a fresh install on Ubuntu 20.04. Rundeck 3.3.10 (deb install) + Mariadb 10.5.9.

For some reason, Rundeck isn't starting automatically. After a reboot **service rundeckd status** shows:

```
Loaded: loaded (/etc/init.d/rundeckd; generated)
Active: inactive (dead)
```

I've checked both rundeck.log and service.log and they aren't showing any errors. Do we need to **systemctl rundeckd enable** for it to auto start? The installation page at https://docs.rundeck.com/docs/administration/maintenance/startup.html says:

> The RPM and DEB installations include the placement of the boot control script that will automatically start Rundeck when the system boots.

I'm not sure if this is a mistake, because putting a script in init.d doen't mean it will start automatically. Do we need to enable it manually or is this a bug with the installer?

**Comment by MegaDrive68k** [comment]
Hi @binaryfire 

Try with`sudo systemctl enable rundeckd`. That worked on my environment and it's needed to enable the service on every reboot.

Regards!

**Comment by binaryfire** [comment]
@MegaDrive68k Great, thought so. Thanks! The docs should probably be updated to correct that?
