### ISSUE TITLE
Allow pressing enter in node search field in jobs

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#6884]
Hi guys

When searching for nodes In the Nodes screen, we're able to press enter after entering a regex pattern. However this doesn't work in the filter inside jobs:
![2021-03-16](https://user-images.githubusercontent.com/5361908/111306963-c6a10080-86a8-11eb-8a4b-01f808444521.png)
 
 Adding this would be a nice usability improvement.

**Comment by MegaDrive68k** [comment]
Hi @binaryfire 

Yes, that's reported and reproduced [here](https://github.com/rundeck/rundeck/issues/6571).

Thanks for your feedback!
