### ISSUE TITLE
SELECT ? high load from ClouSQL insights

### ISSUE THREAD

**Issue by yanc0** [rundeck/rundeck#6885]
Hi there,

We are facing high load on a CloudSQL instance (GCP) with PostgreSQL engine. We don't know if rundeck is responsible of the high cpu load, instance is shared with other applications. However, Google Cloud has recently enabled "Query Insights" and we are wondering about this.

![image](https://user-images.githubusercontent.com/3806094/111342379-b1ad7880-867a-11eb-8199-ec2ced688a54.png)

As you can see, according to Insights, the top query "SELECT ?" is taking much more time than the other. Do you have any idea why ? I have never seen a prepared query like this, is this a Query Insights bug?

**My Rundeck detail**

* Rundeck version: 3.3.3
* install type: deb
* OS Name/version: Debian
* DB Type/version: Postgresql 9.6 (CloudSQL)

Thank you !

**Comment by ProTip** [comment]
Hi @yanc0 ,

Based on the number of calls I would assume this is the connection validation query `SELECT 1`. It runs very frequently to verify connections in the pool are active before/after use.

You can checkout the `rundeck-discuss` group if you need more community assistance with setup troubleshooting: https://groups.google.com/g/rundeck-discuss .
