### ISSUE TITLE
UI bug on Job -> Nodes tab 

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#6889]
Job "Nodes" tab:

Clicking on the word "Yes" for "Editable filter" (circled in red) selects the "Yes" radio button for "Show excluded nodes" (circled in blue) 

![2021-03-17](https://user-images.githubusercontent.com/5361908/111402984-1bca2a00-871c-11eb-9167-2837b70318dc.png)

**Comment by MegaDrive68k** [comment]
Confirmed, also happening on 3.4.0-SNAPSHOT.

Good catch @binaryfire, thanks!
