### ISSUE TITLE
Support LDAP /AD nested groups

### ISSUE THREAD

**Issue by ak0ska** [rundeck/rundeck#689]
The problem is described here: https://groups.google.com/forum/#!msg/rundeck-discuss/ddKa4SF6jD0/LtKmdjuaj6EJ

Haven't seen a ticket created for it.

**Comment by hekaldama** [comment]
Found out what helped me at least to overcome my nested issue. You need to add the ever so intuitive LDAP rule to your `roleMemberAttribute` like:

```
roleMemberAttribute="member:1.2.840.113556.1.4.1941:"
```

See: https://msdn.microsoft.com/en-us/library/windows/desktop/aa746475(v=vs.85).aspx notes on "1.2.840.113556.1.4.1941".
