### ISSUE TITLE
Notification payload format not honored on job UI upload or through Java Library

### ISSUE THREAD

**Issue by rossbundy** [rundeck/rundeck#6899]
**Describe the bug**
The Rundeck UI allows notifications to be set up with a payload format. When a job is created through the UI, and the notification payload format is set to JSON, the setting is honored as expect. Exporting an XML representation of the job shows the JSON setting in the XML. However, if the XML is uploaded through the Rundeck UI to create or update a job, or if the Java CLI Library is used to set the notification payload format, the JSON setting is not honored.

**My Rundeck detail**

* Rundeck version: 3.3.9-20210201
* install type: docker
* OS Name/version: linux centos 7
* DB Type/version: posgresql 12.5

**To Reproduce**
See attached video.

**Expected behavior**
When the notification payload format is set by uploading the job description through the UI or through the Java CLI Library, the setting should be honored.

**Screenshots**
See attached video.

**Desktop (please complete the following information):**
 - OS: Mac OS 10.15.1
 - Browser: Firefox
 - Version: 86.0.1 (64-bit)

**Additional context**
n/a

**Comment by Ashal148148** [comment]
The same thing happens when you duplicate a job, the notification payload format doesn't get duplicated. It shows up empty in the GUI and by default sends XML type payload. 
I have confirmed this issue on versions 3.3.10 using Linux as a host and 3.3.5 using Windows as a host.
