### ISSUE TITLE
keyfile as resources

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#69]
I think using a global application ssh identity file may be restrictive in some conditions. I'm thinking about the following use cases:

a XML file (_keys.xml_) like

@@@
<key name="group1">
 <file>$HOME/.ssh/mysecretkey</file>
</key>
@@@

with a special named _default_ for the default key.

This way, it wil very easy to manage differents keys for a node by adding _keyName_ attribute in a node definition, and if this attribut doesn't exists, the default key will be use.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/212)

Original Creator: Bruno Bonfils

**Comment by ahonor** [comment]
KeyStore handles this
