### ISSUE TITLE
Just got into Rundeck, small enough to run the open source version. Question about bintray

### ISSUE THREAD

**Issue by jeffdyke** [rundeck/rundeck#6924]
I'm sorry this is not a bug, but a rather question around long term open source hosting.  As you likely know bintray is sunsetting in less than 40 days.  Since i automate this build and configuration, I am curious about when releases will be moved.  https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

Its also not a configuration issue not a security issue, just a basic question. 

Thank You,
Jeff

**Comment by fdevans** [comment]
Hi @jeffdyke 
  Good question.  We will be moving to a new solution prior to the Bintray sunsetting along with our 3.4.0 release.  Look for the official announcement with changes/documentation updates etc. in the next few weeks.

**Comment by jeffdyke** [comment]
Just wanted to say thanks @fdevans
