### ISSUE TITLE
unsanitized HTML: script tags are ignored in log output

### ISSUE THREAD

**Issue by gangerli** [rundeck/rundeck#6931]
**Describe the bug**
The contents of  `<script>` tags in unsanitized HTML are ignored when viewed in the Log Output. 

**My Rundeck detail**

* Rundeck version: 3.3.10
* install type: deb
* OS Name/version: Ubuntu 18.04.5 LTS
* DB Type/version: H2

**To Reproduce**

1. Allow unsanitized HTML output in `framework.properties`
   ```
   framework.output.allowUnsanitized=true
   ```

2. Restart Rundeck

3. Allow unsanitized HTML output on the project
   ```
   project.output.allowUnsanitized=true
   ```
4. Create a job with a step that outputs the following HTML and add an unsanitized HTML formatter log filter:
   ```
   <html>
     <head>
       <title>Functions!!!</title>
       <script type="text/javascript">
        function nag()  {
          alert("boo!")
        }
       </script>
     </head>
     <body>
       <button type="button" onclick="(function () { alert('boo') })()">Attribute JS</button>
       <button type="button" onclick="nag()">Script JS</button>
     </body>
   </html>
   ```  

5. Run job with log output as the active tab

**Expected behavior**
Both buttons should produce an alert window when clicked.

**Observed behavior**
Only the button labeled "Attribute JS" works in the Log output. Interestingly, the `<script>` tags are not stripped, and if viewed as HTML, both buttons work as expected. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version: 86.0.1

**Additional context**
Known to work in earlier versions (independently confirmed in 3.2.1)

**Comment by MegaDrive68k** [comment]
Reproduced.

With this job definition:

```xml
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <id>7e99966c-5ef6-46ad-bc7c-a2dcf2a02e11</id>
    <loglevel>INFO</loglevel>
    <name>HTMLExample</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <exec>cat /path/to/the/html/file.html</exec>
        <plugins>
          <LogFilter type='render-datatype'>
            <config>
              <datatype>text/html</datatype>
              <sanitizeHtml>false</sanitizeHtml>
              <striped>true</striped>
            </config>
          </LogFilter>
        </plugins>
      </command>
    </sequence>
    <uuid>7e99966c-5ef6-46ad-bc7c-a2dcf2a02e11</uuid>
  </job>
</joblist>
```

This HTML code:

```html
<html>
<head>
	<title>Functions!!!</title>
	<script type="text/javascript">
      function myFunction()
      {
      	alert("boo!")
      }
	</script>
</head>
<body>
    <button type="button" onclick="(myFunction())">Nag</button>
</body>
</html> 
```

Adding this parameter at `framework.properties` file:

```
framework.output.allowUnsanitized=true
```

And setting "Allow Unsanitized HTML output" at project level:

![conf](https://user-images.githubusercontent.com/51376003/112699471-a45a7000-8e6a-11eb-948c-17d33caed921.png)

On 3.2.X it's posible to "Unsanitize" the log output (<script></script> tag is allowed):

![312](https://user-images.githubusercontent.com/51376003/112699484-ad4b4180-8e6a-11eb-8a20-55601232d88f.png)

But on 3.3.10 doesn't:

![3310](https://user-images.githubusercontent.com/51376003/112699491-b2a88c00-8e6a-11eb-8716-8224b44965b5.png)

Thanks for your feedback @gangerli!
