### ISSUE TITLE
All jobs set to "Execute locally" after importing a project archive

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#6941]
Hi guys

After importing a project archive, all jobs that were set to "Dispatch to nodes" are imported as "Execute locally". Steps to reproduce:

1. Create a job and set to "Dispatch to nodes".
2. Project -> Export archive
3. Delete the project
4. Create a new project and import the archive.
5. Check the job's "Nodes" setting. It will now be "Execute locally"

Cheers

**Comment by fdevans** [comment]
Hi @binaryfire,
Can you please provide more details?  Rundeck version, Operating System, etc. to help us replicate fully.

~Forrest

**Comment by binaryfire** [comment]
@fdevans Sure thing:

OS: Ubuntu 20.04
Rundeck version: 3.3.10
Db: MariaDB 10.5.9

Also, I'm running behind a NGINX reverse proxy but I doubt that'd make a difference in this case. 

Let me know if there's anything else you need

**Comment by MegaDrive68k** [comment]
Hi @binaryfire 

I'm trying to reproduce the issue, have you selected some option at the moment of export/import the project? (for example: "Remove UUIDs").

Greetings.

**Comment by binaryfire** [comment]
Hi Rainer. No, I preserved everything (UUIDs, referenced job names etc). Are you having trouble reproducing it?
