### ISSUE TITLE
Rundeck not recognising CURL error exit codes

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#6946]
HI guys,

curl has a **--fail** option which causes it to throw an error when the server returns an error code that is >= 400:

https://cdcvs.fnal.gov/redmine/projects/simons-dm/wiki/Curl_Error_Codes#:~:text=Curl%20Error%2022&text=This%20is%20returned%20if%20CURLOPT_FAILONERROR,error%20other%20than%20permission%20denied.

However Rundeck doesn't seem to pick up curl's exit codes. Steps to reproduce:

Create a job step with the following command:
`curl --fail -X POST https://gitlab.com/thereisnourlhere`

Curl will return an error and exit with code 22 but Rundeck marks the job as successful. I've noticed the same thing happens with exit code 5 (access denied).

Is it possible to fix this in Rundeck somehow? I'm currently using `if [ "$?" != 0 ]; then exit 1; fi` but it's pretty messy. Especially for scripts with a lot of curl commands.

Cheers

PS. The same problem happens with git. Unsuccessful commands pass because exit codes aren't registering with Rundeck.

**Comment by MegaDrive68k** [comment]
Hi @binaryfire 

Testing your command on Rundeck 3.3.10 I see an error:

![screenshot](https://user-images.githubusercontent.com/51376003/113612788-47a34600-961e-11eb-8947-d3ac962c7701.png)

Could you share a job definition example to test?

Regards!

**Comment by binaryfire** [comment]
Oops. My script was wrapped in a variable so of course it wouldn't be passing an exit code.

My bad! Closing this issue. Sorry to waste your time with this one.
