### ISSUE TITLE
add a config option to add the CORS support to rundeck

### ISSUE THREAD

**Issue by nutsh** [rundeck/rundeck#696]
I'm using jquery ajax , to call the rest api of Rundeck

like 

```
$.ajax(
{
  url:"{rundeck_url}/api/1/job/5?authtoken=D4CUK8DD5DP4sovSR7p9UUnd5DnvU3do"
}
);
```

but get error from brower for doing an XMLHttpRequest to a different
domain 

```
XMLHttpRequest cannot load {rundeck_url}/api/1/job/5?authtoken=D4CUK8DD5DP4sovSR7p9UUnd5DnvU3do. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '{site_url}' is therefore not allowed access. 
```

Could you please add CORS config to set up the  header for Cross-Origin ?

**Comment by Karanjax** [comment]
Has there been any solutions or updates regarding this?

**Comment by ProTip** [comment]
In Rundeck 3 you can configure CORS via the Grails settings: http://docs.grails.org/latest/guide/theWebLayer.html#cors .

In `rundeck-config.properties`:
```
grails.cors.enabled=true
grails.cors.allowedOrigins=http://localhost:5000
```

**Comment by sjrd218** [comment]
In your `rundeck-config.properties` you can add: `grails.cors.enabled=true` and then CORS will be enabled for your ajax requests.

**Comment by Karanjax** [comment]
We are using Rundeck 2.11.XX - will this work on  that version? If not, is there a different solution for Rundeck 2?

**Comment by sjrd218** [comment]
`grails.cors.enabled=true` only works on Rundeck 3.x. There is no support for CORS on Rundeck 2.
