### ISSUE TITLE
Rundeck in docker is not accessible from the outside - Links all point to http://127.0.0.1

### ISSUE THREAD

**Issue by lemmy04** [rundeck/rundeck#6968]
**Describe the bug**
I'm running rundeck in docker with this command:
`docker run -d --name rundeck -p 4440:4440 -v data:/home/rundeck/server/data rundeck/rundeck:3.3.10
`
When i first open http://testhost:4440" I get the login page, but once I log in all I get is an error from my browser stating "http://127.0.0.1:4440 - connection refused".

When I run the browser on the same host as the container it works as expected...

**My Rundeck detail**

* Rundeck version: 3.3.10
* install type: docker
* OS Name/version: openSUSE Leap 15.2
* DB Type/version: no external database

**To Reproduce**
1. docker run -d --name rundeck -p 4440:4440 -v data:/home/rundeck/server/data rundeck/rundeck:3.3.10
2. Access from a host other than the one the container is on
3. log in with admin/admin
3. See error: "Fehler: Verbindung fehlgeschlagen

Firefox kann keine Verbindung zu dem Server unter 127.0.0.1:4440 aufbauen."

**Expected behavior**
I should be able to use the application from any host in my network

**Desktop (please complete the following information):**
 - OS: Windows 10, Linux
 - Browser Firefox
 - Version 87

**Comment by three-old-coders** [comment]
Just a guess: 127.0.0.1 is not reachable from another host. Try your <host IP Adress:4440> and set the grails URL accordingly
RUNDECK_GRAILS_URL=http://<host IP Adress>:4440

docker run -d -e RUNDECK_GRAILS_URL=https://<hostIP>:4441 -e EXTERNAL_SERVER_URL=http://<hostIP>:4441 ...

Jens

**Comment by lemmy04** [comment]
> 
> 
> Try your "host_IP_Adress:4440" and set the grails URL accordingly
> RUNDECK_GRAILS_URL=http://host_IP_Adress:4440

Thats what i needed :)

so ... if I want to run this behind a proxy, i.e. nginx or traefik in K3s, what do I put in those variables...?

**Comment by lemmy04** [comment]
solved that - for a K3s pod behind a traefik LB both variables get the "final"  url, i.e. the one that you'd access with your webbrowser from the outside.

**Comment by fdevans** [comment]
https://docs.rundeck.com/docs/administration/configuration/docker.html#basic

@three-old-coders is correct.  Here are the docs with more specifics.
