### ISSUE TITLE
Context variable that contains the server URL for use in a workflow step script.

### ISSUE THREAD

**Issue by affert** [rundeck/rundeck#6969]
**Is your feature request related to a problem? Please describe.**
We have many jobs that report to PagerDuty via the PagerDuty notification plugin.  I want to include a link to the job in the information that goes to PD. 

We have a dev rundeck server and a prod one, so the URL needs to change when rolling out to prod.

**Describe the solution you'd like**
A variable (like @job.project@) to be available in a script that has the server URL in it.  For example @job.rundeck_server_url@ or something like that.

**Describe alternatives you've considered**
Up to this point, we have been hard-coding the link, which means it needs to be updated when we roll it out onto the prod server.

I could this is a 'key' that gets pulled in via an option, although that's a lot of extra work for something that should be simple.

**Additional context**
n/a

**Comment by gaddman** [comment]
At some point (Rundeck 4.?) this was implemented — you can use `@job.serverUrl@`.
