### ISSUE TITLE
Option model provider fails to validate allowed values with key/value pairs

### ISSUE THREAD

**Issue by nkitanov** [rundeck/rundeck#6989]
**Describe the bug**
When providing key/value pairs from option provider and enforce from allowed values, rundeck fails to validate as it's trying to validate against empty list. 

**My Rundeck detail**

* Rundeck version: 3.2.8
* install type: rpm
* OS Name/version: CentOS 7
* DB Type/version: postrgresql

**To Reproduce**
I have the following options in json:
```
[
  {"name":"switch", "value":21},
  {"name":"wifi-ap", "value":16}
]
```

Option definition:

```
  - enforced: true
    name: Device_role
    required: true
    valuesUrl: http://.../test.json
```

When I run this job with selected **switch** validation fails: `Option Device_role value: 21 was not in the allowed values: []`

**Expected behavior**
In the above example it should validate value 21.

**Comment by MegaDrive68k** [comment]
Same behavior on 3.3.10.

However, works using the JSON file in the following way (wrapping the values with double quotes):

```JSON
[
  {"name":"switch", "value":"21"},
  {"name":"wifi-ap", "value":"16"}
]
```
