### ISSUE TITLE
Rundeck 3.3.10 Notifications page not working

### ISSUE THREAD

**Issue by babvin** [rundeck/rundeck#6991]
**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
Unable to view the options in Notifications. I want to configure email notification but its not visible via UI

**My Rundeck detail**

* Rundeck version: 3.3.10
* install type: RPM
* OS Name/version: Oracle Linux
* DB Type/version: Postgres

**To Reproduce**
1. Go to Job
2. Click on Edit Job
3. Go to Notifications Link / Page
4. Options are not visible

**Expected behavior**
IS to configure email and webhooks plugins to integrate with Teams

**Screenshots**
![image](https://user-images.githubusercontent.com/30034691/115144407-1426d980-a06a-11eb-886a-d25c79600429.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome and Firefox
 - Version latest

**Additional context**
Grails mail host and port are details already present in rundeck-config properties file. Able to successfully send emails using other app/Python/telnet without credentials

**Comment by MegaDrive68k** [comment]
Hi @babvin,

[This](https://github.com/rundeck/rundeck/issues/6857) issue seems the same (opened by you), we can follow up there, on the original thread.

Thank you!
