### ISSUE TITLE
rd-setup does not set grails.serverURL property correctly

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#70]
When using rd-setup to configure RunDeck on a non-default port, the grails.serverURL property in the server/config/rundeck-config.properties file defaults to port 4440.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/234)

Original Creator: Martin Middleton

**Comment by ahonor** [comment]
rd-setup is obsolete.
