### ISSUE TITLE
Run job on 1 single available node from several defined using filters

### ISSUE THREAD

**Issue by ltoussaint** [rundeck/rundeck#700]
Hi,

The goal is to be able to run a job on a single node from a pool.

For now, if we want to run a job only one time, we need to explicitly defined the node.
But if this node is offline, the job will stop and never run.

So I would like to defined a job associated to a pool of nodes (using tags or other filters) but when the job will start, a single available node will be chosen from the pool.
To avoid offline node problems, if the chosen node is offline, the job should start on antoher one.

With this feature, it could be a good idea to **randomly** choose the node.

**Comment by ava-dylang** [comment]
:+1: I've yet to think of any way to hack this into the existing rundeck platform, but this is definitely a feature that we expected to have OOB with rundeck.  Now I've got to try to hack in a solution that works geesh.

**Comment by gschueler** [comment]
in the example code there is an example Orchestrator plugin that can do this.  the plugin is not distributed with rundeck out of the box yet (sorry), it needs to be compiled and installed

**Comment by akshah123** [comment]
:+1: this would be really useful as a way to load balance as well.  Certain tasks need only be run on one instance. This way you can have redundancy as well as a way to load balance such work loads.

**Comment by akshah123** [comment]
@gschueler which plugin is this?

**Comment by gschueler** [comment]
@akshah123 the orchestrator plugins are now bundled by default.  here is the code: https://github.com/rundeck/rundeck/tree/development/plugins/orchestrator-plugin

The [bundled plugins](http://rundeck.org/docs/plugins-user-guide/bundled-plugins.html#orchestrator-plugin) page describes the 3 bundled orchestrator plugins.

You can use the *Random Subset* orchestrator to pick only 1 node from the target set.

However, to achieve the feature of "To avoid offline node problems, if the chosen node is offline, the job should start on antoher one." you would have to either create a new Orchestrator plugin that can test whether a node is online/offline somehow (ask a load balancer?), or you could bake that feature into a Resource Model Source, that adds a special tag to online nodes only.  This tag could then be part of your job's node filters, and you could use the existing Orchestrator plugin as-is.

**Comment by akshah123** [comment]
@gschueler this is great! thank you so much.
