### ISSUE TITLE
Conditional display logic for options

### ISSUE THREAD

**Issue by binaryfire** [rundeck/rundeck#7005]
Hi guys,

It would be great if we hide an option unless a "parent" option has a certain value. For example, lets say we have Foo (a "parent" option) and Bar (only needed when Foo = yes).

In the "Should be hidden" settings of Bar there could be a third setting for "Only show if OPTION equals VALUE". There we would set OPTION to "Foo" and VALUE to "yes".

This would hide Bar from the job run page unless Foo was set to yes.

**Comment by MegaDrive68k** [comment]
Hi @binaryfire 

Right now it's possible using a custom UI plugin, take a look at [this](https://groups.google.com/g/rundeck-discuss/c/wvZClHL_0Jw/m/nPOVNPPECgAJ).

Regards!

**Comment by wKollendorf** [comment]
Hi @MegaDrive68k,
do you have an example how to use this plugin?
Thanks

**Comment by binaryfire** [comment]
@MegaDrive68k Thanks for the link Rainer :) My coding skills aren't the greatest but I'll check it out. 

Do you think it makes sense to include basical conditional logic as part of core? I think a lot of people would find it useful. Nothing too complex- just the ability to show/hide a field depending on the value of another.
