### ISSUE TITLE
Unable to download rundeck (rpm or deb)

### ISSUE THREAD

**Issue by gmacgregor1** [rundeck/rundeck#7006]
**Describe the bug**
Unable to reach download (403 forbidden) packages

**My Rundeck detail**
N/A 
Trying a fresh install on Ubuntu 20.04.

**To Reproduce**
* Go to https://docs.rundeck.com/downloads.html
* Trying to download either rpm or deb package from bintray. 
* 403 forbidden

**Expected behavior**
downloads rpm or deb package

**Screenshots**

APT
```
Err:6 https://rundeck.bintray.com/rundeck-deb  InRelease
  403  Forbidden [IP: 52.35.132.179 443]
Reading package lists... Done
E: Failed to fetch https://rundeck.bintray.com/rundeck-deb/InRelease  403  Forbidden [IP: 52.35.132.179 443
```

YUM
```
https://dl.bintray.com/rundeck/rundeck-rpm/repodata/repomd.xml: [Errno 14] HTTPS Error 403 - Forbidden
```

![image](https://user-images.githubusercontent.com/31040999/116141202-5e314000-a6a6-11eb-8b29-8110c339064a.png)

**Desktop (please complete the following information):**
 - Windows 10/Chrome

**Additional context**
Worked fine on April 23rd.

**Comment by fdevans** [comment]
We will have updated package download information in the next day or two!  Thanks for letting the community know about this.
