### ISSUE TITLE
Rundeck RPM repository structure

### ISSUE THREAD

**Issue by wpoely86** [rundeck/rundeck#7025]
**Describe the bug**

We are syncing the RPM repository of rundeck to our local RPM machine with the standard utility reposync. So far this worked great but since the [new RPM repository](https://docs.rundeck.com/docs/learning/howto/migrate-to-rundeck-packages-repo.html) we've hit an issue:
The new repository is under a directory `x86_64` (the metadata is located there) but the actual RPMs are symlinked in to a directory `../noarch/`. This `noarch` directory is outside the main directory structure of `x86_64`. A normal sync will ignore those.
 
You can force it to download it too by using the option `--allow-path-traversal` but this is highly discouraged (and I wish to not use it for that reason):

>               CAUTION: Using this option has potential security implications since, by providing malicious repodata, an attacker could make reposync write to arbitrary locations on the file system that are
>               accessible by the user running it.

And even with this option, it's pretty annoying. Normally you would run something like:
```
reposync -r rundeck
```
and it would give a directory `rundeck` with a copy of the repository. With that option enabled you get both a `rundeck` directory and `noarch` directory. So if you want to contain the rundeck repository to a single directory, you have to give it a sub directory...

We sync a lot of RPM repos and this is the first time we've encountered this issue. Could you please put all RPMs under a single directory? If you move the metadata one directory up, the issue is solved.

**To Reproduce**
1. Add rundeck RPM repo to machine
2. Run `reposync -r rundeck`

**Expected behavior**
One directory with all of the rundeck repository in it.

**Additional context**
https://groups.google.com/g/rundeck-discuss/c/YzoJYEm9gCQ/m/AuUoI4t2BAAJ

**Comment by MegaDrive68k** [comment]
Using the new RPM repo (rundeck.repo at /etc/yum.repos.d path):

```
[rundeck]
name=rundeck
baseurl=https://packages.rundeck.com/pagerduty/rundeck/rpm_any/rpm_any/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packages.rundeck.com/pagerduty/rundeck/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```

With the following example reposync call:

`reposync -n -r rundeck`

Fails with the following output:

```
base                                                                                   | 3.6 kB  00:00:00     
epel/x86_64/metalink                                                                   |  46 kB  00:00:00     
extras                                                                                 | 2.9 kB  00:00:00     
rundeck/x86_64/signature                                                               |  833 B  00:00:00     
rundeck/x86_64/signature                                                               | 1.0 kB  00:00:00 !!! 
updates                                                                                | 2.9 kB  00:00:00     
WARNING: skipping package rundeck-cli-1.3.4-1.noarch: remote path "../noarch/rundeck-cli-1.3.4-1.noarch.rpm" not within repodir, unsafe to mirror locally
WARNING: skipping package rundeck-3.3.10.20210301-1.noarch: remote path "../noarch/rundeck-3.3.10.20210301-1.noarch.rpm" not within repodir, unsafe to mirror locally
WARNING: skipping package rundeck-config-3.0.27.20191204-1.201912050239.noarch: remote path "../noarch/rundeck-config-3.0.27.20191204-1.201912050239.noarch.rpm" not within repodir, unsafe to mirror locally
You can enable unsafe remote paths by using --allow-path-traversal (see reposync(1) for details)
```

It works with:

`reposync --allow-path-traversal -n -r rundeck`

Thanks for your feedback @wpoely86

**Comment by wpoely86** [comment]
It works with `--allow-path-traversal` but you end up with two directories: `noarch` and `rundeck` instead of one.

**Comment by ProTip** [comment]
@wpoely86 Are the two folders causing the `reposync`d repo to function improperly?

**Comment by wpoely86** [comment]
Not the two folder itself. You can use as many folders as you like, as long as they are all under the 'main' directory (the one which has a `metadata` subfolder).

**Comment by wpoely86** [comment]
Depends on what you expect. It's not functioning correctly as all other repos we sync. Normally you get a subdirectory per repository. This fails here. It can be workaround by first creating a subdirectory yourself and use the unsafe option. But that's not a good solution in my opinion.

**Comment by ProTip** [comment]
@wpoely86 This is due to a combination of how our package hosting provider utilizes the relative paths and how `reposync` determines whether the target path is outside the repo path. Neither are likely to change soon.

I was however able to find a way to get the paths to sync up without enabling the unsafe option in both the legacy and `dnf` `reposync`.

```
mkdir -p /rundeck/noarch
reposync --norepopath --repoid rundeck --download-path /rundeck/noarch
```

**Comment by wpoely86** [comment]
Thanks for digging into it. It's pretty annoying that we now have one RPM repo that needs a custom command to properly sync but at least the unsafe option can be left off.

**Comment by antoinetran** [comment]
We reproduced the issue, and the workaround of "--allow-path-traversal" that should have worked did not work. We had 0 rpm with `reposync --allow-path-traversal`. We ended up doing yumdownload of RPM one-by-one, fortunately there are only 3 rpms we want to retrieve...

**Comment by nbarrientos** [comment]
While this gets sorted out you can mirror from here:

```
[pagerduty-rundeck]
name=pagerduty_rundeck
baseurl=https://linuxsoft.cern.ch/mirror/packages.rundeck.com/pagerduty/rundeck/rpm_any/rpm_any/
enabled=1
gpgcheck=1
gpgkey=https://linuxsoft.cern.ch/mirror/packages.rundeck.com/RPM-GPG-KEY-rundeck-pagerduty
```

Without any warranty, of course. Thanks @alexiri for the mirror.

**Comment by nethsix** [comment]
@nbarrientos @antoinetran @wpoely86 @MegaDrive68k @ProTip
Thanks for reporting and finding workaround for this issue.
In the past, some of you may have written in to packagecloud.io support or chat with us over interactive chat on packagecloud.io, and we advised to add parameters `--allow-path-traversal` as a workaround, which may not be ideal.
We hear you, and PagerDuty/Rundeck has also communicated the importance of this issue. Thus on 2022-11-01, we made a change to the rpm any index to remove the use of path traversal to in the index. With this change, reposync should work as expected, i.e.:

`reposync --repoid=</etc/yum.repos.d/ repository_name> -p /path/to/repository`

Please kindly let us know if this works for you, and if there is some other requests that you all may have.

Thank you for your patience, advice, and cooperation working on this issue.

**Comment by wpoely86** [comment]
@nethsix Thanks for doing something about this issue :)

But it doesn't work for me...
The `baseurl` I'm using is https://packagecloud.io/pagerduty/rundeck/el/7/x86_64/
`reposync` is working but not downloading anything. And indeed, when I get `repodata/repomd.xml` and the `primary` from that file, I get an empty list:

```
# curl -sL 'https://packagecloud.io/pagerduty/rundeck/el/7/x86_64/repodata/511d406f5e15f69b7a8afe593c6a870f0cae024a-primary.xml.gz' | gzip -dc

<?xml version="1.0" encoding="UTF-8"?>
<metadata xmlns="http://linux.duke.edu/metadata/common" xmlns:rpm="http://linux.duke.edu/metadata/rpm" packages="0">
  <!--generated by the amazing packagecloud.io RPM indexer-->
</metadata>
```

Something is broken with the RPM repos?

**Comment by nethsix** [comment]
Hello @wpoely86 !
The rundeck packages are indexed under 'rpm_any/rpm_any' instead of 'el/7'.
This means to curl for repomd.xml, etc. You have to replace 'el/7' with 'rpm_any/rpm_any'
Below is an example of how to get the `repomd.xml`

curl -L "https://packagecloud.io/pagerduty/rundeck/rpm_any/rpm_any/x86_64/repodata/repomd.xml"

Thus for reposync, yum/dnf, you need to setup the repo as `rpm_any/rpm_any` as shown

```
[rundeck]
name=rundeck
baseurl=https://packages.rundeck.com/pagerduty/rundeck/rpm_any/rpm_any/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://packages.rundeck.com/pagerduty/rundeck/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300
```

Feel free to interactive chat with us on packagecloud.io website.

**Comment by wpoely86** [comment]
@nethsix Thanks. Now it all works great again :)

Be aware that the instructions on https://packages.rundeck.com/pagerduty/rundeck/install give different results. Then you end up with the repository file as I showed it.
The instructions at https://www.rundeck.com/community-downloads/4.8.0 do work.

**Comment by gschueler** [comment]
Thanks @nethsix for getting this working!
