### ISSUE TITLE
Limit console logging

### ISSUE THREAD

**Issue by btiernay** [rundeck/rundeck#704]
It would be nice to offer a feature similar to Jenkins console log where only a certain size is shown at a time by default (similar to a back buffer). However, the user should still be able to see the entire log via a link.

Some processes generate a lot of logging and this would help to not overwhelm the rundeck server and improve responsiveness

**Comment by fdevans** [comment]
Due to the age of this request and recent feature releases we are going to close this request.  If there are still gaps in the feature set please feel free to open an enhancement request against the current version of Rundeck with your ideas.
Thank you, 
The Rundeck Team
