### ISSUE TITLE
Please provide the fingerprint of RD's GPG key

### ISSUE THREAD

**Issue by xavier8854** [rundeck/rundeck#7041]
**Is your feature request related to a problem? Please describe.**
I'm unable to check the validity of the GP key at https://docs.rundeck.com/keys/, I can't find its fingerprint nowhere

**Describe the solution you'd like**
Provide the fingerprint on another, secure place

Thanks,
Xavier

**Comment by fdevans** [comment]
We will look into this.  I'm not sure that page is current.  It might have been missed in our recent updates.  Check out https://docs.rundeck.com/docs/learning/howto/migrate-to-rundeck-packages-repo.html#manual-setup

Announcement was made recently via email and social channels.  Release Notes signup is here:
https://www.rundeck.com/release-notes-signup

**Comment by ProTip** [comment]
Hi @xavier8854 ,

The key is linked to in two separate places: 
* On https://docs.rundeck.com
* In our packaging repository https://github.com/rundeck/packaging/blob/main/pubring.gpg

The fingerprint is `3132 7DA0 C35E A6B8 8B9D  4648 F192 5292 98C4 C654`
