### ISSUE TITLE
Unable to upgrade to ver 3.3.11 (Centos 7 Yum Upgrade)

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#7043]
Hello Rundeck Team, 
we received the alert on the Rundeck UI that there is a new version release (3.3.11) but we are not able to see the update during yum upgrade process.

![image](https://user-images.githubusercontent.com/20629911/117675015-0c39f100-b161-11eb-9f68-87526179f423.png)

![image](https://user-images.githubusercontent.com/20629911/117675220-3a1f3580-b161-11eb-89da-4dd236a9b641.png)

![image](https://user-images.githubusercontent.com/20629911/117675617-95e9be80-b161-11eb-8d67-a172a61cb8f6.png)

Thank you!
HS

**Comment by fdevans** [comment]
Did you see these instructions?

https://docs.rundeck.com/docs/learning/howto/migrate-to-rundeck-packages-repo.html

The repository source has changed.
