### ISSUE TITLE
JSON option values cannot be numeric 0 (zero)

### ISSUE THREAD

**Issue by PharcydeTribe** [rundeck/rundeck#7054]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 3.3.9 (docker image: rundeck/rundeck:3.3.9)
* install type: Preinstalled in docker image, WAR I believe
* OS Name/version: Ubuntu 18.04.4 LTS
* DB Type/version: mysql

**Expected Behavior**
I have a JSON file on disk to populate the allowed values of a form field:
```json
[
 {
  "name": "Yes",
  "value": 10
 },
 {
  "name": "No",
  "value": 0
 }
]
```
This is loaded via "remote url": `file:/path/to/option_values.json`
I would expect these option values to be loaded as usual, so a selection of "Yes" and "No" on the form, and the option values of 10 or 0 available to the job.

**Actual Behavior**
The option on the form states:
"Failed parsing remote option values: Item: 1 has no 'value' entry"

![image](https://user-images.githubusercontent.com/21374900/118156724-af9c3780-b3e7-11eb-948f-bc6d52ccf16e.png)

Changing the 0 to a positive integer fixes it.

**How to Reproduce**
Save the above JSON to a file, and use it as the "Allowed Values" from remote url ie `file:/path/to/option_values.json` in a job option. The option I am using is Required and "Enforce from allowed values" is set in Restrictions.

**Comment by MegaDrive68k** [comment]
Confirmed,

![Screenshot_1](https://user-images.githubusercontent.com/51376003/118992941-158e3f00-b953-11eb-813b-a563878a8f76.png)


Thanks for your feedback @PharcydeTribe!
