### ISSUE TITLE
UI: Project dropdown - view All Projects link broken in app context [3.4.0RC]

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#7067]
**Describe the bug**

Clicking "View All Projects" in the Projects drop-down results in 404 error, if the app is running in a servlet context subpath like "/rundeck".

**My Rundeck detail**

* Rundeck version: 3.4.0-RC
* 
**To Reproduce**
1. Run Rundeck with an app context like `/rundeck`
2. Click on 'Projects' dropdown menu
3. Click on "View All Projects"
4. See 404 error

**Expected behavior**
Link goes to projects list page.

**Screenshots**

**Comment by ProTip** [comment]
`href="/"`  What could go wrong?

I think updating this to use an `appLink` link is the way to go.

**Comment by dileshni** [comment]
Fixed by https://github.com/rundeck/rundeck/pull/7069
