### ISSUE TITLE
The vew depot for rundeck Oracle Linux RPM (not rundeckpro) don't have the 3.3.11

### ISSUE THREAD

**Issue by philjov** [rundeck/rundeck#7071]
**Describe the bug**
The vew depot for rundeck Oracle Linux RPM (not rundeckpro) don't have the 3.3.11

The new release of my rundeck is not available through yum upgrade.

**My Rundeck detail**

* Rundeck version: 3.3.10
* install type:rpm
* OS Name/version: Oracle Linux 7
* DB Type/version: PG 13.2

**To Reproduce**

According to https://docs.rundeck.com/docs/history/3_3_x/version-3.3.11.html#overview
- I select RPM and launch the following for repo update:

#curl https://raw.githubusercontent.com/rundeck/packaging/main/scripts/rpm-setup.sh 2> /dev/null | sudo bash -s rundeckpro
Detected operating system as ol/7.
Checking for curl...
Detected curl...
Installing pygpgme to verify GPG signatures...
Loaded plugins: remove-with-leaves, ulninfo
pagerduty_rundeck/x86_64/signature                                                                                         |  833 B  00:00:00
pagerduty_rundeck/x86_64/signature                                                                                         |  951 B  00:00:00 !!!
pagerduty_rundeck-source/signature                                                                                         |  833 B  00:00:00
pagerduty_rundeck-source/signature                                                                                         |  951 B  00:00:00 !!!
Package pygpgme-0.3-9.el7.x86_64 already installed and latest version
Nothing to do
Installing yum-utils...
Loaded plugins: remove-with-leaves, ulninfo
Package yum-utils-1.1.31-54.0.1.el7_8.noarch already installed and latest version
Nothing to do
Generating yum cache for rundeckpro...

The repository is setup! You can now install packages.

- Here is the current version

# rpm -qa|grep rundeck
rundeck-repo-4-0.noarch
rundeck-cli-1.3.4-1.noarch
rundeck-3.3.10.20210301-1.noarch

- I'm trying to upgrade:

#yum upgrade rundeck
Loaded plugins: remove-with-leaves, ulninfo
No packages marked for update

**Expected behavior**
This new version should be installed
rundeck-3.3.11.20210507-1.noarch.rpm

**Comment by ProTip** [comment]
Hi @philjov ,

It looks like the command you've posted sets up the Enterprise repo. This should setup the community repo:

```
curl https://raw.githubusercontent.com/rundeck/packaging/main/scripts/rpm-setup.sh 2> /dev/null | sudo bash -s rundeck
```

**Comment by fdevans** [comment]
Hi @philjov any feedback on the suggestion above?

**Comment by philjov** [comment]
Hello, thanks a lot, it works now.
