### ISSUE TITLE
rundeck: preauthenticate with keyloak

### ISSUE THREAD

**Issue by thamchichth** [rundeck/rundeck#7077]
rundeck 3.3.10 rpm install
os :redhat 8
java:openjdk version "1.8.0_292"

I implemented keyloak for rundeck everything works fine but the problem is that the redirection always gives it to me on the rundeck login page as indicated in the attachment.(I must always access with admin admin)
what i want after sso authentication it directly accesses the user part of rundeck.

![partie 1](https://user-images.githubusercontent.com/73650884/118793538-ff23ad00-b898-11eb-93c8-6eb295918235.PNG)
![partie  2](https://user-images.githubusercontent.com/73650884/118793575-05b22480-b899-11eb-96e2-1e6cb715f230.PNG)

**Comment by luxusv** [comment]
This works for me in version 3.3.12 with the following settings:

`
rundeck.security.authorization.preauthenticated.enabled=true
rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
rundeck.security.authorization.preauthenticated.delimiter=,
rundeck.security.authorization.preauthenticated.userNameHeader=X-Auth-Username
rundeck.security.authorization.preauthenticated.userRolesHeader=X-Auth-Roles
rundeck.security.authorization.preauthenticated.redirectLogout=true
rundeck.security.authorization.preauthenticated.redirectUrl=/oauth/logout?redirect=/

#sync user info headers
rundeck.security.authorization.preauthenticated.userSyncEnabled=true
#these are the default headers for passing user details
rundeck.security.authorization.preauthenticated.userFirstNameHeader=X-Auth-Given-Name
rundeck.security.authorization.preauthenticated.userLastNameHeader=X-Auth-Family-Name
rundeck.security.authorization.preauthenticated.userEmailHeader=X-Auth-Email
`

**Comment by loth** [comment]
> This works for me in version 3.3.12 with the following settings:
> 
> ```
> rundeck.security.authorization.preauthenticated.enabled=true
> rundeck.security.authorization.preauthenticated.attributeName=REMOTE_USER_GROUPS
> rundeck.security.authorization.preauthenticated.delimiter=,
> rundeck.security.authorization.preauthenticated.userNameHeader=X-Auth-Username
> rundeck.security.authorization.preauthenticated.userRolesHeader=X-Auth-Roles
> rundeck.security.authorization.preauthenticated.redirectLogout=true
> rundeck.security.authorization.preauthenticated.redirectUrl=/oauth/logout?redirect=/
> 
> #sync user info headers
> rundeck.security.authorization.preauthenticated.userSyncEnabled=true
> #these are the default headers for passing user details
> rundeck.security.authorization.preauthenticated.userFirstNameHeader=X-Auth-Given-Name
> rundeck.security.authorization.preauthenticated.userLastNameHeader=X-Auth-Family-Name
> rundeck.security.authorization.preauthenticated.userEmailHeader=X-Auth-Email
> ```

I know this is an ancient issue, but there is very little on the subject online, can you share your keycloak and proxy settings that you used for this?
