### ISSUE TITLE
Execution Plugins tab disappears on job create validate failure

### ISSUE THREAD

**Issue by dileshni** [rundeck/rundeck#7081]
**Reproduce**

Navigate to create job
Add a command workflow step as true
Ensure job name is blank
Save
Observe the tab is missing

![68350021-b47e7d80-00c4-11ea-8658-b32ce65f7459](https://user-images.githubusercontent.com/613410/118903363-a75f6300-b8e5-11eb-8229-1ad45353cc5e.png)

Moved from: https://github.com/rundeckpro/rundeckpro/issues/763

**Comment by MegaDrive68k** [comment]
Tested on 3.3.11 and 3.4.0-RC2 and it seems fixed.
