### ISSUE TITLE
Update PostgreSQL schema to support replication

### ISSUE THREAD

**Issue by rootwyrm** [rundeck/rundeck#7083]
**Is your feature request related to a problem? Please describe.**
Out of the box, Rundeck when using the PostgreSQL driver will create a database that cannot be replicated either using pglogical or PUB/SUB. There are a number of scenarios ranging from disaster recovery to load distribution where Rundeck users may want to have their PostgreSQL database doing continuous replication. My specific use case is that my PostgreSQL hosts are highly available in order to perform hardware and software maintenance non-disruptively.

**Describe the solution you'd like**
The solution I'd like is actually very simple, as there are only two tables which block replication on PostgreSQL; `rdoption_values` and `workflow_workflow_step`. These tables do not have a `PRIMARY KEY` which blocks replication. This was a very easy fix from a DBA perspective since the need is to simply have *some* primary key which replication can rely upon. Rundeck is free to completely ignore it, aside from when it would violate the constraint, which is solved by using a simple looping bigint sequence. (You would need to have 9223372036854775807 options or concurrent workflow steps to exceed it.)
```
CREATE SEQUENCE IF NOT EXISTS public.rdoption_values_autoid_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    CACHE 1
    CYCLE;
    
CREATE TABLE public.rdoption_values (
    option_id bigint NOT NULL,
    values_string character varying(255),
    autoid bigint DEFAULT nextval('public.rdoption_values_autoid_seq'::regclass) NOT NULL
);

ALTER TABLE ONLY public.rdoption_values
    ADD CONSTRAINT rdoption_values_pkey PRIMARY KEY (autoid);

CREATE SEQUENCE public.workflow_workflow_step_autoid_seq
    START WITH 1
    INCREMENT BY 1
    MINVALUE 1
    CACHE 1
    CYCLE;

CREATE TABLE public.workflow_workflow_step (
    workflow_commands_id bigint NOT NULL,
    workflow_step_id bigint,
    commands_idx integer,
    autoid bigint DEFAULT nextval('public.workflow_workflow_step_autoid_seq'::regclass) NOT NULL
);

ALTER TABLE ONLY public.workflow_workflow_step
    ADD CONSTRAINT workflow_workflow_step_pkey PRIMARY KEY (autoid);
```

I believe this should be a pretty minor change 

**Describe alternatives you've considered**
Unfortunately, there is no alternative. Both PUB/SUB and pglogical replication methods require all tables have some form of primary key. Selective replication of tables using PUB/SUB appears to be unsafe as it would result in options not being consistent across nodes, or workflows potentially executing the same step multiple times. Generally speaking, pglogical DDL replication will be faster than Rundeck's checks of the workflow step.

**Additional context**
I have tested these changes in a test environment with bi-directional pglogical replication, including failing between database nodes, and didn't see any differences at all from single node operation - which was the goal. However, I am very much new to Rundeck and my environment is very small. So it definitely should be reviewed more thoroughly before adopting my suggestion. It's entirely possible I misunderstood how the `workflow_workflow_step` table is used.

**Comment by yanc0** [comment]
Same problem here ! Nice explanation by the way. :upside_down_face:

**Comment by yanc0** [comment]
Here are my two cents.
In our setup, the `rdoption_values` table has no row. I cannot know which column(s) can be part of a primary key constraint.

```
select count(*) from rdoption_values;
 count
-------
     0
(1 row)
```

The `workflow_workflow_step` has +1M rows but when I substract all distinct rows count with all the rows count, there is no difference. Which could means that all rows are unique. Setting a Primary Key constraint on the `workflow_commands_id` and `workflow_step_id` columns should be good but I may be wrong.
 
```
select
(
    select count(distinct(workflow_commands_id,workflow_step_id))
    from workflow_workflow_step
)
-
(
    select count(*)
    from workflow_workflow_step
) as diff;
 diff
------
    0
(1 row)

```
