### ISSUE TITLE
Rundeck 3.11 RPM install executes self-contained WAR? And WAR contains old SQL Server JDBC driver which fails connecting to an Azure Managed Instance

### ISSUE THREAD

**Issue by frachel** [rundeck/rundeck#7084]
Issue type: Question

We've been using 3.9 (and numerous other versions) via an RPM install, and we were always able to put JARs (JDBC drivers for instance) in /var/lib/rundeck/lib. With 3.11 this doesn't seem to work any more.

We noticed this getting an error using an Azure SQL Managed Instance for our DB - we're getting connection failures, and the log shows them coming from the SQL server JDBC JAR version 6.4, even though we put 8.4 (and also tried 9.2) in the /var/lib/rundeck/lib folder.

After some investigation we found out the 'systemctl start rundeckd' command ends up running the "rundeck-....war" directly, so it's using the SQL server jar that's embedded in the WAR file (6.4, which is pretty old).

So the underlying question - how to use newer JDBC drivers in Rundeck 3.11 when it's installed via RPM, but moreso has the way Rundeck is being launched completely changed? I don't recall it using the WAR when we did an RPM install.

**Comment by rafaelrodrigues3092** [comment]
@frachel have you figured it out?
I am seeing the same behavior.

Thanks
