### ISSUE TITLE
gantt-chart by job start time and average duration

### ISSUE THREAD

**Issue by ozaryx** [rundeck/rundeck#7094]
Hello!

Is it possible to add a Gantt chart for the jobs schedule and activity? 

This would make it easier to track the intersection of critical tasks. 

With regards,
Constantine

**Comment by xTriad** [comment]
I second this. A Gantt chart would be very helpful.

**Comment by fdevans** [comment]
<img width="1966" alt="Screen Shot 2021-06-04 at 9 24 44 AM" src="https://user-images.githubusercontent.com/9272445/120833516-bb76a780-c516-11eb-8c7a-cf7250156b13.png">

This is available on the Dashboard in our Enterprise version.
