### ISSUE TITLE
Open file descriptors exhaust system limit on Username/Password authentication

### ISSUE THREAD

**Issue by booshlinux** [rundeck/rundeck#7096]
**Describe the bug**
When logging in using a username and password, (*Not token*) it appears the java application continually keeps a read file descriptor open on the `/etc/rundeck/realm.properties` file, without releasing it. Eventually the systems limit is reached. (Limit from `ulimit -n`)

```
java    13662 rundeck  108r      REG              253,0      1533 138234 /etc/rundeck/realm.properties
java    13662 rundeck  109r      REG              253,0      1533 138234 /etc/rundeck/realm.properties
java    13662 rundeck  110r      REG              253,0      1533 138234 /etc/rundeck/realm.properties
java    13662 rundeck  111r      REG              253,0      1533 138234 /etc/rundeck/realm.properties
java    13662 rundeck  112r      REG              253,0      1533 138234 /etc/rundeck/realm.properties
java    13662 rundeck  113r      REG              253,0      1533 138234 /etc/rundeck/realm.properties
... Continues ...
java    13662 rundeck 1020r      REG              253,0      1533 138234 /etc/rundeck/realm.properties
java    13662 rundeck 1021r      REG              253,0      1533 138234 /etc/rundeck/realm.properties
java    13662 rundeck 1022r      REG              253,0      1533 138234 /etc/rundeck/realm.properties
```

**My Rundeck detail**

* Rundeck version: 3.3.12
* install type: deb
* OS Name/version: Ubuntu 18.04
* DB Type/version: MySQL

Note: Two Rundeck instances are load balanced with HAProxy.

**To Reproduce**
1. Find all open file descriptors that are open for read on the `realm.properties` file:
```
$ lsof -p `ps aux | grep java | grep -v 'grep' | awk '{print $2}'` | grep 'realm\.properties' | wc -l
<number of open descriptors>
```
2. Log in either through the frontend, or API, repeatedly.
3. Check number of descriptors again:
 ```
$ lsof -p `ps aux | grep java | grep -v 'grep' | awk '{print $2}'` | grep 'realm\.properties' | wc -l
<number of open descriptors>
```
4. Number of open FDs increase, without appearing to close.

**Expected behavior**
File descriptors close once finished reading

**Additional context**
I'm unsure if there is a misconfiguration somewhere, but I couldn't say for sure if anything in the configuration would alter the behavior of java keeping these descriptors open for so long.

Edit: I forgot to mention that even logging out does not appear to remove the descriptor through either the frontend or API.

**Comment by booshlinux** [comment]
More information:
I have been successfully recreating this problem on a vanilla installation of the following versions:

- 3.3.12
- 3.3.11

The problem does not appear on 3.3.10.

**Comment by MegaDrive68k** [comment]
Confirmed on 3.3.12.

Tested on 3.3.13-RC1 and 3.4.0-RC3 and doesn't happen.

Thanks for your feedback @booshlinux!
