### ISSUE TITLE
Rundeck end jobs prematurly ( sending SIGPIPE signal to scripts )

### ISSUE THREAD

**Issue by wmi77** [rundeck/rundeck#7097]
**Describe the bug**
Rundeck kill some jobs ( when runing two or three jobs simulationsly ) after 5 to 12 minutes of the start of a task running  a  script by sending SIGPIPE . This issue occur only with rundeck 3.3.x and not with rundeck 2.10.x

**My Rundeck detail**

* Rundeck version: 3.3.11
* install type: deb
* OS Name/version: ubuntu 20.04
* DB Type/version: postgres

**To Reproduce**
1. Run two or threee jobs at the same time ( jobs run at some tasks bash scripts with 'Invocation String' for the script to exec)
2. wait more than 5 minutes of executions
3. if jobs are stills runing ( rundeck send SIGPIPE to one of them )

**Comment by gschueler** [comment]
@wmi77 can you post specific jobs that this occurs with?

**Comment by wmi77** [comment]
Dear Gschueler,

Here below one example . Thanks .

`- description: 
  executionEnabled: true
  group: Patching
  id: xxxxxxxxxxxxxxx
  loglevel: INFO
  multipleExecutions: true
  name: Servers update
  nodeFilterEditable: false
  options:
  - enforced: true
    name: ORGANIZATION
    required: true
    value: 
    valuesUrl: https://xxxxxxxxxxxxxx/foreman/simple/organizations
  - name: rebootgroup
    required: true
    value: '99'
  - delimiter: ','
    enforced: true
    multivalueAllSelected: true
    multivalued: true
    name: hosts
    valuesUrl: https://xxxxxxxxxxxxxx/get-foreman-rebootgroup.sh?search=params.rebootgroup=${option.rebootgroup.value}+and+organization=%22${option.ORGANIZATION.value}%22
  - description:
    enforced: true
    name: type
    required: true
    value: external
    values:
    - external
    - internal
  - description: 
    enforced: true
    name: API
    required: true
    value: https://xxxxxxxxxxxxxx
    valuesUrl:https://xxxxxxxxxxxxxx/get?key=${option.name}
  - enforced: true
    name: APIHOST_FOREMAN
    required: true
    value: foreman.xxx
    valuesUrl:https://xxxxxxxxxxxxxx/get?key=${option.name}
  - description: 
    name: VCENTERHOST
    required: true
    value: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  - description: If true, display in log all packages upgraded (only for linux)
    enforced: true
    name: log_upgradedpkg
    required: true
    value: 'False'
    values:
    - 'False'
    - 'True'
  - description: If true, reboot at the end of the upgrade even if it is not necessary
    enforced: true
    name: forcereboot
    required: true
    value: 'False'
    values:
    - 'False'
    - 'True'
  - description: If true, send rocketchat notification (see rocket_chan option) before upgrade
    enforced: true
    name: ROCKETCHAT
    required: true
    value: 'True'
    values:
    - 'False'
    - 'True'
  - description: RocketChat Channel for sending notification before upgrade
    name: CHANNEL
    regex: '[#@].*'
    required: true
    value: '#xxxxxx'
  scheduleEnabled: false
  sequence:
    commands:
    - description: Read vcenter credential
      jobref:
        args: -SECRET_NAME xxxxxx -VAR_NAME xxxxxxx -VAULT_BACKEND xxxxxxxxx
        group: Vault
        name: Export secret
        nodeStep: 'true'
        project: Security
    - description: Extract Vcenter credentials from JSON
      interpreterArgsQuoted: false
      plugins:
        LogFilter:
        - config:
            filter: '{ "vcenter_service": .data.data }'
            logData: 'false'
            prefix: result
          type: json-mapper
        - config:
            loglevel: debug
            matchLoglevel: normal
            quietMatch: 'true'
          type: quiet-output
      script: |-
        cat <<'EOF'
        @export.svc_fastr_cloudnexto@
        EOF
      scriptInterpreter: exec
    - description: Read rocketchat credential
      jobref:
        args: -SECRET_NAME rxxxxx -VAR_NAME xxxxxxxxx -VAULT_BACKEND xxxxxxxxxx
        group: Vault
        name: Export secret
        nodeStep: 'true'
        project: Security
    - description: Extract rocketchat credentials from JSON
      interpreterArgsQuoted: false
      plugins:
        LogFilter:
        - config:
            filter: '{ "rocketchat_service": .data.data }'
            logData: 'false'
            prefix: result
          type: json-mapper
        - config:
            loglevel: debug
            matchLoglevel: normal
            quietMatch: 'true'
          type: quiet-output
      script: |-
        cat <<'EOF'
        @export.rocketchat_bot@
        EOF
      scriptInterpreter: exec
    - description: Read Foreman Credentials
      jobref:
        args: -SECRET_NAME xxxxxxxxxxx -VAR_NAME foreman_account -VAULT_BACKEND xxxxxxxxxxx
        group: Vault
        name: Export secret
        nodeStep: 'true'
        project: Security
    - description: Extract Foreman credentials from JSON
      interpreterArgsQuoted: false
      plugins:
        LogFilter:
        - config:
            filter: '{ "foreman_service": .data.data }'
            logData: 'false'
            prefix: result
          type: json-mapper
        - config:
            loglevel: debug
            matchLoglevel: normal
            quietMatch: 'true'
          type: quiet-output
      script: |-
        cat <<'EOF'
        @export.foreman_account@
        EOF
      scriptInterpreter: exec
    
    - description: Server Update
      script: |-
        #!/usr/bin/env bash
        set -euo pipefail;

        # ---------------------------------------------------------------------------- #
        #                           Init script requirements                           #
        # ---------------------------------------------------------------------------- #

        # Treatment specific to Rundeck
        if [[ -n "${RD_JOB_ID:-}" ]]; then
        # Initialize variables from template matching
        # As safe as possible: use heredoc to avoid errors
        FOREMAN_LOGIN="$(
            cat <<-'EOF'
        @data.foreman_service.login@
        EOF
        )";
        FOREMAN_PASSWORD="$(
            cat <<-'EOF'
        @data.foreman_service.password@
        EOF
        )";
        CLOUD_LOGIN="$(
            cat <<-'EOF'
        @data.vcenter_service.login@
        EOF
        )";
        CLOUD_PASSWORD="$(
            cat <<-'EOF'
        @data.vcenter_service.password@
        EOF
        )";
        	
        JOBUSERNAME="${RD_JOB_USERNAME:-}"
        VCENTERHOST="${RD_OPTION_VCENTERHOST:-}"
        TYPE="${RD_OPTION_TYPE:-}"
        LOG_LIST_UPDATE="${RD_OPTION_LOG_UPGRADEDPKG:-}"
        FORCEREBOOT="${RD_OPTION_FORCEREBOOT:-}"
        REBOOTGROUP="${RD_OPTION_REBOOTGROUP:-}";
        ORGANIZATION="${RD_OPTION_ORGANIZATION:-}";
        HOSTS="${RD_OPTION_HOSTS:-}"

        fi;



        # Gather required variables
        declare -g FOREMAN_LOGIN="${FOREMAN_LOGIN:-}";
        declare -g FOREMAN_PASSWORD="${FOREMAN_PASSWORD:-}";
        declare -g CLOUD_LOGIN="${CLOUD_LOGIN:-}";
        declare -g CLOUD_PASSWORD="${CLOUD_PASSWORD:-}";
        declare -g JOBUSERNAME="${JOBUSERNAME:-}"
        declare -g VCENTERHOST="${VCENTERHOST:-}";
        declare -g TYPE="${TYPE:-}";
        declare -g LOG_LIST_UPDATE="${LOG_LIST_UPDATE:-}";
        declare -g FORCEREBOOT="${FORCEREBOOT:-}";
        declare -g REBOOTGROUP="${REBOOTGROUP:-}";
        declare -g ORGANIZATION="${ORGANIZATION:-}";
        declare -g HOSTS="${HOSTS:-}";

        # Ensure all mandatory variables are set
        FOREMAN_API_URL="${FOREMAN_API_URL:?Failed to get FOREMAN_API_URL environment variables}";
        FOREMAN_LOGIN="${FOREMAN_LOGIN:?Failed to get FOREMAN_LOGIN environment variable}";
        FOREMAN_PASSWORD="${FOREMAN_PASSWORD:?Failed to get FOREMAN_PASSWORD environment variable}";
        CLOUD_LOGIN="${CLOUD_LOGIN:?Failed to get CLOUD_LOGIN environment variable}";
        CLOUD_PASSWORD="${CLOUD_PASSWORD:?Failed to get CLOUD_PASSWORD environment variable}";
        JOBUSERNAME="${JOBUSERNAME:?Failed to get JOBUSERNAME environment variable}";
        VCENTERHOST="${VCENTERHOST:?Failed to get VCENTERHOST environment variable}";
        TYPE="${TYPE:?Failed to get TYPE environment variable}";
        LOG_LIST_UPDATE="${LOG_LIST_UPDATE:?Failed to get LOG_LIST_UPDATE environment variable}";
        FORCEREBOOT="${FORCEREBOOT:?Failed to get FORCEREBOOT environment variable}";
        REBOOTGROUP="${REBOOTGROUP:?Failed to get REBOOTGROUP environment variable}";
        ORGANIZATION="${ORGANIZATION:?Failed to get ORGANIZATION environment variable}";

        export FOREMAN_URL="${FOREMAN_API_URL}";
        export FOREMAN_USER="${FOREMAN_LOGIN}";
        export FOREMAN_PASSWORD="${FOREMAN_PASSWORD}";

        jobarguments=(
            --jobArgument "rebootgroup=${REBOOTGROUP}"
            --jobArgument "organization=${ORGANIZATION}"
            --jobArgument "cloudlogin=${CLOUD_LOGIN}"
            --jobArgument "cloudpass=${CLOUD_PASSWORD}"
            --jobArgument "vcenterhost=${VCENTERHOST}"
            --jobArgument "jobusername=${JOBUSERNAME}"
            --jobArgument "type=${TYPE}"
            --jobArgument "log_list_update=${LOG_LIST_UPDATE}"
            --jobArgument "forcereboot=${FORCEREBOOT}"
        )
            exec /usr/local/bin/foreman-run-job \
                --jobTemplateName "Ansible - Servers Update" \
                --targetFilter "name ^ (\"${HOSTS}\")" \
                "${jobarguments[@]}";
      scriptInterpreter: exec
    keepgoing: false
    pluginConfig:
      LogFilter:
      - config:
          logData: 'true'
          regex: ^RUNDECK:DATA:(.+?)\s*=\s*(.+)$
        type: key-value-data
      - config:
          fgcolor: green
          regex: '(ok: .*)|(ok=.* )'
        type: highlight-output
      - config:
          fgcolor: yellow
          regex: '(changed: .*$)|(changed=.* )'
        type: highlight-output
    strategy: node-first
  timeout: '0'
  uuid: e75e1264-fb68-46f8-ae58-xxxxxxxxxxxxxxx
`

**Comment by wmi77** [comment]
not a rundeck issue .
