### ISSUE TITLE
Backup API exported file was wrong

### ISSUE THREAD

**Issue by wadelu** [rundeck/rundeck#7103]
Issue type: Bug report

The Project Exported file created by the backup API  is not correct.

* Rundeck version:  3.3.10
* install type: Docker
* OS Name/version: CentOS 7
* DB Type/version: Oracle

**Expected Behavior**
Call Backup API with admin token and trigger backup, once done, call download file API, the exported project archive should be download correctly.

**How to Reproduce**

**Comment by MegaDrive68k** [comment]
Hi @wadelu 

Which steps are you followed?

Thanks!

**Comment by wadelu** [comment]
Hi @MegaDrive68k 

I trigger export job first by this API: https://docs.rundeck.com/docs/api/rundeck-api.html#project-archive-export-async

Then check the status by this API: https://docs.rundeck.com/docs/api/rundeck-api.html#project-archive-export-async-status

And once ready, I trigger this API to download: https://docs.rundeck.com/docs/api/rundeck-api.html#project-archive-export-async-download

But finally found the file downloaded cannot be recognized by Rundeck itself.
