### ISSUE TITLE
repositories problem under rhel 8/7

### ISSUE THREAD

**Issue by thesal84** [rundeck/rundeck#7114]
**Describe the bug**
We wanted to install the newest Rundeck version on a RHEL 8.4 system. We also  have tested with a RHEL 7.9.
We have installed the repository with:
curl -s https://packagecloud.io/install/repositories/pagerduty/rundeck/script.rpm.sh | sudo bash

But after that when we do a `dnf install rundeck` we get:
`No match for argument: rundeck
Error: Unable to find a match: rundeck`

We had a look int the primary.xml.gz and it seems that some information are missing
`wget https://packagecloud.io/pagerduty/rundeck/el/8/x86_64/repodata/primary.xml.gz `

Summary from the content from primary.xml.gz:
`metadata xmlns="http://linux.duke.edu/metadata/common" xmlns:rpm="http://linux.duke.edu/metadata/rpm" packages="0"
generated by the amazing packagecloud.io RPM indexer`

**Expected behaviour**
Install and update Rundeck with the correct repository.

**Comment by MegaDrive68k** [comment]
Hi @thesal84 

Check the instructions [here](https://docs.rundeck.com/docs/administration/install/linux-rpm.html#installing-on-centos-or-red-hat-linux-distributions). Check carefully the URL of the curl step and the install step.

Hope it helps!

**Comment by thesal84** [comment]
Hello,

Sorry for the late reply. Problem is solved.
Thank you.
