### ISSUE TITLE
RUN-137: 3.4.0 UI Bugs

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#7125]
Hello,
  Thank you for the new UI release. FYI...

Using Chrome browser:

![image](https://user-images.githubusercontent.com/20629911/122414807-448cd600-cf3c-11eb-9024-1d856872151b.png)

![image](https://user-images.githubusercontent.com/20629911/122414833-48b8f380-cf3c-11eb-82cd-95f6621f57c0.png)

![image](https://user-images.githubusercontent.com/20629911/122414847-4c4c7a80-cf3c-11eb-9c68-8232130fddf6.png)

Version:
![image](https://user-images.githubusercontent.com/20629911/122415112-7bfb8280-cf3c-11eb-9915-1ec62a527585.png)

Thanks,
HS

**Comment by gschueler** [comment]
fixed by https://github.com/rundeck/rundeck/pull/7140
