### ISSUE TITLE
Please explain why #7110 is closed.

### ISSUE THREAD

**Issue by enexusde** [rundeck/rundeck#7128]
Id like to know why #7110 is closed. Is it a feature that never will be implemented?

**Comment by enexusde** [comment]
The text from #7110 points out what is the current state-of-the-art. The current state-of-the-art is that jdk 14 is not supported. Since it is a feature request that have been rejected I assume that JDK 14 will never be implemented. Since JDK will never be implemented id like to know why it will never be implemented. Unfortunately this is not part of the description.

**Comment by fdevans** [comment]
Per the template this forum is for code issues and bugs. Feature requests are noted and will be implemented as we progress with the product but there isn't a need to keep them open so the team can focus on code related issues.

Recently we announced new forums for general Rundeck discussion. Feel free to continue open discussions there.

https://community.pagerduty.com/forum/c/rundeck

As always, pull requests with needed updates are welcome.

**Comment by enexusde** [comment]
Please do not abuse github's ticket system. Since I have looked for an existsing feature-request if a modern JDK will be supported I am not sure whenever there already was a feature-request that requests the support of a modern JDK and was closed by you guys. You will have much effort in close (and explain-why, respectfully) possible duplicates instead make a statement.

After all this feature-request is focusing "on code to related issues", and it is a valid feature-request that has been closed. I am not into your workcycles, it would be helpfull if you guys either explain more why a feature-request is closed due to your internal processes or disable the possibility to post feature-request in general because they are closed anyway (and refer to the external forum early).

**Comment by fdevans** [comment]
Thank you for the feedback.
