### ISSUE TITLE
Rundeck Session Timeout Setting Ignored

### ISSUE THREAD

**Issue by hseffler** [rundeck/rundeck#7145]
**Describe the bug**

Rundeck Session Timeout Setting Ignored

**My Rundeck detail**

* Rundeck version: 3.3.7
* install type: deb from puppet
* OS Name/version: Debian Buster
* DB Type/version: mysql

**To Reproduce**
Add
`server.servlet.session.timeout = "36000"`
to
`/etc/rundeck/rundeck-config.groovy`

as described in the documentation

**Expected behavior**
Rundeck session timeout in the browser is 10h == 36000s

**Actual behaviour**
Timeout is much shorter, if I login and come back to the session later, I need to relogin

**Desktop (please complete the following information):**
 - OS: Linux, Mac
 - Browser Chrome, Firefox

**Comment by MegaDrive68k** [comment]
Hi @hseffler 

I tried successfully with a smaller value in the following way on the rundeck-config.groovy file:

`server."servlet.session.timeout"="60"`

Alternatively, you can launch the rundeck instance using the `-Dserver.servlet.session.timeout=36000` parameter, take a look at [this](https://docs.rundeck.com/docs/administration/configuration/system-properties.html#rpm-and-deb) to add it rundeckd file.

I hope it helps!
