### ISSUE TITLE
Expand yaml editor box

### ISSUE THREAD

**Issue by antonvdl** [rundeck/rundeck#7149]
**Describe the issue**
When using the YAML editor in Rundeck UI (for example with Ansible inline playbooks), there are only 7 lines of code visible.
It would be great if this can be extended (with a slider at the corner of the window, or by setting a configuration option).

In the past the field was way larger.
Since I see this in both Ansible and Kubernetes integrations I think it has to do with the UI framework.

**Version**
I believe this started somewhere in Rundeck 3.3; the following two versions have this limitation: for sure
* Rundeck 3.3.10
* Rundeck 3.4.0

**Comment by MegaDrive68k** [comment]
On 3.2.X the textbox expands dinamically:

![Screenshot_5](https://user-images.githubusercontent.com/51376003/125496718-65a1435a-ff75-4ce5-bb81-67e4c4ba5e69.png)

This doesn't happens on 3.3.X and 3.4.0.

Thanks for your feedback @antonvdl!
