### ISSUE TITLE
Need a way to limit max job execution per node.

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#716]
Hello,
I need to limit the maximum number of execution for a particular job, per node.

We use rundeck to deploy a J2EE application on my Websphere servers.
We have determined that the maximum number of simultaneous deployments on each WAS server sould be limited to 3.
So I have designed a rundeck job, which deploys my applications.
This job is standard and is used to deploy all kind of applications on any selected WAS server.
So I cannot limit the job execution because my job can run simultaneously on a random number of WAS servers.

I think I need some kind of job execution limitation by node.
In my case, I would need to limit the job execution to 3 per node.

Is there currently a way to achieve that ?

Thanks by advance
Best regards
Jerome

**Comment by fuinyroot** [comment]
I am looking for the same function, well unfortunately, there is no such parameter to my knowledge.

The workaround is to create 2 jobs as a group, example:
- job1. the 'job' 
- job2. the 'job-control': if 'job' is running, do nothing, else submit 'job' again.

For a node, say 'node-a', create 5 groups, then it means there are only 5 jobs allowed.

**Comment by rdoering** [comment]
Why is here no progress?

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
