### ISSUE TITLE
Export Projects Error Messages

### ISSUE THREAD

**Issue by MegaDrive68k** [rundeck/rundeck#7161]
[RUN-253]
**Describe the bug**

Rundeck 3.4.1 Community can't export projects, this doesn't happens on 3.4.1 Enterprise. 

Rundeck stucks with `The token <uuid_string> was not found. It may have expired.` message at the moment of export any project.

**My Rundeck detail**

* Rundeck version: 3.4.1
* install type: WAR / Docker
* OS Name/version: Manjaro 20.1.7
* DB Type/version: H2

**To Reproduce**

1. Create a Project.
2. Go to Project Settings > Export Archive.
3. Click on the "Export Archive" green button.
4. See the error.

**Expected behavior**

The project must be exported in a .jar file.

**Screenshots**

<img width="1097" alt="Screen Shot 2021-07-15 at 2 07 32 PM" src="https://user-images.githubusercontent.com/51376003/125863039-8d36722e-1f7b-4e38-b191-05a62a416971.png">

**Additional context**

1. This doesn't happen on Rundeck Enterprise.
2. The current workaround is to refresh the page and click on the top "Download project" green button.

[RUN-253]: https://pagerduty.atlassian.net/browse/RUN-253

**Comment by ProTip** [comment]
Likely introduced during the Javascript vendoring refactor. The Knockout import on `wait.gsp` was not updated for the new location. On Enterprise `uiplugins.js`, which inlines KO, gets loaded so the issues is not present there.
