### ISSUE TITLE
Changing the scheduled start time resulted in a double run

### ISSUE THREAD

**Issue by mauriciogc-sudo** [rundeck/rundeck#7164]
**Describe the bug**
When you schedule a job and tried to changed it seconds before executing the job, rundeck run two jobs, the first schedule and the new schedule.
If you do the same but changed the schedule just when the job finish, the new schedule job runs normally.

The issue 
**My Rundeck detail**

* Rundeck version: [ 3.3.11]
* install type: [rpm,war]
* OS Name/version: [Centos,macOS]
* DB Type/version: [postgres,oracle]

**To Reproduce**
1. Choose a job or create a new one
2. Go to schedule job
3. On "Schedule to run repeatedly", choose yes, you can use this crontab: 
0 0/2 * 1/1 * ? *
4- Add a step on workflow and choose to run a simple command, like an "echo $HOSTNAME"
5. Save changes
6. Go to activity and wait to the job ran
7.  Go to the job again and change the schedule, for example using this::
0 0/4 * 1/1 * ? *
Do this change seconds before that the job run
8. With this last change, you will see that rundeck run two jobs, first each 2 min, and then each 4 min

**Expected behavior**
If you change a schedule on rundeck we expected that rundeck run only one job and no two jobs

**Screenshots**

![Screen Shot 2021-07-16 at 8 54 52 PM](https://user-images.githubusercontent.com/84579473/126018674-51d0bc55-a1c3-4b20-afb4-d1475354c1b0.png)

On that screenshot, you will see two schedules, first job each 4 min at 3:04, second job each 6 min but you will see that the job run 3:12, and the third job at 6.  

**Desktop (please complete the following information):**
 - OS: [iOS,Linux]
 - Browser [Firefox]
 - Version [90.0 64Bits]

**Additional context**
This test was performed on Centos and MacOs

**Comment by jtobard** [comment]
Can you confirm this happens on latest release  too? (3.4.1)

**Comment by mauriciogc-sudo** [comment]
> Can you confirm this happens on latest release too? (3.4.1)

Hello @jtobard , I confirm the same issue on version 3.4.1 rundeck enterprise.
