### ISSUE TITLE
edit loglevel of service.log

### ISSUE THREAD

**Issue by sergue2** [rundeck/rundeck#7167]
Hello,

i've got the problem, that /var/log/rundeck/service.log is getting way to big.
After a few weeks, it was about 5gb.
Is there a way to edit the loglevel of service.log?

**Comment by MegaDrive68k** [comment]
Hi @sergue2 

You can rotate the service.log file using [logrotate](https://linux.die.net/man/8/logrotate), take a look at [this](https://docs.rundeck.com/docs/administration/maintenance/logs.html#rotation-of-service-log-linux).

Regards.
