### ISSUE TITLE
Multiple job executions aren't prevented

### ISSUE THREAD

**Issue by juliusstep** [rundeck/rundeck#7169]
**Describe the bug**
Rundeck doesn't prevent parallel runs when job is executed from another job. 

**My Rundeck detail**

* Rundeck version: 3.4.0 Community edition
* Install type: deb
* OS Name/version: debian 10
* DB Type/version: mysql

**To Reproduce**
1. Create a job (Job A) to excute Script (Execute inline script)
2. Set Multiple executions? to "No"
3. Create a job (Job B) to execute Job Reference (Execute another job...)
4. Run Job B multiple execution - Job A script will be ran in parallel despite its "No multiple executions" setting

**Expected behavior**
Multiple executions of Job A is prevented.

**Additional context**
Same behaviour is noticed in 3.2.1 version

**Comment by MegaDrive68k** [comment]
Hi @juliusstep 

Check [this](https://github.com/rundeck/rundeck/issues/5428#issuecomment-631451014) thread.

Regards.

**Comment by juliusstep** [comment]
Didn't find previous issue. Understood.
