### ISSUE TITLE
Can i set "day of month" in Community version?

### ISSUE THREAD

**Issue by arpsyapathy** [rundeck/rundeck#7171]
Hi!

I use Rundeck Community 3.4.1.
I need create job for execute every 3 day of few month.
can i do it?

I see only "time", "month", "day of week" in scheduler.  But don't see "day of month"

Thank you advanced

**Comment by MegaDrive68k** [comment]
Hi @arpsyapathy 

"day of month" is available on the community version, take a look:

![Screenshot_1](https://user-images.githubusercontent.com/51376003/126336615-b5236f6b-9b4e-4e20-bb09-fa8bbc72249b.png)

So, a good tool to generate your cron definitions is [this](https://www.freeformatter.com/cron-expression-generator-quartz.html) website. An example to execute every 3 days starting the Monday's could be:

`0 0 0 ? * 2/3 *`

Hope it helps!

**Comment by arpsyapathy** [comment]
> Hi @arpsyapathy
> 
> "day of month" is available on the community version, take a look:
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/51376003/126336615-b5236f6b-9b4e-4e20-bb09-fa8bbc72249b.png)
> 
> So, a good tool to generate your cron definitions is [this](https://www.freeformatter.com/cron-expression-generator-quartz.html) website. An example to execute every 3 days starting the Monday's could be:
> 
> `0 0 0 ? * 2/3 *`
> 
> Hope it helps!

@MegaDrive68k 
Hi!

In the Simple form day cannot be specified yes? only cron?

**Comment by MegaDrive68k** [comment]
Hi @arpsyapathy 

Yes, that use-case needs cron type schedule.

Greetings.

**Comment by arpsyapathy** [comment]
> Hi @arpsyapathy
> 
> Yes, that use-case needs cron type schedule.
> 
> Greetings.

@MegaDrive68k Thank you very match!
