### ISSUE TITLE
No scrolling available for long description of jobs

### ISSUE THREAD

**Issue by xavier8854** [rundeck/rundeck#7172]
**Describe the bug**
When there is a long (exceeding screen size) description for a job, one cannot scroll to see the remaining;

**My Rundeck detail**

* Rundeck version: 3.4.0
* install type: rpm
* OS Name/version: RHEL 7
* DB Type/version: mariaDB

**To Reproduce**
1. Go to 'Job definitin
2. Enter a description of say 100 lines
3. Save the job
4. See error :  no scrolling available

**Expected behavior**
A scrollbar in this particular window

**Screenshots**
See attached

**Desktop (please complete the following information):**
 - OS: Ubuntu 21.04
 - Browser  Firefox - problem identical with Chromium
 - Version 90

**Additional context**
![Screenshot from 2021-07-20 12-06-17](https://user-images.githubusercontent.com/3287969/126305871-897f4d8c-3948-4eb8-bb62-d6f74558ac1b.png)

**Comment by MegaDrive68k** [comment]
Confirmed and happening on 3.4.1 too.

**Comment by xavier8854** [comment]
Not fixed in 3.4.3

**Comment by qualman** [comment]
Hi all, I've just tested and approved a fix for this issue, #7378. You should see this fix merged soon. Thank you!

**Comment by L2JE** [comment]
Fixed in https://github.com/rundeck/rundeck/pull/7378
