### ISSUE TITLE
Some remote commands with spaces need to be escaped on 3.4.1

### ISSUE THREAD

**Issue by mazzella-c** [rundeck/rundeck#7187]
**Describe the bug**

This specific remote command is working on 3.3.9 :
``sudo /bin/su - user -c "cd ${node.path};tar czf ${node.save}/${node.hostname}_`date -d now +%Y%m%d%H%M%S`.tar.gz test_dir"``

If we launch the same command on 3.4.1 inside any job we have the following output :
`tar: test_dir: Cannot stat: No such file or directory
tar (child): /xxx/host1_20210726204641.tar.gz: Cannot open: Permission denied
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Failed: NonZeroResultCode: [ssh-exec] Result code: 2`

We need to escape every space to get a working solution :

``sudo /bin/su - user -c "cd\ ${node.path}\;tar\ czf\ ${node.save}/${node.hostname}_`date -d now +%Y%m%d%H%M%S`.tar.gz\ test_dir"``

**My Rundeck detail**

* Rundeck version: 3.4.1
* install type: war
* OS Name/version: RHEL 7.9
* DB Type/version: Postgre 12

**To Reproduce**
1. Create a job with the above command to be launched against a Linux host on 3.4.1
2. See error

**Expected behavior**
The behaviour should be the same on 3.3.9 and 3.4.1

**Additional context**
If we use Inline Script there is no need to escape the command even on 3.4.1

**Comment by Mrmel94** [comment]
Same here, with "&" character, need to escape the character but not in inline script

**Comment by NapoSky** [comment]
same in 3.4.2. I need to escape every semicolon and "&" in a commandline workflow. No needs to do it in script workflow.
It's kinda horrible actually because I must take a pass to every of my jobs already generated...

**Comment by Daryes** [comment]
@gschueler, @carlosrfranco, @ProTip
Sorry for the ping, but there's currently a problematic regression which warrant a rollback to v3.3.x when trying the new v3.4.x

To put it simply, the way the "remote command" module handle quotes has changed in an unexpected way that requires altering a lot of jobs, if not all,  when upgrading to 3.4

Load this job definition :
Note : keep the () in the job name, that's on purpose and part of the test

```
<joblist>
  <job>
    <defaultTab>nodes</defaultTab>
    <description></description>
    <executionEnabled>true</executionEnabled>
    <group>bug</group>
    <id>adeed2d5-cf64-4792-b62f-37cee510b546</id>
    <loglevel>INFO</loglevel>
    <name>quoting option regression (test)</name>
    <nodeFilterEditable>false</nodeFilterEditable>
    <plugins />
    <scheduleEnabled>true</scheduleEnabled>
    <sequence keepgoing='false' strategy='node-first'>
      <command>
        <description>local command - no quotes</description>
        <node-step-plugin type='localexec'>
          <configuration>
            <entry key='command' value='echo checking the quotes behavior with special chars in the job name : ${job.name}' />
          </configuration>
        </node-step-plugin>
      </command>
      <command>
        <description>remote command - no quotes</description>
        <exec>echo checking the quotes behavior with special chars in the job name : ${job.name}</exec>
      </command>
      <command>
        <description>local command - with quotes</description>
        <node-step-plugin type='localexec'>
          <configuration>
            <entry key='command' value='echo "checking the quotes behavior with special chars in the job name : ${job.name}"' />
          </configuration>
        </node-step-plugin>
      </command>
      <command>
        <description>remote command - with quotes</description>
        <exec>echo "checking the quotes behavior with special chars in the job name : ${job.name}"</exec>
      </command>
    </sequence>
    <uuid>adeed2d5-cf64-4792-b62f-37cee510b546</uuid>
  </job>
</joblist>
```


On 3.3,x : it'll execute without error.
On 3.4.x : the 4th step using a remote command with quotes will raise this error : `/bin/sh: 1: Syntax error: "(" unexpected`  
The ( come from the job name.

To have it working correctly, you need to triple the quotes (single or double).   
This will work : ` echo """checking the quotes ... ${job.name}""" `

Which is also not in line anymore with the local command module, working correctly without the need to triple the quotes.

On a second though, is there any way to have the remote command module work also locally ? 
This would remove the need to have 2 different modules which have a lot in common.

**Comment by ralfsaier** [comment]
This bug breaks nearly all of our jobs!!
Because of the log4j2 securty break, we HAD to upgrade to 3.4.7.
So rollback to 3.3. is not possible, editing hundred of jobs either.

**Comment by gschueler** [comment]
You can use the mitigation until an updated 3.3 is released (coming as soon as possible)

-- 
Greg

**Comment by dusty73** [comment]
3.3.16 now should have the log4j fix backported, BUT this bug must be fixed, otherwise the adoption of the new version could be very difficult...
We have tons of scripts afflicted by the same problem.

**Comment by lcanavosio** [comment]
From client (The Net-A-Porter Group Limited):
As you can see from the github issue comments, this bug is a main blocker in the adoption of the 3.4.* version, as it breaks many existing jobs for many users, we think that this bug should be solved as soon as possible. We had to rollback to version 3.3.* in order to get all jobs working back, fixing all the jobs with the workaround suggested is not a viable solution for us, it would take a lot of time to review all existing jobs (we have hundreds of jobs defined)

**Comment by fdevans** [comment]
We will look into this deeper and see what's changed and how we can fix it.

**Comment by remifrazierucsf** [comment]
Thank you @fdevans - we added this to our technical review request for our enterprise license renewal and are very grateful you're looking at it.

**Comment by fdevans** [comment]
Anyone willing to try on a 3.4.0 version and report back if you have the same issue?  We can try to mock up the same scenario, but it will take us some time.  There are some other issues we're seeing and a PR from 3.4.1 specifically that might be culprit.  Any feedback will be helpful in getting us closer to a fix.

**Comment by remifrazierucsf** [comment]
@fdevans we think our issues hit on the 3.4.0 release, not 3.4.1, but we're not sure and cannot roll back. :(

As a note, we're also having issues with WinRM calls on this, not just Linux.

**Comment by Daryes** [comment]
@fdevans 
> Anyone willing to try on a 3.4.0 version and report back if you have the same issue? We can try to mock up the same scenario, but it will take us some time. There are some other issues we're seeing and a PR from 3.4.1 specifically that might be culprit. Any feedback will be helpful in getting us closer to a fix.

Just tried it, and ran the job [as described a little upper](https://github.com/rundeck/rundeck/issues/7187#issuecomment-917438857)

**Result for 3.4.0**
```
local command - no quotes | checking the quotes behavior with special chars in the job name : quoting option regression (test)
remote command - no quotes | checking the quotes behavior with special chars in the job name : quoting option regression (test)
local command - with quotes | checking the quotes behavior with special chars in the job name : quoting option regression (test)
remote command - with quotes | checking the quotes behavior with special chars in the job name : quoting option regression (test)
```

**switch back to 3.4.3**
```
local command - no quotes | checking the quotes behavior with special chars in the job name : quoting option regression (test)
remote command - no quotes | checking the quotes behavior with special chars in the job name : quoting option regression (test)
local command - with quotes | checking the quotes behavior with special chars in the job name : quoting option regression (test)
remote command - with quotes | /bin/sh: 1: Syntax error: "(" unexpected
```
So no error for 3.4.0, it seems it started from 3.4.1

**Comment by fdevans** [comment]
Thank you @Daryes. This helps us.
