### ISSUE TITLE
Job fails with "No matched nodes" unless target nodes explicitly selected

### ISSUE THREAD

**Issue by duriona** [rundeck/rundeck#719]
When I try and run a simple job with a single script line I see "Target Nodes 18" but when the job runs I get:

```
com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{}
13:57:26                at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.validateNodeSet(NodeFirstWorkflowStrategy.java:332)
13:57:26                at com.dtolabs.rundeck.core.execution.workflow.NodeFirstWorkflowStrategy.executeWorkflowImpl(NodeFirstWorkflowStrategy.java:84)
13:57:26                at com.dtolabs.rundeck.core.execution.workflow.BaseWorkflowStrategy.executeWorkflow(BaseWorkflowStrategy.java:120)
13:57:26                at com.dtolabs.rundeck.core.execution.WorkflowExecutionServiceThread.run(WorkflowExecutionServiceThread.java:55)
13:57:26            Exception: class com.dtolabs.rundeck.core.NodesetEmptyException: No matched nodes: NodeSet{}
```

Now the odd thing is if I select "Change Target Nodes", Select None, then Select All it runs the job correctly.  

I have verified that my user can see nodes on the project, there are no REJECTS in rundeck.audit.log so I know it's not an aclpolicy issue.  The same job ran fine under Rundeck 1.6.1.

**Comment by fvillain** [comment]
For information I got the same problem here, but this looks like it is caused by privileges definition (in 2.4.2 at least)

With admin rights it is OK: 
```yaml
description: Admin, all access.
context:
  project: '.*' # all projects
for:
  resource:
    - allow: '*' # allow read/create all kinds
  adhoc:
    - allow: '*' # allow read/running/killing adhoc jobs
  job: 
    - allow: '*' # allow read/write/delete/run/kill of all jobs
  node:
    - allow: '*' # allow read/run for all nodes
by:
  group: 
    - admin
---
description: Admin, all access.
context:
  application: 'rundeck'
for:
  resource:
    - allow: '*' # allow create of projects
  project:
    - allow: '*' # allow view/admin of all projects
  storage:
    - allow: '*' # allow read/create/update/delete for all /keys/* storage content
by:
  group:
    - admin
```

But with custom rights it doesn't work : 
```yaml
---
description: ReadOnly  access.
context:
  application: 'rundeck'
for:
  project:
    - allow: [read] # allow view of all projects
  storage:
    - allow: [read,create,update,delete] # allow read for all /keys/* storage content
  system:
    - allow: [read]
  user: 
    - allow: [read]
by:
  group: 
    - Team

---
description: Read-Only project level access control
context:
  project: 'default'
for:
  resource:
    - equals:
        kind: event
      allow: [read]
    - equals:
        kind: node
      allow: [read,run,refresh]
  adhoc:
    - allow: [read,run,kill]
  job:
    - allow: [read,create,delete,update,run,kill]
by:
  group: 
    - Team
```

But maybe my configuration is bad ?

**Comment by gschueler** [comment]
@fvillain your project level access for Team does not have any "node" section.  

e.g.:

~~~ {.yaml}
  node:
    - allow: [read,run]
~~~

Also, see the `rd-acl` tool added in Rundeck 2.5 <http://rundeck.org/docs/man1/rd-acl.html>

**Comment by nfx** [comment]
Please monitor `/var/log/rundeck/rundeck.audit.log` file for a while to get the right reason. It would give you more clues. Most likely your problem is similar to the one described below.

I've faced this problem with job created from API. The thing with rundeck is that it has separate ACL policy for API tokens, which don't really rely on groups of users issuing API tokens. This was out of common sense and a bit surprising, but nevertheless, i've got it working. If the problem setting is the same (job created from API), then try looking at `/etc/rundeck/apitoken.aclpolicy` and make sure that it has `allow: [read,run]` for node by api_token_group.

**Comment by danifr** [comment]
For the record, I was experiencing the same problem after moving some of my machines around different Foreman hostgroups. After all, it was a matter of wrongly set permissions/ownership in `/var/lib/rundeck`

If you happen to run into this problem, remember to check all rundeck directories. It might be it.
Cheers,
Daniel.
