### ISSUE TITLE
Failed: AuthenticationFailure: Authentication failure connecting to node: "db-restore2". Could not authenticate

### ISSUE THREAD

**Issue by cmohanbs** [rundeck/rundeck#7190]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version:   3.3.12
* install type: (rpm,deb,war,launcher?).  rundeck-3.3.12-20210521.war
* OS Name/version:   SMP Debian 3.16.43-2 (2017-04-30) x86_64 GNU/Linux
* DB Type/version: mysql? postgres? h2?..  h2

**Expected Behavior**
Trying to add a remote node and it fails to authenticate using the SSH key.

I was able to generate RSA key pair and set the right permissions for private and public key on rundeck server.   Also copied the public key and saved it as authorized_keys on target node..   SSH connection works fine at unix level without any issue but when tried to add the node using rundeck and try to run a simple command and it fails to authenticate the remote node.

My resource YAML file looks like below

cmohan@db-restore1:~$ more res.yaml
db-restore2:
  description: Rundeck server node
  hostname: <ip of the target node)
  nodename: db-restore2 
  osArch: x86_64
  osFamily: unix
  osName: linux 
  osVersion: 3.16 
  tags: db-restore2
  username.default: cmohan
  ssh-key-path: /home/cmohan/.ssh/id_rsa 

permissions on my source server

-rw-------  1 cmohan cmohan  1679 Jul 24 07:52 id_rsa
-rw-r-----  1 cmohan cmohan   400 Jul 24 07:52 id_rsa.pub

permissions on my target server

-rw-r-----  1 cmohan cmohan  402 Jul 24 08:05 authorized_keys
-rw-r--r--  1 cmohan cmohan  270 Jul 24 08:06 known_hosts

**How to Reproduce**

tried using ansible hosts and still fails with SSH key authentication error

**Comment by spectroman** [comment]
hi, I don't see how u did create the key, but it worked for me only if I forced to create an RSA key, like this:

`ssh-keygen -t rsa -b 4096`

on top of the key file you will see: 
```
-----BEGIN RSA PRIVATE KEY-----
```

instead of the new openssh default which is, and will not work on rundeck (when u run ssh-keygen with no options):

```
-----BEGIN OPENSSH PRIVATE KEY-----
```
