### ISSUE TITLE
Webhook copy URL to clipboard not working

### ISSUE THREAD

**Issue by ProTip** [rundeck/rundeck#7195]
**Describe the bug**
Below are the issues in Webhooks page:

- Webhook URL after creation cannot be copied to clipboard when clicking in URL or the clipboard button. Workaround: select the whole webhook URL and hold it while pressing CTRL+C

**Is this a regression?**  
Yes, if we compare to 3.3.13
No, if we compare to 3.4.1
(applies for both issues)

**My Rundeck detail**
* Rundeck version: 3.4.2
* RC version: [rc1]
* install type: rpm,war
* OS Name/version: centos8,ubuntu18
* DB Type/version: mysql,h2

**To Reproduce**  
1. For URL issue: Go to webhooks page > create a webhook > click on URL or the clipboard button
2. hit CTRL+V in any notepad > nothing pasted

**Expected behavior**  
Get the URL copied to clipboard as in 3.3.13

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Firefox
 - Version Latest

**Comment by dlvcrk** [comment]
![image](https://user-images.githubusercontent.com/58412426/127538909-cdf00567-a9bf-4155-aa97-aa8c1c7b0b10.png)
