### ISSUE TITLE
[RUNDECK - 1.5.2] - Exception: Unexpected content type received: text/plain;charset=UTF-8

### ISSUE THREAD

**Issue by sebastienalbert** [rundeck/rundeck#720]
Creating a job with an option type remote url. 
remote_url: http:// [server]: [port] / raw / iDeploy approx PROJECT / HEAD / env.json! 

The "env.json" file is stored under Gitblit. 
When calling the remote_url, Gitblit returns the content-type and charset like this: text / plain; charset = UTF-8. 
There is no space between the content-type and charset. 

Rundeck does not accept the fact of not having space between the content-type and charset and returns the following error: "Failed loading remote option values" - Exception: Unexpected content type received: text / plain; charset = UTF-8 
URL: http:// [server]: [port] / raw / iDeploy approx PROJECT / HEAD / env.json! 

To solve the problem would have to accept Rundeck receive an http request with content-type and charset of the form : content-type;charset

**Comment by panticz** [comment]
In case you using GitLab to store the Allowed Values > Remote URL options you have to patch GitLab to delivery json as mime-type "application/json" instead of "text/plain":

```
# diff -Naur /opt/gitlab/embedded/service/gitlab-rails/app/helpers/blob_helper.rb.org /opt/gitlab/embedded/service/gitlab-rails/app/helpers/blob_helper.rb
--- /opt/gitlab/embedded/service/gitlab-rails/app/helpers/blob_helper.rb.org	2018-11-29 11:52:58.009109668 +0000
+++ /opt/gitlab/embedded/service/gitlab-rails/app/helpers/blob_helper.rb	2018-11-29 11:52:41.657085392 +0000
@@ -151,6 +151,8 @@
   def safe_content_type(blob)
     if blob.extension == 'svg'
       blob.mime_type
+    elsif blob.extension == 'json'
+      'application/json; charset=utf-8'
     elsif blob.text?
       'text/plain; charset=utf-8'
     elsif blob.image?
```
to by able to acces those as:
https://gitlab.example.com/foo/raw/master/bar.json?private_token=token1234
