### ISSUE TITLE
Localhost/Rundeck Server Node Executing as a Remote Node 

### ISSUE THREAD

**Issue by niall-munnelly** [rundeck/rundeck#7204]
**Describe the bug**
New installation of **Rundeck build 3.4.1 2021-07-15** with one project and one node: the Rundeck server/localhost. Ome project, no jobs. Local node resource is treated as a remote host when executing commands.

**My Rundeck detail**

* Rundeck version: 3.4.1 2021-07-15
* install type: war
* OS Name/version: RHEL7
* DB Type/version:postgres

**To Reproduce**
1. Create and configure new instance with one project and local resource file:
resources.source.1.config.attributes=file-copy-destination-dir\: [my_temp_dir]
	nodename\: localhost
	username\: [my_id]
	resources.source.1.config.description=Rundeck
	resources.source.1.config.hostname=localhost
	resources.source.1.type=local

2. Navigate to project's ad hoc/commands view
3. Select localhost, run a command, like `id`
4. See SSH errors, in my case. Shouldn't these operations be "shelled out?"

**Expected behavior**
I would expect that ad hoc commands would be run on the Rundeck server as a shell operation. Instead, Rundeck is treating this server like a remote node, and searching for a the SSH keyfile defined in the default node and copy executors:

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser Safari, Chrome
 - Version Current

**Additional context**

**Comment by gschueler** [comment]
what is the value of `framework.server.name` in your framework.properties?

**Comment by niall-munnelly** [comment]
/opt/rundeck-community/etc/framework.properties:
framework.server.hostname: [FQDN]
framework.server.name: [FQDN]
framework.server.port: 5440
framework.server.url: http://[FQDN]:5440

Did I confuse these with grails.ServerURL?

**Comment by niall-munnelly** [comment]
Well, don't I feel sheepish - server.hostname and server.name have been set to localhost, and we're in business. Apologies for forgetting!
