### ISSUE TITLE
Cyrillic alphabet in the body of the script - Execute an inline script

### ISSUE THREAD

**Issue by krajster** [rundeck/rundeck#7206]
When using the Cyrillic alphabet in the body of the script, after saving the Cyrillic characters are all replaced with the symbols **???**

**My Rundeck detail**

* Rundeck version: 3.4.2-20210803 
* install type: war
* OS Name/version: Windows 2019
* DB Type/version: mssql

**To Reproduce**
1. Go to Jobs
2. Click on New Jobs
3. Click on Workflow
4. Scroll down to Add a step
5. Click on Script - Execute an inline script
6. In field "Enter the entire script to execute" enter Cyrillic symbols
7. Save script, save Job
8. Edit Job, edit Step 
5. See error

**Expected behavior**
When using the Cyrillic alphabet in the body of the script, after saving the Cyrillic characters are all replaced with the symbols **???**

**Screenshots**
Before save
![before_save](https://user-images.githubusercontent.com/8490440/128362337-a09eea38-3659-4174-8720-08fb6fee671e.png)

After save
![after_save](https://user-images.githubusercontent.com/8490440/128362376-fb04e42e-e5b0-42d9-9077-e73d7cc8313f.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser firefox
 - Version 90.0.2

**Comment by MegaDrive68k** [comment]
Hi @krajster 

Did you try adding `-Dfile.encoding=UTF-8` on your [rundeckd](https://docs.rundeck.com/docs/administration/configuration/system-properties.html#rpm-and-deb) file and restart the instance? Take a look at [this](https://github.com/rundeck/rundeck/issues/1619).

Regards!

**Comment by krajster** [comment]
Hi @MegaDrive68k 
my run profile - VM="-Dfile.encoding=UTF-8" "-Dsun.stdout.encoding=UTF-8" "-Dsun.err.encoding=UTF-8"

**Comment by krajster** [comment]
If you change the current dataSource.url from MSSQL to **"dataSource.url = jdbc: h2: file"** Cyrillic characters will be displayed normally. 
When **"dataSource.url = jdbc:sqlserver://"** Cyrillic characters will be displayed "?????".

**Comment by krajster** [comment]
Resolved:
changed dataSource.url to _jdbc:sqlserver://SERVER;integratedSecurity=true;DatabaseName=RUNDECK;**characterEncoding=UTF-8**_
