### ISSUE TITLE
Disable debug mode globally

### ISSUE THREAD

**Issue by mcassaniti** [rundeck/rundeck#7209]
A normal user can run any job in debug mode. This leaks global variables and can easily leak other variables if the options are incorrectly set on a job definition. Most issues are for disabling this option behind an ACL. Unfortunately this means a reasonable amount of work on the ACL side of things. I'm instead proposing a feature to disable debug globally. If nothing else this will identify all the call sites that need checks put in place.

I can foresee that a global option along with ACL based options can co-exist, so the work done here isn't entirely lost.

**Comment by mcassaniti** [comment]
Related #1137 and #1156

**Comment by mcassaniti** [comment]
I think this is the line that needs a permissions check added. This won't prevent the UI from showing the debug option (yet), but I think it will stop the option from doing anything. Making sure `DEBUG` is removed when it is disabled for the job by a security constraint should prevent it the debug output being logged.

https://github.com/rundeck/rundeck/blob/6e1cf127da87f993da856e5950532aa0c6646544/rundeckapp/grails-app/controllers/rundeck/controllers/ExecutionController.groovy#L890

**Comment by xmontagut** [comment]
I confirm this is a serious security concern. Perhaps I have not fully understood how to do it on a better way, but I use RD Vault + hidden options (as "Secure options") to pass some secrets... And the "debug mode" ruins everything, the users can read everything.
If using an ACL is too complicated, a global parameter would be enough in our case.
