### ISSUE TITLE
RUN-354: rundeck.gui.startpage not working for Community version 3.4.2

### ISSUE THREAD

**Issue by wkk1020** [rundeck/rundeck#7214]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: Community 3.4.2
* install type: rpm
* OS Name/version: CentOS Linux release 7.5.1804 (Core)
* DB Type/version: postgres

**Expected Behavior**
"rundeck.gui.startpage=jobs" is added to rundeck-config.properties and Rundeck is restarted, switching projects using the new project drop down list on the top should navigate to the chosen project's Jobs page, but it goes to the Dashboard page instead

**How to Reproduce**
1. add "rundeck.gui.startpage=jobs" into rundeck-config.properties
2. restart Rundeck
3. switch project using the new project drop down list on the top
4. the Jobs page should be display instead of the Dashboard page

**Comment by MegaDrive68k** [comment]
Confirmed with the same @wkk1020 steps.

Thanks for your feedback!

**Comment by kjoyce77** [comment]
I'm no Github expert -- is there a way to vote for issues?  Anyway, I am experiencing the same thing.
