### ISSUE TITLE
Kill job doesn't work

### ISSUE THREAD

**Issue by demogorgonz** [rundeck/rundeck#7223]
**Describe the bug**
Kill job doesn't kill actual job, process keeps running in background.

**My Rundeck detail**

* Rundeck version: Community 3.4.0
* install type: [chocolatey](https://community.chocolatey.org/packages/rundeck)
* OS Name/version: Win Server 2019

**To Reproduce**
1. Create a step `script` which run script `.\test.ps1 ` with loop task like `while(1) { sleep 1; Get-Random | Out-File 1.log }`
2. Set invocation string `pwsh -NonInteractive -NoProfile -ExecutionPolicy bypass -File`
3. Set file extension `.ps1`
4. Run the job, kill the job.
5. See the script running in process list, or check file content as it keeps changing (script continue to execute after "kill job")

![Capture](https://user-images.githubusercontent.com/5041776/129865288-3bc7e7bc-63c5-4aad-9e3a-3b75d88c314b.PNG)

**Expected behavior**
To kill the job ?

**Desktop (please complete the following information):**
 - OS: [e.g. Win 10]
 - Browser chrome
 - Version 92.0.4515.159

**Comment by majkinetor** [comment]
This happens to me to. Previously this only happened with exe's that are spawned from within shell but now shell itself, that is spawned by Rundeck is not killed which is a major problem.

**Comment by Khelben-Arunsun** [comment]
Yeah there should be a Rundeck option to Hook the kill button, catch the event, and Kill the remote process. 
The Knockout JS should deliver the button click event to end a job to a rundeck option, and then wait for the child process has ended successful callback , then end the current execution. 

`bool Rundeck-Option-kill-job == False;
While (job is running){ 
if (kill job on-click = true){

  try {
              HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
              if (response.statusCode()==200) {
                  Rundeck-Option-kill-job == true;
              } else
                  System.out.println(response.statusCode());
                  System.out.println(response.body());
                  }
  
          } catch (IOException | InterruptedException e) {
              System.out.println("caught exception... Job Did not kill properly");
              e.printStackTrace();
          }

    }
}`

**Comment by demogorgonz** [comment]
Any update on this bug?

**Comment by sanchobouillant** [comment]
Hi, 

Same issue with PHP scripts :)

**Comment by demogorgonz** [comment]
Bumping this issue, the bug was submitted on 18th of August and is still not addressed...
