### ISSUE TITLE
strange command line option: --installonly

### ISSUE THREAD

**Issue by peutch** [rundeck/rundeck#7275]
**Describe the bug**

Rundeck cannot be installed only using the command line option --installonly,
it is just equivalent to skip the server start.

**My Rundeck detail**

* Rundeck version: 3.4.4
* install type: war
* OS Name/version: Debian GNU/Linux 11
* DB Type/version: mariadb

**To Reproduce**

Steps to reproduce the behaviour:

$ java -jar rundeck-3.4.4-20210920.war -d --installonly

[---]
VERBOSE: --skipinstall: Not extracting.
VERBOSE: Done. --installonly: Not starting server.

**Expected behavior**

--installonly should then exclude --skipinstall but it is added by default (so why having this as an option? ;-))

and this is not syntactically equivalent to:

$ java -jar rundeck-3.4.4-20210920.war --skipinstall --installonly

ERROR: --installonly and --skipinstall are mutually exclusive

**Comment by MegaDrive68k** [comment]
Hi @peutch 

Install only just deploy config files without starting the server. A good scenario for that is the WAR-based instance [upgrade](https://docs.rundeck.com/docs/upgrading/upgrading.html#runnable-war).

Regards!

**Comment by peutch** [comment]
Yes, that is exactly what I was expecting.
But after a first run without getting the config files, I used '-d' to get debug message and I saw the following:

VERBOSE: --skipinstall: Not extracting.

So I was surprised because I did not use such an option.
I was thinking that '-installonly' excludes '--skipinstall'  and there is no '--no-skipinstall' option.
