### ISSUE TITLE
API token duration timer 0 does not work in docker container

### ISSUE THREAD

**Issue by Bibelo** [rundeck/rundeck#7282]
Hello all

Let talk about setting the duration timer for the API token to 0 (= infinite)

According to the doc:
>  rundeck.api.tokens.duration.max : Duration string indicating maximum lifetime of API Tokens. If unset, the value will be "30d" (30 days). Format: "##{ydhms}" (years, days, hours, minutes, seconds). If you want to disable the max expiration you can set it to 0 and create token with 0 duration that don't expire.

_This does not work_

Tried settting this parameters as follows:
rundeck.api.tokens.duration.max=0
rundeck.api.tokens.duration.max=0d (as seen in some posts)
Spent all morning trying, then restarting the rundeckd service, tried restarting the container, tried recreating the container (with the config file mounted on the host)

In the WebUI, when adding a token as admin,
**The token invariably sets to 30d effing days**
Strangely enough, when putting 0d in the conguration file, the WebUI field is pre-filled with 0.

As you can see, once again I tried a combination of multiple solution to the point where it's hard for me to know what I tried.

What am I missing here? Are there other authorizations somewhere else? My user is admin, so max privilege I guess.

If someone has a lead on this one, please please let me know. Because I've got to create a token every 30 days and change in all my scripts.

Thank you in advance!

**Comment by MegaDrive68k** [comment]
Hi @Bibelo 

I tested it on my local environment and it works, try [this](https://www.reddit.com/r/Rundeck/comments/pz47y8/comment/heyxe1w/?utm_source=share&utm_medium=web2x&context=3) in your Docker env.

Regards!
