### ISSUE TITLE
How to execute a job on only a single node

### ISSUE THREAD

**Issue by mjallday** [rundeck/rundeck#729]
I'm want to say "run this job once on any of these nodes".

What's the best way to do this? So far it has been suggested to implement it as a StepPlugin.
- http://rundeck.org/docs/developer/workflow-step-plugin.html
- https://github.com/rundeck/rundeck/blob/development/examples/example-java-step-plugin/src/main/java/com/dtolabs/rundeck/plugin/example/ExampleStepPlugin.java#L139

Here's the conversation we had with in IRC

> 12:18 < mahmoudimus> Alex-SF, my colleague mjallday is the one doing the integration here - so he'll take this convo moving fwd
> 12:18 < mahmoudimus> Alex-SF, but I guess the question is: what's the quickest way to mvp this step plugin?
> 12:19 < Alex-SF> it's a WorkflowStep plugin type. this kind of plugin gets the list of nodes that matched for the job and decides what to do
> 12:19 < Alex-SF> e.g, it might call call the dispatch CLI to run an ad-hoc, or it might call another remote execution framework
> 12:21 < Alex-SF> mahmoudimus: here's a java example of that kind of plugin. 
>                  https://github.com/rundeck/rundeck/blob/development/examples/example-java-step-plugin/src/main/java/com/dtolabs/rundeck/plugin/example/ExampleStepPlugin.java#L139
> 12:21 < Alex-SF> mahmoudimus: it is possible to write a shell script type plugin that does the same idea
> 12:22 < mjallday> thanks Alex-SF. taking a look now
> 12:24 < mjallday> are you able to expand on the shell script part Alex-SF ?
> 13:46 < mahmoudimus> Alex-SF: thanks
> 13:46 < mahmoudimus> Alex-SF, do you have any examples of that shell script plugin?
> 13:46 < mahmoudimus> Alex-SF, is that part of the "Bring your own execution framework" ?
> 13:47 < Alex-SF> mahmoudimus: here's the intro doc about script plugins http://rundeck.org/docs/developer/plugin-development.html#script-plugin-development
> 13:48 < Alex-SF> mahmoudimus: the other execution framework only applies if you don't want to use the out-of-the box ssh node executor
> 13:49 < mahmoudimus> Alex-SF, cheers, let me take a look here and I'll followup with any questions I have
> 13:49 < Alex-SF> ok
> 13:50 < mahmoudimus> Alex-SF, thanks!

I'm not familiar with the rundeck platform but I'm beginning to dig through the existing plugins to get an idea of how to do this.

It looks like I just need to implement the `executeStep` method on whatever plugin class I create which has a single property `executionLimit` which is the number of times we'd want the task to be executed.

Any quick tips on how to limit the number of nodes that the task is executed on? `PluginStepContext` has a `getNodes` method which I assume I could override bt I'm unsure how to do that from the context of a plugin. 

``` java
    public void executeStep(final PluginStepContext context, final Map<String, Object> configuration) throws
            StepException{
        if (Integer.parseInt(configuration.get("executionLimit").toString()) > context.getNodes().size()) {
            throw new StepException("executionLimit was > than node count", Reason.InsufficientNodes);
        }
    }
```

Presumably we could do something like

``` java
    public void executeStep(final PluginStepContext context, final Map<String, Object> configuration) throws
            StepException{
        ...
        context.nodes = someFilterMethod(context.nodes);
    }
```

where `someFilterMethod` is something like

``` java
public INodeSet someFilterMethod(INodeSet nodes, Integer executionLimit) {
    NodeSetImpl nodes = new NodeSetImpl();
    for (int i = 0; i < executionLimit; i++) {
        nodes.putNode(nodes[i]);
    }
    return nodes;
}
```

I guess that will always give us the same set of nodes to execute on but it achieves what we want.

**Comment by key-amb** [comment]
:+1: This feature will help us to clusterize batch worker nodes via hot/standby architecture.

**Comment by gschueler** [comment]
perhaps could be done via a plugin #826

**Comment by key-amb** [comment]
I read #826 . It looks a different idea.

* #826 ... Supply rolling update mainly for orchestration. Execute jobs on all nodes
* This issue ... Execute job only one time in one of specified nodes. Not for orchestration

**Comment by jerowe** [comment]
I'd like to vote for this feature too. We would like to use rundeck in an HPC scientific workflow environment, which it seems to be very well suited for except for this one thing. It would be nice if it was a proper feature. ;)

**Comment by ambikads** [comment]
+ 1

**Comment by kevhu** [comment]
This is something we'd like to use too.  Any chance of reviving this thread?

**Comment by akshah123** [comment]
@kevhu  & @ambikads  I believe this is already available as a feature.  You can do this by changing the orchestrator to "Random Subset" and changing the count to 1.  This way it will randomly pick 1 node and run the command on it.

**Comment by kevhu** [comment]
Looks like the Orchestrator plugin could work: https://github.com/rundeck/rundeck/issues/700

**Comment by ambikads** [comment]
I want to show all the nodes on the run page, but the user should be able to select only one node. Some jobs are very critical and its safe to have this instead of having the ability to update all nodes at the same time. If the user chooses more than 1 node, it should error saying 'only one node can be selected'. Don't think orchestrator plugin does that, does it?

**Comment by jph98** [comment]
+1

**Comment by dwinshipIdentifi** [comment]
Is this an option yet?

**Comment by gschueler** [comment]
Orchestrator plugin should be used
