### ISSUE TITLE
Disable Job Activity logging

### ISSUE THREAD

**Issue by matheuscaselani** [rundeck/rundeck#7312]
Issue type: Request ?

**My Rundeck detail**

* Rundeck version: 3.4.3
* install type: Container ( probably war )
* OS Name/version: Ubuntu 18.04 - Bionic
* DB Type/version: mysql 5.7 ( AKA MariaDb )

**Request**
I have more than 200 projects with many many many jobs running at time. During clean up execution my load goes up to the sky and everything stop working. I want to know if there is a way to disable Job Activity logging to stop generating all this XML files.

**How to Reproduce**
Access any project > Navigate to Jobs > Below All jobs u can see the job activity log

**Comment by fdevans** [comment]
@matheuscaselani Are you saying that if you configure "[Execution History Clean](https://docs.rundeck.com/docs/manual/project-settings.html#execution-history-clean)" that your server performance takes a hit?  We have configured that on significantly sized organizations and it has run well.  Seems you might scale down the size of the clean up batches but maybe run a bit more frequently.  Once it's caught up it should be easy to tune the cleanup task to run during off hours and remove most/?all? of the history.

**Comment by fdevans** [comment]
How many executions are they cleaning up each run?
