### ISSUE TITLE
Restarting Rundeck via a job

### ISSUE THREAD

**Issue by simo735** [rundeck/rundeck#7328]
Hello, 

**The problem :**
We have a job that change ldap password in rundeck conf then restart the application.
However during it's execution the job fail in timeout because we lose rundeck for some time due to it's booting.
Is there a way to have a job in rundeck that restart rundeck itself withoutfalling in error.

**Describe the solution you'd like**
We need to have a job that restart rundeck and finish without error. A job that can handle the rundeck restarting.

**Comment by fdevans** [comment]
Hi @simo735.  Please provide the details included in the Issue templates so we can better answer your question.  Particularly environment details like Rundeck version, etc.
