### ISSUE TITLE
Rundeck 3.4.x interprets arguments differently than 3.3.x

### ISSUE THREAD

**Issue by leshik** [rundeck/rundeck#7338]
**Describe the bug**

Starting from v3.4.x Rundeck interprets options in jobs differently than in previous versions. Previously, I didn't have to care about escaping spaces and other characters, and just using `"${option.some_option}"` in steps correctly passed options to commands. This is not the case anymore and is a serious regression. All my regexp became broken and I had to downgrade back to v3.3.12.

**My Rundeck detail**

* Rundeck version: `3.4.5`
* install type: `docker` official
* DB Type/version: `MySQL 5.7`

**To Reproduce**

1. Use some option with regexp, e.g. `pattern_user: ^folder/\d+_USER\.csv$`
2. Pass it to the step (e.g. shell script) as `"${option.pattern_user}"`
3. The result will be different in v3.4.x comparing to v3.3.x (escaping symbols stripped)

**Expected behavior**

I expect the behavior to be backward compatible, i.e. arguments passed to commands should be the same in v3.3.x and v3.4.x.

**Comment by MegaDrive68k** [comment]
Fixed [here](https://github.com/rundeck/rundeck/pull/7389).
