### ISSUE TITLE
Rundeck v. 3.4.5 - Job Scheduling do not work

### ISSUE THREAD

**Issue by picoroma** [rundeck/rundeck#7339]
**Describe the bug**
Scheduling a JOB in the future  do not work and make JOB run immedially
**My Rundeck detail**

* Rundeck version: [ 3.4.5]
* install type: [rpm]
* OS Name/version: [CentOS 7]
* DB Type/version: [mysql ]

**To Reproduce**
1. create a new JOB
2. make it execution in the future - RUN JOB LATER
3. SAVE

**Expected behavior**
The JOB should be waiting for the desired RUN date&time. Instead, It will be executed immediately.
Server TIME\DATE is correct.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Chrome]
 - Version [94]

**Additional context**
On previus version of RUNDECK i have it (3.4.1) . Everythings works fine

**Comment by Jupythr** [comment]
+ 1

**Comment by wakeling-duncan** [comment]
+1 (on 3.4.6 also)

**Comment by constancyGmbH** [comment]
Does anybody know a workaround for that bug?

**Comment by Jupythr** [comment]
> Does anybody know a workaround for that bug?

Hello, we downgraded rundeck in 3.4.4

yum --setopt=obsoletes=0 downgrade rundeck-3.4.4.20210920-1.noarch

**Comment by axcawef** [comment]
We are having the same issue on 3.4.5

**Comment by NoobyNoob1983** [comment]
Revert to 3.4.4  seems to work need Fix for 3.4.5 - 3.4.6

**Comment by 0none** [comment]
Can still reproduce on 3.4.6

**Comment by jtobard** [comment]
closed with: https://github.com/rundeck/rundeck/pull/7357

**Comment by picoroma** [comment]
Sorry for my answer. I need clarification:
To solve this issue I need to wait the release of Ver. 3.4.7 ?
Or perform a downgrade to 3.4.4 ?
Is this correct?
Is possible to know when the Ver. 3.4.7 will be released?
thx
P.

**Comment by jtobard** [comment]
@picoroma you need to wait for 3.4.7 release that will be the next release, it's not possible to know the exact date yet but soon.
