### ISSUE TITLE
Tags of node groups are invisible on the job page.

### ISSUE THREAD

**Issue by buptzhoutian** [rundeck/rundeck#7342]
Issue type: Bug report

**My Rundeck detail**

* Rundeck version: 3.4.5
* install type: deb
* OS Name/version: Debian 10
* DB Type/version: mysql

**Expected Behavior**
tags stand out well against the dark background

![image](https://user-images.githubusercontent.com/4327236/138813584-f9a51d8f-d90d-43eb-ba28-45add1ffff34.png)

**Comment by MegaDrive68k** [comment]
Fixed on 3.4.6.
