### ISSUE TITLE
Custom user logo not displaying correctly

### ISSUE THREAD

**Issue by natpalmer-e4o4** [rundeck/rundeck#7352]
https://github.com/rundeck/rundeck/blob/1b6d16fe4d4ef14516d1342a741d3a0b99c133c7/rundeckapp/grails-app/views/common/_mainbar.gsp#L33-L39

The `margin-top: 10px` is causing logos to display outside of the top menu bar that they're contained in.
![image](https://user-images.githubusercontent.com/43360790/139710223-2eb6d5e6-2972-4af1-af71-5eeff2194b6f.png)

Removing the `margin-top` causes it to display correctly:
![image](https://user-images.githubusercontent.com/43360790/139710470-df119e00-4dc5-4f78-a0ef-90bd5e62563e.png)

This becomes significantly more noticeable when using logos / images with a non-transparent background as it hides the edge transition between the menu bar and main page content.

I don't imagine removing margin-top will cause any other display issues since the height of the image is set explicitly.

**Comment by natpalmer-e4o4** [comment]
A workaround for this issue is to use a logo with a transparent background and 33% padding on the bottom of the image to force it to render in the correct location, though the image will be scaled down somewhat as a result.

For example, a 40px by 40px image can be 'fixed' by replacing it with a 40px by 60px image that has 20px of transparent 'whitespace' along the bottom of the image.

**Comment by MegaDrive68k** [comment]
Confirmed. I see the same behavior:

<img width="850" alt="Screen Shot 2021-11-01 at 16 42 59" src="https://user-images.githubusercontent.com/51376003/139731908-75379cb2-e5c4-42db-9970-a285bd1e11a0.png">

Thanks for your feedback @natpalmer-e4o4 !
