### ISSUE TITLE
User defined instance name is not displaying correctly

### ISSUE THREAD

**Issue by natpalmer-e4o4** [rundeck/rundeck#7353]
https://github.com/rundeck/rundeck/blob/9d5c61581da74dc871c4bb06ee19f977c873729d/rundeckapp/grails-app/views/common/_mainbar.gsp#L113-L122

User defined instance names are being pushed below the bottom of the top bar.
![image](https://user-images.githubusercontent.com/43360790/139711400-31392b9c-e81f-4266-b798-0f5d3acaac78.png)

This can be remediated by setting the `margin` to `margin: 10px 15px 10px 0`
![image](https://user-images.githubusercontent.com/43360790/139711437-c6a96afe-826c-4816-85dd-7751f3a26663.png)

After modifying the margin I didn't notice any additional artifacts when zooming the page in / out.

**Comment by MegaDrive68k** [comment]
Confirmed, 

<img width="337" alt="Screen Shot 2021-11-01 at 16 48 00" src="https://user-images.githubusercontent.com/51376003/139732299-8fe91cbe-d2e3-4a0c-9cb3-762b222b2011.png">

To reproduce: 

1. Stop the Rundeck instance.
2. Add the following line to the `rundeck-config.properties` FILE:

`rundeck.gui.instanceName=MYINSTANCENAME`

3. Start the rundeck instance.
4. See the instance name on the Projects page.


Thanks again @natpalmer-e4o4!
