### ISSUE TITLE
Backslash removed from option after clicking "edit" button.

### ISSUE THREAD

**Issue by elwinh** [rundeck/rundeck#7370]
**Describe the bug**
In the webinterface, when editing a option value where you previously entered a backslash, the backslash is removed. You may re-enter the backslash and it is correctly saved and shown. That is until you press the "edit" button and then the backslash is stripped of the value again.

Example value: "domain\username"
After clicking the edit button, this becomes: "domainusername"

**My Rundeck detail**

* Rundeck version: 3.4.5
* install type: docker
* OS Name/version: ubuntu 20.04
* DB Type/version: mysql

**To Reproduce**
1. Create a option and add as value: 'domain\username'
2. Click on 'save'
3. Click on 'edit'
4. The backslash has been removed from the value

**Expected behavior**
I expect the backslash to be listed after i click the edit button.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Additional context**
-

**Comment by MegaDrive68k** [comment]
Same issue: https://github.com/rundeck/rundeck/issues/7338
