### ISSUE TITLE
Some text of Markdown table is invisible in dark mode

### ISSUE THREAD

**Issue by buptzhoutian** [rundeck/rundeck#7380]
**Describe the bug**
Some text of Markdown table is invisible in dark mode

**My Rundeck detail**

* Rundeck version: 3.4.6
* install type: deb
* OS Name/version: Debian 10
* DB Type/version: MySQL

**Screenshots**

- Light Mode

![image](https://user-images.githubusercontent.com/4327236/141651617-9d847993-20b3-46e8-a31e-fea04271f293.png)

- Dark Mode
![image](https://user-images.githubusercontent.com/4327236/141651632-34a9c718-f1f1-4328-86b5-5c661a1c8d33.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge
 - Version: 95.0.1020.44

**Comment by buptzhoutian** [comment]
@manticora17

**Comment by MegaDrive68k** [comment]
Same for some HTML code:

<img width="1387" alt="Screen Shot 2021-11-15 at 10 00 50" src="https://user-images.githubusercontent.com/51376003/141786459-9f85a5b8-75af-447d-ad1d-3222c84100b0.png">

Thanks for your feedback @buptzhoutian!

**Comment by sieuwe** [comment]
Also the text on some buttons is badly readable:
![2021-11-25 10_16_48-Rundeck - Create New Job](https://user-images.githubusercontent.com/1788082/143413718-527c68ad-04f7-4617-8f21-eccf6e26c45a.png)
