### ISSUE TITLE
3.4.5/3.4.6 : duplicate option does not work

### ISSUE THREAD

**Issue by mazzella-c** [rundeck/rundeck#7381]
**Describe the bug**
Unable to duplicate a job option since 3.4.5, it's working fine until 3.4.4

**My Rundeck detail**

* Rundeck version: 3.4.5/3.4.6
* install type: war
* OS Name/version: RHEL 7.9
* DB Type/version: Postgre

**To Reproduce**
1. Create a job
2. Create an option
3. Try to duplicate it
4. Nothing happens

**Expected behavior**
It should work as before

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser : Firefox/Chrome
 - Version 93/87

**Additional context**
Tested with Firefox/Chrome

**Comment by MegaDrive68k** [comment]
Confirmed. 

Thanks a lot for your feedback @mazzella-c!

**Comment by PDD777** [comment]
Also reproducible in Debian 10 deb install.
Including existing and/or imported job.

**Comment by MegaDrive68k** [comment]
Fixed [here](https://github.com/rundeck/rundeck/pull/7420).
