### ISSUE TITLE
SQLException using API or GUI to delete a job

### ISSUE THREAD

**Issue by pcarvey** [rundeck/rundeck#7382]
**Describe the bug**
Running this command: 
curl -X DELETE -H 'X-Rundeck-Auth-Token: ' http://rundeck-dev.domain:8080/rundeck/api/34/job/jobid throws the following error:

java.sql.SQLException</dd><dt>Message</dt><dd>Could not roll back Hibernate transaction; nested exception is org.hibernate.TransactionException: Unable to rollback against JDBC Connection</dd><dt>Caused by</dt><dd>Connection has already been closed.

Also observed this in the cleanup log:  [quartzScheduler_Worker-7] ERROR rundeck.quartzjobs.ExecutionsCleanUp - Failed to delete execution 1117732 org.hibernate.exception.GenericJDBCException: could not prepare statement

I get the same error if I use the web interface. Problem persists even if I restart tomcat.

**My Rundeck detail**

* Rundeck version: 3.2.3-20200221 
* install type: war
* OS Name/version: RHEL 7.8 
* DB Type/version: postgres

**To Reproduce**
1. Run following command: curl -X DELETE -H 'X-Rundeck-Auth-Token: ' http://rundeck-dev.domain:8080/rundeck/api/34/job/jobid 

**Expected behavior**
Job should be deleted; instead I get this error and need to restart tomcat.

**Comment by MegaDrive68k** [comment]
Hi @pcarvey 

Could you share the full stack trace? Probably you need to [increase](https://github.com/rundeck/rundeck/issues/3989#issuecomment-465108407) the active connections on your backend.

Regards.

**Comment by pcarvey** [comment]
Thanks @MegaDrive68k .. will try that.  Attaching the full stacktrace.
[log.txt](https://github.com/rundeck/rundeck/files/7549750/log.txt)

**Comment by MegaDrive68k** [comment]
It depends on your workload, also try with [these](https://github.com/rundeck/rundeck/issues/4255#issuecomment-454096369) params.

**Comment by pcarvey** [comment]
The following  parameters resolves the issue for us: 
initialSize="10"
                maxActive="200"
                removeAbandoned="true"
                removeAbandonedTimeout="240"
                testOnBorrow="true"
                maxIdle="30"
                maxWait="3000"
                validationQueryTimeout="20000"
