### ISSUE TITLE
Text not visible on pop-up notifications in dark mode

### ISSUE THREAD

**Issue by manticora17** [rundeck/rundeck#7384]
**Describe the bug**
Colors look weird in dark mode, text not visible on pop-up notifications.

**My Rundeck detail**

* Rundeck version: 3.4.6
* install type: docker
* OS Name/version: from rundeck/rundeck:3.4.6
* DB Type/version: PostgreSQL

**To Reproduce**
1. Switch to dark mode
2. Delete a job or perform any other operation that usually renders a pop-up notification
4. See colors

**Expected behavior**
Text is clearly visible on its background

**Screenshots**

**Light mode**
![Screen Shot 2021-11-16 at 4 01 16 PM](https://user-images.githubusercontent.com/37708597/142065204-f76c8269-dc86-4733-975a-93050a8689a4.png)

**Dark mode**
![Screen Shot 2021-11-16 at 3 48 34 PM](https://user-images.githubusercontent.com/37708597/142065266-3995113a-10b9-4b29-8b74-07c66114986a.png)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version 95.0.4638.69

**Comment by MegaDrive68k** [comment]
Fixed here for next release https://github.com/rundeck/rundeck/pull/7368

Thanks, @manticora17!
