### ISSUE TITLE
version mismatch github <--> packagecloud

### ISSUE THREAD

**Issue by elwinh** [rundeck/rundeck#7388]
_Note: Bug Reports not following this template may be closed without feedback._

**Describe the bug**
Following the [tag number on github](https://github.com/rundeck/rundeck/releases/tag/v3.4.6), i expected commit 862233ab428261eaf8d5cf9dfa540a4d23f8eed6 to be part of [v3.4.6-20211110](https://github.com/rundeck/rundeck/compare/v3.4.6...main) as it is listed on github as parts of the [commits](https://github.com/rundeck/rundeck/compare/v3.4.6...main) of that specific version number. (https://github.com/rundeck/rundeck/releases) 

When i look in packagecloud, that specific commit is not part of the package: https://packagecloud.io/pagerduty/rundeck/. In fact, the github version is from a couple of days later version then the version in packagecloud. It looks like additions are made to the github version number after the package has been build and pushed to packagecloud. Those additions have not triggered a rebuild in packagecloud so now we have a version mismatch. 

Can you guys make sure the code on Github of a specific version tag is the same as the code on packagecloud with the same tag?

**Expected behavior**
I expect the content of a specific version number to be the same in github and packagecloud.

**Comment by gschueler** [comment]
Are you clicking the link that says `"30 commits" to main since this release` ? that will list commits that have happened *after* the tag.  so those commits are not included in that release.

clicking on the commit 862233a will show that it is included in tag "3.4.7-rc1", it will be included in the next release version 3.4.7

**Comment by gschueler** [comment]
fyi this link will show commits in the 3.4.6 tag https://github.com/rundeck/rundeck/commits/v3.4.6
