### ISSUE TITLE
Navigation sidebar disappeared

### ISSUE THREAD

**Issue by AMKamel** [rundeck/rundeck#7398]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
I am using rundeck 3.4.6 community edition for about a year now on docker and I suddenly found that UI navigation sidebar disappeared and the look is totally strange now, following are some screenshots
also the header is no longer as it was and the footer has disappeared which was previously including news

**My Rundeck detail**

* Rundeck version: [3.4.6]
* install type: [docker]
* OS Name/version: [ubuntu 20.04]
* DB Type/version: [mysql]

**To Reproduce**
1. Go to Project home page
2. See that there is no more navigation sidebar existing

**Expected behavior**
What is expected is to see sidebar working properly with links to jobs, commands, etc...

**Screenshots**
![image](https://user-images.githubusercontent.com/14953512/144030513-5d1cfc7c-3b27-4eb4-8183-2b6cc5d13ab6.png)

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Browser [chrome]
 - Version [96.0.4664.45]

**Comment by MegaDrive68k** [comment]
Hi @AMKamel 

I'm trying to reproduce the issue unsuccessfully, could you try from an incognito browser window or from another browser like Firefox?

Greetings.

**Comment by AMKamel** [comment]
The same from firefox
![image](https://user-images.githubusercontent.com/14953512/144175480-c9b1323a-ff04-4199-aa20-481cdaf5b19f.png)

**Comment by MegaDrive68k** [comment]
Hi @AMKamel 

Your instance is behind of proxy server? If so, could you try accessing directly to the Rundeck instance to discard this? Probably you're facing [this](https://github.com/rundeck/rundeck/issues/6278).

Regards.

**Comment by AMKamel** [comment]
Thanks for your response @MegaDrive68k 

Actually `grails.serverURL` was set properly but when I disabled cloudflare proxy, it worked properly.

Does it mean that we can't use cloudflare proxy with rundeck or there is a solution for this?

**Comment by MegaDrive68k** [comment]
Hi @AMKamel 

Usually, the solution is to set `RUNDECK_GRAILS_URL` to the proxy URL endpoint and set`RUNDECK_SERVER_FORWARDED` to `true`.  You can check [this](https://github.com/rundeck/docker-zoo/tree/master/cloud) cloud example to test in your env.

Greetings.

**Comment by AMKamel** [comment]
Cloudflare custom rules was the solution for leaving the site behind proxy for protection.
![image](https://user-images.githubusercontent.com/14953512/144267981-9e45f95a-2497-4a90-b32c-e0d649190c6c.png)
```
Polish: Off, Auto Minify: Off, Cache Level: Bypass, Origin Cache Control: On, Disable Performance
```

**Comment by AMKamel** [comment]
Using cloudflare custom rules solved this without disabling their proxy

```
Polish: Off, Auto Minify: Off, Cache Level: Bypass, Origin Cache Control: On, Disable Performance
```
