### ISSUE TITLE
Please support JDK 15 at a minimum.

### ISSUE THREAD

**Issue by gjvc** [rundeck/rundeck#7425]
**Describe the solution you'd like**
Please support JDK 15 at a minimum.

**Comment by MegaDrive68k** [comment]
Hi @gjvc  take a look at [this](https://github.com/rundeck/rundeck/issues/7110#issuecomment-858631694) and [this](https://github.com/rundeck/rundeck/issues/7128#issuecomment-864667398).

Thank you!

**Comment by gjvc** [comment]
Understood.  This item to refer to JDK17 instead, as that is the newly-released LTS version.
