### ISSUE TITLE
Error for download page in docs

### ISSUE THREAD

**Issue by adnub12** [rundeck/rundeck#7432]
In documentation:
```
https://docs.rundeck.com/docs/administration/install/linux-rpm.html#installing-rundeck
```
![Zrzut ekranu z 2021-12-13 12-52-30](https://user-images.githubusercontent.com/96057067/145811794-6181cd88-fe62-4d96-9c33-cb81bd61287b.png)

Is a download Page, who redirect to:
```
https://docs.rundeck.com/docs/downloads.html
```
and this site have 404 Not Found..

![Zrzut ekranu z 2021-12-13 12-49-39](https://user-images.githubusercontent.com/96057067/145811785-521d6f77-ddfa-4aad-bff5-e49afc03f2e7.png)

**Comment by MegaDrive68k** [comment]
Confirmed, thanks for your feedback @adnub12!

**Comment by fdevans** [comment]
this has been fixed and will be refreshed the next time we do a build of the site.  (Likely at next release)
