### ISSUE TITLE
Log output is empty

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#7456]
Hi Guys,

I just upgraded Rundeck to 3.4.9 and it appears for large Logs (not too much large ;) ) the log output is empty. 

Issue:
![image](https://user-images.githubusercontent.com/20629911/147626357-eced3dde-7968-462e-b7b7-cc83feb8e17a.png)

![image](https://user-images.githubusercontent.com/20629911/147626418-f4f6ab01-319f-4c82-a2b2-56fbef6ca787.png)

Note, the same Logs are visible from one of the Execution Log options
![image](https://user-images.githubusercontent.com/20629911/147626469-c3ce854b-84b5-4747-9748-a98d86ee6ed3.png)

I downloaded the log as an HTML file and the size is only 694KB
![image](https://user-images.githubusercontent.com/20629911/147626516-530ad18a-7963-49b2-9cba-641ecb8cb107.png)

a smaller job with a html log file size 80KB does work:
![image](https://user-images.githubusercontent.com/20629911/147626708-3ca7369e-79bd-49f7-ae14-21a39fe1b089.png)

-- INFO -- 
RUNDECK:
  APIVERSION : 40
  BASE : /var/lib/rundeck
  BUILD : 3.4.9-20211221
  BUILDGIT : v3.4.9-0-gfe92051
  NODE : rdserver
  SERVERUUID : 57946b2b-b731-4f00-8e27-xx globe-57
  VERSION : 3.4.9-20211221
OS:
  - ARCH : amd64
  - NAME : Linux
  - VERSION : 3.10.0-862.14.4.el7.x86_64

Thank you!
HS

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world 

This happens when you click the node output and later the log output right? If you click the log output first still happening?

Regards.

**Comment by MegaDrive68k** [comment]
I reproduced it in the following way:

1. I generated a 15K file with `dd if=/dev/urandom of=sample.txt bs=15k count=1`.
2. I created a job that prints that file, then run it.
3. Clicking on Nodes (I see the output).
4. Clicking on Log Output (blank). 

Running the job and clicking on Log output directly (without clicking on Nodes first), the output is available.

**Comment by hs-hub-world** [comment]
You nailed it @MegaDrive68k, that's correct, I was able to reproduce your steps as well.

- run the job while in the Nodes view
- Regardless of while the job is running or if it just finished 
- As long as you **don't view  Node Logs** from the "Nodes View" **you can still see the logs** from the "Log Output"
- As soon as you view a Node Logs and try to switch to "Log Output" it's empty
-Also-
- When viewing the "Log Output" first then switching back to "Nodes" page and viewing the node logs the "Log Output" does not disappear anymore.



I am not sure if the log size matters at this point, I tested with this PS script with increments of 3k,4k,5k,15k, and 150k they all have the same behavior described above.
```

$TempFile="c:\temp\test_file.txt"
write "Starting..." |Out-File "$TempFile" -force
do{
    write "Sample text,test" |Out-File "$TempFile" -Append
}while(((get-item "$TempFile").length/1KB) -lt 15)
gc $TempFile
```

**Comment by aairey** [comment]
We have the same issue, but not sure if I ever viewed node output before ...
Every user so far of our Rundeck instance has it, I doubt if all of them viewed the node output.

This is since upgrading to 3.4.x from 3.3.x, it was okay for sometime, but suddenly it stopped showing.
Restart does not help.
We also changed to mysql as a backend around that time.
