### ISSUE TITLE
(Chrome, Edge) Activity search filter hover text blocks filter edit button

### ISSUE THREAD

**Issue by squirrelchew** [rundeck/rundeck#7469]
**Describe the bug**
When applying a short filter, such as name: tableau, to the dashboard, the hover text to modify the filter almost entirely covers the clickable filter element.

**My Rundeck detail**

* Rundeck version: 3.4.9
* install type: rpm
* OS Name/version: amazon linux 2
* DB Type/version: mysql

**To Reproduce**
1. Go to activity (/project/project-name/activity)
2. Click on "Search"
3. Enter a short name to search for, such as "tableau" and apply the filter
4. Attempt to edit your search filter and witness the majesty of the rendering error

**Expected behavior**
I'd expect to the hover text to render in a fashion that does not block the element I'm hovering over and wish to click.

**Screenshots**
Without hovering:
![image](https://user-images.githubusercontent.com/32274759/148584518-f493e01a-191d-4ef0-bf2a-e9112085a1ff.png)

With hovering:
![image](https://user-images.githubusercontent.com/32274759/148584539-343d7d63-ce92-49cf-a942-ed06ef3a1651.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1
 - Browser: Chrome (incognito/all plugins disabled)
 - Version 96.0.4664.110

**Comment by MegaDrive68k** [comment]
Confirmed, same on Firefox.

**Comment by dlvcrk** [comment]
Reproduced and also occuring when disabling a webhook action (green button):
<img width="232" alt="image" src="https://user-images.githubusercontent.com/58412426/151442797-2ccc378c-c425-4b3b-9685-878fe03c70b4.png">
