### ISSUE TITLE
Could not import a project from an archive got error PR_CONNECT_RESET_ERROR

### ISSUE THREAD

**Issue by Thorsieger** [rundeck/rundeck#7474]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
Could not import a project from an archive got error PR_CONNECT_RESET_ERROR

**My Rundeck detail**

* Rundeck version: 3.4.9
* install type: deb
* OS Name/version: Debian 10.1
* DB Type/version: mariadb 10.3.23

**To Reproduce**
1. Go to a project or create a new one
2. Click on Project settings / import archive
3. Add a previously created .rdproject.jar file
4. Click on import
5. See error

**Expected behavior**
Jobs and all other data should be imported to the project

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04.3 LTS
 - Browser firefox
 - Version 95.0.1

**Additional context**
I just upgrade rundeck from 3.3.1 to 3.4.9 .
The connection is secured by a ssl certificate signed by let's encrypt.
Other pages are working fine over https.
Same error running in a private window

**Comment by MegaDrive68k** [comment]
Hi @Thorsieger 

I'm trying to reproduce the issue unsuccessfully, [researching a bit](https://support.mozilla.org/en-US/questions/1280856) it seems an issue related to Mozilla Firefox Browser. Your instance is behind some firewall solution? Could you test without any extension? Does this happen using another web browser?

Regards.

**Comment by Thorsieger** [comment]
Thanks for the quick response.

I've test without any extension and with a fresh install of chrome v. 97.0.4692.71 with the same result.
My instance is a vm inside an openstack cluster that use security groups.

But the import function was working just before upgrading to rundeck 3.4.9 without any other change in the instance. Other functions seems to work fine as well. That's why I think there is something with rundeck.

**Comment by MegaDrive68k** [comment]
Hi @Thorsieger 

Any clue in the `service.log` output at the moment of importing the project file?

Greetings.

**Comment by Thorsieger** [comment]
Nothing written in the logs files ... 

Rundeck seems to receive the call because i found traffic using a tcpdump
