### ISSUE TITLE
Rundeck referenced Job does NOT honor parent job's Node Filter

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#7478]
Whenever we have a complex script we like to save them in a separate (referenced) job so other jobs can call them with different options. This makes it easier to manage since you would only need to modify the script from one job. This would work great in Rundeck if rundeck Referenced Job's would honor the parent (caller) job's Node filter. I have tried everything possible but it seems that I am missing something.  Could you please review below and let me know if I am missing something.

Here are the Jobs
![image](https://user-images.githubusercontent.com/20629911/149234489-54af80f3-1659-4bfd-b6bc-9cc8ed1ab7ce.png)
![image](https://user-images.githubusercontent.com/20629911/149234501-03c3505c-5229-4b1f-888d-05dd996f3c8e.png)

Here are nodes from the referenced Job
![image](https://user-images.githubusercontent.com/20629911/149234553-acae7d37-d972-4e84-9ccb-83cf2b361f20.png)

Here you can see the Parent (caller) job has only one Node selected
![image](https://user-images.githubusercontent.com/20629911/149234592-a58ec9b3-3115-430f-945e-705c5e3bf877.png)

Here you can see the Parent (caller) job does not have the option checked to use "Use referenced job's nodes..."
![image](https://user-images.githubusercontent.com/20629911/149234622-5b202a4c-2b1b-4638-b05d-c9593cb99be1.png)

Here is the Parent Job-1 before executing the Job
![image](https://user-images.githubusercontent.com/20629911/149234740-2301d2ac-cb1f-4afc-8863-d248b9c10ed9.png)

After executing the Job we can see all the OTHER nodes from the referenced Job were included with this job. 
![image](https://user-images.githubusercontent.com/20629911/149234786-d786394f-e505-422e-b8f3-2a85a4f8fd5e.png)

What am I missing here -?

Rundeck Info:
![image](https://user-images.githubusercontent.com/20629911/149234889-952e2d1d-616d-4fa4-abb8-87f1b3701e47.png)

Install type (Centos -Yum Package manager)

Thank you
HS

**Comment by gaddman** [comment]
Admittedly it doesn't appear to make sense given the checkbox you've highlighted, but I always select the intersection in the parent job and it works:
![image](https://user-images.githubusercontent.com/1311209/149641149-b2dbacfb-36d8-46e5-8254-24293ba44c46.png)

**Comment by hs-hub-world** [comment]
Thanks @gaddman, that works!
