### ISSUE TITLE
Docker Image: Allow managing plugins without requiring to rebuild the base-image

### ISSUE THREAD

**Issue by EugenMayer** [rundeck/rundeck#7487]
# Problem
Right now it is not possible to add any plugin when running the docker-image.

It is obviously not possible at all when running a docker-compose based stack, but it is neither possible when running a kubernetes stack.

One might assume `initContainers` are an option, but they are not. To make those work, we would need to make an volume for ` `/home/rundeck/libexec`. This is not an good idea or an option, since all stock-plugins are located here. Making an volume out of that would render rundeck useless or forces us the deploy all stock plugins manually and maintain them on each update.

There would be an option with ConfigMap and subPath, but since those jars can be several mb big, it is nothing that one stores in ConfigMaps ever.

Right now there is simple no way of adding plugins to the rundeck-instance without creating your own base-image, which has big downsides itself. Maintaining a custom build in the CI, rebuilding the image on each release of rundeck itself.

# Suggestion

Options are
 - a) make scanning for plugins directory-recursive so one can mount a volume to `/home/rundeck/libexec/custom-plugins` - yet this seems not to be the case looking at [this](https://github.com/rundeck/rundeck/blob/9d5c61581da74dc871c4bb06ee19f977c873729d/rundeckapp/grails-app/init/rundeckapp/init/prebootstrap/ServerLibInjectorPreBoostrap.groovy#L25)
 - b) add an alternative path for plugins like `/var/run/rundeck-custom-plugins` which is scanned in addition to `/home/rundeck/libexec`
 - c) Adjust entrypoint to copy external plugins from a specific folder https://github.com/EugenMayer/docker-image-rundeck#rundeck-plugins (one problem is - purely additive)

**Comment by EugenMayer** [comment]
I found a folder `/home/rundeck/server/addons` - not sure what it might do but it sounds familiar. It is not documented on 

- https://docs.rundeck.com/docs/administration/install/docker.html
- https://docs.rundeck.com/docs/administration/configuration/docker.html#security

So if it is the expected folder for that, we should document it

**Comment by EugenMayer** [comment]
Seeing https://github.com/rundeck/rundeck/blob/9d5c61581da74dc871c4bb06ee19f977c873729d/rundeckapp/grails-app/init/rundeckapp/init/prebootstrap/AddonClasspathInjectorPrebootstrap.groovy it might be tracked and injected - the question is, is a plugin an addon or is an addon something different?

**Comment by fdevans** [comment]
If you copy a plugin to `/home/rundeck/libext` of a running container it will be recognized by Rundeck.  I just tested on our [Welcome Project](https://github.com/rundeckpro/welcome-project) setup using this command and it loaded the updated plugin:

`docker cp myplugin.jar rundeck:/home/rundeck/libext`

**Comment by paulcalabro** [comment]
Another alternative is to do this with Compose:

```
---

version: '3.9'

services:
    rundeck:
        ports:
            - '4440:4440'
        volumes:
            - $PWD/docker-container-1.4.3.zip:/home/rundeck/libext/docker-container-1.4.3.zip
        image: rundeck/rundeck:4.0.1
```
<img width="1676" alt="Screen Shot 2022-04-13 at 1 27 07 PM" src="https://user-images.githubusercontent.com/585059/163264674-a2045465-2fb1-4c51-8c1b-cd153e1fa5f3.png">

**Comment by EugenMayer** [comment]
> If you copy a plugin to `/home/rundeck/libext` of a running container it will be recognized by Rundeck. I just tested on our [Welcome Project](https://github.com/rundeckpro/welcome-project) setup using this command and it loaded the updated plugin:
> 
> `docker cp myplugin.jar rundeck:/home/rundeck/libext`

When you upgrade your image, your plugin is one. Using an init-container wont work-since you  have no volume.
A way to do it with kubernetes

- create an volume for the plugins https://github.com/EugenMayer/helm-charts/blob/main/charts/rundeck/templates/plugins-pvc.yaml  and mount some any other place then the final destination.
- you mount your wrapper script https://github.com/EugenMayer/helm-charts/blob/main/charts/rundeck/templates/rundeck-backend-deployment.yaml#L78=
- override the CMD and copy all plugins before you proxy on the actual start CMD ttps://github.com/EugenMayer/helm-charts/blob/main/charts/rundeck/templates/rundeck-backend-deployment.yaml#L40=, https://github.com/EugenMayer/helm-charts/blob/main/charts/rundeck/templates/rundeck-backend-deployment.yaml#L95= and https://github.com/EugenMayer/helm-charts/blob/main/charts/rundeck/scripts/bootstrap.sh

So very easy. But i'am honest, not following any longer. It's time to move on from rundeck. We have been using it for more then 6 years now, but what happened in the last 2 years in rundeck speaks volumes. Time for stackstorm.

**Comment by fdevans** [comment]
Thanks for the feedback.  We'll see if we can incoporate it in future versions.

**Comment by monsdar** [comment]
Why has this been closed? Has this been solved somewhere else?
