### ISSUE TITLE
Docker-Image: what is ~/server/data used for?

### ISSUE THREAD

**Issue by EugenMayer** [rundeck/rundeck#7488]
I understand that `~/server/data` is expected to be mounted as a volume as per https://docs.rundeck.com/docs/administration/install/docker.html - but what is actually stored there?

In a docker runtime
 - projects are stored in the db
 - keys are stored in the db
 - execution logs are stored under `/var/log/rundeck`
 - server logs are under `~/server/logs`

So what is this folder actually for? It is important to understand to pick the right storage provider and to actually explain the usage

**Comment by fdevans** [comment]
When using H2 as the database this is where the database file would be stored.  It seems it's unused in recommended production setups with a stronger database backend.
