### ISSUE TITLE
[Docker-Image] No wat to configure s3 execution log storage (community edition)

### ISSUE THREAD

**Issue by EugenMayer** [rundeck/rundeck#7490]
**Describe the bug**
It seems to be impossible to configure the community edition for aws s3 storage via ENV vars via docker.

I tried this variants here:

```
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_NAME: "org.rundeck.amazon-s3"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_BUCKET: "rundeck-k8s"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_REGION: "eu-central-1"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_ACCESSKEY: "${s3_access_key}"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_SECRETKEY: "${s3_access_secret}"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_PATHSTYLE: "false"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_PATH: "logs/$${job.project}/logs/$${job.execid}.rdlog"
```
and 
```
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_NAME: "org.rundeck.amazon-s3"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_BUCKET: "rundeck-k8s"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_REGION: "eu-central-1"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_AWSACCESSKEYID: "${s3_access_key}"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_AWSSECRETKEY: "${s3_access_secret}"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_PATHSTYLE: "false"
    RUNDECK_PLUGIN_EXECUTIONFILESTORAGE_S3_PATH: "logs/$${job.project}/logs/$${job.execid}.rdlog"
```

Using this policy https://gist.github.com/EugenMayer/3b2c08a1643459f50e04895cfbaf95de

But when rundeck tries to store any logs, access is denied

```
com.amazonaws.services.s3.model.AmazonS3Exception: Access Denied (Service: Amazon S3; Status Code: 403; Error Code: AccessDenied
```

I'am using the community edition from https://github.com/rundeck-plugins/rundeck-s3-log-plugin/releases/download/v1.0.12/rundeck-s3-log-plugin-1.0.12.jar

**My Rundeck detail**

* Rundeck version: [ e.g. 3.4.10]
* install type: docker

* DB Type/version: pg

**To Reproduce**
1. Install [the plugin](https://github.com/rundeck-plugins/rundeck-s3-log-plugin/releases/download/v1.0.12/rundeck-s3-log-plugin-1.0.12.jar) in a community rundeck addition in the official community docker image
2. configure AWS access via ENV like describe in the bug
3. try to run any command and store a log

**Expected behavior**
Logs should be stored on s3

**Comment by MegaDrive68k** [comment]
Hi @EugenMayer!

Under Rundeck community, you have two alternatives: use the [AWS credentials](https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html) file like [this](https://github.com/rundeck/docker-zoo/tree/master/cloud) example. Or extend the image using Remco like [this](https://github.com/variacode/rundeck-docker-examples) example. 

Not sure if these options are valid in your use-case according to the IRC discussion.

Regards.

**Comment by EugenMayer** [comment]
It seems like since the pageduty acquiring the strategy change quiet a lot. 

I understand that you need selling points, fair enough. Paying is a good point for rundeck.

But there is a sensible line in what features to cut, and the current docker image is basically build to anoy the OSS users - by accident or by design (to force more sales). The image is basically kept is broken as needed just to sell some EE features like this one - i cannot explain myself this otherwise. Issues like #7487 are open for years (known for years), worked around for years. The configuration file monolyths are by no means easy to maintain to offer things like you just described (other then `sed` or `awk` hell).

I'am fine paying for software, fine paying for rundeck - but what i have seen the recent days is nothing that convinced me at all. 

Do not get me wrong - i'am a fan. So it is really hard to push me away from rundeck. But i must say, the current documentation and project status overall does a good job in doing so.

Of course, thank you for the insight in any case.
