### ISSUE TITLE
The process doesn't stop after all the steps are completed.

### ISSUE THREAD

**Issue by 8432konia** [rundeck/rundeck#7491]
**Describe the bug**
The daily batches that had been running normally suddenly did not stop even after all the steps were completed.

**My Rundeck detail**

* install type: rpm
* OS Name/version: CentOS7
* DB Type/version: mysql5.7

![スクリーンショット 2022-01-20 15 34 29](https://user-images.githubusercontent.com/43626580/150287138-45cda1b1-e9b0-415c-9c7c-34752f474d40.png)

**Comment by Alex-So** [comment]
@8432konia Please, specify, at least, the Rundeck version you're using. In other case nobody will be able to help you
