### ISSUE TITLE
With "framework.tmp.dir" variable unset, you can't use  "Script Node Execution"

### ISSUE THREAD

**Issue by jadjay** [rundeck/rundeck#7492]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
If framework.tmp.dir is unset, the execution of a "Script Node Execution" result in a Java NullPointerException

**My Rundeck detail**

* Rundeck version: 3.4.9
* install type: war
* OS Name/version: ubuntu 20.04
* DB Type/version: H2

**To Reproduce**

1. Remove (if exist) variable *framework.tmp.dir* from framework config file
2. Try to create a job with module Script Node Execution
3. Node could be local or remote
4. Try to execute a simple bash script with ```uname -a``` for example
5. You get a Java.lang.NullPointerException with very few informations about where the real problem is.

**Expected behavior**
Either an error message pointing the lack of configuration for framework.tmp.dir,
Either a default value for framework.tmp.dir (convention over configuration) e.g. : /tmp
Either a clear information about this workaround in the documentation

**Screenshots**

**Desktop (please complete the following information):**
*not relevant here*

**Additional context**
-

**Comment by MegaDrive68k** [comment]
Confirmed and reproduced following the  @jadjay steps. Thanks for your feedback!

**Comment by jadjay** [comment]
For info : Documentation is here  https://docs.rundeck.com/docs/administration/projects/node-execution/script.html

No mention of **framework.tmp.dir** is mandatory.
