### ISSUE TITLE
add field for a url to job creation page

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#75]
We are using our wiki to create runbook like pages for each job we create in rundeck. Would it be possible to add a field below the description field where we can add a url for the specific wiki page for each job? Once saved it would be great if the link could be active and if clicked open a separate browser window so someone looking at the job can also see the job's wiki page.

Thanks

Ed

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/273)

Original Creator: Ed

**Comment by ahonor** [comment]
Implemented as the "runbook" and mark deep.
