### ISSUE TITLE
JVM_MAX_RAM_FRACTION and JVM_MAX_RAM_PERCENTAGE are not in the same unit

### ISSUE THREAD

**Issue by ffe-enghouse** [rundeck/rundeck#7501]
**Describe the bug**

From the main README.md, we understand that
* `JVM_MAX_RAM_PERCENTAGE` is defined as an integer between `0` and `100` https://github.com/rundeck/rundeck/blob/578278f48d33fa380d1bb6d2cb9c28a4426a88ea/docker/official/README.md#L100
* `JVM_MAX_RAM_FRACTION` is defined as a float between `0` and `1` https://github.com/rundeck/rundeck/blob/578278f48d33fa380d1bb6d2cb9c28a4426a88ea/docker/official/README.md#L44

Moreover, by default, `JVM_MAX_PERCENTAGE` is set to `75`, unless if `JVM_MAX_RAM_FRACTION` is set:
https://github.com/rundeck/rundeck/blob/9d5c61581da74dc871c4bb06ee19f977c873729d/docker/official/lib/includes/100_defaults.sh#L7

But if I set `JVM_MAX_RAM_FRACTION` to `1`, I expect to have  `JVM_MAX_RAM_PERCENTAGE` set to `100`, but it is set to `1`.

So either modify:
* the README.md in order to tell that `JVM_MAX_RAM_FRACTION` is an integer between `0` and `100`,
* or modify 100_defaults.sh in order to x100 the `JVM_MAX_RAM_FRACTION` value before setting it to `JVM_MAX_RAM_PERCENTAGE`,
*  or remove `JVM_MAX_RAM_FRACTION` value in the README.md, keep only `JVM_MAX_RAM_PERCENTAGE`, and update the 100_defaults.sh (best option IMHO)

**My Rundeck detail**

* Rundeck version: 3.4.9
* install type: docker
* OS Name/version: ubuntu 20.04
* DB Type/version: postgres

**To Reproduce**
1. Set `JVM_MAX_RAM_FRACTION` to 1
2. Launch rundeck
3. get the launch command: `ps -ef` 
    You will obtain: `java -XX:MaxRAMPercentage=1 [...]`
4. Remove `JVM_MAX_RAM_FRACTION`
5. get the launch command: `ps -ef` 
    You will obtain: `java -XX:MaxRAMPercentage=75 [...]`

**Expected behavior**
If  I set  `JVM_MAX_RAM_FRACTION` to 1 I expect to have  `-XX:MaxRAMPercentage=100` in the java command line

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: fedora 32
 - Browser: Brave
 - Version:  1.33.106 Chromium: 96.0.4664.110 (Build officiel) (64 bits)

**Additional context**
N/A

**Comment by tjasko** [comment]
I just ran into this today as well.

Allowing the user to provide the `JVM_MAX_RAM_PERCENTAGE` environment variable & have it work properly shouldn't be a problem, as setting its value isn't possible right now anyways. 

However, if any users are taking advantage of the `JVM_MAX_RAM_FRACTION ` environment variable, and simply setting it to the percent of memory to limit the JVM by, correcting this issue would introduce a bug for those users. Perhaps the backwards compatible fix for this would be to detect if the inputted value is over `1`, and if so, treat it as a percentile (of course documenting the reason why).
