### ISSUE TITLE
Ad-hoc commands with the 'local' node-executor do not honor quotation marks

### ISSUE THREAD

**Issue by hfinucane** [rundeck/rundeck#7505]
**My Rundeck detail**

* Rundeck version: 3.4.10
* install type: docker
* OS Name/version: ubuntu 18.04
* DB Type/version: postgres

**To Reproduce**
1. Go to a project using the 'local' default node executor and go to the 'commands' tab
2. Select a node and run `echo 'hello & goodbye'`
3. Get an error like
```
hello
/bin/sh: goodbye: command not found
Result: 127
Failed: NonZeroResultCode: Result code was 127
Execution failed: 217807 in project ansible-dev: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [591ca4d75bf4: NonZeroResultCode: Result code was 127 + {dataContext=MultiDataContextImpl(map={ContextView(node:591ca4d75bf4)=BaseDataContext{{exec={exitCode=127}}}, ContextView(step:1, node:591ca4d75bf4)=BaseDataContext{{exec={exitCode=127}}}}, base=null)} ]}, Node failures: {591ca4d75bf4=[NonZeroResultCode: Result code was 127 + {dataContext=MultiDataContextImpl(map={ContextView(node:591ca4d75bf4)=BaseDataContext{{exec={exitCode=127}}}, ContextView(step:1, node:591ca4d75bf4)=BaseDataContext{{exec={exitCode=127}}}}, base=null)} ]}, status: failed]
```

**Expected behavior**
I expect to get the string "hello & goodbye" back

**Additional context**
Both single quotes and double quotes appear to be stripped. It is possible to work around this by doing your own escaping-
```
echo hello \& goodbye
```
and
```
echo 'hello \& goodbye'
```
work, but quotes are a more accessible way to do a large volume of escaping when necessary.

**Comment by MegaDrive68k** [comment]
Hi @hfinucane 

Following the [documentation](https://docs.rundeck.com/docs/manual/node-steps/builtin.html#quoting-arguments-to-steps) you can use: `"'hello & world'"` or `'''hello & world'''`.

<img width="927" alt="Screen Shot 2022-01-27 at 09 26 45" src="https://user-images.githubusercontent.com/51376003/151359088-8167df2a-a8db-4476-8110-9a56bcef5537.png">

Greetings.
