### ISSUE TITLE
Concurrent job executions in clustered environment

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#757]
Hello,
I am using Rundeck deployed as a webapp on 2 tomcat servers.
These servers are pointing to a MySQL database containing the Rundeck schema, hosted by a third server.
There is also a shared filesystem between the Tomcats, which contains the LOGSTORE of Rundeck (logs, etc...)
Why I am using a clustered Rundeck installation:
1- I need to have Rundeck available 24/7. In case of malfunction, I need Rundeck to remain available and the jobs to be executed without interruption.
2- In case a Tomcat server gets down, I need the Rundeck's jobs launched from the Tomcat1, to be resumed on Tomcat2 without interruption.

To accomplish that, I decided to install Rundeck the way I have described earlier.
The clustering part seems to work.
I have the same projects on both Tomcats and when I create a job on Rundeck1, it gets replicated on Rundeck2.
If I execute a job on Rundeck1, it can be monitored on both Rundeck instances.

My problem follows:
If I run a job from Rundeck1, it gets executed from both Rundeck instances simultaneously.
There is only 1 running job on each instance and the job ID is the same.

Here is a test I did:
I created a scheduled job on Rundeck1.
My job just do a remote command on 2 different servers.
The command is: "hostname && date >> /var/tmp/test_perriodique_1.txt"
The job got replicated on both Rundeck instances with the same UID.
The job gets executed on both instances without problem.

I expected the file "/var/tmp/test_perriodique_1.txt" to be filled with only 1 line for each job execution.
But each Rundeck instance is executing the job and so each Rundeck instance adds a line into the file.
So for each job execution, I get 2 lines into the file.

Could you advise me how to get my Rundeck clustered environment works as expected ?
I think I can't setup an active passive cluster because of my "condition 2" (see: Why am I using a clustered Rundeck install)

Note that I have setup my job with 1 maximum thread and I disallowed multiple executions; but the problem is still there.

I checked the documentation on how to setup a clustered environment and it was useful. But I can't find a lot of information for the problem I'm currently facing.

Last question: what is the best for a clustered environment ? running Rundeck as a Webapp on an application server or running Rundeck "Standalone" ?

Thanks for your help
Jérôme

**Comment by franctony** [comment]
Hi Jerome,

Could you please share the detailed documentation to achive Rundeck Cluster.

Thanks,
Antonye

**Comment by ahonor** [comment]
@jerome83136 Reopen if this is still a concern
