### ISSUE TITLE
Rundeck Winrm execution fails with a Latin letter in the body -> É, é (e-acute)

### ISSUE THREAD

**Issue by hs-hub-world** [rundeck/rundeck#7575]
We have been tracking this issue for a long time and we were finally able to narrow it down ;)

The issue, when WinRM Powershell returns a string in the output with a Latin Character (which is part of a normal AD User Name) Rundeck job fails.
Error message when using node step "Command":
![image](https://user-images.githubusercontent.com/20629911/157494916-61226ed6-d822-4ed5-abd0-e16035fec58c.png)

Error message when using node step "Script":
![image](https://user-images.githubusercontent.com/20629911/157504319-a312030f-a772-4924-9554-b47bb3ea5d56.png)

How to reproduce:
Set Project with WinRM Node Executor Python
Other configs do no matter (your choice is fine)
![image](https://user-images.githubusercontent.com/20629911/157501032-1f70fe6b-3276-4544-b405-8a0dbac7fbb7.png)

Add a job with "Script" node step with this settings
![image](https://user-images.githubusercontent.com/20629911/157501361-e2cb702d-e9f0-404b-b4b2-2555a1549cfa.png)

Place the sample "TestBody.txt" file in the C:\Temp director in the target windows machine.
and run the job, it will fail ;( 
See attached sample text file
[TestBody.txt](https://github.com/rundeck/rundeck/files/8216919/TestBody.txt)

Additional data. Here is the output from the Python Winrm, it seems Python winrm is returning some Asci code, not sure ...?
![image](https://user-images.githubusercontent.com/20629911/157502721-bd5f56ec-4cc5-48c6-8e12-d9577d870e82.png)

Rundeck info:
![image](https://user-images.githubusercontent.com/20629911/157503578-8ac8d74f-b9a0-4351-a9cc-a15e75ebac6d.png)

Plugin versions:
![image](https://user-images.githubusercontent.com/20629911/157503750-9bb86900-c8c5-43f4-bdbc-f3f09f5ebd3f.png)

Python version: 3.6.8
![image](https://user-images.githubusercontent.com/20629911/157505049-81ba0b31-ce13-4b39-a3c1-7b6f756d39cb.png)

Browser: Chrome

Thank you,
HS

**Comment by MegaDrive68k** [comment]
Hi @hs-hub-world 

Which version of pywinrm are you using? (you can see this with the `pip3 list` command), In my test environment, I'm using pywinrm 0.3.0 under Python 3.9.7, the plugin can retrieve the characters correctly:

![Screenshot_3](https://user-images.githubusercontent.com/51376003/157754114-6e50ebad-bacf-4f34-b4de-e5a04eb8a8ee.png)

Plugin version 2.0.15, Rundeck version 3.4.10.

As a tip, make sure to define the Python interpreter path on the Default Node Executor/File Copier project config.

Regards.

**Comment by mazzella-c** [comment]
We had the exact same issue as you on a RHEL 7/8 environment. The culprit was the stock Python version that was installed with yum (3.6.8) and this has nothing to see with the Pywinrm module.
We had no other choice but to compile Python from sources (3.10.2 right now) and use that one instead of the system one to solve this issue. However I don't know the root cause of this behavior, I can only say this has nothing to do with Rundeck.

**Comment by hs-hub-world** [comment]
Thank you @mazzella-c  and @MegaDrive68k . We upgraded our python to 3.8 which solved the issue. 
For some reason, Python 3.10 didn't work well with our Centos 7. the Pip module install would fail due to SSL Cert issue even after we followed all the instructions from this site: https://jhooq.com/pip-install-connection-error/
regardless, Python 3.8 does the job. Thanks a lot!
