### ISSUE TITLE
Problem with authenticating a user/group via LDAP

### ISSUE THREAD

**Issue by azet** [rundeck/rundeck#760]
I've set up rundeck with LDAP integration following this guide: https://github.com/rundeck/rundeck/wiki/Faq#i-get-an-error-logging-in-http-error-403--reason-role

our rundeck admin group is named `grp.gmi.adm.rundeck.admin`. this group is defined as the security-role. Login seems to work but we get an error although the user is a member of the group in question:

```
You have no authorized access to projects.
Contact your administrator. (User roles: [...] grp.gmi.adm.rundeck.admin, [...])
```

Changing the 'group' field  in `admin.aclpolicy` from 'admin' to the name of the mentioned group did not help either. I can not find proper documentation on how to finish this configuration step.

Thanks for your help.

**Comment by ssbarnea** [comment]
I am starting to wonder if there is anyone using AD//LDAP with RunDeck. While it was easy to setup user-authentication, it seems that the group memberships are not recognized at all. I used supplementalRoles to add "users,admin" but it seems that these are the only roles that are loaded and that their permissions are not loaded from `admin.aclpolicy` file.

**Comment by rendicott** [comment]
I was able to get this working. Put some notes up here: http://www.bitester.com/2015/12/ldap-authentication-with-rundeck.html
