### ISSUE TITLE
SCM export to Github fails after security changes

### ISSUE THREAD

**Issue by MrLemur** [rundeck/rundeck#7603]
**Describe the bug**

Since these [changes](https://github.blog/2021-09-01-improving-git-protocol-security-github/), doing an SCM export for a project results in this error: `ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type. Please see https://github.blog/2021-09-01-improving-git-protocol-security-github/ for more information.`

The SSH key being used is generated with this command: `ssh-keygen -t rsa -b 4096 -m PEM -C "test@example.com"`

Newer keys using `ed25519` are not supported by Rundeck.

**My Rundeck detail**

* Rundeck version: 3.4.10
* install type: RPM
* OS Name/version: Amazon Linux 2
* DB Type/version: MariaDB 5.5.68

**To Reproduce**
1. Set up a project to use SCM export to a Github repository with SSH key authentication
2. Enable the export
3. The error appears

**Expected behavior**
To export any local changes to the remote repository

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Browser Chrome
 - Version 100

**Comment by duiliofelix** [comment]
I had the same problem. I was able to do a workaround usind a ECDSA key wich both github and rundeck still supports

**Comment by paulcalabro** [comment]
Here's a relevant discussion on the topic as well as a possible fix:

https://groups.google.com/g/rundeck-discuss/c/an9OKLUfMD8
https://github.com/gradle/gradle/pull/20387
