### ISSUE TITLE
High CPU Usage even at First time startup

### ISSUE THREAD

**Issue by BhuviTheDataGuy** [rundeck/rundeck#7610]
Im using amazon Linux 2 OS with OpenJDK 8

After installing the Rundeck, I did `service rundeckd start`

Its consumes all of my CPU.
And then I installed MySQL, then did restart, this the more CPU and more startup time, even some times, the service never come up online.

**Comment by BhuviTheDataGuy** [comment]
Now I tried with Ubuntu 20.04, Same issue
total CPU core: 2

**Comment by paulcalabro** [comment]
Can you run the following commands and paste the results here?

- `lscpu`
- `free -h`
- `df -h`
- `iostat -m -c 2 5`
- `ps -eo pid,ppid,cmd,%mem,%cpu --sort=-%cpu | head`
