### ISSUE TITLE
Rundeck not sending the kerberos Authourization Header

### ISSUE THREAD

**Issue by atahir** [rundeck/rundeck#762]
Hi, 

I have configured a rundeck project that uses the rundeck winrm plugin and set the Authentication method to kerberos. 

I have also get the following JVM arguments

-Djava.security.krb5.realm=<my realm>
-Djava.security.krb5.kdc=<Domain Controller>

When I execute a job that uses the WinRM executor I am getting the following error 

(cut down version of the log output)

[Krb5LoginModule] user entered username: rundeck@BMGUK.GROUP
15:59:24  
15:59:24            principal is rundeck@BMGUK.GROUP
15:59:24            Commit Succeeded 

And Also....

com.xebialabs.overthere.cifs.winrm.WinRmRuntimeIOException: Unexpected HTTP response on http://MSIISDEVFREDA01.bmguk.group:5985/wsman:   (401)
....

When I inspect the HTTP Headers that are being sent to the remote node the 'Authorization' header is set to Basic ? 

I would have expected it to be set to Kerberos. 

Has anyone come across with the same issue. Is there a rundeck setting that I need to enable to force Kerberos Authentication?

Thanks for your help in Advance.
Anjam

**Comment by ahonor** [comment]
Reopen if this is still a concern
