### ISSUE TITLE
Stuck at Login Page

### ISSUE THREAD

**Issue by Kamalsaiperla** [rundeck/rundeck#7636]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: 4.0.1
* install type: rpm (yum upgrade rundeck)
* OS Name/version: CentOS Linux release 7.6.1810 (Core)
* DB Type/version: postgres

After upgrading to 4.0.1 from 3.4.0
The rundeck ui displaying  The requested URL /user/login was not found on this server.
Later some time login page is displaying
and after providing the login details it stuck at Login Page not redirecting to /menu/home 
When we enter https://x.x.x.x:4440/menu/home it's opening but from login page it's not redirecting

**rundeck-config.properties**

grails.serverURL=https://<server_name>

**framework.properties**

framework.server.name = localhost
framework.server.hostname = localhost
framework.server.port = 4440
framework.server.url = http://localhost:4440

Logs :
WARN  config.NavigableMap - Accessing config key '[filterNames]' through dot notation is deprecated, and it will be removed in a future release. Use 'config.getProperty(key, targetClass)' instead.
WARN  config.NavigableMap - Accessing config key '[filterNames]' through dot notation is deprecated, and it will be removed in a future release. Use 'config.getProperty(key, targetClass)' instead.
WARN  config.NavigableMap - Accessing config key 'chainMap' through dot notation is deprecated, and it will be removed in a future release. Use 'config.getProperty(key, targetClass)' instead.
INFO  rundeckapp.BootStrap - Starting Rundeck 4.0.1-20220404 (2022-04-05) ...
INFO  rundeckapp.BootStrap - using rdeck.base config property: /var/lib/rundeck
INFO  rundeckapp.BootStrap - loaded configuration: /etc/rundeck/framework.properties
WARN  framework.RundeckFilesystemProjectImporter - importing existing filesystem projects
INFO  rundeckapp.BootStrap - RSS feeds disabled
INFO  rundeckapp.BootStrap - Using jaas authentication
WARN  config.NavigableMap - Accessing config key 'chainMap' through dot notation is deprecated, and it will be removed in a future release. Use 'config.getProperty(key, targetClass)' instead.
INFO  rundeckapp.BootStrap - Preauthentication is disabled
INFO  rundeckapp.BootStrap - Rundeck is ACTIVE: executions can be run.
INFO  jaas.JettyCachingLdapLoginModule - Login attempts: 1, Hits: 0, Ratio: 0%.
DEBUG jaas.JettyCachingLdapLoginModule - Cache Miss for admin.
DEBUG jaas.JettyCachingLdapLoginModule - Searching for users with filter: '(&(objectClass={0})({1}={2}))' from base dn: ou=*,dc=*,dc=*
DEBUG jaas.JettyCachingLdapLoginModule - Found user?: false
DEBUG authentication.GrailsUsernamePasswordAuthenticationFilter - Set SecurityContextHolder to JaasAuthenticationToken [Principal=admin, Credentials=[PROTECTED], Authenticated=true, Details=WebAuthenticationDetails [RemoteIpAddress=127.0.0.1, SessionId=node01sdxsoubw96wb1fxpg9x6bpe5k9], Granted Authorities=[Jaas Authority [admin,admin], Jaas Authority [build,build], Jaas Authority [architect,architect], Jaas Authority [user,user], Jaas Authority [deploy,deploy]]]
INFO  rundeckapp.BootStrap - Rundeck startup finished in 3343ms
INFO  rundeckapp.Application - Started Application in 59.447 seconds (JVM running for 63.973)
Grails application running at http://localhost:4440 in environment: production

<img width="753" alt="Screenshot 2022-04-07 at 12 11 47 AM" src="https://user-images.githubusercontent.com/48655495/162048121-18ed7ed6-9e32-4838-b258-c4cd22968924.png">
<img width="442" alt="Screenshot 2022-04-07 at 12 17 07 AM" src="https://user-images.githubusercontent.com/48655495/162048156-e111b56c-3dea-45be-b1b2-05d1e5655494.png">

**Comment by ledufakademy** [comment]
we have the same issue with Active Directory authent. here , is there a fix ?

**Comment by fdevans** [comment]
It's likely due to the issue fixed by this PR. #7633  We will be released 4.1.0 soon which will include the fix.

**Comment by ledufakademy** [comment]
thank you fdevans.

**Comment by ledufakademy** [comment]
it's seem to be ok with last release, can be closed
Thank you to dev team ;-)
