### ISSUE TITLE
Question re: Plugins

### ISSUE THREAD

**Issue by paulcalabro** [rundeck/rundeck#7655]
Is there a particular reason why these plugins are managed separately?

https://github.com/rundeck/rundeck/blob/4ccce5f17ef47ff9055c7ddeb64c9ef6291d4725/build.gradle#L145-L159

https://github.com/rundeck/rundeck/blob/4ccce5f17ef47ff9055c7ddeb64c9ef6291d4725/build.yaml#L1-L10

I'm in the process of hardening the Docker image and I'm looking to remove **unused** plugins.
I want to make sure I don't remove something that's required by Rundeck.

**Comment by gschueler** [comment]
@paulcalabro the build.yaml file lists plugins that are in separate github repos, under the rundeck-plugins organization, so they are not in the rundeck/rundeck repo.

**Comment by gschueler** [comment]
Both sets are included in the bundled plugin contents in the final war

**Comment by paulcalabro** [comment]
Thanks, @gschueler. I appreciate it!
