### ISSUE TITLE
404 page when clicking on doc link in job options

### ISSUE THREAD

**Issue by mazzella-c** [rundeck/rundeck#7681]
**Describe the bug**

404 page when clicking on Rundeck User Guide - Option model provider when Remote URL is selected in Job Options allowed values

https://rundeck.org/docs/index.html/manual/job-options.html#option-model-provider

![404](https://user-images.githubusercontent.com/38751896/165902004-38b814bf-aa62-4019-829a-13d1dea74239.PNG)

**My Rundeck detail**

* Rundeck version: 4.1.0
* install type: war
* OS Name/version: RHEL 8
* DB Type/version: postgre

**To Reproduce**

Click on the link

**Expected behavior**

Remove _index.html_ from the url

**Comment by mazzella-c** [comment]
Hi @MegaDrive68k 

The link redirects to https://rundeck.org/docs/index.html/manual/job-options.html#option-model-provider in any case even with a new project and with different browsers and OS. Did you test with the war ?

**Comment by MegaDrive68k** [comment]
Hi @mazzella-c 

Yes, it's a fresh WAR instance. Is your Rundeck an upgraded instance or a new one?

Sorry for the late answer.

Regards.

**Comment by mazzella-c** [comment]
Yes, it's an upgraded version and I just realize I had this old setting in my rundeck-config.properties :

`rundeck.gui.helpLink=https://rundeck.org/docs/index.html`

Everything is OK when I remove the setting.
