### ISSUE TITLE
Ability to remove notification added to events for job

### ISSUE THREAD

**Issue by iyorozuya** [rundeck/rundeck#7697]
**Is your feature request related to a problem? Please describe.**
After notification is added to event such as "On Start", there is no option to remove that notification from event. 

**Describe the solution you'd like**
There should be a delete button with edit button on notification associated with the event of job

**Additional context**
![image](https://user-images.githubusercontent.com/26306108/167612397-f462b2a0-b0f6-4fa6-a011-065179dea366.png)

Thank you

**Comment by MegaDrive68k** [comment]
Hi @iyorozuya 

The action is available on the left button, take a look:

![Screen Shot 2022-05-10 at 13 02 07](https://user-images.githubusercontent.com/51376003/167683837-b34e5a82-068d-4a0b-a4da-4b98e9621f7b.png)

Greetings.

**Comment by iyorozuya** [comment]
Thanks @MegaDrive68k

**Comment by pBogey** [comment]
Hi, for what it's worth, that button is really hard to see, especially on dark mode.
