### ISSUE TITLE
Cannot login with Chrome

### ISSUE THREAD

**Issue by xavier8854** [rundeck/rundeck#7717]
**Describe the bug**
When using Chrome/Chromium, one cannot login

**My Rundeck detail**

* Rundeck version: 4.1.0
* install type: rpm
* OS Name/version: RHEL7
* DB Type/version: MariaDB

**To Reproduce**
1. Go to login page
2. Enter your (valid) ID
3. Click 'Log In'
4. See error : waiting undefinitely 

**Expected behavior**
Log to Rundeck

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 101
 -

**Comment by liberodark** [comment]
same issue for me on chrome or chromium
