### ISSUE TITLE
Create Project is not working

### ISSUE THREAD

**Issue by leafhe28110** [rundeck/rundeck#7810]
Note: Bug Reports not following this template may be closed without feedback._

 

**Getting Help**

Bug only

 

**Describe the bug**

i have set server.servlet.context-path=rundeck, in Projects dropdown list there has 2 button (View All , Create Project), when i click "Create project" rundeck URL is wrong which is **http://FQDN/resources/createProject** ,ideally the URL should be **http://FQDN/rundeck/resources/createProject**  (the context-path is missing now in the URL)

But when i click "New Project" button (in rundeck menu home page), the request direct to the correct URL: **http://FQDN/rundeck/resources/createProject**

 

**My Rundeck detail**

 

* Rundeck version: 4.40

* install type: war

* OS Name/version: windows

* DB Type/version: mysql

 

**To Reproduce**

1, Set rundeck server.servlet.context-path as rundeck

2. Login rundeck it will go to rundeck menu home page. After you login your rundeck URL is like **http://FQDN/rundeck/menu/home**

3. in the rundeck home page there is a **Projects** dropdown list, in this dropdown list click "Create Project"

4. After click "Create Project" rundeck will show the URL as **http://FQDN/resources/createProject**   (the context-path is missing now in the URL)

5, then you will see 404 request error(resource not found).

 

**Expected behavior**

i should go to "Create a new Project" page once i click "Create Project" in  **Projects** dropdown list.

 

**Screenshots**

 

**Desktop (please complete the following information):**

- OS: Windows

- Browser :chrome

- Version :101.0.4951.67

 

**Additional context**

i can go to "Create a new Project" page when i click "New Project" in rundeck menu home page. (the URL is correct which is http://FQDN/rundeck/resources/createProject)

**Comment by MegaDrive68k** [comment]
Hi @leafhe28110 

This was reported and reproduced [here](https://github.com/rundeck/rundeck/issues/7795).

Thanks!
