### ISSUE TITLE
 no jobs running but the running of system report is not zero

### ISSUE THREAD

**Issue by miaoningzheng** [rundeck/rundeck#7855]
**Describe the bug**
My all jobs is completed and stopped, but the running of System Report is not zero

**My Rundeck detail**

* Rundeck version: 4.4.0
* install type: docker
* OS Name/version: CentOS Linux release 7.9.2009 (Core)
* DB Type/version: mysql

**To Reproduce**
1. Modify the rundeck-config.properties file by template(`/etc/remco/templates/rundeck-config.properties`)
```
  dataSource.pooled=true
  dataSource.properties.removeAbandoned=true
  dataSource.properties.removeAbandonedTimeout=60
  dataSource.properties.testOnBorrow=true
  dataSource.properties.logAbandoned=true
  dataSource.properties.maxActive=1024
```
  And set RUNDECK_QUARTZ_THREADPOOL_THREADCOUNT=1024 by environment variable.
  Then startup the rundeck

2. Create 1000 test jobs:
  The command for all jobs is "pwd && sleep 240 && pwd", and the schedule for jobs is 0 1/10 * * * ? *

3. After about 2 hours, click the System Report button, you can find the warn `Quartz Scheduler thread usage is currently at 100%: 1,024/1,024 Threads in use. Job and Ad-hoc executions will be queued until previous executions complete.`. And if disable all schedule, after all jobs completed, the running of System Report will not be zero

**Expected behavior**
After all jobs completed, the running of System Report will be zero

ps: I'm not a native English speaker, if some description is not clear, please let me known

**Comment by MegaDrive68k** [comment]
Hi @miaoningzheng 

Tried to reproduce your issue unsuccessfully. Which value are you seeing in the system report? Could you try without those JDBC properties?

Regards.

**Comment by miaoningzheng** [comment]
> Hi @miaoningzheng
> 
> Tried to reproduce your issue unsuccessfully. Which value are you seeing in the system report? Could you try without those JDBC properties?
> 
> Regards.

@MegaDrive68k Thanks for your reply
`Which value are you seeing in the system report?`
![image](https://user-images.githubusercontent.com/49636432/185282294-631b8528-8e13-4f9c-8707-2914974e4e68.png)
The value in the red circule, Now i stop all jobs for a few jobs, so it becomes zero

`Could you try without those JDBC properties?`
I will try this.
