### ISSUE TITLE
Execute a local script

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#789]
Hello,
The embedded script Editor for inline scripts is a great feature.
It is useful to have the scripts stored on the same place and to be able to modify them from the Rundeck WebGui.

I need to have the same thing but for a locally executed script.
I need that script to be executed for all the target nodes but locally (on the rundeck instance and not on the remote nodes)
This is because my script is running locally and it will execute customized actions for each node, by grabbing node variables.

How can I write a script with the embedded editor and get it executed locally ?
Thanks for your help
Best regards
Jérôme

**Comment by schast** [comment]
Hi,

i need the same feature as jerome83136.
The Job shoud be executed on a node, not locally.

e.g.:
- step 1: execute script on node
- step 2: execute script locally
- step 3: execute script on node

**Comment by schast** [comment]
Hi @ahonor, is there any progress on this?
do you need further information?

**Comment by ahonor** [comment]
@schast I think we need a new step type. One that executes a script once for the Job (i.e., a Workflow Step).

**Comment by schast** [comment]
The script should not executes only once for the job.
I need a "Node Step Plugin" that executes a Local Script instead of a Local Command.
The local script should executes on any specified node. In the local script i use the node variables.
Currently the script must be stored locally and called as a local command.

**Comment by schast** [comment]
Hi @ahonor, is there any progress on this?

**Comment by schast** [comment]
Hi @gschueler , is there any progress on this?

**Comment by gschueler** [comment]
@schast have you tried creating a "WorkflowNodeStep" plugin to do this? plugins can define a property rendered as a text area, (and in 2.6.9 can support syntax highlighting as well). You could then execute that locally

**Comment by dimatkach** [comment]
Me too! I also need this feature. A script to be executed locally for each node

**Comment by ahonor** [comment]
@dimatkach Here's an example: https://github.com/ahonor/local-script-node-step
