### ISSUE TITLE
error : java.lang.OutOfMemoryError: unable to create new native thread

### ISSUE THREAD

**Issue by ananwishlor** [rundeck/rundeck#7893]
Found job work fail
and log : service of rundeck
with error _java.lang.OutOfMemoryError: unable to create new native thread_

FYI : node-execution : OpenSSH_7.4p1, OpenSSL 1.0.2k-fips
         Rundeck version : 3.2.2
         Backend database : mariadb 10.4.13
         OS : redhat 7.9
         CPU : 4 Core
         RAM : 20GB

![unable_to_create_new_native_thread](https://user-images.githubusercontent.com/112693692/188113174-6a2e8d60-7017-4f9f-8b3e-336f5a223db9.PNG)

![job_failed](https://user-images.githubusercontent.com/112693692/188113198-f12e57e8-3273-4356-95ec-f6451addf950.PNG)

**Comment by MegaDrive68k** [comment]
Issue opened here: https://groups.google.com/u/1/g/rundeck-discuss/c/gGT2NYpnvd0

[Related](https://github.com/rundeck/rundeck/issues/4111#issuecomment-608655350), please test with the latest version.
