### ISSUE TITLE
Running steps in parallel

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#79]
I have stuff that I'd like to do in parallel, but I'd also like to have the output tracked separately ... I run these tasks all on the same node.

In this case, the tasks are things like "Run these 20 commands to bring up new EC2 instances and let Chef auto-configure them" but that shouldn't really matter much.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/329)

Original Creator: Bruce Mitchener

**Comment by ahonor** [comment]
Can use Parallel strategy
