### ISSUE TITLE
Custom attributes cannot be used to define nodesets the same way tags are

### ISSUE THREAD

**Issue by MartinMiddleton** [rundeck/rundeck#790]
I want to be able to have a RunDeck job execute on a given nodeset based upon the value of a custom attribute. This works for tags. If I have multiple tags assigned to nodes I can select a specific tag and use that to define my nodeset. However, this doesn't work work for custom attributes. 

Below is a snippet of a resources.xml file that demonstrates the problem.

```
  <node name="alqa5-svr01" type="Node"
    description="Alert Q5A"
    hostname="alqa5-svr01"
    osArch="sparc" osFamily="unix" osName="SunOS" osVersion="5.10"
    username="releng"
    editUrl=""
    remoteUrl=""
    tags="ALERT,QA5,SVCS" 
    components="ALERTAPP,ALERTAVOX,ALERTCRON,ALERTDB,ALERTENV,ALERTEVNTFAN,ALERTGEN,ALERTLIB,ALERTJASPER,ALERTJDEPLOY,ALERTRPTING,AL
ERTWKFLON,GGBASE,GGALCFG,GGALRTNGCFG,GGCMICFG,GGCTMCFG,GGIQCFG,GGAOCFG"/>
  <node name="alqa5-wls01" type="Node"
    description="Alert Q5A"
    hostname="alqa5-wls01"
    osArch="sparc" osFamily="unix" osName="SunOS" osVersion="5.10"
    username="releng"
    editUrl=""
    remoteUrl=""
    tags="ALERT,QA5,WLS,PRIMARY" 
    components="ALERTAPP, ALERTENV, ALERTLIB, ALERTCRON" />
```

Let's say I have a custom attribute named "components". I want to be able to dispatch jobs based upon a single component. Currently, if I wish to select the host "alqa5-wls01", I have to enter the components as "ALERTAPP, ALERTENV, ALERTLIB, ALERTCRON". I want to be able to enter only one component, so that I can define the nodeset via components: ALERTAPP. This always returns 0 nodes. The only way to return a nodeset is by entering all the components as a string.

I suspect that currently a string comparison is being used as I can only find two ways to control the nodeset: 1) by entering .*; 2) by entering the complete string.

**Comment by ahonor** [comment]
Reopen if this is still a concern
