### ISSUE TITLE
`${execution.dateStarted}` and `${execution.dateEnded}` expand to inconsistent formats

### ISSUE THREAD

**Issue by erhhung** [rundeck/rundeck#7907]
In email notification templates, `${execution.dateStarted}` and `${execution.dateEnded}`, although both in the local time zone and documented at https://docs.rundeck.com/docs/developer/05-notification-plugins.html#execution-data to be `java.util.Date`, expand to inconsistent formats.

For example, using this snippet from my email template:
```html
<body>
  <table>
    <tr>
      <th>Job name:</th>
      <td>${job.name}</td>
    </tr>
    <tr>
      <th>Started at:</th>
      <td>${execution.dateStarted}</td>
    </tr>
    <tr>
      <th>Ended at:</th>
      <td>${execution.dateEnded}</td>
    </tr>
  </table>
</body>
```

I get the following message body:
```
Job name:	My Rundeck Job
Started at:	2022-09-14 00:20:00.040
Ended at:	Wed Sep 14 00:24:32 PDT 2022
```

I have also tried `${execution.dateStartedW3c}` and `${execution.dateEndedW3c}`, and they both expand to ISO 8601-formatted UTC dates, which is fine, but I'd like to see **dates formatted in a consistent, human-readable form and in my local time zone**.

**My Rundeck detail**

* Rundeck version: 4.4.0 2022-07-14
* install type: rpm
* OS Name/version: Amazon Linux 2
* DB Type/version: postgres

**Comment by MegaDrive68k** [comment]
Hi @erhhung 

Please update to the latest version, take a look at [this](https://github.com/rundeck/rundeck/pull/7805).

Regards!

**Comment by erhhung** [comment]
@MegaDrive68k Thanks for the tip. I've upgraded and can confirm that it does indeed fix the issue. Both dates now render like `${execution.dateStarted}`, e.g. `2022-09-14 00:20:00.040`.
