### ISSUE TITLE
When I run parallel jobs, some jobs stuck in "NOT STARTED" state indefinitely

### ISSUE THREAD

**Issue by ananwishlor** [rundeck/rundeck#7919]
When I exceute a parallel job There will be some jobs with "NOT STARTED" state.
Why does my job have a "NOT STARTED" state?

What does a job with "NOT STARTED" status mean?

**Screenshots**
![image](https://user-images.githubusercontent.com/112693692/191162949-b74d99d8-010a-4cda-b584-78c20c9d0270.png)
![image](https://user-images.githubusercontent.com/112693692/191162957-5eb8cb65-167d-471e-b1e4-5ef1b0908725.png)
![image](https://user-images.githubusercontent.com/112693692/191162812-62500f9b-a5b6-4b3a-a44b-90efad9387b2.png)

**Comment by MegaDrive68k** [comment]
Opened here: https://groups.google.com/u/1/g/rundeck-discuss/c/RTSXAwnvhus

Please test with the latest Rundeck version ([related](https://github.com/rundeck/rundeck/issues/7085#issuecomment-848081944)).
