### ISSUE TITLE
Kill a stuck process 

### ISSUE THREAD

**Issue by ananwishlor** [rundeck/rundeck#7921]
Please confirm for 
Can I kill a process that has been stuck for a long time?

FYI : node-execution : OpenSSH_7.4p1, OpenSSL 1.0.2k-fips
         Rundeck version : 3.2.2
         Backend database : mariadb 10.4.13
         OS : redhat 7.9
         CPU : 4 Core
         RAM : 20GB

**Comment by MegaDrive68k** [comment]
Issue opened here: https://groups.google.com/u/1/g/rundeck-discuss/c/Hzhuh3Q2zqM
