### ISSUE TITLE
gateway timeout issue

### ISSUE THREAD

**Issue by ananwishlor** [rundeck/rundeck#7922]
I have a gateway timeout issue on rundeck app gui web page.
In a project with 500+ jobs

What is the cause of such problems?

Can tuning be done to fix the problem?

If able to tune What should I do?

FYI : node-execution : OpenSSH_7.4p1, OpenSSL 1.0.2k-fips
        Rundeck version : 3.2.2
        Backend database : mariadb 10.4.13
        OS : redhat 7.9
        CPU : 4 Core
        RAM : 20GB

**Comment by MegaDrive68k** [comment]
Issue opened here: https://groups.google.com/u/1/g/rundeck-discuss/c/h8SXefL5JcI
