### ISSUE TITLE
Issue with Rundeck SCM Plugin since 4.6.x using SSH Key

### ISSUE THREAD

**Issue by iRemjeyX** [rundeck/rundeck#7923]
**Describe the bug**
SCM Plugin was working fine since 4.5. However, after upgrading Rundeck to 4.6.0, this ssh bug started to appear.

**My Rundeck detail**

* Rundeck version: 4.6.0
* install type: rpm (yum install)
* OS Name/version: Amazon Linux 2
* DB Type/version: MySQL 8.0.28

**To Reproduce**
1. Create SCM Export/Import Integration with the following settings:
{
  "config": {
    "branch": "project_branch",
    "dir": "/var/lib/rundeck/projects/project_name/ScmImport",
    "fetchAutomatically": "true",
    "filePattern": ".*\\.yaml",
    "format": "yaml",
    "gitPasswordPath": "",
    "importUuidBehavior": "preserve",
    "pathTemplate": "${job.group}${job.name}.${config.format}",
    "pullAutomatically": "true",
    "sshPrivateKeyPath": "INSERT_SSH_KEY.pem",
    "strictHostKeyChecking": "no",
    "url": "ssh://git@gitlab.domain.com/project_name.git",
    "useFilePattern": "true"
  }
}
2. Click "Enable", and you will get errors like:
Failed cloning the repository from ssh://git@gitlab.domain.com/project_name.git: ssh://git@gitlab.domain.com/project_name.git: remote hung up unexpectedly
Plugin was not enabled for SCM export: git-export: An error occurred: Failed cloning the repository from ssh://git@gitlab.domain.com/project_name.git: ssh://git@gitlab.domain.com/project_name.git remote hung up unexpectedly

**Expected behavior**
SCM Plugin working fine and dandy without any errors.

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: 104.0.2

**Additional context**
1. Using the git command locally works, but not via the Rundeck SCM Plugin.
2. /var/log/rundeck/service.log immediately outputs the following: [rundeck_plugin_debug.log](https://github.com/rundeck/rundeck/files/9617196/rundeck_plugin_debug.log), may be an SSH dependency issue?

**Comment by MegaDrive68k** [comment]
Hi @iRemjeyX 

It seems that you're facing [this](https://github.com/rundeck/rundeck/issues/7857), could you test [this](https://github.com/rundeck/rundeck/issues/7857#issuecomment-1218188932) solution?

Regards.

**Comment by iRemjeyX** [comment]
Hey @MegaDrive68k,

Thanks for the suggestion. 

That link gave me an idea.

I was using ssh-keygen with the default rsa settings, so that's why it failed. I switched to using an ed25519 key, and that worked perfectly.

```shell
ssh-keygen -t ed25519 -C "<comment>"
```
