### ISSUE TITLE
SQL Server JDBC driver included with Rundeck is very old and doesn't support SQL Server 2019

### ISSUE THREAD

**Issue by frachel** [rundeck/rundeck#7925]
**Is your feature request related to a problem? Please describe.**
We're having frequent random DB/Hibernate issues. Perhaps the SQL Server driver is a possible cause? We do know its very old and we're using a SQL Managed Instance in Azure which is going to be a very-latest DB engine.

**Describe the solution you'd like**
Currently version 6.4 of the SQL Server JDBC driver is included. The request is to include a newer version, with 7.4 being the minimum since that's where SQL Server 2019 support was introduced.

**Comment by MegaDrive68k** [comment]
Hi @frachel 

Did you try adding the latest driver at `/var/lib/rundeck/lib` directory like [this](https://stackoverflow.com/a/73818161/10426011) answer?

Regards!

**Comment by rafaelrodrigues3092** [comment]
@MegaDrive68k 

Does this approach still work? 
I am using containers, and added the drive to the path indicated but it seems it's still using v6.4

![image](https://github.com/rundeck/rundeck/assets/40042276/4c84281e-0a13-43df-9b3f-94d1142db1f9)


![image](https://github.com/rundeck/rundeck/assets/40042276/ee12612a-7eb6-4462-83fe-a17946d60787)


Thanks

**Comment by frachel** [comment]
In our container version we do the following which I beleive has been working for a while:
```
FROM rundeck/rundeck:4.9.0

USER root

RUN apt-get update && apt-get install -y --no-install-recommends \
  vim \
  curl \
  && rm -rf /var/lib/apt/lists/*

#Adding jdbc jars for the potential databases we use
RUN wget -O /home/rundeck/server/lib/sqljdbc.jar     https://repo1.maven.org/maven2/com/microsoft/sqlserver/mssql-jdbc/11.2.3.jre11/mssql-jdbc-11.2.3.jre11.jar  && \
    wget -O /home/rundeck/server/lib/postgresql.jar  https://repo1.maven.org/maven2/org/postgresql/postgresql/42.5.1/postgresql-42.5.1.jar
```

I think my original post was on a VM installation, but we've mostly moved to container since then.

**Comment by rafaelrodrigues3092** [comment]
> /home/rundeck/server/lib/sqljdbc.jar

Thanks a lot for this @frachel 
I believe I have an identical setup as you. Azure Managed Instance and Rundeck running in containers (Azure App Service).

My issue may have been the path where the jar was being dropped and potentially its name as well.

Will give it a shot! Thanks again!

**Comment by frachel** [comment]
I was out of the loop at work on this for a while, but it's come back to me.. It seems it was never working and always using the JDBC drivers included in the WAR, even though when we create an extended image we copy jdbc drivers to the /home/rundeck/server/lib/sqljdbc.jar directory as shown above.

If I hop inside the official Rundeck container, it basically runs "java -jar rundeck.war". Inside the WAR there are OLD jdbc drivers in "WEB-INF/lib/", and those jar files are in the "WEB-INF/classpath.idx".

I don't see if prepending the "/home/rundeck/server/lib" directory (outside the war) to the classpath anywhere.

So back to the original topic of the issue: In the Docker image, how do you replace/override the old JDBC driver that ship with Rundeck, since copying them to "/home/rundeck/server/lib" does not work.

**Comment by gschueler** [comment]
https://github.com/rundeck/rundeck/pull/8487
