### ISSUE TITLE
In RunDeck from the bash script file manual error trigger adds multiple rows under the activities tab

### ISSUE THREAD

**Issue by gogagubi** [rundeck/rundeck#8003]
Hi Guys,
I am using CURL and in case of success output=[0, "OK"]. In case of failure output=[1, "Some error message"]. For both scenarios, the HTTP Status code is 200. So now I want to trigger job failure if I have a failure response.
This is what my bash script looks like. Somehow it works but adds four records(failure records at the same time) in the activity tab. How can I prevent this behavior and add only one failure row instead of four? 

#!/bin/bash

set –e

URL="https://my_url"

MY_COMMAND="command_name"

RAW_DATA="[null,\"${MY_COMMAND}\",{}]"
echo "Raw Data ${RAW_DATA}"

RESULT=$(curl "$URL/${MY_COMMAND}" \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    -H 'User-Agent: my_user_agent' \
    --data-raw $RAW_DATA)
    
echo $RESULT

CODE=`echo $RESULT | head -n1 | cut -c2`
if [ $CODE != '0' ];
then
    exit 1
fi

<img width="1468" alt="image" src="https://user-images.githubusercontent.com/5641169/201109885-764796b4-b50d-4383-9554-386027dff9a3.png">

**Comment by MegaDrive68k** [comment]
Answered [here](https://stackoverflow.com/a/74391107/10426011). Thanks!
