### ISSUE TITLE
Rundeck 4.8 admin user can't create api tokens using a session cookie via the api anymore

### ISSUE THREAD

**Issue by arnaudvre** [rundeck/rundeck#8013]
In Rundeck versions before 4.8 the admin user can create api tokens via the api by first generating a session cookie using password authentication as detailed in the [documentation](https://docs.rundeck.com/docs/api/rundeck-api.html#token-authentication)

- Rundeck version: 4.8.0
- install type: deb
- OS Name/version: ubuntu 20.04
- DB Type/version: postgres

**Version 4.7 (successful)**

1. `curl -k -c rundeck.cookie -d j_username=admin -d j_password=adminpass https://rundeck-hostname1.net:4443  /j_security_check`
2. `curl -k -X POST -b rundeck.cookie -H "Content-Type: application/json" --data '{"user":"admin","roles":"admin","name":"admin-token"}' https://rundeck-hostname1.net:4443/api/41/tokens`

`<?xml version="1.0" encoding="UTF-8"?><token user="admin" token="DRUttAZ9z59GcFbVVxUWv1ctybNioP29" id="98035ee6-85eb-4c50-80d3-dc370bb02f92" creator="admin" name="admin-token"><expiration>2022-12-18 13:52:49.898 UTC</expiration><roles><role>admin</role></roles><expired>false</expired></token>`

**Version 4.8 (unsuccessful)**
1. `curl -k -c rundeck.cookie -d j_username=admin -d j_password=adminpass https://rundeck-hostname2.net:4443/j_security_check`
2. `curl -k -X POST -b rundeck.cookie -H "Content-Type: application/json" --data '{"user":"admin","roles":"admin","name":"admin-token"}' https://rundeck-hostname2.net:4443/api/41/tokens`

`{"error":true,"apiversion":41,"errorCode":"unauthorized","message":"(unauthenticated) is not authorized for: /api/41/tokens"}`

**Desktop:**

- OS: ubuntu 20.04
- Browser firefox version 102.0

**Additional information**

Pull system info on Rundeck 4.8 between step 1 and 2 above to confirm that interacting with the API using the session cookie otherwise works:

`curl -k -b rundeck.cookie -X GET https://rundeck-hostname2.net:4443/api/41/system/info`

`<system>
  <timestamp epoch='1668782358083' unit='ms'>
    <datetime>2022-11-18T14:39:18Z</datetime>
  </timestamp>
  <rundeck>
    <version>4.8.0.20221110</version>
    <build>4.8.0.20221110</build>
    <buildGit>v4.8.0-0-49731bb</buildGit>
    <node>rundeck-hostname2.net</node>
    <base>/var/lib/rundeck</base>
    <apiversion>41</apiversion>
    <serverUUID>f884576d-d6be-4752-ac03-ec8b95a0af4f</serverUUID>
  </rundeck>
  <executions active='true' executionMode='active' />
  <os>
    <arch>amd64</arch>
    <name>Linux</name>
    <version>5.4.0-131-generic</version>
  </os>
  <jvm>
    <name>OpenJDK 64-Bit Server VM</name>
    <vendor>Ubuntu</vendor>
    <version>11.0.16</version>
    <implementationVersion>11.0.16+8-post-Ubuntu-0ubuntu120.04</implementationVersion>
  </jvm>
  <stats>
    <uptime duration='1384365904' unit='ms'>
      <since epoch='1667397992179' unit='ms'>
        <datetime>2022-11-02T14:06:32Z</datetime>
      </since>
    </uptime>
    <cpu>
      <loadAverage unit='percent'>0.009889455730660393</loadAverage>
      <processors>8</processors>
    </cpu>
    <memory unit='byte'>
      <max>8589934592</max>
      <free>1473966256</free>
      <total>2629828608</total>
    </memory>
    <scheduler>
      <running>0</running>
      <threadPoolSize>10</threadPoolSize>
    </scheduler>
    <threads>
      <active>36</active>
    </threads>
  </stats>
  <metrics href='https://rundeck-hostname2.net:4443/api/41/metrics/metrics?pretty=true' contentType='application/json' />
  <threadDump href='https://rundeck-hostname2.net:4443/api/41/metrics/threads' contentType='text/plain' />
  <healthcheck href='https://rundeck-hostname2.net:4443/api/41/metrics/healthcheck' contentType='application/json' />
  <ping href='https://rundeck-hostname2.net:4443/api/41/metrics/ping' contentType='text/plain' />
</system>`

**Comment by gschueler** [comment]
This an affect of this change https://github.com/rundeck/rundeck/pull/7884

The session id will change after the first request after authentication (normally this happens in the browser when you are redirected to the home page). When using curl you would have to use `-b` and `-c` options to update the session cookie in your next request after authentication.  Alternately, you could add the `-L` option to the initial login POST, which will follow the redirect after login and update the cookie in the cookie jar. 

In testing, I can see the first API call after authentication succeed, but subsequent ones fail, unless I use `-L` in the initial request, or `-b` and `-c` in the second request.  After that, subsequent requests work as expected.
