### ISSUE TITLE
killling a remote job

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#802]
Hello,
I need the kill button to be able to kill a remote job execution.

For example: if I run a job with an inline script on a remote job, I would like to be able to kill it whenever I want.

I tried to setup the script-exec plugin ant to allocate a pseudo-tty but it doesn't kill the job actually.

I have setup the script-exec plugin like this:

ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" -o "LogLevel=quiet" -i path-to-keyfile ${node.username}@${node.hostname} ${exec.command}

What am I doing wrong ?

Thanks
Best regards
Jérôme

**Comment by ahonor** [comment]
√
