### ISSUE TITLE
[Rundeck / Job / Project]  Share common jobs among differents projects

### ISSUE THREAD

**Issue by katanafleet** [rundeck/rundeck#807]
We'd like to share common jobs between differents projects.

> To have a special project as a job library

Do you think it's possible to add a feature in order to call a job located in a project "LIB"  from a job located on another project "MYPROJECT" ?

**Comment by abohne** [comment]
We definitely are interested in this functionality.  Any idea where on the roadmap this falls?

**Comment by katanafleet** [comment]
Any news about that ?
