### ISSUE TITLE
rundeck-4.9.0.20230111-1 appears to be singed with wrong key

### ISSUE THREAD

**Issue by bclifford777** [rundeck/rundeck#8084]
**Describe the bug**
Latest rundeck rpm (rundeck-4.9.0.20230111-1) seems to be signed with the wrong key.

**My Rundeck detail**
* Rundeck version: [rundeck-4.9.0.20230111-1]
* install type: [rpm]
* OS Name/version: [RedHat Enterprise 8]
* DB Type/version: [postgres]

**To Reproduce**
rpm --import https://packages.rundeck.com/pagerduty/rundeck/gpgkey

Add repo file
[rundeck]
name=rundeck
baseurl=https://packages.rundeck.com/pagerduty/rundeck/rpm_any/rpm_any/x86_64
gpgcheck=1
enabled=1
gpgkey=https://packages.rundeck.com/pagerduty/rundeck/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
metadata_expire=300

dnf install rundeck
rundeck                                                                                                                                                                         1.1 kB/s | 1.8 kB     00:01    
Dependencies resolved.
Installing:
 rundeck                                         noarch                                         4.9.0.20230111-1              rundeck                                         242 M

Install  1 Package

Total size: 242 M
Installed size: 259 M
Is this ok [y/N]: y
Downloading Packages:                                                                                                                                      
rundeck                                                                                                                         5.0 kB/s | 3.9 kB     00:00    
GPG key at https://packages.rundeck.com/pagerduty/rundeck/gpgkey (0x7C5C34C0) is already installed
The GPG keys listed for the "rundeck" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.. Failing package is: rundeck-4.9.0.20230111-1.noarch
 GPG Keys are configured as: https://packages.rundeck.com/pagerduty/rundeck/gpgkey
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED

**Expected behavior**
rpm to be signed with the key noted for rundeck repository

**Additional context**
Having a look at previous releases we can see the key used to sign matches the one at  https://packages.rundeck.com/pagerduty/rundeck/gpgkey

**this is latest package**
We can see keyID d1d32028e5d5a125 which should be key ID f192529298c4c654

rpm -qpi rundeck-4.9.0.20230111-1.noarch.rpm
warning: rundeck-4.9.0.20230111-1.noarch.rpm: Header V4 RSA/SHA1 Signature, key ID e5d5a125: NOKEY
Name        : rundeck
Epoch       : 0
Version     : 4.9.0.20230111
Release     : 1
Architecture: noarch
Install Date: (not installed)
Group       : System
Size        : 271801680
License     : 
Signature   : RSA/SHA1, Wed 11 Jan 2023 20:03:15 UTC, Key ID d1d32028e5d5a125
Source RPM  : rundeck-4.9.0.20230111-1-src.rpm
Build Date  : Wed 11 Jan 2023 20:03:02 UTC
Build Host  : ip-172-28-91-249
Relocations : /var/lib/rundeck /etc/rundeck /usr/bin /var/log/rundeck /etc/rc.d/init.d 
Packager    : circleci
Vendor      : Rundeck, Inc.
URL         : http://rundeck.com
Summary     : Rundeck

**Previoius package**
rpm -qpi rundeck-4.8.0.20221110-1.noarch.rpm 
Name        : rundeck
Epoch       : 0
Version     : 4.8.0.20221110
Release     : 1
Architecture: noarch
Install Date: (not installed)
Group       : System
Size        : 264265730
License     : 
Signature   : RSA/SHA1, Thu 10 Nov 2022 18:31:09 UTC, Key ID f192529298c4c654
Source RPM  : rundeck-4.8.0.20221110-1-src.rpm
Build Date  : Thu 10 Nov 2022 18:30:56 UTC
Build Host  : ip-172-28-39-112
Relocations : /var/lib/rundeck /etc/rundeck /usr/bin /var/log/rundeck /etc/rc.d/init.d 
Packager    : circleci
Vendor      : Rundeck, Inc.
URL         : http://rundeck.com
Summary     : Rundeck

Package before 4.8
rpm -qpi rundeck-4.7.0.20221006-1.noarch.rpm 
Name        : rundeck
Epoch       : 0
Version     : 4.7.0.20221006
Release     : 1
Architecture: noarch
Install Date: (not installed)
Group       : System
Size        : 285536313
License     : 
Signature   : RSA/SHA1, Thu 06 Oct 2022 23:44:13 UTC, Key ID f192529298c4c654
Source RPM  : rundeck-4.7.0.20221006-1-src.rpm
Build Date  : Thu 06 Oct 2022 23:43:59 UTC
Build Host  : ip-172-28-33-154
Relocations : /var/lib/rundeck /etc/rundeck /usr/bin /var/log/rundeck /etc/rc.d/init.d 
Packager    : circleci
Vendor      : Rundeck, Inc.
URL         : http://rundeck.com
Summary     : Rundeck

As you can see version 4.7 and 4.8 rpm's pass key validation.
4.9 uses a different key which is not available from the download location for use to validation package signing.

Thanks for any assistance here.

Regards
Brett

**Comment by gschueler** [comment]
Please try importing the updated signing key `rpm --import https://docs.rundeck.com/keys/BUILD-GPG-KEY-20230105.key`

**Comment by bclifford777** [comment]
worked like a charm.

key signature now validates.

thanks
Brett

**Comment by gschueler** [comment]
I've made a PR to update our docs to add the new key to the repo definition here: https://github.com/rundeck/docs/pull/1160
