### ISSUE TITLE
Jobs: no output on success

### ISSUE THREAD

**Issue by baskinsy** [rundeck/rundeck#8099]
**Describe the bug**
No output on successful jobs.

**My Rundeck detail**

* Rundeck version: 4.9.0
* install type: deb
* OS Name/version:  ubuntu 22.04
* DB Type/version: postgres

**To Reproduce**
1. Go to Jobs
2. Click on an existing job or create a simple new on (just one command like ls -l)
3. Execute the job to a node all some nodes
4. There is no output of the job although it returns success. If the same command is executed from "Commands" the output is there

**Expected behavior**
Output of the job should appear like on version 4.8.0

**Screenshots**
![Screenshot_20230118_172642](https://user-images.githubusercontent.com/1850894/213213350-93b3d64a-0fa5-4eaf-91a6-dfa83407c416.png)

**Desktop (please complete the following information):**
 - OS: Opensuse Tumbleweed
 - Browser: chrome
 - Version:  109

**Additional context**
Issue is appearing for all users on two different setups of rundeck using different OSes and browsers. Issue appeared after upgrading from 4.8.0 to 4.9.0.

**Comment by amengus87** [comment]
I'm encountering the same problem since Monday after upgrading from 4.8 to 4.9.
I've rollbacked to 4.8 for now.

**Comment by baskinsy** [comment]
Can confirm that downgrading to 4.8.0 solves the issue, so something is broken in 4.9.0.

**Comment by MegaDrive68k** [comment]
Hi folks!

I tried to reproduce this issue unsuccessfully.

![Screenshot_2023-01-20_10-02-57](https://user-images.githubusercontent.com/51376003/213701738-80eba26c-24cd-4117-ad7b-9862a4c84d11.png)

Do you use any "extra" config?  like Rundeck behind proxy server o something.

Regards!

**Comment by amengus87** [comment]
Hi @MegaDrive68k 👋

On my side to extra config. Rundeck is reachable without any proxy.
All scripts normally output results but on 4.9 there is no output at all :
![image](https://user-images.githubusercontent.com/100192717/213703035-8b375def-e159-49c5-90cf-a4076b8f17e5.png)

I'm using "scenarios" and not "commands" for running my scripts.

**Comment by baskinsy** [comment]
> Do you use any "extra" config, like Rundeck behind proxy server or something?

In my case, both installs are behind nginx with ssl termination where 4.8.0 works as expected. Pasting the nginx config if it helps.

```
server {

    server_name myrundeck.example.net;
    access_log  /var/log/nginx/rundeck.access.log;
    location / {

        proxy_pass http://localhost:4440/;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Host $host:$server_port;
        proxy_set_header X-Forwarded-Server $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header User-Agent $http_user_agent;
        proxy_read_timeout  90;
        proxy_redirect   http://localhost:4440 https://myrundeck.example.net;
    }

    listen [::]:443 ssl ipv6only=on; # managed by Certbot
    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/myrundeck.example.net/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/myrundeck.example.net/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = myrundeck.example.net) {
        return 301 https://$host$request_uri;
    } # managed by Certbot



    listen 80;
    listen [::]:80;

    server_name myrundeck.example.net;
    return 404; # managed by Certbot


}

```

**Comment by MegaDrive68k** [comment]
Hi Folks, 

Another question, do you use any "extra" or custom plugins in your Rundeck instance? (could you list/show your available plugins to take a look?).

Regards.

**Comment by amengus87** [comment]
Hi @MegaDrive68k 👋

Where do you show plugins?

On system configuration page there is no custom plugins available / enabled :
![image](https://user-images.githubusercontent.com/100192717/214242769-be649c4a-3c2d-4a5c-a86e-5f7530d5e902.png)

**Comment by baskinsy** [comment]
> Another question, do you use any "extra" or custom plugins in your Rundeck instance? (could you list/show your available plugins to take a look?).

Here is our plugin list installed now on both instances.

```
WinRM Node Executor Python | Node Executor | Author: © 2022, Pagerduty, Inc. | 2.1.0 
Ansible Ad-Hoc Node Executor | Node Executor | Author: David Kirstein | 3.2.2
SSH | Node Executor |   | 4.9.0-20230111 |  
Local | Node Executor |   | 4.9.0-20230111 |  
Script Execution | Node Executor | Author: Rundeck, Inc. | 4.9.0-20230111
openssh / executor | Node Executor | Author: © 2017, Rundeck, Inc. | 2.0.2
SSHJ-SSH | Node Executor | Author: Rundeck, Inc. | 0.1.3
Stub | Node Executor | Author: Rundeck, Inc. | 4.9.0-20230111
WinRM Python File Copier | File Copier | Author: © 2022, Pagerduty, Inc. | 2.1.0
Ansible File Copier | File Copier | Author: David Kirstein | 3.2.2
SCP | File Copier |   | 4.9.0-20230111 
Local | File Copier |   | 4.9.0-20230111
Script Execution | File Copier | Author: Rundeck, Inc. | 4.9.0-20230111
openssh / file-copier | File Copier | Author: © 2017, Rundeck, Inc. | 2.0.2
SSHJ-SCP | File Copier | Author: Rundeck, Inc. | 0.1.3
Stub | File Copier | Author: Rundeck, Inc. | 4.9.0-20230111
Ansible Playbook Inline Workflow Node Step | Workflow Node Step | Author: David Kirstein | 3.2.2
Ansible Playbook Workflow Node Step. | Workflow Node Step | Author: David Kirstein | 3.2.2
Copy File | Workflow Node Step | Author: Rundeck, Inc. | 4.9.0-20230111
Local Command | Workflow Node Step | Author: Rundeck, Inc. | 4.9.0-20230111
Data Node Step | Workflow Node Step | Author: Rundeck, Inc. | 4.9.0-20230111
WinRM Check Step | Workflow Step | Author: © 2022, Pagerduty, Inc. | 2.1.0
Ansible Module | Workflow Step | Author: David Kirstein | 3.2.2
Ansible Playbook Inline | Workflow Step | Author: David Kirstein | 3.2.2
Ansible Playbook | Workflow Step | Author: David Kirstein | 3.2.2
Global Variable | Workflow Step | Author: Rundeck, Inc. | 4.9.0-20230111
Flow Control | Workflow Step | Author: Rundeck, Inc. | 4.9.0-20230111
Job State Conditional | Workflow Step | Author: Rundeck, Inc. | 4.9.0-20230111
Log Data Step | Workflow Step | Author: Rundeck, Inc. | 4.9.0-20230111
Refresh Project Nodes | Workflow Step | Author: Rundeck, Inc. | 4.9.0-20230111
Data Step | Workflow Step | Author: Rundeck, Inc. | 4.9.0-20230111
AWS S3 remote model source | Resource Model Source | Author: Rundeck, Inc. | 1.0.7
Ansible Resource Model Source | Resource Model Source | Author: David Kirstein | 3.2.2
Directory | Resource Model Source |   | 4.9.0-20230111
File | Resource Model Source |   | 4.9.0-20230111
Local | Resource Model Source |   | 4.9.0-20230111
Script | Resource Model Source |   | 4.9.0-20230111
Stub | Resource Model Source | Author: Rundeck, Inc. | 4.9.0-20230111
URL Source | Resource Model Source |   | 4.9.0-20230111
Attribute Match | Node Enhancer | Author: Greg Schueler | 0.1.5
Icon | Node Enhancer | Author: Greg Schueler | 0.1.5
Resource JSON | Resource Format Parser |   | 4.9.0-20230111
Resource XML | Resource Format Parser |   | 4.9.0-20230111
Resource YAML | Resource Format Parser |   | 4.9.0-20230111
Resource JSON | Resource Format Generator |   | 4.9.0-20230111
Resource XML | Resource Format Generator |   | 4.9.0-20230111
Resource YAML | Resource Format Generator |   | 4.9.0-20230111
Max Percentage | Orchestrator | Author: Rundeck, Inc. | 4.9.0-20230111
Rank Tiered | Orchestrator | Author: Rundeck, Inc. | 4.9.0-20230111
Random Subset | Orchestrator | Author: Rundeck, Inc. | 4.9.0-20230111
Send Email | Notification |   | 4.9.0-20230111
Send Webhook | Notification |   | 4.9.0-20230111
Tree Storage | Execution File Storage |   | 4.9.0-20230111
Azure Object Storage | Storage | Author: Rundeck, Inc. | 4.9.0-20230111
DB Storage | Storage |   | 4.9.0-20230111
Filesystem Storage | Storage |   | 4.9.0-20230111
Object Storage | Storage | Author: Rundeck, Inc. | 4.9.0-20230111
Jasypt Encryption | Storage Converter | Author: Rundeck, Inc. | 4.9.0-20230111
Git Export | Scm Export | Author: Rundeck, Inc. | 4.9.0-20230111
Git Import | Scm Import | Author: Rundeck, Inc. | 4.9.0-20230111
Temporary File | File Upload |   | 4.9.0-20230111
Highlight Output | Log Filter |   | 4.9.0-20230111
Key Value Data | Log Filter |   | 4.9.0-20230111
Multiline Regex Data Capture | Log Filter |   | 1.1.1-SNAPSHOT
Mask Log Output By Regex | Log Filter |   | 4.9.0-20230111
Mask Passwords | Log Filter |   | 4.9.0-20230111
Quiet Output | Log Filter |   | 4.9.0-20230111
Render Formatted Data | Log Filter |   | 4.9.0-20230111
HTML View Converter | Content Converter |   | 4.9.0-20230111
JSON Data Converter | Content Converter |   | 4.9.0-20230111
HTML Table View Converter | Content Converter |   | 4.9.0-20230111
Markdown View Converter | Content Converter |   | 4.9.0-20230111
Properties Data Converter | Content Converter |   | 4.9.0-20230111
Tabular Data Converter | Content Converter |   | 4.9.0-20230111
Execution Mode Later UI Plugin | UI |   | 4.9.0-20230111
Log Events | Webhook Event |   | 4.9.0-20230111
Run Job | Webhook Event |   | 4.9.0-20230111
Audit Logging Plugin | Audit Event Listener | Author: Rundeck, Inc. | 4.9.0-20230111
```

**Comment by MegaDrive68k** [comment]
Finally, I'm able to reproduce the issue.

It happens in this way:

1. Launch rundeck 4.9 (fresh install or upgrade from 4.8).
2. Configure an SSH remote node and dispatch some commands on that node (it works like a charm).
3. Go to Project Settings > Edit Configuration and click on the Default Node Executor tab, then change the SSH default node executor by SSHJ.
4. Go back to the Commands section and dispatch commands against the same remote node, you will see the "No Output message".
5. Go back to Edit Configuration and change the default node execution to SSH (default config).
6. Dispatching some commands against the remote nodes, the Issue persists discarding some problem with SSHJ or another node executor.

The workaround here is rolling back to Rundeck 4.8.

Thanks folks for your feedback! @baskinsy @amengus87

**Comment by amengus87** [comment]
Hello @MegaDrive68k 👋

On my side I use SSHJ because the default one can't connect to newest OpenSSH instances : https://github.com/rundeck/rundeck/issues/7815

**Comment by baskinsy** [comment]
Using SSHJ also on both instances.

**Comment by rlueckl** [comment]
Hi @MegaDrive68k,

this issue has been closed without any comments since January. There's also no PR linked to it. Is the issue fixed now, can we safely update? If yes, which version contains the fix?
