### ISSUE TITLE
Add supplementalRole feature to Jetty LDAP Module to workaround !role 403 error

### ISSUE THREAD

**Issue by jdmulloy** [rundeck/rundeck#810]
With Rundeck 2.0 and greater users are given an error "HTTP ERROR 403 Problem accessing /rundeck/. Reason: !role" if they are not assigned the role in web.xml, which by default is "user". There is an FAQ item that explains this here: https://github.com/rundeck/rundeck/wiki/FAQ#i-get-an-error-logging-in-http-error-403--reason-role. The workaround involves changing the required role from "user" to the name of an AD group. However since this requires all Rundeck users to be in the same AD group this workaround does not work for a lot of companies.

The PAM modules accept an option called "supplementalRoles", which allows the administrator to specify a comma separated list of roles to apply to each user. Adding this feature would fix the !role issue by allowing Rundeck to be configured to add all LDAP users to the "user" role. We can then use ACL Policies to control user permissions based on AD groups.

I have already implemented this code and compiled my own Rundeck binary and it works great. I've submitted pull request #803 to have the code merged into the development branch of Rundeck. I'm not quite sure what the procedure is for requesting that code be merged so I'm submitting this ticket.

**Comment by dpetzel** [comment]
Should this be closed via https://github.com/rundeck/rundeck/pull/803?
