### ISSUE TITLE
URL encode ${option.[name].value} in Cascading Remote Options

### ISSUE THREAD

**Issue by gmichels** [rundeck/rundeck#811]
Running Rundeck 1.5.3 and trying to use [Cascading Remote Options](http://rundeck.org/1.5.3/manual/job-options.html?utm_source=rundeckapp&utm_medium=app&utm_campaign=helplink&utm_content=editOpts/edit#option-model-provider).

I managed to get everything working as long as the parent section doesn't contain special characters such as a space.

For example, when calling the Remote URL for the populating the children for **My Test Group** with `http://server/info.php?group=${option.group.value}`, the variable `${option.group.value}` doesn't get url encoded so the spaces aren't converted to `%20`, thus the values don't get loaded.

![Imgur](http://i.imgur.com/Fx21uNm.png?1)

`${option.[name].value}` should be url encoded so the call is successful.

**Comment by vifrrg** [comment]
Is there a way to escape this behaviour since my option is a real path and should NOT be URL encoded?
