### ISSUE TITLE
"bash: del: command not found" with Inline script to Windows node

### ISSUE THREAD

**Issue by vincenthuynh** [rundeck/rundeck#812]
We're encountering this error when running an inline script to a node that is on Windows.

v2.1.1-1
Rundeck Server: CentOS
Node: Windows Server 2008 R3 (via Cygwin ssh)

[code]
bash: del: command not found
16:30:26            Remote command failed with exit status 127
16:30:26            Failed to remove remote file: C:/WINDOWS/TEMP/1401395423824-dev-eat2-cwjc1-dispatch-script.bat
[/code]

Related to this post: https://groups.google.com/forum/#!searchin/rundeck-discuss/bash$3A$20del$3A$20command$20not$20found/rundeck-discuss/0Ia1t76lLFI/9JYSDa9SCjwJ

**Comment by ahonor** [comment]
@vincenthuynh reopen if this is still a concern
