### ISSUE TITLE
AuthenticationFailure after upgrading Ubuntu node to 22.04

### ISSUE THREAD

**Issue by levisik** [rundeck/rundeck#8122]
My rundeck setup worked flawless on multiple nodes. Once I updated 3 nodes from Ubuntu 18.xx and 20.xx to the newest one 22.04 it is impossible to run any command via portal:
Failed: AuthenticationFailure: Authentication failure connecting to node: "My-host". Make sure your resource definitions and credentials are up to date.
When I try to log in on nodes using rundeck user via ssh from mgmt server (where rundeck is installed) it works good.

**My Rundeck detail**

* Rundeck version: [ e.g. 3.3.4]
* install type: deb,war
* OS Name/version: [e.g. ubuntu 20.04]
* DB Type/version: ??

**To Reproduce**

upgrade Ubuntu to the latest one on node.

**Expected behavior**

To work as before upgrade

I think some kind of authentication method changed in latest Ubuntu. But it is strange that via regular ssh it works good.

**Comment by levisik** [comment]
adding PubkeyAcceptedKeyTypes +ssh-rsa into nodes sshd_config files, reloading sshd solves issue

**Comment by Ragavendra-Vigneshwaran-R** [comment]
Thanks @levisik for uploading solution. Same problem occured in my rundeck, solved using you answer:)
