### ISSUE TITLE
 Login only Loading screen

### ISSUE THREAD

**Issue by BoBBer446** [rundeck/rundeck#8199]
i installed on ubuntu server 22.04:

    apt install ansible
    https://docs.docker.com/engine/install/ubuntu/
    https://docs.portainer.io/start/install/server/docker/linux
    git clone https://github.com/rundeck/docker-zoo.git
    sudo usermod -aG docker sysadm
    cd docker-zoo/postgres/
    sudo docker compose up
    
    sudo docker compose up -d

Install runs fine and i see login page:
http://192.168.81.110:4440/user/login

But Login with "admin" "admin" show no response:
![image](https://user-images.githubusercontent.com/10163536/225631305-996be7da-a840-444b-a4cf-9c52704b1c4e.png)

Chrome shows:
Refused to send form data to 'http://192.168.81.110:4440/j_security_check' because it violates the following Content Security Policy directive: "form-action 'self'".

I found this:
https://github.com/rundeck/rundeck/issues/4417

i try to edit:
go into container and edit:

    rundeck@6bb609e6fd9f:~/server/config$ rundeck@6bb609e6fd9f:~/server/config$ nano rundeck-config.properties

but after restart the config ist set back to default
Any idea to solve it?

Goal:
Run Ansible with rundeck to manage linux vms

**My Rundeck detail**

* Rundeck version: Community 4.11.0
* install type: docker
* ubuntu 22.04 Server
* DB Type/version:  postgres

**To Reproduce**
ubuntu server 22.04:

apt install ansible
    https://docs.docker.com/engine/install/ubuntu/
    https://docs.portainer.io/start/install/server/docker/linux
    git clone https://github.com/rundeck/docker-zoo.git
    sudo usermod -aG docker sysadm
    cd docker-zoo/postgres/
    sudo docker compose up
    
    sudo docker compose up -d

**Expected behavior**
Functional login 

**Additional context**
```
Chrome show CSP Error 
Content Security Policy of your site blocks some resources
Some resources are blocked because their origin is not listed in your site's Content Security Policy (CSP). Your site's CSP is allowlist-based, so resources must be listed in the allowlist in order to be accessed.
A site's Content Security Policy is set either via an HTTP header (recommended), or via a meta HTML tag.
To fix this issue do one of the following:
(Recommended) If you're using an allowlist for 'script-src', consider switching from an allowlist CSP to a strict CSP, because strict CSPs are more robust against XSS . See how to set a strict CSP .
Or carefully check that all of the blocked resources are trustworthy; if they are, include their sources in the CSP of your site. ⚠️Never add a source you don't trust to your site's CSP. If you don't trust the source, consider hosting resources on your own site instead.
1 Anweisung
Ressource	Status	Anweisung	Quellort
http://192.168.81.110:4440/j_security_check	blockiert	form-action	login:0
```

**Comment by w00dst0ck** [comment]
You can try to get it work with the following env's

          env:
            # URL
            - name: RUNDECK_GRAILS_URL
              value: https://<url>:<port>
            - name: RUNDECK_SERVER_FORWARDED
              value: "true"

Reference: https://docs.rundeck.com/docs/administration/configuration/docker.html#basic

**Comment by BoBBer446** [comment]
Worked for me! THX
