### ISSUE TITLE
Website "new-to-rundeck" shows a  404 

### ISSUE THREAD

**Issue by schonma** [rundeck/rundeck#8201]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
Page 

**My Rundeck detail**

* Rundeck version: [ e.g. 3.3.10]
* install type: [choose: rpm,deb,war,docker]
* OS Name/version: [e.g. ubuntu 20.04]
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ]

**To Reproduce**
1. Go to '...' https://www.rundeck.com/new-to-rundeck
See : https://docs.rundeck.com/docs/about/introduction.html 

**Expected behavior**
find a page describing the main concepts of rundeck

**Comment by MegaDrive68k** [comment]
Confirmed. Thanks @schonma!
