### ISSUE TITLE
LDAP  AUTH stop working in rundeck 4.11.0.20230313-1

### ISSUE THREAD

**Issue by moutzl** [rundeck/rundeck#8209]
**Describe the bug**
LDAP auth stopped working after upgrade to rundeck 4.11.0.20230313-1

**My Rundeck detail**

* Rundeck version: rundeck 4.11.0.20230313-1
* install type: deb
* OS Name/version: debian 11
* DB Type/version: mysql

**To Reproduce**
1. Try to login by your LDAP account
2. Login failure

**Expected behavior**
Login Success

**Desktop (please complete the following information):**
 - OS: archlinux
 - Browser: chrome
 - Version: 111.0.5563.64

**Additional context**
revert to rundeck 4.10.2.20230307-1 and all is working fine
unluckily, all  logs destroyed :(

**Comment by MegaDrive68k** [comment]
Hi @moutzl 

Could  you elaborate? Do you see any clue in the service log? 

Also, could you test with this parameter in your rundeckk ldap config: `rolePagination=“false”`.

Regards.

**Comment by moutzl** [comment]
Ill do at Monday, also with logs and rolePagination=“false”.

**Comment by moutzl** [comment]
sorry for delays.
rolePagination=“false”

is working solution.  closing ticket. 
Thank you all.
