### ISSUE TITLE
500 error on `menu/listExport` due to wrong content type which breaks SCM import plugin

### ISSUE THREAD

**Issue by kaplanben** [rundeck/rundeck#8213]
**Describe the bug**
Fresh Rundeck installation using SCM plugin to try and import jobs from Github.
After noticing that the plugin does not show any UI indication we saw the following error in `/var/log/rundeck/service.log`:
```
ERROR errors.GrailsExceptionResolver - NullPointerException occurred when processing request: [POST] /menu/listExport
```
This exception repeats each time the Jobs page is loaded/refreshed.
After a bit more digging with developer tools we see this is the request that is failing:
```
curl 'https://${RUNDECK_FQDN}/menu/listExport?project=${PROJECT_NAME}' \
  -H 'content-type: application/json; charset=UTF-8' \
  -H 'accept: application/json, text/javascript, */*; q=0.01' \
  -H 'authority: ${RUNDECK_FQDN}' \
  -H 'cookie: ********' \
  -H 'origin: ${RUNDECK_FQDN}' \
  -H 'x-rundeck-ajax: true' \
  --data-raw '[]'
```
which returns `{"error":"A server error occurred"}`.

When changing the content type from `json` to `xml` e.g. 
```
  -H 'content-type: application/xml; charset=UTF-8' \
  -H 'accept: application/xml, text/javascript, */*; q=0.01' \
```
The request succeeded with 200 and `{}` in response.

**My Rundeck detail**
* Rundeck version: THis confirm in `4.10.1.20230221-1` and `4.11.0.20230313-1`
* install type: deb
* OS Name/version: ubuntu 20.04
* DB Type/version: MySQL

**To Reproduce**
1. New empty installation
2. Configure the SCM plugin to import jobs
3. Go to the Jobs page
4. See the 500 error

**Expected behavior**
The request should succeed with 200 status (and the content type should match the supported one from the API).

**Screenshots**
- `Jobs_Page_Error.jpg` (attached below) shows the error from the browser dev tools.
- [rundeck_scm_bug_exception.log](https://github.com/rundeck/rundeck/files/11072653/rundeck_scm_bug_exception.log) is the full exception error

**Desktop (please complete the following information):**
 - OS: Mac, Linux, PC
 - Browser chrome, firefox, curl

**Additional context**
- We suspect that this affects the SCM plugin and that this is the reason there are no UI indications from the plugin and no way to import jobs from the UI.
- After uploading a job manually to the job page the SCM plugin works as expected but on the main jobs page the problem persists.

![Jobs_Page_Error](https://user-images.githubusercontent.com/77549469/227796612-ab219c9a-a1dd-408b-b257-fb162d8dc136.jpg)

**Comment by kaplanben** [comment]
Maybe this is not related to the SCM missing UI indication since we added an Nginx location block for `menu/listExport` to force the content type to be `application/xml` and with no errors on the client side the SCM issue still persists.

Regardless I think this is still a bug worth fixing.

**Comment by sansken** [comment]
also having this problem.  i am using the rundeck API to configure my SCM.  it seems related to the key storage.  if i edit the SCM config and select the exact same key in the UI that i set in my API parameters, the 500 error goes away.  

when i use my browser to inspect the request being sent on the SCM edit page after reselecting my key, I can see the original and new values do not differ:
```
"orig.gitPasswordPath": "keys/ourbotuser/rundeck_github_token",
"config.gitPasswordPath": "keys/ourbotuser/rundeck_github_token",
```

**Comment by kaplanben** [comment]
this was "solved" for us by setting (either of) `fetchAutomatically`|`pullAutomatically` to `false`.
Now the UI shows `sync needed` and we can manually trigger the `pull` and the import from the UI.
With this, we don't get the 500 error on `menu/listExport`.
🤦‍♂️
