### ISSUE TITLE
Add support for multiple schedule definitions  with option values support.

### ISSUE THREAD

**Issue by jlil** [rundeck/rundeck#828]
---Backstory---
The current implementation of Rundeck only allows one schedule per job with no support to pass option values for scheduled executions.

---Use case---
1. Let's assume that we have a multi-tenancy application.
2. We setup a rundeck job that takes the tenant name/id as a parameter and does some magic.

--Caveat---
I cannot schedule this job to run daily for tenant "ACME" and weekly for tenant "ACME2".

**Comment by gschueler** [comment]
Please vote for this on the roadmap if you want to see this feature: https://trello.com/c/WumO64lz

**Comment by majkinetor** [comment]
> it may be useful if schedules were independent of jobs. so you could define multiple schedules and options for the same job

I usually have funky cases in my corp like this - Run every hour from 8-16 then run in 17:30 and then once in 23:55. This thing would fit this workflow perfectly. I suggest `schedule` option to be array or object. If object, its a single schedule, if array, its multiple.
