### ISSUE TITLE
Disabling scheduling without loosing scheduling configuration

### ISSUE THREAD

**Issue by sylvainr** [rundeck/rundeck#830]
It would be great if one could disable the scheduling part of a job without lossing the scheduling configuration altogether.

Example:
1) I have a job which is scheduled according to a specific cron expression (which took some time to get right).
2) I decide I want to suspend the disabling of that job for a day or two.

Current situation: if you disable the scheduling, and want to re-enable it a few days after, you have to re-enter the hard cron expression you had in the first place.

Enhanced situation: you would just re-enable the scheduling and Rundeck would remember the initial cron expression.

Thanks a lot for the hard work!

**Comment by minhhahl** [comment]
I still can't find this feature in rundeck 2.5. When will it be released?

**Comment by gschueler** [comment]
@minhhahl this will be in 2.6, see https://github.com/rundeck/rundeck/pull/1377
