### ISSUE TITLE
Scripted Rundeck Backup - Feature Request

### ISSUE THREAD

**Issue by chriswynnyk** [rundeck/rundeck#832]
This is a feature request for a Rundeck backup utility.

Key features:
- Equivalent functionality to clicking _MyProject -> Configure -> Export Archive_ (generates myProject.rdproject.jar)
- Executed locally from the command line of the Rundeck installation
- Supports live backups (not necessary to shut down Rundeck first)
- (Nice to have) Option to back up logs and resources.xml files as well.

This can be done now with some web-automation magic; it would be nice to have this directly exposed as a command line utility.

**Comment by Whitepatrick** [comment]
Bump

**Comment by chriswynnyk** [comment]
Yup, this would still be helpful.  -Chris

**Comment by gschueler** [comment]
fyi: the archive export is available as an API call, but it is not yet available in the cli tools http://rundeck.org/docs/api/index.html#project-archive-export

**Comment by chriswynnyk** [comment]
Cool, that's sufficient.  Thanks!
