### ISSUE TITLE
Schedule jobs with Secure Remote Authentication

### ISSUE THREAD

**Issue by acommendador** [rundeck/rundeck#833]
We are currently trying to use Rundeck 2.1.2 and the rundeck-winrm-plugin to authenticate job executions via Kerberos, but have run into an issue while testing Rundeck's scheduling feature.  The job runs fine manually but a scheduled job fails with:

[overthere-winrm:<my host or ip>] Password was not set
Failed: ConfigurationFailure: Password was not set

Is scheduling a job using the rundeck-winrm-plugin with Kerberos authentication supported?  If so, can anyone provide me with the steps for setting this up?  If not, does Rundeck plan to support this feature in the near future?

Thanks,
Tony

**Comment by tomkregenbild** [comment]
Is there an update on this? not having a way to use the 'Secure Remote Authentication' in a scheduled is a very big limitation, can't you store an encrypted value of the password that will be provided for scheduled jobs with 'Secure Remote Authentication'?

**Comment by hsaryan** [comment]
We have figured out a workaround and it works great. I must warn you, you are gong to end up with triple duplicate jobs.   Here is how it works.

 #1. Create a Job with SecureRemote param call it  "Job-A"

 #2.  Create another Job (without any params) and call it "Job-A_Ref" in the workflow add a Step <Job Reference> and click on Choose a Job and select the "Job-A" from Step #1. And Save  Save Close.

 #3. Create another job (without any params) call it Job-A_CLi.  In the workflow add a step <Script> and enter cli command to execute Job from Step #2 enter "run -j Job-A_Ref -p <projectname>" without any quotes.

 Now, if you call the job from #3 from cli, it will call the Job #2 and then job #1 with SecureParam. 
We use this to call multiple jobs in parallel with securestring and it works great...

**Comment by hsaryan** [comment]
..(Continued).add <script> step and add this line
"run -j Job-A_Ref  -p <Project_Name>"   (without quotes)

And now you can call Job from Step-3 from anywhere including from command line and it will call Job from Step-2 and eventually it will execute job from Step #1 with secure param.

**Comment by golgoth777** [comment]
Unfortunately, i couldn't make this workaround working for me :

Error occurred while trying to authenticate to server: java.lang.RuntimeException: Unexpected error: java.security.InvalidAlgorithmParameterException: the trustAnchors parameter must be non-empty

Running 2.4.2-1

Anyone runs this succesfully ?

**Comment by tomkregenbild** [comment]
@hsaryan @golgoth777 It worked for me and this is really great. Still, this is a workaround and it should run properly in one job.

**Comment by gschueler** [comment]
Rundeck 2.6.2 now includes ability to use a key storage password as the default for a secure option

**Comment by golgoth777** [comment]
Not more issue from my side !
