### ISSUE TITLE
SCM plugin Enable error

### ISSUE THREAD

**Issue by charlescoupeau** [rundeck/rundeck#8338]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
Since the latest version 4.13.0 when active Project Seting ->Setup SCM -> Git Export an Error (log en attachment file).
When I retry :  Failed cloning the repository from git@URL_gitlab.git: remote hung up unexpectedly

**My Rundeck detail**

* Rundeck version: 4.13.0
* install type: rpm
* OS Name/version: CentOS 7.9
* DB Type/version: mysql 5.7

**To Reproduce**
1. Go to 'Setup SCM'
2. Click on 'Enable after Setup the GIT URL'

**Screenshots**
![rundeck-scm-4 1 13](https://github.com/rundeck/rundeck/assets/22742744/35f5425c-8185-429e-8eb5-01bae26d9b7d)

**Desktop (please complete the following information):**
 - Browser : Chrome
 - Version : 113

**Additional context**
I declared a new Rundeck user key that I declared in the deploy keys of the gitlab project. Without success
[rundeck-service-log-scm-4-13.txt](https://github.com/rundeck/rundeck/files/11544603/rundeck-service-log-scm-4-13.txt)

**Comment by charlescoupeau** [comment]
Hello, update 4.14 installed and same error.
In version 4.12 the SCM plugins work correctly.

![rundeck-4 14-scm-01](https://github.com/rundeck/rundeck/assets/22742744/c86ecc14-5511-450e-893b-47ae13396480)

![rundeck-4 14-list-installed-plugins](https://github.com/rundeck/rundeck/assets/22742744/9ed0ccf9-48c2-40c8-8c94-dbdad94f8865)

**Comment by bed1984** [comment]
Upgrade from version 4.12.0 to 4.14.1 and I got the same error with this plugin 

![image](https://github.com/rundeck/rundeck/assets/1033062/dd2b648f-df2e-435e-bc36-55fbf7944443)

Rollbacked to 4.12.0 and it works fine. I have tried to check any more information inside the logs but no success. I think it's a dependencies issue with the JGit plugin and the core Rundeck. My first error before restarting Rundeck was a ClassNotFound error.

**Comment by bed1984** [comment]
@charlescoupeau What's your JAVA version ? 

Mine is : 
$ java --version
openjdk 17.0.7 2023-04-18 LTS
OpenJDK Runtime Environment (Red_Hat-17.0.7.0.7-1.el8_7) (build 17.0.7+7-LTS)
OpenJDK 64-Bit Server VM (Red_Hat-17.0.7.0.7-1.el8_7) (build 17.0.7+7-LTS, mixed mode, sharing)

I'm a little bit concerned about this point on the documentation that's explain Rundeck supports JAVA8 and JAVA11 ( https://docs.rundeck.com/docs/administration/install/system-requirements.html )

**Comment by charlescoupeau** [comment]
@bed1984 

Mine is : 
java -version
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)

**Comment by niklassc7** [comment]
I had this error too. In my case, replacing the old SSH-key of type RSA with one of type ed25519 fixed it.

**Comment by bed1984** [comment]
I have generate ed25519 key with success but I have another error after upgrading to 14.1 ( same result at the end :) )

![image](https://github.com/rundeck/rundeck/assets/1033062/fc6217d4-854f-41b4-bf1e-7da35b6aa1ad)

I think the issue is not related to the key format.

**Comment by ipaqmaster** [comment]
Getting the same remote hung up unexpectedly experience against a new gitolite setup with a ed25519 key which works when used to `git clone` the repo url via the cli.

The git server shows: sshd[14648]: fatal: Timeout before authentication for rundeck.ip.goes.here port 43093 multiple times as rundeck attempts to enable SCM connecting up to 5 times before giving up.

Issue #7857 seems to be related.

**Comment by laryssasre** [comment]
> I have generate ed25519 key with success but I have another error after upgrading to 14.1 ( same result at the end :) )
> 
> ![image](https://user-images.githubusercontent.com/1033062/252863471-fc6217d4-854f-41b4-bf1e-7da35b6aa1ad.png)
> 
> I think the issue is not related to the key format.

Rundeck only allows ed25519 rsa keys, I was facing the same problem and managed to configure scm import/export generating a new key of this type and importing it into github.

Rundeck version 4.14.2.

**Comment by charlescoupeau** [comment]
Hello,

After the last update to 4.17.3, creating an **ed25519 key** and modifying the **Git URL** parameter by prefixing with ssh:// we encounter this error :
Failed cloning the repository from ssh://git@url- gitlab/project.git: Exception caught during execution of fetch command

**Comment by charlescoupeau** [comment]
Hello,
For us the solution was to create an ECDSA type key and specify it in SSH Key Storage Path from SCM Export.

**Comment by atomlab** [comment]
The same problem. SSH key format ed25519.
