### ISSUE TITLE
File Copier step that copies files to rundeck from remote nodes

### ISSUE THREAD

**Issue by ahonor** [rundeck/rundeck#835]
Enhance the file copier so it can copy files back to rundeck from remote nodes. The plugin should have a configuration property that defines the base directory where files are kept. This avoids users having to know the physical file system layout of the rundeck server and prevent clobbering runtime files.

**Comment by jfautley** [comment]
This would be very, very useful for our proposed use case. We have an inventory collector script that dumps it output into a file, which we need to retrieve from each remote node.

**Comment by ahonor** [comment]
@jfautley Thinking about your use case, one idea is to support appending to the local file.

**Comment by jfautley** [comment]
@ahonor In this instance it would be really useful if it was separate files from each node that the job ran on, but we're into semantics of specific use cases now I think :)

**Comment by puremourning** [comment]
I need this too. Is there any way this can be implemented in a plugin or via a script? Any tips would be appreciated. If not, happy to make a PR with a bit of guidance on how to go about this.

Currently, we can do this with an `scp` command via a `Local Command` node step, but this bypasses all of the stuff built in to the node config for credentials management.

Ultimately, I need a node step which executes locally and copies a file (actually a pattern, but that's a nice-to-have) from the node to a path. i.e. the exact reverse of the `Copy File` node step plugin.

**Comment by richiereynolds** [comment]
Yep, would be useful, +1.

**Comment by indigodp** [comment]
It will be very helpfull. There are many reasons to work with it.

**Comment by sterburg** [comment]
+1

**Comment by ulrith** [comment]
+1

**Comment by Kurisutian** [comment]
+1

**Comment by jadamt** [comment]
+1

**Comment by hewo** [comment]
+1

**Comment by isll** [comment]
+1

**Comment by hyuan** [comment]
Can consider to use `rsync` to do the job at the node, e.g.:
`rsync -avz user@source:/destination/path` /desthost/path/

**Comment by davalente** [comment]
+1
It would be nice that the FileCopier could deal with copying files between two remote servers.

**Comment by drbeka** [comment]
+1
We would really need this, any proceedings?

**Comment by sanjimenon** [comment]
+1

**Comment by sujitrect** [comment]
+1

**Comment by prakharbanga** [comment]
+1

**Comment by FrankVanDamme** [comment]
+1

**Comment by barthex** [comment]
+1

**Comment by verystrongjoe** [comment]
+1

**Comment by shadowhunter2009** [comment]
+1

**Comment by soar** [comment]
This feature will be great. Copy files between servers is very common task. I'm disappointed, why Rundeck can't copy files from remotes.

**Comment by dimatha** [comment]
+1

**Comment by xeon1400** [comment]
+1

**Comment by niall-munnelly** [comment]
+1

**Comment by zubbilo** [comment]
+1

**Comment by chukkso** [comment]
+1

**Comment by sergiovier** [comment]
.. useful to deploy things

**Comment by ZoeLeah** [comment]
+1

**Comment by mtreize** [comment]
I need that

**Comment by gschueler** [comment]
available as a step plugin since rundeck 2.0

**Comment by gaddman** [comment]
The builtin [Copy File](https://docs.rundeck.com/docs/manual/node-steps/builtin.html#copy-file-step) step appears to only copy _to_ the remote node, not _from_. @gschueler, do you mean the Enterprise [File Transfer](https://docs.rundeck.com/docs/manual/workflow-steps/file-transfer.html) step?
