### ISSUE TITLE
Option Secure Remote Authentication cannot be retrieved in Scheduled Job

### ISSUE THREAD

**Issue by EwyynTomato** [rundeck/rundeck#837]
**How to reproduce:**
1. Create a NodeExecutor plugin
2. Call context.getPrivateDataContext() to retrieve the option
3. Create a job 
4. Add an option with type: "Secure Remote Authentication"
5. Set to job as Scheduled job (crontab)

**Result:**
context.getPrivateDataContext() would return an empty map.

But, if the job is run by clicking "Run the job now", context.getPrivateDataContext() would return a map containing the option key&value.

edit:typo

**Comment by golgoth777** [comment]
+1 critical issue
