### ISSUE TITLE
windows ssh key location

### ISSUE THREAD

**Issue by monofuka** [rundeck/rundeck#839]
When filling in the form or by changing the location in the config file for the ssh key file will not work.  Rundeck is looking for "keys/" while Windows uses the back slash "\" as the folders would be listed as "keys\".  Used the launcher for install and tried for several hours to get it to read my ssh keys.  Ssh keys work as they are used for my winscp, putty, and ec2 connections.  Because of this I was unable to get anywhere with rundeck on windows.

**Comment by bygiro** [comment]
+1

**Comment by ahonor** [comment]
Reopen if this is still a concern
