### ISSUE TITLE
Display return code / filter by return code, colorize

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#84]
When performing an ad-hoc command, please make it possible to display the return code returned by the remote host. Furthermore, allow for me to pass an argument that will show me just the output from instances that either succeeded or failed (0 or non-zero return code), and consider colorizing the output such that non-zero return codes are obvious.  

Keep in mind that colorized output is problematic when run from cron, so dispatch should detect if it is being run from cron and suppress color output if there is no tty. A command-line flag to force colors on/off helps for cases where this detection fails.

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/351)

Original Creator: jhmartin

**Comment by dbeckham** [comment]
fwiw, I know this ticket is old, but it appears that the output of non-zero results are now colorized.

**Comment by ahonor** [comment]
Stderr is colorized and non-zero exits are highlighted.
