### ISSUE TITLE
Start and stop on windows

### ISSUE THREAD

**Issue by monofuka** [rundeck/rundeck#840]
Instructions for start and stop on Windows are not available.  I just relaunch from the launcher to start and stop by killing the process.

**Comment by ahonor** [comment]
See installation as a windows service http://rundeck.org/docs/administration/installation.html#install-the-launcher-as-a-service

**Comment by ShepTeck** [comment]
> See installation as a windows service http://rundeck.org/docs/administration/installation.html#install-the-launcher-as-a-service

this link is broken, is there a new one?
