### ISSUE TITLE
called when useCnt is already zero for

### ISSUE THREAD

**Issue by rdia9** [rundeck/rundeck#8446]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
repeating logs and SCM plugin finally disables
called when useCnt is already zero for

**My Rundeck detail**

* Rundeck version:  4.14.2
* install type:  Docker
* OS Name/version:Debian 11
* DB Type/version:mysql

**To Reproduce**
1. SCM Import git

**Expected behavior**
SCM git disables unexpectedly

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] chrome

**Comment by pob8888** [comment]
I am also seeing this on 4.13.0, although in my case, there doesn't seem to be any impact on the SCM integrations - I can commit, and pull the jobs from git fine via SCM.
From some googling around this error, it seems to come from the jgit library on which the rundeck plugin is based, and is mainly a debug message.  So perhaps this error is not related to your plugin disabling itself?

**Comment by rdia9** [comment]
Hi,
Thanks for your answer.
Effectively, after new investigations, the error is not related to the problem.
It seems it was an issue similar as https://github.com/rundeck/rundeck/issues/4399
