### ISSUE TITLE
RHEL 9 node failure

### ISSUE THREAD

**Issue by dforste** [rundeck/rundeck#8455]
**Describe the bug**
Red Hat Enterprise Linux 9 defaults to a crypto policy that is incompatible with jsch connections. 

**My Rundeck detail**

* Rundeck version: 4.14.0
* install type: docker
* OS Name/version: RHEL 7
* DB Type/version: postgres

**To Reproduce**
1. Define a RHEL 9 node to execute
2. See error
```Session.connect: java.io.IOException: End of IO Stream Read```

**Expected behavior**
Connect and execute step.

**Additional context**
SHA1 is deprecated by default and unavailable to sshd. 
https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9/html-single/considerations_in_adopting_rhel_9/index#ref_considerations-security-crypto_changes-to-security

To workaround from RHEL 9 side run: 
```
sudo update-crypto-policies --set legacy 
sudo systemctl restart sshd
```

**Comment by dd5154** [comment]
We are having this same issue

**Comment by dforste** [comment]
It looks like there is an updated fork that should work as a drop in replacement. https://github.com/mwiede/jsch

**Comment by gaddman** [comment]
@dforste have you tried using the SSHJ plugin? It's the default since 4.16.0: https://docs.rundeck.com/docs/history/4_x/version-4.16.0.html#sshj-default-node-executor-for-new-projects.

**Comment by MegaDrive68k** [comment]
Hi,

You have two options to manage this.

Option 1: follow [this](https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9) on your ssh server (scroll down and check the "I still want to install SHA-1 signed packages!" section).
Option 2: use SSHJ node executor.

Regards!
