### ISSUE TITLE
Bind to http port as early as possible

### ISSUE THREAD

**Issue by diwu1989** [rundeck/rundeck#846]
I have rundeck deployed on Heroku and when I add in the new relic agent, the server often does not start within the 60s dyno bootup limit.

Please make Rundeck bind to the http port as early as possible so that it is deployable on Heroku.

**Comment by diwu1989** [comment]
I'm using the launcher, but the installation part of the launcher isn't necessarily the problem. It's just that initializing rundeck takes a while.

**Comment by patcon** [comment]
Any update on this, re: rundeck working on heroku? Still using this setup, @diwu1989?

**Comment by gschueler** [comment]
rundeck is a webapp deployed into a servlet container: Jetty is the default embedded servlet container used for the launcher.  You can try deploying it to Tomcat, or another container if that would improve the startup time.  The launcher by default first expands the webapp contents then runs the Jetty container, so perhaps you can reduce the time by pre-expanding and configuring it and using the `--skipinstall` flag to the launcher.

**Comment by diwu1989** [comment]
We fixed this issue by deploying a wrapper nodejs proxy that binds early and then forwards to the port that rundeck uses.
