### ISSUE TITLE
Add gssapi-with-mic (kerberos) as an authentication method via the built-in SSH executor/copier

### ISSUE THREAD

**Issue by abohne** [rundeck/rundeck#847]
Currently, only private key and password authentication types are available.  gssapi-with-mic (kerberos) authentication should be added to the available authentication types for the built-in SSH executor/copier (jsch).

**Comment by ktosiek** [comment]
@abohne Have you found any solution? I've worked around this issue with https://github.com/rundeck-plugins/openssh-node-execution/issues/8

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
