### ISSUE TITLE
uuidOption not working in Rundeck api call

### ISSUE THREAD

**Issue by pcarvey** [rundeck/rundeck#8477]
**Describe the bug**

We use ansible to deploy our rundeck jobs. Currently we have to delete the job in order to deploy otherwise it complains that "a Job already exists with this UUID. Change the UUID or delete the other Job". I see  on https://docs.rundeck.com/docs/api/rundeck-api.html#importing-jobs there is an optional parameter uuidOption=remove to avoid this error but it doesn't seem to work ... does anyone have this working?

**My Rundeck detail**

* Rundeck version: 4.14.1

**To Reproduce**
curl -kSsv -H 'X-Rundeck-Auth-Token:' -F xmlBatch=@'./job.yaml' https://url/api/45/project/project-name/jobs/import?fileformat=yaml&dupeOption=update&uuidOption=remove

**Expected behavior**
Job is imported instead of the following error: Cannot create a Job with UUID xxxx-xxx-xxx-xxx-xxxxx: a Job already exists with this UUID. Change the UUID or delete the other Job.</error>

**Comment by MegaDrive68k** [comment]
Hi @pcarvey 

Could you test by using the following way?

```bash
#!/bin/sh

# protocol
protocol="http"

# basic rundeck info
rdeck_host="localhost"
rdeck_port="4440"
rdeck_api="45"
rdeck_token="your_rundeck_api_key"

# specific api call info
rdeck_project="ProjectEXAMPLE"
rdeck_yaml_file="HelloWorld.yaml"

# api call
curl -s --location --request POST "$protocol://$rdeck_host:$rdeck_port/api/$rdeck_api/project/$rdeck_project/jobs/import?fileformat=yaml&dupeOption=update&uuidOption=remove" \
  --header "Accept: application/json" \
  --header "X-Rundeck-Auth-Token: $rdeck_token" \
  -F xmlBatch=@"$rdeck_yaml_file"
```

**Comment by pcarvey** [comment]
Thanks @MegaDrive68k that works!
