### ISSUE TITLE
Bad date format in job's recent activity tab

### ISSUE THREAD

**Issue by sebastianopilla** [rundeck/rundeck#852]
I have installed Rundeck 2.1.3 as a WAR in Tomcat 7.0.54 and configured in WEB-INF/grails-app/i18n/messages.properties the following date format:

jobslist.date.format=yyyy-MM-dd HH:mm
jobslist.date.format.ko=yyyy-MM-dd HH:mm
jobslist.running.format.ko=HH:mm

This works fine when I browse to a job activity (rundeck/project/MyProject/activity), however when I click on the jobs link the date formats in the running, recent, failed and by you tabs are all displayed wrongly. It looks like some of the characters in the date format pattern aren't correctly recognized and that they're displayed as literals (plase see the attached image):

![rundeck-job-recent](https://cloud.githubusercontent.com/assets/1286189/3538959/58e0818a-0836-11e4-9b17-6109d25748ea.png)

**Comment by ssbarnea** [comment]
Have a look at https://github.com/rundeck/rundeck/issues/1682#issue-133928883

**Comment by gjvc** [comment]
In Rundeck 2.10.8-1 cafe mocha dodgerblue bell 2018-02-02 the date format in the job history is not in ISO8601 format -- it definitely should be.
