### ISSUE TITLE
Override option list by providing options in URL

### ISSUE THREAD

**Issue by srubik** [rundeck/rundeck#853]
Given a URL, it would be great to be able to populate some or all of the options in a Job. For example, given a job with 2 options, opt1 and opt2, I'd like to be able to populate them from a link similar to this:

https://myrundeckserver/project/myproject/job/show/21d9cea5-b1fb-4240-88a9-3ff095f0a45f?opt1=value1+opt2=value2

This would open up the Job with opt1 and opt2 populated with value1 and value2. In my use case, value1 and value2 can change so providing these as default options doesn't work for me. Providing these in the link allows someone to review the job prior to running it.

**Comment by ARentz07** [comment]
👍 , this is something we recently discovered we would... well, really want more than need. Auto-generating a link to a job that has some default values plugged-in, for instance, would reduce the chance for error in setting the options.

**Comment by ahonor** [comment]
+1

**Comment by csgyuricza** [comment]
+1

**Comment by variacode95** [comment]
@miguelantonio  Raised [merge request](https://github.com/rundeck/rundeck/pull/2084) against this ticket.

**Comment by schast** [comment]
+1

**Comment by danifr** [comment]
+1

**Comment by gschueler** [comment]
added in 2.7.0 release: https://github.com/rundeck/rundeck/pull/2209
