### ISSUE TITLE
Key Storage select buttons missing throughout rundeck after upgrade to 4.16.0

### ISSUE THREAD

**Issue by padraiglennon** [rundeck/rundeck#8537]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
After upgrading to v4.16.0 the select button for some key-storage fields are missing. There are a number of places they are missing as can be seen in the images below

**My Rundeck detail**

* Rundeck version: [ e.g. 3.3.10] 4.16.0
* install type: [choose: rpm,deb,war,docker] rpm
* OS Name/version: [e.g. ubuntu 20.04] RHEL 7.9
* DB Type/version: [choose: mysql, postgres, mssql, oracle, ... ] Postgres

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to a any project configuration UI. 
2. Click on Default Node Executor or Default File Copier tabs
3. See error with missing buttons

**Expected behavior**
The buttons should be present for any key-storage associated field

**Screenshots**
![image](https://github.com/rundeck/rundeck/assets/745557/6c2bfa1c-9736-480a-b46e-39aeafd17b60)
![image](https://github.com/rundeck/rundeck/assets/745557/48cdeae5-713e-464d-8956-30887fc9f1dc)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - Browser [e.g. chrome, safari] Chrome
 - Version [e.g. 22] 116.0.5845.141

**Additional context**

**Comment by MegaDrive68k** [comment]
Confirmed, thanks for your feedback @padraiglennon!

**Comment by MegaDrive68k** [comment]
Fixed on Rundeck 4.17.
