### ISSUE TITLE
Job form layout is broken with rundeck 4.16 if the description contains a very long string

### ISSUE THREAD

**Issue by FlorianJudith** [rundeck/rundeck#8565]
**Describe the bug**
I discovered this problem after updating to the last version. For my usage, I put a very long string in an option description, a series of values separated by ':' (value1:value2:...:value100). Until the last update, it wasn't a problem. Since updating to Rundeck 4.16.0, the jobs and job editing form are broken in Firefox as the page becomes too large to be fully seen, without the possibility to scroll horizontally to the end of the page. I have the same problem with Chrome.

**My Rundeck detail**

* Rundeck version: 4.16.0
* install type: docker
* OS Name/version: Centos 7
* DB Type/version: mysql

**To Reproduce**
1. Create a new job
2. Add an option with a description containing a very long string (EG : "Value1:Value2:Value3:Value4:Value5:Value6:Value7:Value8:Value9:Value10:Value11:Value12:Value13:Value14:Value15:Value16:Value17:Value18:Value19:Value20:Value21:Value22:Value23:Value24:Value25:Value26:Value27:Value28:Value29:Value30:Value31:Value32:Value33:Value34:Value35:Value36:Value37:Value38:Value39:Value40:Value41:Value42:Value43:Value44:Value45:Value46:Value47:Value48:Value49:Value50:Value51:Value52:Value53:Value54:Value55:Value56:Value57:Value58:Value59:Value60:Value61:Value62:Value63:Value64:Value65:Value66:Value67:Value68:Value69:Value70:Value71:Value72:Value73:Value74:Value75:Value76:Value77:Value78:Value79:Value80:Value81:Value82:Value83:Value84:Value85:Value86:Value87:Value88:Value89:Value90:Value91:Value92:Value93:Value94:Value95:Value96:Value97:Value98:Value99:Value100" )

**Expected behavior**
The string and the Job form are shown according to the width of the browser.

**Screenshots**
![Capture d’écran 2023-09-21 091212](https://github.com/rundeck/rundeck/assets/99026239/75c8d396-65fa-4d59-ad82-845723f7cef9)
![Capture d’écran 2023-09-21 091303](https://github.com/rundeck/rundeck/assets/99026239/fe5f8e4a-a344-4e54-8df7-bbadf46e851e)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Chrome 117.0 / Firefox 117.0

**Additional context**

**Comment by MegaDrive68k** [comment]
Confirmed, thanks for your feedback @FlorianJudith!

**Comment by rcmccarrick** [comment]
I have the same issue. I updated from 4.10 to 4.17. I then noticed the issue when I went to edit an existing job.
I put a lot of text in the description boxes to help the user enter data in the Rundeck jobs. 
Even after stretching my browser window across 2 24 inch monitors, I still cannot scroll over to the right far enough to edit some jobs.

**Comment by MegaDrive68k** [comment]
Hey Folks,

It seems fixed on 5.0.1.

Could you confirm in your environment?

4.16.0:

![Screenshot_2024-01-16_16-41-22](https://github.com/rundeck/rundeck/assets/51376003/669b6318-95c3-4c21-a7b0-ae447a2f8a6d)


5.0.1:

![Screenshot_2024-01-16_16-44-29](https://github.com/rundeck/rundeck/assets/51376003/ac8b160b-972a-4355-b0b7-b207801d18fe)

**Comment by FlorianJudith** [comment]
The last version seems to have solved the problem for me in the job execution window and in the job modification window.
![image](https://github.com/rundeck/rundeck/assets/99026239/6916f286-3e8a-4b48-aa14-e94c5adf25c4)
Thanks @MegaDrive68k !
