### ISSUE TITLE
**Getting Help**

### ISSUE THREAD

**Issue by jhernandez813** [rundeck/rundeck#8571]
Hi!!
I have set up Rundeck and have several active jobs. I have tried to configure Rundeck to notify me when a job is triggered by sending a message to my Google Chat channel, but I can't get it to work. I have used the option in the "Notifications" tab, selected "notification type: send webhook," and in the URL field, I have entered my Google Chat URL, but I'm not exactly sure about the format I need to use.
If you can help me, I would appreciate it. I have checked that integration with Slack is easier because there is a plugin, but I don't see that option for Google Chat. The text that I put in the URL field is the following.
![image](https://github.com/rundeck/rundeck/assets/125731638/b157fa5d-7caf-42a3-b197-7c5e1b082af4)
Thank you for your help, if this is not the right place, please forgive me once again.

**Comment by fdevans** [comment]
Since your key and token are in that sceenshot I'd cycle those and I will delete this conversation.
