### ISSUE TITLE
Can we upgrade to java 17 for Rundeck

### ISSUE THREAD

**Issue by bracken1022** [rundeck/rundeck#8590]
**Is your feature request related to a problem? Please describe.**
No, we just wander if we can use JDK17 for Rundeck

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by MegaDrive68k** [comment]
Hi @bracken1022, nope, check the requirements [here](https://docs.rundeck.com/docs/administration/install/system-requirements.html#system-requirements). Hope it helps!
