### ISSUE TITLE
what is the difference between  framework.server.url and grails.serverURL

### ISSUE THREAD

**Issue by Baozi2** [rundeck/rundeck#8619]
the grails.serverURL   and framework.server.url difference make me confusion？can you explain ? 
thank you

**Comment by Simon-cto** [comment]
framework.server.url is the URL to which the Rundeck server will respond locally.

grails.serverURL is the URL that Rundeck uses to build its link.

When you have a cluster of two nodes, you will have the following configuration:

node1:
framework.server.url: node1.mydomain.tld
grails.serverURL: rundeck.mydomain.tld

node2:
framework.server.url: node2.mydomain.tld
grails.serverURL: rundeck.mydomain.tld

**Comment by Baozi2** [comment]
Thank you for your reply.
If I use IP access, example: 192.168.200.125, which to set?  Is grails.serverURL?

**Comment by Simon-cto** [comment]
If you are using the community version of Rundeck, it means you're in a single node environment. So your framework.server.url and grails.serverURL should be the same value

**Comment by Baozi2** [comment]
got it thank you
