### ISSUE TITLE
upstart/init.d issue on ubuntu with 2.2.0

### ISSUE THREAD

**Issue by ljohnston** [rundeck/rundeck#863]
There's an issue with the current upstart/init.d combination on ubuntu. After an initial installation of the debian package, if the service gets started via /etc/init.d/rundeckd, then '/var/log/rundeck/service.log' gets created and owned by 'root'. That's fine as long as you then ~only~ start and stop the rundeck daemon via /etc/init.d/rundeckd. However, if you try and start the daemon via 'service rundeckd start', it ~seems~ as if the service starts, but it does not. Nor is there any indication in service.log as to why it failed because service.log can't be written to due to the fact that it's owned by root.

**Comment by gschueler** [comment]
I will close the issue. If you still have this problem, please re-open this issue.
