### ISSUE TITLE
/var/log/rundeck/service.log never rotated

### ISSUE THREAD

**Issue by cmclaughlin** [rundeck/rundeck#866]
Ideally the Debian package would drop a /etc/logrotate.d/rundeck config file upon installation.  To avoid stuff like this:

```
/var/log/rundeck # ls -lh
total 1.7G
-rw-rw-r-- 1 root adm 1.7G Jul 22 18:52 service.log
```

I found this dicussion on the topic:

http://rundeck.lighthouseapp.com/projects/59277/tickets/313-varlogrundeckservicelog-never-rotated

But don't see any mention of log rotation in the current codebase.

**Comment by ronabop** [comment]
Access logs get rotated, api logs, audit logs, options logs, jobs log executions logs... what makes service log special?

**Comment by diwu1989** [comment]
+1 it's unmaintenable if rundeck will spew logs forever

**Comment by diwu1989** [comment]
please drop something like
```
/var/log/rundeck/*.log {
	daily
	rotate 7
	compress
	delaycompress
	missingok
	notifempty
	create 644 root root
}
```
into `/etc/logrotate.d/rundeck`

**Comment by lancepowell** [comment]
+1 throw a default file in /etc/logrotate.d

**Comment by nilroy** [comment]
I dropped something like below in /etc/logrotate.d

```
/var/log/rundeck/service.log {
        daily
        missingok
        maxsize 100M
        rotate 5
        compress
        delaycompress
        notifempty
        create 664 rundeck adm
        sharedscripts
        postrotate
                status rundeckd | awk '{print $NF}' | xargs kill -USR1
        endscript
}
```
It rotates the log perfect. But The kill -USR1 command is restarting rundeckd. If I don't use the postrotate stuff rundeck never uses the new service.log created.

**Comment by penekk** [comment]
@nilroy have you tried using copytruncate?

**Comment by dserodio** [comment]
@nilroy Java apps (such as Rundeck) usually ignore UNIX signals like SIGHUP and SIGUSR1. `copytruncate` may work, I'll give it a try.

**Comment by ryancurrah** [comment]
Heres a snippet to remove all logs that end with a date after 7days....

```
/var/log/rundeck/*.????-??-?? {
        daily
        missingok
        compress
        rotate 1
        su rundeck rundeck
        prerotate
            find /var/log/rundeck -name '*.gz' -mtime +7 -delete
        endscript
}
```

**Comment by pchevallereau** [comment]
Hi,

Here, a fonctional logs rotation for .deb install using log4j and logrotate:

**log4j.properties modification:**
use "org.apache.log4j.RollingFileAppender" instead "org.apache.log4j.DailyRollingFileAppender"
and remove all lines containing "datePattern='.'yyyy-MM-dd"

**logrotate configuration**
```
/var/log/rundeck/rundeck*.log {
  copytruncate
  daily
  missingok
  rotate 7
  compress
  delaycompress
  notifempty
  create 640 rundeck adm
}

/var/log/rundeck/service.log {
  copytruncate
  daily
  missingok
  rotate 7
  compress
  delaycompress
  notifempty
  create 640 root adm
}
```

Then, you only need to purge all rundeck logs files and restart rundeckd
Enjoy it :)

**Comment by dirkniblick** [comment]
@pchevallereau, could you please specify exactly what you used for the log4j.properties configuration?

**Comment by pchevallereau** [comment]
Hi @dirkniblick,

I use the default log4j.properties :[]( https://github.com/rundeck/rundeck/blob/master/packaging/root/etc/rundeck/log4j.properties)

In this, you modify "org.apache.log4j.DailyRollingFileAppender" to "org.apache.log4j.RollingFileAppender"
And delete lines matched to log4j.appender.xxxxxx.datePattern='.'yyyy-MM-dd

After this stop all rundeck process, delete all rundeck logs files and set up the logrotate configuration, then start rundeckd.

Wait 24 hours and verify if it's works

**Comment by dirkniblick** [comment]
Okay, it seems I misunderstood your solution.  Is it not possible to rotate the service.log using only the log4j.properties configuration? @gschueler?  It seems silly to rotate every log file but that one.  (I also don't understand why that file has no date/time information.)

**Comment by dirkniblick** [comment]
I guess the service.log isn't managed by this component.  I've followed @pchevallereau 's advice and will manage the logs _for_ Rundeck.

**Comment by pchevallereau** [comment]
@dirkniblick. Personnaly i use logrotate tohave full control on rotating of all logs files

**Comment by gfoligna** [comment]
I have the same kind of issue with audit logs (really heavy). With default log4j config it rotates but I cannot seem to find a way to get it compressed and deleted after X days.
I've already tried changing `org.apache.log4j.DailyRollingFileAppender` with `org.apache.log4j.RollingFileAppender`. I even tried adding apache-log4j-extras to the classpath and use that configuration. No dice.

Running Rundeck 2.10.1 (Debian 9).

**Comment by pchevallereau** [comment]
@gfoligna uses the logrotated solution described above in the comments
