### ISSUE TITLE
Chrome 119.0.6045.123  Unable to login

### ISSUE THREAD

**Issue by maqingshan** [rundeck/rundeck#8681]
Describe the bug**
Chrome 119.0.6045.123  Unable to login.
Safari 17.1 is ok

**My Rundeck detail**

* Rundeck version: Rundeck4.17.22023-11-07
* install type: [choose: rpm]
* OS Name/version: [CentOS Linux release 7.8.2003 (Core)]
* DB Type/version: [[Development Mode] Usage of H2 database]

![image](https://github.com/rundeck/rundeck/assets/7401514/802ecafc-f85a-4b75-b57b-dd16ffbde5ce)

**Comment by maqingshan** [comment]
![image](https://github.com/rundeck/rundeck/assets/7401514/68cfc29a-4f95-4116-974e-1955ee86708e)

**Comment by MegaDrive68k** [comment]
Hi @maqingshan 

Take a look a [this](https://github.com/rundeck/rundeck/issues/7717) thread.
