### ISSUE TITLE
Restart is required when adding a new user or modifying a role

### ISSUE THREAD

**Issue by albertollamaso** [rundeck/rundeck#8694]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**

**My Rundeck detail**

* Rundeck version: 4.17.32023-11-14
* install type: rpm
* OS Name/version: 4.14.327-246.539.amzn2.x86_64
* DB Type/version: mysql

**To Reproduce**

1. Add a new user to the realm.properties file or in realm-w3.properties
2. Save file
3. Try to connect on the web page
4. The user can not login

**Expected behavior**
User is able to login without needing to restart the rundeck service

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos 14.1 (23B74)
 - Browser: Chrome 
 - Version 119.0.6045.159

**Comment by MegaDrive68k** [comment]
Hi @albertollamaso 

To do so you need to add the hot-reloadable capability on the realm.properties file. Take a look at [this](https://docs.rundeck.com/docs/administration/security/authentication.html#hot-reloading-the-realm-properties-file).

Regards.

**Comment by albertollamaso** [comment]
Hi @MegaDrive68k 
Thank you for your feedback. I have changed the settings but I am experience the same issue. Rundeck service is restarted everytime we add/remove/modify and user/role.

Is there any other information that I can share that can help ?.

Thanks !

**Comment by albertollamaso** [comment]
HI @MegaDrive68k
I was able to reproduce the behaviour. This is actually working. Thanks for your quickly responses.
