### ISSUE TITLE
Cron Feature enhancement and Requests

### ISSUE THREAD

**Issue by ghost** [rundeck/rundeck#871]
Would be really cool if the cron scheduler can be used with sudo options.
This would mean the Administrator would create all the wrapper scripts and job options , including setting up default user and password and the operations team making sure the job is run in every cron cycle.

Also would like to be able to export the duration for each job on serval nodes into an excel / cdv file.

Thanks,
Sunil

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
