### ISSUE TITLE
Feature request: give the ability to choose nodes, while using dynamic filters

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#877]
Hello,
On some jobs, I am using dynamic filters based on job options, for selecting target nodes.
It works just fine. When I launch the job, the filters are selecting the correct nodes by using the selected job options.

Would it be possible to add this feature:
While preparing the job execution (options selection, etc...); just before hitting the Run button, it would be usefull to see which nodes will be targeted.

For now when I run my job, in the nodes section, I see: 

"Nodes
Tags: ${option.APPLICATION}.${option.ENVIRONMENT}

The Node filters will be applied when the job is run."

I would like to see which nodes are selected by the dynamic filter and be able to select/unselect nodes before launching the job.

Thanks by advance
Jérôme

**Comment by wilprig** [comment]
Hello,

I think this feature would be really useful: I have a lot of jobs for which options define the node filter and in some job i would be much more confident knowing on which nodes it will be executed before hitting the run button

Thanks a lot!

**Comment by snebel29** [comment]
Yes, this apply also when some job fail and you want to re-run it... let's say you ran a job successfully on a huge list of nodes but one of the last just fail for some reason, you fix the problem but then you want to run your rundeck job again, "I'm assuming you stop job execution on any failure for safety" so at present you would have to do it again on the whole list, being able to pre-select that changes and you could just run it on the remaining nodes.

I think node filters with options is a common practice to run jobs over specific environments without being need to have multiple jobs with the exactly same code just changing the node filters with help on maintenance increase your reusability.

Thanks!

**Comment by MAS150MD200** [comment]
Any progress on this case? I think this feature would be very useful.

**Comment by ka4eli** [comment]
+1

**Comment by ahonor** [comment]
https://github.com/rundeck/rundeck/pull/2056

**Comment by darb21** [comment]
Are you sure that this should be closed by [#2056](https://github.com/rundeck/rundeck/pull/2056)...  I think OP was asking about "using dynamic filters based on job options " and being able to essentially see/change the list of target nodes that the dynamic filter is generating.  

I'm still seeing "The Node filters will be applied when the job is run" no matter what options I select in the job...

![screen shot 2017-11-29 at 2 42 33 pm](https://user-images.githubusercontent.com/16715072/33398376-60f79170-d514-11e7-8122-fd76d6378273.png)

**Comment by Neutrollized** [comment]
+1
I would like this to be reopened.  As it doesn't fix the issue filters based on options are applied before runtime so I'm unable to vet/select nodes I want.

**Comment by frozenmatt** [comment]
This would be huge for us, we currently have to have two jobs for each of our deployments.   One for dynamic nodes, and one named “targeted”.  Otherwise we can’t target one specific node to deploy to when we need to scale out clusters for capacity, outside of a update/new release deployment that would normally go to all nodes.

**Comment by Parece** [comment]
Has a decision been made on whether this enhancement will be included in a given future release?
