### ISSUE TITLE
Broken migration.sh script for 5.0.0 upgrade

### ISSUE THREAD

**Issue by s11fsch** [rundeck/rundeck#8772]
**Describe the bug**
Running the migration scribe throws the following error:

    ./migration.sh: 118: [: v2: unexpected operator

The problem is that the script is run with `/bin/sh` but bash syntax is used.

**My Rundeck detail**

* Rundeck version: 5.0.0
* install type: deb
* OS Name/version: Ubuntu 20.04.6 LTS \n \l
* DB Type/version: sqlite

**To Reproduce**
1. run `migration.sh` with default parameters

**Expected behavior**
Migrate the database

**Additional context**
Changing the first line in the script to `#!/bin/bash` fixes the bug.

**Comment by ahormazabal** [comment]
Thanks for the help! We have applied the fix at the migration script.
