### ISSUE TITLE
node.NodeStepPluginAdapter - Uncaught throwable executing node step

### ISSUE THREAD

**Issue by xavier8854** [rundeck/rundeck#8777]
**Describe the bug**
After upgrading to 5.0.0, a job won't run with this error :
```
node.NodeStepPluginAdapter - Uncaught throwable executing node step
groovy.lang.GroovyRuntimeException: Could not find matching constructor for: org.rundeck.plugin.scriptnodestep.ScriptFileNodeStepExecutor(null, Boolean, null, null, String, null, null)
```
Full stacktrace is attached,as well as the job who crashed

**My Rundeck detail**

* Rundeck version: 5.0.0
* install type: RPM
* OS Name/version: RHEL7
* DB Type/version: MySQL

**To Reproduce**
1. Upgrade from 4.17.3 to 5.0.0
2. See your scheduled or manually launched job fail

**Screenshots**
[stacktrace.txt](https://github.com/rundeck/rundeck/files/13741838/stacktrace.txt)
[Supervision_Instances_Rundeck.yaml.txt](https://github.com/rundeck/rundeck/files/13741865/Supervision_Instances_Rundeck.yaml.txt)

**Desktop (please complete the following information):**
 - OS: any
 - Browser any
 - Version any

**Comment by MegaDrive68k** [comment]
Let's follow this issue [here](https://github.com/rundeck/rundeck/issues/8896).
