### ISSUE TITLE
Security: Debian package /etc/rundeck permissions

### ISSUE THREAD

**Issue by JensRantil** [rundeck/rundeck#879]
The current Debian package allows write access to most files under `/etc/rundeck`. Specifically, this is a security issue because it allows `realm.properties` to be modified by Rundeck itself, which it shouldn't, right? If so, I suggest as many files as remove the write permission on files as they should be read-only.

**Comment by gaddman** [comment]
@JensRantil what files did you end up changing ownership for, and have you encountered any problems as a result? Although I'm using LDAP for authentication, the roles and ACL policies are stored in files owned by the `rundeck` user, so somebody could create a local job to modify these files and elevate themselves to admin. I know the ACL policies can be edited through the web interface, so it would break that capability, but is there anything else that might break?

A good solution to #1726 could help here, if the user for local execution (_Execute locally_) was something other than the `rundeck` user.

**Comment by gaddman** [comment]
@gschueler even if you're using LDAP/AD, with the current permissions you could edit `jaas-loginmodule.conf` to add support for local auth and create your own `realm.properties` or equivalent file. So you'd really need to lock down the directory permissions, not just the file permissions.
However, even then a user can still read `rundeck-config.properties` and get the storage password - so they could dump the database and decrypt the keystore to get all stored passwords.
Given these two issues, I can't see any way to securely allow local execution.

**Comment by gaddman** [comment]
This is still an issue in 3.3.10, although a possible workaround is to disable local execution.
