### ISSUE TITLE
Feature request: option based filter for jobs activity 

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#884]
Hello,
In the "Activity" panel, we can find all the jobs which are running, failed, done, etc...

It would be great if we could add filters that would be able to filter jobs by using job's options.

Example:

Lets say I have 1 job which I use to deploy applications: "deployJob"
I have used this job to deploy "application1" and "application2", by running "deployJob" 2 times.
In the job, there is an option named APPLICATION_NAME, which I have set to "application1" and "application2" depending on which application I have deployed.

I would like to filter by using the job name (deployJob) and by using the "APPLICATION_NAME" option (ex: APPLICATION_NAME=application1)

I hope my request is clear.

Thanks by advance

Jérôme

**Comment by awainer** [comment]
+1
That would be a nice feature.

**Comment by rvs-fluid-it** [comment]
+1

**Comment by rcheleguini** [comment]
+1
