### ISSUE TITLE
Feature request: Allow parent job to override child job filter when referencing 

### ISSUE THREAD

**Issue by jasonhensler** [rundeck/rundeck#886]
We would like to be able to override a jobs filter in the gui when referenced from another job. We would like this as we need to be able to still run a job with a filter but, run several jobs from a parent job using the parents filter. We can work around this by using a dynamic filter and passing argument but, this breaks being able to run a job by itself with a “default filter” (unless we add  an option to the job, which would make the filter redundant). We found another workaround by calling the command-line ‘run’ tool from a parent rundeck job and overriding the filter with the –F “hostname: ${node.hostname}“ option. It would seem like something that could be done since we can override it from the command line.

**Comment by rsack** [comment]
Has anyone tested this out? I seem to be encountering a similar issue where a job is invoked (via API) with a specific filter where only one node matches it, and a job referenced inside the invoked one runs "anywhere" without inheriting the filters.

**Comment by gschueler** [comment]
@rsack this feature allows you to set the filter used in the job ref inside the workflow definition.  It doesn't automatically inherit the parent job's filter, there may be another issue filed for that feature request
