### ISSUE TITLE
RPM packaging runs ssh-keygen and creates .ssh folder, Debian packaging does not

### ISSUE THREAD

**Issue by chadlung** [rundeck/rundeck#887]
In the history of the RPM packaging their was code added to create the .ssh folder as well as generate an initial key via ssh-keygen (historical links):
https://github.com/rundeck/rundeck/commit/d9b6a23087d3ff57ac225a841704cfe7a7893413#diff-0696b6f42c611469831f822e5b16f77e
https://github.com/rundeck/rundeck/commit/b2e0f02545aa2b50fc96ba8dc34d49274b06c1df#diff-0696b6f42c611469831f822e5b16f77e
https://github.com/rundeck/rundeck/commit/b2e0f02545aa2b50fc96ba8dc34d49274b06c1df
https://github.com/rundeck/rundeck/commit/9b3ff692eb4a87ac0dce0e19afeb28630caf12ee

Here the RPM packaging creates the .ssh folder, sets permissions and runs the ssh-keygen:
https://github.com/rundeck/rundeck/blob/d298d56ca205e4839268c749c3ff56f1153e340e/packaging/rundeck.spec#L34
https://github.com/rundeck/rundeck/blob/d298d56ca205e4839268c749c3ff56f1153e340e/packaging/rundeck.spec#L53

This does not happen in the Debian packaging scripts:
https://github.com/rundeck/rundeck/blob/8ab39e2a99f62c6151c6954d9d5e76afe707ea32/packaging/debroot/DEBIAN/postinst

**Comment by acasademont** [comment]
+1 i was running mad searching for it :p
