### ISSUE TITLE
Feature request: give the ability to "disable" a node

### ISSUE THREAD

**Issue by jerome83136** [rundeck/rundeck#888]
Hello,

Today, we had to shut a node down for maintenance purpose.

Unfortunately, the Rundeck jobs which were using that node did not work anymore because the node was offline. (I have selected to stop the job if a step fails)

It would be useful to be able to switch a node to "maintenance" mode. So that Rundeck knows it will not be available until the maintenance mode is disabled.

It would also be useful that Rundeck could check nodes and mark them offline if they become unavailable.
Or be able to switch a node into "maintenance" and/or "offline" mode; by calling the API.
My idea: if our supervision system detects a node down, it can call the Rundeck API to keep it aware from the situation.

I hope this will be useful.

Best regards
Jérôme

**Comment by jerome83136** [comment]
Hello,
I know that request is 2 years old; but we still love to use Rundeck and we still need an answer to that request :)

Short description: we sometimes have unavailable nodes (maintenance, issue, etc...) and we would like to be able to:
- disable a node at the node level so that it will not be selected to run any job (we are using dynamic filters in our jobs)
- detect a node failure so that it gets marked as unavailable and thus disabled (maybe a ping feature based on ICMP and/or http check and/or ssh connection test ?)

Do you think the latest version of Rundeck could be an answer to one of these requests (or both) ?

Thank you for your help

Best regards
Jérôme

**Comment by ambikads** [comment]
+1

**Comment by jerome83136** [comment]
Hi,
Any news on this request ? :)

Best regards
Jérôme

**Comment by acqant** [comment]
+1

**Comment by stevemsmith** [comment]
+1 
This would be really really great.  Is there even a concept of "disabling" a node in Rundeck?

**Comment by jerome83136** [comment]
Hi,
Thank you for your help
Will try it asap
But it seems node sélection based on health check will also soon arrive. It
will help me a lot :-)
Regards

**Comment by gschueler** [comment]
Node Enhancer feature allows a plugin that can dynamically add node attributes, this could be used
