### ISSUE TITLE
resource "rundeck_job" in the terraform gives the EOF error on 'terraform apply'

### ISSUE THREAD

**Issue by cynthiageorge** [rundeck/rundeck#8899]
Issue type: Bug report/Enhancement Request

**My Rundeck detail**

* Rundeck version: Rundeck 5.0.1
* install type: (rpm,deb,war,launcher?) : deb
* OS Name/version: ARCH : amd64
NAME : Linux
VERSION : 5.15.0-1046-gcp
* DB Type/version: mysql? postgres? h2?.. No DB used

**Expected Behavior**
On 'terraform apply' it shouldn't give EOF error so that it can store the resources to the statefile to track the same.
(Even though we see EOF error, Jobs are getting created in rundeck but its not added to the statefile)

**How to Reproduce**
Try running the 'Example Usage' code in the [documentation](https://registry.terraform.io/providers/rundeck/rundeck/latest/docs) using terraform commands. On 'terraform apply' you would see EOF error for the job resources alone.

**Comment by MegaDrive68k** [comment]
Hi @cynthiageorge 

Could you confirm if is [this](https://github.com/rundeck/rundeck/issues/8779) the same issue? 

Regards.

**Comment by cynthiageorge** [comment]
Yes looks like the same issue.

**Comment by MegaDrive68k** [comment]
Let's follow the issue there. 

Please add your use-case in that thread.

Thanks!
