### ISSUE TITLE
Include the authenticated group name of a Rundeck user in the job Activity View 

### ISSUE THREAD

**Issue by jefffiser** [rundeck/rundeck#890]
It would be super helpful to see the (ldap) group the user authenticated against (when logging in) next to (or as part of) the username column of the job Activity view.  This would help ensure the acl policies are working as expected.

**Comment by mprasil** [comment]
You can see the LDAP groups in the profile page of user. I beleive all (if there are more) are evaluated when applying acl policies until all fail or one with required access is found.

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.
