### ISSUE TITLE
RUNDECK - Bearer Token authentication for Remote URL option

### ISSUE THREAD

**Issue by georgemayrin** [rundeck/rundeck#8967]
Issue type: Bug report/Enhancement Request

I am using Remote URL option which reaches out to remote web server to retrieve needed data in json. The URL requires token authentication and I cannot find a way [rundeck docs option model provider](https://docs.rundeck.com/3.3.5/manual/job-options.html#option-model-provider) on how this can be provided. Since we log requests we do not want to add the token in the URL anywhere.

Is there any other way this can be achieved?
I also noticed the [configuration docs](https://docs.rundeck.com/docs/manual/job-options.html#configuration) in this page has a way of providing it but my UI does not have that. What is the difference between the two?
I tried adding a Secure Remote Authentication containing my token but that didnt do anything. I also referred to [rundeck-remote-url-option-to-https-with-basic-auth](https://stackoverflow.com/questions/74104602/rundeck-remote-url-option-to-https-with-basic-auth) and [basic-auth-with-remote-url-option](https://stackoverflow.com/questions/67436530/basic-auth-with-remote-url-option) but both are for basic auth and requires passing param in URL

* Rundeck version: 3.3.5
Thanks in advance

**Comment by MegaDrive68k** [comment]
Hi,

On the latest Rundeck version, you can use Bearer Token authentication for remote options. 

Regards.
