### ISSUE TITLE
Scheduled job staying in running state indefinitely

### ISSUE THREAD

**Issue by deviantony** [rundeck/rundeck#897]
Hey there,

I've got a scheduled job that is still in 'running' state after more than 12hours. Thing is, the process has been terminated in 2hours.

Here is the behavior I've spotted:

My process is starting and output some logs during 2 minutes, then it stop outputting logs for an hour approximatively and outputs new logs again till the end of the process.

It seems that rundeck loses the status/updates of the process in the scheduled job, so the new logs are not appended to the log output section in the rundeck UI.

I've seen that if my scheduled job output some logs constantly, it will be correctly displayed in rundeck and the job will also end correctly.

I'm using rundeck 2.1.3-1.

**Comment by gschueler** [comment]
fyi: a workaround may be to use the "ssh" command directly via a script node executor, as shown here http://rundeck.org/docs/plugins-user-guide/custom-command-and-script-execution-with-the-script-plugin.html

**Comment by minhuber** [comment]
fyi: in case of interested: the script-exec project.properties required for the workaround are listed here: https://groups.google.com/forum/#!msg/rundeck-discuss/6396DcT7sMo/DQSjA2CECQAJ
