### ISSUE TITLE
ClassNotFoundException

### ISSUE THREAD

**Issue by couckearthur** [rundeck/rundeck#8984]
**Describe the bug**

From reading the documentation it is not clear to me if the database options are limited or not. 

> Rundeck includes a JDBC driver for Mysql, MariaDB, Postgres, MSSQL and H2. If you are using another database or if you want to use an updated driver, copy the appropriate JDBC driver (e.g.,"ojdbc14.jar" for Oracle,or "aws-mysql-jdbc.jar" for Amazon Aurora) into the server lib dir

I want to test if it works with **IBM DB2**. I've copied the driver db2jcc4.jar into '/var/lib/rundeck/lib' and added the properties: 

`dataSource.url = jdbc:db2://svmfdb2a:446/DB2A:retrieveMessagesFromServerOnGetMessage=true;clientProgramName=RUNDECK;
dataSource.username = RUNDECK
dataSource.password = ******
dataSource.driverClassName = com.ibm.db2.jcc.DB2Driver
`

When starting we see in the service.log that the class is not found. However it certainly is in the jar (I check with decompiler) 

So I have the feeling that the jar is not picked up in the classpath. It looks like he is only loading the ones included in the WAR file and not the ones in '/var/lib/rundeck/lib'. 

- Is my attempt to link with IBM DB2 is a hopeless one that should be stopped immediately?
- If not, how can I debug this further/check if the jar is picked up? 

**My Rundeck detail**

* Rundeck version: rundeck-5.1.1.20240305-1.noarch.rpm 
* install type: rpm
* OS Name/version: Red Hat Enterprise Linux 9.2
* DB Type/version: IBM DB2 

**To Reproduce**
1. install rundeck-5.1.1.20240305-1.noarch.rpm 
2. add db2jcc4.jar to /var/lib/rundeck/lib
3. Try to load a class from the jar  
         - dataSource.driverClassName = com.ibm.db2.jcc.DB2Driver

**Expected behavior**
In service.log: java.lang.ClassNotFoundException: com.ibm.db2.jcc.DB2Driver

**Screenshots**
see attachment [service.log](https://github.com/rundeck/rundeck/files/14526484/service.log)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser chrome
 - Version 122

**Comment by MegaDrive68k** [comment]
Hi @couckearthur 

DB2 isn't supported by Rundeck, you can see the full list [here](https://docs.rundeck.com/docs/administration/configuration/database/).

Regards.

**Comment by couckearthur** [comment]
ok thank you. I was not entirely sure based on the docs.
