### ISSUE TITLE
options with URL for remote default value

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#90]
Add a new URL field for options, allowing the default value to be retrieved when it is not specified.

reference: https://github.com/dtolabs/rundeck/pull/41

Question: can this be incorporated/replaced by issue #358 ?

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/366)

Original Creator: Greg Schueler

**Comment by AndrewFarley** [comment]
+1 +1 +1 Need this feature, trying to rejuvenate this 4 year old ticket

**Comment by gschueler** [comment]
2.8.0 now supports a `selected: "true"` for remote option values https://github.com/rundeck/rundeck/issues/1189
