### ISSUE TITLE
Unable to delete job

### ISSUE THREAD

**Issue by agobezy** [rundeck/rundeck#9019]
**Describe the bug**
Trying to delete a job and getting a 500 error.

The error message is "could not execute statement; SQL [n/a]; constraint [FKdtqy2uar1ln372ne8u2jj27nw]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement"

**My Rundeck detail**

* Rundeck version: 5.1.1-20240305
* install type: rpm
* OS Name/version: Ubuntu Server 20.04
* DB Type/version: Postgres

**To Reproduce**
1. Login > select Project
2. Select job > Actions > Delete this job
3. Delete Jobs > 500 error

**Expected behavior**
Delete the job without a 500 error

**Screenshots**
![image](https://github.com/rundeck/rundeck/assets/105251934/d5ef8f27-d198-4168-a3fa-ffa3490a7a69)

**Additional context**
Recently removed the node that the job belonged to

**Comment by ahormazabal** [comment]
This issue will be resolved in the next release.

Check out: https://github.com/rundeck/rundeck/pull/9012
