### ISSUE TITLE
key secret is not parsing in job workflow

### ISSUE THREAD

**Issue by ythrinathareddy** [rundeck/rundeck#9041]
_Note: I have shell script in that i have password, so i want to encrypt the password so i used key store to save the password.  And i mentioning the value in script but it is not parsing the values.

is it correct way what i am doing. or there is any other way to store the password.

please find the details below 

this is my shell script. Please tell me any changes required. at the place of password i am parsing stored value $RD_OPTION_AUTOMATIONPASS

```
#!/bin/bash

# Set Oracle environment variables
export ORACLE_HOME=/u01/app/oracle/product/19/dbhome_1
export PATH=$ORACLE_HOME/bin:$PATH
export ORACLE_SID=icici

# Set Oracle database credentials
DB_USER="automation"
DB_PASSWORD="$RD_OPTION_AUTOMATIONPASS"
DB_SID="ORCL"

# Directory to store reports
REPORT_DIR="/u01/"

# Dynamically calculate dates for 'previous hour'
START_DATE=$(date --date='1 hour ago' '+%d-%b-%y %I.%M.%S.000000000 %p')
END_DATE=$(date '+%d-%b-%y %I.%M.%S.000000000 %p')

# Output file with timestamp
OUTPUT_FILE="$REPORT_DIR/hour_report_$(date +%Y%m%d%H%M%S).txt"

# SQL command with dynamic dates
SQL_COMMAND="SET PAGESIZE 0 FEEDBACK OFF VERIFY OFF HEADING OFF ECHO OFF;
select * from events
WHERE EVENT_TIMESTAMP BETWEEN TO_TIMESTAMP('$START_DATE', 'DD-MON-RR HH.MI.SS.FF AM') AND TO_TIMESTAMP('$END_DATE', 'DD-MON-RR HH.MI.SS.FF AM');"

# Run SQL Command
echo "$SQL_COMMAND" | sqlplus -S "$DB_USER/$DB_PASSWORD@$DB_SID" > "$OUTPUT_FILE"
```

<img width="761" alt="automationrundeck" src="https://github.com/rundeck/rundeck/assets/154959894/bddde1b2-1434-4aeb-bd5a-ef8cc6daa9f2">

**Comment by ythrinathareddy** [comment]
@MegaDrive68k  can you please help me in this.

**Comment by ythrinathareddy** [comment]
@MegaDrive68k Thank you for you fast reply. I followed the steps to configure ssh to remote host.

1. ssh-keygen (genrate the ssh key)
2. store the private key in rundeck key store
3. ssh-copy-id root@hostname (ssh key copied to remote server)

these are the steps i followed. And in the shared document they are saying to store the public key in authorized_keys remote server.  
what are the steps i followed is same or different?

And i used the option  @option.myoption@  it is also not parsing the keys.

 kindly requesting to share direct steps what i want to do. 
because i am done lot of search but there is no use full.

**Comment by MegaDrive68k** [comment]
Answered [here](https://stackoverflow.com/a/78267776/10426011).
