### ISSUE TITLE
Support custom Timezone in all views

### ISSUE THREAD

**Issue by hiribarne** [rundeck/rundeck#906]
Hi,
I'm running Rundeck 2.2.1-1-GA on Ubuntu and I configured it with timezone EST5DST (https://groups.google.com/d/msg/rundeck-discuss/_NUBNfuS9tM/qUBT6G5HBG8J)

It's showing the right time for the activity at Job's level but at the project's activity page (URL/project/SOME_PROJECT/activity) its showing an hour less.
Could some please advice of any custom timezone settings that need to be done?

**Comment by teramonagi** [comment]
Hi @hiribarne ;
You can fix this issue easily by yourself.
You just need to modify in "/etc/init.d/rundeckd " like the following:
from 
`
rundeckd="${JAVA_HOME:-/usr}/bin/java ${RDECK_JVM} -cp ${BOOTSTRAP_CP}  com.dtolabs.rundeck.RunServer /var/lib/rundeck ${RDECK_HTTP_PORT}"
`
To
`
rundeckd="${JAVA_HOME:-/usr}/bin/java ${RDECK_JVM} -cp ${BOOTSTRAP_CP} -Duser.timezone=<TimeZone you want> com.dtolabs.rundeck.RunServer /var/lib/rundeck ${RDECK_HTTP_PORT}"
`

**Comment by acasademont** [comment]
It would be really convenient if rundeck used the /etc/defaults file to configure arguments like this. Right now I have to hack into the init.d scripts to insert that line, not really nice!

**Comment by gschueler** [comment]
added trello card, please vote there https://trello.com/c/W4M03gnm
