### ISSUE TITLE
incomplete tags list in Nodes page

### ISSUE THREAD

**Issue by theblop** [rundeck/rundeck#911]
The Nodes page only shows the tags that match the first 20 filtered nodes, even after selecting "Load remaining".

The tag list should show all the tags that match the current filter, irrelevant of the number of nodes actually displayed. If the tag list is too long, it should be limited to a few lines with a clickable ellipsis "..."

Here is an example with with 50 tags assigned across 1000 nodes:
![snapshot3](https://cloud.githubusercontent.com/assets/1685646/4112439/e1213b72-3228-11e4-995e-18ecc9954688.png)

And after "Load remaining", the tag list doesn't change (Firefox 31):
![snapshot4](https://cloud.githubusercontent.com/assets/1685646/4112445/29688840-3229-11e4-8b53-19fd139e1bb7.png)

**Comment by gschueler** [comment]
fixed as of http://rundeck.org/docs/history/version-2.6.3.html
