### ISSUE TITLE
Rundeck Signing Keys Missing

### ISSUE THREAD

**Issue by ajxb** [rundeck/rundeck#9119]
**Describe the bug**

The Rundeck Signing Keys referenced in the documentation [Rundeck Signing Keys](https://docs.rundeck.com/docs/administration/install/signingkeys.html) are missing.

Any attempt to access the associated links results in a 404 not found error.

**To Reproduce**

Try to access any of the key links documented at [Rundeck Signing Keys](https://docs.rundeck.com/docs/administration/install/signingkeys.html)

**Expected behavior**

The Rundeck signing keys referenced in the documentation should be available at the documented endpoints.

**Screenshots**

![image](https://github.com/rundeck/rundeck/assets/1756536/46827b21-0f32-4056-8f2d-deff27069923)

**Comment by gschueler** [comment]
Thanks for reporting it, we've fixed the issue

**Comment by gschueler** [comment]
For future reference, the keys are also committed to https://github.com/rundeck/packaging repository
