### ISSUE TITLE
Node Enhancer icons

### ISSUE THREAD

**Issue by mikef-nl** [rundeck/rundeck#9154]
**Is your feature request related to a problem? Please describe.**
In order to give systems an OS related icon you need icons from the fab (brands) for fontawesome

**Describe the solution you'd like**
The ability to add icons like fa-windows as a node enhancer icon

**Describe alternatives you've considered**

**Additional context**
Adding fa-windows currently shows a blank as an additional fas is used as part of the css class. If fab were allowed then the icon would be visible.

Note: That feature requests will be closed after any clarification discussion to keep the open issues list low.  Closed issues are still considered as part of feature request backlog.  Since this is an Open Source project Pull Requests are welcome with enhancements.

**Comment by gschueler** [comment]
you can use `ui:icon:name` attribute `fab-windows`

<img width="371" alt="Screenshot 2024-05-30 at 9 12 55 AM" src="https://github.com/rundeck/rundeck/assets/55603/fe8d6af8-b4aa-41f7-b17c-ffcf25af2226">

**Comment by mikef-nl** [comment]
I'm a little confused on how you added that via the Node Enhancer ui, can you add a screenshot of that?

**Comment by gschueler** [comment]
You can use the Icon node enhancer, and e.g. attribute name `osFamily` value `windows`, and set the icon to `fab-windows`
![Screenshot 2024-06-05 at 8 57 49 AM](https://github.com/rundeck/rundeck/assets/55603/ee7a76cb-69ae-4928-910a-1980c974a37a)
