### ISSUE TITLE
Feature Request - Optionally execute workflow step based on job options

### ISSUE THREAD

**Issue by wufpack00** [rundeck/rundeck#916]
Request to add a new field on the Workflow Step creation screen. The field would be "Conditionally Execute Step". Allowed values would be "Yes" or "No". 

If "No" is selected, the step is always executed. 

If "Yes" is selected, a new field would display that would allow for the user to input a logic statement to be evaluated. If the logic returns true, the step would be skipped and a message such as "Skipping Workflow Step "Job with option that skips step" would be displayed in the log output.

Example Workflow Step:
Job Name: Job with option that skips step
Job Group: MyGroup
Commandline arguments: ${option.opt1}
Conditionally Execute?: Yes
Execute step if: ${option.opt1} == "Y"

**Comment by khoubyari** [comment]
+1

**Comment by blackside** [comment]
+1

**Comment by AlexKulbiy** [comment]
+1

**Comment by sbecuwe-prosodie** [comment]
+10

**Comment by kincl** [comment]
+1

**Comment by hjdr4** [comment]
+100

**Comment by RawTech** [comment]
+1

**Comment by kincl** [comment]
@gschueler Just wanted you to take another look at this. There appears to be a number of people interested in this fix.

Thanks!

**Comment by eblikstad** [comment]
+1

**Comment by schicky** [comment]
+1

**Comment by schicky** [comment]
+1

**Comment by jametsi** [comment]
+1

**Comment by roccato** [comment]
+1

**Comment by nnadirashvili** [comment]
+1

Very useful feature request. In addition, would be great to have wide range of comparison operators (dropdown) which will include but not limited to:

equals
not equals
containsString
isInList
etc.

**Comment by pgressa** [comment]
+1

**Comment by isuftin** [comment]
While I don't want to just give a +1 here (though I do want this feature badly), what sort of workarounds have people found without having an interim job that fails the workflow execution sequence, thereby breaking the execution chain?

**Comment by mmercer-appneta** [comment]
@isuftin we've built more complex workflows by calling the [Rundeck CLI tool "run"](http://rundeck.org/docs/man1/run.html) in a script step, but it's a little awkward.

**Comment by petr-klemsinsky** [comment]
+1

**Comment by 0xAalaoui** [comment]
+1

**Comment by xiang** [comment]
+1

**Comment by haugene** [comment]
+1

**Comment by atlasloewenherz** [comment]
+1

**Comment by samrajs** [comment]
+1

**Comment by aaaronic** [comment]
+1

**Comment by bryangwilliam** [comment]
+1

As a workaround, I am adding an option to the job and then setting an "Invocation String" for the script on one of my steps:  
` [ "${option.<name_of_option>}" = "<value_that_should_cause_it_to_skip>" ] || `

It isn't too cumbersome and does exactly what I needed, making the "Execution Preview" come out to:

` $ [ "${option.skip_step}" = "true" ] || scriptfile `

**Comment by mirkof** [comment]
+1

**Comment by Pierre-Pauly** [comment]
Any update on this feature being implemented soon? 
It would definitely help marking the jobs in a more meaningful way. Currently my script exits with a non zero exit code when it should prevent the rest of the job from executing. But this tags the whole job as 'failed'. Even though as such it has succeeded, but just decided to not run the remaining steps, which is perfectly fine.

**Comment by gschueler** [comment]
@Pierre-Pauly you can use an error-handler on the step with a Flow Control step to halt the execution in a successful state

**Comment by kallekarlberg** [comment]
+1

**Comment by Pierre-Pauly** [comment]
@gschueler I did use the error handler, but it still halts the execution as failed. Is there a specific command I can run to set the state?

**Comment by strechum** [comment]
+1

**Comment by TheFlyingPig** [comment]
+1

**Comment by kalkehcoisa** [comment]
+1
Oh long Johnson!

**Comment by maveco69** [comment]
+1
!!!!!!!!!!

**Comment by robgott** [comment]
+1

**Comment by tharinduj** [comment]
+1

**Comment by ka4eli** [comment]
+1

**Comment by jdlc** [comment]
+1

**Comment by kondapallivjagan** [comment]
+1

**Comment by krelst** [comment]
+1

**Comment by HowardHong** [comment]
+1

**Comment by dimatha** [comment]
+1

**Comment by methom90wh** [comment]
+1

This would be really helpful

**Comment by haydndup** [comment]
Hi Rundeck team,
Any update on this? This would be a great feature!

**Comment by claire-w** [comment]
+1 it would be great

**Comment by victorhahncastell** [comment]
and another +1

**Comment by sshipway** [comment]
This would be very useful; being able to have a test against a step would allow much more control, and remove the need to have multiple jobs defined that are 90% similar.

**Comment by sujipandi** [comment]
Hi Is this feature is implemented ?

equest to add a new field on the Workflow Step creation screen. The field would be "Conditionally Execute Step". Allowed values would be "Yes" or "No".

If "No" is selected, the step is always executed.

If "Yes" is selected, a new field would display that would allow for the user to input a logic statement to be evaluated. If the logic returns true, the step would be skipped and a message such as "Skipping Workflow Step "Job with option that skips step" would be displayed in the log output.

Example Workflow Step:
Job Name: Job with option that skips step
Job Group: MyGroup
Commandline arguments: ${option.opt1}
Conditionally Execute?: Yes
Execute step if: ${option.opt1} == "Y"

**Comment by sshipway** [comment]
It appears you can use the Error Handler step to approximate this, by having a local-run script that tests variable contents and exits with 1 (to trigger the error-handler step) or 0, but it's not very flexible.

**Comment by mlamutt** [comment]
@gschueler, I have been trying to get the Flow Control step to halt the execution in a successful state,  but I have not been able to get it to work.  Is there any documentation that you can point me to, or provide an example of how to set that up?  
We have a SCM process where we build the jobs on a dev rundeck instance, and then only allow jobs to be run against production on production rundeck instance.  This works well with the exception of scheduled jobs that we do not want to run 2x (in both dev and production).  I am trying to use this Flow Control step to gracefully exit if a job is run from the dev.

**Comment by ctodea** [comment]
I still believe.

**Comment by dpomnean** [comment]
+1 We still want this

**Comment by ahonor** [comment]
FYI, for users of Rundeck Enterprise this feature can be implemented using the ruleset strategy.
See the Examples section in https://docs.rundeck.com/docs/manual/workflow-strategies/ruleset-workflow-strategy-plugin.html

**Comment by dpomnean** [comment]
@ahonor What about the users who are not in Rundeck Enterprise?

**Comment by amunoz951** [comment]
Yeah this seems like it should be pretty basic functionality

**Comment by rayitopy** [comment]
+1

**Comment by cloudlady911** [comment]
+1

**Comment by Romainj1** [comment]
+1

**Comment by puremourning** [comment]
@ahonor i've tried to use the pro workflow strategy stuff, but it's really hard to use, because the logic is necessarily separate from the step itself, and can _easily_ become disconnected.

Take a look at what ansible does:

```yaml
-  name: <task>
    stuff: ...
   when: some really easy to understand expression
```

in rundeck's equivalent you sort of have:

```yaml
 strategy: |
      [random number]: if somecondition
 stuff: blah
 seteps:
    more stuff
    - step:
         thing the condition applies to
```

Morever, one key use-case is the ability to do conditional execution _based on data_ that is gathered during the execution, which is not possible with the pro appraoch.

For example: log in to all the hosts and check their current status. Record that status in the context data (note: this is a key use-case for node-speicific context data in non-node-based workflows). Use that data to determine whther or not to do stuff. Specifically: Check the state of a bunch of servers, if they require a backup, record that. Later, do a backup only on those servers. If there's a failure, only run the restore on the servesr that had a backup done. (note this can't be in node configuration because let's say the decision to make a backup or not is dependent on something external that can't statically configure nodes).

**Comment by ahonor** [comment]
@puremourning for that case (and probably many), it would be nice to have a step-level conditional that resembles that `when` clause, I think.

**Comment by puremourning** [comment]
@ahonor yep that works, as long as the `when` clause has access to usual variables. 

But i think another piece of the "conditional execution" puzzle is restricting execution of steps on nodes based on dynamic data, such as  place in the global data context to store node-specific details, so you could do this in a job-reference step:

```yaml
 - jobRef:
   ...
       nodeFilter: nodeContext.SOME_DATA_I_SET: something
```

That is, i still want to execute the step, but only on these nodes hich match some properties i couldn't know beforehand.

That leads to the final piece (which may or may not have already been resolved): if a job-reference step overrides the node filter, and it matches no nodes, this shouldn't _always_ be an error. We have to use a horrible errorHandler hack for this and it makes job maintenance awkward. I know "no matched nodes" can be set as not-an-error in a job, but iirc this is not true when used as a job-reference. could be wrong about that, which would be great.

**Comment by puremourning** [comment]
Of course, you can achieve the latter with a `when` clause in the referenced job too i suppose, again, assuing there is a concept of node-data which is shared across the full workflow.

**Comment by gevial** [comment]
+1
A bit surprised this is not implemented, conditionals seem to be a basic stuff for any automation/orchestration engine

This is the only reason stopping our team from using Rundeck at the moment

**Comment by lukasged** [comment]
+1

**Comment by sethrice** [comment]
+1 We need to be able to do this as well. It could reduce our job count, and corresponding development, testing, debugging, by several fold. 

Though I find the response from Rundeck defeating, and disappointing. This thread is 21 days away from a 5 year mark, with continual, regular requests since creation.

  "wufpack00 opened this issue on Sep 3, 2014 · 66 comments"

Today - August 13, 2019 
 Still no new feature fulfillment? Come on Rundeck, why are you holding out on us?

**Comment by guidograzioli** [comment]
+1 Adding myself to the queue

**Comment by tholok97** [comment]
+1

**Comment by pedroparraortega** [comment]
+1

**Comment by molinacarlos** [comment]
+1

**Comment by smacz42** [comment]
+1

**Comment by fdevans** [comment]
As Alex mentioned previously:
For users of Rundeck Enterprise this feature can be implemented using the ruleset strategy.
See the Examples section in https://docs.rundeck.com/docs/manual/workflow-strategies/ruleset-workflow-strategy-plugin.html

**Comment by guidograzioli** [comment]
Would rundeck welcome a PR with a community implementation for this feature?

**Comment by fdevans** [comment]
Ideally it would be a plug-in.  [Docs on building plugins is here](https://docs.rundeck.com/docs/developer/01-plugin-development.html#java-plugin-development).

**Comment by puremourning** [comment]
The enterprise feature is, let’s be honest, not the best. It’s a maintenance nightmare compared to the simplicity of the equivalent eg ansible feature. The programming model is just too awkward IMO (having tried it and given up)

**Comment by fdevans** [comment]
I don't disagree.  It's on our roadmap to revisit that plugin and make improvements.

**Comment by amartin3225** [comment]
+1

**Comment by puremourning** [comment]
> Ideally it would be a plug-in

IIRC the "Pro" plugin that implements this uses some internal APIs that are not documented. The [Workflow Strategy plugin type](https://github.com/rundeck/rundeck/blob/c962586cbe85105391dfad6d54826ef1ece8e6a6/core/src/main/java/com/dtolabs/rundeck/plugins/CorePluginProviderServices.java#L53) is [not documented](https://docs.rundeck.com/docs/developer/01-plugin-development.html).

The best we have right now is something like this:

```
steps:
 - type: localexec
    configuration:
      command: 'test "${option.Something}" != "YES"'
    errorHandler:
      jobRef:
        group: Test
        name: Do_The_Thing_If_Something_Equals_YES
        importOptions: true
```

I have looked multiple times and other than making every step use a custom workflow step plugin, it's not obvious how this would be implemented.

**Comment by amartin3225** [comment]
Thanks for the tip on how to do this with an error handler for now until an official implementation is available.
