### ISSUE TITLE
Logging key value data during a job disables ansi colour output for the rest of the job

### ISSUE THREAD

**Issue by LevonW-IIS** [rundeck/rundeck#9178]
_Note: Bug Reports not following this template may be closed without feedback._

**Getting Help**
Please use this issue template for reporting identified or suspected **bugs** *only*. For support on configuration or troubleshooting please see [Getting Help](https://docs.rundeck.com/docs/manual/02-getting-help.html#enterprise-support) for the appropriate channels.

**Describe the bug**
ANSI Colours not being rendered in a job log after a key value data log filter is used with 'Log Data' turned on

**My Rundeck detail**

* Rundeck version: 5.2.0
* install type: war
* OS Name/version: Windows Server 2019 Standard Edition
* DB Type/version: mysql

**To Reproduce**
Run the following job definition.

before the logged data, the job outputs colour normally (green header for the command get-process)
, and after the log, no colour is displayed
[test_colour.json](https://github.com/user-attachments/files/15764856/test_colour.json)

**Expected behavior**
Colour should be rendered before and after logging data

**Screenshots**
![image](https://github.com/rundeck/rundeck/assets/103007146/551a1c95-cce1-4dc8-857f-37894bef7a76)
![image](https://github.com/rundeck/rundeck/assets/103007146/0576f98a-3ba5-49ee-ac8e-89ef92dba21d)
![image](https://github.com/rundeck/rundeck/assets/103007146/bff40dbc-62b5-4e60-81e8-aed4e96d7e29)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Browser Firefox
 - Version 126.0.1 (64 bit)

**Additional context**
This did not appear to happen on 4.x installation of rundeck

**Comment by gschueler** [comment]
there was an issue fixed in 5.3.0 that might have caused this issue, can you check 5.3.0? https://github.com/rundeck/rundeck/pull/9081

**Comment by LevonW-IIS** [comment]
Upgrading to Rundeck 5.4.0 fixed this
