### ISSUE TITLE
Executions not showing up in activity list after upgrading from 3.4.9 to 5.4.0

### ISSUE THREAD

**Issue by bradym** [rundeck/rundeck#9206]
**Describe the bug**
After upgrading from 3.4.9 to 5.4.0 previous executions of jobs are not showing up on the activity tab on the job page. 

This appears to be a frontend bug as the number of previous executions looks reasonable, and there's pagination links like there should be content. But where the table should be there are either zero results shown, or one or two results when there should be many more results. 

The same thing is happening on the Activity page for the project. This is happening on all projects.

**My Rundeck detail**

* Rundeck version: 5.4.0
* install type: RPM in custom Docker image
* OS Name/version: Debian GNU/Linux 12
* DB Type/version: Postgres 14.10

**To Reproduce**
1. Click on a job page
2. Scroll to the bottom and click "Activity"

**Expected behavior**
I expect to see the list of previous executions of jobs.

**Screenshots**

![peek_4](https://github.com/rundeck/rundeck/assets/289182/70286386-b0bb-44c6-929b-869451edff8d)

![image](https://github.com/rundeck/rundeck/assets/289182/884e3448-3987-4821-a94f-5adc95d664fb)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04.4 LTS
 - Browsers:
   - Firefox 126.0.2
   - Google Chrome 126.0.6478.114

**Comment by saran3668** [comment]
I am facing the same issue post upgrade from 4.14.1 to 5.4.0. Can anyone please suggest what should be done here ?

**Comment by smartinellibenedetti** [comment]
@bradym and @saran3668 when upgrading rundeck, have you followed the update notes from all versions in between, or just the notes from 5.4? There have been several breaking changes, therefore it is recommended to go over all of them.

**Comment by bradym** [comment]
I went through all of the documentation on https://docs.rundeck.com/docs/upgrading/ before upgrading. The only relevant change I saw for Rundeck community version is needing to run Java 11, which we are doing. All the other updates I saw were related to using the H2 database, but we're using Postgres.

**Comment by shaunmcdade** [comment]
I upgraded directly from 5.3.0 to 5.4.0. I was able to see historical runs before the upgrade, and I'm not able to after the upgrade. I'm also using Postgres.

**Comment by saran3668** [comment]
I followed the notes only from 5.4. I have done upgrades in the past in the same way and it used to be fine. Only this time I am facing this issue. All other functionalities are working as expected except the old activity getting listed part on the UI. I'm using Mysql.

**Comment by smartinellibenedetti** [comment]
Anything on the logs? And to confirm, you're unable to see the executions that happened before the update, but any new executions are showing up, correct?

**Comment by bradym** [comment]
> Anything on the logs? 

Nope, nothing in the logs.

> And to confirm, you're unable to see the executions that happened before the update, but any new executions are showing up, correct?

This is correct.

**Comment by amartin3225** [comment]
I'm also experiencing this issue on 5.4. How can this problem be resolved or is there a workaround?

**Comment by ddarby-hike** [comment]
Wynn also experienced the problem (they ended up creating a new/empty DB and re-importing all their jobs to resolve the problem).  Morgan Stanley is also having trouble after upgrading (4.14 -> 5.4).  Jobs with PD-add-note Notifications cause endless DB problems/timeouts which then prevents the activity page from working.

**Comment by bradym** [comment]
We upgraded to 5.5.0 yesterday and can confirm that this issue is fixed in that version.
