### ISSUE TITLE
Collapse jobs by default

### ISSUE THREAD

**Issue by jasonhensler** [rundeck/rundeck#921]
Usability suggestion:
Add an option [per project] to collapse all job groups by default. 
We have a use case in which our operations group have start stop jobs in one project by team, if it's collapsed navigating to the group they want is very simple.

**Comment by askmike1** [comment]
I second this.... it would be very nice to be able to have the jobs show in a collapsed state by default.

**Comment by widox** [comment]
Yes, this would be a welcome addition. It would also be nice if you have job groups collapsed, go into a job, come back: the page should respect that setting and still be collapsed.

**Comment by danifr** [comment]
+1 to this. We are starting to have too many jobs

**Comment by jenulis** [comment]
+1

**Comment by atlasloewenherz** [comment]
+1

**Comment by djalai** [comment]
+1

**Comment by byen** [comment]
+1

**Comment by oldingn** [comment]
+11

**Comment by gitlab-cloud** [comment]
+1

**Comment by gorazdzagar** [comment]
+1 (any hacks until then?)

**Comment by blacked** [comment]
👍

**Comment by MAS150MD200** [comment]
+1

**Comment by TheodorD** [comment]
Writing this in here because this is the first result on google:

To do this, go to the project settings -> edit configuration -> User Interface 
There, set "Job Group Expansion Level" to 0 to collapse all groups per default.
