### ISSUE TITLE
Nessus Vulnerability (Medium) - JQuery 1.2 < 3.5.0 Multiple XSS

### ISSUE THREAD

**Issue by sant0sh** [rundeck/rundeck#9241]
Which rundeck version has upgraded JQuery version.

We are currently using  rundeck version : 4.14.1

How we should resolve the compliance issue?

https://rundeck_url:4443/assets/vendor/jquery-ac52a8dfe2701cc3644381f85f75d51e.js

**Comment by MegaDrive68k** [comment]
Hi @sant0sh 

Please check [this](https://groups.google.com/g/rundeck-discuss/c/4kj5bVg3jXg/m/TpS1y2JVAAAJ) post.

Regards.

**Comment by sant0sh** [comment]
Thank you for the answer @MegaDrive68k
