### ISSUE TITLE
Parallel execution 

### ISSUE THREAD

**Issue by mezbiderli** [rundeck/rundeck#927]
Allow parallel execution of steps defined within a workflow.

E.g. if a workflow is defined -conceptually- as;

Sequential {
  Step-1;
  Step-2;
  Parallel {
    Step-3;
    Step-4;
    Step-5:
  }
  Step-3;
}

Sequential workflow can refer to Parallel workflow for executing Step3-5 in parallel.

Parallel block succeeds iff a. all steps within it complete b. all steps succeed

Parallel block fails if any of steps within fail. Failure occurs 'after' all steps complete. It should be able to have this behavior (failing immediately or waiting for all steps) configured.

**Comment by mezbiderli** [comment]
Hi has this been merged already? Or is the feature still in flight?

**Comment by gschueler** [comment]
hi @mezbiderli  it was merged and is in 2.4.0 release.  I will close this issue, thanks.

**Comment by mezbiderli** [comment]
Thanks! I see it's still marked as incubation though

        <g:if test="${workflow?.strategy == 'parallel' || grailsApplication.config.feature?.incubator?.parallelWorkflowStrategy in [true,'true']}">

Is this still the case?

**Comment by gschueler** [comment]
Yes, just to make sure there are no stability issues.  Appreciate any feedback when using it in production environments!

**Comment by isequal2** [comment]
Can some one point me to some resource with an example on how to create job with parallel step execution.
