### ISSUE TITLE
Allow custom file extension for script temp files

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#933]
ref #894

**Comment by dernotte** [comment]
Would it be possible to have the same argument in the adhoc script API. We can set the scriptInterpreter, but not fileExtension. For the moment I use "copy ${filescipt} ${filescript}.psi & powershell -file ${filescript}.ps1 & del ${filescript}.ps1" to invoke a powershell scipt with adhoc APi

**Comment by gschueler** [comment]
@dernotte can you file an issue for that?  I take it you mean for the script-exec node executor

**Comment by dernotte** [comment]
Sure I will
