### ISSUE TITLE
Nessus Vulnerability (Medium) - JQuery 1.2 < 3.5.0 Multiple XSS - Query Part II

### ISSUE THREAD

**Issue by sant0sh** [rundeck/rundeck#9344]
Hi Team,

On some of our environments we still continue to use Rundeck version 3.4.9 non containerized version. I have been asked can existing rundeck work if we just upgrade JQuery 1.2 to JQuery 3.5.0

If yes what will be the steps to do the JQuery upgrade?

@MegaDrive68k

**Comment by MegaDrive68k** [comment]
Hi @sant0sh,

The only way is to upgrade Rundeck. Please take a look at [this](https://docs.rundeck.com/docs/upgrading/). The latest version at this moment uses jquery  3.6.4.

Regards.

**Comment by sant0sh** [comment]
Thank you @MegaDrive68k
