### ISSUE TITLE
Running rundeck on SUSE

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#94]
Here's an init script for the SUSE distribution that could be included in the source code : 

@@@
# !/bin/sh
### BEGIN INIT INFO
# Provides:          rundeck
# Required-Start:    $syslog $remote_fs
# Should-Start:
# Required-Stop:     $syslog $remote_fs
# Should-Stop:
# Default-Start:     3 5
# Default-Stop:      0 1 2 6
# Short-Description: Rundeck Server
# Description:       Start Rundeck Server
### END INIT INFO

. /etc/rundeck/profile

prog="rundeckd"
BIN_FILE="${JAVA_HOME:-/usr}/bin/java"
BIN_OPTS="${RDECK_JVM} -cp ${BOOTSTRAP_CP}:/etc/rundeck com.dtolabs.rundeck.RunServer /etc/rundeck 4440"
PID_FILE=/var/run/rundeckd.pid
LOG_FILE=/var/log/rundeck/service.log
USER_NAME=rundeck

. /etc/rc.status
rc_reset

start() {
    echo -n $"Starting $prog: "
        /sbin/startproc -v -s -l ${LOG_FILE} -u ${USER_NAME} ${BIN_FILE} ${BIN_OPTS} > $PID_FILE
        rc_status -v
}

stop() {
    echo -n $"Stopping $prog: "
    killproc -p $PID_FILE ${BIN_FILE}
    rc_status -v
}

reload() {
    echo -n $"Reloading $prog: "
        ## Stupid but not implemented really
        $0 restart
        rc_status -v
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop
        start
        rc_status -v
        ;;
    status)
            echo -n "Checking for service $prog "
            /sbin/checkproc -p ${PID_FILE} "${BIN_FILE}"
            rc_status -v
        ;;
    *)
        echo $"Usage: $0 {start|stop|restart|reload|status}"
        exit 1
esac
rc_exit
@@@

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/382)

Original Creator: Claude Durocher

**Comment by ahonor** [comment]
Not supporting at this time.
