### ISSUE TITLE
Please help add support for ARM64 docker container

### ISSUE THREAD

**Issue by andrewlauau** [rundeck/rundeck#9430]
I've noticed that containers on Docker Hub are all for amd64. Don't know if there's a chance adding support for ARM64.

**Comment by MegaDrive68k** [comment]
Hi,

let´s follow that request [here](https://github.com/rundeck/rundeck/issues/6433).

Also, take a look at [this](https://github.com/rundeck/rundeck/pull/9141).

thank you.
