### ISSUE TITLE
Rundeck Not Sending Emails

### ISSUE THREAD

**Issue by elocnatsirt** [rundeck/rundeck#944]
I am getting these errors when sending emails through Rundeck:

2014-09-22 15:06:03,033 [quartzScheduler_Worker-1] ERROR grails.app.services.rundeck.services.NotificationService - Error sending notification email to myemail@mydomain.com for Execution 124: Mail server connection failed; nested exception is javax.mail.MessagingException: 501 5.0.0 HELO requires domain address
. Failed messages: javax.mail.MessagingException: 501 5.0.0 HELO requires domain address

Any ideas?

**Comment by franklanganke** [comment]
I got it working uses AWS SES smtp:https://gist.github.com/franklanganke/c5c4c53b03a635eb2abd.js

**Comment by rsheftel** [comment]
Can I ask how you got gmail working as the email service for Rundeck? There are a few of us having problems setting this up. Any help appreciated.

Google groups: https://groups.google.com/forum/#!topic/rundeck-discuss/MkBGvOwlhpA

**Comment by Jamku** [comment]
Hi,
I am newbie to Rundeck, using 2.8.2 version. trying to configure email settings. Please suggest if anything, below is content of rundeck-config.groovy

loglevel.default = "DEBUG"
rdeck.base="/var/lib/rundeck"
rss.enabled="false"
grails.serverURL="10.6.122.129:4440"
dataSource {
  dbCreate="update"
  url="jdbc:h2:file:/var/lib/rundeck/data/rundeckdb;MVCC=true"
}

grails {
  mail {
    host="smtp.gmail.com"
    port="465"
    username="ravikumashi@gmail.com"
    password="Megha@Ravi"
    props=["mail.smtp.auth":"true",
             "mail.smtp.socketFactory.port":"465",
             "mail.smtp.socketFactory.class":"javax.net.ssl.SSLSocketFactory",
             "mail.smtp.socketFactory.fallback":"false"]
  }
}
grails.mail.default.from="deployer@domain.com"

But i still dont receive any emails and also no error in output log also

**Comment by elocnatsirt** [comment]
@Jamku I do not use Rundeck anymore and this is an old issue so you might want to create your own. Also, it looks like you posted your Gmail email/password in plain text, I would nuke that ASAP.
