### ISSUE TITLE
Feature Request: Users' email addresses should pull from LDAP rather than having to enter them in their profiles

### ISSUE THREAD

**Issue by pwhack** [rundeck/rundeck#946]
When authentication is handled by LDAP, it would be efficient to also pull the user's email address from LDAP rather than having to enter the address in the user's Rundeck profile.

**Comment by sidewinder12s** [comment]
+1

**Comment by ssbarnea** [comment]
My impression is that the Rundeck LDAP/AD is totally ignored. I configured probably over 100 products with LDAP and so far, the rundeck experience was by far the worst one. Is only partially documented and you have to google for days and days in order to get a minor progress with it.

**Comment by schast** [comment]
+1

**Comment by marcorel** [comment]
+1

**Comment by akusbharat** [comment]
Do you have any update on this feature, I was also looking for similar feature

**Comment by vmwiz** [comment]
Please add the possibility to fetch user attributes from LDAP to fill in profile informations (firstname, lastname, email) !

**Comment by hekaldama** [comment]
+1 can this get put on trello?

**Comment by vmwiz** [comment]
In the meantime, if you use a MySQL backend, here's a script I wrote which grab the attributes from LDAP and feed them to the database. The script is called from cron every 5 minutes.

```python
#!/usr/bin/python
# Little script to fetch rundeck users profile informations from LDAP directory
# The current LDAP implementation of Rundeck doesn't do it.
#

import MySQLdb
import ldap
import sys

mysql_host = "{{ rundeck_mysql_host }}"
mysql_user = "{{ rundeck_mysql_user }}"
mysql_passwd = "{{ rundeck_mysql_pass }}"
mysql_db = "{{ rundeck_mysql_db }}"

ldap_host = "{{ rundeck_ldap_server }}"
ldap_user = "{{ rundeck_ldap_bind_dn }}"
ldap_passwd = "{{ rundeck_ldap_bind_password }}"
ldap_basedn = "{{ rundeck_ldap_user_base_dn }}"
ldap_search_attributes = ['uid', 'sn', 'givenName', 'mail']
ldap_search_filter = "(&(uid=%s)(objectClass=inetOrgPerson))"

# Create a MySQL connection object
try:
  db = MySQLdb.connect(host=mysql_host,
                       user=mysql_user,
                       passwd=mysql_passwd,
                       db=mysql_db)

except MySQLdb.Error, e:
  print "There is a problem connecting to the MySQL server."
  print e
  sys.exit(0)

# Fetch users from rundeck database where profile is not completed
cur = db.cursor()
cur.execute("SELECT login FROM rduser WHERE ISNULL(first_name) OR ISNULL(last_name) OR ISNULL(email);")

# If incomplete profiles are found, fetch informations from LDAP
if cur.rowcount > 0:

    # Create a LDAP connection object
    try:
      l = ldap.initialize(ldap_host)
      l.protocol_version = ldap.VERSION3
      username = ldap_user
      password = ldap_passwd
      l.bind_s(username, password, ldap.AUTH_SIMPLE)

    except ldap.CONNECT_ERROR:
      print "There is a problem connecting to the LDAP server."
      sys.exit(0)
    except ldap.INVALID_CREDENTIALS:
      print "Invalid LDAP credentials."
      sys.exit(0)
    except ldap.LDAPError, e:
      print e
      sys.exit(0)

    # Loop through MySQL results to get userid
    for row in cur.fetchall():

      searchFilter = ldap_search_filter % row[0]

      ldap_result_id = l.search(ldap_basedn, ldap.SCOPE_SUBTREE, searchFilter, ldap_search_attributes)

      while 1:
        result_type, result_data = l.result(ldap_result_id, 0)
        if (result_data == []):
          break
        else:
          if result_type == ldap.RES_SEARCH_ENTRY:
            # if the userid is found in LDAP, get the attributes and update the database
            email = result_data[0][1]['mail'][0]
            firstname = result_data[0][1]['givenName'][0]
            lastname = result_data[0][1]['sn'][0]
            login = row[0]

            cur.execute("""UPDATE rduser SET email=%s, first_name=%s, last_name=%s WHERE login=%s;""", (email,firstname,lastname,login))
            db.commit()

# Close LDAP and MySQL connections
db.close()
l.unbind_s()
```

**Comment by anthonyclarka2** [comment]
+1

It would definitely make managing 100s of users a lot easier.

**Comment by JustRiedy** [comment]
+1

**Comment by guidograzioli** [comment]
+1

**Comment by pmuller** [comment]
As I _really_ wanted to get email addresses, and I use the default H2 database, I wrote a small Python script for this: https://github.com/pmuller/rundeck-create-users-from-ldap
Hope it helps!

**Comment by flopma** [comment]
Open since 2014? 

Anyway, there is a related question but concerning Rundeck/Crowd integration with provisionning of user name and email stored in Crowd.

I can change my JAAS module to do this, but I need either a Rundeck Principal object I could use in the JAAS module;
or a specific event I could listen to if I write a plugin for Crowd.
I would prefer of course option one, since it does not force users to install two pieces of software to get a unique experience.

Rundeck team, any feedback on this?

For reference: https://github.com/flopma/crowd-jaas/issues/9

**Comment by gschueler** [comment]
@flopma yes, there are ways we could do this, as you mentioned in your link. We would need to add support in Rundeck: some kind of "UserInfoSource" plugin which can retrieve the user info from an external service, or can extract it from the UserPrincipal in the request, which could be supplied by the JAAS login module.

**Comment by ThorbenJ** [comment]
+1 Name fields too

**Comment by joelsdc** [comment]
Hi all, any updates on this? It has been quiet for a while..

**Comment by JeffHemmen** [comment]
+1

**Comment by beelzetron** [comment]
+1

**Comment by umair-io** [comment]
+1

**Comment by sshipway** [comment]
+1 from me as well.  I'm amazed this is not already in there; if you can pull in the grou pmemberships, how hard can it be to also pull in the email and name?

**Comment by skycolangelom** [comment]
+1

**Comment by astapelfeld** [comment]
+1

**Comment by rlueckl** [comment]
Quick question about this: I see that the change has been merged and released with 3.0.12. I've installed that version, but I still don't see the name or e-mail address in Rundeck.

Rundeck version: 3.0.12.20190114-1.201901142226

I've tried logging in with a completely "fresh" user (never logged in in Rundeck before) -> Profile says: E-Mail NOT SET, First Name NOT SET, Last Name NOT SET.

Also tried it with my main user, but everything still says NOT SET.

What am I missing? @gschueler

**Comment by sjrd218** [comment]
@rlueckl 3.0.12 was released with 1 critical bug fix. It did not contain this feature. 3.0.13 is coming out soon and will have this feature. Thanks for your patience and sorry for the confusion.

**Comment by rlueckl** [comment]
Ah, thank you for the info. I'll wait for 3.0.13 then. :)

**Comment by Athos85** [comment]
I am waiting for a long time.. thanks for your efforts, looking forward to 3.0.13 :)

**Comment by cedrico2016** [comment]
thx very much.
also waiting for that feature

**Comment by kpanter** [comment]
What is planned date for 3.0.13 release :D ?

**Comment by rlueckl** [comment]
Sorry to bother you again. 3.0.13 is now released, and according to the comparison between 3.0.12 and 3.0.13 (https://github.com/rundeck/rundeck/compare/v3.0.12...v3.0.13) this feature has been merged and released with 3.0.13

Unfortunately I still don't seem to get the first/last name and e-mail address from LDAP.

**Comment by rlueckl** [comment]
I've added the config to the `rundeck-config.groovy`, but the log output in `service.log` is the same as before. No additional debug log during login:

```2019-02-07 07:44:52.827 DEBUG --- [tp1533295982-48] ailsUsernamePasswordAuthenticationFilter : Request is to process authentication
2019-02-07 07:44:53.080  INFO --- [tp1533295982-48] c.d.r.j.j.JettyCachingLdapLoginModule    : Login attempts: 1, Hits: 0, Ratio: 0%.
2019-02-07 07:44:53.087 DEBUG --- [tp1533295982-48] c.d.r.j.j.JettyCachingLdapLoginModule    : Cache Miss for ******.
2019-02-07 07:44:53.092 DEBUG --- [tp1533295982-48] c.d.r.j.j.JettyCachingLdapLoginModule    : Searching for users with filter: '(&(objectClass={0})({1}={2}))' from base dn: cn=***,ou=***
2019-02-07 07:44:53.105 DEBUG --- [tp1533295982-48] c.d.r.j.j.JettyCachingLdapLoginModule    : Found user?: true
2019-02-07 07:44:53.106  INFO --- [tp1533295982-48] c.d.r.j.j.JettyCachingLdapLoginModule    : Attempting authentication: uid=******,cn=***,ou=***
2019-02-07 07:44:53.294 DEBUG --- [tp1533295982-48] c.d.r.j.j.JettyCachingLdapLoginModule    : Using _rootContext for role lookup.
2019-02-07 07:44:54.074 DEBUG --- [tp1533295982-48] c.d.r.j.j.JettyCachingLdapLoginModule    : JettyCachingLdapLoginModule: User '******' has roles: [***, readonly, user]
2019-02-07 07:44:54.075 DEBUG --- [tp1533295982-48] c.d.r.j.j.JettyCachingLdapLoginModule    : Adding ****** set to expire: 1549521894075300000
2019-02-07 07:44:54.090 DEBUG --- [tp1533295982-48] ailsUsernamePasswordAuthenticationFilter : Authentication success. Updating SecurityContextHolder to contain: org.springframework.security.authentication.jaas.JaasAuthenticationToken@f9bd45e3: Principal: ******; Credentials: [PROTECTED]; Authenticated: true; Details: org.springframework.security.web.authentication.WebAuthenticationDetails@0: RemoteIpAddress: 1.2.3.4; SessionId: node017zgao5******1smz6w3mfi4ma0; Granted Authorities: Jaas Authority [***,***], Jaas Authority [readonly,readonly], Jaas Authority [user,user]```

The config file looks like this:

```root@server /etc/rundeck # tail -n 8 rundeck-config.groovy 

// Ldap debug
import org.slf4j.LoggerFactory
import ch.qos.logback.classic.LoggerContext
import ch.qos.logback.classic.Level
LoggerContext loggerContext = (LoggerContext)LoggerFactory.getILoggerFactory();
loggerContext.getLogger("org.rundeck.security.RundeckAuthenticationSuccessEventListener").setLevel(Level.DEBUG)

root@server /etc/rundeck # ```

**Comment by sjrd218** [comment]
@rlueckl Can you double check your `rundeck-config.properties` and make sure the property:
`rundeck.security.syncLdapUser=true` is set?

**Comment by rlueckl** [comment]
I don't have a `rundeck-config.properties`. Rundeck is installed via the Puppet Forge module (https://forge.puppet.com/puppet/rundeck) and it only creates the `rundeck-config.groovy` file.

I've created `rundeck-config.properties` by hand, added the property and then restarted Rundeck, but it did not help.

I've also tried to add `rundeck.security.syncLdapUser = true` to `rundeck-config.groovy`. This + the debug config gave me a few extra lines in the log:

```
2019-02-08 07:25:02.019 DEBUG --- [tp1440250739-23] c.d.r.j.j.JettyCachingLdapLoginModule    : Adding ****** set to expire: 1549607102018300000
2019-02-08 07:25:02.047 DEBUG --- [tp1440250739-23] undeckAuthenticationSuccessEventListener : Updating user profile from ldap attributes for user: ******
2019-02-08 07:25:02.050 DEBUG --- [tp1440250739-23] undeckAuthenticationSuccessEventListener : First Name: null
2019-02-08 07:25:02.050 DEBUG --- [tp1440250739-23] undeckAuthenticationSuccessEventListener : Last Name: null
2019-02-08 07:25:02.050 DEBUG --- [tp1440250739-23] undeckAuthenticationSuccessEventListener : Email: null
2019-02-08 07:25:02.165 DEBUG --- [tp1440250739-23] ailsUsernamePasswordAuthenticationFilter : Authentication success. Updating SecurityContextHolder [...]
```

So it seems tha "syncLdapUser" was missing, but it also looks like that Rundeck can't get the desired information from LDAP. :cry:

**Comment by Athos85** [comment]
After setting
```
   userLastNameAttribute="sn"
    userFirstNameAttribute="givenName"
    userEmailAttribute="mail"
```
in 
`jaas-ldap.conf`


**AND** (thanks to the hint on this thread)
`rundeck.security.syncLdapUser=true`
in 
`rundeck-config.properties`

The sync worked fine!

Really appreciated! Thanks!

**Comment by kumy** [comment]
What is the recommended way to define `rundeck.security.syncLdapUser=true` when using the official docker image? Is there a dedicated environment variable I can set?

**Comment by rainman-xx** [comment]
> What is the recommended way to define `rundeck.security.syncLdapUser=true` when using the official docker image? Is there a dedicated environment variable I can set?

none that I know of. But you can have add a dockerfile RUN command that inserts line 'rundeck.security.syncLdapUser=true' to the 'rundeck-config.properties' file

**Comment by paulholden** [comment]
Thanks @Athos85 for the pointer - worked fine after following your instructions. Subsequently [found these](https://docs.rundeck.com/docs/administration/security/authenticating-users.html#sync-rundeck-profile-from-ldap-user-attributes) which were also useful.

**Comment by Tadas** [comment]
> > What is the recommended way to define `rundeck.security.syncLdapUser=true` when using the official docker image? Is there a dedicated environment variable I can set?
> 
> none that I know of. But you can have add a dockerfile RUN command that inserts line 'rundeck.security.syncLdapUser=true' to the 'rundeck-config.properties' file

@kumy I was able to set `RUNDECK_SECURITY_SYNCLDAPUSER=true` and it worked thanks to:

https://github.com/rundeck/rundeck/blob/d5b41c50aaffeb7c7a947df4b1bbb77694200cf9/docker/official/remco/templates/rundeck-config.properties#L42-L44
