### ISSUE TITLE
add job.user.email to execution context variables

### ISSUE THREAD

**Issue by pwhack** [rundeck/rundeck#947]
I was able to pass job.user.email to scripts just fine in v2.1.1, however, the value is empty in v2.2.2. I verified the user's profile contains a valid email address.

**Comment by dscowan** [comment]
It would be helpfull if job.user.email could be used in scripts

**Comment by zlanyi** [comment]
+1

**Comment by Slm0n87** [comment]
+1 - this feature would help me, too. To use it in a inline-script

**Comment by brandonpal** [comment]
+1

**Comment by david-richer-adsk** [comment]
+1

**Comment by nmamn** [comment]
+1 ...

**Comment by luckytaxi** [comment]
What's the status of this?

**Comment by astapelfeld** [comment]
+1

**Comment by toninis** [comment]
Hello,

Any updates on this ?
Will this feature be available ?

**Comment by kuribas** [comment]
+1

**Comment by ZoeLeah** [comment]
+1

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jorn-k** [comment]
Hi folks. This issue has been resolved and merged in [4361](https://github.com/rundeck/rundeck/pull/4631). It will be released very soon.

Thank you, again, Rundeck community for continuing to make Rundeck better every day!
