### ISSUE TITLE
Job dies during execution with "Unknown: java.lang.InterruptedException" Message

### ISSUE THREAD

**Issue by shlomosh** [rundeck/rundeck#948]
During execution of long running script on remote system the job died with the following message -

java.lang.InterruptedException
Failed: Unknown: java.lang.InterruptedException
Exception: class com.dtolabs.rundeck.core.execution.dispatch.DispatcherException: Node dispatch interrupted
Node dispatch interrupted

No other information is present.

RunDeck version: 2.2.2

**Comment by ronnbcnews** [comment]
i had this problem too, make sure the timeout value for the job is set long enough for your job to complete.

**Comment by daniamaran** [comment]
i have a same problem, the solution would be to increase the time of the job ?
