### ISSUE TITLE
Feature request: Easy Way to Copy Project Configuration

### ISSUE THREAD

**Issue by dennis-benzinger-hybris** [rundeck/rundeck#949]
There should be an easy way to copy the project configuration from one Rundeck server to another. For example by including the necessary files (e.g. `project.properties`) in the project export JAR.

Or just document which files and possibly database tables have to be copied.

**Comment by fdevans** [comment]
Due to the age of this request and recent feature releases we are going to close this request.  If there are still gaps in the feature set please feel free to open an enhancement request against the current version of Rundeck with your ideas.
Thank you, 
The Rundeck Team

**Comment by broferek** [comment]
For those ending up here when looking for this feature, this is actually easily accomplished by first exporting an archive of a project, then creating an empty project and importing the archive you previously created.

Simply include the project configuration in your export and you're done.
