### ISSUE TITLE
Enable/Disable Jobs from GUI/API

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#95]
As for the current version of rundeck 1.3, there's no way to easily enable or disable from Web Console or using API.  It would be nice to have this feature in the next release of rundeck.  This way, it can greatly help to manage jobs. For example, we can disable certain scheduled jobs for the note maintenance. 

- [x] Another feature I would like to see is to have rd-jobs to support delete function so we can easily delete a group of jobs without go to Web Console to click and delete them one by one. (**NOTE: added in 1.4.4**)

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/391)

Original Creator: chengkai liang

**Comment by ywshz** [comment]
+1 I am waiting for that function

**Comment by ahonor** [comment]
@ywshz look for it in 2.5.0

**Comment by gschueler** [comment]
issue #1327 adds a global "passive" mode you can set for a rundeck server

**Comment by gschueler** [comment]
added in 2.6
