### ISSUE TITLE
The default resources.xml is not created

### ISSUE THREAD

**Issue by cui-liqiang** [rundeck/rundeck#959]
When I create a new project, the following part says the "resources.xml" will be created is it is not exist. But it actually doesn't. Interestingly, if I make some change in the project setting after created, the "resources.xml" got created. Am I using it in a wrong way?
![screen shot 2014-10-04 at 1 59 27 pm](https://cloud.githubusercontent.com/assets/792595/4514765/4b440612-4b8b-11e4-9d72-3b3a3d320a9a.png)
I am using mac osx 10.9.

**Comment by clonedagain** [comment]
@gschueler I think you can close this issue, I had the same and your answer is correct.
