### ISSUE TITLE
HMAC request tokens expiring prematurely: "request did not include a valid token"

### ISSUE THREAD

**Issue by operations-ivy** [rundeck/rundeck#960]
I have to log out/log in for essentially ANY change made to the jobs I'm running currently. I receive the error "The request did not include a valid token, or the token has expired. Please try your request again." 9/10 times when I hit save after editing a jobs details. I'm not waiting an extraordinarily long amount of time before submitting the changes to the job, in some cases I'm hitting save seconds after logging in, and still get the error.

**Comment by AndyBerman** [comment]
I can't reproduce this anymore.  I'm using Chrome now which appears better than IE.

**Comment by memelet** [comment]
What was the fix that closed this issue? I can't edit command more then a few times before being forced to refresh and reenter everything.

**Comment by kshkuratoff** [comment]
The proper fix was done by Greg about a year ago to do with the token generation. 
https://github.com/rundeck/rundeck/commit/4a27a33e226f6a3c22e207715d6a97407c673348

The temporary fix that we applied (which might work for you as well) was to change the token setting in Config.groovy to false
rundeck.security.useHMacRequestTokens=false

**Comment by memelet** [comment]
I've set rundeck.security.useHMacRequestTokens=false, but still get timed within a few minutes. But only on the commands tabs it seems. (Or at least mostly)

**Comment by shlomoa** [comment]
Still happening, with login module: activedirectory

**Comment by pixdrift** [comment]
Also still seeing this with Rundeck 2.10.0-1 using preauthenticated

**Comment by brutus333** [comment]
I am seeing the same with Rundeck 2.10.0-1 and local authentication

**Comment by smysnk** [comment]
Also seeing this in Rundeck 3.0.5 and pre-auth
