### ISSUE TITLE
Can't save script step with a long script

### ISSUE THREAD

**Issue by jdmulloy** [rundeck/rundeck#963]
This is a very odd bug. It only affected one job and clearing out my cookies fixed it. It does not occur on 2.1.1 but it does occur on 2.2.2 and 2.2.3. When clicking on the save button nothing would happen. Looking at the dev tools in Chrome I found that the jquery call was getting errors back from the server. On the first call it would get 413 Full Headers and on subsequent calls it would get 400 Bad Request. I had too many cookies from other sites on my company's network that are at the domain.com level. All Rundeck needs is JSESSIONID. It's a difficult bug to debug and reproduce, if I can figure out how I'll let you know.

**Comment by Ziemowit-LH** [comment]
I confirm this is still happening on Rundeck 3.3.0-20200701.
I create new job, paste the content from attachment and it fails to save.

Dev console shows: 
_jquery-aafa4de7f25b530ee04ba20028b2d154.js:8707 
POST http://146.216.236.138:8075/workflow/save?project=TestsZK net::ERR_CONNECTION_RESET_

The behaviour is not consistent. I was editing a script yesterday and it was saving just fine, then today RD could not save my script even after i removed 10 lines from it.
[rd temp script fails to save.txt](https://github.com/rundeck/rundeck/files/4924652/rd.temp.script.fails.to.save.txt)
