### ISSUE TITLE
Static tokens configuration file not being honored

### ISSUE THREAD

**Issue by travisgroth** [rundeck/rundeck#971]
After doing the best I can to follow the documentation [here](http://rundeck.org/2.2.3/administration/configuration-file-reference.html#framework.properties) and [here](http://rundeck.org/2.2.3/api/index.html#token-authentication), I'm not having any luck using a static tokens file.  Setup:

```
[root@rundeck01 rundeck]# pwd
/etc/rundeck
[root@rundeck01 rundeck]# grep tokens framework.properties 
rundeck.tokens.file=/etc/rundeck/tokens.properties
[root@rundeck01 rundeck]# cat /etc/rundeck/tokens.properties
admin: S3hzAiHyCtBX33aVjgNNcF2Hwgg6OEc3
[root@rundeck01 rundeck]# curl -k https://localhost/api/1/projects?authtoken=S3hzAiHyCtBX33aVjgNNcF2Hwgg6OEc3
<result error='true' apiversion='12'><error code='unauthorized'><message>(Token:S3hzA****) is not authorized for: /api/1/projects</message></error></result>
```

Is there something glaring that I'm missing?  The setup seems pretty straightforward.  Thanks!

**Comment by shlomoa** [comment]
It happened to me and restart did not help

**Comment by andel7** [comment]
Was that fixed ? I'm having similar issue.

**Comment by shlomoa** [comment]
Yes, After 3 service restarts

**Comment by splio-ngirardi** [comment]
Hello,

Same issue here, even after 3 restart. Any solution ?

**Comment by EdoardoVarani** [comment]
Same issue here
I'm trying to POST the executeJob API with X-Rundeck-Auth-Token=myDefinedToken
Still HTTO 403 forbidden
