### ISSUE TITLE
Audit trail for jobs in UI

### ISSUE THREAD

**Issue by gschueler** [rundeck/rundeck#98]
Can we have an audit trail for rundeck jobs?

Something along the lines of http://wiki.hudson-ci.org/display/HUDSON/Audit+Trail+Plugin?

[original LH ticket](http://rundeck.lighthouseapp.com/projects/59277/tickets/409)

Original Creator: Sathish

**Comment by gschueler** [comment]
This enhancement is not on our short term roadmap.  We may re-open this issue in the future.  In the meantime, any community contribution for this feature is welcome.

**Comment by gwaldo** [comment]
Oh, good.  I can stop holding my breath...
