### ISSUE TITLE
Cascaded Options Don't Display Value on "Run Again" in v2.2.3, was fine in 2.2.1

### ISSUE THREAD

**Issue by richiereynolds** [rundeck/rundeck#990]
Hi, I recently upgraded from v2.2.1 with the built in DB to v2.2.3 with mysql.

I have a job with cascading options, you select "component" and that populates a "version" dropdown with the available versions.
In RD version 2.2.1 when you select an execution to "run again" the UI poulates all fields, including version, with the correct values.
In RD version 2.2.3 when you select an execution to "run again" the version field is blank, in fact the box is not even displayed, so the user cannot see what options he is running the job with. Only if the user reselects the component, which is already filled in of course, then the version appears.

I really like rundeck and am currently trying to convince teams in my company to move to using it but very visible bugs like this really aren't helping my case! The QA team, who will be using this functionality have already asked me how something as easily visible as this got through testing so now they're naturally starting to question the reliability of the product in other areas. It doesn't help bild confidence! Unfortunately this isn't the only issue that appears to have been introduced or gotten worse in 2.2.3. Hope you can fix it quick!

Primarily using chrome & firefox, RHEL 6.5 linux as the server, RPM install.

Thanks, Richard.

**Comment by katanafleet** [comment]
Hello,

Do you know when this bug ill be fix ? (same problem in version 2.4.0)

Thanks !
