### ISSUE TITLE
bad interpreter error

### ISSUE THREAD

**Issue by ko-christ** [rundeck/rundeck#993]
had a working job with just an inline script step

updated (with yum) rundeck today from rundeck-2.2.3 to 2.3.0 and I'm getting the following error.
/bin/sh: /tmp/1414588995708-localhost-dispatch-script.tmp.sh: /bin/bash^M: bad interpreter: No such file or directory
Result: 126
Failed: NonZeroResultCode: Result code was 126
Execution failed: 2954: [Workflow step failures: {1=Dispatch failed on 1 nodes: [localhost: NonZeroResultCode: Result code was 126]}, Node failures: {localhost=[NonZeroResultCode: Result code was 126]}]

downgraded rundeck with yum to 2.2.3 and the job executes successfully.

Is there a way/option to convert with dos2unix before they are executed?

**Comment by Bjoern2** [comment]
Hi. I've got this error again in version 2.5.3. Is this a problem again?

**Comment by rajaneeshk1990** [comment]
hi got this error to me 
Result: 126
Failed: NonZeroResultCode: Result code was 126
 Execution failed: 35 in project rajaneeshk: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [localhost: NonZeroResultCode: Result code was 126 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:localhost)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:localhost)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, Node failures: {localhost=[NonZeroResultCode: Result code was 126 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:localhost)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:localhost)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, status: failed]

**Comment by rajaneeshk1990** [comment]
@ahonor  first of all, I am new to rundeck.......I didn't get any interpreter error I am trying to run a small inline script as below 
deploy="@option.deploy@"
if [ -z "$deploy"]
then
echo "package has pushed wait to reflect "
sleep 10
/root/install.sh
else
echo "failed you have not opted to deploy "
fi


when executing the above script I came across this error 
Result: 126
Failed: NonZeroResultCode: Result code was 126
Execution failed: 35 in project rajaneeshk: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [localhost: NonZeroResultCode: Result code was 126 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:localhost)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:localhost)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, Node failures: {localhost=[NonZeroResultCode: Result code was 126 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:localhost)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:localhost)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, status: failed]


please help me to get rid of this issue.

**Comment by ahonor** [comment]
@rajaneeshk1990 Exit code 126 might indicate the /root/install.sh is not executable: See https://www.gnu.org/software/bash/manual/html_node/Exit-Status.html

**Comment by rajaneeshk1990** [comment]
this is the total log output I am facing 



00:14:18 | localhost | 1. Script | package has pushed wait to reflect
-- | -- | -- | --
00:14:28 |   |   | /tmp/0-37-localhost-dispatch-script.tmp.sh: line 6: /root/install.sh: Permission denied
00:14:29 |   |   | Result: 126
00:14:29 |   |   | Failed: NonZeroResultCode: Result code was 126
00:14:29 |   |   | Execution failed: 37 in project rajaneeshk: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [localhost: NonZeroResultCode: Result code was 126 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:localhost)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:localhost)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, Node failures: {localhost=[NonZeroResultCode: Result code was 126 + {dataContext=MultiDataContextImpl(map={ContextView(step:1, node:localhost)=BaseDataContext{{exec={exitCode=0}}}, ContextView(node:localhost)=BaseDataContext{{exec={exitCode=0}}}}, base=null)} ]}, status: failed]

**Comment by rajaneeshk1990** [comment]
error in jenkins as below:-


Started by user rajaneeshk
Building in workspace /var/lib/jenkins/workspace/rundeckjob
Instance 'rundeck' with rundeck user 'admin': Notifying Rundeck...
Looking for jobId : xxxxxxxxx-xxxxxxx-xxxxx-xxxxxx
Notification succeeded ! Execution #31, at http://192.168.33.13:4440/api/23/execution/31 (status : RUNNING)
Waiting for Rundeck execution to finish...
Rundeck execution #31 finished in 0 seconds, with status : FAILED
ERROR: Step ‘Rundeck’ failed: null
Finished: SUCCESS

**Comment by ahonor** [comment]
@rajaneeshk1990 did you see my earlier message about the exit code 126? Try changing your script to either making the /root/install.sh executable or call it with the needed interpreter.
```
deploy="@option.deploy@"
if [ -z "$deploy"]
then
echo "package has pushed wait to reflect "
sleep 10
chmod +x /root/install.sh; # Make sure it is executable
/root/install.sh
else
echo "failed you have not opted to deploy "
fi
```

**Comment by saba2112** [comment]
Hii all
I am getting an error in rundeck. Plx help me to solve this issue.
Result: 1
14:05:18			Failed: NonZeroResultCode: Result code was 1
14:05:18			Execution failed: 32708 in project uk-Utility-backup: [Workflow result: , step failures: {1=Dispatch failed on 1 nodes: [localhost: NonZeroResultCode: Result code was 1]}, Node failures: {localhost=[NonZeroResultCode: Result code was 1]}, status: failed]

**Comment by niall-munnelly** [comment]
That output doesn’t say much, but “bad interpreter” probably does. Is it an in-line script workflow step? Is the “shebang” pointing to a valid executable? Or perhaps you’ve defined the default interpreter in Rundeck; is that path also valid? Linux? Windows?

Without more information, there’s not much one can say.
