### ISSUE TITLE
2.3.0 KeyStorage - private key 'upload file' fails

### ISSUE THREAD

**Issue by anandchida** [rundeck/rundeck#995]
I've been playing with the new key storage feature in 2.3.0 and here's what worked and what did not. 

What worked:
1. Goto KeyStorage -> Add or Upload a key -> Enter text
2. Cut and paste the SSH private key (id_rsa)
3. Click Save

What did not work:

The same steps above when selected via "Upload File", the following error is displayed
- HTTP ERROR 405

Problem accessing /grails/storage/keyStorageUpload.dispatch. Reason:

```
Method Not Allowed
```

Powered by Jetty://

**Comment by ahonor** [comment]
@anandchida Can you try this with 2.4.0?

**Comment by anandchida** [comment]
@ahonor  sure eill do and keep you posted. Thank you for looking into this.

**Comment by anandchida** [comment]
@ahonor this fails on 2.4.0 as well with the same message. 

HTTP ERROR 405

Problem accessing /grails/storage/keyStorageUpload.dispatch. Reason:

    Method Not Allowed

**Comment by gschueler** [comment]
what browser, version, and OS are you using? thanks
